### ISSUE TITLE
Document scan crashes on 3.20.0 RC1

### ISSUE THREAD

**Issue by AlvaroBrey** [nextcloud/android#10028]
From #4435 by @EVOTk

<details>
<summary> Screenshot </summary>

![Screenshot_20220329_165153_com nextcloud client](https://user-images.githubusercontent.com/45015615/160640454-90a34f68-ae43-4a49-a7d2-6ed702e26a35.jpg)

</details>

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Bitmap.createBitmap(this…th, this.height, m, true) must not be null
    at com.zynksoftware.documentscanner.common.extensions.BitmapExtensionsKt.scaledBitmap(BitmapExtensions.kt:50)
    at com.zynksoftware.documentscanner.ui.imagecrop.ImageCropFragment.initializeCropping(ImageCropFragment.kt:98)
    at com.zynksoftware.documentscanner.ui.imagecrop.ImageCropFragment.access$initializeCropping(ImageCropFragment.kt:45)
    at com.zynksoftware.documentscanner.ui.imagecrop.ImageCropFragment$onViewCreated$2.run(ImageCropFragment.kt:77)
    at android.os.Handler.handleCallback(Handler.java:900)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at android.os.Looper.loop(Looper.java:219)
    at android.app.ActivityThread.main(ActivityThread.java:8393)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200051`
* Build flavor: `generic`

### Device information
* Brand: `HONOR`
* Device: `HWYAL`
* Model: `YAL-L21`
* Id: `HUAWEIYAL-L21`
* Product: `YAL-L21EEA`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `10.1.0.241C431`

**Comment by AlvaroBrey** [comment]
Can't reproduce in either of the 2 devices I've tried. It's strange, `Bitmap.createBitmap` is not supposed to return `null`.

**Comment by EVOTk** [comment]
@AlvaroBrey Thank you for opening this report for me!
It used to happen to me all the time, I restarted my phone and it solved!

On the other hand, the loading before the upload is quite long (between 15 and 20 seconds), is it the same for you?

**Comment by AlvaroBrey** [comment]
> @AlvaroBrey Thank you for opening this report for me! It used to happen to me all the time, I restarted my phone and it solved!
> 
> On the other hand, the loading before the upload is quite long (between 15 and 20 seconds), is it the same for you?

Yes, image processing takes a while
