### ISSUE TITLE
App crashes constantly when Nextcloud has an internal server error

### ISSUE THREAD

**Issue by sirdrakeistda** [nextcloud/android#10039]
### Steps to reproduce
1. create an internal server error in nextcloud (e.g. change the php version to an unsupported version)
2. -> the nextcloud app crashes every few seconds. It is nearly impossible to use other apps on android, because the crash reports interrupts you every few seconds. This crash happens also when nextcloud is in background

### Expected behaviour
- The Nextcloud app should catch the error and give an error message instead of crashing.

### Actual behaviour
- Nextcloud app crashes every 5 seconds again.

### Can you reproduce this problem on https://try.nextcloud.com?
- Obviously no. You need an bad configured server for this crash. I think it is important to fix this crash because it makes android unusable until nextcloud is deleted, because every 5 second you get another crash report

### Environment data
Android version:
9
Device model: 
HTC U11
Xiami mi 8

Stock or customized system:
stock
Nextcloud app version:
3.19.1
Nextcloud server version:
23

**Comment by AlvaroBrey** [comment]
I haven't been able to reproduce this, neither with the wrong PHP version nor manually introducing exceptions in `index.php` and `remote.php`, so I guess this only happens when the app is trying to do something specific. 

@sirdrakeistda if you have access to server (apache, or whatever proxy you have) logs, can you attach them so that I can see what URLs the app is trying to access when crashing?

**Comment by ezaquarii** [comment]
@sirdrakeistda Do you have a stack trace from this incident? It should show up after crash.

**Comment by darts** [comment]
I came across this error after my server went down. Since I'm proxying through cloudflare the response to requests to the URL is 523.

This is the log produced by the app:

```
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: network interceptor com.nextcloud.common.IPv4FallbackInterceptor@fcef427 must call proceed() exactly once
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:99)
	at com.nextcloud.common.IPv4FallbackInterceptor.retryWithIPv4(IPv4FallbackInterceptor.kt:74)
	at com.nextcloud.common.IPv4FallbackInterceptor.intercept(IPv4FallbackInterceptor.kt:54)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at com.nextcloud.common.OkHttpMethodBase.execute(OkHttpMethodBase.kt:171)
	at com.nextcloud.client.network.ConnectivityServiceImpl.isInternetWalled(ConnectivityServiceImpl.java:81)
	at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:239)
	at com.owncloud.android.utils.FilesSyncHelper$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.lang.Thread.run(Thread.java:920)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30190190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: asus
Device: ASUS_I002D
Model: ASUS_I002D
Id: SKQ1.210821.001
Product: EU_I002D

************ FIRMWARE ************
SDK: 31
Release: 12
Incremental: 31.0210.0210.221

```

**Comment by AlvaroBrey** [comment]
Relevant codepath: https://github.com/nextcloud/android-library/blob/master/library/src/main/java/com/nextcloud/common/IPv4FallbackInterceptor.kt#L54

We're planning to use OkHttp 5.0`s built-in Fast Eyeballs, instead of this custom fallback interceptor, so this would go away when we do that. We're waiting on OkHttp 5.0 stable release for that.
