### ISSUE TITLE
crash when trying to open reference from qrcode scanner

### ISSUE THREAD

**Issue by kavol** [nextcloud/android#10033]
### Steps to reproduce
1. generate app token on the web, let it show qr code
2. scan the code
3. let the scanner to open the result in nextcloud app

### Expected behaviour
you get connected to your nextcloud account

### Actual behaviour
************ CAUSE OF ERROR ************

java.lang.RuntimeException
	at com.owncloud.android.ui.activities.ActivitiesActivity$$ExternalSyntheticLambda0.get(Unknown Source:2)
	at com.nextcloud.java.util.Optional.orElseThrow(Optional.java:309)
	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onSaveInstanceState(ReceiveExternalFilesActivity.java:267)
	at android.app.Activity.performSaveInstanceState(Activity.java:2037)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1485)
	at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:5332)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4658)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4622)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4697)
	at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:41)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2041)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7386)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30190190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: UMIDIGI
Device: BISON
Model: BISON
Id: QP1A.190711.020
Product: BISON_EEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2010221715

### Can you reproduce this problem on https://try.nextcloud.com?
yes

### Environment data
Android version:
10

Device model: 
BISON

Stock or customized system:
stock

Nextcloud app version:
3.19.1

Nextcloud server version:
23.0.3 (mine)/21.0.4 (demo1.nextcloud.com)

Reverse proxy:
no

**Comment by AlvaroBrey** [comment]
@kavol can you try 3.20.0 RC1? this crash was solved in that version, if I recall correctly

**Comment by kavol** [comment]
ok, with 3.20.0 RC1, it no longer throws the exception

however, it doesn't get me any further, as it says _Na tomto přístroji nejsou žádné Nextcloud účty. Nejdříve zadejte účet._ (roughly "There are no Nextcloud accounts on this device. Specify an account at first.") and puts me onto the setup screen asking to login/register

**Comment by joshtrichards** [comment]
Hi @kavol - Is this still occurring for you?

**Comment by joshtrichards** [comment]
Sounds like you're scanning from outside of the NC client then letting your phone's scanner follow the URL?

What happens if you scan from the first run wizard in the app instead?
