### ISSUE TITLE
Unable to access multiple Folders in Nextcloud Android App

### ISSUE THREAD

**Issue by blackdyn35** [nextcloud/android#10108]
### Steps to reproduce
A:
1. Open directory of desired Folder inside the android app or choose from Favorites
2. Use three button context menu and hit synchronize
3. Error message
OR B:
1. Open directory of desired Folder inside the android app or choose from Favorites
2.  Tap on the folder to open

I can't tell which folders i can access and which i can't. However it seems to be the same folders to be affected. The Error doesnt happen all the time.. Sometimes it works just fine, most of the time it doesn't.

### Expected behaviour
- App is supposed to synchronize or Open the Folder

### Actual behaviour
B:
1.Sometimes shows the actual contents of the folder briefly or skips instantly to step 2
2. Get a Notification "The Folder does not exist anymore"

A:
- An Error Message pops up:
- ************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'long com.owncloud.android.datamodel.OCFile.getFileId()' on a null object reference
	at com.owncloud.android.operations.SynchronizeFolderOperation.removeLocalFolder(SynchronizeFolderOperation.java:236)
	at com.owncloud.android.operations.SynchronizeFolderOperation.checkForChanges(SynchronizeFolderOperation.java:193)
	at com.owncloud.android.operations.SynchronizeFolderOperation.run(SynchronizeFolderOperation.java:141)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:187)
	at com.owncloud.android.services.SyncFolderHandler.doOperation(SyncFolderHandler.java:115)
	at com.owncloud.android.services.SyncFolderHandler.handleMessage(SyncFolderHandler.java:88)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30190190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: gts7lwifi
Model: SM-T870
Id: SP1A.210812.016
Product: gts7lwifieea

************ FIRMWARE ************
SDK: 31
Release: 12
Incremental: T870XXU2CVCD

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:
t870XXU2CVCD / T8700XM2CVCD
Device model: 
Samsung Tab S7
Stock or customized system:

Nextcloud app version:
refer to log above please
Nextcloud server version:
refer to log above please
Reverse proxy:
no
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by joshtrichards** [comment]
We haven't had any other reports of this so far. Are you still experiencing this behavior?

**Comment by joshtrichards** [comment]
Alright. I'll close this out. If you or someone else encounters it at some point in the future, it'll be here in the archives and we can revisit.
