### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by SamGreenwood1** [nextcloud/android#10141]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to resume activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.SecurityException: uid 10716 cannot get user data for accounts of type: nextcloud
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5230)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5269)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.SecurityException: uid 10716 cannot get user data for accounts of type: nextcloud
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
	at android.os.Parcel.createException(Parcel.java:2421)
	at android.os.Parcel.readException(Parcel.java:2404)
	at android.os.Parcel.readException(Parcel.java:2346)
	at android.accounts.IAccountManager$Stub$Proxy.getUserData(IAccountManager.java:1336)
	at android.accounts.AccountManager$2.recompute(AccountManager.java:458)
	at android.accounts.AccountManager$2.recompute(AccountManager.java:449)
	at android.app.PropertyInvalidatedCache.query(PropertyInvalidatedCache.java:562)
	at android.accounts.AccountManager.getUserData(AccountManager.java:641)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.<init>(OCFileListAdapter.java:162)
	at com.owncloud.android.ui.fragment.OCFileListFragment.onActivityCreated(OCFileListFragment.java:357)
	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3028)
	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:578)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:264)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
	at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:462)
	at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:412)
	at com.owncloud.android.ui.activity.BaseActivity.onResume(BaseActivity.java:91)
	at com.owncloud.android.ui.activity.DrawerActivity.onResume(DrawerActivity.java:989)
	at com.owncloud.android.ui.activity.FileActivity.onResume(FileActivity.java:241)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onResume(FileDisplayActivity.java:1157)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1476)
	at android.app.Activity.performResume(Activity.java:8441)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5200)
	... 13 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.accounts.AccountManagerService.getUserData(AccountManagerService.java:1686)
	at android.accounts.IAccountManager$Stub.onTransact(IAccountManager.java:455)
	at com.android.server.accounts.AccountManagerService.onTransact(AccountManagerService.java:1119)
	at android.os.Binder.execTransactInternal(Binder.java:1215)
	at android.os.Binder.execTransact(Binder.java:1179)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30190190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: bloomxq
Model: SM-F707W
Id: SP1A.210812.016
Product: bloomxqcsx

************ FIRMWARE ************
SDK: 31
Release: 12
Incremental: F707WVLU2FVC4

**Comment by AlvaroBrey** [comment]
Closed in favor of #10159
