### ISSUE TITLE
ArrayIndexOutOfBoundsException in GalleryAdapter

### ISSUE THREAD

**Issue by dimitar8080** [nextcloud/android#10177]
### Cause of error
```java
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
    at java.util.ArrayList.get(ArrayList.java:439)
    at com.owncloud.android.ui.adapter.GalleryAdapter.getItem(GalleryAdapter.kt:177)
    at com.owncloud.android.ui.fragment.GalleryFragment.loadMoreWhenEndReached(GalleryFragment.java:249)
    at com.owncloud.android.ui.fragment.GalleryFragment.access$000(GalleryFragment.java:47)
    at com.owncloud.android.ui.fragment.GalleryFragment$1.onScrolled(GalleryFragment.java:82)
    at androidx.recyclerview.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:5347)
    at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5512)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
    at android.view.Choreographer.doCallbacks(Choreographer.java:866)
    at android.view.Choreographer.doFrame(Choreographer.java:792)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8663)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200090`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `a52sxq`
* Model: `SM-A528B`
* Id: `SP1A.210812.016`
* Product: `a52sxqeea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `A528BXXS1CVD1`

**Comment by joshtrichards** [comment]
Hi @dimitar8080 - Possibly (probably?) fixed in #10253. Are you still experiencing this and/or is this something you have the ability to reproduce on-demand?
