### ISSUE TITLE
Crashes when Open media

### ISSUE THREAD

**Issue by sakarya1980** [nextcloud/android#10198]
### Cause of error
```java
Exception in thread "AsyncTask #2" java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$4.done(AsyncTask.java:415)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
    at java.util.concurrent.FutureTask.run(FutureTask.java:271)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)
Caused by: Exception in thread "AsyncTask #2" java.lang.RuntimeException: Accessing result data after operation failed!
    at com.owncloud.android.lib.common.operations.RemoteOperationResult.getData(RemoteOperationResult.java:512)
    at com.owncloud.android.ui.asynctasks.GallerySearchTask.doInBackground(GallerySearchTask.java:100)
    at com.owncloud.android.ui.asynctasks.GallerySearchTask.doInBackground(GallerySearchTask.java:46)
    at android.os.AsyncTask$3.call(AsyncTask.java:394)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200090`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `oriole`
* Model: `Pixel 6`
* Id: `SP2A.220505.002`
* Product: `oriole`

### Firmware
* SDK: `32`
* Release: `12`
* Incremental: `8353555`

**Comment by svenb1234** [comment]
3.20.1 still causes the crash when opening the media view

### Cause of error
```java
Exception in thread "AsyncTask #4" java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$4.done(AsyncTask.java:415)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
    at java.util.concurrent.FutureTask.run(FutureTask.java:271)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)
Caused by: Exception in thread "AsyncTask #4" java.lang.RuntimeException: Accessing result data after operation failed!
    at com.owncloud.android.lib.common.operations.RemoteOperationResult.getData(RemoteOperationResult.java:512)
    at com.owncloud.android.ui.asynctasks.GallerySearchTask.doInBackground(GallerySearchTask.java:102)
    at com.owncloud.android.ui.asynctasks.GallerySearchTask.doInBackground(GallerySearchTask.java:48)
    at android.os.AsyncTask$3.call(AsyncTask.java:394)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `sunfish`
* Model: `Pixel 4a`
* Id: `SP2A.220405.003`
* Product: `sunfish`

### Firmware
* SDK: `32`
* Release: `12`
* Incremental: `8210211`

**Comment by AlvaroBrey** [comment]
cc @tobiasKaminsky

**Comment by svenb1234** [comment]
Had the impression that it got better with 3.20.2 but then this crash happened again.

### Cause of error
```java
Exception in thread "AsyncTask #2" java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$4.done(AsyncTask.java:415)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
    at java.util.concurrent.FutureTask.run(FutureTask.java:271)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)
Caused by: Exception in thread "AsyncTask #2" java.lang.RuntimeException: Accessing result data after operation failed!
    at com.owncloud.android.lib.common.operations.RemoteOperationResult.getData(RemoteOperationResult.java:512)
    at com.owncloud.android.ui.asynctasks.GallerySearchTask.doInBackground(GallerySearchTask.java:102)
    at com.owncloud.android.ui.asynctasks.GallerySearchTask.doInBackground(GallerySearchTask.java:48)
    at android.os.AsyncTask$3.call(AsyncTask.java:394)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200290`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `oriole`
* Model: `Pixel 6`
* Id: `SP2A.220505.002`
* Product: `oriole`

### Firmware
* SDK: `32`
* Release: `12`
* Incremental: `8353555`

**Comment by AlvaroBrey** [comment]
This was fixed in https://github.com/nextcloud/android/commit/62d58d0a366608c205c7389e3263ecbb30878ffb but inadvertently not backported to 3.20. It will be available in 3.21, sorry for the delay.

**Comment by svenb1234** [comment]
Why not inadvertently Release a 3.20.3 with this backport?

**Comment by AlvaroBrey** [comment]
> Why not inadvertently Release a 3.20.3 with this backport?

Yeah, will release today if all goes well, with this fix and some other minor ones.
