### ISSUE TITLE
java Exception in thread "main" 

### ISSUE THREAD

**Issue by viba1** [nextcloud/android#10199]
### Cause of error
```java
Exception in thread "main" android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=1, totalRows=2
    at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
    at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1011)
    at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
    at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
    at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:161)
    at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:131)
    at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:248)
    at android.database.AbstractCursor.moveToNext(AbstractCursor.java:280)
    at android.database.CursorWrapper.moveToNext(CursorWrapper.java:232)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:888)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:187)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:610)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1280)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1228)
    at com.owncloud.android.ui.fragment.OCFileListFragment.onItemClicked(OCFileListFragment.java:987)
    at com.owncloud.android.ui.adapter.OCFileListDelegate.bindGridItemLayout$lambda-1(OCFileListDelegate.kt:164)
    at com.owncloud.android.ui.adapter.OCFileListDelegate.$r8$lambda$Q9OhKWaUB6Dopk7l8lNni9-d6bY(Unknown Source:0)
    at com.owncloud.android.ui.adapter.OCFileListDelegate$$ExternalSyntheticLambda1.onClick(Unknown Source:4)
    at android.view.View.performClick(View.java:7575)
    at android.view.View.performClickInternal(View.java:7531)
    at android.view.View.access$3900(View.java:842)
    at android.view.View$PerformClick.run(View.java:28872)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:265)
    at android.app.ActivityThread.main(ActivityThread.java:8360)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200090`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OP515BL1`
* Model: `DN2103`
* Id: `RP1A.200720.011`
* Product: `DN2103EEA`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `1649864983659`

**Comment by AlvaroBrey** [comment]
Note for devs: why are we doing this in the main thread? this is database access
