### ISSUE TITLE
Crash when opening app

### ISSUE THREAD

**Issue by treysis** [nextcloud/android#10197]
### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter <set-?>
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3114)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7050)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
Caused by: Exception in thread "main" java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter <set-?>
    at com.owncloud.android.lib.resources.status.OCCapability.setRichDocumentsProductName(Unknown Source:2)
    at com.owncloud.android.datamodel.FileDataStorageManager.createCapabilityInstance(FileDataStorageManager.java:2121)
    at com.owncloud.android.datamodel.FileDataStorageManager.getCapability(FileDataStorageManager.java:2029)
    at com.owncloud.android.utils.theme.CapabilityUtils.getCapability(CapabilityUtils.java:83)
    at com.owncloud.android.utils.theme.CapabilityUtils.getCapability(CapabilityUtils.java:51)
    at com.owncloud.android.utils.theme.ThemeUtils.getDefaultDisplayNameForRootFolder(ThemeUtils.java:46)
    at com.owncloud.android.ui.activity.ToolbarActivity.updateActionBarTitleAndHomeButton(ToolbarActivity.java:132)
    at com.owncloud.android.ui.activity.DrawerActivity.updateActionBarTitleAndHomeButton(DrawerActivity.java:647)
    at com.owncloud.android.ui.activity.FileDisplayActivity.updateActionBarTitleAndHomeButton(FileDisplayActivity.java:1576)
    at com.owncloud.android.ui.activity.ToolbarActivity.setupToolbar(ToolbarActivity.java:98)
    at com.owncloud.android.ui.activity.ToolbarActivity.setupHomeSearchToolbarWithSortAndListButtons(ToolbarActivity.java:122)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onCreate(FileDisplayActivity.java:264)
    at android.app.Activity.performCreate(Activity.java:7327)
    at android.app.Activity.performCreate(Activity.java:7318)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7050)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `gracerlte`
* Model: `SM-N935F`
* Id: `PPR1.180610.011`
* Product: `gracerltexx`

### Firmware
* SDK: `28`
* Release: `9`
* Incremental: `N935FXXS8CUD1`

**Comment by AlvaroBrey** [comment]
Thanks @treysis !

**Comment by treysis** [comment]
After resetting the app (deleting app data) it is opening again. Of course all accounts are lost now.
