### ISSUE TITLE
ava Exception in thread "main" java.lang.RuntimeException: Unable to start activity 

### ISSUE THREAD

**Issue by pstorch** [nextcloud/android#10206]
### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter <set-?>
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4035)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8663)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: Exception in thread "main" java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter <set-?>
    at com.owncloud.android.lib.resources.status.OCCapability.setServerLogo(Unknown Source:2)
    at com.owncloud.android.datamodel.FileDataStorageManager.createCapabilityInstance(FileDataStorageManager.java:2097)
    at com.owncloud.android.datamodel.FileDataStorageManager.getCapability(FileDataStorageManager.java:2029)
    at com.owncloud.android.utils.theme.CapabilityUtils.getCapability(CapabilityUtils.java:83)
    at com.owncloud.android.utils.theme.CapabilityUtils.getCapability(CapabilityUtils.java:51)
    at com.owncloud.android.utils.theme.ThemeUtils.getDefaultDisplayNameForRootFolder(ThemeUtils.java:46)
    at com.owncloud.android.ui.activity.ToolbarActivity.updateActionBarTitleAndHomeButton(ToolbarActivity.java:132)
    at com.owncloud.android.ui.activity.DrawerActivity.updateActionBarTitleAndHomeButton(DrawerActivity.java:647)
    at com.owncloud.android.ui.activity.FileDisplayActivity.updateActionBarTitleAndHomeButton(FileDisplayActivity.java:1573)
    at com.owncloud.android.ui.activity.ToolbarActivity.setupToolbar(ToolbarActivity.java:98)
    at com.owncloud.android.ui.activity.ToolbarActivity.setupHomeSearchToolbarWithSortAndListButtons(ToolbarActivity.java:122)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onCreate(FileDisplayActivity.java:264)
    at android.app.Activity.performCreate(Activity.java:8290)
    at android.app.Activity.performCreate(Activity.java:8270)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8663)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200090`
* Build flavor: `generic`

### Device information
* Brand: `samsung`
* Device: `beyond2`
* Model: `SM-G975F`
* Id: `SP1A.210812.016`
* Product: `beyond2lteeea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `G975FXXUEHVC6`

**Comment by pstorch** [comment]
Sorry, it looks like a duplicate of https://github.com/nextcloud/android/issues/10197
