### ISSUE TITLE
On device menu crashed

### ISSUE THREAD

**Issue by Plinsboorg** [nextcloud/android#10204]
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'void com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(com.nextcloud.client.account.User, com.owncloud.android.datamodel.OCFile, com.owncloud.android.datamodel.FileDataStorageManager, boolean, java.lang.String)' on a null object reference
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1285)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1233)
    at com.owncloud.android.ui.fragment.OCFileListFragment.refreshDirectory(OCFileListFragment.java:1229)
    at com.owncloud.android.ui.activity.FileDisplayActivity.showFiles(FileDisplayActivity.java:2288)
    at com.owncloud.android.ui.activity.DrawerActivity.onNavigationItemClicked(DrawerActivity.java:454)
    at com.owncloud.android.ui.activity.DrawerActivity.lambda$setupDrawerMenu$0$com-owncloud-android-ui-activity-DrawerActivity(DrawerActivity.java:398)
    at com.owncloud.android.ui.activity.DrawerActivity$$ExternalSyntheticLambda5.run(Unknown Source:4)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:210)
    at android.os.Looper.loop(Looper.java:299)
    at android.app.ActivityThread.main(ActivityThread.java:8103)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`

### Device information
* Brand: `Xiaomi`
* Device: `lisa`
* Model: `2109119DG`
* Id: `SKQ1.211006.001`
* Product: `lisa_global`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `V13.0.4.0.SKOMIXM`

**Comment by AlvaroBrey** [comment]
Thanks @Plinsboorg !
