### ISSUE TITLE
App crashes with latest build (on F-droid)

### ISSUE THREAD

**Issue by msanguineti** [nextcloud/android#10205]
### Steps to reproduce
1. Tap on the Nextcloud icon to start the app

### Expected behaviour
- The app should start

### Actual behaviour
- The app crashes

### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter <set-?>
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
    at android.app.ActivityThread.-wrap11(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6494)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: Exception in thread "main" java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter <set-?>
    at com.owncloud.android.lib.resources.status.OCCapability.setServerLogo(Unknown Source:2)
    at com.owncloud.android.datamodel.FileDataStorageManager.createCapabilityInstance(FileDataStorageManager.java:2097)
    at com.owncloud.android.datamodel.FileDataStorageManager.getCapability(FileDataStorageManager.java:2029)
    at com.owncloud.android.utils.theme.CapabilityUtils.getCapability(CapabilityUtils.java:83)
    at com.owncloud.android.utils.theme.CapabilityUtils.getCapability(CapabilityUtils.java:51)
    at com.owncloud.android.utils.theme.ThemeUtils.getDefaultDisplayNameForRootFolder(ThemeUtils.java:46)
    at com.owncloud.android.ui.activity.ToolbarActivity.updateActionBarTitleAndHomeButton(ToolbarActivity.java:132)
    at com.owncloud.android.ui.activity.DrawerActivity.updateActionBarTitleAndHomeButton(DrawerActivity.java:647)
    at com.owncloud.android.ui.activity.FileDisplayActivity.updateActionBarTitleAndHomeButton(FileDisplayActivity.java:1573)
    at com.owncloud.android.ui.activity.ToolbarActivity.setupToolbar(ToolbarActivity.java:98)
    at com.owncloud.android.ui.activity.ToolbarActivity.setupHomeSearchToolbarWithSortAndListButtons(ToolbarActivity.java:122)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onCreate(FileDisplayActivity.java:264)
    at android.app.Activity.performCreate(Activity.java:7009)
    at android.app.Activity.performCreate(Activity.java:7000)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
    at android.app.ActivityThread.-wrap11(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6494)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200090`
* Build flavor: `generic`

### Device information
* Brand: `google`
* Device: `bullhead`
* Model: `Nexus 5X`
* Id: `OPM7.181205.001`
* Product: `bullhead`

### Firmware
* SDK: `27`
* Release: `8.1.0`
* Incremental: `277f095ef7`

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
Should be fixed by 3.20.1, which is already out
