### ISSUE TITLE
 error

### ISSUE THREAD

**Issue by Jack-kr** [nextcloud/android#10203]
### Cause of error
```java
Exception in thread "main" java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@479de6d rejected from java.util.concurrent.ThreadPoolExecutor@ef71aa2[Running, pool size = 17, active threads = 17, queued tasks = 128, completed tasks = 232]
    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2085)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
    at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:651)
    at com.owncloud.android.utils.DisplayUtils.setThumbnail(DisplayUtils.java:952)
    at com.owncloud.android.ui.adapter.OCFileListDelegate.bindGridViewHolder(OCFileListDelegate.kt:92)
    at com.owncloud.android.ui.adapter.GalleryAdapter.onBindViewHolder(GalleryAdapter.kt:106)
    at com.afollestad.sectionedrecyclerview.SectionedRecyclerViewAdapter.onBindViewHolder(SectionedRecyclerViewAdapter.java:305)
    at com.afollestad.sectionedrecyclerview.SectionedRecyclerViewAdapter.onBindViewHolder(SectionedRecyclerViewAdapter.java:15)
    at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
    at com.afollestad.sectionedrecyclerview.SectionedRecyclerViewAdapter.onBindViewHolder(SectionedRecyclerViewAdapter.java:325)
    at com.afollestad.sectionedrecyclerview.SectionedRecyclerViewAdapter.onBindViewHolder(SectionedRecyclerViewAdapter.java:15)
    at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
    at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
    at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
    at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
    at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
    at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6702)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`

### Device information
* Brand: `DOOGEE`
* Device: `S90C`
* Model: `S90C`
* Id: `PPR1.180610.011`
* Product: `S90C_EEA`

### Firmware
* SDK: `28`
* Release: `9`
* Incremental: `1620358566`

**Comment by ezaquarii** [comment]
Duplicate of https://github.com/nextcloud/android/issues/10338
