### ISSUE TITLE
app crashes after "click" on "shared" in nav menu

### ISSUE THREAD

**Issue by fastjack-it** [nextcloud/android#10227]
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'com.owncloud.android.utils.FileSortOrder$SortType com.owncloud.android.utils.FileSortOrder.getType()' on a null object reference
    at com.owncloud.android.ui.adapter.OCFileListAdapter.getPopupText(OCFileListAdapter.java:905)
    at me.zhanghai.android.fastscroll.RecyclerViewHelper.getPopupText(RecyclerViewHelper.java:136)
    at me.zhanghai.android.fastscroll.FastScroller.onPreDraw(FastScroller.java:198)
    at me.zhanghai.android.fastscroll.FastScroller.$r8$lambda$fhoCEu3yFeBM02d2QCiuR_Ev5oo(Unknown Source:0)
    at me.zhanghai.android.fastscroll.FastScroller$$ExternalSyntheticLambda1.run(Unknown Source:2)
    at me.zhanghai.android.fastscroll.RecyclerViewHelper$1.onDraw(RecyclerViewHelper.java:52)
    at androidx.recyclerview.widget.RecyclerView.onDraw(RecyclerView.java:4668)
    at android.view.View.draw(View.java:22704)
    at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4603)
    at android.view.View.updateDisplayListIfDirty(View.java:21579)
    at android.view.View.draw(View.java:22435)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
    at android.view.View.draw(View.java:22707)
    at android.view.View.updateDisplayListIfDirty(View.java:21579)
    at android.view.View.draw(View.java:22435)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
    at android.view.View.updateDisplayListIfDirty(View.java:21570)
    at android.view.View.draw(View.java:22435)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
    at android.view.View.updateDisplayListIfDirty(View.java:21570)
    at android.view.View.draw(View.java:22435)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
    at android.view.View.draw(View.java:22707)
    at android.view.View.updateDisplayListIfDirty(View.java:21579)
    at android.view.View.draw(View.java:22435)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
    at android.view.View.updateDisplayListIfDirty(View.java:21570)
    at android.view.View.draw(View.java:22435)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
    at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
    at android.view.View.draw(View.java:22707)
    at android.view.View.updateDisplayListIfDirty(View.java:21579)
    at android.view.View.draw(View.java:22435)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
    at android.view.View.updateDisplayListIfDirty(View.java:21570)
    at android.view.View.draw(View.java:22435)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
    at android.view.View.updateDisplayListIfDirty(View.java:21570)
    at android.view.View.draw(View.java:22435)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
    at android.view.View.updateDisplayListIfDirty(View.java:21570)
    at android.view.View.draw(View.java:22435)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
    at android.view.View.updateDisplayListIfDirty(View.java:21570)
    at android.view.View.draw(View.java:22435)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
    at android.view.View.draw(View.java:22707)
    at com.android.internal.policy.DecorView.draw(DecorView.java:819)
    at android.view.View.updateDisplayListIfDirty(View.java:21579)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:616)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:4525)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4245)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3374)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2179)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8787)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
    at android.view.Choreographer.doCallbacks(Choreographer.java:845)
    at android.view.Choreographer.doFrame(Choreographer.java:780)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `raven`
* Model: `Pixel 6 Pro`
* Id: `SP2A.220405.004`
* Product: `raven`

### Firmware
* SDK: `32`
* Release: `12`
* Incremental: `8233519`

**Comment by AlvaroBrey** [comment]
Thanks for the report @fastjack-it
