### ISSUE TITLE
nextcloud app crashing

### ISSUE THREAD

**Issue by Wiggum127** [nextcloud/android#10238]
### Cause of error
```java
Exception in thread "Thread-8" java.lang.IllegalStateException: network interceptor com.nextcloud.common.IPv4FallbackInterceptor@c9114d4 must call proceed() exactly once
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:99)
    at com.nextcloud.common.IPv4FallbackInterceptor.retryWithIPv4(IPv4FallbackInterceptor.kt:74)
    at com.nextcloud.common.IPv4FallbackInterceptor.intercept(IPv4FallbackInterceptor.kt:54)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
    at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
    at com.nextcloud.common.OkHttpMethodBase.execute(OkHttpMethodBase.kt:171)
    at com.nextcloud.client.network.ConnectivityServiceImpl.isInternetWalled(ConnectivityServiceImpl.java:81)
    at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:239)
    at com.owncloud.android.utils.FilesSyncHelper$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
    at java.lang.Thread.run(Thread.java:761)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `generic`

### Device information
* Brand: `lge`
* Device: `alicee`
* Model: `LG-H840`
* Id: `NRD90U`
* Product: `alicee_global_com`

### Firmware
* SDK: `24`
* Release: `7.0`
* Incremental: `1808720391303`

**Comment by AlvaroBrey** [comment]
Hey @Wiggum127 , can you reproduce this crash reliably?

**Comment by Wiggum127** [comment]
@AlvaroBrey I can reproduce faster than I can submit the error log. Last night the NextCloud app started crashing in continuous loop. Clearing the app cache, stopping the app, restarting the phone did not change the behaviour. Every few seconds I would get an error and error log of the NextCloud app crash. I've removed the app from my phone in the meantime in order to be able to use the phone and other apps. Will re-install as soon as there is an updated version of the app available.

**Comment by duritong** [comment]
Any chance of getting a release with the fix included? Nextcloud App is kinda useless with that issue.

**Comment by duritong** [comment]
Actually, I think I figured out how the issue is triggered: I have multiple nextcloud accounts configured on a multitude of nextcloud instances. One of the instances had a server issue and giving back a 503. This made the whole nextcloud app constantly crashing. Since the server got fixed, the app is not crashing anymore.
