### ISSUE TITLE
`TransactionTooLargeException` in `onCheckAvailableSpaceFinish()`

### ISSUE THREAD

**Issue by Seb968** [nextcloud/android#10242]
### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2857724 bytes
    at android.app.ActivityClient.finishActivity(ActivityClient.java:156)
    at android.app.Activity.finish(Activity.java:6586)
    at android.app.Activity.finish(Activity.java:6620)
    at com.owncloud.android.ui.activity.UploadFilesActivity.onCheckAvailableSpaceFinish(UploadFilesActivity.java:536)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:72)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:34)
    at android.os.AsyncTask.finish(AsyncTask.java:771)
    at android.os.AsyncTask.access$900(AsyncTask.java:199)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8663)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: Exception in thread "main" android.os.TransactionTooLargeException: data parcel size 2857724 bytes
    at android.os.BinderProxy.transactNative(Native Method)
    at android.os.BinderProxy.transact(BinderProxy.java:635)
    at android.app.IActivityClientController$Stub$Proxy.finishActivity(IActivityClientController.java:1557)
    at android.app.ActivityClient.finishActivity(ActivityClient.java:153)
    at android.app.Activity.finish(Activity.java:6586)
    at android.app.Activity.finish(Activity.java:6620)
    at com.owncloud.android.ui.activity.UploadFilesActivity.onCheckAvailableSpaceFinish(UploadFilesActivity.java:536)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:72)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:34)
    at android.os.AsyncTask.finish(AsyncTask.java:771)
    at android.os.AsyncTask.access$900(AsyncTask.java:199)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8663)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `beyond1`
* Model: `SM-G973F`
* Id: `SP1A.210812.016`
* Product: `beyond1lteeea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `G973FXXUEHVC6`

**Comment by joshtrichards** [comment]
Fixed in #13336
