### ISSUE TITLE
Crash when changing to Media

### ISSUE THREAD

**Issue by TomSH75** [nextcloud/android#10258]
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'void com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(com.nextcloud.client.account.User, com.owncloud.android.datamodel.OCFile, com.owncloud.android.datamodel.FileDataStorageManager, boolean, java.lang.String)' on a null object reference
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1285)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1233)
    at com.owncloud.android.ui.fragment.OCFileListFragment.refreshDirectory(OCFileListFragment.java:1229)
    at com.owncloud.android.ui.activity.FileDisplayActivity.showFiles(FileDisplayActivity.java:2288)
    at com.owncloud.android.ui.activity.DrawerActivity.onNavigationItemClicked(DrawerActivity.java:454)
    at com.owncloud.android.ui.activity.DrawerActivity.lambda$setupDrawerMenu$0$com-owncloud-android-ui-activity-DrawerActivity(DrawerActivity.java:398)
    at com.owncloud.android.ui.activity.DrawerActivity$$ExternalSyntheticLambda5.run(Unknown Source:4)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:246)
    at android.app.ActivityThread.main(ActivityThread.java:8653)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `a40`
* Model: `SM-A405FN`
* Id: `RP1A.200720.012`
* Product: `a40eea`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `A405FNXXU4CVD1`

**Comment by hj-beckers** [comment]
Seems I have the same problem:

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'void com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(com.nextcloud.client.account.User, com.owncloud.android.datamodel.OCFile, com.owncloud.android.datamodel.FileDataStorageManager, boolean, java.lang.String)' on a null object reference
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1285)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1233)
    at com.owncloud.android.ui.fragment.OCFileListFragment.refreshDirectory(OCFileListFragment.java:1229)
    at com.owncloud.android.ui.activity.FileDisplayActivity.showFiles(FileDisplayActivity.java:2288)
    at com.owncloud.android.ui.activity.DrawerActivity.onNavigationItemClicked(DrawerActivity.java:454)
    at com.owncloud.android.ui.activity.DrawerActivity.lambda$setupDrawerMenu$0$com-owncloud-android-ui-activity-DrawerActivity(DrawerActivity.java:398)
    at com.owncloud.android.ui.activity.DrawerActivity$$ExternalSyntheticLambda5.run(D8$$SyntheticClass)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:158)
    at android.app.ActivityThread.main(ActivityThread.java:7225)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `generic`

### Device information
* Brand: `samsung`
* Device: `trlte`
* Model: `SM-N910F`
* Id: `MMB29M`
* Product: `trltexx`

### Firmware
* SDK: `23`
* Release: `6.0.1`
* Incremental: `N910FXXU1DRI2`
