### ISSUE TITLE
Crash: TimeoutException in android.media.MediaMetadataRetriever.finalize()

### ISSUE THREAD

**Issue by MarvinV28** [nextcloud/android#10274]
### Cause of error
```java
Exception in thread "FinalizerWatchdogDaemon" java.util.concurrent.TimeoutException: android.media.MediaMetadataRetriever.finalize() timed out after 10 seconds
    at android.media.MediaMetadataRetriever.native_finalize(Native Method)
    at android.media.MediaMetadataRetriever.finalize(MediaMetadataRetriever.java:1115)
    at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
    at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
    at java.lang.Daemons$Daemon.run(Daemons.java:139)
    at java.lang.Thread.run(Thread.java:920)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OnePlus9Pro`
* Model: `LE2123`
* Id: `SKQ1.210216.001`
* Product: `OnePlus9Pro_EEA`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `R.202203102003`

**Comment by Kathou99** [comment]
Hi, I have the same issue here,it's been okay with some bug last 30days but now the app only crashing... 

Does your,you can't open the app?

Like mine I got these error pop all the time
![received_417249199946436](https://user-images.githubusercontent.com/71993497/169697551-6434bd8f-0cc8-4eea-b5ea-b25beef1fa6c.jpeg)
![received_526571615665270](https://user-images.githubusercontent.com/71993497/169697562-6dfc69a8-401d-4ffa-b911-a3c1ce89e359.jpeg)

Hope they will fix the issue soon... :)

**Comment by AlvaroBrey** [comment]
Hi @MarvinV28 , can you reproduce this crash? What are the steps to reproduce it, if so?
