### ISSUE TITLE
Error while renaming an audio file

### ISSUE THREAD

**Issue by Practicalbutterfly5** [nextcloud/android#10290]
### Cause of error
This happens while trying to rename any file. 
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.lib.common.operations.RemoteOperationResult.isSuccess()' on a null object reference
    at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:348)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoteOperationFinish(FileDisplayActivity.java:1649)
    at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:778)
    at com.owncloud.android.services.OperationsService$$ExternalSyntheticLambda0.run(Unknown Source:6)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:236)
    at android.app.ActivityThread.main(ActivityThread.java:8059)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`

### Device information
* Brand: `Redmi`
* Device: `sweetin`
* Model: `M2101K6P`
* Id: `RKQ1.200826.002`
* Product: `sweetin`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `V12.5.8.0.RKFINXM`

**Comment by joshtrichards** [comment]
Hi @Practicalbutterfly5 - Are you using the `groupfolders` app on your server by chance?

**Comment by joshtrichards** [comment]
Duplicate #10465 

Let's consolidate this with #10465 

Feel free to follow-up there with further info/etc.
