### ISSUE TITLE
After remove Account, press back cause an error

### ISSUE THREAD

**Issue by rigasdannbs** [nextcloud/android#10321]
### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException
    at com.owncloud.android.ui.activities.ActivitiesActivity$$ExternalSyntheticLambda0.get(Unknown Source:2)
    at com.nextcloud.java.util.Optional.orElseThrow(Optional.java:309)
    at com.owncloud.android.ui.activity.FileDisplayActivity$8.run(FileDisplayActivity.java:1995)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:233)
    at android.os.Looper.loop(Looper.java:344)
    at android.app.ActivityThread.main(ActivityThread.java:8191)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`

### Device information
* Brand: `OPPO`
* Device: `OP4F1BL1`
* Model: `CPH2145`
* Id: `RKQ1.211103.002`
* Product: `CPH2145T2`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `R.202204182309`

**Comment by AlvaroBrey** [comment]
Duplicate of #10076
