### ISSUE TITLE
Android client stable or preview won't list files, crashes on gallery view

### ISSUE THREAD

**Issue by seanthegeek** [nextcloud/android#10344]
I noticed that new files weren't appearing in the mobile app, so I tried clearing the app storage. I was able to successfully log back in, but the all files listing showed no files, despite the storage indicator at the bottom of the hamburger menu showing that storage was used. When I selected gallery from the hamburger menu, the application crashed, generating the trace back below. The server is running the latest stable release and works fine in a web browser. 

I am using a reverse proxy to route traffic from the public internet to the internal server that is actually hosting Nextcloud. Is there some URL that would impact the mobile app, but not the web version?

### Cause of error
```java
Exception in thread "AsyncTask #2" java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$4.done(AsyncTask.java:415) 
    at java.util.concurrent.FutureTask.finishCompletion(FutwureTask.java:383)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
    at java.util.concurrent.FutureTask.run(FutureTask.java:271)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)
Caused by: Exception in thread "AsyncTask #2" java.lang.RuntimeException: Accessing result data after operation failed!
    at com.owncloud.android.lib.common.operations.RemoteOperationResult.getData(RemoteOperationResult.java:512)
    at com.owncloud.android.ui.asynctasks.GallerySearchTask.doInBackground(GallerySearchTask.java:102)
    at com.owncloud.android.ui.asynctasks.GallerySearchTask.doInBackground(GallerySearchTask.java:48)
    at android.os.AsyncTask$3.call(AsyncTask.java:394)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200251`
* Build flavor: `gplay`

### Device information
redacted

**Comment by svenb1234** [comment]
Dup of  #10198?

**Comment by AlvaroBrey** [comment]
Yep, thanks @svenb1234
