### ISSUE TITLE
Login with app QR code throws an error

### ISSUE THREAD

**Issue by noiob** [nextcloud/android#10347]
### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException
    at com.owncloud.android.ui.activities.ActivitiesActivity$$ExternalSyntheticLambda0.get(Unknown Source:2)
    at com.nextcloud.java.util.Optional.orElseThrow(Optional.java:309)
    at com.owncloud.android.ui.activity.FileDisplayActivity$8.run(FileDisplayActivity.java:1995)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `bramble`
* Model: `Pixel 4a (5G)`
* Id: `SP2A.220505.002`
* Product: `bramble`

### Firmware
* SDK: `32`
* Release: `12`
* Incremental: `8353555`

**Comment by AlvaroBrey** [comment]
@noiob was the second login (successful one) also by QR code?

**Comment by AlvaroBrey** [comment]
Duplicate of #10076

**Comment by noiob** [comment]
Yes, with the same code
