### ISSUE TITLE
crash after switching back from detail to media view

### ISSUE THREAD

**Issue by svenb1234** [nextcloud/android#10383]
### Steps to reproduce
1. Open the media view
2. Open some picture, turn phone to get into landscape mode (not sure the latter makes a difference)
3. Tap on the app's back button

### Expected behaviour
- the media view should be shown again

### Actual behaviour
- long wait then crash

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke interface method 'long com.google.android.exoplayer2.ExoPlayer.getCurrentPosition()' on a null object reference
    at com.owncloud.android.ui.preview.PreviewMediaFragment.onSaveInstanceState(PreviewMediaFragment.java:288)
    at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:3183)
    at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:680)
    at androidx.fragment.app.FragmentStateManager.saveInstanceState(FragmentStateManager.java:671)
    at androidx.fragment.app.FragmentManager.saveFragmentInstanceState(FragmentManager.java:1176)
    at androidx.fragment.app.FragmentStatePagerAdapter.destroyItem(FragmentStatePagerAdapter.java:224)
    at com.owncloud.android.ui.preview.PreviewImagePagerAdapter.destroyItem(PreviewImagePagerAdapter.java:238)
    at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1178)
    at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
    at androidx.viewpager.widget.ViewPager$3.run(ViewPager.java:273)
    at androidx.viewpager.widget.ViewPager.completeScroll(ViewPager.java:2005)
    at androidx.viewpager.widget.ViewPager.scrollToItem(ViewPager.java:692)
    at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1786)
    at android.view.View.layout(View.java:23203)
    at android.view.ViewGroup.layout(ViewGroup.java:6412)
    at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
    at android.view.View.layout(View.java:23203)
    at android.view.ViewGroup.layout(ViewGroup.java:6412)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23203)
    at android.view.ViewGroup.layout(ViewGroup.java:6412)
    at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:536)
    at android.view.View.layout(View.java:23203)
    at android.view.ViewGroup.layout(ViewGroup.java:6412)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23203)
    at android.view.ViewGroup.layout(ViewGroup.java:6412)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
    at android.view.View.layout(View.java:23203)
    at android.view.ViewGroup.layout(ViewGroup.java:6412)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at com.android.internal.policy.DecorView.onLayout(DecorView.java:797)
    at android.view.View.layout(View.java:23203)
    at android.view.ViewGroup.layout(ViewGroup.java:6412)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3749)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3205)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2179)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8787)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
    at android.view.Choreographer.doCallbacks(Choreographer.java:845)
    at android.view.Choreographer.doFrame(Choreographer.java:780)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `oriole`
* Model: `Pixel 6`
* Id: `SP2A.220505.002`
* Product: `oriole`

### Firmware
* SDK: `32`
* Release: `12`
* Incremental: `8353555`

**Comment by svenb1234** [comment]
Thanks for fixing this!
