### ISSUE TITLE
Rapport de Plantage régulier 

### ISSUE THREAD

**Issue by DENIS-P** [nextcloud/android#10412]
### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Unable to pause activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@abf704e is not valid; is your activity running?
    at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5557)
    at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5508)
    at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5460)
    at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:47)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8669)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: Exception in thread "main" android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@abf704e is not valid; is your activity running?
    at android.view.ViewRootImpl.setView(ViewRootImpl.java:1588)
    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:509)
    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:133)
    at android.app.Dialog.show(Dialog.java:512)
    at androidx.fragment.app.DialogFragment.onStart(DialogFragment.java:710)
    at androidx.fragment.app.Fragment.performStart(Fragment.java:3053)
    at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:587)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:279)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
    at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2849)
    at androidx.fragment.app.FragmentManager.dispatchPause(FragmentManager.java:2802)
    at androidx.fragment.app.FragmentController.dispatchPause(FragmentController.java:295)
    at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:366)
    at com.owncloud.android.ui.activity.BaseActivity.onPause(BaseActivity.java:84)
    at com.owncloud.android.ui.activity.FileActivity.onPause(FileActivity.java:254)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onPause(FileDisplayActivity.java:1173)
    at android.app.Activity.performPause(Activity.java:8485)
    at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1530)
    at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5547)
    at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5508)
    at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5460)
    at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:47)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8669)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `c1s`
* Model: `SM-N981B`
* Id: `SP1A.210812.016`
* Product: `c1sxeea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `N981BXXS4FVEA`

**Comment by AlvaroBrey** [comment]
@DENIS-P can you reproduce this crash reliably?

**Comment by DENIS-P** [comment]
@AlvaroBrey 

This bug already exist on my Samsung Note 20. Who I can Help you?

**Comment by AlvaroBrey** [comment]
> This bug already exist on my Samsung Note 20. Who I can Help you?

How can you reproduce this crash? That is, what steps do you take to cause it?

**Comment by DENIS-P** [comment]
The appli is installed on my phone
My Nextcloud Server is locally hosted.

I will try to uninstall / re install and test.
