### ISSUE TITLE
`LoggerTest.queue overflow warning is logged` fails randomly

### ISSUE THREAD

**Issue by AlvaroBrey** [nextcloud/android#10416]
Example here:  https://www.kaminsky.me/nc-dev/android-integrationTests/10036-Unit-test-08-25/classes/com.nextcloud.client.logger.LoggerTest.html#queue%20overflow%20warning%20is%20logged

<details>
<summary> Click to see trace </summary>

```
Argument(s) are different! Wanted:
function2.invoke(
    <custom argument matcher>,
    <any java.lang.Long>
);
-> at com.nextcloud.client.logger.LoggerTest.queue overflow warning is logged(LoggerTest.kt:263)
Actual invocations have different arguments:
function2.invoke(
    [2022-06-20T08:24:50.334Z;D;tag;Message 25, 2022-06-20T08:24:50.334Z;D;tag;Message 26, 2022-06-20T08:24:50.334Z;D;tag;Message 27, 2022-06-20T08:24:50.334Z;D;tag;Message 28, 2022-06-20T08:24:50.334Z;D;tag;Message 29, 2022-06-20T08:24:50.334Z;D;tag;Message 30, 2022-06-20T08:24:50.334Z;D;tag;Message 31, 2022-06-20T08:24:50.334Z;D;tag;Message 32, 2022-06-20T08:24:50.334Z;D;tag;Message 33, 2022-06-20T08:24:50.334Z;D;tag;Message 34, 2022-06-20T08:24:50.334Z;D;tag;Message 35, 2022-06-20T08:24:50.334Z;D;tag;Message 36, 2022-06-20T08:24:50.334Z;D;tag;Message 37, 2022-06-20T08:24:50.334Z;D;tag;Message 38, 2022-06-20T08:24:50.334Z;D;tag;Message 39, 2022-06-20T08:24:50.334Z;D;tag;Message 40, 2022-06-20T08:24:50.334Z;D;tag;Message 41, 2022-06-20T08:24:50.334Z;D;tag;Message 42, 2022-06-20T08:24:50.334Z;D;tag;Message 43, 2022-06-20T08:24:50.334Z;D;tag;Message 44, 2022-06-20T08:24:50.334Z;D;tag;Message 45, 2022-06-20T08:24:50.334Z;D;tag;Message 46, 2022-06-20T08:24:50.334Z;D;tag;Message 47, 2022-06-20T08:24:50.334Z;D;tag;Message 48, 2022-06-20T08:24:50.334Z;D;tag;Message 49, 2022-06-20T08:24:50.334Z;D;tag;Message 50, 2022-06-20T08:24:50.334Z;D;tag;Message 51, 2022-06-20T08:24:50.334Z;D;tag;Message 52, 2022-06-20T08:24:50.334Z;D;tag;Message 53, 2022-06-20T08:24:50.334Z;D;tag;Message 54, 2022-06-20T08:24:50.334Z;D;tag;Message 55, 2022-06-20T08:24:50.334Z;D;tag;Message 56, 2022-06-20T08:24:50.334Z;D;tag;Message 57, 2022-06-20T08:24:50.334Z;D;tag;Message 58, 2022-06-20T08:24:50.334Z;D;tag;Message 59, 2022-06-20T08:24:50.334Z;D;tag;Message 60, 2022-06-20T08:24:50.334Z;D;tag;Message 61, 2022-06-20T08:24:50.334Z;D;tag;Message 62, 2022-06-20T08:24:50.334Z;D;tag;Message 63, 2022-06-20T08:24:50.334Z;D;tag;Message 64, 2022-06-20T08:24:50.334Z;D;tag;Message 65, 2022-06-20T08:24:50.334Z;D;tag;Message 66, 2022-06-20T08:24:50.334Z;D;tag;Message 67, 2022-06-20T08:24:50.334Z;D;tag;Message 68, 2022-06-20T08:24:50.334Z;D;tag;Message 69, 2022-06-20T08:24:50.334Z;D;tag;Message 70, 2022-06-20T08:24:50.334Z;D;tag;Message 71, 2022-06-20T08:24:50.334Z;D;tag;Message 72, 2022-06-20T08:24:50.334Z;D;tag;Message 73, 2022-06-20T08:24:50.334Z;D;tag;Message 74, 2022-06-20T08:24:50.334Z;D;tag;Message 75, 2022-06-20T08:24:50.334Z;D;tag;Message 76, 2022-06-20T08:24:50.334Z;D;tag;Message 77, 2022-06-20T08:24:50.334Z;D;tag;Message 78, 2022-06-20T08:24:50.334Z;D;tag;Message 79, 2022-06-20T08:24:50.334Z;D;tag;Message 80, 2022-06-20T08:24:50.334Z;D;tag;Message 81, 2022-06-20T08:24:50.334Z;D;tag;Message 82, 2022-06-20T08:24:50.334Z;D;tag;Message 83, 2022-06-20T08:24:50.334Z;D;tag;Message 84, 2022-06-20T08:24:50.334Z;D;tag;Message 85, 2022-06-20T08:24:50.334Z;D;tag;Message 86, 2022-06-20T08:24:50.334Z;D;tag;Message 87, 2022-06-20T08:24:50.334Z;D;tag;Message 88, 2022-06-20T08:24:50.334Z;D;tag;Message 89, 2022-06-20T08:24:50.334Z;D;tag;Message 90, 2022-06-20T08:24:50.334Z;D;tag;Message 91, 2022-06-20T08:24:50.334Z;D;tag;Message 92, 2022-06-20T08:24:50.334Z;D;tag;Message 93, 2022-06-20T08:24:50.334Z;D;tag;Message 94, 2022-06-20T08:24:50.334Z;D;tag;Message 95, 2022-06-20T08:24:50.334Z;D;tag;Message 96, 2022-06-20T08:24:50.334Z;D;tag;Message 97, 2022-06-20T08:24:50.334Z;D;tag;Message 98, 2022-06-20T08:24:50.334Z;D;tag;Message 99],
    3150L
);
-> at com.nextcloud.client.logger.LoggerImpl.eventLoop$lambda-1(LoggerImpl.kt:146)

	at app//com.nextcloud.client.logger.LoggerTest.queue overflow warning is logged(LoggerTest.kt:263)
	at java.base@11.0.15/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.15/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.15/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.15/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at app//org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at jdk.internal.reflect.GeneratedMethodAccessor66.invoke(Unknown Source)
	at java.base@11.0.15/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.15/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```
</details>

When this happens, the events in the test contain every log event except for the one we're actually testing for. I haven't been able to reproduce it locally.

This is clearly some sort of race condition but I can't figure out where. I suspect the `Load` event might be getting to the queue before the log events are processed, so that the listener is called before the overflow is written.

 cc @ezaquarii

**Comment by ezaquarii** [comment]
@AlvaroBrey I'll take a look at this.

**Comment by ezaquarii** [comment]
@AlvaroBrey Youp, I can confirm that the test is racey.
