### ISSUE TITLE
crash on enabling a directory for auto upload

### ISSUE THREAD

**Issue by danialbehzadi** [nextcloud/android#10438]
### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Unable to start service com.owncloud.android.files.services.FileUploader@bf6aef4 with Intent { cmp=com.nextcloud.client/com.owncloud.android.files.services.FileUploader (has extras) }: java.lang.IllegalArgumentException: Trying to create a OCFile with a non valid remote path: آپلود فوری/OpenCamera/IMG_20220626_165851.jpg
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4724)
    at android.app.ActivityThread.access$2000(ActivityThread.java:256)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2129)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: Exception in thread "main" java.lang.IllegalArgumentException: Trying to create a OCFile with a non valid remote path: آپلود فوری/OpenCamera/IMG_20220626_165851.jpg
    at com.owncloud.android.datamodel.OCFile.<init>(OCFile.java:138)
    at com.owncloud.android.operations.UploadFileOperation.obtainNewOCFileToUpload(UploadFileOperation.java:153)
    at com.owncloud.android.files.services.FileUploader.gatherAndStartNewUploads(FileUploader.java:396)
    at com.owncloud.android.files.services.FileUploader.onStartCommand(FileUploader.java:327)
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4706)
    at android.app.ActivityThread.access$2000(ActivityThread.java:256)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2129)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `generic`

### Device information
* Brand: `Xiaomi`
* Device: `beryllium`
* Model: `POCO F1`
* Id: `SQ3A.220605.009.A1`
* Product: `beryllium`

### Firmware
* SDK: `32`
* Release: `12`
* Incremental: `6d51ea384c`

**Comment by AlvaroBrey** [comment]
> non valid remote path: آپلود فوری/OpenCamera/IMG_20220626_165851.jpg

That  is indeed an invalid path as it does not start with `/`.

@danialbehzadi Was this enabling one of the auto-detected autoupload folders, or did you manually configure it?

**Comment by danialbehzadi** [comment]
> @danialbehzadi Was this enabling one of the auto-detected autoupload folders, or did you manually configure it?

I've enabled an auto-detected folder.

**Comment by joshtrichards** [comment]
Does the problem also occur if you manually configure a path?

**Comment by joshtrichards** [comment]
May be an RTL issue since we use this string as the literal upload path:

https://github.com/nextcloud/android/blob/ff060eff6ad259bef6e9c873d06d7681a35f84b0/app/src/main/res/values-fa/strings.xml#L448
