### ISSUE TITLE
Renaming a Folder in the Nextcloud app (Android) will produce a NPE

### ISSUE THREAD

**Issue by NikaLost** [nextcloud/android#10444]
### Steps to reproduce
1. Create a folder
2. Try to rename it

### Expected behaviour
The new name should be applied to the folder.

### Actual behaviour
Error (NPE)

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version: 3.20.3

Nextcloud server version: 

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.lib.common.operations.RemoteOperationResult.isSuccess()' on a null object reference
    at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:348)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoteOperationFinish(FileDisplayActivity.java:1649)
    at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:778)
    at com.owncloud.android.services.OperationsService$$ExternalSyntheticLambda0.run(Unknown Source:6)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `oriole`
* Model: `Pixel 6`
* Product: `oriole`

### Firmware
* SDK: `32`
* Release: `12`
* Incremental: `8650216`

**Comment by AlvaroBrey** [comment]
Can't reproduce. Does this happen every time?

**Comment by NikaLost** [comment]
> Can't reproduce. Does this happen every time?

Yes, it does happen everytime. But I do also have some other problems with my nextcloud app, e.g. I can't view/download documents such as pdf in the nextcloud app on my phone..

**Comment by NikaLost** [comment]
Never mind, I just solved the problem. The nextcloud app just needed all permissions for accessing data. Maybe a hint by the nextcloud app would help, if it's missing those permissions.

**Comment by AlvaroBrey** [comment]
Hmm, those things shouldn't need permissions. Will investigate
