### ISSUE TITLE
Android 12 crash

### ISSUE THREAD

**Issue by ThelRaul** [nextcloud/android#10467]
### Cause of error
```java
Exception in thread "main" android.app.ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{af7ef63 u0 com.nextcloud.client/com.owncloud.android.files.services.FileUploader}
    at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2147)
    at android.app.ActivityThread.access$2900(ActivityThread.java:310)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2376)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8669)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `r8q`
* Model: `SM-G781B`
* Id: `SP1A.210812.016`
* Product: `r8qxeea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `G781BXXU4FVE8`

**Comment by tobiasKaminsky** [comment]
Can you tell us when this happens?

**Comment by AlvaroBrey** [comment]
Duplicate of #9617

**Comment by strugee** [comment]
@AlvaroBrey did you mean to close this?

**Comment by AlvaroBrey** [comment]
> @AlvaroBrey did you mean to close this?

no, let's wait to see if we get any extra information from @ThelRaul
