### ISSUE TITLE
Error while renaming a file: NullPointerException: `Attempt to invoke virtual method 'boolean com.owncloud.android.lib.common.operations.RemoteOperationResult.isSuccess()`

### ISSUE THREAD

**Issue by olafkenfenheuer** [nextcloud/android#10465]
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.lib.common.operations.RemoteOperationResult.isSuccess()' on a null object reference
    at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:348)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoteOperationFinish(FileDisplayActivity.java:1649)
    at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:778)
    at com.owncloud.android.services.OperationsService$$ExternalSyntheticLambda0.run(Unknown Source:6)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:241)
    at android.os.Looper.loop(Looper.java:358)
    at android.app.ActivityThread.main(ActivityThread.java:8006)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `gplay`

### Device information
* Brand: `asus`
* Device: `ASUS_I006D`
* Model: `ASUS_I006D`
* Id: `SKQ1.210821.001`
* Product: `EU_I006D`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `31.1010.0411.89`

**Comment by tobiasKaminsky** [comment]
Can you tell us when this happens?
A normal file/folder rename works fine here (which obviously does not say that much… ;-))

**Comment by olafkenfenheuer** [comment]
Hi,


I did nothing special.

Just press three dots Button near the file name.

Rename  file name and press rename.


Nothing more.


best regards

Olaf


________________________________
Von: Tobias Kaminsky ***@***.***>
Gesendet: Montag, 4. Juli 2022 08:40:34
An: nextcloud/android
Cc: Olaf Kenfenheuer; Author
Betreff: Re: [nextcloud/android] Error rename file (Issue #10465)


Can you tell us when this happens?
A normal file/folder rename works fine here (which obviously does not say that much… ;-))

**Comment by joshtrichards** [comment]
Hi @olafkenfenheuer - Per other reports (e.g. #10702) this issue seems fixed. If you can reproduce it still feel free to reply and I'll re-open.
