### ISSUE TITLE
Crash: RuntimeException in thread Chrome_ProcessLauncherThread: illegal meta data value

### ISSUE THREAD

**Issue by telmich** [nextcloud/android#10462]
### Cause of error
```java
Exception in thread "Chrome_ProcessLauncherThread" java.lang.RuntimeException: Illegal meta data value: the child service doesn't exist
    at Wi.a(Unknown Source:35)
    at org.chromium.content.browser.ChildProcessLauncherHelperImpl.b(Unknown Source:153)
    at Dj.run(Unknown Source:36)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.os.HandlerThread.run(HandlerThread.java:67)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `oriole`
* Model: `Pixel 6`
* Id: `SP2A.220305.013.A3`
* Product: `oriole`

### Firmware
* SDK: `32`
* Release: `12`
* Incremental: `8229987`

**Comment by AlvaroBrey** [comment]
Hmmm, how did this crash happen? The exception points to Chrome, not our app. Did this happen while trying to login, or something else?

**Comment by JasminPambhar** [comment]
I have also same issue. Issue are given by Google Crash and ANR

Exception java.lang.RuntimeException: Illegal meta data value: the child service doesn't exist
  at di.a (di.java:95)
  at org.chromium.content.browser.ChildProcessLauncherHelperImpl.a (ChildProcessLauncherHelperImpl.java:134)
  at Li.run (Li.java:458)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:268)
  at android.os.HandlerThread.run (HandlerThread.java:67)
