### ISSUE TITLE
Fehlermeldung beim verschieben von Dateien

### ISSUE THREAD

**Issue by Koert1984** [nextcloud/android#10460]
### Cause of error
```java
Exception in thread "Thread-46" java.lang.IllegalStateException: Couldn't read row 704, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetString(Native Method)
    at android.database.CursorWindow.getString(CursorWindow.java:462)
    at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:54)
    at android.database.CursorWrapper.getString(CursorWrapper.java:215)
    at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:957)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:884)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:187)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:241)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:363)
    at java.lang.Thread.run(Thread.java:920)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `gplay`

### Device information
* Brand: `vivo`
* Device: `2041`
* Model: `V2041`
* Id: `SP1A.210812.003`
* Product: `2041_EEA`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `compiler06081824`

**Comment by AlvaroBrey** [comment]
Duplicate of #9948
