### ISSUE TITLE
Crash: NPE in `com.nextcloud.common.NextcloudClient.<init>`

### ISSUE THREAD

**Issue by lifeodyssey** [nextcloud/android#10475]
### Cause of error
```java
Exception in thread "Thread-4" java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter userId
    at com.nextcloud.common.NextcloudClient.<init>(Unknown Source:8)
    at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:184)
    at com.owncloud.android.lib.common.OwnCloudClientManager.getNextcloudClientFor(OwnCloudClientManager.java:220)
    at com.owncloud.android.ui.activity.DrawerActivity.lambda$getAndDisplayUserQuota$4$com-owncloud-android-ui-activity-DrawerActivity(DrawerActivity.java:821)
    at com.owncloud.android.ui.activity.DrawerActivity$$ExternalSyntheticLambda2.run(Unknown Source:2)
    at java.lang.Thread.run(Thread.java:929)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `gplay`

### Device information
* Brand: `HUAWEI`
* Device: `HWELE`
* Model: `ELE-AL00`
* Id: `HUAWEIELE-AL00`
* Product: `ELE-AL00`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `10.1.0.162C00`

**Comment by joshtrichards** [comment]
Looks like #8233 & #8370, but...

Is this reproducible, @strugee?

https://github.com/nextcloud/android/issues/8233#issuecomment-832625565

**Comment by joshtrichards** [comment]
Oops, I didn't glance high enough; I thought you were the OP sorry. :-)
