### ISSUE TITLE
Crash while browsing for a File  within another app

### ISSUE THREAD

**Issue by poggenpower** [nextcloud/android#10482]
### Cause of error
```java
Exception in thread "Thread-94" java.lang.NullPointerException: Attempt to invoke virtual method 'long com.owncloud.android.datamodel.OCFile.getParentId()' on a null object reference
    at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:450)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:409)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:239)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:398)
    at java.lang.Thread.run(Thread.java:923)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20220629`
* Build flavor: `versionDev`

### Device information
* Brand: `Fairphone`
* Device: `FP4`
* Model: `FP4`
* Id: `RKQ1.210503.001`
* Product: `FP4eea`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `FP3W`

**Comment by joshtrichards** [comment]
Since you're running the dev version you should be able to get more context surrounding this stack trace from your log file under *Settings -> Log*. 

Can you either confirm you're no longer able to reproduce this problem today (in presumably a newer release) or provide the additional context?

Had you recently deleted any files in your NC instance?
