### ISSUE TITLE
Exception when sharing link via e-mail

### ISSUE THREAD

**Issue by lindhe** [nextcloud/android#10480]
### Cause of error
```java
Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property shareType has not been initialized
    at com.owncloud.android.ui.fragment.FileDetailsSharingProcessFragment.validateShareProcessSecond(FileDetailsSharingProcessFragment.kt:522)
    at com.owncloud.android.ui.fragment.FileDetailsSharingProcessFragment.implementClickEvents$lambda-4(FileDetailsSharingProcessFragment.kt:349)
    at com.owncloud.android.ui.fragment.FileDetailsSharingProcessFragment.$r8$lambda$dFfO5R5R2OUHPHwg_R9LQ4yTXgM(Unknown Source:0)
    at com.owncloud.android.ui.fragment.FileDetailsSharingProcessFragment$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
    at android.view.View.performClick(View.java:7792)
    at android.widget.TextView.performClick(TextView.java:16112)
    at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1131)
    at android.view.View.performClickInternal(View.java:7769)
    at android.view.View.access$3800(View.java:910)
    at android.view.View$PerformClick.run(View.java:30218)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8669)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `o1s`
* Model: `SM-G991B`
* Id: `SP1A.210812.016`
* Product: `o1sxeea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `G991BXXU5CVF1`

**Comment by AlvaroBrey** [comment]
Reproduction steps:
1. Create a share link normally
2. Tap on three dot menu and choose "send new email" 
3. Tap on "Set Note" **without** updating the note
