### ISSUE TITLE
Random exception while scrolling through photos

### ISSUE THREAD

**Issue by 154pinkchairs** [nextcloud/android#10494]
### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Fragment already added: PreviewImageFragment{e0ecdb2} (e31d9a73-056a-435c-bd59-bbe617acebad id=0x7f0a01f5)
    at androidx.fragment.app.FragmentStore.addFragment(FragmentStore.java:92)
    at androidx.fragment.app.FragmentManager.addFragment(FragmentManager.java:1422)
    at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:387)
    at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:1906)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1814)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
    at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1670)
    at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
    at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:274)
    at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
    at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
    at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
    at android.view.View.measure(View.java:25466)
    at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1156)
    at android.view.View.measure(View.java:25466)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
    at android.view.View.measure(View.java:25466)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
    at androidx.appcompat.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:496)
    at android.view.View.measure(View.java:25466)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at android.view.View.measure(View.java:25466)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
    at android.view.View.measure(View.java:25466)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at com.android.internal.policy.DecorView.onMeasure(DecorView.java:747)
    at android.view.View.measure(View.java:25466)
    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3402)
    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2246)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2504)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8182)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1046)
    at android.view.Choreographer.doCallbacks(Choreographer.java:869)
    at android.view.Choreographer.doFrame(Choreographer.java:803)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1031)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7669)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `generic`

### Device information
* Brand: `Xiaomi`
* Device: `vince`
* Model: `Redmi 5 Plus`
* Id: `RD2A.211001.002`
* Product: `lineage_vince`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `eng.krishs.20211107.123528`

**Comment by andyxheli** [comment]
### Cause of error

```java

Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String [com.owncloud.android](http://com.owncloud.android/).datamodel.OCFile.getRemotePath()' on a null object reference

    at [com.owncloud.android.services](http://com.owncloud.android.services/).OperationsService$OperationsServiceBinder.isSynchronizing([OperationsService.java:372](http://operationsservice.java:372/))

    at [com.owncloud.android](http://com.owncloud.android/).files.FileMenuFilter.anyFileSynchronizing([FileMenuFilter.java:522](http://filemenufilter.java:522/))

    at [com.owncloud.android](http://com.owncloud.android/).files.FileMenuFilter.anyFileSynchronizing([FileMenuFilter.java:511](http://filemenufilter.java:511/))

    at [com.owncloud.android](http://com.owncloud.android/).files.FileMenuFilter.filter([FileMenuFilter.java:200](http://filemenufilter.java:200/))

    at [com.owncloud.android](http://com.owncloud.android/).files.FileMenuFilter.filter([FileMenuFilter.java:132](http://filemenufilter.java:132/))

    at [com.owncloud.android](http://com.owncloud.android/).ui.preview.PreviewImageFragment.onPrepareOptionsMenu([PreviewImageFragment.java:378](http://previewimagefragment.java:378/))

    at [androidx.fragment.app](http://androidx.fragment.app/).Fragment.performPrepareOptionsMenu([Fragment.java:3144](http://fragment.java:3144/))

    at [androidx.fragment.app](http://androidx.fragment.app/).FragmentManager.dispatchPrepareOptionsMenu([FragmentManager.java:2923](http://fragmentmanager.java:2923/))

    at [androidx.fragment.app](http://androidx.fragment.app/).FragmentController.dispatchPrepareOptionsMenu([FragmentController.java:414](http://fragmentcontroller.java:414/))

    at [androidx.fragment.app](http://androidx.fragment.app/).FragmentActivity.onPreparePanel([FragmentActivity.java:447](http://fragmentactivity.java:447/))

    at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel([WindowCallbackWrapper.java:99](http://windowcallbackwrapper.java:99/))

    at [androidx.appcompat.app](http://androidx.appcompat.app/).AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel([AppCompatDelegateImpl.java:3149](http://appcompatdelegateimpl.java:3149/))

    at [androidx.appcompat.app](http://androidx.appcompat.app/).AppCompatDelegateImpl.preparePanel([AppCompatDelegateImpl.java:1937](http://appcompatdelegateimpl.java:1937/))

    at [androidx.appcompat.app](http://androidx.appcompat.app/).AppCompatDelegateImpl.doInvalidatePanelMenu([AppCompatDelegateImpl.java:2191](http://appcompatdelegateimpl.java:2191/))

    at [androidx.appcompat.app](http://androidx.appcompat.app/).AppCompatDelegateImpl$2.run([AppCompatDelegateImpl.java:273](http://appcompatdelegateimpl.java:273/))

    at android.view.Choreographer$CallbackRecord.run([Choreographer.java:1108](http://choreographer.java:1108/))

    at android.view.Choreographer.doCallbacks([Choreographer.java:866](http://choreographer.java:866/))

    at android.view.Choreographer.doFrame([Choreographer.java:792](http://choreographer.java:792/))

    at android.view.Choreographer$FrameDisplayEventReceiver.run([Choreographer.java:1092](http://choreographer.java:1092/))

    at android.os.Handler.handleCallback([Handler.java:938](http://handler.java:938/))

    at android.os.Handler.dispatchMessage([Handler.java:99](http://handler.java:99/))

    at android.os.Looper.loopOnce([Looper.java:226](http://looper.java:226/))

    at android.os.Looper.loop([Looper.java:313](http://looper.java:313/))

    at [android.app](http://android.app/).ActivityThread.main([ActivityThread.java:8669](http://activitythread.java:8669/))

    at java.lang.reflect.Method.invoke(Native Method)

    at [com.android](http://com.android/).internal.os.RuntimeInit$MethodAndArgsCaller.run([RuntimeInit.java:571](http://runtimeinit.java:571/))

    at [com.android](http://com.android/).internal.os.ZygoteInit.main([ZygoteInit.java:1135](http://zygoteinit.java:1135/))

```

### App information

* ID: com.nextcloud.client

* Version: 30200390

* Build flavor: gplay

### Device information

* Brand: samsung

* Device: t2q

* Model: SM-G996U1

* Id: SP1A.210812.016

* Product: t2quew

### Firmware

* SDK: 31

* Release: 12

* Incremental: G996U1UEU5CVF1

**Comment by 154pinkchairs** [comment]
In the preview mode.

**Comment by 154pinkchairs** [comment]
Also, the photo for which the bug appeared also wasn't accessible through file picker (in Pixeldroid for example, there was just like an empty photo). It did however load into external apps through sharing menu.

**Comment by AlvaroBrey** [comment]
> Also, the photo for which the bug appeared also wasn't accessible through file picker (in Pixeldroid for example, there was just like an empty photo). It did however load into external apps through sharing menu.

Oh, that sounds like it could be related to #9328. Can you check if you have an `(invalid)` folder in your storage? If so, delete it and those "empty" pictures should disappear

**Comment by 154pinkchairs** [comment]
No, neither in the root folder nor in the folder first affected by the issue.
