### ISSUE TITLE
NPE in OCFileListFragment.isGridViewPreferred

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#105]
From the Play store developer console.
### Environment data

Android version: 6.0 and 5.1

Device model: Swift, Nexus 7 (2012) (tilapia), Moto G (3rd Gen) (osprey_umts), Nexus 5X (bullhead), Galaxy S2 (GT-I9100) 

Stock or customized system: -

Nextcloud app version: 1.1.0 stable

Nextcloud server version: - 
#### Nextcloud log (data/nextcloud.log)

```
java.lang.NullPointerException: Attempt to invoke interface method 'com.owncloud.android.datamodel.FileDataStorageManager com.owncloud.android.ui.fragment.FileFragment$ContainerActivity.getStorageManager()' on a null object reference
    at com.owncloud.android.ui.fragment.OCFileListFragment.isGridViewPreferred(OCFileListFragment.java:790)
    at com.owncloud.android.ui.fragment.OCFileListFragment.changeGridIcon(OCFileListFragment.java:835)
    at com.owncloud.android.ui.fragment.OCFileListFragment.onPrepareOptionsMenu(OCFileListFragment.java:402)
    at android.support.v4.app.Fragment.performPrepareOptionsMenu(Fragment.java:2058)
    at android.support.v4.app.FragmentManagerImpl.dispatchPrepareOptionsMenu(FragmentManager.java:2145)
    at android.support.v4.app.FragmentController.dispatchPrepareOptionsMenu(FragmentController.java:282)
    at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:477)
    at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:90)
    at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onPreparePanel(AppCompatDelegateImplBase.java:268)
    at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:90)
    at android.support.v7.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:550)
    at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:443)
    at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:60)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5466)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by AndyScherzinger** [comment]
Do you have any idea @tobiasKaminsky @przybylski? This has been reported 6 times in the last 7 days, so I guess it might happen even more often than that... :(

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky when/where did we fix this?

**Comment by tobiasKaminsky** [comment]
Missed the comment :/
I cannot reproduce it, therefore closing :/
