### ISSUE TITLE
Android nextcloud app

### ISSUE THREAD

**Issue by bratzrick01** [nextcloud/android#10532]
### Cause of error
```java
Exception in thread "main" android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=9
    at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
    at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:986)
    at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:858)
    at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
    at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:153)
    at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:140)
    at android.content.ContentResolver.query(ContentResolver.java:974)
    at android.content.ContentResolver.query(ContentResolver.java:891)
    at android.content.ContentResolver.query(ContentResolver.java:840)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:872)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:187)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:610)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1285)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1233)
    at com.owncloud.android.ui.fragment.OCFileListFragment.onItemClicked(OCFileListFragment.java:992)
    at com.owncloud.android.ui.adapter.OCFileListDelegate.bindGridItemLayout$lambda-1(OCFileListDelegate.kt:164)
    at com.owncloud.android.ui.adapter.OCFileListDelegate.$r8$lambda$Q9OhKWaUB6Dopk7l8lNni9-d6bY(Unknown Source:0)
    at com.owncloud.android.ui.adapter.OCFileListDelegate$$ExternalSyntheticLambda1.onClick(Unknown Source:4)
    at android.view.View.performClick(View.java:7317)
    at android.view.View.performClickInternal(View.java:7291)
    at android.view.View.access$3600(View.java:838)
    at android.view.View$PerformClick.run(View.java:28247)
    at android.os.Handler.handleCallback(Handler.java:900)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at android.os.Looper.loop(Looper.java:219)
    at android.app.ActivityThread.main(ActivityThread.java:8668)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `gplay`

### Device information
* Brand: `HUAWEI`
* Device: `HWVOG`
* Model: `VOG-L29`
* Id: `HUAWEIVOG-L29`
* Product: `VOG-L29EEA`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `10.1.0.150C431`

**Comment by bratzrick01** [comment]
The error occurs in a folder with a lot of pictures. The folder hierarchy is flat
