### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference

### ISSUE THREAD

**Issue by ckujau** [nextcloud/android#10531]
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.services.OperationsService$OperationsServiceBinder.isSynchronizing(OperationsService.java:372)
    at com.owncloud.android.files.FileMenuFilter.anyFileSynchronizing(FileMenuFilter.java:497)
    at com.owncloud.android.files.FileMenuFilter.anyFileSynchronizing(FileMenuFilter.java:486)
    at com.owncloud.android.files.FileMenuFilter.filter(FileMenuFilter.java:194)
    at com.owncloud.android.files.FileMenuFilter.filter(FileMenuFilter.java:126)
    at com.owncloud.android.ui.preview.PreviewImageFragment.onPrepareOptionsMenu(PreviewImageFragment.java:378)
    at androidx.fragment.app.Fragment.performPrepareOptionsMenu(Fragment.java:3253)
    at androidx.fragment.app.FragmentManager.dispatchPrepareOptionsMenu(FragmentManager.java:3051)
    at androidx.fragment.app.FragmentManager$2.onPrepareMenu(FragmentManager.java:466)
    at androidx.core.view.MenuHostHelper.onPrepareMenu(MenuHostHelper.java:63)
    at androidx.activity.ComponentActivity.onPrepareOptionsMenu(ComponentActivity.java:497)
    at android.app.Activity.onPreparePanel(Activity.java:4301)
    at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
    at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3148)
    at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:1936)
    at androidx.appcompat.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:2190)
    at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:273)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
    at android.view.Choreographer.doCallbacks(Choreographer.java:845)
    at android.view.Choreographer.doFrame(Choreographer.java:775)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210051`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `sunfish`
* Model: `Pixel 4a`
* Id: `SQ3A.220705.003.A1`
* Product: `sunfish`

### Firmware
* SDK: `32`
* Release: `12`
* Incremental: `8672226`

**Comment by ckujau** [comment]
This just happened, for the first time, and NC asked me to submit this report.

**Comment by AlvaroBrey** [comment]
Duplicate of #10498
