### ISSUE TITLE
NPE while removing my account in `SynchronizeFolderOperation.getFolderPath`

### ISSUE THREAD

**Issue by FALErwi** [nextcloud/android#10575]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Manage account to remove my account
2. After remove the account below massage came out

### Expected behaviour

Return me to login screen

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getStoragePath()' on a null object reference
    at com.owncloud.android.operations.SynchronizeFolderOperation.getFolderPath(SynchronizeFolderOperation.java:527)
    at com.owncloud.android.utils.ErrorMessageAdapter.getMessageForOperation(ErrorMessageAdapter.java:496)
    at com.owncloud.android.utils.ErrorMessageAdapter.getErrorCauseMessage(ErrorMessageAdapter.java:84)
    at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:377)
    at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:778)
    at com.owncloud.android.services.OperationsService$$ExternalSyntheticLambda0.run(Unknown Source:6)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8669)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `c2s`
* Model: `SM-N986B`
* Id: `SP1A.210812.016`
* Product: `c2sxxx`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `N986BXXS4FVG1`

### Android version

12

### Device brand and model

Samsung Note 20 ultra

### Stock or custom OS?

Stock

### Nextcloud android app version

3.20.3

### Nextcloud server version

24.3

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getStoragePath()' on a null object reference
    at com.owncloud.android.operations.SynchronizeFolderOperation.getFolderPath(SynchronizeFolderOperation.java:527)
    at com.owncloud.android.utils.ErrorMessageAdapter.getMessageForOperation(ErrorMessageAdapter.java:496)
    at com.owncloud.android.utils.ErrorMessageAdapter.getErrorCauseMessage(ErrorMessageAdapter.java:84)
    at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:377)
    at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:778)
    at com.owncloud.android.services.OperationsService$$ExternalSyntheticLambda0.run(Unknown Source:6)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8669)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `c2s`
* Model: `SM-N986B`
* Id: `SP1A.210812.016`
* Product: `c2sxxx`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `N986BXXS4FVG1`

### Server error logs

```bash
### Cause of error

Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getStoragePath()' on a null object reference
    at com.owncloud.android.operations.SynchronizeFolderOperation.getFolderPath(SynchronizeFolderOperation.java:527)
    at com.owncloud.android.utils.ErrorMessageAdapter.getMessageForOperation(ErrorMessageAdapter.java:496)
    at com.owncloud.android.utils.ErrorMessageAdapter.getErrorCauseMessage(ErrorMessageAdapter.java:84)
    at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:377)
    at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:778)
    at com.owncloud.android.services.OperationsService$$ExternalSyntheticLambda0.run(Unknown Source:6)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8669)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)



### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `c2s`
* Model: `SM-N986B`
* Id: `SP1A.210812.016`
* Product: `c2sxxx`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `N986BXXS4FVG1`
```

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getStoragePath()' on a null object reference
    at com.owncloud.android.operations.SynchronizeFolderOperation.getFolderPath(SynchronizeFolderOperation.java:527)
    at com.owncloud.android.utils.ErrorMessageAdapter.getMessageForOperation(ErrorMessageAdapter.java:496)
    at com.owncloud.android.utils.ErrorMessageAdapter.getErrorCauseMessage(ErrorMessageAdapter.java:84)
    at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:377)
    at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:778)
    at com.owncloud.android.services.OperationsService$$ExternalSyntheticLambda0.run(Unknown Source:6)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8669)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `c2s`
* Model: `SM-N986B`
* Id: `SP1A.210812.016`
* Product: `c2sxxx`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `N986BXXS4FVG1`

**Comment by joshtrichards** [comment]
This may have been since fixed via #10013 & #10089.

Have you experienced this since or are you still able to reproduce this in newer versions?
