### ISSUE TITLE
3.21.0 RC1 - App crashes, when a maximized picture will be deleted

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/android#10580]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Look for your pic, you want to delete
2. maximise the pic
3. delete
4. -> Crash

### Expected behaviour

Pic should be deleted

### Actual behaviour

App crashes

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.services.OperationsService$OperationsServiceBinder.isSynchronizing(OperationsService.java:372)
    at com.owncloud.android.files.FileMenuFilter.anyFileSynchronizing(FileMenuFilter.java:497)
    at com.owncloud.android.files.FileMenuFilter.anyFileSynchronizing(FileMenuFilter.java:486)
    at com.owncloud.android.files.FileMenuFilter.filter(FileMenuFilter.java:194)
    at com.owncloud.android.files.FileMenuFilter.filter(FileMenuFilter.java:126)
    at com.owncloud.android.ui.preview.PreviewImageFragment.onPrepareOptionsMenu(PreviewImageFragment.java:378)
    at androidx.fragment.app.Fragment.performPrepareOptionsMenu(Fragment.java:3253)
    at androidx.fragment.app.FragmentManager.dispatchPrepareOptionsMenu(FragmentManager.java:3051)
    at androidx.fragment.app.FragmentManager$2.onPrepareMenu(FragmentManager.java:466)
    at androidx.core.view.MenuHostHelper.onPrepareMenu(MenuHostHelper.java:63)
    at androidx.activity.ComponentActivity.onPrepareOptionsMenu(ComponentActivity.java:497)
    at android.app.Activity.onPreparePanel(Activity.java:4364)
    at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
    at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3148)
    at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:1936)
    at androidx.appcompat.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:2190)
    at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:273)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
    at android.view.Choreographer.doCallbacks(Choreographer.java:866)
    at android.view.Choreographer.doFrame(Choreographer.java:792)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8663)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210051`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `d2s`
* Model: `SM-N975F`
* Id: `SP1A.210812.016`
* Product: `d2seea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `N975FXXS7HVD6`

### Android version

12

### Device brand and model

Samsung Note 10 +

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

Dr. Ketan Rom (Stock Root)

### Nextcloud server version

24

### Using a reverse proxy?

Yes

**Comment by DistortedBit** [comment]
Can reproduce it in 3.21.0.
