### ISSUE TITLE
App crash while scrolling in gallery

### ISSUE THREAD

**Issue by NicolasGoeddel** [nextcloud/android#10614]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [x] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Scroll in gallery

### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Fragment already added: GalleryFragmentBottomSheetDialog{b9940e} (fe49547d-4215-42bf-ba11-81e50c834619 tag=data)
    at androidx.fragment.app.FragmentStore.addFragment(FragmentStore.java:92)
    at androidx.fragment.app.FragmentManager.addFragment(FragmentManager.java:1472)
    at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:387)
    at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:1956)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1864)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1814)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1751)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:538)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210090`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `raven`
* Model: `Pixel 6 Pro`
* Id: `SQ3A.220705.003`
* Product: `raven`

### Firmware
* SDK: `32`
* Release: `12`
* Incremental: `8671607`

### Actual behaviour

Filling in a bug report on my Phone os annoyong

### Android version

12

### Device brand and model

Pixel 6 pro

### Stock or custom OS?

Stock

### Nextcloud android app version

Latest

### Nextcloud server version

Dont know

### Using a reverse proxy?

I don't know

**Comment by joshtrichards** [comment]
FIxed in #10834
