### ISSUE TITLE
NC Client crash in media / gallery 

### ISSUE THREAD

**Issue by weinic** [nextcloud/android#10612]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [ ] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [x] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke interface method 'com.owncloud.android.datamodel.FileDataStorageManager com.owncloud.android.ui.fragment.FileFragment$ContainerActivity.getStorageManager()' on a null object reference
    at com.owncloud.android.ui.fragment.GalleryFragment.runGallerySearchTask(GalleryFragment.java:293)
    at com.owncloud.android.ui.fragment.GalleryFragment.searchCompleted(GalleryFragment.java:243)
    at com.owncloud.android.ui.asynctasks.GallerySearchTask.onPostExecute(GallerySearchTask.java:123)
    at com.owncloud.android.ui.asynctasks.GallerySearchTask.onPostExecute(GallerySearchTask.java:48)
    at android.os.AsyncTask.finish(AsyncTask.java:755)
    at android.os.AsyncTask.access$900(AsyncTask.java:192)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7697)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210090`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OnePlus5`
* Model: `ONEPLUS A5000`
* Id: `QKQ1.191014.012`
* Product: `OnePlus5`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `2010292059`

### Expected behaviour

I just looked at pictures on one account under media, then I switched to another account and then the NC client crashed.

### Actual behaviour

Not

### Android version

10

### Device brand and model

oneplus5

### Stock or custom OS?

Stock

### Nextcloud android app version

shortly before 3.21.0

### Nextcloud server version

22

### Using a reverse proxy?

No

**Comment by joshtrichards** [comment]
Should be fixed by #13074
