### ISSUE TITLE
Crash on upload of several pics

### ISSUE THREAD

**Issue by sunagui** [nextcloud/android#10626]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Have more than 10,000 pics of 2mb average in DCIM phone folder.

Select folder for upload to nextcloud server

Nextcloud app shows insufficient storage on device, would you like to move them to nextcloud folder => select yes

After about 5 seconds, app crashes.

### Expected behaviour

Move files to nextcloud folder and begin upload to nextcloud server.

### Actual behaviour

See reproduce steps above.

### Android version

12

### Device brand and model

Samsung SM-S901U

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.0

### Nextcloud server version

24.0.3

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1248384 bytes
    at android.app.ActivityClient.finishActivity(ActivityClient.java:156)
    at android.app.Activity.finish(Activity.java:6586)
    at android.app.Activity.finish(Activity.java:6620)
    at com.owncloud.android.ui.activity.UploadFilesActivity.onConfirmation(UploadFilesActivity.java:668)
    at com.owncloud.android.ui.dialog.ConfirmationDialogFragment.lambda$onCreateDialog$0$com-owncloud-android-ui-dialog-ConfirmationDialogFragment(ConfirmationDialogFragment.java:137)
    at com.owncloud.android.ui.dialog.ConfirmationDialogFragment$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
    at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8669)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: Exception in thread "main" android.os.TransactionTooLargeException: data parcel size 1248384 bytes
    at android.os.BinderProxy.transactNative(Native Method)
    at android.os.BinderProxy.transact(BinderProxy.java:635)
    at android.app.IActivityClientController$Stub$Proxy.finishActivity(IActivityClientController.java:1557)
    at android.app.ActivityClient.finishActivity(ActivityClient.java:153)
    at android.app.Activity.finish(Activity.java:6586)
    at android.app.Activity.finish(Activity.java:6620)
    at com.owncloud.android.ui.activity.UploadFilesActivity.onConfirmation(UploadFilesActivity.java:668)
    at com.owncloud.android.ui.dialog.ConfirmationDialogFragment.lambda$onCreateDialog$0$com-owncloud-android-ui-dialog-ConfirmationDialogFragment(ConfirmationDialogFragment.java:137)
    at com.owncloud.android.ui.dialog.ConfirmationDialogFragment$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
    at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8669)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210090`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `r0q`
* Model: `SM-S901U`
* Id: `SP1A.210812.016`
* Product: `r0qsqw`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `S901USQU2AVG6`

**Comment by deinhofer** [comment]
I have a similar problem:

I select several Fotos in the Google Fotos App, then select sharing, next loud, folder...
The the upload starts and stops after some files, e.g. 4/15.
I have a motorola g100, Android 12, but the same also happened with my older G7, Android 11.

There are also many other similar issues to that, so maybe the cause is the same?

**Comment by joshtrichards** [comment]
Similar to #10242

**Comment by joshtrichards** [comment]
Fixed in #13336
