### ISSUE TITLE
Crash log

### ISSUE THREAD

**Issue by jpurdy647** [nextcloud/android#10668]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Opened nextcloud after writing a md note

### Expected behaviour

Didn't expect a crash

### Actual behaviour

Crashed

### Android version

12

### Device brand and model

Pixel 4xl

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.0

### Nextcloud server version

24.0.2

### Using a reverse proxy?

Yes

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.lib.common.Template.getExtension()' on a null object reference
    at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment.checkEnablingCreateButton(ChooseTemplateDialogFragment.kt:263)
    at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment.access$checkEnablingCreateButton(ChooseTemplateDialogFragment.kt:71)
    at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment$onCreateDialog$2.afterTextChanged(ChooseTemplateDialogFragment.kt:162)
    at android.widget.TextView.sendAfterTextChanged(TextView.java:10805)
    at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:13820)
    at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1278)
    at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:578)
    at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:314)
    at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
    at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:304)
    at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:48)
    at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:941)
    at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:712)
    at android.view.inputmethod.InputConnectionWrapper.setComposingText(InputConnectionWrapper.java:165)
    at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:633)
    at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:111)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210090`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `coral`
* Model: `Pixel 4 XL`
* Id: `SQ3A.220705.003.A1`
* Product: `coral`

### Firmware
* SDK: `32`
* Release: `12`
* Incremental: `8672226`

**Comment by AlvaroBrey** [comment]
Repro steps:

1. Have phone in airplane mode
2. Open Nextcloud app
3. Tap '+' FAB
4. Tap "create new text document"
5. Type any character
