### ISSUE TITLE
Magenta Cloud didnt load

### ISSUE THREAD

**Issue by A5SAS5IN** [nextcloud/android#10673]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

na.

### Expected behaviour

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.t_systems.android.webdav/com.owncloud.android.authentication.AuthenticatorActivity}: android.view.InflateException: Binary XML file line #10 in com.t_systems.android.webdav:layout/account_setup_webview: Binary XML file line #10 in com.t_systems.android.webdav:layout/account_setup_webview: Error inflating class android.webkit.WebView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3640)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3797)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2215)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:346)
	at android.os.Looper.loop(Looper.java:475)
	at android.app.ActivityThread.main(ActivityThread.java:7890)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
Caused by: android.view.InflateException: Binary XML file line #10 in com.t_systems.android.webdav:layout/account_setup_webview: Binary XML file line #10 in com.t_systems.android.webdav:layout/account_setup_webview: Error inflating class android.webkit.WebView
Caused by: android.view.InflateException: Binary XML file line #10 in com.t_systems.android.webdav:layout/account_setup_webview: Error inflating class android.webkit.WebView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
	at android.view.LayoutInflater.createView(LayoutInflater.java:780)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:934)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:954)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at com.owncloud.android.databinding.AccountSetupWebviewBinding.inflate(AccountSetupWebviewBinding.java:50)
	at com.owncloud.android.databinding.AccountSetupWebviewBinding.inflate(AccountSetupWebviewBinding.java:44)
	at com.owncloud.android.authentication.AuthenticatorActivity.onCreate(AuthenticatorActivity.java:316)
	at android.app.Activity.performCreate(Activity.java:8050)
	at android.app.Activity.performCreate(Activity.java:8030)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1330)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3613)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3797)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2215)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:346)
	at android.os.Looper.loop(Looper.java:475)
	at android.app.ActivityThread.main(ActivityThread.java:7890)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
Caused by: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process com.t_systems.android.webdav (pid 11458), lock owner  unknown
	at org.chromium.android_webview.AwDataDirLock.b(chromium-TrichromeWebViewGoogle6432.aab-stable-511209734:106)
	at org.chromium.android_webview.AwBrowserProcess.j(chromium-TrichromeWebViewGoogle6432.aab-stable-511209734:142)
	at com.android.webview.chromium.b1.d(chromium-TrichromeWebViewGoogle6432.aab-stable-511209734:228)
	at com.android.webview.chromium.b1.b(chromium-TrichromeWebViewGoogle6432.aab-stable-511209734:347)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.n(chromium-TrichromeWebViewGoogle6432.aab-stable-511209734:321)
	at com.android.webview.chromium.WebViewChromium.init(chromium-TrichromeWebViewGoogle6432.aab-stable-511209734:302)
	at android.webkit.WebView.<init>(WebView.java:443)
	at android.webkit.WebView.<init>(WebView.java:363)
	at android.webkit.WebView.<init>(WebView.java:345)
	at android.webkit.WebView.<init>(WebView.java:332)
	... 32 more

************ APP INFORMATION ************
ID: com.t_systems.android.webdav
Version: 7197 (build #9243)
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Sony
Device: XQ-CT54
Model: XQ-CT54
Id: 64.0.A.8.25
Product: XQ-CT54_EEA

************ FIRMWARE ************
SDK: 31
Release: 12
Incremental: 064000A008002502034367672

### Actual behaviour

Magenta Cloud sonst load

### Android version

12.0

### Device brand and model

Xperia 1 IV

### Stock or custom OS?

Stock

### Nextcloud android app version

na

### Nextcloud server version

na

### Using a reverse proxy?

No

**Comment by AndyScherzinger** [comment]
Usually points to an old,  buggy webview shipped by Android itself. Can you try to install https://play.google.com/store/apps/details?id=com.google.android.webview reboot the phone and try again?
