### ISSUE TITLE
Crash after clearing cache and storage with active nextcloud file conflict notifications

### ISSUE THREAD

**Issue by chadclancy** [nextcloud/android#10680]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Modify exif data of any photo which has already been uploaded to nextcloud.
2. "Upload only on wifi/charging" option probably has to be set.
3. Reconnect to wifi or charger to trigger auto sync
4. Leave android notifications about conflicting files active in notification drawer.
5. Erase app data and cache.
6. Reopen app from app drawer.

### Expected behaviour

App should not crash.

### Actual behaviour

App crashed and asked me if I'd like to submit a bug report.

### Android version

12

### Device brand and model

Samsung galaxy fold 3

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.0

### Nextcloud server version

23.0.8

### Using a reverse proxy?

Yes

### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException
    at com.owncloud.android.ui.activities.ActivitiesActivity$$ExternalSyntheticLambda0.get(Unknown Source:2)
    at com.nextcloud.java.util.Optional.orElseThrow(Optional.java:309)
    at com.owncloud.android.ui.activity.FileDisplayActivity$8.run(FileDisplayActivity.java:2024)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8669)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210090`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `q2q`
* Model: `SM-F926U1`
* Id: `SP1A.210812.016`
* Product: `q2quew`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `F926U1UES1DVG3`

**Comment by joshtrichards** [comment]
Fixed by #11518
