### ISSUE TITLE
3.21.1 crashes on background uploads

### ISSUE THREAD

**Issue by dbline** [nextcloud/android#10692]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Having the phone on.... 

### Expected behaviour

It should not throw traceback errors. 

### Cause of error
```java
Exception in thread "Thread-6" android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.nextcloud.client/com.owncloud.android.files.services.FileUploader
    at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
    at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
    at android.os.Parcel.readParcelableInternal(Parcel.java:4772)
    at android.os.Parcel.readParcelable(Parcel.java:4740)
    at android.os.Parcel.createExceptionOrNull(Parcel.java:3006)
    at android.os.Parcel.createException(Parcel.java:2995)
    at android.os.Parcel.readException(Parcel.java:2978)
    at android.os.Parcel.readException(Parcel.java:2920)
    at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:5302)
    at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1894)
    at android.app.ContextImpl.startForegroundService(ContextImpl.java:1870)
    at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
    at com.owncloud.android.files.services.FileUploader.retryUpload(FileUploader.java:1051)
    at com.owncloud.android.files.services.FileUploader.retryFailedUploads(FileUploader.java:1095)
    at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:240)
    at com.owncloud.android.utils.FilesSyncHelper$$ExternalSyntheticLambda0.run(Unknown Source:10)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210190`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `redfin`
* Model: `Pixel 5`
* Id: `TP1A.220624.014`
* Product: `redfin`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `8819323`

### Android version

12 and 13 both 

### Device brand and model

Google pixel 5,. Pixel 2

### Stock or custom OS?

Stock

### Nextcloud android app version

Don't know 

### Nextcloud server version

Don't know 

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "Thread-6" android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.nextcloud.client/com.owncloud.android.files.services.FileUploader
    at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
    at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
    at android.os.Parcel.readParcelableInternal(Parcel.java:4772)
    at android.os.Parcel.readParcelable(Parcel.java:4740)
    at android.os.Parcel.createExceptionOrNull(Parcel.java:3006)
    at android.os.Parcel.createException(Parcel.java:2995)
    at android.os.Parcel.readException(Parcel.java:2978)
    at android.os.Parcel.readException(Parcel.java:2920)
    at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:5302)
    at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1894)
    at android.app.ContextImpl.startForegroundService(ContextImpl.java:1870)
    at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
    at com.owncloud.android.files.services.FileUploader.retryUpload(FileUploader.java:1051)
    at com.owncloud.android.files.services.FileUploader.retryFailedUploads(FileUploader.java:1095)
    at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:240)
    at com.owncloud.android.utils.FilesSyncHelper$$ExternalSyntheticLambda0.run(Unknown Source:10)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210190`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `redfin`
* Model: `Pixel 5`
* Id: `TP1A.220624.014`
* Product: `redfin`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `8819323`

### Server error logs

```bash
Don't have
```

### Additional information

This started happening immediately after the last automatic update through Google Play.

**Comment by AlvaroBrey** [comment]
Likely a consequence of #9997 , cc @tobiasKaminsky

**Comment by AlvaroBrey** [comment]
Investigating ASAP. Possible remediation: clear upload queue, disable autoupload.

**Comment by AlvaroBrey** [comment]
Another possible remediation: disable battery optimization for the app

**Comment by AlvaroBrey** [comment]
Released 3.22.2 yesterday to patch this

**Comment by ksapp-dell** [comment]
Hi, 
Version 3.21.2 ja still crashing

### Cause of error
```java
Exception in thread "Thread-7" java.lang.RuntimeException: javax.net.ssl.SSLException: Unable to create application data
    at org.conscrypt.ConscryptEngine.newSsl(ConscryptEngine.java:209)
    at org.conscrypt.ConscryptEngine.<init>(ConscryptEngine.java:200)
    at org.conscrypt.ConscryptEngineSocket.newEngine(ConscryptEngineSocket.java:114)
    at org.conscrypt.ConscryptEngineSocket.<init>(ConscryptEngineSocket.java:101)
    at org.conscrypt.Java8EngineSocket.<init>(Java8EngineSocket.java:61)
    at org.conscrypt.Platform.createEngineSocket(Platform.java:606)
    at org.conscrypt.OpenSSLSocketFactoryImpl.createSocket(OpenSSLSocketFactoryImpl.java:161)
    at okhttp3.internal.connection.ConnectPlan.connectTlsEtc(ConnectPlan.kt:174)
    at okhttp3.internal.connection.FastFallbackExchangeFinder.find(FastFallbackExchangeFinder.kt:78)
    at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:267)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:65)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
    at okhttp3.internal.connection.RealCall.execute(RealCall.kt:158)
    at com.nextcloud.common.OkHttpMethodBase.execute(OkHttpMethodBase.kt:171)
    at com.nextcloud.client.network.ConnectivityServiceImpl.isInternetWalled(ConnectivityServiceImpl.java:81)
    at com.owncloud.android.files.services.FileUploader.retryFailedUploads(FileUploader.java:1093)
    at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:240)
    at com.owncloud.android.utils.FilesSyncHelper$$ExternalSyntheticLambda0.run(Unknown Source:10)
    at java.lang.Thread.run(Thread.java:764)
Caused by: Exception in thread "Thread-7" javax.net.ssl.SSLException: Unable to create application data
    at org.conscrypt.NativeCrypto.SSL_new(Native Method)
    at org.conscrypt.NativeSsl.newInstance(NativeSsl.java:79)
    at org.conscrypt.ConscryptEngine.newSsl(ConscryptEngine.java:207)
    at org.conscrypt.ConscryptEngine.<init>(ConscryptEngine.java:200)
    at org.conscrypt.ConscryptEngineSocket.newEngine(ConscryptEngineSocket.java:114)
    at org.conscrypt.ConscryptEngineSocket.<init>(ConscryptEngineSocket.java:101)
    at org.conscrypt.Java8EngineSocket.<init>(Java8EngineSocket.java:61)
    at org.conscrypt.Platform.createEngineSocket(Platform.java:606)
    at org.conscrypt.OpenSSLSocketFactoryImpl.createSocket(OpenSSLSocketFactoryImpl.java:161)
    at okhttp3.internal.connection.ConnectPlan.connectTlsEtc(ConnectPlan.kt:174)
    at okhttp3.internal.connection.FastFallbackExchangeFinder.find(FastFallbackExchangeFinder.kt:78)
    at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:267)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:65)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
    at okhttp3.internal.connection.RealCall.execute(RealCall.kt:158)
    at com.nextcloud.common.OkHttpMethodBase.execute(OkHttpMethodBase.kt:171)
    at com.nextcloud.client.network.ConnectivityServiceImpl.isInternetWalled(ConnectivityServiceImpl.java:81)
    at com.owncloud.android.files.services.FileUploader.retryFailedUploads(FileUploader.java:1093)
    at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:240)
    at com.owncloud.android.utils.FilesSyncHelper$$ExternalSyntheticLambda0.run(Unknown Source:10)
    at java.lang.Thread.run(Thread.java:764)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210290`
* Build flavor: `generic`

### Device information
* Brand: `samsung`
* Device: `herolte`
* Model: `SM-G930F`
* Id: `R16NW`
* Product: `heroltexx`

### Firmware
* SDK: `26`
* Release: `8.0.0`
* Incremental: `G930FXXU8ETI2`

**Comment by AlvaroBrey** [comment]
@ksapp-dell that is a different crash, please feel free to open a new issue
