### ISSUE TITLE
Crash when renaming a .md file in a group folder

### ISSUE THREAD

**Issue by Lapotor** [nextcloud/android#10702]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Get a group folder
2. Get a .md File
3. Try to rename it

### Expected behaviour

The File should get a renamed.

### Actual behaviour

The Android App crash

### Android version

13

### Device brand and model

Google Pixel 6 Pro

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.2

### Nextcloud server version

24.0.3

### Using a reverse proxy?

I don't know

#### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.lib.common.operations.RemoteOperationResult.isSuccess()' on a null object reference
    at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:353)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoteOperationFinish(FileDisplayActivity.java:1678)
    at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:778)
    at com.owncloud.android.services.OperationsService$$ExternalSyntheticLambda0.run(Unknown Source:6)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7898)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

#### App information
* ID: `com.nextcloud.client`
* Version: `30210290`
* Build flavor: `gplay`

#### Device information
* Brand: `google`
* Device: `raven`
* Model: `Pixel 6 Pro`
* Id: `TP1A.220624.021`
* Product: `raven`

#### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `8877034`

### Additional information

Using Hetzner Storage Share.

**Comment by joshtrichards** [comment]
Does this occur for you outside of groupfolders?

If so, are you able to test it against your server with the groupfolders app disabled?

**Comment by joshtrichards** [comment]
Related: 

- #10444 
- #10465

Potential duplicates but leaving open pending additional information gathering for now:

- #10290 
- #10553

**Comment by Lapotor** [comment]
With the App Version `3.26.0` i don't see that happening anymore.
Tested it in a group folder and outside both works fine on my end.
