### ISSUE TITLE
StringIndexOutOfBoundsException when opening a JPG in PreviewImageFragment.onPrepareOptionsMenu

### ISSUE THREAD

**Issue by applefire229** [nextcloud/android#10746]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

```
************ CAUSE OF ERROR ************

java.lang.StringIndexOutOfBoundsException: length=20; index=-1
	at java.lang.String.substring(String.java:2023)
	at com.owncloud.android.utils.MimeTypeUtil.isJpgOrPngFile(MimeTypeUtil.java:242)
	at com.owncloud.android.ui.preview.PreviewImageFragment.onPrepareOptionsMenu(PreviewImageFragment.java:467)
	at androidx.fragment.app.Fragment.performPrepareOptionsMenu(Fragment.java:3144)
	at androidx.fragment.app.FragmentManager.dispatchPrepareOptionsMenu(FragmentManager.java:2923)
	at androidx.fragment.app.FragmentController.dispatchPrepareOptionsMenu(FragmentController.java:414)
	at androidx.fragment.app.FragmentActivity.onPreparePanel(FragmentActivity.java:447)
	at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3149)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:459)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
	at android.view.Choreographer.doFrame(Choreographer.java:740)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

************ APP INFORMATION ************
ID: com.t_systems.android.webdav
Version: 7197 (build #9243)
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: gta3xlwifi
Model: SM-T510
Id: RP1A.200720.012
Product: gta3xlwifieea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: T510XXU5CVG2
```

### Expected behaviour

jpeg should open after selecting by "click"

### Actual behaviour

Bug-report is displayed

### Android version

Android 11

### Device brand and model

Brand: samsung Device: gta3xlwifi

### Stock or custom OS?

Stock

### Nextcloud android app version

7.00.406

### Nextcloud server version

RP1a.200720.012

### Using a reverse proxy?

I don't know

### Android logs

```
************ CAUSE OF ERROR ************

java.lang.StringIndexOutOfBoundsException: length=20; index=-1
	at java.lang.String.substring(String.java:2023)
	at com.owncloud.android.utils.MimeTypeUtil.isJpgOrPngFile(MimeTypeUtil.java:242)
	at com.owncloud.android.ui.preview.PreviewImageFragment.onPrepareOptionsMenu(PreviewImageFragment.java:467)
	at androidx.fragment.app.Fragment.performPrepareOptionsMenu(Fragment.java:3144)
	at androidx.fragment.app.FragmentManager.dispatchPrepareOptionsMenu(FragmentManager.java:2923)
	at androidx.fragment.app.FragmentController.dispatchPrepareOptionsMenu(FragmentController.java:414)
	at androidx.fragment.app.FragmentActivity.onPreparePanel(FragmentActivity.java:447)
	at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3149)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:459)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
	at android.view.Choreographer.doFrame(Choreographer.java:740)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

************ APP INFORMATION ************
ID: com.t_systems.android.webdav
Version: 7197 (build #9243)
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: gta3xlwifi
Model: SM-T510
Id: RP1A.200720.012
Product: gta3xlwifieea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: T510XXU5CVG2
```

### Server error logs

```bash
not available
```

### Additional information

.

**Comment by AlvaroBrey** [comment]
This is not a bug in Nextcloud, the method that the stacktrace refers to doesn't even exist in our code.
