### ISSUE TITLE
Unable to upload files to server. Crashes app instead.

### ISSUE THREAD

**Issue by ISlip3890** [nextcloud/android#10772]
### ⚠️ Before posting ⚠️

- [x] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Load app
2. Wait a couple of seconds for uploads to be recognised and to start uploading
3. Crashes after starting to upload.

### Expected behaviour

It should be able to upload the files without it crashing 

### Actual behaviour

When I try to upload my photos to my server, the app crashes straight after it starts to upload files.

### Android version

10

### Device brand and model

Huawei P30 Pro

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.2

### Nextcloud server version

24.0.4

### Using a reverse proxy?

No

### Cause of error

```java
Exception in thread "main" android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{9293e73 u0 com.nextcloud.client/com.owncloud.android.files.services.FileUploader}
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2540)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loop(Looper.java:219)
    at android.app.ActivityThread.main(ActivityThread.java:8668)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

```

```java
Exception in thread "FinalizerWatchdogDaemon" java.util.concurrent.TimeoutException: com.android.internal.os.BinderInternal$GcWatcher.finalize() timed out after 10 seconds
    at java.lang.ref.FinalizerReference.add(FinalizerReference.java:61)
    at com.android.internal.os.BinderInternal$GcWatcher.finalize(BinderInternal.java:63)
    at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
    at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
    at java.lang.Daemons$Daemon.run(Daemons.java:137)
    at java.lang.Thread.run(Thread.java:929)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210290`
* Build flavor: `gplay`

### Device information
* Brand: `HUAWEI`
* Device: `HWVOG`
* Model: `VOG-L09`
* Id: `HUAWEIVOG-L09`
* Product: `VOG-L09EEA`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `10.1.0.150C431`

**Comment by nimnananuk** [comment]
same issue, different device sadly cant post log, as app crashed. But log looked the same

**Comment by ISlip3890** [comment]
Inactive.
