### ISSUE TITLE
App crash while opening folder with thousands of files

### ISSUE THREAD

**Issue by GeneriumMadness** [nextcloud/android#10786]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Create folder with ~7000 files with thumbnails like photos or videos
2. Go to this folder through android client
3. The app will freeze and then crash

### Expected behaviour

Normal display of files and their thumbnails

### Actual behaviour

Crash

### Android version

11 / 13

### Device brand and model

Realme 6 pro / Google Pixel 4

### Stock or custom OS?

Stock

### Nextcloud android app version

3.21.2

### Nextcloud server version

24.0.5

### Using a reverse proxy?

No

### Android logs

-

### Server error logs

```bash
-
```

### Additional information

Unable to post client logs because my app is not dev or beta and also the app crashes without any log. It just went to desktop.
Possible solution: get a list of files partly. I think it tries to get 7000 http requests for previews at the same time.

**Comment by AlvaroBrey** [comment]
Thanks for your report. However not much we can do in this case without a crash log.  Instructions to get a log (even if not a dev or beta version) here: https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat-mag

**Comment by GeneriumMadness** [comment]
How to get NC logs without PC?

**Comment by nursoda** [comment]
Just experienced a crash deleting a screenshot in preview mode within a folder wIth MANY pics.

Cannot provide logs seither as when the Android dialog asked to report the crash, the GitHub app was offered to report it, too, and I clicked that and landed in a "what kind if report" selection (all open in Browser links). I cannot get back to the the Android crash dialog.

**Comment by nursoda** [comment]
OK, I deleted another picture and copied the stacktrace:
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.services.OperationsService$OperationsServiceBinder.isSynchronizing(OperationsService.java:372)
    at com.owncloud.android.files.FileMenuFilter.anyFileSynchronizing(FileMenuFilter.java:532)
    at com.owncloud.android.files.FileMenuFilter.anyFileSynchronizing(FileMenuFilter.java:521)
    at com.owncloud.android.files.FileMenuFilter.filter(FileMenuFilter.java:201)
    at com.owncloud.android.files.FileMenuFilter.filter(FileMenuFilter.java:133)
    at com.owncloud.android.ui.preview.PreviewImageFragment.onPrepareOptionsMenu(PreviewImageFragment.java:381)
    at androidx.fragment.app.Fragment.performPrepareOptionsMenu(Fragment.java:3253)
    at androidx.fragment.app.FragmentManager.dispatchPrepareOptionsMenu(FragmentManager.java:3051)
    at androidx.fragment.app.FragmentManager$2.onPrepareMenu(FragmentManager.java:466)
    at androidx.core.view.MenuHostHelper.onPrepareMenu(MenuHostHelper.java:63)
    at androidx.activity.ComponentActivity.onPrepareOptionsMenu(ComponentActivity.java:497)
    at android.app.Activity.onPreparePanel(Activity.java:4372)
    at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
    at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3148)
    at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:1936)
    at androidx.appcompat.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:2190)
    at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:273)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
    at android.view.Choreographer.doCallbacks(Choreographer.java:899)
    at android.view.Choreographer.doFrame(Choreographer.java:827)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7904)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ExecInit.main(ExecInit.java:49)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210290`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `bluejay`
* Model: `Pixel 6a`
* Id: `TP1A.221005.003`
* Product: `bluejay`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `2022100300`

**Comment by AlvaroBrey** [comment]
@nursoda that's #10580, will be fixed in next release

**Comment by nursoda** [comment]
I can no longer reproduc this issue. OP?

**Comment by GeneriumMadness** [comment]
It crashed the first time, but then everything was fine except several times of freezes. It seems now after loading the cache the application has stopped crashing.
