### ISSUE TITLE
ci: Frequent failures of `displayJavaSnippetFile`

### ISSUE THREAD

**Issue by AlvaroBrey** [nextcloud/android#10818]
Fails on both stable and master.  Runs fine locally when running just the `PreviewTextFileFragmentTest` class.

See for example: https://www.kaminsky.me/nc-dev/android-integrationTests/6312-IT-stable-11-54/. Trace:

```
java.lang.IllegalStateException: cache is closed
at com.jakewharton.disklrucache.DiskLruCache.checkNotClosed(DiskLruCache.java:614)
at com.jakewharton.disklrucache.DiskLruCache.get(DiskLruCache.java:405)
at com.owncloud.android.ui.adapter.DiskLruImageCache.getBitmap(DiskLruImageCache.java:162)
at com.owncloud.android.datamodel.ThumbnailsCacheManager.getBitmapFromDiskCache(ThumbnailsCacheManager.java:251)
at com.owncloud.android.utils.DisplayUtils.setAvatar(DisplayUtils.java:503)
at com.owncloud.android.utils.DisplayUtils.setAvatar(DisplayUtils.java:469)
at com.owncloud.android.utils.DisplayUtils.setAvatar(DisplayUtils.java:455)
at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2399)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
at androidx.test.runner.MonitoringInstrumentation.callActivityOnStart(MonitoringInstrumentation.java:742)
at android.app.Activity.performStart(Activity.java:7029)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Looks like it started failing in CI after #10079 was merged. May be related, cc @tobiasKaminsky

**Comment by AlvaroBrey** [comment]
Caused by https://github.com/nextcloud/android/blob/06ddf3ec4d217369589ad5be2246c65d85ba0465/app/src/androidTest/java/com/owncloud/android/ui/fragment/GalleryFragmentIT.kt#L63-L63.

Clearing the cache also closes it, so it remains closed for the rest of the tests as it's a static variable. Commenting this out makes `displayJavaSnippetFile` work.

Also, GalleryFragmentIT does not work when run by itself.
