### ISSUE TITLE
crash report popup possible after connection to wifi [OOM] near `okhttp3.internal.concurrent`

### ISSUE THREAD

**Issue by stebe** [nextcloud/android#10821]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

App was running in the background when crash popped up 

### Expected behaviour

Nothing expected

### Actual behaviour

Something went wrong I wasn't actively using the application 

### Android version

12

### Device brand and model

samsung SM-G990W

### Stock or custom OS?

Stock

### Nextcloud android app version

30210290

### Nextcloud server version

24.06

### Using a reverse proxy?

Yes

### Cause of error
```java
Exception in thread "OkHttp TaskRunner" java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 4098048 free bytes and 4002KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
    at java.util.ArrayList.iterator(ArrayList.java:834)
    at okhttp3.internal.concurrent.TaskRunner.awaitTaskToRun(TaskRunner.kt:168)
    at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:60)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210290`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `r9q`
* Model: `SM-G990W`
* Id: `SP1A.210812.016`
* Product: `r9qcsx`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `G990WVLS4CVIB`

### Additional information

This has just had happened before but cannot pinpoint cause.

**Comment by Seb3thehacker** [comment]
Issue for me too, but a 16 bit allocation is the issue. App broken completely.

**Comment by dreamwayjgs** [comment]
I have same issue too. It can happen any time using the app. I encountered this error opening folders, entering settings, creating auto uploading folders, and so on.

Device: Samsung SM-G975N (S10+), Android 12
