### ISSUE TITLE
App crashes on entering ip address.

### ISSUE THREAD

**Issue by Pravi21** [nextcloud/android#10868]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Install the app. 
Open the app.
Type in the IP address of local server.
The app crashes.

### Expected behaviour

The app should take you to the login page.

### Actual behaviour

The app crashes and unable to login to the server. This problem is seen in version 3.22.0 and the latest 3.22.1

### Android version

Android 10

### Device brand and model

Poco F1

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.1

### Nextcloud server version

24.0.6

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.LinearLayout com.owncloud.android.databinding.SslUntrustedCertLayoutBinding.getRoot()' on a null object reference
    at com.owncloud.android.ui.dialog.SslUntrustedCertDialog.onCreateDialog(SslUntrustedCertDialog.java:173)
    at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:665)
    at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:579)
    at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1752)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:493)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:224)
    at android.app.ActivityThread.main(ActivityThread.java:7562)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30220190`
* Build flavor: `gplay`

### Device information
* Brand: `Xiaomi`
* Device: `beryllium`
* Model: `POCO F1`
* Id: `QKQ1.190828.002`
* Product: `beryllium`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `V12.0.3.0.QEJMIXM`

### Additional information

I am not able to login to my server from android phones.

**Comment by domhaas** [comment]
Can confirm this bug.
Pixel5 with GrapheneOS latest (Android 13).

**Comment by AlvaroBrey** [comment]
Fix is in #10877, this should only crash for those of you using self-signed or invalid server certificates.

**Comment by Pravi21** [comment]
Can we expect a fix release today or anytime soon? We are unable to login to the server.

**Comment by AlvaroBrey** [comment]
Release 3.22.2 has just been published here on Github and submitted to Google Play, where it should be made available in some hours. It contains a fix for this issue.

**Comment by domhaas** [comment]
> Release 3.22.2 has just been published here on Github and submitted to Google Play, where it should be made available in some hours. It contains a fix for this issue.

thanks!
working as expected again.
