### ISSUE TITLE
Conflicts and crash after Android upgrade

### ISSUE THREAD

**Issue by kleag** [nextcloud/android#10872]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Synchronize several GB of photos
2. Upgrade Android and NC app

### Expected behaviour

Nothing happens

### Actual behaviour

All the GB of photos start to be uploaded again, with a conflict on each. The app crashes a lot.
This is not manageable. Even after disabling synchronization in settings, it continues.

I know there is a lot of existing bug reports around synchronization issues but I was not able to find one similar to this one.

### Android version

11

### Device brand and model

fairphone 3

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.0

### Nextcloud server version

24.0.6

### Using a reverse proxy?

No

### Android logs

-

### Server error logs

```bash
-
```

### Additional information

I am not able to retrieve logs.

**Comment by ninjasan420** [comment]
```
Same, log

### Cause of error
```java
Exception in thread "main" java.lang.ClassCastException: com.owncloud.android.ui.adapter.OCFileListGridImageViewHolder cannot be cast to com.owncloud.android.ui.adapter.ListGridImageViewHolder
    at com.owncloud.android.ui.adapter.OCFileListAdapter.onBindViewHolder(OCFileListAdapter.java:362)
    at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
    at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
    at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
    at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:572)
    at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
    at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
    at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
    at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
    at android.view.View.layout(View.java:23554)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:689)
    at android.view.View.layout(View.java:23554)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
    at android.view.View.layout(View.java:23554)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23554)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
    at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1818)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1584)
    at android.view.View.layout(View.java:23554)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
    at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
    at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2227)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
    at android.view.View.layout(View.java:23554)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
    at android.view.View.layout(View.java:23554)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23554)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23554)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23554)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
    at android.view.View.layout(View.java:23554)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at com.android.internal.policy.DecorView.onLayout(DecorView.java:865)
    at android.view.View.layout(View.java:23554)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3849)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3299)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2263)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8984)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1144)
    at android.view.Choreographer.doCallbacks(Choreographer.java:948)
    at android.view.Choreographer.doFrame(Choreographer.java:877)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1129)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:210)
    at android.os.Looper.loop(Looper.java:299)
    at android.app.ActivityThread.main(ActivityThread.java:8168)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30220090`
* Build flavor: `gplay`

### Device information
* Brand: `Redmi`
* Device: `sweet`
* Model: `M2101K6G`
* Id: `SKQ1.210908.001`
* Product: `sweet_eea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `V13.0.13.0.SKFEUXM`
```

**Comment by AlvaroBrey** [comment]
@ninjasan420 that is #10825, update your app. unrelated to conflicts.

**Comment by AlvaroBrey** [comment]
@kleag  thanks for your report. Can you get a logcat from the Android device so we can see if there's any errors? Instructions here: https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat-mag

Feel free to search and replace the server URL, username and other file names in the output.

**Comment by bdevy** [comment]
I think I'm having this problem as well. I'm running Nextcloud Server 25.0.0 with Android App version 3.22.2 (Galaxy S21 5G). I have Auto Upload on my Android configured to upload and move original files to the app folder. This has worked flawlessly in the past, but I recently noticed (sometime after upgrading to NC 25.0.0 and/or upgrading the Android App to 3.22.2) that while photos still upload to NC, they aren't "moved" to the app directory - so they exist in both the original location and the NC App directory. These photos are piling up as conflicts because now they exist twice - I can manually resolve the conflicts by choosing which file to keep, but that's not really a sustainable method.

I couldn't find any other similar issues. If my issue isn't relevant here please direct me to the relevant issue, otherwise I can create a bug report as well if it doesn't yet exist. Let me know how else I can help.
