### ISSUE TITLE
Server certificate not trustworthy - app crash when opened

### ISSUE THREAD

**Issue by ToHeld** [nextcloud/android#10906]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Notification: upload failed, due to certificate 
2. Open App, 
3. wait a few seconds looking at your top level directory, 
4. crash

### Expected behaviour

Ignore certificate 

### Actual behaviour

Failed upload and crash when opened app

### Android version

11

### Device brand and model

Fairphone 4

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.1 (October 20, 2022)

### Nextcloud server version

24.0.5

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.LinearLayout com.owncloud.android.databinding.SslUntrustedCertLayoutBinding.getRoot()' on a null object reference
    at com.owncloud.android.ui.dialog.SslUntrustedCertDialog.onCreateDialog(SslUntrustedCertDialog.java:173)
    at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:665)
    at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:579)
    at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1752)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:493)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7715)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30220190`
* Build flavor: `gplay`

### Device information
* Brand: `Fairphone`
* Device: `FP4`
* Model: `FP4`
* Id: `RKQ1.210503.001`
* Product: `FP4eea`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `FP4G`

### Additional information

First ever bug report. Feedback is welcome :)

**Comment by AlvaroBrey** [comment]
Duplicate of #10868
