### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by sebastiencastermans** [nextcloud/android#10945]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

...

### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: ScrollView can host only one direct child
    at android.widget.ScrollView.addView(ScrollView.java:371)
    at com.google.android.material.snackbar.BaseTransientBottomBar$SnackbarBaseLayout.addToTargetParent(BaseTransientBottomBar.java:1275)
    at com.google.android.material.snackbar.BaseTransientBottomBar.showView(BaseTransientBottomBar.java:715)
    at com.google.android.material.snackbar.BaseTransientBottomBar$1.handleMessage(BaseTransientBottomBar.java:244)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loopOnce(Looper.java:233)
    at android.os.Looper.loop(Looper.java:344)
    at android.app.ActivityThread.main(ActivityThread.java:8212)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30220290`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OnePlus8Pro`
* Model: `IN2023`
* Id: `RKQ1.211119.001`
* Product: `OnePlus8Pro_EEA`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `Q.GDPR.202208261325`

### Actual behaviour

...

### Android version

12

### Device brand and model

OnePlus 8 Pro

### Stock or custom OS?

Stock

### Nextcloud android app version

..

### Nextcloud server version

..

### Using a reverse proxy?

No

**Comment by AlvaroBrey** [comment]
@sebastiencastermans Please fill in the required fields instead of just inputting `..`
