### ISSUE TITLE
Nextcloud App crashes

### ISSUE THREAD

**Issue by weinic** [nextcloud/android#10971]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Go to the media tab
2. Change the media folder (i changed to my folder named SMB / this is a external files smb integration.
3. I opend a picture (view, not download or other) and then the NC App crashes

### Expected behaviour

View the picture in this folder 🤷‍♂️

### Actual behaviour

The NC app crashes from time to time.
Probably when loading / searching the folder.

I have 20 - 30 thousand pictures in it

### Android version

See Additional information

### Device brand and model

See Additional information

### Stock or custom OS?

Stock

### Nextcloud android app version

See Additional information

### Nextcloud server version

23.0.10

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Couldn't read row 682, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetString(Native Method)
    at android.database.CursorWindow.getString(CursorWindow.java:469)
    at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:53)
    at android.database.CursorWrapper.getString(CursorWrapper.java:141)
    at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:968)
    at com.owncloud.android.datamodel.FileDataStorageManager.getGalleryItems(FileDataStorageManager.java:2241)
    at com.owncloud.android.datamodel.FileDataStorageManager.getAllGalleryItems(FileDataStorageManager.java:2186)
    at com.owncloud.android.ui.preview.PreviewImagePagerAdapter.<init>(PreviewImagePagerAdapter.java:124)
    at com.owncloud.android.ui.preview.PreviewImageActivity.initViewPager(PreviewImageActivity.java:151)
    at com.owncloud.android.ui.preview.PreviewImageActivity.onStart(PreviewImageActivity.java:211)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1521)
    at android.app.Activity.performStart(Activity.java:7838)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3399)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7697)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30220352`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OnePlus5`
* Model: `ONEPLUS A5000`
* Id: `QKQ1.191014.012`
* Product: `OnePlus5`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `2010292059`

**Comment by AlvaroBrey** [comment]
Duplicate of #9948
