### ISSUE TITLE
java.lang.IllegalArgumentException when signing in with WebAuthn

### ISSUE THREAD

**Issue by martin-sucha** [nextcloud/android#10972]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Initiate login flow.
2. Enter username and password.
3. Select `WebAuthn device` for second factor.
4. Insert YubiKey that is registered with the account to USB port.
5. Click `Use Webauthn device` button. The app crashed when the WebAuthn button was pressed, at the same time the WebAuthn popup UI was briefly visible (for a fraction of a second).

### Expected behaviour

App does not crash.

### Actual behaviour

App displays the following error

﻿### Cause of error
```java
Exception in thread "main" java.lang.IllegalArgumentException: com.nextcloud.client: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
    at android.app.PendingIntent.checkFlags(PendingIntent.java:401)
    at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:671)
    at android.app.PendingIntent.getBroadcast(PendingIntent.java:658)
    at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher.requestPermissionForUsbDevice(UsbConnectionDispatcher.java:152)
    at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher.handleConnectedUsbDevice(UsbConnectionDispatcher.java:103)
    at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher.rescanDevices(UsbConnectionDispatcher.java:133)
    at de.cotech.hw.SecurityKeyManager.triggerCallbacksActively(SecurityKeyManager.java:386)
    at de.cotech.hw.SecurityKeyManager.lambda$postTriggerCallbacksActively$0$de-cotech-hw-SecurityKeyManager(SecurityKeyManager.java:379)
    at de.cotech.hw.SecurityKeyManager$$ExternalSyntheticLambda0.run(Unknown Source:2)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7898)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)


```

### App information
* ID: `com.nextcloud.client`
* Version: `30220290`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `sunfish`
* Model: `Pixel 4a`
* Id: `TP1A.221005.002`
* Product: `sunfish`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `9012097`

### Android version

13

### Device brand and model

Google Pixel 4a

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.2

### Nextcloud server version

34.0.6

### Using a reverse proxy?

No

### Additional information

Don't have full log since I used the USB port for the yubikey. I don't have a usb hub right now for connecting the additional USB cable for adb.

**Comment by AlvaroBrey** [comment]
cc @dschuermann  just in case

Unfortunately it seems like hwsecurity development has stopped (see https://github.com/cotechde/hwsecurity/issues/4). This means we'll likely have to fork it and patch this ourselves.

@tobiasKaminsky for this and other reasons, I believe we should consider moving to login flow v2 in order to use the default browser instead of a webview; this would be safer, easier to maintain and it would support any feature the default browser does. (would support webauthn/fido without any extra work if using chrome/firefox for example)

**Comment by AlvaroBrey** [comment]
Verified, although some times it just prints out the error but doesn't crash 🤷  NFC keys also work fine, it's just the USB keys that crash.

**Comment by martin-sucha** [comment]
@AlvaroBrey That works, thanks! :tada:

**Comment by AlvaroBrey** [comment]
Fixed by #10976
