### ISSUE TITLE
Too Many Queued jobs

### ISSUE THREAD

**Issue by algor1th** [nextcloud/android#10994]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

The bug occurred with a Nextcloud instance running on my personal network, after being away, and connecting to a hotel network with the same network CIDR as my home network, but the nextcloud server being unreachable.

After reconnecting to my home network the error started appearing.

The error occurs again when the app is opened and instant upload of images is triggered again manually.

### Expected behaviour

The nextcloud app runs in the background

### Actual behaviour

Android notifies the user of an app crash with the attached logs

### Android version

13

### Device brand and model

Google Pixel 6

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.22.2

### Nextcloud server version

23.0.3

### Using a reverse proxy?

No

### Android logs

type: crash
osVersion: google/oriole/oriole:13/TP1A.221005.002/2022102600:user/release-keys
package: com.nextcloud.client:30220290
process: com.nextcloud.client

java.lang.IllegalStateException: JobScheduler 100 job limit exceeded.  We count 151 WorkManager jobs in JobScheduler; we have 20 tracked jobs in our DB; our Configuration limit is 20.
 at androidx.work.impl.background.systemjob.SystemJobScheduler.scheduleInternal(SystemJobScheduler.java:218)
 at androidx.work.impl.background.systemjob.SystemJobScheduler.schedule(SystemJobScheduler.java:133)
 at androidx.work.impl.Schedulers.schedule(Schedulers.java:108)
 at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:226)
 at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:110)
 at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
 at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.IllegalStateException: Apps may not schedule more than 150 distinct jobs
 at android.os.Parcel.createExceptionOrNull(Parcel.java:3029)
 at android.os.Parcel.createException(Parcel.java:3005)
 at android.os.Parcel.readException(Parcel.java:2981)
 at android.os.Parcel.readException(Parcel.java:2923)
 at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:263)
 at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:47)
 at androidx.work.impl.background.systemjob.SystemJobScheduler.scheduleInternal(SystemJobScheduler.java:187)
 ... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
 at com.android.server.job.JobSchedulerService.scheduleAsPackage(JobSchedulerService.java:1203)
 at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:3085)
 at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:153)
 at android.os.Binder.execTransactInternal(Binder.java:1302)
 at android.os.Binder.execTransact(Binder.java:1265)

### Additional information

Running GrapheneOS

The bug occurred with a Nextcloud instance running on my personal network, after being away, and connecting to a hotel network with the same network CIDR as my home network, but the nextcloud server being unreachable.

**Comment by AlvaroBrey** [comment]
@algor1th this was (likely) fixed in https://github.com/nextcloud/android/pull/10926, which is in 3.22.3. If you can upgrade and test again, that would be nice, but otherwise please close this issue.
