### ISSUE TITLE
Crash when viewing "Media" after changing "Media directory"

### ISSUE THREAD

**Issue by Derkades** [nextcloud/android#11027]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

I am unable to reproduce, partly because Media is extremely slow and I am unable to open it without the app hanging/crashing (https://github.com/nextcloud/android/issues/11026#issuecomment-1312730753)

Hopefully the backtrace makes this bug report somewhat useful

### Expected behaviour

N/A

### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Couldn't read row 694, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetString(Native Method)
    at android.database.CursorWindow.getString(CursorWindow.java:462)
    at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:54)
    at android.database.CursorWrapper.getString(CursorWrapper.java:141)
    at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:968)
    at com.owncloud.android.datamodel.FileDataStorageManager.getGalleryItems(FileDataStorageManager.java:2241)
    at com.owncloud.android.datamodel.FileDataStorageManager.getAllGalleryItems(FileDataStorageManager.java:2186)
    at com.owncloud.android.ui.adapter.GalleryAdapter.showAllGalleryItems(GalleryAdapter.kt:168)
    at com.owncloud.android.ui.fragment.GalleryFragment.showAllGalleryItems(GalleryFragment.java:376)
    at com.owncloud.android.ui.asynctasks.GallerySearchTask.onPostExecute(GallerySearchTask.java:126)
    at com.owncloud.android.ui.asynctasks.GallerySearchTask.onPostExecute(GallerySearchTask.java:48)
    at android.os.AsyncTask.finish(AsyncTask.java:771)
    at android.os.AsyncTask.access$900(AsyncTask.java:199)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7876)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)
```

### App information
* ID: `com.nextcloud.client`
* Version: `30220390`
* Build flavor: `generic`

### Device information
* Brand: `google`
* Device: `sargo`
* Model: `Pixel 3a`
* Id: `SP2A.220505.008`
* Product: `sargo`

### Firmware
* SDK: `32`
* Release: `12`
* Incremental: `2022111100`

### Android version

12

### Device brand and model

Pixel 3a

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

30220390

### Nextcloud server version

25

### Using a reverse proxy?

Yes

**Comment by Derkades** [comment]
whoops.. #9948
