### ISSUE TITLE
Crash - java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by habakuk007** [nextcloud/android#11024]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Start Nextcloud App or wait some minutes
2. Crash happens

### Expected behaviour

No crash

### Actual behaviour

Crash message is shown, see below

### Android version

12

### Device brand and model

Samsung Galaxy S10e

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.3

### Nextcloud server version

24.0.6

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "WM.task-1" java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 122768 free bytes and 119KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
    at libcore.icu.ICU.getCurrencyCode(ICU.java:537)
    at java.util.Currency.getInstance(Currency.java:376)
    at java.text.DecimalFormatSymbols.initialize(DecimalFormatSymbols.java:703)
    at java.text.DecimalFormatSymbols.<init>(DecimalFormatSymbols.java:102)
    at java.text.DecimalFormatSymbols.getInstance(DecimalFormatSymbols.java:156)
    at java.util.Formatter.getZero(Formatter.java:2287)
    at java.util.Formatter.<init>(Formatter.java:1896)
    at java.util.Formatter.<init>(Formatter.java:1918)
    at java.lang.String.format(String.java:2870)
    at androidx.work.impl.background.greedy.GreedyScheduler.schedule(GreedyScheduler.java:144)
    at androidx.work.impl.Schedulers.schedule(Schedulers.java:119)
    at androidx.work.impl.WorkerWrapper.onWorkFinished(WorkerWrapper.java:375)
    at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:331)
    at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30220390`
* Build flavor: `generic`

### Device information
* Brand: `samsung`
* Device: `beyond0`
* Model: `SM-G970F`
* Id: `SP1A.210812.016`
* Product: `beyond0lteeea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `G970FXXUGHVJ5`

**Comment by joshtrichards** [comment]
Hi @habakuk007 - Thanks for the report. 

- Is this still occurring with the current release version (v3.26.0)?
- Was this in a brand-new app installation or a pre-existing one that has worked fine previously?

Assuming existing:

- Were/are you using auto-upload or did you have a large set of upload/download transactions occurring in the background?
- Anything unusual or non-default about your home directory or app setup you can think of? 

This is a weird spot to crash (looking up country currency codes), but it perhaps was actually unrelated and that's just where memory happened to run out...
