### ISSUE TITLE
Nextcloud app crashing constantly and duplicating directories and pictures when uploading pictures to "null" folders the few seconds it lasts open.

### ISSUE THREAD

**Issue by IntelRide** [nextcloud/android#11043]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Opening the Nextcloud client app
2. Letting the Nextcloud client app work on the background

### Expected behaviour

Upload pictures without making duplicate directories and files under folder named "null". Open and be usable or work in background as it is intended to do.

### Actual behaviour

Whenever the app is opened manually or trying to work in the background it constantly crashes, the android system sometimes notifies the app isn't responding or the app simply just crashes showing a log and asking if you want to report issue to tracker.

### Android version

12

### Device brand and model

Samsung Galaxy Note10 / samsung d1q SM-N970U

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.3

### Nextcloud server version

24.0.6

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "Thread-5" java.lang.OutOfMemoryError: Failed to allocate a 48 byte allocation with 147344 free bytes and 143KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
    at java.io.ByteArrayOutputStream.<init>(ByteArrayOutputStream.java:77)
    at java.io.ByteArrayOutputStream.<init>(ByteArrayOutputStream.java:62)
    at sun.security.util.DerOutputStream.<init>(DerOutputStream.java:66)
    at sun.security.util.DerValue.toByteArray(DerValue.java:859)
    at sun.security.x509.RDN.<init>(RDN.java:241)
    at sun.security.x509.X500Name.parseDER(X500Name.java:803)
    at sun.security.x509.X500Name.<init>(X500Name.java:317)
    at javax.security.auth.x500.X500Principal.<init>(X500Principal.java:226)
    at com.android.org.conscrypt.OpenSSLX509Certificate.getSubjectX500Principal(OpenSSLX509Certificate.java:502)
    at okhttp3.internal.tls.BasicTrustRootIndex.<init>(BasicTrustRootIndex.kt:28)
    at okhttp3.internal.platform.Platform.buildTrustRootIndex(Platform.kt:163)
    at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Platform.kt:160)
    at okhttp3.internal.platform.Android10Platform.buildCertificateChainCleaner(Android10Platform.kt:82)
    at okhttp3.internal.tls.CertificateChainCleaner$Companion.get(CertificateChainCleaner.kt:42)
    at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.kt:870)
    at com.nextcloud.common.PlainClient$Companion.createDefaultClient(PlainClient.kt:62)
    at com.nextcloud.common.PlainClient$Companion.access$createDefaultClient(PlainClient.kt:47)
    at com.nextcloud.common.PlainClient.<init>(PlainClient.kt:45)
    at com.nextcloud.client.network.ClientFactoryImpl.createPlainClient(ClientFactoryImpl.java:94)
    at com.nextcloud.client.network.ConnectivityServiceImpl.isInternetWalled(ConnectivityServiceImpl.java:79)
    at com.owncloud.android.files.services.FileUploader.retryFailedUploads(FileUploader.java:1072)
    at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:240)
    at com.owncloud.android.utils.FilesSyncHelper$$ExternalSyntheticLambda0.run(Unknown Source:10)
    at java.lang.Thread.run(Thread.java:920)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30220390`
* Build flavor: `generic`

### Device information
* Brand: `samsung`
* Device: `d1q`
* Model: `SM-N970U`
* Id: `SP1A.210812.016`
* Product: `d1qsq`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `N970USQU7HVH9`

### Server error logs

```bash
[files] Warning: User ncadmin still has unscanned files after running background scan, background scan might be stopped prematurely

at 2022-11-16T04:10:11+00:00

[files] Warning: User ncadmin still has unscanned files after running background scan, background scan might be stopped prematurely

at 2022-11-16T03:55:14+00:00
```

### Additional information

All server logs say have the same message. My two other phones and computers have no issue with the same client app version (Android) and the client program (different versions, OS's Windows/Linux).

**Comment by joshtrichards** [comment]
> Upload pictures without making duplicate directories and files under folder named "null". Open and be usable or work in background as it is intended to do.

Can you elaborate on your reproduction steps? How precisely do you have things like auto upload configured? Are you using encryption? etc.

Also, this was awhile ago. Are you still experiencing this with newer versions of the client?
