### ISSUE TITLE
Exception in thread "AsyncTask" on FileSortOrderByName

### ISSUE THREAD

**Issue by UteHaus** [nextcloud/android#11049]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Swap down on the folder view, to update the list.
Or switch from settings to list view. 

### Expected behaviour

The app not break.

### Actual behaviour

The app crashes when updating the list of files.

### Android version

30220390

### Device brand and model

pixle 4

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.22.3

### Nextcloud server version

25.0.1

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "AsyncTask #20" java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$4.done(AsyncTask.java:415)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
    at java.util.concurrent.FutureTask.run(FutureTask.java:271)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)
Caused by: Exception in thread "AsyncTask #20" java.util.ConcurrentModificationException
    at java.util.ArrayList.sort(ArrayList.java:1472)
    at java.util.Collections.sort(Collections.java:206)
    at kotlin.collections.CollectionsKt__MutableCollectionsJVMKt.sortWith(MutableCollectionsJVM.kt:42)
    at com.owncloud.android.utils.FileSortOrderByName.sortServerFiles(FileSortOrderByName.kt:58)
    at com.owncloud.android.utils.FileSortOrderByName.sortCloudFiles(FileSortOrderByName.kt:43)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.setData(OCFileListAdapter.java:694)
    at com.owncloud.android.ui.fragment.OCFileListSearchAsyncTask.doInBackground(OCFileListSearchAsyncTask.kt:70)
    at com.owncloud.android.ui.fragment.OCFileListSearchAsyncTask.doInBackground(OCFileListSearchAsyncTask.kt:33)
    at android.os.AsyncTask$3.call(AsyncTask.java:394)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30220390`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `sunfish`
* Model: `Pixel 4a`
* Id: `SQ3A.220705.004`
* Product: `sunfish`

### Firmware
* SDK: `32`
* Release: `12`
* Incremental: `8fda5a3502`

**Comment by UteHaus** [comment]
This bug cam when  I selected a folder in the favorites. With this error the App closed.

The error came sporadically and with the new Version 3.23.0  the error no longer came back.

**Comment by Garfonso** [comment]
I get the same behavior. It seems to load the favorites just fine and the suddenly crashes.

This is the log the app shows me:

### Cause of error
```java
Exception in thread "AsyncTask #11" java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$4.done(AsyncTask.java:415)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
    at java.util.concurrent.FutureTask.run(FutureTask.java:269)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
    at java.lang.Thread.run(Thread.java:1012)
Caused by: Exception in thread "AsyncTask #11" java.util.ConcurrentModificationException
    at java.util.ArrayList.sort(ArrayList.java:1472)
    at java.util.Collections.sort(Collections.java:206)
    at kotlin.collections.CollectionsKt__MutableCollectionsJVMKt.sortWith(MutableCollectionsJVM.kt:42)
    at com.owncloud.android.utils.FileSortOrderByName.sortServerFiles(FileSortOrderByName.kt:58)
    at com.owncloud.android.utils.FileSortOrderByName.sortCloudFiles(FileSortOrderByName.kt:43)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.setData(OCFileListAdapter.java:700)
    at com.owncloud.android.ui.fragment.OCFileListSearchAsyncTask.doInBackground(OCFileListSearchAsyncTask.kt:70)
    at com.owncloud.android.ui.fragment.OCFileListSearchAsyncTask.doInBackground(OCFileListSearchAsyncTask.kt:33)
    at android.os.AsyncTask$3.call(AsyncTask.java:394)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30240190`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `dm3q`
* Model: `SM-S918B`
* Id: `TP1A.220624.014`
* Product: `dm3qxeea`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `S918BXXS1AWBM`

**Comment by joshtrichards** [comment]
This appears to match most of the traces in #7782, but reliable reproduction steps are hard to come by. Let's consolidate this matter there.
