### ISSUE TITLE
Crash on start when trying to open new account on device

### ISSUE THREAD

**Issue by agilob** [nextcloud/android#1107]
### Actual behaviour
- app crashes when I try to create new account

### Expected behaviour
- I woudl like to login...
 
### Steps to reproduce
1. install nextcloud from fdroid
2. start app on brand new device
3. app crashes
4. I can see login form and 'application stopped' popup

### Environment data
Android version: 6.0.1

Stock or customized system: stock

Nextcloud app version: 1.4.2

Nextcloud server version: 11

**Comment by tobiasKaminsky** [comment]
Is this working when you create a demo cloud on demo.nextcloud.com and try to connect to it?

**Comment by agilob** [comment]
The crash happens before I even can type user/pass/domain. 

1. Tap on nextcloud icon
2. (milliseconds delay) form shows
3. (milliseconds delay) application crashed popup shows
4. Underlying form becomes white

I'll try to get stacktrace over the weekend.

**Comment by Mannshoch** [comment]
same Error here on Fairphon 2.
I collected a log from Catlog 
```
build.board: FP2
build.bootloader: unknown
build.brand: Fairphone
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: FP2
build.display: FP2-userdebug 6.0.1 FP2 fp2-sibon-17.06.4 release-keys
build.fingerprint: Fairphone/FP2/FP2:6.0.1/FP2/fp2-sibon-17.06.4:userdebug/release-keys
build.hardware: qcom
build.host: jenkins-slave04
build.id: FP2
build.manufacturer: Fairphone
build.model: FP2
build.product: FP2
build.radio: unknown
build.serial: a45abac5
build.tags: release-keys
build.time: 1497522435000
build.type: userdebug
build.user: jenkins
version.codename: REL
version.incremental: fp2-sibon-17.06.4
version.release: 6.0.1
version.sdk_int: 23
```
```
06-28 15:53:21.406 I/ActivityManager( 2288): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10100000 pkg=com.nextcloud.client cmp=com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity} from uid 10016 on display 0
06-28 15:53:21.410 I/am_create_activity( 2288): [0,29411263,336,com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity,android.intent.action.MAIN,NULL,NULL,269484032]
06-28 15:53:21.415 I/am_focused_activity( 2288): [0,com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity]
06-28 15:53:21.431 I/am_restart_activity( 2288): [0,29411263,336,com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity]
06-28 15:53:21.513 I/AccountAuthenticator( 9219): Adding account with type nextcloud and auth token null
06-28 15:53:21.519 I/ActivityManager( 2288): START u0 {flg=0x10800004 cmp=com.nextcloud.client/com.owncloud.android.authentication.AuthenticatorActivity (has extras)} from uid 10106 on display 0
06-28 15:53:21.523 I/am_create_activity( 2288): [0,42624654,336,com.nextcloud.client/com.owncloud.android.authentication.AuthenticatorActivity,NULL,NULL,NULL,276824068]
06-28 15:53:21.523 I/am_pause_activity( 2288): [0,29411263,com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity]
06-28 15:53:21.527 I/am_focused_activity( 2288): [0,com.nextcloud.client/com.owncloud.android.authentication.AuthenticatorActivity]
06-28 15:53:21.817 I/am_restart_activity( 2288): [0,42624654,336,com.nextcloud.client/com.owncloud.android.authentication.AuthenticatorActivity]
06-28 15:53:21.821 D/FileObserverService( 9219): Starting command Intent { act=com.owncloud.android.services.observer.FileObserverService.action.START_OBSERVATION cmp=com.nextcloud.client/com.owncloud.android.services.observer.FileObserverService }
06-28 15:53:21.952 I/ActivityManager( 2288): START u0 {cmp=com.nextcloud.client/com.owncloud.android.ui.activity.WhatsNewActivity} from uid 10106 on display 0
06-28 15:53:21.954 I/am_create_activity( 2288): [0,41961494,336,com.nextcloud.client/com.owncloud.android.ui.activity.WhatsNewActivity,NULL,NULL,NULL,0]
06-28 15:53:21.954 I/am_pause_activity( 2288): [0,42624654,com.nextcloud.client/com.owncloud.android.authentication.AuthenticatorActivity]
06-28 15:53:21.957 I/am_focused_activity( 2288): [0,com.nextcloud.client/com.owncloud.android.ui.activity.WhatsNewActivity]
06-28 15:53:22.300 I/am_restart_activity( 2288): [0,41961494,336,com.nextcloud.client/com.owncloud.android.ui.activity.WhatsNewActivity]
06-28 15:53:22.409 E/AndroidRuntime( 9219): Process: com.nextcloud.client, PID: 9219
06-28 15:53:22.409 I/am_crash( 2288): [9219,0,com.nextcloud.client,948485700,android.content.res.Resources$NotFoundException,String resource ID #0x7f08000a,Resources.java,312]
06-28 15:53:22.409 E/AndroidRuntime( 9219): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.WhatsNewActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x7f08000a
06-28 15:53:22.410 W/ActivityManager( 2288):   Force finishing activity com.nextcloud.client/com.owncloud.android.ui.activity.WhatsNewActivity
06-28 15:53:22.410 I/am_finish_activity( 2288): [0,41961494,336,com.nextcloud.client/com.owncloud.android.ui.activity.WhatsNewActivity,force-crash]
06-28 15:53:22.416 I/am_focused_activity( 2288): [0,com.nextcloud.client/com.owncloud.android.authentication.AuthenticatorActivity]
06-28 15:53:22.417 I/am_pause_activity( 2288): [0,41961494,com.nextcloud.client/com.owncloud.android.ui.activity.WhatsNewActivity]
06-28 15:53:22.417 W/ActivityManager( 2288):   Force finishing activity com.nextcloud.client/com.owncloud.android.authentication.AuthenticatorActivity
06-28 15:53:22.417 I/am_finish_activity( 2288): [0,42624654,336,com.nextcloud.client/com.owncloud.android.authentication.AuthenticatorActivity,force-crash]
06-28 15:53:22.419 I/am_focused_activity( 2288): [0,com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity]
06-28 15:53:22.419 I/am_destroy_activity( 2288): [0,42624654,336,com.nextcloud.client/com.owncloud.android.authentication.AuthenticatorActivity,finish-imm]
06-28 15:53:22.917 W/ActivityManager( 2288): Activity pause timeout for ActivityRecord{2804816 u0 com.nextcloud.client/com.owncloud.android.ui.activity.WhatsNewActivity t336 f}
06-28 15:53:23.026 I/am_resume_activity( 2288): [0,29411263,336,com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity]
06-28 15:53:25.064 W/InputDispatcher( 2288): channel 'f3d119f com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
06-28 15:53:25.064 E/InputDispatcher( 2288): channel 'f3d119f com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
06-28 15:53:25.065 I/WindowState( 2288): WIN DEATH: Window{f3d119f u0 com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}
06-28 15:53:25.065 W/InputDispatcher( 2288): Attempted to unregister already unregistered input channel 'f3d119f com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity (server)'
06-28 15:53:25.068 I/WindowState( 2288): WIN DEATH: Window{37043ee u0 com.nextcloud.client/com.owncloud.android.authentication.AuthenticatorActivity}
06-28 15:53:25.078 I/sf_frame_dur(  287): [com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity,0,0,1,0,0,0,0]
06-28 15:53:25.109 I/ActivityManager( 2288): Process com.nextcloud.client (pid 9219) has died
06-28 15:53:25.109 I/am_proc_died( 2288): [0,9219,com.nextcloud.client]
06-28 15:53:25.110 I/am_service_crashed_too_much( 2288): [0,2,com.nextcloud.client/com.owncloud.android.authentication.AccountAuthenticatorService,9219]
06-28 15:53:25.110 W/ActivityManager( 2288): Service crashed 2 times, stopping: ServiceRecord{a94cfaf u0 com.nextcloud.client/com.owncloud.android.authentication.AccountAuthenticatorService}
06-28 15:53:25.110 W/ActivityManager( 2288): Scheduling restart of crashed service com.nextcloud.client/com.owncloud.android.services.observer.FileObserverService in 1000ms
06-28 15:53:25.110 I/am_schedule_service_restart( 2288): [0,com.nextcloud.client/com.owncloud.android.services.observer.FileObserverService,1000]
06-28 15:53:25.110 W/ActivityManager( 2288): Scheduling restart of crashed service com.nextcloud.client/com.owncloud.android.services.observer.SyncedFolderObserverService in 11000ms
06-28 15:53:25.111 W/ActivityManager( 2288): Force removing ActivityRecord{1c0c7bf u0 com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity t336}: app died, no saved state
06-28 15:53:25.110 I/am_schedule_service_restart( 2288): [0,com.nextcloud.client/com.owncloud.android.services.observer.SyncedFolderObserverService,11000]
06-28 15:53:25.111 I/am_finish_activity( 2288): [0,29411263,336,com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity,proc died without state saved]
06-28 15:53:25.227 I/sf_frame_dur(  287): [Application Error: com.nextcloud.client,19,0,0,0,2,2,0]
06-28 15:53:26.123 I/am_proc_start( 2288): [0,9906,10106,com.nextcloud.client,service,com.nextcloud.client/com.owncloud.android.services.observer.FileObserverService]
06-28 15:53:26.124 I/ActivityManager( 2288): Start proc 9906:com.nextcloud.client/u0a106 for service com.nextcloud.client/com.owncloud.android.services.observer.FileObserverService
06-28 15:53:26.165 I/am_proc_bound( 2288): [0,9906,com.nextcloud.client]
06-28 15:53:26.176 W/System  ( 9906): ClassLoader referenced unknown path: /data/app/com.nextcloud.client-2/lib/arm
06-28 15:53:26.287 D/ThumbnailsCacheManager( 9906): create dir: /storage/emulated/0/Android/data/com.nextcloud.client/cache/thumbnailCache

```

**Comment by agilob** [comment]
Sorry for late response. I made a screenshot from the crash - probably not too helpful XD
This is what I can see right after opening the app.

![screenshot_20170623-093354](https://user-images.githubusercontent.com/2544251/27658424-e5bffa96-5c47-11e7-951e-b7e8487599e4.png)

If the logs above are not sufficient (can't see stracktrace there) I can get logs from my device. Is there anything in the app that would block logging exceptions/stracktrace?

**Comment by tobiasKaminsky** [comment]
> [9219,0,com.nextcloud.client,948485700,android.content.res.Resources$NotFoundException,String resource ID #0x7f08000a,Resources.java,312]

This seems to be related to #946 
Can you give the dev version a try: https://github.com/nextcloud/android#start-contributing there is a link to a direct download or via fdroid.

**Comment by agilob** [comment]
I see you located the issue, but have a stracktrace anyway:

```
9 08:34:53.027  1667  1800 I LaunchCheckinHandler: Displayed com.nextcloud.client/com.owncloud.android.authentication.AuthenticatorActivity,wp,ca,618
06-29 08:34:53.031 12359 12359 D WhatsNewActivity: onCreate(Bundle) starting
06-29 08:34:53.057 12359 12359 W ResourceType: Failure getting entry for 0x7f08000a (t=7 e=10) (error -75)
06-29 08:34:53.058 12359 12359 D AndroidRuntime: Shutting down VM
06-29 08:34:53.065 12359 12359 E AndroidRuntime: FATAL EXCEPTION: main
06-29 08:34:53.065 12359 12359 E AndroidRuntime: Process: com.nextcloud.client, PID: 12359
06-29 08:34:53.065 12359 12359 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.WhatsNewActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x7f08000a
06-29 08:34:53.065 12359 12359 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2429)
06-29 08:34:53.065 12359 12359 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
06-29 08:34:53.065 12359 12359 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(ActivityThread.java)
06-29 08:34:53.065 12359 12359 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357)
06-29 08:34:53.065 12359 12359 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
06-29 08:34:53.065 12359 12359 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
06-29 08:34:53.065 12359 12359 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5459)
06-29 08:34:53.065 12359 12359 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-29 08:34:53.065 12359 12359 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
06-29 08:34:53.065 12359 12359 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
06-29 08:34:53.065 12359 12359 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x7f08000a
06-29 08:34:53.065 12359 12359 E AndroidRuntime:        at android.content.res.Resources.getText(Resources.java:312)
06-29 08:34:53.065 12359 12359 E AndroidRuntime:        at android.widget.TextView.setText(TextView.java:4427)
06-29 08:34:53.065 12359 12359 E AndroidRuntime:        at com.owncloud.android.ui.activity.WhatsNewActivity.onCreate(WhatsNewActivity.java:142)
06-29 08:34:53.065 12359 12359 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6259)
06-29 08:34:53.065 12359 12359 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
06-29 08:34:53.065 12359 12359 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2382)
06-29 08:34:53.065 12359 12359 E AndroidRuntime:        ... 9 more
06-29 08:34:53.073  1667  3693 W ActivityManager:   Force finishing activity com.nextcloud.client/com.owncloud.android.ui.activity.WhatsNewActivity
06-29 08:34:53.078  1667  3693 W ActivityManager:   Force finishing activity com.nextcloud.client/com.owncloud.android.authentication.AuthenticatorActivity
06-29 08:34:53.078  3653  6262 D ProcSpeedReader: Failed to read freq stats from null
```

>Can you give the dev version a try

two last -dev versions from fdroid work fine. Stable version doesn't.

**Comment by tobiasKaminsky** [comment]
:+1: 
Then this is solved as we already have this merged to master and it will be in next version.
Thank you for your help!
