### ISSUE TITLE
Sync Calendar & Contacts - Server address could not be resolved

### ISSUE THREAD

**Issue by mrtumnus** [nextcloud/android#11126]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open Nextcloud App
2. Go to Settings
3. Press "Sync calendar & contacts"

### Expected behaviour

DAVx5 app opens with Nextcloud login flow.

### Actual behaviour

Toast message appears:
```
Server address for the account could not be resolved for DAVx5 (formerly known as DAVdroid)
```

No login flow appears, and no accounts are added.

### Android version

13

### Device brand and model

Samsung Galaxy S22

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.3

### Nextcloud server version

25.0.1

### Using a reverse proxy?

Yes

### Android logs

[Nextcloud_Android.log](https://github.com/nextcloud/android/files/10135778/Nextcloud_Android.log)

### Additional information

The log shows me pressing the "Sync calendar & contacts" button 3 times.  I see the following stack trace in the log 3 times:

```
12-01 14:52:15.883  7651  7651 E SettingsActivity: Base Uri for account could not be resolved to call DAVdroid!
12-01 14:52:15.883  7651  7651 E SettingsActivity: android.content.ActivityNotFoundException: Unable to find explicit activity class {at.bitfire.davdroid/at.bitfire.davdroid.ui.setup.LoginActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
12-01 14:52:15.883  7651  7651 E SettingsActivity: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2171)
12-01 14:52:15.883  7651  7651 E SettingsActivity: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1805)
12-01 14:52:15.883  7651  7651 E SettingsActivity: 	at android.app.Activity.startActivityForResult(Activity.java:5583)
12-01 14:52:15.883  7651  7651 E SettingsActivity: 	at android.app.Activity.startActivityForResult(Activity.java:5541)
12-01 14:52:15.883  7651  7651 E SettingsActivity: 	at com.owncloud.android.ui.activity.SettingsActivity.launchDavDroidLogin(SettingsActivity.java:786)
12-01 14:52:15.883  7651  7651 E SettingsActivity: 	at com.owncloud.android.ui.activity.SettingsActivity.lambda$setupCalendarPreference$13$com-owncloud-android-ui-activity-SettingsActivity(SettingsActivity.java:489)
12-01 14:52:15.883  7651  7651 E SettingsActivity: 	at com.owncloud.android.ui.activity.SettingsActivity$$ExternalSyntheticLambda13.onPreferenceClick(Unknown Source:4)
12-01 14:52:15.883  7651  7651 E SettingsActivity: 	at android.preference.Preference.performClick(Preference.java:1312)
12-01 14:52:15.883  7651  7651 E SettingsActivity: 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:276)
12-01 14:52:15.883  7651  7651 E SettingsActivity: 	at android.widget.AdapterView.performItemClick(AdapterView.java:376)
12-01 14:52:15.883  7651  7651 E SettingsActivity: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1282)
12-01 14:52:15.883  7651  7651 E SettingsActivity: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3558)
12-01 14:52:15.883  7651  7651 E SettingsActivity: 	at android.widget.AbsListView$3.run(AbsListView.java:4711)
12-01 14:52:15.883  7651  7651 E SettingsActivity: 	at android.os.Handler.handleCallback(Handler.java:942)
12-01 14:52:15.883  7651  7651 E SettingsActivity: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-01 14:52:15.883  7651  7651 E SettingsActivity: 	at android.os.Looper.loopOnce(Looper.java:226)
12-01 14:52:15.883  7651  7651 E SettingsActivity: 	at android.os.Looper.loop(Looper.java:313)
12-01 14:52:15.883  7651  7651 E SettingsActivity: 	at android.app.ActivityThread.main(ActivityThread.java:8741)
12-01 14:52:15.883  7651  7651 E SettingsActivity: 	at java.lang.reflect.Method.invoke(Native Method)
12-01 14:52:15.883  7651  7651 E SettingsActivity: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
12-01 14:52:15.883  7651  7651 E SettingsActivity: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
12-01 14:52:15.890  7651  7651 D SettingsActivity: onPause() ending
```

**Comment by AlvaroBrey** [comment]
Something might have changed in the DavX5 side, needs a bit of research

**Comment by AlvaroBrey** [comment]
Upstream PR: https://github.com/bitfireAT/davx5-ose/pull/211

**Comment by itay-grudev** [comment]
Same thing here. Our server us using SAML for authentication if that's relevant.

![Screenshot_20221203_135943_Nextcloud](https://user-images.githubusercontent.com/2123767/205897671-6a033896-8910-4cfb-bf8e-09b729322d9f.jpg)

**Comment by rfc2822** [comment]
This has been fixed in DAVx⁵ 4.2.6 (which has just been released).
