### ISSUE TITLE
Failed to allocate a 16 byte allocation with 9962608 free bytes and 9729KB until OOM

### ISSUE THREAD

**Issue by kasumiru** [nextcloud/android#11141]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

run nextcloud in android, open "status transfer"
and next I see ************ CAUSE OF ERROR ************

### Expected behaviour

start normal synking files

### Actual behaviour

Exception in thread "Thread-10" java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 9962608 free bytes and 9729KB until OOM, target footprint 805306368, growth limit 805306368; failed due to fragmentation (largest possible contiguous allocation 0 bytes). Number of 256KB sized free regions are: 0

### Android version

12

### Device brand and model

asus zenfone 8

### Stock or custom OS?

Stock

### Nextcloud android app version

3.22.3

### Nextcloud server version

 24.0.2

### Using a reverse proxy?

No

### Cause of error
java
Exception in thread "Thread-10" java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 9962608 free bytes and 9729KB until OOM, target footprint 805306368, growth limit 805306368; failed due to fragmentation (largest possible contiguous allocation 0 bytes). Number of 256KB sized free regions are: 0
    at sun.security.x509.X500Name.getRFC2253CanonicalName(X500Name.java:725)
    at sun.security.x509.X500Name.hashCode(X500Name.java:383)
    at javax.security.auth.x500.X500Principal.hashCode(X500Principal.java:487)
    at java.util.HashMap.hash(HashMap.java:338)
    at java.util.LinkedHashMap.get(LinkedHashMap.java:464)
    at okhttp3.internal.tls.BasicTrustRootIndex.<init>(BasicTrustRootIndex.kt:57)
    at okhttp3.internal.platform.Platform.buildTrustRootIndex(Platform.kt:163)
    at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Platform.kt:160)
    at okhttp3.internal.platform.Android10Platform.buildCertificateChainCleaner(Android10Platform.kt:82)
    at okhttp3.internal.tls.CertificateChainCleaner$Companion.get(CertificateChainCleaner.kt:42)
    at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.kt:870)
    at com.nextcloud.common.PlainClient$Companion.createDefaultClient(PlainClient.kt:62)
    at com.nextcloud.common.PlainClient$Companion.access$createDefaultClient(PlainClient.kt:47)
    at com.nextcloud.common.PlainClient.<init>(PlainClient.kt:45)
    at com.nextcloud.client.network.ClientFactoryImpl.createPlainClient(ClientFactoryImpl.java:94)
    at com.nextcloud.client.network.ConnectivityServiceImpl.isInternetWalled(ConnectivityServiceImpl.java:79)
    at com.owncloud.android.files.services.FileUploader.retryFailedUploads(FileUploader.java:1072)
    at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:240)
    at com.owncloud.android.utils.FilesSyncHelper$$ExternalSyntheticLambda0.run(Unknown Source:10)
    at java.lang.Thread.run(Thread.java:1012)

### App information
* ID: com.nextcloud.client
* Version: 30220390
* Build flavor: gplay

### Device information
* Brand: asus
* Device: ASUS_I006D
* Model: ASUS_I006D
* Id: SKQ1.210821.001
* Product: WW_I006D

### Firmware
* SDK: 31
* Release: 12
* Incremental: 31.1010.0411.138

### Server error logs

```bash
--
```

### Additional information

--

**Comment by kasumiru** [comment]
after this crush nextcloud going infinity cycle; "Sync conflict".. 1236 files cant check md5sum automatically. 

![image](https://user-images.githubusercontent.com/25246740/205741831-a4890033-ce14-4a54-99dc-39fd28d76fba.png)

**Comment by kasumiru** [comment]
maybe we can close this issue. I cant reproduce this. this my prone is died
