### ISSUE TITLE
Crash when sharing to Nextcloud from other app, and the last used folder does not exist anymore

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/android#11207]
### Cause of error

Not reproducible but some facts about what happened:

- Nextcloud Android srt up with 3 accounts
- Downloaded a PDF file, opened the file in a PDF viewer
- Pressed "Share", Nextcloud Files app opemed with location chooser
- Pressed "Up" multiple times quickly because the location chooser was in a wrong directory
- Crash

```java
Exception in thread "Thread-435" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:229)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:920)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30230190`
* Build flavor: `generic`

### Device information
* Brand: `Xiaomi`
* Device: `beryllium`
* Model: `POCO F1`
* Id: `SQ3A.220705.004`
* Product: `beryllium`

### Firmware
* SDK: `32`
* Release: `12`
* Incremental: `6f4e1ac54a`

**Comment by stefan-niedermann** [comment]
Update: It is reproducible.

The crux is: I deleted the remoe folder in the meantime, so when choosing my location and I am starting in a folder that does not exist anymore, the app crashes.

It probably should just go ahead to the root directory or so

**Comment by stefan-niedermann** [comment]
Workaround: When location chooser is visible, switch to another account and then back to the actually wanted account. You will be in the root directory then and no crash happens.

**Comment by rmeissn** [comment]
Problem description:
I've last shared to folder /A/B/C and later deleted folder A. Whenever I want to share to Nextcloud again, it reopens /A/B/C, showing the deleted content (cached?), but I'm unable to upload to this folder or to navigate away (e.g. by hitting the back button at the top left) - an exception occurs.
As I only got one account in the Nextcloud client, I'm unable to use @stefan-niedermann workaround. My Workaround: delete all app data and set it up again. Sharing to Nextcloud will open up the root folder again.

**Comment by farhills** [comment]
I believe I am having an issue related. I have 2 accounts 'A' and 'B'. When sharing photos from the phone gallery app, I land in account 'A'.  Choosing 'switch account' in the app menu doesn't trigger a screen refresh. The prior account 'A' folder is still shown.  Any attempt to navigate (ie pressing the left arrow in the app) causes a hard crash.

Workaround is changing back and forth between accounts a few times, while only changing folder levels in the 'A' account until a switch account action triggers a screen refresh to properly display the 'B' account root folder.

Crash dump:
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.datamodel.OCFile.canWrite()' on a null object reference
    at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onCreateOptionsMenu(ReceiveExternalFilesActivity.java:1038)
    at android.app.Activity.onCreatePanelMenu(Activity.java:4456)
    at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:506)
    at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:95)
    at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3122)
    at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:458)
    at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
    at android.view.Choreographer.doCallbacks(Choreographer.java:923)
    at android.view.Choreographer.doFrame(Choreographer.java:847)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8741)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30230191`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `a71`
* Model: `SM-A715W`
* Product: `a71cs`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `A715WVLU4EVK3`

**Comment by mat-l** [comment]
Happened again to me after trying to go one folder level upwards:

`
### Cause of error
```java
Exception in thread "Thread-7" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:929)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30240090`
* Build flavor: `generic`

### Device information
* Brand: `HUAWEI`
* Device: `HWELE`
* Model: `ELE-AL00`
* Id: `HUAWEIELE-AL00`
* Product: `ELE-AL00`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `10.1.0.162C00`
`

**Comment by Leorivasc** [comment]
Came to report the same. 
Attempt to upload file using the share option. It shows the last folder used (still existent). Trying to browse back crashes with the below text.
If try to upload to the shown folder, it doesn't anyway.
Thanks

### Cause of error
```java
Exception in thread "Thread-20" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30240190`
* Build flavor: `gplay`

### Device information
* Brand: `motorola`
* Device: `miami`
* Model: `motorola edge 30 neo`
* Id: `S3SSMS32.34-46-1-4`
* Product: `miami_g`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `94fb5-89a0a`

**Comment by joshtrichards** [comment]
@farhills: Yours looks to be a different issue. Possibly same as #9321?

**Comment by farhills** [comment]
> @farhills: Yours looks to be a different issue. Possibly same as #9321?

No encryption on my server, so not the same as what's happening in 9321.

As I recall it had to do with switching accounts while not in the account root folder. It seemed like the prior account path was still cached by the app and didn't update during the account switch.  When you tried to navigate out of the subfolder (ie Press the back arrow), the app couldn't find the next level up because that folder path only existed on the other account. I can't recall if my circumstance also involved moved/deleted folders.

I've adjusted my workflow to ensure I'm in the account root folder before switching accounts, no crash since. I just made a cursory attempt to reproduce my initial issue and it worked ok to switch accounts while in a subfolder. Didn't experiment with deleting the folders.

**Comment by joshtrichards** [comment]
That code path is executed with or without encryption - the original reporter in that issue just happens to have mentioned it. The stack trace is the key part to compare.

**Comment by SamuXzX** [comment]
Reporting the same:

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.datamodel.OCFile.canWrite()' on a null object reference
    at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onCreateOptionsMenu(ReceiveExternalFilesActivity.java:1034)
    at android.app.Activity.onCreatePanelMenu(Activity.java:4274)
    at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:521)
    at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:95)
    at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3429)
    at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:458)
    at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
    at android.view.Choreographer.doCallbacks(Choreographer.java:796)
    at android.view.Choreographer.doFrame(Choreographer.java:727)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:250)
    at android.app.ActivityThread.main(ActivityThread.java:7755)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30240190`
* Build flavor: `generic`

### Device information
* Brand: `motorola`
* Device: `nairo`
* Model: `moto g 5G plus`
* Id: `RPNS31.Q4U-39-27-9-2-9`
* Product: `nairo_retaile`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `9ab668`

**Comment by rofra** [comment]
Same for me:
### Cause of error
```java
Exception in thread "Thread-9" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:919)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30240290`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `beyond1`
* Model: `SM-G973F`
* Id: `QP1A.190711.020`
* Product: `beyond1lteeea`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `G973FXXU8DTH7`

**Comment by AnrDaemon** [comment]
Happens constantly. Share to Nextcloud -> it shows some directory it remembered from the times past -> trying to navigate away from it crashes the app. Trying to just upload where it lands gets stuck in perpetual collision.
At the same time, uploads from inside the app itself work fine.

In my case, the directory actually exists, albeit I may have removed and recreated it. I don't recall.

**Comment by chaehni** [comment]
Same issue here

**Comment by joshuajeschek** [comment]
Happening to me too, after with this setup:
1. create directories `fuu/bar`
2. upload to `bar`
3. notice typo and rename `fuu` to `foo`
4. try to upload (entry point is `bar`, since last upload was there)
5. navigate one level up
6. -> crash

---

...

**Comment by sunnyd24** [comment]
Issue still exists for me when navigating through folder structure after share (and is repeatable) :

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.datamodel.OCFile.canWrite()' on a null object reference
    at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onCreateOptionsMenu(ReceiveExternalFilesActivity.java:1037)
    at android.app.Activity.onCreatePanelMenu(Activity.java:4469)
    at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:521)
    at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:95)
    at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3429)
    at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:458)
    at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
    at android.view.Choreographer.doCallbacks(Choreographer.java:923)
    at android.view.Choreographer.doFrame(Choreographer.java:847)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8757)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30250090`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `p3s`
* Model: `SM-G998B`
* Id: `TP1A.220624.014`
* Product: `p3sxeea`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `G998BXXS9EWF3`
*

### Cause of error
```java
Exception in thread "Thread-11" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30250090`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `p3s`
* Model: `SM-G998B`
* Id: `TP1A.220624.014`
* Product: `p3sxeea`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `G998BXXS9EWF3`

**Comment by rmeissn** [comment]
I also still git the issue.
Temporary workaround: recreating the old folder structure enables to navigate away within the sharing dialogue. After you've navigated away, you can delete the created folder structure, as the sharing dialogue.

**Comment by joshtrichards** [comment]
> Issue still exists for me when navigating through folder structure after share (and is repeatable) :

@sunnyd24: That's because it's not released yet. It's fixed in the code  base. Wait for the next release. :) Well, or try out the development version:

**Comment by sunnyd24** [comment]
> > Issue still exists for me when navigating through folder structure after share (and is repeatable) :
> 
> @sunnyd24: That's because it's not released yet. It's fixed in the code base. Wait for the next release. :) Well, or try out the development version: https://github.com/nextcloud/android/#development-version-hammer

Thanks @joshtrichards, noted, I didn't realise closed issue meant update in codebase but not released in prod version. Also this issue seems to be related to Group folders Plugin being automatically disabled as the root cause.
