### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by niccokunzmann** [nextcloud/android#11229]
### Cause of error
```java
Exception in thread "WM.task-1" java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
    at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:962)
    at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:599)
    at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
    at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
    at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:752)
    at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
    at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeUpdateDelete(FrameworkSQLiteStatement.java:46)
    at androidx.work.impl.model.WorkSpecDao_Impl.markWorkSpecScheduled(WorkSpecDao_Impl.java:345)
    at androidx.work.impl.Schedulers.schedule(Schedulers.java:89)
    at androidx.work.impl.WorkerWrapper.onWorkFinished(WorkerWrapper.java:375)
    at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:331)
    at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20220421`
* Build flavor: `generic`

### Device information
* Brand: `motorola`
* Device: `osprey_umts`
* Model: `MotoG3`
* Id: `MPIS24`
* Product: `osprey_3gb`

### Firmware
* SDK: `23`
* Release: `6.0.1`
* Incremental: `17`

**Comment by AlvaroBrey** [comment]
Looks like an error on a background job but the trace doesn't show which one. I'll close this issue as you're using a pretty old app version, but if you get the error again please try to get some logs from the phone and post them here. 

Log instructions here: https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat-mag
Feel free to search and replace the server URL, username and other file names in the output.
