### ISSUE TITLE
crash report from app

### ISSUE THREAD

**Issue by rizzopablo** [nextcloud/android#11239]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Cause of error
```java
Exception in thread "Thread-14" java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 1897472 free bytes and 1853KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
    at sun.security.util.DerValue.init(DerValue.java:405)
    at sun.security.util.DerValue.<init>(DerValue.java:337)
    at sun.security.util.DerInputStream.getDerValue(DerInputStream.java:496)
    at sun.security.x509.AVA.<init>(AVA.java:625)
    at sun.security.x509.RDN.<init>(RDN.java:246)
    at sun.security.x509.X500Name.parseDER(X500Name.java:803)
    at sun.security.x509.X500Name.<init>(X500Name.java:317)
    at javax.security.auth.x500.X500Principal.<init>(X500Principal.java:226)
    at com.android.org.conscrypt.OpenSSLX509Certificate.getSubjectX500Principal(OpenSSLX509Certificate.java:502)
    at okhttp3.internal.tls.BasicTrustRootIndex.<init>(BasicTrustRootIndex.kt:28)
    at okhttp3.internal.platform.Platform.buildTrustRootIndex(Platform.kt:163)
    at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Platform.kt:160)
    at okhttp3.internal.platform.Android10Platform.buildCertificateChainCleaner(Android10Platform.kt:82)
    at okhttp3.internal.tls.CertificateChainCleaner$Companion.get(CertificateChainCleaner.kt:42)
    at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.kt:870)
    at com.nextcloud.common.NextcloudClient$Companion.createDefaultClient(NextcloudClient.kt:89)
    at com.nextcloud.common.NextcloudClient$Companion.access$createDefaultClient(NextcloudClient.kt:72)
    at com.nextcloud.common.NextcloudClient.<init>(NextcloudClient.kt:101)
    at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:185)
    at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:236)
    at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:192)
    at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
    at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
    at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:279)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:920)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20221105`
* Build flavor: `versionDev`

### Device information
* Brand: `samsung`
* Device: `a52q`
* Model: `SM-A525M`
* Id: `SQ3A.220605.009.A1`
* Product: `a52qnsxx`

### Firmware
* SDK: `32`
* Release: `12`
* Incremental: `eng.simon.20220704.144116`

### Expected behaviour

Random

### Actual behaviour

Crash

### Android version

12

### Device brand and model

Samsung a52

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

lineageos

### Nextcloud server version

dk

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "Thread-14" java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 1897472 free bytes and 1853KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
    at sun.security.util.DerValue.init(DerValue.java:405)
    at sun.security.util.DerValue.<init>(DerValue.java:337)
    at sun.security.util.DerInputStream.getDerValue(DerInputStream.java:496)
    at sun.security.x509.AVA.<init>(AVA.java:625)
    at sun.security.x509.RDN.<init>(RDN.java:246)
    at sun.security.x509.X500Name.parseDER(X500Name.java:803)
    at sun.security.x509.X500Name.<init>(X500Name.java:317)
    at javax.security.auth.x500.X500Principal.<init>(X500Principal.java:226)
    at com.android.org.conscrypt.OpenSSLX509Certificate.getSubjectX500Principal(OpenSSLX509Certificate.java:502)
    at okhttp3.internal.tls.BasicTrustRootIndex.<init>(BasicTrustRootIndex.kt:28)
    at okhttp3.internal.platform.Platform.buildTrustRootIndex(Platform.kt:163)
    at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Platform.kt:160)
    at okhttp3.internal.platform.Android10Platform.buildCertificateChainCleaner(Android10Platform.kt:82)
    at okhttp3.internal.tls.CertificateChainCleaner$Companion.get(CertificateChainCleaner.kt:42)
    at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.kt:870)
    at com.nextcloud.common.NextcloudClient$Companion.createDefaultClient(NextcloudClient.kt:89)
    at com.nextcloud.common.NextcloudClient$Companion.access$createDefaultClient(NextcloudClient.kt:72)
    at com.nextcloud.common.NextcloudClient.<init>(NextcloudClient.kt:101)
    at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:185)
    at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:236)
    at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:192)
    at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
    at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
    at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:279)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:920)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20221105`
* Build flavor: `versionDev`

### Device information
* Brand: `samsung`
* Device: `a52q`
* Model: `SM-A525M`
* Id: `SQ3A.220605.009.A1`
* Product: `a52qnsxx`

### Firmware
* SDK: `32`
* Release: `12`
* Incremental: `eng.simon.20220704.144116`

**Comment by AlvaroBrey** [comment]
Same crash stack as #10633, so marking as duplicate

**Comment by AlvaroBrey** [comment]
Duplicate of #10633
