### ISSUE TITLE
crash when sharing into nextxloud app

### ISSUE THREAD

**Issue by Sir-Photch** [nextcloud/android#11305]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Share pdf file to be saved via nextcloud.

### Expected behaviour

Nextcloud lets me choose a folder.

### Actual behaviour

It crashes.

### Android version

latest

### Device brand and model

google pixel 7 pro

### Stock or custom OS?

Stock

### Nextcloud android app version

beta (see stacktrace)

### Nextcloud server version

latest stable

### Using a reverse proxy?

No

### Additional information

```
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
    at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:907)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:138)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFileByEncryptedRemotePath(FileDataStorageManager.java:122)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:118)
    at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.populateDirectoryList(ReceiveExternalFilesActivity.java:747)
    at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onStart(ReceiveExternalFilesActivity.java:258)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1548)
    at android.app.Activity.performStart(Activity.java:8377)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3671)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7878)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ExecInit.main(ExecInit.java:49)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20230121`
* Build flavor: `versionDev`

### Device information
* Brand: `google`
* Device: `cheetah`
* Model: `Pixel 7 Pro`
* Id: `TQ1A.230105.002`
* Product: `cheetah`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `2023011000`
```

**Comment by AlvaroBrey** [comment]
Yeah, this is a known bug  in the dev version and should have been fixed by #11287

**Comment by Sir-Photch** [comment]
Updates over F-Droid are pretty slow. Does Nextcloud have it's own repository with faster updates?

**Comment by AlvaroBrey** [comment]
> Updates over F-Droid are pretty slow. Does Nextcloud have it's own repository with faster updates?

Nope.

**Comment by galvalarzen** [comment]
> > Updates over F-Droid are pretty slow. Does Nextcloud have it's own repository with faster updates?
> 
> Nope. The dev version is also published in https://download.nextcloud.com/android/dev/, but it's a different build from the F-Droid one, so you won't be able to update from one to the other.

Link dont work dude

**Comment by AlvaroBrey** [comment]
I'm seeing more reports than usual for an issue like this, so I'm suspecting a lot of the users that reach this have the dev version installed without knowing it.

For reference: **There are two Nextcloud apps in F-Droid, the stable one and the dev one**.

- Stable: https://f-droid.org/en/packages/com.nextcloud.client/
- Dev: https://f-droid.org/en/packages/com.nextcloud.android.beta/

The dev version is autoupdated from this repo and is, by nature, _unstable_. If you are not okay with that, please uninstall the dev version and install the regular one.

**Comment by AlvaroBrey** [comment]
> > > Updates over F-Droid are pretty slow. Does Nextcloud have it's own repository with faster updates?
> > 
> > 
> > Nope. The dev version is also published in https://download.nextcloud.com/android/dev/, but it's a different build from the F-Droid one, so you won't be able to update from one to the other.
> 
> Link dont work dude

I've just triple-checked. Link works just fine. There may be a problem on your end.

**Comment by AlvaroBrey** [comment]
> I'm seeing more reports than expected for an issue like this, so I'm suspecting a lot of the users that reach this have the dev version installed without knowing it.
> 
> For reference: **There are two Nextcloud apps in F-Droid, the stable one and the dev one**.
> 
> * Stable: https://f-droid.org/en/packages/com.nextcloud.client/
> * Dev: https://f-droid.org/en/packages/com.nextcloud.android.beta/
> 
> The dev version is autoupdated from this repo and is, by nature, _unstable_. If you are not okay with that, please uninstall the dev version and install the regular one.

Additionally, if you have the dev version, and still want to keep the dev version, you'll **need to uninstall and reinstall the app** anyway to fix this crash.

**Comment by Apfelwurm** [comment]
@AlvaroBrey i found out because of that issue that i have installed the dev version on a whole lot of phones, without really noticing. I think it would be a good idea, to set the right image on the stable version, since it really does not light up when you search for nextlcoud because of the missing picture.

**Comment by AlvaroBrey** [comment]
> @AlvaroBrey i found out because of that issue that i have installed the dev version on a whole lot of phones, without really noticing. I think it would be a good idea, to set the right image on the stable version, since it really does not light up when you search for nextlcoud because of the missing picture.

I agree, and we recently added the image (#11193 ) but it won't be visible until next release

**Comment by Apfelwurm** [comment]
Btw for all that come across this issue: installing the stable version additionally to the dev version fixes the issue without deleting any data locally :)

**Comment by galvalarzen** [comment]
Exactly. Sounds good. Thank you 👍🙂

mandag den 30. januar 2023 skrev Alex ***@***.***>:
> @AlvaroBrey i found out because of that issue that i have installed the
dev version on a whole lot of phones, without really noticing. I think it
would be a good idea, to set the right image on the stable version, since
it really does not light up when you search for nextlcoud because of the
missing picture.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.<
https://ci4.googleusercontent.com/proxy/RGhmU6zwL_OLkYq5Pdz8YKumtGu8KlpAH5KneyqG8xqmEBQGvXuXadJQFu6K4nZhsLmxUJsxKPAqTMtgj1n2da1yNMwFo5C3ON4K7qxxHihkysdDMQX1mfK1yaylaDhzTsQ2_ttAsZcqBH5eVip8Ys1ZZQgDhHHzRQ5vwaelcUhr_1mCtgx77dr61lVcAKAfSMDGY3grIMN5dIbxmy36TMWueWi33UKSoILU8vlGp4Wuyqxvpg=s0-d-e1-ft#https://github.com/notifications/beacon/A5RTWS47UH3SRQBX3DSY65LWU7IZNA5CNFSM6AAAAAAUHPGXXOWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTST7AJT6.gif>Message
ID: ***@***.***>
