### ISSUE TITLE
NPE on `checkEncryptionStatus`

### ISSUE THREAD

**Issue by SofianeLasri** [nextcloud/android#11316]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Start the app
2. Wait for root folder to load
3. Open the menu
4. Click on the favorite link in the sidebar

### Expected behaviour

It is expected to load the favorite files and folders.

### Actual behaviour

It crash again and again.

### Android version

6.0.1

### Device brand and model

Samsung Galaxy Tab 10.5 SM-T800

### Stock or custom OS?

Stock

### Nextcloud android app version

30230191

### Nextcloud server version

lastest in stable branch

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "AsyncTask #5" java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:309)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
Caused by: Exception in thread "AsyncTask #5" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getDecryptedRemotePath()' on a null object reference
    at com.owncloud.android.utils.FileStorageUtils.checkEncryptionStatus(FileStorageUtils.java:468)
    at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:458)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:408)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:238)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:144)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:153)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.parseVirtuals(OCFileListAdapter.java:786)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.setData(OCFileListAdapter.java:684)
    at com.owncloud.android.ui.fragment.OCFileListSearchAsyncTask.doInBackground(OCFileListSearchAsyncTask.kt:70)
    at com.owncloud.android.ui.fragment.OCFileListSearchAsyncTask.doInBackground(OCFileListSearchAsyncTask.kt:33)
    at android.os.AsyncTask$2.call(AsyncTask.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30230191`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `chagallwifi`
* Model: `SM-T800`
* Id: `MMB29K`
* Product: `chagallwifizs`

### Firmware
* SDK: `23`
* Release: `6.0.1`
* Incremental: `T800ZSU1CQB3`

**Comment by pascalw** [comment]
I'm also affected by this. In my case it seems to prevent automatic upload too.
