### ISSUE TITLE
Crash after simply opening app and using biometric log in

### ISSUE THREAD

**Issue by DavidRLTG** [nextcloud/android#11319]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open app
2. use fingerprint scanner to log in
3. Asks for fingerprint scanner again
4. i scan again
5. asks for it again
6. I just go into recents then it asks again, I do it,
7. re enter the app after logging in from recents
8. I get a crash log

### Expected behaviour

I want to get in the app lmao

### Actual behaviour

crash after infinite log in

### Android version

13

### Device brand and model

Poco F3  / M2012K11AG

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

Dev Latest

### Nextcloud server version

...

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
    at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:907)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:138)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFileByEncryptedRemotePath(FileDataStorageManager.java:122)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:118)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2423)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1546)
    at android.app.Activity.performStart(Activity.java:8330)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3670)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7872)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20230124`
* Build flavor: `versionDev`

### Device information
* Brand: `POCO`
* Device: `alioth`
* Model: `M2012K11AG`
* Id: `TQ1A.230105.001.A2`
* Product: `alioth_global`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `eng.palayc.20230105.011416`

### Additional information

I use the ArrowOS custom ROM with MicroG.

**Comment by AlvaroBrey** [comment]
Duplicate of #11305
