### ISSUE TITLE
Crash while opening a subfolder

### ISSUE THREAD

**Issue by mat-l** [nextcloud/android#11320]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Open Nextcloud app
Move to subdirectory
Open subdirectory
Crash

### Expected behaviour

Open the subdirectory successfully

### Actual behaviour

I noticed the crashes after I have changed the top level folder "Documents" to the name "Documents_user-name" yesterday. Since then Nextcloud App crashes regularly if I now want to open subfolder where it has to show the files in the subfolders.

If I switch back the parents folder name to "Documents" it works again without any crashes.

### Android version

Harmony OS 2.0.0.268

### Device brand and model

Huawei P30

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.23.1

### Nextcloud server version

25.0.3

### Using a reverse proxy?

Yes

### Android logs

Crash information from the app:
### Cause of error
```java
Exception in thread "Thread-10" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getDecryptedRemotePath()' on a null object reference
    at com.owncloud.android.utils.FileStorageUtils.checkEncryptionStatus(FileStorageUtils.java:468)
    at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:458)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:408)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:238)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:929)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30230190`
* Build flavor: `generic`

### Device information
* Brand: `HUAWEI`
* Device: `HWELE`
* Model: `ELE-AL00`
* Id: `HUAWEIELE-AL00`
* Product: `ELE-AL00`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `10.1.0.162C00`

### Server error logs

```bash
No errors Werke produced
```

**Comment by mat-l** [comment]
The crash happens now always, also I have changed the name of the parent folder back to its original name. As of now the share menu of the ist not usable anymore. Therefore it would be great, if there would be a fix for it.

`
### Cause of error
```java
Exception in thread "Thread-34" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:929)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30240190`
* Build flavor: `generic`

### Device information
* Brand: `HUAWEI`
* Device: `HWELE`
* Model: `ELE-AL00`
* Id: `HUAWEIELE-AL00`
* Product: `ELE-AL00`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `10.1.0.162C00`
`
