### ISSUE TITLE
Crash on account selection (new installation from fdroid)

### ISSUE THREAD

**Issue by SublimeProphets** [nextcloud/android#11359]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Installation of latest version 1.21.6. from fdroid (nextcloud app 3.23.0 already installed and configured since a long time)
2. app starts up normal
3. hit button "account selection" 
4. choose an account 
5. allow access to account (android notification accepted)
6. wild crash appears

### Expected behaviour

Should work i guess, not sure what to expect afterwards, probably some decks ;-)

### Actual behaviour

Crashes with following error response
```
App Version: 1.21.6
App Version Code: 1021006
Server App Version: 1.7.3
App Flavor: fdroid

Files App Version Code: 30230090

---

OS Version: 4.9.332-perf+(gms-edfd6a4e)
OS API Level: 30
Device: FP3
Manufacturer: Fairphone
Model (and Product): FP3 (FP3)

---

it.niedermann.nextcloud.deck.exceptions.TraceableException: Sorry, a wild error appeared!

⚠️ If you want to tell us about the following issue, please make sure to censor sensitive data beforehand! ⚠️

Failed to run traceable code with arguments:
{"participant":{"primaryKey":"admin","uid":"admin","displayname":"admin","type":0},"type":0,"boardId":3,"permissionEdit":null,"permissionShare":null,"permissionManage":null,"owner":false,"id":1}
Cause: JsonNull
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseAcl(JsonToEntityParser.java:378)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.lambda$parseBoard$8(JsonToEntityParser.java:327)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser$$ExternalSyntheticLambda12.run(Unknown Source:6)
	at it.niedermann.nextcloud.deck.exceptions.TraceableException.makeTraceableIfFails(TraceableException.java:13)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseBoard(JsonToEntityParser.java:285)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseJsonObject(JsonToEntityParser.java:51)
	at it.niedermann.nextcloud.deck.api.NextcloudArrayDeserializer.deserialize(NextcloudArrayDeserializer.java:36)
	at it.niedermann.nextcloud.deck.api.NextcloudArrayDeserializer.deserialize(NextcloudArrayDeserializer.java:18)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.Gson.fromJson(Gson.java:1214)
	at com.google.gson.Gson.fromJson(Gson.java:1124)
	at com.google.gson.Gson.fromJson(Gson.java:1094)
	at com.nextcloud.android.sso.api.NextcloudAPI.convertStreamToTargetEntity(NextcloudAPI.java:159)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:130)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.UnsupportedOperationException: JsonNull
	at com.google.gson.JsonElement.getAsBoolean(JsonElement.java:162)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.lambda$parseAcl$9(JsonToEntityParser.java:386)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser$$ExternalSyntheticLambda15.run(Unknown Source:4)
	at it.niedermann.nextcloud.deck.exceptions.TraceableException.makeTraceableIfFails(TraceableException.java:13)
	... 24 more

```

### Android version

11 (Kernel-Version 4.9.332-perf+ #1 Wed Nov 23 17:13:15 CET 2022

### Device brand and model

Fairphone 3

### Stock or custom OS?

Stock

### Nextcloud android app version

3.23.0

### Nextcloud server version

24.0.6

### Using a reverse proxy?

Yes

### Additional information

Initially about 1 year ago with only one nextcloud account on my android it did NoT work as well...

**Comment by AlvaroBrey** [comment]
This looks like an issue in the Deck app, please report it there: https://github.com/stefan-niedermann/nextcloud-deck
