### ISSUE TITLE
Share to Nextcloud from apps not uploading `java.io.IOException: No such file or directory`

### ISSUE THREAD

**Issue by stephang** [nextcloud/android#11371]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

When uploading a file (image or pdf document) via Android's share feature, the upload silently fails.

I am aware that this issue was reported already in #7752, #7745, #7698 and #7587. However, having the latest app version, the problem remains in my case.

- Go into Gallery (or file manager)
- Select an image (or a file)
- Select Share > Nextcloud
- Select the Nextcloud destination path and tap *Upload*

The source app does not really matter. Uploading file from whatever app fails. Also uploading files from both location (internal or external storage) both won't work.

Uploading from within the Nextcloud app works however.

### Expected behaviour

Uploading should succeed.

### Actual behaviour

Uploading silently fails. After tapping **Upload** the focus switches back to the gallery (or file manager).

### Android version

11

### Device brand and model

Fairphone 3+

### Stock or custom OS?

Stock

### Nextcloud android app version

3.32.1

### Nextcloud server version

25.0.3

### Using a reverse proxy?

No

### Android logs

**Document upload**

```
00:00:18.457 20373 20373 D ReceiveExternalFilesActivity: Uploading file to dir /
00:00:18.491 20373 20373 D FileActivity: show loading dialog
00:00:18.529  1694  2089 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
00:00:18.530  4503  6491 I MediaProvider: Open with lower FS for /storage/emulated/0/Download/somefile.pdf. Uid: 10047
00:00:18.542  4503 17884 E MediaProvider: Creating or writing to a non-default top level directory is not allowed!
00:00:18.547  4503 17885 E MediaProvider: Creating or writing to a non-default top level directory is not allowed!
00:00:18.551 20373 20401 E CopyAndUploadContentUrisTask: Exception while copying content://com.android.providers.downloads.documents/document/msf%3A1000000082 to temporary file
00:00:18.551 20373 20401 E CopyAndUploadContentUrisTask: java.io.IOException: No such file or directory
00:00:18.551 20373 20401 E CopyAndUploadContentUrisTask:  at java.io.UnixFileSystem.createFileExclusively0(Native Method)
00:00:18.551 20373 20401 E CopyAndUploadContentUrisTask:  at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
00:00:18.551 20373 20401 E CopyAndUploadContentUrisTask:  at java.io.File.createNewFile(File.java:1008)
00:00:18.551 20373 20401 E CopyAndUploadContentUrisTask:  at com.owncloud.android.ui.asynctasks.CopyAndUploadContentUrisTask.doInBackground(CopyAndUploadContentUrisTask.java:170)
00:00:18.551 20373 20401 E CopyAndUploadContentUrisTask:  at com.owncloud.android.ui.asynctasks.CopyAndUploadContentUrisTask.doInBackground(CopyAndUploadContentUrisTask.java:50)
00:00:18.551 20373 20401 E CopyAndUploadContentUrisTask:  at android.os.AsyncTask$3.call(AsyncTask.java:394)
00:00:18.551 20373 20401 E CopyAndUploadContentUrisTask:  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:00:18.551 20373 20401 E CopyAndUploadContentUrisTask:  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
00:00:18.551 20373 20401 E CopyAndUploadContentUrisTask:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
00:00:18.551 20373 20401 E CopyAndUploadContentUrisTask:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
00:00:18.551 20373 20401 E CopyAndUploadContentUrisTask:  at java.lang.Thread.run(Thread.java:923)
00:00:18.569 20373 20373 D ReceiveExternalFilesActivity: onPause() ending
00:00:18.590 20373 20373 D FileActivity: dismiss loading dialog
00:00:18.601  1694  2217 W ActivityTaskManager: Finishing task with all activities already finished
00:00:18.601  1694  2217 W ActivityTaskManager: Duplicate finish request for r=ActivityRecord{9123699 u0 com.nextcloud.client/com.owncloud.android.ui.activity.ReceiveExternalFilesActivity t723 f}}
00:00:18.653  2085  2114 I ndroid.systemu: NativeAlloc concurrent copying GC freed 12748(701KB) AllocSpace objects, 3(60KB) LOS objects, 66% free, 14MB/43MB, paused 104us total 113.486ms
00:00:18.668 20298 20509 I ProvidersCache: Provider returned no roots. Possibly naughty: at.bitfire.davdroid.webdav
00:00:18.812 30950 30950 I GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3227 
00:00:18.813 30950 30950 I GoogleInputMethodService: GoogleInputMethodService.updateDeviceLockedStatus():2087 repeatCheckTimes = 0, unlocked = true
00:00:18.814 30950 30950 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1877 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x0 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=com.google.android.documentsui fieldId=-1 fieldName=null extras=null}, false)
00:00:18.814 30950 30950 I GoogleInputMethodService: GoogleInputMethodService.shouldHideHeaderOnInitialState():4008 ShouldHideHeaderOnInitialState = false
00:00:18.814 30950 30950 I GoogleInputMethodService: GoogleInputMethodService.updateDeviceLockedStatus():2087 repeatCheckTimes = 2, unlocked = true
00:00:19.396 20373 20373 D ReceiveExternalFilesActivity: onStop() ending
00:00:19.404 20373 20373 D ReceiveExternalFilesActivity: onDestroy() ending
00:00:19.415 20373 20373 V OperationsService: Destroying service
```

**Image upload**
```log
00:00:20.172 D ReceiveExternalFilesActivity: Populating view with content of : /
00:00:20.235 D OwnCloudClient #0: REQUEST GET /nc/status.php
00:00:20.237 D AdvancedSslSocketFactory: Creating SSL Socket with remote CENSORED:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@35cb306
00:00:20.237 D AdvancedSslSocketFactory:  ... with connection timeout 60000 and socket timeout 60000
00:00:20.262 I ServerNameIndicator: SSLSocket implementation: org.conscrypt.Java8EngineSocket
00:00:20.262 I ServerNameIndicator: SNI done, hostname: CENSORED
00:00:20.416 W HttpMethodBase: Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
00:00:20.430 D UpdateOCVersionOperation: Got new OC version 25.0.2.3
00:00:20.430 I UpdateOCVersionOperation: Check for update of Nextcloud server version at https://CENSORED/nc/remote.php/dav/files/myuser: Operation finished with HTTP status code -1 (success)
00:00:20.441 D OwnCloudClient #0: REQUEST GET /nc/ocs/v2.php/cloud/capabilities
00:00:21.618 D ReceiveExternalFilesActivity: Uploading file to dir /
00:00:21.654 D FileActivity: show loading dialog
00:00:21.752 E CopyAndUploadContentUrisTask: Exception while copying content://media/external/images/media/1000000090 to temporary file
00:00:21.752 E CopyAndUploadContentUrisTask: java.io.IOException: No such file or directory
00:00:21.752 E CopyAndUploadContentUrisTask:  at java.io.UnixFileSystem.createFileExclusively0(Native Method)
00:00:21.752 E CopyAndUploadContentUrisTask:  at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
00:00:21.752 E CopyAndUploadContentUrisTask:  at java.io.File.createNewFile(File.java:1008)
00:00:21.752 E CopyAndUploadContentUrisTask:  at com.owncloud.android.ui.asynctasks.CopyAndUploadContentUrisTask.doInBackground(CopyAndUploadContentUrisTask.java:170)
00:00:21.752 E CopyAndUploadContentUrisTask:  at com.owncloud.android.ui.asynctasks.CopyAndUploadContentUrisTask.doInBackground(CopyAndUploadContentUrisTask.java:50)
00:00:21.752 E CopyAndUploadContentUrisTask:  at android.os.AsyncTask$3.call(AsyncTask.java:394)
00:00:21.752 E CopyAndUploadContentUrisTask:  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:00:21.752 E CopyAndUploadContentUrisTask:  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
00:00:21.752 E CopyAndUploadContentUrisTask:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
00:00:21.752 E CopyAndUploadContentUrisTask:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
00:00:21.752 E CopyAndUploadContentUrisTask:  at java.lang.Thread.run(Thread.java:923)
00:00:21.756 D ReceiveExternalFilesActivity: onPause() ending
00:00:21.773 D FileActivity: dismiss loading dialog
00:00:22.228 D GetCapabilitiesRemoteOperation: Capabilities not modified
00:00:22.229 D GetCapabilitiesRemoteOperation: *** Get Capabilities completed 
00:00:22.459 D ReceiveExternalFilesActivity: onStop() ending
00:00:22.471 D ReceiveExternalFilesActivity: onDestroy() ending
00:00:22.480 V OperationsService: Destroying service
00:00:22.683 I RefreshFolderOperation: Got display name: UserInfo(id=myuser, enabled=null, displayName=myuser, email=, phone=, address=, website=, twitter=, quota=Quota(free=99723005952, used=6780410406, total=106503416358, relative=6.37, quota=-3), groups=[])
00:00:22.683 D RefreshFolderOperation: Checking changes in myuser@CENSORED/nc/
00:00:22.690 W System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
00:00:22.690 W System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
00:00:22.690 W System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
00:00:22.805 D OwnCloudClient #0: REQUEST PROPFIND /nc/remote.php/dav/files/myuser/
00:00:22.959 I RefreshFolderOperation: Checked myuser@CENSORED/nc/ : changed
00:00:22.975 D OwnCloudClient #0: REQUEST PROPFIND /nc/remote.php/dav/files/myuser/
00:00:23.393 I ReadFolderRemoteOperation: Synchronized /: Operation finished with HTTP status code 207 (success)
00:00:23.393 D RefreshFolderOperation: Synchronizing myuser@CENSORED/nc/
00:00:23.404 D RefreshFolderOperation: Remote folder / changed - starting update of local data 
00:00:23.439 D FileDataStorageManager: Saving folder / with 14 children and 1 files to remove
00:00:23.511 D FileDataStorageManager: Sending 16 operations to FileContentProvider
00:00:23.512 D FileContentProvider: applying batch in provider com.owncloud.android.providers.FileContentProvider@7d34672 (temporary: false)
00:00:23.566 D FileContentProvider: applied batch in provider com.owncloud.android.providers.FileContentProvider@7d34672
00:00:23.593 D RefreshFolderOperation: Send broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED
00:00:23.596 D OwnCloudClient #0: REQUEST GET /nc/ocs/v2.php/apps/files_sharing/api/v1/shares
00:00:23.811 D GetSharesForFileRemoteOperation: Got 0 shares
00:00:23.855 D FileDataStorageManager: Sending 14 operations to FileContentProvider
00:00:23.856 D FileContentProvider: applying batch in provider com.owncloud.android.providers.FileContentProvider@7d34672 (temporary: false)
00:00:23.903 D FileContentProvider: applied batch in provider com.owncloud.android.providers.FileContentProvider@7d34672
00:00:23.903 D RefreshFolderOperation: Send broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_SHARES_SYNCED
```

### Additional information

Using external storage with SD card.

**Comment by stephang** [comment]
**Workaround**: Sharing works when I remove and reinstall the app. 

Not sure if we can close this issue as the problem's root cause is not solved. Without the workaround, the problem persists with app version 3.24.1.

Any thoughts? @tobiasKaminsky @AndyScherzinger

**Comment by Heusini** [comment]
I have the same error unfortunately reinstalling the app did not help. (e.g. i cannot share but uploading within the Nextcloud app works fine)

### Android version

12
### Device brand and model

Samsung Galaxy S10
### Stock or custom OS?

Stock
### Nextcloud android app version

3.24.1

### Nextcloud server version

26.0.0
### Using a reverse proxy?

No

**Comment by joshtrichards** [comment]
> Not sure if we can close this issue as the problem's root cause is not solved. Without the workaround, the problem persists with app version 3.24.1.

@stephang Given the error message and the workaround I wonder if it was an Android permissions issue. The other referenced issues look to be unrelated (at least from a cursory review). Let us know if it re-occurs. 

@Heusini - To clarify: Are you seeing the same error/stack trace logged or merely similar symptoms?

**Comment by Heusini** [comment]
I don't have the problem anymore with version 3.26.0 of the app. I did not change my permissions but I never checked error/stack trace so could have been just same symptoms.

**Comment by joshtrichards** [comment]
Closing this out since haven't been any further reports in >12 months.
