### ISSUE TITLE
Automatic photo upload crash with 3.24.0 - Android 8 - while requesting permissions

### ISSUE THREAD

**Issue by nick81nrw** [nextcloud/android#11386]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Start Nextcloud
2. Setting
3. automatic upload
4. crash

### Expected behaviour

The photo upload window should appear. Since yesterday this behavior changed

### Actual behaviour

In background the app ask for permission to photo folder, but the app chraches immediately.

### Android version

8

### Device brand and model

BG Aquaris X

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.0

### Nextcloud server version

24.0.8

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "DefaultDispatcher-worker-1" java.lang.StackOverflowError: stack size 1037KB
    at com.owncloud.android.utils.PermissionUtil.requestExternalStoragePermission(PermissionUtil.kt:122)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onRequestPermissionsResult(SyncedFoldersActivity.kt:783)
    at android.app.Activity.requestPermissions(Activity.java:4392)
    at androidx.core.app.ActivityCompat$Api23Impl.requestPermissions(ActivityCompat.java:893)
    at androidx.core.app.ActivityCompat.requestPermissions(ActivityCompat.java:557)
    at com.owncloud.android.utils.PermissionUtil.requestStoragePermission$doRequest(PermissionUtil.kt:162)
    at com.owncloud.android.utils.PermissionUtil.requestStoragePermission(PermissionUtil.kt:187)
  
[.............................]
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30240090`
* Build flavor: `gplay`

### Device information
* Brand: `bq`
* Device: `bardock`
* Model: `Aquaris X`
* Id: `OPM1.171019.026`
* Product: `bardock`

### Firmware
* SDK: `27`
* Release: `8.1.0`
* Incremental: `2394`

**Comment by NorbiPeti** [comment]
I get the same error on Android 9 (Huawei FIG-LX1) using Nextcloud 23.1 and 24.0.

**Comment by joshtrichards** [comment]
If you manually give the app "All files access" (the permission it's likely requesting) or the equivalent[1] for your device does this go away?

Still a bug if the app is requesting this and crashing, but trying to at least confirm it's only a request problem and not two problems.

[1]Unfortunately it's named different things and often separate from the other app permissions).

**Comment by NorbiPeti** [comment]
In my case I can see the app correctly handling the situation now. On Android 9 using Nextcloud Android 3.28.0 I get a popup requesting access to the storage. If I deny the permission I get a toast notification asking me to give access. If I do, it works fine.
