### ISSUE TITLE
Nextcloud Android Error on Accepting Requests i.e. Deck invitations: `java.lang.IllegalArgumentException: host parameter is null`

### ISSUE THREAD

**Issue by shabs76** [nextcloud/android#11398]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

To reproduce this error you need to share, deck board to other users. When other users receives the invitation on their Android the error will happen. I haven't tested ios yet.

### Expected behaviour

Expected accept request to succeed and allow user to join.

### Actual behaviour

The following error occurs when user accept the request.
### Cause of error
```java
Exception in thread "AsyncTask #2" java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$4.done(AsyncTask.java:399)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
    at java.util.concurrent.FutureTask.run(FutureTask.java:271)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:919)
Caused by: Exception in thread "AsyncTask #2" java.lang.IllegalArgumentException: host parameter is null
    at org.apache.commons.httpclient.HttpConnection.<init>(HttpConnection.java:206)
    at org.apache.commons.httpclient.HttpConnection.<init>(HttpConnection.java:155)
    at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionWithReference.<init>(MultiThreadedHttpConnectionManager.java:1145)
    at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$ConnectionPool.createConnection(MultiThreadedHttpConnectionManager.java:762)
    at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager.doGetConnection(MultiThreadedHttpConnectionManager.java:476)
    at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager.getConnectionWithTimeout(MultiThreadedHttpConnectionManager.java:416)
    at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:153)
    at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
    at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
    at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:195)
    at com.owncloud.android.ui.asynctasks.NotificationExecuteActionTask.doInBackground(NotificationExecuteActionTask.java:70)
    at com.owncloud.android.ui.asynctasks.NotificationExecuteActionTask.doInBackground(NotificationExecuteActionTask.java:22)
    at android.os.AsyncTask$3.call(AsyncTask.java:378)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:919)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30230191`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `star2qltesq`
* Model: `SM-G965U`
* Id: `QP1A.190711.020`
* Product: `star2qltesq`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `G965USQS8FTJ6`

### Android version

10

### Device brand and model

Samsung 

### Stock or custom OS?

Stock

### Nextcloud android app version

30230191

### Nextcloud server version

25

### Using a reverse proxy?

No

**Comment by joshtrichards** [comment]
Hi @shabs76 - Thanks for your report. This particularly error has always previously been either a misbehaving reverse proxy/web server (i.e. see #10664) or a bug in the server-side app generating the notification.

I tested this morning and I'm unable to reproduce this behavior today. Are you still experiencing it?
