### ISSUE TITLE
Crash when going back in the folder three while sharing an image to Nextcloud

### ISSUE THREAD

**Issue by SamuXzX** [nextcloud/android#11465]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Reach an image in the browser (you are at the actual URL of the image).
2. Touch the upper-left arrow or go back with Android gestures to go one folder level up from were the app opened.
3. Acknowledge the crashing.

### Expected behaviour

While loading an image to Nextcloud with the Share function of Android I should be able to navigate the folder three freely.

### Actual behaviour

The app crashes when trying to go back.

I cannot test going down in a folder because the folder the apl opens when I share the image hasn't got any subfolder and I cannot move to a folder that has it.

### Android version

11

### Device brand and model

Motorola Moto G 5G Plus

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.1

### Nextcloud server version

25.0.4

### Using a reverse proxy?

Yes

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.datamodel.OCFile.canWrite()' on a null object reference
    at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onCreateOptionsMenu(ReceiveExternalFilesActivity.java:1034)
    at android.app.Activity.onCreatePanelMenu(Activity.java:4274)
    at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:521)
    at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:95)
    at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3429)
    at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:458)
    at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
    at android.view.Choreographer.doCallbacks(Choreographer.java:796)
    at android.view.Choreographer.doFrame(Choreographer.java:727)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:250)
    at android.app.ActivityThread.main(ActivityThread.java:7755)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30240190`
* Build flavor: `generic`

### Device information
* Brand: `motorola`
* Device: `nairo`
* Model: `moto g 5G plus`
* Id: `RPNS31.Q4U-39-27-9-2-9`
* Product: `nairo_retaile`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `9ab668`

**Comment by SamuXzX** [comment]
Found obviosuly similar issue, so this is a duplicate:  #11207. Sorry.
