### ISSUE TITLE
Unable to sync folder in background

### ISSUE THREAD

**Issue by almet** [nextcloud/android#11466]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Select a folder and sync it. 

### Expected behaviour

It should sync 

### Actual behaviour

Im getting an error, see below 

### Android version

9

### Device brand and model

Fairphone 3

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.24.1

### Nextcloud server version

Not found

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "Syncfolder thread" java.lang.IllegalStateException: Not allowed to start service Intent { act=SYNC_FOLDER cmp=com.nextcloud.client/com.owncloud.android.services.OperationsService (has extras) }: app is in background uid UidRecord{1368f57 u0a209 SVC  bg:+1m0s208ms idle change:idle procs:2 seq(0,0,0)}
    at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
    at android.app.ContextImpl.startService(ContextImpl.java:1532)
    at android.content.ContextWrapper.startService(ContextWrapper.java:664)
    at com.owncloud.android.operations.SynchronizeFolderOperation.startSyncFolderOperation(SynchronizeFolderOperation.java:540)
    at com.owncloud.android.operations.SynchronizeFolderOperation.classifyFileForLaterSyncOrDownload(SynchronizeFolderOperation.java:387)
    at com.owncloud.android.operations.SynchronizeFolderOperation.synchronizeData(SynchronizeFolderOperation.java:335)
    at com.owncloud.android.operations.SynchronizeFolderOperation.fetchAndSyncRemoteFolder(SynchronizeFolderOperation.java:220)
    at com.owncloud.android.operations.SynchronizeFolderOperation.run(SynchronizeFolderOperation.java:146)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:205)
    at com.owncloud.android.services.SyncFolderHandler.doOperation(SyncFolderHandler.java:115)
    at com.owncloud.android.services.SyncFolderHandler.handleMessage(SyncFolderHandler.java:88)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193)
    at android.os.HandlerThread.run(HandlerThread.java:65)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30240190`
* Build flavor: `gplay`

### Device information
* Brand: `Fairphone`
* Device: `FP3`
* Model: `FP3`
* Id: `PQ3A.190801.002`
* Product: `FP3`

### Firmware
* SDK: `28`
* Release: `9`
* Incremental: `eng.root.20220412.152644`

**Comment by joshtrichards** [comment]
I can't reproduce this on my Android v9 device, but I'm running stock not unofficial firmware.

Looks like you are using e/os perhaps?

Couple ideas:

* Make sure you're running a recent version of e/os
* Try the non-gplay compile of the Nextcloud Android client (via e.g. via F-Droid)

Also:

https://doc.e.foundation/devices/FP3
https://support.fairphone.com/hc/en-us/articles/11351328932497

**Comment by almet** [comment]
Hi, thanks for your quick feedback.

Yes, I'm running e/os, you're right. I'm running the latest version available (0.23-20220412177701).

I've installed the latest version from F-Droid, and I'm still having an issue, here are the logs : 

```java
Exception in thread "Syncfolder thread" java.lang.IllegalStateException: Not allowed to start service Intent { act=SYNC_FOLDER cmp=com.nextcloud.client/com.owncloud.android.services.OperationsService (has extras) }: app is in background uid UidRecord{7fa81b0 u0a210 SVC  bg:+1m0s615ms idle change:idle procs:1 seq(7,7,7)}
    at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
    at android.app.ContextImpl.startService(ContextImpl.java:1532)
    at android.content.ContextWrapper.startService(ContextWrapper.java:664)
    at com.owncloud.android.operations.SynchronizeFolderOperation.startSyncFolderOperation(SynchronizeFolderOperation.java:540)
    at com.owncloud.android.operations.SynchronizeFolderOperation.classifyFileForLaterSyncOrDownload(SynchronizeFolderOperation.java:387)
    at com.owncloud.android.operations.SynchronizeFolderOperation.synchronizeData(SynchronizeFolderOperation.java:335)
    at com.owncloud.android.operations.SynchronizeFolderOperation.fetchAndSyncRemoteFolder(SynchronizeFolderOperation.java:220)
    at com.owncloud.android.operations.SynchronizeFolderOperation.run(SynchronizeFolderOperation.java:146)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:205)
    at com.owncloud.android.services.SyncFolderHandler.doOperation(SyncFolderHandler.java:115)
    at com.owncloud.android.services.SyncFolderHandler.handleMessage(SyncFolderHandler.java:88)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193)
    at android.os.HandlerThread.run(HandlerThread.java:65)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30240190`
* Build flavor: `generic`

### Device information
* Brand: `Fairphone`
* Device: `FP3`
* Model: `FP3`
* Id: `PQ3A.190801.002`
* Product: `FP3`

### Firmware
* SDK: `28`
* Release: `9`
* Incremental: `eng.root.20220412.152644`

**Comment by joshtrichards** [comment]
Hi @almet - From the looks of it you're *not* running the latest. e/os only shows minor updates on your phone. You're three major generations back and running a build e/os doesn't even support any longer: you're on P/Pie (9) and the FP3 is up to S/Snow (12). 

https://community.e.foundation/t/week-23-2022-development-and-testing-updates/41605
https://doc.e.foundation/devices

Upgrades are **not** straightforward with e/os from what I've encountered - you have to upgrade the stock (manufacturer) image I believe first then install the current e/os. Those links I previously provided provide some hints as to the direction you'll need to go if you decide to upgrade to a more current release. Make sure you back up your data!

Fortunately I believe you're on one of the better supported devices for e/os.

You can find some assistance over at the e/os specific forum for your device: https://community.e.foundation/c/e-devices/fairphone/61 (for upgrading and for running the Nextcloud client app on it - there are numerous folks running the Nextcloud client on e/os there!)

P.S. Please verify anything I've stated above - I don't keep up on e/os development.

**Comment by almet** [comment]
Thanks a lot for your input, It helps, and it's very nice of you to spend this time to help me here.

It seems to be way more complex that I previously thought. I will follow the links you gave me and try to upgrade my e/os install 👍 

I'm closing this for now as I believe it's more related to my installation (out of date) than due to NC itself.
