### ISSUE TITLE
Error on exporting larg amount of photos : `java.lang.IllegalStateException: Data cannot occupy more than` ...

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/android#11477]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Go into a folder with 900 photos 
Select all 
Export 
Crash 

### Expected behaviour

Should not crash

### Actual behaviour

Application crashes

### Android version

13

### Device brand and model

S22 Ultra 5G

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.1

### Nextcloud server version

26.0.0

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized
    at androidx.work.Data.toByteArrayInternal(Data.java:407)
    at androidx.work.Data$Builder.build(Data.java:957)
    at com.nextcloud.client.jobs.BackgroundJobManagerImpl.startImmediateFilesExportJob(BackgroundJobManagerImpl.kt:311)
    at com.owncloud.android.ui.helpers.FileOperationsHelper.exportFiles(FileOperationsHelper.java:1050)
    at com.owncloud.android.ui.fragment.OCFileListFragment.onFileActionChosen(OCFileListFragment.java:1197)
    at com.owncloud.android.ui.fragment.OCFileListFragment.lambda$openActionsMenu$5$com-owncloud-android-ui-fragment-OCFileListFragment(OCFileListFragment.java:596)
    at com.owncloud.android.ui.fragment.OCFileListFragment$$ExternalSyntheticLambda5.onResult(Unknown Source:4)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.setResultListener$lambda$6(FileActionsBottomSheet.kt:177)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.$r8$lambda$zNDoKduEKPEn6E5e6C9MtKRmIro(Unknown Source:0)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$$ExternalSyntheticLambda1.onFragmentResult(Unknown Source:2)
    at androidx.fragment.app.FragmentManager$LifecycleAwareResultListener.onFragmentResult(FragmentManager.java:249)
    at androidx.fragment.app.FragmentManager.setFragmentResult(FragmentManager.java:925)
    at androidx.fragment.app.FragmentKt.setFragmentResult(Fragment.kt:33)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.dispatchActionClick(FileActionsBottomSheet.kt:295)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.access$dispatchActionClick(FileActionsBottomSheet.kt:61)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$onCreateView$2.invoke(FileActionsBottomSheet.kt:96)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$onCreateView$2.invoke(FileActionsBottomSheet.kt:95)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.onCreateView$lambda$1(FileActionsBottomSheet.kt:95)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.$r8$lambda$_ZVdO424AE_9Va9J36Ka295XXOw(Unknown Source:0)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$$ExternalSyntheticLambda3.onChanged(Unknown Source:2)
    at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
    at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
    at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
    at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
    at com.nextcloud.ui.fileactions.FileActionsViewModel.onClick(FileActionsViewModel.kt:156)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.inflateActionView$lambda$11$lambda$10(FileActionsBottomSheet.kt:278)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.$r8$lambda$8LHG1EjWT6gxYABWpcaRLD_Z_YY(Unknown Source:0)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
    at android.view.View.performClick(View.java:7892)
    at android.view.View.performClickInternal(View.java:7869)
    at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
    at android.view.View$PerformClick.run(View.java:30880)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8757)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30240190`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `b0q`
* Model: `SM-S908U1`
* Id: `TP1A.220624.014`
* Product: `b0quew`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `S908U1UES2CWB7`

**Comment by AndyXheli** [comment]
Still an issue
