### ISSUE TITLE
NPE when sharing files from another app to Nextcloud

### ISSUE THREAD

**Issue by glalejos** [nextcloud/android#11496]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Steps to reproduce on my phone:
- Select files to share in source App
- Push "share"
- Select Nextcloud
- The last *group directory* used to share files is displayed
- Push "back" to browse parent directory
- NPE is risen

I believe that this will be difficult to reproduce because I think that it is caused because an inconsistent state in the server (however, the Android App should be able to recover).

Sequence of events:
- Some time ago: share files to group directory: worked fine.
- Some time without sharing files (last browsed directory when sharing files was a group directory)
- A few days ago: server underwent upgrade. Group folders broken (they don't show anymore in the Nextcloud web-ui, and I can't recreate, I believe that the underlying files are still there, but need to confirm)
- Now my Nextcloud Android App tries to refer to that directory whenever I share anything, but the directory is in an inconsistent state and can no longer be browsed.

Output generated by the Nextcloud Android App:

### Cause of error
```java
Exception in thread "Thread-28" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:229)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30230190`
* Build flavor: `generic`

### Device information
* Brand: `Fairphone`
* Device: `FP4`
* Model: `FP4`
* Id: `SKQ1.220201.001`
* Product: `FP4eea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `SP21`

### Expected behaviour

I can't find a way to step out of the loop. The Nextcloud Android App should determine whether it's current directory handler is valid, and if not fallback to the home directory(or at least provide controls to the user to jump to well known directories).

### Actual behaviour

NPE is risen.

### Android version

11 (TBC)

### Device brand and model

Fair phone - FP4

### Stock or custom OS?

Stock

### Nextcloud android app version

30230190

### Nextcloud server version

26 (TBC)

### Using a reverse proxy?

Yes

**Comment by joshtrichards** [comment]
Dup of #11207 (and others). There's a fix pending.
