### ISSUE TITLE
Crash while trying to set up autoupload

### ISSUE THREAD

**Issue by olegkrutov** [nextcloud/android#11527]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Install fresh NC client version ("thanks" to f-droid, it just removed flawlessly worked 3.17.1 instead of upgrade so I needed to install app from scratch. No matter where app is installed from - f-droid, getapps, google play, bug is still here.  Version 1.23.1 (the most old version available on f-droid)  crashes too.
2. Enter your credentials, observe files list and go to Settings _ Auto-upload (I have non-English interface so I can be not precise here)
3. See crash dump

### Expected behaviour

Can set auto upload folders

### Actual behaviour

Crash

### Android version

12

### Device brand and model

Xiaomi redmi note 7

### Stock or custom OS?

Stock

### Nextcloud android app version

3.23.1, 3.24.1

### Nextcloud server version

25

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Unable to resume activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.SecurityException: uid 10316 cannot get user data for accounts of type: nextcloud
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4279)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4311)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:224)
    at android.app.ActivityThread.main(ActivityThread.java:7590)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: Exception in thread "main" java.lang.SecurityException: uid 10316 cannot get user data for accounts of type: nextcloud
    at android.os.Parcel.createException(Parcel.java:2074)
    at android.os.Parcel.readException(Parcel.java:2042)
    at android.os.Parcel.readException(Parcel.java:1990)
    at android.accounts.IAccountManager$Stub$Proxy.getUserData(IAccountManager.java:1441)
    at android.accounts.AccountManager.getUserData(AccountManager.java:516)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.<init>(OCFileListAdapter.java:157)
    at com.owncloud.android.ui.fragment.OCFileListFragment.setAdapter(OCFileListFragment.java:431)
    at com.owncloud.android.ui.fragment.OCFileListFragment.onActivityCreated(OCFileListFragment.java:374)
    at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3137)
    at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:579)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:264)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
    at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:495)
    at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:312)
    at com.owncloud.android.ui.activity.BaseActivity.onResume(BaseActivity.java:91)
    at com.owncloud.android.ui.activity.DrawerActivity.onResume(DrawerActivity.java:973)
    at com.owncloud.android.ui.activity.FileActivity.onResume(FileActivity.java:251)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onResume(FileDisplayActivity.java:1096)
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1454)
    at android.app.Activity.performResume(Activity.java:8050)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4269)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4311)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:224)
    at android.app.ActivityThread.main(ActivityThread.java:7590)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: Exception in thread "main" android.os.RemoteException: Remote stack trace:
	at com.android.server.accounts.AccountManagerService.getUserData(AccountManagerService.java:1562)
	at android.accounts.IAccountManager$Stub.onTransact(IAccountManager.java:492)
	at com.android.server.accounts.AccountManagerService.onTransact(AccountManagerService.java:1074)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)


```

### App information
* ID: `com.nextcloud.client`
* Version: `30240290`
* Build flavor: `gplay`

### Device information
* Brand: `xiaomi`
* Device: `lavender`
* Model: `Redmi Note 7`
* Id: `QKQ1.190910.002`
* Product: `lavender_ru`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `V12.5.1.0.QFGRUXM`

**Comment by olegkrutov** [comment]
I found that no permission to storage access were given to an app. I think that this issue must be closed but I didn't get why no permissions were requested during app installation or auto-upload setting.
