### ISSUE TITLE
Crash when trying to edit a Note 

### ISSUE THREAD

**Issue by mat-m** [nextcloud/android#11529]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Display a note from Notes app
2. Click on Edit 

### Expected behaviour

Prompt for app selection or Launch Markor app 

### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Fragment FileActionsBottomSheet{595d665} (01e98077-bdd3-4bcf-8634-51db1e6e7d32) not associated with a fragment manager.
    at androidx.fragment.app.Fragment.getParentFragmentManager(Fragment.java:1107)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.dispatchActionClick(FileActionsBottomSheet.kt:296)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.access$dispatchActionClick(FileActionsBottomSheet.kt:61)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$onCreateView$2.invoke(FileActionsBottomSheet.kt:96)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$onCreateView$2.invoke(FileActionsBottomSheet.kt:95)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.onCreateView$lambda$1(FileActionsBottomSheet.kt:95)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.$r8$lambda$_ZVdO424AE_9Va9J36Ka295XXOw(Unknown Source:0)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$$ExternalSyntheticLambda3.onChanged(Unknown Source:2)
    at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
    at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
    at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
    at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
    at com.nextcloud.ui.fileactions.FileActionsViewModel.onClick(FileActionsViewModel.kt:156)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.inflateActionView$lambda$11$lambda$10(FileActionsBottomSheet.kt:278)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.$r8$lambda$8LHG1EjWT6gxYABWpcaRLD_Z_YY(Unknown Source:0)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
    at android.view.View.performClick(View.java:7506)
    at android.view.View.performClickInternal(View.java:7483)
    at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
    at android.view.View$PerformClick.run(View.java:29357)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7884)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30240290`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `oriole`
* Model: `Pixel 6`
* Id: `TQ2A.230305.008.E1`
* Product: `oriole`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `9677224`

### Android version

13

### Device brand and model

Pixel 6

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.2

### Nextcloud server version

26

### Using a reverse proxy?

Yes

### Additional information

Bug report as suggested by the app

**Comment by tobiasKaminsky** [comment]
Can you add some screenshots,  as I currently fail to reproduce it?
