### ISSUE TITLE
crash on opening encrypted folder

### ISSUE THREAD

**Issue by p5n** [nextcloud/android#11536]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. open ancient encrypted folder
2. app crashed

Encrypted folder that I created recently works well.

I executed 2 occ commands
```
  496  occ encryption:fix-encrypted-version
  508  occ encryption:scan:legacy-format
```
it doesn't help

### Expected behaviour

opened folder

### Actual behaviour

crash

### Android version

13

### Device brand and model

samsung m12

### Stock or custom OS?

Stock

### Nextcloud android app version

Version: `30240190`

### Nextcloud server version

nextcloud 26.0.0-2

### Using a reverse proxy?

Yes

### Android logs

Mon 17 Apr 2023 07:10:35 PM  - sergej: ### Cause of error
```java
Exception in thread "Thread-15" com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 1.1 at line 102 column 23 path $.metadata.version
    at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:251)
    at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:241)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393)
    at com.google.gson.Gson.fromJson(Gson.java:1227)
    at com.google.gson.Gson.fromJson(Gson.java:1137)
    at com.google.gson.Gson.fromJson(Gson.java:1047)
    at com.google.gson.Gson.fromJson(Gson.java:1014)
    at com.owncloud.android.utils.EncryptionUtils.deserializeJSON(EncryptionUtils.java:132)
    at com.owncloud.android.utils.EncryptionUtils.downloadFolderMetadata(EncryptionUtils.java:243)
    at com.owncloud.android.operations.RefreshFolderOperation.getDecryptedFolderMetadata(RefreshFolderOperation.java:551)
    at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:474)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:409)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:239)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:1012)
Caused by: Exception in thread "Thread-15" java.lang.NumberFormatException: Expected an int but was 1.1 at line 102 column 23 path $.metadata.version
    at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1218)
    at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:249)
    at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:241)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393)
    at com.google.gson.Gson.fromJson(Gson.java:1227)
    at com.google.gson.Gson.fromJson(Gson.java:1137)
    at com.google.gson.Gson.fromJson(Gson.java:1047)
    at com.google.gson.Gson.fromJson(Gson.java:1014)
    at com.owncloud.android.utils.EncryptionUtils.deserializeJSON(EncryptionUtils.java:132)
    at com.owncloud.android.utils.EncryptionUtils.downloadFolderMetadata(EncryptionUtils.java:243)
    at com.owncloud.android.operations.RefreshFolderOperation.getDecryptedFolderMetadata(RefreshFolderOperation.java:551)
    at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:474)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:409)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:239)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30240190`
* Build flavor: `generic`

### Device information
* Brand: `samsung`
* Device: `m12`
* Model: `SM-M127F`
* Id: `TP1A.220624.014`
* Product: `m12nsser`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `M127FXXU3CVL2`

### Server error logs

```bash
mostly no logs, just couple of propfind+207 and get+200 requests in apache logs
```

**Comment by viendocraz** [comment]
Also experiencing a crash on trying to open encrypted folder on fresh install of latest android app from Fdroid and with desktop client v3.8.1 and latest Nextcloud server. I enter mnemonic and then app crashes and says something like `exception in thread JsonSyntaxException expected int but was 1.2`.

**Comment by viendocraz** [comment]
https://github.com/nextcloud/desktop/issues/5629

**Comment by joshtrichards** [comment]
There were changes made to the E2E meta-data version code in #11630 released in Android v3.26.0. Can you confirm this behavior still exists in the newer client?

**Comment by joshtrichards** [comment]
> I executed 2 occ commands 
> 496  occ encryption:fix-encrypted-version
> 508  occ encryption:scan:legacy-format

These commands are for server-side encryption not client-side encryption. Are you trying to use them together?

**Comment by joshtrichards** [comment]
Fixed in #11630
