### ISSUE TITLE
Can't use app with untrusted cert: `android.util.AndroidRuntimeException: requestFeature() must be called before adding content`

### ISSUE THREAD

**Issue by HyperPaint** [nextcloud/android#11677]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Generate certificate at freessl.org. Certificates from this CA not installed in my phone and cannot be installed due to android-xiaomi bug.
2. Open app and try connect to server. The earlier application was already working with the server, so it doesn't need to login.
3. App trying update data from server
4. Get stack trace 

### Expected behaviour

A dialog will open stating that the certificate is not trusted. And then i can accept untrusted certificate 

### Actual behaviour

Stack trace

### Android version

Android 6.0.1, MIUI 10.2.2.0

### Device brand and model

Xiaomi Redmi 3s

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.2

### Nextcloud server version

25.0.4

### Using a reverse proxy?

Yes

### Cause of error
```java
Exception in thread "main" android.util.AndroidRuntimeException: requestFeature() must be called before adding content
    at com.android.internal.policy.PhoneWindow.requestFeature(PhoneWindow.java:317)
    at android.app.Dialog.requestWindowFeature(Dialog.java:1126)
    at com.owncloud.android.ui.dialog.SslUntrustedCertDialog.onCreateDialog(SslUntrustedCertDialog.java:168)
    at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:665)
    at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:579)
    at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1752)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:493)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
    at android.os.Handler.handleCallback(Handler.java:742)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:157)
    at android.app.ActivityThread.main(ActivityThread.java:5601)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30240290`
* Build flavor: `gplay`

### Device information
* Brand: `Xiaomi`
* Device: `land`
* Model: `Redmi 3S`
* Id: `MMB29M`
* Product: `land`

### Firmware
* SDK: `23`
* Release: `6.0.1`
* Incremental: `V10.2.2.0.MALMIXM`

### Server error logs

```bash
–
```

### Additional information

From phone with web browser nextcloud works good
From PC with web browser nextcloud works good
The browser trusts this certificate and everything works fine

**Comment by HyperPaint** [comment]
I think you should call 'requestFeature()' on old SDK

**Comment by TachPost** [comment]
Hi Folks,

I Got exactly the same error since i have updated from NC22 to NC26.0.2. I am using Firmware SDK 23 Release 6.0.1 and tried to downgrade from latest app version down to gplay-release-30240052 which did not work for all app versions. I am using Nginx Proxy Manager with valid LetsEncrypt cert. As in HyperPaint`s case, access via browser is working flawlessly and even access and sync over DAVx5 works fine. I even added the proxy ip with the trusted_proxies line in config.php which was not even nesscessary in NC22 with no luck.

### Cause of error
```java
Exception in thread "main" android.util.AndroidRuntimeException: requestFeature() must be called before adding content
    at com.android.internal.policy.PhoneWindow.requestFeature(PhoneWindow.java:398)
    at android.app.Dialog.requestWindowFeature(Dialog.java:1336)
    at com.owncloud.android.ui.dialog.SslUntrustedCertDialog.onCreateDialog(SslUntrustedCertDialog.java:168)
    at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:665)
    at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:579)
    at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1752)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:493)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:158)
    at android.app.ActivityThread.main(ActivityThread.java:7224)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```
### App information
* ID: `com.nextcloud.client`
* Version: `30240190`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `klte`
* Model: `SM-G900F`
* Id: `MMB29M`
* Product: `kltexx`

### Firmware
* SDK: `23`
* Release: `6.0.1`
* Incremental: `G900FXXS1CQD4` 

Greets TachPost

**Comment by joshtrichards** [comment]
Closing since we don't support Android 6 at this point and every report I've seen of this is from Android 6.

https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html#mobile-apps
