### ISSUE TITLE
crash with karadav server

### ISSUE THREAD

**Issue by 532910** [nextcloud/android#11718]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. start karadav in docker: https://f-droid.org/en/packages/com.nextcloud.client
2. install https://f-droid.org/en/packages/com.nextcloud.client/
3. log in

### Expected behaviour

app must not crash

### Cause of error
```java
Exception in thread "Thread-7" java.lang.NumberFormatException: For input string: "eJwrTi1K"
    at java.lang.Long.parseLong(Long.java:736)
    at java.lang.Long.parseLong(Long.java:861)
    at com.owncloud.android.datamodel.OCFile.getLocalId(OCFile.java:606)
    at com.owncloud.android.datamodel.FileDataStorageManager.createContentValuesBase(FileDataStorageManager.java:461)
    at com.owncloud.android.datamodel.FileDataStorageManager.createContentValuesForFolder(FileDataStorageManager.java:478)
    at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:392)
    at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:538)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:409)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:239)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30240190`
* Build flavor: `generic`

### Device information
* Brand: `OnePlus`
* Device: `OnePlus9Pro`
* Model: `LE2120`
* Id: `TQ2A.230505.002`
* Product: `OnePlus9Pro`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `121`

### Android version

* Release: `13`

### Device brand and model

* Brand: `OnePlus` * Device: `OnePlus9Pro` * Model: `LE2120`

### Stock or custom OS?

Stock

### Nextcloud android app version

* Version: `30240190`

### Nextcloud server version

-

### Using a reverse proxy?

I don't know

**Comment by bohwaz** [comment]
This is because NextCloud decided the fileId is now an integer instead of a string: https://github.com/nextcloud/android/commit/b78e991d54ad9f4b9e5b7474c601e2c8b716ed30

But KaraDAV doesn't have an integer fileId, but a base64 string containing the file path.

**Comment by bohwaz** [comment]
KaraDAV is now returning a random integer for fileID to get around this code change. This can be closed, as it is unrelated to NextCloud itself.

**Comment by tobiasKaminsky** [comment]
Yes, please report this on karaDAV.
We will not change fileId from Integer to String because of another server.

**Comment by 532910** [comment]
this is a nextcloud bug and it must be fixed, it must not crash

**Comment by 532910** [comment]
please reopen until fixed

**Comment by AndyScherzinger** [comment]
The Nextcloud client is designed to work with the Nextcloud server and no other types of servers, so there is no plan to support them - hence there is nothing to fix
