### ISSUE TITLE
Crash when sharing an MD file

### ISSUE THREAD

**Issue by tzugen** [nextcloud/android#11749]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Crash when trying to share an. MD file

### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Fragment FileActionsBottomSheet{814b1e0} (24e3b6aa-4f19-4987-9e6d-33f20f7461f6) not associated with a fragment manager.
    at androidx.fragment.app.Fragment.getParentFragmentManager(Fragment.java:1107)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.dispatchActionClick(FileActionsBottomSheet.kt:296)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.access$dispatchActionClick(FileActionsBottomSheet.kt:61)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$onCreateView$2.invoke(FileActionsBottomSheet.kt:96)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$onCreateView$2.invoke(FileActionsBottomSheet.kt:95)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.onCreateView$lambda$1(FileActionsBottomSheet.kt:95)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.$r8$lambda$_ZVdO424AE_9Va9J36Ka295XXOw(Unknown Source:0)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$$ExternalSyntheticLambda3.onChanged(Unknown Source:2)
    at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
    at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
    at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
    at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
    at com.nextcloud.ui.fileactions.FileActionsViewModel.onClick(FileActionsViewModel.kt:156)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.inflateActionView$lambda$11$lambda$10(FileActionsBottomSheet.kt:278)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.$r8$lambda$8LHG1EjWT6gxYABWpcaRLD_Z_YY(Unknown Source:0)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
    at android.view.View.performClick(View.java:7506)
    at android.view.View.performClickInternal(View.java:7483)
    at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
    at android.view.View$PerformClick.run(View.java:29357)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7903)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ExecInit.main(ExecInit.java:49)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30240190`
* Build flavor: `generic`

### Firmware
* SDK: `33`
* Release: `13`

### Actual behaviour

.. 

### Android version

See above

### Device brand and model

See above

### Stock or custom OS?

Stock

### Nextcloud android app version

See above

### Nextcloud server version

See above

### Using a reverse proxy?

I don't know

**Comment by joshtrichards** [comment]
Hi @tzugen - Thanks for your report. Unfortunately I'm unable to reproduce this through your reproduction steps were a bit ambiguous. To clarify, which of these describes what you're trying to do:

1. Share a file (an .md file) from NC Android to another Android app
2. Share a file (an .md file) from within NC Android with another NC user or via a share link
3. Share a file (an .md file) from another Android app to NC Ancroid  

Also, does it still happen for you in v3.25?
