### ISSUE TITLE
Mail widget crashing

### ISSUE THREAD

**Issue by stmichalke** [nextcloud/android#11771]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Install the mail widget on the start screen
2. Tap on the reload button or wait
3. Sometimes an error message with the stacktrace appears

### Expected behaviour

The list of unread mails should be updated.

### Actual behaviour

An info about a crash appears 

### Android version

13

### Device brand and model

Samsung Galaxy A52

### Stock or custom OS?

Stock

### Nextcloud android app version

3.25.0

### Nextcloud server version

26.0.3

### Using a reverse proxy?

Yes

### Cause of error
```java
Exception in thread "binder:13923_4" java.lang.NullPointerException: uriString
    at android.net.Uri$StringUri.<init>(Uri.java:504)
    at android.net.Uri$StringUri.<init>(Unknown Source:0)
    at android.net.Uri.parse(Uri.java:466)
    at com.nextcloud.client.widget.StackRemoteViewsFactory.createLoadMoreView(DashboardWidgetService.kt:158)
    at com.nextcloud.client.widget.StackRemoteViewsFactory.getViewAt(DashboardWidgetService.kt:150)
    at android.widget.RemoteViewsService$RemoteViewsFactoryAdapter.getViewAt(RemoteViewsService.java:164)
    at com.android.internal.widget.IRemoteViewsFactory$Stub.onTransact(IRemoteViewsFactory.java:183)
    at android.os.Binder.execTransactInternal(Binder.java:1316)
    at android.os.Binder.execTransact(Binder.java:1280)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30250090`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `a52q`
* Model: `SM-A525F`
* Product: `a52qnsxx`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `A525FXXS5DWD2`

### Server error logs

```bash
No entry
```

**Comment by joshtrichards** [comment]
Fixed in #13026
