### ISSUE TITLE
Random crash when trying to share from another app

### ISSUE THREAD

**Issue by enoch85** [nextcloud/android#11814]
### Cause of error
```java
Exception in thread "Thread-8" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30250090`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OP516FL1`
* Model: `NE2213`
* Id: `SKQ1.221119.001`
* Product: `NE2213EEA`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `S.113a995-ea8-268bd`

**Comment by enoch85** [comment]
Closing as duplicate: https://github.com/nextcloud/android/issues/11207
