### ISSUE TITLE
Bug every time the app opens from a file shortcut on the home screen 

### ISSUE THREAD

**Issue by sebastiencastermans** [nextcloud/android#11823]
### Steps to reproduce

1. Open a file from a home screen shortcut

### Expected behaviour

The file opens (pdf)

### Actual behaviour

App crashes with logs displayed

### Android version

13

### Device brand and model

Oneplus 11

### Stock or custom OS?

Stock

### Nextcloud android app version

Latest

### Nextcloud server version

Latest AIO

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.files.services.FileDownloader$FileDownloaderBinder.isDownloading(com.nextcloud.client.account.User, com.owncloud.android.datamodel.OCFile)' on a null object reference
    at com.owncloud.android.ui.activity.FileDisplayActivity.requestForDownload(FileDisplayActivity.java:1985)
    at com.owncloud.android.ui.activity.FileDisplayActivity.startDownloadForPreview(FileDisplayActivity.java:2273)
    at com.owncloud.android.ui.fragment.OCFileListFragment.onItemClicked(OCFileListFragment.java:1085)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onOpenFileIntent(FileDisplayActivity.java:586)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onPostCreate(FileDisplayActivity.java:385)
    at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1477)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3928)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2474)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:240)
    at android.os.Looper.loop(Looper.java:351)
    at android.app.ActivityThread.main(ActivityThread.java:8416)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30250090`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OP594DL1`
* Model: `CPH2449`
* Id: `TP1A.220905.001`
* Product: `CPH2449EEA`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `T.R4T3.110730f_335df-2`

### Server error logs

```bash
No
```

### Additional information

No

**Comment by joshtrichards** [comment]
Hi @sebastiencastermans - Thanks for the report. I can't reproduce this unfortunately. I assume you can still successfully open the file if you go into the client and tap it, correct?

Do, by chance, have multiple user profiles configured in your NC client? (Not sure what's causing this behavior for you, but trying to determine what might be a trigger).

**Comment by sebastiencastermans** [comment]
Hi @joshtrichards, yes yes I still have access to it through the app. And no, I don't have multiple user profiles. I think the problem came from the fact that I changed my phone, all the data migrated including the home screen shortcuts but not the Nextcloud App data, that's probably why this shortcut did not lead nowhere...

Maybe the "ID" of the old shortcut was not recognized with the reconfigured app? Anyway, I redid the shortcut and everything works fine 😊.

Thank you for your concern about this issue.
Good afternoon to you!
