### ISSUE TITLE
App crashes on startup, or after logging in

### ISSUE THREAD

**Issue by tadzik** [nextcloud/android#11848]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Login to the nextcloud app
2. Observe the crash
3. A restart of the app starts the login process all over again

### Expected behaviour

App shouldn't crash

### Actual behaviour

App crashes

### Android version

11

### Device brand and model

Samsung Galaxy A5 2017

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.25.0 according to f-droid. Can't check the settings screen for obvious reasons.

### Nextcloud server version

Nextcloud Hub 3 (25.0.8)

### Using a reverse proxy?

No

### Cause of error

```
java
Exception in thread "main" android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=1
    at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
    at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1001)
    at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
    at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
    at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:153)
    at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:140)
    at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:231)
    at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:270)
    at com.nextcloud.client.database.dao.FileDao_Impl.getFileByEncryptedRemotePath(FileDao_Impl.java:425)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:134)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFileByEncryptedRemotePath(FileDataStorageManager.java:122)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:118)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2411)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
    at android.app.Activity.performStart(Activity.java:8018)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7664)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

### App information
* ID: com.nextcloud.client
* Version: 30250090
* Build flavor: generic

### Device information
* Brand: samsung
* Device: a5y17lte
* Model: SM-A520F
* Id: RQ3A.211001.001
* Product: lineage_a5y17lte

### Firmware
* SDK: 30
* Release: 11
* Incremental: e966434d0f

### Additional information

Seemingly a duplicate of https://github.com/nextcloud/android/issues/5926, though that one was allegedly fixed. I guess the fix didn't cover everything – I have observed the issue on my end since 2022-ish too, I just didn't bother reporting it then.

**Comment by joshtrichards** [comment]
See #10213 where work on this is already being tracked along with some further explanations about underlying causes.

Please close out this issue unless you feel your issue isn't addressed there. Thanks!
