### ISSUE TITLE
Error when trying to change folder while sharing an image 

### ISSUE THREAD

**Issue by vabean** [nextcloud/android#11935]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Share an image with Nextcloud app
2. Try to go one folder up in Nextcloud app
3. The error message appears 

### Expected behaviour

No error

### Actual behaviour

An error is displayed 

### Android version

13

### Device brand and model

samsung a71

### Stock or custom OS?

Stock

### Nextcloud android app version

30250090

### Nextcloud server version

25.0.8

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "Thread-11" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30250090`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `a71`
* Model: `SM-A715F`
* Id: `TP1A.220624.014`
* Product: `a71naeea`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `A715FXXUADWE1`

**Comment by joshtrichards** [comment]
Hi @vabean - Thanks for the report. This is fixed in #11410 and is pending the next release.
