### ISSUE TITLE
Crash when opening home screen shortcut to a file

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/android#11949]
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.owncloud.android.ui.adapter.CommonOCFileListAdapterInterface.isMultiSelect()' on a null object reference
    at com.owncloud.android.ui.fragment.OCFileListFragment.onItemClicked(OCFileListFragment.java:972)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onOpenFileIntent(FileDisplayActivity.java:586)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onNewIntent(FileDisplayActivity.java:525)
    at android.app.Activity.performNewIntent(Activity.java:8015)
    at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1409)
    at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1422)
    at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3664)
    at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3676)
    at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:53)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7656)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30250090`
* Build flavor: `generic`

### Device information
* Brand: `google`
* Device: `taimen`
* Model: `Pixel 2 XL`
* Id: `RP1A.201005.004.A1`
* Product: `taimen`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `6934943`

**Comment by parneet-guraya** [comment]
Can you tell how to reproduce the error?

**Comment by gerbrent** [comment]
...not yet!
Will keep trying... stay tuned (and will update if I cannot)
