### ISSUE TITLE
Exception on remove from favourite

### ISSUE THREAD

**Issue by juliuspopp** [nextcloud/android#12025]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Happened when clicking Remove from Favourite. Did not occur when removing another item

### Expected behaviour

No exception 

### Actual behaviour

Exception. Still worlds though

### Android version

See report

### Device brand and model

See report

### Stock or custom OS?

Stock

### Nextcloud android app version

See report

### Nextcloud server version

26.0.5

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "main" java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 3(offset:3).state:6 com.owncloud.android.ui.EmptyRecyclerView{29026c0 VFED..... ......ID 0,0-720,1082 #7f0a0294 app:id/list_root}, adapter:com.owncloud.android.ui.adapter.OCFileListAdapter@7ff88cf, layout:androidx.recyclerview.widget.LinearLayoutManager@2bb5092, context:com.owncloud.android.ui.activity.FileDisplayActivity@a3766e7
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6752)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6688)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6684)
    at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
    at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
    at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
    at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4604)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4307)
    at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4873)
    at android.view.View.layout(View.java:20684)
    at android.view.ViewGroup.layout(ViewGroup.java:6274)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:20684)
    at android.view.ViewGroup.layout(ViewGroup.java:6274)
    at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:689)
    at android.view.View.layout(View.java:20684)
    at android.view.ViewGroup.layout(ViewGroup.java:6274)
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
    at android.view.View.layout(View.java:20684)
    at android.view.ViewGroup.layout(ViewGroup.java:6274)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:20684)
    at android.view.ViewGroup.layout(ViewGroup.java:6274)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
    at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1801)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1567)
    at android.view.View.layout(View.java:20684)
    at android.view.ViewGroup.layout(ViewGroup.java:6274)
    at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:149)
    at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
    at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2376)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
    at android.view.View.layout(View.java:20684)
    at android.view.ViewGroup.layout(ViewGroup.java:6274)
    at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
    at android.view.View.layout(View.java:20684)
    at android.view.ViewGroup.layout(ViewGroup.java:6274)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:20684)
    at android.view.ViewGroup.layout(ViewGroup.java:6274)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:20684)
    at android.view.ViewGroup.layout(ViewGroup.java:6274)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:20684)
    at android.view.ViewGroup.layout(ViewGroup.java:6274)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
    at android.view.View.layout(View.java:20684)
    at android.view.ViewGroup.layout(ViewGroup.java:6274)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at com.android.internal.policy.DecorView.onLayout(DecorView.java:820)
    at android.view.View.layout(View.java:20684)
    at android.view.ViewGroup.layout(ViewGroup.java:6274)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2802)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2329)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1470)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7209)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1012)
    at android.view.Choreographer.doCallbacks(Choreographer.java:823)
    at android.view.Choreographer.doFrame(Choreographer.java:758)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:998)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6794)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30250090`
* Build flavor: `generic`

### Device information
* Brand: `Hisense`
* Device: `HLTE202N`
* Model: `HLTE202N`
* Id: `PKQ1.190504.001`
* Product: `HLTE202N`

### Firmware
* SDK: `28`
* Release: `9`
* Incremental: `L1657.6.01.02`

**Comment by joshtrichards** [comment]
Fixed in #11804
Released in v3.26.0
