### ISSUE TITLE
App crashes when synchronizing data to SD-Card

### ISSUE THREAD

**Issue by hansaushamburg** [nextcloud/android#12104]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

I selected the SD card for storage
When I synchronize data the app crashes

### Expected behaviour

no crash

### Actual behaviour

See above

### Android version

13

### Device brand and model

Samsung Galaxy A54

### Stock or custom OS?

Stock

### Nextcloud android app version

3.26.0

### Nextcloud server version

27.1.2

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Error while computing available space
    at com.owncloud.android.utils.FileStorageUtils.checkIfEnoughSpace(FileStorageUtils.java:674)
    at com.owncloud.android.ui.fragment.OCFileListFragment.syncAndCheckFiles(OCFileListFragment.java:1938)
    at com.owncloud.android.ui.fragment.OCFileListFragment.onFileActionChosen(OCFileListFragment.java:1219)
    at com.owncloud.android.ui.fragment.OCFileListFragment.lambda$openActionsMenu$5(OCFileListFragment.java:618)
    at com.owncloud.android.ui.fragment.OCFileListFragment.$r8$lambda$slgIzxJfj-ZDThyXo8s23Nlrz3E(Unknown Source:0)
    at com.owncloud.android.ui.fragment.OCFileListFragment$$ExternalSyntheticLambda4.onResult(Unknown Source:4)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.setResultListener$lambda$4(FileActionsBottomSheet.kt:189)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.$r8$lambda$gBLh4lQVgKyYSPFY4JEvqe8OJuE(Unknown Source:0)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$$ExternalSyntheticLambda1.onFragmentResult(Unknown Source:2)
    at androidx.fragment.app.FragmentManager$LifecycleAwareResultListener.onFragmentResult(FragmentManager.java:267)
    at androidx.fragment.app.FragmentManager.setFragmentResult(FragmentManager.java:945)
    at androidx.fragment.app.FragmentKt.setFragmentResult(Fragment.kt:33)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.dispatchActionClick(FileActionsBottomSheet.kt:309)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.access$dispatchActionClick(FileActionsBottomSheet.kt:65)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$onCreateView$2.invoke(FileActionsBottomSheet.kt:103)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$onCreateView$2.invoke(FileActionsBottomSheet.kt:102)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$sam$androidx_lifecycle_Observer$0.onChanged(Unknown Source:2)
    at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
    at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
    at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
    at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
    at com.nextcloud.ui.fileactions.FileActionsViewModel.onClick(FileActionsViewModel.kt:162)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.inflateActionView$lambda$9$lambda$8(FileActionsBottomSheet.kt:292)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.$r8$lambda$akwMQPy8SSZm7IZL9pPs1JnKp0Q(Unknown Source:0)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
    at android.view.View.performClick(View.java:7892)
    at android.view.View.performClickInternal(View.java:7869)
    at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
    at android.view.View$PerformClick.run(View.java:30891)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8762)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

### App information
* ID: com.nextcloud.client
* Version: 30260090
* Build flavor: gplay

### Device information
* Brand: samsung
* Device: a54x
* Model: SM-A546B
* Id: TP1A.220624.014
* Product: a54xnaeea

### Firmware
* SDK: 33
* Release: 13
* Incremental: A546BXXS5AWI3

**Comment by joshtrichards** [comment]
This likely is happening because the filesystem access is being denied or something is wrong with the SD card.

- How did you format the SD card? (https://support.google.com/android/answer/12153449?hl=en)
- Can you use it with other apps?
- Check permissions: Look for the *Special app access* section in your Android settings and make sure the Nextcloud client is there and set to *Allowed*

**Comment by hansaushamburg** [comment]
Thank you for the feedback.

- formatting of the SD card was done according to the description in your link
- SD card works with the apps
- all permissions were given

Everything seems to work right now ...
... I can't say why, maybe checking everything once again did the job.

 Thank you again :-)
