### ISSUE TITLE
Samsung s23+ Open app and boom

### ISSUE THREAD

**Issue by blankcdf** [nextcloud/android#12134]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Opened the app for the first time closed and restarted the app fixed may not be reproducible 

### Expected behaviour

App should've opened 

### Actual behaviour

Runtime error from the look of the log

### Android version

13

### Device brand and model

Samsung 23 plus

### Stock or custom OS?

Stock

### Nextcloud android app version

3.25.0

### Nextcloud server version

27.1.3

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Unable to resume activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.SecurityException: uid 10242 cannot get user data for accounts of type: nextcloud
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5378)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5444)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8762)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: Exception in thread "main" java.lang.SecurityException: uid 10242 cannot get user data for accounts of type: nextcloud
    at android.os.Parcel.createExceptionOrNull(Parcel.java:3023)
    at android.os.Parcel.createException(Parcel.java:3007)
    at android.os.Parcel.readException(Parcel.java:2990)
    at android.os.Parcel.readException(Parcel.java:2932)
    at android.accounts.IAccountManager$Stub$Proxy.getUserData(IAccountManager.java:1109)
    at android.accounts.AccountManager$2.recompute(AccountManager.java:465)
    at android.accounts.AccountManager$2.recompute(AccountManager.java:456)
    at android.app.PropertyInvalidatedCache.query(PropertyInvalidatedCache.java:931)
    at android.accounts.AccountManager.getUserData(AccountManager.java:648)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.<init>(OCFileListAdapter.java:160)
    at com.owncloud.android.ui.fragment.OCFileListFragment.setAdapter(OCFileListFragment.java:437)
    at com.owncloud.android.ui.fragment.OCFileListFragment.onActivityCreated(OCFileListFragment.java:379)
    at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3146)
    at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:579)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:264)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1901)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1819)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1762)
    at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:495)
    at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:312)
    at com.owncloud.android.ui.activity.BaseActivity.onResume(BaseActivity.java:91)
    at com.owncloud.android.ui.activity.DrawerActivity.onResume(DrawerActivity.java:983)
    at com.owncloud.android.ui.activity.FileActivity.onResume(FileActivity.java:251)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onResume(FileDisplayActivity.java:1114)
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1531)
    at android.app.Activity.performResume(Activity.java:8734)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5351)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5444)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8762)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: Exception in thread "main" android.os.RemoteException: Remote stack trace:
	at com.android.server.accounts.AccountManagerService.getUserData(AccountManagerService.java:1659)
	at android.accounts.IAccountManager$Stub.onTransact(IAccountManager.java:450)
	at com.android.server.accounts.AccountManagerService.onTransact(AccountManagerService.java:1143)
	at android.os.Binder.execTransactInternal(Binder.java:1316)
	at android.os.Binder.execTransact(Binder.java:1280)


```

### App information
* ID: `com.nextcloud.client`
* Version: `30250090`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `dm2q`
* Model: `SM-S916U1`
* Id: `TP1A.220624.014`
* Product: `dm2quew`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `S916U1UES1AWIF`

### Additional information

Working fine now just happy to contribute

**Comment by joshtrichards** [comment]
Looks like another occurrence of #10159. Let's consolidate tracking/progress there. Thanks for your report, @blankcdf!
