### ISSUE TITLE
Crashes when uploading files from file picker: `TransactionTooLargeException`

### ISSUE THREAD

**Issue by yagarea** [nextcloud/android#12154]
### Steps to reproduce

Try to upload files to directory

### Expected behaviour

not crash and upload files to directory

### Actual behaviour

crashes

### Android version

14

### Device brand and model

Brand: google,  Device: oriole, Model: Pixel 6, Id: UP1A.231105.003, Product: oriole

### Stock or custom OS?

Stock

### Nextcloud android app version

3.26.0

### Nextcloud server version

27.1.2

### Using a reverse proxy?

No

### Android logs

```java
Exception in thread "main" java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1253892 bytes
    at android.app.ActivityClient.finishActivity(ActivityClient.java:178)
    at android.app.Activity.finish(Activity.java:7032)
    at android.app.Activity.finish(Activity.java:7049)
    at com.owncloud.android.ui.activity.UploadFilesActivity.onCheckAvailableSpaceFinish(UploadFilesActivity.java:525)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:72)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:34)
    at android.os.AsyncTask.finish(AsyncTask.java:771)
    at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.app.ActivityThread.main(ActivityThread.java:8199)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ExecInit.main(ExecInit.java:49)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: Exception in thread "main" android.os.TransactionTooLargeException: data parcel size 1253892 bytes
    at android.os.BinderProxy.transactNative(Native Method)
    at android.os.BinderProxy.transact(BinderProxy.java:584)
    at android.app.IActivityClientController$Stub$Proxy.finishActivity(IActivityClientController.java:1583)
    at android.app.ActivityClient.finishActivity(ActivityClient.java:175)
    at android.app.Activity.finish(Activity.java:7032)
    at android.app.Activity.finish(Activity.java:7049)
    at com.owncloud.android.ui.activity.UploadFilesActivity.onCheckAvailableSpaceFinish(UploadFilesActivity.java:525)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:72)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:34)
    at android.os.AsyncTask.finish(AsyncTask.java:771)
    at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.app.ActivityThread.main(ActivityThread.java:8199)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ExecInit.main(ExecInit.java:49)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```

### App information
* ID: com.nextcloud.client
* Version: 30260090
* Build flavor: generic

### Firmware
* SDK: 34
* Release: 14
* Incremental: 2023110700

**Comment by bjlanger** [comment]
Same or similar error here as well.

### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2443332 bytes
    at android.app.ActivityClient.finishActivity(ActivityClient.java:167)
    at android.app.Activity.finish(Activity.java:6673)
    at android.app.Activity.finish(Activity.java:6690)
    at com.owncloud.android.ui.activity.UploadFilesActivity.onCheckAvailableSpaceFinish(UploadFilesActivity.java:525)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:72)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:34)
    at android.os.AsyncTask.finish(AsyncTask.java:771)
    at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:346)
    at android.os.Looper.loop(Looper.java:475)
    at android.app.ActivityThread.main(ActivityThread.java:7950)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: Exception in thread "main" android.os.TransactionTooLargeException: data parcel size 2443332 bytes
    at android.os.BinderProxy.transactNative(Native Method)
    at android.os.BinderProxy.transact(BinderProxy.java:584)
    at android.app.IActivityClientController$Stub$Proxy.finishActivity(IActivityClientController.java:1391)
    at android.app.ActivityClient.finishActivity(ActivityClient.java:164)
    at android.app.Activity.finish(Activity.java:6673)
    at android.app.Activity.finish(Activity.java:6690)
    at com.owncloud.android.ui.activity.UploadFilesActivity.onCheckAvailableSpaceFinish(UploadFilesActivity.java:525)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:72)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:34)
    at android.os.AsyncTask.finish(AsyncTask.java:771)
    at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:346)
    at android.os.Looper.loop(Looper.java:475)
    at android.app.ActivityThread.main(ActivityThread.java:7950)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30260090`
* Build flavor: `gplay`

### Device information
* Brand: `Sony`
* Device: `XQ-CQ62`
* Model: `XQ-CQ62`
* Id: `64.1.A.0.990`
* Product: `XQ-CQ62`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `064001A000099002006725595`
