### ISSUE TITLE
Error in Nextcloud Dev : FileDownloader error due to android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord

### ISSUE THREAD

**Issue by zerwes** [nextcloud/android#12219]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Since a few days the dev version of the app is crashing when trying to view a file (pdf, md, ...)
Strange: it is happening mostly, not always ... approx 90% of the tries causing a crash, 10% end up with a success i.e. opening the desired PDF. But even in the last case, the nc app is crashing (just the user sees it as success, has he can read the desired pdf)
This renders the app unusable.

### Expected behaviour

Download and open a document

### Actual behaviour

crashing and mostly failing to open the desired document

### Android version

14

### Device brand and model

google bluejay Pixel 6a

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

20231125 dev

### Nextcloud server version

25.0.13.2

### Using a reverse proxy?

No

### crash reporrt:
```
type: crash
osVersion: google/bluejay/bluejay:14/UP1A.231105.003/2023112900:user/release-keys
package: com.nextcloud.android.beta:20231125
process: com.nextcloud.android.beta
processUptime: 414 + 542 ms
installer: com.android.packageinstaller
```

### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Unable to start service com.owncloud.android.files.services.FileDownloader@3f2f18f with Intent { cmp=com.nextcloud.android.beta/com.owncloud.android.files.services.FileDownloader (has extras) }: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{8521e41 3968:com.nextcloud.android.beta/u0a142} targetSDK=34
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4856)
    at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2296)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.app.ActivityThread.main(ActivityThread.java:8199)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ExecInit.main(ExecInit.java:49)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: Exception in thread "main" android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{8521e41 3968:com.nextcloud.android.beta/u0a142} targetSDK=34
    at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
    at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
    at android.os.Parcel.readParcelableInternal(Parcel.java:4890)
    at android.os.Parcel.readParcelable(Parcel.java:4872)
    at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
    at android.os.Parcel.createException(Parcel.java:3050)
    at android.os.Parcel.readException(Parcel.java:3026)
    at android.os.Parcel.readException(Parcel.java:2968)
    at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6776)
    at android.app.Service.startForeground(Service.java:775)
    at com.owncloud.android.files.services.FileDownloader.onStartCommand(FileDownloader.java:203)
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4838)
    at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2296)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.app.ActivityThread.main(ActivityThread.java:8199)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ExecInit.main(ExecInit.java:49)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20231125`
* Build flavor: `versionDev`

### Device information
* Brand: `google`
* Device: `bluejay`
* Model: `Pixel 6a`
* Id: `UP1A.231105.003`
* Product: `bluejay`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `2023111500`

### Server error logs

```bash
nothing showing up on the server side
```

### Additional information

If more information are required, just let me know.

**Comment by zerwes** [comment]
It seems this is mostly related to PDF files ... and it seems independent of the PDF viewer app installed / in use.

**Comment by zerwes** [comment]
confirmed: latest dev version of the app works fine! thx !
