### ISSUE TITLE
Crash while solving many upload conflicts caused by earlier NC malfunction 

### ISSUE THREAD

**Issue by arnwas** [nextcloud/android#12222]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

No awareness of specific action which triggered this

### Expected behaviour

No crash if app

### Actual behaviour

Crash

### Android version

See above

### Device brand and model

See above

### Stock or custom OS?

Stock

### Nextcloud android app version

See above

### Nextcloud server version

See above

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "FileDownloaderThread" java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 496856 free bytes and 485KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
    at com.owncloud.android.lib.resources.files.DownloadFileRemoteOperation.downloadFile(DownloadFileRemoteOperation.java:119)
    at com.owncloud.android.lib.resources.files.DownloadFileRemoteOperation.run(DownloadFileRemoteOperation.java:88)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:205)
    at com.owncloud.android.operations.DownloadFileOperation.run(DownloadFileOperation.java:180)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:205)
    at com.owncloud.android.files.services.FileDownloader.downloadFile(FileDownloader.java:474)
    at com.owncloud.android.files.services.FileDownloader.-$$Nest$mdownloadFile(Unknown Source:0)
    at com.owncloud.android.files.services.FileDownloader$ServiceHandler.handleMessage(FileDownloader.java:424)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.os.HandlerThread.run(HandlerThread.java:67)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30260090`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `panther`
* Model: `Pixel 7`
* Id: `UP1A.231105.003`
* Product: `panther`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `11010452`

**Comment by arnwas** [comment]
> > Crash while solving many upload conflicts caused by earlier NC malfunction
> 
> What was the earlier malfunction?

no idea, i just have thousands of conflicts where the files are identical in every respect i can see.
