### ISSUE TITLE
Nextcloud Crashes right after starting

### ISSUE THREAD

**Issue by haexhub** [nextcloud/android#12281]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Download the nextcloud dev App from F-Droid store and try to open it.

### Expected behaviour

It should work

### Actual behaviour

The App crashes immediatly. 

### Android version

14

### Device brand and model

Google Pixel 7 Pro

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

Version 20231208 

### Nextcloud server version

Can't open the app

### Using a reverse proxy?

I don't know

### Android logs

```
type: crash
osVersion: google/cheetah/cheetah:14/UQ1A.231205.015/2023120800:user/release-keys
package: com.nextcloud.android.beta:20231208
process: com.nextcloud.android.beta
processUptime: 3942 + 266 ms
installer: com.android.packageinstaller

java.lang.RuntimeException: Unable to resume activity {com.nextcloud.android.beta/com.owncloud.android.authentication.AuthenticatorActivity}: java.lang.SecurityException: com.nextcloud.android.beta: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4999)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5032)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2455)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8216)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.SecurityException: com.nextcloud.android.beta: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5699)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1883)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1823)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1811)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
	at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher.onResume(UsbConnectionDispatcher.java:113)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.onActivityResumed(SecurityKeyManager.java:281)
	at android.app.Application.dispatchActivityResumed(Application.java:437)
	at android.app.Activity.dispatchActivityResumed(Activity.java:1499)
	at android.app.Activity.onResume(Activity.java:2085)
	at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:309)
	at com.owncloud.android.authentication.AuthenticatorActivity.onResume(AuthenticatorActivity.java:727)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1608)
	at android.app.Activity.performResume(Activity.java:8825)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4989)
	... 15 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14075)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2578)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2767)
	at android.os.Binder.execTransactInternal(Binder.java:1361)
	at android.os.Binder.execTransact(Binder.java:1302)


```

### Additional information

I'm using GrapheneOS with no Google Apps installed

**Comment by AndyScherzinger** [comment]
This has been fixed with yesterday's stable release. So we all have to wait for f-droid/gplay to pick it up
