### ISSUE TITLE
"Share" button in crash dialog not working

### ISSUE THREAD

**Issue by eliasp** [nextcloud/android#12293]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Due to other reasons (#12294), my Android App kept crashing.
The "Share" button in the crash dialog in the upper right corner isn't working and just does nothing, when tapping it.

### Expected behaviour

The "Share" button in the upper right corner should trigger the "Share" intent, which would allow me to share the text displayed in the dialog with another App.

### Actual behaviour

The "Share" button does absolutely nothing, it doesn't even show any signs of being tapped and just acts like a static image.

### Android version

11

### Device brand and model

OnePlus Nord (AC2003)

### Stock or custom OS?

Stock

### Nextcloud android app version

30260090

### Nextcloud server version

28.0.0.11, 27.1.4.1

### Using a reverse proxy?

Yes

### Cause of error
```java
Exception in thread "DefaultDispatcher-worker-3" java.lang.NullPointerException: Attempt to read from field 'com.owncloud.android.lib.ocs.OCSResponse com.owncloud.android.lib.ocs.ServerResponse.ocs' on a null object reference
    at com.nextcloud.android.lib.resources.dashboard.DashboardGetWidgetItemsRemoteOperation.run(DashboardGetWidgetItemsRemoteOperation.kt:47)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:220)
    at com.nextcloud.client.widget.StackRemoteViewsFactory$onDataSetChanged$1.invokeSuspend(DashboardWidgetService.kt:116)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30260090`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `Nord`
* Model: `AC2003`
* Id: `RP1A.201005.001`
* Product: `Nord_EEA`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `2108251343`

### Additional information

I believe this might be caused by the fact, that the dialog also displays a `Loading...` message which overlays the text at the top and either this message's bounding box somehow also overlays the button or the whole dialog is in a state, where the button isn't active yet - but the `Loading...` message never goes away.

The "Report issue to tracker" option at the bottom of the screen works as expected.

![Screenshot_20231213-153355](https://github.com/nextcloud/android/assets/48491/252c7c81-00f1-4ba9-a1a5-dc1a0a14e648)

**Comment by OWAIS-THEGREAT** [comment]
i can give it a try
