### ISSUE TITLE
Crash while attempting to view a photo

### ISSUE THREAD

**Issue by ThRPctmylSgltwH** [nextcloud/android#12343]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Open App
View a photo

### Expected behaviour

Photo should open

### Actual behaviour

App crashed and requested that I submit a report 

### Android version

14

### Device brand and model

Samsung A52S

### Stock or custom OS?

Stock

### Nextcloud android app version

3.27.0

### Nextcloud server version

28.0.1

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.lang.IllegalArgumentException: Scale must be within the range of minScale and maxScale
    at com.github.chrisbanes.photoview.PhotoViewAttacher.setScale(PhotoViewAttacher.java:456)
    at com.github.chrisbanes.photoview.PhotoViewAttacher.setScale(PhotoViewAttacher.java:446)
    at com.github.chrisbanes.photoview.PhotoViewAttacher.setScale(PhotoViewAttacher.java:442)
    at com.github.chrisbanes.photoview.PhotoView.setScale(PhotoView.java:230)
    at com.owncloud.android.ui.preview.PreviewImageFragment.onActivityCreated(PreviewImageFragment.java:247)
    at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3156)
    at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:619)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:275)
    at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
    at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
    at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
    at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2952)
    at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
    at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350)
    at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
    at com.owncloud.android.ui.activity.DrawerActivity.onStart(DrawerActivity.java:1156)
    at com.owncloud.android.ui.activity.FileActivity.onStart(FileActivity.java:247)
    at com.owncloud.android.ui.preview.PreviewImageActivity.onStart(PreviewImageActivity.java:237)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1582)
    at android.app.Activity.performStart(Activity.java:8977)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4198)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8893)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30270090`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `a52sxq`
* Model: `SM-A528B`
* Id: `UP1A.231005.007`
* Product: `a52sxqeea`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `A528BXXS5FWL4`

### Server error logs

```bash
No event in log reader. It seems to just be an Android App issue
```

### Additional information

It works fine after restarting the Android app

**Comment by joshtrichards** [comment]
Fixed in #13084 

(may not see until v3.30
