### ISSUE TITLE
Selecting more than two files causes crash: "Two different ViewHolders have the same stable ID."

### ISSUE THREAD

**Issue by KinimodD** [nextcloud/android#12342]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Happens when selecting a file + file, file + folder, but everything works when it's just folders
1. Select file X
2. Select file y
3. Deselect file X
4. Crash

Also happens when selecting 3 files

https://github.com/nextcloud/android/assets/97245998/09b4c8f9-30c4-405d-8840-426e6686065c

### Expected behaviour

Files should keep selected, not crash

### Actual behaviour

Crash, check logs

### Android version

14

### Device brand and model

Nothing Phone 1 A063

### Stock or custom OS?

Stock

### Nextcloud android app version

3.27.0

### Nextcloud server version

28.0.1

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
 ViewHolder 1:OCFileListFooterViewHolder{d879880 position=6 id=0, oldPos=-1, pLpos:-1 not recyclable(1)} 
 View Holder 2:OCFileListItemViewHolder{366c440 position=5 id=0, oldPos=-1, pLpos:-1} com.owncloud.android.ui.EmptyRecyclerView{ed3bd70 VFED..... ......ID 0,0-1080,1940 #7f0a02d6 app:id/list_root}, adapter:com.owncloud.android.ui.adapter.OCFileListAdapter@7535c61, layout:androidx.recyclerview.widget.LinearLayoutManager@87ff8e9, context:com.owncloud.android.ui.activity.FileDisplayActivity@9b970c9
    at androidx.recyclerview.widget.RecyclerView.handleMissingPreInfoForChangeError(RecyclerView.java:4737)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:4661)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4326)
    at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2054)
    at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:438)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1471)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1480)
    at android.view.Choreographer.doCallbacks(Choreographer.java:1076)
    at android.view.Choreographer.doFrame(Choreographer.java:1000)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1447)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:334)
    at android.app.ActivityThread.main(ActivityThread.java:8291)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:557)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30270090`
* Build flavor: `gplay`

### Device information
* Brand: `Nothing`
* Device: `Spacewar`
* Model: `A063`
* Id: `UP1A.231005.007`
* Product: `SpacewarEEA`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `2312152256`

**Comment by joshtrichards** [comment]
Fixed in #12283
