### ISSUE TITLE
Java error occurs when downloading the PDF of Nextcloud

### ISSUE THREAD

**Issue by Wietse76** [nextcloud/android#12396]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Login into Nextcloud from the Nextcloud Android App (see screenshot loginscreen in the attachments)
2. Try to download the PDF of the Nextcloud manual by selecting it.
3. In the screen (which appears) the content is not loaded (see 2nd screenshot), not even after a long waiting time.
4. Now I try to add a comment by the box in the upperhalf of the screen (see 2nd screenshot again).
5. After pressing the arrowbutton, the JAVA error (see errortext) appears.

Remark: Downloading by the Windows client does work as expected!

![2nd screenshot](https://github.com/nextcloud/android/assets/157296536/89731d40-b4bd-4f64-a8e9-9d49f2fe8215)
[errortekst.docx](https://github.com/nextcloud/android/files/14001739/errortekst.docx)
![loginscreen](https://github.com/nextcloud/android/assets/157296536/42fd0a93-c1f1-466f-94e5-d4244a2b2082)

### Expected behaviour

I expect to have the manual downloaded to my phone (seeing that I tried this on my Android phone)
Further I expect my comment is added after pressing the arrow button.

### Actual behaviour

The manual pdf is not downloaded and after pressing the arrowbutton the JAVA error appears.

### Android version

13

### Device brand and model

Oneplus Nord II

### Stock or custom OS?

Stock

### Nextcloud android app version

3.27.0

### Nextcloud server version

none given; latest version as per 20-01-2024

### Using a reverse proxy?

I don't know

### Android logs

I am not that technical. I do not know how to obtain files from my Nextcloudserver.
If you need this log file (and do not have sufficient info in the errortext in the attachment, do not hesitate to contact me.

### Cause of error

```java
Exception in thread "AsyncTask #3" java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$4.done(AsyncTask.java:415)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
    at java.util.concurrent.FutureTask.run(FutureTask.java:269)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
    at java.lang.Thread.run(Thread.java:1012)
Caused by: Exception in thread "AsyncTask #3" java.lang.IllegalArgumentException: Trying to execute a remote operation with a NULL OwnCloudClient
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:201)
    at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment$SubmitCommentTask.doInBackground(FileDetailActivitiesFragment.java:488)
    at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment$SubmitCommentTask.doInBackground(FileDetailActivitiesFragment.java:467)
    at android.os.AsyncTask$3.call(AsyncTask.java:394)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30270090`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OP555BL1`
* Model: `IV2201`
* Id: `TP1A.220905.001`
* Product: `IV2201`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `R.147d29c-585d`

**Comment by joshtrichards** [comment]
The commenting matter is covered in #12353. The PDF/download matter: I cannot reproduce this behavior unfortunately.

- Is this a brand-new installation of the client?
- Can you try setting the PDF to *Download*?  (i.e. Select the file then using the 3 dots menu then choose *Download*). Does the icon receive a green checkmark?
- Are you able to view, create, and edit other types of files in the client?
