### ISSUE TITLE
Crash in Android App

### ISSUE THREAD

**Issue by Borph** [nextcloud/android#12391]
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.owncloud.android.ui.adapter.CommonOCFileListAdapterInterface.isMultiSelect()' on a null object reference
    at com.owncloud.android.ui.fragment.OCFileListFragment.onItemClicked(OCFileListFragment.java:979)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onOpenFileIntent(FileDisplayActivity.java:604)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onPostCreate(FileDisplayActivity.java:396)
    at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1491)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3697)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:224)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:204)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7924)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30270090`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `flame`
* Model: `Pixel 4`
* Id: `SP1A.210812.015`
* Product: `flame`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `7679548`

**Comment by joshtrichards** [comment]
Hi @Borph - Thanks for the report. Any idea how to trigger/reproduce this?

May be similar to, but necessarily the same as #11809

**Comment by Borph** [comment]
Sorry, I didn't spent time on reproducing, I just clicked on the "report issue" :-) If you want you can close it. What I can say is that I was clicking on the shortcut link: in the options of a folder, you have the chance to create a desktop shortcut for that folder. Somehow using that shortcut didn't work this time, but usually it does.
