### ISSUE TITLE
Auto upload: cannot select different remote folder

### ISSUE THREAD

**Issue by MihailCosmin** [nextcloud/android#12394]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Go to Settings > Auto upload
2. Select a folder for Auto upload. Click the 3 dots
3. Activate Auto upload 
4. Click Remote folder
5. Select different folder
6. Click Move (Additionally tried also Copy, with same result)

### Expected behaviour

The selected folder should be displayed as the Remote folder

### Actual behaviour

Either the selected remote folder is not displayed as the remote folder or the app crashes with below error message.

### Android version

13

### Device brand and model

Samsung Galaxy Note 10 Lite

### Stock or custom OS?

Stock

### Nextcloud android app version

3.27.0

### Nextcloud server version

28.0.1

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Parameter specified as non-null is null: method com.owncloud.android.ui.dialog.SyncedFolderPreferencesDialogFragment$setupListeners$1$5.onItemSelected, parameter view
    at com.owncloud.android.ui.dialog.SyncedFolderPreferencesDialogFragment$setupListeners$1$5.onItemSelected(Unknown Source:2)
    at android.widget.AdapterView.fireOnSelected(AdapterView.java:1396)
    at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:1385)
    at android.widget.AdapterView.selectionChanged(AdapterView.java:1368)
    at android.widget.AdapterView.checkSelectionChanged(AdapterView.java:1557)
    at android.widget.AdapterView.handleDataChanged(AdapterView.java:1533)
    at android.widget.AbsSpinner.onMeasure(AbsSpinner.java:193)
    at android.widget.Spinner.onMeasure(Spinner.java:645)
    at androidx.appcompat.widget.AppCompatSpinner.onMeasure(AppCompatSpinner.java:444)
    at android.view.View.measure(View.java:27731)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
    at android.view.View.measure(View.java:27731)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
    at android.view.View.measure(View.java:27731)
    at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:2352)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at android.widget.ScrollView.onMeasure(ScrollView.java:699)
    at android.view.View.measure(View.java:27731)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
    at android.view.View.measure(View.java:27731)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at android.view.View.measure(View.java:27731)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at android.view.View.measure(View.java:27731)
    at androidx.appcompat.widget.AlertDialogLayout.tryOnMeasure(AlertDialogLayout.java:134)
    at androidx.appcompat.widget.AlertDialogLayout.onMeasure(AlertDialogLayout.java:64)
    at android.view.View.measure(View.java:27731)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
    at android.view.View.measure(View.java:27731)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at android.view.View.measure(View.java:27731)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at android.view.View.measure(View.java:27731)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
    at android.view.View.measure(View.java:27731)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1379)
    at android.view.View.measure(View.java:27731)
    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4841)
    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3397)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3732)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3116)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10885)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
    at android.view.Choreographer.doCallbacks(Choreographer.java:923)
    at android.view.Choreographer.doFrame(Choreographer.java:852)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8762)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30270090`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `r7`
* Model: `SM-N770F`
* Id: `TP1A.220624.014`
* Product: `r7naeea`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `N770FXXS9HWJ1`

**Comment by joshtrichards** [comment]
Fixed in #12290 already
It'll be in the V3.27.1 release
