### ISSUE TITLE
Java error when delete a photo from media 

### ISSUE THREAD

**Issue by raffaelevall** [nextcloud/android#12409]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open android App
2. open Media 
3. select a photo and delete it

### Expected behaviour

Delete the image

### Actual behaviour

show error, but delete the image:

### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Fragment PreviewMediaFragment{1221852} (dd0cef02-50a4-4bd2-96d5-156ca81d0928) not attached to a context.
    at androidx.fragment.app.Fragment.requireContext(Fragment.java:972)
    at com.owncloud.android.ui.preview.PreviewMediaFragment.lambda$onStart$1(PreviewMediaFragment.java:369)
    at com.owncloud.android.ui.preview.PreviewMediaFragment.$r8$lambda$AkxMJlf2KgePzqOIh5h57BVdLW8(Unknown Source:0)
    at com.owncloud.android.ui.preview.PreviewMediaFragment$$ExternalSyntheticLambda0.run(Unknown Source:2)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:210)
    at android.os.Looper.loop(Looper.java:299)
    at android.app.ActivityThread.main(ActivityThread.java:8292)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30270090`
* Build flavor: `gplay`

### Device information
* Brand: `Xiaomi`
* Device: `gauguin`
* Model: `M2007J17G`
* Id: `SKQ1.211006.001`
* Product: `gauguin_eea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `V14.0.2.0.SJSEUXM`

### Android version

12SKQ1.21100  6.001

### Device brand and model

Brand: `Xiaomi' Model: `M2007J17G`

### Stock or custom OS?

Stock

### Nextcloud android app version

30270090

### Nextcloud server version

Nextcloudpi 27.1.3

### Using a reverse proxy?

No

**Comment by satvik2131** [comment]
[Screencast from 20-02-24 02:42:37 PM IST.webm](https://github.com/nextcloud/android/assets/59243339/470ec204-ffb6-4bde-9474-775d42c30738)
Did I did it right ?
