### ISSUE TITLE
App crash when sync favorite folder

### ISSUE THREAD

**Issue by radioteh** [nextcloud/android#12502]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Go to favorite
Tap to folder actions
Tap to sync

### Expected behaviour

Folder should sync

### Actual behaviour

App crash with error log
### Cause of error
```java
Exception in thread "AsyncTask #7" java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$AsyncFutureTask.done(AsyncTask.java:426)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
    at java.util.concurrent.FutureTask.run(FutureTask.java:271)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:930)
Caused by: Exception in thread "AsyncTask #7" java.util.ConcurrentModificationException
    at java.util.ArrayList.sort(ArrayList.java:1472)
    at java.util.Collections.sort(Collections.java:208)
    at kotlin.collections.CollectionsKt__MutableCollectionsJVMKt.sortWith(MutableCollectionsJVM.kt:42)
    at com.owncloud.android.utils.FileSortOrderByName.sortServerFiles(FileSortOrderByName.kt:58)
    at com.owncloud.android.utils.FileSortOrderByName.sortCloudFiles(FileSortOrderByName.kt:43)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.setData(OCFileListAdapter.java:694)
    at com.owncloud.android.ui.fragment.OCFileListSearchAsyncTask.doInBackground(OCFileListSearchAsyncTask.kt:70)
    at com.owncloud.android.ui.fragment.OCFileListSearchAsyncTask.doInBackground(OCFileListSearchAsyncTask.kt:33)
    at android.os.AsyncTask$3.call(AsyncTask.java:394)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:930)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30240090`
* Build flavor: `huawei`

### Device information
* Brand: `HUAWEI`
* Device: `HWAGS5`
* Model: `AGS5-L09`
* Id: `HUAWEIAGS5-L09`
* Product: `AGS5-L09`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `103.0.0.163C10`

### Android version

Harmonyos 3.0.0.163

### Device brand and model

HUAWEI AGS5-L09

### Stock or custom OS?

Stock

### Nextcloud android app version

30240090

### Nextcloud server version

28.0.1

### Using a reverse proxy?

No

**Comment by joshtrichards** [comment]
This was already fixed in #11804. You're running an old version. You'll need to update to at least 3.26 if you want the fix.
