### ISSUE TITLE
app crash at start - android 7.1.2

### ISSUE THREAD

**Issue by iacopodeenosee** [nextcloud/android#1255]
### Actual behaviour
When I start the application this crash immediately without opening any activity

### Expected behaviour
the app start normaly
 
### Steps to reproduce
1. install it via f-droid
2. lauch it

### Environment data
Android version: 7.1.2

Device model: nexus 5

Stock or customized system: LineageOS 14.1

Nextcloud app version: 1.4.2

Nextcloud server version: 12

#### Web server error log
```
///
```

#### Nextcloud log (LOGCAT)
```
08-01 10:18:00.047 1809-1809/com.nextcloud.client V/ConnectivityActionReceiver: action: android.intent.action.ACTION_POWER_CONNECTED
08-01 10:18:00.047 1809-1809/com.nextcloud.client V/ConnectivityActionReceiver: component: ComponentInfo{com.nextcloud.client/com.owncloud.android.files.services.ConnectivityActionReceiver}
08-01 10:18:00.067 1809-1809/com.nextcloud.client V/ConnectivityActionReceiver: no extras
08-01 10:26:11.771 1809-1809/com.nextcloud.client V/FileDisplayActivity: onCreate() start
08-01 10:26:11.801 1809-1809/com.nextcloud.client W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
08-01 10:26:11.817 1809-1809/com.nextcloud.client D/FileDisplayActivity: onCreate(Bundle) starting
08-01 10:26:11.993 1809-1809/com.nextcloud.client I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
08-01 10:26:12.185 1809-1809/com.nextcloud.client V/FileDisplayActivity: onCreate() end
08-01 10:26:12.186 1809-1809/com.nextcloud.client D/FileDisplayActivity: onStart() starting
08-01 10:26:12.204 1809-4207/com.nextcloud.client D/ExternalLinks: links disabled
08-01 10:26:12.230 1809-1809/com.nextcloud.client E/FileDisplayActivity: Access to unexisting list of files fragment!!
08-01 10:26:12.230 1809-1809/com.nextcloud.client E/FileDisplayActivity: Access to unexisting list of files fragment!!
08-01 10:26:12.230 1809-1809/com.nextcloud.client E/FileDisplayActivity: OCFileListFragment is null
08-01 10:26:12.231 1809-1809/com.nextcloud.client V/FileDisplayActivity: onResume() start
08-01 10:26:12.231 1809-1809/com.nextcloud.client D/FileDisplayActivity: onResume() starting
08-01 10:26:12.232 1809-1809/com.nextcloud.client I/OCFileListFragment: onAttach
08-01 10:26:12.238 1809-1809/com.nextcloud.client I/OCFileListFragment: onCreateView() start
08-01 10:26:12.238 1809-1809/com.nextcloud.client D/ExtendedListFragment: onCreateView
08-01 10:26:12.349 1809-1809/com.nextcloud.client I/OCFileListFragment: onCreateView() end
08-01 10:26:12.350 1809-1809/com.nextcloud.client I/OCFileListFragment: onActivityCreated() start
08-01 10:26:12.383 1809-1809/com.nextcloud.client V/FileDisplayActivity: onResume() end
08-01 10:26:12.404 1809-1822/com.nextcloud.client I/AccountAuthenticator: Adding account with type nextcloud and auth token null
08-01 10:26:12.410 1809-1809/com.nextcloud.client D/OperationsService: Creating service
08-01 10:26:12.418 1809-1809/com.nextcloud.client D/FileDownloader: Creating service
08-01 10:26:12.431 1809-1809/com.nextcloud.client D/FileUploader: Creating service
08-01 10:26:12.440 1809-1809/com.nextcloud.client V/UploadsStorageManager: Updating state of any killed upload
08-01 10:26:12.446 1809-1809/com.nextcloud.client V/UploadsStorageManager: No upload was killed
08-01 10:26:12.447 1809-1809/com.nextcloud.client D/FileObserverService: Starting command Intent { act=com.owncloud.android.services.observer.FileObserverService.action.START_OBSERVATION cmp=com.nextcloud.client/com.owncloud.android.services.observer.FileObserverService }
08-01 10:26:12.447 1809-1809/com.nextcloud.client D/FileObserverService: Loading all kept-in-sync files from database to start watching them
08-01 10:26:12.500 1809-4210/com.nextcloud.client I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
08-01 10:26:12.504 1809-4210/com.nextcloud.client I/OpenGLRenderer: Initialized EGL, version 1.4
08-01 10:26:12.504 1809-4210/com.nextcloud.client D/OpenGLRenderer: Swap behavior 1
08-01 10:26:12.581 1809-1809/com.nextcloud.client V/FileDisplayActivity: onPause() start
08-01 10:26:12.583 1809-1809/com.nextcloud.client D/FileDisplayActivity: onPause() ending
08-01 10:26:12.583 1809-1809/com.nextcloud.client V/FileDisplayActivity: onPause() end
08-01 10:26:12.592 1809-1809/com.nextcloud.client D/FileActivity: Operations service connected
08-01 10:26:12.592 1809-1809/com.nextcloud.client D/FileDisplayActivity: Download service connected
08-01 10:26:12.592 1809-1809/com.nextcloud.client D/FileDisplayActivity: Upload service connected
08-01 10:26:12.607 1809-1809/com.nextcloud.client W/art: Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
08-01 10:26:12.764 1809-1809/com.nextcloud.client D/AuthenticatorActivity: onCreate(Bundle) starting
08-01 10:26:12.809 1809-1809/com.nextcloud.client I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
08-01 10:26:12.814 1809-1814/com.nextcloud.client I/art: Do partial code cache collection, code=24KB, data=31KB
08-01 10:26:12.815 1809-1814/com.nextcloud.client I/art: After code cache collection, code=19KB, data=28KB
08-01 10:26:12.815 1809-1814/com.nextcloud.client I/art: Increasing code cache capacity to 128KB
08-01 10:26:12.831 1809-1809/com.nextcloud.client I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
08-01 10:26:12.833 1809-1809/com.nextcloud.client I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
08-01 10:26:12.836 1809-1809/com.nextcloud.client I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
08-01 10:26:12.840 1809-1809/com.nextcloud.client I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
08-01 10:26:12.853 1809-1809/com.nextcloud.client D/AuthenticatorActivity: onStart() starting
08-01 10:26:12.855 1809-1809/com.nextcloud.client D/AuthenticatorActivity: onResume() starting
08-01 10:26:12.942 1809-1809/com.nextcloud.client D/AuthenticatorActivity: onPause() ending
08-01 10:26:12.987 1809-1809/com.nextcloud.client D/WhatsNewActivity: onCreate(Bundle) starting
08-01 10:26:13.044 1809-1809/com.nextcloud.client W/ResourceType: Failure getting entry for 0x7f08000a (t=7 e=10) (error -75)
08-01 10:26:13.046 1809-1809/com.nextcloud.client D/AndroidRuntime: Shutting down VM
08-01 10:26:13.053 1809-1809/com.nextcloud.client E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.nextcloud.client, PID: 1809
                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.WhatsNewActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x7f08000a
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
                                                                        at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                                     Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x7f08000a
                                                                        at android.content.res.Resources.getText(Resources.java:335)
                                                                        at android.widget.TextView.setText(TextView.java:4555)
                                                                        at com.owncloud.android.ui.activity.WhatsNewActivity.onCreate(WhatsNewActivity.java:142)
                                                                        at android.app.Activity.performCreate(Activity.java:6684)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751) 
                                                                        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:154) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6186) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
```

**Comment by mario** [comment]
Can you try if dev fixes it?

https://f-droid.org/wiki/page/com.nextcloud.android.beta

**Comment by tobiasKaminsky** [comment]
Duplicate of / same cause as in  #946

**Comment by cweiske** [comment]
Same here with Android 4.1.1. Works with the dev version.
