### ISSUE TITLE
crash app when write activities from random any file 

### ISSUE THREAD

**Issue by jaaneo** [nextcloud/android#12571]
### Additional context

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by jaaneo** [comment]
### Cause of error
java
Exception in thread "AsyncTask #3" java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$4.done(AsyncTask.java:415)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
    at java.util.concurrent.FutureTask.run(FutureTask.java:269)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
    at java.lang.Thread.run(Thread.java:1012)
Caused by: Exception in thread "AsyncTask #3" java.lang.IllegalArgumentException: Trying to execute a remote operation with a NULL OwnCloudClient
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:201)
    at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment$SubmitCommentTask.doInBackground(FileDetailActivitiesFragment.java:488)
    at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment$SubmitCommentTask.doInBackground(FileDetailActivitiesFragment.java:467)
    at android.os.AsyncTask$3.call(AsyncTask.java:394)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
    at java.lang.Thread.run(Thread.java:1012)



### App information
* ID: com.nextcloud.client
* Version: 30270090
* Build flavor: gplay

### Device information
* Brand: POCO
* Device: alioth
* Model: M2012K11AG
* Id: TKQ1.220829.002
* Product: alioth_global

### Firmware
* SDK: 33
* Release: 13
* Incremental: V14.0.8.0.TKHMIXM

https://github.com/nextcloud/android/assets/34485574/5cdca7d2-1322-4b1f-acf3-57c3bbdd66c7


![crash app android 1](https://github.com/nextcloud/android/assets/34485574/4f7f509c-85b8-4d62-9062-0400dbfe0b4b)
![crash app android 2](https://github.com/nextcloud/android/assets/34485574/e67b1c9e-ae49-4199-a0d5-a8e68f1eed69)

**Comment by MP715** [comment]
Same issue here

### Cause of error
```java
Exception in thread "AsyncTask #3" java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$4.done(AsyncTask.java:415)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
    at java.util.concurrent.FutureTask.run(FutureTask.java:269)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
    at java.lang.Thread.run(Thread.java:1012)
Caused by: Exception in thread "AsyncTask #3" java.lang.IllegalArgumentException: Trying to execute a remote operation with a NULL OwnCloudClient
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:201)
    at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment$SubmitCommentTask.doInBackground(FileDetailActivitiesFragment.java:488)
    at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment$SubmitCommentTask.doInBackground(FileDetailActivitiesFragment.java:467)
    at android.os.AsyncTask$3.call(AsyncTask.java:394)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30270090`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `o1q`
* Model: `SM-G991U`
* Id: `UP1A.231005.007`
* Product: `o1qsqw`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `G991USQSAFXAG`
