### ISSUE TITLE
Trying to list an E2EE folder causes crash

### ISSUE THREAD

**Issue by mpsd** [nextcloud/android#12614]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

While trying to open and list an E2EE encrypted folder in NC28.0.2 with Android App the App Crashes. Windows Desktop App works fine, so it seems to Android App specific issue.

This ist the Crash Report from Android App:

### Cause of error
```java
Exception in thread "Thread-16" java.lang.IllegalStateException: metadata is null!
    at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:490)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:415)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:244)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30280090`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `bluejay`
* Model: `Pixel 6a`
* Id: `UQ1A.240205.002`
* Product: `bluejay`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `11224170`

### Expected behaviour

App opens and lists directory

### Actual behaviour

App crashes

### Android version

14

### Device brand and model

Pixel 6a

### Stock or custom OS?

Stock

### Nextcloud android app version

3.28.0

### Nextcloud server version

28.0.2

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "Thread-16" java.lang.IllegalStateException: metadata is null!
    at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:490)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:415)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:244)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30280090`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `bluejay`
* Model: `Pixel 6a`
* Id: `UQ1A.240205.002`
* Product: `bluejay`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `11224170`

### Server error logs

```bash
None, No entries in Server Log file
```

**Comment by joshtrichards** [comment]
Closing since this was discussed via #12704 and addressed there.
