### ISSUE TITLE
Issue of server not available still present after latest nexcloud update 28.0.3

### ISSUE THREAD

**Issue by awptechnologies** [nextcloud/android#12648]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Try and view one of my auto upload folders.

### Expected behaviour

I expect the folder to refresh and show images.

### Actual behaviour

The loading icon spins and then freezes sometimes crashing app. Never able to see new images.

### Android version

14

### Device brand and model

Galaxy S22 Ultra

### Stock or custom OS?

Stock

### Nextcloud android app version

3.28.0

### Nextcloud server version

Nextcloud Hub 7 (28.0.3)

### Using a reverse proxy?

Yes

**Comment by limburgher** [comment]
I have this on the same app and NC versions, for all files on server. Stock OS, Galaxy S10+.

I've tried EasySync, and it's unable to connect. Looking for an IPv6 address, but my ISP doesn't allow inbound ipv6.

**Comment by awptechnologies** [comment]
i have ipv6 disabled and never had this issue before. Has to be something to do with the android app since i can access it just fine from browser on same phone.

**Comment by limburgher** [comment]
For me, All Files fails, Media succeeds.

**Comment by awptechnologies** [comment]
mine happens with my main upload folder. It does not happen on my autoupload folder containing videos. but yes thousands of photos

**Comment by limburgher** [comment]
The root of my main folder has 16 images. Lots more in subfolders if that matters.

**Comment by TryThisOneMyFriend** [comment]
Same for me here. Many constant crashs in the same way

**Comment by TryThisOneMyFriend** [comment]
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.Stack.push(java.lang.Object)' on a null object reference
    at com.owncloud.android.ui.activity.FileDisplayActivity.setSortListGroup(FileDisplayActivity.java:2496)
    at com.owncloud.android.ui.activity.FileDisplayActivity.setLeftFragment(FileDisplayActivity.java:616)
    at com.owncloud.android.ui.activity.FileDisplayActivity.setLeftFragment(FileDisplayActivity.java:604)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onNewIntent(FileDisplayActivity.java:550)
    at android.app.Activity.performNewIntent(Activity.java:8962)
    at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1556)
    at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1569)
    at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:4362)
    at android.app.ActivityThread.handleNewIntent(ActivityThread.java:4369)
    at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:56)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8893)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30280090`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `t2s`
* Model: `SM-G996B`
* Id: `UP1A.231005.007`
* Product: `t2sxxx`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `G996BXXS9FXAH`

**Comment by awptechnologies** [comment]
Idk what to do should i downgrade the nextcloud or what? every once in a while an auto upload will go through and i can view the new pics through a browser but as soon as i open android app in this one folder it crashes or says server not available...

**Comment by Killerjoe** [comment]
I have the same issue, currently I have only seen this on one folder. I use nextcloud android client 3.28.0 and nextcloud 28.0.3.
One note for this issue, I wanted to check what is the issue with the folder which consists of pdf, xlsx, psd, jpg, ods files and made a copy via webclient to a new folder.
This new folder is browsable with the nexctloud android client. So I only made a copy of the whole folder and that was working.
This is not a solution but maybe brings somebody from the devs to the right place to fix it.

**Comment by awptechnologies** [comment]
Even after moving all files to a new folder it still happens. i have reinstalled Nextcloud on phone. Downgraded to to 27 on android and i cant find any solution. Would be awesome if someone could help. or give me an idea of what to do.

**Comment by daukus** [comment]
Culprit are certain types of image files.

https://github.com/nextcloud/android/issues/12379

**Comment by awptechnologies** [comment]
What should i do to fix this? Downgrade to nextcloud 26 on android?

**Comment by joshtrichards** [comment]
"Server not available" in itself is a relatively generic state. To determine cause - and whether each of you are are experiencing the same situation - the logs (and, if applicable, crash output) are needed.

The main known situation is #12379. If that's your situation we need to close this out as a duplicate so we can focus on that one. If it's a different matter, the logs will help.

**Comment by daukus** [comment]
In my case it was about some old pictures taken with an lg phone. Pictures removed and all looking good again when reading folders.

![Screenshot 2024-03-25 001621](https://github.com/nextcloud/android/assets/78567609/4fdd7bf6-6b99-48a6-b783-b8e85b895190)

**Comment by limburgher** [comment]
3.28.1 fixes the issue for me.

**Comment by awptechnologies** [comment]
Fixed for me as well Thank you for the hard work. Now only if apple would stop being apple and allow autouploads to work correct.
