### ISSUE TITLE
E2E v2  Error creating encrypted folder / metadata is null

### ISSUE THREAD

**Issue by h144m** [nextcloud/android#12704]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Setup e2e 
2. create new folder 
3. set-encrypted
4. upload file

i tried it on android 3.28 and master (3.29-alpha1)

### Expected behaviour

set up an encrypted folder correctly and able to upload a file into it 

### Actual behaviour

show an errors and upload fails , refreshing inside the encrypted folder causes an app crash 

### Android version

14

### Device brand and model

Samsung S23 FE (SM-S711B/DS)

### Stock or custom OS?

Stock

### Nextcloud android app version

3.29-alpha1

### Nextcloud server version

Nextcloud Hub 7 (28.0.3)

### Using a reverse proxy?

I don't know

### Android logs

- folder encryption
```
Error creating encrypted folder
                                                                                                    com.owncloud.android.operations.UploadException: something wrong
                                                                                                    	at com.owncloud.android.utils.EncryptionUtils.retrieveMetadata(EncryptionUtils.java:1471)
                                                                                                    	at com.owncloud.android.ui.fragment.OCFileListFragment.encryptFolder(OCFileListFragment.java:1753)
                                                                                                    	at com.owncloud.android.ui.fragment.OCFileListFragment.onMessageEvent(OCFileListFragment.java:1717)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
                                                                                                    	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:511)
                                                                                                    	at org.greenrobot.eventbus.BackgroundPoster.run(BackgroundPoster.java:64)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
```

- file upload

```

 Upload of /storage/emulated/0/Android/data/com.nextcloud.client/files/Pictures/2024-03-19_134236.jpg to /H/2024-03-19_134236.jpg: Unexpected exception
                                                                                                    com.owncloud.android.operations.UploadException: Forbidden! Please try again later.)
                                                                                                    	at com.owncloud.android.utils.EncryptionUtils.lockFolder(EncryptionUtils.java:1347)
                                                                                                    	at com.owncloud.android.operations.UploadFileOperation.encryptedUpload(UploadFileOperation.java:478)
                                                                                                    	at com.owncloud.android.operations.UploadFileOperation.run(UploadFileOperation.java:437)
                                                                                                    	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:193)
                                                                                                    	at com.nextcloud.client.jobs.upload.FileUploadWorker.upload(FileUploadWorker.kt:235)
                                                                                                    	at com.nextcloud.client.jobs.upload.FileUploadWorker.uploadFiles(FileUploadWorker.kt:185)
                                                                                                    	at com.nextcloud.client.jobs.upload.FileUploadWorker.retrievePagesBySortingUploadsByID(FileUploadWorker.kt:159)
                                                                                                    	at com.nextcloud.client.jobs.upload.FileUploadWorker.doWork(FileUploadWorker.kt:114)
                                                                                                    	at androidx.work.Worker$1.run(Worker.java:82)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
```

- folder refreshing 

```

FATAL EXCEPTION: Thread-31
                                                                                                    Process: com.nextcloud.client, PID: 7802
                                                                                                    java.lang.IllegalStateException: metadata is null!
                                                                                                    	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:490)
                                                                                                    	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:415)
                                                                                                    	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:244)
                                                                                                    	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:387)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)

```

### Server error logs

```bash
{"reqId":"3WjEqgaBQY2VJtXwtNOK","level":3,"time":"2024-03-19T10:40:02+00:00","remoteAddr":"10.0.2.2","user":"h1","app":"no app in context","method":"GET","url":"/ocs/v2.php/apps/end_to_end_encryption/api/v1/meta-data/1868?format=json","message":"Exception thrown: OCP\\Files\\NotFoundException","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.29.0 Alpha1","version":"28.0.3.2","exception":{"Exception":"OCP\\Files\\NotFoundException","Message":"/appdata_ocrwsrm3ph16/end_to_end_encryption/meta-data/1868","Code":0,"Trace":[{"file":"/usr/share/nginx/nextcloud/lib/private/Files/Node/LazyFolder.php","line":161,"function":"get","class":"OC\\Files\\Node\\Root","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/private/Files/AppData/AppData.php","line":132,"function":"get","class":"OC\\Files\\Node\\LazyFolder","type":"->"},{"file":"/usr/share/nginx/nextcloud/apps/end_to_end_encryption/lib/MetaDataStorage.php","line":74,"function":"getFolder","class":"OC\\Files\\AppData\\AppData","type":"->"},{"file":"/usr/share/nginx/nextcloud/apps/end_to_end_encryption/lib/Middleware/ClientHasCapabilityMiddleware.php","line":67,"function":"getMetaData","class":"OCA\\EndToEndEncryption\\MetaDataStorage","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/private/AppFramework/Middleware/MiddlewareDispatcher.php","line":96,"function":"beforeController","class":"OCA\\EndToEndEncryption\\Middleware\\ClientHasCapabilityMiddleware","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":129,"function":"beforeController","class":"OC\\AppFramework\\Middleware\\MiddlewareDispatcher","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/usr/share/nginx/nextcloud/ocs/v1.php","line":65,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/usr/share/nginx/nextcloud/ocs/v2.php","line":23,"args":["/usr/share/nginx/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/usr/share/nginx/nextcloud/lib/private/Files/Node/Root.php","Line":207,"CustomMessage":"Exception thrown: OCP\\Files\\NotFoundException"}}
{"reqId":"4ZoMdcBJSUlqAxp0vfn6","level":3,"time":"2024-03-19T10:49:52+00:00","remoteAddr":"10.0.2.2","user":"--","app":"files","method":"GET","url":"/cron.php","message":"Backends provided no user object for h2","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0","version":"28.0.3.2","exception":{"Exception":"OC\\User\\NoUserException","Message":"Backends provided no user object","Code":0,"Trace":[{"function":"getUserFolder","class":"OC\\Files\\Node\\Root","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/private/Files/Node/LazyFolder.php","line":84,"function":"call_user_func_array"},{"file":"/usr/share/nginx/nextcloud/lib/private/Files/Node/LazyRoot.php","line":52,"function":"__call","class":"OC\\Files\\Node\\LazyFolder","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/private/FilesMetadata/Job/UpdateSingleMetadata.php","line":58,"function":"getUserFolder","class":"OC\\Files\\Node\\LazyRoot","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/public/BackgroundJob/Job.php","line":81,"function":"run","class":"OC\\FilesMetadata\\Job\\UpdateSingleMetadata","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/public/BackgroundJob/QueuedJob.php","line":57,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/public/BackgroundJob/QueuedJob.php","line":47,"function":"start","class":"OCP\\BackgroundJob\\QueuedJob","type":"->"},{"file":"/usr/share/nginx/nextcloud/cron.php","line":177,"function":"execute","class":"OCP\\BackgroundJob\\QueuedJob","type":"->"}],"File":"/usr/share/nginx/nextcloud/lib/private/Files/Node/Root.php","Line":365,"message":"Backends provided no user object for h2","exception":{},"CustomMessage":"Backends provided no user object for h2"}}
{"reqId":"4ZoMdcBJSUlqAxp0vfn6","level":2,"time":"2024-03-19T10:49:52+00:00","remoteAddr":"10.0.2.2","user":"--","app":"no app in context","method":"GET","url":"/cron.php","message":"issue while running UpdateSingleMetadata","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0","version":"28.0.3.2","exception":{"Exception":"OC\\User\\NoUserException","Message":"Backends provided no user object","Code":0,"Trace":[{"function":"getUserFolder","class":"OC\\Files\\Node\\Root","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/private/Files/Node/LazyFolder.php","line":84,"function":"call_user_func_array"},{"file":"/usr/share/nginx/nextcloud/lib/private/Files/Node/LazyRoot.php","line":52,"function":"__call","class":"OC\\Files\\Node\\LazyFolder","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/private/FilesMetadata/Job/UpdateSingleMetadata.php","line":58,"function":"getUserFolder","class":"OC\\Files\\Node\\LazyRoot","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/public/BackgroundJob/Job.php","line":81,"function":"run","class":"OC\\FilesMetadata\\Job\\UpdateSingleMetadata","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/public/BackgroundJob/QueuedJob.php","line":57,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/public/BackgroundJob/QueuedJob.php","line":47,"function":"start","class":"OCP\\BackgroundJob\\QueuedJob","type":"->"},{"file":"/usr/share/nginx/nextcloud/cron.php","line":177,"function":"execute","class":"OCP\\BackgroundJob\\QueuedJob","type":"->"}],"File":"/usr/share/nginx/nextcloud/lib/private/Files/Node/Root.php","Line":365,"message":"issue while running UpdateSingleMetadata","exception":{},"userId":"h2","fileId":368,"CustomMessage":"issue while running UpdateSingleMetadata"}}
{"reqId":"uB7fzKzAo90AEZYmDj5G","level":3,"time":"2024-03-19T10:50:54+00:00","remoteAddr":"10.0.2.2","user":"h1","app":"no app in context","method":"GET","url":"/ocs/v2.php/apps/end_to_end_encryption/api/v1/meta-data/1868?format=json","message":"Exception thrown: OCP\\Files\\NotFoundException","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.29.0 Alpha1","version":"28.0.3.2","exception":{"Exception":"OCP\\Files\\NotFoundException","Message":"/appdata_ocrwsrm3ph16/end_to_end_encryption/meta-data/1868","Code":0,"Trace":[{"file":"/usr/share/nginx/nextcloud/lib/private/Files/Node/LazyFolder.php","line":161,"function":"get","class":"OC\\Files\\Node\\Root","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/private/Files/AppData/AppData.php","line":132,"function":"get","class":"OC\\Files\\Node\\LazyFolder","type":"->"},{"file":"/usr/share/nginx/nextcloud/apps/end_to_end_encryption/lib/MetaDataStorage.php","line":74,"function":"getFolder","class":"OC\\Files\\AppData\\AppData","type":"->"},{"file":"/usr/share/nginx/nextcloud/apps/end_to_end_encryption/lib/Middleware/ClientHasCapabilityMiddleware.php","line":67,"function":"getMetaData","class":"OCA\\EndToEndEncryption\\MetaDataStorage","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/private/AppFramework/Middleware/MiddlewareDispatcher.php","line":96,"function":"beforeController","class":"OCA\\EndToEndEncryption\\Middleware\\ClientHasCapabilityMiddleware","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":129,"function":"beforeController","class":"OC\\AppFramework\\Middleware\\MiddlewareDispatcher","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/usr/share/nginx/nextcloud/ocs/v1.php","line":65,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/usr/share/nginx/nextcloud/ocs/v2.php","line":23,"args":["/usr/share/nginx/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/usr/share/nginx/nextcloud/lib/private/Files/Node/Root.php","Line":207,"CustomMessage":"Exception thrown: OCP\\Files\\NotFoundException"}}

```
```


### Additional information

end-to-end app v1.14.3 , encrypted folders created by the desktop / IOS apps works fine .

**Comment by h144m** [comment]
```     
  } else if (getMetadataOperationResult.getHttpCode() == HttpStatus.SC_NOT_FOUND) { 
```
[EncryptionUtils.java#L1452](https://github.com/nextcloud/android/blob/c35b63e50b222b756ade7682729fa0f07426f21b/app/src/main/java/com/owncloud/android/utils/EncryptionUtils.java#L1452)
i got 
```
RemoteOperationResult{mSuccess=false, mHttpCode=500, mHttpPhrase='Internal Server Error', mException=null, mCode=INSTANCE_NOT_CONFIGURED, message='null', getLogMessage='The Nextcloud server is not configured!'}
```

which i believe is the cause of the issue (ios / desktop works fine on the same server)

**Comment by Clautens** [comment]
I get the same error when I try to open an encrypted folder with the android app:

```
### Cause of error
```java
Exception in thread "Thread-13" java.lang.IllegalStateException: metadata is null!
    at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:490)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:415)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:244)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30280090`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `y2s`
* Model: `SM-G985F`
* Id: `TP1A.220624.014`
* Product: `y2seea`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `G985FXXSJHXA1`

```

**Comment by AndyScherzinger** [comment]
also looping in @alperozturk96

**Comment by kentxvalentines** [comment]
I am getting the same issue and is having the below log entries. 
```
{
  "reqId": "D9fPyB65vaAKDw67O0Ga",
  "level": 3,
  "time": "2024-03-28T07:18:49+00:00",
  "remoteAddr": "113.211.121.235",
  "user": "nyx",
  "app": "no app in context",
  "method": "GET",
  "url": "/ocs/v2.php/apps/end_to_end_encryption/api/v1/meta-data/1692007?format=json",
  "message": "Exception thrown: OCP\\Files\\NotFoundException",
  "userAgent": "Mozilla/5.0 (Android) Nextcloud-android/3.28.0",
  "version": "28.0.3.2",
  "exception": {
    "Exception": "OCP\\Files\\NotFoundException",
    "Message": "/appdata_ocdfavxnpprd/end_to_end_encryption/meta-data/1692007",
    "Code": 0,
    "Trace": [
      {
        "file": "/home/redacted/public_html/lib/private/Files/Node/LazyFolder.php",
        "line": 161,
        "function": "get",
        "class": "OC\\Files\\Node\\Root",
        "type": "->"
      },
      {
        "file": "/home/redacted/public_html/lib/private/Files/AppData/AppData.php",
        "line": 132,
        "function": "get",
        "class": "OC\\Files\\Node\\LazyFolder",
        "type": "->"
      },
      {
        "file": "/home/redacted/public_html/apps/end_to_end_encryption/lib/MetaDataStorage.php",
        "line": 74,
        "function": "getFolder",
        "class": "OC\\Files\\AppData\\AppData",
        "type": "->"
      },
      {
        "file": "/home/redacted/public_html/apps/end_to_end_encryption/lib/Middleware/ClientHasCapabilityMiddleware.php",
        "line": 67,
        "function": "getMetaData",
        "class": "OCA\\EndToEndEncryption\\MetaDataStorage",
        "type": "->"
      },
      {
        "file": "/home/redacted/public_html/lib/private/AppFramework/Middleware/MiddlewareDispatcher.php",
        "line": 96,
        "function": "beforeController",
        "class": "OCA\\EndToEndEncryption\\Middleware\\ClientHasCapabilityMiddleware",
        "type": "->"
      },
      {
        "file": "/home/redacted/public_html/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 129,
        "function": "beforeController",
        "class": "OC\\AppFramework\\Middleware\\MiddlewareDispatcher",
        "type": "->"
      },
      {
        "file": "/home/redacted/public_html/lib/private/AppFramework/App.php",
        "line": 184,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/home/redacted/public_html/lib/private/Route/Router.php",
        "line": 315,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/home/redacted/public_html/ocs/v1.php",
        "line": 65,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/home/redacted/public_html/ocs/v2.php",
        "line": 23,
        "args": [
          "/home/redacted/public_html/ocs/v1.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/home/redacted/public_html/lib/private/Files/Node/Root.php",
    "Line": 207,
    "CustomMessage": "Exception thrown: OCP\\Files\\NotFoundException"
  }
}
```

Im on the latest stable release of NC 28.0.3

hope that this helps

**Comment by mpsd** [comment]
Same issue here with similar Setup: NC28.0.3 Android Client 3.28.0 in Android 14.

E2EE currently not working.

**Comment by kentxvalentines** [comment]
i found out the issue was caused by duplicatefinder app which attempted to remove the metadata file as duplicate file. 
i disabled the app and  e2ee is now working fine.
