### ISSUE TITLE
E2E v2 File upload failed in an encrypted folder 

### ISSUE THREAD

**Issue by h144m** [nextcloud/android#12718]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

upload a file in an encrypted folder 

### Expected behaviour

file uploads without any issues

### Actual behaviour

file doesnt upload 

### Android version

14

### Device brand and model

Samsung S23 FE (SM-S711B/DS)

### Stock or custom OS?

Stock

### Nextcloud android app version

3.29-alpha1

### Nextcloud server version

Nextcloud Hub 7 (28.0.3)

### Using a reverse proxy?

I don't know

### Android logs

```
Storing of metadata for folder 00002690ocrwsrm3ph16 failed: {"ocs":{"meta":{"status":"failure","statuscode":409,"message":""},"data":[]}}
2024-03-21 16:22:30.916  2243-3407  UploadFileOperation     com.nextcloud.client                 E  Upload of /storage/emulated/0/Android/data/com.nextcloud.client/files/Pictures/2024-03-21_162215.jpg to /E2e/1202b50d51b84e53a51a4c0ca805d817: Unexpected exception
                                                                                                    com.owncloud.android.operations.UploadException: Storing metadata was not successful
                                                                                                    	at com.owncloud.android.utils.EncryptionUtilsV2.serializeAndUploadMetadata(EncryptionUtilsV2.kt:962)
                                                                                                    	at com.owncloud.android.utils.EncryptionUtilsV2.serializeAndUploadMetadata(EncryptionUtilsV2.kt:893)
                                                                                                    	at com.owncloud.android.operations.UploadFileOperation.encryptedUpload(UploadFileOperation.java:729)
                                                                                                    	at com.owncloud.android.operations.UploadFileOperation.run(UploadFileOperation.java:437)
                                                                                                    	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:193)
                                                                                                    	at com.nextcloud.client.jobs.upload.FileUploadWorker.upload(FileUploadWorker.kt:235)
                                                                                                    	at com.nextcloud.client.jobs.upload.FileUploadWorker.uploadFiles(FileUploadWorker.kt:185)
                                                                                                    	at com.nextcloud.client.jobs.upload.FileUploadWorker.retrievePagesBySortingUploadsByID(FileUploadWorker.kt:159)
                                                                                                    	at com.nextcloud.client.jobs.upload.FileUploadWorker.doWork(FileUploadWorker.kt:114)
                                                                                                    	at androidx.work.Worker$1.run(Worker.java:82)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
```

### Server error logs

```bash
none
```

### Additional information

end-to-end app v1.14.3

initially solved by adding else statement : [here ](https://github.com/nextcloud/android/blob/5e7458670b7b329af829b5d90044887ea55e5b17/app/src/main/java/com/owncloud/android/operations/UploadFileOperation.java#L497)

```
          if (CapabilityUtils.getCapability(mContext).getEndToEndEncryptionApiVersion().compareTo(E2EVersion.V2_0) >= 0) {
                if (object == null) {
                    return new RemoteOperationResult(new IllegalStateException("Metadata does not exist"));
                }else {
                  metadataExists = true;
                      }
            }

```

**Comment by joshtrichards** [comment]
Fixed in #12668
