### ISSUE TITLE
Crash on back button after viewing PDF file

### ISSUE THREAD

**Issue by svbergerem** [nextcloud/android#12748]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Tap on a PDF file in Nextcloud that has not been downloaded before.
2. Wait for the download to finish. (Nextcloud shows a details page for the file)
3. Select an app to open the file.
4. Wait. (definitely works if you wait for a day, a few hours are also sufficient)
5. Show open apps in Android, go to Nextcloud.
6. Nextcloud still shows the details page.
7. Go back in Android (swipe / tap the global back button)

### Expected behaviour

Nextcloud shows the last opened directory or at least the "home" screen.

### Actual behaviour

Nextcloud crashes.

### Android version

14

### Device brand and model

Samsung SM-X800

### Stock or custom OS?

Stock

### Nextcloud android app version

3.28.0

### Nextcloud server version

27.1.5

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.Stack.pop()' on a null object reference
    at com.owncloud.android.ui.activity.FileDisplayActivity.popSortListGroupVisibility(FileDisplayActivity.java:2505)
    at com.owncloud.android.ui.activity.FileDisplayActivity.popBack(FileDisplayActivity.java:1048)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onBackPressed(FileDisplayActivity.java:1003)
    at android.app.Activity.onKeyUp(Activity.java:4140)
    at android.view.KeyEvent.dispatch(KeyEvent.java:3522)
    at android.app.Activity.dispatchKeyEvent(Activity.java:4488)
    at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:120)
    at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:85)
    at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:138)
    at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)
    at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:60)
    at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3413)
    at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:688)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:8412)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:8272)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7605)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7662)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7628)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7831)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7636)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7888)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7609)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7662)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7628)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7636)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7609)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7662)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7628)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7864)
    at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:8106)
    at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:4578)
    at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:4012)
    at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:4003)
    at android.view.inputmethod.InputMethodManager.-$$Nest$mfinishedInputEvent(Unknown Source:0)
    at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:4555)
    at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
    at android.os.MessageQueue.nativePollOnce(Native Method)
    at android.os.MessageQueue.next(MessageQueue.java:335)
    at android.os.Looper.loopOnce(Looper.java:187)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8913)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30280090`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `gts8pwifi`
* Model: `SM-X800`
* Id: `UP1A.231005.007`
* Product: `gts8pwifieea`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `X800XXS6CXB4`

**Comment by alperozturk96** [comment]
@svbergerem  Could you try with [latest](https://github.com/nextcloud/android/releases/tag/stable-3.28.1 ) version ?

**Comment by svbergerem** [comment]
@alperozturk96 I tried, but then, after step 3, it says that the download failed. This happens for all files that have not been downloaded yet and that I tried so far. When going back from the file detail view to the folder view, the file size is given as 0 B. After refreshing the folder view, it shows again the correct size. So, all in all, I'm unable to reproduce the error with the latest version, but this is just because I am unable to open the files from Nextcloud.

Meanwhile, on another device with version 3.28.0, downloading and opening files from Nextcloud works without any problems.
