### ISSUE TITLE
Crash while viewing (and downloading) media (in the background) 

### ISSUE THREAD

**Issue by rugk** [nextcloud/android#12760]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Dunno, I just swiped some screen. 

### Expected behaviour

Not crash

### Actual behaviour

Crashed and the report dialog let me here

### Android version

14

### Device brand and model

Fairphone 4 (FP4)

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.28.0

### Nextcloud server version

dunno

### Using a reverse proxy?

Yes

### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
    at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1632)
    at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1672)
    at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:341)
    at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:306)
    at androidx.fragment.app.DialogFragment.show(DialogFragment.java:524)
    at com.owncloud.android.ui.activity.FileActivity.showLoadingDialog(FileActivity.java:556)
    at com.owncloud.android.ui.helpers.FileOperationsHelper.lambda$syncFile$1(FileOperationsHelper.java:254)
    at com.owncloud.android.ui.helpers.FileOperationsHelper.$r8$lambda$4uYT9xe-AzaengRJid_wcYy-yTI(Unknown Source:0)
    at com.owncloud.android.ui.helpers.FileOperationsHelper$$ExternalSyntheticLambda4.run(Unknown Source:2)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.app.ActivityThread.main(ActivityThread.java:8248)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30280090`
* Build flavor: `generic`

### Device information
* Brand: `Fairphone`
* Device: `FP4`
* Model: `FP4`
* Id: `UQ1A.240205.004`
* Product: `FP4eea`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `24504010`

### Additional information

OS: Android 14, CalyxOS 5.4.1  
source: F-Droid  
Build-ID: `UQ1A.240205.004.24504010`

**Comment by rugk** [comment]
After the issue started, I restarted nextcloud and opened an image. In the background the download may still be triggered.

After some crashes and restarts, it starts in the main folder and maybe also stopped the download?

**Comment by rugk** [comment]
It's hard to reproduce so well, but thanks for fixing!
