### ISSUE TITLE
Doesn't open pdf in android app

### ISSUE THREAD

**Issue by mihanic89** [nextcloud/android#12830]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open android app
2. Choose any pdf
3. Open it

### Expected behaviour

Bug 

### Actual behaviour

Pdf download and open

### Android version

14

### Device brand and model

Samsung a52

### Stock or custom OS?

Stock

### Nextcloud android app version

3.28.1

### Nextcloud server version

AIO v8.1.0 nc v28.0.4

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.Stack.push(java.lang.Object)' on a null object reference
    at com.owncloud.android.ui.activity.FileDisplayActivity.setSortListGroup(FileDisplayActivity.java:2497)
    at com.owncloud.android.ui.activity.FileDisplayActivity.setLeftFragment(FileDisplayActivity.java:616)
    at com.owncloud.android.ui.activity.FileDisplayActivity.startDownloadForPreview(FileDisplayActivity.java:2146)
    at com.owncloud.android.ui.fragment.OCFileListFragment.onItemClicked(OCFileListFragment.java:1101)
    at com.owncloud.android.ui.adapter.OCFileListDelegate.setItemLayoutOnClickListeners$lambda$3(OCFileListDelegate.kt:287)
    at com.owncloud.android.ui.adapter.OCFileListDelegate.$r8$lambda$DobHPKcHFAOyPw3I9tHUhxGMBtQ(Unknown Source:0)
    at com.owncloud.android.ui.adapter.OCFileListDelegate$$ExternalSyntheticLambda1.onClick(Unknown Source:4)
    at android.view.View.performClick(View.java:8043)
    at android.view.View.performClickInternal(View.java:8020)
    at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
    at android.view.View$PerformClick.run(View.java:31850)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8893)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30280190`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `a52q`
* Model: `SM-A525F`
* Id: `UP1A.231005.007`
* Product: `a52qnsser`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `A525FXXS6EXC2`

**Comment by ralfi** [comment]
Same here, only PDFs. Jpg, Libreoffice files etc. works

**Comment by ostasevych** [comment]
The reason is simple: there's a bug that the files to be open are saved to temp (media/com.nextcloud.client/nextcloud.tmp/<username>/), but not opened from temp.

**Comment by dneuhaeuser** [comment]
3.28.2 now available in Playstore.
-> problem solved

**Comment by mihanic89** [comment]
Great, thanks
