### ISSUE TITLE
Crash by trying to share photo

### ISSUE THREAD

**Issue by 1div0** [nextcloud/android#12866]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Select image in gallery
Press share

### Expected behaviour

Share the image in the selected application

### Actual behaviour

Boom

### Android version

Old A6

### Device brand and model

Lenovo

### Stock or custom OS?

Stock

### Nextcloud android app version

Latest

### Nextcloud server version

Latest

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" android.util.AndroidRuntimeException: requestFeature() must be called before adding content
    at com.android.internal.policy.PhoneWindow.requestFeature(PhoneWindow.java:336)
    at android.app.Dialog.requestWindowFeature(Dialog.java:1149)
    at com.owncloud.android.ui.dialog.SslUntrustedCertDialog.onCreateDialog(SslUntrustedCertDialog.java:168)
    at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:665)
    at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:579)
    at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1755)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:493)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1901)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1819)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1762)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
    at android.os.Handler.handleCallback(Handler.java:815)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loop(Looper.java:207)
    at android.app.ActivityThread.main(ActivityThread.java:5765)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30250090`
* Build flavor: `gplay`

### Device information
* Brand: `Lenovo`
* Device: `TB3-X70L`
* Model: `Lenovo TB3-X70L`
* Id: `MRA58K`
* Product: `LenovoTB3-X70L`

### Firmware
* SDK: `23`
* Release: `6.0`
* Incremental: `Lenovo_TB3-X70L_USR_S000022`

**Comment by alperozturk96** [comment]
Minimum supported Android version is 7
