### ISSUE TITLE
Nextcloud dev app crashed when I adding the widget

### ISSUE THREAD

**Issue by alr86** [nextcloud/android#12948]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Drop nextcloud widget to home screen to add it

### Expected behaviour

...

### Actual behaviour

App opened in nextcloud crashed page

## Cause of error
```java
Exception in thread "DefaultDispatcher-worker-1" java.lang.RuntimeException: Accessing result data after operation failed!
    at com.owncloud.android.lib.common.operations.RemoteOperationResult.getResultData(RemoteOperationResult.java:489)
    at com.nextcloud.client.widget.DashboardWidgetConfigurationActivity$loadWidgets$1$2.invokeSuspend(DashboardWidgetConfigurationActivity.kt:180)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.app.ActivityThread.main(ActivityThread.java:8190)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20240314`
* Build flavor: `versionDev`

### Device information
* Brand: `Redmi`
* Device: `merlinx`
* Model: `Redmi Note 9`
* Id: `UQ1A.231205.015`
* Product: `lineage_merlinx`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `1703757133`

### Additional information

* OS: CrDroid v10.0

**Comment by joshtrichards** [comment]
Fixed in #13230
