### ISSUE TITLE
Unable to log in using Yubikey

### ISSUE THREAD

**Issue by thederputy** [nextcloud/android#12965]
### Cause of error
```java
Exception in thread "security-key-dispatcher" java.lang.SecurityException: Permission Denial: Tag ( ID: 27 82 41 2F 01 41 82 ) is out of date
    at android.nfc.Tag.getTagService(Tag.java:381)
    at android.nfc.tech.IsoDep.isExtendedLengthApduSupported(IsoDep.java:199)
    at de.cotech.hw.internal.transport.nfc.NfcTransport.isExtendedLengthSupported(NfcTransport.java:165)
    at de.cotech.hw.fido2.internal.Fido2AppletConnection.sendWithChaining(Fido2AppletConnection.java:267)
    at de.cotech.hw.fido2.internal.Fido2AppletConnection.communicate(Fido2AppletConnection.java:237)
    at de.cotech.hw.fido2.internal.Fido2AppletConnection.communicateOrThrow(Fido2AppletConnection.java:209)
    at de.cotech.hw.fido2.internal.Fido2AppletConnection.selectFileOrFail(Fido2AppletConnection.java:191)
    at de.cotech.hw.fido2.internal.Fido2AppletConnection.selectFilesFromPrefixOrFail(Fido2AppletConnection.java:168)
    at de.cotech.hw.fido2.internal.Fido2AppletConnection.connectToDevice(Fido2AppletConnection.java:119)
    at de.cotech.hw.fido2.internal.Fido2AppletConnection.connectIfNecessary(Fido2AppletConnection.java:109)
    at de.cotech.hw.fido2.Fido2SecurityKeyConnectionMode.establishSecurityKeyConnection(Fido2SecurityKeyConnectionMode.java:71)
    at de.cotech.hw.fido2.Fido2SecurityKeyConnectionMode.establishSecurityKeyConnection(Fido2SecurityKeyConnectionMode.java:42)
    at de.cotech.hw.SecurityKeyManager$RegisteredConnectionMode.attemptConnectWithRegisteredSecurityMode(SecurityKeyManager.java:565)
    at de.cotech.hw.SecurityKeyManager$RegisteredConnectionMode.transportAttemptImmediate(SecurityKeyManager.java:516)
    at de.cotech.hw.SecurityKeyManager.transportConnectAndDeliverOrPostponeOrFail(SecurityKeyManager.java:355)
    at de.cotech.hw.SecurityKeyManager.$r8$lambda$U0afJSaxV9KUsbh9tfh4qT2dpwE(Unknown Source:0)
    at de.cotech.hw.SecurityKeyManager$$ExternalSyntheticLambda1.nfcTransportDiscovered(D8$$SyntheticClass:0)
    at de.cotech.hw.internal.transport.nfc.NfcTagManager$ManagedNfcTag.lambda$createNewActiveNfcTransport$0$de-cotech-hw-internal-transport-nfc-NfcTagManager$ManagedNfcTag(NfcTagManager.java:133)
    at de.cotech.hw.internal.transport.nfc.NfcTagManager$ManagedNfcTag$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.os.HandlerThread.run(HandlerThread.java:67)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290090`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `sunfish`
* Model: `Pixel 4a`
* Id: `TQ3A.230805.001.S1`
* Product: `sunfish`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `10786265`

**Comment by joshtrichards** [comment]
Hmm. 

Maybe related to this: https://stackoverflow.com/questions/75695662/securityexception-while-ndef-connect-on-android-13
