### ISSUE TITLE
Crash while moving photos

### ISSUE THREAD

**Issue by gigcastro** [nextcloud/android#13001]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

App crashes when attempting to move a few selected photos in my OnePlus 9:
1. Have a folder with auto-sync activated
2. Select a few of the auto-synced photos (30 aprox).
3. Attempt to move them to another folder. I particularly use a shared folder.
It always crashes, happens everytime.

### Expected behaviour

Allowing me to select a folder where to move the photos, select "move" and return back to the original folder.

### Actual behaviour

Move operation is realized but the app crashes when tries to go back to the original folder. The app displays the stacktrace and error logs.

### Android version

14

### Device brand and model

OnePlus 9

### Stock or custom OS?

Stock

### Nextcloud android app version

30290090

### Nextcloud server version

23

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "Thread-31" java.lang.IllegalStateException: Couldn't read row 579, col 20 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetLong(Native Method)
    at android.database.CursorWindow.getLong(CursorWindow.java:539)
    at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:78)
    at com.nextcloud.client.database.dao.FileDao_Impl.getFolderContent(FileDao_Impl.java:2025)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:917)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:225)
    at com.owncloud.android.datamodel.FileDataStorageManager.prepareRemoveSharesInFolder(FileDataStorageManager.java:1580)
    at com.owncloud.android.datamodel.FileDataStorageManager.saveSharesInFolder(FileDataStorageManager.java:1525)
    at com.owncloud.android.operations.RefreshFolderOperation.refreshSharesForFolder(RefreshFolderOperation.java:814)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:270)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:387)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290090`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OnePlus9`
* Model: `LE2115`
* Id: `UKQ1.230924.001`
* Product: `OnePlus9`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `R.1695d68-52ce-52cd`

**Comment by A-Nicoladie** [comment]
Same here 🖐️

My log

### Cause of error
```java
Exception in thread "Thread-153" java.lang.IllegalStateException: Couldn't read row 618, col 20 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetLong(Native Method)
    at android.database.CursorWindow.getLong(CursorWindow.java:542)
    at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:77)
    at androidx.room.driver.SupportSQLiteStatement$SupportAndroidSQLiteStatement.getLong(SupportSQLiteStatement.android.kt:141)
    at com.nextcloud.client.database.dao.FileDao_Impl.getFolderContent$lambda$6(FileDao_Impl.kt:2555)
    at com.nextcloud.client.database.dao.FileDao_Impl.$r8$lambda$t-_pYRcUULZnQWVXjqSiZNjbUW4(Unknown Source:0)
    at com.nextcloud.client.database.dao.FileDao_Impl$$ExternalSyntheticLambda8.invoke(D8$$SyntheticClass:0)
    at androidx.room.util.DBUtil__DBUtil_androidKt$performBlocking$1$invokeSuspend$$inlined$internalPerform$1.invokeSuspend(DBUtil.kt:68)
    at androidx.room.util.DBUtil__DBUtil_androidKt$performBlocking$1$invokeSuspend$$inlined$internalPerform$1.invoke(Unknown Source:8)
    at androidx.room.util.DBUtil__DBUtil_androidKt$performBlocking$1$invokeSuspend$$inlined$internalPerform$1.invoke(Unknown Source:4)
    at androidx.room.driver.SupportSQLiteConnectionPool.useConnection(SupportSQLiteConnectionPool.android.kt:42)
    at androidx.room.RoomConnectionManager.useConnection(RoomConnectionManager.android.kt:126)
    at androidx.room.RoomDatabase.useConnection$room_runtime_release(RoomDatabase.android.kt:593)
    at androidx.room.util.DBUtil__DBUtil_androidKt$performBlocking$1.invokeSuspend(DBUtil.android.kt:247)
    at androidx.room.util.DBUtil__DBUtil_androidKt$performBlocking$1.invoke(Unknown Source:8)
    at androidx.room.util.DBUtil__DBUtil_androidKt$performBlocking$1.invoke(Unknown Source:4)
    at androidx.room.coroutines.RunBlockingUninterruptible_androidKt$runBlockingUninterruptible$1$1.invokeSuspend(RunBlockingUninterruptible.android.kt:52)
    at androidx.room.coroutines.RunBlockingUninterruptible_androidKt$runBlockingUninterruptible$1$1.invoke(Unknown Source:8)
    at androidx.room.coroutines.RunBlockingUninterruptible_androidKt$runBlockingUninterruptible$1$1.invoke(Unknown Source:4)
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:27)
    at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:90)
    at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:123)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
    at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
    at androidx.room.coroutines.RunBlockingUninterruptible_androidKt$runBlockingUninterruptible$1.invokeSuspend(RunBlockingUninterruptible.android.kt:51)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
    at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
    at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
    at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
    at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
    at androidx.room.coroutines.RunBlockingUninterruptible_androidKt.runBlockingUninterruptible(RunBlockingUninterruptible.android.kt:45)
    at androidx.room.util.DBUtil__DBUtil_androidKt.performBlocking(DBUtil.android.kt:69)
    at androidx.room.util.DBUtil.performBlocking(Unknown Source:1)
    at com.nextcloud.client.database.dao.FileDao_Impl.getFolderContent(FileDao_Impl.kt:2367)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:1170)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:452)
    at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:525)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:433)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:246)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:387)
    at java.lang.Thread.run(Thread.java:919)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30320290`
* Build flavor: `generic`

### Device information
* Brand: `unknown`
* Device: `unknown`
* Model: `unknown`
* Id: `unknown`
* Product: `unknown`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `c65720e3ac`

**Comment by gallyamb** [comment]
I've also faced this issue

### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Unable to resume activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.IllegalStateException: Couldn't read row 554, col 20 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:6023)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:6056)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:70)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:271)
    at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:146)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:120)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:3110)
    at android.os.Handler.dispatchMessage(Handler.java:109)
    at android.os.Looper.loopOnce(Looper.java:250)
    at android.os.Looper.loop(Looper.java:340)
    at android.app.ActivityThread.main(ActivityThread.java:9930)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:625)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)
Caused by: Exception in thread "main" java.lang.IllegalStateException: Couldn't read row 554, col 20 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetLong(Native Method)
    at android.database.CursorWindow.getLong(CursorWindow.java:547)
    at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:78)
    at androidx.room.driver.SupportSQLiteStatement$SupportAndroidSQLiteStatement.getLong(SupportSQLiteStatement.android.kt:190)
    at com.nextcloud.client.database.dao.FileDao_Impl.getFolderContent$lambda$0(FileDao_Impl.kt:2929)
    at com.nextcloud.client.database.dao.FileDao_Impl.$r8$lambda$HH3Vt0aXJGuStEBTT9L2wVpzKrk(Unknown Source:0)
    at com.nextcloud.client.database.dao.FileDao_Impl$$ExternalSyntheticLambda15.invoke(D8$$SyntheticClass:0)
    at androidx.room.util.DBUtil__DBUtil_androidKt$performBlocking$1$invokeSuspend$$inlined$internalPerform$1.invokeSuspend(DBUtil.kt:68)
    at androidx.room.util.DBUtil__DBUtil_androidKt$performBlocking$1$invokeSuspend$$inlined$internalPerform$1.invoke(Unknown Source:8)
    at androidx.room.util.DBUtil__DBUtil_androidKt$performBlocking$1$invokeSuspend$$inlined$internalPerform$1.invoke(Unknown Source:4)
    at androidx.room.driver.SupportSQLiteConnectionPool.useConnection(SupportSQLiteConnectionPool.android.kt:42)
    at androidx.room.RoomConnectionManager.useConnection(RoomConnectionManager.android.kt:126)
    at androidx.room.RoomDatabase.useConnection$room_runtime_release(RoomDatabase.android.kt:593)
    at androidx.room.util.DBUtil__DBUtil_androidKt$performBlocking$1.invokeSuspend(DBUtil.android.kt:247)
    at androidx.room.util.DBUtil__DBUtil_androidKt$performBlocking$1.invoke(Unknown Source:8)
    at androidx.room.util.DBUtil__DBUtil_androidKt$performBlocking$1.invoke(Unknown Source:4)
    at androidx.room.coroutines.RunBlockingUninterruptible_androidKt$runBlockingUninterruptible$1$1.invokeSuspend(RunBlockingUninterruptible.android.kt:52)
    at androidx.room.coroutines.RunBlockingUninterruptible_androidKt$runBlockingUninterruptible$1$1.invoke(Unknown Source:8)
    at androidx.room.coroutines.RunBlockingUninterruptible_androidKt$runBlockingUninterruptible$1$1.invoke(Unknown Source:4)
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:20)
    at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:360)
    at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:124)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
    at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
    at androidx.room.coroutines.RunBlockingUninterruptible_androidKt$runBlockingUninterruptible$1.invokeSuspend(RunBlockingUninterruptible.android.kt:51)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
    at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
    at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
    at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:47)
    at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
    at androidx.room.coroutines.RunBlockingUninterruptible_androidKt.runBlockingUninterruptible(RunBlockingUninterruptible.android.kt:45)
    at androidx.room.util.DBUtil__DBUtil_androidKt.performBlocking(DBUtil.android.kt:69)
    at androidx.room.util.DBUtil.performBlocking(Unknown Source:1)
    at com.nextcloud.client.database.dao.FileDao_Impl.getFolderContent(FileDao_Impl.kt:2741)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:1176)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:458)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:882)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1582)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1531)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1520)
    at com.owncloud.android.ui.activity.FileDisplayActivity.updateListOfFilesFragment(FileDisplayActivity.kt:785)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onResume(FileDisplayActivity.kt:1279)
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1722)
    at android.app.Activity.performResume(Activity.java:9651)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:6006)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:6056)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:70)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:271)
    at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:146)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:120)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:3110)
    at android.os.Handler.dispatchMessage(Handler.java:109)
    at android.os.Looper.loopOnce(Looper.java:250)
    at android.os.Looper.loop(Looper.java:340)
    at android.app.ActivityThread.main(ActivityThread.java:9930)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:625)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30340090`
* Build flavor: `gplay`

### Device information
* Brand: `vivo`
* Device: `PD2436`
* Model: `V2436A`
* Id: `AP3A.240905.015.A2_V000L1`
* Product: `PD2436`

### Firmware
* SDK: `35`
* Release: `15`
* Incremental: `compiler250917200830`
