### ISSUE TITLE
`com.google.gson.stream.MalformedJsonException`

### ISSUE THREAD

**Issue by Anatol2121** [nextcloud/android#13019]
### Cause of error
```java
Exception in thread "Thread-5" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
    at com.google.gson.JsonParser.parseReader(JsonParser.java:76)
    at com.google.gson.JsonParser.parseString(JsonParser.java:51)
    at com.owncloud.android.authentication.AuthenticatorActivity.lambda$anonymouslyPostLoginRequest$1(AuthenticatorActivity.java:385)
    at com.owncloud.android.authentication.AuthenticatorActivity.$r8$lambda$ARmmzvV3NFHBz3Avud8XZ4n_Grk(Unknown Source:0)
    at com.owncloud.android.authentication.AuthenticatorActivity$$ExternalSyntheticLambda8.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:1012)
Caused by: Exception in thread "Thread-5" com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
    at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659)
    at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1465)
    at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:551)
    at com.google.gson.stream.JsonReader.peek(JsonReader.java:433)
    at com.google.gson.JsonParser.parseReader(JsonParser.java:71)
    at com.google.gson.JsonParser.parseString(JsonParser.java:51)
    at com.owncloud.android.authentication.AuthenticatorActivity.lambda$anonymouslyPostLoginRequest$1(AuthenticatorActivity.java:385)
    at com.owncloud.android.authentication.AuthenticatorActivity.$r8$lambda$ARmmzvV3NFHBz3Avud8XZ4n_Grk(Unknown Source:0)
    at com.owncloud.android.authentication.AuthenticatorActivity$$ExternalSyntheticLambda8.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20240510`
* Build flavor: `versionDev`

### Device information
* Brand: `motorola`
* Device: `vicky`
* Model: `moto g72`
* Id: `T2SVS33.68-21-8-4`
* Product: `vicky_g_sysn`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `992c5-2a0584`

**Comment by joshtrichards** [comment]
Do you have reproduction steps for us?
