### ISSUE TITLE
Link sharing error

### ISSUE THREAD

**Issue by agross** [nextcloud/android#13014]
### Cause of error
```java
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: length=15; index=-1
    at java.util.ArrayList.set(ArrayList.java:455)
    at com.owncloud.android.ui.fragment.OCFileListFragment.updateOCFile(OCFileListFragment.java:1359)
    at com.owncloud.android.ui.activity.FileActivity.onCreateShareViaLinkOperationFinish(FileActivity.java:804)
    at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:392)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoteOperationFinish(FileDisplayActivity.java:1607)
    at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:786)
    at com.owncloud.android.services.OperationsService$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7937)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290090`
* Build flavor: `gplay`

### Device information
* Brand: `POCO`
* Device: `redwood`
* Model: `22101320G`
* Id: `TQ3A.230901.001`
* Product: `redwood_global`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `272`

**Comment by satvik2131** [comment]
Please define the bug in the proper format 
error : 
actual behaviour:
steps to reproduce : 
screenshots :

**Comment by agross** [comment]
The issue was formatted and submitted by your own app. Do you want to imply you don't consider your own bug reports as being proper?

The error was caused when I was trying to share a link to a file. That should be enough input for you to check why the array was accessed out of bounds.

**Comment by satvik2131** [comment]
ok got it no worries , will look into it .
