### ISSUE TITLE
App from F-Droid crashes after start on Android 6 

### ISSUE THREAD

**Issue by LeSpocky** [nextcloud/android#13021]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open app
2. Wait
3. App crashes

### Expected behaviour

Use the app without the app crashing.

### Actual behaviour

App crashes right after start, not possible to do anything in the app.

### Android version

6

### Device brand and model

ASUS ZenPad 8

### Stock or custom OS?

Stock

### Nextcloud android app version

3.25.0 (from F-Droid)

### Nextcloud server version

25

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" android.util.AndroidRuntimeException: requestFeature() must be called before adding content
    at com.android.internal.policy.PhoneWindow.requestFeature(PhoneWindow.java:317)
    at android.app.Dialog.requestWindowFeature(Dialog.java:1126)
    at com.owncloud.android.ui.dialog.SslUntrustedCertDialog.onCreateDialog(SslUntrustedCertDialog.java:168)
    at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:665)
    at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:579)
    at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1755)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:493)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1901)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1819)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1762)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5484)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30250090`
* Build flavor: `generic`

### Device information
* Brand: `asus`
* Device: `P024_1`
* Model: `P024`
* Id: `MMB29M`
* Product: `WW_P024`

### Firmware
* SDK: `23`
* Release: `6.0.1`
* Incremental: `WW_P024-V5.9.4-20170613`

**Comment by LeSpocky** [comment]
Server has a certificate issued by Lets Encrypt, which is not trusted by Android 6 (anymore).

**Comment by joshtrichards** [comment]
Sorry, but we don't support:

- Client 3.25.0
- Nextcloud Server 25 (has reached end-of-life)
- Android 6

https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html#mobile-apps
