### ISSUE TITLE
Crashed help


### ISSUE THREAD

**Issue by Jessej9holloway** [nextcloud/android#13094]
### Cause of error
```java
Exception in thread "Thread-7" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
    at com.google.gson.JsonParser.parseReader(JsonParser.java:76)
    at com.google.gson.JsonParser.parseString(JsonParser.java:51)
    at com.owncloud.android.authentication.AuthenticatorActivity.lambda$anonymouslyPostLoginRequest$2(AuthenticatorActivity.java:408)
    at com.owncloud.android.authentication.AuthenticatorActivity.$r8$lambda$T0aFAWEWnQwqUWyIJirUr6PVtl0(Unknown Source:0)
    at com.owncloud.android.authentication.AuthenticatorActivity$$ExternalSyntheticLambda7.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:1012)
Caused by: Exception in thread "Thread-7" com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
    at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659)
    at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1465)
    at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:551)
    at com.google.gson.stream.JsonReader.peek(JsonReader.java:433)
    at com.google.gson.JsonParser.parseReader(JsonParser.java:71)
    at com.google.gson.JsonParser.parseString(JsonParser.java:51)
    at com.owncloud.android.authentication.AuthenticatorActivity.lambda$anonymouslyPostLoginRequest$2(AuthenticatorActivity.java:408)
    at com.owncloud.android.authentication.AuthenticatorActivity.$r8$lambda$T0aFAWEWnQwqUWyIJirUr6PVtl0(Unknown Source:0)
    at com.owncloud.android.authentication.AuthenticatorActivity$$ExternalSyntheticLambda7.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20240524`
* Build flavor: `versionDev`

### Device information
* Brand: `samsung`
* Device: `dm3q`
* Model: `SM-S918U`
* Id: `UP1A.231005.007`
* Product: `dm3qsqw`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `S918USQS3CXD7`

**Comment by joshtrichards** [comment]
Can you provide further context? Reproduction steps?
