### ISSUE TITLE
??

### ISSUE THREAD

**Issue by khaledalmurar** [nextcloud/android#13112]
### Cause of error
```java
Exception in thread "Thread-9" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
    at com.google.gson.JsonParser.parseReader(JsonParser.java:76)
    at com.google.gson.JsonParser.parseString(JsonParser.java:51)
    at com.owncloud.android.authentication.AuthenticatorActivity.lambda$anonymouslyPostLoginRequest$2(AuthenticatorActivity.java:408)
    at com.owncloud.android.authentication.AuthenticatorActivity.$r8$lambda$T0aFAWEWnQwqUWyIJirUr6PVtl0(Unknown Source:0)
    at com.owncloud.android.authentication.AuthenticatorActivity$$ExternalSyntheticLambda7.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:1012)
Caused by: Exception in thread "Thread-9" com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
    at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659)
    at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1465)
    at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:551)
    at com.google.gson.stream.JsonReader.peek(JsonReader.java:433)
    at com.google.gson.JsonParser.parseReader(JsonParser.java:71)
    at com.google.gson.JsonParser.parseString(JsonParser.java:51)
    at com.owncloud.android.authentication.AuthenticatorActivity.lambda$anonymouslyPostLoginRequest$2(AuthenticatorActivity.java:408)
    at com.owncloud.android.authentication.AuthenticatorActivity.$r8$lambda$T0aFAWEWnQwqUWyIJirUr6PVtl0(Unknown Source:0)
    at com.owncloud.android.authentication.AuthenticatorActivity$$ExternalSyntheticLambda7.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20240606`
* Build flavor: `versionDev`

### Device information
* Brand: `Xiaomi`
* Device: `shennong`
* Model: `23116PN5BC`
* Id: `UKQ1.230804.001`
* Product: `shennong`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `V816.0.24.6.3.DEV`

**Comment by joshtrichards** [comment]
Reproduction steps would be appreciated.

Duplicate of #13019
