### ISSUE TITLE
Crash before Login

### ISSUE THREAD

**Issue by RealDiez** [nextcloud/android#13138]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Reboot Device
2. Start Nextcloud client app

### Expected behaviour

Nextcloud client app starts and probably asks for login credentials.

### Actual behaviour

App crashes

### Android version

* SDK: `25` * Release: `7.1.2` * Incremental: `cd3927b4dc`

### Device brand and model

* Brand: `motorola` * Device: `cedric` * Model: `Moto G5` * Id: `NJH47F` * Product: `lineage_cedric`

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

* ID: `com.nextcloud.client` * Version: `30290090` * Build flavor: `generic` from F-DROID

### Nextcloud server version

29.0.2

### Using a reverse proxy?

I don't know

### Android logs

As given by APP (NOTE: automatic issue creation does NOT work):

### Cause of error

```java
Exception in thread "main" java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/[com.nmc.android](http://com.nmc.android/).ui.LauncherActivity}: java.util.NoSuchElementException: No value present
    at [android.app](http://android.app/).ActivityThread.performLaunchActivity([ActivityThread.java:2684](http://activitythread.java:2684/))
    at [android.app](http://android.app/).ActivityThread.handleLaunchActivity([ActivityThread.java:2751](http://activitythread.java:2751/))
    at [android.app](http://android.app/).ActivityThread.-wrap12([ActivityThread.java](http://activitythread.java/))
    at [android.app](http://android.app/).ActivityThread$H.handleMessage([ActivityThread.java:1496](http://activitythread.java:1496/))
    at android.os.Handler.dispatchMessage([Handler.java:102](http://handler.java:102/))
    at android.os.Looper.loop([Looper.java:154](http://looper.java:154/))
    at [android.app](http://android.app/).ActivityThread.main([ActivityThread.java:6186](http://activitythread.java:6186/))
    at java.lang.reflect.Method.invoke(Native Method)
    at [com.android](http://com.android/).internal.os.ZygoteInit$[MethodAndArgsCaller.run](http://methodandargscaller.run/)([ZygoteInit.java:889](http://zygoteinit.java:889/))
    at [com.android](http://com.android/).internal.os.ZygoteInit.main([ZygoteInit.java:779](http://zygoteinit.java:779/))
Caused by: Exception in thread "main" java.util.NoSuchElementException: No value present
    at java.util.Optional.get([Optional.java:130](http://optional.java:130/))
    at com.nextcloud.client.mixins.SessionMixin.setAccount(SessionMixin.kt:58)
    at com.nextcloud.client.mixins.SessionMixin.onCreate(SessionMixin.kt:121)
    at com.nextcloud.client.mixins.MixinRegistry.onCreate(MixinRegistry.kt:43)
    at [com.owncloud.android](http://com.owncloud.android/).ui.activity.BaseActivity.onCreate([BaseActivity.java:72](http://baseactivity.java:72/))
    at [com.nmc.android](http://com.nmc.android/).ui.LauncherActivity.onCreate(LauncherActivity.kt:37)
    at [android.app](http://android.app/).Activity.performCreate([Activity.java:6684](http://activity.java:6684/))
    at [android.app](http://android.app/).Instrumentation.callActivityOnCreate([Instrumentation.java:1119](http://instrumentation.java:1119/))
    at [android.app](http://android.app/).ActivityThread.performLaunchActivity([ActivityThread.java:2637](http://activitythread.java:2637/))
    at [android.app](http://android.app/).ActivityThread.handleLaunchActivity([ActivityThread.java:2751](http://activitythread.java:2751/))
    at [android.app](http://android.app/).ActivityThread.-wrap12([ActivityThread.java](http://activitythread.java/))
    at [android.app](http://android.app/).ActivityThread$H.handleMessage([ActivityThread.java:1496](http://activitythread.java:1496/))
    at android.os.Handler.dispatchMessage([Handler.java:102](http://handler.java:102/))
    at android.os.Looper.loop([Looper.java:154](http://looper.java:154/))
    at [android.app](http://android.app/).ActivityThread.main([ActivityThread.java:6186](http://activitythread.java:6186/))
    at java.lang.reflect.Method.invoke(Native Method)
    at [com.android](http://com.android/).internal.os.ZygoteInit$[MethodAndArgsCaller.run](http://methodandargscaller.run/)([ZygoteInit.java:889](http://zygoteinit.java:889/))
    at [com.android](http://com.android/).internal.os.ZygoteInit.main([ZygoteInit.java:779](http://zygoteinit.java:779/))

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290090`
* Build flavor: `generic`

### Device information
* Brand: `motorola`
* Device: `cedric`
* Model: `Moto G5`
* Id: `NJH47F`
* Product: `lineage_cedric`

### Firmware
* SDK: `25`
* Release: `7.1.2`
* Incremental: `cd3927b4dc`

### Additional information

LineageOS 14.1

**Comment by RealDiez** [comment]
Any progress? Currently, the app is useless to me / not functional at all.
I'd be happy to provide more information to solve this problem.

**Comment by joshtrichards** [comment]
> Nextcloud client app starts and probably asks for login credentials.

Is this a brand-new installation of the app?

**Comment by RealDiez** [comment]
No.

Though, not sure whether related:
The app worked without problem for years, then the SD card died (adopted storage). After inserting a new, blank SD card, I had to re-install the nextcloud app and re-setup everything. Then the app was working as expected.
After a reboot of the device, the trouble started.
I tried older versions of the nextcloud app (3.28) and the newest available version (3.29.1), without success. 3.29.1 doesn't even display the crash log, it just silently vanishes after the splash screen.

**Comment by joshtrichards** [comment]
Fixed in #13074
