### ISSUE TITLE
UninitializedPropertyAccessException syncing folder

### ISSUE THREAD

**Issue by veikman** [nextcloud/android#13142]
Selected "Sync" twice for one remote folder, while on a stable Wi-fi connection. The first time, there was no visible reaction apart from the blue and white sync icon appearing briefly. The second time I saw a stack trace. The rest of this report is auto-generated.

### Cause of error
```java
Exception in thread "WM.task-6" kotlin.UninitializedPropertyAccessException: lateinit property notificationManager has not been initialized
    at com.nextcloud.client.jobs.download.FileDownloadWorker.onStopped(FileDownloadWorker.kt:154)
    at androidx.work.ListenableWorker.stop(ListenableWorker.java:294)
    at androidx.work.impl.WorkerWrapper.interrupt(WorkerWrapper.java:386)
    at androidx.work.impl.Processor.interrupt(Processor.java:440)
    at androidx.work.impl.Processor.stopWork(Processor.java:260)
    at androidx.work.impl.utils.StopWorkRunnable.run(StopWorkRunnable.kt:51)
    at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290090`
* Build flavor: `generic`

### Device information
* Brand: `Sony`
* Device: `XQ-AU52`
* Model: `XQ-AU52`
* Id: `59.2.A.0.463`
* Product: `XQ-AU52_EEA`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `059002A000046302402528438`

**Comment by joshtrichards** [comment]
Fixed in #13073
