### ISSUE TITLE
Crash after backing from "upload files from other app" popup

### ISSUE THREAD

**Issue by FlafyDev** [nextcloud/android#13154]
This was the auto generated issue. I assume I just submit it as is...

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
    at com.owncloud.android.ui.adapter.OCFileListAdapter.limitToPersonalFiles(OCFileListAdapter.java:1074)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:741)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1327)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1292)
    at com.owncloud.android.ui.fragment.OCFileListFragment.onBrowseUp(OCFileListFragment.java:914)
    at com.owncloud.android.ui.activity.FileDisplayActivity.browseUp(FileDisplayActivity.java:996)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onBackPressed(FileDisplayActivity.java:989)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onOptionsItemSelected(FileDisplayActivity.java:805)
    at android.app.Activity.onMenuItemSelected(Activity.java:4679)
    at androidx.activity.ComponentActivity.onMenuItemSelected(ComponentActivity.java:528)
    at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:264)
    at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:269)
    at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:110)
    at androidx.appcompat.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:188)
    at android.view.View.performClick(View.java:8043)
    at android.view.View.performClickInternal(View.java:8020)
    at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
    at android.view.View$PerformClick.run(View.java:31850)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8893)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290090`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `a54x`
* Model: `SM-A546E`
* Id: `UP1A.231005.007`
* Product: `a54xnsxx`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `A546EXXS7BXD5`

**Comment by joshtrichards** [comment]
Fixed in #12930
