### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by r0073rr0r** [nextcloud/android#13168]
### Cause of error
```java
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: length=15; index=-1
    at java.util.ArrayList.set(ArrayList.java:455)
    at com.owncloud.android.ui.fragment.OCFileListFragment.updateOCFile(OCFileListFragment.java:1372)
    at com.owncloud.android.ui.activity.FileActivity.onCreateShareViaLinkOperationFinish(FileActivity.java:807)
    at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:393)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoteOperationFinish(FileDisplayActivity.java:1629)
    at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:786)
    at com.owncloud.android.services.OperationsService$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:250)
    at android.app.ActivityThread.main(ActivityThread.java:7886)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290151`
* Build flavor: `gplay`

### Device information
* Brand: `motorola`
* Device: `liber`
* Model: `motorola one fusion+`
* Id: `RPIS31.Q2-42-25-3`
* Product: `liber_retail`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `7e5db7`

**Comment by joshtrichards** [comment]
Fixed in #13166
