### ISSUE TITLE
I just open the app

### ISSUE THREAD

**Issue by Domroon** [nextcloud/android#13188]
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'void com.owncloud.android.ui.activity.FileActivity.checkInternetConnection()' on a null object reference
    at com.owncloud.android.ui.fragment.OCFileListFragment.onItemClicked(OCFileListFragment.java:973)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onOpenFileIntent(FileDisplayActivity.java:576)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onNewIntent(FileDisplayActivity.java:515)
    at android.app.Activity.performNewIntent(Activity.java:8993)
    at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1556)
    at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1569)
    at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:4362)
    at android.app.ActivityThread.handleNewIntent(ActivityThread.java:4369)
    at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:56)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8919)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290090`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `p3s`
* Model: `SM-G998B`
* Id: `UP1A.231005.007`
* Product: `p3sxeea`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `G998BXXSBGXED`

**Comment by Domroon** [comment]
I have a link to an html file on my homescreen. I tap on it and the app crashes directly.
