### ISSUE TITLE
Report 

### ISSUE THREAD

**Issue by Chshyhin** [nextcloud/android#13185]
### Cause of error
```java
Exception in thread "main" java.lang.SecurityException: Starting FGS with type dataSync callerApp=ProcessRecord{96f6cb3 19503:com.squeekr.cloud/u0a1862} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_DATA_SYNC] 
    at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
    at android.os.Parcel.createException(Parcel.java:3053)
    at android.os.Parcel.readException(Parcel.java:3036)
    at android.os.Parcel.readException(Parcel.java:2978)
    at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7234)
    at android.app.Service.startForeground(Service.java:862)
    at androidx.work.impl.foreground.SystemForegroundService$Api31Impl.startForeground(SystemForegroundService.java:193)
    at androidx.work.impl.foreground.SystemForegroundService$1.run(SystemForegroundService.java:129)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8919)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: Exception in thread "main" android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActiveServices.validateForegroundServiceType(ActiveServices.java:2741)
	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:2452)
	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:1797)
	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:15948)
	at android.app.IActivityManager$Stub.onTransact$setServiceForeground$(IActivityManager.java:11974)


```

### App information
* ID: `com.squeekr.cloud`
* Version: `20000000`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `b0q`
* Model: `SM-S908E`
* Id: `UP1A.231005.007`
* Product: `b0qxxx`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `S908EXXS9EXE4`

**Comment by joshtrichards** [comment]
```
App information

    ID: com.squeekr.cloud
    Version: 20000000
    Build flavor: gplay
```

Not sure how you ended up here, but this isn't us/this app. :-)
