### ISSUE TITLE
Fehler beim öffnen und bearbeiten einer TXT

### ISSUE THREAD

**Issue by firewal2000** [nextcloud/android#13233]
### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Fragment FileActionsBottomSheet{f4c633f} (9c820887-51ee-4f6d-83c0-5bdccaa47f08) not associated with a fragment manager.
    at androidx.fragment.app.Fragment.getParentFragmentManager(Fragment.java:1112)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.dispatchActionClick(FileActionsBottomSheet.kt:299)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.access$dispatchActionClick(FileActionsBottomSheet.kt:50)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$onCreateView$2.invoke(FileActionsBottomSheet.kt:88)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$onCreateView$2.invoke(FileActionsBottomSheet.kt:87)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$sam$androidx_lifecycle_Observer$0.onChanged(Unknown Source:2)
    at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
    at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
    at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
    at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
    at com.nextcloud.ui.fileactions.FileActionsViewModel.onClick(FileActionsViewModel.kt:147)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.inflateActionView$lambda$9$lambda$8(FileActionsBottomSheet.kt:281)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet.$r8$lambda$uchH_ll8ENOPxscjh3brNAOCY4U(Unknown Source:0)
    at com.nextcloud.ui.fileactions.FileActionsBottomSheet$$ExternalSyntheticLambda1.onClick(D8$$SyntheticClass:0)
    at android.view.View.performClick(View.java:8047)
    at android.view.View.performClickInternal(View.java:8024)
    at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
    at android.view.View$PerformClick.run(View.java:31890)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8919)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290190`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `dm3q`
* Model: `SM-S918B`
* Id: `UP1A.231005.007`
* Product: `dm3qxeea`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `S918BXXS5CXE9`

**Comment by joshtrichards** [comment]
Duplicate of #11701
