### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Eng-Omar-Alkatheri** [nextcloud/android#13244]
### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Unable to resume activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5877)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5923)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:194)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:106)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:3067)
    at android.os.Handler.dispatchMessage(Handler.java:117)
    at android.os.Looper.loopOnce(Looper.java:210)
    at android.os.Looper.loop(Looper.java:302)
    at android.app.ActivityThread.main(ActivityThread.java:9652)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:601)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1062)
Caused by: Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
    at com.owncloud.android.ui.adapter.OCFileListAdapter.limitToPersonalFiles(OCFileListAdapter.java:1074)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:741)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1343)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1292)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1281)
    at com.owncloud.android.ui.activity.FileDisplayActivity.updateListOfFilesFragment(FileDisplayActivity.java:672)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onResume(FileDisplayActivity.java:1116)
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1622)
    at android.app.Activity.performResume(Activity.java:9191)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5866)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5923)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:194)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:106)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:3067)
    at android.os.Handler.dispatchMessage(Handler.java:117)
    at android.os.Looper.loopOnce(Looper.java:210)
    at android.os.Looper.loop(Looper.java:302)
    at android.app.ActivityThread.main(ActivityThread.java:9652)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:601)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1062)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290190`
* Build flavor: `gplay`

### Device information
* Brand: `HONOR`
* Device: `HNBVL`
* Model: `BVL-N49`
* Id: `HONORBVL-N49`
* Product: `BVL-N49`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `8.0.0.170C185E2R2P2`

**Comment by joshtrichards** [comment]
Fixed in #12930
