### ISSUE TITLE
Mobile Sync to serveur (home serveur Ubuntu 24.04)

### ISSUE THREAD

**Issue by ascentvibes** [nextcloud/android#13263]
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
    at com.owncloud.android.ui.adapter.OCFileListAdapter.limitToPersonalFiles(OCFileListAdapter.java:1074)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:741)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1343)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1292)
    at com.owncloud.android.ui.fragment.OCFileListFragment.onBrowseUp(OCFileListFragment.java:914)
    at com.owncloud.android.ui.activity.FileDisplayActivity.browseUp(FileDisplayActivity.java:1017)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onBackPressed(FileDisplayActivity.java:1010)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onOptionsItemSelected(FileDisplayActivity.java:826)
    at android.app.Activity.onMenuItemSelected(Activity.java:4658)
    at androidx.activity.ComponentActivity.onMenuItemSelected(ComponentActivity.java:528)
    at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:264)
    at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:269)
    at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:110)
    at androidx.appcompat.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:188)
    at android.view.View.performClick(View.java:7931)
    at android.view.View.performClickInternal(View.java:7908)
    at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
    at android.view.View$PerformClick.run(View.java:30989)
    at android.os.Handler.handleCallback(Handler.java:959)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8592)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290190`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `bluejay`
* Model: `Pixel 6a`
* Id: `AP2A.240605.024`
* Product: `bluejay`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `11860263`

**Comment by joshtrichards** [comment]
Fixed in #12930
