### ISSUE TITLE
When deleted photo from android app

### ISSUE THREAD

**Issue by morokoli** [nextcloud/android#13270]
### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Fragment PreviewMediaFragment{33d857c} (dc79107c-fb38-4200-a553-15162c03b807) not attached to a context.
    at androidx.fragment.app.Fragment.requireContext(Fragment.java:972)
    at com.owncloud.android.ui.preview.PreviewMediaFragment.lambda$onStart$1(PreviewMediaFragment.java:351)
    at com.owncloud.android.ui.preview.PreviewMediaFragment.$r8$lambda$uDaoT5tCd_EnFoVGkfSYFCOoOr4(Unknown Source:0)
    at com.owncloud.android.ui.preview.PreviewMediaFragment$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8919)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `q4q`
* Model: `SM-F936B`
* Id: `UP1A.231005.007`
* Product: `q4qxxx`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `F936BXXS7FXEB`

**Comment by alperozturk96** [comment]
Duplication [of](https://github.com/nextcloud/android/issues/13256)
