### ISSUE TITLE
Uploading file from phone 

### ISSUE THREAD

**Issue by CrnaStrela94** [nextcloud/android#13272]
### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2255124 bytes
    at android.app.ActivityClient.finishActivity(ActivityClient.java:182)
    at android.app.Activity.finish(Activity.java:7221)
    at android.app.Activity.finish(Activity.java:7238)
    at com.owncloud.android.ui.activity.UploadFilesActivity.onCheckAvailableSpaceFinish(UploadFilesActivity.java:524)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:58)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:20)
    at android.os.AsyncTask.finish(AsyncTask.java:771)
    at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8919)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: Exception in thread "main" android.os.TransactionTooLargeException: data parcel size 2255124 bytes
    at android.os.BinderProxy.transactNative(Native Method)
    at android.os.BinderProxy.transact(BinderProxy.java:662)
    at android.app.IActivityClientController$Stub$Proxy.finishActivity(IActivityClientController.java:1651)
    at android.app.ActivityClient.finishActivity(ActivityClient.java:179)
    at android.app.Activity.finish(Activity.java:7221)
    at android.app.Activity.finish(Activity.java:7238)
    at com.owncloud.android.ui.activity.UploadFilesActivity.onCheckAvailableSpaceFinish(UploadFilesActivity.java:524)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:58)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:20)
    at android.os.AsyncTask.finish(AsyncTask.java:771)
    at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8919)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `b0s`
* Model: `SM-S908B`
* Id: `UP1A.231005.007`
* Product: `b0sxeea`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `S908BXXSAEXEC`

**Comment by alperozturk96** [comment]
Fixed [via](https://github.com/nextcloud/android/pull/13336)
