### ISSUE TITLE
Tried to load too much im guessing

### ISSUE THREAD

**Issue by Fau57** [nextcloud/android#13284]
### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1431092 bytes
    at android.app.ActivityClient.finishActivity(ActivityClient.java:167)
    at android.app.Activity.finish(Activity.java:6845)
    at android.app.Activity.finish(Activity.java:6862)
    at com.owncloud.android.ui.activity.UploadFilesActivity.onCheckAvailableSpaceFinish(UploadFilesActivity.java:525)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:58)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:20)
    at android.os.AsyncTask.finish(AsyncTask.java:771)
    at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8762)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: Exception in thread "main" android.os.TransactionTooLargeException: data parcel size 1431092 bytes
    at android.os.BinderProxy.transactNative(Native Method)
    at android.os.BinderProxy.transact(BinderProxy.java:662)
    at android.app.IActivityClientController$Stub$Proxy.finishActivity(IActivityClientController.java:1452)
    at android.app.ActivityClient.finishActivity(ActivityClient.java:164)
    at android.app.Activity.finish(Activity.java:6845)
    at android.app.Activity.finish(Activity.java:6862)
    at com.owncloud.android.ui.activity.UploadFilesActivity.onCheckAvailableSpaceFinish(UploadFilesActivity.java:525)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:58)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:20)
    at android.os.AsyncTask.finish(AsyncTask.java:771)
    at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8762)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20240709`
* Build flavor: `versionDev`

### Device information
* Brand: `samsung`
* Device: `r8q`
* Model: `SM-G781W`
* Id: `TP1A.220624.014`
* Product: `r8qcsx`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `G781WVLSEHXE3`

**Comment by alperozturk96** [comment]
Fixed [via](https://github.com/nextcloud/android/pull/13336)

**Comment by Fau57** [comment]
ty
