### ISSUE TITLE
NPE getMimeType() in PreviewMediaActivity  | Unable to stop activity

### ISSUE THREAD

**Issue by alphasixtyfive** [nextcloud/android#13289]
### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Unable to stop activity {com.nextcloud.android.beta/com.owncloud.android.ui.preview.PreviewMediaActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getMimeType()' on a null object reference
    at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5658)
    at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5630)
    at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5695)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:342)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:307)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:279)
    at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8592)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getMimeType()' on a null object reference
    at com.owncloud.android.utils.MimeTypeUtil.isAudio(MimeTypeUtil.java:256)
    at com.owncloud.android.ui.preview.PreviewMediaActivity.onStop(PreviewMediaActivity.kt:753)
    at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1742)
    at android.app.Activity.performStop(Activity.java:9213)
    at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5650)
    at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5630)
    at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5695)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:342)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:307)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:279)
    at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8592)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20240713`
* Build flavor: `versionDev`

### Device information
* Brand: `google`
* Device: `husky`
* Model: `Pixel 8 Pro`
* Id: `AP2A.240705.005`
* Product: `husky`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `11942872`

**Comment by alperozturk96** [comment]
Hello, Thanks for report. Could you share reproducing steps?
