### ISSUE TITLE
crashes when choosing account

### ISSUE THREAD

**Issue by nicojx** [nextcloud/android#13299]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Install nextcloud sync beta app
2. Log into sync app
3. Install nextcloud notes
4. Start notes, select listed account

### Expected behaviour

Log in and sync notes

### Actual behaviour

Crash:

### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.android.beta/com.owncloud.android.ui.activity.SsoGrantPermissionActivity}: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3841)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3978)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:8202)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:573)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)
Caused by: Exception in thread "main" java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).
    at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:247)
    at com.google.android.material.internal.ThemeEnforcement.checkAppCompatTheme(ThemeEnforcement.java:212)
    at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:147)
    at com.google.android.material.internal.ThemeEnforcement.obtainStyledAttributes(ThemeEnforcement.java:76)
    at com.google.android.material.dialog.MaterialDialogs.getDialogBackgroundInsets(MaterialDialogs.java:60)
    at com.google.android.material.dialog.MaterialAlertDialogBuilder.<init>(MaterialAlertDialogBuilder.java:123)
    at com.google.android.material.dialog.MaterialAlertDialogBuilder.<init>(MaterialAlertDialogBuilder.java:109)
    at com.owncloud.android.ui.activity.SsoGrantPermissionActivity.onCreate(SsoGrantPermissionActivity.java:104)
    at android.app.Activity.performCreate(Activity.java:8340)
    at android.app.Activity.performCreate(Activity.java:8319)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3822)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3978)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:8202)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:573)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20240713`
* Build flavor: `versionDev`

### Device information
* Brand: `Lenovo`
* Device: `TB132FU`
* Model: `TB132FU`
* Id: `TP1A.220624.014`
* Product: `TB132FU_EEA`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `TB132FU_S240242_240427_ROW`

### Android version

13

### Device brand and model

Lenovo tablet

### Stock or custom OS?

Stock

### Nextcloud android app version

20240713

### Nextcloud server version

?

### Using a reverse proxy?

No

**Comment by alperozturk96** [comment]
Duplication [of](https://github.com/nextcloud/android/issues/13305) 

@nicojx Could you try with the latest master?
