### ISSUE TITLE
Crash when try to upload all files in directory

### ISSUE THREAD

**Issue by yagarea** [nextcloud/android#13292]
### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 3094864 bytes
    at android.app.ActivityClient.finishActivity(ActivityClient.java:183)
    at android.app.Activity.finish(Activity.java:7328)
    at android.app.Activity.finish(Activity.java:7345)
    at com.owncloud.android.ui.activity.UploadFilesActivity.onConfirmation(UploadFilesActivity.java:663)
    at com.owncloud.android.ui.dialog.ConfirmationDialogFragment.onCreateDialog$lambda$0(ConfirmationDialogFragment.kt:84)
    at com.owncloud.android.ui.dialog.ConfirmationDialogFragment.$r8$lambda$muH3dEu1HilHA9TTFMeZwUDJ3mM(Unknown Source:0)
    at com.owncloud.android.ui.dialog.ConfirmationDialogFragment$$ExternalSyntheticLambda0.onClick(D8$$SyntheticClass:0)
    at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8623)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
    at com.android.internal.os.ExecInit.main(ExecInit.java:50)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: Exception in thread "main" android.os.TransactionTooLargeException: data parcel size 3094864 bytes
    at android.os.BinderProxy.transactNative(Native Method)
    at android.os.BinderProxy.transact(BinderProxy.java:586)
    at android.app.IActivityClientController$Stub$Proxy.finishActivity(IActivityClientController.java:1671)
    at android.app.ActivityClient.finishActivity(ActivityClient.java:180)
    at android.app.Activity.finish(Activity.java:7328)
    at android.app.Activity.finish(Activity.java:7345)
    at com.owncloud.android.ui.activity.UploadFilesActivity.onConfirmation(UploadFilesActivity.java:663)
    at com.owncloud.android.ui.dialog.ConfirmationDialogFragment.onCreateDialog$lambda$0(ConfirmationDialogFragment.kt:84)
    at com.owncloud.android.ui.dialog.ConfirmationDialogFragment.$r8$lambda$muH3dEu1HilHA9TTFMeZwUDJ3mM(Unknown Source:0)
    at com.owncloud.android.ui.dialog.ConfirmationDialogFragment$$ExternalSyntheticLambda0.onClick(D8$$SyntheticClass:0)
    at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8623)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
    at com.android.internal.os.ExecInit.main(ExecInit.java:50)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20240713`
* Build flavor: `versionDev`

### Device information
* Brand: `google`
* Device: `oriole`
* Model: `Pixel 6`
* Id: `AP2A.240705.004`
* Product: `oriole`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `2024071600`

**Comment by alperozturk96** [comment]
@yagarea Thanks for the report. How many files you picked to upload?

**Comment by yagarea** [comment]
> How many files you picked to upload?
Around 5000 photos.
