### ISSUE TITLE
Auto upload page crashed a program.

### ISSUE THREAD

**Issue by piotrbujakowski** [nextcloud/android#13324]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

I checking catalog for backup.
Is a lot of them.

### Expected behaviour

No crash.

### Actual behaviour

Still crachingy.

### Android version

11

### Device brand and model

blackview Tab 11 

### Stock or custom OS?

Stock

### Nextcloud android app version

3.29.2

### Nextcloud server version

I don't know.

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "FinalizerWatchdogDaemon" java.util.concurrent.TimeoutException: android.media.MediaMetadataRetriever.finalize() timed out after 10 seconds
    at android.media.MediaMetadataRetriever.native_finalize(Native Method)
    at android.media.MediaMetadataRetriever.finalize(MediaMetadataRetriever.java:1069)
    at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
    at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
    at java.lang.Daemons$Daemon.run(Daemons.java:139)
    at java.lang.Thread.run(Thread.java:923)

```

### App information
* ID: `tech.shadow.drive.android.client`
* Version: `30290090 (build #22647)`
* Build flavor: `gplay`

### Device information
* Brand: `Blackview`
* Device: `Tab11_EA`
* Model: `Tab 11`
* Id: `RP1A.201005.001`
* Product: `Tab11_EA`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `2022420`

### Server error logs

```bash
I don't have.
```

### Additional information

Not first time.

**Comment by joshtrichards** [comment]
Can you elaborate on how to reproduce this behavior?

Looks similar to #10468 & #10274, but neither had reproduction steps.

> `tech.shadow.drive.android.client`

Looks like a third party build. You should report this to the party that built and distributed this.

**Comment by piotrbujakowski** [comment]
Hi.

I have a SD card with a lot of photos and videos.
When I scroll down, the application can stop working.

**Comment by joshtrichards** [comment]
Possibly related: #10772
