### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by frogman544** [nextcloud/android#13327]
### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: FragmentManager has been destroyed
    at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1825)
    at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:341)
    at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:306)
    at androidx.fragment.app.DialogFragment.show(DialogFragment.java:519)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onSyncFolderSettingsClick(SyncedFoldersActivity.kt:587)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity$load$1$1.invokeSuspend(SyncedFoldersActivity.kt:317)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:334)
    at android.app.ActivityThread.main(ActivityThread.java:8291)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:557)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20240604`
* Build flavor: `versionDev`

### Device information
* Brand: `Nothing`
* Device: `Spacewar`
* Model: `A063`
* Id: `UP1A.231005.007`
* Product: `SpacewarEEA`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `2407051617`

**Comment by alperozturk96** [comment]
Fixed [via](https://github.com/nextcloud/android/commit/f2b059329a58058c154c724ebc834b4954c0ab2f)
