### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Angelohiukky** [nextcloud/android#13320]
### Cause of error
```java
Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property currentAccount has not been initialized
    at com.nextcloud.client.mixins.SessionMixin.getCurrentAccount(SessionMixin.kt:32)
    at com.nextcloud.client.mixins.SessionMixin.onRestart(SessionMixin.kt:100)
    at com.nextcloud.client.mixins.MixinRegistry.onRestart(MixinRegistry.kt:48)
    at com.owncloud.android.ui.activity.BaseActivity.onRestart(BaseActivity.java:118)
    at android.app.Instrumentation.callActivityOnRestart(Instrumentation.java:1606)
    at android.app.Activity.performRestart(Activity.java:9009)
    at android.app.ActivityThread.performRestartActivity(ActivityThread.java:5755)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:260)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:197)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:145)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2616)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:222)
    at android.os.Looper.loop(Looper.java:314)
    at android.app.ActivityThread.main(ActivityThread.java:8706)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `POCO`
* Device: `stone`
* Model: `22071219CG`
* Id: `UP1A.231005.007`
* Product: `stone_p_global`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `V816.0.9.0.ULUMIXM`

**Comment by alperozturk96** [comment]
@Angelohiukky Could you check via [this](https://github.com/nextcloud/android/releases/tag/stable-3.29.1) version?

**Comment by Angelohiukky** [comment]
Yes, after the update there were no more problems. In the end, I believe it was a one-off. Thanks!
