### ISSUE TITLE
`java.lang.IllegalArgumentException: Trying to execute a sync operation with a storage manager for an anonymous account`

### ISSUE THREAD

**Issue by devhttps** [nextcloud/android#13323]
### Cause of error
```java
Exception in thread "Thread-17" java.lang.IllegalArgumentException: Trying to execute a sync operation with a storage manager for an anonymous account
    at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:49)
    at com.owncloud.android.ui.activity.DrawerActivity.lambda$fetchExternalLinks$9(DrawerActivity.java:1231)
    at com.owncloud.android.ui.activity.DrawerActivity.$r8$lambda$oHM2j1MZkviAIdyIFWoI2kSeF9c(Unknown Source:0)
    at com.owncloud.android.ui.activity.DrawerActivity$$ExternalSyntheticLambda6.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `r0q`
* Model: `SM-S901E`
* Id: `UP1A.231005.007`
* Product: `r0qxxx`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `S901EXXS9EXE9`

**Comment by alperozturk96** [comment]
@devhttps Could you try with [v3.29.1](https://github.com/nextcloud/android/releases/tag/stable-3.29.1)?

**Comment by devhttps** [comment]
I updated it and it worked.

**Comment by devhttps** [comment]
> @devhttps Could you try with [v3.29.1](https://github.com/nextcloud/android/releases/tag/stable-3.29.1)?



I updated it and it worked.

**Comment by joshtrichards** [comment]
> `Version: 30290290`
>
> > @devhttps Could you try with [v3.29.1](https://github.com/nextcloud/android/releases/tag/stable-3.29.1)?
> 
> I updated it and it worked.

@alperozturk96 OP was on 3.29.2 already. Were you trying to get them to downgrade and reproduce? 

We're getting a lot of 3.29.2 reports on this and I'm unclear whether this is truly fixed in an upcoming release or not.

**Comment by alperozturk96** [comment]
@joshtrichards Please mention this PR for other reports, I will also check the other reports. I will create PR for fix asap. Thanks for the mention.

**Comment by alperozturk96** [comment]
@devhttps Could you please check with this [PR](https://github.com/nextcloud/android/pull/13440)?
