### ISSUE TITLE
Application crash when adding new auto upload

### ISSUE THREAD

**Issue by scr4bble** [nextcloud/android#13342]
### Cause of error
```java
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 62 out of bounds for length 0
    at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
    at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
    at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
    at java.util.Objects.checkIndex(Objects.java:359)
    at java.util.ArrayList.get(ArrayList.java:434)
    at com.owncloud.android.ui.adapter.SyncedFolderAdapter.get(SyncedFolderAdapter.java:199)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onSaveSyncedFolderPreference(SyncedFoldersActivity.kt:682)
    at com.owncloud.android.ui.dialog.SyncedFolderPreferencesDialogFragment$OnSyncedFolderSaveClickListener.onClick(SyncedFolderPreferencesDialogFragment.kt:485)
    at android.view.View.performClick(View.java:7745)
    at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1218)
    at android.view.View.performClickInternal(View.java:7722)
    at android.view.View.access$3700(View.java:854)
    at android.view.View$PerformClick.run(View.java:29111)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:210)
    at android.os.Looper.loop(Looper.java:299)
    at android.app.ActivityThread.main(ActivityThread.java:8319)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `Redmi`
* Device: `joyeuse`
* Model: `Redmi Note 9 Pro`
* Id: `SKQ1.211019.001`
* Product: `joyeuse_eea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `V14.0.5.0.SJZEUXM`

**Comment by alperozturk96** [comment]
Fixed [via](https://github.com/nextcloud/android/pull/13167)
