### ISSUE TITLE
GPlay:   java.lang.SecurityException - com.owncloud.android.lib.common.accounts.AccountUtils.restoreCookies [RC2] 

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#1335]
java.lang.SecurityException
com.owncloud.android.lib.common.accounts.AccountUtils.restoreCookies

* Reports this week: 63
* Android 7+

```
java.lang.SecurityException: 
  at android.os.Parcel.readException (Parcel.java:1684)
  at android.os.Parcel.readException (Parcel.java:1637)
  at android.accounts.IAccountManager$Stub$Proxy.getUserData (IAccountManager.java:887)
  at android.accounts.AccountManager.getUserData (AccountManager.java:402)
  at com.owncloud.android.lib.common.accounts.AccountUtils.restoreCookies (AccountUtils.java:300)
  at com.owncloud.android.lib.common.accounts.AccountUtils.restoreCookies (AccountUtils.java:342)
  at com.owncloud.android.lib.common.SingleSessionManager.getClientFor (SingleSessionManager.java:123)
  at com.owncloud.android.lib.common.DynamicSessionManager.getClientFor (DynamicSessionManager.java:40)
  at com.owncloud.android.lib.common.operations.RemoteOperation.run (RemoteOperation.java:282)
  at java.lang.Thread.run (Thread.java:761)
```

**Comment by tobiasKaminsky** [comment]
Found additional info in play console:
```
java.lang.SecurityException: uid 10267 cannot get user data for accounts of type: org.dmfs.carddav.account

java.lang.SecurityException: uid 10239 cannot get user data for accounts of type: bitfire.at.davdroid

java.lang.SecurityException: uid 10264 cannot get user data for accounts of type: org.dmfs.carddav.account

java.lang.SecurityException: uid 10363 cannot get user data for accounts of type: fr.unix_experience.owncloud_sms
	at android.os.Parcel.readException(Parcel.java:1693)
	at android.os.Parcel.readException(Parcel.java:1646)
	at android.accounts.IAccountManager$Stub$Proxy.getUserData(IAccountManager.java:824)
	at android.accounts.AccountManager.getUserData(AccountManager.java:382)
	at com.owncloud.android.lib.common.accounts.AccountUtils.restoreCookies(AccountUtils.java:300)
```

**Comment by tobiasKaminsky** [comment]
To test this I installed on an emulator our app and davdroid.
AccountManager.get(context.getApplicationContext()).getAccounts() only lists our accounts, therefore
am.getUserData(account, "oc_account_cookies")
can only use our accounts and thus no problems.

To harden this a bit more, we could try to use getAccountsByTyp(String type) instead of getAccounts(), but then we would have a hard link between client and library.

For now I will just surround it with a try catch to get rid of the error...

**Comment by AndyScherzinger** [comment]
Fix merged
