### ISSUE TITLE
Error on anonymous account 

### ISSUE THREAD

**Issue by aN00BisCZ** [nextcloud/android#13351]
### Cause of error
```java
Exception in thread "Thread-4" java.lang.IllegalArgumentException: Trying to execute a sync operation with a storage manager for an anonymous account
    at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:49)
    at com.owncloud.android.ui.activity.DrawerActivity.lambda$fetchExternalLinks$9(DrawerActivity.java:1231)
    at com.owncloud.android.ui.activity.DrawerActivity.$r8$lambda$oHM2j1MZkviAIdyIFWoI2kSeF9c(Unknown Source:0)
    at com.owncloud.android.ui.activity.DrawerActivity$$ExternalSyntheticLambda6.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:923)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `realme`
* Device: `RMX2144L1`
* Model: `RMX2144`
* Id: `RKQ1.201217.002`
* Product: `RMX2144EEA`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `1660659904283`

**Comment by joshtrichards** [comment]
Duplicate of #13293
