### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Dvaedfug** [nextcloud/android#13404]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Cause of error
```java
Exception in thread "main" android.content.res.Resources$NotFoundException: Resource ID #0x7f0a0401 type #0x12 is not valid
    at android.content.res.Resources.loadXmlResourceParser(Resources.java:2299)
    at android.content.res.Resources.getLayout(Resources.java:1187)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
    at androidx.appcompat.app.AlertController.setupCustomContent(AlertController.java:644)
    at androidx.appcompat.app.AlertController.setupView(AlertController.java:475)
    at androidx.appcompat.app.AlertController.installContent(AlertController.java:233)
    at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:278)
    at android.app.Dialog.dispatchOnCreate(Dialog.java:421)
    at android.app.Dialog.show(Dialog.java:315)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.showPowerCheckDialog(SyncedFoldersActivity.kt:233)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onDisablePowerSaveCheckClicked(SyncedFoldersActivity.kt:217)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onCreateOptionsMenu$lambda$1(SyncedFoldersActivity.kt:210)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.$r8$lambda$q58-_n5tvnvo7t7SwBQVBpaIAdU(Unknown Source:0)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity$$ExternalSyntheticLambda4.onMenuItemClick(D8$$SyntheticClass:0)
    at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
    at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:984)
    at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
    at android.widget.AdapterView.performItemClick(AdapterView.java:330)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1261)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3388)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7398)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20240807`
* Build flavor: `versionDev`

### Device information
* Brand: `Xiaomi`
* Device: `polaris`
* Model: `Mi MIX 2S`
* Id: `QQ3A.200805.001`
* Product: `polaris`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `eng.yyy233.20200815.073329`

### Cause of error
```java
Exception in thread "main" android.content.res.Resources$NotFoundException: Resource ID #0x7f0a0401 type #0x12 is not valid
    at android.content.res.Resources.loadXmlResourceParser(Resources.java:2299)
    at android.content.res.Resources.getLayout(Resources.java:1187)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
    at androidx.appcompat.app.AlertController.setupCustomContent(AlertController.java:644)
    at androidx.appcompat.app.AlertController.setupView(AlertController.java:475)
    at androidx.appcompat.app.AlertController.installContent(AlertController.java:233)
    at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:278)
    at android.app.Dialog.dispatchOnCreate(Dialog.java:421)
    at android.app.Dialog.show(Dialog.java:315)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.showPowerCheckDialog(SyncedFoldersActivity.kt:233)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onDisablePowerSaveCheckClicked(SyncedFoldersActivity.kt:217)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onCreateOptionsMenu$lambda$1(SyncedFoldersActivity.kt:210)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.$r8$lambda$q58-_n5tvnvo7t7SwBQVBpaIAdU(Unknown Source:0)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity$$ExternalSyntheticLambda4.onMenuItemClick(D8$$SyntheticClass:0)
    at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
    at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:984)
    at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
    at android.widget.AdapterView.performItemClick(AdapterView.java:330)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1261)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3388)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7398)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20240807`
* Build flavor: `versionDev`

### Device information
* Brand: `Xiaomi`
* Device: `polaris`
* Model: `Mi MIX 2S`
* Id: `QQ3A.200805.001`
* Product: `polaris`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `eng.yyy233.20200815.073329`

### Cause of error
```java
Exception in thread "main" android.content.res.Resources$NotFoundException: Resource ID #0x7f0a0401 type #0x12 is not valid
    at android.content.res.Resources.loadXmlResourceParser(Resources.java:2299)
    at android.content.res.Resources.getLayout(Resources.java:1187)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
    at androidx.appcompat.app.AlertController.setupCustomContent(AlertController.java:644)
    at androidx.appcompat.app.AlertController.setupView(AlertController.java:475)
    at androidx.appcompat.app.AlertController.installContent(AlertController.java:233)
    at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:278)
    at android.app.Dialog.dispatchOnCreate(Dialog.java:421)
    at android.app.Dialog.show(Dialog.java:315)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.showPowerCheckDialog(SyncedFoldersActivity.kt:233)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onDisablePowerSaveCheckClicked(SyncedFoldersActivity.kt:217)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onCreateOptionsMenu$lambda$1(SyncedFoldersActivity.kt:210)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.$r8$lambda$q58-_n5tvnvo7t7SwBQVBpaIAdU(Unknown Source:0)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity$$ExternalSyntheticLambda4.onMenuItemClick(D8$$SyntheticClass:0)
    at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
    at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:984)
    at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
    at android.widget.AdapterView.performItemClick(AdapterView.java:330)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1261)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3388)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7398)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20240807`
* Build flavor: `versionDev`

### Device information
* Brand: `Xiaomi`
* Device: `polaris`
* Model: `Mi MIX 2S`
* Id: `QQ3A.200805.001`
* Product: `polaris`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `eng.yyy233.20200815.073329`

### Android version

10

### Device brand and model

mimix2s

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

20240807

### Nextcloud server version

1111

### Using a reverse proxy?

I don't know

**Comment by K4r0qtuYNE5G4qgZ** [comment]
I have the same issue with additionally Nextcloud App going into a Fingerprint not recognized loop until I force stop it and reload.

**Comment by guilegatan** [comment]
+1
Same problem here.

Nextcloud App version 3.30.6
Android 11 on Samsung A40 (SM-A405FN/DS)

**Comment by joshtrichards** [comment]
Fix is in 3.30.7 published today
