### ISSUE TITLE
Nextcloud android crash on samsung galaxy tab s6

### ISSUE THREAD

**Issue by yar0d** [nextcloud/android#13428]
### Cause of error
```java
Exception in thread "Thread-20" java.lang.IllegalArgumentException: No suitable parent found from the given view. Please provide a valid view.
    at com.google.android.material.snackbar.Snackbar.makeInternal(Snackbar.java:205)
    at com.google.android.material.snackbar.Snackbar.make(Snackbar.java:164)
    at com.owncloud.android.utils.DisplayUtils.showSnackMessage(DisplayUtils.java:678)
    at com.owncloud.android.ui.preview.PreviewTextStringFragment.lambda$edit$1(PreviewTextStringFragment.java:148)
    at com.owncloud.android.ui.preview.PreviewTextStringFragment.$r8$lambda$_MpHYWLzP65yyRQaF66kF_Bz0rY(Unknown Source:0)
    at com.owncloud.android.ui.preview.PreviewTextStringFragment$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:920)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `gts6lwifi`
* Model: `SM-T860`
* Id: `SP2A.220305.013`
* Product: `gts6lwifieea`

### Firmware
* SDK: `32`
* Release: `12`
* Incremental: `T860XXS5DWH1`

**Comment by joshtrichards** [comment]
Hi @yar0d - Thanks for the report. Any idea how to trigger / reproduce this on-demand?
