### ISSUE TITLE
Activity: gson parser exception

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1343]
```
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $[7].subject_rich[1]
at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:162)
at com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:87)
at com.owncloud.android.lib.resources.activities.models.RichElementTypeAdapter.read(RichElementTypeAdapter.java:54)
at com.owncloud.android.lib.resources.activities.models.RichElementTypeAdapter.read(RichElementTypeAdapter.java:38)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) 
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) 
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) 
at com.google.gson.Gson.fromJson(Gson.java:887) 
at com.google.gson.Gson.fromJson(Gson.java:952) 
at com.owncloud.android.lib.resources.activities.GetRemoteActivitiesOperation.parseResult(GetRemoteActivitiesOperation.java:129) 
at com.owncloud.android.lib.resources.activities.GetRemoteActivitiesOperation.run(GetRemoteActivitiesOperation.java:96) 
at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136) 
at com.owncloud.android.ui.activity.ActivitiesListActivity$3.run(ActivitiesListActivity.java:213) 
at java.lang.Thread.run(Thread.java:818) 
```

$7 is: 
```
"subject_rich":[  
         "Sie haben Ihre E-Mail-Adresse geändert",
         [  

         ]
      ],
```

Shall we handle this, @nickvergessen? Or is this wrong on server side?

**Comment by nickvergessen** [comment]
Would be nice if you can handle this, since the data is not in our control.
So we would need to make sure every app developer does this.

**Comment by nickvergessen** [comment]
```php
var_dump(json_encode(array()));
string(2) "[]"

var_dump(json_encode(array(1, 2)));
string(5) "[1,2]"

var_dump(json_encode(array('a' => 1, 'b' => 2)));
string(13) "{"a":1,"b":2}"
```

Empty + integer index arrays are `[`, string arrays are `{`

So would be nice if you can handle this. But I think `[]` is the only valid case.
On the other hand one could say you can also not send the rich subject in that case.
But better be on the save side and catch that case.

**Comment by tobiasKaminsky** [comment]
Closing as PR is merged.
