### ISSUE TITLE
NPE: `java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference`

### ISSUE THREAD

**Issue by wrenix** [nextcloud/android#13502]
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
    at com.owncloud.android.datamodel.OCFile.isInternalFolderSync(OCFile.java:1058)
    at com.owncloud.android.ui.fragment.FileDetailFragment.updateFileDetails(FileDetailFragment.java:569)
    at com.owncloud.android.ui.fragment.FileDetailFragment.onViewCreated(FileDetailFragment.java:266)
    at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3152)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:608)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2164)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2059)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:702)
    at android.os.Handler.handleCallback(Handler.java:959)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8592)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20240827`
* Build flavor: `versionDev`

### Device information
* Brand: `Fairphone`
* Device: `FP5`
* Model: `FP5`
* Id: `AP2A.240805.005`
* Product: `FP5`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `24510032`

**Comment by sujan6539** [comment]
The issue seems to originate from the `FileEntity.getInternalTwoWaySync` which is nullable, and there might be cases when it is actually null. The getter mentioned above is responsible for setting the internal folder sync timestamp using `setInternalFolderSyncTimestamp` in the manager. I prefer to change implementation of `setInternalFolderSyncTimestamp` in `OCFile.java` to set to default if a new time stamp is null.

**Comment by alperozturk96** [comment]
Thanks for the report. Could you try with this PR: https://github.com/nextcloud/android/pull/13612 ?

**Comment by herrwusel** [comment]
I downloaded the app and can confirm that the PR is working for me.
