### ISSUE TITLE
GPlay:  java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1353]
Version: 2.0.0RC2
Android: 7.x

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleCreateService (ActivityThread.java:3177)
  at android.app.ActivityThread.-wrap5 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1568)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6121)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:889)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:779)
Caused by: java.lang.ClassNotFoundException: 
  at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:56)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:380)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:312)
  at android.app.ActivityThread.handleCreateService (ActivityThread.java:3174)
```

```
java.lang.RuntimeException: Unable to instantiate service com.evernote.android.job.gcm.PlatformGcmService: java.lang.ClassNotFoundException: Didn't find class "com.evernote.android.job.gcm.PlatformGcmService" on path: DexPathList[[zip file "/data/app/com.nextcloud.client-1/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-1/lib/arm64, /system/lib64, /vendor/lib64]]
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3177)
	at android.app.ActivityThread.-wrap5(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1568)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6121)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.evernote.android.job.gcm.PlatformGcmService" on path: DexPathList[[zip file "/data/app/com.nextcloud.client-1/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-1/lib/arm64, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3174)
	... 8 more
	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/gcm/GcmTaskService;
		at java.lang.VMClassLoader.findLoadedClass(Native Method)
		at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
		... 10 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.gcm.GcmTaskService" on path: DexPathList[[zip file "/data/app/com.nextcloud.client-1/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-1/lib/arm64, /system/lib64, /vendor/lib64]]
		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
		... 13 more
```

There is no additional stack trace, so I do not know how to narrow this down :-/

**Comment by tobiasKaminsky** [comment]
@mario I found a second stracktrace with much more details. Do you have in idea what is wrong here?

**Comment by tobiasKaminsky** [comment]
Found something:
https://github.com/evernote/android-job/blob/master/FAQ.md#how-can-i-remove-the-gcm-dependency-from-my-app

I think I remember that we had this snippet in it, but now it is removed?
`
<service
        android:name="com.evernote.android.job.gcm.PlatformGcmService"
        tools:node="remove"/>
`

Can I safely add it again? Best in main/AndroidManifest.xml or in gplay/AndroidManifest.xml?

**Comment by mario** [comment]
Where is it? Can you post it here?

**Comment by tobiasKaminsky** [comment]
It is in my previous post:
https://github.com/nextcloud/android/commit/9130635fa1b9ba7b18a08cb54177c2924c2a8d8c#diff-84fb62e1c8a8f1b095012858ba4dc95dL266

and the snippet in question is:
<service android:name="com.evernote.android.job.gcm.PlatformGcmService" tools:node="remove"/>

and it was in src/main/AndroidManifest.xml

**Comment by tobiasKaminsky** [comment]
I created a PR, so if this needs to removed, we can simply merge without delaying ;-)

**Comment by tobiasKaminsky** [comment]
Fix merged
