### ISSUE TITLE
aU

### ISSUE THREAD

**Issue by jjw18e** [nextcloud/android#13571]
### Cause of error
```java
Exception in thread "Thread-4" java.lang.IllegalArgumentException: Trying to execute a sync operation with a storage manager for an anonymous account
    at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:49)
    at com.owncloud.android.ui.activity.DrawerActivity.lambda$fetchExternalLinks$9(DrawerActivity.java:1231)
    at com.owncloud.android.ui.activity.DrawerActivity.$r8$lambda$oHM2j1MZkviAIdyIFWoI2kSeF9c(Unknown Source:0)
    at com.owncloud.android.ui.activity.DrawerActivity$$ExternalSyntheticLambda6.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OP5552L1`
* Model: `CPH2419`
* Id: `UKQ1.230924.001`
* Product: `CPH2419`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `S.196ef87-d0ab-d0ac`

**Comment by joshtrichards** [comment]
Already known and fixed in #13444 in >=3.29.3
