### ISSUE TITLE
Bug de connexion à nextcloud depuis android

### ISSUE THREAD

**Issue by ErwanGui** [nextcloud/android#13581]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Au lancement de l'application sur Android lors de la sélection du compte, nous avons un crash avec un message d'erreur.

### Expected behaviour

Nous devrions nous connecter au compte utilisateur de nextcloud.

### Actual behaviour

Lors de la sélection du compte, nous avons un crash avec un message d'erreur.

### Android version

14

### Device brand and model

moto g84 5G

### Stock or custom OS?

Stock

### Nextcloud android app version

Version 20240713

### Nextcloud server version

Nextcloud hub 8 29.0.5

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.android.beta/com.owncloud.android.ui.activity.SsoGrantPermissionActivity}: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3898)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4042)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2548)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loopOnce(Looper.java:242)
    at android.os.Looper.loop(Looper.java:362)
    at android.app.ActivityThread.main(ActivityThread.java:8407)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
Caused by: Exception in thread "main" java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).
    at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:247)
    at com.google.android.material.internal.ThemeEnforcement.checkAppCompatTheme(ThemeEnforcement.java:212)
    at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:147)
    at com.google.android.material.internal.ThemeEnforcement.obtainStyledAttributes(ThemeEnforcement.java:76)
    at com.google.android.material.dialog.MaterialDialogs.getDialogBackgroundInsets(MaterialDialogs.java:60)
    at com.google.android.material.dialog.MaterialAlertDialogBuilder.<init>(MaterialAlertDialogBuilder.java:123)
    at com.google.android.material.dialog.MaterialAlertDialogBuilder.<init>(MaterialAlertDialogBuilder.java:109)
    at com.owncloud.android.ui.activity.SsoGrantPermissionActivity.onCreate(SsoGrantPermissionActivity.java:104)
    at android.app.Activity.performCreate(Activity.java:8732)
    at android.app.Activity.performCreate(Activity.java:8710)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3880)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4042)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2548)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loopOnce(Looper.java:242)
    at android.os.Looper.loop(Looper.java:362)
    at android.app.ActivityThread.main(ActivityThread.java:8407)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20240713`
* Build flavor: `versionDev`

### Device information
* Brand: `motorola`
* Device: `bangkk`
* Model: `moto g84 5G`
* Id: `U1TCS34.22-64-18-2`
* Product: `bangkk_ge`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `31594-b8200`

### Server error logs

```bash
Aucun
```

### Additional information

Ras

**Comment by joshtrichards** [comment]
Fixed #13295
Duplicate of #13305

You're running an outdated beta version:

```
ID: com.nextcloud.android.beta
Version: 20240713
Build flavor: versionDev
```

**Comment by ErwanGui** [comment]
Bonjour et merci d'avoir pris connaissance du bug,

Cependant, la version 1.24.1 est la version téléchargeable sur f_Droid. Sur mon smartphone elle fonctionne bien mais pas celui de ma femme. Le message d'erreur provient du portable de ma femme. 

Merci encore à vous.

**Comment by joshtrichards** [comment]
Stable version:

https://f-droid.org/en/packages/com.nextcloud.client/ <--- use this

Beta/development version:

https://f-droid.org/en/packages/com.nextcloud.android.beta/ <-- don't use this

**Comment by ErwanGui** [comment]
Bonjour,

Merci pour votre réponse. Nous avons mis à jour la version nextcloud sur
smartphone et cela fonctionne bien.

Merci et bonne journée
