### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by soymilkreborn** [nextcloud/android#13582]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open app

### Expected behaviour

1. Cannot login and show logs

### Actual behaviour

Open app, show crash/bug logs everytime click log in

### Android version

14

### Device brand and model

S23+

### Stock or custom OS?

Stock

### Nextcloud android app version

-

### Nextcloud server version

-

### Using a reverse proxy?

I don't know

### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Unable to resume activity {com.unificloudstorage.client/com.owncloud.android.authentication.AuthenticatorActivity}: java.lang.SecurityException: com.unificloudstorage.client: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5512)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5593)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2693)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:9063)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: Exception in thread "main" java.lang.SecurityException: com.unificloudstorage.client: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
    at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
    at android.os.Parcel.createException(Parcel.java:3053)
    at android.os.Parcel.readException(Parcel.java:3036)
    at android.os.Parcel.readException(Parcel.java:2978)
    at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6171)
    at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1913)
    at android.app.ContextImpl.registerReceiver(ContextImpl.java:1853)
    at android.app.ContextImpl.registerReceiver(ContextImpl.java:1841)
    at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:772)
    at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher.onResume(UsbConnectionDispatcher.java:113)
    at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.onActivityResumed(SecurityKeyManager.java:281)
    at android.app.Application.dispatchActivityResumed(Application.java:450)
    at android.app.Activity.dispatchActivityResumed(Activity.java:1543)
    at android.app.Activity.onResume(Activity.java:2144)
    at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:310)
    at com.owncloud.android.authentication.AuthenticatorActivity.onResume(AuthenticatorActivity.java:726)
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1603)
    at android.app.Activity.performResume(Activity.java:9172)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5484)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5593)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2693)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:9063)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: Exception in thread "main" android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:16724)
	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:11667)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2983)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3202)
	at android.os.Binder.execTransactInternal(Binder.java:1375)


```

### App information
* ID: `com.unificloudstorage.client`
* Version: `30240195`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `dm2q`
* Model: `SM-S916B`
* Id: `UP1A.231005.007`
* Product: `dm2qxxx`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `S916BXXU6CXH7`

**Comment by joshtrichards** [comment]
This bug was fixed long ago (#12263), but you're using both a highly out-of-date build and *not* our build. You'll need to contact your provider to get a newer build:

```
App information

    ID: com.unificloudstorage.client
    Version: 30240195
    Build flavor: gplay
```
