### ISSUE TITLE
Downloading multiple files gets stuck on "Wait a moment...": `IndexedForest$Node.getParent()' on a null object reference`

### ISSUE THREAD

**Issue by bakugo** [nextcloud/android#13595]
### ⚠️ Before posting ⚠️

- [x] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Select multiple files that have not been downloaded yet
2. Tap the "Download" option

### Expected behaviour

"Wait a moment..." dialog doesn't get stuck

### Actual behaviour

"Wait a moment..." remains on screen forever even after all the downloads are complete, making the app unusable until it's manually closed and restarted

### Android version

13

### Device brand and model

Google Pixel 7

### Stock or custom OS?

Stock

### Nextcloud android app version

3.29.2

### Nextcloud server version

28.0.9

### Using a reverse proxy?

Yes

### Android logs

```
09-22 14:37:16.671 12066 12118 E FileDownloadWorker: Error caught at FilesDownloadWorker(): Attempt to invoke virtual method 'com.owncloud.android.files.services.IndexedForest$Node com.owncloud.android.files.services.IndexedForest$Node.getParent()' on a null object reference
09-22 14:37:16.672 12066 12094 I WM-WorkerWrapper: Worker result FAILURE for Work [ id=ab45576c-80fa-4229-a7ce-62ea6cafa60f, tags={ com.nextcloud.client.jobs.download.FileDownloadWorker, *, name:files_download bakugo@[censored], timestamp:1727012226537, class:FileDownloadWorker, user:bakugo@[censored], folder_downloadbakugo@[censored]3170 } ]
09-22 14:37:16.676 12066 12066 I WM-SystemFgDispatcher: Stopping foreground service
09-22 14:37:17.485 12066 14952 D ContentObserverWork: File-sync Content Observer detected files change
09-22 14:37:17.540 12066 12084 I WM-WorkerWrapper: Work [ id=47cce63c-403f-4091-bc60-163c5b4ccbe9, tags={ com.nextcloud.client.jobs.ContentObserverWork, *, name:content_observer, timestamp:1727011205864, class:ContentObserverWork } ] was cancelled
09-22 14:37:17.540 12066 12084 I WM-WorkerWrapper: java.util.concurrent.CancellationException: Task was cancelled.
09-22 14:37:17.540 12066 12084 I WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1183)
09-22 14:37:17.540 12066 12084 I WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:513)
09-22 14:37:17.540 12066 12084 I WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:474)
09-22 14:37:17.540 12066 12084 I WM-WorkerWrapper: 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:316)
09-22 14:37:17.540 12066 12084 I WM-WorkerWrapper: 	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
09-22 14:37:17.540 12066 12084 I WM-WorkerWrapper: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
09-22 14:37:17.540 12066 12084 I WM-WorkerWrapper: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
09-22 14:37:17.540 12066 12084 I WM-WorkerWrapper: 	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by CatoLynx** [comment]
Can reproduce on my P30 pro with app version 3.29.2

**Comment by rostmodern** [comment]
Can reproduce with 3.30.6. The files get downloaded, same actual behaviour as in issue.

**Comment by joshtrichards** [comment]
Fixed a bit back in #13551
