### ISSUE TITLE
Android app crash when displaying folder details

### ISSUE THREAD

**Issue by CarlosCastaneda** [nextcloud/android#13608]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

When selecting view details of a folder app crashes. See Stack trace

### Expected behaviour

Should display folder details without crashing

### Actual behaviour

crashing with stacktrace

### Android version

14

### Device brand and model

Samsung GalaxyA52 

### Stock or custom OS?

Stock

### Nextcloud android app version

3.30.0

### Nextcloud server version

29.0.7.1

### Using a reverse proxy?

No

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
    at com.owncloud.android.datamodel.OCFile.isInternalFolderSync(OCFile.java:1058)
    at com.owncloud.android.datamodel.FileDataStorageManager.isPartOfInternalTwoWaySync(FileDataStorageManager.java:2504)
    at com.owncloud.android.ui.fragment.FileDetailFragment.updateFileDetails(FileDetailFragment.java:572)
    at com.owncloud.android.ui.fragment.FileDetailFragment.onViewCreated(FileDetailFragment.java:266)
    at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3152)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:608)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2164)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2059)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:702)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8919)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300090`
* Build flavor: `generic`

### Device information
* Brand: `samsung`
* Device: `a52q`
* Model: `SM-A525F`
* Id: `UP1A.231005.007`
* Product: `a52qnseea`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `A525FXXU8FXH1`

**Comment by rmelotte** [comment]
This seems to be the same as https://github.com/nextcloud/android/issues/13607 (opened 1 minute earlier).

**Comment by CarlosCastaneda** [comment]
There seem to be several issues causing the nullpointer exception [#13597](https://github.com/nextcloud/android/issues/13597), [#13596](https://github.com/nextcloud/android/issues/13596)

**Comment by alperozturk96** [comment]
Duplication of https://github.com/nextcloud/android/issues/13502

Could you try with this PR: https://github.com/nextcloud/android/pull/13612 ?
