### ISSUE TITLE
Nextcloud crashes when accessing "Details"

### ISSUE THREAD

**Issue by superzanti** [nextcloud/android#13607]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
    - These issues may be similar, but @AndyScherzinger said I should create it.
    - https://github.com/nextcloud/android/issues/13596
    - https://github.com/nextcloud/android/issues/13597
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

After upgrading to Nextcloud 30300090 from 30290390 (the issue does not exist in the earlier version) after clicking "details" for any file or folder, the app crashes.

This was in an attempt to get 2-way-sync working: https://github.com/nextcloud/android/issues/13294#issuecomment-2369118337_

From linked issue above I was instructed to tag:
@tobiasKaminsky and @alperozturk96

### Expected behaviour

The regular details view should open.

### Actual behaviour

Instead, I get a crash:

```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
    at com.owncloud.android.datamodel.OCFile.isInternalFolderSync(OCFile.java:1058)
    at com.owncloud.android.ui.fragment.FileDetailFragment.updateFileDetails(FileDetailFragment.java:569)
    at com.owncloud.android.ui.fragment.FileDetailFragment.onViewCreated(FileDetailFragment.java:266)
    at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3152)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:608)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2164)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2059)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:702)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7839)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

With:
* ID: `com.nextcloud.client`
* Version: `30300090`
* Build flavor: `generic`

Downgrading to 30290390 fixes this problem.

### Android version

12

### Device brand and model

Pixel 5a

### Stock or custom OS?

Stock

### Nextcloud android app version

30300090

### Nextcloud server version

23.0.3

### Using a reverse proxy?

No

**Comment by AndyScherzinger** [comment]
Sorry for the extra efforts @superzanti and thanks for checking @alperozturk96 - now we know for sure 👍

**Comment by alperozturk96** [comment]
Thanks for the report. Could you try with this PR: https://github.com/nextcloud/android/pull/13612 ? @superzanti

**Comment by superzanti** [comment]
@alperozturk96 I wish I could. unfortunately the NextcloudQA builds have never worked for me. They always crash when I type in the address to my nextcloud server.
