### ISSUE TITLE
Opening a linked file (already synced)

### ISSUE THREAD

**Issue by marco-acorte** [nextcloud/android#13626]
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'void com.owncloud.android.ui.activity.FileActivity.checkInternetConnection()' on a null object reference
    at com.owncloud.android.ui.fragment.OCFileListFragment.onItemClicked(OCFileListFragment.java:982)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onOpenFileIntent(FileDisplayActivity.java:580)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onNewIntent(FileDisplayActivity.java:519)
    at android.app.Activity.performNewIntent(Activity.java:8544)
    at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1538)
    at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1551)
    at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:4020)
    at android.app.ActivityThread.handleNewIntent(ActivityThread.java:4027)
    at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:56)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2394)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:211)
    at android.os.Looper.loop(Looper.java:300)
    at android.app.ActivityThread.main(ActivityThread.java:8296)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `Redmi`
* Device: `sweet`
* Model: `M2101K6G`
* Id: `TKQ1.221013.002`
* Product: `sweet_eea`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `V14.0.9.0.TKFEUXM`

**Comment by alperozturk96** [comment]
This issue resolved with [latest version](https://github.com/nextcloud/android/releases/tag/stable-3.30.0)
