### ISSUE TITLE
File open from Talk w multiple accounts causes crash (if account not active in Files)

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/android#13635]
### Steps to reproduce

1. Have 3 accounts
2. Login account A into the Files app
3. Login account B into the Talk app
4. Send a message with a link to an inaccessible file (e.g. internal link, no share from C to A) from account C to account B
5. Open the link as account B

### Expected behaviour

The link should be opened in the browser as the Files app can not open the file.

### Actual behaviour

The Files app opens but crashes because the only available user A does not have access to the file.

### Device brand and model

Pocophone F1

### Android version

14

### Nextcloud Talk app version

19.0.1

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

### Additional information

This might very well be an issue in the Files app instead, as it should not crash but open the link in the browser once it realizes that the logged in account does not have access to it.

**Comment by gerbrent** [comment]
Confirming this behaviour is repeatable consistently.

**To reproduce:**
Account A logged-in for Files Android and Talk Android.
Account B logged-in for Files Android and Talk Android.

When `Account A` is active in Files, `Account B` active in Talk: If you are in Talk (`Account B`) and you click on an internal link (on `Server B`), the Talk app attempts to open Files to retrieve the file, however since `Account A` is active in Files it causes a crash.

**Expected behaviour:** 
Clicked file from Talk `Account B` should open in Files via `Account B` - i.e. switch accounts in Files to open the file.

Adding some extra crash info:


```
Exception in thread "AsyncTask #1" java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$4.done(AsyncTask.java:415)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
    at java.util.concurrent.FutureTask.run(FutureTask.java:269)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
    at java.lang.Thread.run(Thread.java:1012)
Caused by: Exception in thread "AsyncTask #1" com.owncloud.android.operations.RemoteOperationFailedException: Error during saving file with parents: /Marketing/Launch marketing/Talk positioning/invitation-pressconf.md / Local file does not exist
    at com.owncloud.android.datamodel.FileDataStorageManager.saveFileWithParent(FileDataStorageManager.java:352)
    at com.owncloud.android.ui.asynctasks.FetchRemoteFileTask.doInBackground(FetchRemoteFileTask.java:76)
    at com.owncloud.android.ui.asynctasks.FetchRemoteFileTask.doInBackground(FetchRemoteFileTask.java:27)
    at android.os.AsyncTask$3.call(AsyncTask.java:394)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
    at java.lang.Thread.run(Thread.java:1012)
```

App information

    ID: com.nextcloud.client
    Version: 30300490
    Build flavor: generic

Device information

    Brand: google
    Device: panther
    Model: Pixel 7

Android 15 / GrapheneOS
