### ISSUE TITLE
App crash when attempting to open an encrypted folder: `IllegalStateException: metadata is null!`

### ISSUE THREAD

**Issue by bkilpat01** [nextcloud/android#13646]
When creating the folder, I received an error that there was a failure to upload metadata. When trying to open it, I receive the error below and the app crashes.

### Cause of error
```java
Exception in thread "Thread-12" java.lang.IllegalStateException: metadata is null!
    at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:498)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:418)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:247)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:387)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OP594DL1`
* Model: `CPH2451`
* Id: `TP1A.220905.001`
* Product: `CPH2451`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `T.R4T3.1983169-13fbe_635`

**Comment by joshtrichards** [comment]
Duplicate of #12704

**Comment by joshtrichards** [comment]
See https://github.com/nextcloud/android/issues/12704#issuecomment-2028809989 for solution

**Comment by bkilpat01** [comment]
That solution doesn't apply to this behavior - I don't have an app called "duplicatefinder" installed.

**Comment by joshtrichards** [comment]
> When creating the folder, I received an error that there was a failure to upload metadata.

Any idea what the original error was? 
What version of Nextcloud Server + the End-to-End app are you using?

**Comment by joshtrichards** [comment]
> I received an error that there was a failure to upload metadata. When trying to open it, I receive the error below and the app crashes.

The failed uploading of the metadata would have lead to this. So that's the part that needs to be looked closer at.

Do you have the server-side log entry of this failure?
