### ISSUE TITLE
Trying to edit a readme in the main files directory

### ISSUE THREAD

**Issue by Ganome** [nextcloud/android#13650]
### Cause of error
```java
Exception in thread "Thread-63" java.lang.NullPointerException: Attempt to invoke interface method 'com.owncloud.android.ui.helpers.FileOperationsHelper com.owncloud.android.ui.fragment.FileFragment$ContainerActivity.getFileOperationsHelper()' on a null object reference
    at com.owncloud.android.ui.preview.PreviewTextStringFragment.lambda$edit$1(PreviewTextStringFragment.java:143)
    at com.owncloud.android.ui.preview.PreviewTextStringFragment.$r8$lambda$_MpHYWLzP65yyRQaF66kF_Bz0rY(Unknown Source:0)
    at com.owncloud.android.ui.preview.PreviewTextStringFragment$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `oriole`
* Model: `Pixel 6`
* Id: `AP41.240823.009`
* Product: `oriole_beta`

### Firmware
* SDK: `35`
* Release: `15`
* Incremental: `12329489`

**Comment by alperozturk96** [comment]
Could you check with [latest](https://github.com/nextcloud/android/releases/tag/stable-3.30.0) version?
