### ISSUE TITLE
2.0.0RC2 java.lang.StringIndexOutOfBoundsException on Auto Upload

### ISSUE THREAD

**Issue by taaem** [nextcloud/android#1365]
### Actual behaviour
When opening the auto upload page the app crashes.

### Expected behaviour
Open Auto Upload
 
### Steps to reproduce
1. Open App
2. Open Auto upload
3. Crash

### Environment data
Android version: 7.2.0

Device model: OnePlus X

Stock or customized system: customized

Nextcloud app version: 2.0.0RC2

Nextcloud server version: 12.0.2

#### Nextcloud log (logcat)
```
08-17 15:01:17.512 E/AndroidRuntime(8147): FATAL EXCEPTION: main
08-17 15:01:17.512 E/AndroidRuntime(8147): Process: com.nextcloud.client, PID: 8147
08-17 15:01:17.512 E/AndroidRuntime(8147): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.SyncedFoldersActivity}: java.lang.StringIndexOutOfBoundsException: length=5; regionStart=0; regionLength=-1
08-17 15:01:17.512 E/AndroidRuntime(8147): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
08-17 15:01:17.512 E/AndroidRuntime(8147): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2745)
08-17 15:01:17.512 E/AndroidRuntime(8147): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
08-17 15:01:17.512 E/AndroidRuntime(8147): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1492)
08-17 15:01:17.512 E/AndroidRuntime(8147): 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-17 15:01:17.512 E/AndroidRuntime(8147): 	at android.os.Looper.loop(Looper.java:153)
08-17 15:01:17.512 E/AndroidRuntime(8147): 	at android.app.ActivityThread.main(ActivityThread.java:6208)
08-17 15:01:17.512 E/AndroidRuntime(8147): 	at java.lang.reflect.Method.invoke(Native Method)
08-17 15:01:17.512 E/AndroidRuntime(8147): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
08-17 15:01:17.512 E/AndroidRuntime(8147): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
08-17 15:01:17.512 E/AndroidRuntime(8147): Caused by: java.lang.StringIndexOutOfBoundsException: length=5; regionStart=0; regionLength=-1
08-17 15:01:17.512 E/AndroidRuntime(8147): 	at java.lang.String.substring(String.java:1931)
08-17 15:01:17.512 E/AndroidRuntime(8147): 	at com.owncloud.android.datamodel.MediaProvider.getImageFolders(MediaProvider.java:133)
08-17 15:01:17.512 E/AndroidRuntime(8147): 	at com.owncloud.android.ui.activity.SyncedFoldersActivity.load(SyncedFoldersActivity.java:210)
08-17 15:01:17.512 E/AndroidRuntime(8147): 	at com.owncloud.android.ui.activity.SyncedFoldersActivity.setupContent(SyncedFoldersActivity.java:197)
08-17 15:01:17.512 E/AndroidRuntime(8147): 	at com.owncloud.android.ui.activity.SyncedFoldersActivity.onCreate(SyncedFoldersActivity.java:150)
08-17 15:01:17.512 E/AndroidRuntime(8147): 	at android.app.Activity.performCreate(Activity.java:6684)
08-17 15:01:17.512 E/AndroidRuntime(8147): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
08-17 15:01:17.512 E/AndroidRuntime(8147): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
08-17 15:01:17.512 E/AndroidRuntime(8147): 	... 9 more
08-17 15:01:17.515 W/ActivityManager(1838):   Force finishing activity com.nextcloud.client/com.owncloud.android.ui.activity.SyncedFoldersActivity
08-17 15:01:17.517 W/ActivityManager(1838):   Force finishing activity com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity
08-17 15:01:17.519 W/DropBoxManagerService(1838): Dropping: data_app_crash (1832 > 0 bytes)
08-17 15:01:17.520 W/ContextImpl(1838): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:877 com.android.server.am.AppErrors.crashApplicationInner:374 com.android.server.am.AppErrors.crashApplication:308 com.android.server.am.ActivityManagerService.handleApplicationCrashInner:13570 com.android.server.am.ActivityManagerService.handleApplicationCrash:13552 
08-17 15:01:17.523 E/AppCrashReceiver(8885): com.nextcloud.client stopped unexpectedly...
```

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky the issue is this loc:

```
mediaFolder.absolutePath = filePath.substring(0, filePath.lastIndexOf("/"));
```

which could be hardened by doing a check like:
```
if (filePath.lastIndexOf("/") > 0) {
   mediaFolder.absolutePath = filePath.substring(0, filePath.lastIndexOf("/"));
} else {
   mediaFolder.absolutePath = filePath;
}
```

while I am unsure how a path could exists with a "/", the same thing would then also have to be done for video.

**Comment by tobiasKaminsky** [comment]
With this we want to get the folder where the image is in.
If there is a filepath without any "/" then it cannot be a valid path, even top of the device (root) is "/". So I would ignore those file paths?

**Comment by AndyScherzinger** [comment]
I think so too, path wouldn't be valid

**Comment by AndyScherzinger** [comment]
Fix has been merged
