### ISSUE TITLE
NullPointerException when trying to open a PDF document

### ISSUE THREAD

**Issue by ivanhercaz** [nextcloud/android#13657]
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
    at com.owncloud.android.datamodel.OCFile.isInternalFolderSync(OCFile.java:1079)
    at com.owncloud.android.datamodel.FileDataStorageManager.isPartOfInternalTwoWaySync(FileDataStorageManager.java:2589)
    at com.owncloud.android.ui.fragment.FileDetailFragment.updateFileDetails(FileDetailFragment.java:575)
    at com.owncloud.android.ui.fragment.FileDetailFragment.onViewCreated(FileDetailFragment.java:266)
    at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3152)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:608)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2164)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2059)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:702)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:257)
    at android.os.Looper.loop(Looper.java:368)
    at android.app.ActivityThread.main(ActivityThread.java:8839)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20240925`
* Build flavor: `versionDev`

### Device information
* Brand: `realme`
* Device: `REE2ADL1`
* Model: `RMX3710`
* Id: `UKQ1.230924.001`
* Product: `RMX3710EEA`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `T.R4T2.196a2d1-39af5`

**Comment by ivanhercaz** [comment]
After reporting directly from the application, I searched issues related and I think it is related or the same as #1365 and #13644.

Consider closing this one and keep the track on one.

Thank you very much for all your work with this application!

**Comment by alperozturk96** [comment]
Duplication of https://github.com/nextcloud/android/issues/13502
