### ISSUE TITLE
Crash app

### ISSUE THREAD

**Issue by yantodev** [nextcloud/android#13677]
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
    at com.owncloud.android.ui.adapter.OCFileListAdapter.limitToPersonalFiles(OCFileListAdapter.java:1074)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:741)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1359)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1308)
    at com.owncloud.android.ui.fragment.OCFileListFragment.onBrowseUp(OCFileListFragment.java:923)
    at com.owncloud.android.ui.activity.FileDisplayActivity.browseUp(FileDisplayActivity.java:1017)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onBackPressed(FileDisplayActivity.java:1010)
    at android.app.Activity.onKeyUp(Activity.java:4174)
    at android.view.KeyEvent.dispatch(KeyEvent.java:2958)
    at android.app.Activity.dispatchKeyEvent(Activity.java:4547)
    at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:120)
    at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:85)
    at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:138)
    at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)
    at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:60)
    at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3413)
    at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:445)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:7777)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7625)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7013)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7070)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7036)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7201)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7044)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7258)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7017)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7070)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7036)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7044)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7017)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7070)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7036)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7234)
    at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:7465)
    at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:4386)
    at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:3788)
    at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:3779)
    at android.view.inputmethod.InputMethodManager.-$$Nest$mfinishedInputEvent(Unknown Source:0)
    at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:4363)
    at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
    at android.os.MessageQueue.nativePollOnce(Native Method)
    at android.os.MessageQueue.next(MessageQueue.java:341)
    at android.os.Looper.loopOnce(Looper.java:176)
    at android.os.Looper.loop(Looper.java:318)
    at android.app.ActivityThread.main(ActivityThread.java:8770)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `POCO`
* Device: `redwood`
* Model: `22101320G`
* Id: `UKQ1.231003.002`
* Product: `redwood_id`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `V816.0.6.0.UMSIDXM`

**Comment by alperozturk96** [comment]
Solved with version https://github.com/nextcloud/android/releases/tag/stable-3.30.0
