### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by erikmartino** [nextcloud/android#13672]
### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Unable to resume activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.SecurityException: uid 10464 cannot get user data for accounts of type: nextcloud
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5427)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5508)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8919)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: Exception in thread "main" java.lang.SecurityException: uid 10464 cannot get user data for accounts of type: nextcloud
    at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
    at android.os.Parcel.createException(Parcel.java:3053)
    at android.os.Parcel.readException(Parcel.java:3036)
    at android.os.Parcel.readException(Parcel.java:2978)
    at android.accounts.IAccountManager$Stub$Proxy.getUserData(IAccountManager.java:1111)
    at android.accounts.AccountManager$2.recompute(AccountManager.java:435)
    at android.accounts.AccountManager$2.recompute(AccountManager.java:426)
    at android.app.PropertyInvalidatedCache.query(PropertyInvalidatedCache.java:999)
    at android.accounts.AccountManager.getUserData(AccountManager.java:618)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.<init>(OCFileListAdapter.java:160)
    at com.owncloud.android.ui.fragment.OCFileListFragment.setAdapter(OCFileListFragment.java:437)
    at com.owncloud.android.ui.fragment.OCFileListFragment.onActivityCreated(OCFileListFragment.java:379)
    at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3146)
    at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:579)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:264)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1901)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1819)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1762)
    at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:495)
    at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:312)
    at com.owncloud.android.ui.activity.BaseActivity.onResume(BaseActivity.java:91)
    at com.owncloud.android.ui.activity.DrawerActivity.onResume(DrawerActivity.java:983)
    at com.owncloud.android.ui.activity.FileActivity.onResume(FileActivity.java:251)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onResume(FileDisplayActivity.java:1114)
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1603)
    at android.app.Activity.performResume(Activity.java:9134)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5399)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5508)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8919)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: Exception in thread "main" android.os.RemoteException: Remote stack trace:
	at com.android.server.accounts.AccountManagerService.getUserData(AccountManagerService.java:1718)
	at android.accounts.IAccountManager$Stub.onTransact(IAccountManager.java:450)
	at com.android.server.accounts.AccountManagerService.onTransact(AccountManagerService.java:1171)
	at android.os.Binder.execTransactInternal(Binder.java:1375)
	at android.os.Binder.execTransact(Binder.java:1311)


```

### App information
* ID: `com.nextcloud.client`
* Version: `30250090`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `a52sxq`
* Model: `SM-A528B`
* Id: `UP1A.231005.007`
* Product: `a52sxqeea`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `A528BXXU9GXH1`

**Comment by alperozturk96** [comment]
Could you check with [latest](https://github.com/nextcloud/android/releases/tag/stable-3.30.0) version?

**Comment by joshtrichards** [comment]
Duplicate of #10159
