### ISSUE TITLE
Error when configuring new media folder

### ISSUE THREAD

**Issue by Soliprem** [nextcloud/android#13684]
### Cause of error
Occurred upon clicking on the notification to set up a new media folder
```java
Exception in thread "main" java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
    at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1852)
    at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1892)
    at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:341)
    at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:306)
    at androidx.fragment.app.DialogFragment.show(DialogFragment.java:519)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onSyncFolderSettingsClick(SyncedFoldersActivity.kt:600)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity$load$1$1.invokeSuspend(SyncedFoldersActivity.kt:323)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
    at android.os.Handler.handleCallback(Handler.java:959)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8592)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20240927`
* Build flavor: `versionDev`

### Device information
* Brand: `google`
* Device: `shiba`
* Model: `Pixel 8`
* Id: `AP2A.240905.003`
* Product: `shiba`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `12231197`

**Comment by joshtrichards** [comment]
Similar, but not the same area of our code as #11825
