### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by andrewdnsw** [nextcloud/android#13740]
### Cause of error
```java
Exception in thread "Thread-69" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:237)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:387)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `dm3q`
* Model: `SM-S918B`
* Id: `UP1A.231005.007`
* Product: `dm3qxxx`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `S918BXXS6CXG8`

**Comment by alperozturk96** [comment]
Could you try with [latest](https://github.com/nextcloud/android/releases/tag/rc-3.30.1-01) version?

**Comment by andrewdnsw** [comment]
I'll try it, thanks
