### ISSUE TITLE
rename

### ISSUE THREAD

**Issue by piotrbujakowski** [nextcloud/android#13742]
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.lib.common.operations.RemoteOperationResult.isSuccess()' on a null object reference
    at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:343)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoteOperationFinish(FileDisplayActivity.java:1607)
    at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:786)
    at com.owncloud.android.services.OperationsService$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7945)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

### App information
* ID: `tech.shadow.drive.android.client`
* Version: `30290090 (build #22647)`
* Build flavor: `gplay`

### Device information
* Brand: `Blackview`
* Device: `Tab11_EA`
* Model: `Tab 11`
* Id: `RP1A.201005.001`
* Product: `Tab11_EA`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `2022420`

**Comment by alperozturk96** [comment]
Could you try with [latest](https://github.com/nextcloud/android/releases/tag/rc-3.30.1-01) version?

**Comment by piotrbujakowski** [comment]
Hi.

Is no update is Google Play.
<br>
<br>
+---------------------------------------------------------<br>
| Sincerely<br>
| Piotr Bujakowski<br>
| <a href="https://sites.google.com/view/piotrbujakowski/">website</a><br>
| <a href="http://pl.linkedin.com/pub/piotr-bujakowski/61/77b/984/
">LinkedIn</a><br>
| <a href="https://www.youtube.com/channel/UCvW3qpdHSYb0LSCiUWXMk0g
">YouTube</a><br>

<br>
<br>
Please consider the environment before printing this e-mail.
<br>
<br>
The contents of this e-mail (including attachments) may be confidential and
legally privileged.
If you are not the intended recipient of this e-mail, or you have received
this message in error, please notify the sender immediately and then delete
the message (including any attachments).
Please be informed that any use, copying, disclosure or publication of this
message or of any information contained herein is strictly prohibited and
may cause legal liability.
