### ISSUE TITLE
`ENOSPC (No space left on device)`

### ISSUE THREAD

**Issue by patrickbrandt76** [nextcloud/android#13771]
### Cause of error
```java
Exception in thread "Thread-2" java.io.IOException: write failed: ENOSPC (No space left on device)
    at libcore.io.IoBridge.write(IoBridge.java:540)
    at java.io.FileOutputStream.write(FileOutputStream.java:398)
    at java.io.FileOutputStream.write(FileOutputStream.java:376)
    at com.nextcloud.client.logger.FileLogHandler.write(FileLogHandler.kt:77)
    at com.nextcloud.client.logger.LoggerImpl.eventLoop(LoggerImpl.kt:132)
    at com.nextcloud.client.logger.LoggerImpl.access$eventLoop(LoggerImpl.kt:32)
    at com.nextcloud.client.logger.LoggerImpl$start$1.invoke(LoggerImpl.kt:57)
    at com.nextcloud.client.logger.LoggerImpl$start$1.invoke(LoggerImpl.kt:57)
    at com.nextcloud.client.logger.ThreadLoop.loop(ThreadLoop.kt:70)
    at com.nextcloud.client.logger.ThreadLoop.$r8$lambda$hYfuazcxVm6CsqDRlq1Sko8-5IA(Unknown Source:0)
    at com.nextcloud.client.logger.ThreadLoop$$ExternalSyntheticLambda0.run(Unknown Source:2)
    at java.lang.Thread.run(Thread.java:923)
Caused by: Exception in thread "Thread-2" android.system.ErrnoException: write failed: ENOSPC (No space left on device)
    at libcore.io.Linux.writeBytes(Native Method)
    at libcore.io.Linux.write(Linux.java:293)
    at libcore.io.ForwardingOs.write(ForwardingOs.java:240)
    at libcore.io.BlockGuardOs.write(BlockGuardOs.java:418)
    at libcore.io.ForwardingOs.write(ForwardingOs.java:240)
    at libcore.io.IoBridge.write(IoBridge.java:535)
    at java.io.FileOutputStream.write(FileOutputStream.java:398)
    at java.io.FileOutputStream.write(FileOutputStream.java:376)
    at com.nextcloud.client.logger.FileLogHandler.write(FileLogHandler.kt:77)
    at com.nextcloud.client.logger.LoggerImpl.eventLoop(LoggerImpl.kt:132)
    at com.nextcloud.client.logger.LoggerImpl.access$eventLoop(LoggerImpl.kt:32)
    at com.nextcloud.client.logger.LoggerImpl$start$1.invoke(LoggerImpl.kt:57)
    at com.nextcloud.client.logger.LoggerImpl$start$1.invoke(LoggerImpl.kt:57)
    at com.nextcloud.client.logger.ThreadLoop.loop(ThreadLoop.kt:70)
    at com.nextcloud.client.logger.ThreadLoop.$r8$lambda$hYfuazcxVm6CsqDRlq1Sko8-5IA(Unknown Source:0)
    at com.nextcloud.client.logger.ThreadLoop$$ExternalSyntheticLambda0.run(Unknown Source:2)
    at java.lang.Thread.run(Thread.java:923)

```

### App information
* ID: `com.t_systems.android.webdav`
* Version: `72123 (build #17956)`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `a70q`
* Model: `SM-A705FN`
* Id: `RP1A.200720.012`
* Product: `a70qeea`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `A705FNXXU5DWB4`

**Comment by joshtrichards** [comment]
> No space left on device

You appear to be out of storage space on your phone/tablet.

> ID: com.t_systems.android.webdav
Version: 72123 (build #17956)
Build flavor: gplay

This isn't one of our builds. If you think this is a bug you should probably report it to your provider.

**Comment by joshtrichards** [comment]
Closing since "This isn't one of our builds. If you think this is a bug you should probably report it to your provider." so we don't know know what version of the code base this is referencing.
