### ISSUE TITLE
Crash during reading picture folder via app

### ISSUE THREAD

**Issue by rkolja76** [nextcloud/android#13770]
### Cause of error
```java
Exception in thread "Thread-16" java.lang.OutOfMemoryError: Failed to allocate a 72 byte allocation with 1731680 free bytes and 1691KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
    at java.util.Arrays.copyOf(Arrays.java:3553)
    at java.util.Arrays.copyOf(Arrays.java:3522)
    at java.util.ArrayList.grow(ArrayList.java:244)
    at java.util.ArrayList.grow(ArrayList.java:251)
    at java.util.ArrayList.add(ArrayList.java:461)
    at java.util.ArrayList.add(ArrayList.java:474)
    at org.apache.harmony.xml.dom.NodeListImpl.add(NodeListImpl.java:47)
    at org.apache.harmony.xml.dom.InnerNodeImpl.getChildNodes(InnerNodeImpl.java:59)
    at org.apache.jackrabbit.webdav.xml.ElementIterator.seek(ElementIterator.java:130)
    at org.apache.jackrabbit.webdav.xml.ElementIterator.<init>(ElementIterator.java:56)
    at org.apache.jackrabbit.webdav.xml.ElementIterator.<init>(ElementIterator.java:82)
    at org.apache.jackrabbit.webdav.xml.DomUtil.getChildren(DomUtil.java:345)
    at org.apache.jackrabbit.webdav.MultiStatusResponse.createFromXml(MultiStatusResponse.java:453)
    at org.apache.jackrabbit.webdav.MultiStatus.createFromXml(MultiStatus.java:185)
    at org.apache.jackrabbit.webdav.client.methods.DavMethodBase.processResponseBody(DavMethodBase.java:282)
    at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1749)
    at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
    at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
    at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
    at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
    at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
    at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:192)
    at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.run(ReadFolderRemoteOperation.java:62)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:193)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:413)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:247)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:387)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300190`
* Build flavor: `generic`

### Device information
* Brand: `samsung`
* Device: `e3q`
* Model: `SM-S928B`
* Id: `UP1A.231005.007`
* Product: `e3qxeea`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `S928BXXS3AXI8`

**Comment by joshtrichards** [comment]
Duplicate of #9903
