### ISSUE TITLE
Error on Nextcloud Android app

### ISSUE THREAD

**Issue by acress1** [nextcloud/android#13784]
Hi,
I've got this error message in the Android app:

### Cause of error
```java
Exception in thread "Syncfolder thread" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getEtag()' on a null object reference
    at com.owncloud.android.operations.SynchronizeFolderOperation.checkForChanges(SynchronizeFolderOperation.java:169)
    at com.owncloud.android.operations.SynchronizeFolderOperation.run(SynchronizeFolderOperation.java:127)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:193)
    at com.owncloud.android.services.SyncFolderHandler.doOperation(SyncFolderHandler.java:106)
    at com.owncloud.android.services.SyncFolderHandler.handleMessage(SyncFolderHandler.java:79)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.os.HandlerThread.run(HandlerThread.java:85)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300190`
* Build flavor: `generic`

### Device information
* Brand: `OnePlus`
* Device: `OnePlus5T`
* Model: `ONEPLUS A5010`
* Id: `AP2A.240905.003`
* Product: `OnePlus5T`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `0c7a9b4c4c`

**Comment by z3ntu** [comment]
Also just saw this crash on the same version, while trying to stop https://github.com/nextcloud/android/issues/13738

**Comment by strugee** [comment]
I've just hit this on version ` 30300290`. It happened literally _while _ I was removing entries from the "internal 2-way sync" section in the app settings.

**Comment by AndyScherzinger** [comment]
CC @alperozturk96

**Comment by stilley2** [comment]
Seeing this with 3.30.4 as well

**Comment by joshtrichards** [comment]
Fixed in #16374
