### ISSUE TITLE
Client syncs everything locally despite unchecking "Sync" in details and now it crashed!

### ISSUE THREAD

**Issue by Rex-0x7CB** [nextcloud/android#13782]
### Cause of error
```java
Exception in thread "Syncfolder thread" java.lang.IllegalStateException: metadata is null!
    at com.owncloud.android.operations.SynchronizeFolderOperation.synchronizeData(SynchronizeFolderOperation.java:276)
    at com.owncloud.android.operations.SynchronizeFolderOperation.fetchAndSyncRemoteFolder(SynchronizeFolderOperation.java:206)
    at com.owncloud.android.operations.SynchronizeFolderOperation.run(SynchronizeFolderOperation.java:131)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:193)
    at com.owncloud.android.services.SyncFolderHandler.doOperation(SyncFolderHandler.java:106)
    at com.owncloud.android.services.SyncFolderHandler.handleMessage(SyncFolderHandler.java:79)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.os.HandlerThread.run(HandlerThread.java:67)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300190`
* Build flavor: `generic`

### Device information
* Brand: `samsung`
* Device: `m33x`
* Model: `SM-M336BU`
* Id: `UP1A.231005.007`
* Product: `m33xins`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `M336BUXXS9EXH1`

**Comment by Rex-0x7CB** [comment]
More details: The sync restarts on internet connectivity if I cancel the download. Plus, I keep getting toast notifications saying "Signature does not match" during the download. It all started after the last updating Android client to 3.30.1.

**Comment by mintsoft** [comment]
Yeah the syncing is very broken in 3.30.1; I've uninstalled and downgraded as there isn't a workaround for 3.30.1
It sounds like you're hitting the same problem as all these:

https://github.com/nextcloud/android/issues/13780
https://github.com/nextcloud/android/issues/13773
https://github.com/nextcloud/android/issues/13772
https://github.com/nextcloud/android/issues/13771
https://github.com/nextcloud/android/issues/13752
https://github.com/nextcloud/android/issues/13747
https://github.com/nextcloud/android/issues/13738

**Comment by Joshndroid** [comment]
I am seeing the same thing. Had to disable app for now

**Comment by alexfulton** [comment]
What an incredible update. My phone died and was completely full because next cloud decided to sync everything??? And throw errors for all 6000 items??? Creating a notification for every item 3 times???

**Comment by joshtrichards** [comment]
> ` metadata is null!`

This crash output is encryption related and arose <3.30.1: #13646

The "syncing lots of data" matter is covered in: #13738

**Comment by chascode** [comment]
The app consumed over 10GB of my monthly data allowance.  No matter how many times I said, "no, don't sync anything," it decided to sync everything again and again.

My phone felt warm, too, and nextcloud was the only running background app.

Downgraded to the play store version.
