### ISSUE TITLE
Error during uploading Camera folder (80 GB) from smartphone.

### ISSUE THREAD

**Issue by uninvisible** [nextcloud/android#13804]
### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1186896 bytes
    at android.app.ActivityClient.finishActivity(ActivityClient.java:188)
    at android.app.Activity.finish(Activity.java:7374)
    at android.app.Activity.finish(Activity.java:7391)
    at com.owncloud.android.ui.activity.UploadFilesActivity.onCheckAvailableSpaceFinish(UploadFilesActivity.java:525)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:58)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:20)
    at android.os.AsyncTask.finish(AsyncTask.java:771)
    at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
    at android.os.Handler.dispatchMessage(Handler.java:117)
    at android.os.Looper.loopOnce(Looper.java:210)
    at android.os.Looper.loop(Looper.java:302)
    at android.app.ActivityThread.main(ActivityThread.java:9652)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:601)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1062)
Caused by: Exception in thread "main" android.os.TransactionTooLargeException: data parcel size 1186896 bytes
    at android.os.BinderProxy.transactNative(Native Method)
    at android.os.BinderProxy.transact(BinderProxy.java:606)
    at android.app.IActivityClientController$Stub$Proxy.finishActivity(IActivityClientController.java:1632)
    at android.app.ActivityClient.finishActivity(ActivityClient.java:185)
    at android.app.Activity.finish(Activity.java:7374)
    at android.app.Activity.finish(Activity.java:7391)
    at com.owncloud.android.ui.activity.UploadFilesActivity.onCheckAvailableSpaceFinish(UploadFilesActivity.java:525)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:58)
    at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:20)
    at android.os.AsyncTask.finish(AsyncTask.java:771)
    at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
    at android.os.Handler.dispatchMessage(Handler.java:117)
    at android.os.Looper.loopOnce(Looper.java:210)
    at android.os.Looper.loop(Looper.java:302)
    at android.app.ActivityThread.main(ActivityThread.java:9652)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:601)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1062)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20241016`
* Build flavor: `versionDev`

### Device information
* Brand: `HONOR`
* Device: `HNBVL`
* Model: `BVL-N49`
* Id: `HONORBVL-N49`
* Product: `BVL-N49EEA`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `8.0.0.194C430E12R2P2`

**Comment by joshtrichards** [comment]
In theory this was fixed in #13336 and is a duplicate of #10242 but `20241016` contains that fix. Maybe we have a little bit more work to do in `onCheckAvailableSpaceFinish()`.

Cc: @alperozturk96
