### ISSUE TITLE
Mystery Error: `IllegalArgumentException: context is null`

### ISSUE THREAD

**Issue by qole** [nextcloud/android#13823]
This morning I opened my phone to a screen with this error. I don't think that I had the Nextcloud client open when I put it on the charger last night.

### Cause of error
```java
Exception in thread "WM.task-1" java.lang.IllegalArgumentException: context is null
    at android.accounts.AccountManager.get(AccountManager.java:458)
    at com.owncloud.android.lib.common.OwnCloudAccount.<init>(OwnCloudAccount.java:63)
    at com.nextcloud.client.account.UserAccountManagerImpl.createUserFromAccount(UserAccountManagerImpl.java:194)
    at com.nextcloud.client.account.UserAccountManagerImpl.getUser(UserAccountManagerImpl.java:236)
    at com.owncloud.android.utils.theme.MaterialSchemesProviderImpl.getMaterialSchemesForCurrentUser(MaterialSchemesProviderImpl.kt:48)
    at com.nextcloud.client.di.ThemeModule$Companion.provideMaterialSchemes(ThemeModule.kt:42)
    at com.nextcloud.client.di.ThemeModule_Companion_ProvideMaterialSchemesFactory.provideMaterialSchemes(ThemeModule_Companion_ProvideMaterialSchemesFactory.java:47)
    at com.nextcloud.client.di.ThemeModule_Companion_ProvideMaterialSchemesFactory.get(ThemeModule_Companion_ProvideMaterialSchemesFactory.java:37)
    at com.nextcloud.client.di.ThemeModule_Companion_ProvideMaterialSchemesFactory.get(ThemeModule_Companion_ProvideMaterialSchemesFactory.java:13)
    at com.owncloud.android.utils.theme.ViewThemeUtils_Factory.get(ViewThemeUtils_Factory.java:39)
    at com.owncloud.android.utils.theme.ViewThemeUtils_Factory.get(ViewThemeUtils_Factory.java:12)
    at com.nextcloud.client.jobs.BackgroundJobFactory.createMediaFoldersDetectionWork(BackgroundJobFactory.kt:202)
    at com.nextcloud.client.jobs.BackgroundJobFactory.createWorker(BackgroundJobFactory.kt:87)
    at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:82)
    at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:243)
    at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:144)
    at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `dream2qltecan`
* Model: `SM-G955W`
* Id: `PPR1.180610.011`
* Product: `dream2qltevl`

### Firmware
* SDK: `28`
* Release: `9`
* Incremental: `G955WVLU8CUF3`

**Comment by joshtrichards** [comment]
Looks like #11026, but this was in theory already fixed. We backported #13080 to v3.29.1 via #13098.

@alperozturk96 Any idea why this would still be happening in 3.29.2?

**Comment by alperozturk96** [comment]
> Looks like [#11026](https://github.com/nextcloud/android/issues/11026), but this was in theory already fixed. We backported [#13080](https://github.com/nextcloud/android/pull/13080) to v3.29.1 via [#13098](https://github.com/nextcloud/android/pull/13098).
> 
> [@alperozturk96](https://github.com/alperozturk96) Any idea why this would still be happening in 3.29.2?
> 
> EDIT: Does it have something to do with 3.29.2 not being a tagged release?

It might still be null, so we need to check it at the beginning of the function before using it. I’ll create a fix for this. Thanks for the reminder!
