### ISSUE TITLE
Error adding account

### ISSUE THREAD

**Issue by grrosminet** [nextcloud/android#13828]
### Cause of error
```java
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 9
    at java.lang.String.checkBoundsBeginEnd(String.java:4500)
    at java.lang.String.substring(String.java:2527)
    at com.nextcloud.client.account.UserAccountManagerImpl.exists(UserAccountManagerImpl.java:119)
    at com.nextcloud.client.mixins.SessionMixin.onRestart(SessionMixin.kt:100)
    at com.nextcloud.client.mixins.MixinRegistry.onRestart(MixinRegistry.kt:48)
    at com.owncloud.android.ui.activity.BaseActivity.onRestart(BaseActivity.java:118)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onRestart(FileDisplayActivity.java:2352)
    at android.app.Instrumentation.callActivityOnRestart(Instrumentation.java:1592)
    at android.app.Activity.performRestart(Activity.java:9140)
    at android.app.ActivityThread.performRestartActivity(ActivityThread.java:6062)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:250)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:187)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2693)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:9063)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300190`
* Build flavor: `generic`

### Device information
* Brand: `samsung`
* Device: `b5q`
* Model: `SM-F731B`
* Id: `UP1A.231005.007`
* Product: `b5qxeea`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `F731BXXS3DXI3`

**Comment by grrosminet** [comment]
This was just after clearing all data from the app (because after the update the app started to do a full sync of my whole cloud data to then phone and over cell data whereas it should have only be done over wifi)
