### ISSUE TITLE
Unexpected Crash Message

### ISSUE THREAD

**Issue by falavu** [nextcloud/android#13890]
### Cause of error
```java
Exception in thread "main" android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{c7d6055 u0 com.nextcloud.client/androidx.work.impl.foreground.SystemForegroundService}
    at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2277)
    at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2248)
    at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2542)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:222)
    at android.os.Looper.loop(Looper.java:314)
    at android.app.ActivityThread.main(ActivityThread.java:8716)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
Caused by: Exception in thread "main" android.app.StackTrace: Last startServiceCommon() call for this service was made here
    at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1963)
    at android.app.ContextImpl.startForegroundService(ContextImpl.java:1917)
    at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:841)
    at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:841)
    at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:1128)
    at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:700)
    at androidx.work.impl.Processor.startForeground(Processor.java:206)
    at androidx.work.impl.utils.WorkForegroundUpdater$1.run(WorkForegroundUpdater.java:100)
    at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300290`
* Build flavor: `generic`

### Device information
* Brand: `Redmi`
* Device: `earth`
* Model: `22120RN86G`
* Id: `UP1A.231005.007`
* Product: `earth_global`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `V816.0.6.0.UCVMIXM`

**Comment by falavu** [comment]
This Crash didnt come before; its the First Time in 10 Years using NC. So i think it happens to the last Update.

**Comment by joshtrichards** [comment]
Similar to #12706

**Comment by falavu** [comment]
Today i get a Message again, NC „crashes unexpectedly“. I clicked „send“ (dont know how it does). 
In my Structure are not much Folders (mentioned in #12706).
