### ISSUE TITLE
…

### ISSUE THREAD

**Issue by tangshxiao** [nextcloud/android#13931]
### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Design assumption violated.
    at androidx.viewpager2.adapter.FragmentStateAdapter.placeFragmentInViewHolder(FragmentStateAdapter.java:285)
    at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:274)
    at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:74)
    at androidx.recyclerview.widget.RecyclerView.dispatchChildAttached(RecyclerView.java:8377)
    at androidx.recyclerview.widget.RecyclerView$5.addView(RecyclerView.java:954)
    at androidx.recyclerview.widget.ChildHelper.addView(ChildHelper.java:131)
    at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:9430)
    at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:9388)
    at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:9375)
    at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1676)
    at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
    at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
    at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
    at android.view.View.layout(View.java:24332)
    at android.view.ViewGroup.layout(ViewGroup.java:6758)
    at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:535)
    at android.view.View.layout(View.java:24332)
    at android.view.ViewGroup.layout(ViewGroup.java:6758)
    at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
    at android.view.View.layout(View.java:24332)
    at android.view.ViewGroup.layout(ViewGroup.java:6758)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:359)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:295)
    at android.view.View.layout(View.java:24332)
    at android.view.ViewGroup.layout(ViewGroup.java:6758)
    at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:536)
    at android.view.View.layout(View.java:24332)
    at android.view.ViewGroup.layout(ViewGroup.java:6758)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:359)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:295)
    at android.view.View.layout(View.java:24332)
    at android.view.ViewGroup.layout(ViewGroup.java:6758)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1870)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1714)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1623)
    at android.view.View.layout(View.java:24332)
    at android.view.ViewGroup.layout(ViewGroup.java:6758)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:359)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:295)
    at com.android.internal.policy.DecorView.onLayout(DecorView.java:1319)
    at android.view.View.layout(View.java:24332)
    at android.view.ViewGroup.layout(ViewGroup.java:6758)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:5214)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4542)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3146)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11127)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1599)
    at android.view.Choreographer.doCallbacks(Choreographer.java:1263)
    at android.view.Choreographer.doFrame(Choreographer.java:1127)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1549)
    at android.os.Handler.handleCallback(Handler.java:966)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:293)
    at android.app.ActivityThread.loopProcess(ActivityThread.java:9986)
    at android.app.ActivityThread.main(ActivityThread.java:9975)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290390`
* Build flavor: `generic`

### Device information
* Brand: `HUAWEI`
* Device: `HWELS`
* Model: `ELS-AN00`
* Id: `HUAWEIELS-AN00`
* Product: `ELS-AN00`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `104.2.0.120C00`

**Comment by joshtrichards** [comment]
Any idea how to trigger it? Our code isn't mentioned anywhere in the stack trace unfortunately.
