### ISSUE TITLE
Crash on opening property of a file: in `FileDetailFragment`

### ISSUE THREAD

**Issue by Bonbadil** [nextcloud/android#13933]
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to read from field 'com.google.android.material.tabs.TabLayout com.owncloud.android.databinding.FileDetailsFragmentBinding.tabLayout' on a null object reference in method 'void com.owncloud.android.ui.fragment.FileDetailFragment.lambda$setupViewPager$0()'
    at com.owncloud.android.ui.fragment.FileDetailFragment.lambda$setupViewPager$0(FileDetailFragment.java:355)
    at com.owncloud.android.ui.fragment.FileDetailFragment.$r8$lambda$Sp-VmtMx2q_HeyzGV0P1GEAXBvw(Unknown Source:0)
    at com.owncloud.android.ui.fragment.FileDetailFragment$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7932)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300390`
* Build flavor: `generic`

### Device information
* Brand: `Fairphone`
* Device: `FP4`
* Model: `FP4`
* Id: `TKQ1.230127.002`
* Product: `FP4eea`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `TP2L`

**Comment by joshtrichards** [comment]
Similar to #9351

**Comment by joshtrichards** [comment]
Fixed in #14051
