### ISSUE TITLE
Opened the  client after being  disconnected from VPN and got the following error. 

### ISSUE THREAD

**Issue by lordyavin** [nextcloud/android#13941]
### Cause of error
```java
Exception in thread "Thread-6" java.lang.NullPointerException: Attempt to invoke virtual method 'org.apache.commons.httpclient.HostConfiguration com.owncloud.android.lib.common.OwnCloudClient.getHostConfiguration()' on a null object reference
    at com.nextcloud.common.NextcloudClient.execute(NextcloudClient.kt:116)
    at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$fetchAndSetData$6(FileDetailActivitiesFragment.java:295)
    at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.$r8$lambda$fzpi7kO8PpXaUSSQob84vDVuOjs(Unknown Source:0)
    at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment$$ExternalSyntheticLambda5.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `dm1q`
* Model: `SM-S911B`
* Id: `UP1A.231005.007`
* Product: `dm1qxeea`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `S911BXXS6CXGA`

**Comment by joshtrichards** [comment]
Fixed in nextcloud/android-library#1477
