### ISSUE TITLE
NPE: `AuthenticatorActivity.createAccount` in `getVersion()`

### ISSUE THREAD

**Issue by Eshwarnani74** [nextcloud/android#13965]
### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.lib.resources.status.OwnCloudVersion.getVersion()' on a null object reference
    at com.owncloud.android.authentication.AuthenticatorActivity.createAccount(AuthenticatorActivity.java:1314)
    at com.owncloud.android.authentication.AuthenticatorActivity.onAuthenticatorTaskCallback(AuthenticatorActivity.java:1120)
    at com.owncloud.android.authentication.AuthenticatorAsyncTask.onPostExecute(AuthenticatorAsyncTask.kt:90)
    at com.owncloud.android.authentication.AuthenticatorAsyncTask.onPostExecute(AuthenticatorAsyncTask.kt:30)
    at android.os.AsyncTask.finish(AsyncTask.java:771)
    at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
    at android.os.Handler.dispatchMessage(Handler.java:108)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:328)
    at android.app.ActivityThread.main(ActivityThread.java:9242)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `vivo`
* Device: `2127`
* Model: `V2142`
* Id: `UP1A.231005.007`
* Product: `2127i`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `compiler10211622`

**Comment by joshtrichards** [comment]
Is this easily reproducible for you?

Is this a new installation?

**Comment by Eshwarnani74** [comment]
Yes after updating the app I got the error
