### ISSUE TITLE
Crashes in background and when started

### ISSUE THREAD

**Issue by rugk** [nextcloud/android#14036]
### Cause of error
```java
Exception in thread "Syncfolder thread" java.lang.IllegalStateException: metadata is null!
    at com.owncloud.android.operations.SynchronizeFolderOperation.synchronizeData(SynchronizeFolderOperation.java:276)
    at com.owncloud.android.operations.SynchronizeFolderOperation.fetchAndSyncRemoteFolder(SynchronizeFolderOperation.java:206)
    at com.owncloud.android.operations.SynchronizeFolderOperation.run(SynchronizeFolderOperation.java:132)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:193)
    at com.owncloud.android.services.SyncFolderHandler.doOperation(SyncFolderHandler.java:106)
    at com.owncloud.android.services.SyncFolderHandler.handleMessage(SyncFolderHandler.java:79)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.os.HandlerThread.run(HandlerThread.java:85)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300490`
* Build flavor: `generic`

### Device information
* Brand: `Fairphone`
* Device: `FP4`
* Model: `FP4`
* Id: `AP2A.240905.003`
* Product: `FP4eea`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `24512012`

**Comment by joshtrichards** [comment]
This is E2EE related. What's the `meta.data` version of the folder being accessed?

See https://github.com/nextcloud/end_to_end_encryption/issues/802#issue-2601062295 for an example.

Are you getting a `NotFoundException` in your Server log?

Related: #13646, #12704

And I suspect this: nextcloud/end_to_end_encryption#802
