### ISSUE TITLE
Change in file path for downloaded files crashes app

### ISSUE THREAD

**Issue by marianoju** [nextcloud/android#14074]
I have tried thrice to change the file path for downloaded files. App has crashed every time. 

### Cause of error
```java
Exception in thread "AsyncTask #1" java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$4.done(AsyncTask.java:415)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
    at java.util.concurrent.FutureTask.run(FutureTask.java:271)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:923)
Caused by: Exception in thread "AsyncTask #1" java.lang.RuntimeException: com.owncloud.android.ui.activity.StorageMigration$FileMigrationTask$MigrationException
    at com.owncloud.android.ui.activity.StorageMigration$FileMigrationTask.checkDestinationAvailability(StorageMigration.java:432)
    at com.owncloud.android.ui.activity.StorageMigration$FileMigrationTask.doInBackground(StorageMigration.java:379)
    at com.owncloud.android.ui.activity.StorageMigration$FileMigrationTask.doInBackground(StorageMigration.java:335)
    at android.os.AsyncTask$3.call(AsyncTask.java:394)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:923)
Caused by: Exception in thread "AsyncTask #1" com.owncloud.android.ui.activity.StorageMigration$FileMigrationTask$MigrationException
    at com.owncloud.android.ui.activity.StorageMigration$FileMigrationTask.checkDestinationAvailability(StorageMigration.java:429)
    at com.owncloud.android.ui.activity.StorageMigration$FileMigrationTask.doInBackground(StorageMigration.java:379)
    at com.owncloud.android.ui.activity.StorageMigration$FileMigrationTask.doInBackground(StorageMigration.java:335)
    at android.os.AsyncTask$3.call(AsyncTask.java:394)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:923)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300590`
* Build flavor: `generic`

### Device information
* Brand: `Fairphone`
* Device: `FP3`
* Model: `FP3`
* Id: `8901.4.A.0023.0`
* Product: `FP3`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `gms-e1827e20`

**Comment by matthijskooijman** [comment]
I ran into the same issue, but without changing the path, but only disabling "Allow access from other apps" under settings -> Data storage location.

After pressing ok, the app showed "preparing migration" or something similar for about 10mins, and then the below crash.

This is a fairly large nextcloud repo, total data server side is probably somewhere between 100 and 200GB, the nextcloud app uses 50GB of storage on my phone (tbh I am not sure wjat for, since I did not setup any automatic syncing, so I would expect files would get downloaded/cached on-demand?).


### Cause of error
```java
Exception in thread "AsyncTask #3" java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$4.done(AsyncTask.java:415)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
    at java.util.concurrent.FutureTask.run(FutureTask.java:269)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
    at java.lang.Thread.run(Thread.java:1012)
Caused by: Exception in thread "AsyncTask #3" java.lang.RuntimeException: com.owncloud.android.ui.activity.StorageMigration$FileMigrationTask$MigrationException
    at com.owncloud.android.ui.activity.StorageMigration$FileMigrationTask.checkDestinationAvailability(StorageMigration.java:432)
    at com.owncloud.android.ui.activity.StorageMigration$FileMigrationTask.doInBackground(StorageMigration.java:379)
    at com.owncloud.android.ui.activity.StorageMigration$FileMigrationTask.doInBackground(StorageMigration.java:335)
    at android.os.AsyncTask$3.call(AsyncTask.java:394)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
    at java.lang.Thread.run(Thread.java:1012)
Caused by: Exception in thread "AsyncTask #3" com.owncloud.android.ui.activity.StorageMigration$FileMigrationTask$MigrationException
    at com.owncloud.android.ui.activity.StorageMigration$FileMigrationTask.checkDestinationAvailability(StorageMigration.java:429)
    at com.owncloud.android.ui.activity.StorageMigration$FileMigrationTask.doInBackground(StorageMigration.java:379)
    at com.owncloud.android.ui.activity.StorageMigration$FileMigrationTask.doInBackground(StorageMigration.java:335)
    at android.os.AsyncTask$3.call(AsyncTask.java:394)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30310390`
* Build flavor: `generic`

### Device information
* Brand: `samsung`
* Device: `beyond0lte`
* Model: `SM-G970F`
* Id: `TQ3A.230805.001`
* Product: `lineage_beyond0lte`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `eng.root.20230903.025444`
