### ISSUE TITLE
homelab crash

### ISSUE THREAD

**Issue by Mixze85** [nextcloud/android#14092]
### Cause of error
```java
Exception in thread "main" java.lang.ClassCastException: android.view.AbsSavedState$1 cannot be cast to android.widget.ScrollView$SavedState
    at android.widget.ScrollView.onRestoreInstanceState(ScrollView.java:1963)
    at android.view.View.dispatchRestoreInstanceState(View.java:21031)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4000)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4006)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4006)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4006)
    at android.view.View.restoreHierarchyState(View.java:21009)
    at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2206)
    at android.app.Activity.onRestoreInstanceState(Activity.java:1723)
    at com.owncloud.android.authentication.AuthenticatorActivity.onRestoreInstanceState(AuthenticatorActivity.java:633)
    at android.app.Activity.performRestoreInstanceState(Activity.java:1676)
    at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1377)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3681)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2215)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:346)
    at android.os.Looper.loop(Looper.java:475)
    at android.app.ActivityThread.main(ActivityThread.java:7889)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `Sony`
* Device: `XQ-AS52`
* Model: `XQ-AS52`
* Id: `58.2.A.10.126`
* Product: `XQ-AS52_EEA`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `058002A010012603718185433`

**Comment by joshtrichards** [comment]
Any idea how to trigger/reproduce?
