### ISSUE TITLE
Crash on startup

Hi, I've just added a New Server to my nextcloud App through webdav (a scan to connect to nextcloud qr code).
Since then, my app crashes on startup.

Thanks for your help! 

### ISSUE THREAD

**Issue by Marceau-h** [nextcloud/android#14119]
### Cause of error
```java
Exception in thread "Thread-9" java.lang.NumberFormatException: For input string: "root1632"
    at java.lang.Long.parseLong(Long.java:751)
    at java.lang.Long.parseLong(Long.java:876)
    at com.owncloud.android.datamodel.OCFile.getLocalId(OCFile.java:631)
    at com.owncloud.android.datamodel.FileDataStorageManager.createContentValuesBase(FileDataStorageManager.java:533)
    at com.owncloud.android.datamodel.FileDataStorageManager.createContentValuesForFolder(FileDataStorageManager.java:552)
    at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:464)
    at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:590)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:418)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:247)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:387)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `p3s`
* Model: `SM-G998B`
* Id: `UP1A.231005.007`
* Product: `p3sxeea`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `G998BXXSDGXI5`

**Comment by joshtrichards** [comment]
> `Exception in thread "Thread-9" java.lang.NumberFormatException: For input string: "root1632"`

root1632 is not local file id (nor a remote one for that matter).

Tell us more about the accounts(s) you have configured in the app and the server(s) they're associated with. Are any of them non-Nextcloud?
