### ISSUE TITLE
Unknown crash reason

### ISSUE THREAD

**Issue by n1iic** [nextcloud/android#14113]
### Cause of error
```java
Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property currentAccount has not been initialized
    at com.nextcloud.client.mixins.SessionMixin.getCurrentAccount(SessionMixin.kt:32)
    at com.nextcloud.client.mixins.SessionMixin.onRestart(SessionMixin.kt:100)
    at com.nextcloud.client.mixins.MixinRegistry.onRestart(MixinRegistry.kt:48)
    at com.owncloud.android.ui.activity.BaseActivity.onRestart(BaseActivity.java:118)
    at android.app.Instrumentation.callActivityOnRestart(Instrumentation.java:1445)
    at android.app.Activity.performRestart(Activity.java:8216)
    at android.app.ActivityThread.performRestartActivity(ActivityThread.java:4985)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:243)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2116)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7723)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `Blackview`
* Device: `BL8800Pro`
* Model: `BL8800Pro`
* Id: `RP1A.200720.011`
* Product: `BL8800Pro_EEA`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `1669051792`

**Comment by joshtrichards** [comment]
Duplicate of #13241
