### ISSUE TITLE
Crash in "Uploads" settings: `ArrayIndexOutOfBoundsException` in `UploadListAdapter.getItem()`

### ISSUE THREAD

**Issue by nursoda** [nextcloud/android#14190]
### Cause of error
```java
Exception in thread "Thread-16" java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
    at com.owncloud.android.ui.adapter.UploadListAdapter$UploadGroup.getItem(UploadListAdapter.java:950)
    at com.owncloud.android.ui.adapter.UploadListAdapter.lambda$onBindHeaderViewHolder$1(UploadListAdapter.java:126)
    at com.owncloud.android.ui.adapter.UploadListAdapter.$r8$lambda$YAYMxGL62Zd9c5Duvx7hlxn0wPE(Unknown Source:0)
    at com.owncloud.android.ui.adapter.UploadListAdapter$$ExternalSyntheticLambda11.run(D8$$SyntheticClass:0)
    at java.lang.Thread.run(Thread.java:1117)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300690`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `bluejay`
* Model: `Pixel 6a`
* Id: `AP4A.241205.013`
* Product: `bluejay`

### Firmware
* SDK: `35`
* Release: `15`
* Incremental: `2024121200`

**Comment by joshtrichards** [comment]
Related: #10613
