### ISSUE TITLE
Ahorro de batería

### ISSUE THREAD

**Issue by Arcangel1520** [nextcloud/android#14191]
### Cause of error
```java
Exception in thread "main" android.content.res.Resources$NotFoundException: Resource ID #0x7f0a0420 type #0x12 is not valid
    at android.content.res.Resources.loadXmlResourceParser(Resources.java:2388)
    at android.content.res.Resources.getLayout(Resources.java:1276)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
    at androidx.appcompat.app.AlertController.setupCustomContent(AlertController.java:644)
    at androidx.appcompat.app.AlertController.setupView(AlertController.java:475)
    at androidx.appcompat.app.AlertController.installContent(AlertController.java:233)
    at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:278)
    at android.app.Dialog.dispatchOnCreate(Dialog.java:702)
    at android.app.Dialog.show(Dialog.java:424)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.showPowerCheckDialog(SyncedFoldersActivity.kt:234)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onDisablePowerSaveCheckClicked(SyncedFoldersActivity.kt:218)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.onCreateOptionsMenu$lambda$1(SyncedFoldersActivity.kt:211)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity.$r8$lambda$q58-_n5tvnvo7t7SwBQVBpaIAdU(Unknown Source:0)
    at com.owncloud.android.ui.activity.SyncedFoldersActivity$$ExternalSyntheticLambda4.onMenuItemClick(D8$$SyntheticClass:0)
    at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
    at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:984)
    at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
    at android.widget.AdapterView.performItemClick(AdapterView.java:374)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1736)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:4207)
    at android.widget.AbsListView.onTouchUp(AbsListView.java:6707)
    at android.widget.AbsListView.onTouchEvent(AbsListView.java:6453)
    at android.widget.ListView.onTouchEvent(ListView.java:1721)
    at androidx.appcompat.widget.DropDownListView.onTouchEvent(DropDownListView.java:230)
    at androidx.appcompat.widget.MenuPopupWindow$MenuDropDownListView.onTouchEvent(MenuPopupWindow.java:138)
    at android.view.View.dispatchTouchEvent(View.java:14368)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3857)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
    at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:6365)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
    at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2860)
    at android.view.View.dispatchPointerEvent(View.java:14636)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6579)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6357)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5793)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5846)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5812)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5968)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5820)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6025)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5793)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5846)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5812)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5820)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5793)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9029)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8886)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8839)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9166)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:194)
    at android.os.MessageQueue.nativePollOnce(Native Method)
    at android.os.MessageQueue.next(MessageQueue.java:336)
    at android.os.Looper.loop(Looper.java:197)
    at android.app.ActivityThread.main(ActivityThread.java:8167)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300690`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `crownlte`
* Model: `SM-N960F`
* Id: `QP1A.190711.020`
* Product: `crownltexx`

### Firmware
* SDK: `29`
* Release: `10`
* Incremental: `N960FXXU9FVH1`

**Comment by madman-81** [comment]
I just got this same exception when clicking the checkbox "Uitschakelen stroombespar.." (disable power saving) menu option in the Automatic upload configuration menu. Resetting the app doesn't solve it. I'm using the same app version.

**Comment by joshtrichards** [comment]
Duplicate of #13404
