### ISSUE TITLE
App crash when cancel upload from notifications after stopping it from the app

### ISSUE THREAD

**Issue by molhamalnasr** [nextcloud/android#14236]
### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Unable to start receiver com.nextcloud.client.jobs.upload.FileUploadHelper$UploadNotificationActionReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.owncloud.android.db.OCUpload.setUploadStatus(com.owncloud.android.datamodel.UploadsStorageManager$UploadStatus)' on a null object reference
    at android.app.ActivityThread.handleReceiver(ActivityThread.java:4990)
    at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2506)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:9063)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'void com.owncloud.android.db.OCUpload.setUploadStatus(com.owncloud.android.datamodel.UploadsStorageManager$UploadStatus)' on a null object reference
    at com.nextcloud.client.jobs.upload.FileUploadHelper.cancelFileUpload(FileUploadHelper.kt:195)
    at com.nextcloud.client.jobs.upload.FileUploadHelper$UploadNotificationActionReceiver.onReceive(FileUploadHelper.kt:333)
    at android.app.ActivityThread.handleReceiver(ActivityThread.java:4981)
    at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2506)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:9063)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30290290`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `dm3q`
* Model: `SM-S918B`
* Id: `UP1A.231005.007`
* Product: `dm3qxeea`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `S918BXXS7CXK6`

**Comment by alperozturk96** [comment]
Fixed via https://github.com/nextcloud/android/commit/7167916db9e271d20ba2226a9093aa48f7d39e47
