### ISSUE TITLE
NetworkOnMainThreadException:  FileDataStorageManager.saveFileWithParent

### ISSUE THREAD

**Issue by tabi-ya** [nextcloud/android#14238]
### Cause of error
```java
Exception in thread "main" com.owncloud.android.operations.RemoteOperationFailedException: Error during saving file with parents: /Signal/signal-2024-12-24-21-51-40.backup / Unexpected exception / null
    at com.owncloud.android.datamodel.FileDataStorageManager.saveFileWithParent(FileDataStorageManager.java:549)
    at com.owncloud.android.datamodel.FileDataStorageManager.createPendingFile(FileDataStorageManager.java:209)
    at com.owncloud.android.datamodel.FileDataStorageManager.addCreateFileOfflineOperation(FileDataStorageManager.java:174)
    at com.owncloud.android.ui.activity.FileDisplayActivity.lambda$requestUploadOfFilesFromFileSystem$16(FileDisplayActivity.java:1023)
    at com.owncloud.android.ui.activity.FileDisplayActivity.$r8$lambda$GG51LwFMwIhUrmNJlkp9-QY2xq0(Unknown Source:0)
    at com.owncloud.android.ui.activity.FileDisplayActivity$$ExternalSyntheticLambda9.onComplete(D8$$SyntheticClass:0)
    at com.nextcloud.client.network.ConnectivityServiceImpl.lambda$isNetworkAndServerAvailable$0(ConnectivityServiceImpl.java:76)
    at com.nextcloud.client.network.ConnectivityServiceImpl$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:233)
    at android.app.ActivityThread.main(ActivityThread.java:8063)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: Exception in thread "main" android.os.NetworkOnMainThreadException
    at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1605)
    at org.conscrypt.Platform.blockGuardOnNetwork(Platform.java:804)
    at org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:811)
    at org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:799)
    at org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:772)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:248)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:267)
    at org.apache.commons.httpclient.HttpConnection.isStale(HttpConnection.java:506)
    at org.apache.commons.httpclient.HttpConnection.closeIfStale(HttpConnection.java:431)
    at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.closeIfStale(MultiThreadedHttpConnectionManager.java:1313)
    at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:382)
    at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
    at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
    at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
    at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:192)
    at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:155)
    at com.owncloud.android.lib.resources.files.ReadFileRemoteOperation.run(ReadFileRemoteOperation.java:72)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:132)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:141)
    at com.owncloud.android.datamodel.FileDataStorageManager.saveFileWithParent(FileDataStorageManager.java:538)
    at com.owncloud.android.datamodel.FileDataStorageManager.createPendingFile(FileDataStorageManager.java:209)
    at com.owncloud.android.datamodel.FileDataStorageManager.addCreateFileOfflineOperation(FileDataStorageManager.java:174)
    at com.owncloud.android.ui.activity.FileDisplayActivity.lambda$requestUploadOfFilesFromFileSystem$16(FileDisplayActivity.java:1023)
    at com.owncloud.android.ui.activity.FileDisplayActivity.$r8$lambda$GG51LwFMwIhUrmNJlkp9-QY2xq0(Unknown Source:0)
    at com.owncloud.android.ui.activity.FileDisplayActivity$$ExternalSyntheticLambda9.onComplete(D8$$SyntheticClass:0)
    at com.nextcloud.client.network.ConnectivityServiceImpl.lambda$isNetworkAndServerAvailable$0(ConnectivityServiceImpl.java:76)
    at com.nextcloud.client.network.ConnectivityServiceImpl$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:233)
    at android.app.ActivityThread.main(ActivityThread.java:8063)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20241210`
* Build flavor: `versionDev`

### Device information
* Brand: `OnePlus`
* Device: `OnePlusN100METRO`
* Model: `BE2015`
* Id: `RKQ1.201217.002`
* Product: `OnePlusN100METRO`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `2310091801`

**Comment by joshtrichards** [comment]
Related: #13635
