### ISSUE TITLE
error when logging in with mobile app

### ISSUE THREAD

**Issue by severin10** [nextcloud/android#14263]
### Cause of error
```java
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 9
    at java.lang.String.checkBoundsBeginEnd(String.java:4500)
    at java.lang.String.substring(String.java:2527)
    at com.nextcloud.client.account.UserAccountManagerImpl.exists(UserAccountManagerImpl.java:119)
    at com.nextcloud.client.mixins.SessionMixin.onRestart(SessionMixin.kt:100)
    at com.nextcloud.client.mixins.MixinRegistry.onRestart(MixinRegistry.kt:48)
    at com.owncloud.android.ui.activity.BaseActivity.onRestart(BaseActivity.java:118)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onRestart(FileDisplayActivity.java:2408)
    at android.app.Instrumentation.callActivityOnRestart(Instrumentation.java:1713)
    at android.app.Activity.performRestart(Activity.java:9145)
    at android.app.ActivityThread.performRestartActivity(ActivityThread.java:5873)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:239)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:194)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:176)
    at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:129)
    at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:103)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:80)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2719)
    at android.os.Handler.dispatchMessage(Handler.java:109)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8787)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300690`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `lynx`
* Model: `Pixel 7a`
* Id: `AP4A.241205.013`
* Product: `lynx`

### Firmware
* SDK: `35`
* Release: `15`
* Incremental: `12621605`

**Comment by Kishubhai** [comment]
reinstall the application and install again
