### ISSUE TITLE
unable to start app on cyanogenmod 11 (Android 4.4.4) without GApps

### ISSUE THREAD

**Issue by amo13** [nextcloud/android#1483]
### Actual behaviour
- Starting the nextcloud app just briefly shows the login screen and then the app crashes with android saying "nextcloud wurde beendet"
- To me it looks like the missing Google Apps are the problem, but in my opinion the nextcloud app should not rely on these in any way

### Environment data
Android version: 4.4.4

Device model: HTC One S

Stock or customized system: Cyanogenmod 11 (official)

Nextcloud app version: latest

Nextcloud server version: latest

### Android Logcat

```
--------- beginning of /dev/log/system
I/AccountAuthenticator( 5588): Adding account with type nextcloud and auth token null
D/OperationsService( 5588): Creating service
I/Timeline( 5588): Timeline: Activity_launch_request id:com.nextcloud.client time:5336387
I/ActivityManager(  532): START u0 {flg=0x10800004 cmp=com.nextcloud.client/com.owncloud.android.authentication.AuthenticatorActivity (has extras)} from pid 5588
D/FileDownloader( 5588): Creating service
D/FileUploader( 5588): Creating service
V/UploadsStorageManager( 5588): Updating state of any killed upload
V/UploadsStorageManager( 5588): No upload was killed
D/FileObserverService( 5588): onCreate
D/FileObserverService( 5588): Starting command Intent { act=com.owncloud.android.services.observer.FileObserverService.action.START_OBSERVATION cmp=com.nextcloud.client/com.owncloud.android.services.observer.FileObserverService }
D/FileObserverService( 5588): Loading all kept-in-sync files from database to start watching them
I/Adreno200-EGL( 5588): <qeglDrvAPI_eglInitialize:269>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_JB_VANILLA.04.02.02.60.051_msm8960_JB_VANILLA_CL2997615_release_AU (CL2997615)
I/Adreno200-EGL( 5588): Build Date: 04/11/13 Thu
I/Adreno200-EGL( 5588): Local Branch: 
I/Adreno200-EGL( 5588): Remote Branch: quic/mako_jb_mr1
I/Adreno200-EGL( 5588): Local Patches: NONE
I/Adreno200-EGL( 5588): Reconstruct Branch: AU_LINUX_ANDROID_JB_VANILLA.04.02.02.60.051 +  NOTHING
D/OpenGLRenderer( 5588): Enabling debug mode 0
I/dalvikvm( 5588): Could not find method android.support.v7.widget.LinearLayoutCompat.drawableHotspotChanged, referenced from method android.support.design.internal.ForegroundLinearLayout.drawableHotspotChanged
W/dalvikvm( 5588): VFY: unable to resolve virtual method 17787: Landroid/support/v7/widget/LinearLayoutCompat;.drawableHotspotChanged (FF)V
D/dalvikvm( 5588): VFY: replacing opcode 0x6f at 0x0000
V/FileDisplayActivity( 5588): onPause() start
D/FileDisplayActivity( 5588): onPause() ending
V/FileDisplayActivity( 5588): onPause() end
D/FileActivity( 5588): Operations service connected
D/FileDisplayActivity( 5588): Download service connected
D/FileDisplayActivity( 5588): Upload service connected
D/AuthenticatorActivity( 5588): onCreate(Bundle) starting
I/Timeline( 5588): Timeline: Activity_launch_request id:com.nextcloud.client time:5336706
I/ActivityManager(  532): START u0 {cmp=com.nextcloud.client/com.owncloud.android.ui.activity.WhatsNewActivity} from pid 5588
I/TextInputLayout( 5588): EditText added is not a TextInputEditText. Please switch to using that class instead.
I/TextInputLayout( 5588): EditText added is not a TextInputEditText. Please switch to using that class instead.
I/TextInputLayout( 5588): EditText added is not a TextInputEditText. Please switch to using that class instead.
I/TextInputLayout( 5588): EditText added is not a TextInputEditText. Please switch to using that class instead.
I/TextInputLayout( 5588): EditText added is not a TextInputEditText. Please switch to using that class instead.
D/AuthenticatorActivity( 5588): onStart() starting
D/AuthenticatorActivity( 5588): onResume() starting
D/AuthenticatorActivity( 5588): onPause() ending
D/WhatsNewActivity( 5588): onCreate(Bundle) starting
W/ResourceType( 5588): Failure getting entry for 0x7f08000a (t=7 e=10) in package 0 (error -75)
E/ActivityThread( 5588): Failed to find resource
E/ActivityThread( 5588): android.content.res.Resources$NotFoundException: String resource ID #0x7f08000a
E/ActivityThread( 5588): 	at android.content.res.Resources.getText(Resources.java:265)
E/ActivityThread( 5588): 	at android.widget.TextView.setText(TextView.java:3888)
E/ActivityThread( 5588): 	at com.owncloud.android.ui.activity.WhatsNewActivity.onCreate(WhatsNewActivity.java:142)
E/ActivityThread( 5588): 	at android.app.Activity.performCreate(Activity.java:5231)
E/ActivityThread( 5588): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/ActivityThread( 5588): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
E/ActivityThread( 5588): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
E/ActivityThread( 5588): 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
E/ActivityThread( 5588): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
E/ActivityThread( 5588): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/ActivityThread( 5588): 	at android.os.Looper.loop(Looper.java:136)
E/ActivityThread( 5588): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
E/ActivityThread( 5588): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/ActivityThread( 5588): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/ActivityThread( 5588): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
E/ActivityThread( 5588): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
E/ActivityThread( 5588): 	at dalvik.system.NativeStart.main(Native Method)
D/AndroidRuntime( 5588): Shutting down VM
W/dalvikvm( 5588): threadid=1: thread exiting with uncaught exception (group=0x4160cce0)
E/AndroidRuntime( 5588): FATAL EXCEPTION: main
E/AndroidRuntime( 5588): Process: com.nextcloud.client, PID: 5588
E/AndroidRuntime( 5588): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.WhatsNewActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x7f08000a
E/AndroidRuntime( 5588): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2212)
E/AndroidRuntime( 5588): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
E/AndroidRuntime( 5588): 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
E/AndroidRuntime( 5588): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
E/AndroidRuntime( 5588): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 5588): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 5588): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
E/AndroidRuntime( 5588): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 5588): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 5588): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
E/AndroidRuntime( 5588): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
E/AndroidRuntime( 5588): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 5588): Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x7f08000a
E/AndroidRuntime( 5588): 	at android.content.res.Resources.getText(Resources.java:265)
E/AndroidRuntime( 5588): 	at android.widget.TextView.setText(TextView.java:3888)
E/AndroidRuntime( 5588): 	at com.owncloud.android.ui.activity.WhatsNewActivity.onCreate(WhatsNewActivity.java:142)
E/AndroidRuntime( 5588): 	at android.app.Activity.performCreate(Activity.java:5231)
E/AndroidRuntime( 5588): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime( 5588): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
E/AndroidRuntime( 5588): 	... 11 more
W/ActivityManager(  532):   Force finishing activity com.nextcloud.client/com.owncloud.android.ui.activity.WhatsNewActivity
W/ActivityManager(  532):   Force finishing activity com.nextcloud.client/com.owncloud.android.authentication.AuthenticatorActivity
I/Timeline(  532): Timeline: Activity_windows_visible id: ActivityRecord{421d9908 u0 com.nextcloud.client/com.owncloud.android.authentication.AuthenticatorActivity t24 f} time:5337224
W/ActivityManager(  532): Activity pause timeout for ActivityRecord{42047a10 u0 com.nextcloud.client/com.owncloud.android.ui.activity.WhatsNewActivity t24 f}
I/Process ( 5588): Sending signal. PID: 5588 SIG: 9
I/ActivityManager(  532): Process com.nextcloud.client (pid 5588) has died.
I/WindowState(  532): WIN DEATH: Window{42273790 u0 com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}
W/ActivityManager(  532): Scheduling restart of crashed service com.nextcloud.client/com.owncloud.android.authentication.AccountAuthenticatorService in 1000ms
W/ActivityManager(  532): Scheduling restart of crashed service com.nextcloud.client/com.owncloud.android.services.observer.SyncedFolderObserverService in 10998ms
W/ActivityManager(  532): Scheduling restart of crashed service com.nextcloud.client/com.owncloud.android.services.observer.FileObserverService in 10997ms
W/ActivityManager(  532): Scheduling restart of crashed service com.nextcloud.client/com.evernote.android.job.JobRescheduleService in 20996ms
I/WindowState(  532): WIN DEATH: Window{421f0d90 u0 com.nextcloud.client/com.owncloud.android.authentication.AuthenticatorActivity}
W/ActivityManager(  532): Force removing ActivityRecord{420c20e0 u0 com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity t24}: app died, no saved state
W/InputMethodManagerService(  532): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@41f83760 attribute=null, token = android.os.BinderProxy@41fb2b28
I/Timeline(  851): Timeline: Activity_idle id: android.os.BinderProxy@41a67440 time:5339392
I/Timeline(  532): Timeline: Activity_windows_visible id: ActivityRecord{41b14a70 u0 com.cyanogenmod.trebuchet/org.cyanogenmod.trebuchet.CustomHomeLauncher t1} time:5339804
```

Thanks for investigating

**Comment by lynxis** [comment]
I could verify this bug using nextcloud server: 12.0.2 and nextcloud android: 1.4.2 via fdroid.
Version 2.0.0 RC5 works fine.

**Comment by amo13** [comment]
Oh yes, I did not see Version 2.0.0 RC5 on fdroid, because it installed 1.4.2 automatically. Thanks for pointing me to this!
Closed.

**Comment by lynxis** [comment]
It's not installed as default because it's marked as development. Maybe you should reopen this bug as long the latest "default" version is still broken.

**Comment by AndyScherzinger** [comment]
@lynxis I labeled the issue "2.0.0" so at least (in the future) it will be clear that this matter has been resolved with 2.0.0 :)

**Comment by amo13** [comment]
Ok, reopening until the default version on fdroid works. I hope I'm going to remember closing it again ;)

**Comment by tobiasKaminsky** [comment]
> E/ActivityThread( 5588): android.content.res.Resources$NotFoundException: String resource ID #0x7f08000a

This is the real error and was reported long time ago in #946 and then fixed.

> Ok, reopening until the default version on fdroid works. I hope I'm going to remember closing it again ;)

Let us do it the other way around: if the problem still occurs after 2.0 release, please re-open ;-)
