### ISSUE TITLE
Nextcloud app crashes when opening 'Activities' overview

### ISSUE THREAD

**Issue by louwers** [nextcloud/android#1601]
### Actual behaviour
- Application crashes
### Expected behaviour
- Activities shown
 
### Steps to reproduce
1. Click Activites in sidebar

### Environment data
Android version: 7.1.2

Device model: Oneplus X

Stock or customized system: LineageOS

Nextcloud app version: 20170926 (from F-Droid)

Nextcloud server version: 12.0.3

#### Web server error log
N/A

#### Nextcloud log (data/nextcloud.log)
I can't find such a file on my device.

**Comment by louwers** [comment]
Also when opening 'Notifications' or 'Uploads'.

**Comment by louwers** [comment]
Here's what logcat gave me:
```
09-28 02:58:21.199  3806  3806 E AndroidRuntime: FATAL EXCEPTION: main
09-28 02:58:21.199  3806  3806 E AndroidRuntime: Process: com.nextcloud.android.beta, PID: 3806
09-28 02:58:21.199  3806  3806 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.android.beta/com.owncloud.android.ui.activity.ActivitiesListActivity}: android.view.InflateException: Binary XML file line #34: You must specify a layout in the include tag: <include layout="@layout/layoutID" />
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #34: You must specify a layout in the include tag: <include layout="@layout/layoutID" />
09-28 02:58:21.199  3806  3806 E AndroidRuntime: Caused by: android.view.InflateException: You must specify a layout in the include tag: <include layout="@layout/layoutID" />
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:921)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:854)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at com.owncloud.android.ui.activity.ActivitiesListActivity.onCreate(ActivitiesListActivity.java:127)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6684)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
09-28 02:58:21.199  3806  3806 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
09-28 02:58:21.202  1578 14213 W ActivityManager:   Force finishing activity com.nextcloud.android.beta/com.owncloud.android.ui.activity.ActivitiesListActivity
09-28 02:58:21.208  1578 14213 W ActivityManager:   Force finishing activity com.nextcloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity
09-28 02:58:21.276  1578  6899 I OpenGLRenderer: Initialized EGL, version 1.4
09-28 02:58:21.276  1578  6899 D OpenGLRenderer: Swap behavior 1
09-28 02:58:21.708  1578  1735 W ActivityManager: Activity pause timeout for ActivityRecord{cc59d09 u0 com.nextcloud.android.beta/com.owncloud.android.ui.activity.ActivitiesListActivity t986 f}
09-28 02:58:22.316  4506  4653 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
09-28 02:58:22.316  4506  4653 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
09-28 02:58:23.780   256   424 D audio_hw_primary: out_standby: enter: stream (0xb6270f00) usecase(1: low-latency-playback)
09-28 02:58:23.866   256   424 D hardware_info: hw_info_append_hw_type : device_name = speaker
09-28 02:58:32.048  1578  1735 W ActivityManager: Activity destroy timeout for ActivityRecord{cc59d09 u0 com.nextcloud.android.beta/com.owncloud.android.ui.activity.ActivitiesListActivity t986 f}
09-28 02:58:32.050  1578  1735 W ActivityManager: Activity destroy timeout for ActivityRecord{1c3a1c1 u0 com.nextcloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity t986 f}

```

**Comment by louwers** [comment]
Just tried 2.0.0RC7, no crash here when clicking Activities/Notifications/Uploads. So I am pretty sure it's not my server.

**Comment by tobiasKaminsky** [comment]
Thank you very much for this helpful logcat!

> Caused by: android.view.InflateException: Binary XML file line #34: You must specify a layout in the include tag: <include layout="@layout/layoutID" />

**Comment by tobiasKaminsky** [comment]
> <include
            android:id="@+id/navigation_bar"
            android:layout="@layout/toolbar_standard"/>

Strange, the layout is there...
@AndyScherzinger you did a change regarding the includes: https://github.com/nextcloud/android/commit/6e8d3b1c97dc8d4d416fff276de4ec188a59e230
Do you have time to have a look?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky https://github.com/nextcloud/android/commit/9b876ea2a6abd28f85fde58eb2bf04f8da041e70 should fix this, directly added to the dev branch. I'll check the corresponding feature PR later.

**Comment by AndyScherzinger** [comment]
@louwers does it still happen for you with latest dev version 20170930 ?

**Comment by louwers** [comment]
@AndyScherzinger Nope! Closing this. Thank you.
