### ISSUE TITLE
IndexOutOfBounds (reason unknown) via Play Store Console

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#17]
**App Version 1.0.0** 

**Android version**
    Android 6.01
**Device**
    Xperia Z5 Compact (E5823) 1

> One of my folders kill the nextcloud app. This also happend on owncloud.

```
**java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1**
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at android.widget.HeaderViewListAdapter.isEnabled(HeaderViewListAdapter.java:164)
	at android.widget.AbsListView.onInitializeAccessibilityNodeInfoForItem(AbsListView.java:2478)
	at android.widget.ListView.onInitializeAccessibilityNodeInfoForItem(ListView.java:3946)
	at android.widget.AbsListView$ListItemAccessibilityDelegate.onInitializeAccessibilityNodeInfo(AbsListView.java:2409)
	at android.view.View.onInitializeAccessibilityNodeInfo(View.java:6151)
	at android.view.View.createAccessibilityNodeInfoInternal(View.java:6112)
	at android.view.View$AccessibilityDelegate.createAccessibilityNodeInfo(View.java:22359)
	at android.view.View.createAccessibilityNodeInfo(View.java:6095)
	at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:145)
	at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:119)
	at android.view.View.onInitializeAccessibilityEventInternal(View.java:6049)
	at android.view.View$AccessibilityDelegate.onInitializeAccessibilityEvent(View.java:22271)
	at android.view.View.onInitializeAccessibilityEvent(View.java:6035)
	at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:5902)
	at android.view.View$AccessibilityDelegate.sendAccessibilityEventUnchecked(View.java:22210)
	at android.view.View.sendAccessibilityEventUnchecked(View.java:5885)
	at android.view.View.sendAccessibilityEventInternal(View.java:5864)
	at android.view.View$AccessibilityDelegate.sendAccessibilityEvent(View.java:22168)
	at android.view.View.sendAccessibilityEvent(View.java:5829)
	at android.widget.AdapterView.performItemClick(AdapterView.java:317)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3042)
	at android.widget.AbsListView$3.run(AbsListView.java:3879)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:5514)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by MaksimDmitriev** [comment]
Hi,

Did you find a solution?

**Comment by AndyScherzinger** [comment]
Unfortunately no, is there any change to get a test account to experience this (probably not, but I'll ask anyways)? This would help a lot :)

**Comment by MaksimDmitriev** [comment]
Sorry, I didn't understand your question. What test account do you mean?

**Comment by AndyScherzinger** [comment]
On the server with the folder that kills the app. Unfortunately the stacktrace only shows classes of Androids own Operating System so I can't even see which part of our code is used here.

How many files are in that folder and are any of them special like "hidden" start with a "." or something?

**Comment by MaksimDmitriev** [comment]
Maybe some internal code of the Android accessibility service crashes. That's why we only see the Android classes in the stacktrace.

**Comment by AndyScherzinger** [comment]
The key is this part:
```
**java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1**
    at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
    at java.util.ArrayList.get(ArrayList.java:308)
    at android.widget.HeaderViewListAdapter.isEnabled(HeaderViewListAdapter.java:164)
```
Invalid index 1, size is 1 --> max index thus is 0...
This is probably due to the fact that just one file/folder exists and for whatever reason it tries to access a second element...

**Comment by MaksimDmitriev** [comment]
You could use something like Google Analytics to send the number of folders and their names on the screen prone to the crash. 

I mean the best option for you would be a sequence of events on the dashboard of Google Analytics: the user opened the screen (N folders, {file_name1, file_name2}) --> a crash report.

I'm not sure that's possible with Google Analytics, but if you have some time to do some research, you could do it.

**Comment by AndyScherzinger** [comment]
@MaksimDmitriev unfortunately no, using Google Analytics is strictly against the core idea of Nextcloud (being about freedom and privacy).

**Comment by MaksimDmitriev** [comment]
@AndyScherzinger, I didn't manage to reproduce the crash on my device. If you face it again, please write a comment here. I think some basic info should be enough. I mean something like, "I reproduced the crash with the screen one ListView. I fixed it by wrapping my ListView with a FrameLayout." I'd appreciate that ;)

**Comment by AndyScherzinger** [comment]
Will do!

**Comment by IvanAldrich** [comment]
@MaksimDmitriev have you got any solution for this exception or any advice? I got this exception and have no idea why

**Comment by AndyScherzinger** [comment]
No, not a clue. It seems to happen very rarely (or at least gets reported very rarely) and I never experienced it myself or found a way to reproduce it...
