### ISSUE TITLE
Can not connect if wrong ip6 in nameserver for domain

### ISSUE THREAD

**Issue by mghh** [nextcloud/android#1700]
### Actual behaviour
If I try to connect with the nextcloud app to my server it fails with a timeout without any traces in the error-log. Connecting with firefox/chrome on android was no problem.

My server has a domain like vm.myhost.mydomain. In the nameserver there was a valid ip4 registered to this domain and an invalid ip6.

After deletion of the invalid ipv6 for the domain everything was fine.

### Expected behaviour
It took me weeks to detect the problem because other apps run fine with my server. It would be nice if the app would report that I have a valid ip4 and an invalid ip6.

### Environment data
Android version:
7.0
Device model: 
Samsung S3 Tab

Nextcloud app version:
2.0.0

Nextcloud server version:
12.0.3

**Comment by dartmann** [comment]
@mghh Could you please elaborate how you deleted the invalid ipv6 address? Whats steps did you take to solve the problem? I'm currently having a similar problem and tried several steps without success.
The adb log of this phenomenon:
`10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: Connection check at https://keller2.8pzkpdxsetbyyr3f.myfritz.net/nextcloud: Socket exception
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: java.net.ConnectException: failed to connect to keller2.8pzkpdxsetbyyr3f.myfritz.net/2003:75:d33:3e00:9b16:ca5:c861:68eb (port 443) after 50000ms: isConnected failed: EHOSTUNREACH (No route to host)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	at libcore.io.IoBridge.isConnected(IoBridge.java:234)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	at libcore.io.IoBridge.connect(IoBridge.java:122)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	at java.net.Socket.connect(Socket.java:884)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	at com.owncloud.android.lib.common.network.AdvancedSslSocketFactory.createSocket(AdvancedSslSocketFactory.java:184)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:221)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:191)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	at com.owncloud.android.lib.resources.status.GetRemoteStatusOperation.tryConnection(GetRemoteStatusOperation.java:87)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	at com.owncloud.android.lib.resources.status.GetRemoteStatusOperation.run(GetRemoteStatusOperation.java:184)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	at com.owncloud.android.operations.GetServerInfoOperation.run(GetServerInfoOperation.java:82)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	at com.owncloud.android.services.OperationsService$ServiceHandler.nextOperation(OperationsService.java:477)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	at com.owncloud.android.services.OperationsService$ServiceHandler.handleMessage(OperationsService.java:413)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	at android.os.Looper.loop(Looper.java:152)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	at android.os.HandlerThread.run(HandlerThread.java:61)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: Caused by: android.system.ErrnoException: isConnected failed: EHOSTUNREACH (No route to host)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	at libcore.io.IoBridge.isConnected(IoBridge.java:223)
10-26 18:22:02.659  7941  9704 E GetRemoteStatusOperation: 	... 24 more`

**Comment by xXSTrikeXx** [comment]
Delete ipv6 address for your server ;)

**Comment by dartmann** [comment]
@xXSTrikeXx thanks for you fast response. I already tried that, by deactivating ipv6 via grub boot flag. Unfortuantely, that did not solve the problem.

**Comment by mghh** [comment]
@dartmann 

I had to remove the nameserver entry (AAAA record) for my domain at my service provider. This will take some time for other nameservers to catch the change.

**Comment by dartmann** [comment]
@mghh thanks for your reply. Atm I'm quite unsure how I could solve this in my case 😅. My problem is that I am using the dynamic DNS service of AVM ([MyFRITZ!](https://en.avm.de/service/myfritz/faqs/)) to make my nextcloud instance available in the internet. And I am not aware, how I could edit/delete their nameserver entries.
Maybe I get an inspiration or someone gives me an hint, how to solve the issue 😉.

**Comment by dartmann** [comment]
@xXSTrikeXx thanks a lot for that! I'll try it this evening 👍

**Comment by dartmann** [comment]
Ok, deactivating the IPv6 forwarding solved the problem.
But nevertheless, the nextcloud android client was the only one which had this problem.

**Comment by dartmann** [comment]
Ok, deactivating the IPv6 forwarding solved the problem, for exactly one try 🙈. I've no idea how and why, but after deactivation I could connect once with my account. I saw my list of files and after a minute any further sync failed. So currently I am where I was at the beginning of this issue...
Neither apache nor nextcloud logs gave me any informations about this.

Btw, is this even the correct place to discuss my problems? Because this issue was created by @mghh originally to create an enhancement. Just give me a hint if so and where I would be adviced better in getting some support (e.g. the nextcloud forum?) and I will end blowing up this issue with my posts, thanks.
