### ISSUE TITLE
InstantUploaded photos not moved

### ISSUE THREAD

**Issue by benoiton** [nextcloud/android#1721]
### Actual behaviour
1. I set my photo directory of instant upload (/storage/3230-3861/DCIM/Camera). Destination is "/DCIM". Original file to be moved.
2. I take a picture
3. The file is uploaded
4. The file remains in the photo directory

### Expected behaviour
- After upload, the file should be moved to /sdcard/Android/data/com.nextcloud.client/files/nextcloud/benoit@cloud4.friry.net/DCIM
 
### Environment data
 - Android version: 7.1.2
 - Device model: herolte
 - Stock or customized system: LineageOS 14.1-20171017
 - Nextcloud app version: 2.0.1
 - Nextcloud server version: 12.0.2

#### Logcat
```
10-29 12:19:15.506 24340 29392 D ChunkedUploadRemoteFileOperation: Upload of /storage/emulated/0/Android/data/com.nextcloud.client/files/nextcloud/tmp/benoit@cloud4.friry.net/DCIM//IMG_20171029_121909.jpg to /DCIM//IMG_20171029_121909.jpg, chunk index 3, count 6, HTTP result status 201
10-29 12:19:15.509 24340 29392 D OwnCloudClient #0: REQUEST PUT /remote.php/webdav/DCIM//IMG_20171029_121909.jpg-chunking-824693506-6-4
10-29 12:19:15.840 24340 29392 D ChunkedUploadRemoteFileOperation: Upload of /storage/emulated/0/Android/data/com.nextcloud.client/files/nextcloud/tmp/benoit@cloud4.friry.net/DCIM//IMG_20171029_121909.jpg to /DCIM//IMG_20171029_121909.jpg, chunk index 4, count 6, HTTP result status 201
10-29 12:19:15.841 24340 29392 D OwnCloudClient #0: REQUEST PUT /remote.php/webdav/DCIM//IMG_20171029_121909.jpg-chunking-824693506-6-5
10-29 12:19:15.995 16690 16812 W ConnectivityExtension: ConnectivityExt jar file not present
10-29 12:19:17.656 24340 29392 D ChunkedUploadRemoteFileOperation: Upload of /storage/emulated/0/Android/data/com.nextcloud.client/files/nextcloud/tmp/benoit@cloud4.friry.net/DCIM//IMG_20171029_121909.jpg to /DCIM//IMG_20171029_121909.jpg, chunk index 5, count 6, HTTP result status 201
10-29 12:19:17.658 24340 29392 I UploadFileOperation: Upload of /storage/3230-3861/DCIM/Camera/IMG_20171029_121909.jpg to /DCIM//IMG_20171029_121909.jpg: Operation finished with HTTP status code 201 (success)
10-29 12:19:17.659 24340 29392 W System.err: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.nextcloud.client/files/nextcloud/tmp/benoit@cloud4.friry.net/DCIM/IMG_20171029_121909.jpg (No such file or directory)
10-29 12:19:17.660 24340 29392 W System.err:    at java.io.FileInputStream.open(Native Method)
10-29 12:19:17.660 24340 29392 W System.err:    at java.io.FileInputStream.<init>(FileInputStream.java:146)
10-29 12:19:17.660 24340 29392 W System.err:    at com.owncloud.android.operations.UploadFileOperation.move(UploadFileOperation.java:847)
10-29 12:19:17.660 24340 29392 W System.err:    at com.owncloud.android.operations.UploadFileOperation.run(UploadFileOperation.java:564)
10-29 12:19:17.660 24340 29392 W System.err:    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136)
10-29 12:19:17.660 24340 29392 W System.err:    at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:93)
10-29 12:19:17.660 24340 29392 W System.err:    at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:1039)
10-29 12:19:17.661 24340 29392 W System.err:    at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:982)
10-29 12:19:17.661 24340 29392 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:102)
10-29 12:19:17.661 24340 29392 W System.err:    at android.os.Looper.loop(Looper.java:154)
10-29 12:19:17.661 24340 29392 W System.err:    at android.os.HandlerThread.run(HandlerThread.java:61)
10-29 12:19:17.668 24340 29392 D OwnCloudClient #0: REQUEST PROPFIND /remote.php/webdav/DCIM//IMG_20171029_121909.jpg
10-29 12:19:17.795 24340 29392 D FileDataStorageManager: Number of files updated with CONFLICT: 1
10-29 12:19:17.795 24340 29392 D FileDataStorageManager: checking parents to remove conflict; STARTING with /DCIM//
10-29 12:19:17.803 24340 29392 D FileDataStorageManager: NO MORE conflicts in /DCIM//
10-29 12:19:17.813 24340 29392 D FileDataStorageManager: checking parents to remove conflict; NEXT /DCIM/
10-29 12:19:17.821 24340 29392 D FileDataStorageManager: NO MORE conflicts in /DCIM/
10-29 12:19:17.838 24340 29392 D FileDataStorageManager: checking parents to remove conflict; NEXT /
10-29 12:19:17.846 24340 29392 D FileDataStorageManager: NO MORE conflicts in /
10-29 12:19:17.863 24340 29392 D FileDataStorageManager: checking parents to remove conflict; NEXT 
10-29 12:19:17.869 24340 29392 D UploadsStorageManager: updateDatabaseUploadResult uploadResult: com.owncloud.android.lib.common.operations.RemoteOperationResult@6e87f17 upload: com.owncloud.android.operations.UploadFileOperation@a814f04
10-29 12:19:17.876 26757 26757 D MediaScannerReceiver: action: android.intent.action.MEDIA_SCANNER_SCAN_FILE path: /storage/emulated/0/Android/data/com.nextcloud.client/files/nextcloud/benoit@cloud4.friry.net/DCIM/IMG_20171029_121909.jpg
10-29 12:19:17.877 24340 29858 D skia    : --- SkAndroidCodec::NewFromStream returned null
10-29 12:19:17.877 24340 29392 V UploadsStorageManager: Updating /storage/3230-3861/DCIM/Camera/IMG_20171029_121909.jpg with status:UPLOAD_SUCCEEDED and result:UPLOADED (old:/storage/3230-3861/DCIM/Camera/IMG_20171029_121909.jpg status:UPLOAD_IN_PROGRESS result:-1)
10-29 12:19:17.878 24340 29858 D skia    : --- SkAndroidCodec::NewFromStream returned null
10-29 12:19:17.878 24340 29392 V UploadsStorageManager: Updating /storage/emulated/0/Android/data/com.nextcloud.client/files/nextcloud/benoit@cloud4.friry.net/DCIM/IMG_20171029_121909.jpg with status=UPLOAD_SUCCEEDED
10-29 12:19:17.893 24340 29392 D UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/Android/data/com.nextcloud.client/files/nextcloud/benoit@cloud4.friry.net/DCIM/IMG_20171029_121909.jpg
10-29 12:19:17.894 24340 29392 D UploadsStorageManager: notifyObserversNow
10-29 12:19:17.895 24340 29392 D FileUploader: NotifyUploadResult with resultCode: OK
10-29 12:19:17.909 24340 29392 D FileUploader: Stopping command after id 2
10-29 12:19:17.999 26757 26757 D MediaScannerReceiver: action: android.intent.action.MEDIA_SCANNER_SCAN_FILE path: /storage/emulated/0/Android/data/com.nextcloud.client/files/nextcloud/benoit@cloud4.friry.net/DCIM/IMG_20171029_121909.jpg
```

**Comment by tobiasKaminsky** [comment]
There are known problems if the camera storage is external (sdcard).
As it does not affect all devices this is harder to fix.

Can you try switching your camera storage to internal?

**Comment by benoiton** [comment]
It indeed works when camera storage is set to internal sd.
