### ISSUE TITLE
Open image crash

### ISSUE THREAD

**Issue by joshuaavalon** [nextcloud/android#1728]
### Actual behaviour
1. Open a folder that contains images.
2. Open an image and it downloads and shows the image. (It now has a green tick on the thumbnail.)
3. Reopen the folder.
4. Open the downloaded image and it shows white screen.
5 Open an image in the same folder, the app crashes. (See the error log below)
6. Open an image in the different folder (Same as 2)

P.S. the folders are on external storage on local folder. I don't know if it is the problem.
### Expected behaviour
Not Crash
 
### Steps to reproduce
See Actual behaviour

### Environment data
Android version:
8

Device model: 
Pixel

Stock or customized system:
Stock

Nextcloud app version:
2.0.0

Nextcloud server version:
12.0.3

#### Android error log
```
Process: com.nextcloud.client, PID: 26027
   java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
       at java.util.Vector.get(Vector.java:748)
       at com.owncloud.android.ui.preview.PreviewImagePagerAdapter.getFileAt(PreviewImagePagerAdapter.java:135)
       at com.owncloud.android.ui.preview.PreviewImageActivity.onPageSelected(PreviewImageActivity.java:354)
       at com.owncloud.android.ui.preview.PreviewImageActivity$PreviewImageServiceConnection.onServiceConnected(PreviewImageActivity.java:221)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1634)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1663)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6541)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by alexanderdd** [comment]
App version 2.0.1
Android 4.4.2 
I dont know where to find error logs. 

Similar problem. App opens a few pictures just fine, but after opening 3 or 4 it crashes. I can reproduce, reload app and go to a few folders, open a few pictures, it will crash again and again.
I never saw the picture displayed white as described above.

Just some background: I was on 1.4.1 and things worked great. I tried 1.4.2 and 2.0.0 and 2.0.1 and they crash all the time and are not usable for production.

**Comment by tobiasKaminsky** [comment]
@alexanderdd do you also use external folders?

**Comment by alexanderdd** [comment]
No. 
I just tried again, and the app crashed when trying to open the third picture.
Tell me what you need to fix this please.

**Comment by tobiasKaminsky** [comment]
As this does not happen on our test/productive server, maybe you can try if this also happens with a new user and/or new device?
If this still happens on your server, please provide us a test account and send the credentials to android at nextcloud dot com with a reference to this issue.

**Comment by joshuaavalon** [comment]
@tapanprakasht I am using [docker from LinuxServer.io](https://hub.docker.com/r/linuxserver/nextcloud/). The external storage is only volume passed to the docker.

**Comment by joshuaavalon** [comment]
I did some more testing. The problem seems to be fixed. But the files left behind caused the crash even I uninstall and clear cache. I also remove the left behind (nextcloud folder on the storage) and refresh in the app to fix it. I can no longer reproduce the problem.

**Comment by tobiasKaminsky** [comment]
Glad to hear, but still strange that it occurs in the first time and seems to be related to specific files...
