### ISSUE TITLE
NPE in current Version

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#174]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getName()' on a null object reference
	at com.owncloud.android.ui.adapter.LocalFileListAdapter.getView(LocalFileListAdapter.java:113)
	at android.widget.AbsListView.obtainView(AbsListView.java:2347)
	at android.widget.ListView.makeAndAddView(ListView.java:1864)
	at android.widget.ListView.fillSpecific(ListView.java:1344)
	at android.widget.ListView.layoutChildren(ListView.java:1651)
	at android.widget.AbsListView.onLayout(AbsListView.java:2151)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:596)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2116)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1873)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1084)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5990)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5343)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by tobiasKaminsky** [comment]
Happens when accessing an empty folder.
Fix is coming soon.

**Comment by tobiasKaminsky** [comment]
PR: #180

**Comment by AndyScherzinger** [comment]
merged: 1.3.0
