### ISSUE TITLE
Local path must be an absolute path in the local file system

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#175]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.UploadListActivity}: java.lang.IllegalArgumentException: Local path must be an absolute path in the local file system
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2464)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524)
    at android.app.ActivityThread.access$900(ActivityThread.java:154)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:234)
    at android.app.ActivityThread.main(ActivityThread.java:5526)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IllegalArgumentException: Local path must be an absolute path in the local file system
    at com.owncloud.android.db.OCUpload.<init>(OCUpload.java:114)
    at com.owncloud.android.datamodel.UploadsStorageManager.createOCUploadFromCursor(UploadsStorageManager.java:342)
    at com.owncloud.android.datamodel.UploadsStorageManager.getUploads(UploadsStorageManager.java:321)
    at com.owncloud.android.datamodel.UploadsStorageManager.getFinishedUploads(UploadsStorageManager.java:384)
    at com.owncloud.android.ui.adapter.ExpandableUploadListAdapter$3.refresh(ExpandableUploadListAdapter.java:166)
    at com.owncloud.android.ui.adapter.ExpandableUploadListAdapter.loadUploadItemsFromDb(ExpandableUploadListAdapter.java:605)
    at com.owncloud.android.ui.adapter.ExpandableUploadListAdapter.<init>(ExpandableUploadListAdapter.java:176)
    at com.owncloud.android.ui.fragment.UploadListFragment.onStart(UploadListFragment.java:102)
    at android.support.v4.app.Fragment.performStart(Fragment.java:2000)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1102)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
    at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2051)
    at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:185)
    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
    at com.owncloud.android.ui.activity.BaseActivity.onStart(BaseActivity.java:186)
    at com.owncloud.android.ui.activity.FileActivity.onStart(FileActivity.java:181)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
    at android.app.Activity.performStart(Activity.java:6302)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2427)
    ... 9 more

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky postpone this one to 1.4.0 or possibly 1.3.1 or a later RC of 1.3.0 ?

**Comment by tobiasKaminsky** [comment]
Postpone as I do not know how it occurs.

**Comment by kollix** [comment]
I have this crash now on 1.4.0, Android 6.0.1
I have added a LOT files for upload (hundreds, or probably even > 1000).
It crashes always when trying to view the upload list

Just to be sure, here is the backtrace:
01-06 15:22:36.588 E/AndroidRuntime(16179): FATAL EXCEPTION: main
01-06 15:22:36.588 E/AndroidRuntime(16179): Process: com.nextcloud.client, PID: 16179
01-06 15:22:36.588 E/AndroidRuntime(16179): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.UploadListActivity}: java.lang.IllegalArgumentException: Local path must be an absolute path in the local file system
01-06 15:22:36.588 E/AndroidRuntime(16179):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at android.app.ActivityThread.access$1100(ActivityThread.java:221)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at android.os.Handler.dispatchMessage(Handler.java:102)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at android.os.Looper.loop(Looper.java:158)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at android.app.ActivityThread.main(ActivityThread.java:7224)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at java.lang.reflect.Method.invoke(Native Method)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
01-06 15:22:36.588 E/AndroidRuntime(16179): Caused by: java.lang.IllegalArgumentException: Local path must be an absolute path in the local file system
01-06 15:22:36.588 E/AndroidRuntime(16179):     at com.owncloud.android.db.OCUpload.<init>(OCUpload.java:114)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at com.owncloud.android.datamodel.UploadsStorageManager.createOCUploadFromCursor(UploadsStorageManager.java:343)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at com.owncloud.android.datamodel.UploadsStorageManager.getUploads(UploadsStorageManager.java:322)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at com.owncloud.android.datamodel.UploadsStorageManager.getFinishedUploads(UploadsStorageManager.java:386)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at com.owncloud.android.ui.adapter.ExpandableUploadListAdapter$3.refresh(ExpandableUploadListAdapter.java:169)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at com.owncloud.android.ui.adapter.ExpandableUploadListAdapter.loadUploadItemsFromDb(ExpandableUploadListAdapter.java:616)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at com.owncloud.android.ui.adapter.ExpandableUploadListAdapter.<init>(ExpandableUploadListAdapter.java:179)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at com.owncloud.android.ui.fragment.UploadListFragment.onStart(UploadListFragment.java:102)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at android.support.v4.app.Fragment.performStart(Fragment.java:2106)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1146)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1272)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2154)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:212)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:610)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at com.owncloud.android.ui.activity.BaseActivity.onStart(BaseActivity.java:189)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at com.owncloud.android.ui.activity.FileActivity.onStart(FileActivity.java:181)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1265)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at android.app.Activity.performStart(Activity.java:6915)
01-06 15:22:36.588 E/AndroidRuntime(16179):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3216)
01-06 15:22:36.588 E/AndroidRuntime(16179):     ... 9 more
01-06 15:22:36.588 W/ActivityManager(23272):   Force finishing activity com.nextcloud.client/com.owncloud.android.ui.activity.UploadListActivity

**Comment by kollix** [comment]
I think it has to do with the external SD card (which is selected as location) was full. I manually removed files to make room and now the client does no longer show this crash

**Comment by tobiasKaminsky** [comment]
Glad to hear what was the cause of the problem @kollix 
So closing for now.
