### ISSUE TITLE
NullPointerException in UploadFinishReceiver (reason unknown) via Play Store Console

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#18]
**App Version 1.0.0** 

**Android version**
    Android 5.01

**Device**
    ZenFone 2 (ZE551ML) (Z00A)

```
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.files.services.FileUploaderUPLOAD_FINISH flg=0x10 (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$UploadFinishReceiver@12b4375c
    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:874)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5264)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.ui.activity.FileDisplayActivity$UploadFinishReceiver.onReceive(FileDisplayActivity.java:1075)
    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:864)
    ... 8 more
```

**Comment by bes1002t** [comment]
Is this a reproducable bug and is this still a problem?

**Comment by AndyScherzinger** [comment]
not reported in actual 1.4.1 stable, thus closing it.
