### ISSUE TITLE
"Photos" item does not display anything

### ISSUE THREAD

**Issue by egothor** [nextcloud/android#1892]
### Actual behaviour
Folder "Photos" under "All files" (left menu bar selection) shows several jpeg images in the list.

"Photos" (left menu bar selection) does not display anything, the application waits forever.

Android app runs with cs-CZ locale, so the menu items are "Vsechny soubory"/"All Files" and "Fotky"/"Photos". Server-side homedir includes "Photos" folder (dirname was not translated by the user or server).

### Expected behaviour
The application does not wait for server data and (hopefully) displays something relevant.
 
### Steps to reproduce
1. Open nextcloud app on android
2. Open left menu
3. Touch "Photos" item (left menu, 4th item)
4. Application waits for some data and nothing comes

### Environment data
Android version: 7.1.2

Device model: not relevant

Stock or customized system: not relevant

Nextcloud app version: 2.0.1

Nextcloud server version: 12.0.4 - 12.0.4.3

#### Web server error log
```
192.168.0.67 - user [25/Dec/2017:15:23:27 +0100] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 428
192.168.0.67 - user [25/Dec/2017:15:23:27 +0100] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 428
192.168.0.67 - user [25/Dec/2017:15:23:27 +0100] "OPTIONS /remote.php/dav HTTP/1.1" 200 -
192.168.0.67 - user [25/Dec/2017:15:23:27 +0100] "OPTIONS /remote.php/dav HTTP/1.1" 200 -
192.168.0.67 - user [25/Dec/2017:15:23:27 +0100] "SEARCH /remote.php/dav HTTP/1.1" 404 230
192.168.0.67 - user [25/Dec/2017:15:23:27 +0100] "SEARCH /remote.php/dav HTTP/1.1" 404 230
192.168.0.67 - user [25/Dec/2017:15:23:27 +0100] "GET /status.php HTTP/1.1" 200 146
192.168.0.67 - user [25/Dec/2017:15:23:27 +0100] "GET /ocs/v1.php/cloud/capabilities?format=json HTTP/1.1" 200 1567
192.168.0.67 - user [25/Dec/2017:15:23:28 +0100] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 428
192.168.0.67 - user [25/Dec/2017:15:23:28 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 760
192.168.0.67 - user [25/Dec/2017:15:23:28 +0100] "GET /ocs/v2.php/apps/files_sharing/api/v1/shares?path=%2F&reshares=true&subfiles=true HTTP/1.1" 200 138

```

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"REMOVED","level":0,"time":"2017-12-25T14:23:27+00:00","remoteAddr":"192.168.0.67","user":"REMOVED","app":"webdav","method":"SEARCH","url":"\/remote.php\/dav","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Message\":\"Principal with name user not found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(76): Sabre\\\\DAVACL\\\\AbstractPrincipalCollection->getChild('user')\\n#1 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Files\\\/FileSearchBackend.php(148): Sabre\\\\DAV\\\\Tree->getNodeForPath('files\\\/user')\\n#2 \\\/var\\\/www\\\/html\\\/3rdparty\\\/icewind\\\/searchdav\\\/src\\\/DAV\\\/SearchHandler.php(75): OCA\\\\DAV\\\\Files\\\\FileSearchBackend->search(Object(SearchDAV\\\\XML\\\\BasicSearch))\\n#3 \\\/var\\\/www\\\/html\\\/3rdparty\\\/icewind\\\/searchdav\\\/src\\\/DAV\\\/SearchPlugin.php(123): SearchDAV\\\\DAV\\\\SearchHandler->handleSearchRequest(Array, Object(Sabre\\\\HTTP\\\\Response))\\n#4 [internal function]: SearchDAV\\\\DAV\\\\SearchPlugin->searchHandler(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:SEARCH', Array)\\n#7 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Server.php(258): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(33): OCA\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/html\\\/remote.php(162): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAVACL\\\/AbstractPrincipalCollection.php\",\"Line\":118}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/2.0.1","version":"12.0.4.3"}
{"reqId":"REMOVED","level":0,"time":"2017-12-25T14:23:27+00:00","remoteAddr":"192.168.0.67","user":"REMOVED","app":"webdav","method":"SEARCH","url":"\/remote.php\/dav","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Message\":\"Principal with name user not found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(76): Sabre\\\\DAVACL\\\\AbstractPrincipalCollection->getChild('user')\\n#1 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Files\\\/FileSearchBackend.php(148): Sabre\\\\DAV\\\\Tree->getNodeForPath('files\\\/user')\\n#2 \\\/var\\\/www\\\/html\\\/3rdparty\\\/icewind\\\/searchdav\\\/src\\\/DAV\\\/SearchHandler.php(75): OCA\\\\DAV\\\\Files\\\\FileSearchBackend->search(Object(SearchDAV\\\\XML\\\\BasicSearch))\\n#3 \\\/var\\\/www\\\/html\\\/3rdparty\\\/icewind\\\/searchdav\\\/src\\\/DAV\\\/SearchPlugin.php(123): SearchDAV\\\\DAV\\\\SearchHandler->handleSearchRequest(Array, Object(Sabre\\\\HTTP\\\\Response))\\n#4 [internal function]: SearchDAV\\\\DAV\\\\SearchPlugin->searchHandler(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:SEARCH', Array)\\n#7 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Server.php(258): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(33): OCA\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/html\\\/remote.php(162): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAVACL\\\/AbstractPrincipalCollection.php\",\"Line\":118}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/2.0.1","version":"12.0.4.3"}
```

**Comment by standin000** [comment]
I have the same issue for ios version. expect it be fixed.

**Comment by tobiasKaminsky** [comment]
iOS has its own tracker: https://github.com/nextcloud/ios
On android we are currently working on it and it will be in next version.
