### ISSUE TITLE
DEV-20171230 Send/Share crashes from within preview

### ISSUE THREAD

**Issue by rullzer** [nextcloud/android#1918]
1. Open an image
2. Open menu
3. Click Send/Share
4. :boom:

All works as expected if I click on the share icon in the file list next to the same image.

**Comment by rullzer** [comment]
Trace:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.nextcloud.client, PID: 5910
                  java.lang.ClassCastException: com.owncloud.android.ui.preview.PreviewImageActivity cannot be cast to com.owncloud.android.ui.activity.FileDisplayActivity
                      at com.owncloud.android.ui.preview.PreviewImageFragment.onOptionsItemSelected(PreviewImageFragment.java:425)
                      at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2487)
                      at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:3307)
                      at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:344)
                      at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:374)
                      at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
                      at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
                      at android.support.v7.app.AppCompatDelegateImplV9.onMenuItemSelected(AppCompatDelegateImplV9.java:674)
                      at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
                      at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
                      at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
                      at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
                      at android.widget.AdapterView.performItemClick(AdapterView.java:318)
                      at android.widget.AbsListView.performItemClick(AbsListView.java:1158)
                      at android.widget.AbsListView$PerformClick.run(AbsListView.java:3127)
                      at android.widget.AbsListView$3.run(AbsListView.java:4042)
                      at android.os.Handler.handleCallback(Handler.java:790)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6494)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by maryammsd** [comment]
There is no release version apk file for version 2.1.0. How can I have the apk file with this bug?

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/android/releases
We are already at 3.19.1 and in above link you can find the apk.
