### ISSUE TITLE
IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#198]
### Actual behaviour

-Uploads view crashes
### Expected behaviour

-Uploads view shouldn't crash
### Steps to reproduce
1.  Open the Uploads view in the drawer
### Backround

This bug has been reported several times on the Play developer console.
This bug is present in oC and Nc. 
Research shows it is likely related to a wrongly implemented comparator and Android's swicth to JDK 7 which leads to Array.sort using a different algorithm: https://dertompson.com/2012/11/23/sort-algorithm-changes-in-java-7/
### Environment data

Android version: 5,6,etc.

Device model: Nexus5X amoung others

Stock or customized system: stock

Nextcloud app version: 1.2.0
#### Nextcloud log (data/nextcloud.log)

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.UploadListActivity}: java.lang.IllegalArgumentException: Comparison method violates its general contract!
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5422)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
    at java.util.TimSort.mergeHi(TimSort.java:882)
    at java.util.TimSort.mergeAt(TimSort.java:499)
    at java.util.TimSort.mergeForceCollapse(TimSort.java:440)
    at java.util.TimSort.sort(TimSort.java:219)
    at java.util.TimSort.sort(TimSort.java:169)
    at java.util.Arrays.sort(Arrays.java:2010)
    at com.owncloud.android.ui.adapter.ExpandableUploadListAdapter$2.refresh(ExpandableUploadListAdapter.java:154)
    at com.owncloud.android.ui.adapter.ExpandableUploadListAdapter.loadUploadItemsFromDb(ExpandableUploadListAdapter.java:605)
    at com.owncloud.android.ui.adapter.ExpandableUploadListAdapter.<init>(ExpandableUploadListAdapter.java:176)
    at com.owncloud.android.ui.fragment.UploadListFragment.onStart(UploadListFragment.java:102)
    at android.support.v4.app.Fragment.performStart(Fragment.java:2000)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1102)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
    at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2051)
    at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:185)
    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
    at com.owncloud.android.ui.activity.BaseActivity.onStart(BaseActivity.java:186)
    at com.owncloud.android.ui.activity.FileActivity.onStart(FileActivity.java:181)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
    at android.app.Activity.performStart(Activity.java:6268)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
    ... 9 more
```

**Comment by AndyScherzinger** [comment]
PR: #199 - please review

**Comment by AndyScherzinger** [comment]
Will be released with 1.3.0

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky we need to reopen this one, the issue still occurs, as seen in the Play developer console for 1.3.1
```
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.files.services.FileUploaderUPLOAD_START flg=0x10 (has extras) } in com.owncloud.android.ui.activity.UploadListActivity$UploadMessagesReceiver@828af4b
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:935)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5525)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:882)
	at java.util.TimSort.mergeAt(TimSort.java:499)
	at java.util.TimSort.mergeForceCollapse(TimSort.java:440)
	at java.util.TimSort.sort(TimSort.java:219)
	at java.util.TimSort.sort(TimSort.java:169)
	at java.util.Arrays.sort(Arrays.java:2010)
	at com.owncloud.android.ui.adapter.ExpandableUploadListAdapter$1.refresh(ExpandableUploadListAdapter.java:143)
	at com.owncloud.android.ui.adapter.ExpandableUploadListAdapter.loadUploadItemsFromDb(ExpandableUploadListAdapter.java:610)
	at com.owncloud.android.ui.adapter.ExpandableUploadListAdapter.refreshView(ExpandableUploadListAdapter.java:625)
	at com.owncloud.android.ui.fragment.UploadListFragment.updateUploads(UploadListFragment.java:148)
	at com.owncloud.android.ui.activity.UploadListActivity$UploadMessagesReceiver.onReceive(UploadListActivity.java:337)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:925)
	... 7 more
```

now labeled high since this leads to crashes.

**Comment by strugee** [comment]
I can reproduce this with Nextcloud Beta 20161224 installed from F-Droid on a Nexus 6P running CyanogenMod 13.0-20161220-SNAPSHOT-ZNH5YAO3XH-angler based on Android 6.0.1.

I _did_ upgrade my CyanogenMod recently. I can't 100% confirm that this crash started occurring after the upgrade, but I _think_ it did. I was previously running the snapshot immediately before the one I'm running now.

I'm happy to provide adb logs, run a debug build, etc. if needed.

**Comment by tobiasKaminsky** [comment]
@strugee happy new year :tada: 

Can you describe when the error occurs?
@AndyScherzinger that it occurs when opening the upload pane.
But which content do you have when it is crashing? (which uploads, are they currently uploading, or only pending...?)

**Comment by strugee** [comment]
@tobiasKaminsky it crashes immediately upon opening the upload pane.

IIRC I have a large amount of failed uploads, though, as well as a lot of successful uploads. And I've seen this with and without running uploads.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky just use "wifi only", deactivate wifi, take for pictures, go to uploads view, the activate wifi, go to uploads view and wait, as soon as a upload start it crashes immediately...
![device-2017-01-04-162604](https://cloud.githubusercontent.com/assets/1315170/21647518/eda8d098-d29a-11e6-9f94-6aad851e523f.png)

**Comment by tobiasKaminsky** [comment]
> just use "wifi only", deactivate wifi, take for pictures, go to uploads view, the activate wifi, go to uploads view and wait, as soon as a upload start it crashes immediately...

I did those steps except with "data on/off" as I am using an emulator, but cannot reproduce it :/

**Comment by AndyScherzinger** [comment]
Couldn't reproduce it anymore with the latest master, so closing it for now for 1.5.0. Let's see if it will get reported for 1.5.0 after the release and then re-open.
