### ISSUE TITLE
NPE in FileUploader.uploadFile

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#200]
Reported several times on the Play store developer console (unfortunately no comments)
 
### Environment data
Android version: 6

Device model: Xperia Z3 Compact (D5803)  / OnePlus One (A0001) 

Stock or customized system: - 

Nextcloud app version: 1.2.0

Nextcloud server version: - 

#### Nextcloud log (data/nextcloud.log)
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.operations.UploadFileOperation.getOriginalStoragePath()' on a null object reference
	at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:960)
	at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:866)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:224)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.operations.UploadFileOperation.getOriginalStoragePath()' on a null object reference
	at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:960)
	at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:866)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by tobiasKaminsky** [comment]
PR: #205

**Comment by AndyScherzinger** [comment]
Will be release with 1.3.0
