### ISSUE TITLE
NPE in ExpandableUploadListAdapter...setText

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#201]
Reported on the Play store developer console (unfortunately no comments)
 
### Environment data
Android version: 6

Device model: Xperia Z3 Compact (D5803) 

Stock or customized system: - 

Nextcloud app version: 1.2.0

Nextcloud server version: - 

#### Nextcloud log (data/nextcloud.log)
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
	at com.owncloud.android.ui.adapter.ExpandableUploadListAdapter.getView(ExpandableUploadListAdapter.java:219)
	at com.owncloud.android.ui.adapter.ExpandableUploadListAdapter.getChildView(ExpandableUploadListAdapter.java:636)
	at android.widget.ExpandableListConnector.getView(ExpandableListConnector.java:451)
	at android.widget.AbsListView.obtainView(AbsListView.java:2346)
	at android.widget.ListView.makeAndAddView(ListView.java:1876)
	at android.widget.ListView.fillDown(ListView.java:702)
	at android.widget.ListView.fillSpecific(ListView.java:1367)
	at android.widget.ListView.layoutChildren(ListView.java:1663)
	at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4556)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:603)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:5526)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by AndyScherzinger** [comment]
Now also being seen in 1.30 RCs this is imho a truely strange case since I cannot under any circumstances.
This is the code fragment:
```
Account account = AccountUtils.getOwnCloudAccountByName(mParentActivity, upload.getAccountName());
accountNameTextView.setText(
        DisplayUtils.getAccountNameDisplayText(
                mParentActivity, account, account.name, upload.getAccountName())
);
```

account is null, which means the account in the upload element isn't available anymore in the account manager, but if I remove an account from the client the upload log items also get removed and thus there is no error...

So my proposal is to just harden this and do a null check with a fallback to the upload.name:
```
Account account = AccountUtils.getOwnCloudAccountByName(mParentActivity, upload.getAccountName());
if(account != null) {
accountNameTextView.setText(
        DisplayUtils.getAccountNameDisplayText(
                mParentActivity, account, account.name, upload.getAccountName())
);
} else {
        accountNameTextView.setText(upload.getAccountName());
}
```

What do you think @tobiasKaminsky ? Would this be feasible in your opinion?

**Comment by AndyScherzinger** [comment]
Latest crash comment

> clickink 'Uploads' in the menu Crashes the App. History of my serup: I used the app with an account A which I deleted and added an other Account B. With B the error appeared.

@tobiasKaminsky what do you think about my proposed solution in the comment above?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky please see opened PR #290
