### ISSUE TITLE
Cannot upload 180MB mp4 (Connection failure)

### ISSUE THREAD

**Issue by miodzicho** [nextcloud/android#2017]
### Actual behaviour
Trying to upload ca. 180MB mp4 file using nextcloud android client, always failing saying Connection failure. Ondev app from f-droid says SSL error, but web upload works just fine (Chrome).

### Expected behaviour
File should be uploaded into SofortUpload on nextcloud server
 
### Steps to reproduce
1. take a video with camera
2.  wait until upload will start

### Environment data
Android version: 7.0.1

Device model: 
Oneplus 5T
Stock or customized system:
Stock OOS
Nextcloud app version:
2.0 official and 2018014-dev
Nextcloud server version:
13 rc2
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by miodzicho** [comment]
![screenshot_20180121-153614](https://user-images.githubusercontent.com/1526145/35195833-089ced50-fec1-11e7-830e-5fb8a8cf0dd2.jpg)
This error about SSL I can see only in dev client

**Comment by miodzicho** [comment]
![screenshot_20180121-154017](https://user-images.githubusercontent.com/1526145/35195853-677f9944-fec1-11e7-84f3-bca586ce2aef.jpg)
SSL problem. Only appears in dev client. Regular one just fails.

**Comment by tobiasKaminsky** [comment]
I assume that some of the chunked upload fails and this is then the error message returned back.
But I cannot say why it fails...

**Comment by miodzicho** [comment]
What I can also add, I have split dns. Same dns name on internal network, and from Internet. And upload only is failing from Internet. Internal was fine. No issues in or out with smaller files, like photos etc.

**Comment by marvinwankersteen** [comment]
I have the same issue:

Output from logcat:
```
03-04 00:24:41.941  5961  5961 D ExpandableUploadListAdapter: refreshView
03-04 00:24:41.941  5961  5961 D ExpandableUploadListAdapter: loadUploadItemsFromDb
03-04 00:24:41.968  5961  5961 D FileUploader: Starting command with id 61
03-04 00:24:41.972  5961  5961 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/VID_20180303_165949.mp4 with status=UPLOAD_IN_PROGRESS
03-04 00:24:42.060  5961  5961 D UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/VID_20180303_165949.mp4
03-04 00:24:42.060  5961  5961 D UploadsStorageManager: notifyObserversNow
03-04 00:24:42.062  5961  7115 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/VID_20180303_165949.mp4 with status:UPLOAD_IN_PROGRESS and result:UNKNOWN (old:/storage/emulated/0/DCIM/Camera/VID_20180303_165949.mp4 status:UPLOAD_IN_PROGRESS result:-1)
03-04 00:24:42.062  5961  7115 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/VID_20180303_165949.mp4 with status=UPLOAD_IN_PROGRESS
03-04 00:24:42.073  5961  7115 D UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/VID_20180303_165949.mp4
03-04 00:24:42.073  5961  7115 D UploadsStorageManager: notifyObserversNow
03-04 00:24:42.082  5961  7115 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/VID_20180303_165949.mp4 with status=UPLOAD_IN_PROGRESS
03-04 00:24:42.100  5961  7115 D UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/VID_20180303_165949.mp4
03-04 00:24:42.100  5961  7115 D UploadsStorageManager: notifyObserversNow
03-04 00:24:42.104  5961  7115 D OwnCloudClient #0: REQUEST HEAD /remote.php/webdav/Videos/Handy/Kamera/2018/03/
03-04 00:24:42.104  5961  7115 D AdvancedSslSocketFactory: Creating SSL Socket with remote cloud.<domain>.<tld>:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@8ddb302
03-04 00:24:42.104  5961  7115 D AdvancedSslSocketFactory:  ... with connection timeout 50000 and socket timeout 60000
03-04 00:24:42.109  5961  5961 D ExpandableUploadListAdapter: refreshView
03-04 00:24:42.109  5961  5961 D ExpandableUploadListAdapter: loadUploadItemsFromDb
03-04 00:24:42.142  5961  5961 D ExpandableUploadListAdapter: refreshView
03-04 00:24:42.142  5961  5961 D ExpandableUploadListAdapter: loadUploadItemsFromDb
03-04 00:24:42.177  5961  7115 I ServerNameIndicator: SSLSocket implementation: com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket
03-04 00:24:42.177  5961  7115 I ServerNameIndicator: SNI done, hostname: cloud.<domain>.<tld>
03-04 00:24:42.295  5961  7115 D ExistenceCheckRemoteOperation: Existence check for https://cloud.<domain>.<tld>/remote.php/webdav/Videos/Handy/Kamera/2018/03/ targeting for  existence finished with HTTP status 200
03-04 00:24:42.317  5961  7115 D UploadFileOperation: normal upload
03-04 00:24:42.319  5961  7115 D OwnCloudClient #132: Creating OwnCloudClient
03-04 00:24:42.320  5961  7115 D AccountUtils: Restoring cookies for marco@cloud.<domain>.<tld>
03-04 00:24:42.321  5961  7115 D OwnCloudClient #132: REQUEST GET /index.php/204
03-04 00:24:44.472  5961  7115 D UploadFileOperation: Checking name collision in server
03-04 00:24:44.490  5961  7115 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/VID_20180303_165949.mp4 with status=UPLOAD_IN_PROGRESS
03-04 00:24:44.519  5961  7115 D UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/VID_20180303_165949.mp4
03-04 00:24:44.520  5961  7115 D UploadsStorageManager: notifyObserversNow
03-04 00:24:44.523  5961  7115 D OwnCloudClient #0: REQUEST PUT /remote.php/webdav/Videos/Handy/Kamera//2018/03/VID_20180303_165949.mp4-chunking-1829038743-154-0
03-04 00:24:46.839  5961  7115 D ChunkedUploadRemoteFileOperation: Upload of /storage/emulated/0/DCIM/Camera/VID_20180303_165949.mp4 to /Videos/Handy/Kamera//2018/03/VID_20180303_165949.mp4, chunk index 0, count 154, HTTP result status 201
03-04 00:24:46.840  5961  7115 D OwnCloudClient #0: REQUEST PUT /remote.php/webdav/Videos/Handy/Kamera//2018/03/VID_20180303_165949.mp4-chunking-1829038743-154-1
03-04 00:24:48.871  5961  7115 D ChunkedUploadRemoteFileOperation: Upload of /storage/emulated/0/DCIM/Camera/VID_20180303_165949.mp4 to /Videos/Handy/Kamera//2018/03/VID_20180303_165949.mp4, chunk index 1, count 154, HTTP result status 201
03-04 00:24:48.873  5961  7115 D OwnCloudClient #0: REQUEST PUT /remote.php/webdav/Videos/Handy/Kamera//2018/03/VID_20180303_165949.mp4-chunking-1829038743-154-2
03-04 00:24:51.248  5961  7115 D ChunkedUploadRemoteFileOperation: Upload of /storage/emulated/0/DCIM/Camera/VID_20180303_165949.mp4 to /Videos/Handy/Kamera//2018/03/VID_20180303_165949.mp4, chunk index 2, count 154, HTTP result status 201
03-04 00:24:51.250  5961  7115 D OwnCloudClient #0: REQUEST PUT /remote.php/webdav/Videos/Handy/Kamera//2018/03/VID_20180303_165949.mp4-chunking-1829038743-154-3
03-04 00:24:53.224  5961  7115 D ChunkedUploadRemoteFileOperation: Upload of /storage/emulated/0/DCIM/Camera/VID_20180303_165949.mp4 to /Videos/Handy/Kamera//2018/03/VID_20180303_165949.mp4, chunk index 3, count 154, HTTP result status 201
03-04 00:24:53.226  5961  7115 D OwnCloudClient #0: REQUEST PUT /remote.php/webdav/Videos/Handy/Kamera//2018/03/VID_20180303_165949.mp4-chunking-1829038743-154-4
03-04 00:24:55.153  5961  7115 D ChunkedUploadRemoteFileOperation: Upload of /storage/emulated/0/DCIM/Camera/VID_20180303_165949.mp4 to /Videos/Handy/Kamera//2018/03/VID_20180303_165949.mp4, chunk index 4, count 154, HTTP result status 201
03-04 00:24:55.154  5961  7115 D OwnCloudClient #0: REQUEST PUT /remote.php/webdav/Videos/Handy/Kamera//2018/03/VID_20180303_165949.mp4-chunking-1829038743-154-5
03-04 00:24:57.474  5961  7115 D ChunkedUploadRemoteFileOperation: Upload of /storage/emulated/0/DCIM/Camera/VID_20180303_165949.mp4 to /Videos/Handy/Kamera//2018/03/VID_20180303_165949.mp4, chunk index 5, count 154, HTTP result status 201
03-04 00:24:57.475  5961  7115 D OwnCloudClient #0: REQUEST PUT /remote.php/webdav/Videos/Handy/Kamera//2018/03/VID_20180303_165949.mp4-chunking-1829038743-154-6
03-04 00:24:59.377  5961  7115 D ChunkedUploadRemoteFileOperation: Upload of /storage/emulated/0/DCIM/Camera/VID_20180303_165949.mp4 to /Videos/Handy/Kamera//2018/03/VID_20180303_165949.mp4, chunk index 6, count 154, HTTP result status 201
03-04 00:24:59.378  5961  7115 D OwnCloudClient #0: REQUEST PUT /remote.php/webdav/Videos/Handy/Kamera//2018/03/VID_20180303_165949.mp4-chunking-1829038743-154-7
03-04 00:25:01.710  5961  7115 D ChunkedUploadRemoteFileOperation: Upload of /storage/emulated/0/DCIM/Camera/VID_20180303_165949.mp4 to /Videos/Handy/Kamera//2018/03/VID_20180303_165949.mp4, chunk index 7, count 154, HTTP result status 201
03-04 00:25:01.712  5961  7115 D OwnCloudClient #0: REQUEST PUT /remote.php/webdav/Videos/Handy/Kamera//2018/03/VID_20180303_165949.mp4-chunking-1829038743-154-8
03-04 00:25:03.536  5961  7115 D ChunkedUploadRemoteFileOperation: Upload of /storage/emulated/0/DCIM/Camera/VID_20180303_165949.mp4 to /Videos/Handy/Kamera//2018/03/VID_20180303_165949.mp4, chunk index 8, count 154, HTTP result status 201
03-04 00:25:03.539  5961  7115 D OwnCloudClient #0: REQUEST PUT /remote.php/webdav/Videos/Handy/Kamera//2018/03/VID_20180303_165949.mp4-chunking-1829038743-154-9
03-04 00:25:05.387  5961  7115 D ChunkedUploadRemoteFileOperation: Upload of /storage/emulated/0/DCIM/Camera/VID_20180303_165949.mp4 to /Videos/Handy/Kamera//2018/03/VID_20180303_165949.mp4, chunk index 9, count 154, HTTP result status 201
03-04 00:25:05.389  5961  7115 D OwnCloudClient #0: REQUEST PUT /remote.php/webdav/Videos/Handy/Kamera//2018/03/VID_20180303_165949.mp4-chunking-1829038743-154-10
03-04 00:25:07.670  5961  7115 D ChunkedUploadRemoteFileOperation: Upload of /storage/emulated/0/DCIM/Camera/VID_20180303_165949.mp4 to /Videos/Handy/Kamera//2018/03/VID_20180303_165949.mp4, chunk index 10, count 154, HTTP result status 201
03-04 00:25:07.671  5961  7115 D OwnCloudClient #0: REQUEST PUT /remote.php/webdav/Videos/Handy/Kamera//2018/03/VID_20180303_165949.mp4-chunking-1829038743-154-11
03-04 00:25:09.330  5961  7115 V NativeCrypto: Read error: ssl=0x7f5da8d148: Failure in SSL library, usually a protocol error
03-04 00:25:09.330  5961  7115 V NativeCrypto: error:100003fc:SSL routines:OPENSSL_internal:SSLV3_ALERT_BAD_RECORD_MAC (third_party/openssl/boringssl/src/ssl/tls_record.cc:562 0x7f60682d28:0x00000001)
03-04 00:25:09.330  5961  7115 V NativeCrypto: SSL shutdown failed: ssl=0x7f5da8d148: I/O error during system call, Connection reset by peer
03-04 00:25:09.332  5961  7115 E UploadFileOperation: Upload of /storage/emulated/0/DCIM/Camera/VID_20180303_165949.mp4 to /Videos/Handy/Kamera//2018/03/VID_20180303_165949.mp4: SSL exception
03-04 00:25:09.332  5961  7115 E UploadFileOperation: javax.net.ssl.SSLProtocolException: Read error: ssl=0x7f5da8d148: Failure in SSL library, usually a protocol error
03-04 00:25:09.332  5961  7115 E UploadFileOperation: error:100003fc:SSL routines:OPENSSL_internal:SSLV3_ALERT_BAD_RECORD_MAC (third_party/openssl/boringssl/src/ssl/tls_record.cc:562 0x7f60682d28:0x00000001)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_read(Native Method)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at com.google.android.gms.org.conscrypt.SslWrapper.read(:com.google.android.gms@11975440)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(:com.google.android.gms@11975440:7)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.readLine(MultiThreadedHttpConnectionManager.java:1413)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:1973)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1735)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:232)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at com.owncloud.android.lib.resources.files.ChunkedUploadRemoteFileOperation.uploadFile(ChunkedUploadRemoteFileOperation.java:116)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at com.owncloud.android.lib.resources.files.UploadRemoteFileOperation.run(UploadRemoteFileOperation.java:110)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:145)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at com.owncloud.android.operations.UploadFileOperation.normalUpload(UploadFileOperation.java:827)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at com.owncloud.android.operations.UploadFileOperation.run(UploadFileOperation.java:407)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:145)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:149)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:93)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:1090)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1023)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at android.os.Looper.loop(Looper.java:154)
03-04 00:25:09.332  5961  7115 E UploadFileOperation: 	at android.os.HandlerThread.run(HandlerThread.java:61)
03-04 00:25:09.333  5961  7115 D UploadsStorageManager: updateDatabaseUploadResult uploadResult: com.owncloud.android.lib.common.operations.RemoteOperationResult@472dd64 upload: com.owncloud.android.operations.UploadFileOperation@3b4ebcd
03-04 00:25:09.338  5961  7115 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/VID_20180303_165949.mp4 with status:UPLOAD_FAILED and result:NETWORK_CONNECTION (old:/storage/emulated/0/DCIM/Camera/VID_20180303_165949.mp4 status:UPLOAD_IN_PROGRESS result:-1)
03-04 00:25:09.338  5961  7115 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/VID_20180303_165949.mp4 with status=UPLOAD_FAILED
03-04 00:25:09.356  5961  7115 D UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/VID_20180303_165949.mp4
03-04 00:25:09.356  5961  7115 D UploadsStorageManager: notifyObserversNow
03-04 00:25:09.358  5961  7115 D FileUploader: NotifyUploadResult with resultCode: SSL_ERROR
03-04 00:25:09.368  5961  7115 D FileUploader: Stopping command after id 61
03-04 00:25:09.370  5961  5961 D ExpandableUploadListAdapter: refreshView
03-04 00:25:09.370  5961  5961 D ExpandableUploadListAdapter: loadUploadItemsFromDb
03-04 00:25:09.379  5961  9715 D skia    : --- SkAndroidCodec::NewFromStream returned null
03-04 00:25:09.379  5961  9715 D skia    : --- SkAndroidCodec::NewFromStream returned null
```

Output from nextcloud server log:
`{"reqId":"xY3GrxMlOKpwOHC5E7uK","level":4,"time":"2018-03-03T23:25:09+00:00","remoteAddr":"10.42.24.8","user":"38EA6665-F9AB-4173-830B-B7C73E68A1EF","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/Videos\/Handy\/Kamera\/\/2018\/03\/VID_20180303_165949.mp4-chunking-1829038743-154-11","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Message\":\"expected filesize 1024000 got 933888\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(132): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #17)\\n#1 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(151): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #17)\\n#2 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1096): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('VID_20180303_16...', Resource id #17)\\n#3 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('Videos\\\/Handy\\\/Ka...', Resource id #17, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/html\\\/remote.php(164): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":437}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/3.0.2","version":"13.0.0.14"}`


In front of nextcloud is HAproxy. I already tried the following settings for the nextcloud backend:
```
timeout client 30m
timeout connect 30s
timeout server 30m
```

But it doesn't help. Uploading pictures works without problems.

**Comment by tobiasKaminsky** [comment]
@rullzer do you have an idea here? 
It seems that the last(?) chunk or maybe assembling the chunks result in an exception, which is then wrongly shown to the user.

Can this be related to HAproxy or it is a timeout somewhere?

**Comment by rullzer** [comment]
It seems like a chunk is missing...

```expected filesize 1024000 got 933888```

**Comment by iGeekFace** [comment]
I am also receiving this SSL error for video uploads, and for some images too. I have better luck with images though, so I'm guessing it relates to file size. I'm using a OnePlus 5T as well, but with LineageOS.

**Comment by AldarisPale** [comment]
I have the same problem. Sometimes I get SSL error, sometimes just general Connection Error.
There is no difference between videos and images because is it random (well, no purely, but it **is** from Nextcloud clients point of view). This is because in my case I have a misbehaving router. I use VPN to work around this problem (VPN handles my bad router by resending garbled packages and this is transparent to Nextcloud client).

I do have one proposal: currently when this error occurs nextcloud client starts uploading again from the begging of the file. Every time. One video with a size of 1 Gigabyte with an uplink of 1mbit/s with random restarts makes one month pass very fast without any meaningful restarts. I propose that nextcloud client should verify how much "got through" and continue from there.

I am using Nextcloud Android App version 3.1.0.

**Comment by AndyScherzinger** [comment]
Hi @AldarisPale, that sounds strange since the client does chunked uploads so it should restart right where is stopped, so calling @tobiasKaminsky and @mario :) Since I thought we do have chunked uploads everywhere, no?

**Comment by tobiasKaminsky** [comment]
Yes, we have chunked uploads. But if the server/route behaves weird, maybe one of the chunk is corrupt, which then results in a failing upload.

The new dav endpoint has a decent chunked upload, so this will change at some point.

**Comment by marvinwankersteen** [comment]
I found my problem.
I had on the host with the haproxy loadbalancer a wrong MTU. The MTU on the Server where the nextcloud-container runs is a little bit smaller. So I changed the MTU on the haproxy-node and now everything works fine.

Hope that helps someone ;-)

**Comment by iGeekFace** [comment]
I'm not using a loadbalancer. I checked the MTU on my server and it's 1500. I'm still experiencing this issue.
