### ISSUE TITLE
WebDAV error in 3.0.0. RC2 when accessing Files

### ISSUE THREAD

**Issue by Gilloni** [nextcloud/android#2047]
### Actual behaviour
when i try to open any files on android from my nextcloud 13 RC2 i can't open the files.
i also can't see all my files on the folder ( mostly only 2 or three files are shown).

When i try to downlaod a file i get the error: the file isn't any more on the server.

I tried the official version 2 and it works.

Webdav tried directly and works.

### Expected behaviour
All files are shown and accessible.
 
### Steps to reproduce
1. Install beta client from playstore
2. open folders; files are missing
3. try to download a file

### Environment data
Android version:
Android 7.0
Device model: 
Samsung S8+ (G955F)
Stock or customized system:
Stock
Nextcloud app version:
3.0.0 RC2
Nextcloud server version:
13 RC2
#### Web server error log
No Errors

Access Log
[25/Jan/2018:20:58:13 +0100] "GET /remote.php/webdav/Spiele/Pen%20%26%20Paper/Midgard/M5/Quellenb%C3%BCcher/null HTTP/1.1" 404 281
[25/Jan/2018:20:58:20 +0100] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 413
[25/Jan/2018:20:58:20 +0100] "GET /index.php/avatar/xxxx/336 HTTP/1.1" 404 -
[25/Jan/2018:20:58:21 +0100] "PROPFIND /remote.php/webdav/Spiele/Pen%20%26%20Paper/Midgard/M5/Quellenb%C3%BCcher/ HTTP/1.1" 207 816
[25/Jan/2018:20:58:21 +0100] "GET /ocs/v2.php/apps/files_sharing/api/v1/shares?path=%2FSpiele%2FPen+%26+Paper%2FMidgard%2FM5%2FQuellenb%C3%BCcher%2F&reshares=true&subfiles=true HTTP/1.1" 200 138
[25/Jan/2018:20:58:22 +0100] "GET /remote.php/webdav/Spiele/Pen%20%26%20Paper/Midgard/M5/Quellenb%C3%BCcher/null HTTP/1.1" 404 281
[25/Jan/2018:20:58:26 +0100] "PROPFIND /remote.php/webdav/Spiele/Pen%20%26%20Paper/Midgard/M5/ HTTP/1.1" 207 797
[25/Jan/2018:20:58:26 +0100] "PROPFIND /remote.php/webdav/Spiele/Pen%20%26%20Paper/Midgard/M5/ HTTP/1.1" 207 24490
[25/Jan/2018:20:58:27 +0100] "PROPFIND /remote.php/webdav/Spiele/Pen%20%26%20Paper/Midgard/ HTTP/1.1" 207 795
[25/Jan/2018:20:58:27 +0100] "PROPFIND /remote.php/webdav/Spiele/Pen%20%26%20Paper/Midgard/ HTTP/1.1" 207 9448
[25/Jan/2018:20:58:27 +0100] "GET /ocs/v2.php/apps/files_sharing/api/v1/shares?path=%2FSpiele%2FPen+%26+Paper%2FMidgard%2FM5%2F&reshares=true&subfiles=true HTTP/1.1" 200 138
[25/Jan/2018:20:58:28 +0100] "PROPFIND /remote.php/webdav/Spiele/Pen%20%26%20Paper/ HTTP/1.1" 207 788
[25/Jan/2018:20:58:28 +0100] "GET /ocs/v2.php/apps/files_sharing/api/v1/shares?path=%2FSpiele%2FPen+%26+Paper%2FMidgard%2F&reshares=true&subfiles=true HTTP/1.1" 200 138
[25/Jan/2018:20:58:28 +0100] "PROPFIND /remote.php/webdav/Spiele/Pen%20%26%20Paper/ HTTP/1.1" 207 8602
[25/Jan/2018:20:58:28 +0100] "GET /ocs/v2.php/apps/files_sharing/api/v1/shares?path=%2FSpiele%2FPen+%26+Paper%2F&reshares=true&subfiles=true HTTP/1.1" 200 138
[25/Jan/2018:20:58:28 +0100] "PROPFIND /remote.php/webdav/Spiele/ HTTP/1.1" 207 770
[25/Jan/2018:20:58:28 +0100] "PROPFIND /remote.php/webdav/Spiele/ HTTP/1.1" 207 6173
[25/Jan/2018:20:58:29 +0100] "GET /ocs/v2.php/apps/files_sharing/api/v1/shares?path=%2FSpiele%2F&reshares=true&subfiles=true HTTP/1.1" 200 138
[25/Jan/2018:21:01:46 +0100] "GET /index.php/204 HTTP/1.1" 204 -
[25/Jan/2018:21:01:46 +0100] "GET /index.php/204 HTTP/1.1" 204 -
[25/Jan/2018:21:01:46 +0100] "GET /index.php/204 HTTP/1.1" 204 -
[25/Jan/2018:21:01:47 +0100] "GET /index.php/204 HTTP/1.1" 204 -
[25/Jan/2018:21:01:47 +0100] "GET /index.php/204 HTTP/1.1" 204 -
[25/Jan/2018:21:01:47 +0100] "GET /index.php/204 HTTP/1.1" 204 -

#### Nextcloud log (data/nextcloud.log)
(Other try for an other file):

{“reqId”:“WmrfgcXYDfcttltFgtQfXwAAAAM”,“level”:0,“time”:“2018-01-26T07:57:53+00:00”,“remoteAddr”:“xx.xx.xx.xx”,“user”:“XXXX”,“app”:“webdav”,“method”:“GET”,“url”:"/remote.php/webdav/Notes/null",“message”:“Exception: {“Exception”:“Sabre\\DAV\\Exception\\NotFound”,“Message”:“File with name Notes\/null could not be located”,“Code”:0,“Trace”:”#0 \/var\/www\/html\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(81): OCA\\DAV\\Connector\\Sabre\\ObjectTree->getNodeForPath(‘Notes\/null’)\n#1 [internal function]: Sabre\\DAV\\CorePlugin->httpGet(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \/var\/www\/html\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/var\/www\/html\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(479): Sabre\\Event\\EventEmitter->emit(‘method:GET’, Array)\n#4 \/var\/www\/html\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/html\/nextcloud\/apps\/dav\/appinfo\/v1\/webdav.php(80): Sabre\\DAV\\Server->exec()\n#6 \/var\/www\/html\/nextcloud\/remote.php(164): require_once(’\/var\/www\/html\/n…’)\n#7 {main}",“File”:"\/var\/www\/html\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/ObjectTree.php",“Line”:174}",“userAgent”:“Mozilla/5.0 (Android) Nextcloud-android/3.0.0 RC2”,“version”:“13.0.0.11”}

**Comment by tobiasKaminsky** [comment]
@MorrisJobke do you have any idea why there is "null" in the file name?

**Comment by MorrisJobke** [comment]
cc @georgehrke @blizzz @rullzer for the dav stuff.

**Comment by tobiasKaminsky** [comment]
This might be related to #2044. There I also got the "null".
The cause seems to be that for unknown reason the file is flagged as encrypted.

**Comment by Gilloni** [comment]
Hello,

the new RC3 has fixed the issue with #2044 

Thanks for fixing.

Thomas
