### ISSUE TITLE
Beta app is crashing whenever I try and enter certain folders

### ISSUE THREAD

**Issue by rubrik** [nextcloud/android#2085]
### Actual behaviour
The beta app crashes when I try and enter certain folders.

### Expected behaviour
It should not crash.
 
### Steps to reproduce
1. Enter certain folders (always photos? I think)
2. Crash
3. Send crash report

Do you guys get crash reports? I will debug this logcat tonight.

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
If this is crashing when accessing a folder on server, this is maybe related to server?
Do you see any logs on server?

Can you create us a test account, test if the problem occurs also there and if so send the credentials to android at nextcloud dot com with a reference to this issue?

**Comment by rubrik** [comment]
This is crashing when I access a folder on the server, I don't see any logs at /settings/admin/logging or in /var/www/nextcloud or in /var/log, but I would expect to for a server-side problem. Since re-uploading one of the folders the problem has gone away for that folder, so now the problem is specific to just one certain folder.

Creating a test account would only work if you had access to this folder, wouldn't it?

**Comment by rubrik** [comment]
[adb1.txt](https://github.com/nextcloud/android/files/1691776/adb1.txt)

**Comment by rubrik** [comment]
@tobiasKaminsky do you need any more information from me?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky it is the sorting issue 
```
java.lang.IllegalArgumentException: Comparison method violates its general contract!
       at java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:866)
       at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:483)
       at java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:406)
       at java.util.ComparableTimSort.sort(ComparableTimSort.java:213)
       at java.util.Arrays.sort(Arrays.java:1259)
       at java.util.Collections.sort(Collections.java:174)
       at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:862)
       at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:154)
       at com.owncloud.android.ui.adapter.FileListListAdapter.swapDirectory(FileListListAdapter.java:498)
       at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1189)
       at com.owncloud.android.ui.fragment.OCFileListFragment.onItemClick(OCFileListFragment.java:929)
       at android.widget.AdapterView.performItemClick(AdapterView.java:339)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1718)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:4184)
       at android.widget.AbsListView$13.run(AbsListView.java:6754)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by tobiasKaminsky** [comment]
Huh. Strange. I never saw that sorting problem on folders.
If I remember correctly the sorting problem occurs when the data is changed during sorting, but this should not be possible as we load the content prior sorting...
