### ISSUE TITLE
Upload fails due to locking fails with EAGAIN

### ISSUE THREAD

**Issue by stalker314314** [nextcloud/android#2086]
### Actual behaviour
Uploads very often (>80%) fails with "upload failed" error and no other info. It went through after couple of retries (either manually, or automatically), but it is very annoying, especially when I am taking picture and want it very fast on desktop/laptop.

Not sure if it might be related, but I have both 2.0 and beta from F-Droid. Maybe they are trying to lock at the same time? Not sure.

I am proposing doing exponential backoff with random timeouts (for example, 5 retries, timeout is rand(0, iteration * 200ms). I can jump to implementation, as this is very annoying (and I can test it along the way).

### Expected behaviour
Upload should succeed in larger number of cases
 
### Steps to reproduce
1. Take a picture/video
2. Wait until automatic upload starts
3. See if it fails

### Environment data
Android version:
6.0.1

Device model: 
Galaxy J5

Stock or customized system:
Lineage OS

Nextcloud app version:
Both on 2.0 and from F-Droid beta

Nextcloud server version:
N/A

#### Web server error log
N/A

#### Nextcloud log (data/nextcloud.log)
```
02-01 20:20:58.428 3031-5743/com.nextcloud.client E/UploadFileOperation: Upload of /storage/emulated/0/DCIM/Camera/IMG_20180201_201710.jpg to /Photos/Phone//IMG_20180201_201710.jpg: Unrecovered transport exception
                                                                         java.io.IOException: fcntl failed: EAGAIN (Try again)
                                                                             at java.nio.FileChannelImpl.basicLock(FileChannelImpl.java:123)
                                                                             at java.nio.FileChannelImpl.tryLock(FileChannelImpl.java:181)
                                                                             at java.nio.channels.FileChannel.tryLock(FileChannel.java:584)
                                                                             at com.owncloud.android.operations.UploadFileOperation.run(UploadFileOperation.java:416)
                                                                             at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136)
                                                                             at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:93)
                                                                             at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:1033)
                                                                             at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:976)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                          Caused by: android.system.ErrnoException: fcntl failed: EAGAIN (Try again)
                                                                             at libcore.io.Posix.fcntlFlock(Native Method)
                                                                             at libcore.io.ForwardingOs.fcntlFlock(ForwardingOs.java:70)
                                                                             at java.nio.FileChannelImpl.basicLock(FileChannelImpl.java:121)
                                                                             at java.nio.FileChannelImpl.tryLock(FileChannelImpl.java:181) 
                                                                             at java.nio.channels.FileChannel.tryLock(FileChannel.java:584) 
                                                                             at com.owncloud.android.operations.UploadFileOperation.run(UploadFileOperation.java:416) 
                                                                             at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136) 
                                                                             at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:93) 
                                                                             at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:1033) 
                                                                             at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:976) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:148) 
                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by tobiasKaminsky** [comment]
Do you have enabled auto upload for both apps? 
Then this will indeed lead to trouble.
But having both apps installed and only enabled one auto upload should be no problem.

**Comment by stalker314314** [comment]
Yes, I have auto upload on both. I want to have them both, as idea is to test beta. No point in testing beta, if I turn off auto upload:) What is annoying me is this error message. Maybe I am wrong, but I am hoping if we can backoff for the time of upload, we can avoid this error message (never sure if it is real error, or locking error). Other options that came to my mind is:
* can we delay beta version for 15min/2 during scheduling (scheduleFilesSyncIfNeeded), so jobs are "somewhat" interleaved? Using setExact() maybe? Or just checking inside job if we are started on round number of minutes (00,15,30,45 for prod, 7.5, 22.5, 37.5, 52.5 for beta) and sleep a bit. I am not expert on any of this, so I might be very wrong:)
* why tryLock cannot take shared lock? I don't see need for exclusive lock, if we are just reading/uploading file? I guess, if lock can be promoted to shared, we can have multiple jobs work on it:)
