### ISSUE TITLE
Unable to add content to E2E encrypted folder.

### ISSUE THREAD

**Issue by eric4321** [nextcloud/android#2224]
### Actual behavior
Unable to create a folder in or upload a file to an E2E encrypted folder. 

When trying to create a new folder a "You are not permitted to create this file." error appears.

When trying to upload a single file a notification appears with the error "You are not permitted to upload to this folder"

### Expected behaviour
-The folder should be created in the encrypted directory.
-The file should be uploaded to the encrypted folder.
 
### Steps to reproduce
1.  Create E2E encrypted folder in Android client
2. Enter encrypted folder (and set up keys).
3. Create new folder.
4. Error will appear.

I have also tested this with a completely new user.

### Environment data
Android version:
8.1.0

Device model: 
Google Pixel 2

Stock or customized system:
Stock

Nextcloud app version:
3.0.1 (from F-Droid)

Nextcloud server version:
13.0.0 on FreeBSD
#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"Okri2MOdjmIG3qNO5Czv","level":4,"time":"2018-02-23T09:07:42+00:00","remoteAddr":"192.168.1.18","user":"my.username","app":"webdav","method":"PROPFIND","url":"\/remote.php\/webdav\/pictures\/","message":"Exception: {\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\Forbidden\",\"Message\":\"client not allowed to access end-to-end encrypted content\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/local\\\/www\\\/apache24\\\/data\\\/nextcloud\\\/apps\\\/end_to_end_encryption\\\/lib\\\/Connector\\\/Sabre\\\/LockPlugin.php(124): OCA\\\\EndToEndEncryption\\\\Connector\\\\Sabre\\\\LockPlugin->checkUserAgent('Mozilla\\\/5.0 (An...', '\\\/pictures')\\n#1 [internal function]: OCA\\\\EndToEndEncryption\\\\Connector\\\\Sabre\\\\LockPlugin->checkLock(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/usr\\\/local\\\/www\\\/apache24\\\/data\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/usr\\\/local\\\/www\\\/apache24\\\/data\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#4 \\\/usr\\\/local\\\/www\\\/apache24\\\/data\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/usr\\\/local\\\/www\\\/apache24\\\/data\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/usr\\\/local\\\/www\\\/apache24\\\/data\\\/nextcloud\\\/remote.php(164): require_once('\\\/usr\\\/local\\\/www\\\/...')\\n#7 {main}\",\"File\":\"\\\/usr\\\/local\\\/www\\\/apache24\\\/data\\\/nextcloud\\\/apps\\\/end_to_end_encryption\\\/lib\\\/Connector\\\/Sabre\\\/LockPlugin.php\",\"Line\":169}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/3.0.1","version":"13.0.0.14"}


{"reqId":"LzZI4TNKmLt9IyZ0iWdg","level":4,"time":"2018-02-23T09:07:47+00:00","remoteAddr":"192.168.1.18","user":"my.username","app":"webdav","method":"MKCOL","url":"\/remote.php\/webdav\/pictures\/Bnd\/","message":"Exception: {\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\Forbidden\",\"Message\":\"client not allowed to access end-to-end encrypted content\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/local\\\/www\\\/apache24\\\/data\\\/nextcloud\\\/apps\\\/end_to_end_encryption\\\/lib\\\/Connector\\\/Sabre\\\/LockPlugin.php(124): OCA\\\\EndToEndEncryption\\\\Connector\\\\Sabre\\\\LockPlugin->checkUserAgent('Mozilla\\\/5.0 (An...', '\\\/pictures')\\n#1 [internal function]: OCA\\\\EndToEndEncryption\\\\Connector\\\\Sabre\\\\LockPlugin->checkLock(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/usr\\\/local\\\/www\\\/apache24\\\/data\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/usr\\\/local\\\/www\\\/apache24\\\/data\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#4 \\\/usr\\\/local\\\/www\\\/apache24\\\/data\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/usr\\\/local\\\/www\\\/apache24\\\/data\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/usr\\\/local\\\/www\\\/apache24\\\/data\\\/nextcloud\\\/remote.php(164): require_once('\\\/usr\\\/local\\\/www\\\/...')\\n#7 {main}\",\"File\":\"\\\/usr\\\/local\\\/www\\\/apache24\\\/data\\\/nextcloud\\\/apps\\\/end_to_end_encryption\\\/lib\\\/Connector\\\/Sabre\\\/LockPlugin.php\",\"Line\":169}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/3.0.1","version":"13.0.0.14"}

```

**Comment by tigernero79** [comment]
Problem already open here

https://github.com/nextcloud/android/issues/2189
