### ISSUE TITLE
Crash on open GridView folder

### ISSUE THREAD

**Issue by p5n** [nextcloud/android#2461]
### Actual behaviour
- App crashes

### Expected behaviour
- folder should be opened
 
### Steps to reproduce
1.  Open folder that was previously set to gridview

### Environment data
Android version: 7.1.2

Device model:  xiaomi redmi 4A

Stock or customized system: stock

Nextcloud app version: dev 20180410 from f-droid

#### Nextcloud log (data/nextcloud.log)
```
04-11 15:54:05.819 11200 11200 E AndroidRuntime: FATAL EXCEPTION: main
04-11 15:54:05.819 11200 11200 E AndroidRuntime: Process: com.nextcloud.android.beta, PID: 11200
04-11 15:54:05.819 11200 11200 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.support.v7.widget.GridLayoutManager.calculateItemBorders(GridLayoutManager.java:324)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.support.v7.widget.GridLayoutManager.calculateItemBorders(GridLayoutManager.java:309)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.support.v7.widget.GridLayoutManager.updateMeasurements(GridLayoutManager.java:280)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.support.v7.widget.GridLayoutManager.onAnchorReady(GridLayoutManager.java:355)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:575)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3693)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3410)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.View.layout(View.java:17663)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5577)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:610)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.View.layout(View.java:17663)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5577)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1166)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:851)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.View.layout(View.java:17663)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5577)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.View.layout(View.java:17663)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5577)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.View.layout(View.java:17663)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5577)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1730)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1496)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.View.layout(View.java:17663)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5577)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.View.layout(View.java:17663)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5577)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1172)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.View.layout(View.java:17663)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5577)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.View.layout(View.java:17663)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5577)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.View.layout(View.java:17663)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5577)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.View.layout(View.java:17663)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5577)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.View.layout(View.java:17663)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5577)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:730)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.View.layout(View.java:17663)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5577)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2392)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2114)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1300)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6405)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:688)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:623)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:754)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:163)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6205)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
04-11 15:54:05.819 11200 11200 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
04-11 15:54:05.825  2426  2463 I octvm_klo: klo lock
04-11 15:54:05.829  1523  4169 W ActivityManager:   Force finishing activity com.nextcloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity
04-11 15:54:05.831  2621  2777 I WtProcessController: Receive am_crash event for pid: 11200 pkg = com.nextcloud.android.beta
04-11 15:54:05.831  2621  2777 W KloServer: Aborted broadcast does not supprt for: com.nextcloud.android.beta
04-11 15:54:05.837  1523  4169 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
04-11 15:54:05.839 11200 11200 I Process : Sending signal. PID: 11200 SIG: 9
```

**Comment by ardevd** [comment]
I'm not able to reproduce the issue and the stack trace simply seems to indicate that the array list of files is empty when it shouldn't be. 

Does this issue occur with all your folders or just one specifically?

**Comment by p5n** [comment]
It occurs with any folder. I tried to switch root folder into grid view and app immediately crashed.

**Comment by p5n** [comment]
I think the problem was that storage path = /...emulated/0/ however current app does not allow to choose  this path

**Comment by p5n** [comment]
I also found that current app cannot browse local files when I try to set up custom upload folder. I checked that storage permission enabled.

**Comment by Scoub29** [comment]
Il have exactly the same problem with Huawei p8 (Android 7.0). Change path storage doesn't fix this issue. Grid mode instantly crash the app

**Comment by Scoub29** [comment]
I have fix this issue. Android settings -> App settings -> Nextcloud. Delete cache, delete data.
After, uninstall/reinstall Nextcloud and no problem with grid mode 😉
