### ISSUE TITLE
App crash (beta) with "Bad notification for startForeground"

### ISSUE THREAD

**Issue by stalker314314** [nextcloud/android#2480]
### Actual behaviour
App crash with notification staying at 0% all the time.
Files seems to get uploaded though.
App keeps crashing and no way to get it back.
When I open it again, files get uploaded.

When I take another photo, it crashes again (but files get uploaded etc).

### Expected behaviour
App should continue working
 
### Steps to reproduce
Latest beta (14.04.2018.). Always reproduced when auto uploading files.

### Environment data
Android version:
Lineage 15.1 (8?)

Device model:
Xiaomi 4X

Stock or customized system:
Lineage

Nextcloud app version:
14.04.2018.

Nextcloud server version:
13.0

#### Nextcloud log (data/nextcloud.log)
```
04-18 08:33:12.564 20632-20632/com.nextcloud.android.beta E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.nextcloud.android.beta, PID: 20632
                                                                            android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0xff0082c8 vis=PRIVATE)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                at android.os.Looper.loop(Looper.java:164)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by tobiasKaminsky** [comment]
This change happens due to latest gradle update, PR fixing this is in #2479.

**Comment by stalker314314** [comment]
Sounds fine:) I will optimistically close this issue (and will check on next f-droid release and reopen if it still repro)

**Comment by tobiasKaminsky** [comment]
Please note that once #2479 is merged, Fdroid still might take a few days to build a new dev version.

**Comment by AndyScherzinger** [comment]
merged for 3.2 and the next dev version

**Comment by stalker314314** [comment]
Thanks, appreciated! (as you probably know, every image shot was greeted with annoying "app crash" dialog, so any "photo shooting" was pretty bad experience:D)

**Comment by AndyScherzinger** [comment]
So looking forward to the next dev build :)
