### ISSUE TITLE
Crash when trying to use mosaic display

### ISSUE THREAD

**Issue by leolivier** [nextcloud/android#2498]
Each time I try to display ly files in mosaic mode in nextcloud android 3.1 on my OnePlus 5 phone with Android 8.0, the application crashes.
I sent comments with full journal from within Android when it last happened.

**Comment by tobiasKaminsky** [comment]
It is hard to find a specific crash report within google play console.
Can you also send it to an email address, if so please use tobias.kaminsky@nextcloud.com, or https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by leolivier** [comment]
[logCatOutput.txt](https://github.com/nextcloud/android/files/1951705/logCatOutput.txt)
Hi @tobiasKaminsky 
Please find attached a logcat output of this issue on my phone... Seems to be an array out of bound somewhere (stack trace line 214 and after)

**Comment by tobiasKaminsky** [comment]
Thank you for the logcat. It seems that somehow the computation of androids internal function has a hiccup.
Have you done something "special", like adding files, adding folder, rotating while you browsed the folder.
Background of my question is that somehow it seems that the internal data representation does not match the items that are displayed.

**Comment by leolivier** [comment]
Maybe I did things like that but I don't remember.
2 elements still:
1) I changed some parameters on automatic photos uploading. And it didn't work as expected: older photos were not uploaded
2) I changed my owncloud domain name

**Comment by tobiasKaminsky** [comment]
@Insoleet 
Can you provide us additional infos via logcat to verify if this is the same bug? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by leon-barsamian** [comment]
Hello,

same here
[logcatOutput_2498.txt](https://github.com/nextcloud/android/files/2229539/logcatOutput_2498.txt)

Steps to reproduce : 
* launch nextcloud app
* browse to any photo folder
* click on "mosaic" icon

-> the app crashes

nextcloud 3.2.1
google nexus 5X
Android 8.1.0

**Comment by leolivier** [comment]
Hi @leon-barsamian
The only way I found to fix the problem is to in the Android applications parameters, then find nextcloud and remove **all**  data

**Comment by tobiasKaminsky** [comment]
This is only Androids internal functions…

```
OwnCloudClient #1: REQUEST PROPFIND /remote.php/webdav/Photos/Albums/
07-25 22:44:02.328 26412 26412 D AndroidRuntime: Shutting down VM
07-25 22:44:02.336 26412 26412 E AndroidRuntime: FATAL EXCEPTION: main
07-25 22:44:02.336 26412 26412 E AndroidRuntime: Process: com.nextcloud.client, PID: 26412
07-25 22:44:02.336 26412 26412 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.support.v7.widget.GridLayoutManager.calculateItemBorders(GridLayoutManager.java:324)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.support.v7.widget.GridLayoutManager.calculateItemBorders(GridLayoutManager.java:309)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.support.v7.widget.GridLayoutManager.updateMeasurements(GridLayoutManager.java:280)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.support.v7.widget.GridLayoutManager.onAnchorReady(GridLayoutManager.java:355)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:581)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:606)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1191)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:876)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:895)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1780)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1546)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1171)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:658)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
07-25 22:44:02.336 26412 26412 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
07-25 22:44:02.339  3557  6244 W ActivityManager:   Force finishing activity com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity
07-25 22:44:02.346  3557  3575 I ActivityManager: Showing crash dialog for package com.nextcloud.client u0
``` 

Glad that it is working now for you!
So I am closing this one.
