### ISSUE TITLE
NPE in PreviewMediaFragment.onSaveInstanceState

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#252]
From the Play store developer console.

### Environment data
Android version: 6.0

Device model: OnePlus One (A0001)

Stock or customized system: -

Nextcloud app version: 1.2.0 stable

Nextcloud server version: - 

### Logs

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.owncloud.android.media.MediaServiceBinder.getCurrentPosition()' on a null object reference
	at com.owncloud.android.ui.preview.PreviewMediaFragment.onSaveInstanceState(PreviewMediaFragment.java:259)
	at android.support.v4.app.Fragment.performSaveInstanceState(Fragment.java:2124)
	at android.support.v4.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:1771)
	at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1839)
	at android.support.v4.app.FragmentController.saveAllState(FragmentController.java:134)
	at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:565)
	at android.support.v7.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:502)
	at com.owncloud.android.ui.activity.DrawerActivity.onSaveInstanceState(DrawerActivity.java:511)
	at com.owncloud.android.ui.activity.FileActivity.onSaveInstanceState(FileActivity.java:226)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onSaveInstanceState(FileDisplayActivity.java:822)
	at android.app.Activity.performSaveInstanceState(Activity.java:1302)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1290)
	at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4122)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4084)
	at android.app.ActivityThread.-wrap15(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky code/fix looks good to me! Due to the Hacktoberfest starting on Saturday we probably shouldn't merge hacktoberfest labelled issues before that date so they get counted correctly :rocket:
