### ISSUE TITLE
App craches using grid view during upload and scrolling

### ISSUE THREAD

**Issue by BlackDex** [nextcloud/android#2527]
### Actual behaviour
- When uploading new files and selecting grid-view and scrolling through the list the app crashes.

### Expected behaviour
- The app not crashing.
 
### Steps to reproduce
1. Choose a folder
2. Click the "+" sign at the bottom right
3. Select "Upload Files"
4. Select a folder with a lot of files so you need to scroll, in my case my DCIM/Camera folder.
5. Enable grid view using the 3dot menu top-right.
6. Scroll slow/fast, select a file or something, after a few scrolling attempts the app crashes.

### Environment data
Android version: 8.1.0 and 7.0

Device model: Nexus 5X and Galaxy S6 (SM-G920F)

Stock or customized system: Stock

Nextcloud app version: 20180425

Nextcloud server version: Owncloud 9.1.6 (I know i need to switch & upgrade ;) )

#### Web server error log
```
n/a
```

#### Nextcloud log (data/nextcloud.log)
```
n/a
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by ardevd** [comment]
Please attack a stacktrace with adb logcat of the crash so that we can investigate this issue. This might be a duplicate of #2498 and #2461

**Comment by BlackDex** [comment]
@ardevd Here are the logcat's for both devices during the crash.

**Nexus 5X:**
```
05-01 11:08:49.926 30400 30400 V LocalFileListAdapter: Executing task to generate a new thumbnail
05-01 11:08:50.045 30400 30400 I chatty  : uid=10111(com.nextcloud.android.beta) identical 18 lines
05-01 11:08:50.059 30400 30400 V LocalFileListAdapter: Executing task to generate a new thumbnail
05-01 11:08:50.074 30400 30400 D AndroidRuntime: Shutting down VM
05-01 11:08:50.076 30400 30400 E AndroidRuntime: FATAL EXCEPTION: main
05-01 11:08:50.076 30400 30400 E AndroidRuntime: Process: com.nextcloud.android.beta, PID: 30400
05-01 11:08:50.076 30400 30400 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at com.owncloud.android.utils.MimeTypeUtil.getFileTypeIcon(MimeTypeUtil.java:98)
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at com.owncloud.android.utils.MimeTypeUtil.getFileTypeIcon(MimeTypeUtil.java:85)
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at com.owncloud.android.ui.adapter.LocalFileListAdapter.setThumbnail(LocalFileListAdapter.java:270)
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at com.owncloud.android.ui.adapter.LocalFileListAdapter.onBindViewHolder(LocalFileListAdapter.java:187)
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1333)
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1077)
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4960)
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:655)
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
05-01 11:08:50.076 30400 30400 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
05-01 11:08:50.079   767  1314 W ActivityManager:   Force finishing activity com.nextcloud.android.beta/com.owncloud.android.ui.activity.UploadFilesActivity
05-01 11:08:50.086   767   783 I ActivityManager: Showing crash dialog for package com.nextcloud.android.beta u0
05-01 11:08:50.091   767   782 W BroadcastQueue: Permission Denial: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to ProcessRecord{c4a4255 3206:com.teslacoilsw.notifier/u0a158} (pid=3206, uid=10158) requires android.permission.READ_LOGS due to sender android (uid 1000)
```

**Galaxy S6:**
```
05-01 11:12:51.444  2934  2934 V LocalFileListAdapter: Executing task to generate a new thumbnail
05-01 11:12:51.460  2934  2934 V LocalFileListAdapter: Executing task to generate a new thumbnail
05-01 11:12:51.499  2934  2934 D AndroidRuntime: Shutting down VM
05-01 11:12:51.500  2934  2934 E AndroidRuntime: FATAL EXCEPTION: main
05-01 11:12:51.500  2934  2934 E AndroidRuntime: Process: com.nextcloud.android.beta, PID: 2934
05-01 11:12:51.500  2934  2934 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
05-01 11:12:51.500  2934  2934 E AndroidRuntime: 	at com.owncloud.android.utils.MimeTypeUtil.getFileTypeIcon(MimeTypeUtil.java:98)
05-01 11:12:51.500  2934  2934 E AndroidRuntime: 	at com.owncloud.android.utils.MimeTypeUtil.getFileTypeIcon(MimeTypeUtil.java:85)
05-01 11:12:51.500  2934  2934 E AndroidRuntime: 	at com.owncloud.android.ui.adapter.LocalFileListAdapter.setThumbnail(LocalFileListAdapter.java:270)
05-01 11:12:51.500  2934  2934 E AndroidRuntime: 	at com.owncloud.android.ui.adapter.LocalFileListAdapter.onBindViewHolder(LocalFileListAdapter.java:187)
05-01 11:12:51.500  2934  2934 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
05-01 11:12:51.500  2934  2934 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
05-01 11:12:51.500  2934  2934 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
05-01 11:12:51.500  2934  2934 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
05-01 11:12:51.500  2934  2934 E AndroidRuntime: 	at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
05-01 11:12:51.500  2934  2934 E AndroidRuntime: 	at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:342)
05-01 11:12:51.500  2934  2934 E AndroidRuntime: 	at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
05-01 11:12:51.500  2934  2934 E AndroidRuntime: 	at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
05-01 11:12:51.500  2934  2934 E AndroidRuntime: 	at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
05-01 11:12:51.500  2934  2934 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
05-01 11:12:51.500  2934  2934 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-01 11:12:51.500  2934  2934 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-01 11:12:51.500  2934  2934 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6682)
05-01 11:12:51.500  2934  2934 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-01 11:12:51.500  2934  2934 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
05-01 11:12:51.500  2934  2934 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
05-01 11:12:51.504  3688  4994 D Debug   : !@DumpState : SHIP
05-01 11:12:51.504  3688  4994 D Debug   : !@DumpState : debug level:0x4f4c
05-01 11:12:51.504  3688  4994 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
05-01 11:12:51.504  3688  4994 W ActivityManager:   Force finishing activity com.nextcloud.android.beta/com.owncloud.android.ui.activity.UploadFilesActivity
05-01 11:12:51.504  3688  4994 W MultiScreenManagerService: moveTaskBackToDisplayIfNeeded(): The task has more than one activity
05-01 11:12:51.505  3688  4994 D ActivityManager: moveToFront() : reason=finishActivity adjustFocus setFocusedActivity isAttached=true TaskRecord{a454cd5d0 #6053 A=com.nextcloud.android.beta U=0 StackId=1 sz=2}
05-01 11:12:51.507  3688  4994 D InputDispatcher: Focused application set to: xxxx
```
