### ISSUE TITLE
App crashes when opening Auto Upload screen.

### ISSUE THREAD

**Issue by ardevd** [nextcloud/android#2569]
### Actual behaviour
- When opening the Auto Upload screen, the app crashes.

### Expected behaviour
- No crash should occur. 

### Steps to reproduce
1. Start app 
2. Pick "Auto Upload" from the nav drawer.
3. App crashes

### Environment data
Android version: 8.1.0

Device model: Emulator

Stock or customized system: Stock

Nextcloud app version: Master.

### Logs
```
05-11 09:39:41.905  8980  8980 D AndroidRuntime: Shutting down VM
05-11 09:39:41.906  8980  8980 E AndroidRuntime: FATAL EXCEPTION: main
05-11 09:39:41.906  8980  8980 E AndroidRuntime: Process: com.nextcloud.client, PID: 8980
05-11 09:39:41.906  8980  8980 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
05-11 09:39:41.906  8980  8980 E AndroidRuntime: 	at com.owncloud.android.utils.MimeTypeUtil.getFileTypeIcon(MimeTypeUtil.java:98)
05-11 09:39:41.906  8980  8980 E AndroidRuntime: 	at com.owncloud.android.utils.MimeTypeUtil.getFileTypeIcon(MimeTypeUtil.java:85)
05-11 09:39:41.906  8980  8980 E AndroidRuntime: 	at com.owncloud.android.datamodel.ThumbnailsCacheManager$MediaThumbnailGenerationTask.onPostExecute(ThumbnailsCacheManager.java:704)
05-11 09:39:41.906  8980  8980 E AndroidRuntime: 	at com.owncloud.android.datamodel.ThumbnailsCacheManager$MediaThumbnailGenerationTask.onPostExecute(ThumbnailsCacheManager.java:642)
05-11 09:39:41.906  8980  8980 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:695)
05-11 09:39:41.906  8980  8980 E AndroidRuntime: 	at android.os.AsyncTask.-wrap1(Unknown Source:0)
05-11 09:39:41.906  8980  8980 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
05-11 09:39:41.906  8980  8980 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-11 09:39:41.906  8980  8980 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
05-11 09:39:41.906  8980  8980 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
05-11 09:39:41.906  8980  8980 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-11 09:39:41.906  8980  8980 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
05-11 09:39:41.906  8980  8980 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
05-11 09:39:41.920  1774  2359 W ActivityManager:   Force finishing activity com.nextcloud.client/com.owncloud.android.ui.activity.SyncedFoldersActivity
05-11 09:39:41.922  1774  2359 W ActivityManager:   Force finishing activity com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity

```

**Comment by ardevd** [comment]
Debugging shows that mimetype, context and account objects are null here:

https://github.com/nextcloud/android/blob/3af569988db3af37936e152b04e03a25a0b0f1fb/src/main/java/com/owncloud/android/utils/MimeTypeUtil.java#L96-L99
