### ISSUE TITLE
[3.2.0RC1] NPE in ActivitiesActivity.setProgressIndicatorState

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#2640]
Reported via GPlay console
```
java.lang.NullPointerException: 
  at com.owncloud.android.ui.activities.ActivitiesActivity.setProgressIndicatorState (ActivitiesActivity.java:318)
  at com.owncloud.android.ui.activities.ActivitiesPresenter$1.onActivitiesLoaded (ActivitiesPresenter.java:55)
  at com.owncloud.android.ui.activities.data.activities.RemoteActivitiesRepository$1.onLoaded (RemoteActivitiesRepository.java:42)
  at com.owncloud.android.ui.activities.data.activities.RemoteActivitiesRepository$1.onLoaded (RemoteActivitiesRepository.java:38)
  at com.owncloud.android.ui.activities.data.activities.ActivitiesServiceApiImpl$GetActivityListTask.onPostExecute (ActivitiesServiceApiImpl.java:124)
  at com.owncloud.android.ui.activities.data.activities.ActivitiesServiceApiImpl$GetActivityListTask.onPostExecute (ActivitiesServiceApiImpl.java:54)
  at android.os.AsyncTask.finish (AsyncTask.java:695)
  at android.os.AsyncTask.-wrap1 (Unknown Source)
  at android.os.AsyncTask$InternalHandler.handleMessage (AsyncTask.java:712)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6501)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:807)
```

Any ideas @ardevd ? :)

**Comment by tobiasKaminsky** [comment]
Steps to reproduce:

- open up activities
- while loading, immediately press back
- wait until background job finishes loading activity stream
- crash

(if you delay fetching or have many activities this is of course a bit easier to trigger)

If first error is handled via null check, then this happens:
```
Process: com.nextcloud.client, PID: 8717
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setVisibility(int)' on a null object reference
        at com.owncloud.android.ui.activities.ActivitiesActivity.showActivities(ActivitiesActivity.java:259)
        at com.owncloud.android.ui.activities.ActivitiesPresenter$1.onActivitiesLoaded(ActivitiesPresenter.java:61)
        at com.owncloud.android.ui.activities.data.activities.RemoteActivitiesRepository$1.onLoaded(RemoteActivitiesRepository.java:42)
        at com.owncloud.android.ui.activities.data.activities.RemoteActivitiesRepository$1.onLoaded(RemoteActivitiesRepository.java:38)
        at com.owncloud.android.ui.activities.data.activities.ActivitiesServiceApiImpl$GetActivityListTask.onPostExecute(ActivitiesServiceApiImpl.java:124)
        at com.owncloud.android.ui.activities.data.activities.ActivitiesServiceApiImpl$GetActivityListTask.onPostExecute(ActivitiesServiceApiImpl.java:54)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.-wrap1(Unknown Source:0)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
``` 

I think we need a call/notify from ActivitiesActivity (view) to presenter that we do not need the result anymore (ideally cancel remote operation).

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky do we want to backport this or put it in 3.2.1?

**Comment by tobiasKaminsky** [comment]
We already have a backport for this https://github.com/nextcloud/android/pull/2653, which was merged 2h before creating RC2, so it is already in.
