### ISSUE TITLE
App crash when switching to grid view

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/android#2668]
### Actual behaviour
- The app crashes
- After the crash i cannot access the folder anymore since it crashes again once opening it

### Expected behaviour
- The app shows the grid view
 
### Steps to reproduce
1. Go to any folder
2. Try to switch to the grid view

### Environment data
Android version: 7.0

Device model: Moto G5

Stock or customized system: Stock

Nextcloud app version: 3.2.0 RC1

Nextcloud server version: 13.0.2

#### Android debug log
```
06-01 15:50:30.558  3146  3159 I art     : Background sticky concurrent mark sweep GC freed 27549(1439KB) AllocSpace objects, 16(1508KB) LOS objects, 12% free, 20MB/22MB, paused 8.326ms total 29.441ms
06-01 15:50:30.562  3146  3323 I ReadRemoteFolderOperation: Synchronized /: Operation finished with HTTP status code 207 (success)
06-01 15:50:30.562  3146  3323 D RefreshFolderOperation: Synchronizing jus@cloud.bitgrid.net/
06-01 15:50:30.572  3146  3323 D RefreshFolderOperation: Remote folder / changed - starting update of local data 
06-01 15:50:30.595  3146  3323 D FileDataStorageManager: Saving folder / with 37 children and 0 files to remove
06-01 15:50:30.626  3146  3321 I ReadRemoteFolderOperation: Synchronized /: Operation finished with HTTP status code 207 (success)
06-01 15:50:30.626  3146  3321 D RefreshFolderOperation: Synchronizing jus@cloud.bitgrid.net/
06-01 15:50:30.635  3146  3321 D RefreshFolderOperation: Remote folder / changed - starting update of local data 
06-01 15:50:30.659  3146  3321 D FileDataStorageManager: Saving folder / with 37 children and 0 files to remove
06-01 15:50:30.795  3146  3323 D FileDataStorageManager: Sending 38 operations to FileContentProvider
06-01 15:50:30.795  3146  3323 D FileContentProvider: applying batch in provider com.owncloud.android.providers.FileContentProvider@368b490 (temporary: false)
06-01 15:50:31.038  3146  3323 D FileContentProvider: applied batch in provider com.owncloud.android.providers.FileContentProvider@368b490
06-01 15:50:31.092  3146  3323 D RefreshFolderOperation: Send broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED
06-01 15:50:31.095  3146  3146 D FileDisplayActivity: Received broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED
06-01 15:50:31.097  3146  3323 D OwnCloudClient #7: REQUEST GET /ocs/v2.php/apps/files_sharing/api/v1/shares
06-01 15:50:31.167  3146  3321 D FileDataStorageManager: Sending 38 operations to FileContentProvider
06-01 15:50:31.167  3146  3321 D FileContentProvider: applying batch in provider com.owncloud.android.providers.FileContentProvider@368b490 (temporary: false)
06-01 15:50:31.303  3146  3323 D GetRemoteSharesForFileOperation: Got 0 shares
06-01 15:50:31.364  3146  3321 D FileContentProvider: applied batch in provider com.owncloud.android.providers.FileContentProvider@368b490
06-01 15:50:31.429  3146  3323 D FileDataStorageManager: Sending 37 operations to FileContentProvider
06-01 15:50:31.429  3146  3323 D FileContentProvider: applying batch in provider com.owncloud.android.providers.FileContentProvider@368b490 (temporary: false)
06-01 15:50:31.445  3146  3146 D FileDisplayActivity: Setting progress visibility to true
06-01 15:50:31.445  3146  3321 D RefreshFolderOperation: Send broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED
06-01 15:50:31.449  3146  3321 D OwnCloudClient #7: REQUEST GET /ocs/v2.php/apps/files_sharing/api/v1/shares
06-01 15:50:31.605  3146  3323 D FileContentProvider: applied batch in provider com.owncloud.android.providers.FileContentProvider@368b490
06-01 15:50:31.605  3146  3323 D RefreshFolderOperation: Send broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_SHARES_SYNCED
06-01 15:50:31.627  3146  3321 D GetRemoteSharesForFileOperation: Got 0 shares
06-01 15:50:31.726  3146  3321 D FileDataStorageManager: Sending 37 operations to FileContentProvider
06-01 15:50:31.726  3146  3321 D FileContentProvider: applying batch in provider com.owncloud.android.providers.FileContentProvider@368b490 (temporary: false)
06-01 15:50:31.864  3146  3321 D FileContentProvider: applied batch in provider com.owncloud.android.providers.FileContentProvider@368b490
06-01 15:50:31.864  3146  3321 D RefreshFolderOperation: Send broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_SHARES_SYNCED
06-01 15:50:32.058  3146  3146 D FileDisplayActivity: Received broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED
06-01 15:50:32.137  3146  3146 D FileDisplayActivity: Setting progress visibility to true
06-01 15:50:32.137  3146  3146 I Choreographer: Skipped 41 frames!  The application may be doing too much work on its main thread.
06-01 15:50:32.276  3146  3146 D FileDisplayActivity: Received broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_SHARES_SYNCED
06-01 15:50:32.355  3146  3146 D FileDisplayActivity: Setting progress visibility to false
06-01 15:50:32.356  3146  3146 D FileDisplayActivity: Received broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_SHARES_SYNCED
06-01 15:50:32.433  3146  3146 D FileDisplayActivity: Setting progress visibility to false
06-01 15:50:33.301  3146  3329 D RefreshFolderOperation: Checking changes in jus@cloud.bitgrid.net/Shares/
06-01 15:50:33.306  3146  3329 D OwnCloudClient #7: REQUEST PROPFIND /remote.php/webdav/Shares/
06-01 15:50:33.424  3146  3329 I RefreshFolderOperation: Checked jus@cloud.bitgrid.net/Shares/ : changed
06-01 15:50:33.430  3146  3329 D OwnCloudClient #7: REQUEST PROPFIND /remote.php/webdav/Shares/
06-01 15:50:33.568  3146  3329 I ReadRemoteFolderOperation: Synchronized /Shares/: Operation finished with HTTP status code 207 (success)
06-01 15:50:33.568  3146  3329 D RefreshFolderOperation: Synchronizing jus@cloud.bitgrid.net/Shares/
06-01 15:50:33.577  3146  3329 D RefreshFolderOperation: Remote folder /Shares/ changed - starting update of local data 
06-01 15:50:33.591  3146  3329 D FileDataStorageManager: Saving folder /Shares/ with 10 children and 0 files to remove
06-01 15:50:33.623  3146  3329 D FileDataStorageManager: Sending 11 operations to FileContentProvider
06-01 15:50:33.623  3146  3329 D FileContentProvider: applying batch in provider com.owncloud.android.providers.FileContentProvider@368b490 (temporary: false)
06-01 15:50:33.663  3146  3329 D FileContentProvider: applied batch in provider com.owncloud.android.providers.FileContentProvider@368b490
06-01 15:50:33.702  3146  3329 D RefreshFolderOperation: Send broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED
06-01 15:50:33.705  3146  3146 D FileDisplayActivity: Received broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED
06-01 15:50:33.705  3146  3329 D OwnCloudClient #7: REQUEST GET /ocs/v2.php/apps/files_sharing/api/v1/shares
06-01 15:50:33.820  3146  3146 D FileDisplayActivity: Setting progress visibility to true
06-01 15:50:33.886  3146  3329 D GetRemoteSharesForFileOperation: Got 7 shares
06-01 15:50:33.931  3146  3329 D FileDataStorageManager: Sending 17 operations to FileContentProvider
06-01 15:50:33.931  3146  3329 D FileContentProvider: applying batch in provider com.owncloud.android.providers.FileContentProvider@368b490 (temporary: false)
06-01 15:50:34.099  3146  3329 D FileContentProvider: applied batch in provider com.owncloud.android.providers.FileContentProvider@368b490
06-01 15:50:34.099  3146  3329 D RefreshFolderOperation: Send broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_SHARES_SYNCED
06-01 15:50:34.177  3146  3146 D FileDisplayActivity: Received broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_SHARES_SYNCED
06-01 15:50:34.293  3146  3146 D FileDisplayActivity: Setting progress visibility to false
06-01 15:50:35.069  3146  3146 W art     : Before Android 4.1, method int android.support.v7.widget.DropDownListView.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
06-01 15:50:35.070  3146  3146 W art     : Before Android 4.1, method int android.support.v7.widget.MenuPopupWindow$MenuDropDownListView.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
06-01 15:50:36.460  3146  3146 V ArbitraryDataProvider: Adding arbitrary data with cloud id: jus@cloud.bitgrid.net key: folder_layout_11 value: GRID
06-01 15:50:36.571  3146  3146 D AndroidRuntime: Shutting down VM
06-01 15:50:36.584  3146  3146 E AndroidRuntime: FATAL EXCEPTION: main
06-01 15:50:36.584  3146  3146 E AndroidRuntime: Process: com.nextcloud.client, PID: 3146
06-01 15:50:36.584  3146  3146 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.support.v7.widget.GridLayoutManager.calculateItemBorders(GridLayoutManager.java:324)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.support.v7.widget.GridLayoutManager.calculateItemBorders(GridLayoutManager.java:309)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.support.v7.widget.GridLayoutManager.updateMeasurements(GridLayoutManager.java:280)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.support.v7.widget.GridLayoutManager.onAnchorReady(GridLayoutManager.java:355)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:581)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.view.View.layout(View.java:17538)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5616)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:606)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.view.View.layout(View.java:17538)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5616)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1191)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:876)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:895)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.view.View.layout(View.java:17538)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5616)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.view.View.layout(View.java:17538)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5616)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.view.View.layout(View.java:17538)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5616)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1730)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1496)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.view.View.layout(View.java:17538)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5616)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.view.View.layout(View.java:17538)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5616)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1171)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.view.View.layout(View.java:17538)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5616)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.view.View.layout(View.java:17538)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5616)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.view.View.layout(View.java:17538)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5616)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.view.View.layout(View.java:17538)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5616)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.view.View.layout(View.java:17538)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5616)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
06-01 15:50:36.584  3146  3146 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:724)
06-01 15:50:36.585  3146  3146 E AndroidRuntime: 	at android.view.View.layout(View.java:17538)
06-01 15:50:36.585  3146  3146 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5616)
06-01 15:50:36.585  3146  3146 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2354)
06-01 15:50:36.585  3146  3146 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2081)
06-01 15:50:36.585  3146  3146 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1258)
06-01 15:50:36.585  3146  3146 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6348)
06-01 15:50:36.585  3146  3146 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
06-01 15:50:36.585  3146  3146 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:683)
06-01 15:50:36.585  3146  3146 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:619)
06-01 15:50:36.585  3146  3146 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
06-01 15:50:36.585  3146  3146 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
06-01 15:50:36.585  3146  3146 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-01 15:50:36.585  3146  3146 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
06-01 15:50:36.585  3146  3146 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6123)
06-01 15:50:36.585  3146  3146 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-01 15:50:36.585  3146  3146 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
06-01 15:50:36.585  3146  3146 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

#### Nextcloud log (data/nextcloud.log)
```
Noting special in the Nextcloud log
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
```
static int[] calculateItemBorders(int[] cachedBorders, int spanCount, int totalSpace) {
        if (cachedBorders == null || cachedBorders.length != spanCount + 1
                || cachedBorders[cachedBorders.length - 1] != totalSpace) {
            cachedBorders = new int[spanCount + 1];
        }
        cachedBorders[0] = 0;
```

The last line is crashing when the array has a size of 0.
This only can happen if spanCount = -1, as then "new int[-1 + 1]" is created.

SpanCount is default to -1, but can also set manually, but then an IllegalArgumentException is thrown, if spanCount is <1:
```
public void setSpanCount(int spanCount) {
        if (spanCount == mSpanCount) {
            return;
        }
        mPendingSpanCountChange = true;
        if (spanCount < 1) {
            throw new IllegalArgumentException("Span count should be at least 1. Provided "
                    + spanCount);
        }
        mSpanCount = spanCount;
        mSpanSizeLookup.invalidateSpanIndexCache();
        requestLayout();
    }
```

So the only possible explanation for me is that spanCount is never ever updated, but remains the default value (-1).
This can also not be true, as we create GridLayoutManager here:
https://github.com/nextcloud/android/blob/48d437d376452448b12db709068d8d35b1d5aace/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java#L1146

and this calls "setSpanCount", which then sets mSpanCount or errors out if value is  < 1.

**Comment by Rickinfl** [comment]
I'm having the same issue. Tried to switch into grid view and app crashes. I can no longer get into that folder from my phone. All other folders work until I click that folder and app crashes

**Comment by juliushaertl** [comment]
@Rickinfl Maybe you can also try to get some debug information to see if it is the same issue: https://github.com/nextcloud/android#getting-debug-info-via-logcat

**Comment by jboschuk** [comment]
Also still having that issue.

**Comment by Gerii** [comment]
I "fixed" this issue by removing the app and reinstalling it - however, now I can't use /storage/emulated/0/nextcloud as my storage directory anymore.

**Comment by juliushaertl** [comment]
I cannot reproduce this anymore with the latest release. Seems fine now.

**Comment by Anrock** [comment]
What release is latest? Mine 3.4.1 still crashes
