### ISSUE TITLE
NullPointer when using different AccountType in another Flavor

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/android#2695]
### Actual behaviour
- One should be able to choose his account type free and build the app.

### Expected behaviour
- App crashes when manipulating the account type.
 
### Steps to reproduce
1. Create new flavor
2. Overwrite `account_type` in setup.xml
3. build and run the app -> Crashes with the following error message:

```
06-07 22:31:52.917 4997-4997/de.mytuxedo.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.mytuxedo.android, PID: 4997
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{de.mytuxedo.android/com.owncloud.android.authentication.AuthenticatorActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2679)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
        at android.content.ContextWrapper.getResources(ContextWrapper.java:89)
        at android.view.ContextThemeWrapper.getResourcesInternal(ContextThemeWrapper.java:127)
        at android.view.ContextThemeWrapper.getResources(ContextThemeWrapper.java:121)
        at android.support.v7.app.AppCompatActivity.getResources(AppCompatActivity.java:542)
        at com.owncloud.android.MainApp.getAccountType(MainApp.java:386)
        at com.owncloud.android.authentication.AuthenticatorActivity.<init>(AuthenticatorActivity.java:245)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1174)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2669)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
06-07 22:32:02.973 4997-5092/de.mytuxedo.android E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -19
06-07 22:32:02.974 4997-5092/de.mytuxedo.android E/EGL_emulation: tid 5092: swapBuffers(550): error 0x300d (EGL_BAD_SURFACE)
```

### Environment data
Android version: 8.1

Device model: emulated

Stock or customized system: stock

Nextcloud app version: master branch at bc374c8741b8edcdc1da67be38a6c09090303e06

I am sure, it did not happen with the master branch from 10 April 2018.

Hope it helps you.

**Comment by AndyScherzinger** [comment]
Hi @stefan-niedermann I am pretty sure you just ran into the context bug to be fixed via  #2689 which will also happen for any flavor if you either have a fresh installation or try to add another account. So this will be fixed soon :)

**Comment by stefan-niedermann** [comment]
Yes, indeed :)

Should i close this issue then in favor of #2687 or should it stay open?

**Comment by AndyScherzinger** [comment]
No need to close it. It'll auto close as soon as the PR got merged :)
