### ISSUE TITLE
Crash when sending non-existing log

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#283]
### Actual behaviour
-trying to send the log when it is "empty" which in this case rather means it is non-existing

### Expected behaviour
-do an index check and just ignore the send action
 
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.android.beta/com.owncloud.android.ui.activity.ReceiveExternalFilesActivity}: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2464)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524)
	at android.app.ActivityThread.access$900(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:234)
	at android.app.ActivityThread.main(ActivityThread.java:5526)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.somethingToUpload(ReceiveExternalFilesActivity.java:544)
	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.setAccount(ReceiveExternalFilesActivity.java:170)
	at com.owncloud.android.ui.activity.FileActivity.onCreate(FileActivity.java:160)
	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onCreate(ReceiveExternalFilesActivity.java:144)
	at android.app.Activity.performCreate(Activity.java:6285)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)
	... 9 more

************ DEVICE INFORMATION ***********
Brand: Sony
Device: D5803
Model: D5803
Id: 23.5.A.1.291
Product: D5803

************ FIRMWARE ************
SDK: 23
Release: 6.0.1
Incremental: 2769308465
```

**Comment by AndyScherzinger** [comment]
PR is #284
