### ISSUE TITLE
Sharing a link form the video player does not work

### ISSUE THREAD

**Issue by tilosp** [nextcloud/android#2941]
### Actual behaviour
- The app crashes

### Expected behaviour
- The share link dialog should open
 
### Steps to reproduce
1. Open a video
2. Click on "Send/Share" in the 3 dot menu
3. Click on link

### Environment data
Android version:
8.0

Device model: 
Emulator

Stock or customized system:
Stock

Nextcloud app version:
Current master

Nextcloud server version:
14 RC1

### Logs
```
FATAL EXCEPTION: main
                  Process: com.nextcloud.client, PID: 3305
                  java.lang.ClassCastException: com.owncloud.android.ui.preview.PreviewMediaFragment cannot be cast to com.owncloud.android.ui.fragment.FileDetailFragment
                      at com.owncloud.android.ui.activity.FileDisplayActivity.getShareFileFragment(FileDisplayActivity.java:2017)
                      at com.owncloud.android.ui.activity.FileDisplayActivity.onCreateShareViaLinkOperationFinish(FileDisplayActivity.java:1906)
                      at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoteOperationFinish(FileDisplayActivity.java:1766)
                      at com.owncloud.android.services.OperationsService$1.run(OperationsService.java:738)
                      at android.os.Handler.handleCallback(Handler.java:873)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:193)
                      at android.app.ActivityThread.main(ActivityThread.java:6669)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by tobiasKaminsky** [comment]
Works for me with latest master.

**Comment by tobiasKaminsky** [comment]
It is about sharing link, which indeeds get triggered, but not copied to clipboard.
