### ISSUE TITLE
Upload not working in stable; working in dev

### ISSUE THREAD

**Issue by lukebarone** [nextcloud/android#2955]
### Actual behaviour
- Nextcloud is installed on my server, behind Cloudflare. Starting around a month ago, photos stopped uploading. I cannot manually upload either.

### Expected behaviour
- Images should be uploaded
 
### Steps to reproduce
1. Take a picture while in Wi-Fi range
2. Attempt to upload the picture
3. Fail

### Environment data
Android version: 8.0.0

Device model: Asus Zenfone 3, Samsung Galaxy S8

Stock or customized system: Stock

Nextcloud app version: 3.2.3 (does not work) - 20180825 works

Nextcloud server version: 13.0.6

#### Web server error log
```
1.2.3.4 - lukebarone [03/Sep/2018:12:07:21 -0700] "GET /index.php/204 HTTP/1.1" 204 1363 "-" "Mozilla/5.0 (Android) ownCloud-android/3.2.3"
(above is repeated over and over again)
```

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"fzrDRiJJSiX3FUaPLF56","level":4,"time":"2018-09-03T18:32:36+00:00","remoteAddr":"50.69.222.79","user":"lukebarone","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/Photos\/\/2018\/08\/P_20180826_140731_vHDR_Auto.jpg-chunking-1545002089-4-0","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Message\":\"expected filesize 1024000 got 8192\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/cloud.lukebarone.ca\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(132): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #7)\\n#1 \\\/var\\\/www\\\/cloud.lukebarone.ca\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(156): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #7)\\n#2 \\\/var\\\/www\\\/cloud.lukebarone.ca\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1096): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('P_20180826_1407...', Resource id #7)\\n#3 \\\/var\\\/www\\\/cloud.lukebarone.ca\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(529): Sabre\\\\DAV\\\\Server->createFile('Photos\\\/2018\\\/08\\\/...', Resource id #7, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/cloud.lukebarone.ca\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/cloud.lukebarone.ca\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/www\\\/cloud.lukebarone.ca\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/cloud.lukebarone.ca\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/cloud.lukebarone.ca\\\/remote.php(164): require_once('\\\/var\\\/www\\\/cloud....')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/cloud.lukebarone.ca\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":443}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/3.2.3","version":"13.0.6.1"}
```

**Comment by lukebarone** [comment]
Issue present in 3.3.0 RC1 as well

**Comment by lukebarone** [comment]
Issue was relating to IPv6. Disabled on the server, then rebooted the phones to get them to work properly.
