### ISSUE TITLE
App crash: out of memory while browsing resized images

### ISSUE THREAD

**Issue by antonol68** [nextcloud/android#3019]
### Actual behaviour
- Tell us what happens
App crashes when browsing or rotating photos in full size
### Expected behaviour
- Tell us what should happen
 App should browse and rotate photos
### Steps to reproduce
1. Open app
2. Chose one photos folder
3. Browse or autorotate photos in full size

### Environment data
Android version:
5.0.1
Device model: 
Samsung Galaxy S4 VE (GT-I9515)
Stock or customized system:
Stock system
Nextcloud app version:
3.2.4
Nextcloud server version:
13.0.6
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
--------- beginning of system
E/art     ( 8643): Throwing OutOfMemoryError "Failed to allocate a 25165836 byte allocation with 11863052 free bytes and 11MB until OOM"
E/AndroidRuntime( 8643): FATAL EXCEPTION: main
E/AndroidRuntime( 8643): Process: com.nextcloud.client, PID: 8643
E/AndroidRuntime( 8643): java.lang.OutOfMemoryError: Failed to allocate a 25165836 byte allocation with 11863052 free bytes and 11MB until OOM
E/AndroidRuntime( 8643): 	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
E/AndroidRuntime( 8643): 	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
E/AndroidRuntime( 8643): 	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:752)
E/AndroidRuntime( 8643): 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:728)
E/AndroidRuntime( 8643): 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:766)
E/AndroidRuntime( 8643): 	at com.owncloud.android.ui.adapter.DiskLruImageCache.getBitmap(DiskLruImageCache.java:121)
E/AndroidRuntime( 8643): 	at com.owncloud.android.datamodel.ThumbnailsCacheManager.getBitmapFromDiskCache(ThumbnailsCacheManager.java:204)
E/AndroidRuntime( 8643): 	at com.owncloud.android.ui.preview.PreviewImageFragment.onStart(PreviewImageFragment.java:238)
E/AndroidRuntime( 8643): 	at android.support.v4.app.Fragment.performStart(Fragment.java:2372)
E/AndroidRuntime( 8643): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1467)
E/AndroidRuntime( 8643): 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
E/AndroidRuntime( 8643): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
E/AndroidRuntime( 8643): 	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
E/AndroidRuntime( 8643): 	at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3206)
E/AndroidRuntime( 8643): 	at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:206)
E/AndroidRuntime( 8643): 	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:605)
E/AndroidRuntime( 8643): 	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
E/AndroidRuntime( 8643): 	at com.owncloud.android.ui.activity.BaseActivity.onStart(BaseActivity.java:189)
E/AndroidRuntime( 8643): 	at com.owncloud.android.ui.activity.DrawerActivity.onStart(DrawerActivity.java:1348)
E/AndroidRuntime( 8643): 	at com.owncloud.android.ui.activity.FileActivity.onStart(FileActivity.java:188)
E/AndroidRuntime( 8643): 	at com.owncloud.android.ui.preview.PreviewImageActivity.onStart(PreviewImageActivity.java:166)
E/AndroidRuntime( 8643): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1234)
E/AndroidRuntime( 8643): 	at android.app.Activity.performStart(Activity.java:6329)
E/AndroidRuntime( 8643): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
E/AndroidRuntime( 8643): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767)
E/AndroidRuntime( 8643): 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4471)
E/AndroidRuntime( 8643): 	at android.app.ActivityThread.access$1000(ActivityThread.java:177)
E/AndroidRuntime( 8643): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1455)
E/AndroidRuntime( 8643): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 8643): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime( 8643): 	at android.app.ActivityThread.main(ActivityThread.java:5951)
E/AndroidRuntime( 8643): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8643): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 8643): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
E/AndroidRuntime( 8643): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
E/android.os.Debug(  919): ro.product_ship = true
E/android.os.Debug(  919): ro.debug_level = 0x4f4c
E/SQLiteLog( 7975): (284) automatic index on crash_info_summary(package_name_touched)
E/SMD     ( 8766): smd_init start 
E/SMD     ( 8766): smd Interface open failed errno is 2 -1
E/SMD     ( 8766): smd Interface open failed errno is 2 -1
E/OpenGLRenderer(  919): SFEffectCache:clear(), mSize = 0
E/ActivityManager(  919): checkUser: useridlist=null, currentuser=0
E/ActivityManager(  919): checkUser: useridlist=null, currentuser=0
E/ActivityManager(  919): checkUser: useridlist=null, currentuser=0
E/ActivityManager(  919): checkUser: useridlist=null, currentuser=0
E/Zygote  ( 8944): MountEmulatedStorage()
E/Zygote  ( 8944): v2
E/SELinux ( 8944): [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
E/ViewRootImpl(  919): sendUserActionEvent() mView == null
E/WifiStateMachine(  919): WifiStateMachine CMD_START_SCAN source 10014 txSuccessRate=111,29 rxSuccessRate=231,70 targetRoamBSSID=any RSSI=-63
E/SMD     ( 8766): smd Interface open failed errno is 2 -1
E/PersonaManagerService(  919): inState():  stateMachine is null !!
E/MTPRx   ( 8380): started activity for popup
E/Diag_Lib( 8990):  Diag_LSM_Init: Failed to open handle to diag driver, error = 2
E/SMD     ( 8766): smd Interface open failed errno is 2 -1
E/SettingsReceiverActivity( 8380): PREF_DONT_ASK_AGAIN : true
E/ActivityManager(  919): Invalid thumbnail dimensions: 576x576
E/SMD     ( 8766): smd Interface open failed errno is 2 -1
E/wpa_supplicant( 1429): Cmd 35609 not handled
E/SMD     ( 8766): smd Interface open failed errno is 2 -1
E/SMD     ( 8766): smd Interface open failed errno is 2 -1
E/SMD     ( 8766): smd Interface open failed errno is 2 -1
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
It says out of memory.
Is this happening on downloaded images or also on non-downloaded / resized images?

**Comment by antonol68** [comment]
This is happening only on non-downloaded after browsing 3 or 4 photos or rotating them

**Comment by tobiasKaminsky** [comment]
This is hard for me to to trigger.

What confuses me, is that this happens already on the resized images (~80kb) and while reading them from cache…

On next version we will use a different caching system, which then hopefully will not lead to such crashes.

**Comment by antonol68** [comment]
The problem still persist on 3.3.0 version.
