### ISSUE TITLE
Removing file crashes app.

### ISSUE THREAD

**Issue by Bubu** [nextcloud/android#31]
nextcloud fdroid beta, version 20160613
Trying to remove a file which is not synced locally produces the following result:

(Also I wanted to send the bug report generated by the app, but it doesn't provide an email address to send it to.)

```
************ CAUSE OF ERROR ************

android.content.res.Resources$NotFoundException: String resource ID #0x7f08017f
	at android.content.res.Resources.getText(Resources.java:336)
	at android.content.res.XResources.getText(XResources.java:1065)
	at android.content.res.Resources.getString(Resources.java:424)
	at android.support.v4.app.Fragment.getString(Fragment.java:661)
	at com.owncloud.android.ui.dialog.ConfirmationDialogFragment.onCreateDialog(ConfirmationDialogFragment.java:100)
	at com.owncloud.android.ui.dialog.RemoveFileDialogFragment.onCreateDialog(RemoveFileDialogFragment.java:77)
	at android.support.v4.app.DialogFragment.getLayoutInflater(DialogFragment.java:308)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)

************ DEVICE INFORMATION ***********
Brand: motorola
Device: condor_umts
Model: Moto E
Product: cm_condor

************ FIRMWARE ************
SDK: 23
Release: 6.0.1
```

**Comment by rhoeden** [comment]
Same issue here:

```
************ CAUSE OF ERROR ************
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getMimetype()' on a null object reference
at com.owncloud.android.ui.fragment.OCFileListFragment.checkSendable(OCFileListFragment.java:455)
at com.owncloud.android.ui.fragment.OCFileListFragment.access$400(OCFileListFragment.java:81)
at com.owncloud.android.ui.fragment.OCFileListFragment$10.onItemCheckedStateChanged(OCFileListFragment.java:400)
at android.widget.AbsListView$MultiChoiceModeWrapper.onItemCheckedStateChanged(AbsListView.java:6287)
at android.widget.AbsListView.confirmCheckedPositionsById(AbsListView.java:5327)
at android.widget.AbsListView.handleDataChanged(AbsListView.java:5348)
at android.widget.ListView.layoutChildren(ListView.java:1563)
at android.widget.AbsListView.onLayout(AbsListView.java:2148)
at android.view.View.layout(View.java:16639)
at android.view.ViewGroup.layout(ViewGroup.java:5437)
at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:584)
at android.view.View.layout(View.java:16639)
at android.view.ViewGroup.layout(ViewGroup.java:5437)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
at android.view.View.layout(View.java:16639)
at android.view.ViewGroup.layout(ViewGroup.java:5437)
at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
at android.view.View.layout(View.java:16639)
at android.view.ViewGroup.layout(ViewGroup.java:5437)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
at android.view.View.layout(View.java:16639)
at android.view.ViewGroup.layout(ViewGroup.java:5437)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1732)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
at android.view.View.layout(View.java:16639)
at android.view.ViewGroup.layout(ViewGroup.java:5437)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
at android.view.View.layout(View.java:16639)
at android.view.ViewGroup.layout(ViewGroup.java:5437)
at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
at android.view.View.layout(View.java:16639)
at android.view.ViewGroup.layout(ViewGroup.java:5437)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
at android.view.View.layout(View.java:16639)
at android.view.ViewGroup.layout(ViewGroup.java:5437)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
at android.view.View.layout(View.java:16639)
at android.view.ViewGroup.layout(ViewGroup.java:5437)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
at android.view.View.layout(View.java:16639)
at android.view.ViewGroup.layout(ViewGroup.java:5437)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
at android.view.View.layout(View.java:16639)
at android.view.ViewGroup.layout(ViewGroup.java:5437)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2934)
at android.view.View.layout(View.java:16639)
at android.view.ViewGroup.layout(ViewGroup.java:5437)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
at android.view.Choreographer.doCallbacks(Choreographer.java:670)
at android.view.Choreographer.doFrame(Choreographer.java:606)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5466)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

************ DEVICE INFORMATION ***********
Brand: google
Device: deb
Model: Nexus 7
Id: MMB29X
Product: razorg

************ FIRMWARE ************
SDK: 23
Release: 6.0.1
Incremental: 9380c47663
```

**Comment by tobiasKaminsky** [comment]
Thanks for reporting, I will have a look!

>(Also I wanted to send the bug report generated by the app, but it doesn't provide an email address to send it to.)

This is intentionally: the user should choose what he wants to do with the crash report.

**Comment by Bubu** [comment]
Thanks!
> This is intentionally: the user should choose what he wants to do with the crash report.

I've encountered similar behavior with OSMand and when I chose my email app as a target for the send bug-report intent it prefills an email address. So I can just review the report and hit send. Seemed easier than posting it to github from the phone :-).

**Comment by tobiasKaminsky** [comment]
Maybe for the contributor :) But not for us maintainer as we then have to make a guess out of the crash dump what happened and create an issue.
But you are right that there should also be an email address. I will have a look what we can do.

**Comment by tobiasKaminsky** [comment]
Fixed.
Will be tomorrow on fdroid or now in settings -> download latest beta version

**Comment by tobiasKaminsky** [comment]
@Bubu please confirm and then close it.

**Comment by Bubu** [comment]
Fixed in latest beta.
