### ISSUE TITLE
"expire_date" from "GET /ocs/v1.php/cloud/capabilities" not parseable

### ISSUE THREAD

**Issue by euku** [nextcloud/android#3164]
### Actual behaviour
When I connect to my smartphone via _adb logcat_ and open my app, I see a _JSONException_, because the server response does not seem to be right. The exception complains about this part: `"expire_date":{"enabled":true,"days":"admin","enforced":false}`
I am not sure about the impact of this. But actually I tried to debug other issues that could interfere with this...

### Expected behaviour
The value for "days" should be a number and make more sense, right? -> no exception
 
### Steps to reproduce
1. `adb logcat | grep "$(adb shell ps | grep com.nextcloud.client | awk '{print $2}')"`
2. open the Android app
3. open the root folder "all files" and take a look at the console on the computer

### Environment data
Android version: 6.0.1
Device model: Asus Zenfone 2 (ZE551ML Z00AD)
Stock or customized system: no
Nextcloud app version: 3.3.0
Nextcloud server version: 14.0.3.0

### Logcat
```
10-18 19:21:20.819  5015  9203 D OwnCloudClient #3: REQUEST GET /status.php
10-18 19:21:20.869  5015  5015 D ActivitiesActivity: onStop() ending
10-18 19:21:20.889  5015  5015 D ActivitiesActivity: onDestroy() ending
10-18 19:21:20.939  5015  9203 D UpdateOCVersionOperation: Got new OC version 14.0.3.0
10-18 19:21:20.939  5015  9203 I UpdateOCVersionOperation: Check for update of Nextcloud server version at https://private-xx/remote.php/webdav: Operation finished with HTTP status code -1 (success)
10-18 19:21:20.949  5015  9203 D OwnCloudClient #3: REQUEST GET /ocs/v1.php/cloud/capabilities
10-18 19:21:21.039  5015  9203 D GetRemoteCapabilitiesOperation: Successful response: {"ocs":{"meta":{"status":"ok","statuscode":100,"message":"OK","totalitems":"","itemsperpage":""},"data":{"version":{"major":14,"minor":0,"micro":3,"string":"14.0.3","edition":""},"capabilities":{"core":{"pollinterval":60,"webdav-root":"remote.php\/webdav"},"bruteforce":{"delay":0},"activity":{"apiv2":["filters","filters-api","previews","rich-strings"]},"ocm":{"enabled":true,"apiVersion":"1.0-proposal1","endPoint":"https:\/\/private-xx\/ocm","shareTypes":[{"name":"file","protocols":{"webdav":"\/public.php\/webdav\/"}}]},"dav":{"chunking":"1.0"},"files_sharing":{"api_enabled":true,"public":{"enabled":true,"password":{"enforced":false},"expire_date":{"enabled":true,"days":"admin","enforced":false},"send_mail":false,"upload":true,"upload_files_drop":true},"resharing":true,"user":{"send_mail":false,"expire_date":{"enabled":true}},"group_sharing":true,"group":{"enabled":true,"expire_date":{"enabled":true}},"default_permissions":31,"federation":{"outgoing":true,"incoming":true,"expire_date":{"enabled":true}},"sharebymail":{"enabled":true,"upload_files_drop":{"enabled":true},"password":{"enabled":true},"expire_date":{"enabled":true}}},"notifications":{"ocs-endpoints":["list","get","delete","delete-all","icons","rich-strings"],"push":["devices","object-data"],"admin-notifications":["ocs","cli"]},"password_policy":{"minLength":8,"enforceNonCommonPassword":true,"enforceNumericCharacters":true,"enforceSpecialCharacters":false,"enforceUpperLowerCase":true},"theming":{"name":"Nextcloud","url":"https:\/\/private-xx","slogan":"ein sicherer Ort f\u00fcr all Deine Daten","color":"#0082c9","color-text":"#ffffff","color-element":"#0082c9","logo":"https:\/\/private-xx\/core\/img\/logo.svg?v=1","background":"https:\/\/private-xx\/core\/img\/background.png?v=1","background-plain":false,"background-default":true},"files":{"bigfilechunking":true,"blacklisted_files":[".htaccess"],"undelete":true,"versioning":true}}}}}
10-18 19:21:21.039  5015  9203 D GetRemoteCapabilitiesOperation: *** Added version
10-18 19:21:21.039  5015  9203 D GetRemoteCapabilitiesOperation: *** Added core
10-18 19:21:21.039  5015  9203 E GetRemoteCapabilitiesOperation: Exception while getting capabilities
10-18 19:21:21.039  5015  9203 E GetRemoteCapabilitiesOperation: org.json.JSONException: Value admin at days of type java.lang.String cannot be converted to int
10-18 19:21:21.039  5015  9203 E GetRemoteCapabilitiesOperation: 	at org.json.JSON.typeMismatch(JSON.java:100)
10-18 19:21:21.039  5015  9203 E GetRemoteCapabilitiesOperation: 	at org.json.JSONObject.getInt(JSONObject.java:481)
10-18 19:21:21.039  5015  9203 E GetRemoteCapabilitiesOperation: 	at com.owncloud.android.lib.resources.status.GetRemoteCapabilitiesOperation.run(GetRemoteCapabilitiesOperation.java:235)
10-18 19:21:21.039  5015  9203 E GetRemoteCapabilitiesOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:145)
10-18 19:21:21.039  5015  9203 E GetRemoteCapabilitiesOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:149)
10-18 19:21:21.039  5015  9203 E GetRemoteCapabilitiesOperation: 	at com.owncloud.android.operations.GetCapabilitiesOperation.run(GetCapabilitiesOperation.java:36)
10-18 19:21:21.039  5015  9203 E GetRemoteCapabilitiesOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:121)
10-18 19:21:21.039  5015  9203 E GetRemoteCapabilitiesOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:125)
10-18 19:21:21.039  5015  9203 E GetRemoteCapabilitiesOperation: 	at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:72)
10-18 19:21:21.039  5015  9203 E GetRemoteCapabilitiesOperation: 	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:251)
10-18 19:21:21.039  5015  9203 E GetRemoteCapabilitiesOperation: 	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:235)
10-18 19:21:21.039  5015  9203 E GetRemoteCapabilitiesOperation: 	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:187)
10-18 19:21:21.039  5015  9203 E GetRemoteCapabilitiesOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:316)
10-18 19:21:21.039  5015  9203 E GetRemoteCapabilitiesOperation: 	at java.lang.Thread.run(Thread.java:818)
10-18 19:21:21.039  5015  9203 W RefreshFolderOperation: Update Capabilities unsuccessfully
```

**Comment by tobiasKaminsky** [comment]
This is strange, expiry_date is giving me a number value:

```
"files_sharing": {
					"api_enabled": true,
					"public": {
						"enabled": true,
						"password": {
							"enforced": true
						},
						"expire_date": {
							"enabled": true,
							"days": "7",
							"enforced": true
						},
``` 

What have you specified here, at admin -> sharing
![image](https://user-images.githubusercontent.com/5836855/47212584-ee38f500-d398-11e8-81a9-3050c96aa640.png)

--> I assume that there is a non-numeric value in it…
