### ISSUE TITLE
Auto upload of photos fail everytime due to unexpected size

### ISSUE THREAD

**Issue by spacecowboy** [nextcloud/android#3400]
### Actual behaviour

- App fails to auto upload photos - consistently. It fails pretty much for every picture taken.

### Expected behaviour
- App should successfully auto upload photos
 
### Steps to reproduce
1. Take photo
2. Wait for auto upload
3. See notification saying `Upload failed`

### Additional information

Appears to happen only when I am on my home WiFi - in which case the connection will still go via the router (domain name routes to external IP address - router has a firewall rule specified in the internal network to route to the Nextcloud computer just like externally)

### Environment data
Android version: 9

Device model: Oneplus 6 (A6003)

Stock or customized system: Stock Oxygen OS (default on Oneplus devices)

Nextcloud app version: `3.3.2`

Nextcloud server version: `14.0.4`

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"R35pOrS5mIQ79FDw2bhg","level":4,"time":"2018-03-18T13:07:32+00:00","remoteAddr":"999.999.999.999","user":"user","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/InstantUpload\/Camera\/IMG_20180318_140707.jpg-chunking-1555193144-5-0","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Message\":\"expected filesize 1024000 got 98304\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(105): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #73)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(151): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #73)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1096): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('IMG_20180318_14...', Resource id #73)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('InstantUpload\\\/C...', Resource id #73, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(76): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/nextcl...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":415}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/3.0.3","version":"12.0.3.3"}
{"reqId":"WhHcVHXkyifGH03mnAc1","level":4,"time":"2018-03-18T14:36:04+00:00","remoteAddr":"999.999.999.999","user":"user","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/InstantUpload\/Camera\/IMG_20180318_140707.jpg-chunking-1555193144-5-3","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Message\":\"expected filesize 1024000 got 262144\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(105): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #73)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(151): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #73)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1096): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('IMG_20180318_14...', Resource id #73)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('InstantUpload\\\/C...', Resource id #73, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(76): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/nextcl...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":415}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/3.0.3","version":"12.0.3.3"}
```

**Comment by spacecowboy** [comment]
Just noted logs are **old**. Probably seeing some kind of routing issue. Closing this.
