### ISSUE TITLE
Crashes potentially related to Auto Upload

### ISSUE THREAD

**Issue by jvolker** [nextcloud/android#3557]
### Actual behaviour
- The app hangs and crashes. 100% fail rate when I try to access auto upload.
- After opening the app my phone restarted.

### Expected behaviour
- No hangs, no crashes.
 
### Steps to reproduce
1. Open the app and wait.
2. Or open the app and try to access auto upload.

### Environment data
Android version: 8.0.0

Device model: Samsung Galaxy S7 (SM-G930F)

Stock or customized system: Stock

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by tobiasKaminsky** [comment]
```
60  4517 E Parcel  : Class not found when unmarshalling: com.owncloud.android.datamodel.OCFile
02-07 16:30:23.615  3660  4517 E Parcel  : java.lang.ClassNotFoundException: com.owncloud.android.datamodel.OCFile
02-07 16:30:23.615  3660  4517 E Parcel  : 	at java.lang.Class.classForName(Native Method)
02-07 16:30:23.615  3660  4517 E Parcel  : 	at java.lang.Class.forName(Class.java:453)
02-07 16:30:23.615  3660  4517 E Parcel  : 	at android.os.Parcel.readParcelableCreator(Parcel.java:2843)
02-07 16:30:23.615  3660  4517 E Parcel  : 	at android.os.Parcel.readParcelable(Parcel.java:2797)
02-07 16:30:23.615  3660  4517 E Parcel  : 	at android.os.Parcel.readValue(Parcel.java:2700)
02-07 16:30:23.615  3660  4517 E Parcel  : 	at android.os.Parcel.readArrayMapInternal(Parcel.java:3067)
02-07 16:30:23.615  3660  4517 E Parcel  : 	at android.os.BaseBundle.unparcel(BaseBundle.java:257)
02-07 16:30:23.615  3660  4517 E Parcel  : 	at android.os.BaseBundle.getString(BaseBundle.java:1086)
02-07 16:30:23.615  3660  4517 E Parcel  : 	at android.content.Intent.getStringExtra(Intent.java:7706)
02-07 16:30:23.615  3660  4517 E Parcel  : 	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:468)
02-07 16:30:23.615  3660  4517 E Parcel  : 	at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:419)
02-07 16:30:23.615  3660  4517 E Parcel  : 	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1308)
02-07 16:30:23.615  3660  4517 E Parcel  : 	at com.android.server.am.ActivityManagerService.startActivityInPackage(ActivityManagerService.java:6592)
02-07 16:30:23.615  3660  4517 E Parcel  : 	at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:393)
02-07 16:30:23.615  3660  4517 E Parcel  : 	at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:263)
02-07 16:30:23.615  3660  4517 E Parcel  : 	at com.android.server.am.PendingIntentRecord.sendWithResult(PendingIntentRecord.java:255)
02-07 16:30:23.615  3660  4517 E Parcel  : 	at com.android.server.am.ActivityManagerService.sendIntentSender(ActivityManagerService.java:9946)
02-07 16:30:23.615  3660  4517 E Parcel  : 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4168)
02-07 16:30:23.615  3660  4517 E Parcel  : 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3863)
02-07 16:30:23.615  3660  4517 E Parcel  : 	at android.os.Binder.execTransact(Binder.java:682)
02-07 16:30:23.615  3660  4517 E Parcel  : Caused by: java.lang.ClassNotFoundException: com.owncloud.android.datamodel.OCFile
02-07 16:30:23.615  3660  4517 E Parcel  : 	at java.lang.Class.classForName(Native Method)
02-07 16:30:23.615  3660  4517 E Parcel  : 	at java.lang.BootClassLoader.findClass(ClassLoader.java:1355)
02-07 16:30:23.615  3660  4517 E Parcel  : 	at java.lang.BootClassLoader.loadClass(ClassLoader.java:1415)
02-07 16:30:23.615  3660  4517 E Parcel  : 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
02-07 16:30:23.615  3660  4517 E Parcel  : 	... 20 more
```

Never ever saw this before. This class OCFile is essential to the whole app. I have no idea why this is not found by Android.

**Comment by jvolker** [comment]
Is there anything I can help with on this bug? I am still experiencing the issue which is making the app unusable for me.

Is there any way I might be able to fix the issue myself? I think I tried reinstalling before and it didn't help.
