### ISSUE TITLE
IT tests fail due to AppPreferences

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#3728]
```
    java.lang.NullPointerException: Attempt to invoke interface method 'int com.nextcloud.client.preferences.AppPreferences.getLastSeenVersionCode()' on a null object reference
        at com.owncloud.android.MainApp.fixStoragePath(MainApp.java:249)
        at com.owncloud.android.MainApp.onCreate(MainApp.java:134)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at androidx.test.runner.MonitoringInstrumentation.callApplicationOnCreate(MonitoringInstrumentation.java:413)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
```

This is what I get when I run a single test, e.g. FileIT->testCreateFolder() and look into logcat.

@ezaquarii if you have time and want to look into it
Othewrise I'll have a look at monday.

**Comment by ezaquarii** [comment]
Sure, I'll take a look.
