### ISSUE TITLE
App crash on startup

### ISSUE THREAD

**Issue by thrillfall** [nextcloud/android#3739]
### Actual behaviour
- I open the app and it instantly crashes

### Expected behaviour
- I open the app and see my files.
### Steps to reproduce
1. open appp
2. crash

``
### Environment data
Android version: LineageOS15.1

Device model: Samsung A3

Stock or customized system: Lineageos

Nextcloud app version: dev 20190309

Nextcloud server version: 15.0.2

#### Nextcloud log (data/nextcloud.log)
```
03-11 13:22:24.313 14995 14995 E FileDisplayActivity: Access to unexisting list of files fragment!!
03-11 13:22:24.314 14995 14995 E FileDisplayActivity: Still have a chance to lose the initializacion of list fragment >(
03-11 13:22:24.375 14995 15036 D ExternalLinks: links disabled
03-11 13:22:24.414 14995 15038 D OwnCloudClient #7: REQUEST GET /ocs/v1.php/cloud/users/one
03-11 13:22:24.485 14995 14995 E FileDisplayActivity: Access to unexisting list of files fragment!!
03-11 13:22:24.486  2861  2870 I zygote  : Background concurrent copying GC freed 76902(3MB) AllocSpace objects, 26(828KB) LOS objects, 42% free, 14MB/25MB, paused 218us total 179.217ms
03-11 13:22:24.490 14995 14995 V FileDisplayActivity: onResume() start
03-11 13:22:24.490 14995 14995 D FileDisplayActivity: onResume() starting
03-11 13:22:24.507 14995 14995 I OCFileListFragment: onAttach
03-11 13:22:24.515 14995 14995 I OCFileListFragment: onCreateView() start
03-11 13:22:24.515 14995 14995 D ExtendedListFragment: onCreateView
03-11 13:22:24.546 14995 14995 I zygote  : Deoptimizing void androidx.appcompat.view.menu.MenuBuilder.dispatchPresenterUpdate(boolean) due to JIT inline cache
03-11 13:22:24.576 14995 14995 I zygote  : Deoptimizing int androidx.recyclerview.widget.RecyclerView$5.getChildCount() due to JIT inline cache
03-11 13:22:24.613 14995 14995 I OCFileListFragment: onCreateView() end
03-11 13:22:24.613 14995 14995 I OCFileListFragment: onActivityCreated() start
03-11 13:22:24.754 14995 14995 V FileDisplayActivity: onResume() end
03-11 13:22:24.760 14995 15040 D OpenGLRenderer: HWUI GL Pipeline
03-11 13:22:24.766 14995 14995 D OperationsService: Creating service
03-11 13:22:24.768 14995 14995 D FileDownloader: Creating service
03-11 13:22:24.780 14995 14995 D FileUploader: Creating service
03-11 13:22:24.787 14995 14995 V UploadsStorageManager: Updating state of any killed upload
03-11 13:22:24.790 14995 14995 V UploadsStorageManager: No upload was killed
03-11 13:22:24.864 14995 15040 I com.nextcloud.android.beta: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
03-11 13:22:24.864 14995 15040 I OpenGLRenderer: Initialized EGL, version 1.4
03-11 13:22:24.864 14995 15040 D OpenGLRenderer: Swap behavior 1
03-11 13:22:24.869 14995 15040 D mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [720x1280]-format:1
03-11 13:22:24.896 14995 14995 D AndroidRuntime: Shutting down VM
03-11 13:22:24.897 14995 14995 E AndroidRuntime: FATAL EXCEPTION: main
03-11 13:22:24.897 14995 14995 E AndroidRuntime: Process: com.nextcloud.android.beta, PID: 14995
03-11 13:22:24.897 14995 14995 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at com.owncloud.android.ui.adapter.OCFileListAdapter.onBindViewHolder(OCFileListAdapter.java:328)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1183)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:870)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:889)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1780)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1546)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.View.layout(View.java:19659)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6075)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:658)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
03-11 13:22:24.897 14995 14995 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
03-11 13:22:24.900  2861  2991 W ActivityManager:   Force finishing activity com.nextcloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity
```

**Comment by tobiasKaminsky** [comment]
Can you test it with the latest dev version (20190312)?
I think this is already fixed.

**Comment by thrillfall** [comment]
it also crashes with 20190312 with the same stacktrace

**Comment by tobiasKaminsky** [comment]
Ah, then I fear that the database is corrupted due to the one non-working dev version.
A re-installation should help… :-S

**Comment by thrillfall** [comment]
Reinstalling "solved" it. But good to know that in the background the file auto-upload still worked
