### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by cwmke** [nextcloud/android#380]
### Actual behaviour
nextCloud Beta crashes in the background or with the app open. The app appears to be updating the files but never stops. This does not occur in the non-beta app.

### Expected behaviour
Files update and the app goes into a passive state.
 
### Steps to reproduce
Not positive of steps but believe this to be it.
1. Share a folder with content with another owncloud user.
2. This folder is synced with a desktop client.
3. Delete the folder from the desktop client without unsharing first.
4. Open the Beta app and go to the directory where the deleted folder is.
5. Wait 3-5 minutes and crash.

### Environment data
Android version: 7.0

Device model: Nexus 6P Angler

Stock or customized system: Customized CopperheadOS

Nextcloud app version: F-Droid Beta 20161111

Nextcloud server version: 10.0.1 (stable)

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Couldn't read row 1643, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:511)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:146)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:152)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:95)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:311)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:549)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:316)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:438)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:405)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:444)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:317)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:197)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:271)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:347)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:291)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:347)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:291)
	at com.owncloud.android.syncadapter.FileSyncAdapter.onPerformSync(FileSyncAdapter.java:179)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)

************ DEVICE INFORMATION ***********
Brand: Android
Device: angler
Model: Nexus 6P
Id: NBD91P
Product: aosp_angler

************ FIRMWARE ************
SDK: 24
Release: 7.0
Incremental: 2016.11.10.09.53.38
```

**Comment by tobiasKaminsky** [comment]
Is this still happening?

**Comment by cwmke** [comment]
I just went through the steps and was unable to reproduce so I'll close this.
