### ISSUE TITLE
Crash when opening text file

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#3809]
- open text file
- app crashes

latest master
Android 9 emulator 

```
019-03-29 12:57:13.435 13397-13397/com.nextcloud.client E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nextcloud.client, PID: 13397
    java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.widget.SearchView.setOnQueryTextListener(androidx.appcompat.widget.SearchView$OnQueryTextListener)' on a null object reference
        at com.owncloud.android.ui.preview.PreviewTextFragment$TextLoadAsyncTask.onPostExecute(PreviewTextFragment.java:323)
        at com.owncloud.android.ui.preview.PreviewTextFragment$TextLoadAsyncTask.onPostExecute(PreviewTextFragment.java:256)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.access$600(AsyncTask.java:180)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by tobiasKaminsky** [comment]
Tried it again and cannot reproduce it.
