### ISSUE TITLE
1.4.0 RC2 - App crashing after taking a photo on Android < 7

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#388]
From Google Play Developer Console:

* APP crash after making a photo
* im rc2 ist jetzt photoupload wieder vorhanden. nachdem das aktiviert wurde und ein Photo gemacht wird , stürzt die nextcloud App ab

```
java.lang.RuntimeException: Unable to start receiver com.owncloud.android.files.InstantUploadBroadcastReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2766)
	at android.app.ActivityThread.-wrap14(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at com.owncloud.android.files.InstantUploadBroadcastReceiver.handleNewPictureAction(InstantUploadBroadcastReceiver.java:134)
	at com.owncloud.android.files.InstantUploadBroadcastReceiver.onReceive(InstantUploadBroadcastReceiver.java:65)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2759)
	... 8 more
```

```
java.lang.RuntimeException: Unable to start receiver com.owncloud.android.files.InstantUploadBroadcastReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3642)
	at android.app.ActivityThread.access$2000(ActivityThread.java:222)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1877)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at com.owncloud.android.files.InstantUploadBroadcastReceiver.handleNewPictureAction(InstantUploadBroadcastReceiver.java:134)
	at com.owncloud.android.files.InstantUploadBroadcastReceiver.onReceive(InstantUploadBroadcastReceiver.java:65)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3635)
	... 8 more
```

**Comment by tobiasKaminsky** [comment]
I think this is related to the (wrong) deletion of the instant preferences in RC1.
This should therefore be fixed by RC2 as there the instant upload preferences are deleted only on Nougat (where it is intended).

**Comment by AndyScherzinger** [comment]
fixed via #389
