### ISSUE TITLE
java.lang.SecurityException in DocumentsProvider

### ISSUE THREAD

**Issue by jmue** [nextcloud/android#3902]
### Actual behaviour
- image thumbnails are not shown in DocumentsUI/StoragePicker as a result of java.lang.SecurityException

### Expected behaviour
- no crash should happen
 
### Steps to reproduce
1. Navigate to a folder containing images with DocumentsUI/StoragePicker

### Environment data
Android version: 8.1

Device model: Android Emulator

Stock or customized system:

Nextcloud app version: dev-20190414

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
2019-04-15 13:08:49.233 27887-27961/com.nextcloud.client E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: Permission Denial: reading com.owncloud.android.providers.FileContentProvider uri content://org.nextcloud/arbitrary_data from pid=28010, uid=10010 requires false, or grantUriPermission()
        at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:631)
        at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:501)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:213)
        at android.content.ContentResolver.query(ContentResolver.java:754)
        at android.content.ContentResolver.query(ContentResolver.java:704)
        at android.content.ContentResolver.query(ContentResolver.java:662)
        at com.owncloud.android.datamodel.ArbitraryDataProvider.getValue(ArbitraryDataProvider.java:163)
        at com.owncloud.android.datamodel.ArbitraryDataProvider.getBooleanValue(ArbitraryDataProvider.java:119)
        at com.owncloud.android.datamodel.ArbitraryDataProvider.getBooleanValue(ArbitraryDataProvider.java:123)
        at com.owncloud.android.authentication.AccountUtils.getCurrentOwnCloudAccount(AccountUtils.java:93)
        at com.owncloud.android.providers.DiskLruImageCacheFileProvider.getFile(DiskLruImageCacheFileProvider.java:57)
        at com.owncloud.android.providers.DiskLruImageCacheFileProvider.openFile(DiskLruImageCacheFileProvider.java:66)
        at android.content.ContentProvider.openAssetFile(ContentProvider.java:1543)
        at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1723)
        at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1789)
        at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:423)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1410)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1247)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1170)
        at com.owncloud.android.providers.DocumentsStorageProvider.openDocumentThumbnail(DocumentsStorageProvider.java:335)
        at android.provider.DocumentsProvider.openTypedAssetFileImpl(DocumentsProvider.java:1305)
        at android.provider.DocumentsProvider.openTypedAssetFile(DocumentsProvider.java:1241)
        at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:423)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:302)
        at android.os.Binder.execTransact(Binder.java:697)
2019-04-15 13:08:49.278 27887-27961/com.nextcloud.client E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: Permission Denial: reading com.owncloud.android.providers.FileContentProvider uri content://org.nextcloud/arbitrary_data from pid=28010, uid=10010 requires false, or grantUriPermission()
        at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:631)
        at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:501)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:213)
        at android.content.ContentResolver.query(ContentResolver.java:754)
        at android.content.ContentResolver.query(ContentResolver.java:704)
        at android.content.ContentResolver.query(ContentResolver.java:662)
        at com.owncloud.android.datamodel.ArbitraryDataProvider.getValue(ArbitraryDataProvider.java:163)
        at com.owncloud.android.datamodel.ArbitraryDataProvider.getBooleanValue(ArbitraryDataProvider.java:119)
        at com.owncloud.android.datamodel.ArbitraryDataProvider.getBooleanValue(ArbitraryDataProvider.java:123)
        at com.owncloud.android.authentication.AccountUtils.getCurrentOwnCloudAccount(AccountUtils.java:93)
        at com.owncloud.android.providers.DiskLruImageCacheFileProvider.getFile(DiskLruImageCacheFileProvider.java:57)
        at com.owncloud.android.providers.DiskLruImageCacheFileProvider.openFile(DiskLruImageCacheFileProvider.java:66)
        at android.content.ContentProvider.openAssetFile(ContentProvider.java:1543)
        at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1723)
        at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1789)
        at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:423)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1410)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1247)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1170)
        at com.owncloud.android.providers.DocumentsStorageProvider.openDocumentThumbnail(DocumentsStorageProvider.java:335)
        at android.provider.DocumentsProvider.openTypedAssetFileImpl(DocumentsProvider.java:1305)
        at android.provider.DocumentsProvider.openTypedAssetFile(DocumentsProvider.java:1241)
        at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:423)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:302)
        at android.os.Binder.execTransact(Binder.java:697)
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Pinging @tobiasKaminsky for his doc provider knowledge 💪

**Comment by jmue** [comment]
This one was fixed recently on master. I think the bug-item can be closed.
