### ISSUE TITLE
Crash on sharing to app

### ISSUE THREAD

**Issue by Bubu** [nextcloud/android#41]
Version: `20160617` from fdroid
When sending a file from the file manager to nextcloud I get the following error:

```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.android.beta/com.owncloud.android.ui.activity.ReceiveExternalFilesActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
	at android.support.v7.app.AppCompatDelegateImplV7.setSupportActionBar(AppCompatDelegateImplV7.java:198)
	at android.support.v7.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:99)
	at com.owncloud.android.ui.activity.ToolbarActivity.setupToolbar(ToolbarActivity.java:52)
	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.populateDirectoryList(ReceiveExternalFilesActivity.java:384)
	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onAccountSet(ReceiveExternalFilesActivity.java:201)
	at com.owncloud.android.ui.activity.BaseActivity.onStart(BaseActivity.java:189)
	at com.owncloud.android.ui.activity.FileActivity.onStart(FileActivity.java:177)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
	at android.app.Activity.performStart(Activity.java:6268)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
	... 10 more

************ DEVICE INFORMATION ***********
Brand: motorola
Device: condor_umts
Model: Moto E
Id: MOB30J
Product: cm_condor

************ FIRMWARE ************
SDK: 23
Release: 6.0.1
Incremental: a804b51831
```

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger can you have a look here?

**Comment by AndyScherzinger** [comment]
see https://github.com/nextcloud/android/commit/e43f9db36bd43b5e63b6c87e6705d7e0702ccc33
should be fixed in beta (tested on my device) and is also fixed on the feature branch.

Just FYI @tobiasKaminsky  for some reason account switching seems to be broken on the beta branch but works perfectly fine on the feature branch 0_o

**Comment by AndyScherzinger** [comment]
Also happened for the internal upload view, see stack trace which only happened in the beta not on the feature branch https://github.com/nextcloud/android/commit/6afb5b6a01539b26c60b12b542c7d90dc4256866 This introduced the need of some more tests but I pushed the fix for now so it is present.


```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.android.beta/com.owncloud.android.ui.activity.UploadPathActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
at android.support.v7.app.AppCompatDelegateImplV7.setSupportActionBar(AppCompatDelegateImplV7.java:198)
at android.support.v7.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:99)
at com.owncloud.android.ui.activity.ToolbarActivity.setupToolbar(ToolbarActivity.java:52)
at com.owncloud.android.ui.activity.FolderPickerActivity.onCreate(FolderPickerActivity.java:98)
at com.owncloud.android.ui.activity.UploadPathActivity.onCreate(UploadPathActivity.java:38)
at android.app.Activity.performCreate(Activity.java:6245)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
... 10 more

************ DEVICE INFORMATION ***********
Brand: motorola
Device: osprey_umts
Model: MotoG3
Id: MPI24.65-33
Product: osprey_reteu

************ FIRMWARE ************
SDK: 23
Release: 6.0
Incremental: 35
```

**Comment by AndyScherzinger** [comment]
...so we might need yet another beta release in the near future :disappointed:

**Comment by tobiasKaminsky** [comment]
So I release a beta :+1:

**Comment by tobiasKaminsky** [comment]
@Bubu please try it tomorrow and close if it works

**Comment by AndyScherzinger** [comment]
@Bubu is this issue fixed for you with the latest beta release?

**Comment by Bubu** [comment]
Just tested it and it's fixed for me, thanks :-).

**Comment by AndyScherzinger** [comment]
Glad we could fix it for you (and others of course)! :)
