### ISSUE TITLE
Error opening folder

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#410]
Via Google Play developer console reported for RC2:

--> Nextcloud app beendet sich sobald ich einen Ordner öffnen der geshared ist

```
java.lang.IllegalArgumentException: Empty values
	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1680)
	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1660)
	at com.owncloud.android.providers.FileContentProvider.updateFilesTableAccordingToShareInsertion(FileContentProvider.java:349)
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:283)
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:227)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:245)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:549)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:301)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:402)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:1297)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveSharesInFolder(FileDataStorageManager.java:1484)
	at com.owncloud.android.operations.RefreshFolderOperation.refreshSharesForFolder(RefreshFolderOperation.java:504)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:216)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:303)
	at java.lang.Thread.run(Thread.java:818)
```

### Environment data
Android version: Android 5.1

Device model: Galaxy S5 Mini (kminilte) 

Stock or customized system: stock

Nextcloud app version: 1.4.0 RC2

**Comment by AndyScherzinger** [comment]
fixed via #492
