### ISSUE TITLE
"could not find host" on login

### ISSUE THREAD

**Issue by charlag** [nextcloud/android#4130]
Hey, thanks for the app.

I cannot log into my Nextcloud instance (which is at home but accessible from the outside). It is behind Nginx. I can normally access it from my laptop and also can open it in mobile browser but app fails to log in with such a log:

<details>
<summary>
log
</summary>

```
2019-06-09 20:23:46.950 5756-5846/com.nextcloud.client D/NetworkUtils: Searching known-servers store at /data/user/0/com.nextcloud.client/files/knownServers.bks
2019-06-09 20:23:46.952 5756-5846/com.nextcloud.client D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
2019-06-09 20:23:46.964 5756-5846/com.nextcloud.client D/OwnCloudClient #0: Creating OwnCloudClient
2019-06-09 20:23:46.964 5756-5846/com.nextcloud.client D/AccountUtils: Restoring cookies for null
2019-06-09 20:23:46.992 5756-5846/com.nextcloud.client D/OwnCloudClient #0: REQUEST GET /status.php
2019-06-09 20:23:46.998 5756-5846/com.nextcloud.client D/AdvancedSslSocketFactory: Creating SSL Socket with remote my.serv.er:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@a3eda1d
2019-06-09 20:23:46.999 5756-5846/com.nextcloud.client D/AdvancedSslSocketFactory:  ... with connection timeout 50000 and socket timeout 50000
2019-06-09 20:23:47.049 5756-5846/com.nextcloud.client I/ServerNameIndicator: SSLSocket implementation: com.android.org.conscrypt.ConscryptFileDescriptorSocket
2019-06-09 20:23:47.049 5756-5846/com.nextcloud.client I/ServerNameIndicator: SNI done, hostname: my.serv.er
2019-06-09 20:23:48.060 5756-5846/com.nextcloud.client I/HttpMethodDirector: I/O exception (java.net.ConnectException) caught when processing request: failed to connect to my.serv.er/185.251.103.41 (port 443) from /192.168.0.5 (port 43562) after 50000ms: isConnected failed: ECONNREFUSED (Connection refused)
2019-06-09 20:23:48.061 5756-5846/com.nextcloud.client I/HttpMethodDirector: Retrying request
2019-06-09 20:23:48.061 5756-5846/com.nextcloud.client D/AdvancedSslSocketFactory: Creating SSL Socket with remote my.serv.er:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@a3eda1d
2019-06-09 20:23:48.061 5756-5846/com.nextcloud.client D/AdvancedSslSocketFactory:  ... with connection timeout 50000 and socket timeout 50000
2019-06-09 20:23:48.062 5756-5846/com.nextcloud.client I/ServerNameIndicator: SNI done, hostname: my.serv.er
2019-06-09 20:23:49.069 5756-5846/com.nextcloud.client I/HttpMethodDirector: I/O exception (java.net.ConnectException) caught when processing request: failed to connect to my.serv.er/185.251.103.41 (port 443) from /192.168.0.5 (port 42505) after 50000ms: isConnected failed: ECONNREFUSED (Connection refused)
2019-06-09 20:23:49.070 5756-5846/com.nextcloud.client I/HttpMethodDirector: Retrying request
2019-06-09 20:23:49.070 5756-5846/com.nextcloud.client D/AdvancedSslSocketFactory: Creating SSL Socket with remote my.serv.er:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@a3eda1d
2019-06-09 20:23:49.070 5756-5846/com.nextcloud.client D/AdvancedSslSocketFactory:  ... with connection timeout 50000 and socket timeout 50000
2019-06-09 20:23:49.079 5756-5846/com.nextcloud.client I/ServerNameIndicator: SNI done, hostname: my.serv.er
2019-06-09 20:23:50.088 5756-5846/com.nextcloud.client I/HttpMethodDirector: I/O exception (java.net.ConnectException) caught when processing request: failed to connect to my.serv.er/185.251.103.41 (port 443) from /192.168.0.5 (port 41827) after 50000ms: isConnected failed: ECONNREFUSED (Connection refused)
2019-06-09 20:23:50.089 5756-5846/com.nextcloud.client I/HttpMethodDirector: Retrying request
2019-06-09 20:23:50.089 5756-5846/com.nextcloud.client D/AdvancedSslSocketFactory: Creating SSL Socket with remote my.serv.er:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@a3eda1d
2019-06-09 20:23:50.089 5756-5846/com.nextcloud.client D/AdvancedSslSocketFactory:  ... with connection timeout 50000 and socket timeout 50000
2019-06-09 20:23:50.095 5756-5846/com.nextcloud.client I/ServerNameIndicator: SNI done, hostname: my.serv.er
2019-06-09 20:23:51.110 5756-5846/com.nextcloud.client E/GetRemoteStatusOperation: Connection check at https://my.serv.er: Socket exception
    java.net.ConnectException: failed to connect to my.serv.er/185.251.103.41 (port 443) from /192.168.0.5 (port 37697) after 50000ms: isConnected failed: ECONNREFUSED (Connection refused)
        at libcore.io.IoBridge.isConnected(IoBridge.java:273)
        at libcore.io.IoBridge.connectErrno(IoBridge.java:188)
        at libcore.io.IoBridge.connect(IoBridge.java:130)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:356)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:357)
        at java.net.Socket.connect(Socket.java:616)
        at com.android.org.conscrypt.AbstractConscryptSocket.connect(AbstractConscryptSocket.java:155)
        at com.owncloud.android.lib.common.network.AdvancedSslSocketFactory.createSocket(AdvancedSslSocketFactory.java:186)
        at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
        at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
        at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:235)
        at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:199)
        at com.owncloud.android.lib.resources.status.GetRemoteStatusOperation.tryConnection(GetRemoteStatusOperation.java:88)
        at com.owncloud.android.lib.resources.status.GetRemoteStatusOperation.run(GetRemoteStatusOperation.java:197)
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:145)
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:149)
        at com.owncloud.android.operations.GetServerInfoOperation.run(GetServerInfoOperation.java:80)
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:145)
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:149)
        at com.owncloud.android.services.OperationsService$ServiceHandler.nextOperation(OperationsService.java:484)
        at com.owncloud.android.services.OperationsService$ServiceHandler.handleMessage(OperationsService.java:422)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
        at libcore.io.IoBridge.isConnected(IoBridge.java:262)
        at libcore.io.IoBridge.connectErrno(IoBridge.java:188) 
        at libcore.io.IoBridge.connect(IoBridge.java:130) 
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129) 
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:356) 
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) 
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) 
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:357) 
        at java.net.Socket.connect(Socket.java:616) 
        at com.android.org.conscrypt.AbstractConscryptSocket.connect(AbstractConscryptSocket.java:155) 
        at com.owncloud.android.lib.common.network.AdvancedSslSocketFactory.createSocket(AdvancedSslSocketFactory.java:186) 
        at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707) 
        at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361) 
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387) 
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171) 
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397) 
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323) 
        at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:235) 
        at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:199) 
        at com.owncloud.android.lib.resources.status.GetRemoteStatusOperation.tryConnection(GetRemoteStatusOperation.java:88) 
        at com.owncloud.android.lib.resources.status.GetRemoteStatusOperation.run(GetRemoteStatusOperation.java:197) 
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:145) 
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:149) 
        at com.owncloud.android.operations.GetServerInfoOperation.run(GetServerInfoOperation.java:80) 
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:145) 
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:149) 
        at com.owncloud.android.services.OperationsService$ServiceHandler.nextOperation(OperationsService.java:484) 
        at com.owncloud.android.services.OperationsService$ServiceHandler.handleMessage(OperationsService.java:422) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
```

</details>

I'm really not sure how it could work in browser but not in the app. I'm up to collecting more info if needed. The app worked before with another server.

**Comment by charlag** [comment]
Another thing: I logged in successfully with News app but not with Nextcloud app which makes me even more sure that there's something on the intersection of my setup and the app

**Comment by tobiasKaminsky** [comment]
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by charlag** [comment]
I've tried Dev version from F-Droid and it worked. Kinda. At least I was able to log in using the old method.
