### ISSUE TITLE
App crash on startup (something with thumbnails)

### ISSUE THREAD

**Issue by doits** [nextcloud/android#4150]
### Actual behaviour

Cannot start nextcloud android app:

```
06-14 15:42:06.790 28712 28712 D AndroidRuntime: Shutting down VM
06-14 15:42:06.792 28712 28712 E AndroidRuntime: FATAL EXCEPTION: main
06-14 15:42:06.792 28712 28712 E AndroidRuntime: Process: com.nextcloud.client, PID: 28712
06-14 15:42:06.792 28712 28712 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:800)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at com.owncloud.android.datamodel.ThumbnailsCacheManager.addVideoOverlay(ThumbnailsCacheManager.java:1053)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at com.owncloud.android.ui.adapter.OCFileListAdapter.setThumbnail(OCFileListAdapter.java:551)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at com.owncloud.android.ui.adapter.OCFileListAdapter.onBindViewHolder(OCFileListAdapter.java:322)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:557)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:171)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.View.layout(View.java:21892)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6260)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.View.layout(View.java:21892)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6260)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1183)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:870)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:889)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.View.layout(View.java:21892)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6260)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.View.layout(View.java:21892)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6260)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.View.layout(View.java:21892)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6260)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1818)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1584)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.View.layout(View.java:21892)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6260)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.View.layout(View.java:21892)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6260)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.View.layout(View.java:21892)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6260)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.View.layout(View.java:21892)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6260)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.View.layout(View.java:21892)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6260)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.View.layout(View.java:21892)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6260)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.View.layout(View.java:21892)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6260)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at com.android.internal.policy.DecorView.onLayout(DecorView.java:773)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.View.layout(View.java:21892)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6260)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3078)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2588)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7595)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:725)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7319)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
06-14 15:42:06.792 28712 28712 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)
```

Started to occur by chance, worked fine before. Cannot start the app at all now.

### Environment data
Android version: 10 (QPP4.190502.019)

Device model: Pixel 2 XL

Stock or customized system: Stock

Nextcloud app version: 3.7.0.RC3

Nextcloud server version: 16.0.1

**Comment by ezaquarii** [comment]
@doits is it one-off or reproducible?

**Comment by ezaquarii** [comment]
```
    public static Bitmap addVideoOverlay(final Bitmap thumbnail){
        Bitmap playButton = BitmapFactory.decodeResource(MainApp.getAppContext().getResources(),
                R.drawable.view_play);

        Bitmap resizedPlayButton = Bitmap.createScaledBitmap(playButton,
                (int) (thumbnail.getWidth() * 0.3),
                (int) (thumbnail.getHeight() * 0.3), true);
```

Looks like `playButton` is `null` for some reason. `BitmapFactory.decodeResource` genuinely can fail (documented behaviour) and this condution is not handled.

**Comment by ezaquarii** [comment]
@doits  Could you pls x-reference your problem with #4129? Some user published a video - is there a change that we're dealing with the same issue?

**Comment by doits** [comment]
> one-off or reproducible

Sorry, what do you mean by this? It always crashes, no way to start the app.

> Some user published a video - is there a chance that we're dealing with the same issue?

It looks exactly like this for me, too, so it might be the same issue. Could be totally different cause though - who knows without a stack trace?

**Comment by ezaquarii** [comment]
@dois thank you for coming back to us.

> Sorry, what do you mean by this? It always crashes, no way to start the app.

One-off means single or rare occurence of a defect. Those are most annoying to deal with as it's diffucult to investigate.

> It looks exactly like this for me

Including the initial splash screen shown for a brief moment?

You can take a look at this test build that @AndyScherzinger created. It it based on 3.7.0 RC3.
https://github.com/nextcloud/android/pull/4154
When you install the APK (url or QR code) and manage to reproduce this problem with it, it should launch an e-mail composer with stack trace when it crashes. Sending that stack trace to us (or publishing it) should allow us to pinpoint the root cause.

**Comment by ezaquarii** [comment]
@doits Forget it, I see that **your** report already has the stack trace. Pls disregard my message.

**Comment by doits** [comment]
I could work around it by moving a video file I had in my root directory to a sub dir. First it didn't work but now I can start the app again (presumably it synced in the background and noticed the file is gone?). When I open the folder I moved the video in though it crashes again.

**Comment by ezaquarii** [comment]
> I could work around it by moving a video file I had in my root directory to a sub dir. First it didn't work but now I can start the app again (presumably it synced in the background and noticed the file is gone?). When I open the folder I moved the video in though it crashes again.

Hold on, what do you mean by "the file is gone"? It looks for me as you just discovered / mentioned some important detail about the reproduction steps that we missed before. It's an important clue.

Can you pls tell me what is this file that causes the issue?

cc @emresaracoglu Does it sound familiar?

**Comment by emresaracoglu** [comment]
Yes, i emailed you @ezaquarii

**Comment by ezaquarii** [comment]
@doits We have a fix pending. I invite everybody to test it. QA build is available here: https://github.com/nextcloud/android/pull/4155#issuecomment-502457085
