### ISSUE TITLE
Sticky broadcast giving security exception in Android for work in Android P

### ISSUE THREAD

**Issue by rumbleball80** [nextcloud/android#4205]
### Actual behaviour
- I installed Nextcloud from Play Store in an Android for Work environment. After login and getting access to filesystem the app crashes
- every retry to open the app ends directly in an crash 

### Expected behaviour
- It should launch the application correctly
 
### Steps to reproduce
1. Configure Android for Work
2. Install Nextcloud android app and configure it
3. Launch it one time. 

### Environment data
Android version: 9 patch version 05/05/2019

Device model: HUAWEI P20 lite

Stock or customized system: stock

Nextcloud app version: 3.6.2

Nextcloud server version: 15.0.9

#### Web server error log
Nothing

#### Nextcloud log (data/nextcloud.log)

> 07-05 21:28:46.172 18341 18341 W InputMethodManager: startInputReason = 1
> 07-05 21:28:46.177 18341 18341 D FileDisplayActivity: Received broadcast com.owncloud.android.syncadapter.FileSyncAdapter.EVENT_FULL_SYNC_START
> 07-05 21:28:46.179  1138  3469 W ActivityManager: Permission Denial: unbroadcastIntent() from pid=18341, uid=1110168 requires android.permission.BROADCAST_STICKY
> 07-05 21:28:46.179  1138  3469 W System.err: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=18341, uid=1110168 requires android.permission.BROADCAST_STICKY
> 07-05 21:28:46.181 18341 18341 D AndroidRuntime: Shutting down VM
> 07-05 21:28:46.182 18341 18341 E AndroidRuntime: FATAL EXCEPTION: main
> 07-05 21:28:46.182 18341 18341 E AndroidRuntime: Process: com.nextcloud.client, PID: 18341
> 07-05 21:28:46.182 18341 18341 E AndroidRuntime: java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.syncadapter.FileSyncAdapter.EVENT_FULL_SYNC_START flg=0x10 pkg=com.nextcloud.client (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver@4b91581

### Workaround

after searching for "android.permission.BROADCAST_STICKY" I found this:
[Sticky broadcast giving security exception in Android for work in Android P](https://stackoverflow.com/questions/53244575/sticky-broadcast-giving-security-exception-in-android-for-work-in-android-p)

so when I installed nextcloud also in normal user space (only install, no launch) the application in work profile will work as expected.

**Comment by ByteBitten** [comment]
#413 was closed, therefore I add my logs here:

### Actual behaviour
App crashes when indexing connected NextCloud on startup

### Expected behaviour
Indexing should finish and show folders.
 
### Steps to reproduce
1. Open app, Dev or stable
2. Connect to NextCloud installation

### Environment data
Android version:
9
Device model: 
Nokia Sirocco 8
Stock or customized system:
Stock, non-rooted
Nextcloud app version:
20190803
Nextcloud server version:
16.0.3

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED flg=0x10 pkg=com.nextcloud.android.beta (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver@e3ba62a
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1401)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:874)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:198)
	at android.app.ActivityThread.main(ActivityThread.java:6729)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=12135, uid=1010320 requires android.permission.BROADCAST_STICKY
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.app.IActivityManager$Stub$Proxy.unbroadcastIntent(IActivityManager.java:3861)
	at android.app.ContextImpl.removeStickyBroadcast(ContextImpl.java:1358)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
	at com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver.onReceive(FileDisplayActivity.java:1445)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1391)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.unbroadcastIntent(ActivityManagerService.java:23084)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:183)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3528)
	at android.os.Binder.execTransact(Binder.java:731)


************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20190803
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Nokia
Device: NB1
Model: TA-1004
Id: PPR1.180610.011
Product: TA-1004_00WW

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 00WW_5_15D

```

**Comment by AndyScherzinger** [comment]
afaik this is also related to work profiles, right @mario ?

**Comment by strugee** [comment]
I can confirm this behavior on a Pixel 3a XL device, Android P. I installed the app in a separate user, however, instead of a work profile, so that seems to be impacted by the same bug. The workaround (installing the app in the primary user) also worked for me.

**Comment by tobiasKaminsky** [comment]
This also happens on some devices when a second profile is used (#6545)

**Comment by AndyScherzinger** [comment]
Closing in favor of #6654 for a central issue for discussing a solution and to link any error reports to it. So please subscribe to the mentioned issue for any discussions and updates
