### ISSUE TITLE
TXT preview crashes on 3.7.0

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/android#4213]
### Actual behaviour
Opening a txt file crashes

### Expected behaviour
Preview opens
 
### Steps to reproduce
1. Put txt with with ASCII text in a folder
2. Try opening the preview

Device model: 
OnePlus 6T

Stock or customized system:
Stock

Nextcloud app version:
GPlay 3.7.0 

Nextcloud server version:
16.0.2

### Logs
```
07-09 22:31:57.279  7883  7883 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.nextcloud.client.account.UserAccountManager.isMediaStreamingSupported(android.accounts.Account)' on a null object reference
07-09 22:31:57.279  7883  7883 E AndroidRuntime: 	at com.owncloud.android.ui.preview.PreviewTextFragment.onPrepareOptionsMenu(PreviewTextFragment.java:381)
07-09 22:31:57.279  7883  7883 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performPrepareOptionsMenu(Fragment.java:2575)
07-09 22:31:57.279  7883  7883 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.dispatchPrepareOptionsMenu(FragmentManager.java:3353)
07-09 22:31:57.279  7883  7883 E AndroidRuntime: 	at androidx.fragment.app.FragmentController.dispatchPrepareOptionsMenu(FragmentController.java:343)
07-09 22:31:57.279  7883  7883 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onPreparePanel(FragmentActivity.java:548)
07-09 22:31:57.279  7883  7883 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
07-09 22:31:57.279  7883  7883 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:2576)
07-09 22:31:57.279  7883  7883 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
07-09 22:31:57.279  7883  7883 E AndroidRuntime: 	at androidx.appcompat.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:522)
07-09 22:31:57.279  7883  7883 E AndroidRuntime: 	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
07-09 22:31:57.279  7883  7883 E AndroidRuntime: 	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
07-09 22:31:57.279  7883  7883 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1172)
07-09 22:31:57.279  7883  7883 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:984)
07-09 22:31:57.279  7883  7883 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:806)
07-09 22:31:57.279  7883  7883 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1158)
07-09 22:31:57.279  7883  7883 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-09 22:31:57.279  7883  7883 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-09 22:31:57.279  7883  7883 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
07-09 22:31:57.279  7883  7883 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6863)
07-09 22:31:57.279  7883  7883 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-09 22:31:57.279  7883  7883 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
07-09 22:31:57.279  7883  7883 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07-09 22:32:28.862  8552  8552 E AndroidRuntime: FATAL EXCEPTION: main
07-09 22:32:28.862  8552  8552 E AndroidRuntime: Process: com.nextcloud.client, PID: 8552
07-09 22:32:28.862  8552  8552 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.nextcloud.client.account.UserAccountManager.isMediaStreamingSupported(android.accounts.Account)' on a null object reference
07-09 22:32:28.862  8552  8552 E AndroidRuntime: 	at com.owncloud.android.ui.preview.PreviewTextFragment.onPrepareOptionsMenu(PreviewTextFragment.java:381)
07-09 22:32:28.862  8552  8552 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performPrepareOptionsMenu(Fragment.java:2575)
07-09 22:32:28.862  8552  8552 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.dispatchPrepareOptionsMenu(FragmentManager.java:3353)
07-09 22:32:28.862  8552  8552 E AndroidRuntime: 	at androidx.fragment.app.FragmentController.dispatchPrepareOptionsMenu(FragmentController.java:343)
07-09 22:32:28.862  8552  8552 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onPreparePanel(FragmentActivity.java:548)
07-09 22:32:28.862  8552  8552 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
07-09 22:32:28.862  8552  8552 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:2576)
07-09 22:32:28.862  8552  8552 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
07-09 22:32:28.862  8552  8552 E AndroidRuntime: 	at androidx.appcompat.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:522)
07-09 22:32:28.862  8552  8552 E AndroidRuntime: 	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
07-09 22:32:28.862  8552  8552 E AndroidRuntime: 	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
07-09 22:32:28.862  8552  8552 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1172)
07-09 22:32:28.862  8552  8552 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:984)
07-09 22:32:28.862  8552  8552 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:806)
07-09 22:32:28.862  8552  8552 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1158)
07-09 22:32:28.862  8552  8552 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-09 22:32:28.862  8552  8552 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-09 22:32:28.862  8552  8552 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
07-09 22:32:28.862  8552  8552 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6863)
07-09 22:32:28.862  8552  8552 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-09 22:32:28.862  8552  8552 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
07-09 22:32:28.862  8552  8552 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by ezaquarii** [comment]
@tobiasKaminsky @AndyScherzinger  Is this something we forgot to port from master? It doesn't happen on master and IIRC we fixed it there.

**Comment by tobiasKaminsky** [comment]
Hm. Tried it and it works for me.

``` 
UserAccountManager.isMediaStreamingSupported(android.accounts.Account)' 
```

This is injected via Dagger. 
PreviewTextFragment is also in PreviewTextFragment.

**Comment by AndyScherzinger** [comment]
@ezaquarii should we close this? I didn't revert back to 3.7.0 but like you said it works on master (which is what I tested)

**Comment by ezaquarii** [comment]
Yeah, this is fixed.
