### ISSUE TITLE
Can't save files to Nextcloud through Android Save Files dialog

### ISSUE THREAD

**Issue by leggettc18** [nextcloud/android#4219]
Trying to backup my andOTP encrypted json file to Nextcloud. It always fails this way, but I can download it to my downloads and then upload it through the Nextcloud app. This works for now, but its a few extra steps I would rather not do if possible.

### Actual behaviour
- Receive the message "failed to save document", when I click send.

### Expected behaviour
- File is saved to Nextcloud through the android save dialog.
 
### Steps to reproduce
1. Use an app that offers to save a file through Android's save file dialog
2. Select Nextcloud from the list of destinations in the sidebar
3. Navigate to directory you want to save the file in
4. Click "Save"

### Environment data
Android version: 9

Device model: Galaxy S10

Stock or customized system: Stock

Nextcloud app version: 3.7.0

Nextcloud server version: 16.0.0

### Logs

I can add these later if necessary, currently at work so can't easily access my server logs.

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by pschichtel** [comment]
@leggettc18 Have you found a solution to this problem? I'm facing the exact some issue. On my previous phone (OnePlus 6T with OxygenOS 10.3.9 (Android 10)) the backup feature of AndOTP worked perfectly fine with Nextcloud, on my OnePlus 8 Pro (OxygenOS 11.0.5.5 (Android 11)) it doesn't work.

**Comment by pschichtel** [comment]
this from logcat seems related:

```05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: Download of filepath to /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/tmp/some/filepath: Unexpected exception
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: android.os.NetworkOnMainThreadException
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1605)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.google.android.gms.org.conscrypt.Platform.blockGuardOnNetwork(:com.google.android.gms@211515046@21.15.15 (150400-371058782):0)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(:com.google.android.gms@211515046@21.15.15 (150400-371058782):2)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:248)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at java.io.BufferedInputStream.read(BufferedInputStream.java:267)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.HttpConnection.isStale(HttpConnection.java:506)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.HttpConnection.closeIfStale(HttpConnection.java:431)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.closeIfStale(MultiThreadedHttpConnectionManager.java:1313)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:382)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:219)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.resources.files.DownloadFileRemoteOperation.downloadFile(DownloadFileRemoteOperation.java:111)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.resources.files.DownloadFileRemoteOperation.run(DownloadFileRemoteOperation.java:88)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:184)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.owncloud.android.operations.DownloadFileOperation.run(DownloadFileOperation.java:168)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:184)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.owncloud.android.providers.DocumentsStorageProvider.openDocument(DocumentsStorageProvider.java:202)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at android.provider.DocumentsProvider.openAssetFile(DocumentsProvider.java:1344)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at android.content.ContentProvider$Transport.openAssetFile(ContentProvider.java:528)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:286)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at android.os.Binder.execTransactInternal(Binder.java:1165)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at android.os.Binder.execTransact(Binder.java:1134)
05-01 22:08:07.884 22332 23587 E DocumentsStorageProvider: RemoteOperationResult(mSuccess=false, mHttpCode=-1, mHttpPhrase=null, mException=android.os.NetworkOnMainThreadException, mCode=HOST_NOT_AVAILABLE, message=null, getLogMessage=Unexpected exception)
```

Also opening an issue over at AndOTP
