### ISSUE TITLE
Bug  report

### ISSUE THREAD

**Issue by josephyuen** [nextcloud/android#4304]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineForOffset(int)' on a null object reference
	at android.widget.Editor.updateCursorPositionMz(Editor.java:6986)
	at android.widget.Editor.updateCursorsPositions(Editor.java:1766)
	at android.widget.TextView.getUpdatedHighlightPath(TextView.java:5703)
	at android.widget.TextView.onDraw(TextView.java:5896)
	at com.owncloud.android.ui.components.CustomEditText.onDraw(CustomEditText.java:71)
	at android.view.View.draw(View.java:16553)
	at android.view.View.updateDisplayListIfDirty(View.java:15500)
	at android.view.View.draw(View.java:16301)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.View.draw(View.java:16301)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.draw(View.java:16565)
	at com.google.android.material.textfield.TextInputLayout.draw(TextInputLayout.java:1577)
	at android.view.View.updateDisplayListIfDirty(View.java:15500)
	at android.view.View.draw(View.java:16301)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.View.draw(View.java:16301)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.View.draw(View.java:16301)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.View.draw(View.java:16301)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.draw(View.java:16565)
	at android.widget.ScrollView.draw(ScrollView.java:1745)
	at android.view.View.updateDisplayListIfDirty(View.java:15500)
	at android.view.View.draw(View.java:16301)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.View.draw(View.java:16301)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.View.draw(View.java:16301)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.View.draw(View.java:16301)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15492)
	at android.view.View.draw(View.java:16301)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at com.android.internal.policy.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2842)
	at android.view.View.draw(View.java:16565)
	at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2823)
	at android.view.View.updateDisplayListIfDirty(View.java:15500)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:286)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:292)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:327)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3064)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2868)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2473)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1346)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6840)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:896)
	at android.view.Choreographer.doCallbacks(Choreographer.java:698)
	at android.view.Choreographer.doFrame(Choreographer.java:633)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:882)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:6046)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:840)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:730)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080000
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Meizu
Device: M5s
Model: M5s
Id: MRA58K
Product: meizu_M5s

************ FIRMWARE ************
SDK: 23
Release: 6.0
Incremental: 1532429986

**Comment by castamonte** [comment]
I have the same error. Why the issue is closed? How can I resolve my problem?

**Comment by ezaquarii** [comment]
> I have the same error when I try log in just after installing. Why the issue is closed? How can I resolve my problem?

I guess it is closed as it looks like a bug in Android, not Nextcloud.

1. How often do you experience this problem? Always or is it one-off?

2. Are you able to use the app to do your work?

**Comment by castamonte** [comment]
You are right, it is androids problem. Moreover it's problem of Meizu 5s, because the application works great on Xiaomi Redmi Note 4 (I haven't another phones to check : )  )
Unfortunately this error occurs always on my Meizu. Just I hoped that somebody resolved this problem..

**Comment by tobiasKaminsky** [comment]
Duplicate of #4619
