### ISSUE TITLE
npe when selecting yes on popup wether full size image should be downloaded when thumbnail not available

### ISSUE THREAD

**Issue by beerockxs** [nextcloud/android#4317]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.owncloud.android.ui.preview.PreviewImageActivity.requestForDownload(com.owncloud.android.datamodel.OCFile)' on a null object reference
	at com.owncloud.android.ui.preview.PreviewImageFragment.lambda$setErrorPreviewMessage$2$PreviewImageFragment(PreviewImageFragment.java:696)
	at com.owncloud.android.ui.preview.-$$Lambda$PreviewImageFragment$kydRNo-kMJ0Oklsv9f_06NSEUic.onClick(Unknown Source:2)
	at com.google.android.material.snackbar.Snackbar$1.onClick(Snackbar.java:317)
	at android.view.View.performClick(View.java:6294)
	at android.view.View$PerformClick.run(View.java:24774)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6543)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20190806
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: bq
Device: bardock
Model: Aquaris X
Id: OPM1.171019.026
Product: bardock

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: 2168

**Comment by tobiasKaminsky** [comment]
Can you try this with only one image in a folder?
I could not reproduce NPE, but strangely it downloaded the false one…
