### ISSUE TITLE
Nextcloud bug at boot

### ISSUE THREAD

**Issue by Adrien-ops** [nextcloud/android#4333]
************ CAUSE OF ERROR ************

java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1244)
	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:336)
	at java.util.concurrent.LinkedBlockingQueue.offer(LinkedBlockingQueue.java:380)
	at com.nextcloud.client.logger.LoggerImpl.enqueue(LoggerImpl.kt:105)
	at com.nextcloud.client.logger.LoggerImpl.d(LoggerImpl.kt:67)
	at com.nextcloud.client.logger.LegacyLoggerAdapter.i(LegacyLoggerAdapter.kt:31)
	at com.owncloud.android.lib.common.utils.Log_OC.i(Log_OC.java:124)
	at com.owncloud.android.operations.RefreshFolderOperation.checkForChanges(RefreshFolderOperation.java:312)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:220)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:138)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:268)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.onPerformSync(FileSyncAdapter.java:180)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:334)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20190810
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus5T
Model: ONEPLUS A5010
Id: PQ3A.190605.003
Product: OnePlus5T

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 7ec472ea7a

**Comment by tobiasKaminsky** [comment]
Thanks for your bug report.
How often does this happen for you? Every time?

**Comment by Adrien-ops** [comment]
Hello,
Yes each time my phone starts up.

Best regards.
-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


16 Aug 2019, 13:20 by notifications@github.com:

**Comment by AndyScherzinger** [comment]
@ezaquarii fancy taking a look? ❤️

**Comment by ezaquarii** [comment]
@Adrien-ops can you please test the fix? It's here: https://github.com/nextcloud/android/pull/4336
Just scan the QR code and install the app. It will **not** overwrite your existing app - it's safe to test it.

**Comment by ezaquarii** [comment]
> Hello, Yes each time my phone starts up. Best regards.

I just want to clarify: each time the phone-as-in-device starts, not the app? Are you able to actually use the app for daily work?

**Comment by Adrien-ops** [comment]
Hello !
After several tests I noticed that the bug came randomly after the phone started. As soon as I have more information, I'll let you know.

I have installed your application for the moment no bugs have appeared.

-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


16 Aug 2019, 16:51 by notifications@github.com:
