### ISSUE TITLE
Error by Klick on folder

### ISSUE THREAD

**Issue by Mululu** [nextcloud/android#4385]
### Actual behaviour
- Doesnt Open the folder

### Expected behaviour
- Open the folder
 
### Steps to reproduce
1. Klick on folder

The issue ist not on all folders

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
	at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:1002)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:864)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:157)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:719)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1175)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1120)
	at com.owncloud.android.ui.fragment.OCFileListFragment.onItemClicked(OCFileListFragment.java:894)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.lambda$onBindViewHolder$0$OCFileListAdapter(OCFileListAdapter.java:337)
	at com.owncloud.android.ui.adapter.-$$Lambda$OCFileListAdapter$KYFT7zrcMuRQdUdOUJx291OJcIg.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:6600)
	at android.view.View.performClickInternal(View.java:6577)
	at android.view.View.access$3100(View.java:781)
	at android.view.View$PerformClick.run(View.java:25967)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:210)
	at android.app.ActivityThread.main(ActivityThread.java:7046)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: htc
Device: htc_ocla1_sprout
Model: HTC U11 life
Id: PPR1.180610.011
Product: ocla1_sprout_00401

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 1055045.22

**Comment by JadedHeart** [comment]
Have the same

**Comment by tobiasKaminsky** [comment]
Fix is in #4370 and will be in upcoming RC2, very soon.
