### ISSUE TITLE
Error during pdf upload via Android share function

### ISSUE THREAD

**Issue by oliverweidel** [nextcloud/android#4392]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
	at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:1002)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:864)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:157)
	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.populateDirectoryList(ReceiveExternalFilesActivity.java:769)
	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onItemClick(ReceiveExternalFilesActivity.java:676)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1190)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3200)
	at android.widget.AbsListView$3.run(AbsListView.java:4115)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:180)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: htc
Device: htc_pmeuhl
Model: HTC 10
Id: OPR1.170623.027
Product: pmeuhl_00401

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: 1012001.2

**Comment by tobiasKaminsky** [comment]
This is fixed via https://github.com/nextcloud/android/pull/4370 and will be in RC2 coming soon.
