### ISSUE TITLE
Close

### ISSUE THREAD

**Issue by Arnaudfly** [nextcloud/android#4393]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
	at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:1002)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:864)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:157)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:719)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1175)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1120)
	at com.owncloud.android.ui.fragment.OCFileListFragment.onItemClicked(OCFileListFragment.java:894)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.lambda$onBindViewHolder$0$OCFileListAdapter(OCFileListAdapter.java:337)
	at com.owncloud.android.ui.adapter.-$$Lambda$OCFileListAdapter$KYFT7zrcMuRQdUdOUJx291OJcIg.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:6300)
	at android.view.View$PerformClick.run(View.java:24941)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: vernee
Device: V2_Pro
Model: V2 Pro
Id: O11019
Product: V2_Pro

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: 1529496296

**Comment by tobiasKaminsky** [comment]
This is fixed by #4370 and is already in 3.8.0 RC2
