### ISSUE TITLE
Crash when opening Foto

### ISSUE THREAD

**Issue by WarpinWolf** [nextcloud/android#4402]
### Actual behaviour
- open nextcloud app
- select menu Fothis
- crash

************ CAUSE OF ERROR ************

java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at androidx.recyclerview.widget.GridLayoutManager.calculateItemBorders(GridLayoutManager.java:325)
	at androidx.recyclerview.widget.GridLayoutManager.calculateItemBorders(GridLayoutManager.java:310)
	at androidx.recyclerview.widget.GridLayoutManager.updateMeasurements(GridLayoutManager.java:281)
	at androidx.recyclerview.widget.GridLayoutManager.onAnchorReady(GridLayoutManager.java:356)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:579)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:171)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
	at android.view.View.layout(View.java:22419)
	at android.view.ViewGroup.layout(ViewGroup.java:6584)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
	at android.view.View.layout(View.java:22419)
	at android.view.ViewGroup.layout(ViewGroup.java:6584)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1183)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:870)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:889)
	at android.view.View.layout(View.java:22419)
	at android.view.ViewGroup.layout(ViewGroup.java:6584)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
	at android.view.View.layout(View.java:22419)
	at android.view.ViewGroup.layout(ViewGroup.java:6584)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:22419)
	at android.view.ViewGroup.layout(ViewGroup.java:6584)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1801)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1567)
	at android.view.View.layout(View.java:22419)
	at android.view.ViewGroup.layout(ViewGroup.java:6584)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:22419)
	at android.view.ViewGroup.layout(ViewGroup.java:6584)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:22419)
	at android.view.ViewGroup.layout(ViewGroup.java:6584)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:22419)
	at android.view.ViewGroup.layout(ViewGroup.java:6584)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:22419)
	at android.view.ViewGroup.layout(ViewGroup.java:6584)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:22419)
	at android.view.ViewGroup.layout(ViewGroup.java:6584)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:22419)
	at android.view.ViewGroup.layout(ViewGroup.java:6584)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1041)
	at android.view.View.layout(View.java:22419)
	at android.view.ViewGroup.layout(ViewGroup.java:6584)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3378)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2842)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1888)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8511)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080052
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: dreamlte
Model: SM-G950F
Id: PPR1.180610.011
Product: dreamltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G950FXXU5DSFB

### Expected behaviour
- show me my pics
 
### Steps to reproduce
1. Open Nextcloud
2. Select Menu Fotos
3. Crash

### Environment data
Android version:
9

Device model: 
Brand: samsung
Device: dreamlte
Model: SM-G950F

Stock or customized system:
Stock

Nextcloud app version:

Nextcloud server version:
16.04

### Logs
See above

#### Web server error log

Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```Nothing (all levels selected)
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by WarpinWolf** [comment]
Forgot app version 3.8.0 RC2

**Comment by tobiasKaminsky** [comment]
No idea about this :/ 
It seems to be completely in Androids internal code, which does not mean that we have an underlying issue.

Does this happen all the time?
Do you have any images in your cloud? I guess so ;-)

**Comment by WarpinWolf** [comment]
Thanks for looking into this.
Yes - does happen all the time.

Yes - > 12,000 pictures stored.

I tried with another account - no issues...

I also have the cloud gallery app installed - works without any problems.

The second I try to access "Fotos" from the Android client menu I see this in the web-server access log:
'''
ip.add.re.ss - nextcloud [26/Aug/2019:11:21:42 +0200] "OPTIONS /remote.php/dav HTTP/1.1" 200 1046 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.8.0 RC2"
ip.add.re.ss - - [26/Aug/2019:11:21:42 +0200] "GET /index.php/204 HTTP/1.1" 204 4435 "-" "Jakarta Commons-HttpClient/3.1"
ip.add.re.ss - - [26/Aug/2019:11:21:42 +0200] "GET /index.php/204 HTTP/1.1" 204 4439 "-" "Jakarta Commons-HttpClient/3.1"
ip.add.re.ss - - [26/Aug/2019:11:21:42 +0200] "GET /index.php/204 HTTP/1.1" 204 4437 "-" "Jakarta Commons-HttpClient/3.1"
ip.add.re.ss - - [26/Aug/2019:11:21:42 +0200] "GET /index.php/204 HTTP/1.1" 204 1503 "-" "Jakarta Commons-HttpClient/3.1"
ip.add.re.ss - - [26/Aug/2019:11:21:42 +0200] "GET /index.php/204 HTTP/1.1" 204 1505 "-" "Jakarta Commons-HttpClient/3.1"
ip.add.re.ss - - [26/Aug/2019:11:21:42 +0200] "GET /index.php/204 HTTP/1.1" 204 1513 "-" "Jakarta Commons-HttpClient/3.1"
ip.add.re.ss - - [26/Aug/2019:11:21:42 +0200] "GET /index.php/204 HTTP/1.1" 204 4437 "-" "Jakarta Commons-HttpClient/3.1"
ip.add.re.ss - - [26/Aug/2019:11:21:43 +0200] "GET /index.php/204 HTTP/1.1" 204 1517 "-" "Jakarta Commons-HttpClient/3.1"
ip.add.re.ss - - [26/Aug/2019:11:21:43 +0200] "GET /index.php/204 HTTP/1.1" 204 1517 "-" "Jakarta Commons-HttpClient/3.1"
ip.add.re.ss - - [26/Aug/2019:11:21:43 +0200] "GET /index.php/204 HTTP/1.1" 204 1515 "-" "Jakarta Commons-HttpClient/3.1"
ip.add.re.ss - - [26/Aug/2019:11:21:43 +0200] "GET /index.php/204 HTTP/1.1" 204 1513 "-" "Jakarta Commons-HttpClient/3.1"
ip.add.re.ss - - [26/Aug/2019:11:21:43 +0200] "GET /index.php/204 HTTP/1.1" 204 1513 "-" "Jakarta Commons-HttpClient/3.1"
'''

**Comment by WarpinWolf** [comment]
Hi,
any news/suggestions about this? My (unqualified) assumption is that there is a counter overrun in the app during the layout phase....
Report is basically the same still - change here:
************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090 <----------
Build flavor: gplay

Thanks for providing the app!!!

**Comment by AndyScherzinger** [comment]
@WarpinWolf is the issue still present with 3.8.1 since I think @tobiasKaminsky did try a fix (while this error is hard to reproduce)

**Comment by WarpinWolf** [comment]
Yeah, I wanted to post an update yesterday already but got lost in
searching the thread...

Issue is fixed. No crash anymore (although I'd wish the lazy loading would
be solved differently... ;-)

Thank you very much for your work and attention!!!

Wolf

Andy Scherzinger <notifications@github.com> schrieb am Mo., 14. Okt. 2019,
15:11:
