### ISSUE TITLE
crash open dir

### ISSUE THREAD

**Issue by TheWorms** [nextcloud/android#4405]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
 at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:1002)
 at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:864)
 at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:157)
 at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:719)
 at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1175)
 at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1120)
 at com.owncloud.android.ui.fragment.OCFileListFragment.onItemClicked(OCFileListFragment.java:894)
 at com.owncloud.android.ui.adapter.OCFileListAdapter.lambda$onBindViewHolder$0$OCFileListAdapter(OCFileListAdapter.java:337)
 at com.owncloud.android.ui.adapter.-$$Lambda$OCFileListAdapter$KYFT7zrcMuRQdUdOUJx291OJcIg.onClick(Unknown Source:4)
 at android.view.View.performClick(View.java:7352)
 at android.view.View.performClickInternal(View.java:7318)
 at android.view.View.access$3200(View.java:846)
 at android.view.View$PerformClick.run(View.java:27800)
 at android.os.Handler.handleCallback(Handler.java:873)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:214)
 at android.app.ActivityThread.main(ActivityThread.java:7050)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: greatlte
Model: SM-N950F
Id: PPR1.180610.011
Product: greatltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: N950FXXS7DSH1

**Comment by AndyScherzinger** [comment]
@TheWorms can you please update to RC2 since this issue should be resolved already.
If not, please reopen this issue 😊
