### ISSUE TITLE
Crash while in background

### ISSUE THREAD

**Issue by AndreasDekiert** [nextcloud/android#4409]
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=3546, totalRows=1639
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:895)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:157)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:128)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:237)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:269)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:183)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:127)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:177)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:127)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:177)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:127)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:107)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:299)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:653)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:320)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:474)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:402)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:441)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:339)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:224)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:138)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:268)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.onPerformSync(FileSyncAdapter.java:180)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:334)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080052
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: blueline
Model: Pixel 3
Id: PQ3A.190801.002
Product: blueline

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 5670241

**Comment by tobiasKaminsky** [comment]
It seems that you want to delete a folder, probably with sub folders.
This fails as the content is too big, e.g. too many files. 
How many files do you have in it, so that I can test it?

**Comment by AndreasDekiert** [comment]
This recently happens quite frequently while the Android app is in the background. I do not have any folder synced to my Android device. I primarily use the app to auto upload photos.

I did however move another folder (one which I have never opened in the Android app) which was about 20gb in size (about 20 files). I moved it in the web interface and everything worked as expected and was synced to the windows client. But Android app was never used to even look into that folder.

Anyways since the Android app does not (intiated by the user) interact with that folder this really should not be the cause for any crash. From my understanding the app should not crash while the user is not interacting with it.

**Comment by mase76** [comment]
I have similar crashes with the Fdroid build:

************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Couldn't read row 1172, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:538)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:172)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:127)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:177)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:127)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:107)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:299)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:653)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:320)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:474)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:402)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:441)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:339)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:224)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:138)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:268)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.onPerformSync(FileSyncAdapter.java:180)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:334)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080052
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Sony
Device: suzu
Model: Xperia X
Id: PQ3B.190801.002
Product: omni_suzu

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 48
