### ISSUE TITLE
Crash after upgrade

### ISSUE THREAD

**Issue by jsch** [nextcloud/android#4413]
### Actual behaviour
- After upgrade, when logging into the server the app crashed

### Expected behaviour
- It should authorize the device and log in
 
### Steps to reproduce
1. Upgrade the app
2. Start the app and supply credentials
3. Authorize the device

### Exception log

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
	at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:1002)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:105)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onAccountSet(FileDisplayActivity.java:450)
	at com.owncloud.android.ui.activity.BaseActivity.onStart(BaseActivity.java:197)
	at com.owncloud.android.ui.activity.DrawerActivity.onStart(DrawerActivity.java:1404)
	at com.owncloud.android.ui.activity.FileActivity.onStart(FileActivity.java:204)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2618)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1413)
	at android.app.Activity.performStart(Activity.java:7169)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3146)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1977)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6923)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: motorola
Device: river
Model: moto g(7)
Id: PPO29.114-134
Product: river

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: fee207

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Please upgrade to RC2 which should fix this issue.
