### ISSUE TITLE
App crash on start and periodically on folder sync

### ISSUE THREAD

**Issue by Hellbeast** [nextcloud/android#4414]
### Actual behaviour
- App crash on start and periodically on folder sync

### Expected behaviour
- app opened and sync files
 
### Steps to reproduce
1. install app
2. login to server

### Environment data
Android version: 9

Device model: SM-G965F

Stock or customized system: stock

Nextcloud app version: 3.8.0 RC2

Nextcloud server version: 16.0.4

### Logs
```
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=5701, totalRows=1958
 at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
 at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1060)
 at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
 at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
 at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:169)
 at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:131)
 at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:237)
 at android.database.AbstractCursor.moveToNext(AbstractCursor.java:269)
 at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:183)
 at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:127)
 at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:177)
 at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:127)
 at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:177)
 at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:127)
 at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:107)
 at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:299)
 at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:653)
 at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:319)
 at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:474)
 at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:402)
 at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:441)
 at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:339)
 at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:224)
 at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:138)
 at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:268)
 at com.owncloud.android.syncadapter.FileSyncAdapter.onPerformSync(FileSyncAdapter.java:180)
 at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:334)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080052
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: star2lte
Model: SM-G965F
Id: PPR1.180610.011
Product: star2lteser

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G965FXXU6CSG8
```
#### Web server error log
```
root@Nextcloud-pgsql:/# cat /var/log/apache2/error.log
[Sun Aug 25 06:28:01.659395 2019] [http2:warn] [pid 221] AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive.
[Sun Aug 25 06:28:01.685856 2019] [mpm_prefork:notice] [pid 221] AH00163: Apache/2.4.39 (Ubuntu) OpenSSL/1.1.1c configured -- resuming normal operations
[Sun Aug 25 06:28:01.685888 2019] [core:notice] [pid 221] AH00094: Command line: '/usr/sbin/apache2'
[Sun Aug 25 14:52:03.600703 2019] [authz_core:error] [pid 15079] [client 192.168.3.8:53962] AH01630: client denied by server configuration: /var/www/nextcloud/config

```

#### Nextcloud log (data/nextcloud.log)
```
nextcloud-server logs empty
```

**Comment by tobiasKaminsky** [comment]
>  Row too big to fit

How many files do you have in this folder?

**Comment by mase76** [comment]
This crashes when syncing folders from within the app:

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to read from field 'java.util.concurrent.ConcurrentMap com.owncloud.android.services.OperationsService$OperationsServiceBinder.mBoundListeners' on a null object reference
	at com.owncloud.android.services.OperationsService$OperationsServiceBinder.access$500(OperationsService.java:263)
	at com.owncloud.android.services.OperationsService.dispatchResultToOperationListeners(OperationsService.java:722)
	at com.owncloud.android.services.SyncFolderHandler.doOperation(SyncFolderHandler.java:121)
	at com.owncloud.android.services.SyncFolderHandler.handleMessage(SyncFolderHandler.java:88)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:65)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080052
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Sony
Device: suzu
Model: Xperia X
Id: PQ3B.190801.002
Product: omni_suzu

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 48

**Comment by Hellbeast** [comment]
> 
> 
> > Row too big to fit
> 
> How many files do you have in this folder?

About 300 thousandth. Rollback to last stable version and it's working.

**Comment by Grunthos** [comment]
Also getting this error; 22 files in directory, several recently renamed. Reliably occurs and can not work around.

**Comment by Grunthos** [comment]
This is the relevant log from Android:
'''
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=3047, totalRows=1571
at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:904)
at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:851)
at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:157)
at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:128)
at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:237)
at android.database.AbstractCursor.moveToNext(AbstractCursor.java:269)
at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:183)
at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:127)
at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:177)
at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:127)
at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:177)
at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:127)
at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:177)
at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:127)
at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:177)
at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:127)
at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:107)
at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:299)
at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:661)
at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:336)
at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:474)
at android.content.ContentResolver.applyBatch(ContentResolver.java:1654)
at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:399)
at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:441)
at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:339)
at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:224)
at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:299)
at java.lang.Thread.run(Thread.java:784)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWCLT
Model: CLT-L29
Id: HUAWEICLT-L29
Product: CLT-L29

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 325C636

-- 
'''
