### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Mululu** [nextcloud/android#4439]
New Android Update bug

************ CAUSE OF ERROR ************

java.io.IOException: write failed: ENOSPC (No space left on device)
	at libcore.io.IoBridge.write(IoBridge.java:531)
	at java.io.FileOutputStream.write(FileOutputStream.java:381)
	at java.io.FileOutputStream.write(FileOutputStream.java:359)
	at com.nextcloud.client.logger.FileLogHandler.write(FileLogHandler.kt:77)
	at com.nextcloud.client.logger.LoggerImpl.eventLoop(LoggerImpl.kt:132)
	at com.nextcloud.client.logger.LoggerImpl.access$eventLoop(LoggerImpl.kt:33)
	at com.nextcloud.client.logger.LoggerImpl$start$1.invoke(LoggerImpl.kt:57)
	at com.nextcloud.client.logger.LoggerImpl$start$1.invoke(LoggerImpl.kt:33)
	at com.nextcloud.client.logger.ThreadLoop.loop(ThreadLoop.kt:70)
	at com.nextcloud.client.logger.ThreadLoop.access$loop(ThreadLoop.kt:26)
	at com.nextcloud.client.logger.ThreadLoop$start$1$1.invoke(ThreadLoop.kt:44)
	at com.nextcloud.client.logger.ThreadLoop$start$1$1.invoke(ThreadLoop.kt:26)
	at com.nextcloud.client.logger.ThreadLoop$sam$i$java_lang_Runnable$0.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:764)
Caused by: android.system.ErrnoException: write failed: ENOSPC (No space left on device)
	at libcore.io.Linux.writeBytes(Native Method)
	at libcore.io.Linux.write(Linux.java:288)
	at libcore.io.BlockGuardOs.write(BlockGuardOs.java:348)
	at libcore.io.IoBridge.write(IoBridge.java:526)
	... 13 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080053
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: htc
Device: htc_ocla1_sprout
Model: HTC U11 life
Id: PPR1.180610.011
Product: ocla1_sprout_00401

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 1055045.23

**Comment by AndyScherzinger** [comment]
@mululu see the top of the error: `No space left on device`

@ezaquarii what do you think? Imho in such a scenario we can't do anything better than this (show error)

**Comment by Mululu** [comment]
Oh, I did not see that.

 A normal error message in a pop-up window would be better here generally should be in case of error messages user-friendly messages.  Possibly.  with an error code for the developers.

**Comment by ezaquarii** [comment]
@AndyScherzinger There is not much we can do in such case.

Any kind of global resource exhaustion (RAM, disk space, file descriptors) cause undefined behaviours in all parts of the system (read as "weird stuff happens all over my phone"), as people generally don't code for that scenario - maybe except the operating system itself.

On Linux, if you ran out of free space, you can't login anymore, so `/` filesystem have few % of space reserved for `root`, at least allowing a manual recovery. :)

@Mululu
> A normal error message in a pop-up window would be better here generally should
> be in case of error messages user-friendly messages.
> Possibly. with an error code for the developers.

In situation like this, we can't even guarantee that this window shows on the screen, because your entire phone is kind of "broken". We could make a good UX for that very specific path, but there are so many places that this can happen with completely undefined behaviors that fixing it is like boiling the ocean.

You can also expect similar issues in all other apps you have installed. Many of them will be silent about it, so you can imagine that your e-mail is suddently not syncing for some mysterious reasons, etc.

Our logs are capped to something like 4MB (and rotated), so I don't expect we are at risk of overflowing memory.

Wrapping up, this is very edge case, it can happen in background, and I think that the error message you got is good enough to troubleshoot it.

If we'd like to monitor device for disk space, this needs to be addressed in all parts of the code that write something to disk, mainly logs and sync. Also, a notification would be better output mechanism than a pop-up, as it is less invasive during background operations (sync is most likely to cause it as it pumps lare amount of data).

**Comment by AndyScherzinger** [comment]
@ezaquarii I agree. Like you said while it might be nice and while it be nice to have ID-ed error messages it would be a lot of work to impllement and I am also unsure about it benefit (cost/imapct wise)
