### ISSUE TITLE
[3.8.0RC4] Error searching for photos

### ISSUE THREAD

**Issue by szaimen** [nextcloud/android#4468]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.owncloud.android.lib.resources.files.SearchRemoteOperation.setLimit(int)' on a null object reference
	at com.owncloud.android.ui.asynctasks.PhotoSearchTask.doInBackground(PhotoSearchTask.java:87)
	at com.owncloud.android.ui.asynctasks.PhotoSearchTask.doInBackground(PhotoSearchTask.java:38)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080054
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: beyond0
Model: SM-G970F
Id: PPR1.180610.011
Product: beyond0lteeea

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G970FXXS3ASH1

**Comment by AndyScherzinger** [comment]
pinging @tobiasKaminsky since this is a 3.8.0RC issue

**Comment by szaimen** [comment]
There is unfortunately another Error in RC4: https://github.com/nextcloud/android/issues/4469
