### ISSUE TITLE
Crash on Huawei Mediapad M5 after login

### ISSUE THREAD

**Issue by marukuru** [nextcloud/android#4476]
### Actual behaviour
- Client crashes on File listing right after first login. Unusable after that.

### Expected behaviour
- File view
 
### Steps to reproduce
1. Start App
2. Login
3. Crash

### Environment data
Android version: 8

Device model: Huawei M5

Stock or customized system: Stock, unrooted

Nextcloud app version: 3.8.0 RC4

Nextcloud server version: 16.0.4

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED flg=0x2010 pkg=com.nextcloud.client (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver@6170706
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1533)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:891)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:7539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=10511, uid=1110183 requires android.permission.BROADCAST_STICKY
	at android.os.Parcel.createException(Parcel.java:1953)
	at android.os.Parcel.readException(Parcel.java:1921)
	at android.os.Parcel.readException(Parcel.java:1871)
	at android.app.IActivityManager$Stub$Proxy.unbroadcastIntent(IActivityManager.java:3873)
	at android.app.ContextImpl.removeStickyBroadcast(ContextImpl.java:1552)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
	at com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver.onReceive(FileDisplayActivity.java:1454)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1520)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080054
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWCMR09
Model: CMR-W09
Id: HUAWEICMR-W09
Product: CMR-W09

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 190C432R1
```

**Comment by marukuru** [comment]
Found #4205, installing with main user account serves as a workaround.

**Comment by AndyScherzinger** [comment]
Duplicate of #6654
