### ISSUE TITLE
FolderPicker - App crashes while rotating device

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#448]
### Current behaviour
App stops when the orientation is changed from portrait to landscape

### Expected behaviour
App rotates to landscape mode properly, showing the appropriate view. 

### Steps
1. Select files/folders.
2. Select copy or move in contextual menu.
3. Rotate screen.

### Environment data
Android version: 7.1.1

Device model: Nexus5X

Stock or customized system: stock

Nextcloud app version: 1.4.0

Nextcloud server version: 10.0.2

#### Android client log
```
12-13 10:36:15.095 16583-16583/com.nextcloud.client E/FolderPickerActivity: onPause() start
12-13 10:36:15.157 16583-16583/com.nextcloud.client E/AndroidRuntime: FATAL EXCEPTION: main
  Process: com.nextcloud.client, PID: 16583
  java.lang.NullPointerException: Attempt to invoke virtual method 'void com.owncloud.android.ui.fragment.OCFileListFragment$MultiChoiceModeListener.storeStateIn(android.os.Bundle)' on a null object reference
      at com.owncloud.android.ui.fragment.OCFileListFragment.onSaveInstanceState(OCFileListFragment.java:547)
      at android.support.v4.app.Fragment.performSaveInstanceState(Fragment.java:2244)
      at android.support.v4.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:1863)
      at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1931)
      at android.support.v4.app.FragmentController.saveAllState(FragmentController.java:134)
      at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:568)
      at android.support.v7.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:511)
      at com.owncloud.android.ui.activity.DrawerActivity.onSaveInstanceState(DrawerActivity.java:684)
      at com.owncloud.android.ui.activity.FileActivity.onSaveInstanceState(FileActivity.java:226)
      at android.app.Activity.performSaveInstanceState(Activity.java:1414)
      at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1300)
      at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4541)
      at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4492)
      at android.app.ActivityThread.-wrap19(ActivityThread.java)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:154)
      at android.app.ActivityThread.main(ActivityThread.java:6119)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by tobiasKaminsky** [comment]
PR is #649 by @carstendev
