### ISSUE TITLE
Crash when navigating away from photos (photo details not opening)

### ISSUE THREAD

**Issue by memen45** [nextcloud/android#4508]
### Actual behaviour
- crash

### Expected behaviour
- no crash 
- opening some details fragment? 
 
### Steps to reproduce
1. Open photo tab
2. Tap on a photo in the list
3. Tap on 'more' and then 'details'
4. Photo closes, back in the photo list, navigate to 'all files'
5. Receive crash report and submit on GitHub 😁

Nextcloud server version:
16.0.4

#### Web server error log
```
Insert your webserver log here
```no log entries

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.datamodel.OCFile.canWrite()' on a null object reference
	at com.owncloud.android.ui.fragment.OCFileListFragment.updateLayout(OCFileListFragment.java:1221)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1190)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1124)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onResume(FileDisplayActivity.java:1278)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1514)
	at android.app.Activity.performResume(Activity.java:7305)
	at android.app.ActivityThread.performNewIntents(ActivityThread.java:3260)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3275)
	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:49)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus6T
Model: ONEPLUS A6013
Product: OnePlus6T

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 1908012000

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by nakal** [comment]
Confirmed. I got this stack trace on release 3.8.0:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'long com.owncloud.android.datamodel.OCFile.getLastSyncDateForData()' on a null object reference
	at com.owncloud.android.ui.helpers.FileOperationsHelper.lambda$startSyncForFileAndIntent$0$FileOperationsHelper(FileOperationsHelper.java:209)
	at com.owncloud.android.ui.helpers.-$$Lambda$FileOperationsHelper$Q56PsCgyFZxef_IG4gCdZEuyyO8.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by nakal** [comment]
In 3.8.1 the image details don't work (another bug), so this bug cannot be reproduced.

**Comment by AndyScherzinger** [comment]
@nakal can you please open an issue describing in which way the image details don't work. Highly appreciate your efforts reporting issues 🙏

**Comment by nakal** [comment]
Thank you very much for the nice words.

I looked up and the issue has been already described in #4500.
