### ISSUE TITLE
App crashes on home folder (during refresh)

### ISSUE THREAD

**Issue by brennovich** [nextcloud/android#4512]
### Actual behaviour
- Open the app (already configured)
- Wait it crash (if force refresh it will crash sooner

### Expected behaviour
- Don't crash 

### Environment data

1. Server has server-side-encryption enabled

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.substring(int, int)' on a null object reference
	at com.owncloud.android.datamodel.OCFile.getLocalId(OCFile.java:493)
	at com.owncloud.android.utils.EncryptionUtils.downloadFolderMetadata(EncryptionUtils.java:221)
	at com.owncloud.android.operations.RefreshFolderOperation.getDecryptedFolderMetadata(RefreshFolderOperation.java:450)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:395)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:339)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:224)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:299)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20190906
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: santoni
Model: Redmi 4X
Id: OPM2.171026.006.C1
Product: lineage_santoni

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: b2e9cae7ac
```

**Comment by msecilmis** [comment]
I can take this one too

**Comment by tobiasKaminsky** [comment]
@brennovich from stack trace it seems that you use E2E instead of server side encryption?

**Comment by brennovich** [comment]
I migrate my nextcloud server to snap installation: https://github.com/nextcloud/nextcloud-snap

With this the encryption module did a different setup (the previous installation was old and already upgraded through lots of releases) which fixed the problem!
