### ISSUE TITLE
Application crash while setting up backup of a photo dir on Android 

### ISSUE THREAD

**Issue by kotecky** [nextcloud/android#4519]
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2080)
	at androidx.fragment.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2106)
	at androidx.fragment.app.FragmentManagerImpl.popBackStack(FragmentManager.java:846)
	at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:215)
	at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:191)
	at com.owncloud.android.ui.dialog.SyncedFolderPreferencesDialogFragment$OnSyncedFolderCancelClickListener.onClick(SyncedFolderPreferencesDialogFragment.java:507)
	at android.view.View.performClick(View.java:6256)
	at android.view.View$PerformClick.run(View.java:24710)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:251)
	at android.app.ActivityThread.main(ActivityThread.java:6589)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Sony
Device: F5321
Model: F5321
Id: 34.4.A.2.118
Product: F5321

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: 1631208121

**Comment by msecilmis** [comment]
I can take this one too
