### ISSUE TITLE
Crash when deleting on Android app

### ISSUE THREAD

**Issue by Thovi98** [nextcloud/android#4520]
### Actual behaviour
- When I delete multiple photos from my Nextcloud in my Android app, it crashes.

### Expected behaviour
- Delete witout crash.

### Environment data
Android version: 9.0

Device model: Redmi Note 4 SD (mido)

Stock or customized system: custom - Syberia OS

Nextcloud app version: 3.8.0

Nextcloud server version: 15.0.10 (Yunohost)

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Couldn't read row 987, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetString(Native Method)
	at android.database.CursorWindow.getString(CursorWindow.java:465)
	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
	at android.database.CursorWrapper.getString(CursorWrapper.java:137)
	at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:954)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:864)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:157)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:719)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1179)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1124)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1113)
	at com.owncloud.android.ui.activity.FileDisplayActivity.refreshListOfFilesFragment(FileDisplayActivity.java:742)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoveFileOperationFinish(FileDisplayActivity.java:1909)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoteOperationFinish(FileDisplayActivity.java:1829)
	at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:727)
	at com.owncloud.android.services.-$$Lambda$OperationsService$2BVgsxDpOpa4JqgzeD7OGZBLSiI.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6693)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:861)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: mido
Model: Redmi Note 4
Id: PQ3B.190801.002
Product: syberia_mido

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 495

```

**Comment by msecilmis** [comment]
I can take this one too

**Comment by tobiasKaminsky** [comment]
@msecilmis you can, but do you have an idea? 
For me it looks like for unknown reason the database could not read an needed value.
But stack trace does not say anything about which file or why.

**Comment by msecilmis** [comment]
I have no idea yet, if i get the issue i'll try to reproduce the issue. If noone's assigned please assign it to me
