### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by 150d** [nextcloud/android#4521]
### Actual behaviour
app crashes
 
### Steps to reproduce
have NextCload app running in the background

### Environment data
Android version: 9

Device model: Samsung SG5

Stock or customized system: LineageOS

crash report:

************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
	at com.google.firebase.iid.zzg.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-w61mokhkXge3CqxSSsmsnw==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-w61mokhkXge3CqxSSsmsnw==/lib/arm, /data/app/com.nextcloud.client-w61mokhkXge3CqxSSsmsnw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: klte
Model: SM-G900F
Id: PQ3A.190801.002
Product: lineage_klte

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 11a7517746

**Comment by tobiasKaminsky** [comment]
@150d do you have gcm / gplay / google on your LineageOS?

**Comment by 150d** [comment]
Yes, I do.

(Except I don't really know what "gcm" is...? Play Store is running perfectly, though.)

What may be the problem: In the trace there is something about Google Analytics. I have basic protection against Spyware active, in my case "AdAway". It is very possible that some URLs have been blocked. Of course, that would be all the more reason for shaming the NextCloud client for not only employing Spyware in the first place, but also not being to handle the problems this Spyware causes.

Of course this is all just speculation on my side - I have never seen it stated that NextCloud would use Google Analytics, nor have I consented to this. Naturally, I thus assume that NextCloud doesn't do so. Right?

**Comment by tobiasKaminsky** [comment]
We do not have any Analytic/Firebase included.
We only use GCM for Push Notifications.
A complete FOSS version is available at Fdroid (with lack of push notifications).

To track further, please see #4586
