### ISSUE TITLE
Nextcloud Android app Crashes after logging in

### ISSUE THREAD

**Issue by takom13** [nextcloud/android#4524]
### Actual behaviour
- Open Nextcloud app, crashes before any action happens

### Expected behaviour
- Be able to use the app without it crashing
 
### Steps to reproduce
1. Install Nextcloud app
2. Connect to Nextcloud server
3. Login

### Environment data
Android version: Android 10

Device model: Google Pixel XL 2

Stock or customized system: Stock

Nextcloud app version: Not sure. Downloaded from play store

Nextcloud server version: 16.04

#### Web server error log
```

```************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Couldn't read row 998, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:542)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:77)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:172)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:127)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:177)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:127)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:177)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:127)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:177)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:127)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:107)
	at android.content.ContentProviderOperation.applyInternal(ContentProviderOperation.java:332)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:309)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:661)
	at android.content.ContentProvider.applyBatch(ContentProvider.java:2117)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:371)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:532)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:520)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:1875)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:399)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:441)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:339)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:224)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:299)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: taimen
Model: Pixel 2 XL
Id: QP1A.190711.019
Product: taimen

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 5790879


#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by msecilmis** [comment]
I can take this one too

**Comment by krharsh17** [comment]
@takom13 Just a bit of a suggestion, try to use more descriptive titles while creating issues. It really feels good to have a few seconds saved :)
