### ISSUE TITLE
Error when grant access 

### ISSUE THREAD

**Issue by bakhshb** [nextcloud/android#4527]
### Actual behaviour
- Tell us what happens
1- open app
2- entered my domain and credentials. 

Error screen with system logs pop up. I exited the app and open it again, I can see my files synced but I cannot access any of them and a notification says " Download failed, Moved permanently"
### Expected behaviour
- Tell us what should happen
 I should be able to access my files and download them. 
I should be able to 
### Steps to reproduce
1. In nextcloud app manage account
2. Remove account
3. Go to App info
4- Clear Cache 
5- Clear Storage
6- Open the app
7- Enter domain and credentials. 

### Environment data
Android: 10
Phone:Pixel3a
Nextcloud Version:16
Nextcloud App Version: 3.8.0

************ CAUSE OF ERROR ************

android.view.InflateException: Binary XML file line #7 in com.nextcloud.client:layout/account_setup_webview: Binary XML file line #7 in com.nextcloud.client:layout/account_setup_webview: Error inflating class android.webkit.WebView
Caused by: android.view.InflateException: Binary XML file line #7 in com.nextcloud.client:layout/account_setup_webview: Error inflating class android.webkit.WebView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:854)
	at android.view.LayoutInflater.createView(LayoutInflater.java:776)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:930)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:950)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
	at com.owncloud.android.authentication.AuthenticatorActivity.onGetServerInfoFinish(AuthenticatorActivity.java:1300)
	at com.owncloud.android.authentication.AuthenticatorActivity.onRemoteOperationFinish(AuthenticatorActivity.java:1199)
	at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:727)
	at com.owncloud.android.services.-$$Lambda$OperationsService$2BVgsxDpOpa4JqgzeD7OGZBLSiI.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377
	at org.chromium.android_webview.AwBrowserProcess.b(PG:12)
	at n6.m(PG:33)
	at n6.a(PG:48)
	at n6.b(PG:16)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.a(PG:32)
	at com.android.webview.chromium.WebViewChromium.init(PG:12)
	at android.webkit.WebView.<init>(WebView.java:429)
	at android.webkit.WebView.<init>(WebView.java:353)
	at android.webkit.WebView.<init>(WebView.java:336)
	at android.webkit.WebView.<init>(WebView.java:323)
	... 27 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: sargo
Model: Pixel 3a
Id: QP1A.190711.020
Product: sargo

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 5800535

#### Web server error log
```
Insert your webserver log here
```
No Error Log
#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
No Error Log
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by bakhshb** [comment]
I just noticed that if the name of the file contains space or number, it will not download and it will show a message file has been moved permanently.

**Comment by bakhshb** [comment]
I have solved the problem of accessing my files by going to setting in the web and generate a new app password and use the generated QR to setup nextcloud app. 

Using this way, it allowed me to skip the step of clicking the button "grant access".

**Comment by ezaquarii** [comment]
This problem could be related to this breaking change in API:

https://developer.android.com/about/versions/pie/android-9.0-changes-28
