### ISSUE TITLE
Password manager crash

### ISSUE THREAD

**Issue by dabbill** [nextcloud/android#4531]
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Cannot execute task: the task has already been executed (a task can be executed only once)
	at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:640)
	at android.os.AsyncTask.execute(AsyncTask.java:595)
	at com.owncloud.android.ui.adapter.NotificationListAdapter.lambda$onBindViewHolder$2$NotificationListAdapter(NotificationListAdapter.java:182)
	at com.owncloud.android.ui.adapter.-$$Lambda$NotificationListAdapter$TXM0JwRxGeq8tl4SIWzikYjFQ-k.onClick(Unknown Source:8)
	at android.view.View.performClick(View.java:6615)
	at android.view.View.performClickInternal(View.java:6587)
	at android.view.View.access$3500(View.java:784)
	at android.view.View$PerformClick.run(View.java:26047)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6854)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: lge
Device: judyln
Model: LM-G710
Id: PKQ1.181105.001
Product: judyln_lao_com

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 191831446539b

**Comment by AndyScherzinger** [comment]
Should be fixed with 3.9.0
