### ISSUE TITLE
Crashed by running in the background 

### ISSUE THREAD

**Issue by OiledAmoeba** [nextcloud/android#4548]
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Couldn't read row 1772, col 1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetString(Native Method)
	at android.database.CursorWindow.getString(CursorWindow.java:465)
	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
	at android.database.CursorWrapper.getString(CursorWrapper.java:137)
	at com.owncloud.android.datamodel.UploadsStorageManager.createOCUploadFromCursor(UploadsStorageManager.java:320)
	at com.owncloud.android.datamodel.UploadsStorageManager.getUploads(UploadsStorageManager.java:301)
	at com.owncloud.android.datamodel.UploadsStorageManager.getFailedUploads(UploadsStorageManager.java:372)
	at com.owncloud.android.files.services.FileUploader$UploadRequester.retryFailedUploads(FileUploader.java:405)
	at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:251)
	at com.owncloud.android.utils.-$$Lambda$FilesSyncHelper$kKNrggliFpEukU1kV4bap8ektCs.run(Unknown Source:12)
	at java.lang.Thread.run(Thread.java:784)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWVOG
Model: VOG-L29
Id: HUAWEIVOG-L29
Product: VOG-L29EEA

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 9.1.0.193C431

**Comment by tobiasKaminsky** [comment]
I saw this from time to time, but never could reproduce it.
Overall this is quite strange, as we write something to database (OCUpload) and later read back from database. No one can access it inbetween.
