### ISSUE TITLE
Start and crash after setup

### ISSUE THREAD

**Issue by My1** [nextcloud/android#4553]
### Actual behaviour
- start and crash
- or if not yet setup, start setup and crash

### Expected behaviour
- well no crash
 
### Steps to reproduce
See above 

### Environment data
Android version:
O
Device model: 
Xperia xa2 (H3113) 
Stock or customized system:
Stock
Nextcloud app version:
3.8.0
Nextcloud server version:
16.0.4
#### app error log
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.files.services.FileUploaderUPLOAD_FINISH flg=0x10 pkg=com.nextcloud.client (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$UploadFinishReceiver@2421bcc
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1412)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:280)
	at android.app.ActivityThread.main(ActivityThread.java:6706)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=10982, uid=1010298 requires android.permission.BROADCAST_STICKY
	at android.os.Parcel.createException(Parcel.java:1969)
	at android.os.Parcel.readException(Parcel.java:1935)
	at android.os.Parcel.readException(Parcel.java:1885)
	at android.app.IActivityManager$Stub$Proxy.unbroadcastIntent(IActivityManager.java:3903)
	at android.app.ContextImpl.removeStickyBroadcast(ContextImpl.java:1346)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
	at com.owncloud.android.ui.activity.FileDisplayActivity$UploadFinishReceiver.onReceive(FileDisplayActivity.java:1575)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1397)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.unbroadcastIntent(ActivityManagerService.java:22677)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:183)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3421)
	at android.os.Binder.execTransact(Binder.java:731)


************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Sony
Device: H3113
Model: H3113
Id: 50.2.A.0.400
Product: H3113

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 3640285821
```

**Comment by AndyScherzinger** [comment]
Duplicate of #6654
