### ISSUE TITLE
Tried to log in, got this error

### ISSUE THREAD

**Issue by BetaLeaf** [nextcloud/android#4559]
************ CAUSE OF ERROR ************

android.database.SQLException: ERROR content://org.nextcloud/file
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:280)
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:248)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:309)
	at android.content.ContentResolver.insert(ContentResolver.java:1828)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFile(FileDataStorageManager.java:245)
	at com.owncloud.android.datamodel.FileDataStorageManager.createRootDir(FileDataStorageManager.java:882)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:109)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onAccountSet(FileDisplayActivity.java:450)
	at com.owncloud.android.ui.activity.BaseActivity.onStart(BaseActivity.java:197)
	at com.owncloud.android.ui.activity.DrawerActivity.onStart(DrawerActivity.java:1415)
	at com.owncloud.android.ui.activity.FileActivity.onStart(FileActivity.java:207)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2632)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
	at android.app.Activity.performStart(Activity.java:7825)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:183)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:132)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: taimen
Model: Pixel 2 XL
Id: QP1A.190711.020
Product: taimen

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 5800535

**Comment by tobiasKaminsky** [comment]
Hm. No idea.
Did this happen only once?

**Comment by milanvanzanten** [comment]
Related to #4559.

A client got the same error with the device info:
```
************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: jactivelte
Model: GT-I9295
Id: LRX22C
Product: jactiveltexx

************ FIRMWARE ************
SDK: 21
Release: 5.0.1
Incremental: I9295XXSDPL3
```

**Comment by J0WI** [comment]
It would be easier to debug this if [insertOrThrow](https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#insertOrThrow()) was used.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @J0WI fancy opening a pull request? :)
