### ISSUE TITLE
App crash while opening photo

### ISSUE THREAD

**Issue by CaptainBalou** [nextcloud/android#4562]
Opened app, opened sub menu photos, clicked one of the photos, then the app crashed with this:

************ CAUSE OF ERROR ************

java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{8ef531a position=28 id=-1, oldPos=-1, pLpos:-1 no parent} com.owncloud.android.ui.EmptyRecyclerView{c9f7a9f VFED..... .F...... 0,0-1080,1699 #7f090162 app:id/list_root}, adapter:com.owncloud.android.ui.adapter.OCFileListAdapter@7cc6d4, layout:androidx.recyclerview.widget.GridLayoutManager@5ad707d, context:com.owncloud.android.ui.activity.FileDisplayActivity@893d400
	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5715)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5898)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:286)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:343)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:359)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:366)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:397)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: herolte
Model: SM-G930F
Id: R16NW
Product: heroltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: G930FXXS5ESF1

**Comment by CaptainBalou** [comment]
Additional information:
This happens only on photos which are downloaded.
If I open a picture which is not downloaded the preview is shown and after it is loaded it is shown in full resolution w/o error.

**Comment by CaptainBalou** [comment]
Additional info:
Happens in current dev version 20190928 too.

**Comment by CaptainBalou** [comment]
The behaviour is the same but the error message changed:

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'long com.owncloud.android.datamodel.OCFile.getLastSyncDateForData()' on a null object reference
	at com.owncloud.android.ui.helpers.FileOperationsHelper.lambda$startSyncForFileAndIntent$0$FileOperationsHelper(FileOperationsHelper.java:209)
	at com.owncloud.android.ui.helpers.-$$Lambda$FileOperationsHelper$Q56PsCgyFZxef_IG4gCdZEuyyO8.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20191002
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: samsung
Device: herolte
Model: SM-G930F
Id: R16NW
Product: heroltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: G930FXXS5ESF1

**Comment by CaptainBalou** [comment]
#4575

**Comment by tobiasKaminsky** [comment]
> com.owncloud.android.datamodel.OCFile.getLastSyncDateForData()' on a null object reference
> at

This is fixed via #4592
and should be in any dev version > 20191002
