### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by qcy-hash** [nextcloud/android#4565]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED flg=0x10 pkg=com.nextcloud.client (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver@c5dced4
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1493)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6990)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=17792, uid=15010504 requires android.permission.BROADCAST_STICKY
	at android.os.Parcel.createException(Parcel.java:1966)
	at android.os.Parcel.readException(Parcel.java:1934)
	at android.os.Parcel.readException(Parcel.java:1884)
	at android.app.IActivityManager$Stub$Proxy.unbroadcastIntent(IActivityManager.java:3782)
	at android.app.ContextImpl.removeStickyBroadcast(ContextImpl.java:1425)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:601)
	at com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver.onReceive(FileDisplayActivity.java:1466)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1483)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.unbroadcastIntent(ActivityManagerService.java:26528)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:155)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4126)
	at android.os.Binder.execTransact(Binder.java:739)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: crownlte
Model: SM-N960F
Id: PPR1.18061
Product: crownltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: N960FXXS3CSH

**Comment by AndyScherzinger** [comment]
Duplicate of #6654
