### ISSUE TITLE
Crash on open in work profile (created by shelter)

### ISSUE THREAD

**Issue by riedel** [nextcloud/android#4573]
### Actual behaviour
- Tell us what happens
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED flg=0x10 pkg=com.nextcloud.client (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver@43fc12e
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1401)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=1420, uid=1010159 requires android.permission.BROADCAST_STICKY
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.app.IActivityManager$Stub$Proxy.unbroadcastIntent(IActivityManager.java:3920)
	at android.app.ContextImpl.removeStickyBroadcast(ContextImpl.java:1346)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
	at com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver.onReceive(FileDisplayActivity.java:1466)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1391)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.unbroadcastIntent(ActivityManagerService.java:22175)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:183)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3377)
	at android.os.Binder.execTransact(Binder.java:731)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: lavender
Model: Redmi Note 7
Id: PQ3A.190801.002
Product: lavender

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: eng.root.20190916.232339
### Steps to reproduce
1.  Open app after granting access

### Environment data
Android version:
9
Device model: 
Redmi note 7
Stock or customized system:
Lineage 16

**Comment by riedel** [comment]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED flg=0x10 pkg=com.nextcloud.client (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver@56aab7f
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1401)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=7372, uid=1010175 requires android.permission.BROADCAST_STICKY
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.app.IActivityManager$Stub$Proxy.unbroadcastIntent(IActivityManager.java:3920)
	at android.app.ContextImpl.removeStickyBroadcast(ContextImpl.java:1346)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
	at com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver.onReceive(FileDisplayActivity.java:1466)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1391)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.unbroadcastIntent(ActivityManagerService.java:22175)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:183)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3377)
	at android.os.Binder.execTransact(Binder.java:731)


************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20190914
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: lavender
Model: Redmi Note 7
Id: PQ3A.190801.002
Product: lavender

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: eng.root.20190916.232339

**Comment by tobiasKaminsky** [comment]
> Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=7372, uid=1010175 requires android.permission.BROADCAST_STICKY

Hm. We did not changed anything in this matter…
And I also use LineageOS, but never experienced that crash.

**Comment by riedel** [comment]
I actually tried to install it outside my work profile and it works now. Really strangely it now even stopped crashing in my work profile after having it installed in the main profile. I am happy for now :)

Maybe someone can recreate it by installing it inside of https://github.com/PeterCxy/Shelter.  If not I would close the issue...

**Comment by AndyScherzinger** [comment]
Duplicate of #6654
