### ISSUE TITLE
Crash in Favorites

### ISSUE THREAD

**Issue by JR0815** [nextcloud/android#4578]
### Actual behaviour
- Tell us what happens
Nextcloud App crashed when I selected Favorites in the menu. 

#### Nextcloud log (data/nextcloud.log)
```


************ CAUSE OF ERROR ************

java.lang.NullPointerException
	at java.io.File.<init>(File.java:282)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.onBindViewHolder(OCFileListAdapter.java:433)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
	at android.view.View.layout(View.java:19599)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
	at android.view.View.layout(View.java:19599)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1183)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:870)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:889)
	at android.view.View.layout(View.java:19599)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
	at android.view.View.layout(View.java:19599)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19599)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1780)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1546)
	at android.view.View.layout(View.java:19599)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:19599)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:19599)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19599)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19599)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19599)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:19599)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:767)
	at android.view.View.layout(View.java:19599)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2488)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2204)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1390)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6754)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
	at android.view.Choreographer.doCallbacks(Choreographer.java:778)
	at android.view.Choreographer.doFrame(Choreographer.java:713)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:251)
	at android.app.ActivityThread.main(ActivityThread.java:6589)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Sony
Device: F5321
Model: F5321
Id: 34.4.A.2.118
Product: F5321

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: 1631208121

**Comment by ezaquarii** [comment]
@tobiasKaminsky @AndyScherzinger 

It looks like `file.getStoragePath()` returns `null`  and `File` constructor explicitly asserts with NPE as a result.

I don't know `OCFile` design too well, but it looks fir me like `onlyOnDevice` and `getStoragePath()` should be consistent. Is there any edge case there?
```
                if (onlyOnDevice) {
                    File localFile = new File(file.getStoragePath());

                    long localSize;
                    if (localFile.isDirectory()) {
                        localSize = FileStorageUtils.getFolderSize(localFile);
                    } else {
                        localSize = localFile.length();
                    }

                    itemViewHolder.fileSize.setText(DisplayUtils.bytesToHumanReadable(localSize));
                } 
```

**Comment by tobiasKaminsky** [comment]
What does this have to do with "favorites"? 
According to code the new File(file.getStoragePath()) is only used when "onlyOnDevice" is true.

Now the other question is why is storage path null…

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/android/blob/d445be1b5ff67540759800d87e1eca0bd6a8bdfb/src/main/java/com/owncloud/android/datamodel/OCFile.java#L342

Seeing when this is called with "null" shows that this is only done when deleting a file/folder.
But then the entire database entry should be gone, so it also should not be shown anylonger.
