### ISSUE TITLE
Error repoducion video android

### ISSUE THREAD

**Issue by ederleonel** [nextcloud/android#4582]
### Actual behaviour
- Tell us what happens

### Expected behaviour
- Tell us what should happen
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Fragment PreviewMediaFragment{8c82558} not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:696)
	at androidx.fragment.app.Fragment.getResources(Fragment.java:760)
	at androidx.fragment.app.Fragment.getString(Fragment.java:782)
	at com.owncloud.android.ui.preview.PreviewMediaFragment$LoadStreamUrl.onPostExecute(PreviewMediaFragment.java:564)
	at com.owncloud.android.ui.preview.PreviewMediaFragment$LoadStreamUrl.onPostExecute(PreviewMediaFragment.java:531)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.access$600(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7045)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: dream2lte
Model: SM-G955F
Id: PPR1.180610.011
Product: dream2ltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G955FXXS5DSH4

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by ezaquarii** [comment]
This should be fixed in #4577
