### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: com/google/firebase/analytics/connector/AnalyticsConnector

### ISSUE THREAD

**Issue by Axxxolotl** [nextcloud/android#4586]
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
	at com.google.firebase.iid.zzg.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:784)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-QVkLiMdY4I5mEwlDH_HfkA==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-QVkLiMdY4I5mEwlDH_HfkA==/lib/arm64, /data/app/com.nextcloud.client-QVkLiMdY4I5mEwlDH_HfkA==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 9 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HONOR
Device: HWCOL
Model: COL-L29
Id: HUAWEICOL-L29
Product: COL-L29RU

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 325C10

**Comment by tobiasKaminsky** [comment]
Do you know when this happens?

**Comment by Axxxolotl** [comment]
Unfortunately, I did not notice a certain pattern. I got a new phone about 2 weeks ago. During this time, this appeared 4 times. This happened both when using the "nextcloud" application itself, and while using other applications. Once this error report arose simply when I looked at the screen without launching any applications.
In the phone settings, the application is allowed to work in the background.

**Comment by Axxxolotl** [comment]
Unfortunately, I did not notice a certain pattern. I got a new phone about 2 weeks ago. During this time, this appeared 4 times. This happened both when using the "nextcloud" application itself, and while using other applications. Once this error report arose simply when I looked at the screen without launching any applications.
In the phone settings, the application is allowed to work in the background.

**Comment by albertomna** [comment]
It also happens to me often, especially after the synchronization of some contacts with Davx5.
It's happening more and more frequently.
Android 9 Operating System

**Comment by Chartman123** [comment]
I get the same crashes. It seems to me, that the crash occurs when there is a new notification on the server and the message gets pushed to the client.

**Comment by albertomna** [comment]
Yes i confirm this. Every time that i try to change an information in my Contacts,  the app crashed.

**Comment by tobiasKaminsky** [comment]
This is strange, we did not changed anything in this matter.
@albertomna do you change this locally on your phone?

**Comment by albertomna** [comment]
@tobiasKaminsky Thanks for the reply. No, the change was done directly on Nextcloud on PC  through Browser. I sync with the Davx5 application, contacts and calendar,and seems that everytime i change one contact or calendar on My  PC through Browser, the smartphone app crashed

**Comment by tobiasKaminsky** [comment]
> and seems that everytime i change one contact or calendar on My PC through Browser, the smartphone app crashed

@georgehrke do you have an idea here?
Are there any push notifications send?

**Comment by georgehrke** [comment]
If anything it generates a new Activity, but no push.

**Comment by georgehrke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
Yeah, contacts dont even have activites atm.

**Comment by tobiasKaminsky** [comment]
I can only reproduce this when I install our gplay app on an emulator/device without any google services.
If you have a regular device with play services, then this error should not happen.
if you have a FOSS-only device, please use the version from Fdroid.

**Comment by Chartman123** [comment]
I've installed the app from Google Play and have the Play services on my device, too. Should I provide you with a logcat?

**Comment by tobiasKaminsky** [comment]
@Chartman123 it might be worth a try :+1:

**Comment by ezaquarii** [comment]
Current firebase messaging is available in version 20. We're using 17.

Since we have devices that fail consitently, we could ugrade to 20 and try it out.

**Comment by tobiasKaminsky** [comment]
Hm. I tried to update it locally to 20, but it did not helped.
What instead helped was to remove this:
https://github.com/nextcloud/android/blob/master/build.gradle#L48-L50

But this is something we have to verify what the impact in regard of privacy is.

**Comment by Chartman123** [comment]
Just a quick note: After upgrading my phone to Android 10 and reinstalling the Nextcloud app everything works fine again.

**Comment by Chartman123** [comment]
And it came back after some time...

**Comment by AaronADev** [comment]
I can confirm this issue is now re-occuring especially when 2FA Notifications are enabled. I have a Galaxy S9+ that this happens on. It must be related to the SDK version or something related to the phones they occur on. I have an older, Samsung Galaxy Tab 8.0 that this does NOT occur on during the same notification request.

Here is an additional stack trace from my phone:
```
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
	at com.google.firebase.iid.zzg.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-e6q-dth1im7MasFXkHZR3A==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-e6q-dth1im7MasFXkHZR3A==/lib/arm64, /data/app/com.nextcloud.client-e6q-dth1im7MasFXkHZR3A==/base.apk!/lib/arm64-v8a, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: star2qltesq
Model: SM-G965U
Id: PPR1.180610.011
Product: star2qltesq

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G965USQU7CSK6
```

@tobiasKaminsky Any ideas?

Thanks ya'll. Hope this gets resolved soon!

**Comment by JanHellwig** [comment]
I had the same crash twice today. Both were just there when unlocking my phone. There was a notification due to an update for the TOTP plugin in my Nextcloud and I think it might have been related to that as nothing changed in my setup for a while now.

```
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
at com.google.firebase.iid.zzg.run(Unknown Source:4)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client--gj-5oHllB4BdJCQ6oFGBA==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client--gj-5oHllB4BdJCQ6oFGBA==/lib/arm64, /data/app/com.nextcloud.client--gj-5oHllB4BdJCQ6oFGBA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Sony
Device: H8324
Model: H8324
Id: 52.0.A.11.32
Product: H8324

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 770735829
```

**Comment by b52** [comment]
I second this. I basically see the same crash on a bi-daily basis.

**Comment by galandilias** [comment]
Why closed?

**Comment by tobiasKaminsky** [comment]
Duplicate of #4675
