### ISSUE TITLE
[Crash] Couldn't read row 1062

### ISSUE THREAD

**Issue by Tie-fighter** [nextcloud/android#4614]
### Actual behaviour
- App crashes when updating files view

### Expected behaviour
- Should not crash
 
### Steps to reproduce
0. Have a large nextcloud instance?
1. Open the app
2. Swipe down in the files view
3. App becomes unresponsive and crashes. (App seems to always crash with "Couldn't read row 1062")

************ CAUSE OF ERROR ************
java.lang.IllegalStateException: Couldn't read row 1062, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:511)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:172)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:127)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:177)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:127)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:177)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:127)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:177)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:127)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:107)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:311)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:661)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:315)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:419)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:1275)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:399)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:441)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:339)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:224)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:299)
	at java.lang.Thread.run(Thread.java:818)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: oneplus
Device: A0001
Model: A0001
Id: MHC19Q
Product: bacon

************ FIRMWARE ************
SDK: 23
Release: 6.0.1
Incremental: 2b5f277d1c

**Comment by tobiasKaminsky** [comment]
Hm. This seems that for some unknown reason the database has a problem.
Have you ever restored a backup? Switched device and moved app?

I fear that the only way is to delete the app and re-setup it.

**Comment by Tie-fighter** [comment]
No backup has been restored, no device was switches, no app moved.
The problems coincide with me adding a lot of files to the instance and moving them around.
I have tried deleting the App's Cache without result.
I am using two different nextcloud instances (university and private), so I didn't delete the app but only the private account that was giving me trouble. After re-enrolling the problem still persists

I will try deleting and reinstalling the app.

**Comment by Tie-fighter** [comment]
Reinstalling fixed the issue 👍
