### ISSUE TITLE
Crash after granting app permission for login

### ISSUE THREAD

**Issue by 3j9fkyahunqoxwqu** [nextcloud/android#4615]
### Actual behaviour
- app crashes

### Expected behaviour
- app should show files in account 
 
### Steps to reproduce
1. Login to your nextcloud instance 
2. Grant the permission for app to login
3. Grant or prevent file permission (for android system) that app requests from you
4. App crashes
5. Open app again and app crashes even after force stop and... 

### Environment data
Android version: 9

Device model: Honor 10 lite

Stock or customized system: stock - work profile 

Nextcloud app version: latest - 3.8.0

Nextcloud server version: 16.0.4

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

Crash log:

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED flg=0x10 pkg=com.nextcloud.client (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver@98aff4e
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1533)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:891)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:7539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=12382, uid=1010280 requires android.permission.BROADCAST_STICKY
	at android.os.Parcel.createException(Parcel.java:1953)
	at android.os.Parcel.readException(Parcel.java:1921)
	at android.os.Parcel.readException(Parcel.java:1871)
	at android.app.IActivityManager$Stub$Proxy.unbroadcastIntent(IActivityManager.java:3873)
	at android.app.ContextImpl.removeStickyBroadcast(ContextImpl.java:1552)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
	at com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver.onReceive(FileDisplayActivity.java:1466)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1520)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.unbroadcastIntent(ActivityManagerService.java:23812)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:183)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3632)
	at com.android.server.am.HwActivityManagerService.onTransact(HwActivityManagerService.java:628)
	at android.os.Binder.execTransact(Binder.java:739)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HONOR
Device: HWHRY-H
Model: HRY-LX1MEB
Id: HONORHRY-LX1MEB
Product: HRY-LX1MEB

************ FIRMWARE ************
SDK: 28
Release: 9

**Comment by tobiasKaminsky** [comment]
> Stock or customized system: stock - work profile

Can you try it without a work profile?

**Comment by 3j9fkyahunqoxwqu** [comment]
Hi
Yes, i tested and it worked without any crash.

**Comment by 3j9fkyahunqoxwqu** [comment]
Hello
Please fix this issue
Thanks

**Comment by 3j9fkyahunqoxwqu** [comment]
Hello
Any update?

**Comment by 3j9fkyahunqoxwqu** [comment]
Hello
Please fix this problem.

**Comment by 3j9fkyahunqoxwqu** [comment]
Sorry but it is funny that Nextcloud is focused on business and its android app still won't work in work profile and even don't care at all.

**Comment by AndyScherzinger** [comment]
Duplicate of #6654
