### ISSUE TITLE
Nextcloud client android crashes caller no longer running

### ISSUE THREAD

**Issue by myroad94** [nextcloud/android#4618]
### Actual behaviour
- Out of nowhere this morninf, nextcloud client android crashes each time I open it.

### Expected behaviour
- It should open normally.
 
### Steps to reproduce
1. Open nextcloud client.

### Environment data
Android version:
LineageOs 9
Device model: 
OnePlus 3t
Stock or customized system:
Custom
Nextcloud app version:
3.8.0
Nextcloud server version:
16.0.3

Also, I have two nextcloud server, identical in version.

#### Web server error log
```
No real log: there are logs relates to my PC nextcloud client but nothing for android when it crashes.
```

#### Nextcloud log (data/nextcloud.log)
```

```
Nextcloud client stacktrace log
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.SecurityException: Caller no longer running, last stopped +2s616ms because: timed out while starting
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:195)
	at android.app.job.JobParameters.dequeueWork(JobParameters.java:243)
	at androidx.core.app.JobIntentService$JobServiceEngineImpl.dequeueWork(JobIntentService.java:315)
	at androidx.core.app.JobIntentService.dequeueWork(JobIntentService.java:640)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:390)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobServiceContext.assertCallerLocked(JobServiceContext.java:481)
	at com.android.server.job.JobServiceContext.doDequeueWork(JobServiceContext.java:359)
	at com.android.server.job.JobServiceContext$JobCallback.dequeueWork(JobServiceContext.java:160)
	at android.app.job.IJobCallback$Stub.onTransact(IJobCallback.java:83)
	at android.os.Binder.execTransact(Binder.java:731)


************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus3T
Model: ONEPLUS A3003
Id: PQ3A.190801.002
Product: lineage_oneplus3

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 63bfeb526b

```

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by myroad94** [comment]
I restores the app and data (from yesterday backup) after uninstall, same issue. I uninstalled and reconfigureanually: no more crashes. I guess there was some issue in my client. Probably because I do a backup every night of all app + data + SMS, the upload list was maybe too long...

I could reproduce if I reinstall from my backup but I guess if noone has an idea, I will close it.

**Comment by tobiasKaminsky** [comment]
Seems that on each job a timestamp is saved, and when restoring the app, this will lead to a crash.
But the whole job system is Android, not our system.

Sorry to not have a good idea, but if it is now working, I am closing it.

**Comment by myroad94** [comment]
Hi @tobiasKaminsky,

I just read the message. I don't understand your analysis: the error occurred _before_ the restore. I thought restoring would be a workaround but it is not.
Moreover, is-it a job mechanism issue? The job in question fails in timeout, I read this as: something is wrong in the content of the job, not the job engine itself, is-it?
