### ISSUE TITLE
fail on logon

### ISSUE THREAD

**Issue by rootbdfy** [nextcloud/android#4619]
### Actual behaviour
Fail when push logon button.

### Environment data
Android version: 7.1.2

Device model: Meizu M6note fw 7.2.0.0A

Stock or customized system: stock. tested again after fresh installation.

Nextcloud app version: all 3.*

Nextcloud server version:16.0.5

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineForOffset(int)' on a null object reference
at android.widget.Editor.updateCursorPositionMz(Editor.java:7836)
at android.widget.Editor.updateCursorsPositions(Editor.java:1963)
at android.widget.TextView.getUpdatedHighlightPath(TextView.java:5783)
at android.widget.TextView.onDraw(TextView.java:5969)
at com.owncloud.android.ui.components.CustomEditText.onDraw(CustomEditText.java:71)
at android.view.View.draw(View.java:17305)
at android.view.View.updateDisplayListIfDirty(View.java:16282)
at android.view.View.draw(View.java:17066)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.updateDisplayListIfDirty(View.java:16277)
at android.view.View.draw(View.java:17066)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.draw(View.java:17308)
at com.google.android.material.textfield.TextInputLayout.draw(TextInputLayout.java:1577)
at android.view.View.updateDisplayListIfDirty(View.java:16282)
at android.view.View.draw(View.java:17066)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.updateDisplayListIfDirty(View.java:16277)
at android.view.View.draw(View.java:17066)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.updateDisplayListIfDirty(View.java:16277)
at android.view.View.draw(View.java:17066)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.updateDisplayListIfDirty(View.java:16277)
at android.view.View.draw(View.java:17066)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.draw(View.java:17308)
at android.widget.ScrollView.draw(ScrollView.java:1743)
at android.view.View.updateDisplayListIfDirty(View.java:16282)
at android.view.View.draw(View.java:17066)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.updateDisplayListIfDirty(View.java:16277)
at android.view.View.draw(View.java:17066)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.updateDisplayListIfDirty(View.java:16277)
at android.view.View.draw(View.java:17066)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.updateDisplayListIfDirty(View.java:16277)
at android.view.View.draw(View.java:17066)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.updateDisplayListIfDirty(View.java:16277)
at android.view.View.draw(View.java:17066)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.draw(View.java:17308)
at com.android.internal.policy.DecorView.draw(DecorView.java:786)
at android.view.View.updateDisplayListIfDirty(View.java:16282)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:661)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:667)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:775)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:2837)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2639)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2241)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1276)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6483)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:888)
at android.view.Choreographer.doCallbacks(Choreographer.java:700)
at android.view.Choreographer.doFrame(Choreographer.java:635)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:874)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6381)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:829)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Meizu
Device: M6Note
Model: M6 Note
Id: N2G47H
Product: meizu_M6Note_CN

************ FIRMWARE ************
SDK: 25
Release: 7.1.2
Incremental: m1721.Flyme_7.0.1545878716

**Comment by rootbdfy** [comment]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineForOffset(int)' on a null object reference
	at android.widget.Editor.updateCursorPositionMz(Editor.java:7836)
	at android.widget.Editor.updateCursorsPositions(Editor.java:1963)
	at android.widget.TextView.getUpdatedHighlightPath(TextView.java:5783)
	at android.widget.TextView.onDraw(TextView.java:5969)
	at com.owncloud.android.ui.components.CustomEditText.onDraw(CustomEditText.java:71)
	at android.view.View.draw(View.java:17305)
	at android.view.View.updateDisplayListIfDirty(View.java:16282)
	at android.view.View.draw(View.java:17066)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.updateDisplayListIfDirty(View.java:16277)
	at android.view.View.draw(View.java:17066)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.draw(View.java:17308)
	at com.google.android.material.textfield.TextInputLayout.draw(TextInputLayout.java:1577)
	at android.view.View.updateDisplayListIfDirty(View.java:16282)
	at android.view.View.draw(View.java:17066)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.updateDisplayListIfDirty(View.java:16277)
	at android.view.View.draw(View.java:17066)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.updateDisplayListIfDirty(View.java:16277)
	at android.view.View.draw(View.java:17066)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.updateDisplayListIfDirty(View.java:16277)
	at android.view.View.draw(View.java:17066)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.draw(View.java:17308)
	at android.widget.ScrollView.draw(ScrollView.java:1743)
	at android.view.View.updateDisplayListIfDirty(View.java:16282)
	at android.view.View.draw(View.java:17066)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.updateDisplayListIfDirty(View.java:16277)
	at android.view.View.draw(View.java:17066)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.updateDisplayListIfDirty(View.java:16277)
	at android.view.View.draw(View.java:17066)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.updateDisplayListIfDirty(View.java:16277)
	at android.view.View.draw(View.java:17066)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.updateDisplayListIfDirty(View.java:16277)
	at android.view.View.draw(View.java:17066)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.draw(View.java:17308)
	at com.android.internal.policy.DecorView.draw(DecorView.java:786)
	at android.view.View.updateDisplayListIfDirty(View.java:16282)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:661)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:667)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:775)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2837)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2639)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2241)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1276)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6483)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:888)
	at android.view.Choreographer.doCallbacks(Choreographer.java:700)
	at android.view.Choreographer.doFrame(Choreographer.java:635)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:874)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6381)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:829)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Meizu
Device: M6Note
Model: M6 Note
Id: N2G47H
Product: meizu_M6Note_CN

************ FIRMWARE ************
SDK: 25
Release: 7.1.2
Incremental: m1721.Flyme_7.0.1545878716

**Comment by ambraspace** [comment]
Same here. Same device, except Incremental: m1721.Flyme_6.0.1510480068.

**Comment by tobiasKaminsky** [comment]
@ezaquarii I saw you created a test PR for fixing this.
Do you have an idea what is causing this?

**Comment by ezaquarii** [comment]
I think my fix was about the null canvas. This bug is about null layout.

Either way, there is something seriously wrong with view initialization as those things are happening in the platform code.

I'd take a look at our lifecycle, especially things related to showing the view or hiding. Maybe we have a wonky use case that triggers some platform bug?

**Comment by tobiasKaminsky** [comment]
@rootbdfy 
@ambraspace 
Is this happening after a fresh installation and you click on "log in"?

**Comment by tobiasKaminsky** [comment]
@ezaquarii if I remember correctly (also from other issues), this happens on certain device/Android versions directly on start up / first run.

**Comment by tobiasKaminsky** [comment]
Here and in #4585 only Meizu devices are affected.

**Comment by ambraspace** [comment]
> @rootbdfy
> @ambraspace
> Is this happening after a fresh installation and you click on "log in"?

Yes. Fresh install and click "Log in".

**Comment by tobiasKaminsky** [comment]
@ambraspace once continious integration system is done, there is a APK in #4626 , which you can install in parallel.
Can you test this?

**Comment by ambraspace** [comment]
> @ambraspace once continious integration system is done, there is a APK in #4626 , which you can install in parallel.
> Can you test this?

I will. For now, I confirm that 3.4.2 works fine.

**Comment by ambraspace** [comment]
> @ambraspace once continious integration system is done, there is a APK in #4626 , which you can install in parallel.
> Can you test this?

@tobiasKaminsky, I've just installed the APK in #4626 and when I click Log in, the app just closes. There's no error message.

**Comment by tobiasKaminsky** [comment]
@ambraspace I pushed a change so that there will be an exception handler.
Once the new apk is there, can you test it please?

**Comment by ambraspace** [comment]
> @ambraspace I pushed a change so that there will be an exception handler.
> Once the new apk is there, can you test it please?

@tobiasKaminsky, here's the error displayed:
`************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineForOffset(int)' on a null object reference
 at android.widget.Editor.updateCursorPositionMz(Editor.java:7578)
 at android.widget.Editor.updateCursorsPositions(Editor.java:1923)
 at android.widget.TextView.getUpdatedHighlightPath(TextView.java:5742)
 at android.widget.TextView.onDraw(TextView.java:5928)
 at android.view.View.draw(View.java:17293)
 at android.view.View.updateDisplayListIfDirty(View.java:16275)
 at android.view.View.draw(View.java:17059)
 at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
 at android.view.View.updateDisplayListIfDirty(View.java:16270)
 at android.view.View.draw(View.java:17059)
 at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
 at android.view.View.draw(View.java:17296)
 at com.google.android.material.textfield.TextInputLayout.draw(TextInputLayout.java:1577)
 at android.view.View.updateDisplayListIfDirty(View.java:16275)
 at android.view.View.draw(View.java:17059)
 at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
 at android.view.View.updateDisplayListIfDirty(View.java:16270)
 at android.view.View.draw(View.java:17059)
 at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
 at android.view.View.updateDisplayListIfDirty(View.java:16270)
 at android.view.View.draw(View.java:17059)
 at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
 at android.view.View.updateDisplayListIfDirty(View.java:16270)
 at android.view.View.draw(View.java:17059)
 at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
 at android.view.View.draw(View.java:17296)
 at android.widget.ScrollView.draw(ScrollView.java:1743)
 at android.view.View.updateDisplayListIfDirty(View.java:16275)
 at android.view.View.draw(View.java:17059)
 at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
 at android.view.View.updateDisplayListIfDirty(View.java:16270)
 at android.view.View.draw(View.java:17059)
 at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
 at android.view.View.updateDisplayListIfDirty(View.java:16270)
 at android.view.View.draw(View.java:17059)
 at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
 at android.view.View.updateDisplayListIfDirty(View.java:16270)
 at android.view.View.draw(View.java:17059)
 at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
 at android.view.View.updateDisplayListIfDirty(View.java:16270)
 at android.view.View.draw(View.java:17059)
 at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
 at android.view.View.draw(View.java:17296)
 at com.android.internal.policy.DecorView.draw(DecorView.java:777)
 at android.view.View.updateDisplayListIfDirty(View.java:16275)
 at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
 at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
 at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
 at android.view.ViewRootImpl.draw(ViewRootImpl.java:2826)
 at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2634)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2238)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1273)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6454)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
 at android.view.Choreographer.doCallbacks(Choreographer.java:686)
 at android.view.Choreographer.doFrame(Choreographer.java:621)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
 at android.os.Handler.handleCallback(Handler.java:751)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:154)
 at android.app.ActivityThread.main(ActivityThread.java:6285)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:829)

************ APP INFORMATION ************
ID: com.nextcloud.android.qa
Version: 11135
Build flavor: qa

************ DEVICE INFORMATION ************
Brand: Meizu
Device: M6Note
Model: M6 Note
Id: N2G47H
Product: meizu_M6Note

************ FIRMWARE ************
SDK: 25
Release: 7.1.2
Incremental: m1721.Flyme_6.0.1510480068`

**Comment by tobiasKaminsky** [comment]
Wow. This seems unrelated to CustomEditText…
