### ISSUE TITLE
Android Nextcloud

### ISSUE THREAD

**Issue by Oceania2301** [nextcloud/android#4620]
### Actual behaviour
Crash at start

### Expected behaviour
All should Run

### Environment data
Android version:

Device model: ZenFone 3

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Nextcloud log (data/nextcloud.log)
```************ CAUSE OF ERROR ************

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.owncloud.android.ui.adapter.ActivityListAdapter.getItemViewType(ActivityListAdapter.java:392)
	at com.owncloud.android.ui.adapter.ActivityListAdapter.isHeader(ActivityListAdapter.java:461)
	at com.owncloud.android.ui.adapter.ActivityListAdapter.getHeaderPositionForItem(ActivityListAdapter.java:438)
	at com.owncloud.android.ui.activities.StickyHeaderItemDecoration.getHeaderViewForItem(StickyHeaderItemDecoration.java:99)
	at com.owncloud.android.ui.activities.StickyHeaderItemDecoration.onDrawOver(StickyHeaderItemDecoration.java:55)
	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4223)
	at android.view.View.updateDisplayListIfDirty(View.java:18073)
	at android.view.View.draw(View.java:18851)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
	at android.view.View.draw(View.java:19126)
	at android.view.View.updateDisplayListIfDirty(View.java:18073)
	at android.view.View.draw(View.java:18851)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
	at android.view.View.updateDisplayListIfDirty(View.java:18064)
	at android.view.View.draw(View.java:18851)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
	at android.view.View.updateDisplayListIfDirty(View.java:18064)
	at android.view.View.draw(View.java:18851)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
	at android.view.View.draw(View.java:19126)
	at android.view.View.updateDisplayListIfDirty(View.java:18073)
	at android.view.View.draw(View.java:18851)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
	at android.view.View.updateDisplayListIfDirty(View.java:18064)
	at android.view.View.draw(View.java:18851)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
	at android.view.View.updateDisplayListIfDirty(View.java:18064)
	at android.view.View.draw(View.java:18851)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
	at android.view.View.updateDisplayListIfDirty(View.java:18064)
	at android.view.View.draw(View.java:18851)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
	at android.view.View.updateDisplayListIfDirty(View.java:18064)
	at android.view.View.draw(View.java:18851)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
	at android.view.View.draw(View.java:19126)
	at com.android.internal.policy.DecorView.draw(DecorView.java:785)
	at android.view.View.updateDisplayListIfDirty(View.java:18073)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:643)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:649)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:757)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3010)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2814)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2359)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1394)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6770)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
	at android.view.Choreographer.doCallbacks(Choreographer.java:778)
	at android.view.Choreographer.doFrame(Choreographer.java:713)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:169)
	at android.app.ActivityThread.main(ActivityThread.java:6578)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: asus
Device: ASUS_Z017D_1
Model: ASUS_Z017D
Id: OPR1.170623.026
Product: WW_Phone

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: 15.0410.1807.75-0

Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
What are the steps that lead to a crash?
Given the logcat it seems that you open "Activities"?

**Comment by ezaquarii** [comment]
The `ItemDecoration` is accessing `RecyclerView.Adapter`.

The problem with this approach is that `RecyclerView` items are animated. To support animations, recycler view data model has different lifecycle than adapter data model.

If we have a view in the layout, it does not mean that the corresponding item still exists in the adapter - it could be deleted, and `RecyclerView` item is still "animating out" of the screen.

We need to get rid of adapter references in the decoration code.

**Comment by ezaquarii** [comment]
@tobiasKaminsky This is fairly recent code - can we revert it?

**Comment by ezaquarii** [comment]
@tobiasKaminsky This header decoration is build on assumption that the adapter does not change and this assumption does not hold.

I see 2 options:

1. remove the sticky headers decoration (less fancy UI but less problems with maintenance)
2. don't do dynamic updates - rebuild world on data change, possibly delay decor init after data is available

I think activities are fairly static data so 2 can be satisfactory solution.

**Comment by tobiasKaminsky** [comment]
> I think activities are fairly static data so 2 can be satisfactory solution.

Activities are getting reloaded/appended once we reach the end of the list, which is approx after 60 entries.

Maybe an approach would be to have the entries grouped by date:
- group of activity per date 1
- group of activity per date 2
- group of activity per date 3

each then consists of
- sticky header
- multiple activities

With this we do not need to use adapter in the decoration, as it only works on one "view"?

**Comment by tobiasKaminsky** [comment]
Bug is fixed.
If we want to enhance this, then we can discuss it in a new issue.
