### ISSUE TITLE
I can't start the app - ERROR

### ISSUE THREAD

**Issue by tsmedienagentur** [nextcloud/android#4627]
### Actual behaviour
- When I'm starting the app I get an error.

That's the error I get:
 
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED flg=0x10 pkg=com.nextcloud.client (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver@44203d3
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1441)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=15342, uid=1110407 requires android.permission.BROADCAST_STICKY
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.app.IActivityManager$Stub$Proxy.unbroadcastIntent(IActivityManager.java:3861)
	at android.app.ContextImpl.removeStickyBroadcast(ContextImpl.java:1349)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
	at com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver.onReceive(FileDisplayActivity.java:1466)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1424)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.unbroadcastIntent(ActivityManagerService.java:24195)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:183)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3829)
	at android.os.Binder.execTransact(Binder.java:752)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus5
Model: ONEPLUS A5000
Product: OnePlus5

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 1907311824

**Comment by tobiasKaminsky** [comment]
Do you use a work profile?

**Comment by ezaquarii** [comment]
@tobiasKaminsky Would it be possible to get in touch with original developer to understand `unbroadcastIntent()` purpose? I'm tempted to just remove them, but I don't fully understand the risk of regression.

**Comment by tobiasKaminsky** [comment]
@ezaquarii this is invoked by 
https://github.com/nextcloud/android/blob/2dab887782afddce344cde5a31aa2114cd78b68e/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java#L1448

removeStickyBroadcast(…) is deprecated, but it should work as long as the app has 
https://github.com/nextcloud/android/blob/2dab887782afddce344cde5a31aa2114cd78b68e/src/main/AndroidManifest.xml#L63

We should, at some point, get rid of this and use a sender/listener system, but please no eventBus/third party system.
If we want to do this, let us first discuss the idea.

**Comment by tobiasKaminsky** [comment]
This is only happening to enterprise / MDM solution.
If this needs to be fixed, this can be done via our support.

**Comment by AndyScherzinger** [comment]
Duplicate of #6654
