### ISSUE TITLE
Android App crashes on Sync, when Folder was changed

### ISSUE THREAD

**Issue by arneschlag** [nextcloud/android#4628]
### Actual behaviour
Android APP crashes when synching with Server

### Expected behaviour
Changed Folder should resync

### Steps to reproduce
1. Create a Folder with some Files in it
2. Open the Android App and open and some files in this Folder and Subfolders 
3. Change something Outside the Android App in the Folder
4. Open App an go again in the Folder or resync it

### Environment data
Android version: 9
Device model: Oneplus A3003

Stock or customized system:
Customized System with /e/ based in Lineage OS

Nextcloud app version: 3.8.0
Nextcloud server version: 16.0.5
### Logs
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=3255, totalRows=53
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:895)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:157)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:128)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:237)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:269)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:183)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:127)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:177)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:127)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:177)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:127)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:177)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:127)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:177)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:127)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:107)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:299)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:661)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:320)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:474)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:1627)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:399)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:441)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:339)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:224)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:299)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus3T
Model: ONEPLUS A3003
Id: PQ3A.190801.002
Product: lineage_oneplus3

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: eng.root.20191006.214202

**Comment by computersalat** [comment]
same here, too

**Comment by computersalat** [comment]
lol ... automatic ignorance of issues

**Comment by didierm** [comment]
Android client crashes daily a few times with the above reported error  :
```
android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow
...
at
android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:334)
```


Version: 30090290

**Comment by didierm** [comment]
```
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=6870, totalRows=5010
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:895)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:157)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:128)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:237)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:269)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:128)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:178)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:128)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:178)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:128)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:108)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:299)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:662)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:320)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:474)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:411)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:445)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:339)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:224)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:138)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:268)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.onPerformSync(FileSyncAdapter.java:180)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:334)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: ***
Device: ***
Model: ***
Id: ***
Product: ***

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: eng.append.20191021.233716
```

**Comment by conter86** [comment]
Тоже самая проблема

**Comment by conter86** [comment]
> Тоже самая проблема
> есть решение?


************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=3123, totalRows=373
at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:859)
at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:159)
at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:128)
at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:237)
at android.database.AbstractCursor.moveToNext(AbstractCursor.java:275)
at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:190)
at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:299)
at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:670)
at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:319)
at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:474)
at android.content.ContentResolver.applyBatch(ContentResolver.java:1642)
at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:407)
at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:478)
at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:369)
at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:228)
at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:357)
at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: xiaomi
Device: whyred
Model: Redmi Note 5
Id: PKQ1.180904.001
Product: whyred

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: V11.0.3.0.PEIMIXM
