### ISSUE TITLE
App crashes on login

### ISSUE THREAD

**Issue by Tkopic001** [nextcloud/android#4660]
### Actual behaviour
Keeps crashing afer I logged in on my Nextcloud server. Worked fine before I updated the server from 16 to 17.

Note:
Dev version also crashes

### Expected behaviour
I hoped it would not crash
 
### Steps to reproduce
1.  Install android app
2.  Login into your account
3. Wait for 1-2 sec

### Environment data
Android version:
9
Device model: 
Xiaomi Redmi 7
Stock or customized system:
Stock
Nextcloud app version:
3.8.0
Nextcloud server version:
Stable17

#### Web server error log
```
There was nothing in the logs
```

#### Nextcloud log (data/nextcloud.log)
```
Nothing of relevance here either
```

App crash report
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.substring(int, int)' on a null object reference
	at com.owncloud.android.datamodel.OCFile.getLocalId(OCFile.java:493)
	at com.owncloud.android.utils.EncryptionUtils.downloadFolderMetadata(EncryptionUtils.java:221)
	at com.owncloud.android.operations.RefreshFolderOperation.getDecryptedFolderMetadata(RefreshFolderOperation.java:450)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:395)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:339)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:224)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:299)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: xiaomi
Device: onc
Model: Redmi 7
Id: PKQ1.181021.001
Product: onc_eea

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: V10.3.4.0.PFLEUXM
```

**Comment by tobiasKaminsky** [comment]
Do you use E2E?

**Comment by Tkopic001** [comment]
Hello,

Sorry i didn't write a more comprehensive report i was in a hurry.
After I upgraded nextcloud the android app started complaining about E2E not being installed on the server.
So i installed E2E and it fixed the problem on my phone, but then the webUI stopped working with the "permission denied" error in the files app, i couldn't find a fix for this other than removing the E2E  plugin. After i removed it webUI was fixed but the android app was still not working.
I uninstalled the android app on my phone, cleared all the data and installed the app again. 
I logged in via the QR code, it didn't ask for E2E plugin and it seems i can access my files. But now it's crashing constantly.

Thank you!
Kind regards,

**Comment by Tkopic001** [comment]
Any solution for this problem?
I've tried deleting every trace of nextcloud from the phone and reinstall everything again but it still keeps crashing

**Comment by Bladou46** [comment]
Hello ! 

I have the same issue but I'm not using E2E. Here is my error stack trace: 
```
**** CAUSE OF ERROR ****

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.substring(int, int)' on a null object reference
    at com.owncloud.android.datamodel.OCFile.getLocalId(OCFile.java:493)
    at com.owncloud.android.utils.EncryptionUtils.downloadFolderMetadata(EncryptionUtils.java:221)
    at com.owncloud.android.operations.RefreshFolderOperation.getDecryptedFolderMetadata(RefreshFolderOperation.java:454)
    at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:395)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:339)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:224)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:299)
    at java.lang.Thread.run(Thread.java:764)

**** APP INFORMATION ****
ID: com.nextcloud.client
Version: 30090090
Build flavor: generic

**** DEVICE INFORMATION ****
Brand: OnePlus
Device: OnePlus6T
Model: ONEPLUS A6013
Id: PKQ1.180716.001
Product: OnePlus6T

**** FIRMWARE ****
SDK: 28
Release: 9
Incremental: 1909112330
```

I did have files encryption enabled before (no e2e) but this is not the case anymore. I decrypted my files and it is working fine on webUI, desktop sync client and so on. The only one not working is the Android app.
