### ISSUE TITLE
Android for Work COPE - App crash Android 9.0

### ISSUE THREAD

**Issue by vondue83** [nextcloud/android#4661]
Problem exists only in Android 9.0 devices

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED flg=0x10 pkg=com.nextcloud.client (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver@f554343
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1410)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:220)
	at android.app.ActivityThread.main(ActivityThread.java:6929)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=14713, uid=1010185 requires android.permission.BROADCAST_STICKY
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.app.IActivityManager$Stub$Proxy.unbroadcastIntent(IActivityManager.java:3853)
	at android.app.ContextImpl.removeStickyBroadcast(ContextImpl.java:1349)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
	at com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver.onReceive(FileDisplayActivity.java:1466)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1400)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.unbroadcastIntent(ActivityManagerService.java:22718)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:184)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3563)
	at android.os.Binder.execTransact(Binder.java:746)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080152
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: motorola
Device: kane_sprout
Model: motorola one vision
Id: PSA29.160-50
Product: kane_reteu

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 46393d

**Comment by tobiasKaminsky** [comment]
> Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=14713, uid=1010185 requires android.permission.BROADCAST_STICKY

This is known, for work profiles.
Can you create me a test account for such a work account and send it to tobias at nextcloud dot com?

**Comment by mario** [comment]
It's a work account on Android. How would he do that?

**Comment by tobiasKaminsky** [comment]
To clarifiy, I mean a test account on your MDM you are using (e.g. gsuite).

**Comment by rumbleball80** [comment]
@mario: you can use the workaround from #4205. Install the nextcloud app in main profile

@tobiasKaminsky: you can use the "island"-app to create your own local work profile without any MDM account
https://play.google.com/store/apps/details?id=com.oasisfeng.island

**Comment by vondue83** [comment]
> > Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=14713, uid=1010185 requires android.permission.BROADCAST_STICKY
> 
> This is known, for work profiles.
> Can you create me a test account for such a work account and send it to tobias at nextcloud dot com?

Hello,

ve send you check in details last friday from daniel.vonwald@noel.gv.at

**Comment by vondue83** [comment]
> @vondue83: you can use the workaround from #4205. Install the nextcloud app in main profile
> 
> @tobiasKaminsky: you can use the "island"-app to create your own local work profile without any MDM account
> https://play.google.com/store/apps/details?id=com.oasisfeng.island

i know the workaround - installing nextcloud in main Profile

**Comment by tobiasKaminsky** [comment]
I tested it with Island and Emulator 10, but it works there :thinking: 
Trying your MDM system with emulator 10 does not work yet.
I try it now with a real device, but it is only Android 6.

**Comment by tobiasKaminsky** [comment]
I forgot to post the resolution.
Indeed this is a bug we need to fix, but currently there is no ETA.
If you are a customer and interested in fixing it, please address your account manager.

**Comment by AndyScherzinger** [comment]
Duplicate of #6654
