### ISSUE TITLE
Crash on opening conflicting markdown file

### ISSUE THREAD

**Issue by LeSpocky** [nextcloud/android#4662]
### Actual behaviour
- edited a file `tmr.md` from my notes folder with the markor app
- on opening in nextcloud app afterwards nextcloud app briefly showed conflict dialog, then crashed

### Expected behaviour
- no crash?
 
### Steps to reproduce
1. see above

### Environment data
Android version: 6

Device model: P024

Stock or customized system: stock

Nextcloud app version: unsure

Nextcloud server version: 16

### Logs
This is from the app crash report:

```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.widget.SearchView.setOnQueryTextListener(androidx.appcompat.widget.SearchView$OnQueryTextListener)' on a null object reference
	at com.owncloud.android.ui.preview.PreviewTextFragment$TextLoadAsyncTask.onPostExecute(PreviewTextFragment.java:326)
	at com.owncloud.android.ui.preview.PreviewTextFragment$TextLoadAsyncTask.onPostExecute(PreviewTextFragment.java:259)
	at android.os.AsyncTask.finish(AsyncTask.java:651)
	at android.os.AsyncTask.access$500(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5484)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: asus
Device: P024_1
Model: P024
Id: MMB29M
Product: WW_P024

************ FIRMWARE ************
SDK: 23
Release: 6.0.1
Incremental: WW_P024-V5.9.4-20170613
```

**Comment by LeSpocky** [comment]
Maybe because file was still open in Markor?

**Comment by LeSpocky** [comment]
App was installed Form F-Droid.
