### ISSUE TITLE
crash single sign on with news

### ISSUE THREAD

**Issue by neelusR** [nextcloud/android#4667]
### Actual behaviour
I try to use single sign in for the android News app. 
When i select my account and press ok it crashes.
Using an unofficial build of AospExtended.

### Expected behaviour
- Tell us what should happen
 
### Steps to reproduce
1. 
2. 

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.SsoGrantPermissionActivity}: java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.accounts.Account.name' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.accounts.Account.name' on a null object reference
	at com.owncloud.android.ui.activity.SsoGrantPermissionActivity.onCreate(SsoGrantPermissionActivity.java:108)
	at android.app.Activity.performCreate(Activity.java)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
	... 11 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWY360-U
Model: HUAWEI Y360-U23
Id: NJH47F
Product: Y360-U23

************ FIRMWARE ************
SDK: 25
Release: 7.1.2
Incremental: eng.root.20180105.092900

3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by Yetangitu** [comment]
I just got hit by this, the bug is alive and kicking. Most recent versions of both NC app as well as NC News off Fdroid, same signs, same error. Running Lineage 14.1 on a Samsung GT-P5210.

**Comment by tobiasKaminsky** [comment]
With which method do you install packages via Fdroid? Root, priviled extension / manual?

**Comment by tobiasKaminsky** [comment]
Background: I guess that somehow one of the apps is not allowed to access the others app account and thus it fails.

**Comment by Yetangitu** [comment]
> With which method do you install packages via Fdroid? Root, priviled extension / manual?

Manual

**Comment by neelusR** [comment]
It still happens only on this phone. I suppose it  has something to do with the custom ROM. If there is anything I can add, please let me know.
