### ISSUE TITLE
Nextcloud app died with stack trace after freeze during some work around sharing

### ISSUE THREAD

**Issue by JensErat** [nextcloud/android#4672]
I received a stack trace, multiple hours(?) after doing some work around shares where Nextcloud once froze and Android ask me whether I want to kill it (I didn't want to).

```
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{3ba35fe u0 com.nextcloud.client/com.owncloud.android.services.OperationsService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1905)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6912)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: motorola
Device: payton
Model: moto x4
Id: PPWS29.69-37-5
Product: payton

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 63ca8
```

### Actual behaviour

Nextcloud froze and then died with a stack trace.

### Expected behaviour

Don't freeze and die :)
 
### Steps to reproduce

Could not reproduce -- does the stack trace contain sufficient information? If not, please close the issue -- if I get the error again I'll try to reproduce properly.

### Environment data
Android version: 9

Device model: Motorola Moto X4

Stock or customized system: stock

Nextcloud app version: 3.8.1

Nextcloud server version: 16.3

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by JensErat** [comment]
Somehow I messed up my first try on searching for similar issues, might be related to #2010

**Comment by AndyScherzinger** [comment]
Yes, a duplicate of #2010, so closing it in favor.
