### ISSUE TITLE
App crash - v3.8.1

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#4680]
Application crashes while running in the caching process:

```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.android.server.job.controllers.JobStatus.getUid()' on a null object reference
	at android.app.job.JobService$JobHandler.handleMessage(JobService.java:130)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5530)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:734)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.android.server.job.controllers.JobStatus.getUid()' on a null object reference
	at android.os.Parcel.readException(Parcel.java:1605)
	at android.os.Parcel.readException(Parcel.java:1552)
	at android.app.job.IJobCallback$Stub$Proxy.acknowledgeStartMessage(IJobCallback.java:122)
	at android.app.job.JobService$JobHandler.ackStartMessage(JobService.java:167)
	at android.app.job.JobService$JobHandler.handleMessage(JobService.java:127)
	... 6 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080190
Build flavor: gplay

```
### Environment data
Android version: 6

Nextcloud app version: 3.8.1

Nextcloud server version: 17.0.0

**Comment by tobiasKaminsky** [comment]
No idea what to do here :/
This seems to be from Android's job handler…

**Comment by AndyScherzinger** [comment]
let's close it then, Sorry @Valdnet :/
