### ISSUE TITLE
Cannot download images on Android client

### ISSUE THREAD

**Issue by kanchannmahajan** [nextcloud/android#4723]
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Fragment PreviewImageFragment{7e93ced} not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:696)
	at androidx.fragment.app.Fragment.getResources(Fragment.java:760)
	at com.owncloud.android.ui.preview.PreviewImageFragment.lambda$setErrorPreviewMessage$2$PreviewImageFragment(PreviewImageFragment.java:706)
	at com.owncloud.android.ui.preview.-$$Lambda$PreviewImageFragment$kydRNo-kMJ0Oklsv9f_06NSEUic.onClick(Unknown Source:2)
	at com.google.android.material.snackbar.Snackbar$1.onClick(Snackbar.java:317)
	at android.view.View.performClick(View.java:6669)
	at android.view.View.performClickInternal(View.java:6638)
	at android.view.View.access$3100(View.java:789)
	at android.view.View$PerformClick.run(View.java:26145)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6863)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus3
Model: ONEPLUS A3003
Id: PKQ1.181203.001
Product: OnePlus3

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 1907311932

**Comment by tobiasKaminsky** [comment]
What are the steps that lead to this crash?
