### ISSUE TITLE
crash when trying to switch sorting while moving a file

### ISSUE THREAD

**Issue by violoncelloCH** [nextcloud/android#4732]
### Actual behaviour
- app crashes displaying an error log

### Expected behaviour
- I should be able to change sorting of files in a folder while moving a file
 
### Steps to reproduce
1. move a file
2. go to an other directory where you have a large amount of folders where you want the alphabetical last folder
3. select sorting from the menu and click on Z-A
4. see the app crashing

### Environment data
Android version: 9

Device model: HTC U12+

Stock or customized system: stock

Nextcloud app version: 3.8.1

Nextcloud server version: 16.0.5

#### Crash log
```
************ CAUSE OF ERROR ************

java.lang.ClassCastException: com.owncloud.android.ui.activity.FolderPickerActivity cannot be cast to com.owncloud.android.ui.dialog.SortingOrderDialogFragment$OnSortingOrderListener
	at com.owncloud.android.ui.dialog.SortingOrderDialogFragment$OnSortOrderClickListener.onClick(SortingOrderDialogFragment.java:180)
	at android.view.View.performClick(View.java:6600)
	at android.view.View.performClickInternal(View.java:6577)
	at android.view.View.access$3100(View.java:781)
	at android.view.View$PerformClick.run(View.java:25966)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:210)
	at android.app.ActivityThread.main(ActivityThread.java:7124)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:898)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: htc
Device: htc_imeuhl
Model: HTC U12+
Id: PQ2A.190205.003
Product: imeuhl_00401

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 1088647.1
```

**Comment by violoncelloCH** [comment]
No, that shouldn't be closed... It's what we talked about at the Hackweek @tobiasKaminsiky

**Comment by tobiasKaminsky** [comment]
This seems to be fixed.
If not, please re-open.

**Comment by violoncelloCH** [comment]
verified - seems fixed, thanks!
