### ISSUE TITLE
Crash when opening a large test file

### ISSUE THREAD

**Issue by bapjg** [nextcloud/android#4736]
### Actual behaviour
- Tell us what happens

### Expected behaviour
- Tell us what should happen
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate
************ CAUSE OF ERROR ************

java.lang.OutOfMemoryError: Failed to allocate a 14671912 byte allocation with 10686488 free bytes and 10MB until OOM, max allowed footprint 402653184, growth limit 402653184
	at dalvik.system.VMRuntime.newUnpaddedArray(Native Method)
	at com.android.internal.util.ArrayUtils.newUnpaddedIntArray(ArrayUtils.java:55)
	at android.text.StaticLayout.out(StaticLayout.java:968)
	at android.text.StaticLayout.generate(StaticLayout.java:883)
	at android.text.DynamicLayout.reflow(DynamicLayout.java:614)
	at android.text.DynamicLayout.generate(DynamicLayout.java:482)
	at android.text.DynamicLayout.<init>(DynamicLayout.java:401)
	at android.text.DynamicLayout.<init>(DynamicLayout.java:49)
	at android.text.DynamicLayout$Builder.build(DynamicLayout.java:283)
	at android.widget.TextView.makeSingleLayout(TextView.java:8625)
	at android.widget.TextView.makeNewLayout(TextView.java:8500)
	at android.widget.TextView.onMeasure(TextView.java:8882)
	at androidx.appcompat.widget.AppCompatTextView.onMeasure(AppCompatTextView.java:501)
	at android.view.View.measure(View.java:23466)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
	at android.view.View.measure(View.java:23466)
	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1351)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.widget.ScrollView.onMeasure(ScrollView.java:368)
	at android.view.View.measure(View.java:23466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23466)
	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1396)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:728)
	at android.view.View.measure(View.java:23466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1565)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
	at android.view.View.measure(View.java:23466)
	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
	at android.view.View.measure(View.java:23466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
	at android.view.View.measure(View.java:23466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1565)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
	at android.view.View.measure(View.java:23466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:847)
	at android.view.View.measure(View.java:23466)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2954)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1753)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2041)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1636)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
	at android.view.Choreographer.doCallbacks(Choreographer.java:893)
	at android.view.Choreographer.doFrame(Choreographer.java:812)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HONOR
Device: HWBKL
Model: BKL-L09
Id: HUAWEIBKL-L09S
Product: BKL-L09

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 329C432

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @bapjg not sure how to stop a Out of Memory scenario...

**Comment by Cyber1000** [comment]
I have the same issue with a not so big picture (perhaps some MB big), but only on one device. My bug has exactly the same stacktrace as in #4704. Not quite sure, if we can combine the tasks.

To solve the problem:
- Android isn't my profession right now and on a fast search I found only some rather old stackoverflow Q&A like this: https://stackoverflow.com/questions/25719620/how-to-solve-java-lang-outofmemoryerror-trouble-in-android
- Leading also to an android site: https://developer.android.com/topic/performance/memory.html
-- At least you should be able to call  getMemoryInfo() beforehand to avoid a crash
