### ISSUE TITLE
urgent security risk -> learn more button -> crash

### ISSUE THREAD

**Issue by Kwaadpepper** [nextcloud/android#4745]
### Actual behaviour
Crash when click on learn more button about security notification inside app

### Expected behaviour
Should open Web link in external browser I guess
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version: 10

Device model:  xiaomi mi9t

Stock or customized system: xiaomi.eu

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Cannot execute task: the task has already been executed (a task can be executed only once)
	at android.os.AsyncTask.executeOnExecutor(Unknown Source:24)
	at android.os.AsyncTask.execute(Unknown Source:2)
	at com.owncloud.android.ui.adapter.NotificationListAdapter.lambda$onBindViewHolder$2$NotificationListAdapter(NotificationListAdapter.java:182)
	at com.owncloud.android.ui.adapter.-$$Lambda$NotificationListAdapter$TXM0JwRxGeq8tl4SIWzikYjFQ-k.onClick(Unknown Source:8)
	at android.view.View.performClick(Unknown Source:17)
	at android.view.View.performClickInternal(Unknown Source:3)
	at android.view.View.access$3100(Unknown Source:0)
	at android.view.View$PerformClick.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:207)
	at android.app.ActivityThread.main(Unknown Source:107)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:274)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: davinci
Model: Redmi K20
Id: PKQ1.190302.001
Product: davinci

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: V11.0.3.0.PFJCNXM

```

**Comment by tobiasKaminsky** [comment]
This is fixed via https://github.com/nextcloud/android/pull/4730 and will be in upcoming 3.9.0.
