### ISSUE TITLE
Crashed while trying to make a *.vcf file with app

### ISSUE THREAD

**Issue by WNYmathGuy** [nextcloud/android#4769]
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Fragment ChooseTemplateDialogFragment{3c761d7} not attached to Activity
	at androidx.fragment.app.Fragment.startActivity(Fragment.java:1082)
	at androidx.fragment.app.Fragment.startActivity(Fragment.java:1073)
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment$CreateFileFromTemplateTask.onPostExecute(ChooseTemplateDialogFragment.java:250)
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment$CreateFileFromTemplateTask.onPostExecute(ChooseTemplateDialogFragment.java:212)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.-wrap1(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: angler
Model: Nexus 6P
Id: OPM7.181105.004
Product: angler

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: 5038062

**Comment by WNYmathGuy** [comment]
I've never tried to make another one yet.
