### ISSUE TITLE
Client 20161224 crashes

### ISSUE THREAD

**Issue by jgrete** [nextcloud/android#477]
### Actual behaviour
Client  crashes every  now and then

### Expected behaviour
-no crashes of course 
 
### Steps to reproduce
1.  Don't know, mostly while listing directories (fast scrolling larger directories ) 
2. 
3. 

### Environment data
Android version:

Device model: 
Samsung klte
Stock or customized system:
Cm 13
Nextcloud app version:
Beta 20161224
Nextcloud server version:
11
### Logs
************ CAUSE OF ERROR ************

java.lang.IllegalArgumentException: Empty values
	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1542)
	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1522)
	at com.owncloud.android.providers.FileContentProvider.updateFilesTableAccordingToShareInsertion(FileContentProvider.java:349)
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:283)
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:227)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:302)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:549)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:315)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:419)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:1275)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveSharesInFolder(FileDataStorageManager.java:1484)
	at com.owncloud.android.operations.RefreshFolderOperation.refreshSharesForFolder(RefreshFolderOperation.java:504)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:216)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:303)
	at java.lang.Thread.run(Thread.java:818)

************ DEVICE INFORMATION ***********
Brand: samsung
Device: klte
Model: SM-G900F
Id: M4B30X
Product: cm_klte

************ FIRMWARE ************
SDK: 23
Release: 6.0.1
Incremental: d0edb3bba9

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by eppfel** [comment]
I guess this is the same error as #425. Follow that one for updates.

**Comment by AndyScherzinger** [comment]
fixed via #492 and for the beta will be included in the build 20161231
