### ISSUE TITLE
Json error

### ISSUE THREAD

**Issue by ohari5336** [nextcloud/android#4780]
************ CAUSE OF ERROR ************

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson.JsonParser.parseReader(JsonParser.java:66)
	at com.google.gson.JsonParser.parseString(JsonParser.java:47)
	at com.google.gson.JsonParser.parse(JsonParser.java:98)
	at com.owncloud.android.lib.resources.activities.GetActivitiesRemoteOperation.parseResult(GetActivitiesRemoteOperation.java:184)
	at com.owncloud.android.lib.resources.activities.GetActivitiesRemoteOperation.run(GetActivitiesRemoteOperation.java:150)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:138)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$fetchAndSetData$5$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:335)
	at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$vs5MPES-idduo_KrobEk_5dc5lk.run(lambda)
	at java.lang.Thread.run(Thread.java:818)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1564)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1405)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:543)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:426)
	at com.google.gson.JsonParser.parseReader(JsonParser.java:61)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Panasonic
Device: T45_4G
Model: Panasonic T45 4G
Id: LMY47D
Product: T45_4G

************ FIRMWARE ************
SDK: 22
Release: 5.1
Incremental: 1437210888

**Comment by tobiasKaminsky** [comment]
Can you have a look at web ui and see what kind of activities you see there?

**Comment by ohari5336** [comment]
when I play video and see video details then I got this error

**Comment by tobiasKaminsky** [comment]
This is due to the activity list of this file has some content that our app is not capable to parse.

Please open the specific file in web browser and post a screenshot of those changes that you can see in activity tab.

**Comment by AndyScherzinger** [comment]
This got reported twice on the dev console while (of course) we can't see the json data, my guess some app (or server itself) break the json data format :/

**Comment by tobiasKaminsky** [comment]
Yes, last time we had this, it was because of "you changed your email address", but this is resolved (and would not be shown on a file)

**Comment by AndyScherzinger** [comment]
Yes, I know. My point was rather to discuss how we can harden this part (and still inform about an error) since the server doesn't bulletproof this for us so we need to do it on our side (and still provide feedback to server/app devs).

**Comment by ohari5336** [comment]
I am also a web and android app developer, according to me application got blank JSON from the server and application got null in JSONobject then try-catch  maybe not work

**Comment by AndyScherzinger** [comment]
>  according to me application got blank JSON from the server

Stacktrace says: `malformed JSON at line 1 column 12`
So JSON likely isn't empty

@ohari5336 could you debug into
`com.owncloud.android.lib.resources.activities.GetActivitiesRemoteOperation.parseResult(GetActivitiesRemoteOperation.java:184` ?

**Comment by ohari5336** [comment]
I see this error the only first time when I login in the app and now I try much time but I didn't get this again, so maybe now useless debug this activity and when I logout and re-login then I see new error this:

************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:743)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1606)
	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1552)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:644)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:618)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:251)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:661)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:299)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:406)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:1293)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:405)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:445)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:339)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:224)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:299)
	at java.lang.Thread.run(Thread.java:818)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Panasonic
Device: T45_4G
Model: Panasonic T45 4G
Id: LMY47D
Product: T45_4G

************ FIRMWARE ************
SDK: 22
Release: 5.1
Incremental: 1437210888

**Comment by ohari5336** [comment]
I think to install the app from android studio build then I got more info about errors

**Comment by ohari5336** [comment]
Now after re-login when I open the app every time I got json parse error

**Comment by AndyScherzinger** [comment]
> Now after re-login when I open the app every time I got json parse error

can you debug and find out what the response body contains you get back from the server?

**Comment by AndyScherzinger** [comment]
Any news @ohari5336?

**Comment by ohari5336** [comment]
currently, I change my hosting so I delete full installation when I re-setup then I create the app with source code then if any error then I debug it and post it

**Comment by tobiasKaminsky** [comment]
:+1: Then I close this for now, but feel free to re-open it.
