### ISSUE TITLE
App crashes every time I try to create a new folder

### ISSUE THREAD

**Issue by levster69** [nextcloud/android#4792]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
	at com.owncloud.android.ui.dialog.CreateFolderDialogFragment.onClick(CreateFolderDialogFragment.java:139)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6986)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: star2qlteue
Model: SM-G965U1
Id: PPR1.180610.011
Product: star2qlteue

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G965U1UEU7CSJ3

**Comment by Javad-Aboutorabi** [comment]
I also have this problem in this function
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
at
com.owncloud.android.utils.FileStorageUtils.checkEncryption.nStatus(FileStorageUtils.java440)...

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky seems to happen on several occasions.

**Comment by cweiske** [comment]
Happened today with while setting up instant upload folder, with the same stacktrace as in the description:

```
************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: acer
Device: acer_T02
Model: T02
Id: LMY47D
Product: T02_ww

************ FIRMWARE ************
SDK: 22
Release: 5.1
Incremental: 1464248381
```

**Comment by MichaelTiernan** [comment]
I originally posted this as part of #5081 by error (my own, sorry)

I'll go back and collect more specific details to add.
---

Reproduced easily for me... on two diff devices.

1. Select _Auto upload_
1. Select _Set up a custom folder_
1. Select _Remote folder_
1. Select _New folder_
1. Enter any name press _Create_

***BOOM***

---

~~~
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
	at com.owncloud.android.ui.dialog.CreateFolderDialogFragment.onClick(CreateFolderDialogFragment.java:139)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: manta
Model: Nexus 10
Id: LMY49J
Product: mantaray

************ FIRMWARE ************
SDK: 22
Release: 5.1.1
Incremental: 2640980
~~~

---

~~~
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
	at com.owncloud.android.ui.dialog.CreateFolderDialogFragment.onClick(CreateFolderDialogFragment.java:139)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7073)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: dream2qltesq
Model: SM-G955U
Id: PPR1.180610.011
Product: dream2qltesq

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G955USQU7DSL3

~~~

**Comment by MichaelTiernan** [comment]
A more careful trial...
---
Create folder from android tablet at top level<br>**Works fine**

Scenario #1:

1. Choose "Auto upload"
1. Picked 'screenshots'
1. Enabled preferences for autouploading
1. Choose "Remote Folder"<br>Presented with top level view.
1. Choose "New Folder"
1. Enter anything and select "Create"
	
***Boom***

Senario #2:

1. Choose "Auto upload"
1. Picked 'screenshots'
1. Enabled preferences for autouploading
1. Choose "Remote Folder"<br>Presented with top level view.
1. ***Choose existing sub folder***
1. Choose "New Folder"
1. Enter anything and select "Create"
	
***Works***

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky since reports are pilling up

**Comment by Shagequi** [comment]
@AndyScherzinger @tobiasKaminsky 
Good morning,
This bug happens only in the "root" because `mFile` is empty in FileActivity when we're in the root (`/`) folder.
I'm working on a fix

**Comment by AndyScherzinger** [comment]
> This bug happens only in the "root" because mFile is empty in FileActivity when we're in the root (/) folder.

true, yes! 👍

**Comment by Shagequi** [comment]
@AndyScherzinger It has been fixed and tested on my own ("par mes soins" in french 🇫🇷 😄 ) in : https://github.com/nextcloud/android/pull/5465

I let you watch the PR

Have a nice day
