### ISSUE TITLE
Selecting SSO login account crashes

### ISSUE THREAD

**Issue by mope1** [nextcloud/android#4812]
### Actual behaviour
- I tap the account name for sso login

### Expected behaviour
- Ask permissions
- SSO
 
### ~~Steps to reproduce~~

See details below.

TLDR this is an older samsung device but with current playstore `nextcloud` and `DAVx5`. The bug is minor since I can use the other auth method but still, as this a paid app i'd expect this to be caught and a message to be displayed at least :-)

```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.SsoGrantPermissionActivity}: java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.accounts.Account.name' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
	at android.app.ActivityThread.-wrap14(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6776)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.accounts.Account.name' on a null object reference
	at com.owncloud.android.ui.activity.SsoGrantPermissionActivity.onCreate(SsoGrantPermissionActivity.java:108)
	at android.app.Activity.performCreate(Activity.java:6955)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
	... 9 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a5xelte
Model: SM-A510F
Id: NRD90M
Product: a5xeltexx

************ FIRMWARE ************
SDK: 24
Release: 7.0
Incremental: A510FXXS8CSF3```

**Comment by AndyScherzinger** [comment]
> as this a paid app i'd expect this to be caught and a message to be displayed at least :-)

Just to be clear here, `Nextcloud` is free while `Davx5` is paid and _not_ provided by Nextcloud project buut a thrid party, see https://gitlab.com/bitfireAT/davx5-ose

Your error is lying within the SSO library though which _is_ provided by the Nextcloud project, so pinging @tobiasKaminsky and @David-Development about this issue.

**Comment by David-Development** [comment]
@mope1 Thanks for the report! Indeed, a crash like this should be handled properly.

@tobiasKaminsky Reference: https://github.com/nextcloud/android/blob/946e5c2c1e8e72777ad0382d82fa84df875c706c/src/main/java/com/owncloud/android/ui/activity/SsoGrantPermissionActivity.java#L106

Looks like that the account was not bundled in the intent..?

Not sure if the problem is on the third party apps side (davx5). However if they use our method (see link below) the account should be included.. only thing I can think of is some weird Android Authenticator issues.. :/ 

https://github.com/nextcloud/Android-SingleSignOn/blob/6f46c6461f1c9d7c30f11b3be78fabe9fbfcbb20/src/main/java/com/nextcloud/android/sso/AccountImporter.java#L379

**Comment by AndyScherzinger** [comment]
@mope1 are you using a plain Android profile or do you try to use the app within a so called work profile (which as of now isn't supported)?

**Comment by mope1** [comment]
I do not use the app within work profile **but** I am embarassed to report I actually have a work profile set up on my device (which I forgot about) and is probably messing things up, sorry!

**Comment by mope1** [comment]
oh damn, i just realized this is the wrong repo for this bug report!
