### ISSUE TITLE
App crashes when resizing image

### ISSUE THREAD

**Issue by eduluz1976** [nextcloud/android#4818]
### Actual behaviour
- App just crashed when resizing image

### Expected behaviour
- expected image resized, as suggested by app message
 
### Steps to reproduce
1. Open an image in mobile app (Android)
2. When appears a message suggesting resize the image to view better, the app just crashes

### Environment data
Android version:

Device model: 
LG G6

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Fragment PreviewImageFragment{7d2edbf} not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:696)
	at androidx.fragment.app.Fragment.getResources(Fragment.java:760)
	at com.owncloud.android.ui.preview.PreviewImageFragment.lambda$setErrorPreviewMessage$2$PreviewImageFragment(PreviewImageFragment.java:706)
	at com.owncloud.android.ui.preview.-$$Lambda$PreviewImageFragment$kydRNo-kMJ0Oklsv9f_06NSEUic.onClick(Unknown Source:2)
	at com.google.android.material.snackbar.Snackbar$1.onClick(Snackbar.java:317)
	at android.view.View.performClick(View.java:6615)
	at android.view.View.performClickInternal(View.java:6587)
	at android.view.View.access$3500(View.java:784)
	at android.view.View$PerformClick.run(View.java:26048)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:205)
	at android.app.ActivityThread.main(ActivityThread.java:6991)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: lge
Device: lucye
Model: LG-H873
Id: PKQ1.190522.001
Product: lucye_global_ca

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 192602009a6ae


```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@eduluz1976 does this also happen with 3.9.0 (released yesterday)?
