### ISSUE TITLE
Crash for email-shared folders/files

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#483]
This came in via the Google Play review:

> The app provides some, but the sharing of folders or files with external (ie an email address instead of LDAP) unfortunately leads reliably the app to crash. Once you delete the items in question, the app works perfectly again. Please fix. I have found in the app also no way to know from whom I got assigned to a file. Otherwise, keep it up!

Device
    Galaxy S7 (herolte)

App version
    10040099 (1.4.0)

OS
    Android 6.0

**Comment by Sanookmakmak** [comment]
In my case it was not necessary to delete the shared file. I just removed the share of the file and the app worked fine again.

App version 1.4.0
Android 5.0

![3b6d7aa3cfd34197ec576b684fc30b65ba1ea6e3](https://cloud.githubusercontent.com/assets/24833757/21566878/a8fcddfa-cea7-11e6-9e60-039a60333e43.png)

**Comment by AndyScherzinger** [comment]
With sharing a file via email I could reproduce the error:
```
12-30 16:18:39.982 2740-25031/com.nextcloud.client E/AndroidRuntime: FATAL EXCEPTION: Thread-6
 Process: com.nextcloud.client, PID: 2740
 java.lang.IllegalArgumentException: Empty values
     at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1545)
     at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1525)
     at com.owncloud.android.providers.FileContentProvider.updateFilesTableAccordingToShareInsertion(FileContentProvider.java:349)
     at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:283)
     at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:227)
     at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:302)
     at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:549)
     at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:316)
     at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:438)
     at android.content.ContentResolver.applyBatch(ContentResolver.java:1315)
     at com.owncloud.android.datamodel.FileDataStorageManager.saveSharesInFolder(FileDataStorageManager.java:1484)
     at com.owncloud.android.operations.RefreshFolderOperation.refreshSharesForFolder(RefreshFolderOperation.java:504)
     at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:216)
     at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:303)
     at java.lang.Thread.run(Thread.java:761)
```

**Comment by AndyScherzinger** [comment]
![device-2016-12-30-172628](https://cloud.githubusercontent.com/assets/1315170/21568474/451382e0-ceb5-11e6-9ee6-c9815f39b983.png)
