### ISSUE TITLE
share PDF file exception 

### ISSUE THREAD

**Issue by mschm05** [nextcloud/android#4869]
### Actual behaviour
- Tell us what happens
Java exception when sharing PDF file with nextcloud client 
### Expected behaviour
- expected upload PDF file into nextcloud
 
### Steps to reproduce
1. use a android v8.0.0 device Samsung A5(2017) 
2. android app "Dateimanager+ V 2.3.1"
3. android app "Nextcloud V3.9.0"
4. select device-local PDF-file in Dateimanager+
5. select share with -> nextcloud
6. crash

### Environment data
Android version: 8.0

Device model: Samsung A5(2017)  

Stock or customized system:

Nextcloud app version:  V3.9.0

Nextcloud server version: 14.0.4.2

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@mschm05 thanks for the report. Could you please report the java exception/stacktrace and also which client/server version you are using? Thanks ❤️

**Comment by mschm05** [comment]
> @mschm05 thanks for the report. Could you please report the java exception/stacktrace and also which client/server version you are using? Thanks heart

the java exception/stacktrace was displayed direct after the crash on the android smartphone. I clicked on report bug, but how to retrive it? where to find the log?? I keep on searching ...
Nextcloud server version 14.0.4.2

**Comment by mschm05** [comment]
here is the log, I think the user wasn't loged into the nextcloud server because on another android device where the user was logged in I could upload the PDF file

 ************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.ReceiveExternalFilesActivity}: java.lang.IllegalStateException: Do not call this method before initializing mStorageManager
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.IllegalStateException: Do not call this method before initializing mStorageManager
	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.initTargetFolder(ReceiveExternalFilesActivity.java:990)
	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onStart(ReceiveExternalFilesActivity.java:241)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1340)
	at android.app.Activity.performStart(Activity.java:7200)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2920)
	... 9 more

 ************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090090
Build flavor: gplay

 ************ DEVICE INFORMATION ************
Brand: samsung
Device: a5y17lte
Model: SM-A520F
Id: R16NW
Product: a5y17ltexx

 ************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: A520FXXUBCSJ1

**Comment by AndyScherzinger** [comment]
seems to be related to #4874 (cc @tobiasKaminsky)

Did you have a user configured/logged-in in the Nextcloud app?

**Comment by mschm05** [comment]
Unter Einstellungen -> Konten war nextcloud nicht zu finden. Offenbar war
kein User eingeloggt.

Andy Scherzinger <notifications@github.com> schrieb am Fr., 22. Nov. 2019,
11:35:

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @ezaquarii I think you fixed this, right?

**Comment by ShadowArtist** [comment]
pdf file upload and retrive ,, retriving has issues app crashes when retriving  uploaded files uploading hepens fine but when we retrive files app crashes

**Comment by tobiasKaminsky** [comment]
Please open up a new issue and fill out the template.
