### ISSUE TITLE
Nextcloud Dev à planté

### ISSUE THREAD

**Issue by madiwas** [nextcloud/android#4870]
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: android/os/PersistableBundle
	at java.lang.Class.getDeclaredMethods(Native Method)
	at java.lang.Class.getPublicMethodsRecursive(Class.java:894)
	at java.lang.Class.getMethods(Class.java:877)
	at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:157)
	at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
	at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
	at org.greenrobot.eventbus.EventBus.register(EventBus.java:140)
	at com.owncloud.android.ui.activity.DrawerActivity.onStart(DrawerActivity.java:1433)
	at com.owncloud.android.ui.activity.FileActivity.onStart(FileActivity.java:207)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2547)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1177)
	at android.app.Activity.performStart(Activity.java:5461)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2386)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
	at android.app.ActivityThread.access$900(ActivityThread.java:175)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5602)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.os.PersistableBundle" on path: DexPathList[[zip file "/data/app/com.nextcloud.android.beta-1.apk", zip file "/data/data/com.nextcloud.android.beta/code_cache/secondary-dexes/com.nextcloud.android.beta-1.apk.classes2.zip"],nativeLibraryDirectories=[/data/app-lib/com.nextcloud.android.beta-1, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
	... 24 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20191119
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: samsung
Device: t03g
Model: GT-N7100
Id: KOT49H
Product: t03gxx

************ FIRMWARE ************
SDK: 19
Release: 4.4.2
Incremental: N7100XXSFQA9

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by pSub** [comment]
When I start the app it crashes with the same error message and stacktrace.
```
************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20191221
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: KYOCERA
Device: KC-S701
Model: KC-S701
Id: 102.0.1920
Product: KC-S701

************ FIRMWARE ************
SDK: 19
Release: 4.4.2
Incremental: 102.0.1920
```

**Comment by pSub** [comment]
It seems this bug is similar to https://github.com/greenrobot/EventBus/issues/156 and there is also an [FAQ](http://greenrobot.org/eventbus/documentation/faq/#A_javalangNoClassDefFoundError_is_throw_when_a_subscriber_class_is_registered_What_can_I_do) on greenrobot.org that seems to talk about this class of errors.

**Comment by tobiasKaminsky** [comment]
Sorry for coming back so late.
Is this still happening?
