### ISSUE TITLE
Fresh installation: share file to app

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#4874]
### Actual behaviour
- crash, but without shown to user
- app starts

### Expected behaviour
- good question :/
 
### Steps to reproduce
1. fresh installation
2. share a file to nc app

`
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nextcloud.client, PID: 28601
    java.lang.IllegalStateException: Do not call this method before initializing mStorageManager
        at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.initTargetFolder(ReceiveExternalFilesActivity.java:991)
        at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onStart(ReceiveExternalFilesActivity.java:241)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1425)
        at android.app.Activity.performStart(Activity.java:7825)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
`
This leads to crash reports on google dev console.

My first idea is to check if we have an account and only then throw the error, otherwise just return with a toast(?)?

**Comment by AndyScherzinger** [comment]
> My first idea is to check if we have an account and only then throw the error, otherwise just return with a toast(?)?

sounds good to me

**Comment by tobiasKaminsky** [comment]
Toast: "Please setup an account!"

All other text would maybe consume too much space, or?

**Comment by AndyScherzinger** [comment]
> "Please setup an account first"

Fine with me, I'd say no exclamation mark :)

**Comment by tobiasKaminsky** [comment]
This is fixed via https://github.com/nextcloud/android/pull/5829
