### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by kai-uwe-rommel** [nextcloud/android#4896]
### Actual behaviour
- Tell us what happens

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED flg=0x10 pkg=com.nextcloud.client (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver@c798383
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1401)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:874)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:198)
	at android.app.ActivityThread.main(ActivityThread.java:6729)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=2555, uid=1010244 requires android.permission.BROADCAST_STICKY
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.app.IActivityManager$Stub$Proxy.unbroadcastIntent(IActivityManager.java:3861)
	at android.app.ContextImpl.removeStickyBroadcast(ContextImpl.java:1358)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
	at com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver.onReceive(FileDisplayActivity.java:1415)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1391)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Nokia
Device: AOP_sprout
Model: Nokia 9
Id: PPR1.180610.011
Product: Beholder_00WW

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 00WW_4_27G

### Expected behaviour
- Tell us what should happen
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Do you have any more infos @AndyScherzinger 
Otherwise I have no idea how to reproduce it :/

**Comment by AndyScherzinger** [comment]
anfortunately no, @kai-uwe-rommel do you run the app on a work profile? Just asking because such errors as your happen in that case and the app isn't support Android for work.

**Comment by kai-uwe-rommel** [comment]
I had simply stopped trying to use ist at this time (in November).
I have now tried again and installed it into both the personal and the work profile.
This time it seems to work (for now) in both.
But since November, the device got an upgrade from Android 9 to 10.
Who knows what (how many) changes this brought with it ...

**Comment by AndyScherzinger** [comment]
the definitely has Android 10 issues (as being reported in other issues) but I'll then close the issue for now. Feel free to comment/re-open if the issue comes back, which still Work profiles aren't supported, so if they work it is not "by-design".

**Comment by AndyScherzinger** [comment]
Duplicate of #6654
