### ISSUE TITLE
Illegal argument exception: ActivityRecord not found

### ISSUE THREAD

**Issue by PatrickOnGit** [nextcloud/android#4905]
### Actual behaviour
- photo upload with large backlog (~3000 photos) on slow network keeps crashing.
It starts syncing some files, but every so often crashes.

### Expected behaviour
- no exception raised
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:
 9, kernel 3.18.120

Device model: 
OnePlus3 A3003

Stock or customized system:
OxygenOS 9.0.5

Nextcloud app version:
3.9.0

Nextcloud server version:
?

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```

************ CAUSE OF ERROR ************

java.lang.IllegalArgumentException: reportSizeConfigurations: ActivityRecord not found for: Token{1c1dfab ActivityRecord{2d9ddfa u0 com.nextcloud.client/com.owncloud.android.ui.activity.UploadListActivity t-1 f}}
at android.os.Parcel.createException(Parcel.java:1954)
at android.os.Parcel.readException(Parcel.java:1918)
at android.os.Parcel.readException(Parcel.java:1868)
at android.app.IActivityManager$Stub$Proxy.reportSizeConfigurations(IActivityManager.java:8673)
at android.app.ActivityThread.reportSizeConfigurations(ActivityThread.java:3217)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3176)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6863)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.os.RemoteException: Remote stack trace:
at com.android.server.am.ActivityManagerService.reportSizeConfigurations(ActivityManagerService.java:9770)
at android.app.IActivityManager$Stub.onTransact$reportSizeConfigurations$(IActivityManager.java:11382)
at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2772)
at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3826)
at android.os.Binder.execTransact(Binder.java:752)


************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus3
Model: ONEPLUS A3003
Id: PKQ1.181203.001
Product: OnePlus3

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 1907311932

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by ezaquarii** [comment]
@AndyScherzinger @tobiasKaminsky  
This is most likely a platform bug, ie. not our fault. Not much we can do here.
