### ISSUE TITLE
Nextcloud Android Crashed 

### ISSUE THREAD

**Issue by muellert** [nextcloud/android#4906]
### Actual behaviour
- Tell us what happens
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to read from field 'android.app.Activity android.app.ActivityThread$ActivityClientRecord.activity' on a null object reference
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3949)
	at android.app.ActivityThread.-wrap25(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1530)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus3
Model: ONEPLUS A3000
Id: N2G47O
Product: lineage_oneplus3

************ FIRMWARE ************
SDK: 25
Release: 7.1.2
Incremental: 9096084575
### Expected behaviour
- Tell us what should happen
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@muellert do you have any details regarding the stack trace and also when this is hapüpening / how to reproduce it? I am also running lineage_oneplus3 (but SDK28 as in Lineage 16) without any issues as posted by yopu above
