### ISSUE TITLE
Upload view crash when playing with flight mode

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#491]
Steps to reproduce:
1. set auto upload for Camera + wifi only upload
2. activate flight mode
3. take pictures
4. open clients upload view
5. deactivate flight mode (leadign to a wifi reconnect)
6. right when activated go back to the Nc client / uploads view
7. crash

```
12-30 15:57:41.624 26034-26034/com.nextcloud.client E/AndroidRuntime: FATAL EXCEPTION: main
  Process: com.nextcloud.client, PID: 26034
  java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.files.services.FileUploaderUPLOADS_ADDED flg=0x10 } in com.owncloud.android.ui.activity.UploadListActivity$UploadMessagesReceiver@64a4f11
      at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1132)
      at android.os.Handler.handleCallback(Handler.java:751)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at android.os.Looper.loop(Looper.java:154)
      at android.app.ActivityThread.main(ActivityThread.java:6119)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.owncloud.android.datamodel.UploadsStorageManager$UploadStatus com.owncloud.android.db.OCUpload.getUploadStatus()' on a null object reference
      at com.owncloud.android.ui.adapter.ExpandableUploadListAdapter$UploadGroup$1.compare(ExpandableUploadListAdapter.java:98)
      at com.owncloud.android.ui.adapter.ExpandableUploadListAdapter$UploadGroup$1.compare(ExpandableUploadListAdapter.java:93)
      at java.util.TimSort.countRunAndMakeAscending(TimSort.java:351)
      at java.util.TimSort.sort(TimSort.java:216)
      at java.util.Arrays.sort(Arrays.java:1450)
      at com.owncloud.android.ui.adapter.ExpandableUploadListAdapter$1.refresh(ExpandableUploadListAdapter.java:145)
      at com.owncloud.android.ui.adapter.ExpandableUploadListAdapter.loadUploadItemsFromDb(ExpandableUploadListAdapter.java:616)
      at com.owncloud.android.ui.adapter.ExpandableUploadListAdapter.refreshView(ExpandableUploadListAdapter.java:631)
      at com.owncloud.android.ui.fragment.UploadListFragment.updateUploads(UploadListFragment.java:148)
      at com.owncloud.android.ui.activity.UploadListActivity$UploadMessagesReceiver.onReceive(UploadListActivity.java:337)
      at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1122)
      at android.os.Handler.handleCallback(Handler.java:751) 
      at android.os.Handler.dispatchMessage(Handler.java:95) 
      at android.os.Looper.loop(Looper.java:154) 
      at android.app.ActivityThread.main(ActivityThread.java:6119) 
      at java.lang.reflect.Method.invoke(Native Method) 
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger is this happening after the big rewrite of auto upload?

**Comment by tobiasKaminsky** [comment]
This NPE should be fixed with  
https://github.com/nextcloud/android/commit/1219844d58b5bdeb670f00b06340d6369dd7b860 as it first checks if upload1 or upload2 is null.
