### ISSUE TITLE
NextCloud on Android - crash

### ISSUE THREAD

**Issue by FlavML** [nextcloud/android#4913]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to read from field 'com.owncloud.android.lib.resources.files.SearchRemoteOperation$SearchType com.owncloud.android.ui.events.SearchEvent.searchType' on a null object reference
	at com.owncloud.android.ui.activity.FileDisplayActivity.onNewIntent(FileDisplayActivity.java:518)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1243)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1255)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2824)
	at android.app.ActivityThread.performNewIntents(ActivityThread.java:2839)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2855)
	at android.app.ActivityThread.-wrap15(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1569)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6148)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Lenovo
Device: yeti
Model: Lenovo YB1-X90F
Id: NMF26X
Product: yeti_10_row_wifi

************ FIRMWARE ************
SDK: 25
Release: 7.1.1
Incremental: YB1-X90F_USR_S100083_1710130000_WW08_BP_ROW

**Comment by AndyScherzinger** [comment]
unchecked
