### ISSUE TITLE
Issue com.nextcloud.client

### ISSUE THREAD

**Issue by SMichel72** [nextcloud/android#4928]
************ CAUSE OF ERROR ************

java.lang.OutOfMemoryError: Failed to allocate a 44793868 byte allocation with 16777216 free bytes and 36MB until OOM
at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:646)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:622)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:660)
at com.owncloud.android.ui.adapter.DiskLruImageCache.getBitmap(DiskLruImageCache.java:121)
at com.owncloud.android.datamodel.ThumbnailsCacheManager.getBitmapFromDiskCache(ThumbnailsCacheManager.java:225)
at com.owncloud.android.ui.preview.PreviewImageFragment.onStart(PreviewImageFragment.java:247)
at androidx.fragment.app.Fragment.performStart(Fragment.java:2632)
at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:915)
at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
at androidx.fragment.app.FragmentManagerImpl.dispatchStart(FragmentManagerImpl.java:2619)
at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:257)
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:551)
at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
at com.owncloud.android.ui.activity.BaseActivity.onStart(BaseActivity.java:173)
at com.owncloud.android.ui.activity.DrawerActivity.onStart(DrawerActivity.java:1417)
at com.owncloud.android.ui.activity.FileActivity.onStart(FileActivity.java:207)
at com.owncloud.android.ui.preview.PreviewImageActivity.onStart(PreviewImageActivity.java:185)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
at android.app.Activity.performStart(Activity.java:6739)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2632)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2730)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4539)
at android.app.ActivityThread.-wrap19(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1487)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6144)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: ZTE
Device: P840F12
Model: ZTE BLADE A0620
Id: NMF26F
Product: HOFER_AT_P840F12

************ FIRMWARE ************
SDK: 25
Release: 7.1.1
Incremental: 20180823.172510

**Comment by tobiasKaminsky** [comment]
As said in error message OutOfMemoryError: Failed to allocate a 44793868 byte
I do not know your phone, but it seems to have too little memory to open an image…

**Comment by ezaquarii** [comment]
44MB image is pretty big. Either the user has indeed trying to load big image or cache is corrupted.

We could check the image size before decoding and if it is indeed unreasonably big, apply downscaling.
