### ISSUE TITLE
Crash on login

### ISSUE THREAD

**Issue by bityoda** [nextcloud/android#4963]
************ CAUSE OF ERROR ************

android.view.InflateException: Binary XML file line #7 in com.nextcloud.android.beta:layout/account_setup_webview: Binary XML file line #7 in com.nextcloud.android.beta:layout/account_setup_webview: Error inflating class android.webkit.WebView
Caused by: android.view.InflateException: Binary XML file line #7 in com.nextcloud.android.beta:layout/account_setup_webview: Error inflating class android.webkit.WebView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:854)
	at android.view.LayoutInflater.createView(LayoutInflater.java:776)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:930)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:950)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
	at com.owncloud.android.authentication.AuthenticatorActivity.onGetServerInfoFinish(AuthenticatorActivity.java:1313)
	at com.owncloud.android.authentication.AuthenticatorActivity.onRemoteOperationFinish(AuthenticatorActivity.java:1212)
	at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:727)
	at com.owncloud.android.services.-$$Lambda$OperationsService$2BVgsxDpOpa4JqgzeD7OGZBLSiI.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:435)
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:252)
	at android.webkit.WebView.getFactory(WebView.java:2576)
	at android.webkit.WebView.ensureProviderCreated(WebView.java:2570)
	at android.webkit.WebView.setOverScrollMode(WebView.java:2638)
	at android.view.View.<init>(View.java:5088)
	at android.view.View.<init>(View.java:5241)
	at android.view.ViewGroup.<init>(ViewGroup.java:686)
	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
	at android.webkit.WebView.<init>(WebView.java:411)
	at android.webkit.WebView.<init>(WebView.java:354)
	at android.webkit.WebView.<init>(WebView.java:337)
	at android.webkit.WebView.<init>(WebView.java:324)
	... 27 more
Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:339)
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:402)
	... 39 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20191204
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus7TPro
Model: HD1913
Id: QKQ1.190716.003
Product: OnePlus7TPro_EEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 1911061800

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky any idea?

**Comment by bityoda** [comment]
I have this problem on the weekend, trying to initialize my nextcloud environment on a new phone. The problem seems to reference to a missing library but i could not get the reason why.

Anyway the problem seems to be gone, today. From my opinion you can close the bug.

**Comment by AndyScherzinger** [comment]
Thanks for the feedback @bityoda - this is highly appreciated. It might also be that a newer build fixed it.
