### ISSUE TITLE
App crashes when trying to enter "settings"

### ISSUE THREAD

**Issue by gorjan-hub** [nextcloud/android#4968]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.android.beta/com.owncloud.android.ui.activity.SettingsActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2830)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2909)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1606)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
	at com.owncloud.android.ui.activity.SettingsActivity.setupGeneralCategory(SettingsActivity.java:712)
	at com.owncloud.android.ui.activity.SettingsActivity.onCreate(SettingsActivity.java:168)
	at android.app.Activity.performCreate(Activity.java:6984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1235)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2783)
	... 9 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20191206
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: motorola
Device: addison
Model: XT1635-02
Id: OPNS27.76-12-22-9
Product: addison

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: 10

**Comment by AndyScherzinger** [comment]
@gorjan-hub does this als happen with the latest dev build? Just asking since @tobiasKaminsky did a fix for Version: 20191206

**Comment by gorjan-hub** [comment]
yes, the latest build with f-droid. This happened after reinstalling
the application of the same assembly 20190612.


пн, 9 дек. 2019 г., 12:04 Andy Scherzinger <notifications@github.com>:

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky without looking at the code this likely needs to be fixed for 3.10

**Comment by gorjan-hub** [comment]
Installed the official application of the latest version 3.9.2. There
is no error. There is an error in the dev application.


пн, 9 дек. 2019 г., 13:42 Andy Scherzinger <notifications@github.com>:

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky it's
```
themePref.setSummary(themePref.getEntry().length() == 0 ? DarkMode.LIGHT.name() : themePref.getEntry());
```

`themePref.getEntry()`is likely null initially!

**Comment by codejp3** [comment]
Awaiting update. Same issue on latest Dev version only. Standard App currently working fine.

**Comment by tobiasKaminsky** [comment]
This is fixed via https://github.com/nextcloud/android/pull/4956

@gorjan-hub which dev version do you use?

**Comment by gorjan-hub** [comment]
Dev version 20191206

вт, 10 дек. 2019 г., 11:52 Tobias Kaminsky <notifications@github.com>:

**Comment by AndyScherzinger** [comment]
@gorjan-hub can you upgrade to 2019120**7**

**Comment by codejp3** [comment]
20191206 is latest in f-droid. Issue exists in that version. I'll try out 20191207 as soon as available.

**Comment by gorjan-hub** [comment]
Ver. 20191207 is not available in F-droid
вт, 10 дек. 2019 г., 20:30 codejp3 <notifications@github.com>:

**Comment by codejp3** [comment]
Update working here. Thank you!

**Comment by AndyScherzinger** [comment]
@gorjan-hub I'll close the issue based on @codejp3's feedback (thanks for that), please re-open in case the issue still happens for you with 20191207 (or newer)
