### ISSUE TITLE
Einstellungen funktioniert nicht

### ISSUE THREAD

**Issue by weinic** [nextcloud/android#4969]
Wenn ich auf Einstellungen klicke stürzt die APP ab.
;
;
;
;
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.android.beta/com.owncloud.android.ui.activity.SettingsActivity}: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:235)
	at android.preference.Preference.getPersistedString(Preference.java:1475)
	at android.preference.ListPreference.onSetInitialValue(ListPreference.java:295)
	at android.preference.Preference.dispatchSetInitialValue(Preference.java:1391)
	at android.preference.Preference.onAttachedToHierarchy(Preference.java:1185)
	at android.preference.PreferenceGroup.addPreference(PreferenceGroup.java:163)
	at android.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:105)
	at android.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:104)
	at android.preference.GenericInflater.rInflate(GenericInflater.java:490)
	at android.preference.GenericInflater.rInflate(GenericInflater.java:495)
	at android.preference.GenericInflater.inflate(GenericInflater.java:327)
	at android.preference.GenericInflater.inflate(GenericInflater.java:264)
	at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:280)
	at android.preference.PreferenceActivity.addPreferencesFromResource(PreferenceActivity.java:1521)
	at com.owncloud.android.ui.activity.SettingsActivity.onCreate(SettingsActivity.java:151)
	at android.app.Activity.performCreate(Activity.java:6684)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
	... 9 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20191206
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: samsung
Device: hlte
Model: SM-N9005
Id: NJH47F
Product: lineage_hlte

************ FIRMWARE ************
SDK: 25
Release: 7.1.2
Incremental: a9639c51c9

**Comment by AndyScherzinger** [comment]
Duplicate #4956 fixed via #4956 - please update to latest dev version
