### ISSUE TITLE
Netxcloud Dev app crashes when trying to open settings

### ISSUE THREAD

**Issue by codejp3** [nextcloud/android#4972]
### Actual behaviour
- App crashes when trying to open the settings page. Standard app works fine. Only the Dev version crashes. Tried clearing cache and data with no effect.

### Expected behaviour
- Expecting the settings page to show.
 
### Steps to reproduce
1. Open app
2. Tap menu icon
3. Tap Settings

### Environment data
Android version:
Pie
Device model: 
KLTE-TMO
Stock or customized system:
Lineage ROM
Nextcloud app version:

Nextcloud server version:
15 and 17
#### App Crash Report Log
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.android.beta/com.owncloud.android.ui.activity.SettingsActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
	at com.owncloud.android.ui.activity.SettingsActivity.setupGeneralCategory(SettingsActivity.java:712)
	at com.owncloud.android.ui.activity.SettingsActivity.onCreate(SettingsActivity.java:168)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
	... 11 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20191206
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: samsung
Device: kltetmo
Model: SM-G900T
Id: PQ3A.190801.002
Product: lineage_klte

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: cc929d24cb

**Comment by codejp3** [comment]
Saw another open ticket for this. Going there now
