### ISSUE TITLE
Crash of App when used as sharing Target before configuring any accounts

### ISSUE THREAD

**Issue by splumhoff** [nextcloud/android#4975]
Repro:
Share Data with the nextcloud app before init. any accounts

************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Do not call this method before initializing mStorageManager
	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.initTargetFolder(ReceiveExternalFilesActivity.java:990)
	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onStart(ReceiveExternalFilesActivity.java:241)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1395)
	at android.app.Activity.performStart(Activity.java:7374)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3187)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7263)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: d2s
Model: SM-N975F
Id: PPR1.180610.011
Product: d2seea

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: N975FXXS1ASKB

**Comment by tobiasKaminsky** [comment]
this is fixed via https://github.com/nextcloud/android/pull/5829
