### ISSUE TITLE
Android app crashes when I try to use settings 

### ISSUE THREAD

**Issue by revisionist0** [nextcloud/android#4988]
### Actual behaviour
- Tell us what happens

### Expected behaviour
- Tell us what should happen
 
### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.android.beta/com.owncloud.android.ui.activity.SettingsActivity}: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:283)
	at android.preference.Preference.getPersistedString(Preference.java:1650)
	at android.preference.ListPreference.onSetInitialValue(ListPreference.java:295)
	at android.preference.Preference.dispatchSetInitialValue(Preference.java:1560)
	at android.preference.Preference.onAttachedToHierarchy(Preference.java:1328)
	at android.preference.PreferenceGroup.addPreference(PreferenceGroup.java:163)
	at android.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:105)
	at android.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:42)
	at android.preference.GenericInflater.rInflate(GenericInflater.java:490)
	at android.preference.GenericInflater.rInflate(GenericInflater.java:495)
	at android.preference.GenericInflater.inflate(GenericInflater.java:327)
	at android.preference.GenericInflater.inflate(GenericInflater.java:264)
	at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:324)
	at android.preference.PreferenceActivity.addPreferencesFromResource(PreferenceActivity.java:1549)
	at com.owncloud.android.ui.activity.SettingsActivity.onCreate(SettingsActivity.java:151)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
	... 11 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20191206
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: google
Device: marlin
Model: Pixel XL
Id: PQ3A.190801.002
Product: marlin

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: ccbfc44607

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by ezaquarii** [comment]
@tobiasKaminsky @AndyScherzinger Is it possible that the schema changed or UI has been updated recently?

This crash happens during initial UI hydration - something epects boolean and gets a string.

@revisionist0 Can you tell us what was your upgrade path?

**Comment by AndyScherzinger** [comment]
Bug is already fixed in 20191207 fixed via #4956

**Comment by AndyScherzinger** [comment]
As for the question, yes theme changed from boolean to string

**Comment by revisionist0** [comment]
Hi.
I use F-Droid to manage this app.
I deleted the Nextcloud Dev app, waited a day, then reinstalled said app
after I noticed that it had been updated at source.

The Nextcloud Dev app now works as expected and I cannot reproduce the
crash.

Thanks for your help.

**Comment by AndyScherzinger** [comment]
Thanks for reporting back 🙏
