### ISSUE TITLE
crash when uploading a file

### ISSUE THREAD

**Issue by geraldmwangi** [nextcloud/android#4996]
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Fragment IndeterminateProgressDialog{d0ba7aa (bdfce9d5-447d-42e6-9b62-08b28c6c6865)} not associated with a fragment manager.
	at androidx.fragment.app.Fragment.requireFragmentManager(Fragment.java:910)
	at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:245)
	at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:202)
	at com.owncloud.android.ui.activity.UploadFilesActivity.onCheckAvailableSpaceFinish(UploadFilesActivity.java:471)
	at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:72)
	at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:34)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.-wrap1(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Sony
Device: H3113
Model: H3113
Id: OPM7.181205.001
Product: H3113

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: 3147793b8b

**Comment by tobiasKaminsky** [comment]
I think we fixed this already, at least I do not recall seeing this in gplay crash…
