### ISSUE TITLE
Only trigger media scanner for media files

### ISSUE THREAD

**Issue by grote** [nextcloud/android#4999]
There's several places in the app where [`triggerMediaScan()` is called](https://github.com/nextcloud/android/search?q=triggerMediaScan&type=Code). This happens irrespective of the mimeType which is available in some of these places.

For huge non-media files, this can slow down the system significantly and even crash with OOM errors. Furthermore when writing these files with a DocumentsProvider, maybe the user doesn't want these files get indexed by the media scanner?

Anyway, a simple fix would be to check the mimetype for media files and only trigger a scan for those.

**Comment by grote** [comment]
Just saw this in my log, related but maybe not exactly the same issue:

```
2019-12-16 09:12:03.050 E/Bitmap: OOM allocating Bitmap with dimensions 1440 x 534528
2019-12-16 09:12:03.051 E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
    java.lang.OutOfMemoryError
        at android.graphics.Bitmap.nativeCreate(Native Method)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1122)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:952)
        at android.media.ThumbnailUtils.transform(ThumbnailUtils.java:521)
        at android.media.ThumbnailUtils.extractThumbnail(ThumbnailUtils.java:413)
        at android.media.ThumbnailUtils.extractThumbnail(ThumbnailUtils.java:388)
        at com.owncloud.android.datamodel.ThumbnailsCacheManager.addThumbnailToCache(ThumbnailsCacheManager.java:191)
        at com.owncloud.android.datamodel.ThumbnailsCacheManager.generateResizedImage(ThumbnailsCacheManager.java:1197)
        at com.owncloud.android.operations.RemoveFileOperation.run(RemoveFileOperation.java:95)
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:180)
        at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:87)
        at com.owncloud.android.providers.DocumentsStorageProvider.deleteDocument(DocumentsStorageProvider.java:576)
```

The file in question is not an image and has mime type `application/octet-stream`, so trying to extract a thumbnail is daring.
