### ISSUE TITLE
App crashes after launching file details page

### ISSUE THREAD

**Issue by ezaquarii** [nextcloud/android#5002]
### Steps to reproduce
1.  Launch master-compiled QA variant app
2.  Open file details page
3. Wait until it force-closes

### Environment data
Nextcloud app version: master

### Logs
```
E/AndroidRuntime: FATAL EXCEPTION: Thread-13
    Process: com.nextcloud.android.qa, PID: 14858
    kotlin.UninitializedPropertyAccessException: lateinit property response has not been initialized
        at com.nextcloud.common.OkHttpMethodBase.releaseConnection(OkHttpMethodBase.kt:68)
        at com.owncloud.android.lib.resources.activities.GetActivitiesRemoteOperation.run(GetActivitiesRemoteOperation.java:158)
        at com.nextcloud.common.NextcloudClient.execute(NextcloudClient.kt:63)
        at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$fetchAndSetData$5$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:331)
        at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$N7POe6TZvoGcuV2qP-niPxY_7t4.run(Unknown Source:12)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by ezaquarii** [comment]
It looks like a problem with OkHttp itself, not a nextcloud app bug.

**Comment by EmPeWe** [comment]
I have this Bug too. F-Droid v3.9.2

**Comment by ezaquarii** [comment]
@tobiasKaminsky are we on top of `OkHttp` version?
