### ISSUE TITLE
NPE when removing document with DocumentsProvider

### ISSUE THREAD

**Issue by grote** [nextcloud/android#5015]
```
D/OwnCloudClient #0: REQUEST DELETE /remote.php/webdav/.AndroidBackup/1576247608692/full/com.android.dreams.phototable
I/RemoveFileRemoteOperation: Remove /.AndroidBackup/1576247608692/full/com.android.dreams.phototable: Operation finished with HTTP status code 204 (success)
D/FileContentProvider: Removing FILE 00030582ocb1ubps5cpj
E/DatabaseUtils: Writing exception to parcel
    java.lang.NullPointerException: Attempt to invoke virtual method 'long com.owncloud.android.datamodel.OCFile.getParentId()' on a null object reference
        at com.owncloud.android.providers.DocumentsStorageProvider$Document.getParent(DocumentsStorageProvider.java:778)
        at com.owncloud.android.providers.DocumentsStorageProvider.deleteDocument(DocumentsStorageProvider.java:582)
        at android.provider.DocumentsProvider.callUnchecked(DocumentsProvider.java:1164)
        at android.provider.DocumentsProvider.call(DocumentsProvider.java:1067)
        at android.content.ContentProvider.call(ContentProvider.java:2152)
```
It seems like `Document#getFile()` is called to get the parent file, but is not available anymore after the file was deleted.

Looks like this can be easily reproduced by deleting a file from NextCloud with Android's file manager.

```
E/DeleteJob: Failed to delete document @ content://org.nextcloud.documents/document/1472352573%2F4
    com.android.documentsui.services.ResourceException: Failed to delete file content://org.nextcloud.documents/document/1472352573%2F4 due to an exception.
        at com.android.documentsui.services.Job.deleteDocument(Job.java:273)
        at com.android.documentsui.services.DeleteJob.start(DeleteJob.java:119)
```

**Comment by grote** [comment]
Moving `Document parentFolder = document.getParent();` up before the actual delete operation seems to fix this bug.
