### ISSUE TITLE
Crash while attempting to make a new ods file

### ISSUE THREAD

**Issue by nate2014jatc** [nextcloud/android#5020]
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Fragment ChooseTemplateDialogFragment{4ea334e (1687d27f-0bc3-421a-8be8-ec22464705ab)} not attached to Activity
	at androidx.fragment.app.Fragment.startActivity(Fragment.java:1183)
	at androidx.fragment.app.Fragment.startActivity(Fragment.java:1173)
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment$CreateFileFromTemplateTask.onPostExecute(ChooseTemplateDialogFragment.java:250)
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment$CreateFileFromTemplateTask.onPostExecute(ChooseTemplateDialogFragment.java:212)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.access$600(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: google
Device: marlin
Model: Pixel XL
Id: PQ3A.190801.002
Product: marlin

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 7accda42c1

**Comment by nate2014jatc** [comment]
This was an automated bug report that the app generated.

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky since this is collabora related.
