### ISSUE TITLE
Error when you try to connect on an already logged server/user

### ISSUE THREAD

**Issue by Shagequi** [nextcloud/android#5058]
Hi,

When you're connected on a server and want to connect on the SAME server with the SAME user, AND ONLY if you use a `webview_login_url` by default, the app will crash because `mAuthStatusView` is not defined in AuthenticatorActivity.

A "solution" would be to create a try-catch in `showAuthStatus` method, but it's ugly because the AuthenticatorActivity musts show the login input to show the error message.

If a webview_login_url is defined, the wanted behaviour is ALWAYS to connect through this specified URL and we don't want to show the URL input Activity for login. 

So what I suggest, is to create a Toast containing the error, and if the login fail, we finish Authenticator Activity (only if a `webview_login_url` is defined).

@AndyScherzinger @tobiasKaminsky I've figured out that everything related to branding was really not necessary, are you "interested" in this kind of issue or not? Thanks for your answer and have a happy holiday :D

**Comment by Shagequi** [comment]
Here is the error :
2019-12-23 12:32:03.919 12209-12209/com.nextcloud.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nextcloud.android, PID: 12209
    java.lang.NullPointerException: Attempt to invoke virtual method ‘void android.widget.TextView.setText(java.lang.CharSequence)’ on a null object reference
        at com.owncloud.android.authentication.AuthenticatorActivity.showAuthStatus(AuthenticatorActivity.java:1843)
        at com.owncloud.android.authentication.AuthenticatorActivity.createAccount(AuthenticatorActivity.java:1724)
        at com.owncloud.android.authentication.AuthenticatorActivity.onAuthenticatorTaskCallback(AuthenticatorActivity.java:1544)
        at com.owncloud.android.authentication.AuthenticatorAsyncTask.onPostExecute(AuthenticatorAsyncTask.java:100)
        at com.owncloud.android.authentication.AuthenticatorAsyncTask.onPostExecute(AuthenticatorAsyncTask.java:43)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.access$600(AsyncTask.java:180)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by Shagequi** [comment]
Fixed by #5061

**Comment by Shagequi** [comment]
Up, awaiting for approval

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky

**Comment by AndyScherzinger** [comment]
Fix has been merged to master -> 3.12.0
