### ISSUE TITLE
Running in Samsung Knox app crashes

### ISSUE THREAD

**Issue by stephen-d-hill** [nextcloud/android#5059]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED flg=0x10 pkg=com.nextcloud.client (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver@f4c7f3
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1493)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6986)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=17268, uid=15010299 requires android.permission.BROADCAST_STICKY
	at android.os.Parcel.createException(Parcel.java:1966)
	at android.os.Parcel.readException(Parcel.java:1934)
	at android.os.Parcel.readException(Parcel.java:1884)
	at android.app.IActivityManager$Stub$Proxy.unbroadcastIntent(IActivityManager.java:3782)
	at android.app.ContextImpl.removeStickyBroadcast(ContextImpl.java:1425)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:601)
	at com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver.onReceive(FileDisplayActivity.java:1415)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1483)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.unbroadcastIntent(ActivityManagerService.java:26544)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:155)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4127)
	at android.os.Binder.execTransact(Binder.java:739)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: starlte
Model: SM-G960F
Id: PPR1.180610.011
Product: starltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G960FXXS7CSK4

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by stephen-d-hill** [comment]
v3.10.0 still crashes in Knox

**Comment by AndyScherzinger** [comment]
Cc @tobiasKaminsky since I think we do not plan to support Knox

**Comment by stephen-d-hill** [comment]
After my S9 upgraded to Android 10,  this app now works fine in Knox.

**Comment by AndyScherzinger** [comment]
Thanks for the update @stephen-d-hill ❤️ Glad to hear that the OS update resolved the issue for you.

**Comment by AndyScherzinger** [comment]
Duplicate of #6654
