### ISSUE TITLE
PreviewTextFragment crashes :(

### ISSUE THREAD

**Issue by Shagequi** [nextcloud/android#5068]
Hi,

After the commit : https://github.com/nextcloud/android/commit/ec2cfef13867a31d0f5e2336451520fe0a898fe1 (Direct editing support) the PreviewTextFragment creates an error when instanciated (so the app crashes), here is an error : 

```
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.owncloud.android.ui.preview.PreviewTextFragment: make sure class name exists, is public, and has an empty constructor that is public
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:530)
        at com.owncloud.android.ui.activity.FileDisplayActivity.startTextPreview(FileDisplayActivity.java:2373)
        at com.owncloud.android.ui.activity.FileDisplayActivity.refreshSecondFragment(FileDisplayActivity.java:745)
        at com.owncloud.android.ui.activity.FileDisplayActivity$DownloadFinishReceiver.onReceive(FileDisplayActivity.java:1555)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1483)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
``` 
This happens when I click on a text file on `master` branch.

@tobiasKaminsky do you know how to fix that ?
Thanks

**Comment by AndyScherzinger** [comment]
Pinging @tobiasKaminsky again since this is high prio IMHO.

**Comment by tobiasKaminsky** [comment]
Can you retry this? I remember to fixed this shortly afterwards.

**Comment by AndyScherzinger** [comment]
@Shagequi so close the issue?

**Comment by Shagequi** [comment]
It is fixed, I close the issue.
Thanks
