### ISSUE TITLE
App crashes when trying to upload file without setting up an account first

### ISSUE THREAD

**Issue by David-Development** [nextcloud/android#5071]
### Steps to reproduce
1. Install nextcloud files app
2. Do not open or setup nextcloud files app
3. Go to the gallery, open a photo, click on share, select nextcloud

### Expected behaviour
- show the login page

### Actual behaviour
- app crashes

### Logs

```
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Do not call this method before initializing mStorageManager
 at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.initTargetFolder(ReceiveExternalFilesActivity.java:990)
 at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onStart(ReceiveExternalFilesActivity.java:241)
 at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1514)
 at android.app.Activity.performStart(Activity.java:7838)
 at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3398)
 at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
 at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
 at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:214)
 at android.app.ActivityThread.main(ActivityThread.java:7682)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus7T
Model: HD1903
Id: QKQ1.190716.003
Product: OnePlus7T_EEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 1912060025
```

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky did you fix this for 3.10? I think you or @ezaquarii did a fix for this, right?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky did you fix this for 3.10? I think you or @ezaquarii did a fix for this, right?

**Comment by ezaquarii** [comment]
I don't remember now, but I'll take a look.

**Comment by tobiasKaminsky** [comment]
This is fixed, it shows a toast message and shows server input screen.
