### ISSUE TITLE
Pdf viewer

### ISSUE THREAD

**Issue by BugProg** [nextcloud/android#5073]
************ CAUSE OF ERROR ************

kotlin.UninitializedPropertyAccessException: lateinit property response has not been initialized
	at com.nextcloud.common.OkHttpMethodBase.releaseConnection(OkHttpMethodBase.kt:68)
	at com.owncloud.android.lib.resources.activities.GetActivitiesRemoteOperation.run(GetActivitiesRemoteOperation.java:158)
	at com.nextcloud.common.NextcloudClient.execute(NextcloudClient.kt:63)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$fetchAndSetData$5$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:331)
	at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$N7POe6TZvoGcuV2qP-niPxY_7t4.run(Unknown Source:12)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20191221
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus5T
Model: ONEPLUS A5010
Id: PQ3A.190605.003
Product: OnePlus5T

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 7ec472ea7a

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky ever experienced this? @BugProg is this still happending with the latest nightlies?

**Comment by BugProg** [comment]
Yes for me the problem persists.
