### ISSUE TITLE
Crash creating folder

### ISSUE THREAD

**Issue by zicmama** [nextcloud/android#5081]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.datamodel.OCFile.canWrite()' on a null object reference
	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onCreateOptionsMenu(ReceiveExternalFilesActivity.java:1030)
	at android.app.Activity.onCreatePanelMenu(Activity.java:3465)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:325)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2830)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:655)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: herolte
Model: SM-G930F
Id: R16NW
Product: heroltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: G930FXXS6ESJ2

### Steps to reproduce
1. Share file
2. Change serveur
3. Create folder

**Comment by MichaelTiernan** [comment]
Reproduced easily for me... on two diff devices.

1. Select _Auto upload_
1. Select _Set up a custom folder_
1. Select _Remote folder_
1. Select _New folder_
1. Enter any name press _Create_

***BOOM***

**Comment by AndyScherzinger** [comment]
@MichaelTiernan your error has no link to the one reported here, see `ReceiveExternalFilesActivity` within the initial post which posts to files shared to Nextcloud via Androids share Action from within another app. Yours is a duplicate of #4792 - please comment over there so we have all info in one central place and it be important where you create the folder (root, or sub-directory for example).

**Comment by tobiasKaminsky** [comment]
@zicmama do you know when an how this occurs? Can you reliable reproduce it?

**Comment by MichaelTiernan** [comment]
> @MichaelTiernan your error has no link to the one reported here, s

Thanks for the correction.

I'll revist this more carefully.

**Comment by MichaelTiernan** [comment]
Based on what @AndyScherzinger said I revisited it.
I believe him when he states that this is not the same as the issue #4792 and have looked more carefully and updated that ticket with more info.

To that end, you may ignore my comments on this issue but other's may have more to say on it.

**Comment by AndyScherzinger** [comment]
@Shagequi does your fix also work in this scenario (create folder NPE)

**Comment by tobiasKaminsky** [comment]
> Reproduced easily for me... on two diff devices.
> 
>     1. Select _Auto upload_
> 
>     2. Select _Set up a custom folder_
> 
>     3. Select _Remote folder_
> 
>     4. Select _New folder_
> 
>     5. Enter any name press _Create_

I tested this with 3.11 RC2, and it worked.
Can you verify? :-)
