### ISSUE TITLE
Cause of error

### ISSUE THREAD

**Issue by t00sik** [nextcloud/android#5099]
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=3530, totalRows=40
at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:859)
at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:159)
at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:128)
at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:237)
at android.database.AbstractCursor.moveToNext(AbstractCursor.java:275)
at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:128)
at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:108)
at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:299)
at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:662)
at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:319)
at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:474)
at android.content.ContentResolver.applyBatch(ContentResolver.java:1642)
at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:408)
at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:445)
at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:339)
at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:224)
at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:299)
at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: polaris
Model: Mi MIX 2S
Id: PKQ1.180729.001
Product: polaris

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: V11.0.4.0.PDGMIXM

**Comment by t00sik** [comment]
Thank you

пн, 17 февр. 2020 г., 17:26 stale[bot] <notifications@github.com>:
