### ISSUE TITLE
Crash Log

### ISSUE THREAD

**Issue by Volker-Weissmann** [nextcloud/android#5126]
A few months ago, NC crashed with the  message below.
I don't use NC anymore, so I don't care if you fix it, but I thought it might the helpful to you.
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:1536)
	at androidx.fragment.app.FragmentManagerImpl.enqueueAction(FragmentManagerImpl.java:1558)
	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:317)
	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:282)
	at androidx.fragment.app.DialogFragment.show(DialogFragment.java:172)
	at com.owncloud.android.ui.activity.FileActivity.showLoadingDialog(FileActivity.java:501)
	at com.owncloud.android.ui.helpers.FileOperationsHelper.lambda$syncFile$1$FileOperationsHelper(FileOperationsHelper.java:239)
	at com.owncloud.android.ui.helpers.-$$Lambda$FileOperationsHelper$6veiwPPVcnDkYiDbC_hH1dHAJ4s.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus3
Model: ONEPLUS A3003
Id: PQ3A.190801.002
Product: lineage_oneplus3

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 2c68844f02

**Comment by tobiasKaminsky** [comment]
Thanks for the bug report.
Do you remember when this occured? Otherwise it is hard to reproduce.

**Comment by Volker-Weissmann** [comment]
I can't reproduce it, but I remember that everytime I was trying to sync large amounts of data, I got the "Nextcloud doesn't respond" Android message and when I ignored the message and tried to use the app, it crashed.

**Comment by joshtrichards** [comment]
Fixed in #13037

**Comment by Volker-Weissmann** [comment]
> Fixed in #13037

Thanks
