### ISSUE TITLE
Crash when sharing directory on External storage

### ISSUE THREAD

**Issue by erik78se** [nextcloud/android#5142]
### Steps to reproduce
1. Tried share a folder. The folder is on a Nas external drive
2. The app crashes
3. 

### Expected behaviour
- Tell us what should happen
Allows me to share by link
### Actual behaviour
- Tell us what happens
Crash
### Environment data
Android version:
9
Device model: 
Huawei p30 pro

Stock or customized system:
Stock

Nextcloud app version:
3.10.0 rc1

Nextcloud server version:
17.0.1
### Logs
************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWVOG
Model: VOG-L29
Id: HUAWEIVOG-L29
Product: VOG-L29EEA

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 9.1.0.260C431

************ CAUSE OF ERROR ************

kotlin.UninitializedPropertyAccessException: lateinit property response has not been initialized
	at com.nextcloud.common.OkHttpMethodBase.releaseConnection(OkHttpMethodBase.kt:68)
	at com.owncloud.android.lib.resources.activities.GetActivitiesRemoteOperation.run(GetActivitiesRemoteOperation.java:158)
	at com.nextcloud.common.NextcloudClient.execute(NextcloudClient.kt:63)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$fetchAndSetData$5$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:331)
	at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$N7POe6TZvoGcuV2qP-niPxY_7t4.run(Unknown Source:12)
	at java.lang.Thread.run(Thread.java:784)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWVOG
Model: VOG-L29
Id: HUAWEIVOG-L29
Product: VOG-L29EEA

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 9.1.0.260C431

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky this is at least the second report with such a stack trace if I remember correctly and is likely related to the network library change (I guess).
