### ISSUE TITLE
Crash after changing themes

### ISSUE THREAD

**Issue by adrianvg** [nextcloud/android#5160]
### Steps to reproduce
1. Open Nextcloud android sync client v3.10.0 rc2. 
2. Set theme to dark, then check how it looks. 
3. Change theme to follow system, it's still dark. 
4. Go to settings again and press theme - the client crashes. 

### Expected behaviour
- Not crashing. 

### Actual behaviour
- The client crashes. 

### Environment data
Android version: Android 6, patch level may 5th 2017.

Device model: Lenovo Tab 2 A10-70F

Stock or customized system: Stock

Nextcloud app version: 3.10.0 rc2

Nextcloud server version: 17.0. 2

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to pause activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@ee4640d
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3607)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3562)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3537)
	at android.app.ActivityThread.-wrap13(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1510)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5765)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@ee4640d
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:789)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1200)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:576)
	at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher.onPause(UsbConnectionDispatcher.java:118)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.onActivityPaused(SecurityKeyManager.java:289)
	at android.app.Application.dispatchActivityPaused(Application.java:223)
	at android.app.Activity.onPause(Activity.java:1475)
	at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:418)
	at com.owncloud.android.ui.activity.BaseActivity.onPause(BaseActivity.java:96)
	at com.owncloud.android.ui.activity.FileActivity.onPause(FileActivity.java:230)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onPause(FileDisplayActivity.java:1286)
	at android.app.Activity.performPause(Activity.java:6420)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1322)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3589)
	... 10 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100052
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Lenovo
Device: A10-70F
Model: Lenovo TAB 2 A10-70F
Id: MRA58K
Product: LenovoTAB2A10-70F

************ FIRMWARE ************
SDK: 23
Release: 6.0
Incremental: A10-70F_S000216_170601_ROW

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@adrianvg thanks for the report. The posted error seems unrelated to the theme change but rather related to the hardware 2FA, see
```
Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@ee4640d
```

any ideas @tobiasKaminsky @dschuermann  ?

**Comment by adrianvg** [comment]
Thanks for the feedback!
When you write 2FA, do you mean this wrt logging in to my Nextcloud server?
I don't have 2FA activated there, so don't quite see why that would be a problem.

**Comment by AndyScherzinger** [comment]
I mean as in a hardware (usb/nfc) key connected to your phone

**Comment by adrianvg** [comment]
Thank you. I'm sorry, but I'm a bit out of my league here and I'm not a developen. Just wanted to report the error as I signed up to test the beta syn clients.
Is there anything I can do to help you with this problem?

I don't have any USB or NFC dongles, keys or anything connected to this tablet.
When I got this error I had just updated the Nextcloud Sync Client.

**Comment by AndyScherzinger** [comment]
@adrianvg Thanks for all the details and comments and also: nothing to be sorry for! We are happy about you making an effort in testing the beta release and reporting back issues you found ❤️ 

> Is there anything I can do to help you with this problem?

Not that I am aware of at the moment, still looking forward to feedback from @tobiasKaminsky and @dschuermann

**Comment by dschuermann** [comment]
@AndyScherzinger I am trying to free up some time this week to check out the issue.

**Comment by AndyScherzinger** [comment]
Thanks a lot @dschuermann, this is highly appreciated 🥇

**Comment by adrianvg** [comment]
Cool, thanks guys, you're doing a great job!

**Comment by AndyScherzinger** [comment]
@dschuermann any chance you could have a look at this issue? ❤️ Highly appreciate your input/feedback
