### ISSUE TITLE
Crashed after initial setup

### ISSUE THREAD

**Issue by gisforgirard** [nextcloud/android#5164]
************ CAUSE OF ERROR ************

java.lang.ArrayIndexOutOfBoundsException: length=366; index=-1
	at java.util.ArrayList.get(ArrayList.java:439)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.getItem(OCFileListAdapter.java:677)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.onBindViewHolder(OCFileListAdapter.java:332)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
	at android.view.View.layout(View.java:19728)
	at android.view.ViewGroup.layout(ViewGroup.java:6149)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
	at android.view.View.layout(View.java:19728)
	at android.view.ViewGroup.layout(ViewGroup.java:6149)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
	at android.view.View.layout(View.java:19728)
	at android.view.ViewGroup.layout(ViewGroup.java:6149)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1084)
	at android.view.View.layout(View.java:19728)
	at android.view.ViewGroup.layout(ViewGroup.java:6149)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19728)
	at android.view.ViewGroup.layout(ViewGroup.java:6149)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1780)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1546)
	at android.view.View.layout(View.java:19728)
	at android.view.ViewGroup.layout(ViewGroup.java:6149)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:19728)
	at android.view.ViewGroup.layout(ViewGroup.java:6149)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:19728)
	at android.view.ViewGroup.layout(ViewGroup.java:6149)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19728)
	at android.view.ViewGroup.layout(ViewGroup.java:6149)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19728)
	at android.view.ViewGroup.layout(ViewGroup.java:6149)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19728)
	at android.view.ViewGroup.layout(ViewGroup.java:6149)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:19728)
	at android.view.ViewGroup.layout(ViewGroup.java:6149)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:786)
	at android.view.View.layout(View.java:19728)
	at android.view.ViewGroup.layout(ViewGroup.java:6149)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2604)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2313)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1465)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7233)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:979)
	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
	at android.view.Choreographer.doFrame(Choreographer.java:726)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6651)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20200108
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: lge
Device: cv7a
Model: LM-Q710(FGN)
Id: OPM1.171019.019
Product: cv7a_lao_com

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: 192741036e6d2

**Comment by gisforgirard** [comment]
And crashes every time i try and start the app now 

************ CAUSE OF ERROR ************

java.lang.ArrayIndexOutOfBoundsException: length=366; index=-1
	at java.util.ArrayList.get(ArrayList.java:439)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.getItem(OCFileListAdapter.java:677)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.onBindViewHolder(OCFileListAdapter.java:332)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
	at android.view.View.layout(View.java:19728)
	at android.view.ViewGroup.layout(ViewGroup.java:6149)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
	at android.view.View.layout(View.java:19728)
	at android.view.ViewGroup.layout(ViewGroup.java:6149)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
	at android.view.View.layout(View.java:19728)
	at android.view.ViewGroup.layout(ViewGroup.java:6149)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1084)
	at android.view.View.layout(View.java:19728)
	at android.view.ViewGroup.layout(ViewGroup.java:6149)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19728)
	at android.view.ViewGroup.layout(ViewGroup.java:6149)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1780)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1546)
	at android.view.View.layout(View.java:19728)
	at android.view.ViewGroup.layout(ViewGroup.java:6149)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:19728)
	at android.view.ViewGroup.layout(ViewGroup.java:6149)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:19728)
	at android.view.ViewGroup.layout(ViewGroup.java:6149)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19728)
	at android.view.ViewGroup.layout(ViewGroup.java:6149)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19728)
	at android.view.ViewGroup.layout(ViewGroup.java:6149)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19728)
	at android.view.ViewGroup.layout(ViewGroup.java:6149)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:19728)
	at android.view.ViewGroup.layout(ViewGroup.java:6149)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:786)
	at android.view.View.layout(View.java:19728)
	at android.view.ViewGroup.layout(ViewGroup.java:6149)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2604)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2313)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1465)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7233)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:979)
	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
	at android.view.Choreographer.doFrame(Choreographer.java:726)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6651)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20200108
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: lge
Device: cv7a
Model: LM-Q710(FGN)
Id: OPM1.171019.019
Product: cv7a_lao_com

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: 192741036e6d2

**Comment by tobiasKaminsky** [comment]
Can you retest this with latest dev version?

**Comment by gisforgirard** [comment]
Now it crashes twice, once when it crashes and again when it tries to pull
up the submit crash report dialog... My server is running nextcloud 18RC1
if it means anything

**Comment by tobiasKaminsky** [comment]
Strange.
2020 01 08 is not the latest one.
Do you get it via Fdroid?

**Comment by gisforgirard** [comment]
yeah, tested with 20200110
