### ISSUE TITLE
The client crashes every time when trying to change the remote directory under automatic upload

### ISSUE THREAD

**Issue by GLassnig** [nextcloud/android#5165]
### Actual behaviour
The client crashes every time when trying to change the remote directory under automatic upload
### Environment data

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100052
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Lenovo
Device: TB2-X30F
Model: Lenovo TB2-X30F
Id: LenovoTB2-X30F
Product: TB2-X30F

************ FIRMWARE ************
SDK: 23
Release: 6.0.1
Incremental: TB2-X30F_S000113_160816_ROW

Nextcloud app version: 3.10.0 RC2

Nextcloud server version: 17.0.2

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setVisible(boolean)' on a null object reference
	at com.owncloud.android.ui.fragment.OCFileListFragment.onPrepareOptionsMenu(OCFileListFragment.java:796)
	at androidx.fragment.app.Fragment.performPrepareOptionsMenu(Fragment.java:2723)
	at androidx.fragment.app.FragmentManagerImpl.dispatchPrepareOptionsMenu(FragmentManagerImpl.java:2743)
	at androidx.fragment.app.FragmentController.dispatchPrepareOptionsMenu(FragmentController.java:398)
	at androidx.fragment.app.FragmentActivity.onPreparePanel(FragmentActivity.java:489)
	at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:2857)
	at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
	at androidx.appcompat.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:522)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by GLassnig** [comment]
This problem has already been reported.
