### ISSUE TITLE
Crash upon entering Photos tab (OnePlus 7T)

### ISSUE THREAD

**Issue by kzfoxx** [nextcloud/android#5166]
### Steps to reproduce
1. Launch Nextcloud Android app
2. Tap the three-line icon on upper left corner
3. Tap Photos

### Expected behaviour
- Entering photos gallery on app

### Actual behaviour
- App crashes (Nextcloud has stopped)

### Environment data
Android version: 10
Oxygen OS 10.0.7.HD65AA

Device model: 
OnePlus 7T

Stock or customized system:
Stock

Nextcloud app version:
3.10.0 RC2
(Happens to stable release as well)

Nextcloud server version:
16.0.5.1
(Server side should be fine. Tried web browser and iOS app and both entered gallery normally)

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRichWorkspace()' on a null object reference
	at com.owncloud.android.ui.fragment.OCFileListFragment.onPrepareOptionsMenu(OCFileListFragment.java:796)
	at androidx.fragment.app.Fragment.performPrepareOptionsMenu(Fragment.java:2723)
	at androidx.fragment.app.FragmentManagerImpl.dispatchPrepareOptionsMenu(FragmentManagerImpl.java:2743)
	at androidx.fragment.app.FragmentController.dispatchPrepareOptionsMenu(FragmentController.java:398)
	at androidx.fragment.app.FragmentActivity.onPreparePanel(FragmentActivity.java:489)
	at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:2857)
	at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
	at androidx.appcompat.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:522)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1163)
	at android.view.Choreographer.doCallbacks(Choreographer.java:986)
	at android.view.Choreographer.doFrame(Choreographer.java:894)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1148)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100052
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus7T
Model: HD1900
Id: 
Product: OnePlus7T

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 1912060025

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
closing in favor of #5168 - cc @tobiasKaminsky needs fixing for 3.10
