### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by 4n3y3** [nextcloud/android#5174]
### Steps to reproduce
1.installed nextcloud app
2. Enter the server address
3. Crashed

### Expected behaviour
- Authorize login

### Actual behaviour
- crashed

### Environment data
Android version: 9

Device model:Huawei  p20 lite

Stock or customized system: custom rom.(Omni 9.2 from openkirin

Nextcloud app version: 

Nextcloud server version:

************ CAUSE OF ERROR ************

android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class android.webkit.WebView
Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class android.webkit.WebView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
	at com.owncloud.android.authentication.AuthenticatorActivity.onGetServerInfoFinish(AuthenticatorActivity.java:1310)
	at com.owncloud.android.authentication.AuthenticatorActivity.onRemoteOperationFinish(AuthenticatorActivity.java:1209)
	at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:727)
	at com.owncloud.android.services.-$$Lambda$OperationsService$2BVgsxDpOpa4JqgzeD7OGZBLSiI.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:471)
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:251)
	at android.webkit.WebView.getFactory(WebView.java:2424)
	at android.webkit.WebView.ensureProviderCreated(WebView.java:2419)
	at android.webkit.WebView.setOverScrollMode(WebView.java:2484)
	at android.view.View.<init>(View.java:4807)
	at android.view.View.<init>(View.java:4948)
	at android.view.ViewGroup.<init>(ViewGroup.java:659)
	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
	at android.webkit.WebView.<init>(WebView.java:403)
	at android.webkit.WebView.<init>(WebView.java:348)
	at android.webkit.WebView.<init>(WebView.java:331)
	at android.webkit.WebView.<init>(WebView.java:318)
	... 25 more
Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:376)
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:439)
	... 37 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWANE
Model: ANE-AL00
Id: PQ3A.190705.003
Product: ANE-AL00

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: eng.chris.20190721.140716

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
duplicate of #4943

**Comment by AndyScherzinger** [comment]
this is unfortunately another issue, no Chrome/WebView on the Phone.

**Comment by AndyScherzinger** [comment]
@4n3y3 can you check if you have https://play.google.com/store/apps/details?id=com.google.android.webview installed or if this maybe updated right when you openend the app, since the WebView should be part of Android 5+

**Comment by 4n3y3** [comment]
Thanks.. That worked 😁
