### ISSUE TITLE
App crashes when attempting to move a file

### ISSUE THREAD

**Issue by kotecky** [nextcloud/android#5204]
### Steps to reproduce
1. Tap on "move" for one or more files
2. Crash

### Expected behaviour
Files moved 

### Actual behaviour
App crashes 

### Environment data
Android version: 8

Device model: Sony Xperia x compact 

Stock or customized system: stock 

Nextcloud app version:3.1. Rc2

Nextcloud server version:? 

### Logs

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setVisible(boolean)' on a null object reference
	at com.owncloud.android.ui.fragment.OCFileListFragment.onPrepareOptionsMenu(OCFileListFragment.java:796)
	at androidx.fragment.app.Fragment.performPrepareOptionsMenu(Fragment.java:2723)
	at androidx.fragment.app.FragmentManagerImpl.dispatchPrepareOptionsMenu(FragmentManagerImpl.java:2743)
	at androidx.fragment.app.FragmentController.dispatchPrepareOptionsMenu(FragmentController.java:398)
	at androidx.fragment.app.FragmentActivity.onPreparePanel(FragmentActivity.java:489)
	at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:2857)
	at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
	at androidx.appcompat.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:522)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:251)
	at android.app.ActivityThread.main(ActivityThread.java:6589)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100052
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Sony
Device: F5321
Model: F5321
Id: 34.4.A.2.118
Product: F5321

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: 1631208121

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Hi @kotecky, thanks for reporting this issue. The fix is already in place and has been released with RC3, so closing the issue.
