### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by nc82** [nextcloud/android#5217]
### Steps to reproduce
1. Share a file
2. 
3. 

### Expected behaviour
- Tell us what should happen
Use of other software

### Actual behaviour
- Tell us what happens
Crash
### Environment data
Android version:
9
Device model: 
LG G6
Stock or customized system:
Stock
Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```

```************ CAUSE OF ERROR ************

kotlin.UninitializedPropertyAccessException: lateinit property response has not been initialized
	at com.nextcloud.common.OkHttpMethodBase.releaseConnection(OkHttpMethodBase.kt:68)
	at com.owncloud.android.lib.resources.activities.GetActivitiesRemoteOperation.run(GetActivitiesRemoteOperation.java:158)
	at com.nextcloud.common.NextcloudClient.execute(NextcloudClient.kt:63)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$fetchAndSetData$5$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:331)
	at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$N7POe6TZvoGcuV2qP-niPxY_7t4.run(Unknown Source:12)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20191221
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: lge
Device: lucye
Model: LG-H870DS
Id: PKQ1.190522.001
Product: lucye_global_com

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 192632011c72d

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@nc82 please update the app, you are using `20191221` which is very, very old ;)
