### ISSUE TITLE
Crash on open document

### ISSUE THREAD

**Issue by samtuke** [nextcloud/android#5240]
Pasting crash report here. Hope its useful. I tried to open a markdown file locally on Android from the NC interface. Possibly there were unsynced changes, though they should have been synced as the device had a working Internet connection. 

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.widget.SearchView.setOnQueryTextListener(androidx.appcompat.widget.SearchView$OnQueryTextListener)' on a null object reference
	at com.owncloud.android.ui.preview.PreviewTextFragment$TextLoadAsyncTask.onPostExecute(PreviewTextFragment.java:375)
	at com.owncloud.android.ui.preview.PreviewTextFragment$TextLoadAsyncTask.onPostExecute(PreviewTextFragment.java:308)
	at android.os.AsyncTask.finish(AsyncTask.java:692)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:709)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6517)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: hwbeethoven
Model: BTV-DL09
Id: HUAWEIBEETHOVEN-DL09
Product: BEETHOVEN

************ FIRMWARE ************
SDK: 24
Release: 7.0
Incremental: C100B311

**Comment by AndyScherzinger** [comment]
Hi @samtuke  and thanks for the report. Does this crash still occur with the latest stable release (3.10.0) since @tobiasKaminsky rewrote/reorganized this part of the code?
