### ISSUE TITLE
App 3.10.0 crashes when tryimg to share a folder

### ISSUE THREAD

**Issue by elpraga** [nextcloud/android#5241]
### Steps to reproduce
1. Try to share a folder with a user
2. app crashes
3. 

### Expected behaviour
- app doesn' crash

### Actual behaviour
- Tell us what happens

### Environment data
Android version: 9.0

Device model: 

Stock or customized system:

Nextcloud app version:
3.10.0
Nextcloud server version:
18.0
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@elpraga can you provide a logcat for the crash?

**Comment by elpraga** [comment]
************ CAUSE OF ERROR ************

java.net.SocketTimeoutException: failed to connect to cloud.tomaskaluza.net/92.59.3.107 (port 443) from /192.168.1.101 (port 39316) after 10000ms
	at libcore.io.IoBridge.connectErrno(IoBridge.java:185)
	at libcore.io.IoBridge.connect(IoBridge.java:129)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:621)
	at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:73)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:167)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
	at okhttp3.RealCall.execute(RealCall.java:93)
	at com.nextcloud.common.OkHttpMethodBase.execute(OkHttpMethodBase.kt:126)
	at com.nextcloud.common.NextcloudClient.execute(NextcloudClient.kt:67)
	at com.owncloud.android.lib.resources.activities.GetActivitiesRemoteOperation.run(GetActivitiesRemoteOperation.java:131)
	at com.nextcloud.common.NextcloudClient.execute(NextcloudClient.kt:63)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$fetchAndSetData$5$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:331)
	at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$N7POe6TZvoGcuV2qP-niPxY_7t4.run(Unknown Source:12)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: xiaomi
Device: lavender
Model: Redmi Note 7
Id: PKQ1.180904.001
Product: lavender_eea

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: V11.0.4.0.PFGEUXM

**Comment by elpraga** [comment]
Here its @AndyScherzinger - a fresh one. It crashes every time I start looking for (typing in the name of) the user I want to share with.

**Comment by AndyScherzinger** [comment]
Hi @elpraga is anything else working? Just asking because the log states it is a socket timeout :(

cc @tobiasKaminsky

**Comment by elpraga** [comment]
Yes, @AndyScherzinger everything else is working as expected - upload, download, remote edit...

**Comment by elpraga** [comment]
@AndyScherzinger  were you able to reproduce the crash?

**Comment by AndyScherzinger** [comment]
Nope, works like a charm for me :/

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky for the timeout issue(s)

**Comment by tobiasKaminsky** [comment]
This should be fixed with latest version, if not please test 3.11 RC3 via Play beta program.
