### ISSUE TITLE
NextCloud notes

### ISSUE THREAD

**Issue by IDizzyPirate** [nextcloud/android#5253]
### Steps to reproduce
1. Signing in to Nextcloud notes
2. Shows the error that sync is failing and asking me to check if note sync is enabled online.

### Expected behaviour
- The notes should sync when created.
### Actual behaviour
- Fails to sync

### Environment data
Android version: 

Device model: Samsung M30s

Stock or customized system: OneUI

Nextcloud notes app version: 2.4.8

#### Web server error log
Bug
```
App Version: 2.4.8
App Version Code: 71
Files App Version Code: 30090290

---

OS Version: 4.14.62-17283099(M307FXXU2ASL2)
OS API Level: 28
Device: m30s
Model (and Product): SM-M307F (m30sdd)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 302
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:155)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:194)
	at it.niedermann.owncloud.notes.persistence.NotesClient.putNote(NotesClient.java:134)
	at it.niedermann.owncloud.notes.persistence.NotesClient.createNote(NotesClient.java:145)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pushLocalChanges(NoteServerSyncHelper.java:323)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:289)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:262)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: 
	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:433)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:134)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:117)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:134)
	at android.os.Binder.execTransact(Binder.java:739)
com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 302
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:155)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:194)
	at it.niedermann.owncloud.notes.persistence.NotesClient.getNotes(NotesClient.java:125)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pullRemoteChanges(NoteServerSyncHelper.java:363)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:291)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:262)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: 
	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:433)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:134)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:117)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:134)
	at android.os.Binder.execTransact(Binder.java:739)

```

**Comment by AndyScherzinger** [comment]
cc @stefan-niedermann and @David-Development / @tobiasKaminsky

**Comment by stefan-niedermann** [comment]
Seems to be related / identical to https://github.com/stefan-niedermann/nextcloud-notes/issues/682

**Comment by stefan-niedermann** [comment]
Are you also using `traefik`?

**Comment by IDizzyPirate** [comment]
@stefan-niedermann The thread doesn't really solve the problem too.

**Comment by tobiasKaminsky** [comment]
@IDizzyPirate 
can you give us more details on your setup?
Do you use redirections, eg. from http to https, or from cloud.domain.com to domain.com/cloud or such?

Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by IDizzyPirate** [comment]
@tobiasKaminsky I have sent you a mail with some screenshots. If you need I can give you this account as there is nothing in this account also. It's a new account with no purpose.

**Comment by tobiasKaminsky** [comment]
For real debugging I need some credentials.

**Comment by IDizzyPirate** [comment]
@tobiasKaminsky I have sent you over email.

**Comment by tobiasKaminsky** [comment]
So, as error message indicates correctly: notes app is missing on server.
App "quick notes" is not the same same as "notes"'

Please ask your server admin to enable "notes" and then it should work.

**Comment by IDizzyPirate** [comment]
The fun part is I only created the account. No one did. It would be of great help if you direct me how to do that. @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
As said, you need an admin to enable the app for you: https://apps.nextcloud.com/apps/notes

**Comment by IDizzyPirate** [comment]
@tobiasKaminsky  any idea where I can get hold of an admin.

**Comment by tobiasKaminsky** [comment]
@IDizzyPirate conact your provider. 
They should have some sort of contact.
