### ISSUE TITLE
Crash when deleting account

### ISSUE THREAD

**Issue by mercurytoxic** [nextcloud/android#5263]
************ CAUSE OF ERROR ************

java.lang.NullPointerException
	at com.nextcloud.java.util.Optional.<init>(Optional.java:99)
	at com.nextcloud.java.util.Optional.of(Optional.java:113)
	at com.nextcloud.client.account.UserAccountManagerImpl.getUser(UserAccountManagerImpl.java:230)
	at com.owncloud.android.ui.activity.BaseActivity.getUser(BaseActivity.java:227)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2561)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1514)
	at android.app.Activity.performStart(Activity.java:7838)
	at android.app.Activity.performRestart(Activity.java:7927)
	at android.app.ActivityThread.handleWindowVisibility(ActivityThread.java:4846)
	at android.app.servertransaction.WindowVisibilityItem.execute(WindowVisibilityItem.java:39)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20200110
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus6T
Model: ONEPLUS A6010
Id: QKQ1.190716.003
Product: OnePlus6T

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 1912142009

**Comment by AndyScherzinger** [comment]
@mercurytoxic did you have one or more than one user at the the of the removal?

cc @tobiasKaminsky @ezaquarii since I remember one of you folks fixing an issue regarding account deletions. (at least I think I do remember)

**Comment by mercurytoxic** [comment]
Only had one user.

**Comment by AndyScherzinger** [comment]
@mercurytoxic does this still happen with actual (dev) builds (or 3.11 RC1)?

**Comment by mercurytoxic** [comment]
Sorry this happened back in Jan, just tried with playstore version 3.10.1 and with f-droid dev and can't reproduce.

**Comment by tobiasKaminsky** [comment]
Thanks, then I will close this, but feel free to re-open if needed.
