### ISSUE TITLE
Android App Error

### ISSUE THREAD

**Issue by JonasPfz** [nextcloud/android#5310]
### Steps to reproduce
1. I tried to download a file from my android nextcloud app

### Expected behaviour
- Tell us what should happen

Open the file 

### Actual behaviour
- Tell us what happens

Crash report, not opening the file

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.net.ConnectException: Failed to connect to cloud.pfitznerconsulting.de/85.214.35.97:443
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:249)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:167)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
	at okhttp3.RealCall.execute(RealCall.java:93)
	at com.nextcloud.common.OkHttpMethodBase.execute(OkHttpMethodBase.kt:126)
	at com.nextcloud.common.NextcloudClient.execute(NextcloudClient.kt:67)
	at com.owncloud.android.lib.resources.activities.GetActivitiesRemoteOperation.run(GetActivitiesRemoteOperation.java:131)
	at com.nextcloud.common.NextcloudClient.execute(NextcloudClient.kt:63)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$fetchAndSetData$5$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:331)
	at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$N7POe6TZvoGcuV2qP-niPxY_7t4.run(Unknown Source:12)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.net.ConnectException: failed to connect to cloud.pfitznerconsulting.de/85.214.35.97 (port 443) from /10.181.174.42 (port 44578) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
	at libcore.io.IoBridge.isConnected(IoBridge.java:278)
	at libcore.io.IoBridge.connectErrno(IoBridge.java:187)
	at libcore.io.IoBridge.connect(IoBridge.java:129)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:621)
	at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:73)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
	... 24 more
Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
	at libcore.io.IoBridge.isConnected(IoBridge.java:267)
	... 34 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: tucana
Model: Mi Note 10
Id: PKQ1.190302.001
Product: tucana_eea

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: V11.0.13.0.PFDEUXM

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
--> `isConnected failed: ECONNREFUSED (Connection refused)`

My guess is the server is missconfigured (the browser working jjust fine isn't an indicator, that the server is configured correctly).

cc @tobiasKaminsky

**Comment by JonasPfz** [comment]
Hi @AndyScherzinger,

thanks for your answer!

I can see the following errors:

 Sicherheits- & Einrichtungswarnungen

Für die Sicherheit und Performance Deiner Instanz ist es wichtig, dass alles richtig konfiguriert ist. Um Dir dabei zu helfen, führen wir einige automatische Prüfungen durch. Weitere Informationen kannst Du der verlinkten Dokumentation entnehmen.
Es gibt einige Fehler bei Deiner Systemkonfiguration.

    Einige Dateien haben die Integritätsprüfung nicht bestanden. Weiterführende Informationen befinden sich in unserer Dokumentation. (Liste der ungültigen Dateien… / Erneut analysieren…)

    Dein Web-Server ist nicht richtig eingerichtet um "/.well-known/caldav" aufzulösen. Weitere Informationen findest Du in der Dokumentation.
    Dein Web-Server ist nicht richtig eingerichtet um "/.well-known/carddav" aufzulösen. Weitere Informationen findest Du in der Dokumentation.
    Es wurde kein PHP-Memory-Cache konfiguriert. Zur Erhöhung der Leistungsfähigkeit kann ein Memory-Cache konfiguriert werden. Weitere Informationen findest Du in der Dokumentation.
    In der Datenbank fehlen einige Indizes. Auf Grund der Tatsache, dass das Hinzufügen von Indizes in großen Tabellen einige Zeit in Anspruch nehmen kann, wurden diese nicht automatisch erzeugt. Durch das Ausführen von "occ db:add-missing-indices" können die fehlenden Indizes manuell hinzugefügt werden, während die Instanz weiter läuft. Nachdem die Indizes hinzugefügt wurden, sind Anfragen auf die Tabellen normalerweise schneller.
        Fehlender Index "owner_index" in der Tabelle "oc_share".
        Fehlender Index "initiator_index" in der Tabelle "oc_share".
        Fehlender Index "fs_mtime" in der Tabelle "oc_filecache".
        Fehlender Index "twofactor_providers_uid" in der Tabelle "oc_twofactor_providers".
        Fehlender Index "version" in der Tabelle "oc_whats_new".
        Fehlender Index "cards_abid" in der Tabelle "oc_cards".
        Fehlender Index "cards_prop_abid" in der Tabelle "oc_cards_properties".
    Bei einigen Spalten in der Datenbank fehlt eine Konvertierung in big int. Aufgrund der Tatsache, dass das Ändern von Spaltentypen bei großen Tabellen einige Zeit dauern kann, wurden sie nicht automatisch geändert. Durch Ausführen von "occ db:convert-filecache-bigint" können diese ausstehenden Änderungen manuell übernommen werden. Diese Operation muss ausgeführt werden, während die Instanz offline ist. Weitere Einzelheiten findest Du auf der zugehörigen Dokumentationsseite.
        filecache.mtime
        filecache.storage_mtime
        mounts.storage_id
        mounts.root_id
        mounts.mount_id

Bitte überprüfe noch einmal die Installationsanleitungen ↗ und kontrolliere das Protokoll auf mögliche Fehler oder Warnungen.

Überprüfe die Sicherheit Deiner Nextcloud über unseren Sicherheitsscanner ↗.

Kind regards,
Jonas

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky any ideas?

**Comment by tobiasKaminsky** [comment]
Can you try out our dev version (you can install it in parallel) and give us feedback:
https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#dev-release

**Comment by tobiasKaminsky** [comment]
@JonasPfz can you try dev version?

**Comment by JonasPfz** [comment]
nextcloud-dev-20200225.apk | 2020-02-25 02:38
-- | --


Yes, it works now

**Comment by JonasPfz** [comment]
@tobiasKaminsky

**Comment by JonasPfz** [comment]
@tobiasKaminsky current nextcloud android app V 3.12.1 is still not working.

**Comment by AndyScherzinger** [comment]
@JonasPfz can you post an updated error log with the stack trace since the referenced fix shipped with 3.11

**Comment by JonasPfz** [comment]
@AndyScherzinger I only get the notification "Download failed" but don't see any error log like last time

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky any idea how to collect more details/logs?

**Comment by JonasPfz** [comment]
![Screenshot_2020-08-10-23-20-25-915_com nextcloud client](https://user-images.githubusercontent.com/60294917/89832848-3f167080-db60-11ea-8990-6e96e72a69db.jpg)

**Comment by JonasPfz** [comment]
Still not working..

**Comment by JonasPfz** [comment]
@tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
I still think this is caused by a misconfigured server…

Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat
