### ISSUE TITLE
SQLiteException - duplicate column name

### ISSUE THREAD

**Issue by FlorianKrammel** [nextcloud/android#5316]
### Steps to reproduce
1. Happens randomly in background (I think on media access) or
2. start nextcloud
after update from 20200108 to 20200110

### Expected behaviour
- the app should be silent in background
- the app should start accordingly
- the app should update it self accordinglx

### Actual behaviour
1) If I access other apps nextcloud starts in foreground and dies. This hangs in an infinite loop. I have to press the home button an kill nextcloud to get access to the phone. 
2) same if I start the app directly

- direct Downgrade not possible 
- cleared cache, data not

### Environment data
Android version:
Android 8.1 / LineageOS 15.1
Device model: 
Xiaomi Mi Mix 2
Stock or customized system:

Nextcloud app version:
20200110 (f-droid.org)

#### logcat error log
```
01-26 11:09:30.637 29672:29672 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: com.nextcloud.android.beta, PID: 29672
: Unable to create application com.owncloud.android.MainApp: android.database.sqlite.SQLiteException: duplicate column name: rich_workspace (code 1): , while compiling: ALTER TABLE filelist ADD COLUMN rich_workspace TEXT
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
	at android.app.ActivityThread.-wrap1(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: android.database.sqlite.SQLiteException: duplicate column name: rich_workspace (code 1): , while compiling: ALTER TABLE filelist ADD COLUMN rich_workspace TEXT
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:890)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:501)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1753)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1682)
	at com.owncloud.android.providers.FileContentProvider$DataBaseHelper.onUpgrade(FileContentProvider.java:2092)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:338)
	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:262)
	at com.owncloud.android.providers.FileContentProvider.query(FileContentProvider.java:471)
	at android.content.ContentProvider.query(ContentProvider.java:1057)
	at android.content.ContentProvider.query(ContentProvider.java:1149)
	at android.content.ContentProvider$Transport.query(ContentProvider.java:241)
	at android.content.ContentResolver.query(ContentResolver.java:754)
	at android.content.ContentResolver.query(ContentResolver.java:704)
	at android.content.ContentResolver.query(ContentResolver.java:662)
	at com.owncloud.android.datamodel.UploadsStorageManager.getUploads(UploadsStorageManager.java:289)
	at com.owncloud.android.datamodel.UploadsStorageManager.getFailedUploads(UploadsStorageManager.java:368)
	at com.owncloud.android.utils.FilesSyncHelper.restartJobsIfNeeded(FilesSyncHelper.java:194)
	at com.owncloud.android.MainApp.initSyncOperations(MainApp.java:492)
	at com.owncloud.android.MainApp.onCreate(MainApp.java:309)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
	... 8 more

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky fixed this already via #5267 - please update to the latest version
