### ISSUE TITLE
Crash when deleting locally only

### ISSUE THREAD

**Issue by MightyCreak** [nextcloud/android#5318]
### Steps to reproduce
1. From a folder shared with you
2. Select a (video) file (60 MB)
3. Select delete locally only

### Expected behaviour
- Remove file from my device

### Actual behaviour
- The app crash

### Environment data
Android version: 10 (OxygenOS 10.3.0)

Device model: OnePlus 6T

Stock or customized system: stock

Nextcloud app version: 3.9.2

Nextcloud server version: 17.0.2

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.OutOfMemoryError
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1129)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:959)
	at android.media.ThumbnailUtils.transform(ThumbnailUtils.java:521)
	at android.media.ThumbnailUtils.extractThumbnail(ThumbnailUtils.java:413)
	at android.media.ThumbnailUtils.extractThumbnail(ThumbnailUtils.java:388)
	at com.owncloud.android.datamodel.ThumbnailsCacheManager.addThumbnailToCache(ThumbnailsCacheManager.java:191)
	at com.owncloud.android.datamodel.ThumbnailsCacheManager.generateResizedImage(ThumbnailsCacheManager.java:1196)
	at com.owncloud.android.operations.RemoveFileOperation.run(RemoveFileOperation.java:95)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:138)
	at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:87)
	at com.owncloud.android.services.OperationsService$ServiceHandler.nextOperation(OperationsService.java:463)
	at com.owncloud.android.services.OperationsService$ServiceHandler.handleMessage(OperationsService.java:417)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus6T
Model: ONEPLUS A6013
Id: QKQ1.190716.003
Product: OnePlus6T

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 1912142009
```

**Comment by MightyCreak** [comment]
This bug report is still relevant.

**Comment by AndyScherzinger** [comment]
@MightyCreak are you still running 3.9.2 or a newer version?

**Comment by MightyCreak** [comment]
You're right, on 3.10.1 it seems fixed! Thanks!

**Comment by AndyScherzinger** [comment]
Glad to hear that, so closing it for now. 👍
