### ISSUE TITLE
nextcloud 3.10

### ISSUE THREAD

**Issue by wfue-20** [nextcloud/android#5331]
### Steps to reproduce
1************ CAUSE OF ERROR ************

java.net.SocketTimeoutException: timeout
	at okio.SocketAsyncTimeout.newTimeoutException(Okio.kt:142)
	at okio.AsyncTimeout.exit$okio(AsyncTimeout.kt:203)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:163)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:449)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:333)
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
	at okhttp3.RealCall.execute(RealCall.java:93)
	at com.nextcloud.common.OkHttpMethodBase.execute(OkHttpMethodBase.kt:126)
	at com.nextcloud.common.NextcloudClient.execute(NextcloudClient.kt:67)
	at com.owncloud.android.lib.resources.activities.GetActivitiesRemoteOperation.run(GetActivitiesRemoteOperation.java:131)
	at com.nextcloud.common.NextcloudClient.execute(NextcloudClient.kt:63)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$fetchAndSetData$5$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:331)
	at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$N7POe6TZvoGcuV2qP-niPxY_7t4.run(lambda)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.net.SocketException: socket is closed
	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(:com.google.android.gms@19831022@19.8.31 (040700-284611645):8)
	at okio.InputStreamSource.read(Okio.kt:93)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:159)
	... 26 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: MEDION
Device: P1050X
Model: P1050X
Id: NMF27D
Product: P1050X

************ FIRMWARE ************
SDK: 25
Release: 7.1.1
Incremental: 20190816_1638
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Absturz Nextcloud Version3.10

### Environment data
Android version: 7

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@wfue-20 does this happen consistently? Just asking since `socket is closed` point to the server taking too much time to respond.

cc @tobiasKaminsky in case timeouts need to be re-configured with the introduction of okhttp

**Comment by wfue-20** [comment]
S.g. Herr Scherzinger, yes it happened consistently. Because of that, I deinstalled the 3.10 Version and reinstalled 3.9 of December 19. with no similar failures any more!

Shortly after these actions surprisingly the tablet crashed completely, remaining unstartable. 

Consequently I have to change the device, but due to this experience I’ll stay with version 3.9 for the time being.

kind regards

Walter Fürst

**Comment by tobiasKaminsky** [comment]
Can you try out our dev version (you can install it in parallel) and give us feedback:
https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#dev-release

**Comment by tobiasKaminsky** [comment]
@wfue-20 is this still happening with latest dev version?

**Comment by tobiasKaminsky** [comment]
3.11 RC1 is out, can you please test this via gplay beta program?

**Comment by tobiasKaminsky** [comment]
No response, please re-open if if still happens.
