### ISSUE TITLE
Nextcloud App crashs after upgrade to 17

### ISSUE THREAD

**Issue by 12-34-5** [nextcloud/android#5364]
Not similar to Issue #5305
### Steps to reproduce
1. Every time I start the app Nextcloud client (3.10.0) on Samsung Galaxy S9+ immedately the app crash with report CAUSE OF ERROR , no access to Nextcloud server. This status is after I've initialed the access from app to server. In server log I find the authorization for the device Samsung Galaxy. 

--- What happened before the issue ---
2. the same Nextcloud App works fine to server Nextcloud 16.0.7
3. I upgrade manually the server to 17.0.2
4. Access to Nextcloud with webgui (Mozilla, Chrome, Edge etc) and Nextcloud app iOS (iPhone) works fine, like the desktop client too (Windows 10)
5. Only the app Nextcloud client (3.10.0) crashs. Two times app uninstalled und re-installed , no benefice. 

### Actual behaviour
- see point #1

### Environment data

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: star2lte
Model: SM-G965F
Id: xxxx.xxxxxx.xxx
Product: star2ltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G965FXxxxxxxx

Android version:  9

Stock or customized system:

Nextcloud app version: 3.10.0 (January, 17. 2020)

Nextcloud server version: 17.0.2

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
``` this appare after I start the Nextcloud App Android

************ CAUSE OF ERROR ************

java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at com.owncloud.android.ui.adapter.OCFileListAdapter.showFederatedShareAvatar(OCFileListAdapter.java:558)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.onBindViewHolder(OCFileListAdapter.java:433)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
	at android.view.View.layout(View.java:22398)
	at android.view.ViewGroup.layout(ViewGroup.java:6577)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
	at android.view.View.layout(View.java:22398)
	at android.view.ViewGroup.layout(ViewGroup.java:6577)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
	at android.view.View.layout(View.java:22398)
	at android.view.ViewGroup.layout(ViewGroup.java:6577)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
	at android.view.View.layout(View.java:22398)
	at android.view.ViewGroup.layout(ViewGroup.java:6577)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:22398)
	at android.view.ViewGroup.layout(ViewGroup.java:6577)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1801)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1567)
	at android.view.View.layout(View.java:22398)
	at android.view.ViewGroup.layout(ViewGroup.java:6577)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:22398)
	at android.view.ViewGroup.layout(ViewGroup.java:6577)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:22398)
	at android.view.ViewGroup.layout(ViewGroup.java:6577)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:22398)
	at android.view.ViewGroup.layout(ViewGroup.java:6577)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:22398)
	at android.view.ViewGroup.layout(ViewGroup.java:6577)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:22398)
	at android.view.ViewGroup.layout(ViewGroup.java:6577)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:22398)
	at android.view.ViewGroup.layout(ViewGroup.java:6577)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1042)
	at android.view.View.layout(View.java:22398)
	at android.view.ViewGroup.layout(ViewGroup.java:6577)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3363)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2827)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1873)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8478)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6986)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

Thanks for your help 
Bye

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by Shagequi** [comment]
```
        String[] split = user.split("@");
        String userId = split[0];
        String server = split[1];
```

:)

**Comment by conxulta** [comment]
Confirmed, same here either on Samsung then on Oppo

**Comment by 12-34-5** [comment]
Thanks !
I understand the "conflict" in username ... for me Resolved
Thanks again

**Comment by 12-34-5** [comment]
I have appreciated the info, Thanks to Shagequi and conxulta for the reply
