### ISSUE TITLE
crash after login Düring accsess filesystem

### ISSUE THREAD

**Issue by hschraep** [nextcloud/android#5366]
### Steps to reproduce
1. downlod nextcloud app form fdroid
2. Start the APP and login
3. Grant accsess to the filesystem

### Expected behaviour
- Tell us what should happen
APP crashs
### Actual behaviour
- Tell us what happens

### Environment data
Android version:
9
Device model: 

Stock or customized system:
lineage os 16.0
Nextcloud app version:
3.9.2
Nextcloud server version:
17.0.1
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

### Nextcloud app log:
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED flg=0x10 pkg=com.nextcloud.client (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver@5f8a131
at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1401)
at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6718)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=9153, uid=1010109 requires android.permission.BROADCAST_STICKY
at android.os.Parcel.createException(Parcel.java:1950)
at android.os.Parcel.readException(Parcel.java:1918)
at android.os.Parcel.readException(Parcel.java:1868)
at android.app.IActivityManager$Stub$Proxy.unbroadcastIntent(IActivityManager.java:3920)
at android.app.ContextImpl.removeStickyBroadcast(ContextImpl.java:1346)
at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
at com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver.onReceive(FileDisplayActivity.java:1415)
at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1391)
... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
at com.android.server.am.ActivityManagerService.unbroadcastIntent(ActivityManagerService.java:22177)
at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:183)
at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3377)
at android.os.Binder.execTransact(Binder.java:731)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: gts28vewifi
Model: SM-T713
Id: PQ3A.190801.002
Product: gts28vewifixx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: c7b85eec51 
```

**Comment by AndyScherzinger** [comment]
Hi @hschraep, are you by any chance trying to run the app under Android for Work profile? (which isn't supported)

**Comment by hschraep** [comment]
HI @AndyScherzinger , i do not know what i have done no is the app working. i have installed the app under the administrator user and there the app is working. Then i tryed it again under the secound user and now is the app also working. Thanks for you review. rgds hschraep

**Comment by AndyScherzinger** [comment]
Happy to hear everything is working for you again 👍

**Comment by AndyScherzinger** [comment]
Duplicate of #6654
