### ISSUE TITLE
cant open pdf without previous downloading it from TLS1.3 only server

### ISSUE THREAD

**Issue by Cieniek** [nextcloud/android#5394]
### Steps to reproduce
1. Set server to tls 1.3 only
2. try to open remote pdf file in android client
3. 

### Expected behaviour
- not a crash

### Actual behaviour
- client app crashes

### Environment data
Android version:
10
Device model: 
xiaomi mi 9t
Stock or customized system:
tried on both
Nextcloud app version:
Tried both 3.10.0 and 3.10.1 RC1
Nextcloud server version:
same was on 16.x and now on latest stable 17.x
### Logs

************ CAUSE OF ERROR ************

javax.net.ssl.SSLHandshakeException: Handshake failed
	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@20104037@20.1.04 (120400-288960190):38)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:320)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:284)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
	at okhttp3.RealCall.execute(RealCall.java:93)
	at com.nextcloud.common.OkHttpMethodBase.execute(OkHttpMethodBase.kt:126)
	at com.nextcloud.common.NextcloudClient.execute(NextcloudClient.kt:84)
	at com.owncloud.android.lib.resources.activities.GetActivitiesRemoteOperation.run(GetActivitiesRemoteOperation.java:131)
	at com.nextcloud.common.NextcloudClient.execute(NextcloudClient.kt:80)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$fetchAndSetData$5$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:331)
	at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$N7POe6TZvoGcuV2qP-niPxY_7t4.run(Unknown Source:12)
	at java.lang.Thread.run(Thread.java:919)
Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x7e6d9fd048: Failure in SSL library, usually a protocol error
error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION (third_party/openssl/boringssl/src/ssl/tls_record.cc:592 0x7e6d9e7d48:0x00000001)
	at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.google.android.gms.org.conscrypt.NativeSsl.doHandshake(:com.google.android.gms@20104037@20.1.04 (120400-288960190):6)
	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@20104037@20.1.04 (120400-288960190):14)
	... 26 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100151
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: raphael
Model: Mi 9T Pro
Id: QQ1B.200105.004
Product: raphael_eea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: eng.abhish.20200125.124652

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky @ezaquarii since you might have already fixed this via the lib change (to be released)

**Comment by Cieniek** [comment]
I tried latest nigthly client (20200211) and I can cońfirm that this bug doesn't exist in it.

**Comment by tobiasKaminsky** [comment]
Thanks for feedback
