### ISSUE TITLE
Problem report

### ISSUE THREAD

**Issue by kuno09** [nextcloud/android#5410]
android.database.CursorIndexOutOfBoundsException: Index -1 requested, with a size of 3627
	at android.database.AbstractCursor.checkPosition(AbstractCursor.java:460)
	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:74)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:179)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProvider$Transport.delete(ContentProvider.java:347)
	at android.content.ContentResolver.delete(ContentResolver.java:1642)
	at com.owncloud.android.datamodel.FileDataStorageManager.removeFolderInDb(FileDataStorageManager.java:591)
	at com.owncloud.android.datamodel.FileDataStorageManager.removeFolder(FileDataStorageManager.java:566)
	at com.owncloud.android.operations.RefreshFolderOperation.removeLocalFolder(RefreshFolderOperation.java:387)
	at com.owncloud.android.operations.RefreshFolderOperation.checkForChanges(RefreshFolderOperation.java:348)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:224)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:357)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: herolte
Model: SM-G930F
Id: R16NW
Product: heroltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: G930FXXS7ESK1

**Comment by Friptick** [comment]
Please reopen. Suddenly getting this exact problem. **App unusable.**

Small differences:

************ DEVICE INFORMATION ************
Brand: samsung
Device: on7xelte
Model: SM-G610M

************ FIRMWARE ************
SDK: 27
Release: 8.1.0

**Comment by Friptick** [comment]
Fixed by purging app data and reloading certificate. Possibly correlated: several top-level directories had changed names before the issue arose.

Leave closed, you guys seem to have enough on your plate. Thanks for your work.
