### ISSUE TITLE
crash when opening conflicted file

### ISSUE THREAD

**Issue by dbolton** [nextcloud/android#5430]
### Steps to reproduce
1. Create file conflict between phone and server
2. Sync phone
3. Open file with conflict

### Expected behaviour
- no crash

### Actual behaviour
- crash with error report
#### Web server error log
```
Insert your webserver log here

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.widget.SearchView.setOnQueryTextListener(androidx.appcompat.widget.SearchView$OnQueryTextListener)' on a null object reference
	at com.owncloud.android.ui.preview.PreviewTextFragment$TextLoadAsyncTask.onPostExecute(PreviewTextFragment.java:375)
	at com.owncloud.android.ui.preview.PreviewTextFragment$TextLoadAsyncTask.onPostExecute(PreviewTextFragment.java:308)
	at android.os.AsyncTask.finish(AsyncTask.java:755)
	at android.os.AsyncTask.access$900(AsyncTask.java:192)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: beyond1q
Model: SM-G973U
Id: QP1A.190711.020
Product: beyond1qltesq

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G973USQS2CSL1
```

**Comment by tobiasKaminsky** [comment]
From stacktrace it seems that you ar viewing a text file?
Can you verify the steps to reproduce?

**Comment by dbolton** [comment]
I'm no longer able to edit text files to test this. Is this related to OnlyOffice disabling editing on mobile?

**Comment by tobiasKaminsky** [comment]
No, it should not, as we use our own implementation of only office.
Is there an error message?

**Comment by dbolton** [comment]
The message I get trying to edit text files is "Loading takes very long..." After some investigation this seems to only affect some text files. I created two test files today trying to reproduce the problem. Initially I could edit both of them but now one of the test files can not be edited within the NextCloud Android app. Unfortunately I'm still at a loss at figuring out the exact steps that cause all this weirdness.

**Comment by tobiasKaminsky** [comment]
Sorry, no idea.
Can you ask in https://github.com/nextcloud/documentserver_community
As Android is just opening the file in a web view, there is nothing we can do wrong here…
