### ISSUE TITLE
OutOfMemory Killer close Nextcloud App

### ISSUE THREAD

**Issue by icke2063** [nextcloud/android#5433]
### Steps to reproduce
1. Open App
2. Browser to picture folder
3. Open jpg picture (6MB)
4. Rotate tablet/Nest picture

### Expected behaviour
- show jpg picture from nextcloud folder
- rotate pictures when rotate tablet
- do not use much memory on embedded devices

### Actual behaviour
- The app uses to much memory when showing pictures.
In thumbnails view seems all ok, but when open a picture
for viewing the APP gets killed after some seconds.

### Environment data
Android version: 5.1

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### APP log
************ CAUSE OF ERROR ************

java.lang.OutOfMemoryError: Failed to allocate a 37748748 byte allocation with 4194272 free bytes and 33MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:677)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:653)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:691)
	at com.owncloud.android.ui.adapter.DiskLruImageCache.getBitmap(DiskLruImageCache.java:121)
	at com.owncloud.android.datamodel.ThumbnailsCacheManager.getBitmapFromDiskCache(ThumbnailsCacheManager.java:225)
	at com.owncloud.android.ui.preview.PreviewImageFragment.onStart(PreviewImageFragment.java:254)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:2632)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:915)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStart(FragmentManagerImpl.java:2619)
	at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:257)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:551)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
	at com.owncloud.android.ui.activity.DrawerActivity.onStart(DrawerActivity.java:1430)
	at com.owncloud.android.ui.activity.FileActivity.onStart(FileActivity.java:207)
	at com.owncloud.android.ui.preview.PreviewImageActivity.onStart(PreviewImageActivity.java:186)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1244)
	at android.app.Activity.performStart(Activity.java:6108)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2478)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4210)
	at android.app.ActivityThread.access$900(ActivityThread.java:178)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1476)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5631)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Z90
Device: Z90
Model: Z90
Id: LMY47I
Product: Z90

************ FIRMWARE ************
SDK: 22
Release: 5.1
Incremental: vKB074L
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
How much ram does this have?

**Comment by ph818** [comment]
I also get this when trying to open a very large video. Could nextcloud check and realize that it doesn't have enough memory before trying to open it?

Currently every time this happens I have to ssh and restart apache2.

I am running on a raspberry pi.

**Comment by tobiasKaminsky** [comment]
This out of memory happens on Android/mobile phone.
As you say that you have to restart apache, this is then a server bug/problem.
Please report it there.
