### ISSUE TITLE
Crash when auto uploading camera roll from android pie

### ISSUE THREAD

**Issue by wildjames** [nextcloud/android#5448]
### Steps to reproduce
1. Fresh install of nextcloud on a raspberry pi 3
2. SSL via cloudflare
3. Access through the internet, NOT LAN!

### Expected behaviour
- pretty much not what happened

### Actual behaviour
- immediate crash

### Environment data
Android version: pie

#### phone log report
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
	at com.owncloud.android.ui.dialog.CreateFolderDialogFragment.onClick(CreateFolderDialogFragment.java:140)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6882)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: raphael
Model: Mi 9T Pro
Id: PKQ1.181121.001
Product: raphael_eea

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: V10.3.4.0.PFKEUXM
```

**Comment by AndyScherzinger** [comment]
@wildjames still needs more info: seems related to #4792 while the stack trace shows that the app crashed when trying to create a new folder (still the error doesn't say when/where). Can you elaborate on this?

**Comment by wildjames** [comment]
So I took another look at it this evening, and I'm fairly sure it was an issue with the drive having its permissions changed somehow. The /data directory had been changed to be owned by root. I've no idea how, but changing it back fixed the issue.
