### ISSUE TITLE
Crash app version dev

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#5456]
After entering "Favorites" or "Shared" the app crashes.
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:309)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.ClassCastException: java.lang.Object[] cannot be cast to java.lang.Void[]
	at com.owncloud.android.ui.fragment.OCFileListFragment$3.doInBackground(OCFileListFragment.java:1537)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 3 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20200211
Build flavor: versionDev
```

### Environment data
Android version: 6

Nextcloud app version: dev-20200211

Nextcloud server version: 18.0.0

**Comment by AndyScherzinger** [comment]
I think @tobiasKaminsky worked on a fix that hasn't been merged yet.

**Comment by Valdnet** [comment]
@AndyScherzinger In the dev-20200213 version this still occurs.

**Comment by AndyScherzinger** [comment]
> that hasn't been merged yet

@tobiasKaminsky can you comment on this?

**Comment by tobiasKaminsky** [comment]
This should be fixed, if not please re-open.
