### ISSUE TITLE
crash in search

### ISSUE THREAD

**Issue by elea11** [nextcloud/android#5460]
### Steps to reproduce
1. Open Nextcloud dev
2. Open the subfolder "Documents"
3. Search

### Expected behaviour
- search the folder

### Actual behaviour
- The app crashes

### Environment data
Android version: 10 

Device model: Xiaomi Mi 9SE

Stock or customized system: Customized, Bliss Rom 12.3 (lineage based)

Nextcloud app version: Version 20200212 dev

Nextcloud server version: 17.02

### Logs
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassCastException: java.lang.Object[] cannot be cast to java.lang.Void[]
	at com.owncloud.android.ui.fragment.OCFileListFragment$3.doInBackground(OCFileListFragment.java:1537)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20200212
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: grus
Model: MI 9 SE
Id: QQ1D.200205.002
Product: grus

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: eddcb44350

**Comment by tobiasKaminsky** [comment]
This should be fixed already, can you confirm?

**Comment by elea11** [comment]
yes, it is fixed. can confirm. the issue can be closed, thanks.
