### ISSUE TITLE
Viewing newly uploaded pictures crash

### ISSUE THREAD

**Issue by rkuhnke** [nextcloud/android#5468]
### Steps to reproduce
1. View pictures one at a time and slide through them
2. Some pictures are not shown, msg: do u want to download the full picture. Click yes
3. 

### Expected behaviour
- Tell us what should happen
The picture should be downloaded and shown

### Actual behaviour
- Tell us what happens
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Fragment PreviewImageFragment{cdff0b0 (7754de88-9182-4a78-aa6b-8f53683ca733)} not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:774)
	at androidx.fragment.app.Fragment.getResources(Fragment.java:838)
	at com.owncloud.android.ui.preview.PreviewImageFragment.lambda$setErrorPreviewMessage$2$PreviewImageFragment(PreviewImageFragment.java:727)
	at com.owncloud.android.ui.preview.-$$Lambda$PreviewImageFragment$kydRNo-kMJ0Oklsv9f_06NSEUic.onClick(Unknown Source:2)
	at com.google.android.material.snackbar.Snackbar$1.onClick(Snackbar.java:296)
	at android.view.View.performClick(View.java:7357)
	at android.widget.TextView.performClick(TextView.java:14210)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:967)
	at android.view.View.performClickInternal(View.java:7323)
	at android.view.View.access$3200(View.java:849)
	at android.view.View$PerformClick.run(View.java:27884)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7266)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: gts3llte
Model: SM-T825
Id: PPR1.180610.011
Product: gts3lltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: T825XXU3CSK2

**Comment by ezaquarii** [comment]
The crash is caused by access to resources in line 727:

https://github.com/nextcloud/android/blob/6cb0f1087280004e14bb8f9ae28e3d47edb1f4fc/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java#L721-L730

@tobiasKaminsky I'm looking at this code and it looks like it's a logic error.
If `activity != null` (which means that the fragment is attached), we do `requestForDownload()`.
If `activity == null` (which means that the fragment is **not** attached) we try to show snackbar
using... non-existing activity?

Not sure what we would want to do here instead. If the fragment is not attached, we can't really show anything in parent activity.

**Comment by ezaquarii** [comment]
@rkuhnke thank you for the bug report. I can confirm this defect.
