### ISSUE TITLE
Add new account trouble

### ISSUE THREAD

**Issue by stgodjah** [nextcloud/android#5477]
### Steps to reproduce
1. Start application
2. add new account

### Expected behaviour
- new account added, and now i can switch between accounts
### Actual behaviour

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineForOffset(int)' on a null object reference
	at android.widget.Editor.updateCursorPositionMz(Editor.java:6981)
	at android.widget.Editor.updateCursorsPositions(Editor.java:1760)
	at android.widget.TextView.getUpdatedHighlightPath(TextView.java:5703)
	at android.widget.TextView.onDraw(TextView.java:5896)
	at com.owncloud.android.ui.components.CustomEditText.onDraw(CustomEditText.java:71)
	at android.view.View.draw(View.java:16685)
	at android.view.View.updateDisplayListIfDirty(View.java:15638)
	at android.view.View.draw(View.java:16439)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15630)
	at android.view.View.draw(View.java:16439)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.draw(View.java:16697)
	at com.google.android.material.textfield.TextInputLayout.draw(TextInputLayout.java:1577)
	at android.view.View.updateDisplayListIfDirty(View.java:15638)
	at android.view.View.draw(View.java:16439)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15630)
	at android.view.View.draw(View.java:16439)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15630)
	at android.view.View.draw(View.java:16439)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15630)
	at android.view.View.draw(View.java:16439)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.draw(View.java:16697)
	at android.widget.ScrollView.draw(ScrollView.java:1745)
	at android.view.View.updateDisplayListIfDirty(View.java:15638)
	at android.view.View.draw(View.java:16439)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15630)
	at android.view.View.draw(View.java:16439)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15630)
	at android.view.View.draw(View.java:16439)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15630)
	at android.view.View.draw(View.java:16439)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15630)
	at android.view.View.draw(View.java:16439)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at com.android.internal.policy.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2843)
	at android.view.View.draw(View.java:16697)
	at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2824)
	at android.view.View.updateDisplayListIfDirty(View.java:15638)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:286)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:292)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:327)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3056)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2860)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2469)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1342)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6824)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:898)
	at android.view.Choreographer.doCallbacks(Choreographer.java:699)
	at android.view.Choreographer.doFrame(Choreographer.java:634)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:884)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:6020)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:936)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:797)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: meizu
Device: M5c
Model: M5c
Id: MRA58K
Product: meizu_M5c

************ FIRMWARE ************
SDK: 23
Release: 6.0
Incremental: 1510330837

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by ezaquarii** [comment]
@tobiasKaminsky @AndyScherzinger [this](https://github.com/nextcloud/android/issues?q=is%3Aissue+getLineForOffset+is%3Aclosed) strikes again. How did we solve it last time?

**Comment by AndyScherzinger** [comment]
I guess it was due to removing the custom field implementation via https://github.com/nextcloud/android/pull/4626
