### ISSUE TITLE
dev version crashed

### ISSUE THREAD

**Issue by wfue-20** [nextcloud/android#5500]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens
crashed
### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:
latest dev version
Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
************ CAUSE OF ERROR ************

java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 1(offset:1).state:2 com.owncloud.android.ui.EmptyRecyclerView{ba205c7 GFED..... ......ID 0,0-720,1112 #7f0901b0 app:id/list_root}, adapter:com.owncloud.android.ui.adapter.OCFileListAdapter@a947f4, layout:androidx.recyclerview.widget.LinearLayoutManager@6b82b1d, context:com.owncloud.android.ui.activity.FileDisplayActivity@b3d22f9
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6183)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1730)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1496)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:954)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2716)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2431)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1569)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7301)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:930)
	at android.view.Choreographer.doCallbacks(Choreographer.java:705)
	at android.view.Choreographer.doFrame(Choreographer.java:640)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:916)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6816)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20200219
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: samsung
Device: j5xnlte
Model: SM-J510FN
Id: NMF26X
Product: j5xnltexx

************ FIRMWARE ************
SDK: 25
Release: 7.1.1
Incremental: J510FNXXS3BSH6
*NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by strugee** [comment]
@wfue-20 please edit your issue and fill out the issue template. It's there for a reason - the developers need that information to fix the bug.

**Comment by tobiasKaminsky** [comment]
Hm…Is this a folder with a readme.md aka folder info?
