### ISSUE TITLE
Samsung option to share images folder

### ISSUE THREAD

**Issue by PlaviPixel** [nextcloud/android#5501]
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Do not call this method before initializing mStorageManager
	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.initTargetFolder(ReceiveExternalFilesActivity.java:992)
	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onStart(ReceiveExternalFilesActivity.java:241)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
	at android.app.Activity.performStart(Activity.java:7978)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3472)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7811)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: starlte
Model: SM-G960F
Id: QP1A.190711.020
Product: starltexx

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G960FXXS7DTAD

### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
What are the steps to reproduce?
