### ISSUE TITLE
App crashes when accepting login notification

### ISSUE THREAD

**Issue by minils** [nextcloud/android#5513]
### Steps to reproduce
1. Open app
2. Open sidebar and tap on notifications 
3. Accept the displayed login notification 

### Expected behaviour
- Notification is accepted and the app does not crash

### Actual behaviour
- The notification is accepted and the login is made possible but the app crashes immediately 

### Environment data
Android version: 10

Device model: Oneplus 6

Stock or customized system: stock oxygenos

Nextcloud app version: 3.10.1

Nextcloud server version: 18.0.1

#### App log
```
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:68)
	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
	at com.google.firebase.iid.zzg.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassNotFoundException: com.google.firebase.analytics.connector.AnalyticsConnector
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus6
Model: ONEPLUS A6000
Id: QKQ1.190716.003
Product: OnePlus6

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2001151848
```

**Comment by minils** [comment]
I think this is the same as in  #4675

**Comment by AndyScherzinger** [comment]
Duplicate of #4675
