### ISSUE TITLE
Crash in com.owncloud.android.ui.dialog.CreateFolderDialogFragment.onClick(): NullPointerException

### ISSUE THREAD

**Issue by sevencrazy** [nextcloud/android#5520]
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
at com.owncloud.android.ui.dialog.CreateFolderDialogFragment.onClick(CreateFolderDialogFragment.java:140)
at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:213)
at android.app.ActivityThread.main(ActivityThread.java:8147)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWMAR
Model: MAR-LX1A
Id: HUAWEIMAR-L21A
Product: MAR-LX1AEEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.0.0.167C431
 ```

**Comment by strugee** [comment]
Hopefully this title is more useful while not being too long ;)

@sevencrazy

**Comment by tobiasKaminsky** [comment]
Yes, we need to know when this happens…
