### ISSUE TITLE
What went wrong.....

### ISSUE THREAD

**Issue by cojoslo1986** [nextcloud/android#5524]
### Steps to reproduce
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:4384 flg=0x1 }} to activity {com.nextcloud.client/com.blikoon.qrcodescanner.QrCodeActivity}: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=21801, uid=10200 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4491)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4534)
	at android.app.ActivityThread.-wrap20(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=21801, uid=10200 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
	at android.os.Parcel.readException(Parcel.java:1967)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
	at android.content.ContentResolver.query(ContentResolver.java:760)
	at android.content.ContentResolver.query(ContentResolver.java:710)
	at android.content.ContentResolver.query(ContentResolver.java:668)
	at com.blikoon.qrcodescanner.QrCodeActivity.getPathFromUri(QrCodeActivity.java:386)
	at com.blikoon.qrcodescanner.QrCodeActivity.onActivityResult(QrCodeActivity.java:370)
	at android.app.Activity.dispatchActivityResult(Activity.java:7599)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4487)
	... 9 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Verizon
Device: heroqltevzw
Model: SM-G930V
Id: R16NW
Product: heroqltevzw

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: G930VVRSBCTA1
```

2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by strugee** [comment]
@cojoslo1986 you need to provide more information. Please edit your issue and fill out the full issue template - the developers might need all that information to fix this problem. What were you doing when the crash occurred?

**Comment by cojoslo1986** [comment]
No idea what happen

**Comment by strugee** [comment]
You don't know what you were doing in the app when the crash occurred? Was the app in the background or were you using it?

**Comment by cojoslo1986** [comment]
Running in the backround

**Comment by tobiasKaminsky** [comment]
Can you give the app the permission to read storage?
