### ISSUE TITLE
Programm Absturz

### ISSUE THREAD

**Issue by weinic** [nextcloud/android#5538]
Nachdem ich die Nextcloud App komplett zurück gestetzt und alle Benutuerkonten gelöscht hatte, ist das Programm bei der Neueinrichtung abgestürtzt

************ CAUSE OF ERROR ************

android.database.SQLException: ERROR content://org.nextcloud/file
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:287)
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:255)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:265)
	at android.content.ContentResolver.insert(ContentResolver.java:1279)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFile(FileDataStorageManager.java:247)
	at com.owncloud.android.datamodel.FileDataStorageManager.createRootDir(FileDataStorageManager.java:894)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:110)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2585)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
	at android.app.Activity.performStart(Activity.java:6701)
	at android.app.Activity.performRestart(Activity.java:6775)
	at android.app.ActivityThread.handleWindowVisibility(ActivityThread.java:4014)
	at android.app.ActivityThread.-wrap30(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1535)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: hlte
Model: SM-N9005
Id: NJH47F
Product: lineage_hlte

************ FIRMWARE ************
SDK: 25
Release: 7.1.2
Incremental: a9639c51c9

**Comment by tobiasKaminsky** [comment]
Never saw this error, can you try to completely uninstall the app?
