### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by RIS2000** [nextcloud/android#5540]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.datamodel.OCFile.canWrite()' on a null object reference
	at com.owncloud.android.ui.fragment.OCFileListFragment.updateLayout(OCFileListFragment.java:1296)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1265)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1199)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onResume(FileDisplayActivity.java:1223)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
	at android.app.Activity.performResume(Activity.java:7614)
	at android.app.ActivityThread.performNewIntents(ActivityThread.java:3703)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3718)
	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:49)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWVOG
Model: VOG-L29
Id: HUAWEIVOG-L29
Product: VOG-L29RU

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 9.1.0.241C10

**Comment by tobiasKaminsky** [comment]
Do you remember what the steps are that lead to this crash?

**Comment by RIS2000** [comment]
Hello!

As far as i can remember, the app showed this crashlog when i finished to setup autoloading files.

**Comment by tobiasKaminsky** [comment]
I tried to reproduce it, but could not :/
Can you re-open the issue once it  occurs again, with detailed steps.

**Comment by RIS2000** [comment]
Ok
