### ISSUE TITLE
App Absturz durch Benachrichtigungen

### ISSUE THREAD

**Issue by weinic** [nextcloud/android#5541]
Ich habe festgestellt dass die APP abgestürzt ist, als ich auf der Web Oberfläche von Nextcloud eine Termin Benachrichtigung geschlossen habe.
Ob das zusammen hängt weiß ich nicht.

************ CAUSE OF ERROR ************

android.database.SQLException: ERROR content://org.nextcloud/file
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:287)
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:255)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:265)
	at android.content.ContentResolver.insert(ContentResolver.java:1279)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFile(FileDataStorageManager.java:247)
	at com.owncloud.android.datamodel.FileDataStorageManager.createRootDir(FileDataStorageManager.java:894)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:110)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2585)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
	at android.app.Activity.performStart(Activity.java:6701)
	at android.app.Activity.performRestart(Activity.java:6775)
	at android.app.ActivityThread.handleWindowVisibility(ActivityThread.java:4014)
	at android.app.ActivityThread.-wrap30(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1535)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: hlte
Model: SM-N9005
Id: NJH47F
Product: lineage_hlte

************ FIRMWARE ************
SDK: 25
Release: 7.1.2
Incremental: a9639c51c9

**Comment by weinic** [comment]
Einer von vielen weiteren Abstürzen.
Heute habe ich auf die Neueste Version aktualisiert, auch hier besteht noch das Problem.


************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source)
	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source)
	at com.google.firebase.iid.zzc.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/data/app/com.nextcloud.client-1/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-1/lib/arm, /data/app/com.nextcloud.client-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110053
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: hlte
Model: SM-N9005
Id: NJH47F
Product: lineage_hlte

************ FIRMWARE ************
SDK: 25
Release: 7.1.2
Incremental: a9639c51c9

**Comment by weinic** [comment]
Siehe E-mail vom 8.März 2020
;
;

---------- Forwarded message ---------

Date: So., 8. März 2020, 19:25
Subject: Re: Antwort auf deinen Kommentar zur Android-App "Nextcloud"
To: <android@nextcloud.com>


Mit „Änderung“ ist gemeint, wenn auf dem Server eine Benachrichtigung generiert oder gelöscht wird.
Oder auch durch den Benutzer die Benachrichtigung geschlossen wird, (auch in der APP).
Die Benachrichtigungen werden dann zur Nextcloud APP übertragen, damit diese dort angezeigt/gelöscht werden können.
Und bei eben jener Änderung von Benachrichtigungen kommt es zum Absturz der APP.

Crash-Report...?
Wie erstelle ich diesen? 
Ich dachte der Report von Post #5541 ist ein Crash-Report, weil dieser nach dem Absturz der APP angezeigt wurde.

Mfg Christoph
;
;

<noreply@google.com> schrieb am Fr., 6. März 2020, 10:06:
Google Play Logo
Hallo,
Wir möchten dir hiermit mitteilen, dass der Entwickler der Android-App Nextcloud auf dein Betafeedback vom 05.03.2020 geantwortet hat.



Nextcloud
 Update: Problem mit Benachrichtigungen: Bei jeder Änderung von Benachrichtigungen stürzt die APP ab. Siehe Post #5541 von weinic auf github. Das Problem mit der 100% Auslastung von php-fpm kommt nicht mehr vor. Anzeige von geteilten Dateien/Ordnern funktioniert jetzt ebenfalls 👍
Antwort des Entwicklers:
Post 5541 sieht auf den ersten Blick anders aus.
Was bedeutet Änderung? Gibt es einen Crash-Report?
Edit beta feedback

Wenn du das Problem genauer mit dem Entwickler besprechen möchtest, kannst du ihn direkt kontaktieren, indem du eine E-Mail an Nextcloud sendest oder auf diese E-Mail antwortest.

Entwickler müssen sich bei ihren Antworten an die Posting-Richtlinien halten. Falls du Bedenken bezüglich der Antwort eines Entwicklers auf dein Betafeedback hast, wende dich bitte an Google.

Wenn du keine weiteren Benachrichtigungen erhalten möchtest, wenn Entwickler auf dein Betafeedback antworten, kannst du die Benachrichtigungen hier deaktivieren.

Mit freundlichen Grüßen
Das Google Play-Team

**Comment by AndyScherzinger** [comment]
Hallo @weinic,

bitte immer genau ein Problem pro Issue, ansonsten können wir das nicht gut nachverfolgen. dein letzgemeldetes Thema ist schon bekannt und zu finden unter: #4675

**Comment by tobiasKaminsky** [comment]
First one I do not know, but second is a duplicate of #5579

**Comment by tobiasKaminsky** [comment]
Duplicate of #4675
