### ISSUE TITLE
Absturz beim Öffnen

### ISSUE THREAD

**Issue by weinic** [nextcloud/android#5544]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.owncloud.android.datamodel.FileDataStorageManager com.nextcloud.client.mixins.SessionMixin.getStorageManager()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.owncloud.android.datamodel.FileDataStorageManager com.nextcloud.client.mixins.SessionMixin.getStorageManager()' on a null object reference
	at com.owncloud.android.ui.activity.BaseActivity.getStorageManager(BaseActivity.java:167)
	at com.owncloud.android.ui.fragment.FileDetailSharingFragment.onCreate(FileDetailSharingFragment.java:192)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2586)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:838)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
	at androidx.fragment.app.FragmentManagerImpl.dispatchCreate(FragmentManagerImpl.java:2607)
	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:235)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:316)
	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:105)
	at com.owncloud.android.ui.activity.BaseActivity.onCreate(BaseActivity.java:57)
	at com.owncloud.android.ui.activity.ToolbarActivity.onCreate(ToolbarActivity.java:57)
	at com.owncloud.android.ui.activity.DrawerActivity.onCreate(DrawerActivity.java:1202)
	at com.owncloud.android.ui.activity.FileActivity.onCreate(FileActivity.java:168)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onCreate(FileDisplayActivity.java:236)
	at android.app.Activity.performCreate(Activity.java:6684)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
	... 9 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20200224
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: samsung
Device: hlte
Model: SM-N9005
Id: NJH47F
Product: lineage_hlte

************ FIRMWARE ************
SDK: 25
Release: 7.1.2
Incremental: a9639c51c9

**Comment by tobiasKaminsky** [comment]
Should be fixed with 3.11 next week, please re-open if not.
