### ISSUE TITLE
Fragment ChooseTemplateDialogFragment not attached to a context.

### ISSUE THREAD

**Issue by Googlesfans** [nextcloud/android#5550]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
Caused by: java.lang.IllegalStateException: Fragment ChooseTemplateDialogFragment{285cbe1 (c41d67a9-2dc2-45c3-b4d1-47d9115f2b02)} not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:774)
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment$CreateFileFromTemplateTask.doInBackground(ChooseTemplateDialogFragment.java:258)
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment$CreateFileFromTemplateTask.doInBackground(ChooseTemplateDialogFragment.java:211)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 5 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWHMA
Model: HMA-AL00
Id: HUAWEIHMA-AL00
Product: HMA-AL00

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.0.0.188C00

**Comment by tobiasKaminsky** [comment]
> Caused by: java.lang.IllegalStateException: Fragment ChooseTemplateDialogFragment{285cbe1 (c41d67a9-2dc2-45c3-b4d1-47d9115f2b02)} not attached to a context.

Seems that you wanted to create an office file and then navigated somewhere else while it tried to fetch the templates?
