### ISSUE TITLE
[Bug] java.lang.NullPointerException: Attempt to invoke virtual method...

### ISSUE THREAD

**Issue by PopeRigby** [nextcloud/android#5561]
# CAUSE OF ERROR
java.lang.NullPointerException: Attempt to invoke virtual method 'long com.owncloud.android.datamodel.OCFile.getParentId()' on a null object reference
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:410)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:369)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:228)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:357)
	at java.lang.Thread.run(Thread.java:764)

# APP INFORMATION
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

# DEVICE INFORMATION
Brand: motorola
Device: potter
Model: Moto G (5) Plus
Id: OPSS28.85-17-2
Product: potter

# FIRMWARE
SDK: 27
Release: 8.1.0
Incremental: 945e

**Comment by tobiasKaminsky** [comment]
When does this happen? In which folder?
It tries to get info about a parent folder. Does this one still exist on server?
