### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by wbcho** [nextcloud/android#5568]
### Steps to reproduce
1. Install Nexcloud app from Google Play store
2. Launch the app

### Expected behaviour
- App should open at least

### Actual behaviour
- Series of system message that the app crashed

### Environment data
Android version: 6.0.1

Device model: Samsung SM-G906K

Stock or customized system: Stock

Nextcloud app version: 3.10.1

Nextcloud server version: ?

#### Web server error log
```
Inser your Nextcloud server log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.IncompatibleClassChangeError: Class 'java.util.Collections$EmptyMap' does not implement interface 'dagger.android.AndroidInjector' in call to 'void dagger.android.AndroidInjector.inject(java.lang.Object)' (declaration of 'dagger.android.AndroidInjection' appears in /data/app/com.nextcloud.client-1/base.apk)
	at dagger.android.AndroidInjection.inject(AndroidInjection.java:181)
	at dagger.android.AndroidInjection.inject(AndroidInjection.java:173)
	at com.owncloud.android.providers.DiskLruImageCacheFileProvider.onCreate(DiskLruImageCacheFileProvider.java:60)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:1789)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:1764)
	at android.app.ActivityThread.installProvider(ActivityThread.java:6768)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6363)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6303)
	at android.app.ActivityThread.access$1800(ActivityThread.java:222)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1862)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7230)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: lentisltektt
Model: SM-G906K
Id: MMB29M
Product: lentisltektt

************ FIRMWARE ************
SDK: 23
Release: 6.0.1
Incremental: G906KKTU1CPL1

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by ezaquarii** [comment]
@wbcho How often does is happen for you?

**Comment by wbcho** [comment]
Hi, The app crashed from the very first time and I could not run it even once. Thanks for looking into this problem.

**Comment by tobiasKaminsky** [comment]
> Device model: Samsung SM-G906K

I tried it with a SM-G903F with Android 6.0.1 and it works without any problem.
