### ISSUE TITLE
NextCloud Crashed

### ISSUE THREAD

**Issue by jwhaleyca** [nextcloud/android#5572]
************ CAUSE OF ERROR ************

java.lang.IllegalArgumentException: reportSizeConfigurations: ActivityRecord not found for: Token{a3d205b null}
	at android.os.Parcel.createException(Parcel.java:1970)
	at android.os.Parcel.readException(Parcel.java:1934)
	at android.os.Parcel.readException(Parcel.java:1884)
	at android.app.IActivityManager$Stub$Proxy.reportSizeConfigurations(IActivityManager.java:8642)
	at android.app.ActivityThread.reportSizeConfigurations(ActivityThread.java:3280)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3239)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6990)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.reportSizeConfigurations(ActivityManagerService.java:10528)
	at android.app.IActivityManager$Stub.onTransact$reportSizeConfigurations$(IActivityManager.java:12542)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2401)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4126)
	at android.os.Binder.execTransact(Binder.java:739)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: crownqlteue
Model: SM-N960U1
Id: PPR1.180610.011
Product: crownqlteue

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: N960U1UES3CSK1

**Comment by Charon77** [comment]
Hi, can you reproduce the problem? Does it occur often?
