### ISSUE TITLE
Bug on Android

### ISSUE THREAD

**Issue by InitusJames** [nextcloud/android#5573]
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:1536)
	at androidx.fragment.app.FragmentManagerImpl.enqueueAction(FragmentManagerImpl.java:1558)
	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:317)
	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:282)
	at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:250)
	at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:202)
	at com.owncloud.android.ui.activity.UploadFilesActivity.onCheckAvailableSpaceFinish(UploadFilesActivity.java:471)
	at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:72)
	at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:34)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.-wrap1(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: lge
Device: h1
Model: LG-H831
Id: OPR1.170623.032
Product: h1_rgs_ca

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: 182291613daa1

**Comment by Charon77** [comment]
Hi, does this happen often? Could you reproduce it?

**Comment by tobiasKaminsky** [comment]
We need steps to reproduce, otherwise we cannot do anything…
