### ISSUE TITLE
ConcurrentModificationException in FileSortOrderByName.sortCloudFiles

### ISSUE THREAD

**Issue by szaimen** [nextcloud/android#5597]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList.sort(ArrayList.java:1472)
	at java.util.Collections.sort(Collections.java:206)
	at com.owncloud.android.utils.FileSortOrderByName.sortCloudFiles(FileSortOrderByName.java:52)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.setData(OCFileListAdapter.java:870)
	at com.owncloud.android.ui.fragment.OCFileListFragment$3.doInBackground(OCFileListFragment.java:1559)
	at com.owncloud.android.ui.fragment.OCFileListFragment$3.doInBackground(OCFileListFragment.java:1541)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: beyond0
Model: SM-G970F
Id: QP1A.190711.020
Product: beyond0lteeea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G970FXXS4BTB3

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @ezaquarii any idea when this might happen? Refreshing the file list while it is being sorted?

**Comment by tobiasKaminsky** [comment]
@szaimen do you know when this happened?

**Comment by szaimen** [comment]
I just cklicked a bit through the options in the left menu hamburger menu. Don't know exactly when this happened. But I can no longer reproduce this. So maybe it is already fixed.
