### ISSUE TITLE
App crashing randomly

### ISSUE THREAD

**Issue by Aurnytoraink** [nextcloud/android#5637]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.db.OCUpload.getLocalPath()' on a null object reference
	at com.owncloud.android.ui.dialog.ConflictsResolveDialog.newInstance(ConflictsResolveDialog.java:87)
	at com.owncloud.android.ui.activity.ConflictsResolveActivity.onStart(ConflictsResolveActivity.java:180)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
	at android.app.Activity.performStart(Activity.java:7847)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3295)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:920)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: beryllium
Model: POCO F1
Id: QQ2A.200305.003
Product: beryllium

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 9f554a4a3a

**Comment by tobiasKaminsky** [comment]
This should be fixed with latest beta version, you can test it via google play store.
Please re-open if it still happens.
