### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by elpraga** [nextcloud/android#5647]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:330)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:255)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:776)
Caused by: java.lang.IllegalStateException: Fragment ChooseRichDocumentsTemplateDialogFragment{39969a0 (591c8bb2-abd1-41d6-a7e3-b6ea1835533c)} not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:774)
	at com.owncloud.android.ui.dialog.ChooseRichDocumentsTemplateDialogFragment$CreateFileFromTemplateTask.doInBackground(ChooseRichDocumentsTemplateDialogFragment.java:254)
	at com.owncloud.android.ui.dialog.ChooseRichDocumentsTemplateDialogFragment$CreateFileFromTemplateTask.doInBackground(ChooseRichDocumentsTemplateDialogFragment.java:219)
	at android.os.AsyncTask$2.call(AsyncTask.java:316)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWAGS-Q
Model: AGS-W09
Id: HUAWEIAGS-W09
Product: AGS

************ FIRMWARE ************
SDK: 24
Release: 7.0
Incremental: C100B278

**Comment by AndyScherzinger** [comment]
Hi @elpraga,

Is this happening constantly or was it a one time thing, also how can this be reproduced?

**Comment by elpraga** [comment]
Hi @AndyScherzinger ,
I don't know how to trigger or reproduce the crash. but it does happen once or twice a week (a crash,  not sure if it is the same one).  It is true, though that the app crashes much more often than it used to.

**Comment by elpraga** [comment]
Anther one
************ CAUSE OF ERROR ************

java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:671)
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:679)
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:153)
	at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:131)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
	at okhttp3.RealCall.execute(RealCall.java:93)
	at com.nextcloud.common.OkHttpMethodBase.execute(OkHttpMethodBase.kt:126)
	at com.nextcloud.common.NextcloudClient.execute(NextcloudClient.kt:84)
	at com.owncloud.android.lib.resources.activities.GetActivitiesRemoteOperation.run(GetActivitiesRemoteOperation.java:131)
	at com.nextcloud.common.NextcloudClient.execute(NextcloudClient.kt:80)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$fetchAndSetData$5$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:331)
	at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$N7POe6TZvoGcuV2qP-niPxY_7t4.run(Unknown Source:12)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: xiaomi
Device: lavender
Model: Redmi Note 7
Id: PKQ1.180904.001
Product: lavender_eea

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: V11.0.4.0.PFGEUXM

**Comment by AndyScherzinger** [comment]
@elpraga the timeout crashes should be gone with 3.11.0 as far as I understood @tobiasKaminsky

**Comment by elpraga** [comment]
Great to hear @AndyScherzinger ! Any idea about the release date of 3.11.0?

**Comment by AndyScherzinger** [comment]
That's rather a question for @tobiasKaminsky, but I guess this week :)

**Comment by elpraga** [comment]
That would be great! :)

**Comment by tobiasKaminsky** [comment]
It would be good if you can test RC2 by joining google beta program for this app and verify if this bug is fixed:
https://play.google.com/apps/testing/com.nextcloud.client

**Comment by elpraga** [comment]
OK, done, I will post an update if crashes keep happening @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
Thank, then just re-open :+1:
