### ISSUE TITLE
Cannot use SD card

### ISSUE THREAD

**Issue by stroudmw** [nextcloud/android#5667]
I have a Samsung Galaxy S4, and am running Nextcloud Android app version 3.10.1 and Android 5.0.1. My Nextcloud server is on a Debian 10 linux platform and I installed Nextcloud using snap. I have also tried this using a manual installation using both Nginx and Apache2, as well as Mariadb and Psotgresql (Ubuntu, Debian, Centos 7/8, and FreeBSD servers)  so I don't think the issue is with my server.

When I go into the Android App, select Settings -> Storage Path. I select the option "/storage/extSdCard/Android/media/com.nextcloud.client" it comes up with" "Updating Storage Path" and "Failed during migration".

I have reinstalled the android app, and that hasn't helped. I deleted and recreated my account (so that there wouldn't be any data to migrate) and that didn't help either.

The Nextcloud Android app is not much use to me if I can't access my 32GiB external SD card.

Thank you.

**Comment by stroudmw** [comment]
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:904)
at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1700)
at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1646)
at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:642)
at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:626)
at android.content.ContentProvider$Transport.update(ContentProvider.java:330)
at android.content.ContentResolver.update(ContentResolver.java:1343)
at com.owncloud.android.datamodel.FileDataStorageManager.saveCapabilities(FileDataStorageManager.java:1941)
at com.owncloud.android.operations.GetCapabilitiesOperation.run(GetCapabilitiesOperation.java:44)
at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136)
at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:66)
at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:287)
at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:267)
at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:220)
at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:357)
at java.lang.Thread.run(Thread.java:818)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: ja3g
Model: GT-I9500
Id: LRX22C
Product: ja3gxx

************ FIRMWARE ************
SDK: 21
Release: 5.0.1
Incremental: I9500XXUHOH6

**Comment by j-ed** [comment]
As [already written](https://help.nextcloud.com/t/nextcloud-android-app-sd-card/68426/2?u=j-ed) in the help forum, this problem can most likely not been solved by the App, because the underlying Android version denies direct access to the files and additionally EOS for Android 5 has been declared in November 2015.

**Comment by tobiasKaminsky** [comment]
Yeah, for some reason the app is not allowed to write onto external sd card.
I fear that we cannot do much here… :-(

**Comment by Keilaron** [comment]
This relates to #5610 and #5946 .
