### ISSUE TITLE
Absturz vermutlich durch Freigabe über Kreise

### ISSUE THREAD

**Issue by weinic** [nextcloud/android#5687]
Beim Versuch auf die Ansicht der Geteilten Dateien zu gehen stürtzt die APP ab.
Meine Vermutung ist, dass es an einer Freigabe über die Kreise (Circles) APP liegt, da ich diese kurz vorher angelegt hatte.

************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:325)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.IllegalArgumentException: Empty values
	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1545)
	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1525)
	at com.owncloud.android.providers.FileContentProvider.updateFilesTableAccordingToShareInsertion(FileContentProvider.java:417)
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:309)
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:255)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:290)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:669)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:318)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:438)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:1318)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveShares(FileDataStorageManager.java:1392)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.parseShares(OCFileListAdapter.java:918)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.setData(OCFileListAdapter.java:859)
	at com.owncloud.android.ui.fragment.OCFileListFragment$3.doInBackground(OCFileListFragment.java:1559)
	at com.owncloud.android.ui.fragment.OCFileListFragment$3.doInBackground(OCFileListFragment.java:1541)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 3 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110052
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: hlte
Model: SM-N9005
Id: NJH47F
Product: lineage_hlte

************ FIRMWARE ************
SDK: 25
Release: 7.1.2
Incremental: a9639c51c9

**Comment by weinic** [comment]
Ich habe es gerade getestet, es liegt definitiv an der Freigabe zu einem Kreis.

Nach dem Löschen der Freigabe funktionierte die Anzeige der Geteilten Dateien wieder.

Zum test habe ich nochmals eine andere Datei/Ordner, der noch nicht geteilt ist, nochmals mit einem Kreis geteilt und darauf hin ist die Nextcloud APP wieder mit der Ansicht der Geteilten Dateien abgestürzt.

**Comment by tobiasKaminsky** [comment]
Thanks for confirmation and reporting!
This is fixed via #5688.
In this PR there is an APK which you can install in parallel for testing it.

**Comment by weinic** [comment]
Thanks a lot
The share funktion for circles works fine with nextcloud QA APP 👍

But i have a nother Problem.
The share standards for new shares i would set in Nextcloud (create, delete, change) are not applied in the app

**Comment by weinic** [comment]
That works now.
Thanks 👍
