### ISSUE TITLE
Login not saved

### ISSUE THREAD

**Issue by Matei-Ciobotaru** [nextcloud/android#5701]
### Steps to reproduce
1.  Login to Nextcloud server via Android app
2.  Minimize app and go about life
3. In less than ~8 hours, when accessing NC mobile app it requests login credentials once more

### Expected behaviour
- The app should keep me signed in until I re-install it on my phone.

### Actual behaviour
- NC mobile app requests login credentials again and again, in <  8 hour interval when opened

### Environment data
Android version:  Android v10, kernel v4.14.113-17806689

Device model: Samsung Galaxy S10

Stock or customized system: stock

Nextcloud app version: v3.10.1

Nextcloud server version: v18.0.2

#### Web server error log
```
<IP-REDACTED> - - [20/Mar/2020:19:22:10 +0200] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 5076 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.10.1"
<IP-REDACTED> - - [20/Mar/2020:19:22:10 +0200] "DELETE /ocs/v2.php/apps/notifications/api/v2/push HTTP/1.1" 200 4665 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.10.1"
<IP-REDACTED> - - [20/Mar/2020:19:22:10 +0200] "GET /index.php/avatar/<USER-REDACTED>/384 HTTP/1.1" 304 3991 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.10.1"
<IP-REDACTED> - - [20/Mar/2020:19:22:13 +0200] "PROPFIND /remote.php/webdav/Notes/ HTTP/1.1" 207 1496 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.10.1"
<IP-REDACTED> - - [20/Mar/2020:19:22:10 +0200] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 5076 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.10.1"
<IP-REDACTED> - - [20/Mar/2020:19:22:13 +0200] "PROPFIND /remote.php/webdav/Notes/ HTTP/1.1" 207 9999 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.10.1"
<IP-REDACTED> - - [20/Mar/2020:19:22:14 +0200] "GET /ocs/v2.php/apps/files_sharing/api/v1/shares?path=%2FNotes%2F&reshares=true&subfiles=true HTTP/1.1" 401 1634 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.10.1"
<IP-REDACTED> - - [20/Mar/2020:19:22:15 +0200] "GET /index.php/apps/files/api/v1/thumbnail/256/256/Notes/to%20browse.txt HTTP/1.1" 500 5621 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.10.1"
<IP-REDACTED> - - [20/Mar/2020:19:22:11 +0200] "GET /ocs/v1.php/cloud/capabilities?format=json HTTP/1.1" 200 1567 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.10.1"
<IP-REDACTED> - - [20/Mar/2020:19:22:15 +0200] "GET /index.php/apps/files/api/v1/thumbnail/256/256/Notes/to%20browse.txt HTTP/1.1" 500 6149 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.10.1"
<IP-REDACTED> - - [20/Mar/2020:19:22:15 +0200] "GET /ocs/v2.php/apps/files/api/v1/directEditing?format=json HTTP/1.1" 401 1392 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.10.1"
<IP-REDACTED> - - [20/Mar/2020:19:22:16 +0200] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 401 898 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.10.1"
<IP-REDACTED> - - [20/Mar/2020:19:22:16 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 401 1046 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.10.1"
<IP-REDACTED> - - [20/Mar/2020:19:22:17 +0200] "POST /index.php/core/wipe/check?format=json HTTP/1.1" 404 755 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.10.1"
<IP-REDACTED> - - [20/Mar/2020:19:22:17 +0200] "PROPFIND /remote.php/webdav/Notes/ HTTP/1.1" 401 1046 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.10.1"
<IP-REDACTED> - - [20/Mar/2020:19:22:17 +0200] "GET /status.php HTTP/1.1" 200 1653 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.10.1"
<IP-REDACTED> - - [20/Mar/2020:19:22:17 +0200] "HEAD /remote.php/webdav/ HTTP/1.1" 401 1165 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.10.1"
<IP-REDACTED> - - [20/Mar/2020:19:22:18 +0200] "GET /index.php/login/flow HTTP/1.1" 200 7247 "-" "Samsung SM-G973F (Android)"
<IP-REDACTED> - - [20/Mar/2020:19:22:18 +0200] "GET /index.php/core/js/oc.js?v=3f0b3ad1 HTTP/1.1" 200 6836 "-" "Samsung SM-G973F (Android)"
<IP-REDACTED> - - [20/Mar/2020:19:22:18 +0200] "GET /index.php/apps/accessibility/js/accessibility?v=0 HTTP/1.1" 200 1495 "-" "Samsung SM-G973F (Android)"
<IP-REDACTED> - - [20/Mar/2020:19:22:18 +0200] "GET /index.php/apps/theming/js/theming?v=18 HTTP/1.1" 200 1642 "-" "Samsung SM-G973F (Android)"

```

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"bABLvaUojHzswFa3RnHW","level":2,"time":"2020-03-20T19:22:14+02:00","remoteAddr":"<IP-REDACTED>","user":"--","app":"core","method":"GET","url":"/ocs                                                                                /v1.php/cloud/capabilities?format=json","message":"Login failed: '<USER-REDACTED>' (Remote IP: '<IP-REDACTED>')","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3                                                                                .10.1","version":"18.0.2.2"}
{"reqId":"YOqQvzRGOFZa1J2r5y4Q","level":3,"time":"2020-03-20T19:22:15+02:00","remoteAddr":"<IP-REDACTED>","user":"--","app":"index","method":"GET","url":"/in                                                                                dex.php/apps/files/api/v1/thumbnail/256/256/Notes/to%20browse.txt","message":{"Exception":"TypeError","Message":"Argument 3 passed to OCA\\Files\\Service\\Ta                                                                                gService::__construct() must be an instance of OCP\\ITags, null given, called in /var/www/nextcloud/apps/files/lib/AppInfo/Application.php on line 84","Code"                                                                                :0,"Trace":[{"file":"/var/www/nextcloud/apps/files/lib/AppInfo/Application.php","line":84,"function":"__construct","class":"OCA\\Files\\Service\\TagService",                                                                                "type":"->","args":[{"__class__":"OC\\User\\Session"},{"__class__":"OC\\Activity\\Manager"},null,null,{"__class__":"OC\\EventDispatcher\\SymfonyAdapter"}]},{                                                                                "file":"/var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php","line":118,"function":"OCA\\Files\\AppInfo\\{closure}","class":"OCA\\Files\\AppIn                                                                                fo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.p                                                                                hp","line":113,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["TagService"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Dep                                                                                endencyInjection/DIContainer.php","line":408,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["TagService"]},{"fil                                                                                e":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":386,"function":"queryNoFallback","class":"OC\\AppFramework\\Depen                                                                                dencyInjection\\DIContainer","type":"->","args":["TagService"]},{"file":"/var/www/nextcloud/apps/files/lib/AppInfo/Application.php","line":66,"function":"que                                                                                ry","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["TagService"]},{"file":"/var/www/nextcloud/3rdparty/pimple/pimple/src/Pi                                                                                mple/Container.php","line":118,"function":"OCA\\Files\\AppInfo\\{closure}","class":"OCA\\Files\\AppInfo\\Application","type":"->","args":["*** sensitive para                                                                                meters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":113,"function":"offsetGet","class":"Pimple\\C                                                                                ontainer","type":"->","args":["APIController"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":408,"functio                                                                                n":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["APIController"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/De                                                                                pendencyInjection/DIContainer.php","line":386,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["                                                                                APIController"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":98,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\D                                                                                IContainer","type":"->","args":["APIController"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"                                                                                main","class":"OC\\AppFramework\\App","type":"::","args":["APIController","getThumbnail","*** sensitive parameter replaced ***",{"x":"256","y":"256","file":"                                                                                Notes/to browse.txt","_route":"files.API.getThumbnail"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[                                                                                {"x":"256","y":"256","file":"Notes/to browse.txt","_route":"files.API.getThumbnail"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":299,"                                                                                function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"x":"256","y":"256","file":"Notes/to browse.txt","_route":"                                                                                files.API.getThumbnail"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/fi                                                                                les/api/v1/thumbnail/256/256/Notes/to%20browse.txt"]},{"file":"/var/www/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","a                                                                                rgs":[]}],"File":"/var/www/nextcloud/apps/files/lib/Service/TagService.php","Line":60,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Android) Nextcloud-andr                                                                                oid/3.10.1","version":"18.0.2.2"}
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by Matei-Ciobotaru** [comment]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
	at com.owncloud.android.utils.ThemeUtils.primaryAccentColor(ThemeUtils.java:103)
	at com.owncloud.android.ui.dialog.IndeterminateProgressDialog$1.onShow(IndeterminateProgressDialog.java:74)
	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1595)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7777)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: beyond1
Model: SM-G973F
Id: QP1A.190711.020
Product: beyond1lteeea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G973FXXS4BTB3

**Comment by tobiasKaminsky** [comment]
Hm, the app request re-login if the serve revokes.
Do you have any special server settings?
Do you see the app-token still in the list of your users (in settings)?
Is the NC account still visible in Android's settings?

**Comment by Matei-Ciobotaru** [comment]
> Do you have any special server settings?

Not that i know of, please expand on "special server settings"...

> Do you see the app-token still in the list of your users (in settings)?

I see my account in the app "Manage accounts" settings menu, yes.

> Is the NC account still visible in Android's settings?

Not sure how to check this...

I do want to add, I have 2 NC servers with different accounts in the same app, only the primary has this issue.

**Comment by tobiasKaminsky** [comment]
> > Is the NC account still visible in Android's settings?
> 
> Not sure how to check this...

Android setting -> Account



> I have 2 NC servers with different accounts in the same app, only the primary has this issue.

Is there a difference between the servers, eg. version, etc.?

**Comment by Matei-Ciobotaru** [comment]
I have since updated to NC 18.0.3 and so far the reported issue is no longer encountered.
I am unsure of the root cause and I will leave this issue opened a couple of days to be sure that this is not just a coincidence.
