### ISSUE TITLE
App crashes on first use start  as secondary user/profile

### ISSUE THREAD

**Issue by bingen** [nextcloud/android#5709]
### Steps to reproduce
1. Open app
2. Sign in

### Expected behaviour
- Get into folders view

### Actual behaviour
- It crashes

### Environment data
Android version:
9

Device model: 
Leenovo YT-X705F

Nextcloud app version:
3.10.1

####  App error log
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED flg=0x10 pkg=com.nextcloud.client (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver@ad71f3e
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1410)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6859)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=8814, uid=1010171 requires android.permission.BROADCAST_STICKY
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.app.IActivityManager$Stub$Proxy.unbroadcastIntent(IActivityManager.java:3904)
	at android.app.ContextImpl.removeStickyBroadcast(ContextImpl.java:1346)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
	at com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver.onReceive(FileDisplayActivity.java:1411)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1400)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.unbroadcastIntent(ActivityManagerService.java:22219)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:183)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3323)
	at com.android.server.am.WosActivityManagerService.onTransact(WosActivityManagerService.java:89)
	at android.os.Binder.execTransact(Binder.java:731)


************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Lenovo
Device: YT-X705F
Model: Lenovo YT-X705F
Id: PKQ1.181218.001
Product: YT-X705F_EEA

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: X705F_S001032_191119_ROW
```

**Comment by tobiasKaminsky** [comment]
Do you use Android for Work or similar mechanism?

**Comment by bingen** [comment]
No, but I was using it as a secondary user in that tablet. Could it be related? I'll try if it happens the same as the main user.

**Comment by tobiasKaminsky** [comment]
Yes, this will cause it, I fear.
Please test it :-)

**Comment by bingen** [comment]
I tried and it works with the primary user, but I need to use it with the secondary one. Is there anything I can do? Thanks.

**Comment by tobiasKaminsky** [comment]
Unfortunately not. This needs a (big) change, but we are currently lacking of engineering power and thus this will not be high scheduled… :/

**Comment by AndyScherzinger** [comment]
> I tried and it works with the primary user, but I need to use it with the secondary one. Is there anything I can do? Thanks.

If the app is installed in both profiles it should work, see https://github.com/nextcloud/android/issues/4205 
> so when I installed nextcloud also in normal user space (only install, no launch) the application in work profile will work as expected.

**Comment by AndyScherzinger** [comment]
Duplicate of #6654
