### ISSUE TITLE
Nextcloud Android Client crashes when editing a text file.

### ISSUE THREAD

**Issue by ethanmye-rs** [nextcloud/android#5731]
### Steps to reproduce
1. I added some text to a textfile stored in Nextcloud on my laptop
2. I removed that text after viewing the longer file on my phone
3. After editing the file on my laptop, I tried to open it on my phone, crashing nextcloud.

### Expected behaviour
- It should not crash. Nextcloud mobile shows the correct expected filesize.

### Actual behaviour
- It crashes everytime I attempt to open the new text file.

### Can you reproduce this problem on https://try.nextcloud.com?
I'm unsure of how to link the trial server to my phone to reproduce -- I'm not sure what the passcode to link the two is.

### Environment data
Android version: 10

Device model: OnePlus 6T

Stock or customized system:

Nextcloud app version: 3.10.1

Nextcloud server version: Version 2.6.4stable-Win64 (build 20200303).

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
Android/data/com.nextcloud.client is empty. There seems to be an expert mode that exposed logs, but may have been removed?

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.widget.SearchView.setOnQueryTextListener(androidx.appcompat.widget.SearchView$OnQueryTextListener)' on a null object reference
	at com.owncloud.android.ui.preview.PreviewTextFileFragment$TextLoadAsyncTask.onPostExecute(PreviewTextFileFragment.java:216)
	at com.owncloud.android.ui.preview.PreviewTextFileFragment$TextLoadAsyncTask.onPostExecute(PreviewTextFileFragment.java:149)
	at android.os.AsyncTask.finish(AsyncTask.java:755)
	at android.os.AsyncTask.access$900(AsyncTask.java:192)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus6T
Model: ONEPLUS A6013
Id: QKQ1.190716.003
Product: OnePlus6TSingle

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2001151848

**Comment by tobiasKaminsky** [comment]
>     2\. I removed that text after viewing the longer file on my phone

How do you view the file? Is it plain text and then it opens up the webview?
Can you give us an screenshot?

It should also generate an exception stacktrace.

**Comment by ethanmye-rs** [comment]
I'm going to go ahead and close the issue. I am unable to reproduce it on the try.nextcloud.com service, and am now unable to reproduce it on my end. 

Sorry about that!
