### ISSUE TITLE
java.lang.RuntimeException: Error receiving broadcast Intent

### ISSUE THREAD

**Issue by Entepotenz** [nextcloud/android#5735]
### Steps to reproduce
1. First off: I do not remember all my steps and cannot reproduce this error
2. Navigate to file which is not downloaded yet
3. Select the file
4. I don't think i saw the Opening dialog
5. the App crashed

### Expected behaviour
- The App does not crash

### Actual behaviour
- App crashed

### Environment data
Android version: Android 8.0.0

Nextcloud app version: 3.10.1

Nextcloud server version: 15.0.14

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.files.services.FileDownloaderDOWNLOAD_FINISH flg=0x10 pkg=com.nextcloud.client (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$DownloadFinishReceiver@1fbf637
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_51615(LoadedApk.java:1314)
	at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.$m$0(Unknown Source:4)
	at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.run(Unknown Source:0)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'com.owncloud.android.datamodel.FileDataStorageManager com.owncloud.android.ui.fragment.FileFragment$ContainerActivity.getStorageManager()' on a null object reference
	at com.owncloud.android.ui.fragment.FileDetailFragment.updateFileDetails(FileDetailFragment.java:555)
	at com.owncloud.android.ui.activity.FileDisplayActivity.refreshSecondFragment(FileDisplayActivity.java:754)
	at com.owncloud.android.ui.activity.FileDisplayActivity$DownloadFinishReceiver.onReceive(FileDisplayActivity.java:1555)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_51615(LoadedApk.java:1304)
	... 9 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: motorola
Device: addison
Model: XT1635-02
Id: OPNS27.76-12-22-9
Product: addison

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: 10
```

**Comment by tobiasKaminsky** [comment]
Is this happening often?
From stacktrace (thanks for that!) it seems that you maybe navigated directly back from detail view, so e.g.
- open file detail
- while loading press back

I suspect that this can happen if the internet connection is very bad…

**Comment by Entepotenz** [comment]
It was happening while I needed my nextcloud app with some time pressure. So I executed the same steps for different files and each time the app crashed.

> - open file detail
> - while loading press back
is very close to what I am remembering of my steps.

I don't think a slow internet connection caused this, because my nextcloud instance is running in my wifi and I was connected by the same wifi.
But my nextcloud runs on a Raspberry Pi 2 so the system is not very responsive.
Though might result in the same behavior.

**Comment by tobiasKaminsky** [comment]
Can you verify if this happens, when you do


> * open file detail
> 
> * while loading press back

but with waiting until file detail is really completed loading? e.g. 20s?
