### ISSUE TITLE
Android client crashes on opening a folder that contained a folder transferred to another user

### ISSUE THREAD

**Issue by sgaduuw** [nextcloud/android#5749]
### Steps to reproduce
1. Open client 
2. Enter InstantUpload, which housed the folder transfered to another user
3. Wait for client to finish loading InstantUpload, where it crashes

### Expected behaviour
- Tell us what should happen 
Folder should load without client crashing 

### Actual behaviour
- Tell us what happens
Client shows a seemingly cached view of the InstantUpload folder. I see a folder called `tmp` which had been transferred to another user 1 or 2 weeks prior. The loading animation starts to drop frames until the client crashes. 

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 9

Device model: oneplus 5

Stock or customized system: stock 

Nextcloud app version: f-droid 3.10.1

Nextcloud server version: 18.0.3

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=3555, totalRows=1041
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:859)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:157)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:128)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:237)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:269)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:190)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:327)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:669)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:344)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:474)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:1705)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:407)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:478)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:369)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:228)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:357)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus5
Model: ONEPLUS A5000
Id: PKQ1.180716.001
Product: OnePlus5

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 2002242003
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
> Row too big to fit into CursorWindow

How many files are in this folder?

**Comment by sgaduuw** [comment]
> > Row too big to fit into CursorWindow
> 
> How many files are in this folder?
That is the funny thing. After transferring, the folder has been emptied by the recipient. 
I can also no longer find it physically on disk, server side.

**Comment by sgaduuw** [comment]
Originally, the tmp folder was about 4000-4500 files, totalling 58Gb

**Comment by sgaduuw** [comment]
I have captured a screen recording of the event
https://imgur.com/a/ZgsgetB
