### ISSUE TITLE
Android app crash log 

### ISSUE THREAD

**Issue by maltokyo** [nextcloud/android#5753]
Android app crash:

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'long com.owncloud.android.datamodel.OCFile.getParentId()' on a null object reference
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:410)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:369)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:228)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:181)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:268)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.onPerformSync(FileSyncAdapter.java:180)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:334)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: davinci
Model: Mi 9T
Id: QKQ1.190825.002
Product: davinci

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V11.0.4.0.QFJMIXM

**Comment by tobiasKaminsky** [comment]
Do you know when this is happening?
Is this happening reliable? At which folder?

**Comment by maltokyo** [comment]
When I was logging OUT of the app as I wanted to sign in with a different user.

**Comment by maltokyo** [comment]
Not sure what else I can add

**Comment by tobiasKaminsky** [comment]
i tried to reproduce it, but for me it was working :/
Did it happen again for you?
