### ISSUE TITLE
App cras

### ISSUE THREAD

**Issue by kofe88** [nextcloud/android#5767]
### Steps to reproduce
1. Install
2. Login
3. Crash

### Expected behaviour
************ CAUSE OF ERROR ************

android.database.SQLException: ERROR content://org.nextcloud/file
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:287)
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:255)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:266)
	at android.content.ContentResolver.insert(ContentResolver.java:1594)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFile(FileDataStorageManager.java:247)
	at com.owncloud.android.datamodel.FileDataStorageManager.createRootDir(FileDataStorageManager.java:894)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:110)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2582)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1395)
	at android.app.Activity.performStart(Activity.java:7348)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3145)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7078)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a7y18lte
Model: SM-A750FN
Id: PPR1.180610.011
Product: a7y18lteser

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: A750FNPUS4BTB2

**Comment by tobiasKaminsky** [comment]
Hm, crashing while storing data in database…
Is the app on internal storage? 
Is enough space left?

**Comment by kofe88** [comment]
> Hm, crashing while storing data in database…
> Is the app on internal storage?
> Is enough space left?

Greetings! The app is installed on internal storage, not on an SD card. There is still 2 GB of free space out of 64 GB.
