### ISSUE TITLE
Enregistrer une copie d'un pdf sur kdrive depuis Adobe Acrobat (pro)

### ISSUE THREAD

**Issue by jerja** [nextcloud/android#5768]
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Do not call this method before initializing mStorageManager
	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.initTargetFolder(ReceiveExternalFilesActivity.java:992)
	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onStart(ReceiveExternalFilesActivity.java:241)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1392)
	at android.app.Activity.performStart(Activity.java:7172)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2967)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6854)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)

************ APP INFORMATION ************
ID: com.infomaniak.drive
Version: 30110090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: lge
Device: judyln
Model: LM-G710
Id: PKQ1.181105.001
Product: judyln_lao_com

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 200351439dbaf.FGN

**Comment by jerja** [comment]
(Adobe acrobate version mobile android)
