### ISSUE TITLE
Android sharing error

### ISSUE THREAD

**Issue by Raymo111** [nextcloud/android#5777]
### Steps to reproduce
1. Tap the share icon on a file
2. Tap share
3. Search for a user and press enter

### Expected behaviour
The user should be found

### Actual behaviour
Crash with error:
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to read from field 'com.owncloud.android.lib.resources.files.SearchRemoteOperation$SearchType com.owncloud.android.ui.events.SearchEvent.searchType' on a null object reference
	at com.owncloud.android.ui.activity.FileDisplayActivity.onNewIntent(FileDisplayActivity.java:526)
	at android.app.Activity.performNewIntent(Activity.java:7157)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1366)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1378)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3146)
	at android.app.ActivityThread.performNewIntents(ActivityThread.java:3162)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3179)
	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:49)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: gts210vewifi
Model: SM-T813
Id: PQ3A.190801.002
Product: gts210vewifixx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: ed432962f8
```

**Comment by tobiasKaminsky** [comment]
Thanks for the detailed report :+1: 
I cannot reproduce this. Is this happening reliable?

**Comment by Raymo111** [comment]
No worries. Pretty much constantly. It works when I just type the name and wait, but crashes immediately on enter. I'll try to do a screen record.

**Comment by Raymo111** [comment]
@tobiasKaminsky Here's the screen record:
https://www.youtube.com/watch?v=7x9Xsrxm5Gs

**Comment by tobiasKaminsky** [comment]
If you do not click enter, but click on the user name (sophie), does it then do the sharing correctly?

**Comment by Raymo111** [comment]
@tobiasKaminsky Yeah it works fine that way.

**Comment by tobiasKaminsky** [comment]
Confirmed :+1: 
If we have a text and click enter before search result is returned, FDA tries to catch and parse the search…

**Comment by Raymo111** [comment]
Great! @tobiasKaminsky thanks for fixing :)
