### ISSUE TITLE
Crash on auto uploaf

### ISSUE THREAD

**Issue by FlyingEagle** [nextcloud/android#5787]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.files.services.FileUploaderUPLOADS_ADDED flg=0x10 pkg=com.nextcloud.client } in com.owncloud.android.ui.activity.UploadListActivity$UploadMessagesReceiver@9d96d7c
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52226(LoadedApk.java:1329)
	at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.$m$0(Unknown Source:4)
	at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.run(Unknown Source:0)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.owncloud.android.db.OCUpload.setDataFixed(com.owncloud.android.files.services.FileUploader$FileUploaderBinder)' on a null object reference
	at com.owncloud.android.ui.adapter.UploadListAdapter$UploadGroup.fixAndSortItems(UploadListAdapter.java:842)
	at com.owncloud.android.ui.adapter.UploadListAdapter$1.refresh(UploadListAdapter.java:194)
	at com.owncloud.android.ui.adapter.UploadListAdapter.loadUploadItemsFromDb(UploadListAdapter.java:718)
	at com.owncloud.android.ui.activity.UploadListActivity$UploadMessagesReceiver.onReceive(UploadListActivity.java:394)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52226(LoadedApk.java:1319)
	... 9 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: herolte
Model: SM-G930F
Id: R16NW
Product: heroltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: G930FXXS7ESL9

**Comment by tobiasKaminsky** [comment]
When does this happen?

**Comment by FlyingEagle** [comment]
All the time i removed the app now

**Comment by tobiasKaminsky** [comment]
Sorry to hear :/
Is it happening after a new installation?
