### ISSUE TITLE
Caused by: java.lang.SecurityException: Caller no longer running

### ISSUE THREAD

**Issue by gundesli** [nextcloud/android#5805]
### Steps to reproduce
When Nextcloud synchronise my mobile it crashes sometimes.

### Expected behaviour

************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.SecurityException: Caller no longer running, last stopped +2s161ms because: timed out while starting
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:195)
	at android.app.job.JobParameters.dequeueWork(JobParameters.java:243)
	at androidx.core.app.JobIntentService$JobServiceEngineImpl.dequeueWork(JobIntentService.java:315)
	at androidx.core.app.JobIntentService.dequeueWork(JobIntentService.java:640)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:390)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobServiceContext.assertCallerLocked(JobServiceContext.java:481)
	at com.android.server.job.JobServiceContext.doDequeueWork(JobServiceContext.java:359)
	at com.android.server.job.JobServiceContext$JobCallback.dequeueWork(JobServiceContext.java:160)
	at android.app.job.IJobCallback$Stub.onTransact(IJobCallback.java:83)
	at android.os.Binder.execTransact(Binder.java:731)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Nokia
Device: A1N_sprout
Model: Nokia 8 Sirocco
Id: PPR1.180610.011
Product: Avenger_00WW

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 00WW_4_14M

**Comment by tobiasKaminsky** [comment]
This will be fixed via #5679

**Comment by tobiasKaminsky** [comment]
Might also be: https://issuetracker.google.com/issues/63622293

**Comment by InfamousUser** [comment]
Issues with autoupload, crashes in background and this error appears on simply opening the app.

************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.SecurityException: Caller no longer running, last stopped +2s397ms because: timed out while starting
	at android.os.Parcel.createException(Parcel.java:2071)
	at android.os.Parcel.readException(Parcel.java:2039)
	at android.os.Parcel.readException(Parcel.java:1987)
	at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:292)
	at android.app.job.JobParameters.dequeueWork(JobParameters.java:248)
	at androidx.core.app.JobIntentService$JobServiceEngineImpl.dequeueWork(JobIntentService.java:315)
	at androidx.core.app.JobIntentService.dequeueWork(JobIntentService.java:640)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:390)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobServiceContext.assertCallerLocked(JobServiceContext.java:493)
	at com.android.server.job.JobServiceContext.doDequeueWork(JobServiceContext.java:371)
	at com.android.server.job.JobServiceContext$JobCallback.dequeueWork(JobServiceContext.java:160)
	at android.app.job.IJobCallback$Stub.onTransact(IJobCallback.java:169)
	at android.os.Binder.execTransactInternal(Binder.java:1021

**Comment by InfamousUser** [comment]
The issue stated in this issue appears to be fixed with 3.11.1 RC1.
However, now it crashes when entering uploads from the menu. Serial crashes - it does not crash only once or twice, it crashes 5-10 times before opening finally.

**Comment by tobiasKaminsky** [comment]
Can you try out our dev version (you can install it in parallel): 
https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#developement-release

**Comment by InfamousUser** [comment]
I'd gladly help testing but this is a separate app and these crashes don't happen with fresh install, it needs old data and I cannot get old data since this is a different app.

**Comment by tobiasKaminsky** [comment]
A bit background: we suspect that our background library (evernote) is causing this.
Chris (@ezaquarii) did an amazing job to get rid of evernote, but it will only be in 3.13, or already now in dev version.

So we expect this still to happen on some Android >=9 with 3.12, but not with dev/3.13.
Therefore I close this.
If it happens with 3.13 then we have to re-open it.

**Comment by InfamousUser** [comment]
Cannot even open the app anymore with 3.12.1 RC1, I haven't been able to use the app for my own cloud for months now... I hope 3.13 comes soon...

**Comment by tobiasKaminsky** [comment]
RC1 of 3.13 is planned for 22.07.

**Comment by AndyScherzinger** [comment]
> Cannot even open the app anymore with 3.12.1 RC1, I haven't been able to use the app for my own cloud for months now... I hope 3.13 comes soon...

That sounds like a different issue than the one discussed here, so I'd not be to positive that 3.13 will fix the issue without knowing the matter that leads to your scenario "Cannot even open the app anymore"

**Comment by InfamousUser** [comment]
Waiting for 22.07. then, 3 weeks. I can't open the app because this doInBackground() error shows up every time, it used to open up but crash sometimes, now it's every time.

************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.SecurityException: Caller no longer running, last stopped +4s4ms because: timed out while starting
	at android.os.Parcel.createException(Parcel.java:2071)
	at android.os.Parcel.readException(Parcel.java:2039)
	at android.os.Parcel.readException(Parcel.java:1987)
	at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:292)
	at android.app.job.JobParameters.dequeueWork(JobParameters.java:248)
	at androidx.core.app.JobIntentService$JobServiceEngineImpl.dequeueWork(JobIntentService.java:315)
	at androidx.core.app.JobIntentService.dequeueWork(JobIntentService.java:640)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:390)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobServiceContext.assertCallerLocked(JobServiceContext.java:493)
	at com.android.server.job.JobServiceContext.doDequeueWork(JobServiceContext.java:371)
	at com.android.server.job.JobServiceContext$JobCallback.dequeueWork(JobServiceContext.java:160)
	at android.app.job.IJobCallback$Stub.onTransact(IJobCallback.java:169)
	at android.os.Binder.execTransactInternal(Binder.java:1021)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky this crash coming up every time when the app gets opened, any idea why that is?!

**Comment by tobiasKaminsky** [comment]
When the app opens we schedule some background job. And they seem to have problems on specific devices.

**Comment by InfamousUser** [comment]
Does this mean it is not the issue that's going to be fixed in 3.13 but something else?

**Comment by AndyScherzinger** [comment]
I am unsure actually while @tobiasKaminsky believes this is fixed with 3.13 so we probably have to see and wait for your feedback when 3.13 is out. 😔

**Comment by InfamousUser** [comment]
Alright then, thanks for the reply. All bets are on 3.13 RC1.

**Comment by tobiasKaminsky** [comment]
Yes 3.13 should fix it.
