### ISSUE TITLE
Sharing image without signing in (Crash)

### ISSUE THREAD

**Issue by Lennerados** [nextcloud/android#5807]
### Steps to reproduce
1. Just downloaded the app without opening it
2. Open default Samsung gallery
3. Try to share an image via the share context menu to Nextcloud
4. Nextcloud app opens with a crash

### Expected behaviour
- Some warning should appear, that I have not added a Server yet

### Actual behaviour
- App crashed with the error log below

### Can you reproduce this problem on https://try.nextcloud.com?
Is an android app, so no

### Environment data
Android version: 10

Device model: SM-G970F (Samsungs S10e)

Stock or customized system: Stock

Nextcloud app version: 30110090

Nextcloud server version: -

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Do not call this method before initializing mStorageManager
	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.initTargetFolder(ReceiveExternalFilesActivity.java:992)
	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onStart(ReceiveExternalFilesActivity.java:241)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
	at android.app.Activity.performStart(Activity.java:8004)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3471)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2146)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7777)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: beyond0
Model: SM-G970F
Id: QP1A.190711.020
Product: beyond0lteeea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G970FXXS4BTB3
```

**Comment by AndyScherzinger** [comment]
@ezaquarii fancy taking a look if this can/should be migrated to the new user model implementation.

Else the actual solution would be to call the accountManager and check the length of the account list like
```
if (mAccountManager.getAccountsByType(MainApp.getAccountType(this)).length < 1;) {
    DialogNoAccount dialog = new DialogNoAccount();
    dialog.show(getSupportFragmentManager(), null);
}
```

**Comment by tobiasKaminsky** [comment]
> @ezaquarii fancy taking a look if this can/should be migrated to the new user model implementation.

This can be done independent from the bug fix.
