### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by mschm05** [nextcloud/android#5819]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by mschm05** [comment]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'com.owncloud.android.lib.resources.status.CapabilityBooleanType com.owncloud.android.lib.resources.status.OCCapability.getRichDocuments()' on a null object reference
	at com.owncloud.android.ui.fragment.OCFileListBottomSheetDialog.onCreate(OCFileListBottomSheetDialog.java:129)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:494)
	at android.app.Dialog.show(Dialog.java:342)
	at com.owncloud.android.ui.fragment.OCFileListFragment.lambda$registerFabListener$0$OCFileListFragment(OCFileListFragment.java:414)
	at com.owncloud.android.ui.fragment.-$$Lambda$OCFileListFragment$5sYn_weuHLwdJKK5Y47NrF9_UbA.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:6897)
	at android.view.View$PerformClick.run(View.java:26104)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a5y17lte
Model: SM-A520F
Id: R16NW
Product: a5y17ltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: A520FXXUDCTB1

**Comment by tobiasKaminsky** [comment]
Is this happening reliable?
