### ISSUE TITLE
Netxcloud Error crash on CAT S52

### ISSUE THREAD

**Issue by ruehlep** [nextcloud/android#5831]
### Steps to reproduce
1. open the app
2. type in server
3. sign n with credentials

### Expected behaviour
- open the app to work with it

### Actual behaviour
- the app crashes

### Environment data
Android version: 
Android 9

Device model: CAT S52
Brand: Cat
Device: CatS52
Model: S52
Id: PPR1.180610.011
Product: S52_EEA
SDK: 28
Release: 9
Incremental: LTE_D0201121.E_S52_0.020.01

Nextcloud app version:
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

Nextcloud server version:
17.0.2

#### Nextcloud log (data/nextcloud.log)
```

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED flg=0x10 pkg=com.nextcloud.client (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver@b026e1f
at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1401)
at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6702)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:511)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=11498, uid=1110123 requires android.permission.BROADCAST_STICKY
at android.os.Parcel.createException(Parcel.java:1950)
at android.os.Parcel.readException(Parcel.java:1918)
at android.os.Parcel.readException(Parcel.java:1868)
at android.app.IActivityManager$Stub$Proxy.unbroadcastIntent(IActivityManager.java:3896)
at android.app.ContextImpl.removeStickyBroadcast(ContextImpl.java:1347)
at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
at com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver.onReceive(FileDisplayActivity.java:1408)
at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1391)
... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
at com.android.server.am.ActivityManagerService.unbroadcastIntent(ActivityManagerService.java:22264)
at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:183)
at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3350)
at android.os.Binder.execTransact(Binder.java:731)

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Hi @ruehlep,

looking at 
```
requires android.permission.BROADCAST_STICKY
```

from the log file you posted: Are you using Android for work or profiles in general? 
Both being unsupported by the app which will lead to crashes.

**Comment by ruehlep** [comment]
Hi @AndyScherzinger, 

We are using Android for work activation on all of our devices:
Samsung Galaxy A50, A51, S10; Blackberry Motion; CAT S41. 
On all devices Nextcloud-App works without any crashes or bugs.

**Comment by tobiasKaminsky** [comment]
AfW is known by us to work unreliable.
If its working on CAT S41, it is maybe due to another Android version.

**Comment by ruehlep** [comment]
Hello tobiasKaminsky, 

Yes, that could be the case. 
The CAT S41 is running a old Android 8 version, the CAT S52 Android 9.
What I wonder: we is it working on Samsung Android 9 without any errors?

**Comment by tobiasKaminsky** [comment]
As far as I know Samsung have patched out the support of mutliple users, and I guess that this change also somehow "fixed" the problem…

As Andy says, this is currently unsupported and we don't have support for it on our current roadmap. We would accept patches, if you feel like developing this feature.

If you can't develop it yourself you can of course also contact our sales team and become a customer - we develop features our customers need...

**Comment by AndyScherzinger** [comment]
Duplicate of #6654
