### ISSUE TITLE
Force close on single sign on with nextcloud client (android)

### ISSUE THREAD

**Issue by smaugilein** [nextcloud/android#5859]
### Steps to reproduce
1. Install "Nextcloud News" 
2. Start App
3. Choose "Single sign on", account and click ok

### Expected behaviour
Nextcloud app should grant permission for News App 

### Actual behaviour
Directly force close on clicking OK. Restricted to (unrooted, unmodded) Samsung Tablet. Modded phone is pretty fine.

### Environment data
Android version: 7

Device model: Samsung Sm-T715

Stock or customized system: stock

Nextcloud app version: see log

### Logs
Nextcloud app closes with this report:
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.SsoGrantPermissionActivity}: java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.accounts.Account.name' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2981)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3042)
	at android.app.ActivityThread.-wrap14(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1639)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6780)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1500)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1390)
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.accounts.Account.name' on a null object reference
	at com.owncloud.android.ui.activity.SsoGrantPermissionActivity.onCreate(SsoGrantPermissionActivity.java:107)
	at android.app.Activity.performCreate(Activity.java:6948)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2924)
	... 9 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: gts28lte
Model: SM-T715
Id: NRD90M
Product: gts28ltexx

************ FIRMWARE ************
SDK: 24
Release: 7.0
Incremental: T715XXU2CRH1

**Comment by smaugilein** [comment]
News app is https://play.google.com/store/apps/details?id=de.luhmer.owncloudnewsreader

**Comment by tobiasKaminsky** [comment]
Do you have any account in your NC files app?

**Comment by smaugilein** [comment]
Two, in fact. The fc occurs on both accounts.

**Comment by tobiasKaminsky** [comment]
@David-Development do you have an idea?

Here we do check if account exists…
https://github.com/nextcloud/Android-SingleSignOn/blob/master/src/main/java/com/nextcloud/android/sso/AccountImporter.java#L367

**Comment by David-Development** [comment]
@smaugilein What is the Version of the Nextcloud News App? Maybe you can test if the beta version of the nextcloud news app works for you? 

@tobiasKaminsky Ugh.. 😅 Looks like it is not picking up that account.. right? Maybe some permission issues..?  Maybe it's just a problem with the stable version of the news app because it is using a quite old version of the sso library.. Maybe I should push the beta to stable soon 🙈

**Comment by tobiasKaminsky** [comment]
Would be worth a try :-)

**Comment by smaugilein** [comment]
@David-Development I got the latest version from the Google play store. V0.9.9.25.
Thanks for caring!

**Comment by smaugilein** [comment]
Ok, the beta is working like expected. Seems to be a news app (stable) related problem. Thank you so much for your help!

**Comment by tobiasKaminsky** [comment]
Glad that it is working.
