### ISSUE TITLE
NextCloud Android App Crash

### ISSUE THREAD

**Issue by GabrielSturtevant** [nextcloud/android#5869]
I am creating this at the behest the app after it crashed.

I simply rebooted my phone, and tried to start NextCloud. The app wouldn't start, then showed me this crash report. This was also the first time I restarted my phone since installing the app. Also, since this error occurred, I have been unable to start NextCloud and my phone has become extremely sluggish and unresponsive.

Phone: LG-H918 (TMobile LG V20)
OS: Android 8.0.0
Kernel: 3.18.71

Let me know if I can provide any other info.

************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.SecurityException: Caller no longer running, last stopped +14s12ms because: timed out while starting
	at android.os.Parcel.readException(Parcel.java:1943)
	at android.os.Parcel.readException(Parcel.java:1889)
	at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:191)
	at android.app.job.JobParameters.dequeueWork(JobParameters.java:196)
	at androidx.core.app.JobIntentService$JobServiceEngineImpl.dequeueWork(JobIntentService.java:315)
	at androidx.core.app.JobIntentService.dequeueWork(JobIntentService.java:640)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:390)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: lge
Device: elsa
Model: LG-H918
Id: OPR1.170623.032
Product: elsa_tmo_us

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: 1831917495b33

**Comment by tobiasKaminsky** [comment]
this should be fixed via #5679
