### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by TimvHerpen** [nextcloud/android#5880]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
	at android.widget.Toast$TN.<init>(Toast.java:411)
	at android.widget.Toast.<init>(Toast.java:121)
	at android.widget.Toast.makeText(Toast.java:286)
	at android.widget.Toast.makeText(Toast.java:276)
	at android.widget.Toast.makeText(Toast.java:315)
	at com.owncloud.android.ui.activity.ConflictsResolveActivity.showErrorAndFinish(ConflictsResolveActivity.java:229)
	at com.owncloud.android.ui.activity.ConflictsResolveActivity.lambda$onStart$0$ConflictsResolveActivity(ConflictsResolveActivity.java:192)
	at com.owncloud.android.ui.activity.-$$Lambda$ConflictsResolveActivity$EM0Z1Vrhvmim7X4XXFnNqL4vK1A.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: raphael
Model: Mi 9T Pro
Id: QKQ1.190825.002
Product: raphael_eea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V11.0.5.0.QFKEUXM

**Comment by tobiasKaminsky** [comment]
This will be fixed with upcoming 3.11.1 version via https://github.com/nextcloud/android/pull/5822
