### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by wasprtandrey** [nextcloud/android#5903]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{ru.sberdisk/com.owncloud.android.ui.activity.SyncedFoldersActivity}: java.lang.IllegalArgumentException: Invalid column Distinct bucket_id
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3304)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3443)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7520)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.IllegalArgumentException: Invalid column Distinct bucket_id
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
	at android.content.ContentResolver.query(ContentResolver.java:946)
	at android.content.ContentResolver.query(ContentResolver.java:881)
	at android.content.ContentResolver.query(ContentResolver.java:837)
	at com.owncloud.android.datamodel.MediaProvider.getImageFolders(MediaProvider.java:81)
	at com.owncloud.android.ui.activity.SyncedFoldersActivity.load(SyncedFoldersActivity.java:251)
	at com.owncloud.android.ui.activity.SyncedFoldersActivity.setupContent(SyncedFoldersActivity.java:238)
	at com.owncloud.android.ui.activity.SyncedFoldersActivity.onCreate(SyncedFoldersActivity.java:164)
	at android.app.Activity.performCreate(Activity.java:7893)
	at android.app.Activity.performCreate(Activity.java:7880)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3279)
	... 11 more

************ APP INFORMATION ************
ID: ru.sberdisk
Version: 30191199
Build flavor: prod

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: pyxis
Model: Mi 9 Lite
Id: QKQ1.190828.002
Product: pyxis_eea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V11.0.1.0.QFCEUXM

**Comment by tobiasKaminsky** [comment]
> ID: ru.sberdisk

That is not us, please open an issue on their repo.
