### ISSUE TITLE
Nextcloud app crash

### ISSUE THREAD

**Issue by seekjimmyg** [nextcloud/android#5914]
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Not allowed to start service Intent { act=SYNC_FOLDER cmp=com.nextcloud.client/com.owncloud.android.services.OperationsService (has extras) }: app is in background uid UidRecord{7cd4ff2 u0a169 LAST bg:+1m42s188ms idle change:cached procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1666)
	at android.app.ContextImpl.startService(ContextImpl.java:1611)
	at android.content.ContextWrapper.startService(ContextWrapper.java:677)
	at com.owncloud.android.operations.SynchronizeFolderOperation.startSyncFolderOperation(SynchronizeFolderOperation.java:497)
	at com.owncloud.android.operations.SynchronizeFolderOperation.prepareOpsFromLocalKnowledge(SynchronizeFolderOperation.java:373)
	at com.owncloud.android.operations.SynchronizeFolderOperation.run(SynchronizeFolderOperation.java:142)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:181)
	at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:87)
	at com.owncloud.android.services.SyncFolderHandler.doOperation(SyncFolderHandler.java:119)
	at com.owncloud.android.services.SyncFolderHandler.handleMessage(SyncFolderHandler.java:88)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:65)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110151
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: gts4lwifi
Model: SM-T830
Id: PPR1.180610.011
Product: gts4lwifixx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: T830XXU4BTB2

# Steps to reproduce
1. Open nextcloud app on tablet
2. Choose folder
3. Click sync and after sometime it shows the error above.

### Expected behaviour
- no errors. Due to large number of files I can't really tell if the files were actually synced.

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Can you test the beta version, which is available via gplay beta track?

**Comment by seekjimmyg** [comment]
The app version on gplay store says 3.11.1 RC1, which I believe is Beta

**Comment by tobiasKaminsky** [comment]
Yes, this is the beta. 
Is it working there?
