### ISSUE TITLE
Bug Nextcloud Android

### ISSUE THREAD

**Issue by BugProg** [nextcloud/android#5920]
Hello everyone !

I have this bug at each boot on my phone and I can't run the app.

************ CAUSE OF ERROR ************

java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1677)
	at android.app.ContextImpl.bindService(ContextImpl.java:1612)
	at android.content.ContextWrapper.bindService(ContextWrapper.java:698)
	at com.google.android.gms.common.stats.ConnectionTracker.zza(Unknown Source:22)
	at com.google.android.gms.common.stats.ConnectionTracker.bindService(Unknown Source:24)
	at com.google.firebase.iid.zzaf.zza(com.google.firebase:firebase-iid@@20.1.2:17)
	at com.google.firebase.iid.zzad.zza(com.google.firebase:firebase-iid@@20.1.2:16)
	at com.google.firebase.iid.zzad.zzb(com.google.firebase:firebase-iid@@20.1.2:13)
	at com.google.firebase.iid.zzax.zza(com.google.firebase:firebase-iid@@20.1.2:81)
	at com.google.firebase.iid.zzs.zza(com.google.firebase:firebase-iid@@20.1.2:90)
	at com.google.firebase.iid.zzv.run(Unknown Source:12)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus5T
Model: ONEPLUS A5010
Id: PQ3A.190605.003
Product: OnePlus5T

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 7ec472ea7a

**Comment by BugProg** [comment]
I am on Lineage os Android 9 with microG.

**Comment by tobiasKaminsky** [comment]
Sorry, no idea.
I fear this is something with LineageOS and/or microG.

> com.google.android.gms

Maybe they have removed it somehow?
Please ask over there.

(I for myself also use MircoG with LineageOS 10 on a OnePlus6T without any problems).

**Comment by BugProg** [comment]
Hello,

Thank you for your answer, yes indeed it comes from microG
