### ISSUE TITLE
App crashes when opening folder that contains subfolder with many files

### ISSUE THREAD

**Issue by slovdahl** [nextcloud/android#5926]
### Steps to reproduce

This is what I think happened. I haven't had the chance to try to reliably reproduce yet, but if someone wants me to, I could give it a try. Anyway, here goes:

1. Create a folder `foo` and a subfolder `bar` inside it
1. Create a huge number of files (4700+ in my case, doesn't have to be done on Android) in `bar`
1. Open `foo` and `bar` in the Android app so it's cached. 
1. On another device (or in the web GUI), create a new subfolder in `foo` called `baz` and move `bar` into `baz`. 
1. Open `foo` in the Android app again, and it crashes.

************ CAUSE OF ERROR ************

```
android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=3157, totalRows=1560
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:942)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:161)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:131)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:249)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:281)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:191)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:135)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:185)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:135)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:115)
	at android.content.ContentProviderOperation.applyInternal(ContentProviderOperation.java:342)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:314)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:671)
	at android.content.ContentProvider.applyBatch(ContentProvider.java:2179)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:398)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:532)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:520)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:1915)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:407)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:478)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:369)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:228)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:357)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus8Pro
Model: IN2023
Id: QKQ1.191222.002
Product: OnePlus8Pro_EEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2004111413
```

### Expected behaviour

The app shouldn't crash. 

### Actual behaviour

The app crashes over and over again when opening the `foo` folder. 

### Environment data
Android version: 10

Device model: OnePlus 8 Pro

Stock or customized system: stock

Nextcloud app version: 3.11.1

Nextcloud server version: 18.0.3

Reverse proxy: nginx

**Comment by slovdahl** [comment]
Clearing the cached data of the Android app didn't help.

**Comment by tobiasKaminsky** [comment]
Thanks for the clear way on how to reproduce the issue.
I will try it soon.

**Comment by slovdahl** [comment]
Thank you! Bear in mind that this happened in a real scenario and is what I think happened. If you aren't able to reproduce it yourself, I could try to artificially reproduce it myself as well.

**Comment by tobiasKaminsky** [comment]
I created now a test which fails with same error message like you have.

This fails reliable if count is >= 5000;
https://github.com/nextcloud/android/pull/5918/files#diff-7146121379c37c7fda4c6542bdd37597R63

**Comment by Octav14n** [comment]
I had the same problem.
Deleting all data and syncing it again works as a workaround for me.

**Comment by ggogel** [comment]
I just experienced this issue. I wasn't able to reset the app entirely. Even after I re-installed it and deleted the app data several times, it showed a folder in the root of my data after opening the app, which I had recently deleted via the web-interface. Only after I recreated the folder on the web-interface, then went into the app and deleted it there, the issue was gone. I've never experienced something like this, where the data of an app couldn't be cleared entirely. This is unacceptable and makes the simple workaround of just resetting the app impossible.
OnePlus 8T
Android 11

**Comment by ggogel** [comment]
Never mind, after deleting the folder it's crashing again!

**Comment by jdaviescoates** [comment]
I've deleted my offending folder via the web, but it's still showing up in the Android app and so whenever I access the folder that had the offending folder the app still crashes. How can I get the app to update and no keep trying to show me the deleted folder?!?

**Comment by Tanman897** [comment]
How is it that this widespread app-crashing bug hasn't been fixed almost two years after it was first posted?

**Comment by jdaviescoates** [comment]
> I've deleted my offending folder via the web, but it's still showing up in the Android app and so whenever I access the folder that had the offending folder the app still crashes. How can I get the app to update and no keep trying to show me the deleted folder?!?

I had to uninstall and reinstall the Nextcloud app on my phone to resolve this.

**Comment by Tanman897** [comment]
Again, I don't understand why developers are completely silent on this issue. There is not even an acknowledgement or progress comment on this issue literally **_ever_** for years now. My only possible workaround would be to break up large folders into several smaller ones, a process which would take me hours and hours and mess up my photo library organization. This bug ruins my Nextcloud user experience on a daily basis.

**Comment by svenb1234** [comment]
The usual answer is: if you want support, you have to get the enterprise edition or fix it yourself. You get it for free, so...

IMHO not many nextcloud developers use Nextcloud (Android) for their private life. Otherwise many bugs would not stay unnoticed (for that long). 

Even regressions are not fixed quickly. Example #9328 

On the other hand, if developers create a photo gallery  app which does not use the photos' creation date but the file date, you must not wonder about anything, really.

**Comment by Tanman897** [comment]
@AlvaroBrey I think you fudged on this merge since you seemed to be merging other related issues into this one before and now you just merged this one into a completely unrelated issue in any way. Please re-open this issue as it does not resemble the merged issue.

**Comment by Tanman897** [comment]
@svenb1234, do you have any suggestions for an alternative document and photo sync solution (across devices) to Google Drive/Photos that can be setup in a way that honor's one's privacy? I am not being facetious; I genuinely would like to know of any legitimate alternatives.

**Comment by tigermick** [comment]
Hi,
I have the same problem.
Any plans to correct this bug please ?
(I use nextcloud android 3.19.1)

**Comment by rgeber** [comment]
Same problem here. 

```
### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Unable to resume activity {com.nextcloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity}: android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=39, totalRows=40
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4824)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4857)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: Exception in thread "main" android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=39, totalRows=40
    at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
    at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1003)
    at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
    at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
    at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:153)
    at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:123)
    at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:255)
    at android.database.AbstractCursor.moveToNext(AbstractCursor.java:287)
    at android.database.CursorWrapper.moveToNext(CursorWrapper.java:206)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:899)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:189)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:614)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1321)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1269)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1258)
    at com.owncloud.android.ui.fragment.OCFileListFragment.onActivityCreated(OCFileListFragment.java:409)
    at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3137)
    at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:579)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:264)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
    at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:495)
    at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:312)
    at com.owncloud.android.ui.activity.BaseActivity.onResume(BaseActivity.java:91)
    at com.owncloud.android.ui.activity.DrawerActivity.onResume(DrawerActivity.java:973)
    at com.owncloud.android.ui.activity.FileActivity.onResume(FileActivity.java:246)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onResume(FileDisplayActivity.java:1102)
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1488)
    at android.app.Activity.performResume(Activity.java:8197)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4814)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4857)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20221029`
* Build flavor: `versionDev`

### Device information
* Brand: `Xiaomi`
* Device: `apollo`
* Model: `M2007J3SY`
* Id: `SQ3A.220705.004`
* Product: `lineage_apollon`

### Firmware
* SDK: `32`
* Release: `12`
* Incremental: `c38be290f2`
```

@Tanman897 I use syncthing.

**Comment by rgeber** [comment]
Same problem here:

### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Unable to resume activity {com.nextcloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity}: android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=39, totalRows=40
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4824)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4857)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: Exception in thread "main" android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=39, totalRows=40
    at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
    at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1003)
    at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
    at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
    at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:153)
    at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:123)
    at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:255)
    at android.database.AbstractCursor.moveToNext(AbstractCursor.java:287)
    at android.database.CursorWrapper.moveToNext(CursorWrapper.java:206)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:899)
    at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:189)
    at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:614)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1321)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1269)
    at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1258)
    at com.owncloud.android.ui.fragment.OCFileListFragment.onActivityCreated(OCFileListFragment.java:409)
    at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3137)
    at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:579)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:264)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
    at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:495)
    at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:312)
    at com.owncloud.android.ui.activity.BaseActivity.onResume(BaseActivity.java:91)
    at com.owncloud.android.ui.activity.DrawerActivity.onResume(DrawerActivity.java:973)
    at com.owncloud.android.ui.activity.FileActivity.onResume(FileActivity.java:246)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onResume(FileDisplayActivity.java:1102)
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1488)
    at android.app.Activity.performResume(Activity.java:8197)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4814)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4857)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

### App information
* ID: `com.nextcloud.android.beta`
* Version: `20221029`
* Build flavor: `versionDev`

### Device information
* Brand: `Xiaomi`
* Device: `apollo`
* Model: `M2007J3SY`
* Id: `SQ3A.220705.004`
* Product: `lineage_apollon`

### Firmware
* SDK: `32`
* Release: `12`
* Incremental: `c38be290f2`

@Tanman897 Syncthing could be what you're looking for. Running it for years without any issues and large payloads.
