### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ireeus** [nextcloud/android#5939]
### Steps to reproduce
1. The app is set to send pictures and videos to the server
2. Start the app
3. Try to change the stettings of the upload

### Expected behaviour
- should be able to change settings

### Actual behaviour
- crash

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to resume activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.IllegalArgumentException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3627)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3667)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1667)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6651)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
Caused by: java.lang.IllegalArgumentException
	at android.os.Parcel.readException(Parcel.java:2017)
	at android.os.Parcel.readException(Parcel.java:1959)
	at android.app.IActivityManager$Stub$Proxy.isTopOfTask(IActivityManager.java:8449)
	at android.app.Activity.isTopOfTask(Activity.java:6369)
	at android.app.Activity.onResume(Activity.java:1346)
	at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:456)
	at com.owncloud.android.ui.activity.BaseActivity.onResume(BaseActivity.java:91)
	at com.owncloud.android.ui.activity.DrawerActivity.onResume(DrawerActivity.java:1274)
	at com.owncloud.android.ui.activity.FileActivity.onResume(FileActivity.java:218)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onResume(FileDisplayActivity.java:1206)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1356)
	at android.app.Activity.performResume(Activity.java:7196)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3602)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: xiaomi
Device: vince
Model: Redmi 5 Plus
Id: OPM1.171019.019
Product: vince

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: V11.0.2.0.OEGMIXM

Insert your Nextcloud log here
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by ezaquarii** [comment]
@ireeus Did it happen once or more times?

**Comment by ireeus** [comment]
It happened twice to me so far. 
Also i forgot to mention that the uploading process was running in the background.

**Comment by tobiasKaminsky** [comment]
So this is what you did:
- upload a file
- click to suspend the app
- click on upload notification?
-> crash

**Comment by ireeus** [comment]
1. Configured the app to autosync pictures (large number of pictures to autosync - about 1500)
2. Restart the app
3. Go to the autosync configuration of any local folder and try to change the destination folder on the server. 
4. Crash

**Comment by ireeus** [comment]
It looks like the app is freezing and can't continue to execute some lines in the script

**Comment by tobiasKaminsky** [comment]
Hm. I cannot reproduce it :/

**Comment by ireeus** [comment]
Maybe it's just my phone struggling with the app. Because I have noticed that the app is a bit slow. Loading folders slowly, executing tasks in general very slow. And I'm comparing it to the Owncloud which is working much faster but probably isn't that advance as NC
