### ISSUE TITLE
Nextcloud server is not configured during upload

### ISSUE THREAD

**Issue by stalker314314** [nextcloud/android#5940]
### Steps to reproduce
1. Random files (every 30-50 photos/videos) are persistently failing to be uploaded (automatic upload). I didn't figure out pattern. When new photo is taken, it is uploaded correctly, and only bogus images/videos stay in queue.

It kind of looks like #3556, but my status.php returns properly (installed, not in maintenance mode, no need for DB upgrade...)

If I do manual upload of same file to same location, it works.

### Expected behaviour
- Files should be uplaoded automatically

### Actual behaviour
- Image/video is in "Error\Wait next start"

### Environment data
Android version: 8

Device model: Xiaomi Mi

Stock or customized system: Lineage OS

Nextcloud app version: 3.11.0

Nextcloud server version: 18.0.3.0

Reverse proxy: No

### Logs

```
2020-04-25 14:41:34.574 12998-12998/com.nextcloud.client D/UploadListAdapter: loadUploadItemsFromDb
2020-04-25 14:41:34.583 12998-16803/com.nextcloud.client D/AdvancedSslSocketFactory: Creating SSL Socket with remote <redacted>:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@7c28fbf
2020-04-25 14:41:34.583 12998-16803/com.nextcloud.client D/AdvancedSslSocketFactory:  ... with connection timeout 0 and socket timeout 0
2020-04-25 14:41:34.588 12998-16803/com.nextcloud.client I/ServerNameIndicator: SNI done, hostname: <redacted>
2020-04-25 14:41:35.585 12998-12998/com.nextcloud.client D/UploadListAdapter: loadUploadItemsFromDb
2020-04-25 14:41:35.600 12998-12998/com.nextcloud.client D/FileUploader: Starting command with id 9
2020-04-25 14:41:35.602 12998-12998/com.nextcloud.client V/UploadsStorageManager: Updating /storage/emulated/0/DCIM/OpenCamera/VID_20200424_173051.mp4 with status=UPLOAD_IN_PROGRESS
2020-04-25 14:41:35.604 12998-12998/com.nextcloud.client D/UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/OpenCamera/VID_20200424_173051.mp4
2020-04-25 14:41:35.604 12998-12998/com.nextcloud.client D/UploadsStorageManager: notifyObserversNow
2020-04-25 14:41:35.608 12998-14661/com.nextcloud.client V/UploadsStorageManager: Updating /storage/emulated/0/DCIM/OpenCamera/VID_20200424_173051.mp4 with status:UPLOAD_IN_PROGRESS and result:UNKNOWN (old:/storage/emulated/0/DCIM/OpenCamera/VID_20200424_173051.mp4 status:UPLOAD_IN_PROGRESS result:-1)
2020-04-25 14:41:35.608 12998-14661/com.nextcloud.client V/UploadsStorageManager: Updating /storage/emulated/0/DCIM/OpenCamera/VID_20200424_173051.mp4 with status=UPLOAD_IN_PROGRESS
2020-04-25 14:41:35.611 12998-14661/com.nextcloud.client D/UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/OpenCamera/VID_20200424_173051.mp4
2020-04-25 14:41:35.611 12998-14661/com.nextcloud.client D/UploadsStorageManager: notifyObserversNow
2020-04-25 14:41:35.620 12998-14661/com.nextcloud.client V/UploadsStorageManager: Updating /storage/emulated/0/DCIM/OpenCamera/VID_20200424_173051.mp4 with status=UPLOAD_IN_PROGRESS
2020-04-25 14:41:35.620 12998-12998/com.nextcloud.client D/UploadListAdapter: loadUploadItemsFromDb
2020-04-25 14:41:35.621 12998-14661/com.nextcloud.client D/UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/OpenCamera/VID_20200424_173051.mp4
2020-04-25 14:41:35.621 12998-14661/com.nextcloud.client D/UploadsStorageManager: notifyObserversNow
2020-04-25 14:41:35.639 12998-14661/com.nextcloud.client D/UploadFileOperation: normal upload
2020-04-25 14:41:35.641 12998-14661/com.nextcloud.client D/AdvancedSslSocketFactory: Creating SSL Socket with remote <redacted>:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@1a68db
2020-04-25 14:41:35.641 12998-14661/com.nextcloud.client D/AdvancedSslSocketFactory:  ... with connection timeout 0 and socket timeout 0
2020-04-25 14:41:35.641 12998-14661/com.nextcloud.client I/ServerNameIndicator: SNI done, hostname: <redacted>
2020-04-25 14:41:35.643 12998-12998/com.nextcloud.client D/UploadListAdapter: loadUploadItemsFromDb
2020-04-25 14:41:36.141 12998-12998/com.nextcloud.client D/FileUploader: Starting command with id 10
2020-04-25 14:41:38.313 12998-14661/com.nextcloud.client D/UploadFileOperation: Checking name collision in server
2020-04-25 14:41:38.314 12998-14661/com.nextcloud.client D/OwnCloudClient #0: REQUEST HEAD /remote.php/webdav/Photos/Phone/VID_20200424_173051.mp4
2020-04-25 14:41:39.044 12998-14661/com.nextcloud.client I/HttpMethodDirector: I/O exception (org.apache.commons.httpclient.NoHttpResponseException) caught when processing request: The server <redacted> failed to respond
2020-04-25 14:41:39.045 12998-14661/com.nextcloud.client I/HttpMethodDirector: Retrying request
2020-04-25 14:41:39.045 12998-14661/com.nextcloud.client D/AdvancedSslSocketFactory: Creating SSL Socket with remote <redacted>:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@6b8b341
2020-04-25 14:41:39.046 12998-14661/com.nextcloud.client D/AdvancedSslSocketFactory:  ... with connection timeout 50000 and socket timeout 60000
2020-04-25 14:41:39.052 12998-14661/com.nextcloud.client I/ServerNameIndicator: SNI done, hostname: <redacted>
2020-04-25 14:41:40.576 12998-14661/com.nextcloud.client D/ExistenceCheckRemoteOperation: Existence check for https://<redacted>/remote.php/webdav/Photos/Phone/VID_20200424_173051.mp4 targeting for  existence finished with HTTP status 404(FAIL)
2020-04-25 14:41:40.591 12998-14661/com.nextcloud.client V/UploadsStorageManager: Updating /storage/emulated/0/DCIM/OpenCamera/VID_20200424_173051.mp4 with status=UPLOAD_IN_PROGRESS
2020-04-25 14:41:40.594 12998-14661/com.nextcloud.client D/UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/OpenCamera/VID_20200424_173051.mp4
2020-04-25 14:41:40.595 12998-14661/com.nextcloud.client D/UploadsStorageManager: notifyObserversNow
2020-04-25 14:41:40.596 12998-14661/com.nextcloud.client D/OwnCloudClient #0: REQUEST MKCOL /remote.php/dav/uploads/<username>/f7ab8055c4678f3a58038a31996018cd
2020-04-25 14:41:42.094 12998-14661/com.nextcloud.client D/OwnCloudClient #0: REQUEST PROPFIND /remote.php/dav/uploads/<username>/f7ab8055c4678f3a58038a31996018cd
2020-04-25 14:41:42.095 12998-14661/com.nextcloud.client D/AdvancedSslSocketFactory: Creating SSL Socket with remote <redacted>:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@1a01eb6
2020-04-25 14:41:42.095 12998-14661/com.nextcloud.client D/AdvancedSslSocketFactory:  ... with connection timeout 60000 and socket timeout 60000
2020-04-25 14:41:42.100 12998-14661/com.nextcloud.client I/ServerNameIndicator: SNI done, hostname: <redacted>
2020-04-25 14:41:42.283 3130-3264/system_process E/LightsService: Light requested not available on this device. 2
2020-04-25 14:41:43.436 12998-14661/com.nextcloud.client E/UploadFileOperation: Upload of /storage/emulated/0/DCIM/OpenCamera/VID_20200424_173051.mp4 to /Photos/Phone/VID_20200424_173051.mp4: The Nextcloud server is not configured!
2020-04-25 14:41:43.437 12998-14661/com.nextcloud.client D/UploadsStorageManager: updateDatabaseUploadResult uploadResult: RemoteOperationResult(mSuccess=false, mHttpCode=500, mHttpPhrase=Internal Server Error, mException=null, mCode=INSTANCE_NOT_CONFIGURED, getLogMessage=The Nextcloud server is not configured!) upload: com.owncloud.android.operations.UploadFileOperation@14cb7b7
2020-04-25 14:41:43.446 12998-14661/com.nextcloud.client V/UploadsStorageManager: Updating /storage/emulated/0/DCIM/OpenCamera/VID_20200424_173051.mp4 with status:UPLOAD_FAILED and result:UNKNOWN (old:/storage/emulated/0/DCIM/OpenCamera/VID_20200424_173051.mp4 status:UPLOAD_IN_PROGRESS result:-1)
2020-04-25 14:41:43.446 12998-14661/com.nextcloud.client V/UploadsStorageManager: Updating /storage/emulated/0/DCIM/OpenCamera/VID_20200424_173051.mp4 with status=UPLOAD_FAILED
2020-04-25 14:41:43.451 12998-14661/com.nextcloud.client D/UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/OpenCamera/VID_20200424_173051.mp4
2020-04-25 14:41:43.451 12998-14661/com.nextcloud.client D/UploadsStorageManager: notifyObserversNow
2020-04-25 14:41:43.453 12998-14661/com.nextcloud.client D/FileUploader: NotifyUploadResult with resultCode: INSTANCE_NOT_CONFIGURED
2020-04-25 14:41:43.461 12998-14661/com.nextcloud.client D/FileUploader: Stopping command after id 9
2020-04-25 14:41:43.462 12998-12998/com.nextcloud.client D/UploadListAdapter: loadUploadItemsFromDb
2020-04-25 14:41:43.467 12998-16809/com.nextcloud.client D/skia: --- Failed to create image decoder with message 'unimplemented'
```

**Comment by tobiasKaminsky** [comment]
> Nextcloud app version: 3.11.0

Please update to latest 3.11.1 as this should fix it.
If not, please re-open.

**Comment by grote** [comment]
I am getting the same issue sometimes on `master`, but had to add extra logging to identify it:

```
2020-08-17 16:49:49.815 E/TEST: getLogMessage: null
2020-08-17 16:49:49.815 E/TEST: getLogMessage: The Nextcloud server is not configured!
2020-08-17 16:49:49.815 E/TEST: getCode: INSTANCE_NOT_CONFIGURED
2020-08-17 16:49:49.816 E/TEST: getHttpCode: 500
2020-08-17 16:49:49.821 E/DatabaseUtils: Writing exception to parcel
    android.os.ParcelableException: java.io.FileNotFoundException: Failed to upload document with path /.SeedVaultAndroidBackup/Wfo06MBIjlYhn0ApHeGXUYfd92ZO8FW6gRCR3GDl2Gfs4kn1VLUwidV6ufBBE0QSZ9vrjgo=INq1YxL40BlUXvPGpZHPcnFgD=l5Jb1oHMGrh8f_y2H+3J5Q+qBEW+0z_c8j_Tj3FEl7qv0C1xCIFlJgiwburLlPQilFqfjfm2RaXqPBosqN4oIewlgPhQFjF1efCTk2rqVyA8E+tpYA9XqrGzZQNKN8RNLrYrZZl+fEj2
        at android.provider.DocumentsProvider.call(DocumentsProvider.java:1069)
        at android.content.ContentProvider.call(ContentProvider.java:2152)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:477)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:277)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
     Caused by: java.io.FileNotFoundException: Failed to upload document with path /.SeedVaultAndroidBackup/Wfo06MBIjlYhn0ApHeGXUYfd92ZO8FW6gRCR3GDl2Gfs4kn1VLUwidV6ufBBE0QSZ9vrjgo=INq1YxL40BlUXvPGpZHPcnFgD=l5Jb1oHMGrh8f_y2H+3J5Q+qBEW+0z_c8j_Tj3FEl7qv0C1xCIFlJgiwburLlPQilFqfjfm2RaXqPBosqN4oIewlgPhQFjF1efCTk2rqVyA8E+tpYA9XqrGzZQNKN8RNLrYrZZl+fEj2
        at com.owncloud.android.providers.DocumentsStorageProvider.createFile(DocumentsStorageProvider.java:547)
        at com.owncloud.android.providers.DocumentsStorageProvider.createDocument(DocumentsStorageProvider.java:460)
```

Seems to happen when the file name is larger when what I assume is allowed by Nextcloud.

**Comment by tobiasKaminsky** [comment]
What does nextcloud server log says?
As the server is thowing 500, which is mostly an internal server problem.

Reading the log I suspect that the file name is a bit too long…?

**Comment by grote** [comment]
So I tried deliberately with a long filename and I am getting 400 Bad Request back from the server. Not the 500 error we saw before. Some other log messages from yesterday:

* "renaming part file to final file failed $renameOkay: false, $fileExists: false)"
* "Could not rename part file to final file"
* "Expected filesize of 10240000 bytes but read (from Nextcloud client) and wrote (to Nextcloud storage) 9437184 bytes.       Could either be a network problem on the sending side or a problem writing to the storage on the server side."

It was probably one of those causing the 500.

Btw. I am still wondering why the file name length limit is at 228, here they seem to indicate it should be 255 as well: https://github.com/nextcloud/server/blob/173f8abc7ed48d2436d8df10ad66bc4907d4bb52/lib/private/Files/Storage/Common.php#L543

**Comment by grote** [comment]
I just could trigger it again, has probably to do with long file names, but still maybe a sub-optimal error message:

```json
{
  "reqId": "C3MZEZ0TVUlMKml9K9iq",
  "level": 4,
  "time": "2020-08-19T18:23:20+00:00",
  "app": "webdav",
  "method": "PUT",
  "url": "/remote.php/webdav/.SeedVaultAndroidBackup/7680425718204950616/kv/org.example/vZkpqCpSOPcdBjTQ5GnSi3oJAv%3DDgAsDJTtfNyjxjvV433HwpNgNOzkDBSo7ZnyarF6jzEA7%2BQYegQuFQOMYu7wF9d_ExcNP0t_FerqCzVzkKF63H_xu5g8nzKpzTE_AYO2JRaQX7%2B0_ZJBEsnHxXXCBXz%3DlNuYM5Q4bqTpWNzaHgGzpv4E4Az_7%3DTXpOLn2cpnmpDFNARhzGvJiFLyPWNN%3DcVFL5pY8uK7A",
  "message": {
    "Exception": "Sabre\\DAV\\Exception",
    "Message": "Could not rename part file to final file",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/local/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php",
        "line": 156,
        "function": "put",
        "class": "OCA\\DAV\\Connector\\Sabre\\File",
        "type": "->",
        "args": [
          null
        ]
      },
      {
        "file": "/var/local/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 1096,
        "function": "createFile",
        "class": "OCA\\DAV\\Connector\\Sabre\\Directory",
        "type": "->",
        "args": [
          "vZkpqCpSOPcdBjTQ5GnSi3oJAv=DgAsDJTtfNyjxjvV433HwpNgNOzkDBSo7ZnyarF6jzEA7+QYegQuFQOMYu7wF9d_ExcNP0t_FerqCzVzkKF63H_xu5g8nzKpzTE_AYO2JRaQX7+0_ZJBEsnHxXXCBXz=lNuYM5Q4bqTpWNzaHgGzpv4E4Az_7=TXpOLn2cpnmpDFNARhzGvJiFLyPWNN=cVFL5pY8uK7A",
          null
        ]
      },
      {
        "file": "/var/local/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
        "line": 525,
        "function": "createFile",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          ".SeedVaultAndroidBackup/7680425718204950616/kv/org.example/vZkpqCpSOPcdBjTQ5GnSi3oJAv=DgAsDJTtfNyjxjvV433HwpNgNOzkDBSo7ZnyarF6jzEA7+QYegQuFQOMYu7wF9d_ExcNP0t_FerqCzVzkKF63H_xu5g8nzKpzTE_AYO2JRaQX7+0_ZJBEsnHxXXCBXz=lNuYM5Q4bqTpWNzaHgGzpv4E4Az_7=TXpOLn2cpnmpDFNARhzGvJiFLyPWNN=cVFL5pY8uK7A",
          null,
          null
        ]
      },
      {
        "function": "httpPut",
        "class": "Sabre\\DAV\\CorePlugin",
        "type": "->",
        "args": [
          {
            "absoluteUrl": "https://test.de/remote.php/webdav/.SeedVaultAndroidBackup/7680425718204950616/kv/org.example/vZkpqCpSOPcdBjTQ5GnSi3oJAv%3DDgAsDJTtfNyjxjvV433HwpNgNOzkDBSo7ZnyarF6jzEA7%2BQYegQuFQOMYu7wF9d_ExcNP0t_FerqCzVzkKF63H_xu5g8nzKpzTE_AYO2JRaQX7%2B0_ZJBEsnHxXXCBXz%3DlNuYM5Q4bqTpWNzaHgGzpv4E4Az_7%3DTXpOLn2cpnmpDFNARhzGvJiFLyPWNN%3DcVFL5pY8uK7A",
            "__class__": "Sabre\\HTTP\\Request"
          },
          {
            "__class__": "Sabre\\HTTP\\Response"
          }
        ]
      },
      {
        "file": "/var/local/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php",
        "line": 105,
        "function": "call_user_func_array",
        "args": [
          [
            {
              "__class__": "Sabre\\DAV\\CorePlugin"
            },
            "httpPut"
          ],
          [
            {
              "absoluteUrl": "https://test.de/remote.php/webdav/.SeedVaultAndroidBackup/7680425718204950616/kv/org.example/vZkpqCpSOPcdBjTQ5GnSi3oJAv%3DDgAsDJTtfNyjxjvV433HwpNgNOzkDBSo7ZnyarF6jzEA7%2BQYegQuFQOMYu7wF9d_ExcNP0t_FerqCzVzkKF63H_xu5g8nzKpzTE_AYO2JRaQX7%2B0_ZJBEsnHxXXCBXz%3DlNuYM5Q4bqTpWNzaHgGzpv4E4Az_7%3DTXpOLn2cpnmpDFNARhzGvJiFLyPWNN%3DcVFL5pY8uK7A",
              "__class__": "Sabre\\HTTP\\Request"
            },
            {
              "__class__": "Sabre\\HTTP\\Response"
            }
          ]
        ]
      },
      {
        "file": "/var/local/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 479,
        "function": "emit",
        "class": "Sabre\\Event\\EventEmitter",
        "type": "->",
        "args": [
          "method:PUT",
          [
            {
              "absoluteUrl": "https://test.de/remote.php/webdav/.SeedVaultAndroidBackup/7680425718204950616/kv/org.example/vZkpqCpSOPcdBjTQ5GnSi3oJAv%3DDgAsDJTtfNyjxjvV433HwpNgNOzkDBSo7ZnyarF6jzEA7%2BQYegQuFQOMYu7wF9d_ExcNP0t_FerqCzVzkKF63H_xu5g8nzKpzTE_AYO2JRaQX7%2B0_ZJBEsnHxXXCBXz%3DlNuYM5Q4bqTpWNzaHgGzpv4E4Az_7%3DTXpOLn2cpnmpDFNARhzGvJiFLyPWNN%3DcVFL5pY8uK7A",
              "__class__": "Sabre\\HTTP\\Request"
            },
            {
              "__class__": "Sabre\\HTTP\\Response"
            }
          ]
        ]
      },
      {
        "file": "/var/local/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 254,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          {
            "absoluteUrl": "https://test.de/remote.php/webdav/.SeedVaultAndroidBackup/7680425718204950616/kv/org.example/vZkpqCpSOPcdBjTQ5GnSi3oJAv%3DDgAsDJTtfNyjxjvV433HwpNgNOzkDBSo7ZnyarF6jzEA7%2BQYegQuFQOMYu7wF9d_ExcNP0t_FerqCzVzkKF63H_xu5g8nzKpzTE_AYO2JRaQX7%2B0_ZJBEsnHxXXCBXz%3DlNuYM5Q4bqTpWNzaHgGzpv4E4Az_7%3DTXpOLn2cpnmpDFNARhzGvJiFLyPWNN%3DcVFL5pY8uK7A",
            "__class__": "Sabre\\HTTP\\Request"
          },
          {
            "__class__": "Sabre\\HTTP\\Response"
          }
        ]
      },
      {
        "file": "/var/local/nextcloud/apps/dav/appinfo/v1/webdav.php",
        "line": 82,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/local/nextcloud/remote.php",
        "line": 165,
        "args": [
          "/var/local/nextcloud/apps/dav/appinfo/v1/webdav.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/local/nextcloud/apps/dav/lib/Connector/Sabre/File.php",
    "Line": 280,
    "CustomMessage": "--"
  },
  "userAgent": "Mozilla/5.0 (Android) Nextcloud-android/20200129",
  "version": "18.0.7.1"
}
```

**Comment by AndyScherzinger** [comment]
Looping in @nextcloud/server-triage

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage can you help us here?

**Comment by AndyScherzinger** [comment]
@nextcloud/server-triage can you help us here?

**Comment by nickvergessen** [comment]
Hmm it's 241 chars, so should be fine:
https://github.com/nextcloud/server/blob/2a054e6c04e0a40421510eb889cbf59f153c5177/lib/private/Files/Storage/Common.php#L542-L546
