### ISSUE TITLE
Nextcloud Cirkles invite an lokal user does not work

### ISSUE THREAD

**Issue by vaidares** [nextcloud/android#5942]
### Steps to reproduce
1. In WEB interface NC Cirkles invite a lokal user
2. The User gets an Information in Android App 
3. Iff he accepted it pops up an error

### Expected behaviour
- the User should be a member off the cirkle

### Actual behaviour
- in the NC Android App appears an error

### Environment data
Android version: 10
Device model: Xperia (H8266) 

Nextcloud app version: 3.11.1

Nextcloud server version: 18.0.4

#### Nextcloud log (data/nextcloud.log)
`************ CAUSE OF ERROR ************

java.lang.IllegalArgumentException: host parameter is null
	at org.apache.commons.httpclient.HttpConnection.<init>(HttpConnection.java:206)
	at org.apache.commons.httpclient.HttpConnection.<init>(HttpConnection.java:155)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionWithReference.<init>(MultiThreadedHttpConnectionManager.java:1145)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$ConnectionPool.createConnection(MultiThreadedHttpConnectionManager.java:762)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager.doGetConnection(MultiThreadedHttpConnectionManager.java:476)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager.getConnectionWithTimeout(MultiThreadedHttpConnectionManager.java:416)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:153)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:219)
	at com.owncloud.android.jobs.NotificationJob$NotificationReceiver.executeAction(NotificationJob.java:365)
	at com.owncloud.android.jobs.NotificationJob$NotificationReceiver.lambda$onReceive$0$NotificationJob$NotificationReceiver(NotificationJob.java:314)
	at com.owncloud.android.jobs.-$$Lambda$NotificationJob$NotificationReceiver$Ta0golCkjD5LcDq0J-ufk7tOQZo.run(Unknown Source:10)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Sony
Device: H8266
Model: H8266
Id: 52.1.A.0.672
Product: H8266

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 052001A000067202006556692
`

**Comment by tobiasKaminsky** [comment]
What do you mean with "local user"?
