### ISSUE TITLE
App not loading

### ISSUE THREAD

**Issue by georgeb2005** [nextcloud/android#5993]
### Steps to reproduce
1. Install frersh app
2. open app
3. no seting available in app (act like a web browser)

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens
ask to chose server and next open the server web page and ask for credential. but app does not work to setup auto upload etc...
### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:
9
Device model: 
Huawei/J4+
Stock or customized system:
Stok
Nextcloud app version:
3.11.1
Nextcloud server version:
10.4.1
Reverse proxy:
no
#### Web server error log
``` no errors
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
``` no errors
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by georgeb2005** [comment]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'com.owncloud.android.lib.resources.status.CapabilityBooleanType com.owncloud.android.lib.resources.status.OCCapability.getRichDocuments()' on a null object reference
at com.owncloud.android.ui.fragment.OCFileListBottomSheetDialog.onCreate(OCFileListBottomSheetDialog.java:128)
at android.app.Dialog.dispatchOnCreate(Dialog.java:610)
at android.app.Dialog.show(Dialog.java:454)
at com.owncloud.android.ui.fragment.OCFileListFragment.lambda$registerFabListener$0$OCFileListFragment(OCFileListFragment.java:414)
at com.owncloud.android.ui.fragment.-$$Lambda$OCFileListFragment$5sYn_weuHLwdJKK5Y47NrF9_UbA.onClick(Unknown Source:4)
at android.view.View.performClick(View.java:6659)
at android.view.View.performClickInternal(View.java:6631)
at android.view.View.access$3100(View.java:790)
at android.view.View$PerformClick.run(View.java:26187)
at android.os.Handler.handleCallback(Handler.java:907)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:216)
at android.app.ActivityThread.main(ActivityThread.java:7625)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWFIG-H
Model: FIG-LX1
Id: HUAWEIFIG-L11
Product: FIG-LX1

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 9.1.0.176C02
 If i press back gave me this error.

**Comment by georgeb2005** [comment]
![20200501_211129](https://user-images.githubusercontent.com/64651789/80830549-d2e7b080-8bf1-11ea-9567-589b9a54dc48.jpg)
![20200501_211132](https://user-images.githubusercontent.com/64651789/80830553-d4b17400-8bf1-11ea-8284-be7c71202dd0.jpg)
![20200501_211157](https://user-images.githubusercontent.com/64651789/80830554-d54a0a80-8bf1-11ea-8676-a50145e7d709.jpg)
![20200501_211121](https://user-images.githubusercontent.com/64651789/80830557-d5e2a100-8bf1-11ea-95b3-d43537fad8bc.jpg)
On demo2.nextcloud.com same issue.

**Comment by tobiasKaminsky** [comment]
owncloud is not supported.
