### ISSUE TITLE
Android App crashing while while uploading huge amounts 

### ISSUE THREAD

**Issue by Starola** [nextcloud/android#5998]
### Steps to reproduce
1. Activate auto upload (-> with option to upload old files / pictures ; also option, that pictures get sorted by year / month ) 
2. Have a ton of old pictures (In my case around 14 000)
(when uploading only a few pictures, app doesn't crash) 
3. App will crash 
(app has to be restarted every few secons, sometimes app starts, but will crash after a short amount of time, most times it will crash while loading) 

### Expected behaviour
App should not crash 

### Actual behaviour
App crashes (with the error message)

### Environment data
Android version:

Device model: 

Stock or customized system: 

Nextcloud app version:

Nextcloud server version:

Nextcloud abgestürzt
************ CAUSE OF ERROR ************
```
java.lang.IllegalArgumentException: reportSizeConfigurations: ActivityRecord not found for: Token{50fbb87 ActivityRecord{3608fc6 u0 com.nextcloud.client/com.owncloud.android.ui.activity.UploadListActivity t33041 f}}
	at android.os.Parcel.readException(Parcel.java:1669)
	at android.os.Parcel.readException(Parcel.java:1618)
	at android.app.ActivityManagerProxy.reportSizeConfigurations(ActivityManagerNative.java:6885)
	at android.app.ActivityThread.reportSizeConfigurations(ActivityThread.java:2934)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2877)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1570)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6595)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```
************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HONOR
Device: HWSTF
Model: STF-L09
Id: HUAWEISTF-L09
Product: STF-L09

************ FIRMWARE ************
SDK: 24
Release: 7.0
Incremental: C432B183

**Comment by joshtrichards** [comment]
https://github.com/nextcloud/android/issues/4905#issuecomment-560533578

https://issuetracker.google.com/issues/62427912?pli=1
