### ISSUE TITLE
Nextcloud constantly crashing after microSD card change

### ISSUE THREAD

**Issue by ZuseZ4** [nextcloud/android#6032]
### Steps to reproduce
Shut down phone, replace microSD card, restart phone.

### Expected behaviour
App should still be working normaly

### Actual behaviour
App started to constantly crash ~ every 2 Minutes

### Can you reproduce this problem on https://try.nextcloud.com?
Couldn't reproduce it due to hw dependency.

Apparently nextcloud disliked that I changed my microSD card (128GB->256).
After restarting the phone with a new microSD card it stated to upload roughly 4000 images which I have on my nextcloud instance and which aren't on my phone anymore. While trying to figure out what was going wrong the app became even more laggy then it was normally till it finally crashed. 
I tried to re-open nextcloud but it got stuck everytime in the login window. I used androids "kill application", but it seems to either continue in the background or restart itself. Either way, since the first crash I'm now receiving that crash message every ~2 Minutes. 
At least the app did not change anything on the cloud after anouncing to upload 4k images.
And another info, I guess I might have chosen in the nextcloud app settings, that it should store stuff on the microSD card.
Practically I just used the auto-upload function for camera photos. Since this app doesn't support true two-way sync I'm using another app for webdav synchronisation. But they shouldn't interfer since they shouldn't interfere since they work on different folders and my sync app was even turned off before changing the microSD card.
After restarting I tried to remove the admin account from the app in order to reduce the possible damage by this errors. For some reason that started the crash-loop again, I wasn't able to remove the admin account for my cloud. I didn't spent time on trying which other features would also result in such crashes and just removed this app since it seems like it is not the right tool for me.
I thought the error message could still be useful for you, I'll try to answer questions which might come up.

************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.SecurityException: Caller no longer running, last stopped +18s336ms because: timed out while starting
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:195)
	at android.app.job.JobParameters.dequeueWork(JobParameters.java:243)
	at androidx.core.app.JobIntentService$JobServiceEngineImpl.dequeueWork(JobIntentService.java:315)
	at androidx.core.app.JobIntentService.dequeueWork(JobIntentService.java:640)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:390)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobServiceContext.assertCallerLocked(JobServiceContext.java:481)
	at com.android.server.job.JobServiceContext.doDequeueWork(JobServiceContext.java:359)
	at com.android.server.job.JobServiceContext$JobCallback.dequeueWork(JobServiceContext.java:160)
	at android.app.job.IJobCallback$Stub.onTransact(IJobCallback.java:83)
	at android.os.Binder.execTransact(Binder.java:756)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: lge
Device: lucye
Model: LG-H870
Id: PKQ1.190522.001
Product: lucye_global_com

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 1930916292597

**Comment by ZuseZ4** [comment]
Well apparently it seems to be common right now for the app to crash.
I guess I also ran into this second issue https://github.com/nextcloud/android/pull/6017
I guess (?) this bugreport could therefore be closed?

**Comment by ezaquarii** [comment]
@ZuseZ4 no, this error is different, as the stack trace is different.

However, it's already fixed here: https://github.com/nextcloud/android/pull/5986
