### ISSUE TITLE
Crash in grid

### ISSUE THREAD

**Issue by 007fred50** [nextcloud/android#6039]
Then I try to send a file inside upload files.
it crash then I change list to grid

### Steps to reproduce
Step 1: Log ind (Username and Password)
Step 2: Grant access
Step 3: Open default photo (Photos)
Step 4: Press the add button right bottom
Step 5: And "Send files"
Step 6: Now press the 3 dots top right
Step 7: and press "show Grid view"

### Expected behaviour
- Show grid view

### Actual behaviour
- it crash

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 9

Device model: umidigi power

Stock or customized system:

Nextcloud app version: 3.11.1

Nextcloud server version: new version..

Reverse proxy: no proxy

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Can you give us the exact steps to reproduce?

**Comment by 007fred50** [comment]
Step 1: Log ind (Username and Password)
Step 2: Grant access
Step 3: Open default photo (Photos)
Step 4: Press the add button right bottom
Step 5: And "Send files"
Step 6: Now press the 3 dots top right
Step 7: and press "show Grid view"

**Comment by 007fred50** [comment]
And it was on Android.

**Comment by AndyScherzinger** [comment]
@007fred50 there must be some confusion here. Can you add some more details, maybe screenshots since the Photos view (via the main menu)

* has no button on the bottom right 
* has no grid/list view menu item 

Also for the crash, does it show an error dialog with detailed stack traces etc you could share?

**Comment by 007fred50** [comment]
i have uploade some video and photo
https://people8people.com/nextcloud/

**Comment by J-hitz** [comment]
I have the same error on Android Phone. 
This is the Error-Log

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
at com.owncloud.android.ui.adapter.LocalFileListAdapter$LocalFileListGridImageViewHolder.<init>(LocalFileListAdapter.java:464)
at com.owncloud.android.ui.adapter.LocalFileListAdapter$LocalFileListGridImageViewHolder.<init>(LocalFileListAdapter.java:451)
at com.owncloud.android.ui.adapter.LocalFileListAdapter$LocalFileListGridItemViewHolder.<init>(LocalFileListAdapter.java:474)
at com.owncloud.android.ui.adapter.LocalFileListAdapter$LocalFileListGridItemViewHolder.<init>(LocalFileListAdapter.java:470)
at com.owncloud.android.ui.adapter.LocalFileListAdapter.onCreateViewHolder(LocalFileListAdapter.java:281)
at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:561)
at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
at android.view.View.layout(View.java:23754)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
at android.view.View.layout(View.java:23754)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
at android.view.View.layout(View.java:23754)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
at android.view.View.layout(View.java:23754)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:23754)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23754)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23754)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23754)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:23754)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at com.android.internal.policy.DecorView.onLayout(DecorView.java:1052)
at android.view.View.layout(View.java:23754)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3651)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3111)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2169)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8932)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
at android.view.Choreographer.doCallbacks(Choreographer.java:794)
at android.view.Choreographer.doFrame(Choreographer.java:729)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:7807)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: m20lte
Model: SM-M205FN
Id: QP1A.190711.020
Product: m20lteeea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: M205FNEEU3CTA3

**Comment by ezaquarii** [comment]
This issue is caused by b4db8d8f95c371c49da6a18dd6e7245c0666d3f3.

List adapter is using 2 different layouts for list and grid view. This item does not exist in grid layout.
