### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mjbvp** [nextcloud/android#6062]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
	at com.owncloud.android.ui.activity.UserInfoActivity.populateUserInfoUi(UserInfoActivity.java:266)
	at com.owncloud.android.ui.activity.UserInfoActivity.lambda$null$0$UserInfoActivity(UserInfoActivity.java:384)
	at com.owncloud.android.ui.activity.-$$Lambda$UserInfoActivity$gWBfB6Gsuel8SADkZiTj2AR_AJs.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:6809)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: beryllium
Model: POCOPHONE F1
Id: PKQ1.180729.001
Product: beryllium

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 9.6.27

**Comment by tobiasKaminsky** [comment]
Can you give us the steps to reproduce?
I suspect that you wanted to see the user infos and navigated away while fetching the infos and then it crashed?

**Comment by mjbvp** [comment]
I did not reproduce this problem.

**Comment by tobiasKaminsky** [comment]
No problem, I could verify it.
