### ISSUE TITLE
App crashes on trying to open unread messages

### ISSUE THREAD

**Issue by SShas73** [nextcloud/android#6091]
### Steps to reproduce
1. Launch app(I'm using nextcloud talk v 8.0.9
2. Click on a conversation with unread messages
3. 

### Expected behaviour
-conversation should open and function as intended

### Actual behaviour
- on clicking on a conversation with unread messages, app crashes multiple times producing the same cause of error report with option to report error

-crashes persist on switching to other apps(I don't think nextcloud closes when I switch)

- this seems to only happen when there are unread messages

### Can you reproduce this problem on https://try.nextcloud.com?

Sorry, but I could not? 
Not sure how to reproduce this. 

- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Sorry, all these below have been provided in the "nextcloud log" section, all as generated by the nextcloud cause of error report.

Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.client-3Hm6VIEdafQgpeBwO07Gxg==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-3Hm6VIEdafQgpeBwO07Gxg==/lib/arm64, /data/app/com.nextcloud.client-3Hm6VIEdafQgpeBwO07Gxg==/base.apk!/lib/arm64-v8a, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: m30s
Model: SM-M307F
Id: 
Product: m30sdd

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: M307FXXS2ATB3
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by SShas73** [comment]
Thank you for developing this tool! 
I have no prior experience with coding, and obviously my first time on GitHub. If there are any errors with my report, apologies in advance.
