### ISSUE TITLE
SecurityException in OCFileListAdapter: uid 10247 cannot get user data for accounts of type: nextcloud

### ISSUE THREAD

**Issue by profago** [nextcloud/android#6108]
Opening the app
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to resume activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.SecurityException: uid 10247 cannot get user data for accounts of type: nextcloud
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4539)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4572)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2220)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8016)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
Caused by: java.lang.SecurityException: uid 10247 cannot get user data for accounts of type: nextcloud
	at android.os.Parcel.createException(Parcel.java:2088)
	at android.os.Parcel.readException(Parcel.java:2056)
	at android.os.Parcel.readException(Parcel.java:2004)
	at android.accounts.IAccountManager$Stub$Proxy.getUserData(IAccountManager.java:1441)
	at android.accounts.AccountManager.getUserData(AccountManager.java:515)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.<init>(OCFileListAdapter.java:164)
	at com.owncloud.android.ui.fragment.OCFileListFragment.onActivityCreated(OCFileListFragment.java:344)
	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2619)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:904)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
	at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:446)
	at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:459)
	at com.owncloud.android.ui.activity.BaseActivity.onResume(BaseActivity.java:91)
	at com.owncloud.android.ui.activity.DrawerActivity.onResume(DrawerActivity.java:1274)
	at com.owncloud.android.ui.activity.FileActivity.onResume(FileActivity.java:218)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onResume(FileDisplayActivity.java:1206)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1454)
	at android.app.Activity.performResume(Activity.java:8105)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4529)
	... 11 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.accounts.AccountManagerService.getUserData(AccountManagerService.java:1656)
	at android.accounts.IAccountManager$Stub.onTransact(IAccountManager.java:492)
	at com.android.server.accounts.AccountManagerService.onTransact(AccountManagerService.java:1114)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)


************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: beyond1
Model: SM-G973F
Id: QP1A.190711.020
Product: beyond1lteeea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G973FXXU4CTC9
```

**Comment by tobiasKaminsky** [comment]
Do you use Android For Work or MDM or something similar?

**Comment by profago** [comment]
> Do you use Android For Work or MDM or something similar?

Hi,
no, I haven't installed any app like AFW or MDM.
Thankyou
