### ISSUE TITLE
IllegalStateException in UploadFilesActivity.showLocalStoragePathPickerDialog: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by nanderer** [nextcloud/android#6127]
Why dont you dont just forward to mail app or send the stuff yourself, forcing me to sign in in a force dual auth site just to report this crash anoys me. ..

Whatever thats what the crashing app copyed to my clipboard

```
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2080)
	at androidx.fragment.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2106)
	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:683)
	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:637)
	at androidx.fragment.app.DialogFragment.show(DialogFragment.java:161)
	at com.owncloud.android.ui.activity.UploadFilesActivity.showLocalStoragePathPickerDialog(UploadFilesActivity.java:336)
	at com.owncloud.android.ui.activity.UploadFilesActivity.onBackPressed(UploadFilesActivity.java:383)
	at com.owncloud.android.ui.activity.UploadFilesActivity.onOptionsItemSelected(UploadFilesActivity.java:286)
	at android.app.Activity.onMenuItemSelected(Activity.java:3626)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:436)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:196)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:188)
	at android.view.View.performClick(View.java:6302)
	at android.view.View$PerformClick.run(View.java:24908)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6558)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: blackberry
Device: bbb100
Model: BBB100-2
Id: OPM1.171019.026
Product: bbb100emea

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: ABT975
```

### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
What are the steps to reproduce? Otherwise this might very hard to track down…

**Comment by AndyScherzinger** [comment]
Other than that @nanderer could you please update to the latest version? You are still using 3.8 while 3.11.1 is the latest stable release.

**Comment by nanderer** [comment]
Ive tryed to get some free space by uploading a directory with a couple wav files (more then 10 less then 100) with a overall filesize more then 1GB. I first tryed your integration within androids fail api ("Downloads " app) but that did not worked out. Then i used your internal upload thing that did not allow me to upload and delet locally a whole directory, so i navigated to it. By doing that i started from the main directory (/sdcardg or storage/emolated/0 whatever/) and that is quite full. The app had problems with its load listing that many entrys for one directory. 

You should to work that out do some benchmarking and then i guess youll see the limits of your android software. Just get some device with at least 64 gb of internal space, fill it up with as much files as possible, try to use your app to upload a couple of big files (mp4/wav/whatever) and/or a lot of (more then 100 at once) smaller once and you will see how inperfect it works. 

I guess The best would be to delete all your backend stuff and port the perfectly working code from your desktop app so i am able to sync my whole /sdcard with my server without that hazzles this app gives me richt now...

Ive just upgraded, ill get in touch if iz occurs again

Thanks a lot in advance and keep up the good work!

Am 22. Mai 2020 10:14:59 MESZ schrieb Tobias Kaminsky <notifications@github.com>:
>What are the steps to reproduce? Otherwise this might very hard to
>track down…>
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/nextcloud/android/issues/6127#issuecomment-632562227

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by nanderer** [comment]
take it or leave it, nextcloud android app is inefficent programmed so what or maybe rewrite    the code completely to fix it or dont, i dont care, i now syncing using termux and webdav without an app on android...

Am 20-Jun-2020 19:11:04 +0200 schrieb notifications@github.com: 

This bug report did not receive an update in the last 4 weeks. Please take a look again and update the issue with new details, otherwise the issue will be automatically closed in 2 weeks. Thank you! 

--
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.  

-------------------------------------------------------------------------------------------------
FreeMail powered by mail.ch

**Comment by nanderer** [comment]
What details, your app did this, i send it, i told you maybe in this maybe in another issue what i think of your android implememntation, also i am not a programmer but some system integration guy$...

Am 23. Juli 2020 08:11:35 MESZ schrieb "stale[bot]" <notifications@github.com>:
>This bug report did not receive an update in the last 4 weeks. Please
>take a look again and update the issue with new details, otherwise the
>issue will be automatically closed in 2 weeks. Thank you!
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/android/issues/6127#issuecomment-662835712

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by AndyScherzinger** [comment]
no information provided whatsoever regarding the originally reported issue, especially after

> could you please update to the latest version? You are still using 3.8 while 3.11.1 is the latest stable release.

leading to

> Ive just upgraded, ill get in touch if iz occurs again

So closing, any other comments are just random rants about the app and the people building it-
