### ISSUE TITLE
App crash in background "Caused by: java.lang.NoSuchFieldException: USER"

### ISSUE THREAD

**Issue by GuilleW** [nextcloud/android#6149]
### Steps to reproduce
- Just let Nextcloud run in background (NOT OPENED) few hours.

### Expected behaviour
- Sync files and be quiet

### Actual behaviour
- Crash 2-3 times a day when I unlock my phone, the nextcloud app show a error screen with error bellow

### Can you reproduce this problem on https://try.nextcloud.com?
- no, sorry

### Environment data
- Nextcloud server version: Nextcloud 18.0.4

#### Nextcloud log (from Nextcloud app crash)

```java
************ CAUSE OF ERROR ************

java.lang.AssertionError: AssertionError (GSON 2.8.6): java.lang.NoSuchFieldException: USER
	at com.google.gson.Gson.fromJson(Gson.java:949)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:1019)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:106)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFile(FileDataStorageManager.java:226)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:239)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:181)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:268)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.onPerformSync(FileSyncAdapter.java:180)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
Caused by: java.lang.AssertionError: java.lang.NoSuchFieldException: USER
	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:792)
	at com.google.gson.internal.bind.TypeAdapters$30.create(TypeAdapters.java:818)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.ArrayTypeAdapter$1.create(ArrayTypeAdapter.java:48)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.Gson.fromJson(Gson.java:931)
	... 17 more
Caused by: java.lang.NoSuchFieldException: USER
	at java.lang.Class.getField(Class.java:1104)
	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:781)
	... 26 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: hlte
Model: SM-N9005
Id: LRX21V
Product: hltexx

************ FIRMWARE ************
SDK: 21
Release: 5.0
Incremental: N9005XXSGBPL6

```

**Comment by tobiasKaminsky** [comment]
This fails when trying to parse the sharees.
normally it should look like: 
```
[{"displayName":"admin","shareType":"USER","userId":"admin"}]
```
the first part is the field, but exception says that there so field "USER", which is totally correct, as this should be the value.

@nextcloud/server-triage do you have an idea why this could happen?

@GuilleW do you know in which folder this happen? Do you have special shares?

**Comment by GuilleW** [comment]
My Nextcloud instance is a *home cloud*, only shared with my wife (2 users only). I have indeed 3 folders shared with my wife, and 1 (old) folder shared by email with read only permission (not registered user). @tobiasKaminsky, can you tell me where to digg to get extra informations needed ?

**Comment by tobiasKaminsky** [comment]
I fear that the only possible way is to run a manual curl command agaist your server:
```
curl --request PROPFIND \
  -u $user:$pass \
  --url http://$server/remote.php/webdav/ \
  --header 'content-type: application/xml' \
  --data '<?xml version="1.0" encoding="UTF-8"?>
<D:propfind xmlns:D="DAV:">
<D:prop>
<D:displayname/>
<sharees  xmlns="http://nextcloud.org/ns"/>
</D:prop></D:propfind>
'
```
This is querying against the topmost folder of your user.
It returns a list of all folders and files with its name and its sharees.

For me an excerpt of it with the shared folders is enough.
It should look like:
```
<d:response>
    <d:href>/nc/remote.php/webdav/0/</d:href>
    <d:propstat>
      <d:prop>
        <nc:sharees>
          <nc:sharee>
            <nc:id/>
            <nc:display-name/>
            <nc:type>3</nc:type>
          </nc:sharee>
          <nc:sharee>
            <nc:id>admin</nc:id>
            <nc:display-name>admin</nc:display-name>
            <nc:type>0</nc:type>
          </nc:sharee>
        </nc:sharees>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
    <d:propstat>
```
In this case it is folder "/0/" with sharees Admin and public link (share type 3).

**Comment by GuilleW** [comment]
Using curl I get : 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<d:multistatus xmlns:d="DAV:" 
  xmlns:s="http://sabredav.org/ns" 
  xmlns:oc="http://owncloud.org/ns" 
  xmlns:nc="http://nextcloud.org/ns">

  [...removed default folders...]

  [... but here's just one default folder for example...]
  
  <d:response>
    <d:href>/remote.php/webdav/aaaaaaaaaaaaaa/</d:href>
    <d:propstat>
      <d:prop>
        <nc:sharees/>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
    <d:propstat>
      <d:prop>
        <d:displayname/>
      </d:prop>
      <d:status>HTTP/1.1 404 Not Found</d:status>
    </d:propstat>
  </d:response>

  [...]
  
  <d:response>
    <d:href>/remote.php/webdav/bbbbbbbbbbbbbb/</d:href>
    <d:propstat>
      <d:prop>
        <nc:sharees>
          <nc:sharee>
            <nc:id>USER_B</nc:id>
            <nc:display-name>NICKNAME_B</nc:display-name>
            <nc:type>0</nc:type>
          </nc:sharee>
        </nc:sharees>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
    <d:propstat>
      <d:prop>
        <d:displayname/>
      </d:prop>
      <d:status>HTTP/1.1 404 Not Found</d:status>
    </d:propstat>
  </d:response>
  
  <d:response>
    <d:href>/remote.php/webdav/ccccccccccccccc/</d:href>
    <d:propstat>
      <d:prop>
        <nc:sharees>
          <nc:sharee>
            <nc:id>USER_B</nc:id>
            <nc:display-name>NICKNAME_B</nc:display-name>
            <nc:type>0</nc:type>
          </nc:sharee>
        </nc:sharees>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
    <d:propstat>
      <d:prop>
        <d:displayname/>
      </d:prop>
      <d:status>HTTP/1.1 404 Not Found</d:status>
    </d:propstat>
  </d:response>
  
</d:multistatus>
```

**Comment by GuilleW** [comment]
Still having crash

**Comment by GuilleW** [comment]
Still having crash

**Comment by GuilleW** [comment]
`
************ CAUSE OF ERROR ************

java.lang.AssertionError: AssertionError (GSON 2.8.6): java.lang.NoSuchFieldException: CONTACT
	at com.google.gson.Gson.fromJson(Gson.java:949)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:1017)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:874)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:156)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:432)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:369)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:228)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:181)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:268)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:344)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:288)
	at com.owncloud.android.syncadapter.FileSyncAdapter.onPerformSync(FileSyncAdapter.java:180)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
Caused by: java.lang.AssertionError: java.lang.NoSuchFieldException: CONTACT
	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:792)
	at com.google.gson.internal.bind.TypeAdapters$30.create(TypeAdapters.java:818)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.ArrayTypeAdapter$1.create(ArrayTypeAdapter.java:48)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.Gson.fromJson(Gson.java:931)
	... 17 more
Caused by: java.lang.NoSuchFieldException: CONTACT
	at java.lang.Class.getField(Class.java:1104)
	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:781)
	... 26 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: hlte
Model: SM-N9005
Id: LRX21V
Product: hltexx

************ FIRMWARE ************
SDK: 21
Release: 5.0
Incremental: N9005XXSGBPL6

`

**Comment by GuilleW** [comment]
I reset my Samsung Galaxy Note 3 with the old Android 5 (end of support from Samsung since 2015) and go to LineageOS with F-Droid store. Since 3 weeks now, no crash. Closing the issue, thank for support.
