### ISSUE TITLE
Nextcloud beta 20170130 unrecoverable crash

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/android#617]
### Actual behaviour
-Tell us what happens
Trying to get access to "Settings" caused the dispplay to turn black, but some of the phone overlay such as network, time and others were still visible.
Nextcloud app would then return to the "passcode" page.
Once passcode entered, the "error" log would appear and upon deleting the log, the app would crash again.
I was able to send the log with my normal Nextcloud app version 1.4.1 which works concurrently on my phone.
I couldn't get pass the "error" log under Nextcloud Beta. My only option was to unsintall it from the phone.
During this issue, several things seemed to have happen so this makes troubleshooting more difficult:

- It seems there was a Google update in the process.
- I lost connection to the Nextcloud 11 server due to "Brute force attack" prevention. I don't know the cause of it, but one of my account, was causing the issue. Maybe one of the Nextcloud app had the wrong account password causing the loss of server connection. I know which account triggered the attack defense, as I logged to my Nextcloud server from a different IP address.

I installed the newer 20170202 Beta version and will be monitoring its behavior.

### Expected behaviour
-Tell us what should happen
 
### Steps to reproduce
1. Cannot reproduce
2. 
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.android.beta/com.owncloud.android.ui.activity.Preferences}: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.owncloud.android.ui.adapter.DiskLruImageCache.getMaxSize()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
	at android.app.ActivityThread.access$900(ActivityThread.java:157)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5551)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.owncloud.android.ui.adapter.DiskLruImageCache.getMaxSize()' on a null object reference
	at com.owncloud.android.datamodel.ThumbnailsCacheManager.getMaxSize(ThumbnailsCacheManager.java:228)
	at com.owncloud.android.ui.activity.Preferences.onCreate(Preferences.java:227)
	at android.app.Activity.performCreate(Activity.java:6272)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
	... 9 more

************ DEVICE INFORMATION ***********
Brand: lge
Device: g3
Model: LG-D852
Id: MRA58K
Product: g3_bell_ca

************ FIRMWARE ************
SDK: 23
Release: 6.0
Incremental: 162091130443e

**Comment by mario** [comment]
Can you reproduce this with newest beta?

**Comment by tobiasKaminsky** [comment]
@OlivierS1 is this still happening with latest dev version?
