### ISSUE TITLE
Login: NullPointerException: Attempt to invoke virtual method 'FileDataStorageManager.getFileByPath(String)' on a null object reference

### ISSUE THREAD

**Issue by quider** [nextcloud/android#6181]
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'com.owncloud.android.datamodel.OCFile com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(java.lang.String)' on a null object reference
	at com.owncloud.android.ui.activity.FileDisplayActivity.browseToRoot(FileDisplayActivity.java:1609)
	at com.owncloud.android.ui.activity.DrawerActivity.onNavigationItemClicked(DrawerActivity.java:417)
	at com.owncloud.android.ui.activity.DrawerActivity.access$300(DrawerActivity.java:124)
	at com.owncloud.android.ui.activity.DrawerActivity$3$1.run(DrawerActivity.java:353)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8016)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120052
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: beyond2
Model: SM-G975F
Id: QP1A.190711.020
Product: beyond2lteeea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G975FXXU4CTC9
```

**Comment by tobiasKaminsky** [comment]
This tries to fetch your top most folder on cloud from storage, which should always be there.
Do you have some storage problem? Missing storage permissions?
