### ISSUE TITLE
set up a couple of file auto uploads for 10 gb of data and 100

### ISSUE THREAD

**Issue by nanderer** [nextcloud/android#6183]
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Couldn't read row 1945, col 1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetString(Native Method)
	at android.database.CursorWindow.getString(CursorWindow.java:438)
	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
	at android.database.CursorWrapper.getString(CursorWrapper.java:137)
	at com.owncloud.android.datamodel.UploadsStorageManager.createOCUploadFromCursor(UploadsStorageManager.java:321)
	at com.owncloud.android.datamodel.UploadsStorageManager.getUploads(UploadsStorageManager.java:302)
	at com.owncloud.android.datamodel.UploadsStorageManager.getFailedUploads(UploadsStorageManager.java:368)
	at com.owncloud.android.files.services.FileUploader.retryFailedUploads(FileUploader.java:1005)
	at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:232)
	at com.owncloud.android.utils.-$$Lambda$FilesSyncHelper$fa2LBpPOxRVQOm4F_Glue5u4hdM.run(Unknown Source:10)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: blackberry
Device: bbb100
Model: BBB100-2
Id: OPM1.171019.026
Product: bbb100emea

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: ABT975

**Comment by nanderer** [comment]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.SecurityException: Caller no longer running, last stopped +3s686ms because: timed out while starting
	at android.os.Parcel.readException(Parcel.java:2013)
	at android.os.Parcel.readException(Parcel.java:1959)
	at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:191)
	at android.app.job.JobParameters.dequeueWork(JobParameters.java:208)
	at androidx.core.app.JobIntentService$JobServiceEngineImpl.dequeueWork(JobIntentService.java:315)
	at androidx.core.app.JobIntentService.dequeueWork(JobIntentService.java:640)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:390)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: blackberry
Device: bbb100
Model: BBB100-2
Id: OPM1.171019.026
Product: bbb100emea

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: ABT975

**Comment by nanderer** [comment]
![Screenshot_20200530-132644](https://user-images.githubusercontent.com/45161625/83327046-40324400-a279-11ea-976d-837a5d280f42.png)

**Comment by tobiasKaminsky** [comment]
Can you test latest beta from play store? 3.12.0 RC2? And report back if this solves it?
