### ISSUE TITLE
Bug by auto uploading files from smartphone

### ISSUE THREAD

**Issue by lth99** [nextcloud/android#6187]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- the Android app should upload my file automatically 

### Actual behaviour
- I get an error all 10 seconds on my smartphone, I can't use any app now 

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Bug:
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Couldn't read row 1866, col 1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetString(Native Method)
	at android.database.CursorWindow.getString(CursorWindow.java:469)
	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:53)
	at android.database.CursorWrapper.getString(CursorWrapper.java:141)
	at com.owncloud.android.datamodel.UploadsStorageManager.createOCUploadFromCursor(UploadsStorageManager.java:321)
	at com.owncloud.android.datamodel.UploadsStorageManager.getUploads(UploadsStorageManager.java:302)
	at com.owncloud.android.datamodel.UploadsStorageManager.getFailedUploads(UploadsStorageManager.java:368)
	at com.owncloud.android.files.services.FileUploader.retryFailedUploads(FileUploader.java:1005)
	at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:232)
	at com.owncloud.android.utils.-$$Lambda$FilesSyncHelper$fa2LBpPOxRVQOm4F_Glue5u4hdM.run(Unknown Source:10)
	at java.lang.Thread.run(Thread.java:929)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HONOR
Device: HWPCT
Model: PCT-L29
Id: HUAWEIPCT-L29
Product: PCT-L29

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.0.0.197C432

#### Web server error log
```
https://appkosmos.de/feed/ read error : cURL error 28: Operation timed out after 60001 milliseconds with 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) 
#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Can you switch to beta version via Play Store and report back if this solves the problem?

**Comment by lth99** [comment]
Hey, I only get this bug if I want to upload from an android device more than 10000 files

**Comment by lth99** [comment]
So it is not a critical bug, maybe it happens cause my nextcloud setup is not enough to upload so many files at the same time
