### ISSUE TITLE
Nextcloud app crashes on start

### ISSUE THREAD

**Issue by Spielmops** [nextcloud/android#6200]
### Steps to reproduce
1. start nextcloud
2. read crashreport
3. crash report:

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to resume activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.SecurityException: uid 10121 cannot get user data for accounts of type: nextcloud
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3469)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3509)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2772)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.SecurityException: uid 10121 cannot get user data for accounts of type: nextcloud
	at android.os.Parcel.readException(Parcel.java:1692)
	at android.os.Parcel.readException(Parcel.java:1645)
	at android.accounts.IAccountManager$Stub$Proxy.getUserData(IAccountManager.java:887)
	at android.accounts.AccountManager.getUserData(AccountManager.java:402)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.<init>(OCFileListAdapter.java:164)
	at com.owncloud.android.ui.fragment.OCFileListFragment.onActivityCreated(OCFileListFragment.java:344)
	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2619)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:904)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
	at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:446)
	at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:459)
	at com.owncloud.android.ui.activity.BaseActivity.onResume(BaseActivity.java:91)
	at com.owncloud.android.ui.activity.DrawerActivity.onResume(DrawerActivity.java:1274)
	at com.owncloud.android.ui.activity.FileActivity.onResume(FileActivity.java:218)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onResume(FileDisplayActivity.java:1206)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
	at android.app.Activity.performResume(Activity.java:6788)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3446)
	... 11 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: CUBOT
Device: MAX
Model: CUBOT MAX
Id: NJH47F
Product: lineage_MAX

************ FIRMWARE ************
SDK: 25
Release: 7.1.2
Incremental: 0b9343a255
### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

Spielmops

**Comment by tobiasKaminsky** [comment]
Do you use Android for Work or profiles?

**Comment by Spielmops** [comment]
No to both. Additional info: This happend two times after an up- and download session for about 10 minutes. It did not help to delete cache and data of the app, but a restart of the phone brought the app back to live. Internet connection was not broken, I tried to reach my server by webinterface and that went fine

Spielmops.
