### ISSUE TITLE
NC client on Android 10 crashes at random, no input causes this.

### ISSUE THREAD

**Issue by m0rd3cai** [nextcloud/android#6258]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to create service com.evernote.android.job.JobRescheduleService: java.lang.RuntimeException: android.os.DeadSystemException
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4166)
	at android.app.ActivityThread.access$1500(ActivityThread.java:268)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1998)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7814)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
Caused by: java.lang.RuntimeException: android.os.DeadSystemException
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4160)
	... 8 more
Caused by: android.os.DeadSystemException
	... 9 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a50
Model: SM-A505U1
Id: QP1A.190711.020
Product: a50ue

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: A505U1UES6BTE1

Client will crash at random. No input causes this. Does about once per day.

**Comment by tobiasKaminsky** [comment]
@ezaquarii do you have an idea?
