### ISSUE TITLE
Nextcloud App crash on clicking .vcf

### ISSUE THREAD

**Issue by psyca** [nextcloud/android#6277]
### Steps to reproduce
1. Create a Backup of your (smartphone) contacts via App
2. Open the hidden .contact folder and click on the created .vcf
3. App crashes

### Expected behaviour
- Tell us what should happen
Open the file, download it or something else but no crash

### Actual behaviour
- Tell us what happens
The Nextcloud App crash

### Environment data
Android version: 9.0

Device model: Samsung Galaxy S8

Stock or customized system: Stock

Nextcloud app version: 3.12.0

Nextcloud server version: 19.0

### Logs
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.ContactsPreferenceActivity}: java.lang.ClassCastException: com.nextcloud.client.account.RegisteredUser cannot be cast to org.parceler.ParcelWrapper
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3114)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by: java.lang.ClassCastException: com.nextcloud.client.account.RegisteredUser cannot be cast to org.parceler.ParcelWrapper
	at org.parceler.Parcels.unwrap(Parcels.java:91)
	at com.owncloud.android.ui.activity.ContactsPreferenceActivity.onCreate(ContactsPreferenceActivity.java:96)
	at android.app.Activity.performCreate(Activity.java:7327)
	at android.app.Activity.performCreate(Activity.java:7318)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)
	... 11 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: dreamlte
Model: SM-G950F
Id: PPR1.180610.011
Product: dreamltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G950FXXS9DTEA

**Comment by AndyScherzinger** [comment]
Thanks for the report @psyca 

I can reproduce the crash and it is also happening on the latest dev version

**Comment by ezaquarii** [comment]
@AndyScherzinger @tobiasKaminsky on it

**Comment by ezaquarii** [comment]
Navigating to a hidden folder instead of following contacts restoration UI can be considered being "power user" workflow. Immediate fix is pending, but on `master` I'd prefer to wait for a proper solution following #5866 practice.

**Comment by ezaquarii** [comment]
Fix proposition for `master` is avaialble as well.

**Comment by AndyScherzinger** [comment]
@ezaquarii while true beware that the app also crashes in case you have a vcf file any place else :/

**Comment by ezaquarii** [comment]
@AndyScherzinger 
The location of `vcf` should not matter - the fix is in target activity.
