### ISSUE TITLE
Android app crashes during sync

### ISSUE THREAD

**Issue by OStrama** [nextcloud/android#6280]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Not allowed to start service Intent { act=SYNC_FOLDER cmp=com.nextcloud.client/com.owncloud.android.services.OperationsService (has extras) }: app is in background uid UidRecord{8753e4 u0a175 SVC  bg:+1m3s568ms idle change:idle procs:2 proclist:15732,15822, seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1666)
	at android.app.ContextImpl.startService(ContextImpl.java:1611)
	at android.content.ContextWrapper.startService(ContextWrapper.java:677)
	at com.owncloud.android.operations.SynchronizeFolderOperation.startSyncFolderOperation(SynchronizeFolderOperation.java:496)
	at com.owncloud.android.operations.SynchronizeFolderOperation.prepareOpsFromLocalKnowledge(SynchronizeFolderOperation.java:372)
	at com.owncloud.android.operations.SynchronizeFolderOperation.run(SynchronizeFolderOperation.java:141)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:181)
	at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:85)
	at com.owncloud.android.services.SyncFolderHandler.doOperation(SyncFolderHandler.java:119)
	at com.owncloud.android.services.SyncFolderHandler.handleMessage(SyncFolderHandler.java:88)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:65)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: dreamlte
Model: SM-G950F
Id: PPR1.180610.011
Product: dreamltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G950FXXS8DTC6

Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Seems to be related to power saving mechanism.
Can you disable it for NC app?

**Comment by OStrama** [comment]
Hi Tobias, thanks for the response. I'll try it when I'm back home next week. However, the crash occured while the app and the screen was active as far as I remember..GreetingsOlafVon meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Tobias Kaminsky <notifications@github.com> Datum: 15.06.20  12:04  (GMT+01:00) An: nextcloud/android <android@noreply.github.com> Cc: OStrama <o.strama@t-online.de>, Author <author@noreply.github.com> Betreff: Re: [nextcloud/android] Android app crashes during sync (#6280) 
Seems to be related to power saving mechanism.
Can you disable it for NC app?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/nextcloud/android/issues/6280#issuecomment-644033349",
"url": "https://github.com/nextcloud/android/issues/6280#issuecomment-644033349",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
