### ISSUE TITLE
NullPointer during files menu access

### ISSUE THREAD

**Issue by thenickname** [nextcloud/android#6282]
#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.datamodel.OCFile.canWrite()' on a null object reference
	at com.owncloud.android.ui.fragment.OCFileListFragment.updateLayout(OCFileListFragment.java:1291)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1260)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1194)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onResume(FileDisplayActivity.java:1222)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1413)
	at android.app.Activity.performResume(Activity.java:7408)
	at android.app.ActivityThread.performNewIntents(ActivityThread.java:3198)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3213)
	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:49)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1840)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: tucana
Model: Mi Note 10
Id: PKQ1.190302.001
Product: tucana_eea

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: V11.0.17.0.PFDEUXM

**Comment by tobiasKaminsky** [comment]
Is this happening for a specific folder?

**Comment by thenickname** [comment]
I believe it happened for a large folder with lots of files and overall size. But I'm not sure.

Also, I don't know how to reliably reproduce.
