### ISSUE TITLE
SQLiteReadOnlyDatabaseException: attempt to write a readonly database in FileContentProvider.update()

### ISSUE THREAD

**Issue by AOANUN995** [nextcloud/android#6291]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java)
	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java)
	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:643)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:627)
	at android.content.ContentProvider$Transport.update(ContentProvider.java)
	at android.content.ContentResolver.update(ContentResolver.java)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveCapabilities(FileDataStorageManager.java:1967)
	at com.owncloud.android.operations.GetCapabilitiesOperation.run(GetCapabilitiesOperation.java:44)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136)
	at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:64)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:287)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:267)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:220)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:357)
	at java.lang.Thread.run(Thread.java:818)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: omega
Model: Redmi Pro
Id: MRA58K
Product: omega

************ FIRMWARE ************
SDK: 23
Release: 6.0
Incremental: 9.1.3
```

**Comment by tobiasKaminsky** [comment]
> SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)

This is something done on Android side, and I never saw this before.
Is this happening more than once?
Do you have enough space left?

**Comment by ezaquarii** [comment]
From our internal chat, where we discussed the issue:

it get's readable DB for read operations and writable for write ops. In this particular case FileContentProvider requests a writeable database (just looked at the code) - I have no idea why the returned database is read-only.

Hah, they even have a workaround for similar bug in their platform code:
https://android.googlesource.com/platform/packages/apps/Launcher3/+/0250945759f7ac58aab912448d62dc108b1770c5%5E!/

I guess this is a platform bug, not our fault.
