### ISSUE TITLE
ClassCastException: FolderPickerActivity cannot be cast to FileDisplayActivity

### ISSUE THREAD

**Issue by d-popov** [nextcloud/android#6292]
```
************ CAUSE OF ERROR ************

java.lang.ClassCastException: com.owncloud.android.ui.activity.FolderPickerActivity cannot be cast to com.owncloud.android.ui.activity.FileDisplayActivity
	at com.owncloud.android.ui.fragment.OCFileListFragment.onHeaderClicked(OCFileListFragment.java:541)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.lambda$onBindViewHolder$0$OCFileListAdapter(OCFileListAdapter.java:341)
	at com.owncloud.android.ui.adapter.-$$Lambda$OCFileListAdapter$bgzutKtJ5puk4q5eCv6UbcIJ6MM.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:6608)
	at android.view.View.performClickInternal(View.java:6585)
	at android.view.View.access$3100(View.java:782)
	at android.view.View$PerformClick.run(View.java:25905)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6869)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:861)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Lenovo
Device: jd2018
Model: Lenovo L78011
Id: PKQ1.190127.001
Product: jd2018

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 11.1.053_190731
```

**Comment by ezaquarii** [comment]
@tobiasKaminsky Obviously `FolderPickerActivity` does not derive `FileDisplayActivity` where the called API is implemented, but a more generic `FileActivity`.

It's either the UI that allows some illegal use case or the API is misplaced and should be moved to `FileActivity` or I missed something.

**Comment by tobiasKaminsky** [comment]
What are the steps to reproduce?
