### ISSUE TITLE
Nextcloud app crashed on anroid on autoupload

### ISSUE THREAD

**Issue by rpsinghk** [nextcloud/android#6305]
### Steps to reproduce
1. I was playing around with autoupload
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:  3.12.0

Nextcloud server version: 19.0.0

Reverse proxy:
None
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
************ CAUSE OF ERROR ************

android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@c398674 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:687)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:288)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
	at android.app.Dialog.show(Dialog.java:312)
	at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
	at com.owncloud.android.ui.activity.SyncedFoldersActivity.showBatteryOptimizationInfo(SyncedFoldersActivity.java:910)
	at com.owncloud.android.ui.activity.SyncedFoldersActivity.onSaveSyncedFolderPreference(SyncedFoldersActivity.java:770)
	at com.owncloud.android.ui.dialog.SyncedFolderPreferencesDialogFragment$OnSyncedFolderSaveClickListener.onClick(SyncedFolderPreferencesDialogFragment.java:552)
	at android.view.View.performClick(View.java:5184)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:967)
	at android.view.View$PerformClick.run(View.java:20910)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5951)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: ja3g
Model: GT-I9500
Id: LRX22C
Product: ja3gxx

************ FIRMWARE ************
SDK: 21
Release: 5.0.1
Incremental: I9500XXUHPI2

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
@ezaquarii do you have an idea?
It seems that the underlying activity is gone, but I though this would only happen if you have a long running thread, which at the end shows such a dialog and meanwhile you end the activity.
But according to code this dialog is shown very very quickly.

Nevertheless I create PR.
