### ISSUE TITLE
App crash after renaming directory

### ISSUE THREAD

**Issue by sebeksd** [nextcloud/android#6308]
### Steps to reproduce
1. Rename folder on Windows desktop
2. Open Android app
3. Crash

Folder name was: [Zdjecia]
Renamed to: Zdjecia
Folder on Android app was out of screen (if it's important).
Folder name was updated on WEB interface.
Reinstalling, clearing cache do nothing, app still crashes.

### Expected behaviour
- update folder name in android app without crashing

### Actual behaviour
- app crash, same error after reinstalling app 

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 8

Device model: Galaxy S7 Edge

Stock or customized system: Stock

Nextcloud app version: 3.0.12

Nextcloud server version: 9.0.12

Reverse proxy: Traefik 2

### Logs
************ CAUSE OF ERROR ************

android.database.CursorIndexOutOfBoundsException: Index -1 requested, with a size of 4781
at android.database.AbstractCursor.checkPosition(AbstractCursor.java:460)
at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:74)
at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:179)
at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:299)
at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:670)
at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:323)
at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:465)
at android.content.ContentResolver.applyBatch(ContentResolver.java:1584)
at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:405)
at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:478)
at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:369)
at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:228)
at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:357)
at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: hero2lte
Model: SM-G935F
Id: R16NW
Product: hero2ltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: G935FXXS8ETC3

**Comment by tobiasKaminsky** [comment]
How big was the content of this folder?

**Comment by sebeksd** [comment]
About 5900 files 36GB, phone and server is local network WiFi AC ~350mbps. 
I have problem with uploading my phones galery and I was thinking that maybe "[" and "]" in folder name was a problem (some Windows apps don't like this naming scheme) so I change the name.

This is new installation of Nextcloud, I am only user of this server, PHP memory limit is set to 3GB.

**Comment by sebeksd** [comment]
It seems that app store some settings/database somewhere that is persistent during reinstallation and cache cleanup. I was not able to stop this app from crashing until I rename folder back to its original name. Same thing is happening with "auto upload folder" (not sure how it i called in English version), every time I reinstall or clean cache of this app its starts whit same settings trying to upload all files and failing, its flooding my notification in Android. I'm trying to set it to upload to new clean folder but I can't do that, app always try to upload using old setting (and in general it do nothing, just continuously show new notification about conflicts).
I think that that crash mentioned above may be related to "auto upload" (PL: "Automatyczne wysyłanie").

On a side note, where app stores this settings or database (it should be deleted during reinstall) I want to remove it to try clean configuration ?

**Comment by ezaquarii** [comment]
@sebeksd Application data is stored in `/data/data/com.nextcloud.client` or something similar. This directory is purged when you uninstall the application.

**Comment by sebeksd** [comment]
I'm not sure how but every time I reinstall the app settings of "Auto upload" is set to values I set first time (for [Zdjecia] folder) and it starts flooding my system with notifications about failed upload. I've tried to set it to use empty folder so there was no conflicts but app is still flooding my system notification with old path (it is still going after one day of waiting...).
