### ISSUE TITLE
SecurityException in DrawerMenuUtil: uid 11214 cannot get user data for accounts of type: nextcloud

### ISSUE THREAD

**Issue by ronaldocb** [nextcloud/android#6331]
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.SecurityException: uid 11214 cannot get user data for accounts of type: nextcloud
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3488)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3635)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2175)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7857)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
Caused by: java.lang.SecurityException: uid 11214 cannot get user data for accounts of type: nextcloud
	at android.os.Parcel.createException(Parcel.java:2088)
	at android.os.Parcel.readException(Parcel.java:2056)
	at android.os.Parcel.readException(Parcel.java:2004)
	at android.accounts.IAccountManager$Stub$Proxy.getUserData(IAccountManager.java:1441)
	at android.accounts.AccountManager.getUserData(AccountManager.java:515)
	at com.nextcloud.client.account.UserAccountManagerImpl.getServerVersion(UserAccountManagerImpl.java:299)
	at com.owncloud.android.utils.DrawerMenuUtil.filterTrashbinMenuItem(DrawerMenuUtil.java:71)
	at com.owncloud.android.ui.activity.DrawerActivity.filterDrawerMenu(DrawerActivity.java:378)
	at com.owncloud.android.ui.activity.DrawerActivity.setupDrawerMenu(DrawerActivity.java:369)
	at com.owncloud.android.ui.activity.DrawerActivity.setupDrawer(DrawerActivity.java:250)
	at com.owncloud.android.ui.activity.DrawerActivity.setupDrawer(DrawerActivity.java:235)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onCreate(FileDisplayActivity.java:264)
	at android.app.Activity.performCreate(Activity.java:7955)
	at android.app.Activity.performCreate(Activity.java:7944)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3463)
	... 11 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.accounts.AccountManagerService.getUserData(AccountManagerService.java:1656)
	at android.accounts.IAccountManager$Stub.onTransact(IAccountManager.java:492)
	at com.android.server.accounts.AccountManagerService.onTransact(AccountManagerService.java:1114)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)


************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: starqltechn
Model: SM-G9600
Id: QP1A.190711.020
Product: starqltezh

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G9600ZHS6DTD5
```

**Comment by tobiasKaminsky** [comment]
Do you use Android for Work / profiles?
