### ISSUE TITLE
AutoUpload Fails due to too many jobs

### ISSUE THREAD

**Issue by ChrisDeath** [nextcloud/android#634]
### Actual behaviour
Activated Camara Autoupload after it finally works since 1.4.1. But then App throws exception:

```
java.lang.IllegalStateException: Apps may not schedule more than 100 
distinct jobs
	at android.os.Parcel.readException(Parcel.java:1692)
	at android.os.Parcel.readException(Parcel.java:1637)
	at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:158)
	at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:42)
	at com.owncloud.android.services.FileAlterationMagicListener.onFileCreate(FileAlterationMagicListener.java:103)
	at org.apache.commons.io.monitor.FileAlterationObserver.doCreate(FileAlterationObserver.java:379)
	at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:345)
	at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:304)
	at org.apache.commons.io.monitor.FileAlterationMonitor.run(FileAlterationMonitor.java:182)
	at java.lang.Thread.run(Thread.java:761)
```

### Expected behaviour
(new) Photos gets uploaded.
 
### Steps to reproduce
0. have more then 100 photos in camara folder (me has 374)
1. open autoupload settings
2. don't change anything
3. press save
4. Exception shown

App is restarting then and uploads the first 100 Images, but then stops until new image is added or steps above are done. While repeating that process the most images fails but some are uploaded twice or more with "(2)" attached to filename.

### Environment data
************ DEVICE INFORMATION ***********
Brand: google
Device: bullhead
Model: Nexus 5X
Id: N4F26I
Product: bullhead

************ FIRMWARE ************
SDK: 25
Release: 7.1.1
Incremental: 3532671

Stock or customized system: Stock

Nextcloud app version: 20170206 Beta

Nextcloud server version: 11.0.1

**Comment by AndyScherzinger** [comment]
Hi @ChrisDeath 
this should be fixed with the next beta release via #615 - 20170208 Beta.

Please reopen, report back if it isn't solved for you (which it should)

cc @mario
