### ISSUE TITLE
Can't open csv from .contact Folder

### ISSUE THREAD

**Issue by mrcpnt6** [nextcloud/android#6371]
Samsung S9

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.ContactsPreferenceActivity}: java.lang.ClassCastException: com.nextcloud.client.account.RegisteredUser cannot be cast to org.parceler.ParcelWrapper
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3632)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3784)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2270)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8125)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.ClassCastException: com.nextcloud.client.account.RegisteredUser cannot be cast to org.parceler.ParcelWrapper
	at org.parceler.Parcels.unwrap(Parcels.java:91)
	at com.owncloud.android.ui.activity.ContactsPreferenceActivity.onCreate(ContactsPreferenceActivity.java:96)
	at android.app.Activity.performCreate(Activity.java:7957)
	at android.app.Activity.performCreate(Activity.java:7946)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3607)
	... 11 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: star2lte
Model: SM-G965F
Id: QP1A.190711.020
Product: star2ltexx

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G965FXXU9ETF5

**Comment by ezaquarii** [comment]
@mrcpnt6  thank you for the report.

The bug you observed has been fixed recenly: https://github.com/nextcloud/android/pull/6288
The fix will soon be available in the upcoming bugfix release.
