### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by oktay454** [nextcloud/android#6376]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.IllegalArgumentException: Trying to execute a remote operation with a NULL Context
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:125)
	at com.owncloud.android.ui.fragment.contactsbackup.ContactsBackupFragment$2.doInBackground(ContactsBackupFragment.java:230)
	at com.owncloud.android.ui.fragment.contactsbackup.ContactsBackupFragment$2.doInBackground(ContactsBackupFragment.java:218)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: daisy
Model: Mi A2 Lite
Id: QQ2A.200501.001.B2
Product: lineage_daisy

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: eng.hukad.20200527.215302

**Comment by tobiasKaminsky** [comment]
Do you have some steps to reproduce?

**Comment by oktay454** [comment]
Sorry, I could not reproduce the problem.

**Comment by tobiasKaminsky** [comment]
Once it pops up again, please re-open and tell us how it happened.
