### ISSUE TITLE
Not auto uploading and app (android) crashing every time i turn auto upload on or off a folder 

### ISSUE THREAD

**Issue by ditmoli** [nextcloud/android#6417]
### Steps to reproduce
1. open android app
2. "Auto upload" from menu
3. Press cloud icon on any folder. 

### Expected behaviour
- Tell us what should happen.. should toggle on an off and then upload files from folder (if on charge and WiFi)

### Actual behaviour
- Tell us what happens... freezes every time. No uploads commence. 

This process is WAY too hard to report a simple bug. 
Come on seriously ! Makes me think I should leave the platform. I do not have the time for any of the other steps. It is obvious your app does bot operate correctly from above.

My email is ditmoli@protonmail.com

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

>  It is obvious your app does bot operate correctly from above.

It is not that obvious, otherwise it would have been reported more often. So I assume it is something device specific.
Can you give us details on your phone?

**Comment by ditmoli** [comment]
Hello

Google pixel 3
Android 10

What else can I tell you ?

Sorry but I find the experience of using your bug reporting form difficult

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by CV8R** [comment]
Brand new user to Nextcloud, new install of Server. Same app crash occuring on two different phones, two different users. One is an Oppo Reno 2Z Android 9 and the other is a Samsung Galaxy S9 on Android 10

**Comment by ditmoli** [comment]
Anything ?

**Comment by DC7IA** [comment]
I guess this is the same problem?

Or do I have to open a new issue?

```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.lib.common.operations.RemoteOperationResult.isCancelled()' on a null object reference
	at com.owncloud.android.datamodel.UploadsStorageManager.updateDatabaseUploadResult(UploadsStorageManager.java:527)
	at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:630)
	at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1347)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120151
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Android
Device: sargo
Model: Pixel 3a
Id: QQ3A.200605.002
Product: calyx_sargo

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2020.06.03.12
```

**Comment by DC7IA** [comment]
It crashes every two seconds, difficult to even hit the button to report this or copy the message before it crashes again... ._.

**Comment by DC7IA** [comment]
Oh, just realised this is probably a different problem. Will open a new issue for me.

**Comment by ditmoli** [comment]
Any chance of anyon me replying ?

**Comment by spackmat** [comment]
I tried to test auto upload with an E2EE encrypted folder in 3.13.0 RC1, bit the app crashes when I select an encrypted folder. When I choose an unencrypted folder, it works as expected. I get the following error log:

````
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.floatingactionbutton.FloatingActionButton.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
	at com.owncloud.android.ui.fragment.OCFileListFragment.registerFabListener(OCFileListFragment.java:422)
	at com.owncloud.android.ui.fragment.OCFileListFragment.updateLayout(OCFileListFragment.java:1302)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1272)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1214)
	at com.owncloud.android.ui.fragment.OCFileListFragment.onItemClicked(OCFileListFragment.java:951)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.lambda$onBindViewHolder$1$OCFileListAdapter(OCFileListAdapter.java:379)
	at com.owncloud.android.ui.adapter.-$$Lambda$OCFileListAdapter$pouWgEOOHT1aDFHaHM0Ifm3xWtY.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7161)
	at android.view.View.performClickInternal(View.java:7138)
	at android.view.View.access$3500(View.java:811)
	at android.view.View$PerformClick.run(View.java:27419)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7520)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130051
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: perseus
Model: Mi MIX 3
Id: QKQ1.190828.002
Product: perseus

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V11.0.5.0.QEEMIXM

````

Maybe it is the same cause as the errors described in this issue, maybe not.

**Comment by ditmoli** [comment]
So is there literally no way to get technical support for this service I pay for?

Good to know. Will be sure to recommend it to no one and never renew the subscription

**Comment by tobiasKaminsky** [comment]
> Good to know. Will be sure to recommend it to no one and never renew the subscription

If you are a customer please report to support.nextcloud.com.
