### ISSUE TITLE
Android crash after installing newest beta (first run)

### ISSUE THREAD

**Issue by ctrlbrk42** [nextcloud/android#6475]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.accounts.Account.name' on a null object reference
	at com.owncloud.android.services.OperationsService.toUser(OperationsService.java:714)
	at com.owncloud.android.services.OperationsService.newOperation(OperationsService.java:519)
	at com.owncloud.android.services.OperationsService.access$200(OperationsService.java:85)
	at com.owncloud.android.services.OperationsService$OperationsServiceBinder.queueNewOperation(OperationsService.java:339)
	at com.owncloud.android.authentication.AuthenticatorActivity.checkOcServer(AuthenticatorActivity.java:773)
	at com.owncloud.android.authentication.AuthenticatorActivity.onEditorAction(AuthenticatorActivity.java:1350)
	at android.widget.TextView.onEditorAction(TextView.java:7058)
	at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:138)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:363)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:93)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20200714
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: google
Device: crosshatch
Model: Pixel 3 XL
Id: RPB2.200611.009
Product: crosshatch

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 6625208

**Comment by tobiasKaminsky** [comment]
Fixed by #6476
