### ISSUE TITLE
Crash when add new account.

### ISSUE THREAD

**Issue by BugProg** [nextcloud/android#6481]
### Steps to reproduce
1. clic on "add account"
2. clic on "Log in"
3. Enter the server address 

### Expected behaviour
- Login with my new account

### Actual behaviour
- The app crash

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 9

Device model: One Plus 5T

Stock or customized system: customized /e/ os UNOFFICIAL

Nextcloud app version: Nextcloud dev 20200714

Nextcloud server version: 18.0.7

Reverse proxy: no

### Logs
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.accounts.Account.name' on a null object reference
	at com.owncloud.android.services.OperationsService.toUser(OperationsService.java:714)
	at com.owncloud.android.services.OperationsService.newOperation(OperationsService.java:519)
	at com.owncloud.android.services.OperationsService.access$200(OperationsService.java:85)
	at com.owncloud.android.services.OperationsService$OperationsServiceBinder.queueNewOperation(OperationsService.java:339)
	at com.owncloud.android.authentication.AuthenticatorActivity.checkOcServer(AuthenticatorActivity.java:773)
	at com.owncloud.android.authentication.AuthenticatorActivity.onEditorAction(AuthenticatorActivity.java:1350)
	at android.widget.TextView.onEditorAction(TextView.java:6282)
	at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:138)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:360)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20200714
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus5T
Model: ONEPLUS A5010
Id: PQ3A.190801.002
Product: OnePlus5T

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: eng.root.20200713.174834

**Comment by tobiasKaminsky** [comment]
Will be fixed via #6476

**Comment by BugProg** [comment]
Thank you
