### ISSUE TITLE
newly installed nextcloud dev crashes immediately 

### ISSUE THREAD

**Issue by gwhitney** [nextcloud/android#6485]
Installed latest.apk, opened app, entered server URL, hit next -> crash, backtrace below.

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.accounts.Account.name' on a null object reference
	at com.owncloud.android.services.OperationsService.toUser(OperationsService.java:714)
	at com.owncloud.android.services.OperationsService.newOperation(OperationsService.java:519)
	at com.owncloud.android.services.OperationsService.access$200(OperationsService.java:85)
	at com.owncloud.android.services.OperationsService$OperationsServiceBinder.queueNewOperation(OperationsService.java:339)
	at com.owncloud.android.authentication.AuthenticatorActivity.checkOcServer(AuthenticatorActivity.java:773)
	at com.owncloud.android.authentication.AuthenticatorActivity.onEditorAction(AuthenticatorActivity.java:1350)
	at android.widget.TextView.onEditorAction(TextView.java:5397)
	at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:139)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:304)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6930)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20200714
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: samsung
Device: gvwifiue
Model: SM-T670
Id: LMY47X
Product: gvwifiue

************ FIRMWARE ************
SDK: 22
Release: 5.1.1
Incremental: T670UEU2APJ1
## Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Will be fixed via #6476
