### ISSUE TITLE
App crashed and show error code

### ISSUE THREAD

**Issue by VantStark** [nextcloud/android#6490]
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=3393, totalRows=1454
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:942)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:161)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:131)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:249)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:281)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:190)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProviderOperation.applyInternal(ContentProviderOperation.java:342)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:314)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:670)
	at android.content.ContentProvider.applyBatch(ContentProvider.java:2179)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:398)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:532)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:520)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:1915)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:405)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:478)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:369)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:228)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:357)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus7Pro
Model: GM1910
Id: QKQ1.190716.003
Product: OnePlus7Pro_CH

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2005132200

**Comment by tobiasKaminsky** [comment]
Do you know what you did to get this error?

**Comment by VantStark** [comment]
I just delete many files on the web page, and clean all the cache files.
The phone with the crashed app has not been opened for more than a week. once I click the app, it crashed.

**Comment by VantStark** [comment]
The app can sync files in background normally, but  everytime when I refresh the file list, it will get stuck.

**Comment by xboxboy** [comment]
I get the same error, but with the first error line being "android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=3173, totalRows=196"

App has worked fine for years:

I reorganized my files and directories via the web page.

Crashing seems to coincide since that.

I have cleared app cache with no change in behaviour.

Auto uploads appear to be working correctly: with all my latest pictures etc uploaded correctly.

Just opening the app, the app appears to try to sync/refresh and then crashes.

Asus Max Pro M1
Android 9
App from google play, version 3.12.1

Server is nextcloud 18.0.7

**Comment by xboxboy** [comment]
Just applied the latest update that come through google play store ie. v.3.13.0 but this issue remains.

**Comment by tobiasKaminsky** [comment]
> The largest folder is 11GB

How many files are in that? 
I suspect that the app cannot deal with it if the file count is too high.

**Comment by xboxboy** [comment]
How many files are in that?
I suspect that the app cannot deal with it if the file count is too high.

Apologies for slow reply: Over 2,700.

So a fair few.

**Comment by tobiasKaminsky** [comment]
Duplicate of #6688
