### ISSUE TITLE
Nextcloud keeps crashing

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/android#6512]
### Steps to reproduce
1. Use nextcloud android
2. See it crash and loop over the device authentication

### Expected behaviour
- no crash

### Actual behaviour
- crash

### Can you reproduce this problem on https://try.nextcloud.com?
- no

### Environment data
Android version: 10

Device model: MI A2

Stock or customized system: stock

Nextcloud app version: 3.12.1

Nextcloud server version: 19

Reverse proxy: traefik

#### App logs
```
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:120)
	at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.3:1)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:50)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/data/app/com.nextcloud.client-KQEeyyOBgJatT92Whgj9bg==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.client-KQEeyyOBgJatT92Whgj9bg==/lib/arm64, /data/app/com.nextcloud.client-KQEeyyOBgJatT92Whgj9bg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: xiaomi
Device: jasmine_sprout
Model: Mi A2
Id: QKQ1.190910.002
Product: jasmine

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V11.0.11.0.QDIMIXM
```

**Comment by skjnldsv** [comment]
duplicate of https://github.com/nextcloud/android/issues/4675
