### ISSUE TITLE
Error when trying to connect Nextcloud Android app

### ISSUE THREAD

**Issue by ThomasGodefroy** [nextcloud/android#6513]
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Could not execute method for android:onClick
	at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:414)
	at android.view.View.performClick(View.java:6608)
	at android.view.View.performClickInternal(View.java:6585)
	at android.view.View.access$3100(View.java:785)
	at android.view.View$PerformClick.run(View.java:25921)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:409)
	... 11 more
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.accounts.Account.name' on a null object reference
	at com.owncloud.android.services.OperationsService.toUser(OperationsService.java:714)
	at com.owncloud.android.services.OperationsService.newOperation(OperationsService.java:519)
	at com.owncloud.android.services.OperationsService.access$200(OperationsService.java:85)
	at com.owncloud.android.services.OperationsService$OperationsServiceBinder.queueNewOperation(OperationsService.java:339)
	at com.owncloud.android.authentication.AuthenticatorActivity.checkOcServer(AuthenticatorActivity.java:773)
	at com.owncloud.android.authentication.AuthenticatorActivity.onTestServerConnectionClick(AuthenticatorActivity.java:539)
	... 13 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20200714
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: xiaomi
Device: whyred
Model: Redmi Note 5
Id: PKQ1.180904.001
Product: whyred

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: V11.0.3.0.PEIMIXM

**Comment by tobiasKaminsky** [comment]
> Version: 20200714

This should be fixed with a newer version.
Can you update and retry?
If it does not work, please re-open.
