### ISSUE TITLE
[3.13.0RC1] Crash on startup and not only

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#6536]
whether I do a clean install that updating from nextcloud stable app crashes.  with clean installation the application starts but crashes when I tend to access an external storage folder, in my case via smb protocol.  if I upgrade from stable 3.12.0 to beta 3.13..0 rc1 application crashes when I try to start it.  I also sent error log.  and I take screenshots that I attach here.

![Screenshot_20200724-143606](https://user-images.githubusercontent.com/35575744/88391731-0aae6080-cdbb-11ea-94c9-56d97e26dbab.png)

**Comment by tobiasKaminsky** [comment]
> but crashes when I tend to access an external storage folder, in my case via smb protocol.

This only happens when you use an external storage?
So
- app start
- browse "normal" folders -> fine
- go into external storage -> crash?

**Comment by tigernero79** [comment]
Yes,
or after an update from 3.12 to 3.13 RC1 in this case crash on startup

**Comment by doits** [comment]
I have a similar problem/backtrace, it crashes when trying to start the app.

```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to resume activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4205)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference
	at com.owncloud.android.datamodel.OCFile.getDecryptedRemotePath(OCFile.java:212)
	at com.owncloud.android.datamodel.OCFile.getDecryptedFileName(OCFile.java:388)
	at com.owncloud.android.datamodel.OCFile.getFileName(OCFile.java:379)
	at third_parties.daveKoeller.AlphanumComparator.compare(AlphanumComparator.java:91)
	at com.owncloud.android.utils.FileSortOrderByName.lambda$sortCloudFiles$0(FileSortOrderByName.java:54)
	at com.owncloud.android.utils.-$$Lambda$FileSortOrderByName$YdISYWUaQVK-4PIrs4OOhoEHgbQ.compare(Unknown Source:6)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:239)
	at java.util.Arrays.sort(Arrays.java:1492)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:206)
	at com.owncloud.android.utils.FileSortOrderByName.sortCloudFiles(FileSortOrderByName.java:52)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:912)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1261)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1214)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1203)
	at com.owncloud.android.ui.activity.FileDisplayActivity.updateListOfFilesFragment(FileDisplayActivity.java:629)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onResume(FileDisplayActivity.java:1103)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453)
	at android.app.Activity.performResume(Activity.java:7962)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
	... 11 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: coral
Model: Pixel 4 XL
Id: QQ3A.200705.002
Product: coral

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 6506677
```

**Comment by AndyScherzinger** [comment]
thanks for the report ans stacktrace @doits - afaik @tobiasKaminsky has a fix for this that'll ship with the next release candidate 🚀

**Comment by goldengel** [comment]
Ihis bug eats battery enormous. When will it be released?

**Comment by AndyScherzinger** [comment]
> This bug eats battery enormous. When will it be released?

has been released already afaik, you should see RC2 on GPlay

**Comment by AndyScherzinger** [comment]
#6557 should fix this, please update to RC2 and re-open if issue persists

**Comment by goldengel** [comment]
Can I test? Can you share the apk file?

**Comment by tigernero79** [comment]
@AndyScherzinger @tobiasKaminsky 

unfortunately error has now moved on to the encrypted e2e folders, as i try to access it application crashes.  but how is it possible to have RCs that instead of having new bugs return to having old bugs?

if possible reopen the problem, I updated from nextcloud 3.12 stable to 3.13 rc2

![Screenshot_20200803-212327](https://user-images.githubusercontent.com/35575744/89219355-e7ac5980-d5cf-11ea-8106-26fa6728e337.png)

**Comment by AndyScherzinger** [comment]
@tigernero79 re-openend, thanks for the update (3.13 ships an updated E2EE implementation)
@tobiasKaminsky there still seem to be issues with E2EE

@goldengel see https://github.com/nextcloud/android/pull/6557#issuecomment-665671865 for a test build (this APK installs in parallel)

**Comment by goldengel** [comment]
Thank you very much. For the moment, since installation of Nextcloud QA, not one image was automatically synced from Photo Gally. I restarted, switched Wifi off, on, setup auto upload again for several foders. Main problem is gone but now auto upload seems to be fully disabled. I keep testing.

**Comment by tobiasKaminsky** [comment]
Auto upload should work, but is also independent from this bug report.
Thanks for testing!

**Comment by tigernero79** [comment]
@tobiasKaminsky with the rc3 there is problem of uploading files in e2e folders, even if i create new e2e folder i cannot upload files in and on external e2e folders on external hd app it crashes because you have closed the problem?

**Comment by tobiasKaminsky** [comment]
What kind of external storage is this? How is this mounted into e2e?
@georgehrke do you see there any possible problems?

**Comment by tigernero79** [comment]
@tobiasKaminsky 

I have an external hd connected usb to the PC and configured via smb on nextcloud done this I created on external hd then encrypted e2ee folder but even if on hd where nextcloud installed it is still not possible to upload the files it gives me error loading this with 3.13 rc3

![20200806_153953](https://user-images.githubusercontent.com/35575744/89538633-1c502900-d7fb-11ea-851b-f2b72631a045.jpg)

**Comment by tobiasKaminsky** [comment]
Can you give us a logcat?

**Comment by tigernero79** [comment]
@tobiasKaminsky 
I'm currently on vacation I made videos that you can download at this link where you will see that with rc3 I can neither delete files in the e2ee folder nor upload a simple file, this not only on external hd but also if I create an e2ee folder on hd where it is  installed nextcloud.  moreover the files are not decrypted they remain encoded

I'm currently on vacation I made videos that you can download at this link where you will see that with rc3 I can neither delete files in the e2ee folder nor upload a simple file, this not only on external hd but also if I create an e2ee folder on hd where it is  installed nextcloud.  moreover the files are not decrypted they remain encoded.

here url my video:

https://tigernero.duckdns.org/index.php/s/tfgTTm25cLBFC8a

**Comment by tobiasKaminsky** [comment]
Have you followed https://help.nextcloud.com/t/help-test-the-latest-version-of-e2ee/87590 ?
It seems that this is old data, as it cannot decrypt the file names…

**Comment by tigernero79** [comment]
Ok try, thanks

**Comment by tigernero79** [comment]
my public openpgp key ecdsa ed25519 

-----BEGIN PGP PUBLIC KEY BLOCK-----

mDMEXyMRDhYJKwYBBAHaRw8BAQdA8VFvl+vIWThKWezE3xyP3n8edpBU/WF4g9NS
xvqI9KS0Nkdpb3Zhbm5pIFJpdG8gUnVzc28gKEluIEdvZCBXZSBUcnVzdCkgPG5l
cm83OUBtc24uY29tPohyBBMWCgAaBAsJCAcCFQoCFgECGQEFgl8qzAsCngECmwMA
CgkQWInUuqdSyVbPgwD7BIIdpbmcP9InHOJgnMTd9szI9MlfLC1GqOXNtfk23D4B
AIKe2Vp0zu5O8Pa0VViN5PLB9zivLJViXRMLL6zaE8wMiQIcBBABCgAGBQJfK/yY
AAoJEKFq8nml94865G0P/iEleYR36ZcpKEpOdu9gzAUp3bt7Ed2PUNggHowhAW/y
zF4pbRxCcHLXob2L5ib4M00Q/KE1cSFfudZbTWNI/5TJQESrzsF16kWC3CwRLo52
KVMPzqslXD8gIglFKbMSyPhjtg8qO2iWI1eOKyI8h0JAR48XR9TslKPxmhf4ypGp
arGzJZjalimfOcS9c3FjdFdUjFutCO9ZO/7nUKAJSEm1Jx/EH3H9NlorSyWJIBdC
Q6NhAkx+X+MS9fvgc+a4xxM9h1Vaf1mpEyJzqRc95OI3DBc98z5ss5Hw3pQRx6cO
awdLr32LF+Jm9bzjQDuq5uaFKp1ZLiLYWxAtcgoZdUMy0SoRD+oICo9UAe1faQZE
RWetSiPvy2yMrifTa1S6OrX3qqu3JxD9FoL8JE29hjCMmO8Hmu6meVQDgNXu2FDf
i3gxIDKvjIR01urOYhnDqE+kovvdjDofgEIyaMmC5GGzVks+uHt0/54cNYvkGRVR
XaTHLpxT9L6hPA5sHzqn2A1LVL31EMRaCi6gfPLs2hy20YKdIhvD1B9MiTQ2tLtZ
B5I1Uyywv704gurwcduuumCv+sckwuB5pbAc17WVpXch+jY1Qn9A6TDLeikq6OYE
9XoRhdqWYSKCEDiAMN3h7hKHdrDuD84BGy3VHRtLCc1nhINyfgRdFx1aOxCYYUfH
tCVHaW92YW5uaSBSaXRvIFJ1c3NvIDxuZXJvNzlAZW1haWwuaXQ+iHIEExYKABoE
CwkIBwIVCgIWAQIZAAWCXyrLegKeAQKbAwAKCRBYidS6p1LJVs+DAQCP2/E8TwVm
ptGs7i6TDXsEHmDb6P3bzICCY7waZOKdfwEApHlYgbLkGl1wnerkEwikGQ41BpI+
zBzbrYRbfVR56AS0IVRpQGVyIDxzZW50aW1lbnRpQHBlbnNpZXJhbmRvLml0Pohy
BBMWCgAaBAsJCAcCFQoCFgECGQAFgl8rpOUCngECmwMACgkQWInUuqdSyVbPgwEA
hPVPqHSAQh+saqQuvymlY6qpRR4CCN9Bzb9LMfTgqoYA/jMfWDZgcxROcXRwIvwO
U/anefrqoAo50zXgokYVT6cFuDMEXyMRDhYJKwYBBAHaRw8BAQdAG/OHlSHidgLD
Ajtnpfz8jSmdr795wwuvxUSR0NkL5juIeAQYFggAIBYhBMn+yS45g80UTzezEFiJ
1LqnUslWBQJfIxEOAhsgAAoJEFiJ1LqnUslW/5UBAMIUzaDK5eLYMl3jmHhmVuYd
OxvxwOu3gIwSypCdr+nBAP9ZG98aT4dCKBPr2pj1yR/wyJ05Xr0CBYeQ2d423Irt
DLg4BF8jEQ4SCisGAQQBl1UBBQEBB0CyRaHjSG1crfnO6YqUR34kJctcBNMmsl0E
IGxZJI9ydAMBCAeIeAQYFggAIBYhBMn+yS45g80UTzezEFiJ1LqnUslWBQJfIxEO
AhsMAAoJEFiJ1LqnUslW6a8BAOFzsQIJHnC9VYRcL9FzRJc9m79WlFAO3MEoqzhK
6xBDAQD8mSA3h9khViAQoBSGl2LezzjDr5zKX8CLEVsGAQSQBg==
=WGX5
-----END PGP PUBLIC KEY BLOCK-----
