### ISSUE TITLE
Nextcloud app crashes

### ISSUE THREAD

**Issue by LeongSumHoy** [nextcloud/android#6538]
### Steps to reproduce
1.Open Nextcloud app, crashes instantly. 
2. 
3. 

### Expected behaviour
- Tell us what should happen
Opens Nextcloud app without crashing
### Actual behaviour
- Tell us what happens
Crashed with errors on screen

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:
Android 10
Device model: 
Pixel 3
Stock or customized system:

Nextcloud app version:
3.12.1
Nextcloud server version:
19.0.1
Reverse proxy:

#### Web server error log
```
Insert your webserver log here

************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Couldn't read row 140, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:542)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:77)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:179)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProviderOperation.applyInternal(ContentProviderOperation.java:332)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:309)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:670)
	at android.content.ContentProvider.applyBatch(ContentProvider.java:2117)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:371)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:532)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:520)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:1875)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:405)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:478)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:369)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:228)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:357)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: crosshatch
Model: Pixel 3 XL
Id: QQ3A.200705.002
Product: crosshatch

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 6506677

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Do you remember what you did?

**Comment by LeongSumHoy** [comment]
Hi Tobias,

I opened my Nextcloud application and it crashed instantly.
However, I removed it from my Android mobile and install a fresh copy, that
worked fine.

Not exactly sure what caused it, but it's working at the moment.

Thank you.

Regards,
SumHoy.

**Comment by LeongSumHoy** [comment]
Hi Guys,

Do close this issue.  I've got no more issues ever since my last reinstall.


Regards,
SumHoy.
