### ISSUE TITLE
Nextcloud v3 - sqLite error on Android

### ISSUE THREAD

**Issue by DorinJ** [nextcloud/android#6541]
### Steps to reproduce
1. open Nextcloud, Android app
2. click Log in button
3. enter server's address

### Expected behaviour
- view app dashboard

### Actual behaviour
- crash

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 8.0.0

Device model: Sony Xperia XZ (F8331) 

Stock or customized system:

Nextcloud app version: 3.12.1

Nextcloud server version: 16

Reverse proxy:

### Logs

************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:740)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1579)
	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1525)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:643)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:627)
	at android.content.ContentProvider$Transport.update(ContentProvider.java:359)
	at android.content.ContentResolver.update(ContentResolver.java:1675)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveCapabilities(FileDataStorageManager.java:1967)
	at com.owncloud.android.operations.GetCapabilitiesOperation.run(GetCapabilitiesOperation.java:44)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136)
	at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:64)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:287)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:267)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:220)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:357)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Sony
Device: F8331
Model: F8331
Id: 41.3.A.2.192
Product: F8331

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: 1629831864

**Comment by tobiasKaminsky** [comment]
> android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)

I fear that this is out of our hands.
This is something Android related.
It might help to restart the device.
