### ISSUE TITLE
Crashes after login

### ISSUE THREAD

**Issue by thorus90** [nextcloud/android#6545]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED flg=0x10 pkg=com.nextcloud.client (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver@993db49
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1546)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=26085, uid=1010183 requires android.permission.BROADCAST_STICKY
	at android.os.Parcel.createException(Parcel.java:1953)
	at android.os.Parcel.readException(Parcel.java:1921)
	at android.os.Parcel.readException(Parcel.java:1871)
	at android.app.IActivityManager$Stub$Proxy.unbroadcastIntent(IActivityManager.java:3897)
	at android.app.ContextImpl.removeStickyBroadcast(ContextImpl.java:1556)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
	at com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver.onReceive(FileDisplayActivity.java:1410)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1533)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.unbroadcastIntent(ActivityManagerService.java:23972)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:183)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3648)
	at com.android.server.am.HwActivityManagerService.onTransact(HwActivityManagerService.java:609)
	at android.os.Binder.execTransact(Binder.java:739)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWCMR09
Model: CMR-W09
Id: HUAWEICMR-W09
Product: CMR-W09

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 9.1.0.335C432

**Comment by AndyScherzinger** [comment]
Hi @thorus90, are you using Google Work Profiles?

**Comment by thorus90** [comment]
Not really sure what that means, the nextcloud instance is selfhosted(as an docker container) with an active directory for authentication. The Device where it crashes is a Huawei MediaPad M5.

**Comment by AndyScherzinger** [comment]
> Perhaps the info that it is a secondary account on the tablet is useful?

Yes that is indeed helpful 👍 

@tobiasKaminsky Is there a difference between Google Work Profiles and secondary accounts (technically speaking)?

For your information @thorus90:
```
Permission Denial: unbroadcastIntent() from pid=26085, uid=1010183 requires android.permission.BROADCAST_STICKY
```
from your reports points to such profile-related issues as in the client isn't compatible with Google Work Profiles - I don't know anything regarding secondary account on the Android device though :/

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky Is there a difference between Google Work Profiles and secondary accounts (technically speaking)?

No, unfortunately both seem to cause problems.

**Comment by AndyScherzinger** [comment]
> Second accounts work on some devices / vendors, but not on all.

I think the reason might be a different one: @thorus90 can you try to install the app itself in both profiles? From "the internet" it seems the security exception might not occur if the application is installed in all profiles. So at least that is worth a try.

Sticky broadcasts have been deprecated with Android v21 so at some point we will have to get rid of them completely :/ (which might be quite some work where I think @ezaquarii is indirectly solving such issues with the new download manager implementation as one way to not rely on such mechanisms).

**Comment by thorus90** [comment]
@AndyScherzinger thanks, Installing it into the main profile(I only have two profiles on the device) fixed the issue.

**Comment by AndyScherzinger** [comment]
@thorus90 glad to hear the workaround helps with the situation, still the issue remains but is tracked in the issue linked by Tobias 👍

**Comment by AndyScherzinger** [comment]
Duplicate of #6654
