### ISSUE TITLE
App Crashed

### ISSUE THREAD

**Issue by Animus83** [nextcloud/android#6547]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:365)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:784)
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList.sort(ArrayList.java:1472)
	at java.util.Collections.sort(Collections.java:201)
	at com.owncloud.android.utils.FileSortOrderByName.sortCloudFiles(FileSortOrderByName.java:52)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.setData(OCFileListAdapter.java:890)
	at com.owncloud.android.ui.fragment.OCFileListFragment$3.doInBackground(OCFileListFragment.java:1562)
	at com.owncloud.android.ui.fragment.OCFileListFragment$3.doInBackground(OCFileListFragment.java:1544)
	at android.os.AsyncTask$2.call(AsyncTask.java:345)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWDUB-Q
Model: DUB-LX1
Id: HUAWEIDUB-LX1
Product: DUB-LX1

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: 167(C185)

**Comment by psi-4ward** [comment]
Same here. App completely broken since the update

**Comment by tobiasKaminsky** [comment]
Is this happening on every folder?

**Comment by Animus83** [comment]
The whole app crashes. Not a specific folder.

**Comment by tobiasKaminsky** [comment]
My question was more if this happens directly when listing root of your cloud files, or only if you try to enter a specific folder?

**Comment by coop2540** [comment]
> My question was more if this happens directly when listing root of your cloud files, or only if you try to enter a specific folder?

When I make the login to the server the apps seems to login but redirects to the login page. Never enter at directories.
I made the login using user and pass, but also with QR code, and no way both.

**Comment by tobiasKaminsky** [comment]
Can you try it with try.nextcloud.com to see if it a problem on your device?

**Comment by coop2540** [comment]
I have finished testing with https://demo2.nextcloud.com and I have obtained the same results
The tokens worked, I gave permission, but after that the app redirects to login. The same with my server.

I had the app working, with two servers and I was able to change users and server.  
I also had Talk app. 

I tried everything (everything I know) - uninstall all apps, reinstall from playstore or from FDroid . Clear all cache apps , reboots, etc . All, and no way to connect to the server. 

Nextcloud Talk is working and connects.... 
Reinstall Nextcloud after, try to connect same way, browser to login and give permission, seems to show a directory 1 sec and redirects to login again... 
Nextcloud Talk continues working ...

Thanks a lot for your effort.

**Comment by tobiasKaminsky** [comment]
Then this must be a real strange device specific problem :S

**Comment by ezaquarii** [comment]
@tobiasKaminsky I'm affraid not. It is a known problem some other contributor tried to fix a year ago. Concurrent access exception can be probably avoided by locking the container and working on a clone.

**Comment by tobiasKaminsky** [comment]
Ah, right, I remember that I also tried it, but this was related to changing date while sorting in upload view.

@coop2540 from source code it seems that you are perfoming some kind of search? Photo search or a manual file search and then it crashes?

**Comment by tobiasKaminsky** [comment]
If there are two concurrent searches, then it might happen that data to sort is changing…

**Comment by coop2540** [comment]
> Ah, right, I remember that I also tried it, but this was related to changing date while sorting in upload view.
> 
> @coop2540 from source code it seems that you are perfoming some kind of search? Photo search or a manual file search and then it crashes?

I'm sorry I don't remember what I was doing. It's not sure, but I think I was trying apps like cospend and moneybuster. 
I have four instances of nextcloud in the same server, and I changed with no problem between from the smartphone.

I'm also think that it's a problem with my android, it's a conflict between android and nextcloud app. I use DAVx5 too, for synchronize contacts, tasks and calendar. 

The point is that this conflict does not occur with nextcloud talk

I'm going to try other apps (deck, bookmarks) 

Deck makes the same fail, Talk continues working

Seems that Talk don't take the account from the accounts in android, and the problem it's here, to create a Nextcloud Account in android (the same, from Nextcloud app or from add account in the system).

I know, it's my android, but... I have to reset totally my smartphone?

Thanks so much for your attention.

**Comment by Animus83** [comment]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$AsyncFutureTask.done(AsyncTask.java:429)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList.sort(ArrayList.java:1472)
	at java.util.Collections.sort(Collections.java:208)
	at com.owncloud.android.utils.FileSortOrderByName.sortCloudFiles(FileSortOrderByName.java:52)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.setData(OCFileListAdapter.java:1001)
	at com.owncloud.android.ui.fragment.OCFileListFragment$2.doInBackground(OCFileListFragment.java:1576)
	at com.owncloud.android.ui.fragment.OCFileListFragment$2.doInBackground(OCFileListFragment.java:1558)
	at android.os.AsyncTask$3.call(AsyncTask.java:389)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWVOG
Model: VOG-L09
Id: HUAWEIVOG-L09
Product: VOG-L09

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.1.0.151C316
