### ISSUE TITLE
Unable to start AuthenticatorActivity due to IllegalArgumentException: Unsupported ABI: null

### ISSUE THREAD

**Issue by oswajas** [nextcloud/android#6565]
### Steps to reproduce

Start Nextcloud Android App

### Expected behaviour

II will eventually be able to log in to my Nextcloud server.

### Actual behaviour

I see a window with the following message

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.authentication.AuthenticatorActivity}: java.lang.IllegalArgumentException: Unsupported ABI: null
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2649)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2710)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1461)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6088)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.IllegalArgumentException: Unsupported ABI: null
	at dalvik.system.VMRuntime.getInstructionSet(VMRuntime.java:370)
	at dalvik.system.VMRuntime.is64BitAbi(VMRuntime.java:383)
	at android.webkit.WebViewFactory.getWebViewNativeLibraryPaths(WebViewFactory.java:505)
	at android.webkit.WebViewFactory.loadNativeLibrary(WebViewFactory.java:630)
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:344)
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
	at android.webkit.CookieManager.getInstance(CookieManager.java:39)
	at com.owncloud.android.authentication.AuthenticatorActivity.deleteCookies(AuthenticatorActivity.java:360)
	at com.owncloud.android.authentication.AuthenticatorActivity.onCreate(AuthenticatorActivity.java:287)
	at android.app.Activity.performCreate(Activity.java:6679)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2602)
	... 9 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: matissewifi
Model: SM-T530
Id: NDE63X
Product: samsung/matissewifixx/matissewifi:5.0.2/LRX22G/T530XXU1BOD8:user/release-keys

************ FIRMWARE ************
SDK: 25
Release: 7.1
Incremental: e93aca0a67

### Environment data
Android version: 7.1

Device model: Samsung Galaxy Tab 4 SM-T530

Stock or customized system: CyanogenMod 14.1

Nextcloud app version: Nextcloud Dev 20200723 from FDroid

**Comment by AndyScherzinger** [comment]
Hi @oswajas 
according to your crash report this is within Android itself, see

```
Caused by: java.lang.IllegalArgumentException: Unsupported ABI: null
at dalvik.system.VMRuntime.getInstructionSet(VMRuntime.java:370)
android.webkit.WebViewFactory
```

There is likely nothing we can do about this from an app's perspective. Could you check if you can install the webview update from Google: https://play.google.com/store/apps/details?id=com.google.android.webview this should replace your system web view with a actual version which might solve this matter for you.

**Comment by oswajas** [comment]
Updating Android System WebView solved the problem.

**Comment by AndyScherzinger** [comment]
@oswajas Glad to hear this solved the issue 🚀
