### ISSUE TITLE
"Permission Denied" error when uploading from Android Client (but fine from Windows and iOS Clients)

### ISSUE THREAD

**Issue by jmone1** [nextcloud/android#6570]
I was asked to create this ticket from the Help Desk Post - https://help.nextcloud.com/t/permission-denied-when-uploading-from-android-client-but-fine-using-windows-client/83696

### Steps to reproduce
When trying to upload from an Android Phone, I get the following error:

`Thu Jun 04 23:02:28.952824 2020] [core:crit] [pid 597] (13)Permission denied: [client xxx.xxx.xxx.xxx:12345] AH00529: /home/me/public_html/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/me/public_html/' is executable`

In initial testing, I've found:

- OK : Creating, deleting, downloading files is fine from my Win10 PC using the Win10 Nextcloud App
- OK: Creating Folders, deleting & downloading files is fine from my phone using the Nexcloud App
- Fail: Uploading Files using the Nextcloud App. The file upload itself works fine, but a few seconds after 100% uploaded I get “You are not permitted to upload to this folder” and the upload items shows as failed and “Permission Denied”.

If further testing I found:

- iPhone App: No Issues
- Win10 Desktop App: No Issues
- Android App: I’ve now tested on 2 x phones and both fails the same way

I have tried to some basic troubleshooting but have been unable to change the behaviour

- I have installed/uninstalled/reinstalled the Android App many times.
- I have tried changing the the .htaccess file in both public_html and under public_html/nextcloud from 644 to 755

### Expected behaviour
- Uploading from an Android Client should work

### Actual behaviour
- Uploading from an Android Client Fails

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:  10 - Kernel 4.14.117

Device model: LG V50 (can test on others)

Stock or customized system: Stock

Nextcloud app version: 3.12.1

Nextcloud server version: 18.0.5, 19.0.0, 19.0.1
Operating system and version: Linux 3.10.0-1062.18.1.el7.x86_64 x86_64
Apache or nginx version : ??
PHP version: 7.3.18

Reverse proxy: unsure

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I asked @jmone1 to open an issue since from the description (also posted on the forum) I think this needs some further debugging (since it works with other clients)

**Comment by jmone1** [comment]
Happy to test, try changes, provide logs, even provide anaccount on the site if you need.

**Comment by tobiasKaminsky** [comment]
> Thu Jun 04 23:02:28.952824 2020] [core:crit] [pid 597] (13)Permission denied: [client xxx.xxx.xxx.xxx:12345] AH00529: /home/me/public_html/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/me/public_html/' is executable

This is output of web server, or?

**Comment by jmone1** [comment]
Apologies, If I'm flying blind to get you the correct info.  That error (and others like it) are from CPanel's Error Log for the Web Server.  I get a few of these most days but I'm unsure if they are related to the upload issue from the android client as I don't see other errors being reported in CPanel or the Next Cloud Log.

For example, I just tried uploading another file from my android client (a couple of times) and kept an eye on both the NextCloud Log (Admin / Logging) and also the Web Server log.  Both times they failed to upload but neither log reported any new issues with the failure.  

The only "recent" errors in the Nextcloud Log are as follows (and the last one was 3 days ago):
`[PHP] Error: session_start(): A session had already been started - ignoring at /home/bray/public_html/nextcloud/lib/private/Session/Internal.php#209

GET /nextcloud/ocs/v1.php/cloud/user?format=json
from xx.xx.xx at 2020-08-03T07:18:54+00:00`

**Comment by jmone1** [comment]
I also re-tested uploading by adding a file in my Nextcloud Windows Directory and it syned up fine to the server.

**Comment by jmone1** [comment]
Updated to 19.02 still failed

**Comment by tobiasKaminsky** [comment]
Is this happening both, for small and big files?
Background is that we have two different approaches.
Can you test it with <500kb and >10Mb?

**Comment by jmone1** [comment]
Tested on a 70K and a 30MB file.  Both failed the same way.

**Comment by tobiasKaminsky** [comment]
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by jmone1** [comment]
Thanks Tobias - E-Mail sent.

**Comment by tobiasKaminsky** [comment]
do you have any kind of rate limiting?
I logged in, uploaded a file, tried it again and now I cannot connect anymore.

As far as I could see this seems to be a server problem, as you cannot upload a file, but this fails on server side.

**Comment by jmone1** [comment]
Hi Tobias,

No rate limiting that I know off, though I was just uploaded (an hour or so ago) a 2.1GB Video File to my bray.id.au/nexcloud instance (I have two next cloud instances on the same server) from my Windows Nextcloud Client.  It uploaded just fine.  

 

I just logged into https://jmone.org/jmonenextcloud with a browser using the “Support” user account and could upload a document just fine as well (using the Windows Client) called “TestUpload.TXT”.  I also tried to upload a document from the Web Interface (which I never do) but it FAILED with an “Unknown Error”.

 

Thanks

Nathan

**Comment by jmone1** [comment]
Sent an e-mail

**Comment by tobiasKaminsky** [comment]
Still does not work…

**Comment by jmone1** [comment]
e-mail sent

**Comment by tobiasKaminsky** [comment]
I tried it again.
And now I see that I get a http nc error html page back when trying to do a webdav put.
So this is clearly a problem on server, probably with http redirect / rewrite.

**Comment by brandon2e** [comment]
Commenting to add what helped me since there was little online about this;

1. Files I added to Nextcloud/data somehow had the wrong owner, not www-data but my main Linux user name. chown the whole folder to be sure and could upload from the Android client

2. I had some TWRP files (Android backup utility) I couldn't delete from the Android client but that seemed to be specific to those files, no idea why because I could delete other files. Removed the from terminal in Linux and good to go.

**Comment by jmone1** [comment]
Thanks - I don't even have a user or group called www-data.

**Comment by Happyfeet01** [comment]
I have the same error.

Strange is that all picture from the DCIM Folder on my android Device can't be uploaded, but the upload from Screenshots from an other folder working.
I have no error messages in Nextcloud and Nginx. Maybe an Smartphone problem?

Have nextcloud 20.1 installed
![Screenshot_20201108_083415_com nextcloud client](https://user-images.githubusercontent.com/3295104/98460131-c5fbd900-21a1-11eb-8058-826f73af4a8e.jpg)

**Comment by tobiasKaminsky** [comment]
Hm, might be.
Where are those images stored? Is it an external sdcard?

**Comment by Happyfeet01** [comment]
No internal

**Comment by tobiasKaminsky** [comment]
When you try to upload the exact same file to the same remote folder manually, does this then work?

**Comment by mathieujobin** [comment]
I am still having this issue, it works for a while... then stop working, and I'm not sure, maybe I should turn off automatic upload and wait a week? 
its no longer uploading anything...

**Comment by mathieujobin** [comment]
please reopen this issue @github-actions

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by mathieujobin** [comment]
@tobiasKaminsky I just tried that. I have USB debugging enabled, but `adb` cannot see my device.

```
$ adb shell ps
error: no devices/emulators found
```

I had ~20GB auto-uploaded and suddenly permission error.
is there a server setting that I can check?

**Comment by mathieujobin** [comment]
Ok, I changed cable/port and I can fetch the logs now.

```
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation: Existence check for https://cloud.EXAMPLE.net/next/remote.php/dav/files/example//InstantUpload/Camera/IMG_20220110_075009.jpg targeting for  existence : Socket timeout exception
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation: java.net.SocketTimeoutException: failed to connect to cloud.EXAMPLE.net/7x.1xx.2xx.2xx (port 443) from /192.168.yy.xx (port 40863) after 50000ms: isConnected failed: ETIMEDOUT (Connection timed out)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at libcore.io.IoBridge.isConnected(IoBridge.java:283)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at libcore.io.IoBridge.connectErrno(IoBridge.java:192)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at libcore.io.IoBridge.connect(IoBridge.java:134)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at java.net.Socket.connect(Socket.java:621)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at com.google.android.gms.org.conscrypt.AbstractConscryptSocket.connect(:com.google.android.gms@214815037@21.48.15 (150400-414534850):4)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at com.owncloud.android.lib.common.network.AdvancedSslSocketFactory.createSocket(AdvancedSslSocketFactory.java:184)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:200)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:171)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at com.owncloud.android.lib.resources.files.ExistenceCheckRemoteOperation.run(ExistenceCheckRemoteOperation.java:95)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:187)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at com.owncloud.android.operations.UploadFileOperation.existsFile(UploadFileOperation.java:1152)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at com.owncloud.android.operations.UploadFileOperation.checkNameCollision(UploadFileOperation.java:941)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at com.owncloud.android.operations.UploadFileOperation.normalUpload(UploadFileOperation.java:760)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at com.owncloud.android.operations.UploadFileOperation.run(UploadFileOperation.java:448)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:187)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:640)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1415)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at android.os.Handler.dispatchMessage(Handler.java:106)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at android.os.Looper.loop(Looper.java:237)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at android.os.HandlerThread.run(HandlerThread.java:67)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation: Caused by: android.system.ErrnoException: isConnected failed: ETIMEDOUT (Connection timed out)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         at libcore.io.IoBridge.isConnected(IoBridge.java:274)
01-11 13:01:04.356 19026 10828 E ExistenceCheckRemoteOperation:         ... 30 more
```
found this stack trace, do you need more information ?

**Comment by mathieujobin** [comment]
also ...

```
01-11 13:00:20.809 19026 10828 D OwnCloudClient #0: REQUEST MOVE /next/remote.php/dav/uploads/username/a8d96f95f667976aaf6ccfc9cdcf0888/.file
01-11 13:00:21.320 19026 10828 E UploadFileOperation: Upload of /storage/emulated/0/DCIM/Camera/IMG_20220110_083559.jpg to /InstantUpload/Camera/IMG_20220110_083559.jpg: Operation finished with HTTP status code 403 (fail)
01-11 13:00:21.320 19026 10828 D UploadsStorageManager: updateDatabaseUploadResult uploadResult: RemoteOperationResult(mSuccess=false, mHttpCode=403, mHttpPhrase=Forbidden, mException=null, mCode=FORBIDDEN, message=null, getLogMessage=Operation finished with HTTP status code 403 (fail)) upload: com.owncloud.android.operations.UploadFileOperation@cc94360
01-11 13:00:21.322 19026 10828 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/IMG_20220110_083559.jpg with status:UPLOAD_FAILED and result:PRIVILEGES_ERROR (old:/storage/emulated/0/DCIM/Camera/IMG_20220110_083559.jpg status:UPLOAD_IN_PROGRESS result:-1)
01-11 13:00:21.322 19026 10828 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/IMG_20220110_083559.jpg with status=UPLOAD_FAILED
01-11 13:00:21.326 19026 10828 D UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/DCIM/Camera/IMG_20220110_083559.jpg
01-11 13:00:21.326 19026 10828 D UploadsStorageManager: notifyObserversNow
01-11 13:00:21.326 19026 10828 D FileUploader: NotifyUploadResult with resultCode: FORBIDDEN
01-11 13:00:21.331 19026 10828 D FileUploader: Stopping command after id 1
01-11 13:00:21.436 19026 10828 V UploadsStorageManager: Updating /storage/emulated/0/DCIM/Camera/IMG_20220110_075013.jpg with status:UPLOAD_IN_PROGRESS and result:UNKNOWN (old:/storage/emulated/0/DCIM/Camera/IMG_20220110_075013.jpg status:UPLOAD_IN_PROGRESS result:-1)
```

**Comment by tobiasKaminsky** [comment]
This sounds like a network issue… can you access the cloud via browser in the moment this happens?

**Comment by Aharper9917** [comment]
I had a similar issue where I couldn't upload files to a local external drive I setup in Nextcloud. My comment might be irrelevant to this issue, if so please disregard. However, I hope someone finds this useful. 

I noticed my nextcloud instance set up a new user 'www-data'. Later I checked the permissions for the directory I mounted for my local external drive and they were: 'drwxrwxr-x'. I did a quick ```chmod -R 777 <PATH_TO_DIR>``` to allow write privileges for all other users, and I was able to upload files to that folder. In my case I was okay with give all users r/w privileges.

**Comment by mathieujobin** [comment]
it is not a unix file permission issue. I have double check that... 
but recently, its happening much less.
maybe a recent software update improve things, I'll report back when it happens again

**Comment by skjnldsv** [comment]
I can also reproduce the issue.
All permissions are correct and checked multiple times (chown and chmod ran again just in case)
It seems to randomly misbehave.

Clicking restart in the android app works fine. Meaning it was indeed not a permission issue on the server side.

**Comment by psychedelicu** [comment]
Almost 2025 and I still have this issue. How can i fix it? This is happening only when my Android upload videos.
