### ISSUE TITLE
Parameter specified as non-null is null

### ISSUE THREAD

**Issue by h6s** [nextcloud/android#6614]
************ CAUSE OF ERROR ************

java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter value
	at com.owncloud.android.datamodel.ArbitraryDataSet.<init>(Unknown Source:12)
	at com.owncloud.android.datamodel.ArbitraryDataProvider.getArbitraryDataSet(ArbitraryDataProvider.java:207)
	at com.owncloud.android.datamodel.ArbitraryDataProvider.storeOrUpdateKeyValue(ArbitraryDataProvider.java:67)
	at com.owncloud.android.operations.RefreshFolderOperation.updateDirectEditing(RefreshFolderOperation.java:313)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:295)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:270)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:223)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130052
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Sony
Device: castor
Model: Xperia Z2 Tablet LTE
Id: QQ3A.200705.002
Product: SGP521

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 1712

**Comment by tobiasKaminsky** [comment]
Somehow your database seems to be missing an important info to change a value in OCCapability.
Is this also happening on a fresh account?

(I removed release candidate tag as this is not related to 3.13)
