### ISSUE TITLE
com.owncloud.android.ui.activity.FolderPickerActivity cannot be cast to com.owncloud.android.ui.activity.FileDisplayActivity

### ISSUE THREAD

**Issue by jpopovitch** [nextcloud/android#6616]
### Steps to reproduce
1. Create a new Auto Upload
2. Select a remote Folder

### Expected behaviour
- The Folder should become the selected folder

### Actual behaviour
- The App crashes

************ CAUSE OF ERROR ************

java.lang.ClassCastException: com.owncloud.android.ui.activity.FolderPickerActivity cannot be cast to com.owncloud.android.ui.activity.FileDisplayActivity
        at com.owncloud.android.ui.fragment.OCFileListFragment.resetHeaderScrollingState(OCFileListFragment.java:1867)
        at com.owncloud.android.ui.fragment.OCFileListFragment.onItemClicked(OCFileListFragment.java:906)
        at com.owncloud.android.ui.adapter.OCFileListAdapter.lambda$onBindViewHolder$1$OCFileListAdapter(OCFileListAdapter.java:379)
        at com.owncloud.android.ui.adapter.-$$Lambda$OCFileListAdapter$pouWgEOOHT1aDFHaHM0Ifm3xWtY.onClick(Unknown Source:4)
        at android.view.View.performClick(View.java:6274)
        at android.view.View$PerformClick.run(View.java:24859)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130052
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: lge
Device: lucye
Model: LG-H872
Id: OPR1.170623.032
Product: lucye_tmo_us

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: 183621644ce05

**Comment by AndyScherzinger** [comment]
Hi @jpopovitch and thank you for the report.

This issue will be fixed via #6632 and ship with 3.13.0 RC3
