### ISSUE TITLE
APP crashs on startup.

### ISSUE THREAD

**Issue by tacruc** [nextcloud/android#6618]
When I open the nextcloud APP it crashes with the following error. The last time I fixed it by resting the app completely, which is annozing due to SSO.

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to resume activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3822)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3854)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference
	at com.owncloud.android.datamodel.OCFile.getDecryptedRemotePath(OCFile.java:212)
	at com.owncloud.android.datamodel.OCFile.getDecryptedFileName(OCFile.java:388)
	at com.owncloud.android.datamodel.OCFile.getFileName(OCFile.java:379)
	at com.owncloud.android.datamodel.OCFile.isHidden(OCFile.java:537)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.filterHiddenFiles(OCFileListAdapter.java:1222)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:906)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1261)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1214)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1203)
	at com.owncloud.android.ui.activity.FileDisplayActivity.updateListOfFilesFragment(FileDisplayActivity.java:629)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onResume(FileDisplayActivity.java:1103)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
	at android.app.Activity.performResume(Activity.java:7300)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3814)
	... 11 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130051
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: a5y17lte
Model: SM-A520F
Product: a5y17ltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: af34c35071

**Comment by tacruc** [comment]
Duplicate #6574

**Comment by AndyScherzinger** [comment]
#6557 should fix this, please update to RC2
