### ISSUE TITLE
App crashes when trying to move files to different folder

### ISSUE THREAD

**Issue by thimovandenberg** [nextcloud/android#6638]
### Steps to reproduce
1. Select files
2. Click move
3. Click on folder in the folder picking overview

### Expected behaviour
- The selected folder should be displayed

### Actual behaviour
- The app crashes

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10

Device model: OnePlus 6

Stock or customized system: Stock

Nextcloud app version: 3.13.0 RC2

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.ClassCastException: com.owncloud.android.ui.activity.FolderPickerActivity cannot be cast to com.owncloud.android.ui.activity.FileDisplayActivity
	at com.owncloud.android.ui.fragment.OCFileListFragment.resetHeaderScrollingState(OCFileListFragment.java:1867)
	at com.owncloud.android.ui.fragment.OCFileListFragment.onItemClicked(OCFileListFragment.java:906)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.lambda$onBindViewHolder$1$OCFileListAdapter(OCFileListAdapter.java:379)
	at com.owncloud.android.ui.adapter.-$$Lambda$OCFileListAdapter$pouWgEOOHT1aDFHaHM0Ifm3xWtY.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7201)
	at android.view.View.performClickInternal(View.java:7170)
	at android.view.View.access$3500(View.java:806)
	at android.view.View$PerformClick.run(View.java:27562)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7643)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130052
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus6
Model: ONEPLUS A6003
Id: QKQ1.190716.003
Product: OnePlus6

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2003192339

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Hi @thimovandenberg 
this has been fixed with the RC3 (some hours ago), so it should arrive on your device any minute :)
