### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by walymar** [nextcloud/android#6644]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.swiperefreshlayout.widget.SwipeRefreshLayout.setRefreshing(boolean)' on a null object reference
	at com.owncloud.android.ui.activities.ActivitiesActivity.lambda$setProgressIndicatorState$1$ActivitiesActivity(ActivitiesActivity.java:314)
	at com.owncloud.android.ui.activities.-$$Lambda$ActivitiesActivity$uvt0YXeTiKYN88DkMHLujKlZ8Ng.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWPOT-H
Model: POT-LX3
Id: HUAWEIPOT-L23
Product: POT-LX3

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.0.0.228C605

**Comment by walymar** [comment]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.swiperefreshlayout.widget.SwipeRefreshLayout.setRefreshing(boolean)' on a null object reference
	at com.owncloud.android.ui.activities.ActivitiesActivity.lambda$setProgressIndicatorState$1$ActivitiesActivity(ActivitiesActivity.java:314)
	at com.owncloud.android.ui.activities.-$$Lambda$ActivitiesActivity$uvt0YXeTiKYN88DkMHLujKlZ8Ng.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWPOT-H
Model: POT-LX3
Id: HUAWEIPOT-L23
Product: POT-LX3

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.0.0.228C605

**Comment by tobiasKaminsky** [comment]
@ezaquarii as you rewrote ActivitiesActivity, does this still happen?
I suspect that this is due to long running async task, when the user meanwhile navigates somewhere else.

**Comment by tobiasKaminsky** [comment]
I think we fixed this with 3.14.
Please re-open if not.
