### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by tetarwal** [nextcloud/android#6649]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED flg=0x10 pkg=com.nextcloud.client (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver@d48313b
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1401)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=29303, uid=1210202 requires android.permission.BROADCAST_STICKY
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.app.IActivityManager$Stub$Proxy.unbroadcastIntent(IActivityManager.java:3895)
	at android.app.ContextImpl.removeStickyBroadcast(ContextImpl.java:1346)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
	at com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver.onReceive(FileDisplayActivity.java:1410)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1391)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.unbroadcastIntent(ActivityManagerService.java:22566)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:183)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3353)
	at android.os.Binder.execTransact(Binder.java:731)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: asus
Device: ASUS_X00T_2
Model: ASUS_X00TD
Id: PKQ1
Product: WW_X00TD

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 16.2017.2007.084-20200706

**Comment by AndyScherzinger** [comment]
Hi @tetarwal,

did you install the app in a secondary Android profile on your device or are you using "Android for Work".

If so, please also install the app in the main profile (which should solve your issue).

**Comment by tetarwal** [comment]
Yes, I'm using this in my work profile.

**Comment by AndyScherzinger** [comment]
@tetarwal unfortunately we don't support Android for Work at the moment, does installing it on the main profile help resolve this issue for you?

**Comment by tetarwal** [comment]
Yes, it's working totally fine in personal space. 
I'm newbie at android development, can you quickly tell me what causing it to crash in work profile.

**Comment by AndyScherzinger** [comment]
> Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=29303, uid=1210202 requires android.permission.BROADCAST_STICKY

^This. Sticky broadcast have been deprecated with newer Android version while this app still relies on them. There is no issue/crash in any Android version except when one is using the app in a multiple-profile scenario like Android4Work or secondary profiles where newer Android versions will prevent this and just crash :(

**Comment by AndyScherzinger** [comment]
Duplicate of #6654
