### ISSUE TITLE
Replace sticky broadcasts with and event-mechanism or else

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#6654]
**Workaround**
Installing app into the main profile also (just installing is enough)

**Issue description**
As reported in several tickets the app crashes with a security exception in case the app is used in a non-primary profile which might be a secondary profile or a Android 4 Work profile. This is due to the usage of (deprecated) sticky broadcasts, see for example #4205

> Google 
Sticky broadcasts should not be used. They provide no security (anyone can access them), no protection (anyone can modify them), and many other problems. The recommended pattern is to use a non-sticky broadcast to report that something has changed, with another mechanism for apps to retrieve the current value whenever desired.

It seems the solution is to move to events e.g. via an Eventbus, see https://stackoverflow.com/a/46836794 with GreenRobot EventBus being part of our application already _OR_ see  #6048 by @ezaquarii to move to complete rewrites for these areas of the code base.

What do you think @tobiasKaminsky @ezaquarii ? Since the sticky broadcasts have been deprecated with API21 we will liekly get into more trouble in the future while I can't say if @ezaquarii's solution can be applied in all situations where we use sticky*.

Closing #4205 in favor of this issue that rather discusses the solution and can be used as a central issue.

**Reports**
#4205 #4229 #4476 #4553 #4565 #4573 #4615 #4627 #4661 #4896 #4931 
#5059 #5131 #5309 #5366 #5514 #5709 #5831 #5907 
#6545 #6649

**Comment by AndyScherzinger** [comment]
Reported Stack Traces

**Nearly all reports**
<details>
  <summary>RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED</summary>
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED flg=0x10 pkg=com.nextcloud.client (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver@ad71f3e
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1410)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6859)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=8814, uid=1010171 requires android.permission.BROADCAST_STICKY
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.app.IActivityManager$Stub$Proxy.unbroadcastIntent(IActivityManager.java:3904)
	at android.app.ContextImpl.removeStickyBroadcast(ContextImpl.java:1346)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
	at com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver.onReceive(FileDisplayActivity.java:1411)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1400)
	... 8 more
</details>

1 Report
<details>
  <summary>FileUploaderUPLOAD_FINISH</summary>
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.files.services.FileUploaderUPLOAD_FINISH flg=0x10 pkg=com.nextcloud.client (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$UploadFinishReceiver@2421bcc
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1412)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:280)
	at android.app.ActivityThread.main(ActivityThread.java:6706)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=10982, uid=1010298 requires android.permission.BROADCAST_STICKY
	at android.os.Parcel.createException(Parcel.java:1969)
	at android.os.Parcel.readException(Parcel.java:1935)
	at android.os.Parcel.readException(Parcel.java:1885)
	at android.app.IActivityManager$Stub$Proxy.unbroadcastIntent(IActivityManager.java:3903)
	at android.app.ContextImpl.removeStickyBroadcast(ContextImpl.java:1346)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
	at com.owncloud.android.ui.activity.FileDisplayActivity$UploadFinishReceiver.onReceive(FileDisplayActivity.java:1575)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1397)
	... 8 more
</details>

**Comment by ezaquarii** [comment]
@tobiasKaminsky @AndyScherzinger 

Indeed, I plan to completely re-work the transfer mechanism. So much in fact that it will provide completely new semantics. Once this is done, we'll need to rewrite the syncer and port UI code. It is a big task.

For the immediate fix, porting broadcasts to `EventBus` sounds like a sensible, low cost solution.

**Comment by tobiasKaminsky** [comment]
Is there a reason why we cannot just simply use internal/normal broadcasts?

**Comment by AndyScherzinger** [comment]
I am not too familiar with broadcasts, so I can't tell. :/

**Comment by tobiasKaminsky** [comment]
Seems I did all the work some time ago already…🙈
-> #6748
