### ISSUE TITLE
Android client crashes when there is connection to the internet

### ISSUE THREAD

**Issue by dshurbin** [nextcloud/android#6664]
### Steps to reproduce
1. Approx 17k+ photos left in synchronizing WhatsApp/images on the device; 6GB+ already synchronized; all other directories are already done; every synchronizing directory set to sync *ONLY* when connected via WiFi.
2. Having WiFi connected or maybe bile internet, whatever connection, the problem occurs; same with all syncronizing directories set to "disabled" (blue cloud turned to gray)
3. Switching to flight mode or disabling any connection allows to run the app

### Expected behaviour
-  data syncronization, running app

### Actual behaviour
- program interface won't show up with any active internet connection, regardless syncronization settings

### Environment data
Android version:

Device model: Xiaomi Redmi Note 8 Pro

Stock or customized system:
Stock, MIUI global 11.0.3 stable; Android 10

Nextcloud app version:
Can't see right now, sat up 05.08.2020 from PlayMarket
Nextcloud server version:
Ubuntu 18.04 LTS, Apache2, NextCloud 19.0.1
Reverse proxy: -

#### Web server error log
No errors
Insert your webserver log here
Nothing special

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here

************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.SecurityException: Caller no longer running, last stopped +14s510ms because: timed out while starting
	at android.os.Parcel.createException(Parcel.java:2074)
	at android.os.Parcel.readException(Parcel.java:2042)
	at android.os.Parcel.readException(Parcel.java:1990)
	at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:292)
	at android.app.job.JobParameters.dequeueWork(JobParameters.java:248)
	at androidx.core.app.JobIntentService$JobServiceEngineImpl.dequeueWork(JobIntentService.java:315)
	at androidx.core.app.JobIntentService.dequeueWork(JobIntentService.java:640)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:390)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobServiceContext.assertCallerLocked(JobServiceContext.java:497)
	at com.android.server.job.JobServiceContext.doDequeueWork(JobServiceContext.java:375)
	at com.android.server.job.JobServiceContext$JobCallback.dequeueWork(JobServiceContext.java:160)
	at android.app.job.IJobCallback$Stub.onTransact(IJobCallback.java:169)
	at android.os.Binder.execTransactInternal(Binder.java:1021)


************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Redmi
Device: begonia
Model: Redmi Note 8 Pro
Id: QP1A.190711.020
Product: begonia_ru

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V11.0.3.0.QGGRUXM
*NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
I fear that this is a problem due to too many outstanding uploads…
Can you try to reduce them?
