### ISSUE TITLE
Nextcloud app crashes when opening a large folder

### ISSUE THREAD

**Issue by 1Yanik3** [nextcloud/android#6677]
### Steps to reproduce
1. Open folder with many files (in my case pictures) 

### Expected behaviour
- App lists folder content

### Actual behaviour
- App crashes (only crashes in app, not web) 

### Environment data

Device model: OnePlus 7 Pro

Stock or customized system: stock

Nextcloud app version: 3.12.1

Nextcloud server version: latest docker

Reverse proxy: Nginx

#### Nextcloud log (data/nextcloud.log)

************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=3662, totalRows=1043
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:942)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:161)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:131)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:249)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:281)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:190)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProvider$Transport.delete(ContentProvider.java:438)
	at android.content.ContentResolver.delete(ContentResolver.java:1989)
	at com.owncloud.android.datamodel.FileDataStorageManager.removeFolderInDb(FileDataStorageManager.java:589)
	at com.owncloud.android.datamodel.FileDataStorageManager.removeFolder(FileDataStorageManager.java:564)
	at com.owncloud.android.operations.RefreshFolderOperation.removeLocalFolder(RefreshFolderOperation.java:387)
	at com.owncloud.android.operations.RefreshFolderOperation.checkForChanges(RefreshFolderOperation.java:348)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:224)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:357)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus7Pro
Model: GM1913
Id: QKQ1.190716.003
Product: OnePlus7Pro_EEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2005132200

**Comment by tobiasKaminsky** [comment]
How many files do you have in it? So that I know a rough number to test it with…

**Comment by 1Yanik3** [comment]
About 400

**Comment by bedartha** [comment]
I have a similar issue with a large folder of PDF files which currently has ca. 120 files. The app does not crash but it does not proceed beyond the "Loading..." message. I can go to another part of the app without issues (I.e. app is not frozen) and dismiss the "Loading..." dialog. It is however not possible to view the contents of the folder.

This does not happen with the Nextcloud web app for Firfox on Android.

**Comment by tobiasKaminsky** [comment]
> I have a similar issue with a large folder of PDF files which currently has ca. 120 files. The app does not crash but it does not proceed beyond the "Loading..." message. I can go to another part of the app without issues (I.e. app is not frozen) and dismiss the "Loading..." dialog. It is however not possible to view the contents of the folder.
> 
> This does not happen with the Nextcloud web app for Firfox on Android.

This then seems to be a difference problem, please open up a new issue for it.

**Comment by bedartha** [comment]
> > I have a similar issue with a large folder of PDF files which currently has ca. 120 files. The app does not crash but it does not proceed beyond the "Loading..." message. I can go to another part of the app without issues (I.e. app is not frozen) and dismiss the "Loading..." dialog. It is however not possible to view the contents of the folder.
> > This does not happen with the Nextcloud web app for Firfox on Android.
> 
> This then seems to be a difference problem, please open up a new issue for it.

Done:
https://github.com/nextcloud/android/issues/6988#issue-706146182
