### ISSUE TITLE
Seach for jpg in a folder

### ISSUE THREAD

**Issue by weinic** [nextcloud/android#6690]
I seached for jpg in a Ordner with 85 jpg and 85 dng Picture Files on my SMB Share.
My SMB Share is a Home Server with 30-40 thousand jpg Files. 

************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130054
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus5
Model: ONEPLUS A5000
Id: QKQ1.191014.012
Product: OnePlus5

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2006012143

**Comment by tobiasKaminsky** [comment]
Search is not folder specific but searches in whole your cloud.


> OutOfMemoryError

Then means that you might get too many results back…? :fearful: 
Can you try it with a more specific search query to see if the search per se is working?

**Comment by weinic** [comment]
Hello, 
the search works and returns results.  There are probably too many results.  
What I wanted to achieve, however, is that only the jpg files are displayed in this folder.  Unfortunately, it is not possible to sort the files by file type.  
That would be a suggestion to be able to sort files by file type.  This also makes it easier to select certain files for a download.
