### ISSUE TITLE
Apkmody.io djay 2 crashes android

### ISSUE THREAD

**Issue by dolphin-cat** [nextcloud/android#6709]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ComponentName android.content.Intent.getComponent()' on a null object reference
	at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1566)
	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1736)
	at android.app.ContextImpl.bindService(ContextImpl.java:1660)
	at android.content.ContextWrapper.bindService(ContextWrapper.java:715)
	at com.google.android.vending.licensing.LicenseChecker.checkAccess(Unknown Source:80)
	at com.google.android.vending.expansion.downloader.impl.DownloaderService$LVLRunnable.run(Unknown Source:71)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:221)
	at android.app.ActivityThread.main(ActivityThread.java:7520)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by dolphin-cat** [comment]
What can i do to fix it

**Comment by tobiasKaminsky** [comment]
Can you give us more details how and when the crash occurred?

**Comment by dolphin-cat** [comment]
i downloaded a cracked version of djay 2 on my phone from apkmody (link: https://apkmody.io/apps/djay-2-apk) and when i opened the app it crashed and closed with the above error massage

**Comment by dolphin-cat** [comment]
to download the app visit https://apkmody.io/apps/djay-2-apk/download/0

**Comment by tobiasKaminsky** [comment]
I will not download any cracked version nor help / test anything related to that.
