### ISSUE TITLE
error deleting an account

### ISSUE THREAD

**Issue by poggenpower** [nextcloud/android#6710]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'long com.owncloud.android.datamodel.OCFile.getParentId()' on a null object reference
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:410)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:369)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:228)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:357)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: d1
Model: SM-N970F
Id: QP1A.190711.020
Product: d1eea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: N970FXXS6CTGA

**Comment by tobiasKaminsky** [comment]
Is this folder in any way special?
