### ISSUE TITLE
crash when selecting filed

### ISSUE THREAD

**Issue by JulianLor** [nextcloud/android#6720]
### Steps to reproduce
1. create a folder with more than 2500 pictures on a lineage whyred phone
2. select to upload the pictures

### Expected behaviour
- the screen goes black (probably because the reading oft the folder takes too long)

### Actual behaviour
- after a while a crash report is shown

Device model: ************ CAUSE OF ERROR ************

java.util.concurrent.TimeoutException: com.android.internal.os.BinderInternal$GcWatcher.finalize() timed out after 10 seconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:422)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:188)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:209)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:232)
	at java.lang.Daemons$Daemon.run(Daemons.java:103)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20200809
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: whyred
Model: Redmi Note 5 Pro
Id: OPM6.171019.030.K1
Product: whyred

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: fc5e494154

**Comment by tobiasKaminsky** [comment]
Better upload it in chunks, but yes this is a valid bug…
