### ISSUE TITLE
application crashes if you try to set a password to the file share

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#6749]
@tobiasKaminsky 

application crashes if you try to set a password to the file share, set password then click ok on app 3.13.0 stable and app crash

![Screenshot_20200819-113538_Nextcloud](https://user-images.githubusercontent.com/35575744/90618663-9b3c5d00-e210-11ea-91a9-e9b7ba6124b5.jpg)

**Comment by Lablnet** [comment]
Same issue

Debug info

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'long com.owncloud.android.lib.resources.shares.OCShare.getId()' on a null object reference
	at com.owncloud.android.ui.helpers.FileOperationsHelper.setPasswordToPublicShare(FileOperationsHelper.java:592)
	at com.owncloud.android.ui.dialog.SharePasswordDialogFragment.setPassword(SharePasswordDialogFragment.java:198)
	at com.owncloud.android.ui.dialog.SharePasswordDialogFragment.onClick(SharePasswordDialogFragment.java:187)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6758)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:912)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Infinix
Device: Infinix-X627STU
Model: Infinix X627
Id: PPR1.180610.011
Product: H624

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: STXYZAa-200617V315

![Screenshot_20200819-163338](https://user-images.githubusercontent.com/27757785/90630378-5c230180-e23a-11ea-8e33-7480a95cee51.png)
