### ISSUE TITLE
Crash after deleting folder on server

### ISSUE THREAD

**Issue by ThyMYthOS** [nextcloud/android#6752]
```
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Couldn't read row 1257, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:511)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:179)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:299)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:672)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:321)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:465)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:1578)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:435)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:490)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:372)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:231)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130054
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: motorola
Device: albus
Model: Moto Z2 Play
Id: OPSS27.76-12-25-23
Product: albus

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: 22
```

**Comment by tobiasKaminsky** [comment]
What are the steps to reproduce?

**Comment by ThyMYthOS** [comment]
Good question. The only thing I can remember for sure is that I deleted a large folder via the web frontend and from that point on the Android client was not able to sync anymore.
It still showed the folder in the overview and the loading spinner did not stop. The App did not respond to any user actions.
