### ISSUE TITLE
Android app crashes 

### ISSUE THREAD

**Issue by lockeftw** [nextcloud/android#6755]
### Steps to reproduce
1. Open nextcloud app in Android 10
2. Crawling through files
3. After a few seconds a crash report appears 

### Expected behaviour
- Tell us what should happen
Fourther more crawling
### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:3.13.0

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```

```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$AsyncFutureTask.done(AsyncTask.java:429)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
Caused by: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8913)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1557)
	at android.view.View.requestLayout(View.java:24690)
	at android.view.View.requestLayout(View.java:24690)
	at android.view.View.requestLayout(View.java:24690)
	at android.view.View.requestLayout(View.java:24690)
	at android.view.View.requestLayout(View.java:24690)
	at android.view.View.requestLayout(View.java:24690)
	at androidx.drawerlayout.widget.DrawerLayout.requestLayout(DrawerLayout.java:1303)
	at android.view.View.requestLayout(View.java:24690)
	at android.view.View.requestLayout(View.java:24690)
	at android.view.View.requestLayout(View.java:24690)
	at android.view.View.requestLayout(View.java:24690)
	at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:380)
	at android.view.View.requestLayout(View.java:24690)
	at android.view.View.requestLayout(View.java:24690)
	at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:4412)
	at android.view.View.requestLayout(View.java:24690)
	at android.view.View.requestLayout(View.java:24690)
	at androidx.constraintlayout.widget.ConstraintLayout.requestLayout(ConstraintLayout.java:3172)
	at android.view.View.requestLayout(View.java:24690)
	at android.view.View.requestLayout(View.java:24690)
	at android.view.View.setFlags(View.java:15338)
	at android.view.View.setVisibility(View.java:10932)
	at android.widget.ImageView.setVisibility(ImageView.java:1697)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.stopShimmer(OCFileListAdapter.java:787)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.access$600(OCFileListAdapter.java:109)
	at com.owncloud.android.ui.adapter.OCFileListAdapter$2.onError(OCFileListAdapter.java:711)
	at com.owncloud.android.datamodel.ThumbnailsCacheManager$ThumbnailGenerationTask.doInBackground(ThumbnailsCacheManager.java:524)
	at com.owncloud.android.datamodel.ThumbnailsCacheManager$ThumbnailGenerationTask.doInBackground(ThumbnailsCacheManager.java:423)
	at android.os.AsyncTask$3.call(AsyncTask.java:389)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWVOG
Model: VOG-L29
Id: HUAWEIVOG-L29
Product: VOG-L29EEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.1.0.140C431

**Comment by tobiasKaminsky** [comment]
@Shagequi this seems to be caused by the shimmer effect.
Do you have an idea?

**Comment by Shagequi** [comment]
Hi Tobias, 
Not really, I didn't personnally implemented the Shimmer, @sirambd maybe ?

**Comment by tobiasKaminsky** [comment]
> And I think the favicon (the small picture left beside its name) can't load for some reason...

Thanks for this important hint.
I looked again into stack trace and it indeeds come from:
OCFileListAdapter$2.onError

Now looking into the code, on both onSuccess/onError the same function stopShimmer() is executed.
But the difference is that onSuccess is called in ThumbnailsCacheManager.onPostExecute() which is run on UI thread.
onError in opposite is run in ThumbnailsCacheManager.doInBackground() and thus crashes.

I will fix it.
