### ISSUE TITLE
android app down

### ISSUE THREAD

**Issue by clawfinger30** [nextcloud/android#6756]
************ CAUSE OF ERROR ************

java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at com.owncloud.android.ui.adapter.OCFileListAdapter.showFederatedShareAvatar(OCFileListAdapter.java:597)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.onBindViewHolder(OCFileListAdapter.java:471)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
	at android.view.View.layout(View.java:21964)
	at android.view.ViewGroup.layout(ViewGroup.java:6317)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
	at android.view.View.layout(View.java:21964)
	at android.view.ViewGroup.layout(ViewGroup.java:6317)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:21964)
	at android.view.ViewGroup.layout(ViewGroup.java:6317)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:21964)
	at android.view.ViewGroup.layout(ViewGroup.java:6317)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1818)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1584)
	at android.view.View.layout(View.java:21964)
	at android.view.ViewGroup.layout(ViewGroup.java:6317)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1892)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:21964)
	at android.view.ViewGroup.layout(ViewGroup.java:6317)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:21964)
	at android.view.ViewGroup.layout(ViewGroup.java:6317)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:21964)
	at android.view.ViewGroup.layout(ViewGroup.java:6317)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:21964)
	at android.view.ViewGroup.layout(ViewGroup.java:6317)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:21964)
	at android.view.ViewGroup.layout(ViewGroup.java:6317)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:21964)
	at android.view.ViewGroup.layout(ViewGroup.java:6317)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:802)
	at android.view.View.layout(View.java:21964)
	at android.view.ViewGroup.layout(ViewGroup.java:6317)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3161)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2671)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1799)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7770)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:789)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7520)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Redmi
Device: curtana
Model: Redmi Note 9S
Id: QKQ1.191215.002
Product: curtana_global

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V11.0.9.0.QJWMIXM

### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
We are assuming that any userID with "@" in it might be a federated share and thus trying to get the federated share avatar.
Do you know which userId is affected? I fear you have to find this out manually. Note on which folder listing it is crashing, go to web ui and search for all shared folder/files in it and give us the userId please (you can anonymize them, but please do not change syntax).

**Comment by clawfinger30** [comment]
Thank you
The repair is complete.

2020年8月20日(木) 16:59 Tobias Kaminsky <notifications@github.com>:

**Comment by tobiasKaminsky** [comment]
I assume that means that we can close the issue?
