### ISSUE TITLE
App crashes after loading file list

### ISSUE THREAD

**Issue by sanderdegrote** [nextcloud/android#6766]
### Steps to reproduce
1. Have an existing account already added to the app, in my case it's been there for several updates
2. Add a new account
3. Nextcloud now crashes when it's able to connect to the newly added account's serverr.

### Environment data
Nextcloud server versions: 19.0.1

Android stack trace:
************ CAUSE OF ERROR ************

java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter value
	at com.owncloud.android.datamodel.ArbitraryDataSet.<init>(Unknown Source:12)
	at com.owncloud.android.datamodel.ArbitraryDataProvider.getArbitraryDataSet(ArbitraryDataProvider.java:207)
	at com.owncloud.android.datamodel.ArbitraryDataProvider.storeOrUpdateKeyValue(ArbitraryDataProvider.java:67)
	at com.owncloud.android.operations.RefreshFolderOperation.updateDirectEditing(RefreshFolderOperation.java:313)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:295)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:270)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:223)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a71
Model: SM-A715F
Id: QP1A.190711.020
Product: a71naeea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: A715FXXU2ATG1

Hope this helps the project, if there are any more logs needed feel free to ask.

**Comment by tobiasKaminsky** [comment]
Will be fixed via #6774
