### ISSUE TITLE
create password for a link throws a NullPointerException

### ISSUE THREAD

**Issue by rschlag** [nextcloud/android#6777]
### Steps to reproduce
1. open the nextcloud app on an android device (samsung)
2. create a share link for a folder or file
3. set a password for this shared link
4. no password has been set

### Expected behaviour
- a password should be set

### Actual behaviour
- a NullPointerException with a stack trace is displayed

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10

Device model: Samsung S9 (SM-G960F) / also in Samsung S8

Stock or customized system:

Nextcloud app version: 3.13.0

Nextcloud server version: 19.0.1.1

Reverse proxy:

#### mobile phone message
```

********** CAUSE OF ERROR **********

java.lang.NullPointerException: Attempt to invoke virtual method 'long com.owncloud.android.lib.resources.shares.OCShare.getId()' on a null object reference
at com.owncloud.android.ui.helpers.FileOperationsHelper.setPasswordToPublicShare(FileOperationsHelper.java:592)
at com.owncloud.android.ui.dialog.SharePasswordDialogFragment.setPassword(SharePasswordDialogFragment.java:198)
at com.owncloud.android.ui.dialog.SharePasswordDialogFragment.onClick(SharePasswordDialogFragment.java:175)
at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8125)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

********** APP INFORMATION **********
ID: com.nextcloud.client
Version: 30130090
Build flavor: gplay

********** DEVICE INFORMATION **********
Brand: samsung
Device: starlte
Model: SM-G960F
Id: QP1A.190711.020
Product: starltexx

********** FIRMWARE **********
SDK: 29
Release: 10
Incremental: G960FXXUAETG3
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
This should be fixed via #6662
