### ISSUE TITLE
App crash on startup

### ISSUE THREAD

**Issue by daKrueml** [nextcloud/android#6779]
### Steps to reproduce
1. Start app
2. Wait 5 seconds
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Couldn't read row 1164, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:542)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:77)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:179)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProviderOperation.applyInternal(ContentProviderOperation.java:342)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:314)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:672)
	at android.content.ContentProvider.applyBatch(ContentProvider.java:2179)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:398)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:532)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:520)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:1915)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:435)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:490)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:372)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:231)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus7Pro
Model: GM1913
Id: QKQ1.190716.003
Product: OnePlus7Pro_EEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2007240000

**Comment by tobiasKaminsky** [comment]
Do you have any very large folders in it? Folders with many many files?
