### ISSUE TITLE
Crash when deleting file

### ISSUE THREAD

**Issue by LilimVipera** [nextcloud/android#6803]
### Steps to reproduce
1. Try to delete inside group folder

### Expected behaviour
- File should have been deleted for everyone

### Actual behaviour
************ CAUSE OF ERROR ************

java.lang.OutOfMemoryError: Failed to allocate a 279221160 byte allocation with 25165824 free bytes and 94MB until OOM, target footprint 194591680, growth limit 268435456
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
	at java.io.BufferedInputStream.skip(BufferedInputStream.java:382)
	at java.io.DataInputStream.skipBytes(DataInputStream.java:223)
	at androidx.exifinterface.media.ExifInterface$ByteOrderedDataInputStream.skipBytes(ExifInterface.java:7654)
	at androidx.exifinterface.media.ExifInterface.getPngAttributes(ExifInterface.java:6077)
	at androidx.exifinterface.media.ExifInterface.loadAttributes(ExifInterface.java:4568)
	at androidx.exifinterface.media.ExifInterface.initForFilename(ExifInterface.java:5197)
	at androidx.exifinterface.media.ExifInterface.<init>(ExifInterface.java:3926)
	at com.owncloud.android.utils.BitmapUtils.rotateImage(BitmapUtils.java:155)
	at com.owncloud.android.datamodel.ThumbnailsCacheManager.addThumbnailToCache(ThumbnailsCacheManager.java:194)
	at com.owncloud.android.datamodel.ThumbnailsCacheManager.generateResizedImage(ThumbnailsCacheManager.java:1235)
	at com.owncloud.android.operations.RemoveFileOperation.run(RemoveFileOperation.java:97)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:181)
	at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:85)
	at com.owncloud.android.services.OperationsService$ServiceHandler.nextOperation(OperationsService.java:460)
	at com.owncloud.android.services.OperationsService$ServiceHandler.handleMessage(OperationsService.java:417)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.os.HandlerThread.run(HandlerThread.java:67)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: d2s
Model: SM-N975F
Id: QP1A.190711.020
Product: d2seea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: N975FXXS6CTGA

### Can you reproduce this problem on Nextcloud.com?
Not at the moment. Just wanted to share like the app recommended

### Environment data

Look above

#### Web server error log
```
?
```

#### Nextcloud log (data/nextcloud.log)
```
Couldn't find anywhere
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
What file do you try to delete?
It  seems like a very large(?) image?
