### ISSUE TITLE
Cannot open jpg

### ISSUE THREAD

**Issue by Dolf19** [nextcloud/android#6824]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here

************ CAUSE OF ERROR ************

java.lang.IllegalArgumentException: Scale must be within the range of minScale and maxScale
	at com.github.chrisbanes.photoview.PhotoViewAttacher.setScale(PhotoViewAttacher.java:456)
	at com.github.chrisbanes.photoview.PhotoViewAttacher.setScale(PhotoViewAttacher.java:446)
	at com.github.chrisbanes.photoview.PhotoViewAttacher.setScale(PhotoViewAttacher.java:442)
	at com.github.chrisbanes.photoview.PhotoView.setScale(PhotoView.java:230)
	at com.owncloud.android.ui.preview.PreviewImageFragment.onActivityCreated(PreviewImageFragment.java:230)
	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2718)
	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1200)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1830)
	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:303)
	at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:270)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
	at androidx.viewpager.widget.ViewPager$3.run(ViewPager.java:273)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
	at android.view.Choreographer.doCallbacks(Choreographer.java:875)
	at android.view.Choreographer.doFrame(Choreographer.java:772)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8347)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWHMA
Model: HMA-L29
Id: HUAWEIHMA-L29
Product: HMA-L29

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.1.0.278C432


```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Do you know the steps to reproduce?

**Comment by Dolf19** [comment]
Hi,No I don't know the steps to reproduce it.Can it be that the pictures are encrypted?I deleted these apps...? Kind regards RalphOp 27 aug. 2020 07:24 schreef Tobias Kaminsky <notifications@github.com>:
Do you know the steps to reproduce?

**Comment by tobiasKaminsky** [comment]
> Scale must be within the range of minScale and maxScale

It seems that you zoomed into one image and now the system tries to reset this zoom, but it is out of bounds…
No idea how this is possible…

**Comment by Dolf19** [comment]
Strange...Is there a solution? Op 28 aug. 2020 07:45 schreef Tobias Kaminsky <notifications@github.com>:



Scale must be within the range of minScale and maxScale



It seems that you zoomed into one image and now the system tries to reset this zoom, but it is out of bounds…

No idea how this is possible…

**Comment by tobiasKaminsky** [comment]
No idea how to trigger this, but I created a fix.

**Comment by Dolf19** [comment]
You are great!!

Thanks a lot

________________________________
Van: Tobias Kaminsky <notifications@github.com>
Verzonden: maandag 31 augustus 2020 11:07
Aan: nextcloud/android <android@noreply.github.com>
CC: Dolf19 <Ralphbroux79@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [nextcloud/android] Cannot open jpg (#6824)


No idea how to trigger this, but I created a fix.
