### ISSUE TITLE
Reproducible NoHttpResponseException when making many requests

### ISSUE THREAD

**Issue by grote** [nextcloud/android#6830]
When hammering Nextcloud hard with requests (programmatically via DocumentsProvider) I reliably get a NoHttpResponseException which makes the request fail.

The log shows every few seconds:

```ruby
D/AdvancedSslSocketFactory: Creating SSL Socket with remote test.de:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@356164d
D/AdvancedSslSocketFactory:  ... with connection timeout 50000 and socket timeout 60000
```

Short before the failure it shows:

```ruby
D/AdvancedSslSocketFactory: Creating SSL Socket with remote test.de:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@612b1f
D/AdvancedSslSocketFactory:  ... with connection timeout 0 and socket timeout 0
```

Note that suddenly the timeouts are set to `0` which is strange.

Then eventually, the exception is thrown (which gets rethrown as a FileNotFoundException):

```ruby
D/OwnCloudClient #0: REQUEST PUT /remote.php/webdav/.SeedVaultAndroidBackup/1598533762174/kv/%40pm%40/bmV0LnRhbGVyLmNhc2hpZXI
E/DocumentsStorageProvider: RemoteOperationResult(mSuccess=false, mHttpCode=-1, mHttpPhrase=null, mException=org.apache.commons.httpclient.NoHttpResponseException: The server test.de failed to respond, mCode=UNKNOWN_ERROR, getLogMessage=Unrecovered transport exception)
E/DatabaseUtils: Writing exception to parcel
    android.os.ParcelableException: java.io.FileNotFoundException: Failed to upload document with path /.SeedVaultAndroidBackup/1598533762174/kv/@pm@/bmV0LnRhbGVyLmNhc2hpZXI
        at android.provider.DocumentsProvider.call(DocumentsProvider.java:1069)
        at android.content.ContentProvider.call(ContentProvider.java:2152)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:477)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:277)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
     Caused by: java.io.FileNotFoundException: Failed to upload document with path /.SeedVaultAndroidBackup/1598533762174/kv/@pm@/bmV0LnRhbGVyLmNhc2hpZXI
        at com.owncloud.android.providers.DocumentsStorageProvider.createFile(DocumentsStorageProvider.java:547)
        at com.owncloud.android.providers.DocumentsStorageProvider.createDocument(DocumentsStorageProvider.java:460)
        at android.provider.DocumentsProvider.callUnchecked(DocumentsProvider.java:1121)
        at android.provider.DocumentsProvider.call(DocumentsProvider.java:1067)
        at android.content.ContentProvider.call(ContentProvider.java:2152) 
```

Potentially related: #5940 as it has the same exception in the logs.
Further reading:
* https://williamsbdev.com/posts/no-http-response-exceptions/
* https://stackoverflow.com/a/10600762/4856311

**Comment by tobiasKaminsky** [comment]
> Note that suddenly the timeouts are set to `0` which is strange.

As mentioned yesterday "0" means infinite timeout.
Indeed it is strange that it not uses our default, but this should not be the cause.

Can you see anything related in nextcloud.log on server?

**Comment by grote** [comment]
I managed to reproduce the issue with a stress instrumentation test (pushed to [`grote/6830-no-http-response-exception`](https://github.com/grote/nextcloud-android/tree/grote/6830-no-http-response-exception)).

My server shows nothing in the two error logs (nextcloud and apache) and the failing request does not get logged into the Apache access log indicating that it never even arrives at the server, because the HttpClient is trying to use a stale socket.

Added debug logs have shown that at most two connections are in the connection pool at the same time.

**Comment by tobiasKaminsky** [comment]
> Added debug logs have shown that at most two connections are in the connection pool at the same time.

In MultiThreadedHttpConnectionManager it checks if there are free connections left, if yes it reuses them.
Maybe there is no need to have more than those 2 connections, especially when doing debug, where are operations are done one after the other with long delay.
