### ISSUE TITLE
Nextcloud mobile app crash

### ISSUE THREAD

**Issue by thabrez123** [nextcloud/android#6839]
************ CAUSE OF ERROR ************

java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter value
	at com.owncloud.android.datamodel.ArbitraryDataSet.<init>(Unknown Source:12)
	at com.owncloud.android.datamodel.ArbitraryDataProvider.getArbitraryDataSet(ArbitraryDataProvider.java:207)
	at com.owncloud.android.datamodel.ArbitraryDataProvider.storeOrUpdateKeyValue(ArbitraryDataProvider.java:67)
	at com.owncloud.android.operations.RefreshFolderOperation.updateDirectEditing(RefreshFolderOperation.java:313)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:295)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:270)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:223)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: crownlte
Model: SM-N960F
Id: QP1A.190711.020
Product: crownltexx

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: N960FXXS6ETH4

**Comment by tobiasKaminsky** [comment]
Fixed by #6831, will be in upcoming 3.13.1
