### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by labibllaca** [nextcloud/android#6903]
************ CAUSE OF ERROR ************

java.lang.NullPointerException
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:309)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
	at android.view.View.measure(View.java:17478)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
	at android.view.View.measure(View.java:17478)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.view.View.measure(View.java:17478)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
	at android.view.View.measure(View.java:17478)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2548)
	at android.view.View.measure(View.java:17478)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2285)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1396)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1595)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6632)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:814)
	at android.view.Choreographer.doCallbacks(Choreographer.java:614)
	at android.view.Choreographer.doFrame(Choreographer.java:584)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:800)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5487)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30120090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: konawifi
Model: GT-N5110
Id: KOT49H
Product: konawifixx

************ FIRMWARE ************
SDK: 19
Release: 4.4.2
Incremental: N5110XXDNF1

**Comment by tobiasKaminsky** [comment]
Thanks for the stacktrace, unfortunately this is not showing the cause within our app and also not where/when it happens.

Do you have steps to reproduce?
