### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by AlexandreFoley** [nextcloud/android#6912]
Good luck
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to read from field 'int com.android.server.wm.TaskRecord.taskId' on a null object reference
	at android.os.Parcel.createException(Parcel.java:2077)
	at android.os.Parcel.readException(Parcel.java:2039)
	at android.os.Parcel.readException(Parcel.java:1987)
	at android.app.IActivityTaskManager$Stub$Proxy.reportAssistContextExtras(IActivityTaskManager.java:5317)
	at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:3557)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1973)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityTaskManagerService.reportAssistContextExtras(ActivityTaskManagerService.java:3034)
	at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:2451)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Nokia
Device: CTL_sprout
Model: Nokia 7.1
Id: QKQ1.190828.002
Product: Crystal_00WW

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 00WW_4_15G

**Comment by tobiasKaminsky** [comment]
> Good luck

Indeed :-)
I have no idea what this could cause…As there is also no NC related info in the stacktrace, I have no clue…

Do you recall when this happened?
Can you reproduce it?

**Comment by AlexandreFoley** [comment]
I was having a bit of trouble syncing a folder (about 5GB of mp3) when it happened. The download was not progressing, without error message regarding the server. As far as i could tell the server was working fine. So i canceled the sync, and started it again.
Then the app froze a few seconds before crashing.

I'm unsure any of that really related to the crash.
I'm unable to reproduce the first step (no progress on the download). And if i do the rest anyway, so far there's no problem.

I was hoping that stack trace would enough, because that's all the solid information that I actually have =p.

So far, my experience is that the app is stable. That crash is the only one I had.

**Comment by tobiasKaminsky** [comment]
Thanks for the info.
Then I'll close it, but please reply if it happens again :)
