### ISSUE TITLE
Crashed while Scan a Code as Picture

### ISSUE THREAD

**Issue by PikachuPlus** [nextcloud/android#6930]
I wanted to scan a Code on a picture on my phone. 
But the application is crashed. 

PS: i am a Java Developer to 
(Most time i Developing for Minecraft or little Handy games) 

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:14460 flg=0x1 }} to activity {com.nextcloud.client/com.blikoon.qrcodescanner.QrCodeActivity}: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5230)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5271)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7948)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
Caused by: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
	at android.database.AbstractCursor.checkPosition(AbstractCursor.java:515)
	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:138)
	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:52)
	at android.database.CursorWrapper.getString(CursorWrapper.java:141)
	at com.blikoon.qrcodescanner.QrCodeActivity.getPathFromUri(QrCodeActivity.java:390)
	at com.blikoon.qrcodescanner.QrCodeActivity.onActivityResult(QrCodeActivity.java:370)
	at android.app.Activity.dispatchActivityResult(Activity.java:8292)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5223)
	... 11 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a10
Model: SM-A105FN
Id: QP1A.190711.020
Product: a10eea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: A105FNXXU3BTD4

**Comment by tobiasKaminsky** [comment]
You want to scan a qrcode? Which one?
This is only supported to login in during setup.
