### ISSUE TITLE
Exception while previewing video

### ISSUE THREAD

**Issue by Drqf** [nextcloud/android#6943]
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{3da22d u0 com.nextcloud.android.beta/com.nextcloud.client.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1977)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7582)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20200913
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Redmi
Device: lmipro
Model: Redmi K30 Pro Zoom Edition
Id: QKQ1.191117.002
Product: lmipro

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V12.0.8.0.QJKCNXM

**Comment by Drqf** [comment]
same to 6941
