### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by unf0rg0tt3n** [nextcloud/android#6945]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'long com.owncloud.android.lib.resources.shares.OCShare.getId()' on a null object reference
	at com.owncloud.android.ui.helpers.FileOperationsHelper.setPasswordToPublicShare(FileOperationsHelper.java:592)
	at com.owncloud.android.ui.dialog.SharePasswordDialogFragment.setPassword(SharePasswordDialogFragment.java:198)
	at com.owncloud.android.ui.dialog.SharePasswordDialogFragment.onClick(SharePasswordDialogFragment.java:175)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8154)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: y2s
Model: SM-G986B
Id: QP1A.190711.020
Product: y2sxeea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G986BXXU4BTH5

**Comment by tobiasKaminsky** [comment]
This should be fixed with 3.13.1 RC1 which is available via Play Store beta.
Can you try this?

**Comment by unf0rg0tt3n** [comment]
This works!
