### ISSUE TITLE
Random nextcloud crash while watching a music video on Youtube?!

### ISSUE THREAD

**Issue by priceratops** [nextcloud/android#6948]
************ CAUSE OF ERROR ************

java.lang.IllegalArgumentException: Receiver not registered: androidx.work.impl.constraints.trackers.NetworkStateTracker$NetworkStateBroadcastReceiver@2aca8852
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:801)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1759)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:536)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:536)
	at androidx.work.impl.constraints.trackers.NetworkStateTracker.stopTracking(NetworkStateTracker.java:124)
	at androidx.work.impl.constraints.trackers.ConstraintTracker.removeListener(ConstraintTracker.java:86)
	at androidx.work.impl.constraints.controllers.ConstraintController.replace(ConstraintController.java:97)
	at androidx.work.impl.constraints.WorkConstraintsTracker.replace(WorkConstraintsTracker.java:106)
	at androidx.work.impl.background.greedy.GreedyScheduler.removeConstraintTrackingFor(GreedyScheduler.java:224)
	at androidx.work.impl.background.greedy.GreedyScheduler.onExecuted(GreedyScheduler.java:210)
	at androidx.work.impl.Processor.onExecuted(Processor.java:302)
	at androidx.work.impl.Processor$FutureListener.run(Processor.java:375)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5597)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Amazon
Device: douglas
Model: KFDOWI
Id: LVY48F
Product: douglas

************ FIRMWARE ************
SDK: 22
Release: 5.1.1
Incremental: 50.6.5.7_user_657612420

**Comment by tobiasKaminsky** [comment]
Can you fill out the template, or at least give us steps to reproduce?
Currently I do not get what youtube has to do with our app…?
