### ISSUE TITLE
Crash in mobile app for Android

### ISSUE THREAD

**Issue by Aleksei-Badyaev** [nextcloud/android#6952]
### Steps to reproduce
1. Open mobile app
2. Start contacts sync
3. Wait

### Expected behaviour
- Contacts are synced

### Actual behaviour
- Crash in app
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:318)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.IllegalArgumentException: Trying to execute a remote operation with a NULL Context
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:128)
	at com.owncloud.android.ui.fragment.contactsbackup.ContactsBackupFragment$2.doInBackground(ContactsBackupFragment.java:230)
	at com.owncloud.android.ui.fragment.contactsbackup.ContactsBackupFragment$2.doInBackground(ContactsBackupFragment.java:218)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Meizu
Device: PRO7Plus
Model: PRO 7 Plus
Id: NRD90M
Product: meizu_PRO7Plus

************ FIRMWARE ************
SDK: 24
Release: 7.0
Incremental: 1535448440

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version: latest

Nextcloud server version: 19.0.3

Reverse proxy: Nginx

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by tobiasKaminsky** [comment]
>     2\. Start contacts sync

How did you do this? Manually or scheduled?
