### ISSUE TITLE
Android App crashes on startup

### ISSUE THREAD

**Issue by sixsox** [nextcloud/android#6960]
Android App crashes on startup, even after cache and appdata have been cleared.

************ CAUSE OF ERROR ************

android.database.SQLException: ERROR content://org.nextcloud/capabilities
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:321)
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:255)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:309)
	at android.content.ContentResolver.insert(ContentResolver.java:1828)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveCapabilities(FileDataStorageManager.java:1955)
	at com.owncloud.android.operations.GetCapabilitiesOperation.run(GetCapabilitiesOperation.java:51)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:139)
	at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:64)
	at com.owncloud.android.ui.activity.DrawerActivity.lambda$fetchExternalLinks$5$DrawerActivity(DrawerActivity.java:1028)
	at com.owncloud.android.ui.activity.-$$Lambda$DrawerActivity$7r726W9nEhA053kMOzVzspjY07M.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: google
Device: marlin
Model: Pixel XL
Id: QP1A.191005.007.A3
Product: marlin

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 5972272

**Comment by tobiasKaminsky** [comment]
No idea what happened there…
But as you already removed appdata, can you try to re-install it?

**Comment by sixsox** [comment]
Yes, reinstalled from F-Droid, same problem after entering log-in credentials. 
The app just briefly showed the root directory of my hub data and then crashed again. 
Interestingly this DOES NOT happen when installing Nextcloud app from the Google Play Store.
Appears to be a problem of the F-Droid build only.

**Comment by tobiasKaminsky** [comment]
> Interestingly this DOES NOT happen when installing Nextcloud app from the Google Play Store.
> Appears to be a problem of the F-Droid build only.

Uh. That is strange, as the only change between Fdroid and Play Store releases is missing/adding push notification support.

> fetchExternalLinks

What kind of external links do you have?
