### ISSUE TITLE
Nextcloud App crashes on link password modification

### ISSUE THREAD

**Issue by pludi** [nextcloud/android#6966]
### Steps to reproduce
1. Create a shareable link
2. Try to set or remove the password

### Expected behaviour
- Password on the link is changed/removed

### Actual behaviour
- App crashes with a null-pointer exception

### Can you reproduce this problem on https://try.nextcloud.com?
Yes

### Environment data
Android version: 8.1.0

Device model: Bq Aquaris X Pro

Stock or customized system: Stock

Nextcloud app version: 3.13.0

Nextcloud server version: 17.0.9

Reverse proxy: nginx

### Exception Log
```
java.lang.NullPointerException: Attempt to invoke virtual method 'long com.owncloud.android.lib.resources.shares.OCShare.getId()' on a null object reference
	at com.owncloud.android.ui.helpers.FileOperationsHelper.setPasswordToPublicShare(FileOperationsHelper.java:592)
	at com.owncloud.android.ui.dialog.SharePasswordDialogFragment.setPassword(SharePasswordDialogFragment.java:198)
	at com.owncloud.android.ui.dialog.SharePasswordDialogFragment.onClick(SharePasswordDialogFragment.java:181)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6543)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: bq
Device: bardock-pro
Model: Aquaris X Pro
Id: OPM1.171019.026
Product: bardock-pro

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: 2395
```

**Comment by tobiasKaminsky** [comment]
This is fixed via 3.13.1.
Please upgrade.
