### ISSUE TITLE
App crash on syncing a New folder (nullpointer)

### ISSUE THREAD

**Issue by fleixi** [nextcloud/android#6972]
### Steps to reproduce
1. Open App
2. Try to sync a New folder
3. App crash

### Expected behaviour
- Folder geht synced

### Actual behaviour
- App crash

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10

Device model: one plus one bacon

Stock or customized system: lineageos

Nextcloud app version: fdroid dev 20200908

Nextcloud server version: 19

Reverse proxy:  nginx

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
Error from the App

************ CAUSE OF ERROR ************

java.lang.NullPointerException
	at java.io.File.<init>(File.java:283)
	at com.owncloud.android.ui.fragment.OCFileListFragment.checkIfEnoughSpace(OCFileListFragment.java:1785)
	at com.owncloud.android.ui.fragment.OCFileListFragment.syncAndCheckFiles(OCFileListFragment.java:1770)
	at com.owncloud.android.ui.fragment.OCFileListFragment.onFileActionChosen(OCFileListFragment.java:1160)
	at com.owncloud.android.ui.fragment.OCFileListFragment.lambda$onOverflowIconClicked$4$OCFileListFragment(OCFileListFragment.java:532)
	at com.owncloud.android.ui.fragment.-$$Lambda$OCFileListFragment$Vub-hSwuRnZYfTOMLTxZ0VL71II.onMenuItemClick(Unknown Source:4)
	at android.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:108)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:787)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:151)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:934)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:924)
	at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1190)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3198)
	at android.widget.AbsListView$3.run(AbsListView.java:4116)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20200908
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: oneplus
Device: bacon
Model: A0001
Id: QQ3A.200805.001
Product: bacon

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 431caa5ea7

**Comment by tobiasKaminsky** [comment]
Can you update your app to latest dev and test it again?
I think this is already fixed.
If not, please re-open.
