### ISSUE TITLE
First time install and login, crash after login

### ISSUE THREAD

**Issue by zilexa** [nextcloud/android#6977]
### Steps to reproduce
1. Install app on Pixel 1/Android 10
2. Enter FileRun server and login credentials
3. Allow access 
4. Immediate crash

### Expected behaviour
- No crash

### Actual behaviour

```
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032 SQLITE_READONLY_DBMOVED)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:831)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1704)
	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1650)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:645)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:629)
	at android.content.ContentProvider$Transport.update(ContentProvider.java:420)
	at android.content.ContentResolver.update(ContentResolver.java:1993)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveCapabilities(FileDataStorageManager.java:1940)
	at com.owncloud.android.operations.GetCapabilitiesOperation.run(GetCapabilitiesOperation.java:51)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:139)
	at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:64)
	at com.owncloud.android.ui.activity.DrawerActivity.lambda$fetchExternalLinks$5$DrawerActivity(DrawerActivity.java:1028)
	at com.owncloud.android.ui.activity.-$$Lambda$DrawerActivity$7r726W9nEhA053kMOzVzspjY07M.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: sailfish
Model: Pixel
Id: QP1A.191005.007.A3
Product: sailfish

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 5972272
```

**Comment by tobiasKaminsky** [comment]
> attempt to write a readonly database

Strange, this seems that somehow Android prevents you to write.
Maybe disk is full?

**Comment by zilexa** [comment]
Not sure why it crashed a couple of times. I reinstalled my FileRun docker instance and I don't have this issue anymore.
