### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nmkeb** [nextcloud/android#6992]
#####Actual behaviour
- Closing of the Apps juste after opening. 

### Logs
************ CAUSE OF ERROR ************

java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter value
	at com.owncloud.android.datamodel.ArbitraryDataSet.<init>(Unknown Source:12)
	at com.owncloud.android.datamodel.ArbitraryDataProvider.getArbitraryDataSet(ArbitraryDataProvider.java:207)
	at com.owncloud.android.datamodel.ArbitraryDataProvider.storeOrUpdateKeyValue(ArbitraryDataProvider.java:67)
	at com.owncloud.android.operations.RefreshFolderOperation.updateDirectEditing(RefreshFolderOperation.java:313)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:295)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:270)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:223)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Sony
Device: G8441
Model: G8441
Id: 47.2.A.11.228
Product: G8441

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 3311891731

**Comment by tobiasKaminsky** [comment]
Please update to 3.13.1 as this is already fixed.
