### ISSUE TITLE
App crashing on splash

### ISSUE THREAD

**Issue by limallucas96** [nextcloud/android#6993]
### Steps to reproduce
1. Download the app from play store
2. Open it
3. Crashes on splash

### Expected behaviour
- Open activity after splash

### Actual behaviour
- Crashes on splash activity

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to resume activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.SecurityException: uid 10670 cannot get user data for accounts of type: nextcloud
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3828)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3860)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.lang.SecurityException: uid 10670 cannot get user data for accounts of type: nextcloud
	at android.os.Parcel.createException(Parcel.java:1953)
	at android.os.Parcel.readException(Parcel.java:1921)
	at android.os.Parcel.readException(Parcel.java:1871)
	at android.accounts.IAccountManager$Stub$Proxy.getUserData(IAccountManager.java:1020)
	at android.accounts.AccountManager.getUserData(AccountManager.java:517)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.<init>(OCFileListAdapter.java:167)
	at com.owncloud.android.ui.fragment.OCFileListFragment.onActivityCreated(OCFileListFragment.java:352)
	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2718)
	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1200)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
	at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:447)
	at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:458)
	at com.owncloud.android.ui.activity.BaseActivity.onResume(BaseActivity.java:91)
	at com.owncloud.android.ui.activity.DrawerActivity.onResume(DrawerActivity.java:899)
	at com.owncloud.android.ui.activity.FileActivity.onResume(FileActivity.java:240)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onResume(FileDisplayActivity.java:1087)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1413)
	at android.app.Activity.performResume(Activity.java:7400)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3820)
	... 11 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.accounts.AccountManagerService.getUserData(AccountManagerService.java:1547)
	at android.accounts.IAccountManager$Stub.onTransact(IAccountManager.java:77)
	at com.android.server.accounts.AccountManagerService.onTransact(AccountManagerService.java:1075)
	at android.os.Binder.execTransact(Binder.java:735)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: xiaomi
Device: tulip
Model: Redmi Note 6 Pro
Id: PKQ1.180904.001
Product: tulip

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: V11.0.5.0.PEKMIXM

**Comment by tobiasKaminsky** [comment]
Do you use android for work, profiles, MDM, etc.?

**Comment by limallucas96** [comment]
Yes I do. Actually when I closed the app and opened again it worked but it has a strange behavior. It keeps starting an activity when I tap go back, so I can never really exit the login screen. 
I'm an Android dev looking to fix it, how can I create a PR?

**Comment by tobiasKaminsky** [comment]
> I'm an Android dev looking to fix it, how can I create a PR?

That would be awesome. Here are some basics to start:

https://github.com/nextcloud/android/blob/master/SETUP.md
https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md

If you need more info, just reply here :+1:
