### ISSUE TITLE
Crashing after first login

### ISSUE THREAD

**Issue by LaakkoT** [nextcloud/android#7018]
### Steps to reproduce
1. Started nextcloud on work profile with VPN
2. logo in succesfully
3. After log in nextcloud crash

### Expected behaviour
- able to use files

### Actual behaviour
- everytime when trying to log in nextcloud crash

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

************ CAUSE OF ERROR ********

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED flg=0x10 pkg=com.nextcloud.client (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver@cccc534
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1401)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6746)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:500)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.SecurityException: Permission Denial: unbroadcastIntent() from pid=30737, uid=1010211 requires android.permission.BROADCAST_STICKY
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.app.IActivityManager$Stub$Proxy.unbroadcastIntent(IActivityManager.java:3920)
	at android.app.ContextImpl.removeStickyBroadcast(ContextImpl.java:1346)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
	at android.content.ContextWrapper.removeStickyBroadcast(ContextWrapper.java:588)
	at com.owncloud.android.ui.activity.FileDisplayActivity$SyncBroadcastReceiver.onReceive(FileDisplayActivity.java:1311)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1391)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.unbroadcastIntent(ActivityManagerService.java:22185)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:183)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3320)
	at android.os.Binder.execTransact(Binder.java:731)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Bittium
Device: craton
Model: Bittium Tough Mobile 2
Id: MR5
Product: slate_gms_EEA

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 72.1_sdp40

**Comment by LaakkoT** [comment]
Not yet tested on demo server. I will do that next.

**Comment by AndyScherzinger** [comment]
@LaakkoT did you use a work profile or secondary profile on Android? If so please install the app an the primary profile to (just install, nothing else, no login needed).

@tobiasKaminsky is working on a fix for this but this isn't shipped yet but the workaround mentioned should do the trick for now.

**Comment by LaakkoT** [comment]
Hi,

@AndyScherzinger, thanks for the workaround, it works!

**Comment by AndyScherzinger** [comment]
Glad to hear that 🎉 

You are very welcome :)
