### ISSUE TITLE
Random error

### ISSUE THREAD

**Issue by Bored0ne** [nextcloud/android#7027]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to pause activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@4bcbdaf is not valid; is your activity running?
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4721)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4672)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4624)
	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2183)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:7617)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@4bcbdaf is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:935)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:387)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
	at android.app.Dialog.show(Dialog.java:342)
	at androidx.fragment.app.DialogFragment.onStart(DialogFragment.java:529)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:2731)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:365)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1206)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2641)
	at androidx.fragment.app.FragmentManager.dispatchPause(FragmentManager.java:2605)
	at androidx.fragment.app.FragmentController.dispatchPause(FragmentController.java:280)
	at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:419)
	at com.owncloud.android.ui.activity.BaseActivity.onPause(BaseActivity.java:84)
	at com.owncloud.android.ui.activity.FileActivity.onPause(FileActivity.java:253)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onPause(FileDisplayActivity.java:1181)
	at android.app.Activity.performPause(Activity.java:7986)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1529)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4711)
	... 12 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: motorola
Device: def
Model: motorola one hyper
Id: QPFS30.103-47-8
Product: def_retail

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 75af32

**Comment by tobiasKaminsky** [comment]
Can you add steps to reproduce?
