### ISSUE TITLE
NC app crashed when turning the phone to landscape

### ISSUE THREAD

**Issue by scheinercc** [nextcloud/android#7029]
### Steps to reproduce
1. Open picture
2. Change phone from portrait to landscape
3. Crash

### Expected behaviour
Show picture in landscape

### Actual behaviour
The app crashed

### Environment data
************ CAUSE OF ERROR ************

java.lang.IllegalArgumentException: Scale must be within the range of minScale and maxScale
	at com.github.chrisbanes.photoview.PhotoViewAttacher.setScale(PhotoViewAttacher.java:456)
	at com.github.chrisbanes.photoview.PhotoViewAttacher.setScale(PhotoViewAttacher.java:446)
	at com.github.chrisbanes.photoview.PhotoViewAttacher.setScale(PhotoViewAttacher.java:442)
	at com.github.chrisbanes.photoview.PhotoView.setScale(PhotoView.java:230)
	at com.owncloud.android.ui.preview.PreviewImageFragment.onActivityCreated(PreviewImageFragment.java:230)
	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2718)
	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1200)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at com.owncloud.android.ui.activity.DrawerActivity.onStart(DrawerActivity.java:1000)
	at com.owncloud.android.ui.activity.FileActivity.onStart(FileActivity.java:230)
	at com.owncloud.android.ui.preview.PreviewImageActivity.onStart(PreviewImageActivity.java:182)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
	at android.app.Activity.performStart(Activity.java:7864)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3295)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Fairphone
Device: FP3
Model: FP3
Id: 8901.3.A.0045.20200905
Product: FP3

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 09051550

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky see #6824 which you fixed (for 3.13.1). It seems there is yet another scenario. 
@scheinercc what are the dimensions of the image and file type?

**Comment by scheinercc** [comment]
Sorry @AndyScherzinger the email with your reply got lost in too many emails :/

I just tested it with a few pictures and can't replicate it anymore. Closing this ticket.
