### ISSUE TITLE
Resources$NotFoundException

### ISSUE THREAD

**Issue by insiderser** [nextcloud/android#7047]
### Steps to reproduce
1. Click on account icon in the header.
2. "Manage accounts".
3. Click on any account.

### Expected behaviour
I can see some info about my account.

### Actual behaviour
Crash:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.UserInfoActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f070174
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f070174
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:237)
	at android.content.res.Resources.getDimension(Resources.java:752)
	at com.owncloud.android.ui.activity.UserInfoActivity.onCreate(UserInfoActivity.java:140)
	at android.app.Activity.performCreate(Activity.java:8000)
	at android.app.Activity.performCreate(Activity.java:7984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
	... 11 more
```

### Additional info
Looks like it can't find `R.dimen.nav_drawer_header_avatar_radius`. It is defined in `values-sw360dp/dims.xml`, but not in `values/dims.xml`. This will crash on devices with the smallest width less than 360dp. I've set "Display size" to "Larger" in system settings, which is probably the reason why it thinks my sw < 360dp. If I temporarily change "Display size" to "Normal", UserInfoActivity opens as expected.

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky

**Comment by AndyScherzinger** [comment]
Thanks for the report and also for the detailed analysis of the root cause ❤️

**Comment by AndyScherzinger** [comment]
#7052 should fix it and also streamline the dimension handling as well as adding some layouting optimizations (like material design single line iconized layout height)
