### ISSUE TITLE
Out of Memory exception while moving files

### ISSUE THREAD

**Issue by cebe** [nextcloud/android#7069]
### Steps to reproduce
1. I have uploaded fotos from my phone to next cloud (10.6GB, 1972 files)
2. After that I want to categorize them so I select multiple photos in the nextcloud app (about 100) and move them to another directory. 

### Expected behaviour
- photos should be moved 

### Actual behaviour
- after being unresponsive for a while next cloud app crashes with out of memory error

![photo_2020-10-10_01-00-25](https://user-images.githubusercontent.com/189796/95638191-15ac8f00-0a94-11eb-9407-2a540ea1662e.jpg)

### Environment data
Android version: 7.1.2

Device model: Fairphone 2

Stock or customized system: FP2

Nextcloud app version: 3.13.0

Nextcloud server version: 19.0.3

Reverse proxy: ?

#### Nextcloud log (data/nextcloud.log)

I have no `data/nextcloud.log` file as far as I see. Here is the output saved to clipboard after the crash:

```
************ CAUSE OF ERROR ************

java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Fairphone
Device: FP2
Model: FP2
Id: 19.11.2
Product: FP2

************ FIRMWARE ************
SDK: 25
Release: 7.1.2
Incremental: sibon-24df0be9

```

Please let me know if there is any more information needed.

**Comment by cebe** [comment]
Sorry for the mess, I just typed this on my phone. Will clean up later.

**Comment by tobiasKaminsky** [comment]
Hm, I tried it with my emulator and there 100 images work.
Can you try it with little less?

**Comment by cebe** [comment]
************ CAUSE OF ERROR ************

java.lang.OutOfMemoryError: Failed to allocate a 52 byte allocation with 2040 free bytes and 2040B until OOM; failed due to fragmentation (required continguous free 4096 bytes for a new buffer where largest contiguous free 0 bytes)
	at java.util.Arrays.copyOf(Arrays.java:3231)
	at java.util.Arrays.copyOf(Arrays.java:3204)
	at java.util.ArrayList.grow(ArrayList.java:249)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:223)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:215)
	at java.util.ArrayList.add(ArrayList.java:459)
	at org.apache.harmony.xml.dom.InnerNodeImpl.insertChildAt(InnerNodeImpl.java:130)
	at org.apache.harmony.xml.dom.InnerNodeImpl.appendChild(InnerNodeImpl.java:52)
	at org.apache.harmony.xml.parsers.DocumentBuilderImpl.appendText(DocumentBuilderImpl.java:351)
	at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:232)
	at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:295)
	at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:295)
	at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:295)
	at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:295)
	at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:295)
	at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:128)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:107)
	at org.apache.jackrabbit.webdav.xml.DomUtil.parseDocument(DomUtil.java:104)
	at org.apache.jackrabbit.webdav.client.methods.DavMethodBase.getResponseBodyAsDocument(DavMethodBase.java:113)
	at org.apache.jackrabbit.webdav.client.methods.DavMethodBase.getRootElement(DavMethodBase.java:137)
	at org.apache.jackrabbit.webdav.client.methods.DavMethodBase.processResponseBody(DavMethodBase.java:282)
	at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1749)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:219)
	at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.run(ReadFolderRemoteOperation.java:80)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:184)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:368)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:231)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:761)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Fairphone
Device: FP2
Model: FP2
Id: 19.11.2
Product: FP2

************ FIRMWARE ************
SDK: 25
Release: 7.1.2
Incremental: sibon-24df0be9

**Comment by cebe** [comment]
Even selecting the items in the folder which currently has 1972 files in it makes the app kind of unresponsive for short amount of time. But it still works.

I can still see the problem when I select 100 files. Same behavior. App becomes unresponsive, then after a while I get the OutOfMemoryError.

I tried moving 75 files from that folder, same issue.But I get the stack trace, posted above :point_up:  

Error might be related to the total number of files in the folder, not to the amount of files moved?

How does moving work? I'd assume, that it would be sending a list of file ids to move to the server, not much work to do on the client for this. Is it implemented differently?

**Comment by tobiasKaminsky** [comment]
> at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:368)

This seems to just crash due to too many files in folder.
So the resulting array is too big for your device and thus it crashes…

As this is in  within httpclient libary, I fear we cannot do anything right now.
This will be better when we switch to new library, which then also supports streams…

**Comment by cebe** [comment]
As far as I see there has not been a fix for this. Please re-open.

**Comment by joshtrichards** [comment]
Tracking in #9903
