### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by benma0005** [nextcloud/android#7072]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:31371 flg=0x1 }} to activity {com.nextcloud.client/com.blikoon.qrcodescanner.QrCodeActivity}: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4965)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5006)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7551)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
Caused by: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
	at android.database.AbstractCursor.checkPosition(AbstractCursor.java:521)
	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:138)
	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:52)
	at android.database.CursorWrapper.getString(CursorWrapper.java:141)
	at com.blikoon.qrcodescanner.QrCodeActivity.getPathFromUri(QrCodeActivity.java:390)
	at com.blikoon.qrcodescanner.QrCodeActivity.onActivityResult(QrCodeActivity.java:370)
	at android.app.Activity.dispatchActivityResult(Activity.java:8249)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4958)
	... 11 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Redmi
Device: begonia
Model: Redmi Note 8 Pro
Id: QP1A.190711.020
Product: begonia_eea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V12.0.1.0.QGGEUXM

```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Can you fill out the entire template?
