### ISSUE TITLE
Error when trying to create a odt document in nextcloud mobile app. Collavora Office online installed on server and working perfectly.

### ISSUE THREAD

**Issue by pulkitkrishna00** [nextcloud/android#7074]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.IllegalStateException: Fragment ChooseRichDocumentsTemplateDialogFragment{1b43e92} (71d8add8-cf10-435c-89ee-f4da92323d45)} not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:805)
	at com.owncloud.android.ui.dialog.ChooseRichDocumentsTemplateDialogFragment$CreateFileFromTemplateTask.doInBackground(ChooseRichDocumentsTemplateDialogFragment.java:249)
	at com.owncloud.android.ui.dialog.ChooseRichDocumentsTemplateDialogFragment$CreateFileFromTemplateTask.doInBackground(ChooseRichDocumentsTemplateDialogFragment.java:214)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: m30s
Model: SM-M307F
Id: QP1A.190711.020
Product: m30sdd

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: M307FXXS4BTI2

**Comment by tobiasKaminsky** [comment]
> Caused by: java.lang.IllegalStateException: Fragment ChooseRichDocumentsTemplateDialogFragment{1b43e92} (71d8add8-cf10-435c-89ee-f4da92323d45)} not attached to a context.

Have you navigated away?
Can you wait a bit more when you try to create a new file?
