### ISSUE TITLE
Crash on Android

### ISSUE THREAD

**Issue by dotMavriQ** [nextcloud/android#7080]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.populateList(FileDetailActivitiesFragment.java:418)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$null$3$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:370)
	at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$M8TYfIenzWzYVRkIKXs5v-Y2zZA.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6548)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20201008
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Ulefone
Device: Armor_6
Model: Armor_6
Id: O11019
Product: Armor_6_EEA

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: 1556191902

**Comment by tobiasKaminsky** [comment]
Do you know when this happens?

**Comment by dotMavriQ** [comment]
> 
> 
> Do you know when this happens?

It happens when I attempt to open a markdown file from an S3 (Wasabi) folder that I have in my files directory.

**Comment by tobiasKaminsky** [comment]
Hm. Open or view details? 
As stack trace seems to be related do file details / activity stream?
