### ISSUE TITLE
Some rendom error 

### ISSUE THREAD

**Issue by empratyush** [nextcloud/android#7113]
> I am just providing crash report without checking is it already reported or not so feel free to close the case in case if it's already reported.

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to read from field 'java.util.concurrent.ConcurrentMap com.owncloud.android.services.OperationsService$OperationsServiceBinder.mBoundListeners' on a null object reference
	at com.owncloud.android.services.OperationsService$OperationsServiceBinder.access$500(OperationsService.java:260)
	at com.owncloud.android.services.OperationsService.dispatchResultToOperationListeners(OperationsService.java:734)
	at com.owncloud.android.services.SyncFolderHandler.doOperation(SyncFolderHandler.java:121)
	at com.owncloud.android.services.SyncFolderHandler.handleMessage(SyncFolderHandler.java:88)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.os.HandlerThread.run(HandlerThread.java:67)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Android
Device: taimen
Model: Pixel 2 XL
Id: RP1A.201005.004
Product: aosp_taimen

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 2020.10.06.02

**Comment by tobiasKaminsky** [comment]
Do you know when this happens?

**Comment by empratyush** [comment]
sorry for late response.

i am not sure but i guess on refresh/sync

**Comment by tobiasKaminsky** [comment]
Is this happening reliable?

**Comment by empratyush** [comment]
No not very often but when there is a lot files like 7gb of images (dmg, png etc) involved it's throw same exception. when a sync is already in progress and we nagivate to any other folder.
