### ISSUE TITLE
Android App crashes when trying to manage account

### ISSUE THREAD

**Issue by kamazeuci** [nextcloud/android#7131]
### Steps to reproduce
1. Open App
2. Tap User Capital letter (top right)
3.  Tap "Manage Accounts"
4. Tap user name/account

### Expected behaviour
I suppose it should give me account sync and other options.

### Actual behaviour
Nextcloud crashed report

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.UserInfoActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f070174
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3477)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3620)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2183)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:241)
at android.app.ActivityThread.main(ActivityThread.java:7617)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f070174
at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:237)
at android.content.res.Resources.getDimension(Resources.java:675)
at com.owncloud.android.ui.activity.UserInfoActivity.onCreate(UserInfoActivity.java:140)
at android.app.Activity.performCreate(Activity.java:7810)
at android.app.Activity.performCreate(Activity.java:7799)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1328)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3452)
... 11 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: motorola
Device: troika_sprout
Model: motorola one action
Id: QSBS30.62-17-13
Product: troika

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 1d1e

**Comment by tobiasKaminsky** [comment]
This is already fixed and will be in today's 3.14.0 RC1.
