### ISSUE TITLE
Nullpointer bug when going back in login screen

### ISSUE THREAD

**Issue by konstantin-spiess** [nextcloud/android#7143]
### Steps to reproduce
1. Click on login
2. Go back two times (android button)
3. Click on the plus icon at the bottom right corner

### Expected behaviour
- You should not be able to go two steps back

### Actual behaviour
- Crashes (Nullpointer)

### Crash log
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'com.owncloud.android.lib.resources.status.CapabilityBooleanType com.owncloud.android.lib.resources.status.OCCapability.getRichDocuments()' on a null object reference
	at com.owncloud.android.ui.fragment.OCFileListBottomSheetDialog.onCreate(OCFileListBottomSheetDialog.java:128)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:421)
	at android.app.Dialog.show(Dialog.java:315)
	at com.owncloud.android.ui.fragment.OCFileListFragment.lambda$registerFabListener$2$OCFileListFragment(OCFileListFragment.java:433)
	at com.owncloud.android.ui.fragment.-$$Lambda$OCFileListFragment$QZSjQfSuvxKNvMpRngqzT4P2ngY.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7201)
	at android.view.View.performClickInternal(View.java:7170)
	at android.view.View.access$3500(View.java:806)
	at android.view.View$PerformClick.run(View.java:27582)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus7Pro
Model: GM1913
Id: QKQ1.190716.003
Product: OnePlus7Pro_EEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2007240000

**Comment by tobiasKaminsky** [comment]
Is this happening with a clean installation aka you have no account set up yet?

**Comment by konstantin-spiess** [comment]
I just tested with a new installation and the problem was gone. However, it reappeared when I typed anything in the server address field e.g. "123" and then quit the application. When I opened it again the bug occurred as described.

**Comment by tobiasKaminsky** [comment]
How do you quit the app? Back button, or "minimize"?

**Comment by konstantin-spiess** [comment]
I close the app in the recent apps overview, so that it is completely stopped.

**Comment by konstantin-spiess** [comment]
![WhatsApp-Video-2020-10-28-at-140](https://user-images.githubusercontent.com/22649845/97439885-0ac47c00-1927-11eb-8ccb-b9f814082ee1.gif)

**Comment by tobiasKaminsky** [comment]
I think this is fixed via https://github.com/nextcloud/android/pull/7124
Please report if it is still in 3.14.0 RC1 (coming today)
