### ISSUE TITLE
Android app crash

### ISSUE THREAD

**Issue by raldone01** [nextcloud/android#7190]
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1703)
	at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1743)
	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:321)
	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:286)
	at androidx.fragment.app.DialogFragment.show(DialogFragment.java:198)
	at com.owncloud.android.ui.activity.FileActivity.showLoadingDialog(FileActivity.java:537)
	at com.owncloud.android.ui.helpers.FileOperationsHelper.lambda$syncFile$1$FileOperationsHelper(FileOperationsHelper.java:245)
	at com.owncloud.android.ui.helpers.-$$Lambda$FileOperationsHelper$6veiwPPVcnDkYiDbC_hH1dHAJ4s.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: dreamlte
Model: SM-G950F
Id: PPR1.180610.011
Product: dreamltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G950FXXSADTI1

**Comment by tobiasKaminsky** [comment]
Stacktrace indicates that there is some sort of dialog open.
Do you know what exactly happened / how you can reproduce it?

**Comment by raldone01** [comment]
I don't think a dialog opnened and I can't reproduce. It seemed random. Sorry I can't provide further information. My network connection was very bad though. Maybe a network request took too long?

I reported this although it seemed random because i think random crashes are not good for the ux.

**Comment by tobiasKaminsky** [comment]
> i think random crashes are not good for the ux.

Indeed and it is good that you reported it, but this is then even more trickier to fix… ;-)

**Comment by joshtrichards** [comment]
Fixed in #13037
