### ISSUE TITLE
App crash after opening account selector

### ISSUE THREAD

**Issue by Chartman123** [nextcloud/android#7199]
As a side note: The currently selected profile points to an unreachable/offline server.

### Steps to reproduce
1. Open account selector
2. Wait a second
3. 

### Expected behaviour
- you should be able to select another account 

### Actual behaviour
- app crashes

### Environment data
Android version: 11

Device model: Oneplus 8

Stock or customized system: Stock

Nextcloud app version: 3.14.0 RC1

Nextcloud server version: 20.0.1

Reverse proxy: yes

```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.ArrayList.get(int)' on a null object reference
	at com.owncloud.android.lib.common.operations.RemoteOperationResult.getSingleData(RemoteOperationResult.java:489)
	at com.owncloud.android.ui.asynctasks.RetrieveStatusAsyncTask.doInBackground(RetrieveStatusAsyncTask.java:56)
	at com.owncloud.android.ui.asynctasks.RetrieveStatusAsyncTask.doInBackground(RetrieveStatusAsyncTask.java:37)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus8
Model: IN2013
Id: RP1A.201005.001
Product: OnePlus8_EEA

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 2009301800

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky seems to Status retrieval in the liberal project needs some hardening.

**Comment by tobiasKaminsky** [comment]
Yes, this is fixed via https://github.com/nextcloud/android/pull/7213

**Comment by tobiasKaminsky** [comment]
Will be in RC2.
