### ISSUE TITLE
NPE Anrdoid FileStorageUtils

### ISSUE THREAD

**Issue by Commander9000** [nextcloud/android#7200]
### Steps to reproduce
1. Restart the app
2. 
3. 

### Expected behaviour
- No NPE in the logs

### Actual behaviour
- NPE is thrown

### Can you reproduce this problem on https://try.nextcloud.com?
- No

### Environment data
Android version:
9

Device model: 
LG-H870

Stock or customized system:
Stock

Nextcloud app version:
3.13.1

Nextcloud server version:
20.0.1

Reverse proxy:
Yes

#### Web server error log
```
Nothing to see
```

#### Nextcloud log (data/nextcloud.log)
```
11-02 01:05:48.223	5578	5617	com.nextcloud.client	E	WM-WorkerWrapper	Work [ id=30c0135b-5242-4652-8caa-0287994f897f, tags={ name:periodic_files_sync, com.nextcloud.client.jobs.FilesSyncWork, *, timestamp:1604275496457 } ] failed because it threw an exception/error
11-02 01:05:48.223	5578	5617	com.nextcloud.client	E	WM-WorkerWrapper	java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
11-02 01:05:48.223	5578	5617	com.nextcloud.client	E	WM-WorkerWrapper		at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
11-02 01:05:48.223	5578	5617	com.nextcloud.client	E	WM-WorkerWrapper		at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
11-02 01:05:48.223	5578	5617	com.nextcloud.client	E	WM-WorkerWrapper		at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:298)
11-02 01:05:48.223	5578	5617	com.nextcloud.client	E	WM-WorkerWrapper		at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
11-02 01:05:48.223	5578	5617	com.nextcloud.client	E	WM-WorkerWrapper		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-02 01:05:48.223	5578	5617	com.nextcloud.client	E	WM-WorkerWrapper		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-02 01:05:48.223	5578	5617	com.nextcloud.client	E	WM-WorkerWrapper		at java.lang.Thread.run(Thread.java:764)
11-02 01:05:48.223	5578	5617	com.nextcloud.client	E	WM-WorkerWrapper	Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
11-02 01:05:48.223	5578	5617	com.nextcloud.client	E	WM-WorkerWrapper		at com.owncloud.android.utils.FileStorageUtils.getInstantUploadFilePath(FileStorageUtils.java:181)
11-02 01:05:48.223	5578	5617	com.nextcloud.client	E	WM-WorkerWrapper		at com.nextcloud.client.jobs.FilesSyncWork.syncFolder(FilesSyncWork.kt:185)
11-02 01:05:48.223	5578	5617	com.nextcloud.client	E	WM-WorkerWrapper		at com.nextcloud.client.jobs.FilesSyncWork.doWork(FilesSyncWork.kt:119)
11-02 01:05:48.223	5578	5617	com.nextcloud.client	E	WM-WorkerWrapper		at androidx.work.Worker$1.run(Worker.java:85)
11-02 01:05:48.223	5578	5617	com.nextcloud.client	E	WM-WorkerWrapper		... 3 more
```

**Comment by tobiasKaminsky** [comment]
Fixed via https://github.com/nextcloud/android/pull/7230 and will be in 3.14.0.
You can test it already when joining beta program.
