### ISSUE TITLE
Crash opening PDF file

### ISSUE THREAD

**Issue by XueSheng-GIT** [nextcloud/android#7208]
### Steps to reproduce
1. Tap pdf file to open (not downloaded!)
2. Download of PDF starts
3. Nextcloud crashes while opening PDF file (this does not happen if the PDF file was downloaded manually before!!!)

### Expected behaviour
- PDF file should open in external viewer app (xodo in my case)

### Actual behaviour
- Nextcloud crashes

### Logs
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.swiperefreshlayout.widget.SwipeRefreshLayout.setVisibility(int)' on a null object reference
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.populateList(FileDetailActivitiesFragment.java:418)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$null$3$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:370)
	at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$ZzLUj33qKg0e1Ki8Vd5bki8I6B4.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8347)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWLYA
Model: LYA-L29
Id: HUAWEILYA-L29
Product: LYA-L29

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.1.0.289C432

**Comment by tobiasKaminsky** [comment]
Thanks for reporting!
Will be fixed via #7210 and will be in RC2.
