### ISSUE TITLE
Absturz beim Download / Öffnen von Dateien

### ISSUE THREAD

**Issue by weinic** [nextcloud/android#7238]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.swiperefreshlayout.widget.SwipeRefreshLayout.setVisibility(int)' on a null object reference
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.populateList(FileDetailActivitiesFragment.java:418)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$null$3$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:370)
	at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$ZzLUj33qKg0e1Ki8Vd5bki8I6B4.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7697)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus5
Model: ONEPLUS A5000
Id: QKQ1.191014.012
Product: OnePlus5

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2006012143

Neulich stürzt NC beim Download von Dateien ab

**Comment by weinic** [comment]
Die App stürzt nicht wegen dem Download ab, sondern beim Versuch die Datei zu öffnen. Das habe ich bis jetzt bei einer PDF und gpx Datei festgestellt.
Rechts auf die drei Punkte klicken und dann herunterladen funktioniert.
Wenn ich allerdings die Datei direkt anklicke, läd Nextcloud diese herunter und scheitert danach beim öffnen.
Wenn die Datei dann herunter geladen ist, lässt sie sich öffnen.

**Comment by AndyScherzinger** [comment]
Duplicate of #7188
