### ISSUE TITLE
More gracefully handle full device condition

### ISSUE THREAD

**Issue by kr4z33** [nextcloud/android#7248]
### Steps to reproduce
1. Fill a phone with crap
2. Use Nextcloud
3. 

### Expected behaviour
- generate a nice error message and not crash

### Actual behaviour
- See below, which was offered at crash time:
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to create application com.owncloud.android.MainApp: android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 4874 SQLITE_IOERR_SHMSIZE)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6145)
at android.app.ActivityThread.access$1200(ActivityThread.java:213)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:215)
at android.app.ActivityThread.main(ActivityThread.java:6952)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
Caused by: android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 4874 SQLITE_IOERR_SHMSIZE)
at android.database.sqlite.SQLiteConnection.nativeExecuteForLong(Native Method)
at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:612)
at android.database.sqlite.SQLiteSession.executeForLong(SQLiteSession.java:652)
at android.database.sqlite.SQLiteStatement.simpleQueryForLong(SQLiteStatement.java:107)
at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:842)
at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:830)
at android.database.sqlite.SQLiteDatabase.getVersion(SQLiteDatabase.java:956)
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:371)
at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:322)
at com.owncloud.android.providers.FileContentProvider.query(FileContentProvider.java:472)
at android.content.ContentProvider.query(ContentProvider.java:1057)
at android.content.ContentProvider.query(ContentProvider.java:1149)
at android.content.ContentProvider$Transport.query(ContentProvider.java:241)
at android.content.ContentResolver.query(ContentResolver.java:802)
at android.content.ContentResolver.query(ContentResolver.java:752)
at android.content.ContentResolver.query(ContentResolver.java:710)
at com.owncloud.android.datamodel.UploadsStorageManager.getUploads(UploadsStorageManager.java:289)
at com.owncloud.android.datamodel.UploadsStorageManager.getFailedUploads(UploadsStorageManager.java:368)
at com.owncloud.android.utils.FilesSyncHelper.restartJobsIfNeeded(FilesSyncHelper.java:201)
at com.owncloud.android.MainApp.initSyncOperations(MainApp.java:497)
at com.owncloud.android.MainApp.onCreate(MainApp.java:314)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1176)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6140)
... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: motorola
Device: surfna
Model: moto e6
Id: PCB29.73-109-6-3-6
Product: surfna_t

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: e3dff
```

### Environment data
Android version: 9

Device model: moto e6

Stock or customized system: stock

Nextcloud app version: 30110090

Nextcloud server version: 18.0.10

Reverse proxy: ?

#### Web server error log
```
-n/a-
```

#### Nextcloud log (data/nextcloud.log)
```
-n/a-
```

**Comment by tobiasKaminsky** [comment]
> disk I/O error

Means that the app cannot write onto your device.
Unfortunately this is nothing we can really handle…
