### ISSUE TITLE
PDF downlowd error

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/android#7253]
### Steps to reproduce
1. Click on a pdf
2. On some files the Error occoures
3. 

### Expected behaviour
- PDF should open 

### Actual behaviour
- crash

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.swiperefreshlayout.widget.SwipeRefreshLayout.setVisibility(int)' on a null object reference
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.populateList(FileDetailActivitiesFragment.java:415)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$null$3$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:370)
	at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$ZzLUj33qKg0e1Ki8Vd5bki8I6B4.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus7T
Model: HD1903
Id: QKQ1.190716.003
Product: OnePlus7T_EEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2010111725

**Comment by ei-ke** [comment]
I can confirm this since about a week. Workaround: Sync the file to the device, then yoi can open it from the app.
Webserver log shows nothing fancy.
Also happens for other filetypes except images.

PDF
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.swiperefreshlayout.widget.SwipeRefreshLayout.setVisibility(int)' on a null object reference
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.populateList(FileDetailActivitiesFragment.java:415)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$null$3$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:370)
	at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$ZzLUj33qKg0e1Ki8Vd5bki8I6B4.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8107)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: m51
Model: SM-M515F
Id: QP1A.190711.020
Product: m51nseea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: M515FXXU1ATI1

```
Plain text without extension (with txt extension works) 
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.swiperefreshlayout.widget.SwipeRefreshLayout.setVisibility(int)' on a null object reference
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.populateList(FileDetailActivitiesFragment.java:418)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$null$3$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:370)
	at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$ZzLUj33qKg0e1Ki8Vd5bki8I6B4.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8107)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: m51
Model: SM-M515F
Id: QP1A.190711.020
Product: m51nseea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: M515FXXU1ATI1

```
XLSX
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.swiperefreshlayout.widget.SwipeRefreshLayout.setVisibility(int)' on a null object reference
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.populateList(FileDetailActivitiesFragment.java:418)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$null$3$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:370)
	at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$ZzLUj33qKg0e1Ki8Vd5bki8I6B4.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8107)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: m51
Model: SM-M515F
Id: QP1A.190711.020
Product: m51nseea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: M515FXXU1ATI1

```
CSV
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.swiperefreshlayout.widget.SwipeRefreshLayout.setVisibility(int)' on a null object reference
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.populateList(FileDetailActivitiesFragment.java:418)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$null$3$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:370)
	at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$ZzLUj33qKg0e1Ki8Vd5bki8I6B4.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8107)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: m51
Model: SM-M515F
Id: QP1A.190711.020
Product: m51nseea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: M515FXXU1ATI1

```

**Comment by AndyScherzinger** [comment]
There is a PR with a fix and I hope we can get this in got the next release candidate.

Cc @tobiasKaminsky for PR review

**Comment by AndyScherzinger** [comment]
Duplciate of #7188
