### ISSUE TITLE
Different internal and login username cause JSONException for fetching user information

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/android#726]
### Actual behaviour
- It uses the username that was entered during login (but this is not for sure the internal username - LDAP allows to use CN, email and a nickname together with the same password to login and maps internally to a UUID as username)

In the test we used the current master of the android app and logged in via `abc@example.com` but the internal username is `abc.def` - `abc@example.com` is only allowed to be used as username for the login form.

```
03-06 16:50:43.620 20551-25186/com.nextcloud.client D/ExistenceCheckRemoteOperation: Existence check for https://www.example.com/remote.php/webdav/ targeting for  existence finished with HTTP status 200
03-06 16:50:43.621 20551-25186/com.nextcloud.client D/OwnCloudClient #3: REQUEST GET /ocs/v1.php/cloud/users/abc@example.com
03-06 16:50:45.561 20551-25186/com.nextcloud.client W/HttpMethodBase: Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
03-06 16:50:45.563 20551-25186/com.nextcloud.client D/GetRemoteUserInfoOperation: Successful response: {"ocs":{"meta":{"status":"failure","statuscode":998,"message":"The requested user could not be found"},"data":[]}}
03-06 16:50:45.564 20551-25186/com.nextcloud.client E/GetRemoteUserInfoOperation: Exception while getting OC user information
   org.json.JSONException: Value [] at data of type org.json.JSONArray cannot be converted to JSONObject
      at org.json.JSON.typeMismatch(JSON.java:100)
      at org.json.JSONObject.getJSONObject(JSONObject.java:613)
      at com.owncloud.android.lib.resources.users.GetRemoteUserInfoOperation.run(GetRemoteUserInfoOperation.java:137)
      at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136)
      at com.owncloud.android.authentication.AuthenticatorAsyncTask.doInBackground(AuthenticatorAsyncTask.java:84)
      at com.owncloud.android.authentication.AuthenticatorAsyncTask.doInBackground(AuthenticatorAsyncTask.java:41)
      at android.os.AsyncTask$2.call(AsyncTask.java:305)
      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
      at java.lang.Thread.run(Thread.java:761)
```

### Expected behaviour
- It should use the correct user name and fetch the user information for that username

Sadly I have no real access to the server and can't provide better steps. But maybe @mario @AndyScherzinger  or @tobiasKaminsky have an idea about this.

**Comment by mario** [comment]
This does not look like the current master. When did you test?

**Comment by MorrisJobke** [comment]
This evening, but I need to check, when the latest pull happened.

**Comment by mario** [comment]
@MorrisJobke news?

The app does use wrong username all around I guess, but this particular issue should be fixed already.

**Comment by aleister09** [comment]
I'm here with @MorrisJobke and I found out that the change of the android-library from 1.0.10 to 1.0.11 caused the bug https://github.com/nextcloud/android/pull/610/files#diff-c197962302397baf3a4cc36463dce5eaL43

If I change back the version of the library to 1.0.10 the error is gone.

**Comment by mario** [comment]
We are already on 1.0.13 though?

**Comment by MorrisJobke** [comment]
> We are already on 1.0.13 though?

Ah - right. Let @aleister09 fetch the latest code and try again.
