### ISSUE TITLE
App crash - "On device" menu

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#7290]
### Steps to reproduce

1. Launch the application.
2. Download a shared file in the shared directory from another user to the device.
3. Go to the "On device" menu.
4. Only delete the file locally in the directory.
5. Only remove the directory locally.

```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.swiperefreshlayout.widget.SwipeRefreshLayout.setVisibility(int)' on a null object reference
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.populateList(FileDetailActivitiesFragment.java:418)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$null$3$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:370)
	at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$ZzLUj33qKg0e1Ki8Vd5bki8I6B4.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140051
Build flavor: gplay
```

Nextcloud app version: 3.14.0 RC1

Nextcloud server version: 20.0.0

Android: 10

**Comment by AndyScherzinger** [comment]
@Valdnet this has been fixed with RC2 which should arrive on your device within the next hours :)

**Comment by Valdnet** [comment]
@AndyScherzinger I'm already installing 😉.
