### ISSUE TITLE
Video files is not playing

### ISSUE THREAD

**Issue by tadius** [nextcloud/android#7313]
I configured local Ubuntu Server and install snap NextCloud. Everything work well on web interface, but when I'm trying open videofile on Android in NextCloud app - it's not working. I have local ip with self-signed certificate.

### Steps to reproduce
1. Upload any mp4 video file
2. Try to open it with Nextcloud

### Expected behaviour
Video starts playback

### Actual behaviour
Progress bar running, then showing error

#### Nextcloud log (data/nextcloud.log)
com.nextcloud.client W/MediaPlayer: Couldn't open https://192.168.1.149/remote.php/direct/o0orqKT7QnfuCqp8ZTnzN63eDm8VRCETAikiBYY4y7fKrwY2i0UuwIxk1iee: java.io.FileNotFoundException: No content provider: https://192.168.1.149/remote.php/direct/o0orqKT7QnfuCqp8ZTnzN63eDm8VRCETAikiBYY4y7fKrwY2i0UuwIxk1iee

**Comment by tobiasKaminsky** [comment]
Can you post a bit more from logcat? 
It is strange that there is FileNotFoundException when trying to use a streamed https…

**Comment by tadius** [comment]
> Can you post a bit more from logcat?
> It is strange that there is FileNotFoundException when trying to use a streamed https…

I have connected my phone to pc and this is all logs from logcat of Android Studio

`system_process D/AudioService: Stream muted, skip playback
com.nextcloud.client D/OwnCloudClient #3: REQUEST POST /ocs/v2.php/apps/dav/api/v1/direct
com.nextcloud.client D/AdvancedSslSocketFactory: Creating SSL Socket with remote 192.168.1.149:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@412be7e
com.nextcloud.client D/AdvancedSslSocketFactory:  ... with connection timeout 5000 and socket timeout 40000
com.nextcloud.client I/ServerNameIndicator: SSLSocket implementation: com.google.android.gms.org.conscrypt.Java8FileDescriptorSocket
com.nextcloud.client I/ServerNameIndicator: SNI done, hostname: 192.168.1.149
system_process I/MediaFocusControl:  AudioFocus  requestAudioFocus() from uid/pid 10079/5603 clientId=android.media.AudioManager@42d78e1 req=1 flags=0x0
com.nextcloud.client E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
com.nextcloud.client E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
com.nextcloud.client W/MediaPlayer: Couldn't open https://192.168.1.149/remote.php/direct/o0orqKT7QnfuCqp8ZTnzN63eDm8VRCETAikiBYY4y7fKrwY2i0UuwIxk1iee: java.io.FileNotFoundException: No content provider: https://192.168.1.149/remote.php/direct/o0orqKT7QnfuCqp8ZTnzN63eDm8VRCETAikiBYY4y7fKrwY2i0UuwIxk1iee
? D/NuPlayer: onSetVideoSurface(0x4123a800, no video decoder)`

**Comment by tadius** [comment]
Additional logs:

`D/AdvancedSslSocketFactory: Creating SSL Socket with remote 192.168.1.104:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@94ff151
D/AdvancedSslSocketFactory:  ... with connection timeout 5000 and socket timeout 40000
I/ServerNameIndicator: SNI done, hostname: 192.168.1.104
W/extcloud.clien: Accessing hidden field Landroid/widget/TextView;->mCursorDrawableRes:I (greylist-max-p, reflection, denied)
W/extcloud.clien: Accessing hidden field Landroid/widget/Editor;->mSelectHandleLeft:Landroid/graphics/drawable/Drawable; (greylist-max-p, reflection, denied)
E/ThemeUtils: Error setting TextView handles color
    java.lang.NoSuchFieldException: No field mSelectHandleLeft in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes3.dex)
        at java.lang.Class.getDeclaredField(Native Method)
        at com.owncloud.android.utils.ThemeUtils.setTextViewHandlesColor(ThemeUtils.java:838)
        at com.owncloud.android.utils.ThemeUtils.setEditTextColor(ThemeUtils.java:588)
        at com.owncloud.android.utils.ThemeUtils.themeSearchView(ThemeUtils.java:601)
        at com.owncloud.android.ui.activity.FileDisplayActivity.onCreateOptionsMenu(FileDisplayActivity.java:745)
        at android.app.Activity.onCreatePanelMenu(Activity.java:4206)
        at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:324)
        at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3070)
        at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
        at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:727)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
W/extcloud.clien: Accessing hidden field Landroid/widget/TextView;->mCursorDrawableRes:I (greylist-max-p, reflection, denied)
W/extcloud.clien: Accessing hidden field Landroid/widget/Editor;->mSelectHandleLeft:Landroid/graphics/drawable/Drawable; (greylist-max-p, reflection, denied)
E/ThemeUtils: Error setting TextView handles color
    java.lang.NoSuchFieldException: No field mSelectHandleLeft in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes3.dex)
        at java.lang.Class.getDeclaredField(Native Method)
        at com.owncloud.android.utils.ThemeUtils.setTextViewHandlesColor(ThemeUtils.java:838)
        at com.owncloud.android.utils.ThemeUtils.setEditTextColor(ThemeUtils.java:588)
        at com.owncloud.android.utils.ThemeUtils.themeSearchView(ThemeUtils.java:601)
        at com.owncloud.android.ui.fragment.ExtendedListFragment.onCreateOptionsMenu(ExtendedListFragment.java:198)
        at androidx.fragment.app.Fragment.performCreateOptionsMenu(Fragment.java:2809)
        at androidx.fragment.app.FragmentManager.dispatchCreateOptionsMenu(FragmentManager.java:2684)
        at androidx.fragment.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:387)
        at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:325)
        at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3070)
        at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
        at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:727)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/MediaFocusControl: requestAudioFocus() from uid/pid 10152/29938 clientId=android.media.AudioManager@8eb8166 callingPack=com.nextcloud.client req=1 flags=0x0 sdk=29
D/NuPlayerDriver: NuPlayerDriver(0xf2441960) created, clientPid(29938)
D/SurfaceUtils: connecting to surface 0xeb5c0018, reason setVideoSurfaceTexture
D/NuPlayer: onSetVideoSurface(0xeb5c3270, no video decoder)
E/NuCachedSource2: source returned error -1, 10 retries left
E/NuCachedSource2: source returned error -1, 9 retries left
I/PeriodicStatsRunner: PeriodicStatsRunner.call():180 call()
I/PeriodicStatsRunner: PeriodicStatsRunner.call():184 No submit PeriodicStats since input started.
D/BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.mdisync.service.START pkg=com.google.android.gms cmp=com.google.android.gms/.chimera.GmsApiService }
E/NuCachedSource2: source returned error -1, 8 retries left
E/NuCachedSource2: source returned error -1, 7 retries left
E/netmgr: qemu_pipe_open_ns:62: Could not connect to the 'pipe:qemud:network' service: Invalid argument
E/netmgr: Failed to open QEMU pipe 'qemud:network': Invalid argument
E/NuCachedSource2: source returned error -1, 6 retries left
E/wifi_forwarder: qemu_pipe_open_ns:62: Could not connect to the 'pipe:qemud:wififorward' service: Invalid argument
E/wifi_forwarder: RemoteConnection failed to initialize: RemoteConnection failed to open pipe
E/NuCachedSource2: source returned error -1, 5 retries left
E/ClipboardService: Denying clipboard access to com.huawei.hwid, application is not in focus nor is it a system service for user 0
I/Finsky: [1026] nys.run(3): Stats for Executor: BlockingExecutor oay@437f828[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 45]
I/Finsky: [1026] nys.run(3): Stats for Executor: LightweightExecutor oay@610941[Running, pool size = 3, active threads = 0, queued tasks = 0, completed tasks = 98]
I/Finsky: [1026] nys.run(3): Stats for Executor: bgExecutor oay@368eee6[Running, pool size = 4, active threads = 0, queued tasks = 0, completed tasks = 176]
E/NuCachedSource2: source returned error -1, 4 retries left
E/NuCachedSource2: source returned error -1, 3 retries left
E/NuCachedSource2: source returned error -1, 2 retries left
E/NuCachedSource2: source returned error -1, 1 retries left
E/NuCachedSource2: source returned error -1, 0 retries left
E/GenericSource: initFromDataSource, cannot create extractor!
E/GenericSource: Failed to init from data source!
E/MediaPlayerNative: error (1, -2147483648)
E/MediaPlayer: Error (1,-2147483648)
D/VideoView: Error: 1,-2147483648
E/PreviewMediaFragment: Error in video playback, what = 1, extra = -2147483648`

**Comment by tadius** [comment]
It works fine on demo2.nextcloud.com (Nextcloud intro.mp4).
Maybe it depends on server side?
I tried both http and https with self-signed certificate.
Maybe there are some preference which I should enable/disable?

**Comment by tadius** [comment]
I tried to use Iphone and video plays pretty well. So the problem is not on server side but on Android side.
Please, take a look at this problem.

**Comment by toAtulArora** [comment]
> I tried to use Iphone and video plays pretty well. So the problem is not on server side but on Android side.
> Please, take a look at this problem.

I have exactly the same problem. I setup a self signed server using snap on Ubuntu and everything works well except for streaming (both audio and video) on Android while on iPhone both work fine.

I don't know if it helps but for me, on android, sometimes it fails to download even not so large files (over 30 MBs) but works perfectly on iPhone. Strangely enough, if (on android again) I'm on the same local network as the server (using a VPN connection say) then it downloads the file just fine. It still won't stream though. I'm sorry if this is superfluous.

Regardless, thanks for this amazing software! Great work.

**Comment by tadius** [comment]
Still actual

**Comment by tobiasKaminsky** [comment]
I suspect that you can view video when you download it beforehand, right?

**Comment by tadius** [comment]
> I suspect that you can view video when you download it beforehand, right?

Yes, if I download video manually by long click on file - it plays well. So online stream doesn't work correctly.

**Comment by tobiasKaminsky** [comment]
Then let us track it in #4204 and / or #3061 and / or #3601
