### ISSUE TITLE
Crash when file is above certain size, and its encrypted with E2E.

### ISSUE THREAD

**Issue by sysoppl** [nextcloud/android#7317]
### Steps to reproduce
1. Upload files to E2E folder
2. Download file above ~100MB via Andorid app
3. App crashes

### Expected behaviour
- File should decrypt and run

### Actual behaviour
- File is downloading well, until it reaches 100%, then app crashes. This error does not occur with smaller files.
Tested with few files:

Folder 1 (encrypted with e2e):
67 MB - ok
53 MB - ok
151 MB - crash
204 MB - crash

Folder 2 (encrypted with e2e):
108 MB - ok
97 MB - ok
151 MB (same file as in folder 1) - crash

Folder 3 (not encrypted)
193 MB - ok

Everything is up to date. This error occures only for bigger files that are e2e encrypted.

### Environment data
Android version: 9

Device model: LG G6

Stock or customized system: Stock

Nextcloud app version: 3.13.1

Nextcloud server version: 20.0.1

Reverse proxy:

#### Web server error log
```
No errors occured
```

#### Nextcloud log (data/nextcloud.log)
```
No errors occured
```

#### Android crash log
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.lib.common.operations.RemoteOperationResult.isCancelled()' on a null object reference
	at com.owncloud.android.files.services.FileDownloader.notifyDownloadResult(FileDownloader.java:609)
	at com.owncloud.android.files.services.FileDownloader.downloadFile(FileDownloader.java:478)
	at com.owncloud.android.files.services.FileDownloader.access$500(FileDownloader.java:81)
	at com.owncloud.android.files.services.FileDownloader$ServiceHandler.handleMessage(FileDownloader.java:415)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:205)
	at android.os.HandlerThread.run(HandlerThread.java:65)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: lge
Device: lucye
Model: LG-H870
Id: PKQ1.190522.001
Product: lucye_global_com

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 1930916292597

```

**Comment by tobiasKaminsky** [comment]
Do you try to download those all at once, e.g. folder sync?
Or really click only on download this one big file?

**Comment by sysoppl** [comment]
I was trying to download them one by one. Now I tried folder sync and the issue still occur with same log

**Comment by LucaVignati** [comment]
I just had the same problem.
Files under 100MB download and sync just fine. Files above 100MB crash the app when they reach 100%.

If fingerprint authentication is enabled, the app enters an endless loop of fingerprint authentication requests instead of crashing.

This is my log:
************ CAUSE OF ERROR ************

java.lang.OutOfMemoryError: Failed to allocate a 107019248 byte allocation with 25165824 free bytes and 80MB until OOM, target footprint 141630504, growth limit 201326592
	at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:1208)
	at javax.crypto.Cipher.doFinal(Cipher.java:2055)
	at com.owncloud.android.utils.EncryptionUtils.decryptFile(EncryptionUtils.java:357)
	at com.owncloud.android.operations.DownloadFileOperation.run(DownloadFileOperation.java:201)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:187)
	at com.owncloud.android.files.services.FileDownloader.downloadFile(FileDownloader.java:475)
	at com.owncloud.android.files.services.FileDownloader.access$500(FileDownloader.java:87)
	at com.owncloud.android.files.services.FileDownloader$ServiceHandler.handleMessage(FileDownloader.java:422)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.os.HandlerThread.run(HandlerThread.java:67)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30190190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: taimen
Model: Pixel 2 XL
Id: RP1A.201005.004.A1
Product: taimen

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 6934943
 

**Environment data**
Android version: 11

Device model: Google Pixel 2XL

Stock or customized system: Stock

Nextcloud app version: 3.19.1

Nextcloud server version: 23.0.3

Reverse proxy: Nginx Proxy Manager
