### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Bianca339** [nextcloud/android#7321]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to resume activity {com.nextcloud.client/com.blikoon.qrcodescanner.QrCodeActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=Intent { dat=content://com.google.android.apps.photos.contentprovider/3/1/content://media/external/images/media/20709/ORIGINAL/NONE/image/jpeg/1250864098 flg=0x1 clip={text/uri-list U:content://com.google.android.apps.photos.contentprovider/3/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F20709/ORIGINAL/NONE/image%2Fjpeg/1250864098} }} to activity {com.nextcloud.client/com.blikoon.qrcodescanner.QrCodeActivity}: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=18383, uid=10249 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3790)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3830)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3038)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=Intent { dat=content://com.google.android.apps.photos.contentprovider/3/1/content://media/external/images/media/20709/ORIGINAL/NONE/image/jpeg/1250864098 flg=0x1 clip={text/uri-list U:content://com.google.android.apps.photos.contentprovider/3/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F20709/ORIGINAL/NONE/image%2Fjpeg/1250864098} }} to activity {com.nextcloud.client/com.blikoon.qrcodescanner.QrCodeActivity}: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=18383, uid=10249 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4491)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3762)
	... 10 more
Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=18383, uid=10249 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
	at android.os.Parcel.readException(Parcel.java:1967)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
	at android.content.ContentResolver.query(ContentResolver.java:760)
	at android.content.ContentResolver.query(ContentResolver.java:710)
	at android.content.ContentResolver.query(ContentResolver.java:668)
	at com.blikoon.qrcodescanner.QrCodeActivity.getPathFromUri(QrCodeActivity.java:386)
	at com.blikoon.qrcodescanner.QrCodeActivity.onActivityResult(QrCodeActivity.java:370)
	at android.app.Activity.dispatchActivityResult(Activity.java:7599)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4487)
	... 11 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a5y17lte
Model: SM-A520F
Id: R16NW
Product: a5y17ltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: A520FXXUGCTI9

### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by aqaqsubin** [comment]
Did you not grant permission to read external storage?

**Comment by GreifswalderNet** [comment]
All permissions allowed.
Since version 3.14.0 these errors.
Many users have also reported here.
Your version 3.14.1 RC1 also has bugs.
Cloud is a matter of trust ...

**Comment by tobiasKaminsky** [comment]
@GreifswalderNet what device do you have? And which Android version?

**Comment by GreifswalderNet** [comment]
Samsung Galaxy S10e
Android-Version 10

**Comment by tobiasKaminsky** [comment]
Hm. It might be that the QR scanning app stores the image on wrong place (external storage) and thus cannot open it.

Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat
