### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by KwonEunKyung** [nextcloud/android#7341]
### Steps to reproduce
1.  upload file
2.  refresh

### Expected behaviour

Refresh :)

### Actual behaviour

I just uploaded and tried to refresh, but there was an unexpected error.

### Environment data
Android version: 8.0 

Device model: Samsung Galaxy S7 edge

Stock or customized system:

Nextcloud app version: 3.13.1

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionOCFileListItemViewHolder{bd58904 position=21 id=-1, oldPos=-1, pLpos:-1 no parent} com.owncloud.android.ui.EmptyRecyclerView{9596e21 VFED..... .F...... 0,0-1080,1035 #7f0901c2 app:id/list_root}, adapter:com.owncloud.android.ui.adapter.OCFileListAdapter@9282246, layout:androidx.recyclerview.widget.LinearLayoutManager@8ac1c07, context:com.owncloud.android.ui.activity.FileDisplayActivity@1bdf7d0
	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5974)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6158)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: hero2ltektt
Model: SM-G935K
Id: R16NW
Product: hero2ltektt

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: G935KKKU3ETJ1

```

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Does this happen reliable?
