### ISSUE TITLE
Crash on playing videos

### ISSUE THREAD

**Issue by suggested-username** [nextcloud/android#7364]
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{473d5fc u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2174)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: realme
Device: RMX2086L1
Model: RMX2086
Id: QKQ1.191021.002
Product: RMX2086T2

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 1600779907

**Comment by tobiasKaminsky** [comment]
This will be fixed with #7340 and then will be in 3.14.1.
It is also a duplicate, therefore closing.
