### ISSUE TITLE
Autoupload causes Nextcloud app to freeze and not respond after crashing is fixed

### ISSUE THREAD

**Issue by InfamousUser** [nextcloud/android#7378]
### Steps to reproduce
1. Have QA version of Nextcloud from https://github.com/nextcloud/android/pull/7340
2. Have a lot of uploads set to be auto uploaded
3. Wait

### Expected behaviour
File should get uploaded normally

### Actual behaviour
Files get uploaded and the app constantly gets ANR dialogues and freezes the Android system interface half the time.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 11

Device model: Google Pixel 2

Stock or customized system: stock

Nextcloud app version: 3.15.0

Nextcloud server version: 19.0.4

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Logcat logs (I think): [Nextcloud.txt](https://github.com/nextcloud/android/files/5567880/Nextcloud.txt)
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Do you see where and when it hangs? Can you give us a screenshot?

**Comment by InfamousUser** [comment]
I think it hangs when it attempts to autoupload. I don't need to be in the app, I can be in another app and I get the ANR dialogue. Otherwise I simply go to uploads menu and it freezes there if it's autouploading, if it isn't autouploading, then it might work normally.

When it says "App terminated" under the uploads, if I press  "Failed/pending restart", it freezes, the Android interface freezes as well for 20~ seconds and then it displays ANR.

Nothing out of ordinary to screenshot; all looks normal, but when it starts to autoupload it's as if it gets overloaded and everything freezes while it processes.

**Comment by tobiasKaminsky** [comment]
> When it says "App terminated" under the uploads, if I press "Failed/pending restart", it freezes, the Android interface freezes as well for 20~ seconds and then it displays ANR.

That is an important point, thanks!

**Comment by tobiasKaminsky** [comment]
How many failed items do you have?

**Comment by InfamousUser** [comment]
> > When it says "App terminated" under the uploads, if I press "Failed/pending restart", it freezes, the Android interface freezes as well for 20~ seconds and then it displays ANR.
> 
> That is an important point, thanks!
Oh?

> How many failed items do you have?
37862

**Comment by tobiasKaminsky** [comment]
Failed/pending only reloads stored items from database and displays them.
If you have >30k items this just takes too long.
So this is somehow unrelated to AutoUpload, it just occurs due to the uploading of all old images.

You could trigger this also manually, when uploading 30k images.

**Comment by InfamousUser** [comment]
> So this is somehow unrelated to AutoUpload, it just occurs due to the uploading of all old images.

That's what I thought, but then again I don't know much about programming so...
This happened without adding upload existing files before though, I even reported a bug a while ago because Nextcloud was never uploading my stuff, only to realize it was never designed to do so when it was added as a feature and it never said it wouldn't. So this must have existed before that.

**Comment by bardo** [comment]
I had a similar issue when I enabled auto-upload on a folder with a few thousand pictures on a Pixel 3a. The app kept freezing and crashing, and after every restart it would start again from the beginning without looking for already synchronized files. I disabled power saving for the app as indicated in the manual, but it did not help, it was not able to run in the background. Power consumption was also extremely high while uploading.

As a workaround I forced the screen to stay on by enabling developer mode on Android and activating the corresponding option (you can also install [Coffee](https://f-droid.org/en/packages/com.github.muellerma.coffee/) for the same result), connected the phone to a USB cable, and let it synchronize with the app open. It took a long time but it worked.

Clearly, this isn't a good workaround for a non-technical user, but it can get the job done.

**Comment by InfamousUser** [comment]
Right, I think I did that one time with uploads menu open, if I didn't touch the app it wouldn't crash, but as soon as I tried scrolling or moving around it would hang, trying it multiple times caused a crash or non responsiveness dialogue iirc.

**Comment by InfamousUser** [comment]
Here is log for 3.14.1 freeze and crash in case it helps any. I scroll the upload menu slowly, it works for a couple of seconds, then around 15:19:40 it freezes for about 3-5 seconds, then automatically reopens with loading screen and whole Android is frozen for half a minute (system buttons on the botton don't work), then it unlocks and I get ANR dialogue.

[Log_2020-12-05_15-21-30.txt](https://github.com/nextcloud/android/files/5647201/Log_2020-12-05_15-21-30.txt)

**Comment by tobiasKaminsky** [comment]
Judging from logcat, thanks for that, it seems indeed that the app uses too much memory and therefore Android tries to kill it.
Maybe Pixel 2 is more restrictive…

**Comment by InfamousUser** [comment]
If it helps, in Android memory usage it says it uses an average of 26 MB and 156 MB maximum, if that's accurate.
It should be able to use almost all RAM in foreground. I mean, I'm sure modern games take at least 1-2+ GB when running. There must be something specific that's tripping it up.

**Comment by tobiasKaminsky** [comment]
Maybe the implementation of listing those files is sup-optimal and thus creates to much memory…

**Comment by InfamousUser** [comment]
Must be, it's been created that way. Since I've first seen it there was stuff wrong with autoupload, first it wouldn't upload, haven't been relying on it for years, or since introduction, then gave it another shot and it's been having these crashes/freezes for a year or two, at least it uploads stuff now. My previous phone failed around that time and didn't have anything backed up, lost all that was on it, the flash chip or bootloader failed for some reason.

I'd love to be able to use it reliably, as would the rest of the community I'm sure. Especially as an enterprise option. I don't understand how so many problems with one thing.

If you need any further data to get this fixed I'm available.

**Comment by oxc** [comment]
Is there any further information required at this point?

**Comment by InfamousUser** [comment]
Inb4 issue gets closed for no reason.

**Comment by InfamousUser** [comment]
I don't know how to stop the bot from closing this. Convensional means of saying something doesn't work.

**Comment by tobiasKaminsky** [comment]
Is this only ANR (app not responding) when you want to list/refresh failed uploads?
Or also if you click on restart failed uploads and then suspend app in background?

**Comment by InfamousUser** [comment]
Happens by itself in the background when I'm minding my own business (I assume when it autouploads), it happens if I restart failed uploads, it happens if I just open the uploads menu and look or scroll. Also perhaps important is that when I freshly open the app and go to uploads, it will upload a random small number of files (lets say 3) and then it will freeze and then start not responding/stop responding.

**Comment by tobiasKaminsky** [comment]
Do you still have those 32.000 failed uploads?

**Comment by InfamousUser** [comment]
20k now.

**Comment by InfamousUser** [comment]
I will try reinstalling the app, deleting the data on server and resyncing everything from scratch.

**Comment by InfamousUser** [comment]
aaaaaaaaaaaa

**Comment by InfamousUser** [comment]
Damn bot.

**Comment by InfamousUser** [comment]
Original problems again. I have reinstalled the app, updated the server to the latest version, readded the autoupload, waited a few days, nothing got uploaded yet.

**Comment by InfamousUser** [comment]
App will not autoupload at all anymore. Opening a new issue for that first before this can progress.

**Comment by gomme600** [comment]
Having the same problem. Just opening the app is enough to crash it 90% of the time if a lot of uploads are waiting.

**Comment by gomme600** [comment]
Can someone open this issue again please and stop the bot closing it?

**Comment by gomme600** [comment]
Thanks

**Comment by tobiasKaminsky** [comment]
> Having the same problem. Just opening the app is enough to crash it 90% of the time if a lot of uploads are waiting.

How many uploads do you have?

**Comment by gomme600** [comment]
Over 2000

**Comment by mauritsderuiter95** [comment]
I also have this issue for months now. I'm trying to move from Google Photos, but I have a lot of images. App keeps crashing. Once in a while I open the app again to try again, but it's just not usable this way.

Is the solution for now just keeping the app open and hitting "wait" every time the pop-up shows up telling me the app is not responding?

**Comment by InfamousUser** [comment]
Brilliant.

**Comment by bardo** [comment]
Still happening, and getting worse.

After upgrading to Android 11, some apps changed their data directory due to [scoped storage](https://developer.android.com/about/versions/11/privacy/storage), forcing me to reconfigure the auto-upload for, e.g., chat app media. Most of the media is already synchronized, but the grand total is >5000 images.

This generated a lot of file conflicts and app crashes, so in some way I managed to disabled the synchronization and set the option to ignore the upload in case of file conflicts. I restarted the app, and now I can't access the auto-upload folder selection screen anymore. I get a blank screen and after a while Android proposes me to kill the app or wait. Waiting does not help.

I am under the impression that the whole auto-upload strategy needs to be re-evaluated to at least avoid blocking the app.

**Comment by b-pfl** [comment]
> Still happening, and getting worse.

> I am under the impression that the whole auto-upload strategy needs to be re-evaluated to at least avoid blocking the app.

I totally agree. 

To add to this issue, I'd like to add observations from my current case:
I am using the NC Android client on a Samsung Galaxy S9 and use the auto-upload to synchronize my images.
Those images (~10500) are stored on an SD card and I tried syncing them ever since Owncloud / Nextcloud clients supported this.

It seems that there are multiple issue related to the auto-upload feature, which I just discovered when I had to re-install the NC client on my phone after repair.
- Syncing a large amount of (existing) files seems to freeze the app and not respond properly
- Even though Sync was switched on permanently (including the "include existing files" option since its existence), not all files have been uploaded. I did not find any common pattern yet regarding which files were uploaded
- There is no proper conflict mitigation happening in case of existing files (see also https://github.com/nextcloud/android/issues/6911#issuecomment-900694464_): identical files (create date, size, checksum) should just be skipped, for the rest either the default option (overwrite, skip) should be performed or explicit user interaction is required.
- In many cases of a conflict, the Android notification shows a conflict but when tapping on it, the conflict message cannot be regenerated.

**Comment by b-pfl** [comment]
Btw, this seems to be related to https://github.com/nextcloud/android/issues/5998?

**Comment by InfamousUser** [comment]
Lots of files is definitely related, but this is only a compounding issue.

**Comment by InfamousUser** [comment]
This bug report did not receive an update in the last 4 weeks. Please take a look again and see if the issue is solved, otherwise it makes no sense to close the issue. Thank you!

**Comment by ajclements** [comment]
I just encountered this today. Fresh install of server, version 22.0.0. Android 11, security update August 5; running on Pixel 4. App version 3.17.0.

**Comment by m1435** [comment]
I can confirm this issue. I can't even open the Autoupload Settings as it already causes the app to crash. Have retried installing the app - didn't help.

Device: Oneplus 5T, Android 11/Lineage 18.1
App version 3.17.1
Server version 22.1.1.2

**Comment by calderonth** [comment]
Also seeing this issue.
Opening the Auto-upload dialog hangs, dialog shows the app is hanging, forcing it to wait sometimes do brings the dialog up but unreliable and very slow.

**Comment by AlvaroBrey** [comment]
@m1435 @calderonth Although likely caused by similar reasons, your issues are different from the original. The original was about ANRs when uploading tons of files at the same time, not when opening the Autoupload settings. Please open a separate issue for that.

**Comment by Robinatus** [comment]
Encountered the same issue today with a large folder (> 10k files) on a Pixel 5 with Android 12 and the newest app version. The app keeps freezing when I open the "Auto Upload" Settings and does not upload a single file from the respective folder. 
Guess I have to reinstall the app 😅

**Comment by noci2012** [comment]
On a new phone, enabling backup causes a crash and subsequent failure of the app to respond to anything.

**Comment by LucImmerzeel** [comment]
After reinstalling the app it worked normal when I didn't hide the default Auto upload's. I just didn't enable and didn't hide them.
This worked for me. Maybe it works for someone else.

**Comment by noci2012** [comment]
The issue i noticed with backup was on a new phone ==> a fresh install.
Diabling backup made the problems disappear.
Phone is a FairPhone4, running Android 11

**Comment by fuenfundachtzig** [comment]
Same problem here, after hiding all automatically added "auto uploads" (11 folders in total; I would love to remove them rather than hiding them) I get a "app not responding" screen whenever I open the auto-upload menu item. If I select "wait" it will eventually show up after a minute or so.

**Comment by icecore2** [comment]
Same issue here with 6k files and seems like around 5.5k duplicates.
it hang right after the startup logo

**Comment by EvilOlaf** [comment]
Seems like still an issue...

**Comment by AHermann94** [comment]
Wtf?! How can a primary feature of the app be so broken? I also have the bug. It makes the App unuseable! (And by extension, the whole service!)
"I'm sorry, but if you've actually decided to back up enough data that it's worth to back up, our app will crash and freeze and you won't be able to use it" genius!

**Comment by InfamousUser** [comment]
This has been an issue for years, it is nowhere near a priority it seems.

**Comment by munsuri** [comment]
Having the same issue, and currently there are other open bugs with this exact issue. #9407 or #9757 to refer a few... it can't be hard to fix, can it? Did anyone (from Nextcloud or not) start to take a look at the code by any chance?

**Comment by Dsw77** [comment]
It is still not fixed. Nexcloud app is currently crashing my phone. It's non responding, then after a few minutes the phone crashes and reboots.

**Comment by EvilOlaf** [comment]
Auto upload itself works. It seems it runs into trouble when there is a lot of stuff to upload. After a few dozen crashes everything was uploaded and now running fine.

**Comment by InfamousUser** [comment]
For you, for me it doesn't even work at all anymore.

**Comment by Sieboldianus** [comment]
Auto upload still works for me. I have several folder set up for auto upload. The thing is, when I open the "auto upload" page (e.g. to add a new folder), the app is stuck with "loading" for very long time (like 20 Minutes). This is on a not so old Pixel 3A. So maybe this could be an issue of how this page is set up. There's no need to display contents for auto-upload folders in there, simply give me a list of folder to add checkmarks. I don't need to see image previews.

**Comment by stoically** [comment]
Maybe related: https://github.com/nextcloud/android/issues/10572

**Comment by hakong** [comment]
Happens here too.

App is:
- stuck in a loop
- crashes when uploading
- refuses to upload when not charging ("Awaiting charge") even though both folders configured in Auto Upload do NOT have "Only upload when charging" checked.

This is unacceptable experience for someone wanting to move from a service like Dropbox or Google Photos. How is this issue 2 years old and not solved? I can log into Google Photos or Dropbox on a new account with thousands of photos on the phone and it will _just upload_. **Worry-free, comfortable user experience.**

With Nextcloud, it's a constant struggle. Restarting the app, clearing the cache, re-installing the app, re-starting the upload process, enabling/disabling settings hoping that it'll complete at least one round of uploads.

This feature is broken and should at the very least be marked as BETA.

**Comment by stoically** [comment]
@hakong While I do understand your frustration, you should keep the following in mind: If Google (or any of its automated scans) declare your account as suspicious and close it, your done – good luck contacting them. With self-hosted cloud you keep control. Also, it being that problematic is a recent issue, see here: https://github.com/nextcloud/android/issues/10993

**Comment by AHermann94** [comment]
@stoically with nextcloud, if my NAS burns down, nothing happens, because I couldn't f*cking upload anything!

**Comment by stoically** [comment]
@AHermann94 Google being very thorough in terms of backups doesn't help you if your account is closed.

**Comment by AHermann94** [comment]
@stoically yeah, you're right, I shouldn't use google on the off-chance that they decide to ban me for nothing, I should instead use this rock that lies in front of my house for my backup. It's not a storage medium, or electric in any way, but just as useful nextcloud for my phone backup!

**Comment by stoically** [comment]
@AHermann94 A NAS burning down sounds like an off-chance to me as well. In the end one has to weigh up the pro and cons for their personal situation and make a decision. It's obviously totally up to you – tho, I don't understand why we discuss this in the nextcloud server repository.

**Comment by AHermann94** [comment]
@stoically are you dense or are you intentionally ignoring the issue here?! 
NEXTCLOUD DOES IS NOT ABLE TO DO ANYTHING FOR US EXCEPT FOR CRASHING OUR PHONES!!!!

it doesn't do a backup, it doesn't sync our files. It's completely useless. There are no pros and cons. Does that enter your brain? Does this information compute?

**Comment by stoically** [comment]
@AHermann94 No reason to get rude.

@munsuri / @AHermann94 It worked for me for years. I'm sorry if it doesn't work for you at all.

**Comment by AHermann94** [comment]
@stoically sorry, but I got rude after you missed obvious sarcasm and whole sentences in several messages and sent us issue references which do not apply to our problem. You also seem to have missed that this thread is two years old and described this as a "new" problem.

**Comment by stoically** [comment]
@AHermann94 No worries. The issues are related: It was an issue in the past, but it got worse recently. That's what I was trying to say by referencing https://github.com/nextcloud/android/issues/10993.

Btw: Maybe technical issues in source repositories are not the place to get sarcastic. Staying on topic helps generally.

**Comment by InfamousUser** [comment]
Repeating this for the 10th or so time. The problem with autoupload existed since it was added, it's been going on for years. Nobody is fixing it. There were finally attempts and some fixes a while ago, but this just resolved some symptoms, the feature as whole doesn't work (for some people) and is unstable.

**Comment by EvilOlaf** [comment]
I "worked around" this issue by frequently killing the app once it did not respond anymore until everything was uploaded. Once that big initial chunk was done everything worked smoothly from that point. Obviously not ideal though.

**Comment by InfamousUser** [comment]
Not only not ideal, but not a solution at all, just a workaround.

**Comment by AHermann94** [comment]
I tried to do that but gave up after ~36h and about 1GB of data on the NAS.

**Comment by EvilOlaf** [comment]
> Not only not ideal, but not a solution at all, just a workaround. Not worth commenting about, this needs to be solved, not found workarounds for by people for years.

Yep, just a poor workaround. But well, what do you want to do? If an issue report does not get attention after a while people will start to tinker on their own to find solutions and "solutions" :grin: 



> I tried to do that but gave up after ~36h and about 1GB of data on the NAS.

Hm that is quite low...guess it depends on the phone.

**Comment by victordariovera** [comment]
I have a thing to say. Nextcloud app completely hangs in a Samsung Galaxy S52 with 6gb of RAM. BUT, I switched to a brand new Samsung Galaxy S22 Ultra with 16gb of RAM and Nextcloud app works awesome. I think its an optimization issue.

**Comment by yeupou** [comment]
I suffer this problem since about a month.  It was working finely for years.

I tried many versions of the android app, assuming something changed recently. I also tested by reducing the amount of files on the phone. It still hangs when configuring a simple 7 pictures folder.

The lack of autoupload really decrease the usability and usefullness of the app.

And the issue handling is a mess: app unresponsive, using CPU and eating battery. As if there was a loop or something. Is there any plan regarding this opened 2 years ago?

**Comment by stoically** [comment]
@yeupou My workaround is pinning to an older version: Deinstall Nextcloud App fully. Now install version 3.22.2 via apk (https://github.com/nextcloud/android/releases/tag/stable-3.22.2), disable auto updating of the app (play store -> manage apps -> open nextcloud app infos -> three dots top right -> untick "enable auto-update" checkbox) and now log into the app and configure auto-uploading accordingly.

**Comment by Regis-Frollo** [comment]
Same here:
### Cause of error
```java
Exception in thread "Thread-8" java.lang.OutOfMemoryError: Failed to allocate a 160 byte allocation with 1001976 free bytes and 978KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
    at com.android.org.conscrypt.NativeCrypto.X509_get_subject_name(Native Method)
    at com.android.org.conscrypt.OpenSSLX509Certificate.getSubjectX500Principal(OpenSSLX509Certificate.java:501)
    at okhttp3.internal.tls.BasicTrustRootIndex.<init>(BasicTrustRootIndex.kt:28)
    at okhttp3.internal.platform.Platform.buildTrustRootIndex(Platform.kt:163)
    at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Platform.kt:160)
    at okhttp3.internal.platform.Android10Platform.buildCertificateChainCleaner(Android10Platform.kt:82)
    at okhttp3.internal.tls.CertificateChainCleaner$Companion.get(CertificateChainCleaner.kt:42)
    at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.kt:870)
    at com.nextcloud.common.PlainClient$Companion.createDefaultClient(PlainClient.kt:62)
    at com.nextcloud.common.PlainClient$Companion.access$createDefaultClient(PlainClient.kt:47)
    at com.nextcloud.common.PlainClient.<init>(PlainClient.kt:45)
    at com.nextcloud.client.network.ClientFactoryImpl.createPlainClient(ClientFactoryImpl.java:94)
    at com.nextcloud.client.network.ConnectivityServiceImpl.isInternetWalled(ConnectivityServiceImpl.java:79)
    at com.owncloud.android.files.services.FileUploader.retryFailedUploads(FileUploader.java:1067)
    at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:240)
    at com.owncloud.android.utils.FilesSyncHelper$$ExternalSyntheticLambda0.run(Unknown Source:10)
    at java.lang.Thread.run(Thread.java:920)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30220290`
* Build flavor: `generic`

### Device information
* Brand: `samsung`
* Device: `beyond2`
* Model: `SM-G975F`
* Id: `SP1A.210812.016`
* Product: `beyond2lteeea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `G975FXXUGHVJ5`

**Comment by chris246** [comment]
For me the app is just completely unusable and often hangs directly after opening it when it is showing the files list.
Auto Upload is enabled, a few files are queued for upload but the phone is not plugged in.

As mentioned before, killing the app multiple times via Android Settings usually resolves it, but this is not how it should work.

**Comment by GownerCode** [comment]
It is now May 2024, the original issue is almost 4 years old and the issue persists still. Phones with limited RAM like my Pixel 4a are still not able to handle uploading more than a few hundred pictures at once with auto-upload. I have 2600 pictures in the whatsapp folder. If I add it to auto-upload, it will queue up up to 2000 of them. Then they all instantly fail with the message "App terminated", it instantly starts collecting them all again until it reaches that mark, they all fail and so on. With each go, you're lucky to upload 3-4 pictures.

I can definitely understand some people's frustration here. Why is this issue still open after 4 years?

**Comment by ripper17** [comment]
Got the same issue with about 2500 pictures. The worst thing is, that some of those pictures are conflicting and I can't resolve the conflict and will be getting the "conflict" message constantly. Trying to open the conflict resolution just gives my a "App is not responding: Wait / Terminate App" message after a couple of seconds and I don't know how to resolve this other than probably deleting the files on the server manually...

**Comment by calderonth** [comment]
I personally switched to Immich and haven't looked back. Everything works
so much better to backup pictures.

**Comment by mvorisek** [comment]
I am affected as well. I have about 1400 photos to upload and the upload freezes every about 100, 200 photos. Around 1000 photos uploaded after 10 hours with many phone restarts.

I have 4 GB of phone RAM with about 1.5 GB free, so in my case, the limitation is not caused by RAM.

My line is broadband, so the data rate is not limiting neither.

It seems the upload code needs to be revisited as it seems it is very CPU hungry. Maybe some n^2 complexity, IDK.

I would be grateful if someone with Android experience can investigate the upload with some massive folders. The app should handle 100k files upload without any major freezing.
