### ISSUE TITLE
ViewGroup.dispatchCollectViewAttributes NPE

### ISSUE THREAD

**Issue by IvanAldrich** [nextcloud/android#738]
Running monkey i got this crash, it appeared that mChildren[i] null which is supposed never happened. Or is there any posibility cause that?

### Logs
java.lang.NullPointerException
at android.view.ViewGroup.dispatchCollectViewAttributes(ViewGroup.java:1112)
at android.view.ViewGroup.dispatchCollectViewAttributes(ViewGroup.java:1112)
at android.view.ViewGroup.dispatchCollectViewAttributes(ViewGroup.java:1112)
at android.view.ViewGroup.dispatchCollectViewAttributes(ViewGroup.java:1112)
at android.view.ViewGroup.dispatchCollectViewAttributes(ViewGroup.java:1112)
at android.view.ViewGroup.dispatchCollectViewAttributes(ViewGroup.java:1112)
at android.view.ViewGroup.dispatchCollectViewAttributes(ViewGroup.java:1112)
at android.view.ViewGroup.dispatchCollectViewAttributes(ViewGroup.java:1112)
at android.view.ViewRootImpl.collectViewAttributes(ViewRootImpl.java:1038)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1304)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1005)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5609)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
at android.view.Choreographer.doCallbacks(Choreographer.java:574)
at android.view.Choreographer.doFrame(Choreographer.java:544)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5001)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:736)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:570)
at dalvik.system.NativeStart.main(Native Method)

### Logs
java.lang.NullPointerException
    at android.view.ViewGroup.canViewReceivePointerEvents(ViewGroup.java:2140)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1903)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2105)
    at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1531)
    at android.app.Activity.dispatchTouchEvent(Activity.java:2531)

### Logs
java.lang.NullPointerException
    at android.view.ViewGroup.dispatchVisibilityChanged(ViewGroup.java:1064)
    at android.view.View.setFlags(View.java:8956)
    at android.view.View.setVisibility(View.java:6027)

**Comment by tobiasKaminsky** [comment]
Can you give us some more infos how you have triggered this crash?

**Comment by IvanAldrich** [comment]
sorry i just got this crash when doing monkey test and have no idea how to reproduce it. but i got several similar crash which refers that mChildrea[i] occurred to be null

**Comment by IvanAldrich** [comment]
@tobiasKaminsky I submit two logs which seems to have the same cause with the original one, hope it help

**Comment by tobiasKaminsky** [comment]
Sorry for coming back so late.
Thank you for your logs, but they do not contain any app specific output, so I cannot see how and where this crashes.
Therefore I am closing it. 
If you experience this again, please reopen with steps to reproduce.

**Comment by IvanAldrich** [comment]
@tobiasKaminsky I found that when I try to removeView or setLayoutParam when doing animation, this error may occur. Similar issue: https://stackoverflow.com/questions/5569267/nullpointerexception-that-doesnt-point-to-any-line-in-my-code.  I consider it as a bug of the system, right?

**Comment by tobiasKaminsky** [comment]
Unfortunately I guess so :/
