### ISSUE TITLE
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/android#7389]
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{55f3bab u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1946)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7403)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: xiaomi
Device: jasmine_sprout
Model: Mi A2
Id: QKQ1.190910.002
Product: jasmine

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V11.0.12.0.QDIMIXM

**Comment by tobiasKaminsky** [comment]
Will be fixed with #7340
