### ISSUE TITLE
Consistant crash on playing video

### ISSUE THREAD

**Issue by lleibovici** [nextcloud/android#7396]
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{27d04cb u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2126)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWCMR09
Model: CMR-W09
Id: HUAWEICMR-W09
Product: CMR-W09

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 9.1.0.335C432

**Comment by sleeplessnight2** [comment]
The here, just on a Samsung Note 10...

But videos never worked. Constantly hang up and take forever to play at all. In principle not usable as long as it has not been downloaded to the smartphone.

**Comment by aqaqsubin** [comment]
This has already been discussed in #2010,
And there is a PR (#7340) that solved this issue!

**Comment by tobiasKaminsky** [comment]
Closing as duplicate.
