### ISSUE TITLE
Nextcloud slow, and bug error, since last update

### ISSUE THREAD

**Issue by xeno024** [nextcloud/android#7404]
*********** CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{731f312 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1973)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Redmi
Device: joyeuse
Model: Redmi Note 9 Pro
Id: QKQ1.191215.002
Product: joyeuse_eea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V12.0.1.0.QJZEUXM

**Comment by AndyScherzinger** [comment]
Duplicate of #6905
