### ISSUE TITLE
CursorIndexOutOfBoundsException: Index -1 requested, with a size of 7779

### ISSUE THREAD

**Issue by cyrg38** [nextcloud/android#7408]
************ CAUSE OF ERROR ************

android.database.CursorIndexOutOfBoundsException: Index -1 requested, with a size of 7779
	at android.database.AbstractCursor.checkPosition(AbstractCursor.java:515)
	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:138)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:76)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:179)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProviderOperation.applyInternal(ContentProviderOperation.java:332)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:309)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:672)
	at android.content.ContentProvider.applyBatch(ContentProvider.java:2138)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:371)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:532)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:520)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:1882)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:436)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:519)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:401)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:237)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: starlte
Model: SM-G960F
Id: QP1A.190711.020
Product: starltexx

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G960FXXUCFTJ2

**Comment by tobiasKaminsky** [comment]
Can you reproduce this? And if yes, when does it happen?

**Comment by GreifswalderNet** [comment]
Many people have already reported the error. Unfortunately, Mr. Kaminsky cannot see that.

**Comment by rolandmas** [comment]
I can reproduce this. Closing the app, then opening it again, I see a spinner (while it tries to refresh the top-level folders?), then a freeze and a crash after ~45 seconds. If I quickly click on one of the folders that i know is small, it does switch to that folder, but it starts to spin after 1-2 seconds, then again, freeze and crash. Same backtrace as initial poster.

Running Nextcloud server 20.0.1. I should mention that there are a lot of files on the server (like half a million, split across numerous folders and subfolders).

**Comment by tobiasKaminsky** [comment]
@rolandmas how many top-level folders and files do you have?
And what device?

**Comment by rolandmas** [comment]
10 top-level folders, no files at top level. I'm on a Samsung Galaxy A20e.
I should note that I installed the "Nextcloud beta" app (from F-Droid, like I did for the main app), and that one seems to be working better.

**Comment by tobiasKaminsky** [comment]
Hm. That is surprising… :S

**Comment by rolandmas** [comment]
This still happens after upgrading to 30140190 from F-Droid.

**Comment by rolandmas** [comment]
This still happens after upgrading to 3.15.0 from F-Droid.

**Comment by tobiasKaminsky** [comment]
Is this happening only with this server/account or also on other?
Is this happening only on this device or can you try the same server/account on another device?

**Comment by kfiz** [comment]
I'm seeing the exact same error on a Samsung Galaxy S10. As soon as I start to download. I'm running Android 11.
