### ISSUE TITLE
Exception when opening a video

### ISSUE THREAD

**Issue by tomwimmenhove** [nextcloud/android#7417]
### Steps to reproduce
1. Open a video

### Expected behaviour
- Play the selected video

### Actual behaviour
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1881)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: heroqltetmo
Model: SM-G930T
Id: R16NW
Product: heroqltetmo

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: G930TUVSACSI1

**Comment by tobiasKaminsky** [comment]
Should be fixed via #7340
