### ISSUE TITLE
Absturz

### ISSUE THREAD

**Issue by Karsten55** [nextcloud/android#7440]
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{4c2e7ba u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2093)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:7582)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: motorola
Device: odessa
Model: moto g(9) plus
Id: QPA30.19-Q3-32-39-1
Product: odessa_retaile

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 5ca099

**Comment by tobiasKaminsky** [comment]
Should be fixed via #7340
