### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by dstrifler** [nextcloud/android#7456]
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{aae9455 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2188)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: beyond0q
Model: SM-G970U
Id: QP1A.190711.020
Product: beyond0qltesq

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G970USQS4ETJ2

**Comment by axheli** [comment]
I hope this is just another symptom of the same cause, so it will be fixed with #7340

**Comment by axheli** [comment]
@tobiasKaminsky  Can you close this since its a dup?
