### ISSUE TITLE
Cannot Play/Stream Video on Android App

### ISSUE THREAD

**Issue by galiehneh** [nextcloud/android#7460]
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{2eab1b7 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1946)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7398)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: oppo
Device: RMX1801
Model: Realme 2 Pro
Id: QQ3A.200805.001
Product: RMX1801

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 68

**Comment by tobiasKaminsky** [comment]
Is fixed via #7340 and is in 3.14.1 RC1. You can test it via play store beta program.
