### ISSUE TITLE
Crash when switching profiles

### ISSUE THREAD

**Issue by HitchRait** [nextcloud/android#7463]
Hi,

I have two profiles in Nextcloud app:
1) main one with regular files in VPN net (use it for a long time already)
2) new one empty, no any folders and it faces internet . Added this one yesterday.

Reproduced the crash several times following these steps:
1) Switch to new profile
2) Upload a single photo to new profile
3) Switch back to main one, swipe to update
4) Again switch to new one, swipe to update
5) Delete the photo
6) Switch to main
7) Crash a second later

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{906bde8 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1945)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus3T
Model: ONEPLUS A3003
Id: QQ3A.200805.001
Product: lineage_oneplus3

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: c5322916be

**Comment by tobiasKaminsky** [comment]
Is fixed via #7340 and is in 3.14.1 RC1. You can test it via play store beta program.
