### ISSUE TITLE
*********** CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{405de4 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1874)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7073)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: greatlteks
Model: SM-N950N
Id: PPR1.180610.011
Product: greatlteks

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: N950NKSU5DTJ3

### ISSUE THREAD

**Issue by writingdeveloper** [nextcloud/android#7464]

**Comment by tobiasKaminsky** [comment]
This is fixed with 3.14.1 RC1, you can join Play store beta program for testing.
