### ISSUE TITLE
Crash with 3.14.1 RC1

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/android#7470]
Looks like crash from https://github.com/nextcloud/android/issues/6905 is not fixed completely.

Error log:
`\*\*\*\*\*\*\*\*\*\* **CAUSE OF ERROR** \*\*\*\*\*\*\*\*\*\*
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{668249d u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2038)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

\*\*\*\*\*\*\*\*\*\* **APP INFORMATION** \*\*\*\*\*\*\*\*\*\*
ID: com.nextcloud.client
Version: 30140151
Build flavor: gplay

\*\*\*\*\*\*\*\*\*\* **DEVICE INFORMATION** \*\*\*\*\*\*\*\*\*\*
Brand: OnePlus
Device: OnePlus6
Model: ONEPLUS A6003
Id: QKQ1.190716.003
Product: OnePlus6

\*\*\*\*\*\*\*\*\*\* **FIRMWARE** \*\*\*\*\*\*\*\*\*\*
SDK: 29
Release: 10
Incremental: 2010042216`

**Comment by tobiasKaminsky** [comment]
This should be fixed in 3.14.1 RC2 coming today. You can test it via play store beta program.
If not, please re-open.
