### ISSUE TITLE
App crashed upon adding a connection profile

### ISSUE THREAD

**Issue by jitdor** [nextcloud/android#7471]
************ CAUSE OF ERROR ************

android.database.SQLException: ERROR content://org.nextcloud/file
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:289)
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:255)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:309)
	at android.content.ContentResolver.insert(ContentResolver.java:1835)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFile(FileDataStorageManager.java:273)
	at com.owncloud.android.datamodel.FileDataStorageManager.createRootDir(FileDataStorageManager.java:924)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:128)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByEncryptedRemotePath(FileDataStorageManager.java:112)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:108)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2399)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
	at android.app.Activity.performStart(Activity.java:7986)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3677)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: gts6l
Model: SM-T865
Id: QP1A.190711.020
Product: gts6lxx

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: T865XXU4BTJ2

**Comment by tobiasKaminsky** [comment]
Hm. Is there some info missing? I do not see the error message…

**Comment by GreifswalderNet** [comment]
Many people have already reported the error. Unfortunately, Mr. Kaminsky cannot see that.

**Comment by tobiasKaminsky** [comment]
> android.database.SQLException: ERROR content://org.nextcloud/file
> at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:289)

To be more precise: SQLEception is only the error class, but not the real error. So without the real error message "e.g. failed to lock database", etc. we cannot figure out the cause…
