### ISSUE TITLE
Crash app

### ISSUE THREAD

**Issue by hasanbagcaci** [nextcloud/android#7485]
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{539f0b5 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2126)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWMHA
Model: MHA-L29
Id: HUAWEIMHA-L29
Product: MHA-L29

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 9.1.0.275C432

**Comment by tobiasKaminsky** [comment]
Fixed via 3.14.1 RC1, please test it via beta program.
