### ISSUE TITLE
Mobile App Error

### ISSUE THREAD

**Issue by Mululu** [nextcloud/android#7495]
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{153a1c3 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2400)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8349)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140151
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWELS
Model: ELS-NX9
Id: HUAWEIELS-N29
Product: ELS-N29

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.1.0.176C432

**Comment by axheli** [comment]
Media Tab loading issues #7245

**Comment by axheli** [comment]
#7461

**Comment by tobiasKaminsky** [comment]
This is fixed via 3.14.1 RC2, please check via play store beta program.
