### ISSUE TITLE
The application suddenly crashed.

### ISSUE THREAD

**Issue by CRK1918** [nextcloud/android#7497]
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{8289210 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2060)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7707)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus8Pro
Model: IN2025
Id: QKQ1.191222.002
Product: OnePlus8Pro

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2008080018

**Comment by tobiasKaminsky** [comment]
This is fixed via 3.14.1 RC2, please check via play store beta program.
