### ISSUE TITLE
Crashed Report

### ISSUE THREAD

**Issue by soaibsafi** [nextcloud/android#7498]
My Nextcloudpi is running on Raspberry pi 4 2GB. 
Whenever I try to play/download/stream upload vide, the app has been crashed. 

I tried on iOS 14. It works smoothly. 

#### Nextcloud log
************ CAUSE OF ERROR ************
```
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{afec9a7 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1946)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```
************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: laurel_sprout
Model: Mi A3
Id: *******
Product: laurel_sprout

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V11.0.19.0.QFQMIXM

**Comment by tobiasKaminsky** [comment]
This is fixed via 3.14.1 RC2, please check via play store beta program.
