### ISSUE TITLE
App crashes repeatedly after selecting and deleting more than one file

### ISSUE THREAD

**Issue by anibtro** [nextcloud/android#7505]
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{2e70120 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1801)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:210)
	at android.app.ActivityThread.main(ActivityThread.java:7124)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:898)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140151
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: htc
Device: htc_ocndugl
Model: HTC U11
Id: PQ2A.190205.003
Product: ocndugl_00401

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 1086798.1

**Comment by AndyScherzinger** [comment]
Does this still happen with 3.14.1 RC2? (published yesterday)

**Comment by tobiasKaminsky** [comment]
Please re-open if it happens again.

**Comment by anibtro** [comment]
Thanks for your quick answer. With
> 3.14.1 RC2 the problem is gone
. The update appeared today afternoon (German Play Store). Again many thanks!

26.11.2020 10:18:18 Andy Scherzinger <notifications@github.com>:
