### ISSUE TITLE
Nextcloud client stops when navigating

### ISSUE THREAD

**Issue by rafa62** [nextcloud/android#7509]
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{34adea3 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2313)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWBLA
Model: BLA-L09
Id: HUAWEIBLA-L09S
Product: BLA-L09

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.0.0.159C771

**Comment by tobiasKaminsky** [comment]
This should be fixed in 3.14.1 RC2 coming today. You can test it via play store beta program.
If not, please re-open.

**Comment by rafa62** [comment]
Thank you very much!!!
I will try it.

----------
Le ven. 27 nov. 2020 à 03:00, Tobias Kaminsky <notifications@github.com> a
écrit :
