### ISSUE TITLE
Crash bug

### ISSUE THREAD

**Issue by josafagm** [nextcloud/android#7510]
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{94cc154 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2191)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8125)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: crownqltechn
Model: SM-N9600
Id: QP1A.190711.020
Product: crownqltezh

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: N9600ZHS5ETJ4

**Comment by woodlandery** [comment]
Exactly same problem on Sony Xperia XZ2 H8266

**Comment by AndyScherzinger** [comment]
a fix has been published with the latest Release Candidates, you can opt-in as a test on Google pLay and will receive that version or you can wait for the final release of the bugfix release.

**Comment by tobiasKaminsky** [comment]
This is fixed via 3.14.1 RC2, which is available via play store beta program or as stable next week.
