### ISSUE TITLE
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{3379860 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2188)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: starlte
Model: SM-G960F
Id: 
Product: starltexx

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G960FXXUCFTK1


### ISSUE THREAD

**Issue by chrisbeardy** [nextcloud/android#7514]
### Actual behaviour
- App crashed when trying to delete a file from external storage. Report ING error in case it's useful.

**Comment by tobiasKaminsky** [comment]
This is fixed via 3.14.1 RC2, which is available via play store beta program or as stable next week.
