### ISSUE TITLE
App crash on file upload

### ISSUE THREAD

**Issue by p4tchw0rk** [nextcloud/android#7516]
### Steps to reproduce
1. Open Android app, do not log in
2. Multitask button
3. Return to NextCloud Android app
4. Hit back button on phone
5. App drops into interface as if it had been logged in
6. Nothing works, and clicking the + upload button stack traces

### Expected behaviour
- nothing should happen. I shouldn't be able to see the interface until I log in

### Actual behaviour
- opening the Android app and logging in just looks like the normal web app interface and not the actual app. After completing the steps outlined above, the app drops into the expected Android interface but nothing works. Hitting the upload button shouldn't do anything after I get to it, because I haven't actually connected to a server at that point.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

No. But it's specific to the Android app and is not connected to a server. Pre-authentication.

### Environment data
Android version: 10

Device model: Samsung Galaxy Note 10+

Stock or customized system: stock

Nextcloud app version: 3.14.0

Nextcloud server version: N/A

Reverse proxy: N/A

#### Web server error log
```N/A
Insert your webserver log here
```N/A

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'com.owncloud.android.lib.resources.status.CapabilityBooleanType com.owncloud.android.lib.resources.status.OCCapability.getRichDocuments()' on a null object reference
	at com.owncloud.android.ui.fragment.OCFileListBottomSheetDialog.onCreate(OCFileListBottomSheetDialog.java:128)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:702)
	at android.app.Dialog.show(Dialog.java:424)
	at com.owncloud.android.ui.fragment.OCFileListFragment.lambda$registerFabListener$2$OCFileListFragment(OCFileListFragment.java:442)
	at com.owncloud.android.ui.fragment.-$$Lambda$OCFileListFragment$aYkoWPoxzAOahKL5AVjT06NhcnM.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7862)
	at android.view.View.performClickInternal(View.java:7831)
	at android.view.View.access$3600(View.java:879)
	at android.view.View$PerformClick.run(View.java:29359)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: d2q
Model: SM-N975U
Id: QP1A.190711.020
Product: d2qsq

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: N975USQS5DTJ8

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
I cannot reproduce it on latest master, so I think I fixed it with some PR I cannot find…
If it still happens with 3.14.1 or 3.15, please re-open.
