### ISSUE TITLE
Remote Service Exception

### ISSUE THREAD

**Issue by serhatduygun** [nextcloud/android#7540]
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{a0d24a0 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: sunfish
Model: Pixel 4a
Id: RP1A.201105.002
Product: sunfish

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 6869500

**Comment by tobiasKaminsky** [comment]
Will be fixed with 3.14.1, which is already available as a test version via play store beta program.
