### ISSUE TITLE
Crash after local deletion

### ISSUE THREAD

**Issue by TobiVanHelsinki** [nextcloud/android#7545]
### Steps to reproduce
0. Have files and folders synced to device
1. Goto files on device
2. Delete folders just local
3. Wait some seconds
4. Go back to mainview files
5. Crash

### Expected behaviour
- Tell us what should happen
- no crash

### Actual behaviour
- The files get deleted anyway

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{2ec0380 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1946)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Nokia
Device: DDV_sprout
Model: Nokia 7.2
Id: QKQ1.191014.001
Product: Daredevil_00EEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 00WW_2_340_SP04

**Comment by tobiasKaminsky** [comment]
Will be fixed with 3.14.1, which is already available as a test version via play store beta program.
