### ISSUE TITLE
Crash after opening folder with pics

### ISSUE THREAD

**Issue by camilzi** [nextcloud/android#7548]
### Steps to reproduce
1. Open folder with pics
2. Change sorting, e.g. oldest to newest or similar

### Expected behaviour
- new view or sorting is visible

### Actual behaviour
- crash

### Environment data
************ CAUSE OF ERROR ************

java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 33(offset:33).state:44 com.owncloud.android.ui.EmptyRecyclerView{7c1552a VFED..... ........ 0,0-1080,2168 #7f09021d app:id/list_root}, adapter:com.owncloud.android.ui.adapter.OCFileListAdapter@2f3abec, layout:androidx.recyclerview.widget.GridLayoutManager@4aa4bb5, context:com.owncloud.android.ui.activity.FileDisplayActivity@e45af41
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6183)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Redmi
Device: joyeuse
Model: Redmi Note 9 Pro
Id: QKQ1.191215.002
Product: joyeuse_global

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V12.0.1.0.QJZMIXM

### Logs
Not available

**Comment by tobiasKaminsky** [comment]
Is this happening while still loading? Or also when folder list is complete?
