### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ecejuan** [nextcloud/android#7556]
Streaming mp3 to vlc ... happens all times

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{641153c u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7814)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a50
Model: SM-A505FN
Id: QP1A.190711.020
Product: a50eea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: A505FNXXS5BTJ4

**Comment by tobiasKaminsky** [comment]
Will be fixed with 3.14.1, which is already available as a test version via play store beta program.
