### ISSUE TITLE
App Crash  There is no resized image. Download the full picture? 

### ISSUE THREAD

**Issue by playaz44** [nextcloud/android#7557]
### Steps to reproduce
1. Open app, go to JPG or PNG photo 
2. The application informs "There is no resized image. Download the full picture? "
3. Click Yes, switch to next photo 
4. Again click Yes - > app crash

### Expected behaviour
- Tell us what should happen

The application should download the photo from the server and view it (preview) 

### Actual behaviour
- Tell us what happens

App crash

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

I can't, it only happens in the mobile app 

### Environment data
Android version:

10.0.0.182

Device model: 

Huawei p20 pro 

Stock or customized system:

Emui 10.0.0

Nextcloud app version:

Latest beta, 3.14.1 RC2

Nextcloud server version:

20.0.2

Reverse proxy:

No

#### Web server error log

There are no logs from the server 

Insert your webserver log here

There are no logs from the server 

#### Nextcloud log (data/nextcloud.log)

Not applicable / no logs 

Insert your Nextcloud log here

************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Fragment PreviewImageFragment{99ba563} (8eda94e2-9550-45df-8165-99df6bebec08)} not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:805)
	at androidx.fragment.app.Fragment.getResources(Fragment.java:869)
	at com.owncloud.android.ui.preview.PreviewImageFragment.lambda$setErrorPreviewMessage$2$PreviewImageFragment(PreviewImageFragment.java:744)
	at com.owncloud.android.ui.preview.-$$Lambda$PreviewImageFragment$lYlNRKiEmwgldJH0g5sQ-_uYXY4.onClick(Unknown Source:2)
	at com.google.android.material.snackbar.Snackbar$1.onClick(Snackbar.java:307)
	at android.view.View.performClick(View.java:7192)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992)
	at android.view.View.performClickInternal(View.java:7166)
	at android.view.View.access$3500(View.java:824)
	at android.view.View$PerformClick.run(View.java:27592)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140152
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWCLT
Model: CLT-L29
Id: HUAWEICLT-L29
Product: CLT-L29

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.0.0.171C432

**Comment by tobiasKaminsky** [comment]
From stacktrace there should be shown an error message, which indicates that you do not have a network connection?

**Comment by playaz44** [comment]
Unlikely I have a router netgear r7000, Internet fiber connection 500Mbps sending and 500Mbps download, in addition it is in the LAN.
