### ISSUE TITLE
Technical error with connectivity (?)

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/android#7560]
Not sure what exactly caused it, but I just updated the app to latest dev version (via F-Droid), so I guess it is related to that:

```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.wifi.STATE_CHANGE flg=0x4000010 (has extras) } in com.owncloud.android.utils.ReceiversHelper$1@ee07b69
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52511(LoadedApk.java:1323)
	at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7(Unknown Source:4)
	at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run(Unknown Source:39)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkCapabilities.hasCapability(int)' on a null object reference
	at com.nextcloud.client.network.ConnectivityServiceImpl.getConnectivity(ConnectivityServiceImpl.java:121)
	at com.owncloud.android.utils.ReceiversHelper$1.onReceive(ReceiversHelper.java:58)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52511(LoadedApk.java:1313)
	... 9 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20201127
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Fairphone
Device: FP2
Model: FP2
Id: OPM7.181105.004
Product: FP2

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: de8920e892

```

**Comment by AndyScherzinger** [comment]
Only change I can think of would be #7488 @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
Strange that AndroidStudio does not warn about Nullability…

**Comment by jancborchardt** [comment]
Error on the same thing but slightly different looking, just in case it helps further with debugging:

```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkCapabilities.hasCapability(int)' on a null object reference
	at com.nextcloud.client.network.ConnectivityServiceImpl.getConnectivity(ConnectivityServiceImpl.java:121)
	at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:207)
	at com.owncloud.android.utils.-$$Lambda$FilesSyncHelper$78U1WN_nzr5HiGIrRZMThSEamz8.run(Unknown Source:10)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20201127
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Fairphone
Device: FP2
Model: FP2
Id: OPM7.181105.004
Product: FP2

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: de8920e892
```

**Comment by tobiasKaminsky** [comment]
There is an APK file in PR #7565, which you can install in parallel to your existing Nextcloud app.
It would be great if you can verify the fix.

**Comment by jancborchardt** [comment]
> There is an APK file in PR #7565, which you can install in parallel to your existing Nextcloud app.
> It would be great if you can verify the fix.

Have had the issue again with the dev app, but the QA build from the pull request seems fine. So thanks! :)

**Comment by jancborchardt** [comment]
Btw this seems to be triggered by the wifi dropping (and thus switching to mobile), which sometimes happens randomly with this device.

**Comment by AndyScherzinger** [comment]
the fix has been merged, so it'll ship with tonight's dev build :)
