### ISSUE TITLE
Nextcloud android app keeps crashing

### ISSUE THREAD

**Issue by LaunchedBerry07** [nextcloud/android#7561]
### Steps to reproduce
- I was reading a md file.

### Expected behaviour
- The app should not have crashed and closed.

### Actual behaviour
- The app crashed, closed, and an error message appeared.

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{3e59ebc u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2188)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: r7
Model: SM-N770F
Id: QP1A.190711.020
Product: r7nsxx

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: N770FXXS6CTJ4

**Comment by tobiasKaminsky** [comment]
Will be fixed with 3.14.1, which is already available as a test version via play store beta program.
