### ISSUE TITLE
Nextcloud app video playback error

### ISSUE THREAD

**Issue by hctcomputermy** [nextcloud/android#7563]
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{26af29f u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1923)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:226)
	at android.app.ActivityThread.main(ActivityThread.java:7224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:500)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:913)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OPPO
Device: OP4B79L1
Model: CPH1931
Id: PKQ1.190714.001
Product: CPH1931

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 1592806792

**Comment by tobiasKaminsky** [comment]
Will be fixed with 3.14.1, which is already available as a test version via play store beta program.
