### ISSUE TITLE
Cannot upload file (picture, data etc.) on android11

### ISSUE THREAD

**Issue by wagu1** [nextcloud/android#7574]
Error-Message:
```
App Version: 2.17.1
App Version Code: 2017001
App Flavor: fdroid

Files App Version Code: 30140090OS Version: 4.4.223-ga176abe6ae2a-ab6713882(6782484)
OS API Level: 30
Device: taimen
Manufacturer: Google
Model (and Product): Pixel 2 XL (taimen)com.nextcloud.android.sso.exceptions.UnknownErrorException: failed to connect to nextcloud.gussmann-berlin.de/2a03:4000:17:353::1 (port 443) from /2003:e4:8f36:8200:c0ca:578d:2a5a:7f6f (port 38190) after 60000ms: isConnected failed: ECONNREFUSED (Connection refused)
at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:167)
at it.niedermann.owncloud.notes.persistence.NotesClientV1.putNote(NotesClientV1.java:41)
at it.niedermann.owncloud.notes.persistence.NotesClientV1.editNote(NotesClientV1.java:49)
at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pushLocalChanges(NoteServerSyncHelper.java:373)
at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:347)
at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:307)
at android.os.AsyncTask$3.call(AsyncTask.java:394)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)

com.nextcloud.android.sso.exceptions.UnknownErrorException: failed to connect to nextcloud.gussmann-berlin.de/2a03:4000:17:353::1 (port 443) from /2003:e4:8f36:8200:c0ca:578d:2a5a:7f6f (port 41732) after 60000ms: isConnected failed: ECONNREFUSED (Connection refused)
at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:167)
at it.niedermann.owncloud.notes.persistence.NotesClientV1.getNotes(NotesClientV1.java:31)
at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pullRemoteChanges(NoteServerSyncHelper.java:435)
at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:349)
at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:307)
at android.os.AsyncTask$3.call(AsyncTask.java:394)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)

```
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- pictures should be upload to server if WLAN-connection available

### Actual behaviour
- Upload error (see above)

### Can you reproduce this problem on https://try.nextcloud.com?
- There is no problem within the browser

### Environment data
Android version: 11

Device model: Google Pixel 2

Stock or customized system:

Nextcloud app version: 3.14.0

Nextcloud server version:Nextcloud 20.0.2.2

Reverse proxy:no

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Seems like your NC cannot be reached via ipV6?

**Comment by mgrachten** [comment]
I have the same problem (file uploads don't work), also Android 11 on a Pixel 2. I don't know where to find the error logs.
