### ISSUE TITLE
player mp4 format video crash

### ISSUE THREAD

**Issue by black0592** [nextcloud/android#7575]
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{417c809 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2400)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8347)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HONOR
Device: HWYAL-O
Model: YAL-AL50
Id: HUAWEIYAL-AL50
Product: YAL-AL50

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.1.0.94C00

**Comment by tobiasKaminsky** [comment]
This will be fixed via 3.14.1 coming today.
