### ISSUE TITLE
Gplay app crash: webm browse

### ISSUE THREAD

**Issue by Dinsmoor** [nextcloud/android#7577]
### Steps to reproduce
1. Try to browse webm files in the app, swiping left and right
2. Get a few webms, then crash with the report at the bottom of this issue

### Expected behaviour
- no crash

### Actual behaviour
- crash
-this app was recently updated, before, I didn't have any problems with the same files. Server version same between upgrades.

### Environment data
See the log at the end

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{d3b044b u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6936)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: motorola
Device: messi
Model: moto z3
Id: PDXS29.84-51-11-5
Product: messi_verizon

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: c69ad

**Comment by tobiasKaminsky** [comment]
This will be fixed via 3.14.1 coming today.
