### ISSUE TITLE
crash after deleting file from trashbin

### ISSUE THREAD

**Issue by bknow1452** [nextcloud/android#7592]
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1788)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: motorola
Device: addison
Model: XT1635-02
Id: OPNS27.76-12-22-9
Product: addison

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: 10

**Comment by tobiasKaminsky** [comment]
Please update to 3.14.1
