### ISSUE TITLE
uploading a file

### ISSUE THREAD

**Issue by grrosminet** [nextcloud/android#7593]
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{5fac3c6 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2188)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: beyond1
Model: SM-G973F
Id: QP1A.190711.020
Product: beyond1lteeea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G973FXXU9DTJA

**Comment by AndyScherzinger** [comment]
Please update to latest released version 3.14.1
