### ISSUE TITLE
exeption

### ISSUE THREAD

**Issue by juanjgit** [nextcloud/android#7596]
### Steps to reproduce
1. Stops. Working while un background since laat update
2. Owncloud server show end of life announcement

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.wifi.STATE_CHANGE flg=0x4000010 (has extras) } in com.owncloud.android.utils.ReceiversHelper$1@ef9cb14
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1401)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkCapabilities.hasCapability(int)' on a null object reference
	at com.nextcloud.client.network.ConnectivityServiceImpl.getConnectivity(ConnectivityServiceImpl.java:121)
	at com.owncloud.android.utils.ReceiversHelper$1.onReceive(ReceiversHelper.java:58)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1391)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20201127
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: whyred
Model: Redmi Note 5
Id: PQ2A.190405.003
Product: whyred

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: eng.subhra.20190430.175229

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
This is fixed with 20201202 dev version, please upgrade.
