### ISSUE TITLE
Plantage opencloud lineageos

### ISSUE THREAD

**Issue by spareige** [nextcloud/android#7605]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.wifi.STATE_CHANGE flg=0x4000010 (has extras) } in com.owncloud.android.utils.ReceiversHelper$1@ccad3bb
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1132)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkCapabilities.hasCapability(int)' on a null object reference
	at com.nextcloud.client.network.ConnectivityServiceImpl.getConnectivity(ConnectivityServiceImpl.java:121)
	at com.owncloud.android.utils.ReceiversHelper$1.onReceive(ReceiversHelper.java:58)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1122)
	... 7 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20201127
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Samsung
Device: zeroflte
Model: SM-G920F
Id: NJH47F
Product: zerofltexx

************ FIRMWARE ************
SDK: 25
Release: 7.1.2
Incremental: 88b3874426

**Comment by AndyScherzinger** [comment]
@spareige please update to latest dev version e.g. https://github.com/nextcloud/android/releases/tag/dev-20201203 since this issue has been fixed in the meantime :)
