### ISSUE TITLE
[Dev] App crashes when changing theme

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#7607]
### Steps to reproduce

1. Launch the app.
2. Select "Media".
3. Select "Settings".
4. Change the app theme.

```
********** CAUSE OF ERROR **********

java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.recyclerview.widget.RecyclerView$LayoutManager androidx.recyclerview.widget.RecyclerView.getLayoutManager()' on a null object reference

at com.owncloud.android.ui.fragment.ExtendedListFragment.isGridEnabled(ExtendedListFragment.java:179)

at com.owncloud.android.ui.fragment.ExtendedListFragment.onSaveInstanceState(ExtendedListFragment.java:455)

at com.owncloud.android.ui.fragment.OCFileListFragment.onSaveInstanceState(OCFileListFragment.java:771)

at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2864)

at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:434)

at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:400)

at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:143)

at androidx.fragment.app.FragmentManager.saveAllState(FragmentManager.java:2398)

at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:152)

at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:512)

at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:544)

at com.owncloud.android.ui.activity.DrawerActivity.onSaveInstanceState(DrawerActivity.java:841)

at com.owncloud.android.ui.activity.FileActivity.onSaveInstanceState(FileActivity.java:280)

at com.owncloud.android.ui.activity.FileDisplayActivity.onSaveInstanceState(FileDisplayActivity.java:1100)

at android.app.Activity.performSaveInstanceState(Activity.java:2131)

at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1500)

at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:5955)

at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5254)

at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5218)

at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5293)

at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:41)

at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190)

at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)

at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:57)

at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5889)

at android.app.ActivityThread.access$4500(ActivityThread.java:296)

at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2397)

at android.os.Handler.dispatchMessage(Handler.java:107)

at android.os.Looper.loop(Looper.java:213)

at android.app.ActivityThread.main(ActivityThread.java:8178)

at java.lang.reflect.Method.invoke(Native Method)

at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)

at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)


********** APP INFORMATION **********

ID: com.nextcloud.android.beta

Version: 20201203

Build flavor: versionDev
```

### Environment data
Android version: 10

Nextcloud app version: dev 20201203

**Comment by tobiasKaminsky** [comment]
Thanks for reporting!
Fix will be soon in dev version.
