### ISSUE TITLE
Multimedia

### ISSUE THREAD

**Issue by txsastre** [nextcloud/android#7615]
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{d2c994e u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1945)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: lavender
Model: Redmi Note 7
Id: QQ3A.200805.001
Product: lavender

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 1e21ab8631

**Comment by AndyScherzinger** [comment]
Please update to latest release 3.14.1 shipping a fix for this.
