### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by rullydotcom** [nextcloud/android#7621]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized
	at androidx.work.Data.toByteArrayInternal(Data.java:417)
	at androidx.work.Data$Builder.build(Data.java:846)
	at com.nextcloud.client.jobs.BackgroundJobManagerImpl.startImmediateContactsImport(BackgroundJobManagerImpl.kt:254)
	at com.owncloud.android.ui.fragment.contactsbackup.ContactListFragment.importContacts(ContactListFragment.java:367)
	at com.owncloud.android.ui.fragment.contactsbackup.ContactListFragment.getAccountForImport(ContactListFragment.java:424)
	at com.owncloud.android.ui.fragment.contactsbackup.ContactListFragment.access$100(ContactListFragment.java:113)
	at com.owncloud.android.ui.fragment.contactsbackup.ContactListFragment$1.onClick(ContactListFragment.java:230)
	at android.view.View.performClick(View.java:7259)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992)
	at android.view.View.performClickInternal(View.java:7236)
	at android.view.View.access$3600(View.java:801)
	at android.view.View$PerformClick.run(View.java:27897)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7398)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: vince
Model: Redmi 5 Plus
Id: QQ3A.200905.001
Product: rr_vince

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: eng.rutura.20201125.064849

**Comment by ezaquarii** [comment]
@rullydotcom Do you remember how many contacts you tried to import?

**Comment by rullydotcom** [comment]
> @rullydotcom Do you remember how many contacts you tried to import?

hundreds

**Comment by rullydotcom** [comment]
but its okay. i can show the hidden folder and take the vcf file from there
