### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by suggested-username** [nextcloud/android#7629]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to stop activity {com.nextcloud.client/com.owncloud.android.ui.activity.UploadFilesActivity}: java.lang.IllegalStateException: Bindings already cleared.
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4938)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4908)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4990)
	at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:41)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:181)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:102)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2245)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
Caused by: java.lang.IllegalStateException: Bindings already cleared.
	at com.owncloud.android.ui.dialog.LocalStoragePathPickerDialogFragment_ViewBinding.unbind(LocalStoragePathPickerDialogFragment_ViewBinding.java:29)
	at com.owncloud.android.ui.dialog.LocalStoragePathPickerDialogFragment.onStop(LocalStoragePathPickerDialogFragment.java:123)
	at androidx.fragment.app.Fragment.performStop(Fragment.java:2895)
	at androidx.fragment.app.FragmentStateManager.stop(FragmentStateManager.java:391)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1223)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
	at androidx.fragment.app.FragmentManager.dispatchStop(FragmentManager.java:2610)
	at androidx.fragment.app.FragmentController.dispatchStop(FragmentController.java:291)
	at androidx.fragment.app.FragmentActivity.onStop(FragmentActivity.java:563)
	at androidx.appcompat.app.AppCompatActivity.onStop(AppCompatActivity.java:216)
	at com.owncloud.android.ui.activity.DrawerActivity.onStop(DrawerActivity.java:1023)
	at com.owncloud.android.ui.activity.UploadFilesActivity.onStop(UploadFilesActivity.java:651)
	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1474)
	at android.app.Activity.performStop(Activity.java:8222)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4930)
	... 12 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: realme
Device: RMX2086L1
Model: RMX2086
Id: QKQ1.191021.002
Product: RMX2086T2

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 1600779907

**Comment by AndyScherzinger** [comment]
@suggested-username can you name the steps that lead to this crash?

**Comment by suggested-username** [comment]
I kinda forgot what did I do. all I knew is I minimized it and re-open it again while uploading some images
