### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by NicolasToussaint** [nextcloud/android#7631]
Happened twice while watching short videos 
I think I can reproduce, if needed

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{9bbc46c u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1946)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Fairphone
Device: FP3
Model: FP3
Id:
Product: FP3

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 09290922

**Comment by AndyScherzinger** [comment]
@NicolasToussaint please update to latest release 3.14.1

**Comment by NicolasToussaint** [comment]
Thanks; indeed, cannot reproduce after updating ;
Should have thought about it :-/

**Comment by AndyScherzinger** [comment]
No worries, most importantly it has been resolved 😊👍
