### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by rudi48** [nextcloud/android#7648]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.markCommentsAsRead()' on a null object reference
	at com.owncloud.android.ui.fragment.FileDetailFragment$1.onPageScrolled(FileDetailFragment.java:242)
	at androidx.viewpager.widget.ViewPager.dispatchOnPageScrolled(ViewPager.java:1930)
	at androidx.viewpager.widget.ViewPager.onPageScrolled(ViewPager.java:1904)
	at androidx.viewpager.widget.ViewPager.pageScrolled(ViewPager.java:1842)
	at androidx.viewpager.widget.ViewPager.scrollToItem(ViewPager.java:694)
	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1786)
	at android.view.View.layout(View.java:23753)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23753)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23753)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1818)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1584)
	at android.view.View.layout(View.java:23753)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1996)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:23753)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:23753)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23753)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23753)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23753)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23753)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1065)
	at android.view.View.layout(View.java:23753)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3683)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3143)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2204)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9069)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
	at android.view.Choreographer.doCallbacks(Choreographer.java:797)
	at android.view.Choreographer.doFrame(Choreographer.java:732)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8107)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: gta3xlwifi
Model: SM-T510
Id: QP1A.190711.020
Product: gta3xlwifieea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: T510XXU3BTK1

- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Please tell us the steps to reproduce.

**Comment by rudi48** [comment]
With Nextcloud 20.0.7 the error is gone.
