### ISSUE TITLE
android client crash

### ISSUE THREAD

**Issue by ocrampal** [nextcloud/android#7658]
### Steps to reproduce
1. Clicking on a file marked with a red icon
2. 
3. 

### Expected behaviour
- Tell us what should happen
Should download the file

### Actual behaviour
- Tell us what happens
Client crashes

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start service com.nextcloud.client.media.PlayerService@ab09c62 with Intent { act=PLAY cmp=com.nextcloud.client/.media.PlayerService (has extras) }: java.io.FileNotFoundException: /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/ocrampal@cloud.splindex.com: open failed: EISDIR (Is a directory)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4166)
	at android.app.ActivityThread.access$1900(ActivityThread.java:224)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1919)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/ocrampal@cloud.splindex.com: open failed: EISDIR (Is a directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileInputStream.<init>(FileInputStream.java:159)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1235)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1213)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1178)
	at com.nextcloud.client.media.Player$delegate$1.onPrepare(Player.kt:113)
	at com.nextcloud.client.media.PlayerStateMachine$11.invoke(PlayerStateMachine.kt:157)
	at com.nextcloud.client.media.PlayerStateMachine$11.invoke(PlayerStateMachine.kt:69)
	at com.nextcloud.client.media.PlayerStateMachine$sam$com_github_oxo42_stateless4j_delegates_Action$0.doIt(Unknown Source:2)
	at com.github.oxo42.stateless4j.StateConfiguration$6.doIt(StateConfiguration.java:284)
	at com.github.oxo42.stateless4j.StateConfiguration$6.doIt(StateConfiguration.java:281)
	at com.github.oxo42.stateless4j.StateConfiguration$7.doIt(StateConfiguration.java:300)
	at com.github.oxo42.stateless4j.StateConfiguration$7.doIt(StateConfiguration.java:297)
	at com.github.oxo42.stateless4j.StateRepresentation.executeEntryActions(StateRepresentation.java:122)
	at com.github.oxo42.stateless4j.StateRepresentation.enter(StateRepresentation.java:101)
	at com.github.oxo42.stateless4j.StateMachine.publicFire(StateMachine.java:225)
	at com.github.oxo42.stateless4j.StateMachine.fire(StateMachine.java:145)
	at com.nextcloud.client.media.PlayerStateMachine.immediateTransition(PlayerStateMachine.kt:191)
	at com.nextcloud.client.media.PlayerStateMachine.access$immediateTransition(PlayerStateMachine.kt:69)
	at com.nextcloud.client.media.PlayerStateMachine$7.invoke(PlayerStateMachine.kt:146)
	at com.nextcloud.client.media.PlayerStateMachine$7.invoke(PlayerStateMachine.kt:69)
	at com.nextcloud.client.media.PlayerStateMachine$sam$com_github_oxo42_stateless4j_delegates_Action$0.doIt(Unknown Source:2)
	at com.github.oxo42.stateless4j.StateConfiguration$6.doIt(StateConfiguration.java:284)
	at com.github.oxo42.stateless4j.StateConfiguration$6.doIt(StateConfiguration.java:281)
	at com.github.oxo42.stateless4j.StateConfiguration$7.doIt(StateConfiguration.java:300)
	at com.github.oxo42.stateless4j.StateConfiguration$7.doIt(StateConfiguration.java:297)
	at com.github.oxo42.stateless4j.StateRepresentation.executeEntryActions(StateRepresentation.java:122)
	at com.github.oxo42.stateless4j.StateRepresentation.enter(StateRepresentation.java:101)
	at com.github.oxo42.stateless4j.StateMachine.publicFire(StateMachine.java:225)
	at com.github.oxo42.stateless4j.StateMachine.fire(StateMachine.java:145)
	at com.nextcloud.client.media.PlayerStateMachine.post(PlayerStateMachine.kt:224)
	at com.nextcloud.client.media.Player.play(Player.kt:187)
	at com.nextcloud.client.media.PlayerService.onActionPlay(PlayerService.kt:145)
	at com.nextcloud.client.media.PlayerService.onStartCommand(PlayerService.kt:123)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4145)
	... 8 more
Caused by: android.system.ErrnoException: open failed: EISDIR (Is a directory)
	at libcore.io.IoBridge.open(IoBridge.java:486)
	... 42 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: nitrogen
Model: MI MAX 3
Id: QKQ1.190910.002
Product: nitrogen

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V12.0.1.0.QEDMIXM

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
> java.io.FileNotFoundException: /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/ocrampal@cloud.splindex.com: open failed: EISDIR (Is a directory)

This looks extremely strange…
I tested it and here it works.
What kind of file is this? Can you verify that this is indeed a file already downloaded on your device?

**Comment by ocrampal** [comment]
Dear Tobias,

here are some more screen shots:

I tried to sync the file. But it does not sync, goes back to red icon.



---
Marco Palombi

http://ocrampal.com
