### ISSUE TITLE
File sharing by Android API crashes

### ISSUE THREAD

**Issue by yihanwu1024** [nextcloud/android#7669]
### Steps to reproduce
1. Open the share menu of a file (not folder)
2. Tap a sharing method provided by Android

### Expected behaviour
- The Android sharing method should open

### Actual behaviour
- Nextcloud crashes and shows error log

### Environment data
Android version: 10

Device model: Huawei MAR

Stock or customized system: Stock, EMUI 10

Nextcloud app version: 3.14.1 F-Droid

Nextcloud server version: 20.0.2

Reverse proxy: Port forwarding only

#### Android app log
```
************ CAUSE OF ERROR ************

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.huawei.intent.action.hwCHOOSER (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2113)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1739)
	at android.app.Activity.startActivityForResult(Activity.java:5363)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
	at android.app.Activity.startActivityForResult(Activity.java:5304)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
	at android.app.Activity.startActivity(Activity.java:5734)
	at android.app.Activity.startActivity(Activity.java:5702)
	at com.owncloud.android.ui.helpers.FileOperationsHelper.sendCachedImage(FileOperationsHelper.java:737)
	at com.owncloud.android.ui.dialog.SendShareDialog.lambda$setupSendButtonClickListener$4$SendShareDialog(SendShareDialog.java:225)
	at com.owncloud.android.ui.dialog.-$$Lambda$SendShareDialog$Sv9AeldJVMwZR3LIfTLmDNSgX2U.onClick(Unknown Source:4)
	at com.owncloud.android.ui.adapter.SendButtonAdapter$ViewHolder.onClick(SendButtonAdapter.java:85)
	at android.view.View.performClick(View.java:7192)
	at android.view.View.performClickInternal(View.java:7166)
	at android.view.View.access$3500(View.java:824)
	at android.view.View$PerformClick.run(View.java:27592)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWMAR
Model: MAR-AL00
Id: HUAWEIMAR-AL00
Product: MAR-AL00

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.0.0.161C00
```

### Note
Is Huawei just messing up with the Android intent API? Because I can share on another AOSP device without issue.

**Comment by md-clone** [comment]
i have the same issue with file sharing on android, i downgraded to v3.14.0 and it works again

**Comment by ezaquarii** [comment]
On Mon, Dec 14, 2020 at 07:39:13PM -0800, Yihan Wu wrote:
> Is Huawei just messing up with the Android intent API? Because I can share on another AOSP device without issue.

It looks like they send some proprietary intent:

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.huawei.intent.action.hwCHOOSER (has extras) }
```

**Comment by yihanwu1024** [comment]
So is there a plan to add this compatibility?

**Comment by tobiasKaminsky** [comment]
> So is there a plan to add this compatibility?

without having such a device and Huawei not obeying the official Android API I fear that we cannot do much here.

What wonders me is, that something translates the normal sharing intent to this new hwCHOOSER one, but then there is no receiver for it…

**Comment by yihanwu1024** [comment]
I believe most devs hate adapting to a non-standard API. Maybe just wait for some random dev to do that. Shall we still leave this issue open?

**Comment by fto77533** [comment]
التكاثر
افتح قائمة مشاركة ملف (وليس مجلد)
انقر فوق طريقة المشاركة التي يوفرها Android
سلوك متوقع
يجب أن يتم فتح طريقة مشاركة Android
السلوك الفعلي
Nextcloud تعطل ويظهر سجل الخطأ
بيانات البيئة
إصدار أندرويد: 10

طراز الجهاز: Huawei MAR

نظام المخزون أو النظام المخصص: Stock ، EMUI 10

إصدار تطبيق Nextcloud: 3.14.1 F-Droid

إصدار خادم Nextcloud: 20.0.2

الوكيل العكسي: إعادة توجيه المنفذ فقط

السجلات
سجل تطبيقات Android
************ CAUSE OF ERROR ************

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.huawei.intent.action.hwCHOOSER (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2113)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1739)
	at android.app.Activity.startActivityForResult(Activity.java:5363)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
	at android.app.Activity.startActivityForResult(Activity.java:5304)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
	at android.app.Activity.startActivity(Activity.java:5734)
	at android.app.Activity.startActivity(Activity.java:5702)
	at com.owncloud.android.ui.helpers.FileOperationsHelper.sendCachedImage(FileOperationsHelper.java:737)
	at com.owncloud.android.ui.dialog.SendShareDialog.lambda$setupSendButtonClickListener$4$SendShareDialog(SendShareDialog.java:225)
	at com.owncloud.android.ui.dialog.-$$Lambda$SendShareDialog$Sv9AeldJVMwZR3LIfTLmDNSgX2U.onClick(Unknown Source:4)
	at com.owncloud.android.ui.adapter.SendButtonAdapter$ViewHolder.onClick(SendButtonAdapter.java:85)
	at android.view.View.performClick(View.java:7192)
	at android.view.View.performClickInternal(View.java:7166)
	at android.view.View.access$3500(View.java:824)
	at android.view.View$PerformClick.run(View.java:27592)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWMAR
Model: MAR-AL00
Id: HUAWEIMAR-AL00
Product: MAR-AL00

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.0.0.161C00
ملحوظة
هل تقوم Huawei بالعبث في واجهة برمجة تطبيقات Android intent؟ لأنه يمكنني المشاركة على جهاز AOSP آخر دون مشكلة
