### ISSUE TITLE
Crash on sign in 

### ISSUE THREAD

**Issue by axheli** [nextcloud/android#7676]
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032 SQLITE_READONLY_DBMOVED)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:890)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1845)
	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1791)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:645)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:629)
	at android.content.ContentProvider.update(ContentProvider.java:1870)
	at android.content.ContentProvider$Transport.update(ContentProvider.java:487)
	at android.content.ContentResolver.update(ContentResolver.java:2400)
	at android.content.ContentResolver.update(ContentResolver.java:2362)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveCapabilities(FileDataStorageManager.java:1945)
	at com.owncloud.android.operations.GetCapabilitiesOperation.run(GetCapabilitiesOperation.java:51)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:139)
	at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:64)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:296)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:276)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:229)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:923)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus8Pro
Model: IN2025
Id: RP1A.201005.001
Product: OnePlus8Pro

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 2011190108

**Comment by tobiasKaminsky** [comment]
Do you know what led to this?

**Comment by axheli** [comment]
> Do you know what led to this?

I signed into the app for the first time and got this

**Comment by tobiasKaminsky** [comment]
Did you restore the app via backup, or moved it from one phone to another?

**Comment by axheli** [comment]
No I did not i installed this fresh from the play store
