### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by monsterflo** [nextcloud/android#7681]
************ CAUSE OF ERROR ************

java.lang.IllegalArgumentException: Receiver not registered: androidx.work.impl.constraints.trackers.NetworkStateTracker$NetworkStateBroadcastReceiver@1d4b48bd
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:801)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1759)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:536)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:536)
	at androidx.work.impl.constraints.trackers.NetworkStateTracker.stopTracking(NetworkStateTracker.java:124)
	at androidx.work.impl.constraints.trackers.ConstraintTracker.removeListener(ConstraintTracker.java:86)
	at androidx.work.impl.constraints.controllers.ConstraintController.replace(ConstraintController.java:97)
	at androidx.work.impl.constraints.WorkConstraintsTracker.replace(WorkConstraintsTracker.java:106)
	at androidx.work.impl.background.greedy.GreedyScheduler.removeConstraintTrackingFor(GreedyScheduler.java:224)
	at androidx.work.impl.background.greedy.GreedyScheduler.onExecuted(GreedyScheduler.java:210)
	at androidx.work.impl.Processor.onExecuted(Processor.java:302)
	at androidx.work.impl.Processor$FutureListener.run(Processor.java:375)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5604)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Amazon
Device: suez
Model: KFSUWI
Id: LVY48F
Product: suez

************ FIRMWARE ************
SDK: 22
Release: 5.1.1
Incremental: 40.6.5.9_user_659655920

**Comment by tobiasKaminsky** [comment]
Do you know what led to this crash?
