### ISSUE TITLE
Upload fails with Unknown Error

### ISSUE THREAD

**Issue by besendorf** [nextcloud/android#7696]
### Steps to reproduce
1. Upload file

### Expected behaviour
- File uploads as expected

### Actual behaviour
- Upload fails

### Can you reproduce this problem on https://try.nextcloud.com?
no its only on mobile

### Environment data
Android version: 11.0

Device model: Pixel 4a

Stock or customized system: GrpaheneOS

Nextcloud app version: 3.14.1

Nextcloud server version:

Reverse proxy: Caddy

#### Web server error log
```


Error | PHP | Error: Cannot  modify header information - headers already sent by (output started at  /var/www/html/3rdparty/sabre/http/lib/Sapi.php:132) at  /var/www/html/apps/dav/lib/Connector/Sabre/File.php#691 |  
-- | -- | -- | --


[PHP] Error: Error: Cannot modify header information - headers already sent by (output started at /var/www/html/3rdparty/sabre/http/lib/Sapi.php:132) at /var/www/html/apps/dav/lib/Connector/Sabre/File.php#691 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError(2, "Cannot modify h ... )", "/var/www/html/a ... p", 691, {string: "X-Hash ... "})
 1. /var/www/html/apps/dav/lib/Connector/Sabre/File.php line 691
    header("X-Hash-SHA1: da ... 9")
 2. /var/www/html/apps/dav/lib/Connector/Sabre/File.php line 192
    OCA\DAV\Connector\Sabre\File->header("X-Hash-SHA1: da ... 9")
 3. <<closure>>
    OCA\DAV\Connector\Sabre\File->OCA\DAV\Connector\Sabre\{closure}("*** sensitive parameters replaced ***")
 4. /var/www/html/lib/private/Files/Stream/HashWrapper.php line 71
    call_user_func(Closure {}, "*** sensitive parameter replaced ***")
 5. <<closure>>
    OC\Files\Stream\HashWrapper->stream_close()
 6. /var/www/html/3rdparty/icewind/streams/src/Wrapper.php line 132
    fclose(null)
 7. /var/www/html/lib/private/Files/Stream/HashWrapper.php line 75
    Icewind\Streams\Wrapper->stream_close()
 8. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 319
    OC\Files\Stream\HashWrapper->stream_close()
 9. /var/www/html/apps/dav/appinfo/v1/webdav.php line 84
    Sabre\DAV\Server->exec()
10. /var/www/html/remote.php line 167
    require_once("/var/www/html/a ... p")

PUT /remote.php/webdav/.SeedVaultAndroidBackup/1608335875857/.backup.metadata
from 192.168.128.1 by besen at 2020-12-19T11:22:42+00:00



[PHP] Error: Error: Cannot modify header information - headers already sent by (output started at /var/www/html/3rdparty/sabre/http/lib/Sapi.php:132) at /var/www/html/apps/dav/lib/Connector/Sabre/File.php#691 at <<closure>>

0. <<closure>>
   OC\Log\ErrorHandler::onError(2, "Cannot modify h ... )", "/var/www/html/a ... p", 691, {string: "X-Hash ... "})
1. /var/www/html/apps/dav/lib/Connector/Sabre/File.php line 691
   header("X-Hash-SHA256:  ... 5")
2. /var/www/html/apps/dav/lib/Connector/Sabre/File.php line 195
   OCA\DAV\Connector\Sabre\File->header("X-Hash-SHA256:  ... 5")
3. <<closure>>
   OCA\DAV\Connector\Sabre\File->OCA\DAV\Connector\Sabre\{closure}("*** sensitive parameters replaced ***")
4. /var/www/html/lib/private/Files/Stream/HashWrapper.php line 71
   call_user_func(Closure {}, "*** sensitive parameter replaced ***")
5. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 319
   OC\Files\Stream\HashWrapper->stream_close()
6. /var/www/html/apps/dav/appinfo/v1/webdav.php line 84
   Sabre\DAV\Server->exec()
7. /var/www/html/remote.php line 167
   require_once("/var/www/html/a ... p")

PUT /remote.php/webdav/.SeedVaultAndroidBackup/1608335875857/.backup.metadata
from 192.168.128.1 by besen at 2020-12-19T11:22:42+00:00
```

#### Nextcloud Android App logcat
```
2020-12-19 12:22:39.943 13378-13378/? D/UploadListAdapter: loadUploadItemsFromDb
2020-12-19 12:22:39.944 13378-17345/? D/UploadsStorageManager: QUERY: (status== ? OR last_result==9 OR last_result==13 OR last_result==11 OR last_result==14 ) AND last_result!= 16 ROWID: -1
2020-12-19 12:22:39.946 13378-13378/? D/UploadsStorageManager: QUERY: status==0 OR last_result==9 OR last_result==13 OR last_result==11 OR last_result==14 AND account_name== ? ROWID: -1
2020-12-19 12:22:39.951 13378-17345/? V/UploadsStorageManager: getUploads() got 1 rows from page 0, 1 rows total so far, last ID 1
2020-12-19 12:22:39.951 13378-17345/? D/UploadsStorageManager: QUERY: ((status== ? OR last_result==9 OR last_result==13 OR last_result==11 OR last_result==14 ) AND last_result!= 16) AND _id < ? ROWID: 1
2020-12-19 12:22:39.951 13378-13378/? V/UploadsStorageManager: getUploads() got 0 rows from page 0, 0 rows total so far, last ID -1
2020-12-19 12:22:39.951 13378-13378/? V/UploadsStorageManager: getUploads() returning 0 (0) rows after reading 1 pages
2020-12-19 12:22:39.954 13378-13378/? D/UploadsStorageManager: QUERY: status==1 AND last_result<>9 AND last_result<>13 AND last_result<>11 AND last_result<>14 AND account_name== ? ROWID: -1
2020-12-19 12:22:39.955 13378-17345/? V/UploadsStorageManager: getUploads() got 0 rows from page 1, 1 rows total so far, last ID 1
2020-12-19 12:22:39.955 13378-17345/? V/UploadsStorageManager: getUploads() returning 1 (1) rows after reading 2 pages
2020-12-19 12:22:39.959 13378-17345/? D/AdvancedSslSocketFactory: Creating SSL Socket with remote cloud2.mydomain.com:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@e22dc7d
2020-12-19 12:22:39.959 13378-13378/? V/UploadsStorageManager: getUploads() got 1 rows from page 0, 1 rows total so far, last ID 1
2020-12-19 12:22:39.959 13378-17345/? D/AdvancedSslSocketFactory:  ... with connection timeout 0 and socket timeout 0
2020-12-19 12:22:39.959 13378-13378/? D/UploadsStorageManager: QUERY: (status==1 AND last_result<>9 AND last_result<>13 AND last_result<>11 AND last_result<>14 AND account_name== ?) AND _id < ? ROWID: 1
2020-12-19 12:22:39.964 13378-13378/? V/UploadsStorageManager: getUploads() got 0 rows from page 1, 1 rows total so far, last ID 1
2020-12-19 12:22:39.964 13378-13378/? V/UploadsStorageManager: getUploads() returning 1 (1) rows after reading 2 pages
2020-12-19 12:22:39.966 13378-13378/? D/UploadsStorageManager: QUERY: status==2 AND account_name== ? ROWID: -1
2020-12-19 12:22:39.969 13378-13378/? V/UploadsStorageManager: getUploads() got 0 rows from page 0, 0 rows total so far, last ID -1
2020-12-19 12:22:39.970 13378-13378/? V/UploadsStorageManager: getUploads() returning 0 (0) rows after reading 1 pages
2020-12-19 12:22:40.163 854-930/? D/VSC: @ 163645.271: [WO] tilt angle 89
2020-12-19 12:22:40.231 13378-17345/? I/ServerNameIndicator: SNI done, hostname: cloud2.mydomain.com
2020-12-19 12:22:40.838 13378-13378/? D/UploadListAdapter: loadUploadItemsFromDb
2020-12-19 12:22:40.838 13378-17348/? D/UploadsStorageManager: QUERY: (status== ? OR last_result==9 OR last_result==13 OR last_result==11 OR last_result==14 ) AND last_result!= 16 ROWID: -1
2020-12-19 12:22:40.841 13378-13378/? D/UploadsStorageManager: QUERY: status==0 OR last_result==9 OR last_result==13 OR last_result==11 OR last_result==14 AND account_name== ? ROWID: -1
2020-12-19 12:22:40.847 13378-17348/? V/UploadsStorageManager: getUploads() got 1 rows from page 0, 1 rows total so far, last ID 1
2020-12-19 12:22:40.847 13378-13378/? V/UploadsStorageManager: getUploads() got 0 rows from page 0, 0 rows total so far, last ID -1
2020-12-19 12:22:40.847 13378-17348/? D/UploadsStorageManager: QUERY: ((status== ? OR last_result==9 OR last_result==13 OR last_result==11 OR last_result==14 ) AND last_result!= 16) AND _id < ? ROWID: 1
2020-12-19 12:22:40.847 13378-13378/? V/UploadsStorageManager: getUploads() returning 0 (0) rows after reading 1 pages
2020-12-19 12:22:40.851 13378-13378/? D/UploadsStorageManager: QUERY: status==1 AND last_result<>9 AND last_result<>13 AND last_result<>11 AND last_result<>14 AND account_name== ? ROWID: -1
2020-12-19 12:22:40.852 13378-17348/? V/UploadsStorageManager: getUploads() got 0 rows from page 1, 1 rows total so far, last ID 1
2020-12-19 12:22:40.852 13378-17348/? V/UploadsStorageManager: getUploads() returning 1 (1) rows after reading 2 pages
2020-12-19 12:22:40.854 13378-13378/? V/UploadsStorageManager: getUploads() got 1 rows from page 0, 1 rows total so far, last ID 1
2020-12-19 12:22:40.854 13378-13378/? D/UploadsStorageManager: QUERY: (status==1 AND last_result<>9 AND last_result<>13 AND last_result<>11 AND last_result<>14 AND account_name== ?) AND _id < ? ROWID: 1
2020-12-19 12:22:40.856 13378-17348/? D/AdvancedSslSocketFactory: Creating SSL Socket with remote cloud2.mydomain.com:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@9e5b7c3
2020-12-19 12:22:40.856 13378-17348/? D/AdvancedSslSocketFactory:  ... with connection timeout 0 and socket timeout 0
2020-12-19 12:22:40.857 13378-17348/? I/ServerNameIndicator: SNI done, hostname: cloud2.mydomain.com
2020-12-19 12:22:40.858 13378-13378/? V/UploadsStorageManager: getUploads() got 0 rows from page 1, 1 rows total so far, last ID 1
2020-12-19 12:22:40.858 13378-13378/? V/UploadsStorageManager: getUploads() returning 1 (1) rows after reading 2 pages
2020-12-19 12:22:40.860 13378-13378/? D/UploadsStorageManager: QUERY: status==2 AND account_name== ? ROWID: -1
2020-12-19 12:22:40.863 13378-13378/? V/UploadsStorageManager: getUploads() got 0 rows from page 0, 0 rows total so far, last ID -1
2020-12-19 12:22:40.863 13378-13378/? V/UploadsStorageManager: getUploads() returning 0 (0) rows after reading 1 pages
2020-12-19 12:22:41.218 13378-13378/? D/FileUploader: Starting command with id 18
2020-12-19 12:22:41.236 13378-13378/? V/UploadsStorageManager: Updating /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/besen@cloud2.mydomain.com/.SeedVaultAndroidBackup/1608335875857/.backup.metadata with status=UPLOAD_IN_PROGRESS
2020-12-19 12:22:41.246 13378-13378/? D/UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/besen@cloud2.mydomain.com/.SeedVaultAndroidBackup/1608335875857/.backup.metadata
2020-12-19 12:22:41.246 13378-13378/? D/UploadsStorageManager: notifyObserversNow
2020-12-19 12:22:41.247 13378-13378/? D/UploadListAdapter: loadUploadItemsFromDb
2020-12-19 12:22:41.250 13378-13378/? D/UploadsStorageManager: QUERY: status==0 OR last_result==9 OR last_result==13 OR last_result==11 OR last_result==14 AND account_name== ? ROWID: -1
2020-12-19 12:22:41.256 13378-14982/? V/UploadsStorageManager: Updating /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/besen@cloud2.mydomain.com/.SeedVaultAndroidBackup/1608335875857/.backup.metadata with status:UPLOAD_IN_PROGRESS and result:UNKNOWN (old:/storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/besen@cloud2.mydomain.com/.SeedVaultAndroidBackup/1608335875857/.backup.metadata status:UPLOAD_IN_PROGRESS result:-1)
2020-12-19 12:22:41.256 13378-14982/? V/UploadsStorageManager: Updating /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/besen@cloud2.mydomain.com/.SeedVaultAndroidBackup/1608335875857/.backup.metadata with status=UPLOAD_IN_PROGRESS
2020-12-19 12:22:41.258 13378-13378/? V/UploadsStorageManager: getUploads() got 1 rows from page 0, 1 rows total so far, last ID 1
2020-12-19 12:22:41.258 13378-13378/? D/UploadsStorageManager: QUERY: (status==0 OR last_result==9 OR last_result==13 OR last_result==11 OR last_result==14 AND account_name== ?) AND _id < ? ROWID: 1
2020-12-19 12:22:41.260 13378-14982/? D/UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/besen@cloud2.mydomain.com/.SeedVaultAndroidBackup/1608335875857/.backup.metadata
2020-12-19 12:22:41.260 13378-14982/? D/UploadsStorageManager: notifyObserversNow
2020-12-19 12:22:41.261 13378-13378/? V/UploadsStorageManager: getUploads() got 0 rows from page 1, 1 rows total so far, last ID 1
2020-12-19 12:22:41.261 13378-13378/? V/UploadsStorageManager: getUploads() returning 1 (1) rows after reading 2 pages
2020-12-19 12:22:41.263 13378-13378/? D/UploadsStorageManager: QUERY: status==1 AND last_result<>9 AND last_result<>13 AND last_result<>11 AND last_result<>14 AND account_name== ? ROWID: -1
2020-12-19 12:22:41.270 13378-13378/? V/UploadsStorageManager: getUploads() got 0 rows from page 0, 0 rows total so far, last ID -1
2020-12-19 12:22:41.270 13378-13378/? V/UploadsStorageManager: getUploads() returning 0 (0) rows after reading 1 pages
2020-12-19 12:22:41.273 13378-13378/? D/UploadsStorageManager: QUERY: status==2 AND account_name== ? ROWID: -1
2020-12-19 12:22:41.276 13378-14982/? D/UploadsStorageManager: QUERY: null ROWID: -1
2020-12-19 12:22:41.277 13378-13378/? V/UploadsStorageManager: getUploads() got 0 rows from page 0, 0 rows total so far, last ID -1
2020-12-19 12:22:41.277 13378-13378/? V/UploadsStorageManager: getUploads() returning 0 (0) rows after reading 1 pages
2020-12-19 12:22:41.277 13378-13378/? D/UploadListAdapter: loadUploadItemsFromDb
2020-12-19 12:22:41.280 13378-13378/? D/UploadsStorageManager: QUERY: status==0 OR last_result==9 OR last_result==13 OR last_result==11 OR last_result==14 AND account_name== ? ROWID: -1
2020-12-19 12:22:41.281 13378-14982/? V/UploadsStorageManager: getUploads() got 1 rows from page 0, 1 rows total so far, last ID 1
2020-12-19 12:22:41.281 13378-14982/? D/UploadsStorageManager: QUERY: _id < ? ROWID: 1
2020-12-19 12:22:41.286 13378-13378/? V/UploadsStorageManager: getUploads() got 1 rows from page 0, 1 rows total so far, last ID 1
2020-12-19 12:22:41.286 13378-13378/? D/UploadsStorageManager: QUERY: (status==0 OR last_result==9 OR last_result==13 OR last_result==11 OR last_result==14 AND account_name== ?) AND _id < ? ROWID: 1
2020-12-19 12:22:41.287 13378-14982/? V/UploadsStorageManager: getUploads() got 0 rows from page 1, 1 rows total so far, last ID 1
2020-12-19 12:22:41.287 13378-14982/? V/UploadsStorageManager: getUploads() returning 1 (1) rows after reading 2 pages
2020-12-19 12:22:41.287 13378-14982/? V/UploadsStorageManager: Updating /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/besen@cloud2.mydomain.com/.SeedVaultAndroidBackup/1608335875857/.backup.metadata with status=UPLOAD_IN_PROGRESS
2020-12-19 12:22:41.290 13378-13378/? V/UploadsStorageManager: getUploads() got 0 rows from page 1, 1 rows total so far, last ID 1
2020-12-19 12:22:41.290 13378-13378/? V/UploadsStorageManager: getUploads() returning 1 (1) rows after reading 2 pages
2020-12-19 12:22:41.291 13378-14982/? D/UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/besen@cloud2.mydomain.com/.SeedVaultAndroidBackup/1608335875857/.backup.metadata
2020-12-19 12:22:41.291 13378-14982/? D/UploadsStorageManager: notifyObserversNow
2020-12-19 12:22:41.292 13378-13378/? D/UploadsStorageManager: QUERY: status==1 AND last_result<>9 AND last_result<>13 AND last_result<>11 AND last_result<>14 AND account_name== ? ROWID: -1
2020-12-19 12:22:41.299 13378-13378/? V/UploadsStorageManager: getUploads() got 0 rows from page 0, 0 rows total so far, last ID -1
2020-12-19 12:22:41.299 13378-13378/? V/UploadsStorageManager: getUploads() returning 0 (0) rows after reading 1 pages
2020-12-19 12:22:41.302 13378-13378/? D/UploadsStorageManager: QUERY: status==2 AND account_name== ? ROWID: -1
2020-12-19 12:22:41.306 13378-13378/? V/UploadsStorageManager: getUploads() got 0 rows from page 0, 0 rows total so far, last ID -1
2020-12-19 12:22:41.306 13378-13378/? V/UploadsStorageManager: getUploads() returning 0 (0) rows after reading 1 pages
2020-12-19 12:22:41.326 13378-14982/? D/UploadFileOperation: normal upload
2020-12-19 12:22:41.328 13378-13378/? D/FileUploader: Starting command with id 19
2020-12-19 12:22:41.333 13378-14982/? D/AdvancedSslSocketFactory: Creating SSL Socket with remote cloud2.mydomain.com:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@8961e35
2020-12-19 12:22:41.333 13378-14982/? D/AdvancedSslSocketFactory:  ... with connection timeout 0 and socket timeout 0
2020-12-19 12:22:41.333 13378-14982/? I/ServerNameIndicator: SNI done, hostname: cloud2.mydomain.com
2020-12-19 12:22:41.430 1498-1498/? D/NotificationService: 0|com.nextcloud.client|411|null|10165: granting content://settings/system/notification_sound
2020-12-19 12:22:41.431 1498-1498/? I/chatty: uid=1000(system) Binder:1498_3 identical 1 line
2020-12-19 12:22:41.432 1498-1498/? D/NotificationService: 0|com.nextcloud.client|411|null|10165: granting content://settings/system/notification_sound
2020-12-19 12:22:41.434 1498-1498/? W/NotificationHistory: Attempted to add notif for locked/gone/disabled user 0
2020-12-19 12:22:41.451 2363-2363/? D/InterruptionStateProvider: No bubble up: not allowed to bubble: 0|com.nextcloud.client|411|null|10165
2020-12-19 12:22:41.452 2363-2363/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.nextcloud.client|411|null|10165
2020-12-19 12:22:41.490 2363-2363/? D/InterruptionStateProvider: No bubble up: not allowed to bubble: 0|com.nextcloud.client|411|null|10165
2020-12-19 12:22:41.492 2363-2363/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.nextcloud.client|411|null|10165
2020-12-19 12:22:41.543 2363-2363/? D/InterruptionStateProvider: No bubble up: not allowed to bubble: 0|com.nextcloud.client|411|null|10165
2020-12-19 12:22:41.544 2363-2363/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.nextcloud.client|411|null|10165
2020-12-19 12:22:41.605 13378-14982/? D/UploadFileOperation: Checking name collision in server
2020-12-19 12:22:41.605 13378-14982/? D/OwnCloudClient #0: REQUEST HEAD /remote.php/webdav/.SeedVaultAndroidBackup/1608335875857/.backup.metadata
2020-12-19 12:22:41.606 13378-14982/? D/AdvancedSslSocketFactory: Creating SSL Socket with remote cloud2.mydomain.com:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@9838520
2020-12-19 12:22:41.606 13378-14982/? D/AdvancedSslSocketFactory:  ... with connection timeout 50000 and socket timeout 50000
2020-12-19 12:22:41.606 13378-14982/? I/ServerNameIndicator: SNI done, hostname: cloud2.mydomain.com
2020-12-19 12:22:42.115 13378-14982/? D/ExistenceCheckRemoteOperation: Existence check for https://cloud2.mydomain.com/remote.php/webdav/.SeedVaultAndroidBackup/1608335875857/.backup.metadata targeting for  existence finished with HTTP status 200
2020-12-19 12:22:42.115 13378-14982/? D/UploadFileOperation: Overwriting file
2020-12-19 12:22:42.131 13378-14982/? D/UploadsStorageManager: QUERY: null ROWID: -1
2020-12-19 12:22:42.143 854-930/? D/VSC: @ 163647.252: [WO] tilt angle 89
2020-12-19 12:22:42.144 13378-14982/? V/UploadsStorageManager: getUploads() got 1 rows from page 0, 1 rows total so far, last ID 1
2020-12-19 12:22:42.145 13378-14982/? D/UploadsStorageManager: QUERY: _id < ? ROWID: 1
2020-12-19 12:22:42.156 13378-14982/? V/UploadsStorageManager: getUploads() got 0 rows from page 1, 1 rows total so far, last ID 1
2020-12-19 12:22:42.156 13378-14982/? V/UploadsStorageManager: getUploads() returning 1 (1) rows after reading 2 pages
2020-12-19 12:22:42.157 13378-14982/? V/UploadsStorageManager: Updating /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/besen@cloud2.mydomain.com/.SeedVaultAndroidBackup/1608335875857/.backup.metadata with status=UPLOAD_IN_PROGRESS
2020-12-19 12:22:42.168 13378-14982/? D/UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/besen@cloud2.mydomain.com/.SeedVaultAndroidBackup/1608335875857/.backup.metadata
2020-12-19 12:22:42.168 13378-14982/? D/UploadsStorageManager: notifyObserversNow
2020-12-19 12:22:42.173 13378-14982/? D/OwnCloudClient #0: REQUEST PUT /remote.php/webdav/.SeedVaultAndroidBackup/1608335875857/.backup.metadata
2020-12-19 12:22:42.417 2363-2363/? D/InterruptionStateProvider: No bubble up: not allowed to bubble: 0|com.nextcloud.client|411|null|10165
2020-12-19 12:22:42.418 2363-2363/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.nextcloud.client|411|null|10165
2020-12-19 12:22:42.729 13378-14982/? D/RemoteOperationResult: RemoteOperationResult has processed UNHANDLED_HTTP_CODE: 400 Bad Request
2020-12-19 12:22:42.730 13378-14982/? E/UploadFileOperation: Upload of /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/besen@cloud2.mydomain.com/.SeedVaultAndroidBackup/1608335875857/.backup.metadata to /.SeedVaultAndroidBackup/1608335875857/.backup.metadata: Operation finished with HTTP status code 400 (fail)
2020-12-19 12:22:42.730 13378-14982/? D/UploadsStorageManager: updateDatabaseUploadResult uploadResult: RemoteOperationResult(mSuccess=false, mHttpCode=400, mHttpPhrase=Bad Request, mException=null, mCode=UNHANDLED_HTTP_CODE, getLogMessage=Operation finished with HTTP status code 400 (fail)) upload: com.owncloud.android.operations.UploadFileOperation@843b196
2020-12-19 12:22:42.738 13378-14982/? V/UploadsStorageManager: Updating /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/besen@cloud2.mydomain.com/.SeedVaultAndroidBackup/1608335875857/.backup.metadata with status:UPLOAD_FAILED and result:UNKNOWN (old:/storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/besen@cloud2.mydomain.com/.SeedVaultAndroidBackup/1608335875857/.backup.metadata status:UPLOAD_IN_PROGRESS result:-1)
2020-12-19 12:22:42.738 13378-14982/? V/UploadsStorageManager: Updating /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/besen@cloud2.mydomain.com/.SeedVaultAndroidBackup/1608335875857/.backup.metadata with status=UPLOAD_FAILED
2020-12-19 12:22:42.747 13378-14982/? D/UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/besen@cloud2.mydomain.com/.SeedVaultAndroidBackup/1608335875857/.backup.metadata
2020-12-19 12:22:42.748 13378-14982/? D/UploadsStorageManager: notifyObserversNow
2020-12-19 12:22:42.749 13378-14982/? D/FileUploader: NotifyUploadResult with resultCode: UNHANDLED_HTTP_CODE
2020-12-19 12:22:42.755 13378-14982/? D/FileUploader: Stopping command after id 18
2020-12-19 12:22:42.755 13378-13378/? D/UploadListAdapter: loadUploadItemsFromDb

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
> [PHP] Error: Error: Cannot modify header information - headers already sent by (output started at /var/www/html/3rdparty/sabre/http/lib/Sapi.php:132) at /var/www/html/apps/dav/lib/Connector/Sabre/File.php#691 at <<closure>>

This sounds like you have a problem with your server…
Please check with help.nextcloud.com and re-open if there is still a problem with this app even when this error is gone.

**Comment by besendorf** [comment]
I created a thread on help.nextcloud.com but didnt get any response.
 https://help.nextcloud.com/t/specific-file-always-fails-to-upload/103784

Multiple people seem to have the same issue though. See here:
https://github.com/seedvault-app/seedvault/issues/184

**Comment by besendorf** [comment]
I still experience the issue. Here's a logcat from today. This error leads to a lot of app crashes every other minute and really prevents me from using my phone regulary.
@tobiasKaminsky could you reopen this please? Do you need more information from me?
```
021-07-14 15:19:37.557 5223-5301/? E/ReadFileRemoteOperation: Read file /.SeedVaultAndroidBackup/1608335875857/kv/@pm@/Y29tLmFuZHJvaWQud2FsbHBhcGVyY3JvcHBlcg failed: Socket timeout exception
    java.net.SocketTimeoutException: failed to connect to cloud2.besendorf.org/2a02:8109:8880:4a01:5551:a436:742b:8edd (port 443) from /2a02:8109:8880:4a01:1c44:a4:7e81:a056 (port 40057) after 5000ms
        at libcore.io.IoBridge.connectErrno(IoBridge.java:190)
        at libcore.io.IoBridge.connect(IoBridge.java:134)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
        at java.net.Socket.connect(Socket.java:621)
        at org.conscrypt.AbstractConscryptSocket.connect(AbstractConscryptSocket.java:155)
        at com.owncloud.android.lib.common.network.AdvancedSslSocketFactory.createSocket(AdvancedSslSocketFactory.java:186)
        at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
        at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
        at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:219)
        at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:190)
        at com.owncloud.android.lib.resources.files.ReadFileRemoteOperation.run(ReadFileRemoteOperation.java:84)
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:183)
        at com.owncloud.android.operations.SynchronizeFileOperation.run(SynchronizeFileOperation.java:195)
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:139)
        at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:66)
        at com.nextcloud.client.jobs.OfflineSyncWork.recursive(OfflineSyncWork.kt:118)
        at com.nextcloud.client.jobs.OfflineSyncWork.recursive(OfflineSyncWork.kt:125)
        at com.nextcloud.client.jobs.OfflineSyncWork.recursive(OfflineSyncWork.kt:125)
        at com.nextcloud.client.jobs.OfflineSyncWork.recursive(OfflineSyncWork.kt:125)
        at com.nextcloud.client.jobs.OfflineSyncWork.recursive(OfflineSyncWork.kt:125)
        at com.nextcloud.client.jobs.OfflineSyncWork.doWork(OfflineSyncWork.kt:68)
        at androidx.work.Worker$1.run(Worker.java:85)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

**Comment by Janosch** [comment]
@besendorf On my device, the problem disappeared. I suspect the upgrade from Nextcloud App 3.16.0 to 3.16.1 fixed it. Are you running 3.16.1?

**Comment by besendorf** [comment]
Im also on 3.16.1. but the error is still the same

**Comment by guttermonk** [comment]
I'm also on Nextcloud version 3.16.1 and still having this issue.

**Comment by AnaTool** [comment]
Same issue. anyone found a solution ? newest graphenOS, newest Nextcloud App, newest Nextcloud Server Installation. localbackup works but upload to nextcloud fails.

**Comment by alexanderadam** [comment]
Still an issue in end of 2023 :man_shrugging:

**Comment by besendorf** [comment]
@tobiasKaminsky could you please consider reopening this?
