### ISSUE TITLE
Android crash: app tried to file issue directly, but I am not logged in to GitHub on my phone

### ISSUE THREAD

**Issue by shankari** [nextcloud/android#7701]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.recyclerview.widget.RecyclerView$LayoutManager androidx.recyclerview.widget.RecyclerView.getLayoutManager()' on a null object reference
 at com.owncloud.android.ui.fragment.ExtendedListFragment.isGridEnabled(ExtendedListFragment.java:188)
 at com.owncloud.android.ui.fragment.ExtendedListFragment.onSaveInstanceState(ExtendedListFragment.java:467)
 at com.owncloud.android.ui.fragment.OCFileListFragment.onSaveInstanceState(OCFileListFragment.java:780)
 at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2864)
 at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:434)
 at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:400)
 at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:143)
 at androidx.fragment.app.FragmentManager.saveAllState(FragmentManager.java:2398)
 at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:152)
 at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:512)
 at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:544)
 at com.owncloud.android.ui.activity.DrawerActivity.onSaveInstanceState(DrawerActivity.java:841)
 at com.owncloud.android.ui.activity.FileActivity.onSaveInstanceState(FileActivity.java:280)
 at com.owncloud.android.ui.activity.FileDisplayActivity.onSaveInstanceState(FileDisplayActivity.java:1102)
 at android.app.Activity.performSaveInstanceState(Activity.java:1414)
 at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1300)
 at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4505)
 at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3827)
 at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3886)
 at android.app.ActivityThread.-wrap25(ActivityThread.java)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:154)
 at android.app.ActivityThread.main(ActivityThread.java:6077)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: shamu
Model: Nexus 6
Id: NBD92G
Product: shamu

************ FIRMWARE ************
SDK: 24
Release: 7.0
Incremental: 3754298

**Comment by tobiasKaminsky** [comment]
Do you know when this happened? Can you reproduce it?

**Comment by shankari** [comment]
@tobiasKaminsky This has not happened since the original bug report. So it is definitely not very reproducible. If it happens again, I can reopen the bug with additional information.
