### ISSUE TITLE
Appcrash on open

### ISSUE THREAD

**Issue by breemts** [nextcloud/android#7704]
Don't know what caused the app crash, but it keeps crashing on ever load.
Worked fine for a while, than did some file changes in the web and now I'm stuck with this error.

```
Insert your Nextcloud log here
************ CAUSE OF ERROR ************

android.database.CursorIndexOutOfBoundsException: Index -1 requested, with a size of 3583
	at android.database.AbstractCursor.checkPosition(Unknown Source:21)
	at android.database.AbstractWindowedCursor.checkPosition(Unknown Source:0)
	at android.database.AbstractWindowedCursor.getLong(Unknown Source:0)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:179)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProviderOperation.apply(Unknown Source:73)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:672)
	at android.content.ContentProvider$Transport.applyBatch(Unknown Source:111)
	at android.content.ContentProviderClient.applyBatch(Unknown Source:13)
	at android.content.ContentResolver.applyBatch(Unknown Source:44)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:438)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:519)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:401)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:237)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: dreamlte
Model: SM-G950F
Id: R16NW
Product: dreamltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: G950FXXU4CRL3
```

**Comment by tobiasKaminsky** [comment]
Might be #6688

**Comment by breemts** [comment]
thanks for having a look at it. I tried to clean data and reinstall the app but always got the error. Then I uninstalled the nextcloud talk app. After that a clean install of the nextcloud app got it working again.
Currently I can't reproduce the issue. So I will close this until I ran into it again and can provide some more information.
