### ISSUE TITLE
Login with qrcode crash on android oneplus6t

### ISSUE THREAD

**Issue by jpsarda** [nextcloud/android#7709]
### Steps to reproduce
1. Just installed a fresh version of nextcloud on my own server (debian 9)
2. Downloaded the app on android
3. Try to login with qrcode

### Expected behaviour
- Loigin

### Actual behaviour
- Crash/Android exception

### Can you reproduce this problem on https://try.nextcloud.com?
- Can't login on mobile app with try.nextcloud.com as far as I can know.

```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.setVisibility(int)' on a null object reference
	at com.owncloud.android.authentication.AuthenticatorActivity.onAuthenticatorTaskCallback(AuthenticatorActivity.java:1186)
	at com.owncloud.android.authentication.AuthenticatorAsyncTask.onPostExecute(AuthenticatorAsyncTask.java:100)
	at com.owncloud.android.authentication.AuthenticatorAsyncTask.onPostExecute(AuthenticatorAsyncTask.java:43)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.access$600(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6863)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus6T
Model: ONEPLUS A6013
Id: PKQ1.180716.001
Product: OnePlus6T

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 1904032100
```

Reverse proxy:

#### Web server error log
```
No errors server side
```

#### Nextcloud log (data/nextcloud.log)
```
Nothing on nexcloud.log for this error
```

**Comment by jpsarda** [comment]
Not sure why I had installed an old version of the server, updating the server to v20 fixed it.
