### ISSUE TITLE
Nextcloud Android App crashed upon opening a .mov file

### ISSUE THREAD

**Issue by Fanboy-Studios** [nextcloud/android#7725]
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{4298456 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1745)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: p4notewifi
Model: GT-N8010
Id: PQ3A.190801.002
Product: p4notewifiue

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: eng.html64.20201215.154434

**Comment by Fanboy-Studios** [comment]
I shoul add that I'm using Lineage OS 16 on my Galaxy Note 10.1, rather than the old Stock TouchWiz Android 4.3 firmware.

**Comment by AndyScherzinger** [comment]
Can you please update to 3.14.1 available on Google Play that should contain a fix?
