### ISSUE TITLE
Crash upon opening the app

### ISSUE THREAD

**Issue by gerroon** [nextcloud/android#7726]
### Steps to reproduce
1. Open the app

```

************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lokio/Buffer;
	at okhttp3.ResponseBody.create(ResponseBody.java:210)
	at okhttp3.internal.Util.<clinit>(Util.java:62)
	at okhttp3.Credentials.basic(Credentials.java:30)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:330)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:304)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:276)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:229)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "okio.Buffer" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nextcloud.android.beta-mzvukMKVz6rcAK-bZ7rveg==/base.apk"],nativeLibraryDirectories=[/data/app/com.nextcloud.android.beta-mzvukMKVz6rcAK-bZ7rveg==/lib/arm, /data/app/com.nextcloud.android.beta-mzvukMKVz6rcAK-bZ7rveg==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 10 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20201216
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: samsung
Device: treltexx
Id:
Product: treltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: f841079da7


```

**Comment by AndyScherzinger** [comment]
This has been fixed with 20201223,please update.
