### ISSUE TITLE
Nextcloud App crashes

### ISSUE THREAD

**Issue by wehrstedt** [nextcloud/android#7732]
### Steps to reproduce
Tried to move around 50 images from one folder to another via the app and got this exception:
```
************ CAUSE OF ERROR ************

java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 262000 free bytes and 255KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 239337472 bytes)
	at java.lang.Class.getDeclaredField(Native Method)
	at com.google.android.gms.org.conscrypt.Platform.getFileDescriptor(:com.google.android.gms@204516037@20.45.16 (120400-344294571):1)
	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(:com.google.android.gms@204516037@20.45.16 (120400-344294571):6)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:248)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:288)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
	at org.apache.commons.httpclient.ChunkedInputStream.read(ChunkedInputStream.java:182)
	at org.apache.commons.httpclient.ChunkedInputStream.read(ChunkedInputStream.java:196)
	at org.apache.commons.httpclient.ChunkedInputStream.exhaustInputStream(ChunkedInputStream.java:369)
	at org.apache.commons.httpclient.ChunkedInputStream.close(ChunkedInputStream.java:346)
	at java.io.FilterInputStream.close(FilterInputStream.java:181)
	at org.apache.commons.httpclient.AutoCloseInputStream.notifyWatcher(AutoCloseInputStream.java:194)
	at org.apache.commons.httpclient.AutoCloseInputStream.close(AutoCloseInputStream.java:158)
	at sun.nio.cs.StreamDecoder.implClose(StreamDecoder.java:423)
	at sun.nio.cs.StreamDecoder.close(StreamDecoder.java:196)
	at java.io.InputStreamReader.close(InputStreamReader.java:199)
	at com.android.org.kxml2.io.KXmlParser.close(KXmlParser.java:1757)
	at libcore.io.IoUtils.closeQuietly(IoUtils.java:165)
	at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:155)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:107)
	at org.apache.jackrabbit.webdav.xml.DomUtil.parseDocument(DomUtil.java:104)
	at org.apache.jackrabbit.webdav.client.methods.DavMethodBase.getResponseBodyAsDocument(DavMethodBase.java:113)
	at org.apache.jackrabbit.webdav.client.methods.DavMethodBase.getRootElement(DavMethodBase.java:137)
	at org.apache.jackrabbit.webdav.client.methods.DavMethodBase.processResponseBody(DavMethodBase.java:282)
	at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1749)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:219)
	at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.run(ReadFolderRemoteOperation.java:80)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:184)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:397)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:237)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: beyond1
Model: SM-G973F
Id: QP1A.190711.020
Product: beyond1lteeea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G973FXXS9DTK9
```

### Expected behaviour
- Tell 

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by wehrstedt** [comment]
Again, deleting images...

```
************ CAUSE OF ERROR ************

java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 262000 free bytes and 255KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 239337472 bytes)
	at java.lang.Class.getDeclaredField(Native Method)
	at com.google.android.gms.org.conscrypt.Platform.getFileDescriptor(:com.google.android.gms@204516037@20.45.16 (120400-344294571):1)
	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(:com.google.android.gms@204516037@20.45.16 (120400-344294571):6)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:248)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:288)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
	at org.apache.commons.httpclient.ChunkedInputStream.read(ChunkedInputStream.java:182)
	at org.apache.commons.httpclient.ChunkedInputStream.read(ChunkedInputStream.java:196)
	at org.apache.commons.httpclient.ChunkedInputStream.exhaustInputStream(ChunkedInputStream.java:369)
	at org.apache.commons.httpclient.ChunkedInputStream.close(ChunkedInputStream.java:346)
	at java.io.FilterInputStream.close(FilterInputStream.java:181)
	at org.apache.commons.httpclient.AutoCloseInputStream.notifyWatcher(AutoCloseInputStream.java:194)
	at org.apache.commons.httpclient.AutoCloseInputStream.close(AutoCloseInputStream.java:158)
	at sun.nio.cs.StreamDecoder.implClose(StreamDecoder.java:423)
	at sun.nio.cs.StreamDecoder.close(StreamDecoder.java:196)
	at java.io.InputStreamReader.close(InputStreamReader.java:199)
	at com.android.org.kxml2.io.KXmlParser.close(KXmlParser.java:1757)
	at libcore.io.IoUtils.closeQuietly(IoUtils.java:165)
	at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:155)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:107)
	at org.apache.jackrabbit.webdav.xml.DomUtil.parseDocument(DomUtil.java:104)
	at org.apache.jackrabbit.webdav.client.methods.DavMethodBase.getResponseBodyAsDocument(DavMethodBase.java:113)
	at org.apache.jackrabbit.webdav.client.methods.DavMethodBase.getRootElement(DavMethodBase.java:137)
	at org.apache.jackrabbit.webdav.client.methods.DavMethodBase.processResponseBody(DavMethodBase.java:282)
	at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1749)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:219)
	at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.run(ReadFolderRemoteOperation.java:80)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:184)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:397)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:237)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: beyond1
Model: SM-G973F
Id: QP1A.190711.020
Product: beyond1lteeea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G973FXXS9DTK9
```

**Comment by tobiasKaminsky** [comment]
Seems that your phone just ran out of memory, which is strange as it is a recent enough device…

Can you reproduce it, or is it random?

**Comment by wehrstedt** [comment]
Yes, I just selected 60 images and tried to move them to an other folder. After click on "choose folder" (i dont know if its the english Label) the App returns to the origin folder where i selected the files to move. Then the App starts moving the files in the background. While it is working, i just scroll up and down, up and down... In the same folder. Then, randomly the files i moved disappears and Show up again. 

Steps:
1. Select 60 files
2. Move them to an other folder
3. Wait until the App open the folder where you selected the files you want to move
4. Scroll up and down randomly
-> throbber Shows up and disappears randomly
-> files i had selected to move Shows up and disappears randomly
-> App crashes

**Comment by wehrstedt** [comment]
After I wrote this comment, I opened the App again. The files were all moved to the selected folder

**Comment by wehrstedt** [comment]
https://user-images.githubusercontent.com/27811714/107864338-7a6d6100-6e5b-11eb-839d-6c70677d69da.mp4

**Comment by tobiasKaminsky** [comment]
This is an out of memory crash.
So maybe the app was consuming a bit too much memory, or there were too many other apps occupying memory.

Good to hear that it in the end worked.

**Comment by wehrstedt** [comment]
Well, its not really working .. I can reproduce this error pretty reliably by just scrolling up and down when moving files. Currently my phone use 3.7 GB of 8 GB RAM. And i was not executing some heavy calculations in the background ...

**Comment by tobiasKaminsky** [comment]
Is the source or the target folder big? In terms of has many files in it?

**Comment by joshtrichards** [comment]
Tracking in #9903
