### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Lokio/Buffer

### ISSUE THREAD

**Issue by gajanak** [nextcloud/android#7733]
### Steps to reproduce
1. Open App
The daily Beta Version was Wirkung until today .
Means the Missing library Problem was not there after Installation sind dass ago.

### Expected behaviour
- menu Main view

### Actual behaviour
- exception lese Seconds after Open of App.

************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lokio/Buffer;
	at okhttp3.ResponseBody.create(ResponseBody.java:210)
	at okhttp3.internal.Util.<clinit>(Util.java:62)
	at okhttp3.Credentials.basic(Credentials.java:30)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:330)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:304)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:276)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:229)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassNotFoundException: okio.Buffer
	... 10 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20201216
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus5
Model: ONEPLUS A5000
Id: QKQ1.191014.012
Product: OnePlus5

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2010292059

**Comment by AndyScherzinger** [comment]
This has been fixed with build 20201223, please update.
