### ISSUE TITLE
Not a single time opens

### ISSUE THREAD

**Issue by selva-1106** [nextcloud/android#7738]
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lokio/Buffer;
	at okhttp3.ResponseBody.create(ResponseBody.java:210)
	at okhttp3.internal.Util.<clinit>(Util.java:62)
	at okhttp3.Credentials.basic(Credentials.java:30)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:330)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:304)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:276)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:229)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassNotFoundException: okio.Buffer
	... 10 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20201216
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: samsung
Device: a30
Model: SM-A305F
Id: QP1A.190711.020
Product: a30dd

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: A305FDDU6BTJ2

**Comment by AndyScherzinger** [comment]
Update to version 20201223 which ships a fix for this bug
