### ISSUE TITLE
Bug  Google Pixel 3

### ISSUE THREAD

**Issue by michael1999crypto** [nextcloud/android#7740]
************ CAUSE OF ERROR ************

java.lang.NoClassDefFoundError: Failed resolution of: Lokio/Buffer;
	at okhttp3.ResponseBody.create(ResponseBody.java:210)
	at okhttp3.internal.Util.<clinit>(Util.java:62)
	at okhttp3.Credentials.basic(Credentials.java:30)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:330)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:304)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:276)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:229)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.ClassNotFoundException: okio.Buffer
	... 10 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20201216
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Android
Device: blueline
Model: Pixel 3
Id: RQ1A.201205.003
Product: aosp_blueline

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 2020.12.12.03

**Comment by AndyScherzinger** [comment]
Please update to latest Dev version, 20201223 which ships a fix for this issue
