### ISSUE TITLE
Error with Status

### ISSUE THREAD

**Issue by Tulskie** [nextcloud/android#7741]
### Steps to reproduce
1. ************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Fragment SetStatusDialogFragment{4198423} (0632921a-0e5b-4e54-a475-d98ff3407c37)} not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:805)
	at androidx.fragment.app.Fragment.getResources(Fragment.java:869)
	at com.nextcloud.ui.SetStatusDialogFragment.clearTopStatus(SetStatusDialogFragment.kt:347)
	at com.nextcloud.ui.SetStatusDialogFragment.access$clearTopStatus(SetStatusDialogFragment.kt:86)
	at com.nextcloud.ui.SetStatusDialogFragment$setStatus$1.invoke(SetStatusDialogFragment.kt:317)
	at com.nextcloud.ui.SetStatusDialogFragment$setStatus$1.invoke(SetStatusDialogFragment.kt:86)
	at com.nextcloud.client.core.Task$run$1.run(Task.kt:54)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a51
Model: SM-A515F
Id: QP1A.190711.020
Product: a51nseea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: A515FXXU4CTJ1

2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by ezaquarii** [comment]
Looks like a lifecycle issue. I'll take a look.

**Comment by fto77533** [comment]
java.lang.IllegalStateException: Fragment SetStatusDialogFragment {4198423} (0632921a-0e5b-4e54-a475-d98ff3407c37)} غ

**Comment by ezaquarii** [comment]
@tobiasKaminsky @AndyScherzinger I think it can be safely backported to next point release

/backport to stable-3.14

**Comment by ezaquarii** [comment]
@tobiasKaminsky @AndyScherzinger I think it can be safely backported to next point release

**Comment by Tulskie** [comment]
Thank you for fixing the error.


⁣TypeApp for Android herunterladen ​
