### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by dinaesh** [nextcloud/android#7743]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lokio/Buffer;
	at okhttp3.ResponseBody.create(ResponseBody.java:210)
	at okhttp3.internal.Util.<clinit>(Util.java:62)
	at okhttp3.Credentials.basic(Credentials.java:30)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.nextcloud.client.network.ClientFactoryImpl.createNextcloudClient(ClientFactoryImpl.java:61)
	at com.owncloud.android.ui.asynctasks.RetrieveStatusAsyncTask.doInBackground(RetrieveStatusAsyncTask.java:55)
	at com.owncloud.android.ui.asynctasks.RetrieveStatusAsyncTask.doInBackground(RetrieveStatusAsyncTask.java:39)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
Caused by: java.lang.ClassNotFoundException: okio.Buffer
	... 13 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20201216
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: rolex
Model: Redmi 4A
Id: RD1A.201105.003.C1
Product: rolex

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: eng.buildb.20201123.084942

**Comment by tobiasKaminsky** [comment]
Does this still happens with latest dev version?
