### ISSUE TITLE
Exception when sharing from gallery (file browser works)

### ISSUE THREAD

**Issue by asmw** [nextcloud/android#7745]
### Steps to reproduce
1. Open gallery app (I tried the builtin LineageOS gallery and Simple Gallery Pro from fdroid)
2. Share one picture to nextcloud
3. Pick any folder
3. Click upload
(Note that sharing from the builtin File Browser works!)

### Expected behaviour
- The image is uploaded to the folder

### Actual behaviour
- Nothing, logcat error see below

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10.0

Device model: Oneplus 6

Stock or customized system: LineageOS 17.1

Nextcloud app version: 3.14.1

Nextcloud server version: 20.0.4 (snap)

Reverse proxy:

#### ADB log
```
12-28 13:43:30.783  8412 25382 E CopyAndUploadContentUrisTask: Exception while copying content://media/external/images/media/43610 to temporary file
12-28 13:43:30.783  8412 25382 E CopyAndUploadContentUrisTask: java.lang.IllegalArgumentException: column 'last_modified' does not exist. Available columns: [instance_id, duration, description, picasa_id, latitude, orientation, height, is_drm, bucket_display_name, owner_package_name, volume_name, date_modified, date_expires, _display_name, datetaken, mime_type, _id, _data, _hash, _size, title, width, longitude, is_trashed, group_id, document_id, is_pending, date_added, mini_thumb_magic, primary_directory, secondary_directory, isprivate, original_document_id, bucket_id, relative_path]
12-28 13:43:30.783  8412 25382 E CopyAndUploadContentUrisTask: 	at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:352)
12-28 13:43:30.783  8412 25382 E CopyAndUploadContentUrisTask: 	at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:91)
12-28 13:43:30.783  8412 25382 E CopyAndUploadContentUrisTask: 	at com.owncloud.android.ui.asynctasks.CopyAndUploadContentUrisTask.doInBackground(CopyAndUploadContentUrisTask.java:156)
12-28 13:43:30.783  8412 25382 E CopyAndUploadContentUrisTask: 	at com.owncloud.android.ui.asynctasks.CopyAndUploadContentUrisTask.doInBackground(CopyAndUploadContentUrisTask.java:49)
12-28 13:43:30.783  8412 25382 E CopyAndUploadContentUrisTask: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
12-28 13:43:30.783  8412 25382 E CopyAndUploadContentUrisTask: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-28 13:43:30.783  8412 25382 E CopyAndUploadContentUrisTask: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
12-28 13:43:30.783  8412 25382 E CopyAndUploadContentUrisTask: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-28 13:43:30.783  8412 25382 E CopyAndUploadContentUrisTask: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-28 13:43:30.783  8412 25382 E CopyAndUploadContentUrisTask: 	at java.lang.Thread.run(Thread.java:919)
```

#### Web server error log
No remote communication happens

**Comment by asmw** [comment]
I reproduced this on a stock Galaxy Tab S2 running Android 7, except on that device sharing from the builtin file browser did also NOT work.

Exception looks similar:
```
12-28 13:56:41.477 10445 12041 E CopyAndUploadContentUrisTask: Exception while copying content://0@media/external/images/media/902 to temporary file
12-28 13:56:41.477 10445 12041 E CopyAndUploadContentUrisTask: java.lang.IllegalArgumentException: column 'last_modified' does not exist
12-28 13:56:41.477 10445 12041 E CopyAndUploadContentUrisTask: 	at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:333)
12-28 13:56:41.477 10445 12041 E CopyAndUploadContentUrisTask: 	at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:87)
12-28 13:56:41.477 10445 12041 E CopyAndUploadContentUrisTask: 	at com.owncloud.android.ui.asynctasks.CopyAndUploadContentUrisTask.doInBackground(CopyAndUploadContentUrisTask.java:156)
12-28 13:56:41.477 10445 12041 E CopyAndUploadContentUrisTask: 	at com.owncloud.android.ui.asynctasks.CopyAndUploadContentUrisTask.doInBackground(CopyAndUploadContentUrisTask.java:49)
12-28 13:56:41.477 10445 12041 E CopyAndUploadContentUrisTask: 	at android.os.AsyncTask$2.call(AsyncTask.java:304)
12-28 13:56:41.477 10445 12041 E CopyAndUploadContentUrisTask: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-28 13:56:41.477 10445 12041 E CopyAndUploadContentUrisTask: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
12-28 13:56:41.477 10445 12041 E CopyAndUploadContentUrisTask: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
12-28 13:56:41.477 10445 12041 E CopyAndUploadContentUrisTask: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
12-28 13:56:41.477 10445 12041 E CopyAndUploadContentUrisTask: 	at java.lang.Thread.run(Thread.java:762)

```

**Comment by af7567** [comment]
I have this same bug on my Pixel 3a with stock Android 11.
I can use the share dialog from another app, then select to share by nextcloud and select/create a folder on the nextcloud server. But when tapping the upload button it just closes and nothing is uploaded.

```
2020-12-29 13:54:46.369 10572-10572/? D/ReceiveExternalFilesActivity: Uploading file to dir /Galaxyscreen/
2020-12-29 13:54:46.391 10572-10572/? D/FileActivity: show loading dialog
2020-12-29 13:54:46.431 10572-20166/? E/CopyAndUploadContentUrisTask: Exception while copying content://media/external/images/media/48860 to temporary file
    java.lang.IllegalArgumentException: column 'last_modified' does not exist. Available columns: [instance_id, compilation, disc_number, duration, album_artist, description, picasa_id, resolution, latitude, orientation, artist, author, height, is_drm, bucket_display_name, owner_package_name, f_number, volume_name, date_modified, writer, date_expires, composer, _display_name, scene_capture_type, datetaken, mime_type, bitrate, cd_track_number, _id, iso, xmp, year, _data, _size, album, genre, title, width, longitude, is_favorite, is_trashed, exposure_time, group_id, document_id, generation_added, is_download, generation_modified, is_pending, date_added, mini_thumb_magic, capture_framerate, num_tracks, isprivate, original_document_id, bucket_id, relative_path]
        at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:351)
        at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:91)
        at com.owncloud.android.ui.asynctasks.CopyAndUploadContentUrisTask.doInBackground(CopyAndUploadContentUrisTask.java:156)
        at com.owncloud.android.ui.asynctasks.CopyAndUploadContentUrisTask.doInBackground(CopyAndUploadContentUrisTask.java:49)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2020-12-29 13:54:46.503 10572-10572/? D/ReceiveExternalFilesActivity: onPause() ending
2020-12-29 13:54:46.512 10572-10572/? D/FileActivity: dismiss loading dialog
```

**Comment by AndyScherzinger** [comment]
This issue has been fixed and will ship with the upcoming release 3.14.2

**Comment by asmw** [comment]
Awesome, thanks for your work @AndyScherzinger

**Comment by AndyScherzinger** [comment]
Fix has been done by @ezaquarii ❤️

**Comment by asmw** [comment]
Well then, thanks @ezaquarii. (I swear I'll shut up now, just very happy about you all)
