### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by lualcoda** [nextcloud/android#7757]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```

************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Not allowed to start service Intent { act=SYNC_FOLDER cmp=com.nextcloud.client/com.owncloud.android.services.OperationsService (has extras) }: app is in background uid UidRecord{4e18159 u0a151 TRNB bg:+1m39s281ms idle change:idle procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1810)
	at android.app.ContextImpl.startService(ContextImpl.java:1765)
	at android.content.ContextWrapper.startService(ContextWrapper.java:664)
	at com.owncloud.android.operations.SynchronizeFolderOperation.startSyncFolderOperation(SynchronizeFolderOperation.java:531)
	at com.owncloud.android.operations.SynchronizeFolderOperation.classifyFileForLaterSyncOrDownload(SynchronizeFolderOperation.java:380)
	at com.owncloud.android.operations.SynchronizeFolderOperation.synchronizeData(SynchronizeFolderOperation.java:328)
	at com.owncloud.android.operations.SynchronizeFolderOperation.fetchAndSyncRemoteFolder(SynchronizeFolderOperation.java:213)
	at com.owncloud.android.operations.SynchronizeFolderOperation.run(SynchronizeFolderOperation.java:139)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:184)
	at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:85)
	at com.owncloud.android.services.SyncFolderHandler.doOperation(SyncFolderHandler.java:121)
	at com.owncloud.android.services.SyncFolderHandler.handleMessage(SyncFolderHandler.java:90)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.os.HandlerThread.run(HandlerThread.java:65)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWJAT-M
Model: JAT-LX3
Id: HUAWEIJAT-LX3
Product: JAT-L03HW

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 9.1.0.339C605


```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Is this happening reliable?
Is this in background, or manually sync?

**Comment by lualcoda** [comment]
Manually

**Comment by tobiasKaminsky** [comment]
And reliable?
Is this is a special/big folder?
