### ISSUE TITLE
Crash on some selection

### ISSUE THREAD

**Issue by AllanChain** [nextcloud/android#7790]
### Steps to reproduce
1. click folder description
2. long press to select title
3. long press at the blank space after title

https://user-images.githubusercontent.com/36528777/103870410-a122d400-5106-11eb-837d-415084cd1be1.mp4

### Expected behaviour
- don't crash

### Actual behaviour
- crash

### Can you reproduce this problem on https://try.nextcloud.com?
I believe the bug is client-side

### Environment data

See log

### Logs

```
************ CAUSE OF ERROR ************

java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
	at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:442)
	at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:163)
	at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:152)
	at android.text.SpannableString.setSpan(SpannableString.java:46)
	at android.text.Selection.setSelection(Selection.java:76)
	at android.widget.Editor$SelectionModifierCursorController.resetDragAcceleratorState(Editor.java:5769)
	at android.widget.Editor$SelectionModifierCursorController.onTouchEvent(Editor.java:5620)
	at android.widget.Editor.onTouchEvent(Editor.java:1408)
	at android.widget.TextView.onTouchEvent(TextView.java:9916)
	at android.view.View.dispatchTouchEvent(View.java:11788)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:549)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1953)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3559)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:502)
	at android.view.View.dispatchPointerEvent(View.java:12027)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5304)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5093)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4588)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4641)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4607)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4734)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4615)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4791)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4588)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4641)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4607)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4615)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4588)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7195)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7169)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7130)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7351)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:379)
	at android.os.Looper.loop(Looper.java:144)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: honor
Device: HWFRD
Model: FRD-AL10
Id: HUAWEIFRD-AL10
Product: FRD-AL10

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: 556(C00)
```

#### Web server error log
I believe the bug is client-side

#### Nextcloud log (data/nextcloud.log)
I believe the bug is client-side

### Additional comment

This is a small bug that does not matter too much. But the less crashes, the better :)

**Comment by tobiasKaminsky** [comment]
Thanks for the video to reproduce the bug.
On my test devices this does not happen.

Judging from the stactrace this is in Android's internal methods.
I suspect this might be related to Android version and/or brand (honor).

Can you test it with another device?

**Comment by AllanChain** [comment]
Alright, seems bug of my android system. Cannot reproduce on a higher version of honor.
