### ISSUE TITLE
Client Crash when clicking "+" button

### ISSUE THREAD

**Issue by morpheus8111** [nextcloud/android#7796]
### Steps to reproduce
1.  Press the + Button let the application crashing every time

Backend 20.4

************ CAUSE OF ERROR ************

java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5260)
	at android.view.ViewGroup.addView(ViewGroup.java:5089)
	at android.view.ViewGroup.addView(ViewGroup.java:5029)
	at android.view.ViewGroup.addView(ViewGroup.java:5001)
	at com.owncloud.android.ui.fragment.OCFileListBottomSheetDialog.onCreate(OCFileListBottomSheetDialog.java:131)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:419)
	at android.app.Dialog.show(Dialog.java:313)
	at com.owncloud.android.ui.fragment.OCFileListFragment.lambda$registerFabListener$2$OCFileListFragment(OCFileListFragment.java:442)
	at com.owncloud.android.ui.fragment.-$$Lambda$OCFileListFragment$aYkoWPoxzAOahKL5AVjT06NhcnM.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7520)
	at android.view.View.performClickInternal(View.java:7489)
	at android.view.View.access$3600(View.java:826)
	at android.view.View$PerformClick.run(View.java:28555)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:245)
	at android.app.ActivityThread.main(ActivityThread.java:7953)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140251
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus8Pro
Model: IN2023
Id: RP1A.201005.001
Product: OnePlus8Pro_EEA

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 2011190105

**Comment by Virastrum** [comment]
I have encountered exactly this issue on the same device

**Comment by tobiasKaminsky** [comment]
It seems to be caused while adding special add options for e.g. Text, OnlyOffice, Collabora, etc.
What kind of those apps do you have? 
Can you please post a screenshot of "+" section of web ui?

**Comment by morpheus8111** [comment]
Hello,

Here the screenshots.

![Screenshot_20210114-072707__01](https://user-images.githubusercontent.com/77188333/104553318-bcc43800-563a-11eb-8197-7c71d8234138.jpg)
![Screenshot_20210114-072719__01](https://user-images.githubusercontent.com/77188333/104553324-c0f05580-563a-11eb-907b-4d65474ca8e5.jpg)
![Screenshot_20210114-072729__01](https://user-images.githubusercontent.com/77188333/104553328-c3eb4600-563a-11eb-879a-142367648e8b.jpg)
![Screenshot_20210114-072742__01](https://user-images.githubusercontent.com/77188333/104553335-c64da000-563a-11eb-9695-c3e234d5feef.jpg)
![Screenshot_20210114-072749__01](https://user-images.githubusercontent.com/77188333/104553346-cb125400-563a-11eb-8482-527f65869450.jpg)

**Comment by tobiasKaminsky** [comment]
Thanks for the fast reply, but I meant this:
![image](https://user-images.githubusercontent.com/5836855/104553600-3a884380-563b-11eb-9d6e-4b43ba5fc811.png)

As it crashes when opening "+", and on Android the same set of info are shown as in web UI, it might help to track down the issue.

**Comment by tobiasKaminsky** [comment]
I can reproduce it now, trying to fix it now
