### ISSUE TITLE
App crashes regularly (connecting to ownCloud 9.0.2 )

### ISSUE THREAD

**Issue by Bugsbane** [nextcloud/android#78]
### Actual behaviour
App crashes regularly

### Expected behaviour
App doesn't crash regularly
 
### Steps to reproduce
Unfortunately, I haven't found a consistent pattern for reproducing the problem yet. The last time it happened I was switching between detail to grid view.

### Environment data
Android version:
5.1.1

Device model: 
Galaxy Grand Prime

Stock or customized system:

Nextcloud app version:
20160621

Nextcloud server version:
Actually it's interfacing with ownCloud 9.0.2

### Logs
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Cannot add header view to grid -- setAdapter has already been called.
	at third_parties.in.srain.cube.GridViewWithHeaderAndFooter.addFooterView(GridViewWithHeaderAndFooter.java:183)
	at com.owncloud.android.ui.fragment.ExtendedListFragment.setFooterEnabled(ExtendedListFragment.java:533)
	at com.owncloud.android.ui.fragment.ExtendedListFragment.setFooterText(ExtendedListFragment.java:559)
	at com.owncloud.android.ui.fragment.OCFileListFragment.updateLayout(OCFileListFragment.java:855)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:830)
	at com.owncloud.android.ui.fragment.OCFileListFragment.onBrowseUp(OCFileListFragment.java:541)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onBackPressed(FileDisplayActivity.java:857)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onOptionsItemSelected(FileDisplayActivity.java:560)
	at android.app.Activity.onMenuItemSelected(Activity.java:3137)
	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:361)
	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:147)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
	at android.support.v7.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:194)
	at android.view.View.performClick(View.java:5254)
	at android.view.View$PerformClick.run(View.java:21173)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6838)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

************ DEVICE INFORMATION ***********
Brand: samsung
Device: gprimeltecan
Model: SM-G530W
Id: LMY47X
Product: gprimeltevl

************ FIRMWARE ************
SDK: 22
Release: 5.1.1
Incremental: G530WVLU1AOFB

```

**Comment by tobiasKaminsky** [comment]
This should be fixed both in beta and in official release.
@Bugsbane can you confirm?

**Comment by Bugsbane** [comment]
Yep. I'm not seeing this regular crash any more.

**Comment by AndyScherzinger** [comment]
@Bugsbane in beta, official or both? :smiley:

**Comment by tobiasKaminsky** [comment]
Was only in beta, so closing  :)
