### ISSUE TITLE
Bug when clicking on a notification about duplicate file conflict..

### ISSUE THREAD

**Issue by ghost** [nextcloud/android#7802]
### Steps to reproduce
1. Sync files with duplicates
2. An notification will pop up saying "File upload conflict-pick which version to keep of <file name>
3. THEN crash report appears

### Expected behaviour
- It would show two version of the file and  user should choose one

### Actual behaviour
- Crash report....

### Environment data
Android version:10

Device model: Samsung m11

Stock or customized system:

Nextcloud app version:3.14.1

Nextcloud server version:

Reverse proxy:

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
	at com.owncloud.android.ui.activity.ConflictsResolveActivity.onStart(ConflictsResolveActivity.java:187)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
	at android.app.Activity.performStart(Activity.java:7978)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3472)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7814)
	at java.lang.reflect.Method.invoke(Native Method)
	at

**Comment by jdaviescoates** [comment]
I don't have this exact issue in that the notification doesn't cause a crash, but I have a similar issue in that I keep getting the same notification and the same conflict over and over and over again. Whatever I do (choose original file, choose the new file, or cancel) doesn't make any difference, within a few minutes I get the exact same notification about the exact same conflict again.
![Screenshot_20210128-155456](https://user-images.githubusercontent.com/2113743/106163554-369f0a00-6181-11eb-9a69-8a6a2b7b4080.png)

![Screenshot_20210128-120617](https://user-images.githubusercontent.com/2113743/106163634-4c143400-6181-11eb-9d32-7a3a9be20a00.png)

**Comment by tobiasKaminsky** [comment]
Is one file downloaded? Or are both files not on device?

**Comment by nalinalini** [comment]
It happens when we upload a file to the server from the phone....I think in my xase there was not any duplicate files as I opened a new folder in the nextcloud and synced another folder to it...

**Comment by AndyScherzinger** [comment]
added references to duplicates

**Comment by tobiasKaminsky** [comment]
Any reasons you did this @AndyScherzinger ? :-)

**Comment by AndyScherzinger** [comment]
Yes, the issue was marked as "needs info", some feedback has been given, no dev replies, so bot closed it... So I think we need to check if it can simply be closed since the bot shouldn't close it after the reporter replied... ;-)
