### ISSUE TITLE
Opening video crashes Nextcloud App

### ISSUE THREAD

**Issue by tilllt** [nextcloud/android#7812]
### Steps to reproduce
Open video in nextcloud app

### Expected behaviour
Should play the video and not crash

### Actual behaviour
Crashes the nextcloud app

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{4354796 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2039)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7697)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus5T
Model: ONEPLUS A5010
Id: QKQ1.191014.012
Product: OnePlus5T

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2010292059

**Comment by ezaquarii** [comment]
Please upgrade the app to the latest version 3.14.3.
This bug has been fixed in 3.14.1.
