### ISSUE TITLE
Exception after press the PLUS button or ADD button

### ISSUE THREAD

**Issue by biware-repo** [nextcloud/android#7840]
### Steps to reproduce
1. Start android nextcloud app and press + button

### Expected behaviour
- It should open options what to add (folder, file, upload etc) 

### Actual behaviour
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5958)
	at android.view.ViewGroup.addView(ViewGroup.java:5777)
	at android.view.ViewGroup.addView(ViewGroup.java:5717)
	at android.view.ViewGroup.addView(ViewGroup.java:5690)
	at com.owncloud.android.ui.fragment.OCFileListBottomSheetDialog.onCreate(OCFileListBottomSheetDialog.java:131)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:702)
	at android.app.Dialog.show(Dialog.java:424)
	at com.owncloud.android.ui.fragment.OCFileListFragment.lambda$registerFabListener$2$OCFileListFragment(OCFileListFragment.java:442)
	at com.owncloud.android.ui.fragment.-$$Lambda$OCFileListFragment$aYkoWPoxzAOahKL5AVjT06NhcnM.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7862)
	at android.view.View.performClickInternal(View.java:7831)
	at android.view.View.access$3600(View.java:879)
	at android.view.View$PerformClick.run(View.java:29359)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140251
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: d2s
Model: SM-N975F
Id: QP1A.190711.020
Product: d2seea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: N975FXXS6DTK8

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not

### Environment data

Nextcloud server version:
20.0.4

**Comment by AndyScherzinger** [comment]
This has been fixed with 3.14.3 released yesterday during the day, please update :)
