### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by puditracode** [nextcloud/android#7855]
### Steps to reproduce
1.  Opening the app
2.  Clicking the + button
3.  Crash

### Expected behaviour
- Tell us what should happen
-  i can add my files

### Actual behaviour
- Tell us what happens
- it crash and tell me i should report it to github

************ CAUSE OF ERROR ************

java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5264)
	at android.view.ViewGroup.addView(ViewGroup.java:5085)
	at android.view.ViewGroup.addView(ViewGroup.java:5025)
	at android.view.ViewGroup.addView(ViewGroup.java:4998)
	at com.owncloud.android.ui.fragment.OCFileListBottomSheetDialog.onCreate(OCFileListBottomSheetDialog.java:131)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:550)
	at android.app.Dialog.show(Dialog.java:391)
	at com.owncloud.android.ui.fragment.OCFileListFragment.lambda$registerFabListener$2$OCFileListFragment(OCFileListFragment.java:442)
	at com.owncloud.android.ui.fragment.-$$Lambda$OCFileListFragment$aYkoWPoxzAOahKL5AVjT06NhcnM.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7341)
	at android.view.View.performClickInternal(View.java:7307)
	at android.view.View.access$3200(View.java:846)
	at android.view.View$PerformClick.run(View.java:27790)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7097)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140251
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: j4primelte
Model: SM-J415F
Id: PPR1.180610.011
Product: j4primeltedx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: J415FXXU2BSDL

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
This has been fixed and is already available with the latest version via Google Play
