### ISSUE TITLE
nextcloud android app crashes

### ISSUE THREAD

**Issue by kysersoze81** [nextcloud/android#7881]
### Steps to reproduce
1. Open nextcloud app on phone
2. Open a subfolder
3. 

### Expected behaviour
- Tell us what should happen
Display folder contents
### Actual behaviour
- Tell us what happens
Waiting for several seconds before app crashes

Output from crash
************ CAUSE OF ERROR ************

android.database.CursorIndexOutOfBoundsException: Index -1 requested, with a size of 6778
	at android.database.AbstractCursor.checkPosition(AbstractCursor.java:515)
	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:138)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:76)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:179)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProviderOperation.applyInternal(ContentProviderOperation.java:332)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:309)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:672)
	at android.content.ContentProvider.applyBatch(ContentProvider.java:2138)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:371)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:532)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:520)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:1882)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:438)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:519)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:401)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:237)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: d1
Model: SM-N970F
Id: QP1A.190711.020
Product: d1xx

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: N970FXXS6DTK8

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Is this happening to every subfolder?
If not, do you see any special about this subfolder where it occurs?

**Comment by kysersoze81** [comment]
So far it seems to happen when I go into my pictures folder and scroll around or go into a sub-folder
structure is =>Photos=>2020=>02=>image.file
The app seems to lock in place with a loading circle that's stopped and then displays a crash report. sometimes if I'm fast enough it gets to a thumbnail of a photo before the crash. Pictures to help.
Nextcloud 20.0.5
Nextcloud Android App 3.15.0
![Screenshot_20210223-181559_Nextcloud](https://user-images.githubusercontent.com/61527666/108819794-03785b00-7607-11eb-9808-30d83d408bc5.jpg)
![Screenshot_20210223-181536_Nextcloud](https://user-images.githubusercontent.com/61527666/108819802-05dab500-7607-11eb-8ded-adf3cb9e58c7.jpg)
![Screenshot_20210223-181524_Nextcloud](https://user-images.githubusercontent.com/61527666/108819811-07a47880-7607-11eb-8b2e-7eb59a1261ce.jpg)
![Screenshot_20210223-181443_Nextcloud](https://user-images.githubusercontent.com/61527666/108819813-08d5a580-7607-11eb-9b58-c47f1a8bd82c.jpg)
![Screenshot_20210223-181437_Nextcloud](https://user-images.githubusercontent.com/61527666/108819816-0a06d280-7607-11eb-8c25-7a22c47e5d09.jpg)
![Screenshot_20210223-181431_Nextcloud](https://user-images.githubusercontent.com/61527666/108819820-0b37ff80-7607-11eb-803c-4ac91be94487.jpg)

**Comment by tobiasKaminsky** [comment]
Can you go to this subfolder on web and see how many files are in there?

**Comment by kysersoze81** [comment]
The picture shows 2 sub-folders 01 and 02 where it crashed but those folders have 961 and 126 image files respectively
That being said it has crashed again before it got that far, Meaning before it opened the 2021 folder which has the 2 sub-folders 01 and 02. Attached more screen shots to explain better.
![Screenshot_20210225-182042_Nextcloud](https://user-images.githubusercontent.com/61527666/109124782-0dc95f00-7797-11eb-9dc7-68473c87bc85.jpg)
![Screenshot_20210225-182055_Nextcloud](https://user-images.githubusercontent.com/61527666/109124795-115ce600-7797-11eb-888c-95c3655e7c8e.jpg)
![Screenshot_20210225-182101_Nextcloud](https://user-images.githubusercontent.com/61527666/109124811-15890380-7797-11eb-8fbc-5a337e71a90f.jpg)

**Comment by tobiasKaminsky** [comment]
Can you wait always some time, e.g. 30s, before continuing, so that we know at which folder it really crashes?

**Comment by kysersoze81** [comment]
I opened the app and waited until the loading circle went away and then opened the photos folder. while waiting for the loading circle to go away it crashed. So its doing it from the first sub-folder

**Comment by tobiasKaminsky** [comment]
Is there something special about this sub folder? 
How many files/folders, is it shared, external storage, etc.?

**Comment by kysersoze81** [comment]
It's not shared, Its internal storage and the sub-folders you can see in the pictures. The sub folders have less than 1000 pictures and videos in each folder

**Comment by tobiasKaminsky** [comment]
Can you clear cache and check again?

**Comment by kysersoze81** [comment]
I cleared the cache and opened the app slowly went to pictures then it crashed while I was waiting for the loading wheel. I had not yet tapped on the year yet.
