### ISSUE TITLE
App crash during QR scan

### ISSUE THREAD

**Issue by cyroxx** [nextcloud/android#7891]
### Steps to reproduce
1. Start app
2. Choose "Login with QR code" 
3. Scan QR code

### Expected behaviour
- continue login

### Actual behaviour
- app crash

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 7.0

Device model: Samsung Galaxy Tab S2 (SM-T719)

Stock or customized system: Stock

Nextcloud app version: (latest F-Droid version, just installed it)

Nextcloud server version: Storage Share 19.0.3

Reverse proxy: N/A, managed instance

#### Web server error log
N/A

#### Nextcloud log (data/nextcloud.log)

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
	at com.owncloud.android.authentication.AuthenticatorActivity.onAuthenticatorTaskCallback(AuthenticatorActivity.java:1186)
	at com.owncloud.android.authentication.AuthenticatorAsyncTask.onPostExecute(AuthenticatorAsyncTask.java:100)
	at com.owncloud.android.authentication.AuthenticatorAsyncTask.onPostExecute(AuthenticatorAsyncTask.java:43)
	at android.os.AsyncTask.finish(AsyncTask.java:660)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6780)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1500)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1390)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: gts28velte
Model: SM-T719
Id: NRD90M
Product: gts28veltexx

************ FIRMWARE ************
SDK: 24
Release: 7.0
Incremental: T719XXS2BTJ1

**Comment by cyroxx** [comment]
Probably related: #7890

**Comment by tobiasKaminsky** [comment]
Is this a valid QR?

**Comment by cyroxx** [comment]
IIRC yes it was

**Comment by cyroxx** [comment]
Anything that I could/should do to help with this?
