### ISSUE TITLE
Nextcloud application keeps crashing on my One Plus 8 running Android 11

### ISSUE THREAD

**Issue by Laurin12344** [nextcloud/android#7893]
Since the update to Android 11 the nextcloud application keeps crashing when beeing used (upload data/download data/viewing data) something like this never happened before the update to Android 11 or on other operating systems. Please fix this problem (the cause of the error is under this message)

************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{d927a9a u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2137)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:7959)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus8
Model: IN2013
Id: RP1A.201005.001
Product: OnePlus8_EEA

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 2012102310

**Comment by AndyScherzinger** [comment]
@Laurin12344 please update to latest version 3.14.3 available via Google Play. Depending on the area where this crash happens (not visible via the given Stack Trace) this might be fixed already

**Comment by Laurin12344** [comment]
No unfortunately not I update and my nextcloud application still keeps crashing... :(

************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Couldn't read row 827, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:542)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:77)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:179)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProvider.delete(ContentProvider.java:1820)
	at android.content.ContentProviderOperation.applyInternal(ContentProviderOperation.java:389)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:352)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:672)
	at android.content.ContentProvider.applyBatch(ContentProvider.java:2476)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:421)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:586)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:574)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:2234)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:438)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:519)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:401)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:237)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:923)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140390
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus8
Model: IN2013
Id: RP1A.201005.001
Product: OnePlus8_EEA

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 2012102310

**Comment by AndyScherzinger** [comment]
Thanks for the heads-up while your latest comment shows a completely different error :(

**Comment by Laurin12344** [comment]
I hope you guys can fix it fast 🥴😁

**Comment by Laurin12344** [comment]
I couldn't handle these crashes anymore so I downgraded to version 3.13.0 and everything works completely fine I will update when you guys say it's working without crashes
