### ISSUE TITLE
App crashes when unsharing a folder shared by other user.

### ISSUE THREAD

**Issue by luckkmaxx** [nextcloud/android#7899]
### Steps to reproduce
1. Share some folder being logged with USER1
2. Log to USER2 and tap "unshare" button. 

### Expected behaviour
- 1: Make different shared icon for external shares and disable "unshare" option. 
- 2: Or simply display a message saying you cannot unshare the item. 

### Actual behaviour
- App crashes

**Comment by luckkmaxx** [comment]
Sorry this bug was while testing beta.

**Comment by tobiasKaminsky** [comment]
Is this still happening with latest beta version?

**Comment by luckkmaxx** [comment]
> Is this still happening with latest beta version?
> 

I cant test it. Tried with latest dev and stable.
I cant share a test folder with any user, app crashes with some differences between dev and stable:

dev: when I type a username to share with, the app shows me a java exception error as in the screenshoot, and when I tap this the app crashes.

stable: when I type a username, the app shows me the user, but when I tap on it the app crashes with the same error.

no errors when sharing with a link.
![Screenshot_20210224-153957_Nextcloud_dev.png](https://user-images.githubusercontent.com/14180594/109017281-501b6f00-76b7-11eb-8ab4-9ebc6f284ca5.png)

**Comment by luckkmaxx** [comment]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Accessing result data after operation failed!
	at com.owncloud.android.lib.common.operations.RemoteOperationResult.getData(RemoteOperationResult.java:486)
	at com.owncloud.android.utils.ErrorMessageAdapter.getMessageForCreateShareOperations(ErrorMessageAdapter.java:254)
	at com.owncloud.android.utils.ErrorMessageAdapter.getMessageForResultAndOperation(ErrorMessageAdapter.java:143)
	at com.owncloud.android.utils.ErrorMessageAdapter.getErrorCauseMessage(ErrorMessageAdapter.java:79)
	at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:380)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoteOperationFinish(FileDisplayActivity.java:1704)
	at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:734)
	at com.owncloud.android.services.-$$Lambda$OperationsService$KsB1LbjHjlEBSp0h7XO24czs-OQ.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20210224
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: willow
Model: Redmi Note 8T
Id: RQ1A.210205.004
Product: willow

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: eng.mg7127.20210213.225105

**Comment by luckkmaxx** [comment]
Tried to share a new folder that is common to all users (external folder) and the app doesnt let me share (says cant share again, and its a new folder with a name I never used)
![Screenshot_20210224-155502_Nextcloud.png](https://user-images.githubusercontent.com/14180594/109018891-c66ca100-76b8-11eb-9dd2-925f28d9acb0.png)

**Comment by tobiasKaminsky** [comment]
> dev: when I type a username to share with, the app shows me a java exception error as in the screenshoot, and when I tap this the app crashes.

This might happen when having dev and stable installed in parallel.

> 
> stable: when I type a username, the app shows me the user, but when I tap on it the app crashes with the same error.

Can you test 3.15.1 RC1 from beta program of Gplay? (or soon via Fdroid)

**Comment by tobiasKaminsky** [comment]
ava.lang.RuntimeException: Accessing result data after operation failed!
