### ISSUE TITLE
Crashes every 2nd time

### ISSUE THREAD

**Issue by fabio3000** [nextcloud/android#7912]
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Do not call this method before initializing mStorageManager
	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.initTargetFolder(ReceiveExternalFilesActivity.java:999)
	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onStart(ReceiveExternalFilesActivity.java:253)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
	at android.app.Activity.performStart(Activity.java:7986)
	at android.app.Activity.performRestart(Activity.java:8081)
	at android.app.ActivityThread.handleWindowVisibility(ActivityThread.java:5230)
	at android.app.servertransaction.WindowVisibilityItem.execute(WindowVisibilityItem.java:39)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140390
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a71
Model: SM-A715F
Id: QP1A.190711.020
Product: a71naeea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: A715FXXU3ATK1

**Comment by tobiasKaminsky** [comment]
Do you remember what you did to trigger this?

**Comment by fabio3000** [comment]
No, I haven't installed or done anything else. Can't you read something from the code? Am 23.02.21, 08:27 schrieb Tobias Kaminsky <notifications@github.com>:

   
  Do you remember what you did to trigger this?

**Comment by tobiasKaminsky** [comment]
Strange.
Guessing from code it seems that you share a file from another app to NC app and then it crashes.

Can you describe when it crashes for you?

**Comment by fabio3000** [comment]
No I'm sorry. If I notice anything, I'll write to you.Kind regardsFabioAm 25.02.21, 09:41 schrieb Tobias Kaminsky <notifications@github.com>:

   
  Strange. Guessing from code it seems that you share a file from another app to NC app and then it crashes. 
  Can you describe when it crashes for you?

**Comment by jaller94** [comment]
I found a reproducible way to get an error that looks very similar:
https://github.com/nextcloud/android/issues/11221
