### ISSUE TITLE
The app doesn't respond when I open it

### ISSUE THREAD

**Issue by jbaenaxd** [nextcloud/android#7920]
### Steps to reproduce
1. Open the app

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to read from field 'int com.android.server.wm.TaskRecord.taskId' on a null object reference
	at android.os.Parcel.createException(Parcel.java:2094)
	at android.os.Parcel.readException(Parcel.java:2056)
	at android.os.Parcel.readException(Parcel.java:2004)
	at android.app.IActivityTaskManager$Stub$Proxy.reportAssistContextExtras(IActivityTaskManager.java:5956)
	at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:3953)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2215)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityTaskManagerService.reportAssistContextExtras(ActivityTaskManagerService.java:3987)
	at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:2728)
	at android.os.Binder.execTransactInternal(Binder.java:1056)
	at android.os.Binder.execTransact(Binder.java:1029)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a70q
Model: SM-A705FN
Id: QP1A.190711.020
Product: a70qeea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: A705FNXXU5CTK4

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Looking at the stacktrace this is pure Android, nothing in our app.

Do you know what steps you did to trigger this?
