### ISSUE TITLE
Teilen auch bei der Dev Version nicht möglich

### ISSUE THREAD

**Issue by weinic** [nextcloud/android#7942]
Teilen ist auch bei der Developer Version nicht möglich.
Vermutlich das gleiche Problem wie bei #7863

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Accessing result data after operation failed!
	at com.owncloud.android.lib.common.operations.RemoteOperationResult.getData(RemoteOperationResult.java:486)
	at com.owncloud.android.utils.ErrorMessageAdapter.getMessageForCreateShareOperations(ErrorMessageAdapter.java:254)
	at com.owncloud.android.utils.ErrorMessageAdapter.getMessageForResultAndOperation(ErrorMessageAdapter.java:143)
	at com.owncloud.android.utils.ErrorMessageAdapter.getErrorCauseMessage(ErrorMessageAdapter.java:79)
	at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:380)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoteOperationFinish(FileDisplayActivity.java:1704)
	at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:734)
	at com.owncloud.android.services.-$$Lambda$OperationsService$KsB1LbjHjlEBSp0h7XO24czs-OQ.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7697)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20210130
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus5
Model: ONEPLUS A5000
Id: QKQ1.191014.012
Product: OnePlus5

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2010292059

**Comment by weinic** [comment]
Das hier tritt nur bei der Dev. Version auf, das anstatt der Namen irgend welche Fehler angezeigt werden.
Das war bei der Server Version 20.0.6 und auch jetz noch bei 20.0.7 so.

![Screenshot_20210205-155626](https://user-images.githubusercontent.com/57099502/107050696-d422bb00-67cb-11eb-985b-3e9f19592a0f.jpg)

**Comment by si90** [comment]
Negativ, ich nutze 20.0.4 und die standard Android App, nix mit Dev.
Selbst nach einem Update auf 20.0.7 geht es nicht. 
Bin auf dem Stable Build. 

Seit ein paar Tagen kann ich nichts mehr Teilen, davor hat alles prima geklappt - in dieser Zeit wurden auch keine Updates am Server eingespielt, das Update auf 20.0.7 habe ich nur durchgeführt um zu sehen ob sich das Problem löst...

**Comment by tobiasKaminsky** [comment]
Duplicate of https://github.com/nextcloud/android/issues/7987
Fix is in: #7992
