### ISSUE TITLE
Absturz beim Teilen vom Ordner

### ISSUE THREAD

**Issue by KiWiDE** [nextcloud/android#7945]
Ich möchte einen schon vorhandenen Ordner in der App teilen. Nachdem ich den Benutzer auswähle, stürtzt die App mit folgendem Fehler-Code ab.
Auf dem Nextcloud-Test-Server passiert genau das Gleiche - die App stürtzt ab. 
Auf dem Iphone ausprobiert - da läuft alles schick, kein Absturz. 
Ich hoffe auf schnelle Lösung.

P.S. Übrigens beim Teilen von einer schon vorhandenen Datei (egal ob diese in dem Ordner liegt, bei welchem zum Absturz kommt oder nicht) funktioniert alles super. Den Absturz gibt es NUR beim Teilen einen Ordner.
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Accessing result data after operation failed!
	at com.owncloud.android.lib.common.operations.RemoteOperationResult.getData(RemoteOperationResult.java:486)
	at com.owncloud.android.utils.ErrorMessageAdapter.getMessageForCreateShareOperations(ErrorMessageAdapter.java:254)
	at com.owncloud.android.utils.ErrorMessageAdapter.getMessageForResultAndOperation(ErrorMessageAdapter.java:143)
	at com.owncloud.android.utils.ErrorMessageAdapter.getErrorCauseMessage(ErrorMessageAdapter.java:79)
	at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:380)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoteOperationFinish(FileDisplayActivity.java:1704)
	at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:734)
	at com.owncloud.android.services.-$$Lambda$OperationsService$KsB1LbjHjlEBSp0h7XO24czs-OQ.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8414)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: r8s
Model: SM-G780F
Id: RP1A.200720.012
Product: r8seea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: G780FXXS1BTL2

**Comment by si90** [comment]
bump

**Comment by tobiasKaminsky** [comment]
Duplicate of https://github.com/nextcloud/android/issues/7987
Fix is in: #7992
