### ISSUE TITLE
Crash while sharing a new created folder

### ISSUE THREAD

**Issue by SkipperChris** [nextcloud/android#7948]
### Steps to reproduce
1. Create new subfolder
2. Add permission (Cloud user) 
3. Try to check permission 

### Expected behaviour
- share the folder

### Actual behaviour
- NextCloud App Crash 

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10

Device model: Moto G7 64 GB

Stock or customized system: Stock

Nextcloud app version: 3.15.0

Nextcloud server version: 20.0.4

Reverse proxy:

#### Web server error log

Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
by mistke no plo available, sorry
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by thgoebel** [comment]
Do you get any crash logs? E.g. between after selecting the target user? Your issue might be related to #7987, having a log would help confirm this.

**Comment by SkipperChris** [comment]
Very sorry, by mistake the lkog was not attached to the post. Not any more available.

Afterwards I found, for unknown reason, at my phone data roaming was disabled (in domestic use), what might have been a trigger to the crash - although I've been online via WLAN ?

Did not happen again meahnwhile

**Comment by hul51u** [comment]
I think i got the same problem.  I tried to share a subfolder and my app just crashed.

Server: Nextcloud 20.0.6

Connection via wifi (maybe with slightly stability problems)

The log file is:

\*\*\*\*\*\*\*\*\*\*\*\* CAUSE OF ERROR \*\*\*\*\*\*\*\*\*\*\*\*

java.lang.RuntimeException: Accessing result data after operation failed!

	at com.owncloud.android.lib.common.operations.RemoteOperationResult.getData(RemoteOperationResult.java:486)

	at com.owncloud.android.utils.ErrorMessageAdapter.getMessageForCreateShareOperations(ErrorMessageAdapter.java:254)

	at com.owncloud.android.utils.ErrorMessageAdapter.getMessageForResultAndOperation(ErrorMessageAdapter.java:143)

	at com.owncloud.android.utils.ErrorMessageAdapter.getErrorCauseMessage(ErrorMessageAdapter.java:79)

	at com.owncloud.android.ui.activity.FileActivity.onCreateShareViaLinkOperationFinish(FileActivity.java:830)

	at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:400)

	at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoteOperationFinish(FileDisplayActivity.java:1704)

	at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:734)

	at com.owncloud.android.services.-$$Lambda$OperationsService$KsB1LbjHjlEBSp0h7XO24czs-OQ.run(Unknown Source:6)

	at android.os.Handler.handleCallback(Handler.java:883)

	at android.os.Handler.dispatchMessage(Handler.java:100)

	at android.os.Looper.loop(Looper.java:214)

	at android.app.ActivityThread.main(ActivityThread.java:7397)

	at java.lang.reflect.Method.invoke(Native Method)

	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)

	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

\*\*\*\*\*\*\*\*\*\*\*\* APP INFORMATION \*\*\*\*\*\*\*\*\*\*\*\*

ID: com.nextcloud.client

Version: 30150090

Build flavor: gplay

\*\*\*\*\*\*\*\*\*\*\*\* DEVICE INFORMATION \*\*\*\*\*\*\*\*\*\*\*\*

Brand: Fairphone

Device: FP3

Model: FP3

Id: 8901.3.A.0077.20201221

Product: FP3

\*\*\*\*\*\*\*\*\*\*\*\* FIRMWARE \*\*\*\*\*\*\*\*\*\*\*\*

SDK: 29

Release: 10

Incremental: 12211240

**Comment by tobiasKaminsky** [comment]
Please try 3.15.1 RC1 via Play store beta and re-open if it still happens.
