### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by Yajo** [nextcloud/android#7951]
### Steps to reproduce
1. Open it, today.

### Expected behaviour
- opens

### Actual behaviour
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.markCommentsAsRead()' on a null object reference
	at com.owncloud.android.ui.fragment.FileDetailFragment$1.onPageScrolled(FileDetailFragment.java:242)
	at androidx.viewpager.widget.ViewPager.dispatchOnPageScrolled(ViewPager.java:1930)
	at androidx.viewpager.widget.ViewPager.onPageScrolled(ViewPager.java:1904)
	at androidx.viewpager.widget.ViewPager.pageScrolled(ViewPager.java:1842)
	at androidx.viewpager.widget.ViewPager.scrollToItem(ViewPager.java:694)
	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1786)
	at android.view.View.layout(View.java:23750)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23750)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23750)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1818)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1584)
	at android.view.View.layout(View.java:23750)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1996)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:23750)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:23750)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23750)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23750)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23750)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23750)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1099)
	at android.view.View.layout(View.java:23750)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3712)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3164)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2225)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9126)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
	at android.view.Choreographer.doCallbacks(Choreographer.java:797)
	at android.view.Choreographer.doFrame(Choreographer.java:732)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: gts4lvwifi
Model: SM-T720
Id: QP1A.190711.020
Product: gts4lvwifieea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: T720XXU1CTK1
```

### Can you reproduce this problem on https://try.nextcloud.com?
- to be honest, this just happened once, and the next time I opened the app it was working fine. So i guess it'll work there too.

**Comment by tobiasKaminsky** [comment]
Is this happening reliable?

**Comment by Yajo** [comment]
🤷🏼‍♂️ I have no idea what produced this, I just published the issue hoping the traceback helped more than me.

**Comment by tobiasKaminsky** [comment]
Unfortunately I cannot reproduce this, so a way to reproduce it would be needed.
Can you reply once it happens again?

**Comment by Yajo** [comment]
Of course, I somehow suspected that.

I'll reopen if it happens again.
