### ISSUE TITLE
Nextcloud for Android keeps crashing when left running in background

### ISSUE THREAD

**Issue by AJSchiller** [nextcloud/android#7964]
### Steps to reproduce
1. Open file from Nextcloud, which launches an external app (in my case, a PDF file that opens in the app Xodo). 
2. Work in the other app for a while, with the Nextcloud app open in the background. 
3. Switch back to Nextcloud. 

When reaching step 3 above, I get a message that Nextcloud has crashed, with the following information (this has happened multiple times in recent days, though not necessarily every time I use Nextcloud in this way):

************ CAUSE OF ERROR ************
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.markCommentsAsRead()' on a null object reference
	at com.owncloud.android.ui.fragment.FileDetailFragment$1.onPageScrolled(FileDetailFragment.java:242)
	at androidx.viewpager.widget.ViewPager.dispatchOnPageScrolled(ViewPager.java:1930)
	at androidx.viewpager.widget.ViewPager.onPageScrolled(ViewPager.java:1904)
	at androidx.viewpager.widget.ViewPager.pageScrolled(ViewPager.java:1842)
	at androidx.viewpager.widget.ViewPager.scrollToItem(ViewPager.java:694)
	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1786)
	at android.view.View.layout(View.java:22498)
	at android.view.ViewGroup.layout(ViewGroup.java:7188)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:22498)
	at android.view.ViewGroup.layout(ViewGroup.java:7188)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:22498)
	at android.view.ViewGroup.layout(ViewGroup.java:7188)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1801)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1567)
	at android.view.View.layout(View.java:22498)
	at android.view.ViewGroup.layout(ViewGroup.java:7188)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1996)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:22498)
	at android.view.ViewGroup.layout(ViewGroup.java:7188)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:22498)
	at android.view.ViewGroup.layout(ViewGroup.java:7188)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:22498)
	at android.view.ViewGroup.layout(ViewGroup.java:7188)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:22498)
	at android.view.ViewGroup.layout(ViewGroup.java:7188)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:22498)
	at android.view.ViewGroup.layout(ViewGroup.java:7188)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:22498)
	at android.view.ViewGroup.layout(ViewGroup.java:7188)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1100)
	at android.view.View.layout(View.java:22498)
	at android.view.ViewGroup.layout(ViewGroup.java:7188)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3455)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2915)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1963)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8719)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:988)
	at android.view.Choreographer.doCallbacks(Choreographer.java:765)
	at android.view.Choreographer.doFrame(Choreographer.java:700)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7266)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```
************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: gts3llte
Model: SM-T825
Id: PPR1.180610.011
Product: gts3lltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: T825XXU3CTD1

- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
> * Work in the other app for a while, with the Nextcloud app open in the background.
> 
> *

Does this also happen if you directly switch back?

**Comment by AJSchiller** [comment]
No. As far as I can tell, it only happens after I have been working in Xodo for a while first.
