### ISSUE TITLE
Tried to move selected files into other folder

### ISSUE THREAD

**Issue by TRoYan4eG** [nextcloud/android#7978]
### Steps to reproduce
1. Go into folder
2. Select all files (2359 files, 9.9GB)
3. Press move to other folder

### Expected behaviour
- Files moved to other folder

### Actual behaviour
- Got Exception, app closed

### Environment data
Android version: 11

Device model: Xiaomi MI MIX3

Stock or customized system: stock

Nextcloud app version: 3.15.0

Nextcloud server version: 20.0.7

Reverse proxy:

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Failure from system
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1722)
	at android.app.Activity.startActivityForResult(Activity.java:5258)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
	at android.app.Activity.startActivityForResult(Activity.java:5216)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
	at com.owncloud.android.ui.fragment.OCFileListFragment.onFileActionChosen(OCFileListFragment.java:1160)
	at com.owncloud.android.ui.fragment.OCFileListFragment$MultiChoiceModeListener.onActionItemClicked(OCFileListFragment.java:707)
	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:2684)
	at androidx.appcompat.view.SupportActionModeWrapper$CallbackWrapper.onActionItemClicked(SupportActionModeWrapper.java:172)
	at androidx.appcompat.app.AppCompatDelegateImpl$ActionModeCallbackWrapperV9.onActionItemClicked(AppCompatDelegateImpl.java:2689)
	at androidx.appcompat.view.StandaloneActionMode.onMenuItemSelected(StandaloneActionMode.java:142)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1219)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3230)
	at android.widget.AbsListView$3.run(AbsListView.java:4186)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: android.os.TransactionTooLargeException: data parcel size 1985908 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:511)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3969)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
	... 25 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: perseus
Model: Mi MIX 3
Id: QKQ1.190828.002
Product: perseus

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V12.0.2.0.QEEMIXM

```

**Comment by tobiasKaminsky** [comment]
It seems that 
https://github.com/nextcloud/android/blob/cf2a35f64ddab1a8734febd5e055a3425f276aae/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java#L1157

just does not allow to transfer such a big list:
https://www.neotechsoftware.com/blog/android-intent-size-limit
