### ISSUE TITLE
conflict crash

### ISSUE THREAD

**Issue by Kellermaan** [nextcloud/android#7979]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
	at com.owncloud.android.ui.activity.ConflictsResolveActivity.onStart(ConflictsResolveActivity.java:187)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8210)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3800)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2289)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8456)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: o1q
Model: SM-G9910
Id: RP1A.200720.012
Product: o1qzcx

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: G9910ZCU1AUAG

**Comment by tobiasKaminsky** [comment]
Do you know what leads to it?
Have you done anything special, or is there something special about the folder/files you were handling?

**Comment by AndyScherzinger** [comment]
Duplicate of #7802
