### ISSUE TITLE
App crashes on qr code scan

### ISSUE THREAD

**Issue by BihJ** [nextcloud/android#7980]
### Steps to reproduce
1. Open desktop then browse on settings/user/security
2. Scan qr code with app
3. App crashes

### Expected behaviour
- Tell us what should happen
Logging in after I scan qr code on desktop with dark theme of Nextcloud
### Actual behaviour
- Tell us what happens
App crashes
### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:
Oxygen os 10.3.8 android version 10
Device model: 
Oneplus 6t

**Comment by lmamane** [comment]
I reproduced this bug when trying to connect to my own Nextcloud server (version 18.0.14) but not with try.nextcloud.com

******** CAUSE OF ERROR ********

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.setVisibility(int)' on a null object reference
 at com.owncloud.android.authentication.AuthenticatorActivity.onAuthenticatorTaskCallback(AuthenticatorActivity.java:1178)
 at com.owncloud.android.authentication.AuthenticatorAsyncTask.onPostExecute(AuthenticatorAsyncTask.java:100)
 at com.owncloud.android.authentication.AuthenticatorAsyncTask.onPostExecute(AuthenticatorAsyncTask.java:43)
 at android.os.AsyncTask.finish(AsyncTask.java:755)
 at android.os.AsyncTask.access$900(AsyncTask.java:192)
 at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:214)
 at android.app.ActivityThread.main(ActivityThread.java:7356)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

******** APP INFORMATION ********
ID: com.nextcloud.client
Version: 30150090
Build flavor: generic

******** DEVICE INFORMATION ********
Brand: OnePlus
Device: OnePlus7Pro
Model: OnePlus 7 Pro
Id: QQ3A.200805.001
Product: OnePlus7Pro

******** FIRMWARE ********
SDK: 29
Release: 10
Incremental: 073b5e8d9e

**Comment by lmamane** [comment]
I did two things and the problem disappeared:
- upgrade the server to 19.0.8
- I applied https://github.com/nextcloud/server/pull/25725 to the server, which in combination with my "restrict by IP or user" config (see https://github.com/nextcloud/limit_login_to_ip) fixed token logins for my user.
So I'm not whether the bug was triggered by:
- server 18.0
- the fact that, in my setup, token logins were broken (they were giving a 403 HTTP error)
anyway, the Android client should "cleanly" show an error message, not crash

**Comment by tobiasKaminsky** [comment]
>     * the fact that, in my setup, token logins were broken (they were giving a 403 HTTP error)
>       anyway, the Android client should "cleanly" show an error message, not crash

It might that https://github.com/nextcloud/android/pull/7919 would have "fixed" this so that it does not crash.
But good that you found the root cause of it!
