### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by KingStoffen** [nextcloud/android#7983]
### Steps to reproduce
1. Create a folder with a lot of data
2. Remove this folder
3. Create the same folder with another structure and a lot of data
4. For example /pictures/xy/ALotOfFolders
5. Remove xy/*
6. Create /pictures/yz/ALotOfFilders
7. App crashes while loading pictures folders

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
#################################################################
Error Code : 1032 (SQLITE_READONLY_DBMOVED)
Caused By : Database or Journal file have been removed.
	(attempt to write a readonly database (code 1032))
#################################################################
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:816)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1967)
	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1913)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:645)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:629)
	at android.content.ContentProvider$Transport.update(ContentProvider.java:362)
	at android.content.ContentResolver.update(ContentResolver.java:1413)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveCapabilities(FileDataStorageManager.java:1945)
	at com.owncloud.android.operations.GetCapabilitiesOperation.run(GetCapabilitiesOperation.java:51)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:139)
	at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:64)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:296)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:276)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:229)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:762)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: zeroflte
Model: SM-G920F
Id: NRD90M
Product: zerofltexx

************ FIRMWARE ************
SDK: 24
Release: 7.0
Incremental: G920FXXS6ETI6

**Comment by tobiasKaminsky** [comment]
> android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)

This is nothing we can fix, as this is handled by Android :/
