### ISSUE TITLE
Bug for share folder from Android

### ISSUE THREAD

**Issue by gigidsss** [nextcloud/android#7987]
### Steps to reproduce
1. Just share a folder of 9 Gb

### Logs
All info are under this text
#### Web server error log
```
Insert your webserver log here
```

#7514 ********* CAUSE OF ERROR ************

java.lang.RuntimeException: Accessing result data after operation failed!
	at com.owncloud.android.lib.common.operations.RemoteOperationResult.getData(RemoteOperationResult.java:486)
	at com.owncloud.android.utils.ErrorMessageAdapter.getMessageForCreateShareOperations(ErrorMessageAdapter.java:254)
	at com.owncloud.android.utils.ErrorMessageAdapter.getMessageForResultAndOperation(ErrorMessageAdapter.java:143)
	at com.owncloud.android.utils.ErrorMessageAdapter.getErrorCauseMessage(ErrorMessageAdapter.java:79)
	at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:380)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoteOperationFinish(FileDisplayActivity.java:1704)
	at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:734)
	at com.owncloud.android.services.-$$Lambda$OperationsService$KsB1LbjHjlEBSp0h7XO24czs-OQ.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7156)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: j7y17lte
Model: SM-J730F
Id: PPR1.180610.011
Product: j7y17ltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: J730FXXS7CTH2

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by thgoebel** [comment]
From #7989, and me reproducing it:
it seems to only affect sharing with (remote or local) Nextcloud users, but not sharing links to folders.

**Comment by thgoebel** [comment]
And even earlier report is here: #7974, which one do we keep?

**Comment by weinic** [comment]
For information, 
The problem also exists with #7863

**Comment by tobiasKaminsky** [comment]
There is an APK file in PR #79992, which you can install in parallel to your existing Nextcloud app.
It would be great if you can verify the fix.
