### ISSUE TITLE
App crashes on Start 

### ISSUE THREAD

**Issue by ksapp-dell** [nextcloud/android#7988]
### Steps to reproduce
1. Update from previous version to latest version from fdroid
2. Enter serveradress and credentials
3. Crash

Next time it crashes immediately.

### Expected behaviour
- no crash 

### Actual behaviour
- crash

### Can you reproduce this problem on https://try.nextcloud.com?
No - didn't try because the previous version was working fine with the existing server setup

### Environment data
Android version:
8.0
Device model: 
Samsung S7 flat

Stock or customized system:
Stock
Nextcloud app version:
3.15.0
Nextcloud server version:
19.08
Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by ksapp-dell** [comment]
Hi, i probes around a little bit and it has something to Du with my Nextcloud user. 
After the crash I wanted to revert to 3.14.1 and now it is crashing as well. I tested around and if I choose another Nextcloud user then the old version 3.14.1 works again.
If I log the features out and log in my regular user, 3.14.1 starts to crash again. I went to my desktop and logged into Nextcloud with my regular user and there was a corrupt  trashbin. I cleaned the database and the trashbin is fine again.
But 3.14.1 keeps on crashing with my regular user.  The output of 3.14.1 is this:

Any idea how I can repair this  ? 


************ CAUSE OF ERROR ************

java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at com.owncloud.android.ui.adapter.OCFileListAdapter.showFederatedShareAvatar(OCFileListAdapter.java:598)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.onBindViewHolder(OCFileListAdapter.java:472)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
	at android.view.View.layout(View.java:20857)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
	at android.view.View.layout(View.java:20857)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
	at android.view.View.layout(View.java:20857)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20857)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1780)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1546)
	at android.view.View.layout(View.java:20857)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1996)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:20857)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:20857)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20857)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20857)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20857)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:20857)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:945)
	at android.view.View.layout(View.java:20857)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2956)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2643)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1780)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7827)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: herolte
Model: SM-G930F
Id: R16NW
Product: heroltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: G930FXXU8ETI2

**Comment by ksapp-dell** [comment]
I tried a little more and now I can get also the new app going. After installation on my S7 I can log in as normal.  After log in, Android asks for permissions to access files and photos and imeditally after that I have to change the view of the files and folders from standard mode to the bigger folder icons and then it does not crash ??
If I switch back to the standard view mode the app  crash again and i have to reinstall the app again.

**Comment by ksapp-dell** [comment]
![Screenshot_20210215-173927_Nextcloud](https://user-images.githubusercontent.com/62463497/107972895-c849ac80-6fb4-11eb-9a8e-601206468cc7.jpg)
That's what I mean with ,bigger folder icons' by switching to this icons the app is working so far.

**Comment by ksapp-dell** [comment]
This bug is reproducible for me. I switched the view back to listmode instead of ,bigger icons' and the app crashes immediately. In this case even deleting app data does not help. I have to uninstall the app and reinstall it again.

************ CAUSE OF ERROR ************

java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at com.owncloud.android.ui.adapter.OCFileListAdapter.showFederatedShareAvatar(OCFileListAdapter.java:573)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.onBindViewHolder(OCFileListAdapter.java:447)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
	at android.view.View.layout(View.java:20857)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
	at android.view.View.layout(View.java:20857)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
	at android.view.View.layout(View.java:20857)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20857)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1780)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1546)
	at android.view.View.layout(View.java:20857)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1996)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:20857)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:20857)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20857)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20857)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20857)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:20857)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:945)
	at android.view.View.layout(View.java:20857)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2956)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2643)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1780)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7827)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: herolte
Model: SM-G930F
Id: R16NW
Product: heroltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: G930FXXU8ETI2

**Comment by tobiasKaminsky** [comment]
@ksapp-dell this seems to crash due to your shared user.
Can you post the userIds of those users?
(if you do not want to expose the names, you can change it by aaa, but please make sure to have an special char remained, e.g:
"Tobias@Kaminsky" -> forename@lastname

**Comment by ksapp-dell** [comment]
You were right. There was a user @Test . I deleted the user and now it is fine.
The interesting part is, that the app was work as long I switched the view to the bigger icons.
Anyway - for me it is solved. Thank you.

**Comment by tobiasKaminsky** [comment]
Thanks for verifying it!
I will work on a fix.

**Comment by tobiasKaminsky** [comment]
There is an APK file in PR #8027, which you can install in parallel to your existing Nextcloud app.
It would be great if you can verify the fix.

**Comment by ksapp-dell** [comment]
Downloaded was ok, install was ok. App crashes on start up - even before setting up the server.
Android says ,Nextcloud QA crashed' and nothing more is possible.
