### ISSUE TITLE
nextcloud dev crash

### ISSUE THREAD

**Issue by hj-beckers** [nextcloud/android#7996]
### Steps to reproduce
1. 
2. 
3. 
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Credentials.kt)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Credentials.kt)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:330)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:304)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:276)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:229)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:818)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20210203
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: samsung
Device: trlte
Model: SM-N910F
Id: MMB29M
Product: trltexx

************ FIRMWARE ************
SDK: 23
Release: 6.0.1
Incremental: N910FXXU1DRI2
### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Can you tell us what you did? 
Was this a fresh installation? When does it happen?

**Comment by hj-beckers** [comment]
I start it - it crashes ...
No new installation. I see the root directory and immediately the message "nextcloud dev angehalten (= stopped)" appears. The non-dev NC version (3.15.0, installed after the crashes) works. I use the versions from f-droid.org.

**Comment by tobiasKaminsky** [comment]
> Version: 20210203

This is rather old, can you update?

**Comment by hj-beckers** [comment]
This is the latest version f-droid offers. Do You have a link to a newer apk? /android/releases has only tar.gz/zip-versions.

**Comment by tobiasKaminsky** [comment]
https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.nextcloud.android.beta.yml#L6573

there should be a new version soon.

**Comment by hj-beckers** [comment]
Over the weekend I tried nextcloud-dev-202102[17|20].apk from download.nextcloud.com/android/nightly. Their installation was refused/stopped with an error. This morning fdroid offered 20210219. This could be installed, but on start the same crash happens.

**Comment by tobiasKaminsky** [comment]
You cannot mix Fdroid and manual apk for download.nc.c, as they are signed/built with a different key.

Is it the same stacktrace?

**Comment by hj-beckers** [comment]
I hope so. I had to copy the error in two steps. I marked the second with "SECOND screencopy". Could it be that my device/software is to old (Samsung Galaxy Note 4, Android 6.0.1, 3 GB)?

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Credentials.kt)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Credentials.kt)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:330)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:304)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:276)
	at com.owncloud.android.operations.RefreshFolderOperation.run

SECOND Screencopy

at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:229)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:818)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20210219
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: samsung
Device: trlte
Model: SM-N910F

**Comment by hj-beckers** [comment]
Just installed 20210220 (f-droid.org) and it gets in an endless loop. It even survives an cold boot. After installation it started itself (?, I'm not sure, but I didn't start it). And it must have put itself into autostart, because even after an cold start it immediately crashes again. My smartphone changes only between "nextcloud dev stopped" and a new crash. I can't stop it over the list of last programs.
SO: how to I get my device back into a workable state?

**Comment by hj-beckers** [comment]
Could help myself: Entered Save Mode and removed nextcloud-dev

**Comment by tobiasKaminsky** [comment]
Does this also happen with another server, e.g. try.nextcloud.com?

**Comment by hj-beckers** [comment]
Sorry, but I have no chance to enter anything. I start it - i crashes/goes into an endless loop.  But others seem to have the same/similiar problem (see above).

**Comment by NotSoImportant** [comment]
As I was made aware maybe ipv4 vs ipv6 connectivity is an issue (although stacktrace is different, but I either had both issue or they are related): #7400

**Comment by zian92** [comment]
Hey, 
I am currently facing the exact same issue. 
I changed my password of the nextcloud login. After that, the application crashes with the shown stack trace. Changing it back does not resolve the issue. 

The android app has perfectly worked for weeks. It did not offer to enter new credentials.

**Comment by bignose-debian** [comment]
I have today encountered substantially the same crash as reported originally:

```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Unknown Source:8)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Unknown Source:2)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:277)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: google
Device: bullhead
Model: Nexus 5X
Id: OPM2.171026.006.H1
Product: bullhead

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: a477551705
```

This is the latest stable release in F-Droid, no update is offered.

**Comment by bignose-debian** [comment]
I am unable to re-open this GitHub issue, but in response to @github-actions request: Yes this issue remains unresolved, and should be open until it is resolved.

**Comment by julot57** [comment]
Hi,

facing the same issue after a login / password change on server. version 30160190
