### ISSUE TITLE
DocumentFile.createFile returns null instead of creating a file

### ISSUE THREAD

**Issue by zell-mbc** [nextcloud/android#8028]
I am the developer of an application and I'd like to offer my users the possibility to create backups/exports on Nextcloud.
I seem to have a similar issue as this https://github.com/nextcloud/android/issues/7350 which unfortunately didn't get resolved.

I can select the Nextcloud folder just fine and get what I think is a proper Uri back.
But when I execute _createFile_ I run into a _Failed to create document_ exception. File type and selected folder don’t seem to matter. 

According to the issue referenced above, this should work, but I can’t figure out where things go wrong for me.

The below screen shot shows my code sequence with the content of the variables for reference:

![image](https://user-images.githubusercontent.com/29018767/108755252-4ecb3480-7547-11eb-8d15-19b833a8c086.png)

### Steps to reproduce
1. Select folder from Nextcloud storage provider
![image](https://user-images.githubusercontent.com/29018767/108756144-6f47be80-7548-11eb-8c93-67f04130cfc8.png)

![image](https://user-images.githubusercontent.com/29018767/108756375-b6ce4a80-7548-11eb-93ba-0547588aec97.png)

2. Execute DocumentFile.FromTreeUri
3. Try to create a file in selected folder via folder.createFile

### Expected behaviour
- createFile returns a Uri for an empty file

### Actual behaviour
- createFile returns null, always

### Environment data
Android version: 11

Device model: OnePlus 8 Pro

Stock or customized system: Stock

Nextcloud app version: 3.15.0

Nextcloud server version: 20.0.7

Stack trace:

```
W/DocumentsContract: Failed to create document
    android.os.ParcelableException: java.io.FileNotFoundException: Failed to upload document with path /MediLog-2021-02-22.csv
        at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:82)
        at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:79)
        at android.os.Parcel.readParcelable(Parcel.java:3281)
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2368)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
        at android.content.ContentProviderProxy.call(ContentProviderNative.java:755)
        at android.content.ContentResolver.call(ContentResolver.java:2449)
        at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1375)
        at androidx.documentfile.provider.TreeDocumentFile.createFile(TreeDocumentFile.java:53)
        at androidx.documentfile.provider.TreeDocumentFile.createFile(TreeDocumentFile.java:45)
        at com.zell_mbc.medilog.data.ViewModel.exportCSVFile(ViewModel.kt:372)
        at com.zell_mbc.medilog.MainActivity.onActivityResult(MainActivity.kt:680)
        at android.app.Activity.dispatchActivityResult(Activity.java:8316)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5164)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5212)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2198)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:7959)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
     Caused by: java.io.FileNotFoundException: Failed to upload document with path /MediLog-2021-02-22.csv
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.os.ParcelableException.readFromParcel(ParcelableException.java:56)

```

**Comment by AndyScherzinger** [comment]
Cc @tobiasKaminsky for feedback

**Comment by tobiasKaminsky** [comment]
Do you see any logs on Android Files side?

@grote maybe you have an idea?

**Comment by zell-mbc** [comment]
Thanks for getting involved Gents. As far as the logs go, you mean things log a core dump output in the file system? Can't see anything no unexpected files nowhere. I use a file manager which also show hidden files, but even with this turned on, I don't see anything unusual.

**Comment by grote** [comment]
Who is throwing `java.io.FileNotFoundException: Failed to upload document with path /MediLog-2021-02-22.csv` ? Is this coming from Nextcloud? (The stacktrace unfortunately doesn't show)

If it is from Nextcloud, there might be more logs right before that stacktrace which might provide more insight.

**Comment by zell-mbc** [comment]
No, it's my Android app. I get the execption inside of AndroidStudio.

**Comment by grote** [comment]
Android Studio has a logcat tab that can show you *all* system logs, not only from your own app. If Nextcloud doesn't say much, try a development build of it.

Other things to try: Can you save/export files to other storage which is not Nextcloud?

**Comment by zell-mbc** [comment]
> Android Studio has a logcat tab that can show you _all_ system logs, not only from your own app. 

I created the error a few times now, but I don't see any corresponding entries in Logcat.
 
> If Nextcloud doesn't say much, try a development build of it.

The only (visible) interaction with Nextcloud in this process is when I navigate the NextCloud folders as shown in the "Test" screen shot above. After that my app resumes control and the Uri is passed to me. Is there a way to observe what's happening inside the Nextcloud app when I try to write the file? A log file somewhere maybe?

> Other things to try: Can you save/export files to other storage which is not Nextcloud?

Yes, storing on the local file system works fine with this code.

By the way, if you need to see the context of the createFile call, the source code is available here: https://gitlab.com/toz12/medilog/-/blob/master/app/src/main/java/com/zell_mbc/medilog/data/ViewModel.kt
Line 365 for creating a CSV file, and 416 for creating a ZIP file, both won't work.

**Comment by grote** [comment]
>  Is there a way to observe what's happening inside the Nextcloud app when I try to write the file? A log file somewhere maybe?

The release build of Nextcloud might not show too much log out put (did you select No Filter in the logcat view?). If so, you can compile the app from this repo and do your test against that. I've been doing this and got lots of logs.

> By the way, if you need to see the context of the createFile call, the source code is available here:

Ah MediLog. Nice app, been using that. I've been bitten by that proguard error in 2.0 as well :P

Try turning this into a suspend function https://gitlab.com/toz12/medilog/-/blob/master/app/src/main/java/com/zell_mbc/medilog/data/ViewModel.kt#L409 with `withContext(Dispatchers.IO)` to ensure you are not calling this from the UI Thread.

**Comment by zell-mbc** [comment]
>  (did you select No Filter in the logcat view?

Ah, I didn't :-)
But removing the filter didn't change much, more seemingly unrelated entries, but none which appear the time the error happens.

> Ah MediLog. Nice app, been using that. I've been bitten by that proguard error in 2.0 as well :P

Now that is a funny coincidence :-), I hope you read my "do-not-uninstall" note in time and things worked out fine in the end. That event is the exact reason why I am looking into adding Nextcloud support as a priority, I want to offer automated backups and the files need to somehow get off the phone to qualify as proper backup.

> Try turning this into a suspend function

Agree, this whole import / export section needs a substantial refactoring.

**Comment by grote** [comment]
> > Try turning this into a suspend function

> Agree, this whole import / export section needs a substantial refactoring.

The reason I suggest this is to ensure that you are not running into the same network on main thread exception like in the related issues.

> I am looking into adding Nextcloud support as a priority, I want to offer automated backups 

Off-topic here, but may I suggest to simply use the system's backup functionality?

Can also require encrypted backup transport: https://github.com/seedvault-app/seedvault/wiki/FAQ

**Comment by zell-mbc** [comment]
> The reason I suggest this is to ensure that you are not running into the same network on main thread exception like in the related issues.

That was it, I moved things over to a Coroutine and bingo, file is saved...and synced!
Thank you very much for that hint.
