### ISSUE TITLE
fc

### ISSUE THREAD

**Issue by jookk** [nextcloud/android#8049]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: android.os.DeadSystemException
	at android.app.ActivityThread.installContentProviders(Unknown Source:55)
	at android.app.ActivityThread.handleBindApplication(Unknown Source:1195)
	at android.app.ActivityThread.access$1400(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:710)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loop(Unknown Source:242)
	at android.app.ActivityThread.main(Unknown Source:98)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
Caused by: android.os.DeadSystemException
	... 10 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: xiaomi
Device: willow
Model: Redmi Note 8T
Id: QKQ1.200114.002
Product: willow

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V12.0.2.0.QCXMIXM

**Comment by tobiasKaminsky** [comment]
Is this happening reliable?
It looks to me like a pure Android stacktrace.
Maybe out of memory, or something like this…
