### ISSUE TITLE
Crash aplication upload

### ISSUE THREAD

**Issue by didi-loiola** [nextcloud/android#8073]
```
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1703)
	at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1743)
	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:321)
	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:286)
	at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:276)
	at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:228)
	at com.owncloud.android.ui.activity.UploadFilesActivity.onCheckAvailableSpaceFinish(UploadFilesActivity.java:437)
	at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:72)
	at com.owncloud.android.ui.asynctasks.CheckAvailableSpaceTask.onPostExecute(CheckAvailableSpaceTask.java:34)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.-wrap1(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:7000)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: gtaxlwifi
Model: SM-T580
Id: M1AJQ
Product: gtaxlwifixx

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: T580XXS5CTK1
```

**Comment by tobiasKaminsky** [comment]
Do you know what you did to reproduce this crash?

**Comment by didi-loiola** [comment]
The error occurred when I tried to upload a file with 2gb in size. It happened a few times, and I identified that the application even with the storage defined in the SD card it still copies the file to the internal memory on the device, after insisting on uploading this file it presents the error shown above

**Comment by tobiasKaminsky** [comment]
Do you have enough space on your internal memory?

**Comment by didi-loiola** [comment]
> Do you have enough space on your internal memory?

Yes, both the SD card and the internal memory had enough memory although the internal memory was left with only 1GB free

**Comment by tobiasKaminsky** [comment]
> java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

According to docs this may happen if you inbetween already changed to another screen on Android.
Can you check if this also happens if you do nothing after starting upload?
