### ISSUE TITLE
unable to share folder with read and put or put only rights

### ISSUE THREAD

**Issue by RobinSegura** [nextcloud/android#8077]
### Steps to reproduce
1. Create empty folder
2. Créate sharing link
3. Change permissions of the link from read only to put only or "read and put files"

### Expected behaviour
- should change access rights of the folder

### Actual behaviour
- application crash with logs bellow

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Accessing result data after operation failed!
	at com.owncloud.android.lib.common.operations.RemoteOperationResult.getData(RemoteOperationResult.java:486)
	at com.owncloud.android.utils.ErrorMessageAdapter.getMessageForUpdateShareOperations(ErrorMessageAdapter.java:204)
	at com.owncloud.android.utils.ErrorMessageAdapter.getMessageForResultAndOperation(ErrorMessageAdapter.java:152)
	at com.owncloud.android.utils.ErrorMessageAdapter.getErrorCauseMessage(ErrorMessageAdapter.java:79)
	at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:380)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoteOperationFinish(FileDisplayActivity.java:1704)
	at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:734)
	at com.owncloud.android.services.-$$Lambda$OperationsService$KsB1LbjHjlEBSp0h7XO24czs-OQ.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6766)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: CROSSCALL
Model: Trekker-X4

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: L637_10.4.1

**Comment by tobiasKaminsky** [comment]
Please try 3.15.1 RC1 via Play store beta and re-open if it still happens.

**Comment by RobinSegura** [comment]
Fixed in 3.15.1 
Thank you @tobiasKaminsky
