### ISSUE TITLE
Nextcloud dev in crash loop on missing server

### ISSUE THREAD

**Issue by mikini** [nextcloud/android#8082]
### Steps to reproduce
1. Install dev v. 20210224 (currently latest on F-Deoid)
2. Connect to account on server 
3. Shutdown server

### Expected behaviour
- Application handles missing server connectivity in a sensible way

### Actual behaviour
- Application crashes in loop

### Can you reproduce this problem on https://try.nextcloud.com?
- if you shut it down I'll test

### Environment data
Android version:
9

Device model: 
Samsung Galaxy S8

Stock or customized system:
Stock

Nextcloud app version:
dev 20210224

Nextcloud server version:
Was at 20-something (latest in Syncloud) 

Reverse proxy:
No

#### Web server error log
N/A

#### Nextcloud log (data/nextcloud.log)
N/A

#### Android stack trace
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: java.net.ConnectException: Failed to connect to nextcloud.mikini.dk/109.57.224.233:443
	at com.nextcloud.common.OkHttpMethodBase.execute(OkHttpMethodBase.kt:174)
	at com.nextcloud.client.network.ConnectivityServiceImpl.isInternetWalled(ConnectivityServiceImpl.java:75)
	at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:207)
	at com.owncloud.android.utils.-$$Lambda$FilesSyncHelper$78U1WN_nzr5HiGIrRZMThSEamz8.run(Unknown Source:10)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.net.ConnectException: Failed to connect to nextcloud.mikini.dk/109.57.224.233:443
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at com.nextcloud.common.OkHttpMethodBase.execute(OkHttpMethodBase.kt:171)
	... 4 more
Caused by: java.net.ConnectException: failed to connect to nextcloud.mikini.dk/109.57.224.233 (port 443) from /192.168.1.136 (port 36304) after 10000ms: isConnected failed: EHOSTUNREACH (No route to host)
	at libcore.io.IoBridge.isConnected(IoBridge.java:278)
	at libcore.io.IoBridge.connectErrno(IoBridge.java:187)
	at libcore.io.IoBridge.connect(IoBridge.java:129)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:621)
	at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.kt:63)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
	... 20 more
Caused by: android.system.ErrnoException: isConnected failed: EHOSTUNREACH (No route to host)
	at libcore.io.IoBridge.isConnected(IoBridge.java:267)
	... 30 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20210224
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: samsung
Device: dreamlte
Model: SM-G950F
Id: PPR1.180610.011
Product: dreamltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G950FXXSBDTJ1
```

**Comment by mikini** [comment]
After now having restarted the server with a clean installation of [Syncloud](https://syncloud.org/) waiting for me to go setup Nextcloud the dev application crashes even more violently. Restarting, I guess, 2 times per second and hurting itself into the foreground at each attempt making Android completely useless until it will finally detect your frantic attempt to use the application shifter key to shut down the app.

The original behaviour was less violent and your could actually manage to see/press the report/shutdown option in the crash dialogue and put the application into the background.

At one attempt, though, I seem to have been able to press report and when I came back to the phone afterwards I got this exception dump, indicating something is not right with around SSL/TLS (nextcloud's requests to the domain will hit the Syncloud admin/setup interface which is initially deployed with a self signed certificate):

```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: com.owncloud.android.lib.common.network.CertificateCombinedException
	at com.nextcloud.common.OkHttpMethodBase.execute(OkHttpMethodBase.kt:174)
	at com.nextcloud.client.network.ConnectivityServiceImpl.isInternetWalled(ConnectivityServiceImpl.java:75)
	at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:207)
	at com.owncloud.android.utils.-$$Lambda$FilesSyncHelper$78U1WN_nzr5HiGIrRZMThSEamz8.run(Unknown Source:10)
	at java.lang.Thread.run(Thread.java:764)
Caused by: javax.net.ssl.SSLHandshakeException: com.owncloud.android.lib.common.network.CertificateCombinedException
	at org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:361)
	at org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1136)
	at org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1091)
	at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:878)
	at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:749)
	at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:714)
	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:833)
	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:706)
	at org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:230)
	at org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:209)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at com.nextcloud.common.OkHttpMethodBase.execute(OkHttpMethodBase.kt:171)
	... 4 more
Caused by: java.security.cert.CertificateException: com.owncloud.android.lib.common.network.CertificateCombinedException
	at org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1654)
	at org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
	at org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:567)
	at org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1097)
	at org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1081)
	... 29 more
Caused by: com.owncloud.android.lib.common.network.CertificateCombinedException
	at com.owncloud.android.lib.common.network.AdvancedX509TrustManager.checkServerTrusted(AdvancedX509TrustManager.java:104)
	at org.conscrypt.Platform.checkServerTrusted(Platform.java:437)
	at org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1646)
	... 33 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20210224
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: samsung
Device: dreamlte
Model: SM-G950F
Id: PPR1.180610.011
Product: dreamltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G950FXXSBDTJ1
```
# screenshot 
![Screenshot_20210301-111256_Nextcloud dev](https://user-images.githubusercontent.com/1330166/109483467-2ecfcf80-7a77-11eb-9eb3-67548d3fa5a5.jpg)
