### ISSUE TITLE
Crash while sharing files 

### ISSUE THREAD

**Issue by ingebrixen** [nextcloud/android#8096]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Accessing result data after operation failed!
	at com.owncloud.android.lib.common.operations.RemoteOperationResult.getData(RemoteOperationResult.java:486)
	at com.owncloud.android.utils.ErrorMessageAdapter.getMessageForCreateShareOperations(ErrorMessageAdapter.java:254)
	at com.owncloud.android.utils.ErrorMessageAdapter.getMessageForResultAndOperation(ErrorMessageAdapter.java:143)
	at com.owncloud.android.utils.ErrorMessageAdapter.getErrorCauseMessage(ErrorMessageAdapter.java:79)
	at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:380)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoteOperationFinish(FileDisplayActivity.java:1704)
	at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:734)
	at com.owncloud.android.services.-$$Lambda$OperationsService$KsB1LbjHjlEBSp0h7XO24czs-OQ.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:280)
	at android.app.ActivityThread.main(ActivityThread.java:6706)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Sony
Device: G8441
Model: G8441
Id: 47.2.A.11.228
Product: G8441

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 3311891731

Ceashes every time

**Comment by AndyScherzinger** [comment]
@ingebrixen can you retest with 3.15.1 RC1 (via the beta tester progamm)?

@tobiasKaminsky just to be safe: afaik this has been fixed by you via 3.15.1 RC1

**Comment by ingebrixen** [comment]
All fine with 3.15.1 RC1. 

I've tried different files. no crashes @AndyScherzinger

**Comment by AndyScherzinger** [comment]
Thanks for the feedback, so closing 👍
