### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by FreeNameAreOutOfStock** [nextcloud/android#8107]
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{f1c7a61 u0 com.nextcloud.android.beta/com.nextcloud.client.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1769)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20200913
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: tucana
Model: Mi Note 10
Id: PKQ1.190302.001
Product: tucana

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: V11.0.7.0.PFDMIXM

**Comment by AndyScherzinger** [comment]
Version: 20200913

--> @FreeNameAreOutOfStock please update to a recent dev version please, like 20210302
