### ISSUE TITLE
Starting nc after downloading 05/03/2021

### ISSUE THREAD

**Issue by bapjg** [nextcloud/android#8118]
### Steps to reproduce
1. Pressed download
2. Open app
3. 

### Expected behaviour
- should open nc android client
### Actual behaviour
- ************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.ArrayList.get(int)' on a null object reference
	at com.owncloud.android.lib.common.operations.RemoteOperationResult.getSingleData(RemoteOperationResult.java:527)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:339)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:304)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:276)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:229)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:929)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20210304
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: HONOR
Device: HWBKL
Model: BKL-L09
Id: HUAWEIBKL-L09S
Product: BKL-L09

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.0.0.177C432

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
This is fixed via https://github.com/nextcloud/android/pull/8106 and will be available in tomorrows dev version.
I merged a library change too early and thus app was not ready…

If it still happens on dev version 20210309, then please re-open.
