### ISSUE TITLE
crash while accessing photos

### ISSUE THREAD

**Issue by patman-cp** [nextcloud/android#8126]
### Steps to reproduce
1. Open a photo
2. Crash

### Expected behaviour
- Don't crash

### Actual behaviour
- Crashes stack trace below

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

To hard to edit on my phone, the call trace:

```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 4069512 bytes
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:161)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: android.os.TransactionTooLargeException: data parcel size 4069512 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:575)
	at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:5148)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
	... 7 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: star2qltesq
Model: SM-G965U
Id: QP1A.190711.020
Product: star2qltesq

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G965USQS9FUA2
```

**Comment by tobiasKaminsky** [comment]
Is this photo already downloaded?
From stacktrace I cannot see what is causing it, therefore I need more info when exactly it happens.

**Comment by patman-cp** [comment]
> Is this photo already downloaded?
> From stacktrace I cannot see what is causing it, therefore I need more info when exactly it happens.

No, I uploaded the image on my laptop via the web interface and wanted to download it to my phone but each time I click on it in the app it crashes.

Are there any other log files I can pull off the phone that might help?

**Comment by tobiasKaminsky** [comment]
Can you click on "three dots menu" of this image and download it manually?
And then open it?

I want to know what exactly leads to a crash…

**Comment by patman-cp** [comment]
> Can you click on "three dots menu" of this image and download it manually?

Nope, it looks like it's just plain text, and it's truncated like that :-(

I guess it's part of whatever crash reporting tool the app is using.

> And then open it?
> 
> I want to know what exactly leads to a crash…

I can still download the images, but if I try to view them in the app it crashes.

**Comment by tobiasKaminsky** [comment]
Can you do a screenshot of this?

**Comment by patman-cp** [comment]
What exactly do you want a screen shot of? The crash screen is the same as the text I put in the original report, plus a pop up asking if I want to report the crash.

To reproduce it, I just click on a photo, it briefly shows the image, and then it crashes.

I did notice that this is only happening for one folder and so far any images in that folder - opening images in other folders doesn't crash the app.

If the crash report stack shown is too short, you should probably fix that as a starting point so in the fugutre at least you can get the entire stack. And if there's some other way to capture the entire stack, let me know.

**Comment by tobiasKaminsky** [comment]
I was referring to "it looks like it's just plain text".
I understood as if this was some corrupted view of the image, but actually you were reffering to the error message.

So this is really strange, if it only happens in one folder.
What if you copy such a "corrupted" image in a new folder, or a working image in the "corrupted" folder?

**Comment by tobiasKaminsky** [comment]
Does this also happen when you use a different device?

**Comment by patman-cp** [comment]
- It's crashing if I try to copy or move an image using the app, it just blinks and the app screen goes away, there is no error screen or stack like I posted here.

I used the web interface to move an image from that folder to another folder, and then could access the image via the app.

In the app, I tried moving that image back to the previous folder, and it crashed.

- Other than the web interface, I don't have another device to test this on.

**Comment by tobiasKaminsky** [comment]
So it is only about the one specific folder, and as soon as there is any working image in it, it does not work?

Can you download this file and open it with another image viewer?

**Comment by patman-cp** [comment]
> So it is only about the one specific folder, and as soon as there is any working image in it, it does not work?

Not sure if you meant "any non-working image" but it doesn't matter as I haven't tried to move all of the photos to a different folder.

> 
> Can you download this file and open it with another image viewer?

Not using the app - if I tap the image, the app crashes.

Since you can't reproduce this, to debug it, you really need to fix the stack trace in the error reporting code to show the full stack, or tell me how to get a full stack trace to you. I can't spend a lot time trying to isolate this for you, especially given that the steps I've tried so far are not helping you.

Soon I'll just move everything to a new folder to avoid the problem, but then you'll have this outstanding bug that someone will likely hit in the future and then you'll spend hours trying to debug it again.

**Comment by tobiasKaminsky** [comment]
> you really need to fix the stack trace in the error reporting code to show the full stack,

You already provided all info that is available via Logcat. There is nothing more, as Android does not give us more info.



> > Can you download this file and open it with another image viewer?
> 
> Not using the app - if I tap the image, the app crashes.

To reassure that we are on the same side:
- go into NC app
- download a problematic image via three buttons and select download
- open up a file browser app
- go to Android/media/Nextcloud/accountName/ -> problematic folder
- see the downloaded image and click on it
- this then should open up the image in your default gallery

**Comment by patman-cp** [comment]
That's really bad that you can't get a full stack trace, I don't know how you can debug this without some sort of log output or stack trace.

I had to change from grid view to to list view to see the three buttons and download choice, I selected download for an image, it was visible under the Android folder and opened without issue via the default gallery viewer.

**Comment by tobiasKaminsky** [comment]
> I had to change from grid view to to list view to see the three buttons and download choice, I selected download for an image, it was visible under the Android folder and opened without issue via the default gallery viewer.

Thanks for testing.
As you now have downloaded the image, you should see a green checkmark.
What happens when you click on it now?

Background is, that if you click on a non-downloaded file, the app does not download the entire image, but only a reduced size for preview.
Once you downloaded a file, this is obviously not needed and thus the image is shown in full size.

I am just guessing, but maybe something in process of downloading reduced size and displaying this cached image leads to this trouble…

**Comment by patman-cp** [comment]
> What happens when you click on it now?

It crashes :-(

**Comment by patman-cp** [comment]
With nextcloud app version 3.15.1, it crashes with the same output as listed in this bug.

**Comment by patman-cp** [comment]
This still crashes with 3.16, with the same exception but different size.

`java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1634588 bytes`

Stack generally looks the same with the last 7 function calls not visible.

**Comment by patman-cp** [comment]
Still crashes with Nextcloud app version 3.16.1.
