### ISSUE TITLE
Crash while uploading (from share)

### ISSUE THREAD

**Issue by winny-** [nextcloud/android#8128]
### Steps to reproduce
1. Touch the share button
2. Select nextcloud dev
3. Touch upload
4. app crashes, but media appears to upload successfully (?)

### Expected behaviour
- Upload should complete successfully

### Actual behaviour
- Crashes.
- Noting this appeared to only crash when uploading the first item after upgrading my nextcloud dev client. 
- Subsequent uploads do not appear to crash. 
- However I'm stuck in the "Nextcloud dev crashed" activity, not sure if this is PEBKAC, but open an issue for that problem: #8127

### Environment

```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.ArrayList.get(int)' on a null object reference
	at com.owncloud.android.lib.common.operations.RemoteOperationResult.getSingleData(RemoteOperationResult.java:527)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:339)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:304)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:276)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:229)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20210304
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: motorola
Device: channel
Model: moto g(7) play
Id: QPYS30.85-18-9
Product: channel

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 767ff
```

**Comment by tobiasKaminsky** [comment]
This is fixed via https://github.com/nextcloud/android/pull/8106 and will be available in tomorrows dev version.
I merged a library change too early and thus app was not ready…

If it still happens on dev version 20210309, then please re-open.
