### ISSUE TITLE
[dev] App crash on startup

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#8133]
When starting the app, an error message appears:
```
************ CAUSE OF ERROR ************

java.lang.UnsupportedOperationException: Not used anymore
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:99)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:139)
	at com.owncloud.android.ui.activity.DrawerActivity.lambda$getAndDisplayUserQuota$4$DrawerActivity(DrawerActivity.java:734)
	at com.owncloud.android.ui.activity.-$$Lambda$DrawerActivity$drdUCYgYHawhhF_lMrqiK8ir7OE.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:929)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20210307
Build flavor: versionDev
```

### Environment data
Android version: 10

**Comment by tobiasKaminsky** [comment]
This should be fixed via #8106 merged today.
Can you test dev version built today (>= 20210308) and re-open if it still happens.
