### ISSUE TITLE
Nextcloud Android app crashes when trying to share a directory

### ISSUE THREAD

**Issue by mikoladz** [nextcloud/android#8138]
### Steps to reproduce
1. Open Nextcloud app on Android and go to files.
2. Pick any directory and click the sharing icon.
3. Start typing user name and select once it appears.

### Expected behaviour
- The directory is now shared with the selected user.

### Actual behaviour
- The application crashes.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data

Error message:
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Accessing result data after operation failed!
	at com.owncloud.android.lib.common.operations.RemoteOperationResult.getData(RemoteOperationResult.java:486)
	at com.owncloud.android.utils.ErrorMessageAdapter.getMessageForCreateShareOperations(ErrorMessageAdapter.java:254)
	at com.owncloud.android.utils.ErrorMessageAdapter.getMessageForResultAndOperation(ErrorMessageAdapter.java:143)
	at com.owncloud.android.utils.ErrorMessageAdapter.getErrorCauseMessage(ErrorMessageAdapter.java:79)
	at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:380)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoteOperationFinish(FileDisplayActivity.java:1704)
	at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:734)
	at com.owncloud.android.services.-$$Lambda$OperationsService$KsB1LbjHjlEBSp0h7XO24czs-OQ.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Sony
Device: lilac
Model: G8441
Id: OPM7.181005.003
Product: lilac

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: 76102e37e6

**Comment by tobiasKaminsky** [comment]
This is fixed via 3.15.1, coming today.
If not, please re-open.
