### ISSUE TITLE
crash nextcloud dev android after start aplication #8105

### ISSUE THREAD

**Issue by amcdon03** [nextcloud/android#8148]
### Steps to reproduce
1. Click on Nextcloud app
2. 
3. 

### Expected behaviour
So should open

### Actual behaviour
App opens with spinning circle (loading) then crashes within seconds

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:
Brand: google
Device: redfin
Model: Pixel 5

Stock or customized system:

Nextcloud app version:
ID: com.nextcloud.android.beta
Version: 20210304
Build flavor: versionDev

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.ArrayList.get(int)' on a null object reference
	at com.owncloud.android.operations.GetUserProfileOperation.run(GetUserProfileOperation.java:61)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:139)
	at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:64)
	at com.owncloud.android.operations.RefreshFolderOperation.updateUserProfile(RefreshFolderOperation.java:282)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:923)
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
> Version: 20210304

Please test with a version >= 20210309 as we fixed it there.
If it still happens, please re-open.
