### ISSUE TITLE
I can't open the app

### ISSUE THREAD

**Issue by AnsFed** [nextcloud/android#8153]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.ArrayList.get(int)' on a null object reference
	at com.owncloud.android.lib.common.operations.RemoteOperationResult.getSingleData(RemoteOperationResult.java:527)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:339)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:304)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:276)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:229)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20210304
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: Redmi
Device: joyeuse
Model: Redmi Note 9 Pro
Id: QKQ1.191215.002
Product: joyeuse_eea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V12.0.2.0.QJZEUXM

**Comment by tobiasKaminsky** [comment]
> Version: 20210304

Can you test this with a version >= 20210309 as we fixed this.
If the problem still occurs, please re-open.
