### ISSUE TITLE
error

### ISSUE THREAD

**Issue by R44D44** [nextcloud/android#8155]
### Steps to reproduce
1.  open app
2. open synced folder
3.  
### Expected behaviour
- Tell us what should happen
the app should not show this error. it is unusable this way.
### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:11

Device model: poco x3 nfc

Stock or customized system: custom crdroid

Nextcloud app version: 20210304

Nextcloud server version: unknown/tabdigital

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.ArrayList.get(int)' on a null object reference
	at com.owncloud.android.operations.GetUserProfileOperation.run(GetUserProfileOperation.java:61)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:139)
	at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:64)
	at com.owncloud.android.operations.RefreshFolderOperation.updateUserProfile(RefreshFolderOperation.java:282)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:923)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20210304
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: POCO
Device: surya
Model: POCO X3 NFC
Id: RQ2A.210305.006
Product: lineage_surya

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: eng.gtrcra.20210307.100858

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky

**Comment by R44D44** [comment]
this issue disappeared with todays nextcloud update. thanx for looking into it.
