### ISSUE TITLE
I try solve conflict

### ISSUE THREAD

**Issue by eduardomazolini** [nextcloud/android#8163]
```
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{b9d654f u0 com.nextcloud.android.beta/com.owncloud.android.files.services.FileUploader}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1975)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7564)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20210310
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: xiaomi
Device: willow
Model: Redmi Note 8T
Id: QKQ1.200114.002
Product: willow_eea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V12.0.2.0.QCXEUXM
```

**Comment by tobiasKaminsky** [comment]
Can you exactly tell us what lead to this crash?

**Comment by eduardomazolini** [comment]
When I click on the notification it crashes. And requests to send the
report.

Eduardo Mazolini


Em seg., 15 de mar. de 2021 às 08:01, Tobias Kaminsky <
***@***.***> escreveu:

**Comment by tobiasKaminsky** [comment]
Which notification? The one that lets you solve the conflict?
