### ISSUE TITLE
Bug in v 3.16RC1

### ISSUE THREAD

**Issue by szaimen** [nextcloud/android#8174]
### Steps to reproduce
1. Click on create file from template
2. Crash

```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to read from field 'java.util.Map com.owncloud.android.lib.common.TemplateList.templates' on a null object reference
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment$FetchTemplateTask.onPostExecute(ChooseTemplateDialogFragment.java:417)
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment$FetchTemplateTask.onPostExecute(ChooseTemplateDialogFragment.java:373)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.access$900(AsyncTask.java:199)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: beyond0
Model: SM-G970F
Id: RP1A.200720.012
Product: beyond0lteeea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: G970FXXS9EUB1
```

**Comment by Derkades** [comment]
Same issue when creating just a regular text file
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to read from field 'java.util.Map com.owncloud.android.lib.common.TemplateList.templates' on a null object reference
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment$FetchTemplateTask.onPostExecute(ChooseTemplateDialogFragment.java:417)
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment$FetchTemplateTask.onPostExecute(ChooseTemplateDialogFragment.java:373)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.access$900(AsyncTask.java:199)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: sargo
Model: Pixel 3a
Id: RQ2A.210305.006
Product: sargo

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 7119741
```

**Comment by tobiasKaminsky** [comment]
Thanks, this will be fixed with RC2, via an update of library.
