### ISSUE TITLE
App crashes when changing file order

### ISSUE THREAD

**Issue by massenmensch** [nextcloud/android#8175]
### Steps to reproduce
1. Open any Folder
2. Change order to recently first
3. Search for anything, but abort search while it's loading by using the system's back-arrow
4. Change order to A-Z, A first

### Expected behaviour
Files should be sorted alphabetically

### Actual behaviour
App crashes. 

### Can you reproduce this problem on https://try.nextcloud.com?
No, as it's an error within the Android App

### Environment data
Android version: 10

Device model: Huawei SNE-LX1

Stock or customized system: Stock (with Huawei EMUI)

Nextcloud app version: 30150190

Nextcloud server version: /

Reverse proxy: /

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.util.ConcurrentModificationException
	at java.util.ArrayList.sort(ArrayList.java:1472)
	at java.util.Collections.sort(Collections.java:208)
	at com.owncloud.android.utils.FileSortOrderByName.sortCloudFiles(FileSortOrderByName.java:52)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.setSortOrder(OCFileListAdapter.java:1124)
	at com.owncloud.android.ui.fragment.OCFileListFragment.sortFiles(OCFileListFragment.java:1321)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onSortingOrderChosen(FileDisplayActivity.java:1250)
	at com.owncloud.android.ui.dialog.SortingOrderDialogFragment$OnSortOrderClickListener.onClick(SortingOrderDialogFragment.java:181)
	at android.view.View.performClick(View.java:7192)
	at android.view.View.performClickInternal(View.java:7166)
	at android.view.View.access$3500(View.java:824)
	at android.view.View$PerformClick.run(View.java:27592)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWSNE
Model: SNE-LX1
Id: HUAWEISNE-L21
Product: SNE-LX1

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.0.0.245C432

```

**Comment by tobiasKaminsky** [comment]
This happened for some devices/Android versions a while ago, but we could not really tracked it down…
