### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Rothammel** [nextcloud/android#8193]
************ CAUSE OF ERROR ************

android.database.SQLException: ERROR content://org.nextcloud/capabilities
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:321)
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:255)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:309)
	at android.content.ContentResolver.insert(ContentResolver.java:1841)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveCapabilities(FileDataStorageManager.java:1960)
	at com.owncloud.android.operations.GetCapabilitiesOperation.run(GetCapabilitiesOperation.java:51)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:139)
	at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:64)
	at com.owncloud.android.ui.activity.DrawerActivity.lambda$fetchExternalLinks$5$DrawerActivity(DrawerActivity.java:1036)
	at com.owncloud.android.ui.activity.-$$Lambda$DrawerActivity$RaU_Wf1ywDAbBMs71OnisiylNgA.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Redmi
Device: begonia
Model: Redmi Note 8 Pro
Id: QP1A.190711.020
Product: begonia_eea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V12.0.4.0.QGGEUXM

**Comment by tobiasKaminsky** [comment]
Do you know what you did to trigger this?
