### ISSUE TITLE
Crash while navigating task list not activating application

### ISSUE THREAD

**Issue by mikini** [nextcloud/android#8195]
### Crash notification
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.markCommentsAsRead()' on a null object reference
	at com.owncloud.android.ui.fragment.FileDetailFragment$1.onPageScrolled(FileDetailFragment.java:242)
	at androidx.viewpager.widget.ViewPager.dispatchOnPageScrolled(ViewPager.java:1930)
	at androidx.viewpager.widget.ViewPager.onPageScrolled(ViewPager.java:1904)
	at androidx.viewpager.widget.ViewPager.pageScrolled(ViewPager.java:1842)
	at androidx.viewpager.widget.ViewPager.scrollToItem(ViewPager.java:694)
	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1786)
	at android.view.View.layout(View.java:16636)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16636)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16636)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1732)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
	at android.view.View.layout(View.java:16636)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1996)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:16636)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:16636)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16636)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16636)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16636)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16636)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
	at android.view.View.layout(View.java:16636)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:606)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: google
Device: flo
Model: Nexus 7
Id: MOB30X
Product: razor

************ FIRMWARE ************
SDK: 23
Release: 6.0.1
Incremental: 3036618
```

**Comment by tobiasKaminsky** [comment]
Do you know which steps lead to this?

**Comment by mikini** [comment]
I had left the NC application with no activity running. I was navigating  the task list switching between two other applications when this crash popped to front.

**Comment by mikini** [comment]
I have since determined that the device has the latest official firmware from Google ([6.0.1 for razor aka. flo "MOB30X" variant](https://developers.google.com/android/ota#razor)).

Are you interested in me doing further tests on this latest official release?

However, there are also LineageOS 16.1 & 17.1 releases dubbed flox which should bring it up from 6.

More info about the device and updates:
* Wikipedia: https://en.wikipedia.org/wiki/Nexus_7_(2013)
* GSM Arena spec.: https://www.gsmarena.com/asus_google_nexus_7_(2013)-5600.php
* LineageOS spec. (yml): https://github.com/LineageOS/lineage_wiki/blob/master/_data/devices/flo.yml
* https://wiki.lineageos.org/devices/flo
* https://wiki.lineageos.org/devices/flox/

**Comment by tobiasKaminsky** [comment]
A reliable way to reproduce it would be great, even if it is "only" on your device.

**Comment by AndyScherzinger** [comment]
> Are you interested in me doing further tests on this latest official release?

If you can reproduce the issue than that would be nice while looking at the posted stack trace it seems to be related to a UI interaction _with_ the app itself and the the file details view.
