### ISSUE TITLE
Crash when editing shared file permissions

### ISSUE THREAD

**Issue by mikini** [nextcloud/android#8213]
Was editing a shared file's permissions, specifically removing the "can edit" property. This caused the application to show a busy spinner for app. 30 seconds after which I changed to another application. When returning to NC the application had crashed.

I think there were network problems at the server, or some other still uninvestigated server issue, as I was not able to access NC through the webinterface or via iOS application after this.

Concurrently with this there were an iOS "upload camera roll" with app. 1000 photos running. 

```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to resume activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.RuntimeException: Accessing result data after operation failed!
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4014)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4046)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by: java.lang.RuntimeException: Accessing result data after operation failed!
	at com.owncloud.android.lib.common.operations.RemoteOperationResult.getData(RemoteOperationResult.java:488)
	at com.owncloud.android.utils.ErrorMessageAdapter.getMessageForUpdateShareOperations(ErrorMessageAdapter.java:204)
	at com.owncloud.android.utils.ErrorMessageAdapter.getMessageForResultAndOperation(ErrorMessageAdapter.java:152)
	at com.owncloud.android.utils.ErrorMessageAdapter.getErrorCauseMessage(ErrorMessageAdapter.java:79)
	at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:384)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoteOperationFinish(FileDisplayActivity.java:1704)
	at com.owncloud.android.services.OperationsService$OperationsServiceBinder.dispatchResultIfFinished(OperationsService.java:353)
	at com.owncloud.android.ui.activity.FileActivity.doOnResumeAndBound(FileActivity.java:563)
	at com.owncloud.android.ui.activity.FileActivity.onResume(FileActivity.java:242)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onResume(FileDisplayActivity.java:1146)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
	at android.app.Activity.performResume(Activity.java:7572)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4006)
	... 11 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150151
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: dreamlte
Model: SM-G950F
Id: PPR1.180610.011
Product: dreamltexx

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G950FXXSBDUA3

```

**Comment by tobiasKaminsky** [comment]
If this happens again with a running server, please re-open.
