### ISSUE TITLE
Android error

### ISSUE THREAD

**Issue by rlalak** [nextcloud/android#8214]
************ CAUSE OF ERROR ************

android.database.SQLException: ERROR content://org.nextcloud/file
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:289)
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:255)
	at android.content.ContentProvider.insert(ContentProvider.java:1673)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:336)
	at android.content.ContentResolver.insert(ContentResolver.java:2149)
	at android.content.ContentResolver.insert(ContentResolver.java:2111)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFile(FileDataStorageManager.java:275)
	at com.owncloud.android.datamodel.FileDataStorageManager.createRootDir(FileDataStorageManager.java:926)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:130)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByEncryptedRemotePath(FileDataStorageManager.java:112)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:108)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2401)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8024)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3475)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: walleye
Model: Pixel 2
Id: RP1A.201005.004.A1
Product: walleye

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 6934943

**Comment by tobiasKaminsky** [comment]
Please fill out template and re-open.
