### ISSUE TITLE
Android 11 auto upload crash 

### ISSUE THREAD

**Issue by Linecutterx** [nextcloud/android#8218]
### Steps to reproduce
1. Set up auto upload 
2. Wait for it to crash (file conflict dialog is shown, But this was with a clean directory to upload to 
3. 

### Expected behaviour
- Tell us what should happen
- upload without crashing 

### Actual behaviour
- Tell us what happens
- it crashes 

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum
- 
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
	at com.owncloud.android.ui.activity.ConflictsResolveActivity.onStart(ConflictsResolveActivity.java:187)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8222)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3818)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8506)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: beyond2
Model: SM-G975F
Id: RP1A.200720.012
Product: beyond2lteeea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: G975FXXU9FUBD

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
>     2\. file conflict dialog is shown

What is shown here?
