### ISSUE TITLE
report a bug.

### ISSUE THREAD

**Issue by cs327259852** [nextcloud/android#8227]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.IllegalArgumentException: Trying to execute a remote operation with a NULL Context
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:128)
	at com.owncloud.android.ui.fragment.contactsbackup.ContactsBackupFragment$2.doInBackground(ContactsBackupFragment.java:230)
	at com.owncloud.android.ui.fragment.contactsbackup.ContactsBackupFragment$2.doInBackground(ContactsBackupFragment.java:218)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: lge
Device: flashlmdd
Model: LM-V500N
Id: QKQ1.191021.002
Product: flashlmdd_lao_com

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 203011357550b

**Comment by tobiasKaminsky** [comment]
Do you know when this happened?
