### ISSUE TITLE
bug: automatically closing the application

### ISSUE THREAD

**Issue by Lunovox** [nextcloud/android#8238]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to read from field 'android.widget.TextView com.owncloud.android.databinding.TextFilePreviewBinding.textPreview' on a null object reference
	at com.owncloud.android.ui.preview.PreviewTextFragment.lambda$performSearch$0$PreviewTextFragment(PreviewTextFragment.java:154)
	at com.owncloud.android.ui.preview.-$$Lambda$PreviewTextFragment$G7P0DKoywov3LvjfehsajAMol-U.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6647)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: motorola
Device: athene_f
Model: Moto G (4)
Id: OPJ28.111-22-1
Product: athene_f

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: 1ec4b

**Comment by tobiasKaminsky** [comment]
Please fill out template and re-open.
