### ISSUE TITLE
Error when opening full-sized image

### ISSUE THREAD

**Issue by Schedulaar** [nextcloud/android#8240]
I was looking at pictures. One picture did not have a thumbnail available, hence O pressed the button to show the full-sized image. This error occured.

### Environment data
Android version: 10

Device model: OnePlus 6

Stock or customized system: Stock

```
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Fragment PreviewImageFragment{a13eef0} (4c71ce8f-c211-494f-9e18-ab5a35c2489a)} not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:805)
	at androidx.fragment.app.Fragment.getResources(Fragment.java:869)
	at com.owncloud.android.ui.preview.PreviewImageFragment.lambda$setErrorPreviewMessage$2$PreviewImageFragment(PreviewImageFragment.java:742)
	at com.owncloud.android.ui.preview.-$$Lambda$PreviewImageFragment$lYlNRKiEmwgldJH0g5sQ-_uYXY4.onClick(Unknown Source:2)
	at com.google.android.material.snackbar.Snackbar$1.onClick(Snackbar.java:307)
	at android.view.View.performClick(View.java:7201)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992)
	at android.view.View.performClickInternal(View.java:7170)
	at android.view.View.access$3500(View.java:806)
	at android.view.View$PerformClick.run(View.java:27562)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus6
Model: ONEPLUS A6003
Id: QKQ1.190716.003
Product: OnePlus6

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2103022249

```

**Comment by tobiasKaminsky** [comment]
> , hence O pressed the button

what is O?

**Comment by Schedulaar** [comment]
> > , hence O pressed the button
> 
> what is O? Did you suspended the app?

"O" was a typo. I meant to say "..., hence I pressed the button "Show full-sized image"

I don't think I suspended the app.
