### ISSUE TITLE
Files App Crashes Upon Opening an Image Shared on Team Conversation

### ISSUE THREAD

**Issue by fynali** [nextcloud/android#8244]
### Steps to reproduce
1. Open Talk,
2. Go to a conversation,
3. Tap on an image shared earlier in the group conversation.

### Expected behaviour
- The image should simply open up.

### Actual behaviour
- Files app crashes!

### Environment data
Android version: 11

Device model: Google Pixel 3XL

Stock or customized system: Stock

Nextcloud Files app version: v3.15.0, build 4804

Nextcloud server version: 21.0.0

Reverse proxy:

#### error log from the app
************ CAUSE OF ERROR ************

java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:899)
	at java.util.TimSort.mergeAt(TimSort.java:516)
	at java.util.TimSort.mergeForceCollapse(TimSort.java:457)
	at java.util.TimSort.sort(TimSort.java:254)
	at java.util.Arrays.sort(Arrays.java:1492)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:206)
	at com.owncloud.android.utils.FileSortOrderByName.sortCloudFiles(FileSortOrderByName.java:52)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:922)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1259)
	at com.owncloud.android.ui.asynctasks.FetchRemoteFileTask.onPostExecute(FetchRemoteFileTask.java:133)
	at com.owncloud.android.ui.asynctasks.FetchRemoteFileTask.onPostExecute(FetchRemoteFileTask.java:45)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.access$900(AsyncTask.java:199)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

************ APP INFORMATION ************
ID: sa.gov.tafaul.android.client
Version: 30150090 (build #4804)
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: crosshatch
Model: Pixel 3 XL
Id: RQ2A.210305.006
Product: crosshatch

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 7119741

**Comment by tobiasKaminsky** [comment]
Does this also happen if you go manually within files app to this folder/file?

**Comment by fynali** [comment]
Files won't crash when going to the file/folder directly.
I think this is fixed in the v11.1.7

**Comment by tobiasKaminsky** [comment]
Duplicate of #7782
