### ISSUE TITLE
Can't login with QR code (or manually)

### ISSUE THREAD

**Issue by Seversonic** [nextcloud/android#8245]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.setVisibility(int)' on a null object reference
	at com.owncloud.android.authentication.AuthenticatorActivity.onAuthenticatorTaskCallback(AuthenticatorActivity.java:1178)
	at com.owncloud.android.authentication.AuthenticatorAsyncTask.onPostExecute(AuthenticatorAsyncTask.java:100)
	at com.owncloud.android.authentication.AuthenticatorAsyncTask.onPostExecute(AuthenticatorAsyncTask.java:43)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.access$600(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: dreamqltecan
Model: SM-G950W
Id:
Product: dreamqltevl

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G950WVLS8CTK1

**Comment by beppe9000** [comment]
Me too. App is not useable.... I did the login part manually but it fails anyway (error 401😕 ) on clicking the grant button.
When I use the QR code the app crashes...
```
******** CAUSE OF ERROR ********

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
 at com.owncloud.android.authentication.AuthenticatorActivity.onAuthenticatorTaskCallback(AuthenticatorActivity.java:1178)
 at com.owncloud.android.authentication.AuthenticatorAsyncTask.onPostExecute(AuthenticatorAsyncTask.java:100)
 at com.owncloud.android.authentication.AuthenticatorAsyncTask.onPostExecute(AuthenticatorAsyncTask.java:43)
 at android.os.AsyncTask.finish(AsyncTask.java:681)
 at android.os.AsyncTask.-wrap1(AsyncTask.java)
 at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:698)
 at android.os.Handler.dispatchMessage(Handler.java:110)
 at android.os.Looper.loop(Looper.java:203)
 at android.app.ActivityThread.main(ActivityThread.java:6259)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

******** APP INFORMATION ********
ID: com.nextcloud.client
Version: 30150190
Build flavor: gplay

******** DEVICE INFORMATION ********
Brand: CUBOT
Device: CUBOT_NOTE_Plus
Model: CUBOT NOTE Plus
Id: NRD90M
Product: CUBOT_NOTE_Plus

******** FIRMWARE ********
SDK: 24
Release: 7.0
Incremental: 1526996771
```

**Comment by Seversonic** [comment]
Not sure what I did or how I fixed it, I didnt change anything on Nextcloud or android side. 
I logged out of nextcloud web ui, logged in, regenerated the QR code and then it started working

**Comment by tobiasKaminsky** [comment]
Please re-open if it occurs again.

**Comment by beppe9000** [comment]
> 
> 
> Please re-open if it occurs again.

was the app updated ?
