### ISSUE TITLE
Crashed 

### ISSUE THREAD

**Issue by GEnergetik** [nextcloud/android#8260]
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Couldn't read row 882, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:542)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:77)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:179)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProviderOperation.applyInternal(ContentProviderOperation.java:332)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:309)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:672)
	at android.content.ContentProvider.applyBatch(ContentProvider.java:2147)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:387)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:532)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:520)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:441)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:519)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:401)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:237)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:184)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:269)
	at com.owncloud.android.syncadapter.FileSyncAdapter.syncChildren(FileSyncAdapter.java:345)
	at com.owncloud.android.syncadapter.FileSyncAdapter.synchronizeFolder(FileSyncAdapter.java:289)
	at com.owncloud.android.syncadapter.FileSyncAdapter.onPerformSync(FileSyncAdapter.java:181)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:334)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWELS
Model: ELS-NX9
Id: HUAWEIELS-N29
Product: ELS-N29

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 11.0.0.176C10

**Comment by tobiasKaminsky** [comment]
Please fill out template and re-open.
