### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Bianca339** [nextcloud/android#8274]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=Intent { dat=content://com.google.android.apps.photos.contentprovider/3/1/content://media/external/images/media/21977/ORIGINAL/NONE/image/jpeg/1828485211 flg=0x1 clip={text/uri-list U:content://com.google.android.apps.photos.contentprovider/3/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F21977/ORIGINAL/NONE/image%2Fjpeg/1828485211} }} to activity {com.nextcloud.client/com.blikoon.qrcodescanner.QrCodeActivity}: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=6050, uid=10249 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4491)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4534)
	at android.app.ActivityThread.-wrap20(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=6050, uid=10249 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
	at android.os.Parcel.readException(Parcel.java:1967)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
	at android.content.ContentResolver.query(ContentResolver.java:760)
	at android.content.ContentResolver.query(ContentResolver.java:710)
	at android.content.ContentResolver.query(ContentResolver.java:668)
	at com.blikoon.qrcodescanner.QrCodeActivity.getPathFromUri(QrCodeActivity.java:386)
	at com.blikoon.qrcodescanner.QrCodeActivity.onActivityResult(QrCodeActivity.java:370)
	at android.app.Activity.dispatchActivityResult(Activity.java:7599)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4487)
	... 9 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a5y17lte
Model: SM-A520F
Id: R16NW
Product: a5y17ltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: A520FXXUGCTKA

**Comment by tobiasKaminsky** [comment]
Please fill out template and re-open.
