### ISSUE TITLE
Nextcloud Crash on Android 11

### ISSUE THREAD

**Issue by scryptic86** [nextcloud/android#8277]
************ CAUSE OF ERROR ************

android.view.InflateException: Binary XML file line #7 in com.nextcloud.client:layout/account_setup_webview: Binary XML file line #7 in com.nextcloud.client:layout/account_setup_webview: Error inflating class android.webkit.WebView
Caused by: android.view.InflateException: Binary XML file line #7 in com.nextcloud.client:layout/account_setup_webview: Error inflating class android.webkit.WebView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createView(LayoutInflater.java:774)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:928)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:948)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1002)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
	at com.owncloud.android.authentication.AuthenticatorActivity.onNewIntent(AuthenticatorActivity.java:692)
	at android.app.Activity.performNewIntent(Activity.java:8015)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1409)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1422)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3658)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3670)
	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:53)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7661)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: android.content.pm.PackageManager$NameNotFoundException: Application package com.android.webview not found
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:435)
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:252)
	at android.webkit.WebView.getFactory(WebView.java:2576)
	at android.webkit.WebView.ensureProviderCreated(WebView.java:2570)
	at android.webkit.WebView.setOverScrollMode(WebView.java:2638)
	at android.view.View.<init>(View.java:5321)
	at android.view.View.<init>(View.java:5467)
	at android.view.ViewGroup.<init>(ViewGroup.java:697)
	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
	at android.webkit.WebView.<init>(WebView.java:413)
	at android.webkit.WebView.<init>(WebView.java:355)
	at android.webkit.WebView.<init>(WebView.java:337)
	at android.webkit.WebView.<init>(WebView.java:324)
	... 32 more
Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: android.content.pm.PackageManager$NameNotFoundException: Application package com.android.webview not found
	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:389)
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:402)
	... 44 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus5T
Model: ONEPLUS A5010
Id: RQ2A.210405.006
Product: OnePlus5T

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 7144

**Comment by scryptic86** [comment]
I just realized that I have a custom Webkit installation on my phone. I will check with standard Chrome Webview.
