### ISSUE TITLE
Crash when opening Nextcloud

### ISSUE THREAD

**Issue by knusbaum** [nextcloud/android#8291]
### Steps to reproduce
1. Open the Nextcloud app
2. Wait 
3. Stack trace appears

### Expected behaviour
- app should function normally

### Actual behaviour
- app crashes with stack trace

```
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Couldn't read row 981, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:542)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:77)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:179)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProviderOperation.applyInternal(ContentProviderOperation.java:342)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:314)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:672)
	at android.content.ContentProvider.applyBatch(ContentProvider.java:2179)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:398)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:532)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:520)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:1915)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:438)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:519)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:401)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:237)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:360)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus7Pro
Model: GM1917
Id: QKQ1.190716.003
Product: OnePlus7Pro

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2101212056
```

**Comment by tobiasKaminsky** [comment]
How big is your folder?

**Comment by knusbaum** [comment]
The top level directory is quite small. 1 file 6 folders.

**Comment by AndyScherzinger** [comment]
Did you by any chance move or delete a larger amount of files (as in numbers not file size)

**Comment by knusbaum** [comment]
Not manually, but I have large auto-upload folders.
The application now opens but it freezes when trying to open the auto-upload settings page.

**Comment by AndyScherzinger** [comment]
> The application now opens but it freezes when trying to open the auto-upload settings page.

That would be another issue I think while I don't know what might cause the freeze (except the obvious thing of having to process too many files for display).
