### ISSUE TITLE
Crash while screen rotating

### ISSUE THREAD

**Issue by jeanbruder** [nextcloud/android#8295]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.markCommentsAsRead()' on a null object reference
	at com.owncloud.android.ui.fragment.FileDetailFragment$1.onPageScrolled(FileDetailFragment.java:242)
	at androidx.viewpager.widget.ViewPager.dispatchOnPageScrolled(ViewPager.java:1930)
	at androidx.viewpager.widget.ViewPager.onPageScrolled(ViewPager.java:1904)
	at androidx.viewpager.widget.ViewPager.pageScrolled(ViewPager.java:1842)
	at androidx.viewpager.widget.ViewPager.scrollToItem(ViewPager.java:694)
	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1786)
	at android.view.View.layout(View.java:17989)
	at android.view.ViewGroup.layout(ViewGroup.java:5717)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
	at android.view.View.layout(View.java:17989)
	at android.view.ViewGroup.layout(ViewGroup.java:5717)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
	at android.view.View.layout(View.java:17989)
	at android.view.ViewGroup.layout(ViewGroup.java:5717)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1971)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1737)
	at android.view.View.layout(View.java:17989)
	at android.view.ViewGroup.layout(ViewGroup.java:5717)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1996)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:17989)
	at android.view.ViewGroup.layout(ViewGroup.java:5717)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:17989)
	at android.view.ViewGroup.layout(ViewGroup.java:5717)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
	at android.view.View.layout(View.java:17989)
	at android.view.ViewGroup.layout(ViewGroup.java:5717)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
	at android.view.View.layout(View.java:17989)
	at android.view.ViewGroup.layout(ViewGroup.java:5717)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
	at android.view.View.layout(View.java:17989)
	at android.view.ViewGroup.layout(ViewGroup.java:5717)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
	at android.view.View.layout(View.java:17989)
	at android.view.ViewGroup.layout(ViewGroup.java:5717)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:787)
	at android.view.View.layout(View.java:17989)
	at android.view.ViewGroup.layout(ViewGroup.java:5717)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2718)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2386)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1473)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7049)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:910)
	at android.view.Choreographer.doCallbacks(Choreographer.java:712)
	at android.view.Choreographer.doFrame(Choreographer.java:646)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:896)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6349)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Blackview
Device: P6000
Model: P6000
Id: N4F26M
Product: P6000

************ FIRMWARE ************
SDK: 25
Release: 7.1.1
Incremental: 1523601614

**Comment by tobiasKaminsky** [comment]
Please fill out template and re-open.
