### ISSUE TITLE
SQlite crashed multiple times

### ISSUE THREAD

**Issue by flixofon** [nextcloud/android#8307]
### Steps to reproduce
1.  Open Nextcloud Android App

### Expected behaviour
- normal starting

### Actual behaviour
- on Start, SQlite Database crashes

### Environment data
Android version:

Device model: Xiaomi Mi 9

Stock or customized system: Miui 12.5 / stock

Nextcloud app version: 3.15.1

Nextcloud server version: newest of stable channel

Reverse proxy: not in use

#### Web server error log
```
Nothing with relation to this Problem 
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=1
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(Unknown Source:92)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(Unknown Source:41)
	at android.database.sqlite.SQLiteQuery.fillWindow(Unknown Source:28)
	at android.database.sqlite.SQLiteCursor.fillWindow(Unknown Source:44)
	at android.database.sqlite.SQLiteCursor.getCount(Unknown Source:6)
	at android.content.ContentResolver.query(Unknown Source:201)
	at android.content.ContentResolver.query(Unknown Source:4)
	at android.content.ContentResolver.query(Unknown Source:12)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileCursorForValue(FileDataStorageManager.java:950)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:122)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByEncryptedRemotePath(FileDataStorageManager.java:112)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:108)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2401)
	at android.app.Instrumentation.callActivityOnStart(Unknown Source:0)
	at android.app.Activity.performStart(Unknown Source:31)
	at android.app.ActivityThread.handleStartActivity(Unknown Source:31)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(Unknown Source:140)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(Unknown Source:10)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(Unknown Source:25)
	at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:76)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:52)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loop(Unknown Source:249)
	at android.app.ActivityThread.main(Unknown Source:134)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:313)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150190
Build flavor: gplay
```

**Comment by flixofon** [comment]
No, has nothing to do with big Photo Folder, cause there are only 6G Files stored
