### ISSUE TITLE
Created new odt file using collabora code server

### ISSUE THREAD

**Issue by bubbabear64** [nextcloud/android#8316]
### Steps to reproduce
1. Create new document
2. Enter file name
3. Collabora will execute and report error
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.IllegalStateException: Fragment ChooseRichDocumentsTemplateDialogFragment{d409b83} (9b541160-7b03-4b33-b7ad-b23b96a8fa82) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:900)
	at com.owncloud.android.ui.dialog.ChooseRichDocumentsTemplateDialogFragment$CreateFileFromTemplateTask.doInBackground(ChooseRichDocumentsTemplateDialogFragment.java:291)
	at com.owncloud.android.ui.dialog.ChooseRichDocumentsTemplateDialogFragment$CreateFileFromTemplateTask.doInBackground(ChooseRichDocumentsTemplateDialogFragment.java:256)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160052
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: lge
Device: cv7as
Model: LM-Q720
Id: QKQ1.200308.002
Product: cv7as_fg

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 210552140c31d

### Expected
Should have brought up editor screen
### Actual behaviour
Loads Collabora CODE server ans crashes
### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate
@

**Comment by tobiasKaminsky** [comment]
> Caused by: java.lang.IllegalStateException: Fragment ChooseRichDocumentsTemplateDialogFragment{d409b83} (9b541160-7b03-4b33-b7ad-b23b96a8fa82) not attached to a context.

Have you navigated away or suspended app?
