### ISSUE TITLE
Saving AndOTP backup to Nextcloud fails

### ISSUE THREAD

**Issue by pschichtel** [nextcloud/android#8338]
### Steps to reproduce
1. Create backup in AndOTP
2. Select Nextcloud remote storage
3. save

### Expected behaviour
- Nextcloud should successfully save the backup created by AndOTP on the Nextcloud server

### Actual behaviour
It fails with the following error in logcat:
```05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: Download of filepath to /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/tmp/some/filepath: Unexpected exception
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: android.os.NetworkOnMainThreadException
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1605)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.google.android.gms.org.conscrypt.Platform.blockGuardOnNetwork(:com.google.android.gms@211515046@21.15.15 (150400-371058782):0)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(:com.google.android.gms@211515046@21.15.15 (150400-371058782):2)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:248)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at java.io.BufferedInputStream.read(BufferedInputStream.java:267)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.HttpConnection.isStale(HttpConnection.java:506)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.HttpConnection.closeIfStale(HttpConnection.java:431)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.closeIfStale(MultiThreadedHttpConnectionManager.java:1313)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:382)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:219)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.resources.files.DownloadFileRemoteOperation.downloadFile(DownloadFileRemoteOperation.java:111)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.resources.files.DownloadFileRemoteOperation.run(DownloadFileRemoteOperation.java:88)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:184)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.owncloud.android.operations.DownloadFileOperation.run(DownloadFileOperation.java:168)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:184)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.owncloud.android.providers.DocumentsStorageProvider.openDocument(DocumentsStorageProvider.java:202)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at android.provider.DocumentsProvider.openAssetFile(DocumentsProvider.java:1344)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at android.content.ContentProvider$Transport.openAssetFile(ContentProvider.java:528)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:286)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at android.os.Binder.execTransactInternal(Binder.java:1165)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at android.os.Binder.execTransact(Binder.java:1134)
05-01 22:08:07.884 22332 23587 E DocumentsStorageProvider: RemoteOperationResult(mSuccess=false, mHttpCode=-1, mHttpPhrase=null, mException=android.os.NetworkOnMainThreadException, mCode=HOST_NOT_AVAILABLE, message=null, getLogMessage=Unexpected exception)
```

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 11

Device model: OnePlus 8 Pro

Stock or customized system: stock

Nextcloud app version: 3.15.1

Nextcloud server version: 20.0.8

Reverse proxy: Nginx

**Comment by pschichtel** [comment]
This is a follow up to #4219

**Comment by tobiasKaminsky** [comment]
> 05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: android.os.NetworkOnMainThreadException

It seems that the other app is running the backup thread not in background, and thus it crashes.
Please report it on their side.
