### ISSUE TITLE
Android app crash after login

### ISSUE THREAD

**Issue by storm1er** [nextcloud/android#8342]
### Steps to reproduce
1. Create QR code for AP login
2. Login using Android app (scan QR)
3. App crash

### Expected behaviour
- app does not crash

### Actual behaviour
- app crash

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10

Device model: OnePlus 6

Stock or customized system: stock android

Nextcloud app version: 3.15.1

Nextcloud server version: 21

Reverse proxy: traefik

#### Web server error log
No error nor warn in logs

#### Nextcloud log (data/nextcloud.log)
On Android app, after login attempt

```
************ CAUSE OF ERROR ************

android.database.SQLException: ERROR content://org.nextcloud/file
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:289)
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:255)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:325)
	at android.content.ContentResolver.insert(ContentResolver.java:1854)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFile(FileDataStorageManager.java:275)
	at com.owncloud.android.datamodel.FileDataStorageManager.createRootDir(FileDataStorageManager.java:926)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:130)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByEncryptedRemotePath(FileDataStorageManager.java:112)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:108)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2401)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1514)
	at android.app.Activity.performStart(Activity.java:7838)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3398)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30150190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus6
Model: ONEPLUS A6003
Id: QKQ1.190716.003
Product: OnePlus6

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2103022249
```

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Does it work if you manually log in, without QR?

**Comment by storm1er** [comment]
The same problem happens. The crash screen can be skipped, and the app works flawlessly. Just this errors appears.

My girlfriends also had the error on Samsung Galaxy Note 9.
