### ISSUE TITLE
Crash during auto upload

### ISSUE THREAD

**Issue by tomwimmenhove** [nextcloud/android#8357]
### Steps to reproduce
1. Turn on auto upload
2. Go to sleep
3. Wake up

************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 2062)
#################################################################
Error Code : 2062 (SQLITE_CANTOPEN_EMFILE)
Caused By : Application has opened too many files. Maximum of available file descriptors in one process is 1024 in default.
	(unable to open database file (code 2062))
#################################################################
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1018)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:152)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:141)
	at android.content.ContentResolver.query(ContentResolver.java:779)
	at android.content.ContentResolver.query(ContentResolver.java:710)
	at android.content.ContentResolver.query(ContentResolver.java:668)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUploadStatus(UploadsStorageManager.java:195)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateDatabaseUploadStart(UploadsStorageManager.java:597)
	at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:605)
	at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1414)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: heroqltetmo
Model: SM-G930T
Id: R16NW
Product: heroqltetmo

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: G930TUVSBCTA2

**Comment by tobiasKaminsky** [comment]
How many pending uploads do you have?
