### ISSUE TITLE
android app

### ISSUE THREAD

**Issue by linton1024** [nextcloud/android#8366]
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{ad12951 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2081)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8067)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: cmi
Model: Mi 10 Pro
Id: RKQ1.200826.002
Product: cmi

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 21.4.28

**Comment by AndyScherzinger** [comment]
Hi @linton1024 does this also happen on newer versions?  You seem to run 3.14.0 while 3.15.1 is available via f-droid and 3.16.0 has been published and should become available any time soon.

**Comment by ezaquarii** [comment]
Yeah, I remember that @tobiasKaminsky fixed this problem some time ago.
@linton1024 please update the app to a newest version.
