### ISSUE TITLE
Nextcloud crash android app

### ISSUE THREAD

**Issue by fischer-felix** [nextcloud/android#8368]
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Fragment PreviewImageFragment{8052463} (7b1b677f-2975-450a-9cdd-98ea929390e9) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:900)
	at androidx.fragment.app.Fragment.getResources(Fragment.java:964)
	at com.owncloud.android.ui.preview.PreviewImageFragment.lambda$setErrorPreviewMessage$2$PreviewImageFragment(PreviewImageFragment.java:742)
	at com.owncloud.android.ui.preview.-$$Lambda$PreviewImageFragment$lYlNRKiEmwgldJH0g5sQ-_uYXY4.onClick(Unknown Source:2)
	at com.google.android.material.snackbar.Snackbar$1.onClick(Snackbar.java:351)
	at android.view.View.performClick(View.java:6615)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
	at android.view.View.performClickInternal(View.java:6587)
	at android.view.View.access$3500(View.java:784)
	at android.view.View$PerformClick.run(View.java:26048)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:205)
	at android.app.ActivityThread.main(ActivityThread.java:6991)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: lge
Device: joan
Model: LG-H930
Id: PKQ1.190414.001
Product: joan_global_com

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 193091504cde8

**Comment by tobiasKaminsky** [comment]
Can you tell us how/when this happens?
