### ISSUE TITLE
Error on Android app

### ISSUE THREAD

**Issue by atierant** [nextcloud/android#8369]
### Steps to reproduce
1. Click on profile picture on android app, and then account management
2. Click on connected account
3. Data is loading and then.... bug appears

### Expected behaviour
- Open account settings

### Actual behaviour
- Bug appears

### Environment data
Android version: 10 (OxygenOS 10.3.10)

Device model: OnePlus 6T

Stock or customized system: Stock (Updates on OTA only)

Nextcloud app version: 3.16.0

Nextcloud server version: 21.0.1

#### Web server error log
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException
	at com.nextcloud.ui.ChooseAccountDialogFragment.getBinding(ChooseAccountDialogFragment.kt:71)
	at com.nextcloud.ui.ChooseAccountDialogFragment.avatarGenerated(ChooseAccountDialogFragment.kt:196)
	at com.owncloud.android.datamodel.ThumbnailsCacheManager$AvatarGenerationTask.onPostExecute(ThumbnailsCacheManager.java:921)
	at com.owncloud.android.datamodel.ThumbnailsCacheManager$AvatarGenerationTask.onPostExecute(ThumbnailsCacheManager.java:868)
	at android.os.AsyncTask.finish(AsyncTask.java:755)
	at android.os.AsyncTask.access$900(AsyncTask.java:192)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus6T
Model: ONEPLUS A6013
Id: QKQ1.190716.003
Product: OnePlus6T

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2104202153
```

**Comment by tobiasKaminsky** [comment]
Fixed via #8356
