### ISSUE TITLE
SQLiteReadOnlyDatabaseException

### ISSUE THREAD

**Issue by FloDM** [nextcloud/android#8389]
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start service com.owncloud.android.files.services.FileUploader@e47b954 with Intent { cmp=com.nextcloud.client/com.owncloud.android.files.services.FileUploader (has extras) }: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032 SQLITE_READONLY_DBMOVED)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4531)
	at android.app.ActivityThread.access$2200(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2131)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8010)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032 SQLITE_READONLY_DBMOVED)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:890)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1845)
	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1791)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:647)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:629)
	at android.content.ContentProvider.update(ContentProvider.java:1870)
	at android.content.ContentProvider$Transport.update(ContentProvider.java:487)
	at android.content.ContentResolver.update(ContentResolver.java:2400)
	at android.content.ContentResolver.update(ContentResolver.java:2362)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUpload(UploadsStorageManager.java:131)
	at com.owncloud.android.files.services.FileUploader.retryUploads(FileUploader.java:554)
	at com.owncloud.android.files.services.FileUploader.onStartCommand(FileUploader.java:339)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4513)
	... 8 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus7TPro
Model: HD1913
Id: RKQ1.201022.002
Product: OnePlus7TPro_EEA

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 2104061419
```

**Comment by stefan-niedermann** [comment]
Please fill out the complete issue template, especially the used versions and clear steps about how to reproduce the issue.
