### ISSUE TITLE
Accessing result data after operation failed

### ISSUE THREAD

**Issue by rubo77** [nextcloud/android#8411]
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Accessing result data after operation failed!
	at com.owncloud.android.lib.common.operations.RemoteOperationResult.getData(RemoteOperationResult.java:486)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$fetchAndSetData$5$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:350)
	at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$kKf4rQWdefIyyvcUxuV6BOjWFU8.run(Unknown Source:8)
	at java.lang.Thread.run(Thread.java:923)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20201107
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: samsung
Device: beyond2
Model: SM-G975F
Id: RP1A.200720.012
Product: beyond2lteeea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: G975FXXU9FUCD
```

**Comment by stefan-niedermann** [comment]
Please fill out the complete issue template, especially the used versions and clear steps about how to reproduce the issue.

**Comment by AndyScherzinger** [comment]
Version 20201107 is super old. Please update and re-open if issue still present.

**Comment by rubo77** [comment]
I updated NC client and the issue didn't reappear
