### ISSUE TITLE
Nextcloud App crashing on faild file download

### ISSUE THREAD

**Issue by 4ctiv** [nextcloud/android#8417]
This is about the nextcloud app being unable to download files from connected SMB storage and crashing after faild download. 

### Steps to reproduce
1. Open Nextcloud app
2. Go into external storage folder (SMB/CIFS)
3. Download item in external storage folder

### Expected behaviour
 - No crash
- prompt download successful
- ask how to open downloaded file

### Actual behaviour

1. Prompt: Error downloading file x
2 Wait 2~3 seconds
3. Shows Nextcloud crash dialogue

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 11

Device model: Umidigi S5 Pro | Samsung Galaxy Note 9

Stock or customized system: S5 custom GSI | Note 9 standard

Nextcloud app version: 3.16.0 (latest Playstore release)

Nextcloud server version: 21.1.0

Reverse proxy: ? 

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here

(Sth about a java nullpointer exception)
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Is this related to SMB?

Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by 4ctiv** [comment]
That's the full error message displayed in the app

************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Fragment PreviewImageFragment{294ed3d} (2df4d1c4-8dff-4141-ae99-cc0bf9929aad) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:900)
	at androidx.fragment.app.Fragment.getResources(Fragment.java:964)
	at com.owncloud.android.ui.preview.PreviewImageFragment.lambda$setErrorPreviewMessage$2$PreviewImageFragment(PreviewImageFragment.java:742)
	at com.owncloud.android.ui.preview.-$$Lambda$PreviewImageFragment$lYlNRKiEmwgldJH0g5sQ-_uYXY4.onClick(Unknown Source:2)
	at com.google.android.material.snackbar.Snackbar$1.onClick(Snackbar.java:351)
	at android.view.View.performClick(View.java:7448)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
	at android.view.View.performClickInternal(View.java:7425)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28305)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Phh
Device: phhgsi_arm64_ab
Model: Phh-Treble with GApps
Id: RQ2A.210405.005
Product: treble_arm64_bgS

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 210415
