### ISSUE TITLE
Error reinstall app

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/android#8419]
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032 SQLITE_READONLY_DBMOVED[1032])
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:1164)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:2324)
	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:2270)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:651)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:629)
	at android.content.ContentProvider.update(ContentProvider.java:1848)
	at android.content.ContentProvider$Transport.update(ContentProvider.java:457)
	at android.content.ContentResolver.update(ContentResolver.java:2359)
	at android.content.ContentResolver.update(ContentResolver.java:2321)
	at com.owncloud.android.datamodel.ArbitraryDataProvider.storeOrUpdateKeyValue(ArbitraryDataProvider.java:104)
	at com.owncloud.android.ui.activity.DrawerActivity.lambda$fetchExternalLinks$5$DrawerActivity(DrawerActivity.java:1091)
	at com.owncloud.android.ui.activity.-$$Lambda$DrawerActivity$RaU_Wf1ywDAbBMs71OnisiylNgA.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:923)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: beyond2
Model: SM-G975F
Id: RP1A.200720.012
Product: beyond2lteeea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: G975FXXU9FUCD

**Comment by tobiasKaminsky** [comment]
No idea, but this is purely Android. 
Is this happening often/reliable?

**Comment by tigernero79** [comment]
yes, it happens that if you reset the server with a fresh installation and then reinstall end to end as an application.  even if the android client is uninstalled and reinstalled, it will always carry old mnemonic code.  I solved it by logging in with another user created by me, but the mnemonic codes should also be deleted by deleting the account

**Comment by tigernero79** [comment]
happens when you reinstall and log in with new server with same credentials.  just delete cache.
