### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by 1x23** [nextcloud/android#8434]
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:735)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1653)
	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1599)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:647)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:629)
	at android.content.ContentProvider$Transport.update(ContentProvider.java:359)
	at android.content.ContentResolver.update(ContentResolver.java:1672)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUpload(UploadsStorageManager.java:131)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUploadInternal(UploadsStorageManager.java:173)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUploadStatus(UploadsStorageManager.java:208)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateDatabaseUploadResult(UploadsStorageManager.java:579)
	at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:654)
	at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1414)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Blackview
Device: BV9500
Model: BV9500
Id: O11019
Product: BV9500

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: 1553063486

**Comment by tobiasKaminsky** [comment]
This seems to be an Android problem.
Maybe there was no space left?
