### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by hewei2723** [nextcloud/android#8441]
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Fragment PreviewImageFragment{15d13f1} (46041bca-4e7d-4f3e-b06c-fd687e397a2c)} not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:805)
	at androidx.fragment.app.Fragment.getResources(Fragment.java:869)
	at com.owncloud.android.ui.preview.PreviewImageFragment.lambda$setErrorPreviewMessage$2$PreviewImageFragment(PreviewImageFragment.java:744)
	at com.owncloud.android.ui.preview.-$$Lambda$PreviewImageFragment$lYlNRKiEmwgldJH0g5sQ-_uYXY4.onClick(Unknown Source:2)
	at com.google.android.material.snackbar.Snackbar$1.onClick(Snackbar.java:307)
	at android.view.View.performClick(View.java:6659)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992)
	at android.view.View.performClickInternal(View.java:6631)
	at android.view.View.access$3100(View.java:790)
	at android.view.View$PerformClick.run(View.java:26187)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWMRD-M
Model: MRD-AL00
Id: HUAWEIMRD-AL00
Product: MRD-AL00

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 9.1.0.272C00

**Comment by tobiasKaminsky** [comment]
Please fill out template and re-open.
