### ISSUE TITLE
NextCloud android app crash

### ISSUE THREAD

**Issue by fkelly907** [nextcloud/android#8454]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
************ CAUSE OF ERROR ************

java.lang.IllegalArgumentException: reportSizeConfigurations: ActivityRecord not found for: Token{888e825 null}
	at android.os.Parcel.createException(Parcel.java:1970)
	at android.os.Parcel.readException(Parcel.java:1934)
	at android.os.Parcel.readException(Parcel.java:1884)
	at android.app.IActivityManager$Stub$Proxy.reportSizeConfigurations(IActivityManager.java:8626)
	at android.app.ActivityThread.reportSizeConfigurations(ActivityThread.java:3327)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3286)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1970)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7156)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.reportSizeConfigurations(ActivityManagerService.java:10696)
	at android.app.IActivityManager$Stub.onTransact$reportSizeConfigurations$(IActivityManager.java:12675)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2346)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4185)
	at android.os.Binder.execTransact(Binder.java:739)


************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: cruiserlteatt
Model: SM-G892A
Id: PPR1.180610.011
Product: cruiserlteuc

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G892AUCU5CUD3

**Comment by tobiasKaminsky** [comment]
When does this happen? Please fill out template.
