### ISSUE TITLE
Android app crashes while uploading photos and creating odt file

### ISSUE THREAD

**Issue by TobjasR** [nextcloud/android#8459]
the Android app just crashed while it was uploading photos (restarted instant uploads after connection failure) and trying to create a new odt file.

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.NullPointerException: Attempt to read from field 'androidx.viewpager.widget.ViewPager com.owncloud.android.databinding.FileDetailsFragmentBinding.pager' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2944)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3079)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1836)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6702)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
Caused by: java.lang.NullPointerException: Attempt to read from field 'androidx.viewpager.widget.ViewPager com.owncloud.android.databinding.FileDetailsFragmentBinding.pager' on a null object reference
	at com.owncloud.android.ui.fragment.FileDetailFragment.getFileDetailSharingFragment(FileDetailFragment.java:158)
	at com.owncloud.android.ui.activity.FileActivity.getShareFileFragment(FileActivity.java:855)
	at com.owncloud.android.ui.activity.FileActivity.getFile(FileActivity.java:297)
	at com.owncloud.android.ui.activity.FileDisplayActivity.updateActionBarTitleAndHomeButton(FileDisplayActivity.java:1625)
	at com.owncloud.android.ui.activity.ToolbarActivity.setupToolbar(ToolbarActivity.java:103)
	at com.owncloud.android.ui.activity.ToolbarActivity.setupHomeSearchToolbarWithSortAndListButtons(ToolbarActivity.java:127)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onCreate(FileDisplayActivity.java:264)
	at android.app.Activity.performCreate(Activity.java:7136)
	at android.app.Activity.performCreate(Activity.java:7127)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2924)
	... 11 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: alps
Device: k63v2_64_bsp
Model: Volla Phone
Id: PPR1.180610.011
Product: full_k63v2_64_bsp

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: eng.helios.20201019.112318

**Comment by tobiasKaminsky** [comment]
How did you create the odt file?
