### ISSUE TITLE
Crash when rotate 

### ISSUE THREAD

**Issue by aleister09** [nextcloud/android#850]
### Actual behaviour
If the user rotate the SmartPhone when the info is loading the app crashes 
It happens in Activities, Favorites, Photos, Shared 
 
### Steps to reproduce
1. Open the App
2. Open Photos
3. Rotate SmartPhone when the info is loading

### Environment data
Android version: 7.1.2

Device model: Nexus 5X

Stock or customized system:

Nextcloud app version: Master

Nextcloud server version: 11

### Logs
```
04-19 12:10:03.438 30036-32726/com.nextcloud.client E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #11
                                                                      Process: com.nextcloud.client, PID: 30036
                                                                      java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                          at android.os.AsyncTask$3.done(AsyncTask.java:325)
                                                                          at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                          at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                          at java.lang.Thread.run(Thread.java:761)
                                                                       Caused by: java.lang.IllegalArgumentException: Trying to execute a remote operation with a NULL Context
                                                                          at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:106)
                                                                          at com.owncloud.android.ui.fragment.OCFileListFragment$12.doInBackground(OCFileListFragment.java:1319)
                                                                          at android.os.AsyncTask$2.call(AsyncTask.java:305)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                          at java.lang.Thread.run(Thread.java:761) 
```
![ezgif com-video-to-gif 3](https://cloud.githubusercontent.com/assets/25756086/25194599/913a2790-2500-11e7-82d0-80491a94bb13.gif)

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by mario** [comment]
@tobiasKaminsky please look into this :)
