### ISSUE TITLE
Nextcloud app (3.16.0) crashed

### ISSUE THREAD

**Issue by tryallthethings** [nextcloud/android#8510]
### Steps to reproduce
1. App was only running in background. I saw a notification that a new media folder was detected. Touched the message and received the error below

### Actual behaviour
App crashed with error.
This is the first time this crash happened.

```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.SyncedFoldersActivity}: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3792)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:899)
	at java.util.TimSort.mergeAt(TimSort.java:516)
	at java.util.TimSort.mergeForceCollapse(TimSort.java:457)
	at java.util.TimSort.sort(TimSort.java:254)
	at java.util.Arrays.sort(Arrays.java:1424)
	at com.owncloud.android.utils.SyncedFolderUtils.getFileList(SyncedFolderUtils.java:233)
	at com.owncloud.android.utils.SyncedFolderUtils.isQualifyingMediaFolder(SyncedFolderUtils.java:112)
	at com.owncloud.android.ui.activity.SyncedFoldersActivity.mergeFolderData(SyncedFoldersActivity.java:353)
	at com.owncloud.android.ui.activity.SyncedFoldersActivity.load(SyncedFoldersActivity.java:268)
	at com.owncloud.android.ui.activity.SyncedFoldersActivity.setupContent(SyncedFoldersActivity.java:227)
	at com.owncloud.android.ui.activity.SyncedFoldersActivity.onCreate(SyncedFoldersActivity.java:161)
	at android.app.Activity.performCreate(Activity.java:8198)
	at android.app.Activity.performCreate(Activity.java:8182)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765)
	... 11 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: r8q
Model: SM-G781B
Id: RP1A.200720.012
Product: r8qxeea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: G781BXXU3CUD6
```

### Environment data
Android version: 11
Device model: Samsung Galaxy S20 FE 5G
Stock or customized system: Stock 
Nextcloud app version: 3.16.0
Nextcloud server version: 21.0.2
Reverse proxy: None

**Comment by tobiasKaminsky** [comment]
Does this happen reliable?
There might sometimes be a race condition when underlying data is changed during sorting…

**Comment by tryallthethings** [comment]
No, I've only seen this once so far. And a new version was installed later that day on my phone.

**Comment by tryallthethings** [comment]
Haven't seen the issue again so far.

**Comment by AndyScherzinger** [comment]
Let's close it for now then and re-open if it comes back in a reproducible way.
