### ISSUE TITLE
next cloud crash

### ISSUE THREAD

**Issue by stilian82** [nextcloud/android#8520]
************ CAUSE OF ERROR ************

java.lang.IllegalArgumentException: Receiver not registered: androidx.work.impl.constraints.trackers.NetworkStateTracker$NetworkStateBroadcastReceiver@41d53fb0
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:667)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1562)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:489)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:489)
	at androidx.work.impl.constraints.trackers.NetworkStateTracker.stopTracking(NetworkStateTracker.java:124)
	at androidx.work.impl.constraints.trackers.ConstraintTracker.removeListener(ConstraintTracker.java:86)
	at androidx.work.impl.constraints.controllers.ConstraintController.replace(ConstraintController.java:97)
	at androidx.work.impl.constraints.WorkConstraintsTracker.replace(WorkConstraintsTracker.java:106)
	at androidx.work.impl.background.greedy.GreedyScheduler.removeConstraintTrackingFor(GreedyScheduler.java:224)
	at androidx.work.impl.background.greedy.GreedyScheduler.onExecuted(GreedyScheduler.java:210)
	at androidx.work.impl.Processor.onExecuted(Processor.java:302)
	at androidx.work.impl.Processor$FutureListener.run(Processor.java:375)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5292)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
	at dalvik.system.NativeStart.main(Native Method)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30130190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Lenovo
Device: A3500H
Model: Lenovo A3500-H
Id: KOT49H
Product: A3500-H

************ FIRMWARE ************
SDK: 19
Release: 4.4.2
Incremental: Lenovo_A3500-H_A442_01_S034

**Comment by AndyScherzinger** [comment]
@stilian82 you are runnign an old version of the app (3.13.1) please update to latest version 3.16.1 and re-open if issue still keeps happening.
