### ISSUE TITLE
App crashes when opening .md file

### ISSUE THREAD

**Issue by SHA-NDY** [nextcloud/android#8526]
### Steps to reproduce
1. Open NC app
2. Tap on .md file

### Expected behaviour
- File should open

### Actual behaviour
- NC crashes

### Environment data
Android version: 10

Device model: Volla Phone / GS290

Stock or customized system: AOSP

Nextcloud app version: 3.16.1

Nextcloud server version: 21.0.1

WebView: Bromite Webview

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.TextEditorWebView}: android.view.InflateException: Binary XML file line #62 in com.nextcloud.client:layout/richdocuments_webview: Binary XML file line #62 in com.nextcloud.client:layout/richdocuments_webview: Error inflating class android.webkit.WebView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3298)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3437)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2041)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7386)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
Caused by: android.view.InflateException: Binary XML file line #62 in com.nextcloud.client:layout/richdocuments_webview: Binary XML file line #62 in com.nextcloud.client:layout/richdocuments_webview: Error inflating class android.webkit.WebView
Caused by: android.view.InflateException: Binary XML file line #62 in com.nextcloud.client:layout/richdocuments_webview: Error inflating class android.webkit.WebView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:854)
	at android.view.LayoutInflater.createView(LayoutInflater.java:776)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:930)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:950)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1140)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1101)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1143)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1101)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
	at com.owncloud.android.ui.activity.ExternalSiteWebView.onCreate(ExternalSiteWebView.java:91)
	at com.owncloud.android.ui.activity.EditorWebView.onCreate(EditorWebView.java:120)
	at com.owncloud.android.ui.activity.TextEditorWebView.onCreate(TextEditorWebView.kt:46)
	at android.app.Activity.performCreate(Activity.java:7802)
	at android.app.Activity.performCreate(Activity.java:7791)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3273)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3437)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2041)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7386)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
Caused by: android.util.AndroidRuntimeException: java.lang.reflect.InvocationTargetException
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:271)
	at android.webkit.WebView.getFactory(WebView.java:2551)
	at android.webkit.WebView.ensureProviderCreated(WebView.java:2545)
	at android.webkit.WebView.setOverScrollMode(WebView.java:2613)
	at android.view.View.<init>(View.java:5062)
	at android.view.View.<init>(View.java:5203)
	at android.view.ViewGroup.<init>(ViewGroup.java:676)
	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
	at android.webkit.WebView.<init>(WebView.java:410)
	at android.webkit.WebView.<init>(WebView.java:353)
	at android.webkit.WebView.<init>(WebView.java:336)
	at android.webkit.WebView.<init>(WebView.java:323)
	... 36 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:266)
	... 47 more
Caused by: yp: errorCode=2
	at Qj.g(chromium-SystemWebView.apk-stable-1620434410:15)
	at Qj.i(chromium-SystemWebView.apk-stable-1620434410:5)
	at org.chromium.android_webview.AwBrowserProcess.f(chromium-SystemWebView.apk-stable-1620434410:9)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.f(chromium-SystemWebView.apk-stable-1620434410:84)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(chromium-SystemWebView.apk-stable-1620434410:12)
	at com.android.webview.chromium.WebViewChromiumFactoryProviderForQ.<init>(chromium-SystemWebView.apk-stable-1620434410:1)
	at com.android.webview.chromium.WebViewChromiumFactoryProviderForQ.create(chromium-SystemWebView.apk-stable-1620434410:1)
	... 49 more
Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/product/app/webview/webview.apk"],nativeLibraryDirectories=[/system/product/app/webview/lib/arm64, /system/product/app/webview/webview.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64, /system/lib64, /system/product/lib64]]] couldn't find "libwebviewchromium.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
	at java.lang.System.loadLibrary(System.java:1667)
	at Qj.g(chromium-SystemWebView.apk-stable-1620434410:8)
	... 55 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: alps
Device: k63v2_64_bsp
Model: Volla Phone
Id: QP1A.190711.020
Product: full_k63v2_64_bsp

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: mp1V9135

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by SHA-NDY** [comment]
Was related to webview bug. Update to Bromite WebView 91.0.4472.97 solved the issue
