### ISSUE TITLE
Crash on first launch on Galaxy Tab S7

### ISSUE THREAD

**Issue by savvasdalkitsis** [nextcloud/android#8530]
### Steps to reproduce
1. First launch after installation 

### Expected behaviour
- App shouldn't crash 

### Actual behaviour
- App crashes 

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to resume activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.SecurityException: uid 10278 cannot get user data for accounts of type: nextcloud
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4864)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4901)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.SecurityException: uid 10278 cannot get user data for accounts of type: nextcloud
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)
	at android.os.Parcel.createException(Parcel.java:2369)
	at android.os.Parcel.readException(Parcel.java:2352)
	at android.os.Parcel.readException(Parcel.java:2294)
	at android.accounts.IAccountManager$Stub$Proxy.getUserData(IAccountManager.java:1326)
	at android.accounts.AccountManager.getUserData(AccountManager.java:516)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.<init>(OCFileListAdapter.java:171)
	at com.owncloud.android.ui.fragment.OCFileListFragment.onActivityCreated(OCFileListFragment.java:352)
	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2985)
	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:580)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:451)
	at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:436)
	at com.owncloud.android.ui.activity.BaseActivity.onResume(BaseActivity.java:91)
	at com.owncloud.android.ui.activity.DrawerActivity.onResume(DrawerActivity.java:911)
	at com.owncloud.android.ui.activity.FileActivity.onResume(FileActivity.java:240)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onResume(FileDisplayActivity.java:1148)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
	at android.app.Activity.performResume(Activity.java:8344)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4854)
	... 11 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.accounts.AccountManagerService.getUserData(AccountManagerService.java:1685)
	at android.accounts.IAccountManager$Stub.onTransact(IAccountManager.java:453)
	at com.android.server.accounts.AccountManagerService.onTransact(AccountManagerService.java:1121)
	at android.os.Binder.execTransactInternal(Binder.java:1190)
	at android.os.Binder.execTransact(Binder.java:1159)


************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: gts7lwifi
Model: SM-T870
Id: RP1A.200720.012
Product: gts7lwifieea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: T870XXU2BUE2

**Comment by savvasdalkitsis** [comment]
Now that subsequent launched worked ok. It was only the initial launch that crashed once

**Comment by tobiasKaminsky** [comment]
Do you use some kind of restricted user profile on Samsung?

**Comment by savvasdalkitsis** [comment]
Nope. It's a pretty standard setup. I haven't had any more issues since this crash. It was a one off. And since the app worked fine the next time i launched it, I guess it's not a critical bug but i'm more than happy to provide any info you think you might need to investigate. Logs, device info etc
