### ISSUE TITLE
Crash creating a markdown file (crash on tmeplate chooser dialog)

### ISSUE THREAD

**Issue by meismann** [nextcloud/android#8539]
### Steps to reproduce
1. Switch on Bluetooth on android menu bar
2. Open app, click "plus" to create new text (Markup) document, wait for prompt to enter file name
3. Switch mobile keyboard on
4. App should crash now

### Expected behaviour
Well, the app should not crash; the file name should now be editable with the Bluetooth device.

### Actual behaviour
The app crashes and shows a Java Nullpointerexception, including stacktrace (see below)

### Can you reproduce this problem on https://try.nextcloud.com?
No, and I am not going to. This should very much be a local device issue.

### Environment data
Android version: 7.1.1

Device model: Sony Z5 Compact, E5823

Stock or customized system: not customised

Nextcloud app version: 3.16.0

Stacktrace:
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setEnabled(boolean)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2720)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2781)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4615)
	at android.app.ActivityThread.-wrap19(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1514)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:6274)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setEnabled(boolean)' on a null object reference
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment.checkEnablingCreateButton(ChooseTemplateDialogFragment.java:277)
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment.access$000(ChooseTemplateDialogFragment.java:81)
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment$1.afterTextChanged(ChooseTemplateDialogFragment.java:182)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:8211)
	at android.widget.TextView.setText(TextView.java:4493)
	at android.widget.TextView.setText(TextView.java:4341)
	at android.widget.EditText.setText(EditText.java:89)
	at android.widget.TextView.setText(TextView.java:4316)
	at android.widget.TextView.onRestoreInstanceState(TextView.java:4207)
	at android.view.View.dispatchRestoreInstanceState(View.java:15803)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3237)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3237)
	at com.google.android.material.textfield.TextInputLayout.dispatchRestoreInstanceState(TextInputLayout.java:2841)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3237)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3237)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3237)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3237)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3237)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3237)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3237)
	at android.view.View.restoreHierarchyState(View.java:15781)
	at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2106)
	at android.app.Dialog.onRestoreInstanceState(Dialog.java:469)
	at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:496)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3124)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3068)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:501)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at com.owncloud.android.ui.activity.DrawerActivity.onStart(DrawerActivity.java:1031)
	at com.owncloud.android.ui.activity.FileActivity.onStart(FileActivity.java:230)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2378)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
	at android.app.Activity.performStart(Activity.java:6737)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2683)
	... 10 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Sony
Device: E5823
Model: E5823
Id: 32.4.A.1.54
Product: E5823

************ FIRMWARE ************
SDK: 25
Release: 7.1.1
Incremental: 3761073091

**Comment by AndyScherzinger** [comment]
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setEnabled(boolean)' on a null object reference
at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment.checkEnablingCreateButton(ChooseTemplateDialogFragment.java:277)
at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment.access$000(ChooseTemplateDialogFragment.java:81)
```

--> not related to the keyboard/bluethooth but an issue nevertheless

**Comment by tobiasKaminsky** [comment]
I cannot reproduce it.
Is this happening also without the bluetooth keyboard?
