### ISSUE TITLE
SQL Error after starting the app - SQLiteBlobTooBigException

### ISSUE THREAD

**Issue by l0bster** [nextcloud/android#8555]
### Steps to reproduce
1. install nextcloud app for android
2. connect it to a nextcloud instance
3. shows files, loads a few seconds and then crashes with the exception below

### Expected behaviour
- should not crash

### Actual behaviour
- crashes with an sql error

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 11

Device model: oneplus 7

Stock or customized system: stock

Nextcloud app version: 3.16.1

Nextcloud server version: 21.0.2

Reverse proxy: NGinx

### Logs
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=2961, totalRows=1035
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1001)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:161)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:131)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:248)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:280)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:190)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProvider.delete(ContentProvider.java:1820)
	at android.content.ContentProviderOperation.applyInternal(ContentProviderOperation.java:389)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:352)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:672)
	at android.content.ContentProvider.applyBatch(ContentProvider.java:2476)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:421)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:586)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:574)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:2234)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:438)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:528)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:410)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:238)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:923)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus7
Model: GM1900
Id: RKQ1.201022.002
Product: OnePlus7

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 2105071635

**Comment by l0bster** [comment]
deleted my phone backup from gdrive, reinstalled nextcloud app and it seems to work now.

followed this hint 
https://github.com/nextcloud/android/issues/6109
