### ISSUE TITLE
Android last version client error

### ISSUE THREAD

**Issue by joabbl** [nextcloud/android#8557]
Client crashes and the only way yo restart It is restarting the phone. It happens randomly. The log is:

*********** CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Insets android.view.WindowInsets.getInsets(int)' on a null object reference
	at android.view.View.fitSystemWindowsInt(View.java:11238)
	at android.view.View.fitSystemWindows(View.java:11227)
	at android.view.View.onApplyWindowInsets(View.java:11299)
	at android.view.View.dispatchApplyWindowInsets(View.java:11360)
	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7320)
	at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:7334)
	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7325)
	at androidx.core.view.ViewCompat.dispatchApplyWindowInsets(ViewCompat.java:2527)
	at com.google.android.material.internal.NavigationMenuPresenter.dispatchApplyWindowInsets(NavigationMenuPresenter.java:358)
	at com.google.android.material.navigation.NavigationView.onInsetsChanged(NavigationView.java:357)
	at com.google.android.material.internal.ScrimInsetsFrameLayout$1.onApplyWindowInsets(ScrimInsetsFrameLayout.java:86)
	at androidx.core.view.ViewCompat$1.onApplyWindowInsets(ViewCompat.java:2474)
	at android.view.View.dispatchApplyWindowInsets(View.java:11358)
	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7320)
	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1091)
	at android.view.View.measure(View.java:25548)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
	at android.view.View.measure(View.java:25548)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25548)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25548)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25548)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:781)
	at android.view.View.measure(View.java:25548)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3527)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2353)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2616)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2064)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8400)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:250)
	at android.app.ActivityThread.main(ActivityThread.java:7755)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: motorola
Device: racer
Model: motorola edge
Id: RPDS31.Q4U-39-26-4-2
Product: racer_retaile

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 226d93
---------/

**Comment by tobiasKaminsky** [comment]
Do you know when this happens?
In the stacktrace there is no app specific code mention, so it is really hard to debug… :/

**Comment by joabbl** [comment]
When I start the client and let It run in background, some times when I put It in foreground again to browse the Server directories the error Window appears. It can be after hours or even days working Ok. When this happens the only solution is reinstall and Connect the client again. An interesting thing is that the Server synch keeps on working so I take a picture and is uploaded Ok, but the client is Broken. This behaviour happens only since the last client update.
Hope this helps
Good luck
J. Manuel

Enviado desde ProtonMail móvil

-------- Mensaje original --------
