### ISSUE TITLE
Repeated crash

### ISSUE THREAD

**Issue by MaMaKow** [nextcloud/android#8569]
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:735)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1653)
	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1599)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:647)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:629)
	at android.content.ContentProvider$Transport.update(ContentProvider.java:359)
	at android.content.ContentResolver.update(ContentResolver.java:1675)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUpload(UploadsStorageManager.java:131)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUploadInternal(UploadsStorageManager.java:173)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUploadStatus(UploadsStorageManager.java:208)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateDatabaseUploadStart(UploadsStorageManager.java:597)
	at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:612)
	at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1421)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: bq
Device: bardock-pro
Model: Aquaris X Pro
Id: OPM1.171019.026
Product: bardock-pro

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: 2395

**Comment by MaMaKow** [comment]
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:735)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1653)
	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1599)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:647)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:629)
	at android.content.ContentProvider$Transport.update(ContentProvider.java:359)
	at android.content.ContentResolver.update(ContentResolver.java:1675)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUpload(UploadsStorageManager.java:131)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUploadInternal(UploadsStorageManager.java:173)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUploadStatus(UploadsStorageManager.java:208)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateDatabaseUploadStart(UploadsStorageManager.java:597)
	at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:612)
	at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1421)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: bq
Device: bardock-pro
Model: Aquaris X Pro
Id: OPM1.171019.026
Product: bardock-pro

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: 2395

**Comment by tobiasKaminsky** [comment]
> android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)

This is something Android specific and nothing we can influence.
Sadly, I have no idea how to help you. Maybe a new install of the app helps.
