### ISSUE TITLE
android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed

### ISSUE THREAD

**Issue by NoName1311** [nextcloud/android#8571]
When I switch on the screen of my mobile phone, a window opens with the following message: 

************ CAUSE OF ERROR ************

android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
	at android.database.CursorWindow.<init>(CursorWindow.java:108)
	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
	at android.database.sqlite.SQLiteCursor.clearOrCreateWindow(SQLiteCursor.java:309)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:147)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:141)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:258)
	at androidx.work.impl.model.WorkSpecDao_Impl.getState(WorkSpecDao_Impl.java:727)
	at androidx.work.impl.WorkerWrapper.onWorkFinished(WorkerWrapper.java:334)
	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:320)
	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Model: SM-A320FL

************ FIRMWARE ************
SDK: 26
Release: 8.0.0

Stock or customized system: Stock system

Nextcloud server version: Two accounts on different instances, both version 21.0.2

Reverse proxy: no

The app and all functions work as expected.

**Comment by tobiasKaminsky** [comment]
Do you have any idea what could lead to this? 
This stack trace does not show the real cause… :/

**Comment by NoName1311** [comment]
I have no idea. Most of the time the app is running in background. I use it for automatic picture upload.

**Comment by NoName1311** [comment]
I have observed that I get a different error sometimes, but the behavior is the same. 
Is it possible to activate a debug log or something else to find the root cause?

************ CAUSE OF ERROR ************

java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:733)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:970)
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1038)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1180)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Model: SM-A320FL

************ FIRMWARE ************
SDK: 26
Release: 8.0.0

**Comment by AndyScherzinger** [comment]
@NoName1311 how many pictures do you have that would have to be auto uploaded (my guess is the amount is so large that it breaks the query on Android)

**Comment by NoName1311** [comment]
Please excuse my late reply. Maybe 5 pictures / videos per week.

I have moved all the pictures / videos (about 800 MB) from the upload folder on my server into another folder. That's about a week ago and since then I have not seen the issues anymore.
My wife's upload folder is > 2GB and she has not experienced anything similar.
But she have a different phone....

Thank you for your help.

**Comment by AndyScherzinger** [comment]
Thanks for the update @NoName1311, so let's close it for now. The is isn't about the filesize-total but the number of files I think
