### ISSUE TITLE
Nextcloud Android app crash shared folder

### ISSUE THREAD

**Issue by tenorable** [nextcloud/android#8572]
### Steps to reproduce
1. Open Nextcloud app
2. Select shared
3. 

### Expected behaviour
- Tell us what should happen
See shared files
### Actual behaviour
- Tell us what happens
Crashed
### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalArgumentException: Empty values
	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1772)
	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1752)
	at com.owncloud.android.providers.FileContentProvider.updateFilesTableAccordingToShareInsertion(FileContentProvider.java:420)
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:311)
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:255)
	at android.content.ContentProvider.insert(ContentProvider.java:1673)
	at android.content.ContentProviderOperation.applyInternal(ContentProviderOperation.java:375)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:352)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:672)
	at android.content.ContentProvider.applyBatch(ContentProvider.java:2413)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:403)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:576)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:564)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:2196)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveShares(FileDataStorageManager.java:1409)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.parseShares(OCFileListAdapter.java:1038)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.setData(OCFileListAdapter.java:976)
	at com.owncloud.android.ui.fragment.OCFileListFragment$2.doInBackground(OCFileListFragment.java:1567)
	at com.owncloud.android.ui.fragment.OCFileListFragment$2.doInBackground(OCFileListFragment.java:1549)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: bramble
Model: Pixel 4a (5G)
Id: RQ2A.210505.003
Product: bramble

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 7255357

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Strange, on a new account with one incoming and one outgoing share and it does not crash.
Now the tricky part is to find out why it does crash on my other test account with 190 shares…

**Comment by tobiasKaminsky** [comment]
It seems that it is about a federated group.

**Comment by tobiasKaminsky** [comment]
Fixed via https://github.com/nextcloud/android-library/pull/649
