### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by AMajor-C** [nextcloud/android#8580]
### Steps to reproduce
1. Revoke app session on the security page
2. Get error and infinite loop of device credentials requests
3. Or reauth acc in the Talk app using option use account from nextcloud app

### Expected behaviour
- Tell us what should happen

### Actual behaviour
Getting error and infinite loop of device credentials requests. But at the same time Talk and Phonetrack apps work normally.

************ CAUSE OF ERROR ************

 @java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Credentials.kt)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Credentials.kt)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:277)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:760)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: santoni
Model: Redmi 4X
Id: N2G47H
Product: santoni

************ FIRMWARE ************
SDK: 25
Release: 7.1.2
Incremental: V11.0.2.0.NAMMIXM

**Comment by AndyScherzinger** [comment]
Duplicate of #8370
