### ISSUE TITLE
Crashes related to unregistered Fido USB receiver

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/android#8585]
### Steps to reproduce

1. Enter the application settings.
2. Change the theme.

```
********** CAUSE OF ERROR **********

java.lang.RuntimeException: Unable to pause activity {com.nextcloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@a17fb6c

	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5127)

	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5076)

	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5016)

	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:242)

	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)

	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)

	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)

	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:57)

	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5889)

	at android.app.ActivityThread.access$4500(ActivityThread.java:296)

	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2397)

	at android.os.Handler.dispatchMessage(Handler.java:107)

	at android.os.Looper.loop(Looper.java:213)

	at android.app.ActivityThread.main(ActivityThread.java:8178)

	at java.lang.reflect.Method.invoke(Native Method)

	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)

	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

Caused by: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@a17fb6c

	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1507)

	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1647)

	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:664)

	at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher.onInactive(UsbConnectionDispatcher.java:131)

	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.ensureStateInactive(SecurityKeyManager.java:316)

	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.refreshActiveState(SecurityKeyManager.java:290)

	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.onActivityPaused(SecurityKeyManager.java:333)

	at android.app.Application.dispatchActivityPaused(Application.java:473)

	at android.app.Activity.dispatchActivityPaused(Activity.java:1351)

	at android.app.Activity.onPause(Activity.java:2316)

	at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:388)

	at com.owncloud.android.ui.activity.BaseActivity.onPause(BaseActivity.java:84)

	at com.owncloud.android.ui.activity.FileActivity.onPause(FileActivity.java:253)

	at com.owncloud.android.ui.activity.FileDisplayActivity.onPause(FileDisplayActivity.java:1254)

	at android.app.Activity.performPause(Activity.java:8272)

	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1522)

	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5117)

	... 16 more

********** APP INFORMATION **********

ID: com.nextcloud.android.beta

Version: 20210612

Build flavor: versionDev

********** FIRMWARE **********

SDK: 29

Release: 10

Incremental: 10.0.0.238C432
```

**Comment by tobiasKaminsky** [comment]
> Caused by: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@a17fb6c

@dschuermann as you implemented the fido u2f support, do you have an idea why this happens?

**Comment by Valdnet** [comment]
The error still exists in dev 20210709.

**Comment by AndyScherzinger** [comment]
While this ssems to be related to lifycacle management and the fido implementation, so not directly related to a theme change

**Comment by Cwpute** [comment]
same bug here. here is my own crash report:
`************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to pause activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@66955a9
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4208)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3064)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4995)
	at android.app.ActivityThread.-wrap18(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1783)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:6861)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@66955a9
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1222)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1469)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:652)
	at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher.onInactive(UsbConnectionDispatcher.java:131)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.ensureStateInactive(SecurityKeyManager.java:316)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.refreshActiveState(SecurityKeyManager.java:290)
	at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.onActivityPaused(SecurityKeyManager.java:333)
	at android.app.Application.dispatchActivityPaused(Application.java:225)
	at android.app.Activity.onPause(Activity.java:1702)
	at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:388)
	at com.owncloud.android.ui.activity.BaseActivity.onPause(BaseActivity.java:84)
	at com.owncloud.android.ui.activity.FileActivity.onPause(FileActivity.java:253)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onPause(FileDisplayActivity.java:1254)
	at android.app.Activity.performPause(Activity.java:7264)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1408)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4197)
	... 10 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170051
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWDRA-M
Model: DRA-L21
Id: HUAWEIDRA-L21
Product: DRA-L21

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: 1.0.0.152(C33)
`

**Comment by Valdnet** [comment]
The error still exists in version 3.17.0.

**Comment by AlvaroBrey** [comment]
Thanks @Valdnet. Can you consistently reproduce the issue or does it just happen sometimes?

**Comment by AlvaroBrey** [comment]
> The issue is recreated every time.

Do you mind testing this APK: https://github.com/nextcloud/android/pull/8933#issuecomment-911740986 and telling me if the issue persists?

**Comment by Valdnet** [comment]
I have installed the QA version and it is now working fine on my device. Good job 👍.

**Comment by AlvaroBrey** [comment]
Patched in https://github.com/nextcloud/android/pull/8933 and https://github.com/nextcloud/android/pull/8941
