### ISSUE TITLE
unable to import contacts from a backup file

### ISSUE THREAD

**Issue by szamanr** [nextcloud/android#8587]
### Steps to reproduce
1. select contacts backup file
2. selects all contacts to restore
3. choose import into "local contacts" 

### Expected behaviour
contacts should be imported 

### Actual behaviour
crash

### Environment data
Android version: 8.0

Device model: huawei ane-lx1

Stock or customized system: stock 

Nextcloud app version: 3.16.1

Nextcloud server version:

Reverse proxy:

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized
	at androidx.work.Data.toByteArrayInternal(Data.java:417)
	at androidx.work.Data$Builder.build(Data.java:846)
	at com.nextcloud.client.jobs.BackgroundJobManagerImpl.startImmediateContactsImport(BackgroundJobManagerImpl.kt:254)
	at com.owncloud.android.ui.fragment.contactsbackup.ContactListFragment.importContacts(ContactListFragment.java:338)
	at com.owncloud.android.ui.fragment.contactsbackup.ContactListFragment.access$400(ContactListFragment.java:108)
	at com.owncloud.android.ui.fragment.contactsbackup.ContactListFragment$3.onClick(ContactListFragment.java:409)
	at androidx.appcompat.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1068)
	at android.widget.AdapterView.performItemClick(AdapterView.java:321)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1217)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3203)
	at android.widget.AbsListView$3.run(AbsListView.java:4151)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWANE
Model: ANE-LX1
Id: HUAWEIANE-LX1
Product: ANE-LX1

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: 174(C432)
 
```

**Comment by szamanr** [comment]
tried to import 1225 contacts.

**Comment by ezaquarii** [comment]
It looks like we try to build an array with all contact IDs. This array apparently grows beyond platform limit.

We can build it and store it in a temporary file in cache directory. Another workaround would be to try compressing the array using gzip.

**Comment by zukunft** [comment]
Looks like I had a similar crash: 

### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized
    at androidx.work.Data$Companion.toByteArrayInternalV1(Data_.kt:703)
    at androidx.work.Data$Builder.build(Data_.kt:525)
    at com.nextcloud.client.jobs.BackgroundJobManagerImpl.startFilesUploadJob(BackgroundJobManagerImpl.kt:619)
    at com.nextcloud.client.jobs.upload.FileUploadHelper.cancelAndRestartUploadJob(FileUploadHelper.kt:266)
    at com.owncloud.android.ui.activity.UploadListActivity.toggleGlobalPause(UploadListActivity.java:281)
    at com.owncloud.android.ui.activity.UploadListActivity.onOptionsItemSelected(UploadListActivity.java:300)
    at android.app.Activity.onMenuItemSelected(Activity.java:4443)
    at androidx.activity.ComponentActivity.onMenuItemSelected(ComponentActivity.kt:477)
    at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:264)
    at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:256)
    at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
    at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:66)
    at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:224)
    at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:769)
    at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:833)
    at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:157)
    at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:984)
    at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:974)
    at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:620)
    at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:155)
    at android.view.View.performClick(View.java:7542)
    at android.view.View.performClickInternal(View.java:7519)
    at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
    at android.view.View$PerformClick.run(View.java:29476)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7924)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30320390`
* Build flavor: `generic`

### Device information
* Brand: `OnePlus`
* Device: `OnePlus9Pro`
* Model: `LE2123`
* Id: `TQ3A.230901.001`
* Product: `OnePlus9Pro`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `eng.root.20250710.023933`

Maybe reason has been, that there have been too many files to upload at once.

Additional I would suggest, that the number of messages shown to the user in the app would be limited e.g. to 100 and if there are more messages of a similar type, show to the user a link with "... and xxx more". When clicking on the link, 100 more messages are shown and with another click 200 more, than 400 and so on. Maybe this way the number of bytes can be kept below 10240. Should I create a separate issue for improving the UI?
