### ISSUE TITLE
Error when clicking "sync contact"

### ISSUE THREAD

**Issue by andiim3** [nextcloud/android#8592]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalArgumentException: Trying to execute a remote operation with a NULL Context
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:128)
	at com.owncloud.android.ui.fragment.contactsbackup.ContactsBackupFragment$2.doInBackground(ContactsBackupFragment.java:235)
	at com.owncloud.android.ui.fragment.contactsbackup.ContactsBackupFragment$2.doInBackground(ContactsBackupFragment.java:223)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Redmi
Device: sweet
Model: M2101K6G
Id: RKQ1.200826.002
Product: sweet_global

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: V12.5.1.0.RKFMIXM

**Comment by tobiasKaminsky** [comment]
Have you meanwhile navigated away?

**Comment by andiim3** [comment]
The app exited right away. Cannot navigate away.
