### ISSUE TITLE
Crash on app opening

### ISSUE THREAD

**Issue by phillipp** [nextcloud/android#8600]
### Steps to reproduce
1. open app 

### Expected behaviour
- App should show files list

### Actual behaviour
- App crashes with the following message:

```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.IllegalStateException: Couldn't read row 0, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2821)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2899)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1625)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6558)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)
Caused by: java.lang.IllegalStateException: Couldn't read row 0, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetString(Native Method)
	at android.database.CursorWindow.getString(CursorWindow.java:438)
	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
	at android.database.CursorWrapper.getString(CursorWrapper.java:137)
	at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:982)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:125)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByEncryptedRemotePath(FileDataStorageManager.java:112)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:108)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2403)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1335)
	at android.app.Activity.performStart(Activity.java:7276)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2784)
	... 9 more
```

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
```
************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: blackberry
Device: bbf100
Model: BBF100-6
Id: OPM1.171019.026
Product: bbf100dsglobal

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: ACQ160
```

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Does the same account work on another device?
It seems that somehow the stored data cannot be read, maybe you also want to try to clean data of the app?

**Comment by phillipp** [comment]
Hi, the web and desktop clients (linux and windows) work fine. Calendar sync to phones (CalDAV) are fine, too.

I tried reinstalling the app and installing older versions (the problem first occurred in May, I had hopes that it was a bug and solved in future versions), but no luck.

**Comment by phillipp** [comment]
@tobiasKaminsky When I force quit the app, empty the app cache and delete all app data I can start the app and see an initial "no files" screen and only then it crashes. While it does the initial sync, I can open settings and browse activity list, but it still crashes after 5-15 seconds.

For me and other users of the same installation, desktop clients & web continue to work fine, only the android app crashes (on my device, don't know if anyone else uses it).

**Comment by edmundlaugasson** [comment]
Having similar issue, tried clear cache and data - didn't help.
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Unknown Source:8)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Unknown Source:2)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:277)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus3
Model: ONEPLUS A3003
Id: PKQ1.181203.001
Product: OnePlus3

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 1911042107
```

**Comment by edmundlaugasson** [comment]
There is a problem, that permission asking dialog is not on top of other windows. When opened app, during a fraction of second I noticed the dialog window with choices Allow and Not Allow. But impossible to tap the allow as the dialog is not accessible. Tried also latest development version via F-droid - same problem.

**Comment by phillipp** [comment]
The stack traces do not seem very similiar, one is a uninitialized cursor, the other a null error. They are almost certainly not related.

**Comment by AndyScherzinger** [comment]
I agree with @phillipp. @edmundlaugasson your error log points to #8370 actually.
