### ISSUE TITLE
Deleting app data leads to error

### ISSUE THREAD

**Issue by Discostu36** [nextcloud/android#8601]
### Steps to reproduce
1. Open Android app settings of Nextcloud 
2. Click on manage data
3. In Nextcloud App, click on delete data 

### Log

************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database - SQLITE_READONLY_DBMOVED (Sqlite code 1032 SQLITE_READONLY_DBMOVED), (OS error - 2:No such file or directory)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:875)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:776)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1785)
	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1726)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:647)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:629)
	at android.content.ContentProvider$Transport.update(ContentProvider.java:448)
	at android.content.ContentResolver.update(ContentResolver.java:2031)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUpload(UploadsStorageManager.java:131)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUploadInternal(UploadsStorageManager.java:173)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUploadStatus(UploadsStorageManager.java:208)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateDatabaseUploadResult(UploadsStorageManager.java:579)
	at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:661)
	at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1421)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.os.HandlerThread.run(HandlerThread.java:67)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWELE
Model: ELE-L09
Id: HUAWEIELE-L09
Product: ELE-L09EEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.1.0.150C431

**Comment by tobiasKaminsky** [comment]
This seems to be an Android internal problem as the database could not be read.
I tried to reproduce it on different phones and there were no problems :/

Can you retry it?

**Comment by Discostu36** [comment]
I can reproduce on my phone. This time nothing seemed to happen when I clicked on Delete Data and the error occurred when opening the app the next time.

**Comment by gerdesj** [comment]
Is that not working as designed?  On my Samsung it explicitly states that deleting data does exactly that:  it deletes all of the apps settings and files.  The error message given above states that the SQLite database has vanished (no such file or directory), which it will do if you delete it.

There is also the option of deleting cache but the OP explicitly states using the "delete data" function.

**Comment by Discostu36** [comment]
Maybe in the backend of the app everything is working as designed, but the end user should not be confronted with a SQL error
