### ISSUE TITLE
crash when tried to change account after server reset

### ISSUE THREAD

**Issue by xoddark** [nextcloud/android#8645]
### Steps to reproduce
1. Add account(s) in application from a nextcloud server (self hosted on yunohost for exemple)
2. uninstall and reinstall nextcloud server, and create same account again.  
3. open the android application again, tried to refresh files or tried to change current account

### Expected behaviour
no crash and allow remove, refresh, reconnect account

### Actual behaviour
crash when tried to remove/refresh/reconnect account from a reseted nextcloud server

java.lang.NullPointerException
	at com.nextcloud.ui.ChooseAccountDialogFragment.getBinding(ChooseAccountDialogFragment.kt:71)
	at com.nextcloud.ui.ChooseAccountDialogFragment.avatarGenerated(ChooseAccountDialogFragment.kt:196)
	at com.owncloud.android.datamodel.ThumbnailsCacheManager$AvatarGenerationTask.onPostExecute(ThumbnailsCacheManager.java:921)
	at com.owncloud.android.datamodel.ThumbnailsCacheManager$AvatarGenerationTask.onPostExecute(ThumbnailsCacheManager.java:868)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.access$600(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7266)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

### Can you reproduce this problem on https://try.nextcloud.com?
I think I can't because I'm not able to manage test account name and pass

### Environment data
Android version:
7.1.1

Stock or customized system:
Stock

Nextcloud app version:
ID: com.nextcloud.client
Version: 30160090
Build flavor: generic

Nextcloud server version:
21.0.2 on yunohost

**Comment by AndyScherzinger** [comment]
Thanks for the report

Fixed via #8356

--> Next release
