### ISSUE TITLE
Contacts backup "choose date" button crash

### ISSUE THREAD

**Issue by mario** [nextcloud/android#868]
04-21 12:56:51.735 10413-10413/com.nextcloud.client E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.nextcloud.client, PID: 10413
                                                                      java.lang.IllegalStateException: Could not execute method for android:onClick
                                                                          at android.view.View$DeclaredOnClickListener.onClick(View.java:5046)
                                                                          at android.view.View.performClick(View.java:6207)
                                                                          at android.widget.TextView.performClick(TextView.java:11094)
                                                                          at android.view.View$PerformClick.run(View.java:23639)
                                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6688)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                                                                       Caused by: java.lang.reflect.InvocationTargetException
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at android.view.View$DeclaredOnClickListener.onClick(View.java:5041)
                                                                          at android.view.View.performClick(View.java:6207) 
                                                                          at android.widget.TextView.performClick(TextView.java:11094) 
                                                                          at android.view.View$PerformClick.run(View.java:23639) 
                                                                          at android.os.Handler.handleCallback(Handler.java:751) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                          at android.os.Looper.loop(Looper.java:154) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6688) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358) 
                                                                       Caused by: java.util.NoSuchElementException
                                                                          at java.util.Vector.lastElement(Vector.java:503)
                                                                          at com.owncloud.android.ui.activity.ContactsPreferenceActivity.openDate(ContactsPreferenceActivity.java:296)
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at android.view.View$DeclaredOnClickListener.onClick(View.java:5041) 
                                                                          at android.view.View.performClick(View.java:6207) 
                                                                          at android.widget.TextView.performClick(TextView.java:11094) 
                                                                          at android.view.View$PerformClick.run(View.java:23639) 
                                                                          at android.os.Handler.handleCallback(Handler.java:751) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                          at android.os.Looper.loop(Looper.java:154) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6688) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by mario** [comment]
This happens when I open the screen (and don't have backups).
