### ISSUE TITLE
App keeps crashing

### ISSUE THREAD

**Issue by sodomak** [nextcloud/android#8685]
### Steps to reproduce
1.  Everytime I open the app. 

### Environment data
Android version: 9

Stock or customized system: LineageOS

### Logs

************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=2956, totalRows=75
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:895)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:157)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:128)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:237)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:269)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:190)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:299)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:672)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:320)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:474)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:1627)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:438)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:528)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:410)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:238)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: nokia
Device: Starlord
Model: Nokia 6.2
Id: PQ3A.190801.002
Product: Starlord

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 2

**Comment by CramMK** [comment]
I'm experiencing a similiar SQLite error, whilst trying to open a directory containing other ("big" )directories (~25GB)

```
************ CAUSE OF ERROR ************
 
android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=4471, totalRows=2885
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:942)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:161)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:131)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:249)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:281)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:190)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProviderOperation.applyInternal(ContentProviderOperation.java:342)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:314)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:672)
	at android.content.ContentProvider.applyBatch(ContentProvider.java:2179)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:398)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:532)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:520)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:1915)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:438)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:528)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:410)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:238)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:919)
 
************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay
 
************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus6
Model: ONEPLUS A6003
Id: QKQ1.190716.003
Product: OnePlus6
 
************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2107132155
 
```

**Comment by sodomak** [comment]
Just FYI: Issue persists after update to v. 30170090

**Comment by bonswouar** [comment]
Same here on Android 11.
I can't even access settings (or retry failed auto uploads...) as it crashes on startup...
