### ISSUE TITLE
Android client fails to start

### ISSUE THREAD

**Issue by DimStar77** [nextcloud/android#8706]
### Steps to reproduce
1. Open the client
2. See a crash / trace
3. 

### Expected behaviour
- access to the files

### Actual behaviour
- backtrace

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to resume activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=10, totalRows=11
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4504)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4536)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2104)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7861)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=10, totalRows=11
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1001)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:163)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:131)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:248)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:286)
	at android.database.CursorWrapper.moveToNext(CursorWrapper.java:206)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:913)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:185)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:914)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1262)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1215)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1204)
	at com.owncloud.android.ui.fragment.OCFileListFragment.onActivityCreated(OCFileListFragment.java:399)
	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2985)
	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:580)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:451)
	at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:436)
	at com.owncloud.android.ui.activity.BaseActivity.onResume(BaseActivity.java:91)
	at com.owncloud.android.ui.activity.DrawerActivity.onResume(DrawerActivity.java:911)
	at com.owncloud.android.ui.activity.FileActivity.onResume(FileActivity.java:240)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onResume(FileDisplayActivity.java:1148)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1457)
	at android.app.Activity.performResume(Activity.java:8248)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4494)
	... 11 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Redmi
Device: curtana
Model: Redmi Note 9S
Id: RKQ1.200826.002
Product: curtana_eea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: V12.0.2.0.RJWEUXM

**Comment by strugee** [comment]
Seems likely to be a duplicate of #8685?

**Comment by DimStar77** [comment]
Indeed, that looks very similar. Let's close this one and i will subscribe to the other bug. Thanks for pointing out
