### ISSUE TITLE
Crash when attempting upload

### ISSUE THREAD

**Issue by djlactose** [nextcloud/android#8707]
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2, result=1, data=Intent { (has extras) }} to activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5013)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5054)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference
	at com.owncloud.android.ui.activity.FileDisplayActivity.requestUploadOfFilesFromFileSystem(FileDisplayActivity.java:964)
	at com.owncloud.android.ui.activity.FileDisplayActivity.requestUploadOfFilesFromFileSystem(FileDisplayActivity.java:959)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onActivityResult(FileDisplayActivity.java:889)
	at android.app.Activity.dispatchActivityResult(Activity.java:8304)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5006)
	... 11 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170052
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: blueline
Model: Pixel 3
Id: RQ3A.210705.001
Product: blueline

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 7380771
```

**Comment by AlvaroBrey** [comment]
@djlactose Is this still happening in the latest version?

**Comment by djlactose** [comment]
No, this was resolved after the next beta update.

**Comment by AlvaroBrey** [comment]
Thanks @djlactose
