### ISSUE TITLE
Crashed while checking conflict file

### ISSUE THREAD

**Issue by khandakershahi** [nextcloud/android#8708]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
	at com.owncloud.android.ui.activity.ConflictsResolveActivity.onStart(ConflictsResolveActivity.java:187)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8222)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3818)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: a50
Model: SM-A505F
Id: RP1A.200720.012
Product: a50dd

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: A505FDDU8CUE4

**Comment by tobiasKaminsky** [comment]
Do you know which file this was?
Is it present in app or is it a new file?

**Comment by khandakershahi** [comment]
I didn't able to check which file. I have changed the next cloud provider and added the account to my android. When the android try to sync the camera folder that is already upload  before it start to mark them as conflict and suppose to be allow me select an option but it crashed.
