### ISSUE TITLE
Error while downloading immaged  

### ISSUE THREAD

**Issue by RobinDev03** [nextcloud/android#8709]
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Fragment PreviewImageFragment{b3c82a0} (ba7b0128-ef4c-4706-8d60-e03eeab721c3) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:900)
	at androidx.fragment.app.Fragment.getResources(Fragment.java:964)
	at com.owncloud.android.ui.preview.PreviewImageFragment.lambda$setErrorPreviewMessage$2$PreviewImageFragment(PreviewImageFragment.java:742)
	at com.owncloud.android.ui.preview.-$$Lambda$PreviewImageFragment$lYlNRKiEmwgldJH0g5sQ-_uYXY4.onClick(Unknown Source:2)
	at com.google.android.material.snackbar.Snackbar$1.onClick(Snackbar.java:351)
	at android.view.View.performClick(View.java:8160)
	at android.widget.TextView.performClick(TextView.java:16222)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
	at android.view.View.performClickInternal(View.java:8137)
	at android.view.View.access$3700(View.java:888)
	at android.view.View$PerformClick.run(View.java:30236)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: beyond1
Model: SM-G973F
Id: RP1A.200720.012
Product: beyond1lteeea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: G973FXXSBFUE6

**Comment by strugee** [comment]
Looks like a duplicate of #7808?
