### ISSUE TITLE
Login crash after temp. 2FA activation

### ISSUE THREAD

**Issue by tpurschke** [nextcloud/android#8716]
### Steps to reproduce
1. Activate 2FA
2. deactivate 2FA
3. Open nextcloud app

### Expected behaviour
Login should work

### Actual behaviour
App crashes

### Can you reproduce this problem on https://try.nextcloud.com?

No

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version: 22

Reverse proxy: apache

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter password
	at okhttp3.Credentials.basic(Unknown Source:8)
	at okhttp3.Credentials.basic$default(Credentials.kt:28)
	at okhttp3.Credentials.basic(Unknown Source:2)
	at com.owncloud.android.lib.common.OwnCloudClientFactory.createNextcloudClient(OwnCloudClientFactory.java:217)
	at com.owncloud.android.operations.RefreshFolderOperation.updatePredefinedStatus(RefreshFolderOperation.java:338)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:311)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:277)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:230)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
	at java.lang.Thread.run(Thread.java:923)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: redfin
Model: Pixel 5
Id: RQ3A.210705.001
Product: redfin

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 7380771

```

**Comment by tpurschke** [comment]
fixed by adding missing  'overwriteprotocol' => 'https', in nextcloud config
