### ISSUE TITLE
NPE checking if user changes in FIleDisplayActivity

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#8725]
### Steps to reproduce
1. Fresh installation
2. Login via webflow
3. Crash

### Expected behaviour
- Don't crash

### Actual behaviour
- Crashes right away

### Can you reproduce this problem on https://try.nextcloud.com?
- Yes

### Environment data
Android version: 11

Device model: OP9Pro

Stock or customized system:Stock

Nextcloud app version:3.10 Alpha / latest-master

Nextcloud server version: 20

Reverse proxy:no

### Logs
```
2021-07-18 00:24:07.474 32624-32624/com.nextcloud.client E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nextcloud.client, PID: 32624
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object com.nextcloud.java.util.Optional.orElse(java.lang.Object)' on a null object reference
        at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2414)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1525)
        at android.app.Activity.performStart(Activity.java:8030)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3642)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2251)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8035)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

Changed line which crashes has been introduced via https://github.com/nextcloud/android/pull/8658/files#diff-63ac3b87ffc30fe6a5a9033783579006befbe5de5921a080ed073fb0ca593138R2417 so also looping in @ezaquarii for help ❤️

**Comment by AndyScherzinger** [comment]
Also happens on our unit tests: https://www.kaminsky.me/nc-dev/android-integrationTests/1769-IT-master-21-26/com.nextcloud.client.FileDisplayActivityIT.html#switchToGridView:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object com.nextcloud.java.util.Optional.orElse(java.lang.Object)' on a null object reference
at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2414)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
at androidx.test.runner.MonitoringInstrumentation.callActivityOnStart(MonitoringInstrumentation.java:742)
at android.app.Activity.performStart(Activity.java:7029)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by ezaquarii** [comment]
@AndyScherzinger looking into it

**Comment by ezaquarii** [comment]
@AndyScherzinger yeah, it looks like it's a bug introduced by recent refactoring. I'll fix it.
