### ISSUE TITLE
Webpack crash

### ISSUE THREAD

**Issue by markcjf** [nextcloud/android#8733]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Prism4j internal error. Number of entry nodes is greater that the text length.
Nodes: [TextImpl{literal=''}]
Text: 
	at io.noties.prism4j.Prism4j.matchGrammar(Prism4j.java:224)
	at io.noties.prism4j.Prism4j.tokenize(Prism4j.java:185)
	at io.noties.prism4j.Prism4j.matchGrammar(Prism4j.java:324)
	at io.noties.prism4j.Prism4j.tokenize(Prism4j.java:185)
	at io.noties.markwon.syntax.Prism4jSyntaxHighlight.highlight(Prism4jSyntaxHighlight.java:94)
	at io.noties.markwon.syntax.Prism4jSyntaxHighlight.highlightWithLanguageInfo(Prism4jSyntaxHighlight.java:82)
	at io.noties.markwon.syntax.Prism4jSyntaxHighlight.highlight(Prism4jSyntaxHighlight.java:55)
	at io.noties.markwon.core.CorePlugin.visitCodeBlock(CorePlugin.java:367)
	at io.noties.markwon.core.CorePlugin$6.visit(CorePlugin.java:293)
	at io.noties.markwon.core.CorePlugin$6.visit(CorePlugin.java:290)
	at io.noties.markwon.MarkwonVisitorImpl.visit(MarkwonVisitorImpl.java:183)
	at io.noties.markwon.MarkwonVisitorImpl.visit(MarkwonVisitorImpl.java:91)
	at org.commonmark.node.FencedCodeBlock.accept(FencedCodeBlock.java:14)
	at io.noties.markwon.MarkwonVisitorImpl.visitChildren(MarkwonVisitorImpl.java:214)
	at io.noties.markwon.MarkwonVisitorImpl.visit(MarkwonVisitorImpl.java:185)
	at io.noties.markwon.MarkwonVisitorImpl.visit(MarkwonVisitorImpl.java:81)
	at org.commonmark.node.Document.accept(Document.java:7)
	at io.noties.markwon.MarkwonImpl.render(MarkwonImpl.java:77)
	at io.noties.markwon.MarkwonImpl.toMarkdown(MarkwonImpl.java:97)
	at com.owncloud.android.ui.preview.PreviewTextFragment.getRenderedMarkdownText(PreviewTextFragment.java:193)
	at com.owncloud.android.ui.preview.PreviewTextFragment.setText(PreviewTextFragment.java:223)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.onBindViewHolder(OCFileListAdapter.java:351)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1818)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1584)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2003)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1225)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4212)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3647)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2575)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9910)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
	at android.view.Choreographer.doFrame(Choreographer.java:744)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8506)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: r8s
Model: SM-G780F
Id: RP1A.200720.012
Product: r8seea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: G780FXXU4CUF1

**Comment by AndyScherzinger** [comment]
@markcjf any chance you could share the markdown file which caused this crash?

**Comment by markcjf** [comment]
Not sure what the file is or where it would be - would it be in my folders, need a bit of direction, sorry.

**Comment by markcjf** [comment]
Unsure where this file would be - can you give me some direction as I do not see a file name or location for it, sorry.

Mark

**Comment by AndyScherzinger** [comment]
To be more precise with my question, sorry about that: how many files are in the folder on your device which you configured for auto upload?

**Comment by markcjf** [comment]
Understood - I have syncing with my laptop 2k+ folders/files 

I can see my notes on my laptop but get an error when trying on my android.



Hope this helps - here if you need more info

Regards
Mark

**Comment by AndyScherzinger** [comment]
> I can see my notes on my laptop but get an error when trying on my android.

```
....PreviewTextFragment.getRenderedMarkdownText(PreviewTextFragment.java:193)
```

Points to you opening a text-file

```
 io.noties.prism4j.Prism4j.matchGrammar...
```

Point to you opening a markdown file. So the file you tried to open here would be the file I was asking for earlier if it could be shared while prism4j is part of the markdown render lib we are using so it might be an issue with the lib itself :(
@noties have you seen this error before or can you name any infos you'd need to maybe also have a look?

**Comment by markcjf** [comment]
Am looking at my Nextcloud system now - it was down while I got some electric equipment replaced and on checking I now get a message on my android that it is in maintenance mode.

On checking as admin the config has it set to false and of course I can access the web interface no problem. On checking the logs some icon files I created for an external site are missing and I wonder if there are other files missing too.

If I could ask - as it is a virtual machine with backup images would I be messing things up if I restored a previous version.

As for the files you mention I suspect that it is one of two things - my Notes were changed from .txt to .md (I don’t think this is the issue as I was previously able to access them. Second, I started recently backing up some web dev files and among these are yarn lock files which Nextcloud ransomware add-on saw as a threat, but besides this I thought all was good except for getting sync errors regarding same.

Mark

**Comment by markcjf** [comment]
Hello Andy

Just an update on the situation - after my last email to you I rethought the whole situation and it was the part where the files were missing part that got me thinking and without further ado - I now have access to all the system etc.

It is my thinking that the android failed to connect or at least was the first to fail, and as I wasn’t aware of the of issues with other devices at the time I thought it a good idea to send the information in my first email.

I thank you for your response but again if you think it is something else I can continue to ‘assist’.

Regards,
Mark

**Comment by AndyScherzinger** [comment]
Thanks for the heads up @markcjf. Since it is rather hard to debug atm I'd close it for now and if it comes back with any new/other situation then let's re-open it then. Anyways thank you very much for taking the time to report and discuss, this is highly appreciated.
