### ISSUE TITLE
Crash after attempting to edit conflicted markdown file

### ISSUE THREAD

**Issue by eniad** [nextcloud/android#8746]
### Steps to reproduce
1. Have Nextcloud Android and Windows clients on separate devices
2. Edit markdown file in Android client
3. Edit file on Windows
4. Open file on Android
5. Crash

### Expected behaviour

The Android client should either:  
A. Allow resolution of conflicts without crashing  
B. Prevent conflicts by updating local copy to saved (on server)

### Actual behaviour

Conflicts cause several problems:

1. Crash before conflict resolution (as in this bug report)
2. Conflict resolution interaction that does not actually resolve when the saved file is selected (can submit separate bug report or add as a comment on this bug report)
3. Crash after conflict resolution in #2 is tried.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data

_will fill out this info after switch from phone to desktop to make copy/paste easier_

Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setVisibility(int)' on a null object reference
	at com.owncloud.android.ui.activity.EditorWebView.hideLoading(EditorWebView.java:75)
	at com.owncloud.android.ui.activity.-$$Lambda$7YfaHXb6ttANEryhFmOc5vhllUM.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:215)
	at android.app.ActivityThread.main(ActivityThread.java:6939)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: motorola
Device: ali
Model: moto g(6)
Id: ####redacted####
Product: ali

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 3afd9

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by eniad** [comment]
The behavior is not consistent (see `Actual behaviour` above). Screen shots of failed conflict resolution interaction (behavior 2):

![Screenshot_20210719-083646](https://user-images.githubusercontent.com/3921901/126512704-08ce317f-3400-4090-9263-7165b7cdfc53.png)

User clicks `saved`. Then the thinking circle appears:

![Screenshot_20210719-083733](https://user-images.githubusercontent.com/3921901/126512861-a9e9aff7-1c06-41d5-87a3-bc99c85665f3.png)

After a breif time, the thinking circle stops and the user is left on the interaction page. The conflict is not resolved.

![Screenshot_20210719-083745](https://user-images.githubusercontent.com/3921901/126513028-c2869fba-ebea-4fb0-b21d-b13043769c8d.png)

**Comment by tobiasKaminsky** [comment]
This is within text app, redirecting.
