### ISSUE TITLE
Nextcloud app keeps crashing

### ISSUE THREAD

**Issue by Excx999** [nextcloud/android#8771]
### Steps to reproduce
1. Install nextcloud app from fdroid repo 3.16.1 or 3.17.0 RC1
2. Login to account
3. The app crashes

### Expected behaviour
Login to account and load data... 

### Actual behaviour
App crashes

### Environment data
Android version: 11

Device model: Pixel 3a

Stock or customized system: GrapheneOS

Nextcloud app version: 3.16.1 or 3.17.0 RC1

Nextcloud server version: 21.0.3

### Logs

************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=1
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1001)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:153)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:140)
	at android.content.ContentResolver.query(ContentResolver.java:1202)
	at android.content.ContentResolver.query(ContentResolver.java:1115)
	at android.content.ContentResolver.query(ContentResolver.java:1071)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileCursorForValue(FileDataStorageManager.java:950)
	at com.owncloud.android.datamodel.FileDataStorageManager.fileExists(FileDataStorageManager.java:933)
	at com.owncloud.android.datamodel.FileDataStorageManager.fileExists(FileDataStorageManager.java:179)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFile(FileDataStorageManager.java:249)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:251)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:363)
	at java.lang.Thread.run(Thread.java:923)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170051
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: google
Device: sargo
Model: Pixel 3a

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 2021.07.19.18

**Comment by Excx999** [comment]
Seems fixed with Update of GrapheneOS to RQ3A.210705.001.2021.07.26.20.
