### ISSUE TITLE
Notification Bar won't disappear until "activities" tab is opened.

### ISSUE THREAD

**Issue by RainbowRivey** [nextcloud/android#8785]
### Steps to reproduce
1. Press "add a file" button
2. Press "upload file" without selecting any file
3. TubCloud uploading files... Stays in `notifications`

Crash log which appears always when i open Activities tab (maybe it also crashes when i do so?):

************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NumberFormatException: For input string: "2147721481"
	at java.lang.Integer.parseInt(Integer.java:618)
	at java.lang.Integer.parseInt(Integer.java:650)
	at com.owncloud.android.lib.resources.activities.GetActivitiesRemoteOperation.run(GetActivitiesRemoteOperation.java:139)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:138)
	at com.owncloud.android.ui.activities.data.activities.ActivitiesServiceApiImpl$GetActivityListTask.doInBackground(ActivitiesServiceApiImpl.java:105)
	at com.owncloud.android.ui.activities.data.activities.ActivitiesServiceApiImpl$GetActivityListTask.doInBackground(ActivitiesServiceApiImpl.java:66)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

************ APP INFORMATION ************
ID: de.tuberlin.android
Version: 30090290 (build #1928)
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Nokia
Device: NB1
Model: TA-1004
Id: PPR1.180610.011
Product: TA-1004_00WW

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 00WW_5_15K

**Comment by AndyScherzinger** [comment]
@RainbowRivey this doesn't happen on recent versions of the Nextcloud app. You are using the client from TUB which has been released in December 2019. To prevent this from happening either tub gets updated to a newer version or you might need to find a way to use the Nextcloud client itself (can't say of that is possible)
