### ISSUE TITLE
Reinstall causes exception on first start

### ISSUE THREAD

**Issue by SimJoSt** [nextcloud/android#8825]
### Steps to reproduce
1. Have Nextcloud installed and configured
2. Uninstall it
3. Reinstall it
4. Open it

### Expected behaviour
- Setup screen is shown

### Actual behaviour
- Error is shown

The error is not shown on the second launch and also goes away by using the app switcher to switch away and back. Sometimes the error is shown only shortly and then the normal setup screen appears.

### Environment data
Android version: 10

Device model: OnePlus 6T

Stock or customized system: OnePlus OxygenOS

Nextcloud app version: 3.16.1

Nextcloud server version: 21.0.3

Reverse proxy: Caddy & Apache

#### Nextcloud Android crash log
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to resume activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.SecurityException: uid 10821 cannot get user data for accounts of type: nextcloud
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4322)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4354)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.SecurityException: uid 10821 cannot get user data for accounts of type: nextcloud
	at android.os.Parcel.createException(Parcel.java:2071)
	at android.os.Parcel.readException(Parcel.java:2039)
	at android.os.Parcel.readException(Parcel.java:1987)
	at android.accounts.IAccountManager$Stub$Proxy.getUserData(IAccountManager.java:1441)
	at android.accounts.AccountManager.getUserData(AccountManager.java:516)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.<init>(OCFileListAdapter.java:171)
	at com.owncloud.android.ui.fragment.OCFileListFragment.onActivityCreated(OCFileListFragment.java:352)
	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2985)
	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:580)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:451)
	at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:436)
	at com.owncloud.android.ui.activity.BaseActivity.onResume(BaseActivity.java:91)
	at com.owncloud.android.ui.activity.DrawerActivity.onResume(DrawerActivity.java:911)
	at com.owncloud.android.ui.activity.FileActivity.onResume(FileActivity.java:240)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onResume(FileDisplayActivity.java:1148)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1560)
	at android.app.Activity.performResume(Activity.java:7952)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4312)
	... 11 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.accounts.AccountManagerService.getUserData(AccountManagerService.java:1544)
	at android.accounts.IAccountManager$Stub.onTransact(IAccountManager.java:492)
	at com.android.server.accounts.AccountManagerService.onTransact(AccountManagerService.java:1072)
	at android.os.Binder.execTransactInternal(Binder.java:1032)
	at android.os.Binder.execTransact(Binder.java:1005)


************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus6T
Model: ONEPLUS A6013
Id: QKQ1.190716.003
Product: OnePlus6T

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2107132231
```

**Comment by AlvaroBrey** [comment]
@SimJoSt can you still reproduce this in the latest version of the app?
