### ISSUE TITLE
ManageAccounts Activity Crash

### ISSUE THREAD

**Issue by aleister09** [nextcloud/android#883]
### Actual behaviour
-The app crash after open ManageAccounts Activity

### Steps to reproduce
1. Open the app 
2. Open ManageAccounts Activity

### Environment data
Android version:7.1.2

Device model: Nexus 5x

Nextcloud app version: Master

Nextcloud server version: 12

#### Web server error log
```
4-24 12:43:18.970 19636-19636/com.nextcloud.client E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.nextcloud.client, PID: 19636
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.ManageAccountsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
                                                                          at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                                       Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
                                                                          at com.owncloud.android.ui.activity.DrawerActivity.updateQuotaLink(DrawerActivity.java:832)
                                                                          at com.owncloud.android.ui.activity.DrawerActivity.onPostCreate(DrawerActivity.java:1034)
                                                                          at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1199)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2648)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727) 
                                                                          at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:154) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6121) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
04-24 12:43:18.972 4945-22557/? W/ActivityManager:   Force finishing activity com.nextcloud.client/com.owncloud.android.ui.activity.ManageAccountsActivity
04-24 12:43:18.975 4945-22557/? W/ActivityManager:   Force finishing activity com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity
04-24 12:43:19.029 4945-2317/? I/OpenGLRenderer: Initialized EGL, version 1.4
04-24 12:43:19.029 4945-2317/? D/OpenGLRenderer: Swap behavior 1
04-24 12:43:19.475 4945-4970/? W/ActivityManager: Activity pause timeout for ActivityRecord{9e68106 u0 com.nextcloud.client/com.owncloud.android.ui.activity.ManageAccountsActivity t330 f}
```

**Comment by tobiasKaminsky** [comment]
Fixed in #906
