### ISSUE TITLE
crash uploading folder 

### ISSUE THREAD

**Issue by schindlershadow** [nextcloud/android#8837]
### Steps to reproduce
1. Select folder to upload
2. Not enough space warning, select move
3. Crash

### Expected behaviour
- folder upload

### Actual behaviour
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2, result=1, data=Intent { (has extras) }} to activity {com.nextcloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4941)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4982)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:239)
	at android.app.ActivityThread.main(ActivityThread.java:7500)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference
	at com.owncloud.android.ui.activity.FileDisplayActivity.requestUploadOfFilesFromFileSystem(FileDisplayActivity.java:953)
	at com.owncloud.android.ui.activity.FileDisplayActivity.requestUploadOfFilesFromFileSystem(FileDisplayActivity.java:948)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onActivityResult(FileDisplayActivity.java:878)
	at android.app.Activity.dispatchActivityResult(Activity.java:8155)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4934)
	... 11 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20210803
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: asus
Device: ASUS_I001_1
Model: ASUS_I001DE
Id: QKQ1.190825.002
Product: WW_I001D

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 17.0240.2107.100-0
```
I'm on dev 20210803

**Comment by TheDaAndy** [comment]
I got the exact same problem on lineageos.

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HTC
Device: htc_ocndugl
Model: HTC U11
Id: QQ3A.200805.001
Product: ocnuhl_00710

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: eng.golv.20201008.154843

**Comment by schindlershadow** [comment]
Looks like its working on the newest stable version of the app
