### ISSUE TITLE
Crash in UploadListActivity: CursorWindowAllocationException: Cursor window allocation of 2048 kb failed.

### ISSUE THREAD

**Issue by kasumiru** [nextcloud/android#8853]
### Steps to reproduce
1. run nextcloud in android, open "status transfer"
2. and next I see ************ CAUSE OF ERROR ************

### Expected behaviour
- Tstart normal synking files

### Actual behaviour
- I see ************ CAUSE OF ERROR ************ and stack trace.

### Can you reproduce this problem on https://try.nextcloud.com?
- no, I cant reproduce it, but it sometimes appears again

### Environment data
Android version: 8.0.0

Device model: 
lg g5 (best today device with quality of cam and its not big <5.2)
Stock or customized system:
stock

Nextcloud app version:
3.16.1
Nextcloud server version:
21.0.3
Reverse proxy:
nginx
#### Web server error log
```
webserver log in attach: xxx.mydomain.com__nginx.json.log
[xxx.mydomain.com__nginx.json.log](https://github.com/nextcloud/android/files/6975183/xxx.mydomain.com__nginx.json.log)
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
 at android.database.CursorWindow.<init>(CursorWindow.java:108)
 at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
 at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
 at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
 at android.content.ContentResolver.query(ContentResolver.java:775)
 at android.content.ContentResolver.query(ContentResolver.java:705)
 at android.content.ContentResolver.query(ContentResolver.java:663)
 at com.owncloud.android.datamodel.UploadsStorageManager.getUploads(UploadsStorageManager.java:352)
 at com.owncloud.android.datamodel.UploadsStorageManager.getFailedButNotDelayedUploadsForCurrentAccount(UploadsStorageManager.java:480)
 at com.owncloud.android.ui.adapter.UploadListAdapter$2.refresh(UploadListAdapter.java:203)
 at com.owncloud.android.ui.adapter.UploadListAdapter.loadUploadItemsFromDb(UploadListAdapter.java:725)
 at com.owncloud.android.ui.activity.UploadListActivity$UploadMessagesReceiver.onReceive(UploadListActivity.java:353)
 at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
 at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
 at android.os.Handler.dispatchMessage(Handler.java:105)
 at android.os.Looper.loop(Looper.java:164)
 at android.app.ActivityThread.main(ActivityThread.java:6710)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: lge
Device: h1
Model: LG-H860
Id: OPR1.170623.032
Product: h1_global_com

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: 19038182082bf
```

**Comment by AndyScherzinger** [comment]
@kasumiru do you know / can guess the number of uploads that might be queued? Looking at the stack trace it seems it is quite a large number.

**Comment by kasumiru** [comment]
@AndyScherzinger how much files in transfer queue? I think not above 100. but some files are huge. example: 350 mb, 250 mb, 400 mb.

**Comment by AndyScherzinger** [comment]
Hmmm,

since:
```
 at com.owncloud.android.datamodel.UploadsStorageManager.getUploads(UploadsStorageManager.java:352)
```
point to loading the queue (upload entries not their respective file)
ending with:
```
android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
```
which means the query result is "too big" since 2MB is Android default limit. Any idea @tobiasKaminsky since this shouldn't be an issue for querying the upload list, no?

**Comment by strugee** [comment]
Reopening since we don't appear to be waiting on the reporter for this bug.

**Comment by kasumiru** [comment]
closed I think. I can't reproduce it, my phone is die..

**Comment by baznikin** [comment]
Please, reopen. It is still issue.
Just installed application, about 1700 files in upload queue.

### Cause of error
```java
Exception in thread "WM.task-3" android.database.CursorWindowAllocationException: Cursor window allocation of 2097152 bytes failed. # Open Cursors=1 (# cursors opened by this proc=1)
    at android.database.CursorWindow.<init>(CursorWindow.java:136)
    at android.database.CursorWindow.<init>(CursorWindow.java:114)
    at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
    at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
    at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:137)
    at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
    at android.database.AbstractCursor.moveToNext(AbstractCursor.java:269)
    at androidx.room.InvalidationTracker$1.checkUpdatedTable(InvalidationTracker.java:417)
    at androidx.room.InvalidationTracker$1.run(InvalidationTracker.java:388)
    at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)
```


### App information
* ID: com.nextcloud.client
* Version: 30220290
* Build flavor: gplay

### Device information
* Brand: OnePlus
* Device: OnePlus3
* Model: ONEPLUS A3000
* Id: PKQ1.181203.001
* Product: OnePlus3

### Firmware
* SDK: 28
* Release: 9
* Incremental: 1911042107

**Comment by kasumiru** [comment]
and open again. related: https://github.com/nextcloud/android/issues/11141
