### ISSUE TITLE
Side menu crash

### ISSUE THREAD

**Issue by neekless** [nextcloud/android#8862]
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Canvas: trying to draw too large(106328180bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
	at android.graphics.drawable.LayerDrawable.draw(LayerDrawable.java:1018)
	at android.widget.ImageView.onDraw(ImageView.java:1436)
	at android.view.View.draw(View.java:22350)
	at android.view.View.updateDisplayListIfDirty(View.java:21226)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22353)
	at android.view.View.updateDisplayListIfDirty(View.java:21226)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5030)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22353)
	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429)
	at android.view.View.updateDisplayListIfDirty(View.java:21226)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22353)
	at com.google.android.material.internal.ScrimInsetsFrameLayout.draw(ScrimInsetsFrameLayout.java:109)
	at android.view.View.updateDisplayListIfDirty(View.java:21226)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22353)
	at android.view.View.updateDisplayListIfDirty(View.java:21226)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22353)
	at com.android.internal.policy.DecorView.draw(DecorView.java:806)
	at android.view.View.updateDisplayListIfDirty(View.java:21226)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4106)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3833)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3104)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7666)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170053
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: google
Device: taimen
Model: Pixel 2 XL
Id: RQ3A.210705.001
Product: taimen

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 1626561981
```

**Comment by AndyScherzinger** [comment]
@neekless we display your server's logo in the sidebar menu, so do you have a logo on the server of the size the errors mentions? --> 106328180bytes

**Comment by AlvaroBrey** [comment]
Confirmed that this happens when the server logo is set to a very large image.

**Comment by TrentSaggus** [comment]
Confirm resizing Logo to 1000px x 1000px and re-uploading to nextcloud server solves issue. Original Image was 6142 x 6142. Have not attempted any other image sizes as anything less that 1000 x 1000 should work.

> Confirmed that this happens when the server logo is set to a very large image.

I hope this helps others with the same issue.

**Comment by samwa** [comment]
I'm having the same issue using the android app on Google Pixel 2 XL and nextcloud hosted on Qloud servers. Not sure if the fix is with the app of with Qloud

**Comment by AlvaroBrey** [comment]
Can any of the affected people test [the APK in this comment](https://github.com/nextcloud/android/pull/9385#issuecomment-980393388) and confirm that it doesn't crash?
