### ISSUE TITLE
Reoccuring app crash when opening app

### ISSUE THREAD

**Issue by dirrgang** [nextcloud/android#8893]
### Steps to reproduce
1. Open app
2. Wait
3. Crash

### Expected behaviour
It should show my files

### Actual behaviour
It shows an older file structure (old files that aren't in my root folder anymore) and after a few seconds crashes.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
- *********** APP INFORMATION ************
ID: com.nextcloud.client
Version: 30160190
Build flavor: gplay
- *********** DEVICE INFORMATION ************
Brand: google
Device: redfin
Model: Pixel 5
Id: RQ3A.210705.001
Product: redfin
- *********** FIRMWARE ************
SDK: 30
Release: 11
Incremental: 7380771

Stock or customized system:

Running in a nextcloud:apache docker instance.

Nextcloud server version:
  - installed: true
  - version: 22.1.0.1
  - versionstring: 22.1.0
Reverse proxy:
traefik 2 reverse proxy

#### Android App Error Log
- *********** CAUSE OF ERROR ************

java.lang.IllegalStateException: Couldn't read row 1159, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
at android.database.CursorWindow.nativeGetLong(Native Method)
at android.database.CursorWindow.getLong(CursorWindow.java:542)
at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:77)
at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:179)
at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
at android.content.ContentProvider.delete(ContentProvider.java:1757)
at android.content.ContentProviderOperation.applyInternal(ContentProviderOperation.java:389)
at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:352)
at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:672)
at android.content.ContentProvider.applyBatch(ContentProvider.java:2413)
at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:403)
at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:576)
at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:564)
at android.content.ContentResolver.applyBatch(ContentResolver.java:2196)
at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:438)
at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:528)
at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:410)
at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:238)
at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:359)
at java.lang.Thread.run(Thread.java:923)

**Comment by AlvaroBrey** [comment]
Duplicate of #6103
