### ISSUE TITLE
Audio player fullscreen throws exception

### ISSUE THREAD

**Issue by cfpwastaken** [nextcloud/android#8903]
### Steps to reproduce
1. Open an audio file (play it)
2. Go to the three dots and click on fullscreen
3. Exception

### Expected behaviour
- Tell us what should happen
Open the audio file in fullscreen mode

### Actual behaviour
- Tell us what happens
It throws an exception

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 11

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.IllegalArgumentException: Non-video file passed as argument
	at com.owncloud.android.ui.preview.PreviewVideoActivity.onStart(PreviewVideoActivity.java:201)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
	at android.app.Activity.performStart(Activity.java:7846)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3357)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2076)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:232)
	at android.app.ActivityThread.main(ActivityThread.java:7441)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: WIKO
Device: W-V730
Model: W-V730-EEA
Id: QP1A.190711.020
Product: W-V730-EEA

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 585

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

I am sorry that i didnt fill out all of the information. I just dont know them without looking right now. And if i filled in stuff in the wrong places then i am sorry for that too

**Comment by ezaquarii** [comment]
It looks like the fullscreen option should be disabled for audio files.

**Comment by cfpwastaken** [comment]
Yeah probably, why would you need to fullscreen audio files anyway?
