### ISSUE TITLE
Overlapping Fragment

### ISSUE THREAD

**Issue by aleister09** [nextcloud/android#891]
### Actual behaviour
When the user rotate the app in favorites section while the info is loading the fragments are overlapping 

### Steps to reproduce
1. Open App
2. Open Favorites
3. Rotate the App many times

### Environment data
Android version:7.1.2

Device model: Nexus 5X

Stock or customized system:

Nextcloud app version:Master

Nextcloud server version:12

### Logs
![device-2017-04-25-170726](https://cloud.githubusercontent.com/assets/25756086/25409957/db8a6264-29d9-11e7-9f59-e6984938ef5c.png)

**Comment by AndyScherzinger** [comment]
sister issue is #905 since this also happens for shared (and probably any other filter/search like screen)

**Comment by tobiasKaminsky** [comment]
Please test with latest https://github.com/nextcloud/android/pull/896

**Comment by aleister09** [comment]
I think the issue was fixed but the app is crashing after rotation
````
05-08 09:57:57.390 22442-22565/com.nextcloud.client E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
                                                                      Process: com.nextcloud.client, PID: 22442
                                                                      java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                          at android.os.AsyncTask$3.done(AsyncTask.java:325)
                                                                          at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                          at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                          at java.lang.Thread.run(Thread.java:761)
                                                                       Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'com.owncloud.android.datamodel.FileDataStorageManager com.owncloud.android.ui.fragment.FileFragment$ContainerActivity.getStorageManager()' on a null object reference
                                                                          at com.owncloud.android.ui.fragment.OCFileListFragment$11.doInBackground(OCFileListFragment.java:1396)
                                                                          at android.os.AsyncTask$2.call(AsyncTask.java:305)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                          at java.lang.Thread.run(Thread.java:761) 
````

**Comment by tobiasKaminsky** [comment]
Thank you, I have added another check.
Please re-test.

**Comment by aleister09** [comment]
Is still happen in the branch searchViewWrongFiles

````
05-11 10:28:26.032 25335-25440/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
                                                   Process: com.nextcloud.client, PID: 25335
                                                   java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                       at android.os.AsyncTask$3.done(AsyncTask.java:325)
                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                       at java.lang.Thread.run(Thread.java:761)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'com.owncloud.android.datamodel.FileDataStorageManager com.owncloud.android.ui.fragment.FileFragment$ContainerActivity.getStorageManager()' on a null object reference
                                                       at com.owncloud.android.ui.fragment.OCFileListFragment$11.doInBackground(OCFileListFragment.java:1396)
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:305)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                       at java.lang.Thread.run(Thread.java:761) 
````

**Comment by tobiasKaminsky** [comment]
Sorry, I have not pushed it, stupid mistake.
https://github.com/nextcloud/android/pull/896/commits/399ff5802fbc93625e4075a6d5526e7e9af37355

Please re-test it

**Comment by aleister09** [comment]
Now is working fine 👍

**Comment by AndyScherzinger** [comment]
Nice :tada:
