### ISSUE TITLE
App crashes when selecting 'Open With'

### ISSUE THREAD

**Issue by AnonGitHubUser1** [nextcloud/android#8926]
### Steps to reproduce
1. App crashes when selecting three dots next to file and selecting 'Open With'.
2. 
### Expected behaviour
- selection of apps should open to choose from.

### Actual behaviour
- app crashes
- 
### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 11 Grapheneos

Device model: Google Pixel 5

Stock or customized system:

Nextcloud app version:

#### Web server error log
************ CAUSE OF ERROR ************

java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=content://org.nextcloud.files/external_files/emulated/0/Android/media/com.nextcloud.client/nextcloud/nxtcld.kigby@aleeas.com@pro.woelkli.com/Joplin/Readme.md typ=text/markdown flg=0x10000003 cmp=com.tresorit.mobile/com.tresorit.android.activity.TextEditorPrivateActivity } from ProcessRecord{7170b38 7700:com.nextcloud.client/u0a202} (pid=7700, uid=10202) not exported from uid 10194
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3696)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
	at android.app.Activity.startActivityForResult(Activity.java:5314)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:574)
	at android.app.Activity.startActivityForResult(Activity.java:5272)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:560)
	at android.app.Activity.startActivity(Activity.java:5658)
	at android.app.Activity.startActivity(Activity.java:5611)
	at com.owncloud.android.ui.helpers.FileOperationsHelper$1.run(FileOperationsHelper.java:343)
	at java.lang.Thread.run(Thread.java:923)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1043)
	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:999)
	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:669)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1096)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1068)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: google
Device: redfin
Model: Pixel 5
Id: RQ3A.210805.001.A1
Product: redfin

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 2021082501

Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
Can't reproduce. Can you give any details about the file you're trying to open? (format, size, etc)
