### ISSUE TITLE
unexpected issue

### ISSUE THREAD

**Issue by KafaliOnur** [nextcloud/android#8943]
### Steps to reproduce
1. ************ CAUSE OF ERROR ************

java.util.concurrent.TimeoutException: org.conscrypt.ConscryptEngine.finalize() timed out after 10 seconds
	at org.conscrypt.NativeCrypto.BIO_free_all(Native Method)
	at org.conscrypt.NativeSsl$BioWrapper.close(NativeSsl.java:698)
	at org.conscrypt.ConscryptEngine.closeAndFreeResources(ConscryptEngine.java:1677)
	at org.conscrypt.ConscryptEngine.finalize(ConscryptEngine.java:1684)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
	at java.lang.Daemons$Daemon.run(Daemons.java:103)
	at java.lang.Thread.run(Thread.java:784)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWCLT
Model: CLT-L09
Id: HUAWEICLT-L09
Product: CLT-L09

************ FIRMWARE ************
SDK: 27
Release: 8.1.0
Incremental: 159(C782)

2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
Hi @KafaliOnur, thanks for your report. Steps to reproduce? What were you doing when this crash happened?
