### ISSUE TITLE
Crash while picking data for upload

### ISSUE THREAD

**Issue by dewi-ny-je** [nextcloud/android#8951]
### Steps to reproduce
1. Press the SD card icon
2. Pick Camera folder
3. Push top left icon (arrow backwards) to cancel
4. Push "cancel" button next to "upload" because 3. didn't work
5. Repeat 3. and 4. until it crashes

### Expected behaviour
- it should go back to file listing

### Actual behaviour
- crash

### Can you reproduce this problem on https://try.nextcloud.com?
It's an app bug not nextcloud bug

### Environment data
Android version:
10

Device model: 
Nokia 8.1

Stock or customized system:
Stock

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

### Logs

```
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Bindings already cleared.
	at com.owncloud.android.ui.dialog.LocalStoragePathPickerDialogFragment_ViewBinding.unbind(LocalStoragePathPickerDialogFragment_ViewBinding.java:29)
	at com.owncloud.android.ui.dialog.LocalStoragePathPickerDialogFragment.onStop(LocalStoragePathPickerDialogFragment.java:121)
	at androidx.fragment.app.Fragment.performStop(Fragment.java:3184)
	at androidx.fragment.app.FragmentStateManager.stop(FragmentStateManager.java:640)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:320)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2180)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7697)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Nokia
Device: PNX_sprout
Model: Nokia 8.1
Id: RKQ1.200906.002
Product: Phoenix_00WW

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 00WW_6_21C

```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by AlvaroBrey** [comment]
I can't seem to reproduce this. For me, the back arrow works, and I am taken back to the root file list. @dewi-ny-je Does this always happen for you, or is it only sometimes?

Additionally:
* What path does "Camera" resolve to in your phone? It's `DCIM`for me
* Do you have many files under that folder? Is it empty?
* Are you sure these are all the steps to reproduce? No file selecting or anything else?

**Comment by dewi-ny-je** [comment]
The  app suggested me to file a bug report with the log file so I did, but I think it's not easy to reproduce, I also tried again and it worked.

Likely it requires some delay from the server, so that the back arrow takes long time and there is time to try the Cancel button.

I'll see better next time it happens.
