### ISSUE TITLE
app crashes if trying to remove all data after removing local directory

### ISSUE THREAD

**Issue by madpipeline** [nextcloud/android#8957]
### Steps to reproduce
1. Use a file manager to delete the local nextcloud folder
2. Go to app settings (in android, not in app)
3. Click on remove cache and then remove all data, and confirm

### Expected behaviour
- all data is wiped

### Actual behaviour
- app crashes

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

android.database.SQLException: ERROR content://org.nextcloud/arbitrary_data
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:364)
	at com.owncloud.android.providers.FileContentProvider.insert(FileContentProvider.java:255)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:325)
	at android.content.ContentResolver.insert(ContentResolver.java:1854)
	at com.owncloud.android.datamodel.ArbitraryDataProvider.storeOrUpdateKeyValue(ArbitraryDataProvider.java:90)
	at com.owncloud.android.utils.PushUtils.pushRegistrationToServer(PushUtils.java:253)
	at com.owncloud.android.services.firebase.NCFirebaseMessagingService.onNewToken(NCFirebaseMessagingService.java:68)
	at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.3:107)
	at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.3:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:919)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus6T
Model: ONEPLUS A6013
Id: QKQ1.190716.003
Product: OnePlus6T

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2107132231

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
> 1. Use a file manager to delete the local nextcloud folder

@madpipeline You mean removing `Android/data/com.nextcloud.client`? You probably  need a rooted device to even be able to do that, and it of course isn't supported.

**Comment by madpipeline** [comment]
I mean what ever path is set as local storage in the Nextcloud Android app. In my case that currently is set to `/storage/emulated/0/Android/media/com.nextcloud.client`.

**Comment by AlvaroBrey** [comment]
Unfortunately I can't reproduce this. I see you were using version 3.17.0 of the app; some fixes were made to the space management implementation in 3.19.0.

Please verify if this still happens for you in 3.19.0 and if not, we can close this.

**Comment by madpipeline** [comment]
I can no longer reproduce this issue.
