### ISSUE TITLE
Crash after opening the app

### ISSUE THREAD

**Issue by pptthh** [nextcloud/android#8971]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to create application com.owncloud.android.MainApp: java.lang.SecurityException: Package android does not belong to 10226
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6860)
	at android.app.ActivityThread.access$1500(ActivityThread.java:250)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1989)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7864)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
Caused by: java.lang.SecurityException: Package android does not belong to 10226
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
	at android.os.Parcel.createException(Parcel.java:2360)
	at android.os.Parcel.readException(Parcel.java:2343)
	at android.os.Parcel.readException(Parcel.java:2285)
	at android.net.IConnectivityManager$Stub$Proxy.getNetworkCapabilities(IConnectivityManager.java:2456)
	at android.net.ConnectivityManager.getNetworkCapabilities(ConnectivityManager.java:1437)
	at com.nextcloud.client.network.ConnectivityServiceImpl.getConnectivity(ConnectivityServiceImpl.java:103)
	at com.owncloud.android.utils.FilesSyncHelper.restartJobsIfNeeded(FilesSyncHelper.java:233)
	at com.owncloud.android.MainApp.initSyncOperations(MainApp.java:456)
	at com.owncloud.android.MainApp.onCreate(MainApp.java:287)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6855)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.AppOpsManager.checkPackage(AppOpsManager.java:7924)
	at com.android.server.MtkConnectivityService.getNetworkCapabilities(MtkConnectivityService.java:1750)
	at android.net.IConnectivityManager$Stub.onTransact(IConnectivityManager.java:978)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
	at android.os.Binder.execTransact(Binder.java:1123)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Redmi
Device: merlinnfc
Model: M2003J15SC
Id: RP1A.200720.011
Product: merlinnfc_eea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: V12.5.1.0.RJOEUXM

**Comment by AlvaroBrey** [comment]
That stack trace suggests that the app process is bound to the wrong user. Did you:

* Install the app with some sort of custom work profile or other "app duplicates" manager?
* Use some root program to force-move the app to an external storage?

Or something related to that?

Additionally, does this happen every time you try to open the app?  Does it happen on a fresh installation?

**Comment by pptthh** [comment]
Sorry, it never ever happened again.
* No, I haven't  _Install the app with some sort of custom work profile or other "app duplicates" manager_.
* and No, I haven't _Use some root program to force-move the app to an external storage_.
I do not know how to reproduce it. It was during the beginning of configuration, to connect with my server.
I haven't tried to install it again, because since than it works fine.

**Comment by AlvaroBrey** [comment]
Thank you @pptthh. Feel free to reopen if you find the problem again!
