### ISSUE TITLE
App crashes after renaming a large folder elsewhere: `android.database.CursorIndexOutOfBoundsException`

### ISSUE THREAD

**Issue by aarakh** [nextcloud/android#8986]
************ CAUSE OF ERROR ************
```
android.database.CursorIndexOutOfBoundsException: Index -1 requested, with a size of 17794
	at android.database.AbstractCursor.checkPosition(AbstractCursor.java:514)
	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:138)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:76)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:179)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProvider.delete(ContentProvider.java:1798)
	at android.content.ContentProviderOperation.applyInternal(ContentProviderOperation.java:389)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:352)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:675)
	at android.content.ContentProvider.applyBatch(ContentProvider.java:2454)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:403)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:576)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:564)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:2206)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:438)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:531)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:410)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:238)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:363)
	at java.lang.Thread.run(Thread.java:923)
```
************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: samsung
Device: t2s
Model: SM-G996B
Id: RP1A.200720.012
Product: t2sxxx

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: G996BXXS3AUHD

### Steps to reproduce
1. Not sure may be this one helps
2. directory previously named as "P h o t o s" with around ~ 55GB of images files(all jpg format)
3. Renamed this directory to "Photos" (Removed spaces) on Nextcloud desktop application.
4. On Android application however it's still showing as "P h o t o s", and nextcloud android application crashes whenever I try to browse files from that on Mobile Device.

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 11

Device model: Samsung SM-G996B

Stock or customized system: customized

Nextcloud app version: 30170090

Nextcloud server version: 21.0.4

Reverse proxy: None

**Comment by joshtrichards** [comment]
Fixed in #9694
