### ISSUE TITLE
Crash on deleting three local+remote files with latestF-Droid beta release(20160621)

### ISSUE THREAD

**Issue by gsurrel** [nextcloud/android#90]
### Actual behaviour
-Crash on deleting three local+remote files

### Expected behaviour
-Remove 3 files without crash rather than only two with a crash

### Environment data
Android version: 6.0.1

Device model: 1+1 

Stock or customized system: official cyanogen

Nextcloud app version: 20160621 (beta)

Nextcloud server version: unsure (owncloud external provider)

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Lost it when toggling between Firefox and the app on mobile.

What about adding automatically the log to that shortcut?

I could reproduce the crash, here is the log:

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getMimetype()' on a null object reference
	at com.owncloud.android.ui.fragment.OCFileListFragment.checkSendable(OCFileListFragment.java:455)
	at com.owncloud.android.ui.fragment.OCFileListFragment.access$400(OCFileListFragment.java:81)
	at com.owncloud.android.ui.fragment.OCFileListFragment$10.onItemCheckedStateChanged(OCFileListFragment.java:400)
	at android.widget.AbsListView$MultiChoiceModeWrapper.onItemCheckedStateChanged(AbsListView.java:6287)
	at android.widget.AbsListView.confirmCheckedPositionsById(AbsListView.java:5327)
	at android.widget.AbsListView.handleDataChanged(AbsListView.java:5348)
	at android.widget.ListView.layoutChildren(ListView.java:1563)
	at android.widget.AbsListView.onLayout(AbsListView.java:2148)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:584)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1724)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1490)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2934)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2179)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1939)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:606)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

************ DEVICE INFORMATION ***********
Brand: oneplus
Device: A0001
Model: A0001
Id: MHC19Q
Product: bacon

************ FIRMWARE ************
SDK: 23
Release: 6.0.1
Incremental: ced5430fc0




```

**Comment by przybylski** [comment]
Something is not right with this report, or the released APK. Method which is causing problem doesn't exist for a long time now.

**Comment by gsurrel** [comment]
The settings page says version 20160621 and the "Download latest beta version" confirms I'm running the latest. I'm running the f-droid version.

**Comment by przybylski** [comment]
Beta release has an old version of responsible files, I'm guessing that @tobiasKaminsky can tell when next best will be available (if any).

**Comment by tobiasKaminsky** [comment]
@gsurrel Can you update to the latest beta and try again?

**Comment by gsurrel** [comment]
I tried several times and at different moment (rebooted, fully synced...), I can't do a single write operation (delete file, folder not create one)

**Comment by AndyScherzinger** [comment]
Hi @gsurrel can you try to update via f-droid using the latest published beta: 20160728 ? :smiley:

**Comment by gsurrel** [comment]
It's the one I'm running, but nevermind, the host is down. I'll retry whenever they put the service back online.

**Comment by AndyScherzinger** [comment]
Oh okay! Sorry to hear that :(

**Comment by gsurrel** [comment]
It's working, indeed. It is really slow for my test folder of ~400 files (as in "Delete one, wait around 2 seconds, refresh displayed list, continue to next element to delete") but it works.
Thanks

**Comment by tobiasKaminsky** [comment]
Can you please open a new issue for this, if you think it is not good enough?
