### ISSUE TITLE
app crash after switching back to it

### ISSUE THREAD

**Issue by cyberb** [nextcloud/android#9006]
************ CAUSE OF ERROR ************
```java
java.lang.RuntimeException: Unable to resume activity {com.nextcloud.client/com.owncloud.android.ui.activity.UploadListActivity}: java.lang.RuntimeException: Accessing result data after operation failed!
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4300)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4332)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7561)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
Caused by: java.lang.RuntimeException: Accessing result data after operation failed!
	at com.owncloud.android.lib.common.operations.RemoteOperationResult.getData(RemoteOperationResult.java:514)
	at com.owncloud.android.ui.activity.UploadListActivity.onRemoteOperationFinish(UploadListActivity.java:290)
	at com.owncloud.android.services.OperationsService$OperationsServiceBinder.dispatchResultIfFinished(OperationsService.java:353)
	at com.owncloud.android.ui.activity.FileActivity.doOnResumeAndBound(FileActivity.java:564)
	at com.owncloud.android.ui.activity.FileActivity.onResume(FileActivity.java:243)
	at com.owncloud.android.ui.activity.UploadListActivity.onResume(UploadListActivity.java:211)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453)
	at android.app.Activity.performResume(Activity.java:8050)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4290)
	... 11 more
```
************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Redmi
Device: galahad
Model: M2004J19C
Id: QP1A.190711.020
Product: galahad_eea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: V12.0.2.0.QJCEUXM

**Comment by joshtrichards** [comment]
Any idea how to reproduce this behavior? Looks sort of like (but not exactly) #8213.

**Comment by cyberb** [comment]
I have not experienced it since, let's just close it.
