### ISSUE TITLE
Crash at start of application

### ISSUE THREAD

**Issue by mihtm97** [nextcloud/android#9089]
### Steps to reproduce
1. Start the App
2. Wait for the circle to stop moving
3. Read the crash notice

### Expected behaviour
- The app should pull the actualized list of dorectories and data from the server.

### Actual behaviour
- The App crashes during the loading of the actualized directory and data list. 

### Environment data
Android version: 11

Device model: OnePlus 7T

Stock or customized system: Stock

Nextcloud app version: 30170090

Nextcloud server version: 22.2.0

Reverse proxy: yes

###Error message###

************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Couldn't read row 1033, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:542)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:77)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:179)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProvider.delete(ContentProvider.java:1820)
	at android.content.ContentProviderOperation.applyInternal(ContentProviderOperation.java:389)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:352)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:675)
	at android.content.ContentProvider.applyBatch(ContentProvider.java:2476)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:421)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:586)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:574)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:2234)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:438)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:531)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:410)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:238)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:363)
	at java.lang.Thread.run(Thread.java:923)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus7T
Model: HD1903
Id: RKQ1.201022.002
Product: OnePlus7T_EEA

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 2108182246

**Comment by strugee** [comment]
Ack, that's embarrassing 😅 

I'm not sure what issue I meant to dupe this against, but it seems like #9076 is a duplicate anyway?
