### ISSUE TITLE
Not open auto uploads dirs

### ISSUE THREAD

**Issue by xpro666** [nextcloud/android#9173]
Have 2 problem
1 Not opened conflict resolver window
2 crash wen try open auto uploads dir

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.substring(int, int)' on a null object reference
	at com.owncloud.android.datamodel.OCFile.getLocalId(OCFile.java:555)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$fetchAndSetData$6$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:302)
	at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$teeJYeeJ0U_eGoL93tC3tkb9ND8.run(Unknown Source:8)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: a7y17lte
Model: SM-A720F
Id: R16NW
Product: a7y17ltexx

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: A720FXXS9CTJ9

**Comment by AlvaroBrey** [comment]
Fixed by #9902
