### ISSUE TITLE
More detailed error on Android 

### ISSUE THREAD

**Issue by simenatsu** [nextcloud/android#9273]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.substring(int, int)' on a null object reference
	at com.owncloud.android.datamodel.OCFile.getLocalId(OCFile.java:555)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$fetchAndSetData$6$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:302)
	at com.owncloud.android.ui.fragment.-$$Lambda$FileDetailActivitiesFragment$teeJYeeJ0U_eGoL93tC3tkb9ND8.run(Unknown Source:8)
	at java.lang.Thread.run(Thread.java:923)
********
ID: com.nextcloud.client
Version: 30170190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OPPO
Device: OP4A89
Model: PCLM10
Id: RKQ1.200928.002
Product: PCLM10

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 1625145099342

**Comment by AlvaroBrey** [comment]
Should be fixed by #9902
