### ISSUE TITLE
Trying to purge appdata android

### ISSUE THREAD

**Issue by tostlund** [nextcloud/android#9297]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 
Pixel
Stock or customized system:

Nextcloud app version:
Latest
Nextcloud server version:

Reverse proxy:

### Logs
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032 SQLITE_READONLY_DBMOVED)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:892)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:67)
	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1807)
	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1753)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:650)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:632)
	at android.content.ContentProvider.update(ContentProvider.java:1835)
	at android.content.ContentProvider$Transport.update(ContentProvider.java:452)
	at android.content.ContentResolver.update(ContentResolver.java:2400)
	at android.content.ContentResolver.update(ContentResolver.java:2362)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUpload(UploadsStorageManager.java:132)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUploadInternal(UploadsStorageManager.java:174)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUploadStatus(UploadsStorageManager.java:209)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateDatabaseUploadResult(UploadsStorageManager.java:580)
	at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:661)
	at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1402)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: sunfish
Model: Pixel 4a
Id: SP1A.211105.002
Product: sunfish

************ FIRMWARE ************
SDK: 31
Release: 12
Incremental: 7743617

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
Duplicate of #8985
