### ISSUE TITLE
Update to Nextcloud 3.18.0 prevents Nextcloud News app from fetching items

### ISSUE THREAD

**Issue by macearl** [nextcloud/android#9344]
### Steps to reproduce
1. Install and setup Nextcloud <3.18.0 
2. Setup the nextcloud news app with "login through Nextcloud App" 
3. Update to Nextcloud 3.18.0

### Expected behaviour
- the news app should still fetch new articles

### Actual behaviour
- the news app does not fetch any articles anymore and there are errors for the sso module:

## Environment data
Android version: 11

Device model: Pocophone F1

Stock or customized system: LineageOS 18 microg build

Nextcloud app version: 3.17.1 works,  3.18.0 not both f-Droid builds

Nextcloud server version: 21.0.5

Reverse proxy:

#### logcat
```
11-22 17:31:28.867 13322 23238 I chatty  : uid=10190(de.luhmer.owncloudnewsreader) expire 33 lines
11-22 17:31:28.908 13322 23240 I chatty  : uid=10190(de.luhmer.owncloudnewsreader) expire 1 line
11-22 17:31:28.917  6093  6497 E InputStreamBinder: Error during Nextcloud request
11-22 17:31:28.917  6093  6497 E InputStreamBinder: java.lang.ClassNotFoundException: com.nextcloud.android.sso.api.QueryParam
11-22 17:31:28.917  6093  6497 E InputStreamBinder: 	at java.lang.Class.classForName(Native Method)
11-22 17:31:28.917  6093  6497 E InputStreamBinder: 	at java.lang.Class.forName(Class.java:454)
11-22 17:31:28.917  6093  6497 E InputStreamBinder: 	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:682)
11-22 17:31:28.917  6093  6497 E InputStreamBinder: 	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1703)
11-22 17:31:28.917  6093  6497 E InputStreamBinder: 	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1594)
11-22 17:31:28.917  6093  6497 E InputStreamBinder: 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1872)
11-22 17:31:28.917  6093  6497 E InputStreamBinder: 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1412)
11-22 17:31:28.917  6093  6497 E InputStreamBinder: 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:427)
11-22 17:31:28.917  6093  6497 E InputStreamBinder: 	at java.util.LinkedList.readObject(LinkedList.java:1149)
11-22 17:31:28.917  6093  6497 E InputStreamBinder: 	at java.lang.reflect.Method.invoke(Native Method)
11-22 17:31:28.917  6093  6497 E InputStreamBinder: 	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1066)
11-22 17:31:28.917  6093  6497 E InputStreamBinder: 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2013)
11-22 17:31:28.917  6093  6497 E InputStreamBinder: 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1899)
11-22 17:31:28.917  6093  6497 E InputStreamBinder: 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1412)
11-22 17:31:28.917  6093  6497 E InputStreamBinder: 	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2114)
11-22 17:31:28.917  6093  6497 E InputStreamBinder: 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2038)
11-22 17:31:28.917  6093  6497 E InputStreamBinder: 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1899)
11-22 17:31:28.917  6093  6497 E InputStreamBinder: 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1412)
11-22 17:31:28.917  6093  6497 E InputStreamBinder: 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:427)
11-22 17:31:28.917  6093  6497 E InputStreamBinder: 	at com.nextcloud.android.sso.InputStreamBinder.deserializeObjectAndCloseStream(InputStreamBinder.java:226)
11-22 17:31:28.917  6093  6497 E InputStreamBinder: 	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStream(InputStreamBinder.java:171)
11-22 17:31:28.917  6093  6497 E InputStreamBinder: 	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequest(InputStreamBinder.java:149)
11-22 17:31:28.917  6093  6497 E InputStreamBinder: 	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:109)
11-22 17:31:28.917  6093  6497 E InputStreamBinder: 	at android.os.Binder.execTransactInternal(Binder.java:1154)
11-22 17:31:28.917  6093  6497 E InputStreamBinder: 	at android.os.Binder.execTransact(Binder.java:1123)
11-22 17:31:28.917  6093  6497 E InputStreamBinder: Caused by: java.lang.ClassNotFoundException: com.nextcloud.android.sso.api.QueryParam
11-22 17:31:28.917  6093  6497 E InputStreamBinder: 	... 25 more
11-22 17:31:28.924  6093 23241 E com.nextcloud.android.sso.aidl.ParcelFileDescriptorUtil.TransferThread: writing failed: write failed: EPIPE (Broken pipe)
11-22 17:31:28.924  6093 23241 D InputStreamBinder: Done sending result
```

**Comment by macearl** [comment]
Seems to have been fixed in: https://github.com/nextcloud/news-android/releases/tag/v.0.9.9.65

So I'm guessing the sso module/library was intentionally removed.
