### ISSUE TITLE
Crash clicking on a full text search result

### ISSUE THREAD

**Issue by jkumeboshi** [nextcloud/android#9345]
### Steps to reproduce
1. Enable full text search
2. Search text inside a PDF
3. Click on any search resul from full text search plugin

### Expected behaviour
- the PDF should open

### Actual behaviour
- application exception

Crash log:

************ CAUSE OF ERROR ************

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=/apps/files/?dir=/&scrollto=doc.pdf }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2081)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1737)
	at android.app.Activity.startActivityForResult(Activity.java:5420)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
	at android.app.Activity.startActivityForResult(Activity.java:5378)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:583)
	at android.app.Activity.startActivity(Activity.java:5764)
	at androidx.core.content.ContextCompat$Api16Impl.startActivity(ContextCompat.java:828)
	at androidx.core.content.ContextCompat.startActivity(ContextCompat.java:276)
	at androidx.fragment.app.FragmentHostCallback.onStartActivityFromFragment(FragmentHostCallback.java:166)
	at androidx.fragment.app.Fragment.startActivity(Fragment.java:1377)
	at androidx.fragment.app.Fragment.startActivity(Fragment.java:1365)
	at com.owncloud.android.ui.fragment.UnifiedSearchFragment.setUpViewModel$lambda-3(UnifiedSearchFragment.kt:113)
	at com.owncloud.android.ui.fragment.UnifiedSearchFragment.$r8$lambda$QwgTQ7EDrXEkSMPCsDx-t5cEFXw(Unknown Source:0)
	at com.owncloud.android.ui.fragment.UnifiedSearchFragment$$ExternalSyntheticLambda0.onChanged(Unknown Source:4)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at com.owncloud.android.ui.unifiedsearch.UnifiedSearchViewModel.openResult(UnifiedSearchViewModel.kt:151)
	at com.owncloud.android.ui.fragment.UnifiedSearchFragment.onSearchResultClicked(UnifiedSearchFragment.kt:173)
	at com.owncloud.android.ui.adapter.UnifiedSearchItemViewHolder.bind$lambda-0(UnifiedSearchItemViewHolder.kt:81)
	at com.owncloud.android.ui.adapter.UnifiedSearchItemViewHolder.$r8$lambda$Kwk2aCSP5YJnTxPcA1OzfMLcrgw(Unknown Source:0)
	at com.owncloud.android.ui.adapter.UnifiedSearchItemViewHolder$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7509)
	at android.view.View.performClickInternal(View.java:7486)
	at android.view.View.access$3600(View.java:841)
	at android.view.View$PerformClick.run(View.java:28709)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8061)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: raphael
Model: Mi 9T Pro
Id: RKQ1.200826.002
Product: raphael_eea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: V12.5.1.0.RFKEUXM

**Comment by AlvaroBrey** [comment]
Hi @jkumeboshi, thanks for your report. do you know if this worked before the 3.18 update?

**Comment by jkumeboshi** [comment]
Well, in v3.17 there wasn't "unified search" in the android app, results from fulltextsearch provider just didn't appeared.

If you instead mean in any v3.18-RC pre release, I didn't tested it, so I cannot say.

Anyway, same error happens with the dev version 20211119 from f-droid
