### ISSUE TITLE
App sometimes crashes when listening tracks via Music Nextcloud app.

### ISSUE THREAD

**Issue by vitasha10** [nextcloud/android#9353]
### Steps to reproduce
1. Install nextcloud 22.2.0 via docker.
2. Install Music by Pauli Järvinen.
3. Start listen music in android nextcloud app.
4. Sometimes app is crashing.

### Expected behaviour
App should work without crashes.

### Actual behaviour
App is crashing.

### Can you reproduce this problem on try...
Actually it's android nextcloud app/Music app problem.
Please read logs!

### Environment data
Android version: 12 Stable

Device model: Redmi note 7 (Pixel 6 Pro)

Stock or customized system: port from Pixel 6 Pro. Spotify and every other app is working correctly.

Nextcloud app version: 30180090

Nextcloud server version: 22.2.0

Reverse proxy: none

#### Web server error log
```
None at that (+-hour) time.
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

android.app.ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{f74c7f5 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1923)
	at android.app.ActivityThread.access$2700(ActivityThread.java:247)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2148)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7838)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: raven
Model: Pixel 6 Pro
Id: SD1A.210817.036
Product: raven

************ FIRMWARE ************
SDK: 31
Release: 12
Incremental: 7805805

```

**Comment by AlvaroBrey** [comment]
@vitasha10 can you still reproduce this crash in latest app versions?
