### ISSUE TITLE
Nextcloud app problems

### ISSUE THREAD

**Issue by YamiChris** [nextcloud/android#9360]
Hey guys

We want to use nextcloud in my kindergarden and we use tablets and Laptops. Since few days we cant use nextcloud app with our tablets. The Laptops haven't any problems. Please help us. 

```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.substring(int, int)' on a null object reference
	at com.owncloud.android.datamodel.OCFile.getLocalId(OCFile.java:555)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$fetchAndSetData$6$com-owncloud-android-ui-fragment-FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:302)
	at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment$$ExternalSyntheticLambda6.run(Unknown Source:8)
	at java.lang.Thread.run(Thread.java:923)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: gta4lwifi
Model: SM-T500
Id: RP1A.200720.012
Product: gta4lwifieea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: T500XXU3BUJ1
```

**Comment by ezaquarii** [comment]
@YamiChris Can you tell us how did you reproduce this issue? Is the file locally on the device?

**Comment by ezaquarii** [comment]
@YamiChris does it also happen on a phone?
