### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by markginter31** [nextcloud/android#9364]
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032 SQLITE_READONLY_DBMOVED)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:892)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:67)
	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1807)
	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1753)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:646)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:630)
	at android.content.ContentProvider.update(ContentProvider.java:1835)
	at android.content.ContentProvider$Transport.update(ContentProvider.java:452)
	at android.content.ContentResolver.update(ContentResolver.java:2400)
	at android.content.ContentResolver.update(ContentResolver.java:2362)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveCapabilities(FileDataStorageManager.java:1955)
	at com.owncloud.android.operations.GetCapabilitiesOperation.run(GetCapabilitiesOperation.java:55)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:143)
	at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:64)
	at com.owncloud.android.operations.RefreshFolderOperation.updateCapabilities(RefreshFolderOperation.java:304)
	at com.owncloud.android.operations.RefreshFolderOperation.updateOCVersion(RefreshFolderOperation.java:280)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:231)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:363)
	at java.lang.Thread.run(Thread.java:920)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: blueline
Model: Pixel 3
Id: SP1A.210812.015
Product: blueline

************ FIRMWARE ************
SDK: 31
Release: 12
Incremental: 7679548

**Comment by AlvaroBrey** [comment]
Hi @markginter31, can you reproduce this issue? If so, what are the steps? And if not, what were you doing in the app when it crashed?

**Comment by markginter31** [comment]
It crashed - gave the option to post a bug - and when I restarted the app it worked fine -- so this can be closed.  Thanks for checking so quickly!
