### ISSUE TITLE
File list crashed after login: android.database.sqlite.SQLiteBlobTooBigException

### ISSUE THREAD

**Issue by alerque** [nextcloud/android#9384]
### Steps to reproduce
1. open app
2. grant new all files permission, then login again when prompted
3. click on dir. crash.

**Comment by alerque** [comment]
This was a report by email and I didn't know much about it at the time.

I'm still seeing this ... at it happens any time the app tries to refresh the main top level file list. The app connects and I can use things like the activity view, but if I try to refresh the file list or tap on any directory it crashes.

This only happening on my Phone (OnePlus 5) where Nextcloud is installed from the Play stor, but not on my eink tablet (Boox Nova Air) where it is installed from F-Droid. The crashing version on my phone is 3.18.0.

**Comment by alerque** [comment]
I tried clearing the cache and user data for the Nextcloud app from my phone, and got the same result. Crash on refresh.

I uninstalled the Play Store version and installed in from F-Droid instead (same version number). Now it works fine as expected.

**Comment by AlvaroBrey** [comment]
That is strange, there shouldn't be that much of a difference between the GPlay and the F-Droid versions. Do you:
a) Have spaces in your username, or
b) Have a lot of files in your top directory (as in more than 1000)?

Just trying to narrow it down. Of course if you could get a logcat that would be great.

**Comment by alerque** [comment]
> a) Have spaces in your username, or

No. All lowercase ASCII.

Note that authentication is through a SSO plugin.

> b) Have a lot of files in your top directory (as in more than 1000)?

No, 116.

There is one directory in my account with ~3700 files in a single directory, but that wasn't what I was opening and it isn't the top level.

A logcat is kind of hard to get at the moment. If I get a chance to switch back to Play I'll give it a go. I think it was supposed to be attached to this issue report (which was automatically submitted) but I don't see it.

**Comment by AlvaroBrey** [comment]
> > a) Have spaces in your username, or
> 
> 
> Note that authentication is through a SSO plugin.
> 

Ah, this may be related to #9486 then. We have to investigate if there's something wrong with SSO login.

**Comment by alerque** [comment]
Here is a crash log from another device (my wife's) which just turned up the same problem (infrequently used, probably dates back to the same time I had the issue). The same solution switching to an F-Droid build worked for her too.

Different device, different Android version, same Nextcloud instance and SSO in use.

```
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=3112, totalRows=1717
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:895)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:157)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:128)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:237)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:269)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:190)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:184)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProvider$Transport.delete(ContentProvider.java:344)
	at android.content.ContentResolver.delete(ContentResolver.java:1685)
	at com.owncloud.android.datamodel.FileDataStorageManager.removeFolderInDb(FileDataStorageManager.java:632)
	at com.owncloud.android.datamodel.FileDataStorageManager.removeFolder(FileDataStorageManager.java:607)
	at com.owncloud.android.operations.RefreshFolderOperation.removeLocalFolder(RefreshFolderOperation.java:427)
	at com.owncloud.android.operations.RefreshFolderOperation.checkForChanges(RefreshFolderOperation.java:388)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:235)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:363)
	at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Lenovo
Device: K53a48
Model: Lenovo K53a48
Id: PQ3A.190801.002
Product: karatep

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 8
```

**Comment by Zocker1999NET** [comment]
I have a really similar issue, but I use a F-Droid build instead of the Google Play version. I have not any directory on Nextcloud with more than 300 files, the base directory has about 30 entries. But I used Nextcloud as target for Seedvault (integrated in Lineage OS) backups.
I disabled the backups (but did not remove them from Nextcloud), cleared the whole app data and config and so far no issue occurred. I will test it for the next days and will eventually reenable Seedvault backups to check, if the issue will reappear.

**Comment by joshtrichards** [comment]
Fixed in #9694
