### ISSUE TITLE
QR- picture crashes android app

### ISSUE THREAD

**Issue by jontok** [nextcloud/android#9419]
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:48705 flg=0x1 }} to activity {com.nextcloud.client/com.blikoon.qrcodescanner.QrCodeActivity}: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5244)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5285)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2251)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
	at android.database.AbstractCursor.checkPosition(AbstractCursor.java:514)
	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:138)
	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:52)
	at android.database.CursorWrapper.getString(CursorWrapper.java:141)
	at com.blikoon.qrcodescanner.QrCodeActivity.getPathFromUri(QrCodeActivity.java:390)
	at com.blikoon.qrcodescanner.QrCodeActivity.onActivityResult(QrCodeActivity.java:370)
	at android.app.Activity.dispatchActivityResult(Activity.java:8316)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5237)
	... 11 more

```

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus6
Model: ONEPLUS A6003
Id: RKQ1.201217.002
Product: OnePlus6

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 2109171635

**Comment by joshtrichards** [comment]
Hi @jontok - Can you provide reproduction steps?

Appears to be a duplicate of #6930, but it was closed to a lack of follow-up information.
