### ISSUE TITLE
NEXTCLOUD ANDROID CRASH REPORT

### ISSUE THREAD

**Issue by tendaworld** [nextcloud/android#9455]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen
Login into to Nextcloud Android App with username password of a registered user. 
Grant Access to your Android device to access you XXXX nextcloud account. 
### Actual behaviour
- Tell us what happens
App Crashed
### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:
Brand: OnePlus
Device: OnePlus8Pro
Model: IN2020
Id: RP1A.201005.001
Product: OnePlus8Pro
Device model: 

Stock or customized system:
Stock
Nextcloud app version:
3.18.0
Nextcloud server version:
22.2.0
Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.RuntimeException: Accessing result data after operation failed!
	at com.owncloud.android.lib.common.operations.RemoteOperationResult.getResultData(RemoteOperationResult.java:503)
	at com.owncloud.android.authentication.AuthenticatorAsyncTask.doInBackground(AuthenticatorAsyncTask.java:80)
	at com.owncloud.android.authentication.AuthenticatorAsyncTask.doInBackground(AuthenticatorAsyncTask.java:45)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus8Pro
Model: IN2020
Id: RP1A.201005.001
Product: OnePlus8Pro

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 2110091917

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
Any special characters in the username (spaces, symbols...)?

**Comment by tendaworld** [comment]
Username used for two failing cases is:

j-xxxx, and
***@***.***

**Comment by Llazcanoster** [comment]
I think it is the same error

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Canvas: trying to draw too large(527785020bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
	at android.graphics.drawable.LayerDrawable.draw(LayerDrawable.java:1018)
	at android.widget.ImageView.onDraw(ImageView.java:1436)
	at android.view.View.draw(View.java:22350)
	at android.view.View.updateDisplayListIfDirty(View.java:21226)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22353)
	at android.view.View.updateDisplayListIfDirty(View.java:21226)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5204)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22353)
	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4603)
	at android.view.View.updateDisplayListIfDirty(View.java:21226)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22353)
	at com.google.android.material.internal.ScrimInsetsFrameLayout.draw(ScrimInsetsFrameLayout.java:109)
	at android.view.View.updateDisplayListIfDirty(View.java:21226)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22353)
	at android.view.View.updateDisplayListIfDirty(View.java:21226)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22353)
	at com.android.internal.policy.DecorView.draw(DecorView.java:806)
	at android.view.View.updateDisplayListIfDirty(View.java:21226)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4106)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3833)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3104)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus5T
Model: ONEPLUS A5010
Id: RQ3A.211001.001
Product: OnePlus5T

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: eng.root.20211203.184102

**Comment by AlvaroBrey** [comment]
> I think it is the same error when I press the top three bars

No, that's a completely different trace. This last one is the same as #8862, which should be fixed soon.

**Comment by Llazcanoster** [comment]
> > I think it is the same error when I press the top three bars
> 
> No, that's a completely different trace. This last one is the same as #8862, which should be fixed soon.

Ok, sorry for duplicating, I was checking and didn't find that case, sorry.
Shall I delete the post so as not to mess up where it doesn't belong?
