### ISSUE TITLE
Crash report after encountering server not available

### ISSUE THREAD

**Issue by balvie** [nextcloud/android#9458]
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Fragment PreviewImageFragment{f8f71dc} (a85b95d0-1e2c-4df0-9173-cbf72b9de093) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:900)
	at androidx.fragment.app.Fragment.getResources(Fragment.java:964)
	at com.owncloud.android.ui.preview.PreviewImageFragment.lambda$setErrorPreviewMessage$2$com-owncloud-android-ui-preview-PreviewImageFragment(PreviewImageFragment.java:723)
	at com.owncloud.android.ui.preview.PreviewImageFragment$$ExternalSyntheticLambda2.onClick(Unknown Source:2)
	at com.google.android.material.snackbar.Snackbar$1.onClick(Snackbar.java:351)
	at android.view.View.performClick(View.java:7520)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
	at android.view.View.performClickInternal(View.java:7489)
	at android.view.View.access$3600(View.java:826)
	at android.view.View$PerformClick.run(View.java:28555)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus6
Model: ONEPLUS A6003
Id: RKQ1.201217.002
Product: OnePlus6

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 2111252325

**Comment by balvie** [comment]
no further actio is taken by others. Me myself have no linger interest in answers.
Closing...
