### ISSUE TITLE
S5 Neo: no start

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#946]
I wanted to debug some stuff with external sdcard on Samsung s5 Neo.
But I even cannot launch it...
Does anybody have any idea?

` FATAL EXCEPTION: main
                                                                      Process: com.nextcloud.client, PID: 27929
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.WhatsNewActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x7f08000a
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3255)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3351)
                                                                          at android.app.ActivityThread.access$1100(ActivityThread.java:222)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:158)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:7230)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                       Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x7f08000a
                                                                          at android.content.res.Resources.getText(Resources.java:1468)
                                                                          at android.widget.TextView.setText(TextView.java:5051)
                                                                          at com.owncloud.android.ui.activity.WhatsNewActivity.onCreate(WhatsNewActivity.java:134)
                                                                          at android.app.Activity.performCreate(Activity.java:6877)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3208)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3351) 
                                                                          at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:158) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:7230) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
05-03 15:32:15.219 27929-28106/com.nextcloud.client D/JobRescheduleService: Reschedule 0 jobs of 0 jobs`

**Comment by mario** [comment]
Sounds like missing some string?

**Comment by AndyScherzinger** [comment]
Either WhatsNewActivity isn't defined as an activity in the manifest or you can also try a rebuild. Else I don't see a reason for this stack trace...

**Comment by tobiasKaminsky** [comment]
It is exactly the same code rev which is working on emulator.
(of course it get recompiled and installed via adb, but this is all handled by AndroidStudio).

**Comment by AndyScherzinger** [comment]
The WhatsNewActivity.java:134 line seems to want to set a String that isn't available?!

**Comment by tobiasKaminsky** [comment]
It seems so. But why does this is wanted on a real phone, but not on my emulator?
