### ISSUE TITLE
State handling error - IllegalStateException

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#95]
Crash from the Google Play Developer Console:

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
    at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1489)
    at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1507)
    at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:634)
    at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:613)
    at com.owncloud.android.ui.activity.FileDisplayActivity.cleanSecondFragment(FileDisplayActivity.java:463)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onBackPressed(FileDisplayActivity.java:819)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onOptionsItemSelected(FileDisplayActivity.java:557)
    at android.app.Activity.onMenuItemSelected(Activity.java:2919)
    at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:361)
    at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:147)
    at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
    at android.support.v7.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:194)
    at android.view.View.performClick(View.java:5226)
    at android.view.View$PerformClick.run(View.java:21266)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:168)
    at android.app.ActivityThread.main(ActivityThread.java:5845)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
```

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
    at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1493)
    at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1511)
    at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:638)
    at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:617)
    at android.support.v4.app.DialogFragment.dismissInternal(DialogFragment.java:201)
    at android.support.v4.app.DialogFragment.dismiss(DialogFragment.java:167)
    at com.owncloud.android.ui.activity.FileActivity.dismissLoadingDialog(FileActivity.java:485)
    at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:297)
    at com.owncloud.android.ui.activity.ShareActivity.onRemoteOperationFinish(ShareActivity.java:203)
    at com.owncloud.android.utils.GetShareWithUsersAsyncTask.onPostExecute(GetShareWithUsersAsyncTask.java:94)
    at com.owncloud.android.utils.GetShareWithUsersAsyncTask.onPostExecute(GetShareWithUsersAsyncTask.java:44)
    at android.os.AsyncTask.finish(AsyncTask.java:636)
    at android.os.AsyncTask.access$500(AsyncTask.java:177)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5282)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

```
java.lang.RuntimeException: Unable to stop activity {com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
    at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3544)
    at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3594)
    at android.app.ActivityThread.-wrap20(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1392)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5466)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
    at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1489)
    at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1507)
    at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:634)
    at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:613)
    at android.support.v4.app.DialogFragment.dismissInternal(DialogFragment.java:201)
    at android.support.v4.app.DialogFragment.dismiss(DialogFragment.java:167)
    at com.owncloud.android.ui.preview.PreviewTextFragment$TextLoadAsyncTask.dismissLoadingDialog(PreviewTextFragment.java:249)
    at com.owncloud.android.ui.preview.PreviewTextFragment.onStop(PreviewTextFragment.java:406)
    at android.support.v4.app.Fragment.performStop(Fragment.java:2135)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1124)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
    at android.support.v4.app.FragmentManagerImpl.dispatchStop(FragmentManager.java:2065)
    at android.support.v4.app.FragmentController.dispatchStop(FragmentController.java:209)
    at android.support.v4.app.FragmentActivity.onStop(FragmentActivity.java:567)
    at android.support.v7.app.AppCompatActivity.onStop(AppCompatActivity.java:135)
    at com.owncloud.android.ui.activity.FileDisplayActivity.onStop(FileDisplayActivity.java:264)
    at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1279)
    at android.app.Activity.performStop(Activity.java:6395)
    at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3541)
    ... 9 more
```

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
    at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1493)
    at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1511)
    at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:638)
    at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:617)
    at android.support.v4.app.DialogFragment.dismissInternal(DialogFragment.java:201)
    at android.support.v4.app.DialogFragment.dismiss(DialogFragment.java:167)
    at com.owncloud.android.ui.activity.FileActivity.dismissLoadingDialog(FileActivity.java:485)
    at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:297)
    at com.owncloud.android.ui.activity.ShareActivity.onRemoteOperationFinish(ShareActivity.java:203)
    at com.owncloud.android.utils.GetShareWithUsersAsyncTask.onPostExecute(GetShareWithUsersAsyncTask.java:94)
    at com.owncloud.android.utils.GetShareWithUsersAsyncTask.onPostExecute(GetShareWithUsersAsyncTask.java:44)
    at android.os.AsyncTask.finish(AsyncTask.java:651)
    at android.os.AsyncTask.-wrap1(AsyncTask.java)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky it seems the app has several state issues linked to asynchronous processing

**Comment by tobiasKaminsky** [comment]
This is so old and I have no idea how to reproduce it, thus I think we have to close this and hope that a) it never happens again or b) we get a proper description.
