### ISSUE TITLE
App don't work without android webview

### ISSUE THREAD

**Issue by johnwooded** [nextcloud/android#9585]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens
- app crash when i paste my server address and press enter

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model:  Oneplus 7 pro

Stock or customized system: Lineage os 18.1 (without gapps and with android web view uninstalled cause it's developed by google)

Nextcloud app version: 20211211

Nextcloud server version: I don't know, i just use opsone-cloud

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
************ CAUSE OF ERROR ************

android.view.InflateException: Binary XML file line #10 in com.nextcloud.android.beta:layout/account_setup_webview: Binary XML file line #10 in com.nextcloud.android.beta:layout/account_setup_webview: Error inflating class android.webkit.WebView
Caused by: android.view.InflateException: Binary XML file line #10 in com.nextcloud.android.beta:layout/account_setup_webview: Error inflating class android.webkit.WebView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createView(LayoutInflater.java:774)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:928)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:948)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1002)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at com.owncloud.android.databinding.AccountSetupWebviewBinding.inflate(AccountSetupWebviewBinding.java:50)
	at com.owncloud.android.databinding.AccountSetupWebviewBinding.inflate(AccountSetupWebviewBinding.java:44)
	at com.owncloud.android.authentication.AuthenticatorActivity.onGetServerInfoFinish(AuthenticatorActivity.java:929)
	at com.owncloud.android.authentication.AuthenticatorActivity.onRemoteOperationFinish(AuthenticatorActivity.java:843)
	at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:778)
	at com.owncloud.android.services.OperationsService$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:435)
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:252)
	at android.webkit.WebView.getFactory(WebView.java:2576)
	at android.webkit.WebView.ensureProviderCreated(WebView.java:2570)
	at android.webkit.WebView.setOverScrollMode(WebView.java:2638)
	at android.view.View.<init>(View.java:5321)
	at android.view.View.<init>(View.java:5467)
	at android.view.ViewGroup.<init>(ViewGroup.java:697)
	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
	at android.webkit.WebView.<init>(WebView.java:413)
	at android.webkit.WebView.<init>(WebView.java:355)
	at android.webkit.WebView.<init>(WebView.java:337)
	at android.webkit.WebView.<init>(WebView.java:324)
	... 26 more
Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:339)
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:402)
	... 38 more

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20211211
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus7Pro
Model: GM1917
Id: RQ3A.211001.001
Product: OnePlus7Pro

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 10037534

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AndyScherzinger** [comment]
Please upgrade to the latest webview, you can do so via Google Play store since the OS version isn't updated regularly. See https://play.google.com/store/apps/details?id=com.google.android.webview
