### ISSUE TITLE
NPE in OCFile.getRemotePath()

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android#96]
Crash from the Google Play Developer Console:

```
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.files.services.FileUploaderUPLOAD_FINISH flg=0x10 (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$UploadFinishReceiver@3505cb1
    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:892)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5466)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String 
    com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.ui.activity.FileDisplayActivity$UploadFinishReceiver.onReceive(FileDisplayActivity.java:1068)
    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:882)
    ... 7 more
```

Reported 3 times for 1.0.0 and 1.0.1 on Android 6.0, 5.0, 4.4

**Comment by tobiasKaminsky** [comment]
Without more context, I am closing this :/
