### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by bugimann1** [nextcloud/android#9605]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Couldn't read row 1102, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:542)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:77)
	at com.owncloud.android.providers.FileContentProvider.deleteDirectory(FileContentProvider.java:179)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:134)
	at com.owncloud.android.providers.FileContentProvider.delete(FileContentProvider.java:114)
	at android.content.ContentProvider.delete(ContentProvider.java:1757)
	at android.content.ContentProviderOperation.applyInternal(ContentProviderOperation.java:401)
	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:357)
	at com.owncloud.android.providers.FileContentProvider.applyBatch(FileContentProvider.java:673)
	at android.content.ContentProvider.applyBatch(ContentProvider.java:2413)
	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:403)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:576)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:564)
	at android.content.ContentResolver.applyBatch(ContentResolver.java:2212)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFolder(FileDataStorageManager.java:448)
	at com.owncloud.android.operations.RefreshFolderOperation.synchronizeData(RefreshFolderOperation.java:530)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:409)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:239)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:363)
	at java.lang.Thread.run(Thread.java:923)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: realme
Device: RMX2202L1
Model: RMX2202
Id: RKQ1.201105.002
Product: RMX2202EEA

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 1634579115446

**Comment by AlvaroBrey** [comment]
Hello @bugimann1 , please fill in the report template (app version, repro steps, etc)
