### ISSUE TITLE
Not working on android 11

### ISSUE THREAD

**Issue by DaveSV** [nextcloud/android#9616]
### Steps to reproduce
1. Login to own server
2. accept user and password
3. stuks on loading with serevral errors

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by DaveSV** [comment]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.RuntimeException: Accessing result data after operation failed!
	at com.owncloud.android.lib.common.operations.RemoteOperationResult.getResultData(RemoteOperationResult.java:503)
	at com.owncloud.android.authentication.AuthenticatorAsyncTask.doInBackground(AuthenticatorAsyncTask.java:80)
	at com.owncloud.android.authentication.AuthenticatorAsyncTask.doInBackground(AuthenticatorAsyncTask.java:45)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: motorola
Device: cebu
Model: moto g(9) power
Id: RZCS31.Q2-57-12-3
Product: cebu_retail

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 3dc37

**Comment by sgutermann** [comment]
looks like the same error as mine

**Comment by sgutermann** [comment]
I had the above error as well. It turned out that it is the exact same error you get when you have messed up on your proxy header.

Lokking in vie the browser will not show the error, however all mobile Apps will.

So if you have the lates version and still get this error do check you proxy header setup.

**Comment by AlvaroBrey** [comment]
@DaveSV please check if @sgutermann 's solution works for you (if you have a proxy setup).

**Comment by DaveSV** [comment]
Yes, I´ll do it.

**Comment by DaveSV** [comment]
Thnx!

**Comment by DaveSV** [comment]
I think that indeed the problem may be in my ISP's proxy. I will do some tests configuring my direct connection to verify or discard.
