### ISSUE TITLE
Crash on FileUploaderService

### ISSUE THREAD

**Issue by Jnidecki** [nextcloud/android#9617]
### Steps to reproduce
1. Upload large amount of files in one session
2. 
3. 

### Expected behaviour
- Tell us what should happen
- Diesnt upload and comes up with crash report on exiting nextcloud app

### Actual behaviour
- Tell us what happens
- doesnt upload and crashes on exiting the app

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: s21 ultra lates OS

Stock or customized system:

Nextcloud app version: latest fresh install

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
************ CAUSE OF ERROR ************

android.app.ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{1d96e82 u0 com.nextcloud.client/com.owncloud.android.files.services.FileUploader}
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2134)
	at android.app.ActivityThread.access$2900(ActivityThread.java:309)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2363)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8582)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: p3s
Model: SM-G998B
Id: SP1A.210812.016
Product: p3sxeea

************ FIRMWARE ************
SDK: 31
Release: 12
Incremental: G998BXXS3BUL1

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
Fixed by #10737
