### ISSUE TITLE
unresponsive, then crash 

### ISSUE THREAD

**Issue by JanneM** [nextcloud/android#9621]
The android app freezes when opening, after drawing the updating-circle thing. It then adds a large chunk of base64 encoded html data at the top of the file list. 

The app remains unresponsive and after a bit I get a crash message and invited to report it here.

### Steps to reproduce
1. Have a nextcloud instance (Ubuntu snap, so up to date)
2. Open the nextcloud app for the first time in a long time

### Expected behaviour
Not doing the below would be nice :)

### Actual behaviour

 The app freezes, shows a base64 encoded chunk of html data at the top of the file list, then crashes.

### Can you reproduce this problem on https://try.nextcloud.com?

Not applicable or doable as the app crashes on start.

### Environment data
Android version: 12

Device model: pixel 5

Stock or customized system: stock (YouTube Vanced is installed)

Nextcloud app version: 3.18.1

Nextcloud server version: 22.3.3snap2 (Ubuntu snap install)

Reverse proxy: nginx

#### Web server error log

I'm on my phone. From what I can see there is only a billion lines of the following spammed in the log:

```
Debug files_sha... /appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead
```

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 826940 bytes
	at android.app.ActivityClient.activityStopped(ActivityClient.java:86)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: android.os.TransactionTooLargeException: data parcel size 826940 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:571)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1297)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:83)
	... 9 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: redfin
Model: Pixel 5
Id: SQ1A.211205.008
Product: redfin

************ FIRMWARE ************
SDK: 31
Release: 12
Incremental: 7888514

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by JanneM** [comment]
The data is an image/svg+html

**Comment by ParishMills** [comment]
I ran into this same problem. 

THE FIX: I uninstalled the Nextcloud app that I had installed from the Google Play Store, and installed the version on F-Droid. I was then able to login to Nextcloud without any error messages. I know this doesn't solve the problem with the Play Store's version, but it does get us up and running.
