### ISSUE TITLE
Batch uploads limited to 7 files

### ISSUE THREAD

**Issue by agp8x** [nextcloud/android#9627]
I noticed that from 190 photos, autoupload only put 90 in my nextcloud instance. Because I did not want to figure this out on android, I tried to upload the photos to another folder an sort it out later. This manual upload only contained 7 photos, the upload log did not list any further files. I could upload the remaining files in batches of 7, which is rather tedious.

I only tested with Photo files, with Google Files and Photo app.

### Steps to reproduce
1. Use nextcloud 3.18.0 on android 12 (Pixel 6)
2. select many files  (9+)
3. Share them to nextcloud

### Expected behaviour
- All files should be uploaded to the server

### Actual behaviour
- The upload Activity list only 7 files, and 7 files appear in the nextcloud instance.
- With `adb logcat` I catched  this snippet when batch uploading:
```
12-27 16:47:35.130  2458  2458 D FileUploader: Starting command with id 7
12-27 16:47:35.131  1391  2129 E DatabaseUtils: Writing exception to parcel
12-27 16:47:35.131  1391  2129 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading com.google.android.apps.photos.contentprovider.impl.MediaContentProvider uri content://com.google.android.apps.photos.contentprovider/0/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F9282/REQUIRE_ORIGINAL/NONE/image%2Fjpeg/174017837 from pid=2458, uid=10249 requires the provider be exported, or grantUriPermission()
12-27 16:47:35.131  1391  2129 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:832)
12-27 16:47:35.131  1391  2129 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:694)
12-27 16:47:35.131  1391  2129 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:233)
12-27 16:47:35.131  1391  2129 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
12-27 16:47:35.131  1391  2129 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1184)
12-27 16:47:35.131  1391  2129 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1143)
12-27 16:47:35.133  2458  2519 E CopyAndUploadContentUrisTask: Not enough permissions to read source file content://com.google.android.apps.photos.contentprovider/0/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F9282/REQUIRE_ORIGINAL/NONE/image%2Fjpeg/174017837
12-27 16:47:35.133  2458  2519 E CopyAndUploadContentUrisTask: java.lang.SecurityException: Permission Denial: reading com.google.android.apps.photos.contentprovider.impl.MediaContentProvider uri content://com.google.android.apps.photos.contentprovider/0/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F9282/REQUIRE_ORIGINAL/NONE/image%2Fjpeg/174017837 from pid=2458, uid=10249 requires the provider be exported, or grantUriPermission()
12-27 16:47:35.133  2458  2519 E CopyAndUploadContentUrisTask: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
12-27 16:47:35.133  2458  2519 E CopyAndUploadContentUrisTask: 	at android.os.Parcel.createException(Parcel.java:2409)
12-27 16:47:35.133  2458  2519 E CopyAndUploadContentUrisTask: 	at android.os.Parcel.readException(Parcel.java:2392)
12-27 16:47:35.133  2458  2519 E CopyAndUploadContentUrisTask: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
12-27 16:47:35.133  2458  2519 E CopyAndUploadContentUrisTask: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
12-27 16:47:35.133  2458  2519 E CopyAndUploadContentUrisTask: 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
12-27 16:47:35.133  2458  2519 E CopyAndUploadContentUrisTask: 	at android.content.ContentResolver.query(ContentResolver.java:1219)
12-27 16:47:35.133  2458  2519 E CopyAndUploadContentUrisTask: 	at android.content.ContentResolver.query(ContentResolver.java:1151)
12-27 16:47:35.133  2458  2519 E CopyAndUploadContentUrisTask: 	at android.content.ContentResolver.query(ContentResolver.java:1107)
12-27 16:47:35.133  2458  2519 E CopyAndUploadContentUrisTask: 	at com.owncloud.android.ui.asynctasks.CopyAndUploadContentUrisTask.doInBackground(CopyAndUploadContentUrisTask.java:151)
12-27 16:47:35.133  2458  2519 E CopyAndUploadContentUrisTask: 	at com.owncloud.android.ui.asynctasks.CopyAndUploadContentUrisTask.doInBackground(CopyAndUploadContentUrisTask.java:51)
12-27 16:47:35.133  2458  2519 E CopyAndUploadContentUrisTask: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
12-27 16:47:35.133  2458  2519 E CopyAndUploadContentUrisTask: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-27 16:47:35.133  2458  2519 E CopyAndUploadContentUrisTask: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
12-27 16:47:35.133  2458  2519 E CopyAndUploadContentUrisTask: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-27 16:47:35.133  2458  2519 E CopyAndUploadContentUrisTask: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-27 16:47:35.133  2458  2519 E CopyAndUploadContentUrisTask: 	at java.lang.Thread.run(Thread.java:920)
12-27 16:47:35.136  2458  2458 V UploadsStorageManager: Inserting /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/tmp/nextcloudinstance/SofortUpload/Camera/2021/W2/photo_file.jpg with status=UPLOAD_IN_PROGRESS
12-27 16:47:35.138  2458  2458 D UploadsStorageManager: storeUpload returns with: content://org.nextcloud/uploads/30 for file: /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/tmp/nextcloudinstance/SofortUpload/Camera/2021/W2/PXL_20211224_191252112.jpg
12-27 16:47:35.138  2458  2458 D UploadsStorageManager: notifyObserversNow
12-27 16:47:35.142  2458  2630 D ExistenceCheckRemoteOperation: Existence check for https://nextclopud-instance/remote.php/dav/files/me//SofortUpload/Camera/2021/W2/photo_file.jpg targeting for  existence finished with HTTP status 404(FAIL)
```

### Environment data
Android version: 12

Device model: Google Pixel 6

Stock or customized system: Stock

Nextcloud app version: 3.18 0

Nextcloud server version: 23.0.0

Reverse proxy: Traefik

#### Web server error log
No server errors, uploads from Nextcloud client 3.15 from Android 9 works as intended.

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by DEvil0000** [comment]
8 Files for me so it may be some string length/name length thing.
Using HD-Kamera app on Nokia 9 with Android 10.

**Comment by AlvaroBrey** [comment]
Can't reproduce this, I just upoaded 21 files by sharing them from Google Photos, with no problem.

@agp8x can you still reproduce this issue in the latest Nextcloud version?

**Comment by agp8x** [comment]
Just tried with 3.20.1:
* 190 files: 5/6 uploaded (same data set as in OP, 2 runs). Returned to share dialog with "Medien konnten nicht heruntergeladen werden"
* 30 files: 3 uploaded

Updated to 3.20.3 via Fdroid:
* 30 files: returns to share options, without error message, 3 uploads
* 190 files: same as above, 8 uploads
* 20 files: 5 uploads
* 16 files: 6 uploads

**Comment by Hoffmann77** [comment]
I experience the same issue on my Pixel 6. Around 6 Images get uploaded in my case.
Probably related to #2592 and #8328.

**Comment by joshtrichards** [comment]
Let's centralize tracking for this in #10937.
I encourage those following here to subscribe and/or upvote :+1: that issue.
