### ISSUE TITLE
login to nextcloud v23 fails with android 11 device

### ISSUE THREAD

**Issue by sgutermann** [nextcloud/android#9628]
### Steps to reproduce
1. install nextcloud v23 on linux server
2. download newest android app
3. try to log in with user and password

### Expected behaviour
- should just login and show dashboard

### Actual behaviour
- java lang error telling me to write a reporton GitHub

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

did not try the try nextcloud server

my nextcloud server works absolutely fine with a browser (chrome or firefox)

Nextcloud app version: do not know, the one I just installed 10 minutes ago

Nextcloud server version: 23

Reverse proxy:

### Logs

************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.RuntimeException: Accessing result data after operation failed!
	at com.owncloud.android.lib.common.operations.RemoteOperationResult.getResultData(RemoteOperationResult.java:503)
	at com.owncloud.android.authentication.AuthenticatorAsyncTask.doInBackground(AuthenticatorAsyncTask.java:80)
	at com.owncloud.android.authentication.AuthenticatorAsyncTask.doInBackground(AuthenticatorAsyncTask.java:45)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: nabu
Model: 21051182G
Id: RKQ1.200826.002
Product: nabu_eea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: V12.5.8.0.RKXEUXM

**Comment by sgutermann** [comment]
Really sorry for this. The issue can be closed. Turns out that this error was produced by me and my somewhat messed up proxy header setup.

You can log in via Browser if you have messed up header or rather missing headers. However the android apps do mind th missing headersand will produce this exact error.
