### ISSUE TITLE
Android app keeps crashing on Auto Upload settings

### ISSUE THREAD

**Issue by rvhirani** [nextcloud/android#9638]
### Steps to reproduce
1. ************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.SyncedFoldersActivity}: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeLo(TimSort.java:777)
	at java.util.TimSort.mergeAt(TimSort.java:514)
	at java.util.TimSort.mergeCollapse(TimSort.java:439)
	at java.util.TimSort.sort(TimSort.java:245)
	at java.util.Arrays.sort(Arrays.java:1424)
	at com.owncloud.android.utils.SyncedFolderUtils.getFileList(SyncedFolderUtils.java:233)
	at com.owncloud.android.utils.SyncedFolderUtils.isQualifyingMediaFolder(SyncedFolderUtils.java:112)
	at com.owncloud.android.ui.activity.SyncedFoldersActivity.mergeFolderData(SyncedFoldersActivity.java:352)
	at com.owncloud.android.ui.activity.SyncedFoldersActivity.load(SyncedFoldersActivity.java:267)
	at com.owncloud.android.ui.activity.SyncedFoldersActivity.setupContent(SyncedFoldersActivity.java:226)
	at com.owncloud.android.ui.activity.SyncedFoldersActivity.onCreate(SyncedFoldersActivity.java:160)
	at android.app.Activity.performCreate(Activity.java:8051)
	at android.app.Activity.performCreate(Activity.java:8031)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
	... 12 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: raven
Model: Pixel 6 Pro
Id: SD1A.210817.036
Product: raven

************ FIRMWARE ************
SDK: 31
Release: 12
Incremental: 7805805

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by AlvaroBrey** [comment]
Developer ref:  http://github.com/nextcloud/android/blob/cb1cad7ead2b0fab156866f8053ac2458994baf3/app/src/main/java/com/owncloud/android/utils/SyncedFolderUtils.java#L234-L234

Re-visiting this due to #10564, which has the same crash, but I can't wrap my head around the cause. The referenced `Comparator` that seems to violate its contract is just a lambda call to `Long.compare`.

The only possible explanation is that `File.lastModified()` changes during the comparison for some of the files, which would potentially result in two comparisons being inconsistent.
