### ISSUE TITLE
App crash: out of memory while syncing

### ISSUE THREAD

**Issue by empratyush** [nextcloud/android#9639]
### Steps to reproduce
1.  try to sync any E2EE folder 

### Expected behaviour
- Folder should sync

### Actual behaviour
- App crashed

log:

************ CAUSE OF ERROR ************

java.lang.OutOfMemoryError: Failed to allocate a 154030544 byte allocation with 100663296 free bytes and 101MB until OOM, target footprint 262407944, growth limit 268435456
	at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:1265)
	at javax.crypto.Cipher.doFinal(Cipher.java:2055)
	at com.owncloud.android.utils.EncryptionUtils.decryptFile(EncryptionUtils.java:357)
	at com.owncloud.android.operations.DownloadFileOperation.run(DownloadFileOperation.java:197)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:187)
	at com.owncloud.android.files.services.FileDownloader.downloadFile(FileDownloader.java:476)
	at com.owncloud.android.files.services.FileDownloader.access$500(FileDownloader.java:86)
	at com.owncloud.android.files.services.FileDownloader$ServiceHandler.handleMessage(FileDownloader.java:421)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: google
Device: flame
Model: Pixel 4
Id: S2B1.211112.006
Product: flame

************ FIRMWARE ************
SDK: 32
Release: 12
Incremental: 7934767

**Comment by AlfredoCubitos** [comment]
This bug is still alive :-(
Same error on this device:
Version: 30280290
Build flavor: generic

Brand: Android
Device: espressowifi
Model: Galaxy Tab 2

Firmware
SDK: 25
Release 7.1.2
Incremental f27505cd71
