### ISSUE TITLE
Android app: Crash after enter filename for new file while template filename not loaded from server yet

### ISSUE THREAD

**Issue by mike1703** [nextcloud/android#9640]
The Android app crashes if you create a new file and already enter a filename while the box for entering a filename is still empty (new filename template not yet loaded from server). You have to be fast (or have a flaky network connection to have more time to reproduce this) to reproduce this.

### Steps to reproduce
1. Open Android Nextcloud Client
2. Create a new Text document
3. While waiting for the empty filename to be loaded from server enter your own characters quickly while the filename field is still empty.
4. Wait until the template for a new filename is loaded from server
5. Crash incoming

### Expected behaviour
- Don't panic

### Actual behaviour
- Android App produced the Stacktrace below

### Can you reproduce this problem on https://try.nextcloud.com?
- Not really a web problem

### Environment data

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus3
Model: ONEPLUS A3003
Id: PKQ1.181203.001
Product: OnePlus3

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 1911042107

************ CAUSE OF ERROR ************

java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1341)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:697)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:689)
	at android.text.Selection.setSelection(Selection.java:93)
	at android.text.Selection.setSelection(Selection.java:77)
	at android.text.Selection.setSelection(Selection.java:152)
	at android.widget.EditText.setSelection(EditText.java:136)
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment.prefillFilenameIfEmpty(ChooseTemplateDialogFragment.java:252)
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment.onTemplateChosen(ChooseTemplateDialogFragment.java:243)
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment.access$200(ChooseTemplateDialogFragment.java:81)
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment$FetchTemplateTask.onPostExecute(ChooseTemplateDialogFragment.java:421)
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment$FetchTemplateTask.onPostExecute(ChooseTemplateDialogFragment.java:373)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.access$600(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6863)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus3
Model: ONEPLUS A3003
Id: PKQ1.181203.001
Product: OnePlus3

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 1911042107

**Comment by AlvaroBrey** [comment]
Strange, this should've been (incidentally) fixed by https://github.com/nextcloud/android/pull/9286, which prevents the call to `setSelection` with a negative index...
