### ISSUE TITLE
Android App Broken on VPN (Crash log)

### ISSUE THREAD

**Issue by azukaar** [nextcloud/android#9650]
### Steps to reproduce
1. Server is setup without any warning/error in overviews (overwrite protocol, host etc... is set, so is trusted proxies). Using Traefik and Docker
2. Simply login from Android while connected to VPN
3. The loading is stuck at the end of every login mechanisms (QR Code, app password, normal email/password)
4. Eventually crashes with this :

https://pastebin.com/8dvx12Fp

I had the crash once while trying to upload as well

### Environment data
Android version: 11

Device model: Fold 3

Stock or customized system: Stock

Nextcloud app version: Latest from market

Nextcloud server version: Nextcloud Hub II (23.0.0)

VPN: Wireguard with Pi.hole, I have checked and none of the nextcloud called have been blocked though.

Reverse proxy: Traefik

There are no logs in the Nextcloud server  logs, nor in Traefik. I have attached earlier the Android logs

*Worth noting that both the **windows apps and ios app work**, so native app login is working in itself. Hopefully, the crash report is useful. The login on the Android app also works when VPN is off.*

Could the VPN somehow mess up the SSL handshake?
Could Nextcloud trip when two different devices try to connect from the same IP (both my laptop and phone uses VPN)

EDIT: realised it was because of VPN, and that upload is also (sometime?) broken.

**Comment by azukaar** [comment]
Might be related to #6449

**Comment by ezaquarii** [comment]
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.RuntimeException: Accessing result data after operation failed!
	at com.owncloud.android.lib.common.operations.RemoteOperationResult.getResultData(RemoteOperationResult.java:503)
	at com.owncloud.android.authentication.AuthenticatorAsyncTask.doInBackground(AuthenticatorAsyncTask.java:80)
	at com.owncloud.android.authentication.AuthenticatorAsyncTask.doInBackground(AuthenticatorAsyncTask.java:45)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
```

I swear that I've seen this one before...

**Comment by AlvaroBrey** [comment]
This is the same crash as #9583, #9628 and some others. It's most likely caused by messed up headers in the server requests. In this case the VPN probably does something with them.

I'll have to investigate this further, as it seems it's affecting lots of people with less-than-perfect home setups.

**Comment by azukaar** [comment]
I am using Traefik on a bare metal dedicated server with the recommanded header configuration (TLS headers + Redirection), and when I turn off the VPN (vanilla self hosted wireguard) it actually can log in, so there's nothing too exotic in my setup

**Comment by AlvaroBrey** [comment]
Can you check the QA apk in https://github.com/nextcloud/android/pull/9607 and see if it does anything different?
