### ISSUE TITLE
Trying to watch a 4k hdr video full screen.

### ISSUE THREAD

**Issue by Byter3** [nextcloud/android#9653]
Android 12
Galaxy s21 ultra
One ui 4

Trying to watch a 4k hdr video full screen.

************ CAUSE OF ERROR ************

java.lang.OutOfMemoryError: Failed to allocate a 112 byte allocation with 135560 free bytes and 132KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at java.lang.StringFactory.newStringFromChars(StringFactory.java:112)
	at java.lang.StringBuilder.toString(StringBuilder.java:413)
	at java.lang.StackTraceElement.toString(StackTraceElement.java:206)
	at java.lang.String.valueOf(String.java:2924)
	at java.lang.StringBuilder.append(StringBuilder.java:132)
	at java.lang.Throwable.printStackTrace(Throwable.java:670)
	at java.lang.Throwable.printStackTrace(Throwable.java:735)
	at android.util.Log.getStackTraceString(Log.java:491)
	at com.google.android.exoplayer2.util.Log.getThrowableString(Log.java:162)
	at com.google.android.exoplayer2.util.Log.appendThrowableString(Log.java:168)
	at com.google.android.exoplayer2.util.Log.e(Log.java:132)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:437)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: p3s
Model: SM-G998B
Id: SP1A.210812.016
Product: p3sxeea

************ FIRMWARE ************
SDK: 31
Release: 12
Incremental: G998BXXS3BULC

**Comment by AlvaroBrey** [comment]
This is a crash in `ExoPlayer` that we probably can't do much about (other than catching it and showing an error). It seems the process ran out of memory. How much memory (RAM) does your phone have?

**Comment by Byter3** [comment]
12 GB

It worked for sometime and when I tryed to sgow someone again the same video i always got this error. Maybe Memory leaking? Anywy its not a deal breaker, but I figured I submit it anyways. If nothing can be done, close it! ;) Thanks!

**Comment by AlvaroBrey** [comment]
Duplicate #9428
