### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by gcwu** [nextcloud/android#9731]
************ CAUSE OF ERROR ************

android.app.ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{87fdf67 u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1972)
	at android.app.ActivityThread.access$2800(ActivityThread.java:264)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2197)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8085)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Xiaomi
Device: star
Model: M2102K1C
Id: SKQ1.211006.001
Product: star

************ FIRMWARE ************
SDK: 31
Release: 12
Incremental: V13.0.5.1.1.DEV

**Comment by AlvaroBrey** [comment]
Hello @gcwu, that is a way too old version of the Nextcloud app. Please try to update to the latest version (3.18.1) and verify if the bug persists.
