### ISSUE TITLE
Cannot login to Android client 

### ISSUE THREAD

**Issue by 7omasz8** [nextcloud/android#9777]
### Steps to reproduce
1. Open freshly installed app
2. Log in by scanning QR code from Web client

### Expected behaviour
- App synchronizes with server

### Actual behaviour
- stacktrace 

### Environment data
Android version: 10

Device model: Huawei mate 20 lite

Nextcloud app version: 3.18.1

### Logs
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
Caused by: java.lang.RuntimeException: Accessing result data after operation failed!
	at com.owncloud.android.lib.common.operations.RemoteOperationResult.getResultData(RemoteOperationResult.java:503)
	at com.owncloud.android.authentication.AuthenticatorAsyncTask.doInBackground(AuthenticatorAsyncTask.java:80)
	at com.owncloud.android.authentication.AuthenticatorAsyncTask.doInBackground(AuthenticatorAsyncTask.java:45)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: HUAWEI
Device: HWSNE
Model: SNE-LX1
Id: HUAWEISNE-L21
Product: SNE-LX1

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.0.0.245C432

**Comment by AlvaroBrey** [comment]
@7omasz8 can you try [3.19.0 RC2](https://github.com/nextcloud/android/releases/tag/rc-3.19.0-02)? I think this bug may be fixed in this newer version.
