### ISSUE TITLE
No system activity for All Files permission

### ISSUE THREAD

**Issue by carrabelloy** [nextcloud/android#9845]
************ CAUSE OF ERROR ************

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.MANAGE_APP_ALL_FILES_ACCESS_PERMISSION dat=package:com.nextcloud.android.beta }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2258)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1914)
	at android.app.Activity.startActivityForResult(Activity.java:5326)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:588)
	at android.app.Activity.startActivityForResult(Activity.java:5284)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:574)
	at com.owncloud.android.utils.PermissionUtil.requestManageFilesPermission$lambda-1(PermissionUtil.kt:134)
	at com.owncloud.android.utils.PermissionUtil.$r8$lambda$FE9iUchxoTWOaaSGRZ8L-ymr578(Unknown Source:0)
	at com.owncloud.android.utils.PermissionUtil$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20220208
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus6T
Model: ONEPLUS A6013
Id: RKQ1.201217.002
Product: OnePlus6T

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 2111252327

### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by Xananax** [comment]
I have the same, using Android 11.

To reproduce, I simply have to open the app.

After first install, I can login, after which Nextcloud shows me the "we need more permissions" modal. If I click it, I get the error above. From there on, if I open the app, I get the error above.

I do have a "special app access" section, but nothing there about file access.

If I check the app's permissions, there's nothing about files access either; only calendar, camera, and contacts.

In the "permission manager", under "files and media", Nextcloud doesn't show, either as permitted or not permitted.

Phone specs:

Galaxy A03 Core - SM-A032F/DS
Android 11 - Kernel 4.14 199-2303091

This is a current, but very low-end phone with low-spec hardware (I bought it because it's the cheapest I could find that'd run Android; using it to run damned obligatory gov tracking apps, banking apps that dislike EOM unlocked phones, etc). I think Android is heavily customized to run smoothly despite the low-end hardware, and as a result is maybe not entirely conforming to spec.

Another option might be that there's a fringe Android version in the early 11's series that doesn't have this permission.

I'm available for any debugging you might need me to do in order to help you help me. I know my way relatively well around adb and such.

**Comment by AlvaroBrey** [comment]
Wow, I am perplexed by this. [Docs](https://developer.android.com/reference/android/provider/Settings#ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION)

>  In some cases, a matching Activity may not exist, so ensure you safeguard against this. 

With no mention on what to do in this cases, of course, thanks Google.

I will try to address this as part of #9343

**Comment by Xananax** [comment]
Nope! I don't have my Samsung at hand right now to test again, but I never found a solution, sorry.

**Comment by omarbenzekri** [comment]
Ok thanks.

**Comment by PhantomLord72** [comment]
I have faced this issue on other low-end phones: Galaxy A03 Core, OPPO A16k, Amlogic W2. I am currrently check if a solution exists

**Comment by max-kammerer** [comment]
Hi folks! Have you found any solution?
