### ISSUE TITLE
App crashed while browsing large folder

### ISSUE THREAD

**Issue by goofacz** [nextcloud/android#9860]
App crashed while browsing rather large folder with photos and clips (over 100GB). First it started lagging and finally crashed.

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
	at com.owncloud.android.services.OperationsService$OperationsServiceBinder.isSynchronizing(OperationsService.java:372)
	at com.owncloud.android.files.FileMenuFilter.anyFileSynchronizing(FileMenuFilter.java:452)
	at com.owncloud.android.files.FileMenuFilter.anyFileSynchronizing(FileMenuFilter.java:441)
	at com.owncloud.android.files.FileMenuFilter.filter(FileMenuFilter.java:181)
	at com.owncloud.android.files.FileMenuFilter.filter(FileMenuFilter.java:125)
	at com.owncloud.android.ui.preview.PreviewImageFragment.onPrepareOptionsMenu(PreviewImageFragment.java:378)
	at androidx.fragment.app.Fragment.performPrepareOptionsMenu(Fragment.java:3144)
	at androidx.fragment.app.FragmentManager.dispatchPrepareOptionsMenu(FragmentManager.java:2923)
	at androidx.fragment.app.FragmentController.dispatchPrepareOptionsMenu(FragmentController.java:414)
	at androidx.fragment.app.FragmentActivity.onPreparePanel(FragmentActivity.java:447)
	at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3149)
	at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:1937)
	at androidx.appcompat.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:2191)
	at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:273)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8582)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30190090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: p3s
Model: SM-G998B
Id: SP1A.210812.016
Product: p3sxeea

************ FIRMWARE ************
SDK: 31
Release: 12
Incremental: G998BXXU4BULF

**Comment by invario** [comment]
Related to #6233 ?
