### ISSUE TITLE
nextcloud app crashes when moving files

### ISSUE THREAD

**Issue by danikuci1** [nextcloud/android#9903]
### Steps to reproduce
1.  Select files in one folder
2.  Cut and paste them into a second folder
3.  Profit?

### Expected behaviour

Expected nextcloud to move the files. 

### Actual behaviour

************ CAUSE OF ERROR ************

java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 2074992 free bytes and 2026KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at org.apache.harmony.xml.dom.ElementImpl.<init>(ElementImpl.java:51)
	at org.apache.harmony.xml.dom.DocumentImpl.createElementNS(DocumentImpl.java:347)
	at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:272)
	at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:296)
	at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:296)
	at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:296)
	at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:296)
	at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:128)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:107)
	at org.apache.jackrabbit.webdav.xml.DomUtil.parseDocument(DomUtil.java:104)
	at org.apache.jackrabbit.webdav.client.methods.DavMethodBase.getResponseBodyAsDocument(DavMethodBase.java:113)
	at org.apache.jackrabbit.webdav.client.methods.DavMethodBase.getRootElement(DavMethodBase.java:137)
	at org.apache.jackrabbit.webdav.client.methods.DavMethodBase.processResponseBody(DavMethodBase.java:282)
	at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1749)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:205)
	at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.run(ReadFolderRemoteOperation.java:80)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:187)
	at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:405)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:239)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:363)
	at java.lang.Thread.run(Thread.java:920)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30190090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: google
Device: sunfish
Model: Pixel 4a
Id: SQ1A.220205.002
Product: sunfish

************ FIRMWARE ************
SDK: 31
Release: 12
Incremental: 8010174

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by danikuci1** [comment]
It was maybe 20 or 30 files in a folder of maybe 15K files total. 

Apologies as I had thought the rest of the environment info would be copied with the crash report. Will retrieve and add.

**Comment by brezelman** [comment]
Maybe same?

Tried to move 46 photo files from a folder with lots of files to an empty folder.

### Cause of error
```java
Exception in thread "Thread-375" java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 13096 free bytes and 12KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
    at java.text.DateFormat.parse(DateFormat.java:397)
    at com.owncloud.android.lib.common.network.WebdavUtils.parseResponseDate(WebdavUtils.java:54)
    at com.owncloud.android.lib.common.network.WebdavEntry.<init>(WebdavEntry.kt:172)
    at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.readData(ReadFolderRemoteOperation.java:133)
    at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.run(ReadFolderRemoteOperation.java:70)
    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:193)
    at com.owncloud.android.operations.RefreshFolderOperation.fetchAndSyncRemoteFolder(RefreshFolderOperation.java:428)
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:246)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:387)
    at java.lang.Thread.run(Thread.java:1012)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30310190`
* Build flavor: `generic`

### Device information
* Brand: `Fairphone`
* Device: `FP4`
* Model: `FP4`
* Id: `TKQ1.230127.002`
* Product: `FP4eea`

### Firmware
* SDK: `33`
* Release: `13`
* Incremental: `TP2R`

**Comment by DFINITYManu** [comment]
Actually this happens just by trying to access (open) a folder with thousands of files (13.5 GB in size).  Crash in `fetchAndSyncRemoteFolder` during memory allocations that happen within the Apache Harmony WebDAV client method `ReadFolderRemoteOperation.run()`.

The memory allocations happen deep within Jackrabbit (what appears to be a DOM parsing utility) as it attempts to deserialize the XML coming from Nextcloud into RAM.  My phone says "growth limit 268435456" implying that the XML itself, when deserialized, is taking well over a quarter gigabyte of RAM.

It's not an easy problem to solve!  Those libraries all assume that you have zettabytes of RAM because your code is running on some terabyte-RAM enterprise server executing Tomcat or something like that.  For the mobile use case, anything beyond a couple hundred files (serialized via WebDAV over the wire) is gonna hit this traditional barrier of DOM representations inflating into 3x-10x the binary size of the XML.

To optimize this, there will likely be no other way than to switch directory listings to a different algorithm, which means walking away from DOM, and Jackrabbit, and basically walking away from the Apache Commons HTTP / DAV library.  Perhaps a custom parser based on SAX is sufficient to efficiently parse the WebDAV PROPFIND response, but even then loading the parsed response into RAM might be too much, which raises the question of whether perhaps local pagination is needed.

The owncloud people hit a similar problem and explored paginated PROPFIND responses here for example: https://github.com/owncloud/core/issues/13915 .  No work has taken place.

I am optimistic.  I don't think pagination from the server is required to make this work (although it might be required to make it work _fast_).  I think the standard WebDAV response can be parsed in an efficient manner, then stored locally in some disk-based structure, that can then be paginated locally to display the folder.

**But this really does need fixing.**  As it is, there are several folders I can't access on my NC machine, and others that literally freeze the app many seconds when accessing it.  That is a terrible user experience, which you don't see in apps like Dropbox or Google Drive.

**Comment by DFINITYManu** [comment]
It occurs to me there's a low-intensity way to close this ticket that does not involve switching to a custom SAX-based parser.

Perhaps the server, when seeing a specific content type request (`Accept:` header), it could switch to sending *multiple* reasonably-sized PROPFIND responses, each one after the other, in the same HTTP response:

```xml
<?xml version="1.0" encoding="utf-8"?>
<D:multistatus xmlns:D="DAV:">
    <D:response>
        <D:href>/path/to/resource</D:href>
        <D:propstat>
            <D:prop>
                <D:getlastmodified>Mon, 27 Jul 2023 12:00:00 GMT</D:getlastmodified>
                <D:getcontentlength>12345</D:getcontentlength>
                <D:getcontenttype>text/plain</D:getcontenttype>
            </D:prop>
            <D:status>HTTP/1.1 200 OK</D:status>
        </D:propstat>
    </D:response>
</D:multistatus>
<!-- end of first batch, beginning of second batch-->
<D:multistatus xmlns:D="DAV:">
    <D:response>
        <D:href>/path/to/resource</D:href>
        <D:propstat>
            <D:prop>
                <D:getlastmodified>Mon, 27 Jul 2023 12:00:00 GMT</D:getlastmodified>
                <D:getcontentlength>12345</D:getcontentlength>
                <D:getcontenttype>text/plain</D:getcontenttype>
            </D:prop>
            <D:status>HTTP/1.1 200 OK</D:status>
        </D:propstat>
    </D:response>
</D:multistatus>
[...]
```

If each batch in the response is tuned so it's roughly around 10 MB in size, then the client can split and deserialize each subdocument using the exact same Java library being used today (although lower-level methods will be needed than just the current happy path).  Then the client can merge each response into whatever the `fetchAndSync*` routines already need (I'm almost certain it's merging some local data with the remote incoming data), saving memory allocations while keeping the changes minimal.

The important thing is that the incoming stream must be sliced at a closing </D:Multistatus> that is semantically paired with a following <D:Multistatus>, and that this custom format (as specified in some Nextcloud standard) promises to always be like this, for clients to use properly.

This logic would trigger only (1) if the client sends the right Accept request header (2) when the server detects that header and sends the correct Content-Type response header.  This would preserve backwards compatibility since the same algorithm and code can process a single subdocument or more than one in a response.

**Comment by flaviut** [comment]
I've briefly looked into this,

1. the `ReadFolderRemoteOperation.java` entry that's the common thread in all these issues is gone as of Jackrabbit 2.15.0, from *2016*. I'm not active in this project, and this feels like the kind of painful tech debt that everyone already knows about but doesn't want to touch, but this library *really needs to be upgraded*.
2. newer versions of this library have a different API where it would be possible to use a streaming XML deserializer, and then with careful trimming of `android-library/library/src/main/java/com/owncloud/android/lib/resources/files/model/RemoteFile.kt`'s memory usage, it would be possible to load 100000s of files without a significant architectural change.
   ```
   propfind = new HttpPropfind(
           client.getFilesDavUri(remotePath),
           WebdavUtils.getAllPropSet(),   // or a trimmed set — see note below
           DavConstants.DEPTH_1);
   
   response = client.execute(propfind);   // HttpClient 4.x execute — does NOT parse the body
   int status = response.getStatusLine().getStatusCode();
   boolean isSuccess = (status == HttpStatus.SC_MULTI_STATUS || status == HttpStatus.SC_OK);
   
   if (!isSuccess) {
       return new RemoteOperationResult<>(false, response);
   }
   
   HttpEntity entity = response.getEntity();
   if (entity == null) {
       return new RemoteOperationResult<>(false, response);
   }
   
   ArrayList<RemoteFile> files;
   try (InputStream in = entity.getContent()) {
       files = MultiStatusStreamParser.parse(in, client.getFilesDavUri().getEncodedPath());
   }
   ```
