### ISSUE TITLE
Crash on disk space full

### ISSUE THREAD

**Issue by tennox** [nextcloud/android#9961]
### Steps to reproduce
1. Have full disk space
2. Use your phone
3. Nextcloud crashes

### Expected behaviour
- app pausing / stopping work / warning but not crashing

### Actual behaviour
- I wasn't even using nextcloud app, but the app opened with this crash log.
- also crashes when opening app

### Environment data
see below

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.io.IOException: write failed: ENOSPC (No space left on device)
	at libcore.io.IoBridge.write(IoBridge.java:540)
	at java.io.FileOutputStream.write(FileOutputStream.java:398)
	at java.io.FileOutputStream.write(FileOutputStream.java:376)
	at com.nextcloud.client.logger.FileLogHandler.write(FileLogHandler.kt:77)
	at com.nextcloud.client.logger.LoggerImpl.eventLoop(LoggerImpl.kt:132)
	at com.nextcloud.client.logger.LoggerImpl.access$eventLoop(LoggerImpl.kt:32)
	at com.nextcloud.client.logger.LoggerImpl$start$1.invoke(LoggerImpl.kt:57)
	at com.nextcloud.client.logger.LoggerImpl$start$1.invoke(LoggerImpl.kt:57)
	at com.nextcloud.client.logger.ThreadLoop.loop(ThreadLoop.kt:70)
	at com.nextcloud.client.logger.ThreadLoop.$r8$lambda$hYfuazcxVm6CsqDRlq1Sko8-5IA(Unknown Source:0)
	at com.nextcloud.client.logger.ThreadLoop$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:923)
Caused by: android.system.ErrnoException: write failed: ENOSPC (No space left on device)
	at libcore.io.Linux.writeBytes(Native Method)
	at libcore.io.Linux.write(Linux.java:293)
	at libcore.io.ForwardingOs.write(ForwardingOs.java:240)
	at libcore.io.BlockGuardOs.write(BlockGuardOs.java:418)
	at libcore.io.ForwardingOs.write(ForwardingOs.java:240)
	at libcore.io.IoBridge.write(IoBridge.java:535)
	... 11 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30190152
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus6T
Model: ONEPLUS A6013
Id: RKQ1.201217.002
Product: OnePlus6T

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 2111252327
```

**Comment by ezaquarii** [comment]
Although I understand where the expected behaviour sentiment comes from, I think it's not realistic.

Exhausting global resource - RAM, disk space, file descriptors, etc - will cause random, unpredictable, undefined runtime behaviour. Trying to fix it in a Whack-a-Mole style is a lost cause. Something else, somewhere else will crash as well. It's a lost cause for no UX gain.

I added a "fix" just to prove the point that it's not hard, but I still advise against "fixing" it. 

@AlvaroBrey FYI

**Comment by AlvaroBrey** [comment]
Yeah, I agree with @ezaquarii. No point in handling this; if it's not Nextcloud, a bunch of other apps will also crash if your disk space is full. Systems are not designed to work when resources are completely used up.

**Comment by tennox** [comment]
Fair enough & agreed 👍
