### ISSUE TITLE
error setting auto upload

### ISSUE THREAD

**Issue by HenryMiller1** [nextcloud/android#9962]
### Steps to reproduce
1. New phone, login,
2. Grant folder permissions (I might have done this wrong, trying to accept defaults so i hit back not seeing any other option)
3. Settings 
4. Auto upload
5. See following error message 

### Expected behaviour
- able to add folders to auto upload 

### Actual behaviour
- see crash backtrace 

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Can't create handler inside thread Thread[DefaultDispatcher-worker-1,5,main] that has not called Looper.prepare()
	at android.os.Handler.<init>(Handler.java:227)
	at android.os.Handler.<init>(Handler.java:129)
	at android.app.Dialog.<init>(Dialog.java:173)
	at android.app.Dialog.<init>(Dialog.java:278)
	at androidx.appcompat.app.AppCompatDialog.<init>(AppCompatDialog.java:57)
	at androidx.appcompat.app.AlertDialog.<init>(AlertDialog.java:98)
	at androidx.appcompat.app.AlertDialog$Builder.create(AlertDialog.java:983)
	at com.owncloud.android.utils.PermissionUtil.requestManageFilesPermission(PermissionUtil.kt:137)
	at com.owncloud.android.utils.PermissionUtil.requestExternalStoragePermission(PermissionUtil.kt:109)
	at com.owncloud.android.datamodel.MediaProvider.checkPermissions(MediaProvider.java:190)
	at com.owncloud.android.datamodel.MediaProvider.getImageFolders(MediaProvider.java:77)
	at com.owncloud.android.ui.activity.SyncedFoldersActivity$load$1.invokeSuspend(SyncedFoldersActivity.kt:282)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30190190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: r0q
Model: SM-S901U
Id: SP1A.210812.016
Product: r0qsqw

************ FIRMWARE ************
SDK: 31
Release: 12
Incremental: S901USQU1AVA7

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server versi

21.0.4

**Comment by AlvaroBrey** [comment]
Should be fixed by #9873 when merged

**Comment by BugRMSys** [comment]
Actually, I run into the same problem of this. But does not submit it earlier. thank you all guys

**Comment by BugRMSys** [comment]
> Actually, I run into the same problem of this. But does not submit it earlier. thank you all guys

I find the problem in review created in 2022-01-24: "Auto upload does not work. It's first function vi wanted to enroll..."
