### ISSUE TITLE
RuntimeException when sharing PDF to Nextcloud app

### ISSUE THREAD

**Issue by jaller94** [nextcloud/android#9990]
### Steps to reproduce
0. I'm not logged into Nextcloud Android.
1. Tried to share a PDF from Microsoft Lens with the Nextcloud app.

### Expected behaviour
- The app opens and asks to sign in or shows me my folders to decide where to upload the PDF.

### Actual behaviour
- A crash message appears.
```
************ CAUSE OF ERROR ************

java.lang.RuntimeException
	at com.owncloud.android.ui.activities.ActivitiesActivity$$ExternalSyntheticLambda0.get(Unknown Source:2)
	at com.nextcloud.java.util.Optional.orElseThrow(Optional.java:309)
	at com.owncloud.android.ui.activity.ReceiveExternalFilesActivity.onSaveInstanceState(ReceiveExternalFilesActivity.java:267)
	at android.app.Activity.performSaveInstanceState(Activity.java:2037)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1621)
	at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:5422)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4748)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4712)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4787)
	at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:41)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7697)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30190190
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus5
Model: ONEPLUS A5000
Id: QKQ1.191014.012
Product: OnePlus5

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 2010292059
.
```

### Can you reproduce this problem on https://try.nextcloud.com?
No, the issue goes away once I'm signed into any instance.

### Environment data
Android version: 10

Device model: OnePlus 5

Stock or customized system: stock

Nextcloud app version: 3.19.1

Nextcloud server version: n/a

Reverse proxy: n/a

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by jaller94** [comment]
Duplicate of #9971.
